### ISSUE TITLE
Unable to stage individual hunk

### ISSUE THREAD

**Issue by YorkZ** [magit/magit#1139]
Reproduce steps:
1. Run `magit-status'.
2. Move point to a file that has been modified in working tree.
3. Suppose that there are many unstaged hunks, pick any hunk and press "s" (`magit-stage-item').
4. The hunk is not staged, the following message shows up: 
   
   foo.el: patch does not apply ... [See buffer _magit-process_ for details]
5. Hit "$" to bring up the "magit-process" buffer, the following line shows up:
   
   1 git --no-pager apply --cached -

**Comment by angrybacon** [comment]
Is this fixed? I'm still experiencing the issue when staging a region of a diff under Windows. I can provide versions for Emacs, Git and Magit when I get home if necessary.

**Comment by npostavs** [comment]
@angrybacon Please open a new issue with all the details (versions, precise instructions to reproduce, etc).
