### ISSUE TITLE
discard multiple items

### ISSUE THREAD

**Issue by bling** [magit/magit#1167]
the status window lets you discard items one by one using `magit-discard-item`.  often times i want to discard more than one item, and something like marking items (similar to `package` or `dired`) and executing an action on all of them would be very useful.  this concept could be applied to (un)staging as well, which currently is all-or-one.

thanks.

**Comment by aguynamedben** [comment]
Was just trying to do this and found 2 ways...

From magit-status, `M-1` to collapse the file listing to "Unstaged changes (13)" then hit `k` on that. It will confirm that you want to discard changes from 13 files.

or...

From magit-status, `M-2` to show the files changed, then `Tab-Spc`, select the files you want to discard changes from, then hit `k` and the same confirmation will pop up.

Not sure if that's what was added in #1459 but it seems to work on the latest magit.
