### ISSUE TITLE
Integrate git branch --edit-description

### ISSUE THREAD

**Issue by Niluge-KiWi** [magit/magit#1269]
Since git 1.7.9 we can store in the config file a description for any given branch, it's only local information and cannot be pushed or pulled, but it's used at least in the merge commit message, useful for feature branches, when we have many of them, and when a branch name is not enough.

See also http://stackoverflow.com/a/8858853.

It would also be great to be able to read this branch description somewhere in the branch manager, or for the current branch.

**Comment by theldoria** [comment]
What happened to that feature?

I would love to see it integrated.

**Comment by tarsius** [comment]
> What happened to that feature?

It got merged into master.

> I would love to see it integrated.

If the current branch has a description then it is shown at the top of the buffer shown by `y`. To change it press `b d`.

**Comment by theldoria** [comment]
Wow, great, thanks :-)

**Comment by rkachach** [comment]
I can't find the command `magit-branch-edit-description`. I'm using the latest version from MELPA.

**Comment by tarsius** [comment]
You can invoke it by pressing `b d`. It is now named `magit-branch.<branch>.description` because reasons.

**Comment by rkachach** [comment]
that works, thanks for the quick response.
