### ISSUE TITLE
Args out of range

### ISSUE THREAD

**Issue by nomicode** [magit/magit#1274]
I installed magit today. I've not used it yet, not configured it.

I have a Makefile in Git directory that calls this:

```
emacs --batch -l config.el -f org-publish-all
```

For some reason, this fails with:

```
Args out of range: #("Git@" 0 4 (help-echo "Locally added file under the Git version control system")), 0, 7
```

Again, I'm not using magit for anything. It's not mentioned in config.el. All I've done is install with with MELPA.

Strangely enough, when I run that command from the CLI, it works fine!

Output of `which emacsclient`:

```
/usr/local/bin/emacsclient
```

This looks legit to me.

**Comment by flajann2** [comment]
Adding:

(setq vc-handled-backends nil)

To .emacs fixed this long-annoying problem for me. Thanks.
