### ISSUE TITLE
`git diff --cached` with Magit?

### ISSUE THREAD

**Issue by kuanyui** [magit/magit#1307]
I use [`git diff --cached`](http://stackoverflow.com/questions/1587846/how-do-i-show-the-changes-which-have-been-staged) very often, which to show the changes which have been staged.
Does Magit have this function?

**Comment by goromlagche** [comment]
is it possible to `magit-diff-staged` against a branch?
e.g. `git diff --cached master`

**Comment by tarsius** [comment]
`d C-u s`, see `d ? s` for more information.
