### ISSUE TITLE
Magit on windows no longer works with Cygwin Git

### ISSUE THREAD

**Issue by rneatherway** [magit/magit#1318]
I've used it quite successfully in this configuration for a year or so. Perhaps I was lucky and this support wasn't intended, but it would be nice if it continued to work. MSysGit doesn't understand my file permissions properly among other issues.

The problem seems to be in `magit-get-top-dir` when it shells out to `git rev-parse --show-toplevel`: https://github.com/magit/magit/blob/master/magit.el#L2058

On my machine the `default-directory` variable in that function (which doesn't seem to be used anymore?) is correct, something like `d:/cygwin/home/user/repo`, but `git rev-parse --show-toplevel` then returns `/home/user/repo` which gets expanded back out to `d:/home/user/repo`. This later triggers the `"%s isn't an existing directory"` error, so I can't use `magit-status`.

**Comment by poldy** [comment]
I can confirm the workaround from @kensanata. I modified it slightly to work with msys git and use the new nadvice.el package in Emacs 24.4 if anyone's interested:

```
(defun magit-expand-git-file-name--msys (args)
  "Handle Msys directory names such as /c/* by changing them to C:/*"
  (let ((filename (car args)))
        (when (string-match "^/\\([a-z]\\)/\\(.*\\)" filename)
          (setq filename (concat (match-string 1 filename) ":/"
                                 (match-string 2 filename))))
        (list filename)))
(advice-add 'magit-expand-git-file-name :filter-args #'magit-expand-git-file-name--msys)
```

**Comment by PeterMosmans** [comment]
Thanks @poldy and @kensanata for the workaround. Confirmed working with msys2 and the latest (master branch, 25.0.50.1) build of Emacs on Windows.

**Comment by tarsius** [comment]
See http://unix.stackexchange.com/questions/44677/how-do-i-get-rid-of-cygwins-cygdrive-prefix-in-all-paths. I think that question sums up the problem pretty well :-)

Then check whether the accepted answer fixes the issue.

**Comment by tarsius** [comment]
Also please test whether the version from the `next` branch works without using an advice or editing fstab.

**Comment by tarsius** [comment]
Reopening in favor of the recent duplicate.

**Comment by tarsius** [comment]
> Eli wrote (on g.e.help): "I believe cygwin-mount does it thing via expand-file-name, so I'm
guessing some call to expand-file-name is missing somehere in magit."

So please also try

```diff
diff --git a/magit.el b/magit.el
index b71948e..ad8a848 100644
--- a/magit.el
+++ b/magit.el
@@ -2092,10 +2092,11 @@ (defun magit-get-top-dir (&optional directory)
 
 (defun magit-expand-git-file-name (filename)
   (when (tramp-tramp-file-p default-directory)
-    (setq filename (file-relative-name filename
-                                       (with-parsed-tramp-file-name
-                                           default-directory nil
-                                         localname))))
+    (setq filename (file-relative-name
+                    (expand-file-name filename)
+                    (with-parsed-tramp-file-name
+                        (expand-file-name default-directory) nil
+                      localname))))
   (expand-file-name filename))
 
 (defun magit-file-relative-name (file)
```

**Comment by tarsius** [comment]
But please try `expand-file-name` in some place that seem relevant. I cannot perform these experiments myself because I don't use Windows and if I did I would stay as far as possible away from cygwin - it seems to be a constant source of frustration.

**Comment by tarsius** [comment]
I'm gonna assume the solution I linked to actually works. I have added a faq entry at https://github.com/magit/magit/wiki/FAQ#windows-there-is-no-git-repository-in-pathtolocalrepo. Please try it and then report back here.

**Comment by PeterMosmans** [comment]
@tarsius , please reopen this issue, as the cygwin trick does not work (for me, at least).

**Comment by tarsius** [comment]
I have just installed a work around based on the advices above and some assumption of my own. Does that do the trick for everyone?

**Comment by ilohmar** [comment]
Awesome!  With that change, my favored combination "NTEmacs + cygwin tools (incl git)" seems to work flawlessly again (and fast, and OOTB), without *any* personal patches (that had accumulated for the master branch).

Just wanted to thank you: I know first-hand how hard it is to troubleshoot the win/cygwin/ntemacs idiosyncrasies sitting in front of a windows machine (not my preference..).  Amazing job fixing this stuff relying on 2nd-hand comments!  Magit just keeps getting better.

**Comment by pete-lee** [comment]
It seems code was added to address this issue:

Magit on windows no longer works with Cygwin Git #1318

```
(defun magit-expand-git-file-name (filename &optional localname)
  (setq filename
        (if (file-name-absolute-p filename)
            (if localname
                filename
              (concat (file-remote-p default-directory) filename))
          (expand-file-name
           filename
           (and localname (file-remote-p default-directory 'localname)))))
  (if (and (memq system-type '(cygwin windows-nt)) ; #1318
           (string-match "^/\\(cygdrive/\\)?\\([a-z]\\)/\\(.*\\)" filename))
      (concat (match-string 2 filename) ":/"
              (match-string 3 filename))
    filename)
  )
```

I run console emacs within cygwin and the conversion from /cygdrive/ to :/ breaks magit-status.

Commenting out that if statement works for me.

If system-type is 'cygwin... then I don't think you want to run that code... I believe it should be constrained to windows-nt.  It makes sense to do if running non-cygwin emacs + cygwin git... it doesn't make sense for cygwin emacs (at least the console version) + cygwin git

**Comment by tarsius** [comment]
Makes sense. I have changed it as you suggested.

**Comment by benquike** [comment]
I have solved this problem.
1. downlow cygwin-mount.el(http://emacswiki.org/emacs/cygwin-mount.el) to somewhere
2. download setup-cygwin.el(http://www.emacswiki.org/emacs/setup-cygwin.el) to somewhere
3. in your init.el(or .emacs),add the following
```lisp
(add-to-list 'load-path "where you placed cygwin-mount.el and setup-cygwin.el")
(require 'setup-cygwin)
```

**Comment by tarsius** [comment]
Maybe someone in here could help out with #2127?

**Comment by amitahire** [comment]
Just to reiterate - Solved the issue https://github.com/magit/magit/issues/2127 with @benquike's suggested setup.

**Comment by thorrr** [comment]
I solved the issue without using cygwin-mount.el which was somewhat buggy for me.  Had to use kensanata / poldy's approach with the following additional hook for git-commit-mode:

```elisp
(defun un-cygwin-buffer-file-name ()
  (when (string-match "^\\([a-z]\\):/cygdrive/\\([a-z]\\)/\\(.*\\)" buffer-file-name)
    ;; assertion:  filename should look like "c:/cygwin/c/Users..." i.e. the drive is repeated
    (if (equal (match-string 1 buffer-file-name) (match-string 2 buffer-file-name)) (progn
      (set-visited-file-name
            (concat (match-string 1 buffer-file-name) ":/"
                    (match-string 3 buffer-file-name)) 't)))))
(add-hook 'git-commit-mode-hook 'un-cygwin-buffer-file-name)
```

**Comment by nstares0** [comment]
Hello, 

I am having the same issue as #2127. When trying to commit, I get:
```
/bin/emacsclient --socket-name=/tmp/emacs1064542/server: /bin/emacsclient: No such file or directory   
error: There was a problem with the editor '/bin/emacsclient --socketname=/tmp/emacs1064542/server'.  
Please supply the message using either -m or -F option.    
```                                            
I'm running `Magit 20171115.1141, Git 2.13.0.windows.1, Emacs 25.3.1, cygwin`  
Other magit features seem to work fine.

I tried @benquike's setup, but it did not work. I also tried some other suggestions in this thread but honestly I don't understand enough to know what I'm doing.

**Comment by PeterMosmans** [comment]
Hi @nstares0 - what's the value of the $GIT_EDITOR environment variable ? This can be checked in Emacs by evaluating `(getenv "GIT_EDITOR")`.
It sounds like it could have something to do with that...

**Comment by nstares0** [comment]
Hi @PeterMosmans, thanks for your help. `(getenv "GIT_EDITOR")` evaluates to nil.

**Comment by npostavs** [comment]
@nstares0 try wrapping in `magit-with-editor`:
```elisp
(magit-with-editor
  (getenv "GIT_EDITOR"))
```

**Comment by nstares0** [comment]
@npostavs Are you saying I should evaluate this in a buffer inside the git directory?

**Comment by npostavs** [comment]
The directory shouldn't matter. Use the `magit-with-editor` macro does.

**Comment by nstares0** [comment]
Running that didn't change anything.

**Comment by npostavs** [comment]
Hmm, it really evaluates to nil? What do you get from `M-x with-editor-debug`?

**Comment by nstares0** [comment]
When I run `M-x with-editor-debug` emacs hangs indefinitely.

**Comment by npostavs** [comment]
If you do `M-x toggle-debug-on-quit` first, can you get a backtrace by hitting `C-g` when it hangs?

**Comment by nstares0** [comment]
Here is the trace:

```
Debugger entered--Lisp error: (quit)                                                                                       
  make-network-process(:name "server-client-test" :family local :server nil :noquery t :service "/tmp/emacs1064542/server")
  server-running-p()                                                                                                       
  with-editor-debug()                                                                                                      
  funcall-interactively(with-editor-debug)                                                                                 
  call-interactively(with-editor-debug record nil)                                                                         
  command-execute(with-editor-debug record)                                                                                
  execute-extended-command(nil "with-editor-debug" "with-editor-debug")                                                    
  funcall-interactively(execute-extended-command nil "with-editor-debug" "with-editor-debug")                              
  call-interactively(execute-extended-command nil nil)                                                                     
  command-execute(execute-extended-command)                                                                                                                                                                                                                                                                                                                  
```

**Comment by npostavs** [comment]
Hmm, what version and flavour of Emacs are you running? I get `(error "Unknown address family")` when I try to run evaluate that `make-network-process` call on w32 builds of Emacs 25.3 and 26 pretest.

**Comment by nstares0** [comment]
I'm running emacs-nox 25.3.1

**Comment by npostavs** [comment]
Oh, you're using cygwin Emacs with w32 git. This is the opposite configuration from what this issue is about (w32 Emacs with cygwin git), please open a new issue. (Possibly some of the troubleshooting snippets from #2284 and #2714 could be relevant)
