### ISSUE TITLE
Magit fails to detect the git repository

### ISSUE THREAD

**Issue by kprav33n** [magit/magit#1329]
I have a local git repository, where all the git operations are working fine. I was successfully using magit on that repository until the last upgraded of magit. However, after upgrading to magit-20140407.1314, magit is not detecting the git repository anymore.

When I invoke `M-x magit-status` from the top level of the git repository, I get the a prompt in the minibuffer like `Git repository: /path/to/top-level/dir`. When I press return, it further prompts `There is no Git repository in /path/to/top-level/dir/.  Create one? (y or n)`.

The same directory used to work fine before I upgraded to latest magit. I don't remember what was the previous version that I was using. In order to further debug the problem, I did the following:

```
$ cd /path/to/top-level/dir
$ git rev-parse --git-dir
.git
```

Please let me know if I should turn on any further debugging, and provide necessary info.

GNU Emacs 24.3.1, magit-20140407.1314 (from melpa.milkbox.net), CentOS 6.3.

**Comment by ltrojan** [comment]
I'm getting the same problem... I'm running git from within a raspberry pi,

* GNU Emacs 25.1.50.1 compiled and installed from source
* magit 20160312.2307 installed from melpa
* git version 1.7.10.4 installed from raspberry repos

the command above does point to the root dir (`git --no-pager -c core.preloadindex=true rev-parse --show-toplevel`)

**Comment by johnmastro** [comment]
@ltrojan, Magit v2 requires git 1.9.4 or newer. 

If you can't install a newer git, you can install an older Magit (as mentioned [in the FAQ](http://magit.vc/manual/magit/I-cannot-install-the-pre_002drequisites-for-Magit-v2.html#I-cannot-install-the-pre_002drequisites-for-Magit-v2))

**Comment by ltrojan** [comment]
I've compiled latest git from git repo directly on the pi... took a bit of space on my sd card but works out well, thanks! :D

**Comment by asifatgrabbd** [comment]
Turns out i had upgraded xcode and had not accepted the license, just run 'sudo xcodebuild -license' if its a similar issue

**Comment by sr105** [comment]
I had the same xcode issue, even though I use homebrew versions of tools. My problem was that emacs was not seeing my homebrew directory in the places to look for executables.

**Comment by squarepegsys** [comment]
This bit me today too.... which also revealed the `exec-path` issue.

**Comment by captain-yoshi** [comment]
Got this exact problem today when doing a `magit-status` on a mounted folder.

 Turns out there was a fatal error in git :
 ```bash
 fatal: detected dubious ownership in repository at '/media/share/CoolProject'
To add an exception for this directory, call:

	git config --global --add safe.directory /media/share/CoolProjectgit config --global --add safe.directory /media/share/CoolProject
 ```
 
 Adding the exception resolves the issue. Not sure if magit should detect this usecase...

**Comment by tarsius** [comment]
> Setting the new `git-commit-cd-to-toplevel` to `t` should help with this. See its docstring for more information and maybe the issue it references.
