### ISSUE TITLE
lightweight tagging results in wrong number of arguments error

### ISSUE THREAD

**Issue by zenspider** [magit/magit#1372]
Tried `t t` in both log and status views. In both cases, I go through setting the tag name and where it should be applied (default) and get the following error:

```
call-interactively: Wrong number of arguments: #[(name rev) "ÃÄÅÆ  
D\"#" [magit-custom-options name rev apply magit-run-git "tag" append] 7 ("/Users/ryan/.emacs.d/elpa/magit-log-edit-20140303.700/magit-log-edit.elc" . 1294) (list (magit-read-tag "Tag name") (magit-read-rev "Place tag on" (or (magit-guess-branch) "HEAD")) current-prefix-arg)], 3
```

No clue what the binary data is.

**Comment by Dryvenn** [comment]
same here, but on ubuntu after fresh install from melpa

**Comment by tarsius** [comment]
Please post steps to reproduce and a backtrace.

**Comment by Dryvenn** [comment]
M-x magit-status
t t
Tag name: test
Place tag on: HEAD

call-interactively: Wrong number of arguments: #[(name rev) "ÃÄÅÆ^H
D\"#\207" [magit-custom-options name rev apply magit-run-git "tag" append] 7 ("/home/dryvenn/.emacs.d/elpa/magit-log-edit-20140522.1137/magit-log-edit.elc" . 1258) (list (magit-read-tag "Tag name") (magit-read-re\
v "Place tag on" (or (magit-guess-branch) "HEAD")) current-prefix-arg)], 3

Hope I'm doing it the right way... :-s
I should mention that helm, auto-indent, projectile, auto-complete, flycheck, and yasnippet are activated.

**Comment by tarsius** [comment]
What version of Magit are you using? Could you please remove all `elc` files, restart Emacs, and the repeat these steps -- that should give a more meaningful backtrace. Thanks.

**Comment by Dryvenn** [comment]
Here it is:

call-interactively: Wrong number of arguments: (lambda (name rev) "Create a new lightweight tag with the given NAME at REV.
('git tag NAME REV')." (interactive (list (magit-read-tag "Tag name") (magit-read-rev "Place tag on" (or (magit-guess-branch) "HEAD")) current-prefix-arg)) (apply (function magit-run-git) "tag" (append magit-cust\
om-options (list name rev)))), 3

**Comment by tarsius** [comment]
The string "lightweight" does not appear anywhere in a library on the `master` branch, and the command that creates tags does *not* only takes the arguments NAME and REV as the backtrace suggests, but also an optional ANNOTATE. So while you have installed Magit from Melpa, you also have an old version laying around somewhere *earlier* on the `load-path`. That old version get's loaded instead of the up-to-date version you have installed, and apparently that version has a bug in the tagging command. To fix carefully search for all installed version, remove all of them, and then reinstall from Melpa.

**Comment by tarsius** [comment]
Ah, I just scrolled up a bit... do you also have `magit-log-edit` installed? Uninstall it, it only serves to make committing *worse*, and the only reason that it is still available, is that some people thought worse is better and wouldn't stop bothering me about it.

**Comment by tarsius** [comment]
Ah, there was indeed a bug in `magit-log-edit.el`. I fixed it, but I still recommend to you abandon that package as soon as possible.

**Comment by Dryvenn** [comment]
Okay, thanks for the help !
