### ISSUE TITLE
Cannot open load file: git-commit-mode

### ISSUE THREAD

**Issue by LukeMauldin** [magit/magit#1399]
When launching magit-status, I receive this error: "Cannot open load file: git-commit-mode"

I have installed git-commit-mode and when I try to install it again using package-install I receive this message: package-unpack-single: File exists: /home/lmauldin/.emacs.d/elpa/git-commit-mode-20140605.520/git-commit-mode-pkg.el"

I am using Emacs 24.3.1 on Xbuntu 14.04.

**Comment by FabriceSalvaire** [comment]
I encountered this issue after renaming `.config/emacs-legacy` to `.config/emacs`

**Comment by FabriceSalvaire** [comment]
Try to cleanup everything, issue is reproducible without a symlink.
