### ISSUE TITLE
Magit for mercurial

### ISSUE THREAD

**Issue by priyadarshan** [magit/magit#1417]
> I happen to work in one of these large companies, with several hundred developers. I know of quite a few other large companies like this one, that may be 'under the radar' from public statistics, but are in effect privileging 'hg' over 'git', for their own reasons.

These companies also have the money to pay for the tools their developers use. They also pay their developers for the work they do for them. I get payed very little to work on magit. So little that I don't know how much longer I can effort to do so. So I spend that time improving magit as an interface to the version control system that I use, and not by implementing things I have no use for.

> Please, we badly need 'magic for hg'!

In 2011 someone created just that by forking magit injecting some hg and naming the result monky. Ironically it is [hosted on github](https://github.com/ananthakumaran/monky). It hasn't been improved since 2012 but it might be a start.

But also try [git-remote-hg](https://github.com/felipec/git-remote-hg). With that you might not even notice that you are talking to a hg repository. If your company uses old-school mercurial branches instead of git-like "bookmarks" that might complicate things a bit though.

> Many hope that, sooner rather than later, `magit` will be integrated into Emacs source.

I don't think magit is ready for that, yet.

> Even more so, it would be fantastic if it would be abstracted from using just `git`, and at least allow `mercurial` as well

I am trying to split up magit into more composable components, many of which don't actually have anything to do with git (or even just version control). Doing this makes magit itself better and it will benefit all those users who would like to use certain magit features elsewhere, which seem to be quite a few, including myself. So while I won't personally bring the magic to mercurial, a lot of my ongoing work is going to make it much easier for someone else to do so.

But that too takes time and has high opportunity costs for me.

> Please, consider making 'magic' `magit` work on `mercurial` as well. Many developers will be forever thankful.

If you would like to support these efforts of modularizing magit you could do so by improving my salary here: https://www.gittip.com/magit.

**Comment by ztlevi** [comment]
Do we have any support for mercurial updated since 2014?

**Comment by tarsius** [comment]
No.

**Comment by vermiculus** [comment]
You're better off looking for a solution that teaches git how to work with mercurial projects (a la git-svn), but that might be difficult.
