### ISSUE TITLE
Move Untracked files section behind Unstaged changes section 

### ISSUE THREAD

**Issue by dove-young** [magit/magit#1422]
If there are untracked files in the working directory,  the <b>Untracked files:</b> section is used to be displayed in front of <b>Untracked files:</b> section in a  magit-status buffer. 

Since untracked files are used to be low important than those on tracked, especially which were changed and not committed.  So it would be much better moving tracked and changed files in front of untracked files. 

To implement this change, simply adjust sequence in <b>magit-status-sections-hook</b> like this git diff represented.

```
 ->   git diff magit.el
 diff --git a/magit.el b/magit.el
 index cff4d27..44bcb3a 100644
 --- a/magit.el
 +++ b/magit.el
 @@ -769,12 +769,12 @@ manager but it will be used in more places in the future."
      magit-insert-bisect-rest
      magit-insert-bisect-log
      magit-insert-stashes
 -    magit-insert-untracked-files
      magit-insert-pending-commits
      magit-insert-unstaged-changes
      magit-insert-staged-changes
      magit-insert-unpulled-commits
 -    magit-insert-unpushed-commits)
 +    magit-insert-unpushed-commits
 +    magit-insert-untracked-files)
    "Hook run to insert sections into the status buffer.

  This option allows reordering the sections and adding sections
```

**Comment by tobimensch** [comment]
I just tried your three liner and it didn't have any effect.

Is it still supposed to work?

I just want to move the "Untraced files" section to the bottom.

**Comment by tarsius** [comment]
The function `magit-insert-unpushed-commits` no longer exists. So putting something "after it" does not work and the function you want to move there is left where it is. I recommend you instead use `M-x customize-option RET magit-status-sections-hook RET`.
