### ISSUE TITLE
Make log graphs prettier and faster

### ISSUE THREAD

**Issue by tarsius** [magit/magit#1425]
Log graphs have two issues which ideally are addressed together:

1. Even when limiting the log range Git insists on looking at every commit first, including the commits that are not in the range. This can make Magit's log very slow for large histories.
2. The graphs `log --graph` gives us are not exactly pretty and clear.

The first issue could, and maybe should (because the second might take some time) be addressed separately. Junio [has suggested](http://www.spinics.net/lists/git/msg232235.html) a simple way in which this could potentially be done. Someone (maybe you) just has to follow up on that.

However even if that is fixed in Git we might still want to draw our own prettier graph. Or if it turn our that there is no easy fix for Git then we have to do so not only to make it prettier but also to make it fast.

To do so we should replace `--graph` with `--parents` and then use the list of parents output for each commit to construct our own graph.

* [tig](https://github.com/jonas/tig) draws very nice graphs. I particularly like how it never needs more than one line per commit. I have looked at the C code and it should be fairly easy to port that. But it is a lot of code. Also the colorization of certain parts of the graph are not correct. I am currently holding out for that to be addressed.
* In #495 another algorithm was suggested. Unfortunately that needs more than one line per commit and the code is unreadable (and the author currently does not have the time to fix it).
* We could also use Emacs' svg image support to draw graphs comparable to those of e.g. gitk.

Also in #495 another approach to making the graphs prettier was suggested (and this is actually what that issue originally was about): just replace the ascii characters with prettier unicode characters. Of course that does nothing for speed and your mileage might vary depending on what font you use, but at least I have already implemented that, see option `magit-log-format-graph-function`.

**Comment by andschwa** [comment]
@tarsius
>  the problem is that Git first goes outside and has a smoke.

One of the best things I've read in a while! Haha.

**Comment by tarsius** [comment]
Maybe dim merge commits as suggested in #1909.

**Comment by MikeSanMichel2** [comment]
emacs 25's alleged support for [dynamic library loading](http://endlessparentheses.com/big-things-to-expect-from-emacs-25.html) and [libgit2](https://libgit2.github.com/)?

**Comment by tarsius** [comment]
The various hacks seem to work, performance wise. Making the graph prettier boils down to reimplementing that feature from scratch (though possibly taking inspiration from elsewhere). Might happen eventually, but don't hold your breath.

**Comment by Niluge-KiWi** [comment]
What about the slow, complex queries that would benefit from an async log ?

Le dim. 10 janv. 2016 14:08, Jonas Bernoulli <notifications@github.com> a
écrit :

**Comment by tarsius** [comment]
Yes. Still planning on doing that.

That's what I posted on the other issues that I closed today:

---

Tabula rasa

Closing, to avoid pressuring myself into implementing this before the prerequisites are fully ready, just because there's an open issue for this but not the prerequisites.

Also see the 3.1.0 milestone (click on "more").
