### ISSUE TITLE
next: option to disable highlighting overlay

### ISSUE THREAD

**Issue by holomorph** [magit/magit#1457]
It seems a lot of effort went into making control of magit's overlay highlighting possible in #994.  This doesn't appear to be present in next.  In fact, there are two different faces for each diff element.  I'll admit it looks quite nice, and I was pleasantly surprised by the appearance when I switched to next, but I miss the ability to turn off all the highlighting.  I find it distracting.

At first sight, it looks like a design decision was made, so if this is too much of a request to make (I'm surprised I couldn't find an existing issue!), there could be some pretty inconsequential changes made with the faces in next, and I'd be glad to write a patch:
- most of the `foo` and `foo-highlight` pairs' foregrounds are the same (or extremely close), so `foo-highlight` should just inherit from `foo` and set a different background
- context should inherit from shadow

**Comment by grothesque** [comment]
> It's now possible to disable highlighting of the current section by removing magit-section-highlight from magit-section-highlight-hook. (...)

> You might also want to consider changing magit-diff-refine-hunk from t to all, (...)

This is great, just what I was looking for.  Thanks for making this so easily configurable.

I find that with the default configuration of magit (with a bright background) the changed parts of refined hunks are hardly distinguishable from the unchanged parts of a line.

Also, the default choice in magit to use green/red foreground text on greenish/reddish background has not enough contrast for my weary eyes.

I applied the above changes, and customized the faces `magit-diff-added` to inherit directly from `diff-added`, etc.  The result looks like ediff and is IMHO more readable.
