### ISSUE TITLE
How to checkout a commit from the magit-commit buffer?

### ISSUE THREAD

**Issue by smaret** [magit/magit#1465]
Is there a way to checkout a commit from the`*magit-commit*` buffer? I would like `magit` ro run `git checkout xxxx` in the background.

**Comment by AtomicNess123** [comment]
Hi, once I do b b (magit-checkout) and type my specific commit. How do I go back to the previous state? I mean, I was only "visiting" (checkingout) that commit. Thanks!

**Comment by tarsius** [comment]
In the future please don't ask for help on an old (somewhat related) issue. Instead [open a new "discussion"](https://github.com/magit/magit/discussions). That is what we use for support now.

<sub>This is a [canned response](https://help.github.com/en/github/writing-on-github/working-with-saved-replies); it may not apply 100% in this case.</sub>

----

I don't fully understand your question. Just check out gain the branch that was checked out before, e.g. `b b the-branch RET`. Seems obvious, so maybe that's not actually what you are asking. If you don't remember what branch or commit was checked out before, then you can use `l H` to show you the reflog. Entries like this should help you figure out what you just did:

```
e80eff30d 0  checkout         moving from master to e80eff30d
```
