### ISSUE TITLE
Push deleted tags (delete on remote)

### ISSUE THREAD

**Issue by kpurdon** [magit/magit#1468]
Please excuse me if this is possible and i'm missing something. What i'm trying to do is:

```
git tag -d tag-to-delete  
git push origin :refs/tags/tag-to-delete
```

Deleting the local tag works fine, it's the second command which I cannot find a solution for. I believe doing a Push-Tags should do the push origin to delete the remote tag (correct?)

My questions are:
1. How can I push a deleted local tag to also delete on the remote using Magit.
2. If I cannot currently do (1) how should this be implemented in Magit.

Thanks!

**Comment by hraban** [comment]
Thanks very useful feature
