### ISSUE TITLE
On Windows magit is "unable to auto-detect email address"

### ISSUE THREAD

**Issue by mrmagooey** [magit/magit#1497]
With a fresh install of MSysGit, emacs and magit when I try to commit I am getting:

```
128 c:/Program Files (x86)/Git/bin/git.exe --no-pager -c core.preloadindex=true commit --

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got '<my username> @<my computer name>.(none)')
```

These config options are set (and I set them again to be sure, with --global), and I can otherwise normally commit files using git directly from the command line.

**Comment by tensai-cirno** [comment]
The proper way is to set HOME environment variable to `%APPDATA%`, but that [doesn't play very nice with msysgit](https://groups.google.com/d/msg/msysgit/p306hHBuzZ0/LryrROwvgcwJ).

Msysgit stores configuration in `%USERPROFILE%`, while everyone else is using `%APPDATA%`. The easiest way is to copy .gitconfig or create sym/hardlink.
