### ISSUE TITLE
Is rebase --onto supported?

### ISSUE THREAD

**Issue by jplindstrom** [magit/magit#1519]
Is there a way to do "rebase --onto" using Magit?

(Looking at the docs and searching the code it seems not.)

**Comment by gzm0** [comment]
What is the status on this? I still can't find any documentation on this and its one of the few reasons I still need to use the shell...

**Comment by tarsius** [comment]
See #1645. It should come out this month.

**Comment by markshep** [comment]
Maybe I'm being stupid, but I can't work out where this is in magit.  There's nothing mentioning "onto" in the `*magit-rebase-popup*` buffer.  Is it accessible some other way instead?

**Comment by kyleam** [comment]
Try `magit-rebase-subset`.

**Comment by markshep** [comment]
OK, thanks - got it working now!
