### ISSUE TITLE
defaults to always signoff or sign

### ISSUE THREAD

**Issue by Falkor** [magit/magit#1524]
Hello; 

With the new version of `magit`, I couldn't find the appropriate variable/way to set or customize the default behavior of `magit` upon commit such that the `-s` switch or the `=S` arg (for instance) is enabled by default. 

I tried to have 

``` lisp
(setq magit-commit-signoff                 t)
```

[in my configuration](https://github.com/Falkor/emacs-config2/blob/devel/config/general_settings/magit.el) yet it does not work. 

Any hint would be welcome.  

Also, is there a way to ensure that `magit-status` opens with the cursor already place at the first line of the first section (often my `Unstaged changes` section) - that would save some time to stage file - I currently rely on `ace-jump-mode` to do that yet it's an additional step.

**Comment by ricky-rav** [comment]
@tarsius what's the current way of signing off by default every commit?
Thanks!

**Comment by tarsius** [comment]
The commit popup features `-s` and...

**Comment by tarsius** [comment]
The infix arguments used by a certain transient popups can be [set/saved](https://magit.vc/manual/transient/Saving-Values.html) for future invocations.  TL;DR Enter the transient as usual, enable and/or disable arguments, and finally type <kbd>C-x s</kbd> or <kbd>C-x C-s</kbd>.

<sub>This is a [canned response](https://help.github.com/en/github/writing-on-github/working-with-saved-replies); it may not apply 100% in this case.</sub>
