### ISSUE TITLE
Always override the author for a repo

### ISSUE THREAD

**Issue by UnwashedMeme** [magit/magit#1536]
Scenario:
1. Open a repo via TRAMP to `root@example.com:/etc/.git`  (etckeeper is awesome). Repo is accessed by multiple people, no where to distinguish with `git config`
2. Go to commit, I want my name as the author.

Right now the only way I can find to do this is to specify it with `=A` on every commit. This is a hassle. 

Ways to improve:
- `=A` override the author read-from-minibuffer defaults to the emacs config for user and email
- A customizable to always override (perhaps an alist of `(regex-for-reponame . author-info)`

**Comment by myrjola** [comment]
Hi @tarsius!

I solved this issue by defining my own argument insertion.
```
  (eval-after-load 'magit
    '(magit-key-mode-insert-argument
      'committing
      "=a" "Me as author"
      "--author="
      (lambda
        (prompt)
        (read-from-minibuffer prompt "Martin <my@email.com>")))
```

After evaluating this the keybinding "=a" in the commit popup should now prompt the new author, but with a pre-filled minibuffer.

Cheers!
