### ISSUE TITLE
Magit-diff very slow

### ISSUE THREAD

**Issue by AndreaCrotti** [magit/magit#1549]
Hi guys, today I noticed that magit-diff takes a very long time (many seconds).
I think it depends on the last update I did, I'm on these versions:
- magit-20141013.951
- GNU Emacs 25.0.50.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F34)) of 2014-10-07 on builder10-9.porkrind.org

I suspect the cause is this:

https://github.com/magit/magit/commit/febc832cbe12739309c41e453b36067dd4c4bc55

Reverting back that seems to make it normal again, maybe the issue is that I have hundreds of buffers open?

What can happen if I revert that commit?
Thanks

**Comment by EvgeniiFrolov** [comment]
Thanks a lot for magit! It's great!
However, what about this issue?
Diffing with previous commits is SO slow....
Is there any progress here?

**Comment by tarsius** [comment]
There are some tips at https://github.com/magit/magit/wiki/FAQ#what-can-i-do-about-poor-performance. You could also try the `next` branch, while still not fast as one would wish, it's an improvement.
