### ISSUE TITLE
have *magit-branches* indicate the "age" of a branch

### ISSUE THREAD

**Issue by offby1** [magit/magit#1550]
Here's a problem I have, that magit could help me with: I tend to accumulate lots of branches, most of which I haven't touched in ages.  When I type `b v` and see the `*magit-branches*` buffer, there's no easy way for me to tell which of those branches are "active" (i.e., have relatively young commits); I wish there were.  That way I could ignore the branches that are mostly irrelevant.

I could, of course, rename those irrelevant branches, but that's tedious.  Here are some ideas for how magit could tell me which branches are fresh:

1. color-code the branches so that new ones are red, vaguely like how vc-annotate colors lines in a file
2. include a third column that shows me a summary (including the date) of the commit to which the branch points
3. let me sort the list so that newer branches are on top

**Comment by tarsius** [comment]
I probably won't add something like this to Magit itself. But I do want to make it easier for others to extend Magit (and then distribute these extensions as separate packages). So I will add some simple examples to the manual. That manual doesn't exist yet, but here is the code for one of the "how to create a simple mode" examples it is going to contain. This assumes Magit's `next` branch.

```lisp
(defcustom PREFIX-branches-buffer-name-format "*PREFIX: %a*"
  "Name format for buffers used to list buffers by age."
  :group 'PREFIX
  :type 'string)

(defun PREFIX-show-branches ()
  "List all local branches by age."
  (interactive)
  (magit-mode-setup PREFIX-branches-buffer-name-format nil
                    #'PREFIX-branches-mode
                    #'PREFIX-branches-refresh-buffer))

(define-derived-mode PREFIX-branches-mode magit-mode "PREFIX"
  "Mode which lists local branches sorted by age.")

(defun PREFIX-branches-refresh-buffer ()
  (magit-insert-section (branchbuf)
    (magit-insert-heading "Branches by age:")
    (dolist (branch (cl-sort (PREFIX--list-branches) #'> :key #'cl-caddr))
      (cl-destructuring-bind (branch summary _) branch
        (magit-insert-section (branch branch)
          (insert (format "%-25s %s\n"
                          (propertize branch 'face 'magit-branch-local)
                          summary)))))))

(defun PREFIX--list-branches ()
  (mapcar (lambda (branch)
            (let ((format (magit-rev-format "%ct%s" branch)))
              (list branch
                    (substring format 10)
                    (string-to-number (substring format 0 10)))))
          (magit-list-local-branch-names)))
```

This happens to do the basics of what you want. Of course you might also want to show the age of the branches, not just sort them by age. But these examples are intended to demonstrate how to use the abstractions provided by Magit without the case specific complications. Provided you know elisp it shouldn't be to hard to implement that though. On the other hand notice how certain things just work (i.e. defaulting to the branch when pressing `RET` without you having to do anything.

**Comment by tarsius** [comment]
I ended implementing something anyway, on `next`. In refs buffers `L` (`magit-toggle-margin`) now shows the committer name and date similar to how the author name and date are shown in log buffers, when pressing the same key. The key binding might still change. Also see the new option `magit-refs-show-margin`.

**Comment by slowfranklin** [comment]
This can nicely be done with a git alias in .gitconfig. I know it's not magic ^w magit, but anyway, here it is:
`brd = !git for-each-ref --sort='-authordate' --format='%(authordate:iso8601)%09%(refname)' refs/heads | sed -e 's-refs/heads/--'`

brd stand for _b_ranch by _d_ate

**Comment by alexanderkjeldaas** [comment]
A fairly simple alias that works for me:
```
[alias]
  br = branch --sort=committerdate
```
