### ISSUE TITLE
preview result of merge 

### ISSUE THREAD

**Issue by andrebeat** [magit/magit#1551]
The basic idea is to be able to have a diff view like the one shown on GitHub's pull requests but without actually having to do the merge (e.g. showing conflicts unlike `git diff`). This would be really useful to review pull requests using ediff.

It is possible to generate a diff of the resulting merge like this `git merge-tree $(git merge-base $2 $1) $2 $1`.

**Comment by tarsius** [comment]
> The basic idea is to be able to have a diff view like the one shown on GitHub's pull requests but without actually having to do the merge

That's already possible just using Magit's wrapper around `git diff`.

> (e.g. showing conflicts unlike git diff).

I don't think Github supports that either. I just looked at a pr with conflicts and GIthub did not let me look at the conflicts. Could you please point me to a conflicting pr on Github and tell me what I then have to do to see the conflicts (or even just the diffs for the parts that don't conflict).

**Comment by tarsius** [comment]
Also do you really think it is necessary to preview the conflicts? Wouldn't a command that tells you whether there will be any conflicts if you attempt to merge be enough. If you really want to see the conflicts you could then attempt the merge, look at the conflicts, and then very easily back out of it with `m a` (on `next` at least, not sure about `master`).

**Comment by tarsius** [comment]
[This](http://stackoverflow.com/a/6283843/51019) approach would probably work in that case.

**Comment by tarsius** [comment]
I have implemented this on the next branch. `magit-merge-preview` is available from the merge popup.

**Comment by andrebeat** [comment]
> I don't think Github supports that either. I just looked at a pr with conflicts and GIthub did not let me look at the conflicts. Could you please point me to a conflicting pr on Github and tell me what I then have to do to see the conflicts (or even just the diffs for the parts that don't conflict).

You are correct, Github doesn't do this, although Bitbucket does (which is what I use at work and I assumed GH had the same behavior).

It's a funny coincidence but the Bitbucket team just posted a blog post explaining how their "pull request" view works and how it is different from Github's. You can read about it here: https://developer.atlassian.com/blog/2015/01/a-better-pull-request/

I still haven't tried your implementation of the `magit-merge-preview` (since I'm not running on `next` yet). But I'll make sure to test it during the weekend.

Thanks!
