### ISSUE TITLE
Create a fancier magit-copy-as-kill (and give it a better name)

### ISSUE THREAD

**Issue by jsyjr** [magit/magit#1586]
(Please ignore if the development version already addresses this -- I use the version installed by el-get.)

The description of C-w (magit-copy-item-as-kill) says "Copy sha1 of commit at point into kill ring".  This is alternately unclear or inaccurate.  In reality it copies the displayed portion of the SHA1.  If an abbreviated SHA1 is displayed then that is all you get.  My reading of that doc string lead me to expect a copy of the canonical 40-character SHA1.  My preference would be to have C-w uniformly copy the full SHA1.

Given the pending change to git there has been an active discussion the emacs-devel mailing list about how to refer to commits and the overhead of using copy-paste.  That prompts my second suggestion.  I would like to see 'W' (capital W) generalize C-w to allow copying various fragments associated with the commit at point.  These could include all of --pretty's built-in formats, a selection of the %placeholders and perhaps a means of supplying an arbitrary format string.

**Comment by tarsius** [comment]
Also support killing a commit message as suggested in #1715.

**Comment by tarsius** [comment]
Work on this has began in #2225 and will likely make it into v2.3.

I have renamed the commands. The way I intend to implement "fancier" is to save the value to a revision stack, provided it is a rev of course, and add a command to pop the latest rev and insert a representation at point or at point and eob. The user can customize how exactly the rev is formatted using an option.
