### ISSUE TITLE
log: add option for "--simplify-by-decoration"

### ISSUE THREAD

**Issue by Silex** [magit/magit#1629]
Hello

I just discovered about `git log --oneline --all --graph --decorate --simplify-by-decoration` which is very nice to understand the general layout of a repo, and I think it'd be a nice simple magit addition.

I'll maybe get around to add a popup option for it, just creating the issue for now.

**Comment by tarsius** [comment]
I like to delegate things like this... could you please ask the Git folks to make the `=full` in `--simplify-by-decoration --decorate=full` not be ignored.

**Comment by tarsius** [comment]
I've added the switch to to popup. At some point it might disappear again in favor of an action, but probably not.

This required a kludge in `magit-format-ref-labels` to deal with the non-full ref names.
