### ISSUE TITLE
Makefile doesn't find dash if it's installed via elpa

### ISSUE THREAD

**Issue by garyo** [magit/magit#1635]
If you install dash using the instructions at https://github.com/magit/magit/tree/next#installation, which say to use M-x package-install, that installs dash in ~/.emacs.d/elpa/dash-SOMENUMBERS.  The Makefile only looks in ../dash so it fails to build for me (unless I unpack magit into .emacs.d/elpa I suppose).  To fix, I did this:

```
modified   Makefile
@@ -103,6 +103,7 @@ help:
 %.elc: %.el
    @printf "Compiling %s\n" $<
    @$(BATCH) -eval "(progn\
+   (package-initialize)\
    (setq with-editor-emacsclient-executable nil)\
    (fset 'message* (symbol-function 'message))\
    (fset 'message  (lambda (f &rest a)\
```

which works fine for me.

**Comment by varmanishant** [comment]
Not sure if its ok to mention this but when you clone dash from https://github.com/magnars/dash.el.git you get the same issue. I had to rename dash.el to dash to fix this issue.

**Comment by npostavs** [comment]
@varmanishant: that has already been discussed in #1914.

**Comment by varmanishant** [comment]
@npostavs Thanks. I will read up.
