### ISSUE TITLE
Save commit buffer with bookmark

### ISSUE THREAD

**Issue by tuhdo** [magit/magit#1639]
It would be nice if I can quickly bookmark a `*magit-commit*` buffer and open it later, similar to how Dired and Bookmark work with each other. `orgit` is fantastic, but it could be improved along with adding this feature:
- We should be able to bookmark/link not only commit buffer, but log buffer as well. So, when we bookmark/link a log buffer, it saves the command that could be used to recreate that log buffer again.
- After the above is done, it is desirable if point is restored according to when the buffer is saved..

**Comment by tarsius** [comment]
Like `orgit` this should be a separate package. I have created a separate (so far empty) repository for this (except for the TODO issue https://github.com/magit/magit-bookmark/issues/1).

**Comment by yurikhan** [comment]
What happened to that repository? It says 404 now.

Anyway, I have implemented basic support for `magit-status` bookmarks. (Stores just the top-level directory and not the expand/collapse state of sections. It might make sense to save state of top-level sections (Untracked, Unstaged, Staged, Stashes, Unmerged, Unpulled) but everything below is way too volatile for a long-lived bookmark.

The code is 28 significant lines of Elisp, and I expect near-linear growth in the number of supported modes. @tarsius, are you sure you don’t want that in core?

**Comment by tarsius** [comment]
We recently added `magit-imenu.el` to this repository. If you write `magit-bookmarks.el`, then we could add that too. I am not really familiar with `imenu` or `bookmarks`, but I suspect there might be some code that could be reused.

**Comment by tarsius** [comment]
I eventually deleted the `magit-bookmarks` repository because it always was only a stub. I do not have a leftover copy of that stub.

**Comment by yurikhan** [comment]
Okay, then I’m collecting feature requests/ideas as to which kinds of Magit buffers should be supported, in addition to “`magit-status` of a specific repository”.

I’m interpreting @tuhdo’s original comment as asking for bookmarks to “a specific commit in a specific repository” and, I guess, “log of a specific repository with specific options, starting with the current HEAD, a specific set of refs or all refs”.
