### ISSUE TITLE
magit-push asks for my ssh passphrase

### ISSUE THREAD

**Issue by NicolasPetton** [magit/magit#1654]
After updating magit to the latest version from MELPA, it now asks for my ssh passphrase when trying to push to a remote.

Running `git push` from the command-line doesn't ask me for it.

**Comment by junjizhi** [comment]
Not sure if it's related, but the same issue also happens in Mac OS X if I started emacs from dashboard. Starting emacs from terminal didn't have this issue.

**Comment by npostavs** [comment]
@junjizhi Probably due to different environment variables. See https://github.com/purcell/exec-path-from-shell. https://github.com/magit/ssh-agency might also be useful.
