### ISSUE TITLE
Cannot push in magit mode 

### ISSUE THREAD

**Issue by ghost** [magit/magit#1655]
Thanks for creating this amazing plugin. Regarding the error, I have the one below when I tried to push the repositories, and the same command was executed in zsh shell without a problem:

```
git --no-pager -c core.preloadindex=true push -v origin master:refs/heads/master                                                   
Pushing to git@bitbucket.org:my-name/dotfiles.git                                                                                         

fatal: Could not read from remote repository.                                                                                          

Please make sure you have the correct access rights                                                                                    
and the repository exists.  
```

**Comment by gsimard** [comment]
I had the same issue today. The root cause was emacs (where pushing didn't work) and my shell (where pushing does work) did not have the same home folder path. Therefore, magit did not have access to the .ssh folder because it was looking for it under the wrong home folder path.

**Comment by npostavs** [comment]
> Therefore, magit did not have access to the .ssh folder because it was looking for it under the wrong home folder path.

Yes, this is a known pitfall for Windows systems: https://github.com/magit/magit/wiki/Pushing-with-Magit-from-Windows#before-starting-set-home
