### ISSUE TITLE
magit-diff-refine-hunk doesn't highlight whitespace

### ISSUE THREAD

**Issue by jschaf** [magit/magit#1689]
I'd like magit to highlight whitespace changes between lines.  Is there an option to set that?

![cursor_and__magit__tss_](https://cloud.githubusercontent.com/assets/22385/5565905/7586eb34-8f0f-11e4-881e-2fd34496b69c.png)

**Comment by tarsius** [comment]
Yep, there is such a variable: `smerge-refine-ignore-whitespace`.

I probably had that set to `nil` at some point, but then removed it, thus my confusion.

**Comment by jschaf** [comment]
Nice, that works like a charm

    (setq smerge-refine-ignore-whitespace nil)
