### ISSUE TITLE
Relation from magit-status to repos unclear in manual.

### ISSUE THREAD

**Issue by GregorZattler** [magit/magit#1695]
From the info manual: "When invoking ‘M-x magit-status’ from within a Git repository, it will switch to the status buffer of that repository."

Does this mean: "When invoking ‘M-x magit-status’ from *a buffer which is associted with a file which in turn is recognised as under git version control* ~~within a Git repository~~, it will switch to the status buffer of *its* ~~that~~ repository." ?

Sorry for the nitpicking but I'm not feeling certain enough...

**Comment by tarsius** [comment]
Yes, that's what it means, except that this description is both more *and less* correct. Emacs buffers like shells have a concept of a working directory. In the case of Emacs this is a buffer-local variable called `default-directory`. *Many* commands take its value into account when doing stuff, especially when that involves running child processes (which is very similar to what you usually do in a shell).

Maybe I'll improve this a bit when writing the new manual, but I don't think that explaining the above is a good idea. Sure it provides context, but for users who already know this (it's quite vital that you do if you want to get the most out of Emacs) it also distracts from the new information. We'll see.
