### ISSUE TITLE
magit: commit --amend with -S arg not work

### ISSUE THREAD

**Issue by douglarek** [magit/magit#1697]
It equals `git commit --amend -S`, but it does not work in magit.

````
magit-20141228.1413

GNU Emacs 24.4.1 (x86_64-apple-darwin14.0.0)
```

**Comment by tarsius** [comment]
Please define "does not work" in more detail. Also what are the keys you pressed? There are several amend variants; do all of them "not work"?

**Comment by douglarek** [comment]
@tarsius thanks for your quick reply. And I have a picture to show this:

![magit-amend]
(https://www.evernote.com/shard/s224/sh/4402794c-493a-4d4b-83ed-12f34c1b371d/0a18bf788dfbb8488df76cae5b1461ea/res/56b0a270-dd80-4019-8acb-62c17229b1d1/skitch.png)

Last, I got a result as `git commit --amend` rather than `git commit --amend -S`.

**Comment by douglarek** [comment]
@tarsius I just try to commit with -S, it can not be commited.

So I just try to use c(Commit) and a(Amend) with =S(Sign using gpg), both of them do not work.

**Comment by vanicat** [comment]
I've try to look to this. Appart from an unhelpful "it work here", I've seen that it is not obvious to see that there is a gpg signature. By default neither the magit-status nor the 'show commit' buffer display it, you have to look at a log buffer with the `-S` option to see them.

**Comment by douglarek** [comment]
@vanicat thanks for your reply.

When I finished it, I excuted `git show --show-signature` in my shell, it does not show the signature!
and the SHA 1 of HEAD not changed !!

And more, below is the  magit *message*:

```
Type a prefix key to toggle it. Run 'actions' with their prefixes. '?' for more help. [2 times]
Running git commit --amend --gpg-sign=1FF29C3A8CFB9AC6
When done with a buffer, type C-c C-c
Type C-c C-c to commit (C-c C-k to abort).
(No changes need to be saved)
```

**Comment by vanicat** [comment]
I forgot to ask you to show the content the process buffer (you can use $ in the -status buffer to go to the -process buffer. Don't forget to unhide the content of the useful section).

**Comment by douglarek** [comment]
@vanicat thanks for your reminder.

I used `$` to check magit process buffer, it asked me to type password for my gpg signature! 

But how can I enter a password ?

**Comment by douglarek** [comment]
@vanicat Ooops, I think I have found where I am lost.

I am a Chinese user, When I use `git commit -S`, it will give a Chinese prompt to ask a password, so magit will not catch it.

And I am using Fish shell, when I `set -X LANG C`, and restart Emacs, It is OK!

**Comment by douglarek** [comment]
This is my fish shell locale:

```
➜  ~ locale
LANG="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_CTYPE="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_ALL=
```

When I use magit in Emacs, git will give a Chinese password asking prompt. Magit can not catch this string-match, so maybe another good method to handle gpg signature password asking is needed !

And a temporary solution is:

```
set -x LANG en_US.UTF-8
```

**Comment by vanicat** [comment]
Another solution is to use gpg-agent for this.

**Comment by douglarek** [comment]
@vanicat thanks very much!
