### ISSUE TITLE
Branch manager incorrectly refreshed after -ff merge

### ISSUE THREAD

**Issue by Fuco1** [magit/magit#1699]
When I go into the branch manager, put cursor over the branch I want to merge from, hit `m` to go into merge dialog, then `-ff` to enable fast forward merge only and `m` to merge, the branch manager's buffer discards all branches. When I revert with `g` it reloads correctly.

Possibly related to #1162

**Comment by tarsius** [comment]
I am afraid I have bad news for you; I am not going to fix this and you'll have to wait for the release of `2.1.0` or dive into the `next` branch now. Luckily you already found a workaround. See #1645 for why I am no longer fixing bugs on `master`.

**Comment by tarsius** [comment]
By the way the reason this happens is that the current version of Magit refreshes the buffer immediately after it started an asynchronous process. That's a pretty fundamental flaw and fixing it requires risky changes all over the place. I have done so on `next` but backporting to `master` would be way to risky at this point.

**Comment by Fuco1** [comment]
Fair enough, it's not a fundamental flaw, I just wanted to provide another data point :) But it seems like you already know what's going on.
