### ISSUE TITLE
[next] Failure in `make lisp` for with-editor.el

### ISSUE THREAD

**Issue by j-mckitrick** [magit/magit#1700]
Here's the message I'm getting:

```
Compiling with-editor.el

In toplevel form:
with-editor.el:91:19:Warning: reference to free variable `dired-get-filename'
with-editor.el:92:19:Warning: reference to free variable
    `term-emulate-terminal'

In with-editor-return:
with-editor.el:280:15:Warning: kill-buffer called with 0 arguments, but
    requires 1
with-editor.el:283:25:Warning: kill-buffer called with 0 arguments, but
    requires 1

In with-editor-output-filter:
with-editor.el:445:76:Warning: reference to free variable `hop'

In end of data:
with-editor.el:637:1:Warning: the following functions are not known to be
    defined: declare-function, string-match-p, process-lines,
    server-send-string, internal-default-process-filter, user-error,
    server-running-p, server-force-delete, async-shell-command,
    read-shell-command
Wrote /Users/jmckitrick/.emacs.d/site-lisp/magit/with-editor.elc
Compiling git-commit.el

In toplevel form:
git-commit.el:74:1:Error: Symbol's value as variable is void: dired-get-filename
make: *** [git-commit.elc] Error 1
```

**Comment by tarsius** [comment]
What version of Emacs are you using?

**Comment by j-mckitrick** [comment]
Emacs for MacOSX, 24.3

**Comment by j-mckitrick** [comment]
I just updated to 24.4 on my home mac, and got this error:

```
Compiling with-editor.el

In toplevel form:
with-editor.el:81:1:Error: Cannot open load file: cl-lib
make: *** [with-editor.elc] Error 1
```

Even though cl-lib is built-in.

**Comment by tarsius** [comment]
OS X comes with ancient Emacs-22 preinstalled and with the executable properly on `$PATH`. When you install a later version in a way that let's you click on an icon to start it, then the respective executable is not automatically put on `$PATH`.

Start Emacs by clicking on it, determine the value of `invocation-directory`, and put that at the beginning of `$PATH` in your shells init file.

> Even though cl-lib is built-in.

While it is built-in a backward compatibility implementation for older Emacsen is also available from GNU Elpa. Make sure you don't have that installed.

**Comment by j-mckitrick** [comment]
Solved!  Thanks for your help.

**Comment by j-mckitrick** [comment]
Actually, a dialog button popped up after each file was compiled saying 'Application cannot be run on your computer.  Sorry!'  But the file still compiled and magit seems to work.  Is this a problem?

**Comment by tarsius** [comment]
I don't know... apparently not.

**Comment by Pitometsu** [comment]
Could you use EMACS variable instead of EMACSBIN?

**Comment by tarsius** [comment]
No, I *just* changed this from EMACS to EMACSBIN. The reason for that change is that older versions of Emacs use that variable to tell subprocesses that they are running inside Emacs (now INSIDE_EMACS is used, I believe). Without this it would not be possible to build Magit by running make in a shell buffer.

On the other hand we are dropping support for older Emacsen, so this will probably be reverted eventually.

**Comment by Pitometsu** [comment]
Thank you for the clarification.
