### ISSUE TITLE
[next] Performance issues when viewing refs

### ISSUE THREAD

**Issue by j-mckitrick** [magit/magit#1701]
I'm working on a github codebase with about 3800 lines in the remotes view, between tags and branches.  The new version of magit takes a long time to load this view, probably because of the new diff count statistic next to each branch name.  Is there a way to skip that statistic, and speed up loading just the branch and tag names themselves?

**Comment by tarsius** [comment]
What a coincidence I have literally (literally literally as one has to say by now) just looked at the variables that can be used to avoid inserting (and calculating) the commit count before reading this message, and wondered "wasn't there something I wanted to change here, except for adding doc-strings?".

So you can either remove "%4c"  from `magit-local-branch-format`, `magit-remote-branch-format`, and `magit-tags-format`, and set `magit-refs-indent-cherry-lines` to 0; or wait to see whether I am making this easier to customize over the next few days, maybe today.

**Comment by j-mckitrick** [comment]
Sounds good!  Literally! ;-)

**Comment by tarsius** [comment]
> github codebase

Errr, do you mean "git repository" or are you a Github employee?

> about 3800 ... tags and branches.

That's a bit gross.

> The new version of magit takes a long time

And with `master` this doesn't happen? Then most of these tags-and-branches must actually be tags, because otherwise you would have been able to not only fetch a snack while waiting for Magit to complete, but go out and buy the ingredients, and walk to the store and back. :-)

**Comment by j-mckitrick** [comment]
Ha!  Well, it also takes longer (than the master version of magit) to check out a given branch.  It's a large codebase (repository, lol) with some stale branches that need to be pruned.  But that's neither here nor there. :-)

**Comment by j-mckitrick** [comment]
And you are right: many more tags than branches, but still slow overall.

**Comment by j-mckitrick** [comment]
Any suggestions?

**Comment by tarsius** [comment]
On the `next` it's now possible to control this by customizing a single option `magit-refs-insert-commit-counts`. Set it to `branch` to insert the counts for branches but not tags. You can also change the value only in big repositories by adding this to `/path/to/repo/.dir-locals.el`:

```lisp
((magit-refs-mode . ((magit-refs-show-commit-count . branch))))
```

> a custom setting for whether to refresh all the 'wazzup' numbers in the margin of each branch.

That's currently not possible. Either we update them every time something happens or we don't insert them at all.
