### ISSUE TITLE
`magit-wip-save` is run on edit/merge message buffers

### ISSUE THREAD

**Issue by jguenther** [magit/magit#1702]
Using the most recent stable versions of `magit-mode` and `git-wip`, when I perform a commit emacs tries to run `magit-wip-save` on `.git/COMMIT_EDITMESSAGE`, which prints the following error in the `*magit-process*` buffer:

```
  1 git --no-pager -c core.preloadindex=true wip save WIP .git/COMMIT_EDITMSG --editor -- <topdir>/.git/COMMIT_EDITMSG
fatal: /usr/local/bin/git-wip cannot be used without a working tree.
```

It seems that `magit-wip-save` needs to ensure that `filename` is under the work tree.

**Comment by tarsius** [comment]
Since I have last edited `magit-wip.el` on the `master` branch ten months ago, I am a bit surprised nobody else has encountered this before. Is there any other user of `magit-wip.el` from `master` out there, who has some insights on this?

On the `next` branch `magit-wip.el` has been completely rewritten to not depend on the `git-wip` script.

**Comment by tarsius** [comment]
After a quick look at the old implementation my guess is that this can happen when symlinks are involved. Is that so? I.e. is `default-directory` equal to `(file-truename default-directory)` inside the repository?

**Comment by tarsius** [comment]
If symlinks are involved, please check whether removing `file-truename` from `magit-wip-save` fixes the issue.

**Comment by jguenther** [comment]
No symlinks are involved. `(file-truename default-directory)` and `default-directory` are identical in the COMMIT_EDITMESSAGE buffer.

I also tried running `emacs -Q`, then manually loading `magit` and enabling`global-magit-wip-save-mode`, but the problem still occurs.

I think the easiest fix would be to have `turn-on-magit-wip-save` check whether the buffer is visiting a file in the repo's worktree before enabling `magit-wip-save-mode` in that buffer. Currently, it checks that the file is under a git repo using `magit-get-top-dir`, but (according to its documentation) that function returns the top dir for files under the `.git` config dir as well as files in the worktree.

Perhaps an optional parameter for `magit-get-top-dir` that makes it return `nil` if unless the file is in the worktree?
