### ISSUE TITLE
Push a particular tag to git remote repo

### ISSUE THREAD

**Issue by analyticd** [magit/magit#1704]
It's nice that you can push all tags to a remote git repo using magit. However, it would be nice also to have the ability to push a particular tag to a git repo as in:
git push origin tag_name_here

There are times when this is useful as discussed here: 
http://stackoverflow.com/questions/5195859/push-a-tag-to-a-remote-repository-using-git

Thanks for this awesome library!

**Comment by tarsius** [comment]
I've added this to the `next` branch.

**Comment by analyticd** [comment]
Hi Jonas,

Thank you!
