### ISSUE TITLE
git format-patch support

### ISSUE THREAD

**Issue by rrthomas** [magit/magit#1707]
I was just looking for this and found this patch:

https://groups.google.com/forum/#!topic/magit/PtpqhBMU9S4

I haven't looked into how much work it would be to apply to master, but it would be nice to see this feature in magit (post-2.1.0, obviously!).

**Comment by tarsius** [comment]
There's already a command `magit-format-patch` on `next`, but it's a regular command, not a popup and so none of the arguments are supported as of now. I might implement an initial popup now.

**Comment by rrthomas** [comment]
Thanks, that would be great.

**Comment by tarsius** [comment]
I have implemented a basic popup in 63b55c1d5de677ef44e0375fb89af7a0f4471716. That's how far I want to go now. I have big plans for both github as well as email based contribution workflows, but that is a lot of work and requires some careful planing. And that has to wait until after the release.
