### ISSUE TITLE
git-log branch exclusion?

### ISSUE THREAD

**Issue by treyharris** [magit/magit#1708]
I frequently use the
```
git log branch1 ^branch2
```
construct on the CLI to see what commits branching from a common ancestor have, and have not, been merged, but I really can't figure out how to accomplish the same with Magit. (Which is quite rare; for the most, part Magit works _so_ well that I rarely use the shell for `git` commands anymore.)

I can enter a manual argument to the log Magit is executing via the `x..y` ranged choices, but they don't work for this purpose: `x..^y` is an invalid range.

Is there an option besides dropping into a shell?

**Comment by treyharris** [comment]
(Btw, this may not have been clear from the original request, but assuming it's not easy and I overlooked it, this is a feature request. :-)

**Comment by tarsius** [comment]
`x..^y` isn't valid, instead use `y..x`. From `gitrevisions(7)`:

> To exclude commits reachable from a commit, a prefix ^ notation is used. E.g. ^r1 r2 means commits reachable from r2 but exclude the ones reachable from r1.

> This set operation appears so often that there is a shorthand for it. When you have two commits r1 and r2, you can ask for commits that are reachable from r2 excluding those that are reachable from r1 by ^r1 r2 and it can be written as r1..r2.

On the `next` branch you can also use `x ^y` or `^y x` if you prefer those.
