### ISSUE TITLE
Easy way to close diff view from the log?

### ISSUE THREAD

**Issue by j-mckitrick** [magit/magit#1710]
When viewing the log, the up and down keys work great.  The 'n' and 'p' keys do the same thing, but show the diff for that commit.

Is there an easy way to close the commit buffer and continue navigating the log, besides C-x 0?

**Comment by tarsius** [comment]
You can close any magit buffer with `q`, which not only closes the buffer but also restores the previous window configuration (provided `magit-restore-window-configuration` is non-nil).

**Comment by j-mckitrick** [comment]
That's the first thing I tried, because 'q' always closes a buffer.  But when the focus is in the log buffer as I am navigating, with the diff in the other buffer, 'q' closes both the diff buffer *and* the log buffer, sending me back to the magit status buffer.  That's not exactly what I was hoping for.  I was hoping to close the diff buffer, which would go back to whatever was behind that buffer before, while I could continue to navigate the log entries.

**Comment by tarsius** [comment]
Well you mentioned `C-x 0` not `C-x 1` so I figured you wanted to close the current buffer.

There isn't a command to close the other Magit buffer (yet?). But once you are done walking through the log and close that buffer, the diff buffer also disappears.

**Comment by tarsius** [comment]
In log buffers `q` is now bound to the new command `magit-log-bury-buffer` which behaves like `magit-mode-bury-buffer` (previously known as `magit-log-quit-window`) except with a negative prefix argument it instead buries the revision buffer.
