### ISSUE TITLE
Debugger entered--Lisp error: (args-out-of-range

### ISSUE THREAD

**Issue by ianbarton** [magit/magit#1714]
This seems to be similar to #1274. I have a post commit hook:

    #!/bin/sh

    echo Running post-commit hook.

    # Publish org-agenda to my web site.
    emacs --batch --eval "(load-file \"/home/ian/.emacs\")" -f igb-export-agenda
    rsync -avz /home/ian/Documents/emacs/org/agenda.html ian@wilkesley.org:~/public_html/org/

If I make a commit from the shell I don't get any errors. However, when I commit from magit I get the backtrace shown below. This seems to be a vc-mode error, but I have disabled the vc back end with (setq vc-handled-backends nil). I am using magit from melpa. This used to work fine, but stopped working either after an Emacs upgrade, or a magit upgrade. Using Emacs 24.4.1 at the moment.

    0 git --no-pager -c core.preloadindex=true commit --
    Waiting for Emacs...
    Running post-commit hook.
    Loading /home/ian/.emacs...
    Loading /home/ian/.emacs.d/blacky.el (source)...
    ../../../.emacs-lisp/boxquote.el: `flet' is an obsolete macro (as of 24.3); use either `cl-flet' or `cl-letf'.
    ../../../.emacs-lisp/boxquote.el: `flet' is an obsolete macro (as of 24.3); use either `cl-flet' or `cl-letf'.
    Debugger entered--Lisp error: (args-out-of-range #("Git@" 0 4 (help-echo "Locally added file under    the Git version control system")) 0 7)
      vc-git-mode-line-string("/home/ian/Documents/emacs/org/org_files/data/bookmarks")
      apply(vc-git-mode-line-string "/home/ian/Documents/emacs/org/org_files/data/bookmarks")
      vc-call-backend(Git mode-line-string "/home/ian/Documents/emacs/org/org_files/data/bookmarks")
      vc-mode-line("/home/ian/Documents/emacs/org/org_files/data/bookmarks" Git)
      vc-find-file-hook()

**Comment by tarsius** [comment]
I have seen this error reported in a few places now:

* http://emacs.stackexchange.com/questions/7544/locally-added-file-under-the-git-version-control-system
* https://lists.gnu.org/archive/html/bug-gnu-emacs/2014-10/msg00944.html

This is not a Magit bug and I don't currently have the time to investigate it. Your best bet is to follow up on bug-gnu-emacs.

**Comment by rversteegen** [comment]
I think the following post on bug-gnu-emacs explains the problem:
> What is the value of (getenv "GIT_DIR")? If emacs was started as e.g. 
> GIT_EDITOR, it will inherit this and pass it to child git processes run by vc, 
> confusing them inordinately.
https://lists.gnu.org/archive/html/bug-gnu-emacs/2015-02/msg00305.html

Not a magit user (yet!), just had the same error message and found this; it turns out I started emacs --daemon via emacs-client via git commit; magit users may encounter the same problem.

**Comment by tarsius** [comment]
Thanks for the tip! I cannot immediately see what we can do about this issue (except maybe add it to the faq) but intend to get back to this at some point.

He, just realized that the "point" label (.) is quite appropriate for this :-)
