### ISSUE TITLE
binding to display the log for the current function

### ISSUE THREAD

**Issue by dachary** [magit/magit#1717]
Something that runs git log -L :current_function:current_file would when the point is in current_function in the buffer visiting current_file would be nice. That would quickly answer this question : "What's the history of this function modification ?".

**Comment by tarsius** [comment]
You can blame the complete file using `magit-blame`. If you are using a recent Git then that is quite fast, so no need to limit to a region.

**Comment by dachary** [comment]
Sorry for chosing a misleading title: it has nothing to do with blame really. What I often need is as described in the original description, specially when backporting when I wonder: what's the log of this function. I'm not interested in the log of the file, just this function. And blame only gives me the latest change when I really want to see the diff of all changes. Does that make sense ?

**Comment by tarsius** [comment]
Ah, yes. I also often wish that already existed but it will be quite a bit of work to implement this properly and I won't get to it anytime soon. But it's definitely something that will come eventually.

**Comment by dachary** [comment]
Cool :-) Would you mind re-opening so there is a trace for when there is time to work on it ?

**Comment by phil-s** [comment]
dachary: What are the git commands for doing this? File logs and file annotations/blame I'm familiar with, but I've never heard of what you're describing.

**Comment by dachary** [comment]
@phil-s this is git log -L as documented at http://www.git-scm.com/docs/git-log

**Comment by phil-s** [comment]
Oh, neat. Thanks!

I guess the guts of this (or at least a simplistic first pass) would be something like:

    (save-excursion
      (save-restriction
        (widen)
        (magit-run-git
         "log" "-L"
         (destructuring-bind (beginning . end)
             (bounds-of-thing-at-point 'defun)
           (format "%d,%d:%s"
                   (line-number-at-pos beginning)
                   (line-number-at-pos end)
                   buffer-file-name)))))

I'm not sure offhand how one wraps that sort of thing to actually display the process output in magit, but feel free to run with this.

If I use `magit-run-git-with-logfile` instead, it logs the expected output.

**Comment by dachary** [comment]
@tarsius it occurs to me that **maybe** the complexity of the implementation you though about was because you did not intend to use **git log -L**. Am I mistaken ?

**Comment by tarsius** [comment]
I considered both using `git log -L` and implementing something independent of that. The latter would certainly turn into a lot of work, while I am not really satisfied with the output of the former. One problem is that it does not always display what I expected, especially for changes "at the border" - I think `log -L` just isn't smart enough for that.

Another problem is that the diffs would have to be displayed inside the log buffer. We do that for "verbose" logs already but support is very incomplete. The diffs are just displayed and cannot be acted on like in diff buffers.

I won't tackle this before the release.

**Comment by michael-heerdegen** [comment]
For the record: In #2189 I proposed more or less the same thing as here, but instead of displaying the log of the current function, I wanted a log for a selected region, and wanted to be able to display the log for a wip branch as well.

**Comment by tarsius** [comment]
Work on this has began in #2226. This will probably make it into v2.4.

**Comment by andreasabel** [comment]
What is the command / key binding for this new feature in magit now?

**Comment by npostavs** [comment]
It's `=L` in the log popup.
