### ISSUE TITLE
Strange behavior on stashing new file.

### ISSUE THREAD

**Issue by shigi** [magit/magit#1722]
Operate following on next branch:
1) Create new file.
2) Stage it.
3) Stash on magit.
4) Pop stash on magit.

The result:
> Unstaged changes:
> deleted   test.txt
>
> Staged changes:
> new file   test.txt

Unstaged chnges is not necessary.

If I operate stash on command line at 3), the result seems to be correct.

**Comment by phil-s** [comment]
FYI in this scenario, `git stash` deletes the file from the working copy. So the difference here is whether or not the file is recreated on the *filesystem* (as well as in the index) when the stash is applied. It seems that command line git recreates the file, but `magit-stash-apply` does not (hence the unstaged 'deletion').

Which is odd, as it looks like `magit-stash-apply` simply calls `git stash apply --index` and, if that fails, plain `git stash apply`, and when run from the command line, both of those recreate the file.

`: stash apply --index` in magit has the same effect as `magit-stash-apply`.

`: --version` logs the same git version that I see from my shell.

Even if I add in the extra arguments which magit generates, giving me `git --no-pager --literal-pathspecs -c core.preloadindex=true stash apply --index`, running that on the command line still causes the file to be recreated.

Very mysterious. I'm sure tarsius will have some insight once he's back from his holiday.

**Comment by tarsius** [comment]
While Magit uses `git stash` to apply stashes it does not do so anymore when creating stashes, because that isn't flexible enough. New, staged files are not properly handled here.

**Comment by tarsius** [comment]
I am a bit nervous about this fix because I cannot figure out why we used to do it the way we did. Please report if you quickly if some stash and snapshot commands start to behave strangely.

**Comment by shigi** [comment]
Thank you for your fix!
I confirmed the problem is solved.
