### ISSUE TITLE
no equivalent of `git log mybranch`?

### ISSUE THREAD

**Issue by aspiers** [magit/magit#1725]
Maybe I'm missing something, but it doesn't seem possible to ask magit to show the equivalent of `git log mybranch`, i.e. an **un**ranged (short) log starting at `mybranch` and continuing indefinitely in reverse chronological order.  The use case was cherry-picking a bunch of commits from one branch to another, which prevents me from working around the lack in functionality by switching to `mybranch` and typing `ll`.

The `=b` argument doesn't help because as the `git-log` man page says:

    If pattern lacks ?, *, or [, /* at the end is implied.

So typing `=bmybranch` doesn't work (and IMHO that would be too many keystrokes even if it did).

Maybe it's worth adding `lb` which prompts for one or more commit-ishs which get passed as arguments to `git log`?

**Comment by kyleam** [comment]
This is available on the `next` branch through 'Log other' action (`lo`). Also,  have a look at `magit-cherry` for displaying commits for cherry picking.

**Comment by phil-s** [comment]
And if you're not running `next`, then it's simply `l r l mybranch RET RET`

**Comment by aspiers** [comment]
@phil-s Thanks - just realised that I used to use the `RET RET` trick but had forgotten about it because having `flx-ido` and `ido-ubiquitous` set up doesn't make it obvious how to enter the empty string at the `Log end: ` prompt.  The answer is actually `C-j`, i.e.

`l r l mybranch RET C-j`

**Comment by aspiers** [comment]
@kyleam Thanks a lot for the info!  Somehow I had missed / forgotten about `magit-cherry`.

Closing this as three good answers were supplied.
