### ISSUE TITLE
magit is very easy to stuck in *magit-log* buffer

### ISSUE THREAD

**Issue by c02y** [magit/magit#1726]
When I'm in `*magit-log*` (created by `l l` in `*magit: project*` buffer), `Enter` on an commit item, Emacs is very easy to stuck, like forever, I have to `C-g` to quit manually.

I think the big size (commit for changes of multiple files) of `*magit-commit*` will cause this problem, but is there any solution?

**Comment by tarsius** [comment]
Is this with Magit's `master` or `next` branch? If you are using `master` (e.g. from Melpa), please install `next` instead and try again. See https://github.com/magit/magit/tree/next#installation and  #1645.

**Comment by tarsius** [comment]
Judging from the buffer name, it must be `master`. I am no longer backporting to `master`, to have more time getting `next` ready for release. So I am closing this.
