### ISSUE TITLE
Magit status errors if upstream branch doesn't exist (on next)

### ISSUE THREAD

**Issue by Bruce-Connor** [magit/magit#1727]
To reproduce, do `magit-status` on a branch with an upstream. Then issue `b k` and kill the upstream. The operation will be successful but then magit throws the error `magit-insert-status-headers: Args out of range: "", 0, 7`.

Further `magit-status` (or just hitting `g`) trigger the same error.

Unsetting the upstream with `b u` resolves this.

**Comment by npostavs** [comment]
Dup of #1723.
