### ISSUE TITLE
Errors involving emacsclient when trying to commit.

### ISSUE THREAD

**Issue by kevinwaddle** [magit/magit#1728]
This was working fine for me, until a few days. I believe the last major thing I did that may have contributed was to do an M-x el-get-update-all.

Error I am getting:
```
git --no-pager -c core.preloadindex=true commit --
Waiting for Emacs...
*ERROR*: Wrong number of arguments: #[(map) "\302 \303\232\203
error: There was a problem with the editor '/usr/local/bin/emacsclient --socket-name=/tmp/emacs1000/server'.
Please supply the message using either -m or -F option.
```

Output from the emacsclient debug script:
```
system:
  system-type:                   gnu/linux
  system-configuration:          i686-pc-linux-gnu
  system-configuration-options:  --without-x
magit:        /home/kevin/.emacs.d/el-get/magit/magit.el  (90150116-1-g1176825)
git:          git  (1.7.9.5)
emacs:        /usr/local/bin/emacs  (24.4.1)
server:
  server-running-p:  t
  server-process:    #<process server>
  server-use-tcp:    nil
  server-name:       server
  server-socket-dir: /tmp/emacs1000
    server
  server-auth-dir:   ~/.emacs.d/server/
magit-emacsclient-executable:
  value:   /usr/local/bin/emacsclient  (24.4)
  default: /usr/local/bin/emacsclient  (24.4)
  funcall: /usr/local/bin/emacsclient  (24.4)
path:
  $PATH:     "/home/kevin/Envs/intranet/bin:/home/kevin/bin:/usr/local/sbin:/usr/local/bin:/home/kevin/bin:/usr/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/kevin/gocode/bin:/home/kevin/gocode/bin"
  exec-path: (/home/kevin/.emacs.d/el-get/go-def/bin /home/kevin/.emacs.d/el-get/go-autocomplete/bin /home/kevin/Envs/intranet/bin /home/kevin/bin /usr/local/sbin /usr/local/bin /home/kevin/bin /usr/local/sbin /usr/local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /home/kevin/gocode/bin /home/kevin/gocode/bin /usr/local/libexec/emacs/24.4/i686-pc-linux-gnu)
  used path:
    /usr/local/bin (t)
      emacsclient (24.4)
    /home/kevin/.emacs.d/el-get/go-def/bin (t)
    /home/kevin/.emacs.d/el-get/go-autocomplete/bin (t)
    /home/kevin/Envs/intranet/bin (t)
    /home/kevin/bin (t)
    /usr/local/sbin (t)
    /usr/sbin (t)
    /usr/bin (t)
    /sbin (t)
    /bin (t)
    /usr/games (t)
    /home/kevin/gocode/bin (t)
    /usr/local/libexec/emacs/24.4/i686-pc-linux-gnu (t)
```

**Comment by phil-s** [comment]
Perhaps try `el-get-remove` magit, and then re-install it, and then restart Emacs, just to be sure that the update process didn't leave it in an invalid state.

**Comment by kevinwaddle** [comment]
Thank you. I tried this, but the issue remains.

**Comment by npostavs** [comment]
Try doing a manual install from git to confirm it's not an el-get bug.

Try removing elc files and setting `debug-on-error` so the error message might be a little more enlightening.

**Comment by kevinwaddle** [comment]
Thank for you the further suggestions on this issue!

I deleted magit from .emacs.d/el-get/.  I cloned magit into the same directory (.emacs.d/el-get), then ran 'make lisp docs' in the new magit directory.

Started a fresh emacs. I tested. Same error.

I exited emacs.

I went into .emacs.d/el-get/magit and deleted all elc files. I started a new emacs. set debug-on-error to t. Tested again. Same error. Nothing added to *Backtrace* buffer from debug-on-error.

I then tried doing the same process with git-modes, in case that was involved/related. No improvement, same error message.

**Comment by npostavs** [comment]
Maybe it's something in your init.el? Try testing with `emacs -Q -L ~/.emacs.d/el-get/magit -L ~/.emacs.d/el-get/git-modes`

**Comment by phil-s** [comment]
Which branch of magit are you using? Are you using the master branch (or a stable release), or are you using the "next" branch? (Or something else?) Magit has some dependencies which might also need to be checked to ensure they are correctly installed.

**Comment by kevinwaddle** [comment]
phil-s: I am on master, not next branch.

npostavs: That worked! Now how to track down what in my init.el, and all other packages I am using, is now causing this?

**Comment by npostavs** [comment]
> Now how to track down what in my init.el, and all other packages I am using, is now causing this?

Your config is in https://github.com/kevinwaddle/dotfiles-castle, I guess? I had a quick look, and couldn't see anything obviously bad. Perhaps the `defadvice` in `home/.emacs.d/el-get-init-files/init-god-mode.el` could cause some bad interaction. Otherwise...

> To find out what part of your init file (~/.emacs) is causing the behavior you see, bisect your init file recursively: First comment-out half, to see which half is responsible, then 3/4, to see which quarter is responsible,... 

http://stackoverflow.com/a/23772957/319698

**Comment by kevinwaddle** [comment]
Thank you npostavs. That defadvice business is pretty fresh too. I will start there. And thanks for the tip on the bisecting technique, if the defadvice turns out not to be the culprit.
