### ISSUE TITLE
Error message on cherry pick

### ISSUE THREAD

**Issue by j-mckitrick** [magit/magit#1730]
In the `next` branch, when cherry picking (`A` command) the operation appears to succeed, but there is a large debug dump posted in the magit buffer.  I believe it was an argument type error.  I will update this ticket the next time I see it.

**Comment by tarsius** [comment]
That's likely the bug I ran into when looking into #1732. Please update and check whether it works now.

**Comment by tarsius** [comment]
Reopen if that's not the case.

**Comment by j-mckitrick** [comment]
I think that fixed the problem, but I haven't used cherry picking much
since then.  I'll let you know if I see the issue again.

thanks!


--
Jonathon McKitrick
