### ISSUE TITLE
Don't inhibit reverting when blaming, don't display blamed file in another window

### ISSUE THREAD

**Issue by kljohann** [magit/magit#1731]
I'm using the next branch and try to use `magit-blame` on a buffer that has `auto-revert-mode` turned on. As `auto-revert-handler` is `defadvice`d to temporarily turn `magit-blame-mode` on and off, and that minor mode in turn calls `magit-blame`, this leads to a cascade of calls to git every time `auto-revert-mode` checks if the buffer may be modified.

And maybe related: If I then switch to a different window (that displays a different buffer), eventually the blamed buffer will display there, too. And then the blame headings will just disappear..?

So instead of the current `defadvice`, I suggest simply inhibiting `auto-revert-mode` instead (while `magit-blame-mode` is active), as the buffer is in a read-only state anyways. That fixes this bug for me.

```emacs-lisp
(defadvice auto-revert-handler (around magit-blame activate)
  (unless magit-blame-mode
    ad-do-it))
```

**Comment by tarsius** [comment]
I can reproduce this issue and that your proposed change fixes it. Still I would like to avoid bypassing `auto-revert-mode` since the file might change on disk even when `magit-blame-mode` is enabled. If `auto-revert-mode` had no effect while `magit-blame-mode` was enabled that would be confusing to users.

But I don't understand why `auto-revert-handler` is called due to (I guess) `(magit-blame-mode 1)`. Did you investigate this?

**Comment by tarsius** [comment]
I have installed your proposed work-around but would still prefer if we found a way to keep the mode effective without `magit-blame-mode` going boink. But that's a feature request now.

**Comment by tarsius** [comment]
> If I then switch to a different window (that displays a different buffer), eventually the blamed buffer will display there, too.

I can confirm that and it also happens when it is `magit-auto-revert-mode` which triggers the blaming. Additionally the buffer can end up read-only. So far I could not figure out what's going on.

I have updated the issue title accordingly.

**Comment by tarsius** [comment]
Until now this was only fixed when using `auto-revert-mode`. When also/instead using `magit-auto-revert-mode` this persisted:

> If I then switch to a different window (that displays a different buffer), eventually the blamed buffer will display there, too.

I have now added a similar kludge for `magit-auto-revert-mode` too. And I change this to a feature request for replacing the kludge with a proper fix which does not suppress both kinds of reverts when `magit-blame-mode` is on. But that can wait until after the release.

I could not figure out why - the buffer and window seem to be correct when the buffer-to-be-blamed is re-blamed, but then the buffer is still also displayed in the window that was selected when the refresh was triggered.

**Comment by tarsius** [comment]
I have decided that simply not reverting when `magit-blame-mode` is on is actually quite reasonable.
