### ISSUE TITLE
Magit 2.1.0 cherry-pick and revert seems to be incomplete with conflict handling

### ISSUE THREAD

**Issue by villem** [magit/magit#1732]
Hi,

In magit 2.1.0 (next branch), I do not get pop-continue (abort, skip after pressing A) for cherry-pick if some merge conflict occurs. I think the problem is that there is no .git/sequencer/todo file. It seems that there is a same problem with revert action.
My magit next is currently 1feaf32dcb67986ef0ad4a676842700602f6f708.

**Comment by tarsius** [comment]
While investigating this I run into some bug which is not related to what you suggest might be the cause of this issue. After fixing that problem conflicts during cherry-pick and revert seem to be handled correctly.

Could you please try if this fixes the issue for you too. Else, what version of Git are you using? At least with `2.1.3` `.git/sequencer/todo` is created as expected by Magit.

**Comment by villem** [comment]
I updated to latest next 61c90f0c2567338e83b3b1b4f412b8f7d90563c6. I had git 2.1.0 and no todo directory. I updated to latest git 2.3.0 and still no sequencer/todo. I'm running on ubuntu 14.04. Here is my .git directory top level during cherry-pick conflict
ls  .git/
branches          COMMIT_EDITMSG~  FETCH_HEAD  hooks  logs       ORIG_HEAD
CHERRY_PICK_HEAD  config           gitk.cache  index  MERGE_MSG  packed-refs
COMMIT_EDITMSG    description      HEAD        info   objects    refs

**Comment by tarsius** [comment]
I am pretty sure that Git has been creating that file for a long time. But I haven't asserted that this really is the case, that's I have asked what version you using. You mention that you use `2.*.*`, but have you asserted that you are using that version *inside Emacs*? Due to path differences you might e.g. be using the version from `/usr` instead of the manually installed one from `/usr/local`.

Also assert that you are actually using Magit `2.1.0`. Here too you might have multiple versions installed, and if the older one comes earlier on the `load-path`, then that's what you are using.

Finally are you sure there actually is a conflict? If not, then the file is created, but then removed again before you got a change to check whether it was created. Use <kbd>$</kbd> to bring up the process log, and look for output that sais that there was a conflict. Alternatively do the cherry-pick on the command line to see whether it complains about conflicts.

**Comment by villem** [comment]
emacs locate-libarary magit point to 2.1.0 to magit.elc. I've only got the standard git. M-x shell gives me the same git as the command line.
I think I've got the conflict:
   1 git … cherry-pick --ff dd49eb
error: could not apply dd49eb1... Fix BGP's use of restart bit.
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'

I could hack magit to out put used git version if it helps.

**Comment by tarsius** [comment]
> M-x shell gives me the same git as the command line. ... I could hack magit to out put used git version if it helps.

Try `: version RET` instead.

**Comment by tarsius** [comment]
Are you using <kbd>a</kbd> or <kbd>A</kbd>, the former does not perform a "real" cherry-pick.

**Comment by villem** [comment]
Yes I'm using 'A' also I tried the same git command from command line and with git 2.3.0 and did not get the todo file. Actually I straced the git execution and in the trace there was  sequencer/ directory creation at all.
BTW: the : version RET executed but did not give me any output.

**Comment by tarsius** [comment]
Ah, it seems that is what Git does when cherry-picking a single commit (possibly also when the conflict occurs in the last commit).

There is not much I can do about it, but once you are aware of this it's easy to deal with, simply resolve the conflict and then commit `c c` the commit message buffer will start out with the correct commit message from the old commit.

Or if you want to abort discard the changes. Unfortunately that will not remove the commit message template, so the next time you commit something else, the commit message buffer will also be populated with a now bogus initial message.

> BTW: the : version RET executed but did not give me any output.

It goes into the buffer you get with <kbd>$</kbd>.

**Comment by villem** [comment]
Ok. The bash prompt seems to notice this situation and gives me
(quagga|CHERRY-PICKING)
and I can do the abort or continue. I can live this limitation, especially now that I now <pre>: cherry-pick --abort</pre>

About the version. This strange what I see in buffer is:
  0 git … version
  0 git … version

(I tried to times). But when cut and pasting it to this comment  I do get

  0 git … version
git version 2.3.0

  0 git … version
git version 2.3.0

I'm using emacs 24.3.1 ubuntu 14.10.

**Comment by tarsius** [comment]
> The bash prompt seems to notice this situation

Could you please post the code so that I can see how the come to the conclusion that a cherry-pick is in progress.

> This strange what I see in buffer is [just the headings]

These sections can be expanded using <kbd>TAB</kbd> like in other magit buffers.

**Comment by tarsius** [comment]
Never mind, they likely use `.git/CHERRY_PICK_HEAD`. Will look into using that.

**Comment by villem** [comment]
Yes, there is 
<pre>
   elif [ -f "$g/MERGE_HEAD" ]; then
                        r="|MERGING"
                elif [ -f "$g/CHERRY_PICK_HEAD" ]; then
                        r="|CHERRY-PICKING"
                elif [ -f "$g/REVERT_HEAD" ]; then
                        r="|REVERTING"
                elif [ -f "$g/BISECT_LOG" ]; then
                        r="|BISECTING"
                fi
</pre>

The details are in _/usr/lib/git-core/git-sh-prompt_

For version info TAB work well! (you learn something new each day...)

**Comment by tarsius** [comment]
Magit next is using these files too now.

**Comment by villem** [comment]
Works great! Thank you!
