### ISSUE TITLE
Ediff doesn't work with difference output from history

### ISSUE THREAD

**Issue by tgould-rms** [magit/magit#1734]
In magit I can see the history using `l l`. Then I can mark one commit with `.` and select another commit using `=` to see differences between the two commits. But in the resulting buffer if I try to use ediff with `e` I get 0 diffs in each file.

As a workaround if I manually select the commits to diff using `D`, I get the expect number of diffs in each file when I use `e`.

**Comment by tarsius** [comment]
Ediff on `master` is pretty broken,  please install `next` instead and try again. See https://github.com/magit/magit/tree/next#installation and  #1645.

They key bindings have changed (unfortunately they likely will change again). Use <kbd>M-e</kbd> the dwim variant, or <kbd>M-d</kbd> which is for comparing arbitrary commits, after marking the range of commits in the log buffer using the region.

**Comment by Silex** [comment]
@tarsius: `M-e` on next on unstaged changes shows me the "3-way merge" ediff, is this intentional? It'd be better if it shows the conventional ediff, with "before/after" buffers.

**Comment by tarsius** [comment]
Yes, it's intentional but probably both should be possible. Don't remember the reasoning for using 3-way diff, maybe it was inspired by vc?

**Comment by Silex** [comment]
In my case, I just don't see what it's useful for... maybe it makes it easier to revert some changes (with `a` and `b` like when merging), but you usually do that in the `magit-status` buffer anyway.

**Comment by tarsius** [comment]
Uh, could you add a new feature request for that too then. I probably won't get to it until I start working on the ediff part of the documentation.

**Comment by Silex** [comment]
Alright :)

**Comment by tarsius** [comment]
I am no longer backporting to `master` so this won't get fixed there.
