### ISSUE TITLE
Hang inspecting file log

### ISSUE THREAD

**Issue by pepone** [magit/magit#1737]
When try to inspect a file log from a large commit it hangs, seems the cpu is spinning and never gives control back.

The commit affects 489,111 lines, of then 5,461 are part of the file I inspecting with magit-file-log

    time git show 91adbcd > log.txt
    real    0m0.559s
    user    0m0.497s
    sys     0m0.060s
    wc -l log.txt 
    489111 log.txt

    time git show 91adbcd Parser.cpp  > log.txt
    real    0m0.011s
    user    0m0.010s
    sys     0m0.000s
    wc -l log.txt 
    5461 log.txt

I using magit  20150124.930,  I see the same issue with Emacs 24.3.1 in Ubuntu and 24.4.1 on OS X

Not sure if there is other info I could provide as emacs hangs and the only way to continue is to kill the process.

**Comment by tarsius** [comment]
Is this with Magit's `master` or `next` branch? If you are using `master` (e.g. from Melpa), please install `next` instead and try again. See https://github.com/magit/magit/tree/next#installation and  #1645.

**Comment by pepone** [comment]
Tested with next and it works, I would not complain if it was faster but it works :+1:

**Comment by tarsius** [comment]
Yeah, speed is still an issue but improvements here likely require big changes so it will have to wait until after the release of 2.1.0.
