### ISSUE TITLE
magit-status: wrong-type-argument listp 769

### ISSUE THREAD

**Issue by mkleehammer** [magit/magit#1738]
This is happening using the official GNU 24.4.1 on Windows.  I've tried installing from git and using next, 1.2.2 and 1.2.0.  I've seen the other issues that look related but the patches / recommendations did not help.

One difficulty is I was not able to run "make lisp" on the next branch since Windows doesn't have make.  I ran it on OS X with "-n" and created a batch file to run those commands on Windows.  Same error.

The weird thing is this just started happening a few weeks ago and I could uninstall magit from MELPA and re-install, restart emacs a couple of times and things would work.  I never figured out what the difference was.  Now I can't get it to work at all.

From the next branch.  This is an autoload from use-package, but I get the same error from load-library, just no stack trace even with debug-on-error.

```elisp
Debugger entered--Lisp error: (wrong-type-argument listp 769)
  magit-max-args-internal(delete-directory)
  byte-code([snip] [functionp start-file-process defalias magit-start-process
    start-process fboundp string-match-p #[(regexp string &optional start)
    [snip] [inhibit-changing-match-data regexp string start t
    string-match] 4 "Same as `string-match' except this function does not\nchange
    the match data."] with-silent-modifications magit-with-silent-modifications
    macro #[(&rest body) [snip] [body
    set-buffer-modified-p prog1 (buffer-modified-p) let ((buffer-undo-list t)
    before-change-functions after-change-functions)] 6 "Execute body without
    changing `buffer-modified-p'.\nAlso, do not record undo information."]
    magit-max-args-internal delete-directory 2 magit-delete-directory #[(directory
    &optional recursive) [snip] [directory recursive file --dolist-tail-- file-symlink-p
    file-directory-p delete-file directory-files full
    "\\([^.]\\|\\.\\([^.]\\|\\..\\)\\).*" nil magit-delete-directory
    delete-directory] 5 "Delete a directory named DIRECTORY.\nIf RECURSIVE is
    non-nil, recursively delete all of DIRECTORY's\ncontents as well.  Don't follow
    symlinks."]] 4)
  autoload-do-load((autoload "magit" nil t nil) magit-status)
  command-execute(magit-status)
```

From 1.2.something:

```elisp
Debugger entered--Lisp error: (wrong-type-argument listp 769)
  magit-max-args-internal(delete-directory)
  byte-code("[snip]" [directory recursive file --dolist-tail-- file-symlink-p file-directory-p delete-file directory-files full "\\([^.]\\|\\.\\([^.]\\|\\..\\)\\).*" nil magit-delete-directory delete-directory] 5 "Delete a directory named DIRECTORY.\nIf RECURSIVE is non-nil, recursively delete all of DIRECTORY's\ncontents as well.  Don't follow symlinks."]] 4)
  autoload-do-load((autoload "magit" nil t nil) magit-status)
  command-execute(magit-status record)
  execute-extended-command(nil "magit-status")
  smex-read-and-run(("toggle-debug-on-error" "magit-status" "byte-recompile-directory" "byte-compile-file" "grep" "kill-all-buffers" "text-mode" "sql-ms" "kill-other-buffers" "package-install" "package-list-packages" "calendar" "find-library" "sql-mode" "revert-buffer" "package-list-packages-no-fetch" "python-mode" "sql-linter" "erase-buffer" "query-replace" "imenu" "align-cols" "load-library" "customize-group" "find-file-at-point" "rgrep" "js-mode" "version" "dos-file" "insert-date" "align-regexp" "align-current" "make-buffer-neat" "shell" "dm-changelog" "set-variable" "flyspell-mode" "less-css-mode" "auto-fill-mode" "smartscan-mode" "ido-goto-symbol" "diary-insert-entry" "query-replace-regexp" "whitespace-cleanup-region" "delete-trailing-whitespace" "calc" "diary" "eshell" "web-mode" "nxml-mode" ...))
  smex()
  call-interactively(smex nil nil)
  command-execute(smex)
```

**Comment by npostavs** [comment]
> One difficulty is I was not able to run "make lisp" on the next branch since Windows doesn't have make.

Actually, can you reproduce the error without compiling? The backtrace would be more readable then.

**Comment by mkleehammer** [comment]
I've confirmed it is something that the use-package macro is doing.  First, I can't get a readable backtrace after deleting *.elc files so I suspect use-package is byte-compiling.  I'll look into that.

Secondly, if I manually add magit to the load-path instead of using ":load-path" in the macro it works.  For now I've removed it and I will work with the use-package author to see if they can help.  Both of these packages are used widely so it would be nice to get them working together.

Perhaps this issue should be renamed to include use-package in the title.  You might want to test use-package yourself and put something in the FAQ.  Before this it has been a great utility and it seems to be spreading quick.

I'll close this now and post any new information I find in further comments.  Sorry to waste your time.

**Comment by npostavs** [comment]
In case it wasn't clear, I'm not the magit maintainer (he's currently on vacation). I do use both magit and use-package.

My guess is you have some old version of magit installed somewhere (which further explains why removing elc files seems to have no effect). Check your `load-path`; jwiegley/use-package#105 is probably relevant.
