### ISSUE TITLE
magit-insert-status-headers/magit-rev-format doesn't handle upstream gone

### ISSUE THREAD

**Issue by Silex** [magit/magit#1740]
See #1739 for more details.

Basically in `magit-insert-status-headers`, there is the following lines:

``` elisp
              (setq line (or (magit-rev-format "%h %s" upstream) ""))
              (string-match "^\\([^ ]+\\) \\(.*\\)" line)
              (magit-bind-match-strings (hash msg) line
```

This fails when the upstream was deleted.

I think the following should be enough to reproduce:

``` console
git checkout -b foo
git push -u origin foo
git push origin :foo
emacs -f magit-status
```

I would have liked to fix it myself but I can't figure out what to do :disappointed:

**Comment by npostavs** [comment]
I think this is a duplicate of #1723, there is a proposed patch in the comments there.

**Comment by Silex** [comment]
Oh, nice!
