### ISSUE TITLE
with renamed file, magit-diff-staged and magit-diff-working-tree do not show correct diff

### ISSUE THREAD

**Issue by jeffgran** [magit/magit#1741]
I have a single file in my staged changes, that was renamed and a few lines added. `git diff --cached` in the terminal reports just the changes in that file. M-x magit-diff-staged reports something different, though I'm having trouble figuring out what because it's generating a 3.1M diff buffer that hangs emacs. Something is clearly wrong, although I'm sorry I can't tell more about exactly what.

Also, in this situation (where I have one file that was renamed/changed, git reports with "R" label in `git status --short`, which is staged), M-x magit-diff-working-tree RET (select default "HEAD" to compare against) shows new "added" file, which it should not because that file addition is staged, not dirty in the working tree.

I guess my theory is that this "R" status is not handled correctly when generating the `git diff` commands from magit.

**Comment by tarsius** [comment]
Is this with Magit's `master` or `next` branch? If you are using `master` (e.g. from Melpa), please install `next` instead. See https://github.com/magit/magit/tree/next#installation and  #1645.

**Comment by tarsius** [comment]
In `next`, after setting `-M` in the popup, the correct diffs are shown. (Without `-M` one gets a removed and a new file).

As I am no longer backporting to `master` I am closing this.

**Comment by jeffgran** [comment]
Haven't had a chance to try installing `next` yet, but I am assuming you're correct that it works there. Thanks, sorry for obsolete bug report.
