### ISSUE TITLE
Magit help popup no longer columnar

### ISSUE THREAD

**Issue by andschwa** [magit/magit#1748]
Hi,

Commit 56352fb65157721bfe046e4e82d845718118715e (on branch next) has caused my help popup to longer be separated into columns.

Granted, I have a lot of minor modes enabled, and am about to start going through them to see if any are conflicting:

```
Enabled minor modes: Anzu Auto-Composition Auto-Compression
Auto-Encryption Blink-Cursor Column-Number Delete-Selection
Diff-Auto-Refine Electric-Indent File-Name-Shadow Font-Lock
Global-Anzu Global-Auto-Revert Global-Eldoc Global-Font-Lock
Global-Git-Commit Global-Undo-Tree Global-Whitespace-Cleanup Helm
Helm-Autoresize Helm-Match-Plugin Helm-Occur-Match-Plugin Line-Number
Magit-Auto-Revert Menu-Bar Mouse-Wheel Override-Global Popwin
Projectile Projectile-Global Read-Only Recentf Shell-Dirtrack
Show-Paren Show-Smartparens-Global Smartparens-Global Smooth-Scroll
Tooltip Undo-Tree Which-Function Whitespace-Cleanup Winner
```

**Comment by tarsius** [comment]
It's that commit. I am currently refactoring that function and related functionality. Should be ready tomorrow or so.

**Comment by andschwa** [comment]
Cool, thanks for the reply @tarsius!

**Comment by tarsius** [comment]
Okay, I have reverted that commit and after having thought a bit more about the problem that it was supposed to fix, came up with 87c2ee71797d998ccf59eb071ebf9dee59c2c679.

To be honest when I wrote the first commit, I understood neither the symptoms nor the code I was changing to address them correctly. With a clear mind it really is all quite obvious - no more experiments until it "works" :-)

**Comment by andschwa** [comment]
Awesome! I, too, had only a vague clue what that code snippet was doing.

**Comment by andschwa** [comment]
Yup, working perfect now!
