### ISSUE TITLE
[next][minor] Help-section popup buttons don't work with `RET`

### ISSUE THREAD

**Issue by npostavs** [magit/magit#1757]
Hitting `RET` when point is on any of the buttons in the help section gives `Wrong type argument: commandp, "<label>"`.

I noticed this quite a while back, but I only now confirmed it happens with vanilla magit, starting from `emacs -Q`.

**Comment by tarsius** [comment]
Fixed. Funnier was:

While testing the fix I managed to push the only button for which this does just doesn't make any sense: "Push button", leading to 9b3c7454012c8d52c72339b1a534a917804237ba.
