### ISSUE TITLE
Question : How does magit stage via status diff + region.

### ISSUE THREAD

**Issue by jasonm23** [magit/magit#1759]
This is a question about the internals and interfacing with git.  (as opposed to how do I do this using Magit.) (which for anyone who ever googles this by mistake: https://vid.me/8qi5)

What exactly does magit do with git for this action?

**Comment by vanicat** [comment]
something like`git apply --cached < patch` (well, the equivalent in elisp)

By the way, better that only real issue (bug, feature wish...) are posted here. There is http://emacs.stackexchange.com/ and a mailing list (http://groups.google.com/group/magit, mostly inactive, but not completely dead) for more general question.

And read the code, for this kind of question, you will learn more by reading the code.

**Comment by jasonm23** [comment]
Thanks @vanicat I figured this would be the best source of info for the question, apologies.

I'd read the code, but the git operations are at several levels of indirection.  I should've probably just attached the debugger to the various functions.

**Comment by jasonm23** [comment]
Note that this appears to be the way a hunk is staged, but not a region.

ie. https://github.com/magit/magit/blob/master/magit.el#L4763

    ([hunk diff unstaged]
     (magit-apply-hunk-item it "--cached"))
    ([diff unstaged]
     (magit-run-git "add" "-u"
                    (if (use-region-p)
                        (magit-section-region-siblings #'magit-section-info)
                      info)))

It seems that the output from 

    (magit-section-region-siblings #'magit-section-info)

is sent to `git add -u` ... which doesn't document such behavior (anywhere I can find, ie. the git reference materials.)

**Comment by jasonm23** [comment]
Note if I select a single line from an unstaged hunk and run the previously mentioned command, I just get.

   ("@@ -97,3 +98,8 @@")

(note: this would cover the entire hunk.)

And then I do, from the shell.

    echo "@@ -97,3 +98,8 @@" | git add -u

Git then stages the entire hunk.

I will experiment with this, but it still doesn't explain what magit is doing.  By the way, even if you disagree with the location of this issue, please don't close it until it's properly answered.  Thank you.

**Comment by jasonm23** [comment]
Perhaps I should be looking at `(magit-apply-hunk-item it "--cached")` ?

**Comment by jasonm23** [comment]
_Ok, let's mark the answer as:_

See : `(defun magit-apply-hunk-item ...`

Note that if the region is set and the diff is non-zero, magit will generate a `*magit-input*` buffer, which at it's most basic, uses for stdin with a `git apply --cached` command.

To view the `*magit-input*` you can temporarily turn off the `(kill-buffer buf)`  at the end of the function, and take a look at it.

_Hopefully this might help someone else out in the future._
