### ISSUE TITLE
`magit-blame` support for read-only files

### ISSUE THREAD

**Issue by fommil** [magit/magit#1765]
(one for the backlog)

My system has a few read only git repos, which are shared between users as reference sources of upstream projects.

However, it is not possible to use `magit-blame` in these repos because `magit-blame` is unable to operate on read-only buffers.

**Comment by tarsius** [comment]
Did you try the `next` branch? With that able to blame a read-only buffer from a read-only repository without any problems.

**Comment by fommil** [comment]
I'm using the latest dev version on stable, you have a branch **ahead** of that?
