### ISSUE TITLE
Provide a way to diff a single file across commits.

### ISSUE THREAD

**Issue by tmccombs** [magit/magit#1766]
I would like to have a way to see the changes made to a single file in a  single commit. 
So something like: `git diff ref1 ref2 -- path`

**Comment by tarsius** [comment]
You are aware that you can hide the other files using <kbd>TAB</kbd>, right? But yet that isn't very convenient. Is there another reason why you want to limit diff to a single file?

I might implement this, but probably only after the release.

**Comment by phil-s** [comment]
...or to invert that suggestion, in magit's commit buffer, you can also use <code>M-1</code> to collapse *all* files, and then <code>TAB</code> to expand the one you're interested in.

Alternatively, not using magit: From the file buffer, <code>C-x v l</code> to show the commit log for that file; <code>n</code>/<code>p</code> to navigate the commits in the log buffer; lower-case <code>d</code> to show the diff for that file (only) for the commit at point.

**Comment by tarsius** [comment]
On the `next` branch diffs can now be limited to certain files, just like it was already possible for logs (again on the `next` branch).
