### ISSUE TITLE
PDF of documentation

### ISSUE THREAD

**Issue by fommil** [magit/magit#1768]
Is there any chance you could produce PDFs of the info manual? I really love to print these sorts of manuals off to read them. These docs don't print out well http://magit.github.io/master/magit.html

**Comment by tarsius** [comment]
Yes, I plan on doing that, starting with the next release.

**Comment by fommil** [comment]
:smile:

**Comment by tarsius** [comment]
Closing in favor of #1096 which now explicitly mentions this.

**Comment by tarsius** [comment]
The manual as now available as a pdf, see http://magit.vc.

**Comment by fommil** [comment]
:smile: on its way to my printer...
