### ISSUE TITLE
On Magit 'next' branch, M-x magic-status no longer visits symlinks

### ISSUE THREAD

**Issue by jwiegley** [magit/magit#1769]
My `~/.emacs.d` directory is a symlink to `~/src/dot-emacs`.  When I visit the symlink, it asks if I want to create a repository there.  With the `master` branch, it simply shows me the status, as if I'd visited the latter.

Nice speedups on the `next` branch, btw!  I'm liking it a lot.

**Comment by tarsius** [comment]
I cannot reproduce this, not even when I set `vc-follow-symlinks` as well as `find-file-visit-truename` to `nil`. (I generally recommend keeping the defaults of nil for the former and t for the latter). Are you using 25.0.50? If so please try 24.4 too. And what Git version are you using?

Thanks for noticing the speedups :-)

**Comment by jwiegley** [comment]
I'm using 24.4.  Here's an example of the error I just received:

```
/Users/johnw/Contracts/OSS/Projects/nixpkgs/master/ is a repository.  Create another in /Users/johnw/oss/nixpkgs/master/? (y or n) n
```

Where `oss` is a symlink to `OSS/Projects`.

**Comment by tarsius** [comment]
Please try with `emacs -Q`.
What Git version are you using?
What does `ls -l /path/to/link` print?
What does `cd /path/to/link; git  rev-parse --show-toplevel` print?
What about `magit-toplevel`, `magit-toplevel-safe`, and `magit-get-top-dir`?

**Comment by tarsius** [comment]
Still having problems with this?

**Comment by jwiegley** [comment]
Yes, the behavior is still the same.  Been meaning to debug this for you.  Let me try right now.

**Comment by jwiegley** [comment]
It's this call causing the problem:

``` elisp
(string-equal directory toplevel)
```

Directory is `/Users/johnw/.emacs.d`, but `top-level` is `/Users/johnw/Projects/dot-emacs`.

**Comment by jwiegley** [comment]
Doing a filename canonicalization prior to comparison should cure it.

**Comment by tarsius** [comment]
Makes sense, but unless you use a prefix argument, we should not even enter THEN in `magit-status`s `if`.

Does `(let ((default-directory "/Users/johnw/.emacs.d/")) (magit-get-top-dir))` return `nil` in your case? It should return `"/Users/johnw/Projects/dot-emacs/"`. Your suggested fix still makes sense, since when you do use a prefix argument then we enter THEN and indeed have to get the truename of the provided directory. Also note that Magit buffers always visit the truename anyway, so we should convert to the truename earlier, and not just for the test.

**Comment by jwiegley** [comment]
It returns `"/Users/johnw/Projects/dot-emacs/"`.

**Comment by tarsius** [comment]
So was THEN entered in your case, or did you just assume it did, and actually had the debug statements placed elsewhere?

**Comment by tarsius** [comment]
This is what I tried to reproduce:

```
$ mkdir parent
$ git init parent/repo
Initialized empty Git repository in /tmp/parent/repo/.git/
$ ln -s parent/repo link
$ cd link
$ git rev-parse --show-toplevel

(let ((default-directory "/tmp/link/"))
  (magit-status))
```

**Comment by jwiegley** [comment]
Here is the code:

``` elisp
  (if directory
      (let ((toplevel (magit-toplevel-safe directory)))
        (setq directory (file-name-as-directory (expand-file-name directory)))
        (if (and toplevel (string-equal directory toplevel))
            (magit-status-internal directory)
          (when (y-or-n-p
                 (if toplevel
                     (format "%s is a repository.  Create another in %s? "
                             toplevel directory)
                   (format "Create repository in %s? " directory)))
            (magit-init directory))))
    (magit-status-internal default-directory))
```

I enter the ELSE case, because the `string-equal` indicates that the strings are not equal (as they are not), even though they refer to the same underlying path.

**Comment by tarsius** [comment]
I meant the outer `if`. I don't see how DIRECTORY could possibly be non-nil (*), which it has to be for THEN to be entered.

_* except of course for the reasons given inside `interactive`. But since you said that `magit-get-top-dir` returns non-nil, and (so I have to assume) you don't use a prefix argument, DIRECTORY is cannot be anything but `nil`.

**Comment by tarsius** [comment]
Are you invoking `magit-status` directly as an interactive command, or do you use some wrapper command, which provides the DIRECTORY argument?

**Comment by jwiegley** [comment]
I'm invoking `magit-status` directly as an interactive command.

**Comment by tarsius** [comment]
So do you understand why I think DIRECTORY cannot be non-nil, or do you have reason to believe that I misunderstand what is going on inside `interactive`?

**Comment by jwiegley** [comment]
I don't understand this conversation anymore.  `directory` is non-nil because I was just prompted by `magit-read-repository` to give it a directory name, which I did, the symlink `/Users/johnw/.emacs.d`.

**Comment by jwiegley** [comment]
Also, is the branch viewer gone now?  How do I see a summary of my other branches?

**Comment by jwiegley** [comment]
I'm invoking `magit-status` from a directory with no parent repository, so `(not (magit-get-top-dir))`  is true.

**Comment by tarsius** [comment]
`Y` but it's slow due to some new features. I will provide instructions on how to turn them off or even do so by default.

**Comment by jwiegley** [comment]
You mean `Y` the cherry picker?

**Comment by tarsius** [comment]
Ups, I meant `y`.

**Comment by jwiegley** [comment]
ahhh

**Comment by tarsius** [comment]
(And the slowness is due to it doing some cherry-related stuff (but not as slow as the old wazzup buffer). The new branch manger absorbed the wazzup buffer).

**Comment by tarsius** [comment]
> I'm invoking `magit-status` from a directory with no parent repository, so `(not (magit-get-top-dir))`  is true.

Ah, now it makes sense ... you were kinda refusing to provide that information, you know.

**Comment by jwiegley** [comment]
Was I refusing to? :)  Isn't it normal to call magit-status from directories other than those under Git's control?

**Comment by tarsius** [comment]
Many people do - I personally almost never do, but it's a perfectly fine way of entering Magit.

I only ever have one or two windows per frame and first opening a a file or dired buffer and then the status buffer from that guarantees that the status buffer is always at the bottom.

**Comment by jwiegley** [comment]
Ah.  Well, the excellence of your Magit package has convinced me that `magit-status` is the best "home buffer" for my projects, so I forgo the dired altogether!

**Comment by jwiegley** [comment]
I also have a hack that starts `git-monitor` whenever I open a Magit buffer, so that way I get continual tracking of my changes in Git as a work, on a snapshots ref.

**Comment by tarsius** [comment]
I will install your proposed fix (using `(file-truename directory)`, that's what you had in mind, right?).

Just to make sure you haven't missed it: the `default-directory` in magit buffers is always a truename. That might bother some people, but there's not much I can do about that except not using git to find out where git's directories are. And I really don't want to go there.

**Comment by jwiegley** [comment]
`file-truename` is what I had in mind.  I didn't notice that the name of magit buffers became really long on the `next` branch.  I would have preferred just the basename of the directory to be part of the buffer name, as I think it was in 1.x.  It makes `ido` easier to use (because otherwise, all the long paths mean I see very few candidates in my minibuffer).

**Comment by tarsius** [comment]
> Ah.  Well, the excellence of your Magit package has convinced me that `magit-status` is the best "home buffer" for my projects, so I forgo the dired altogether!

And I have never used dired to it's full potential, so I force myself to use it more :-)

**Comment by tarsius** [comment]
You can make the buffer names shorter by replacing %a with %b in `magit-status-buffer-name-format` and similar variables. For each buffer type there is now one buffer per repository. If you have two repositories with the same basename and use %b, then that will conflict though.

**Comment by tarsius** [comment]
It would be possible to be smarter about it (similar to what `uniquify` does for file-visiting buffers) but that hasn't been implemented yet.

**Comment by jwiegley** [comment]
I miss `U` and `S` meaning unstage or stage all.  Was there a reason to change them?

**Comment by tarsius** [comment]
I am not sure what `S` used to do, but stagging all modified (i.e. already tracked but modified files) seems like the reasonable thing to do.

`U` is bound to `magit-reset-index`, which might sound like it does something else, but actually does unstage all staged changes.

In what way does the behavior differ from what you expected?

**Comment by jwiegley** [comment]
`U` prompts now, so I'm not sure what it's going to do, while before it just unstaged everything.

**Comment by tarsius** [comment]
If you just confirm the default choice using `RET` directly, then it will just unstage. I admit this is a bit confusing and unexpected in this case, but is consistent with how confirmation-or-selection is now done across Magit. See http://magit.vc/manual/next/magit_79.html#Confirmation-and-completion

**Comment by tarsius** [comment]
> I also have a hack that starts `git-monitor` whenever I open a Magit buffer, so that way I get continual tracking of my changes in Git as a work, on a snapshots ref.

`magit-wip-mode` has been improved, so you might want to give that a try too. There now also is a `magit-backup-mode` which creates a stash before "applying" a change (stage, unstage, revert, apply). But it does not perform well. I intend to combine the two eventually into just one, faster mode. You might, or might not, like the current implementations. (These modes of course only have an effect for actions performed from within Emacs/Magit).

**Comment by tarsius** [comment]
Ah, you are the author of git-monitor, so you are probably not gonna ditch it in favor of something else.

Using stashes in `magit-backup-mode` has turned out to be a mistake. It doesn't perform well - especially because I had to reimplement `git stash` in elisp, because the implementation from git isn't flexible enough. `magit-wip-mode` and I believe `git-monitor` only track the working tree, but there is nothing that would keep them from keeping two independent wip refs, one for the index and one for the tree.

**Comment by jwiegley** [comment]
I'm pretty sure `git-monitor` only tracks working tree contents for files under version control.

**Comment by jwiegley** [comment]
I have a branch that uses `fsevents` to make updates immediately, and this is able to deal with untracked files too, but it isn't stable enough yet.

**Comment by tarsius** [comment]
What I meant is that you *could* also keep a second wip ref which tracks the state of the index, *if* you want to do that.

**Comment by tarsius** [comment]
(And that this is what I will probably do in Magit eventually).
