### ISSUE TITLE
magit-ranged-log is broken

### ISSUE THREAD

**Issue by slackorama** [magit/magit#1773]
When trying to do get the history between two branches, it only grabs the logs up to the first specificed revision.

The commit fc76a82c527817889239b709b6ef9c7f8a77b6e7 turns the passed in `range` of `("master" . "develop")`   into just `"master"`. So I get the output of `git log master` vs. `git log master..develop`

I'm not sure what forward compatiblity this is trying to fix so I can't really submit a patch for it.

**Comment by tarsius** [comment]
I though I already fixed that. Which demonstrates that one should open an issue not just comment on a commit :-)

**Comment by slackorama** [comment]
Thanks for the quick turn-around!
