### ISSUE TITLE
Is there a way to disable showing the staging area as a diff on commit (next branch)

### ISSUE THREAD

**Issue by jwiegley** [magit/magit#1776]
Whenever I commit now, Magit wants to show me a diff of everything that goes into the commit.  This is problematic for three reasons:

 1. I already know what's going into the commit, because I just spent time reading over each hunk and staging it.
 2. It moves windows around unpredictably sometimes, so that I have to hunt to find where my commit message window just went to.
 3. It is slow.

I looked in the customization group for a way to disable this behavior, but could find nothing.

**Comment by tarsius** [comment]
It's surprisingly well hidden because of the way I had to implement it. Remove `magit-commit-diff` from `server-switch-hook`.

**Comment by jwiegley** [comment]
Thanks! :)
