### ISSUE TITLE
Quit during push does not kill git process

### ISSUE THREAD

**Issue by greenrd** [magit/magit#1779]
I initiated a push, then when a prompt asking for my https://github.com username appeared, I realised that I had tried to push to the wrong repo (the upstream repo, instead of my fork). So I cancelled the push with C-g, but then I found out using `pidof` that the `git` process was still around and hadn't been killed.

**Comment by tarsius** [comment]
Pushing happens asynchronously so you won't be able to kill the process like this. You could press `$` and then `M-x magit-process-kill` after making sure point is on the right process. Might be to slow to kill the process before it has done its thing though.

**Comment by greenrd** [comment]
I would have thought that the prompt for the username could kill the process when it quits. I do get an error in the minibuffer when I quit.

**Comment by tarsius** [comment]
Ah sorry, I misunderstood. Well yes it should do that. Push on `master` is wrong in many ways, I have added a new implementation on `next`. But I think even the `master` should allow aborting during the prompt using `C-g` (provided there actually is a prompt).

**Comment by tarsius** [comment]
I finally read your report properly ... will investigate.
