### ISSUE TITLE
[next][patch(es)] With view-read-only = t, magit-blame-mode fights for view-mode over keybindings

### ISSUE THREAD

**Issue by npostavs** [magit/magit#1780]
With `view-read-only` = `t`, the `view-mode` keybindings can shadow `magit-blame-mode`'s, for example, `q` is bound to `View-quit` (which leaves the buffer still in `magit-blame-mode`, and buries it) instead of `magit-blame-quit`.

I thought of 2 possible solutions:

- Set `view-read-only` buffer locally to `nil` (could be a problem if the user has setup their own buffer-local settings (or am I over thinking this?)) https://github.com/magit/magit/compare/magit:next...npostavs:blame-no-view?expand=1

- Make sure `magit-blame-mode` precedes `view-mode` in `minor-mode-map-alist` so `magit-blame-mode` shadows `view-mode` rather than the other way around. Seems less problematic, though having to manipulate `minor-mode-map-alist` feels a bit silly. https://github.com/magit/magit/compare/magit:next...npostavs:blame-over-view?expand=1

**Comment by tarsius** [comment]
Two more options:

* Just turn of `view-mode` using `magit-blame-disable-modes`.
* Advice `View-quit`.

Of course it would be best if there was an official way to make sure some map appears before another. I believe there was a discussion about that on emacs-devel. But even if that happened to already be implemented, we would still need something for older Emacs versions.

So far I think your second suggestion is best. It's probably not finished yet though.

What happens if `view-mode` is turned on after `magit-blame-mode`?

**Comment by npostavs** [comment]
> Just turn of view-mode using magit-blame-disable-modes.

Oh, I missed that variable. This does seem strictly better than my first suggestion.

> Advice View-quit.

`View-quit` was just an example, in fact, only 
```
`magit-blame-mode' Minor Mode Bindings:
key             binding
---             -------

N		magit-blame-next-chunk-same-commit
P		magit-blame-previous-chunk-same-commit
b		magit-blame-popup
t		magit-blame-toggle-headings
```
are left unshadowed (and I actually bound `b` to `View-scroll-page-backward`, so I have even 1 less).

> So far I think your second suggestion is best. It's probably not finished yet though.
> 
> What happens if view-mode is turned on after magit-blame-mode?

If turning on `view-mode` causes it to be loaded then it grabs first place in the list. Perhaps `(eval-after-load 'view-mode '(magit-blame-put-keymap-before-view-mode))`?

**Comment by tarsius** [comment]
I prefer your second approach. Using `magit-blame-disable-modes` doesn't seem like such a good idea because users might actually turn it on to be able to use its keybindings :-)

Could you please finish this, test it and then open a pr. Thanks.
