### ISSUE TITLE
New ways to donate

### ISSUE THREAD

**Issue by tarsius** [magit/magit#1784]
/cc @dudebout @vanicat @sigma 

At the end of 2013 @bradleywright [suggested](https://github.com/magit/magit/issues/1121) that we should accept donations through Gratipay (then Gittips).  I setup a group account which allowed all contributors to take their share as they saw fit.  Only Yann ever joined that group and never took more than the minimal amount of one cent per week.  The weekly donations peeked at $26.

Unfortunately Gratipay isn't as popular as I wished it was.  Many users would have to signup and transfer money to Gratipay, just so they could donate to Magit development.  For a long time I intended to add more donation options, but only now got around to do it (I needed another nudge by a user).

In addition to Gratipay its now possible to donate using Flattr, PayPal, and the block-chain.  This can be done from the [donation page](http://magit.vc/donations).

I have setup personal accounts, so for the time being I receive all donations made through the new services directly.  I think this is appropriate since in 2014 and 2015 95% of all changes were made by me (over the complete livetime of Magit it is [58%](http://magit.vc/stats/authors.html)). Should that change, then we can also adjust how donations are accepted and distributed.  I hope this is okay with everyone.

Please also note that the donations page also mentions that users should consider donating to former maintainers. (If you want to accept donations, then please provide a way for users to do so).  Also I can really use the money as I currently have no other income and my savings are vanishing.

**Comment by Silex** [comment]
@tarsius: are you looking for a job? any online CV/portfolio we can look at?

Don't get me wrong I likely won't have much to offer but maybe someone in my (swiss) network do.

**Comment by sigma** [comment]
>>>>> "Jonas" == Jonas Bernoulli <notifications@github.com> writes:

> /cc @dudebout @vanicat @sigma 
> At the end of 2013 @bradleywright
> [suggested](https://github.com/magit/magit/issues/1121) that we should accept
> donations through Gratipay (then Gittips).  I setup a group account which
> allowed all contributors to take their share as they saw fit.  Only Yann ever
> joined that group and never took more than the minimal amount of one cent per
> week.  The weekly donations peeked at $26.

> Unfortunately Gratipay isn't as popular as I wished it was.  Many users would
> have to signup and transfer money to Gratipay, just so they could donate to
> Magit development.  For a long time I intended to add more donation options,
> but only now got around to do it (I needed another nudge by a user).

> In addition to Gratipay its now possible to donate using Flattr, PayPal, and
> the block-chain.  This can be done from the [donation
> page](http://magit.vc/donations).

> I have setup personal accounts, so for the time being I receive all donations
> made through the new services directly.  I think this is appropriate since in
> 2014 and 2015 95% of all changes were made by me (over the complete livetime of
> Magit it is [58%](http://magit.vc/stats/authors.html)). Should that change,
> then we can also adjust how donations are accepted and distributed.  I hope
> this is okay with everyone.

> Please also note that the donations page also mentions that users should
> consider donating to former maintainers. (If you want to accept donations, then
> please provide a way for users to do so).  Also I can really use the money as
> I currently have no other income and my savings are vanishing.

That's perfectly fine with me, and I personally don't intend to accept
any donations (and certainly not for magit, given my absolute lack of
involvement :)).

Good luck, and I hope your situation improves shortly. I don't think
I have you as contact on Linkedin (yet?), but I probably still have
a decent network from my time in Switzerland, so if I can be of any
help...

Thanks

Yann.

-- 
To know what one ought to do is not enough.

  -- PRINCE RHOMBUR VERNIUS

**Comment by tarsius** [comment]
@Silex @sigma Thanks for the offers, I'll contact you by mail.
