### ISSUE TITLE
melpa-stable tag breaks all master installs

### ISSUE THREAD

**Issue by bradleywright** [magit/magit#1785]
https://github.com/magit/magit/releases/tag/90150116 causes `90150116` to come before the current master of `20150319.1355` - this means it's impossible to install master due to the way Emacs numerical packages work.

Is this intentional?

**Comment by tarsius** [comment]
Yes, but it will stop being relevant later today.

**Comment by tarsius** [comment]
I have released `1.4.0`. Unfortunately the `90150116` remains. @milkypostman will delete it when he gets the change, see https://github.com/milkypostman/melpa/pull/2640#issuecomment-88657763.

**Comment by milkypostman** [comment]
I have cleaned out everything and it should be ready in an hour or so. If the 1.4.0 doesn't appear by end of day PST I'll have another look.

**Comment by tarsius** [comment]
Melpa-Stable now is at `1.4.0`. Thanks @milkypostman and @purcell.
