### ISSUE TITLE
magit.info

### ISSUE THREAD

**Issue by Pitometsu** [magit/magit#1788]
Where is now *magit.info*?
`
install-info: No such file or directory for /Users/netsu/.emacs.d/el-get/magit/./magit.info
`

**Comment by tarsius** [comment]
I forgot to ensure that the el-get package continues to be build from the master branch. I have proposed such a change now, see https://github.com/dimitri/el-get/pull/2145.

(The manual for the next branch currently only exists in the webpage repository).

**Comment by Pitometsu** [comment]
Oh, I already create one: https://github.com/dimitri/el-get/pull/2144
