### ISSUE TITLE
Emacsclient wiki page is missing information

### ISSUE THREAD

**Issue by daveloyall** [magit/magit#1789]
In magit 20150402.729 (melpa), when emacsclient can't be located programmatically, magit pops up a buffer that suggests visiting https://github.com/magit/magit/wiki/Emacsclient for more information.

Some information is missing from that page: how do I manually tell magit which emacsclient to use?

Side note: Just store the wikipage in magit and open a buffer with the entire page content if/when the content is needed.

**Comment by tarsius** [comment]
I have updated the page.

**Comment by daveloyall** [comment]
Fine work.  Thank you!
