### ISSUE TITLE
`magit-status` always asks to create a git repo

### ISSUE THREAD

**Issue by steckerhalter** [magit/magit#1796]
After some recent upgrade I cannot use `magit-status` anymore. It is unable to detect that the current directory is part (or top-level) of a git repo and when I specify the dir via the prompt it asks me to create a new repo.

I have installed v1.4.0 now which works as expected. 

git version 1.7.10.4
GNU Emacs 24.4.1 (i486-pc-linux-gnu, GTK+ Version 3.4.2) of 2015-01-12 on babin, modified by Debian

**Comment by tarsius** [comment]
> I have installed v1.4.0 now which works as expected. 

And in which version/branch doesn't it work as expected?

**Comment by steckerhalter** [comment]
on the branch `next` which is set as default

**Comment by tarsius** [comment]
Does reverting 8467f15a6c9eadd8ef87b320584ab7f06c78dab9 if it?

**Comment by tarsius** [comment]
If not, then there are probably symlinks involved, right?

**Comment by steckerhalter** [comment]
no change with reverting 8467f15

I tried various directories and none of them are symlinks.

From what I could analyse both `magit-toplevel` and `magit-git-dir` return nil. I couldn't yet see why. My guess is that the "current" directory is not correctly set...

**Comment by johnmastro** [comment]
I ran into this issue the other day on an Ubuntu Server 12.04 box. 

The closest I got to the root cause was that `magit-get-top-dir` was returning `nil`. Using a more recent `git` resolved the issue, though I haven't gotten back to it yet to see precisely what was going on.

**Comment by tarsius** [comment]
At least `1.9.1` is required. Magit will soon start to complain at startup if an older version is used.

**Comment by steckerhalter** [comment]
ok, I have upgraded git and it works now, thanks
