### ISSUE TITLE
Support sending and receiving patches and working with pull requests

### ISSUE THREAD

**Issue by tarsius** [magit/magit#1800]
Instead of implementing basic support for `git send-email` and the fetching of pull requests, we should implement complete workflows for interacting with other developers per mail, github, bitbucket, gitlab, and probable some others.

Getting this right will be a lot of work and will likely end up as the major new feature of some later release. I do not intend to accept patches that implement just parts of this. `2.1.0` will provide basic support for creating patches using `git format-patch` and sending pull requests per mail using `git request-pull`. These features already exist on the `next` branch, and are here to stay until they are replaced with something better. However I do not intend to add support for `git send-email` anytime soon, especially not one that doesn't offer much over just typing that command into a shell.

**Comment by andschwa** [comment]
:+1:

**Comment by tarsius** [comment]
Tabula rasa

Closing, to avoid pressuring myself into implementing this before the prerequisites are fully ready, just because there's an open issue for this but not the prerequisites.

Also see the [`3.1.0`](https://github.com/magit/magit/milestones) milestone (click on "more").

**Comment by zabbal** [comment]
Note: while integration with mu4e is certainly nice to have it's not necessary for the first step. For example right now git send-email works for me via msmtp so just a basic wrapper on top of git-send-email which takes care of setting all relevant options and getting cover-letter from emacs would do.

**Comment by tarsius** [comment]
> while integration with mu4e is certainly nice to have it's not necessary for the first step.

The problem with intermediate implementations is that users get used to them. Later when I remove something which is no longer necessary and/or gets in the way of the "ultimate version", some users would urge us to restore the dropped feature/workflow because "that was the best part of it".

**Comment by zabbal** [comment]
In general you're absolutely right. But in this particular case I doubt we can convince every single magit user to switch to use mu4e for emails (although it would be cool :) So I think even if you won't add plain git-send-email support and go straight for mu4e, users would keep demanding it because it's "least common denominator" regardless of personal choice for MUA.

**Comment by tarsius** [comment]
>  plain git-send-email support

I probably won't object to merging a minimal viable version if someone else implemented it.

> mu4e ... "least common denominator"

Did I mention just mu4e? I intend to support Gnus too.

**Comment by zabbal** [comment]
mu4e, gnus, whatever - it doesn't matter how many clients you support directly, there'll always be another guy who only uses mutt or or thunderbird or, gods forbid, outlook. Hence inevitably there will be requests to support sending patches indirectly via git-send-email instead of interacting with some email client directly.

**Comment by tarsius** [comment]
I know. I will implement it, eventually. Not now.

> Closing, to avoid pressuring myself into implementing this before the prerequisites are fully ready, just because there's an open issue for this but not the prerequisites.

Okay so maybe this particular subset of

> Instead of implementing basic support for git send-email and the fetching of pull requests, we should implement complete workflows for interacting with other developers per mail, github, bitbucket, gitlab, and probable some others.

doesn't actually have many prerequisites. But the most important part of the first quote wasn't "after prerequisites" but **"not pressuring"**. So please don't do that.

Please note that for a very long time now I have, whenever possible, rushed those little things user requested. I have decided to stop doing that because it's not the most productive way to improve Magit. The breaking point was the `v2.4` release. Which I released yesterday. I am not going to break that resolution on the **very first day**.

**Comment by tarsius** [comment]
Please keep this in mind:

> I probably won't object to merging a minimal viable version **if someone else implemented it**.

**Comment by llvilanova** [comment]
I'm not sure if this is the right place to comment it, but magit-stgit recently got the ability to send patches as mails (command `stg mail`, revision magit/magit-stgit@9d13effdbc213a0c8dcce78e1825011631fa0652).

**Comment by Hi-Angel** [comment]
> Tabula rasa
> 
> Closing, to avoid pressuring myself into implementing this before the prerequisites are fully ready, just because there's an open issue for this but not the prerequisites.
> 
> Also see the [`3.1.0`](https://github.com/magit/magit/milestones) milestone (click on "more").

Thanks, so, is there a documentation for how this new workflow is implemented? Btw, `3.1.0` mileston doesn't exist.

**Comment by tarsius** [comment]
Support for pull-requests is implemented in the new Forge package. It does not support mail based workflows, but see #2972.

I decided to release a `3.0.0` so `3.1.0` was renamed to that. (There never was a `2.0.0`, `2.1.0` was the first `2.*.*`. That naming scheme was inspired by how Emacs does it. I decided to not doing that way again.)
