### ISSUE TITLE
magit.extension=wip-save doesn't work in branch next?

### ISSUE THREAD

**Issue by daveloyall** [magit/magit#1801]
I have to manually enable `magit-wip-save-mode`.

I tried setting `global-magit-wip-save-mode` and setting `magit.extension=wip-save` in my repository.

But, when I visit a file in that repository, wip-save isn't automatically enabled.  It works when I activate it manually.

**Comment by tarsius** [comment]
Probably because that library is not automatically loaded. I have a commit sitting in a lengthy patch series which makes sure it is autoload (or if that fails loaded upfront). I'll probably push that tomorrow. Meanwhile just requiring the library explicitly should do the trick.

**Comment by tarsius** [comment]
I pushed the changes, but you still have to explicitly load `magit-wip.el` in addition to the git configuration.
