### ISSUE TITLE
Commit messages almost never saved to `log-edit-comment-ring`

### ISSUE THREAD

**Issue by Malabarba** [magit/magit#1802]
(On the `next` branch)
Maybe I'm doing something wrong, but I noticed that `git-commit-save-message` only gets called when the commit-message buffer is first created (when it's still empty) and not when I finish editing the buffer.
Because of that, commit messages are rarely stored in the ring and hitting `M-p` never gives me the previous messages.

Is that the intended behavior? If so, is there a way to have the current commit message saved to log-edit-comment-ring every time I finish a commit?

Cheers

**Comment by npostavs** [comment]
I think this is a dup of #1677.

**Comment by tarsius** [comment]
What do you guys think, should messages be saved by default when creating the commit? (It will be documented better anyway).

**Comment by Malabarba** [comment]
> What do you guys think, should messages be saved by default when creating the commit? 

I prefer messages to be saved. But it's also very easy to change (now that I know how) so I have no strong feelings on the default.
