### ISSUE TITLE
RFH A "How to push on MS Windows" tutorial

### ISSUE THREAD

**Issue by tarsius** [magit/magit#1810]
Every other week a MS Windows user posts somewhere that she cannot push using Magit. I am pretty sure that almost never Magit is to blame, but never-the-less this isn't good for its reputation among Windows users.

We have two FAQ entries about this, but there are two problems with those. (a) Many users don't read the FAQ. Unfortunately we cannot do anything about that. (b) When we do point users to these explanations, then that might be enough for them, but it also *might not*.

I would like to get to the point where we can just point users to some resource, which is sufficient to "fix" the issue for 95% of them. A simple FAQ entry - or two - won't do. It is more complex than that.

So this is a request for someone to contribute such an in depth tutorial. It should cover "does it happen on the command line too?", **all** the options available on Windows (including pros and cons), and for each variant it would explain in depth what potential issues are, how to diagnose them, and how to remove failed attempts to work around them.

**Comment by tarsius** [comment]
Ps: I am considering creating yet another issue on the [Emacs Stackexchange site](http://emacs.stackexchange.com) for this. That question would differ from other such issues, in that it would clearly state that it isn't about fixing the issue just for *one particular person*, and that only people who fully understand the issue should answer. Which I am afraid doesn't include me (I haven't used Windows in years). Maybe I should make that a "community wiki question" but then those contributing answers would not get brownie points.

**Comment by tarsius** [comment]
Once more this request led nowhere so I am closing. I might still create the stackexchange question should there be another burst of users having issues configuring git.

**Comment by npostavs** [comment]
At the time this was opened, I was really busy, and looking at it kind of fell off my TODO list. I've now written https://github.com/magit/magit/wiki/Pushing-with-Magit-from-Windows that should mostly cover this, probably the troubleshooting sections will need to be expanded as we find more people having trouble.

Oh, and I've assumed native Emacs with Git for Windows, I suppose there could be additional wrinkles using any combination of native/Cygwin/Msys2 Emacs/git.

**Comment by tarsius** [comment]
Thanks a lot @npostavs! Looks good!

> Under Windows, Magit is unable to intercept the password prompt from git,

Have you verified that this is still the case. The way I remember it is that this only ever happened for some users and that we never figured out why that is so. In case that was a bug in Git that might have been fixed since.

**Comment by npostavs** [comment]
I rechecked now with latest release: Emacs 24.5, and Git for Windows 1.9.5; it's still the case.

> The way I remember it is that this only ever happened for some users and that we never figured out why that is so.

I believe it was working for people who use a passphrase-less ssh key.

---

> In case that was a bug in Git that might have been fixed since.

I think it's rather a fundamental limitation: Windows lacks PTYs. I did just now see what looked like a relevant bugfix for 1.9.5:

> ⦁	ssh-agent: only ask for password if not already loaded

except that appears to actually refer to `start-ssh-agent.cmd` which is a Windows batch script wrapper for `ssh-agent`: https://github.com/msysgit/msysgit/commit/a30ae7418c608001ac3bb1f0579e004df190cd6f

I wasn't aware of this script until now, perhaps it can be used to simplify the OpenSSH passphrase caching case.

**Comment by npostavs** [comment]
So I've come up with some elisp to set up/connect to ssh-agent instead of the bash scripts. Would it make sense to add these functions to magit?

```elisp
(defconst ssh-add-executable (concat (file-name-directory magit-git-executable) "ssh-add.exe"))
(defconst ssh-agent-executable (concat (file-name-directory magit-git-executable) "ssh-agent.exe"))

(defun ssh-add-keys-w32 ()
  "Add keys to ssh-agent."
  (pcase (call-process ssh-add-executable nil nil nil "-l")
    (0 t)                ; ssh-agent running, has keys. Nothing to do.
    (1 (call-process-shell-command ; ssh-agent running, no keys. So add them.
        ;; Passphrase can only be entered in console, so use cmd.exe's `start' to get one.
        (concat "start \"ssh-add\" " (shell-quote-argument ssh-add-executable))
        nil '(t t) t))
    (_ nil)))                           ; ssh-agent not running

(defun start-ssh-agent-w32 ()
  "Start ssh-agent and add keys, as needed."
  (or (ssh-add-keys)
      (let* ((pid
              (--first (-let (((&alist 'comm comm 'user user) (process-attributes it)))
                         (and (string= comm "ssh-agent.exe")
                              (string= user user-login-name)))
                       (list-system-processes)))
             (sock
              (when pid
                (catch 'ssh-sock
                  (dolist (sock-dir (directory-files temporary-file-directory t "\\`ssh-" t))
                    (dolist (sock-file (directory-files sock-dir t "\\`agent\.[0-9]+\\'" t))
                      ;; Follow the lead of msysgit's start-ssh-agent.cmd: replace %TEMP% with "/tmp".
                      (setq sock-file (replace-regexp-in-string (regexp-quote temporary-file-directory)
                                                                "/tmp/" sock-file))
                      (let ((process-environment (cons (concat "SSH_AUTH_SOCK=" sock-file)
                                                       process-environment)))
                        (when (ssh-add-keys)
                          (throw 'ssh-sock sock-file)))))))))
        (if (not (and pid sock))
            (with-temp-buffer ; no running agent, so start one.
              (call-process ssh-agent-executable nil '(t t))
              (goto-char 1)
              (while (re-search-forward "^\\(SSH_[^=]+\\)=\\([^;]+\\)" nil t)
                (setenv (match-string 1) (match-string 2)))
              (ssh-add-keys))
          (setenv "SSH_AGENT_PID" (number-to-string pid))
          (setenv "SSH_AUTH_SOCK" sock)))))
```

**Comment by tarsius** [comment]
> Would it make sense to add these functions to magit?

Yes! Well maybe not these *exact* functions, but something in the spirit.

This is a bit like `with-editor.el` which solves a similar problem (and then also provides additional functionality). Here we are mostly (only?) dealing with incomplete configuration, never-the-less this is a problem that is never going away because there will always be a fresh supply of users who haven't bothered to learn how this works and then configured it. This doesn't affect just Magit so, I think that like `with-editor` this should be implemented as a separate library which is maintained inside the Magit repository but distributed as a separate package, so that others can use it to (and to ensure a clean implementation).

It might also be worth learning from @purcell's [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell). Or maybe that package could be extended to deal with this particular issue?

**Comment by tarsius** [comment]
Just writing down things that come to mind here. Yours might very well be the best approach.

**Comment by npostavs** [comment]
> It might also be worth learning from @purcell's exec-path-from-shell. Or maybe that package could be extended to deal with this particular issue?

The problem with that approach on Windows is that the main OS shell is not the same shell as the one git and ssh use. It would only work if the user has added the needed code into .bashrc and started the git bash shell first. Doing it all in elisp has the advantage that the user doesn't have to think about coordinating program launches.
