### ISSUE TITLE
New magit is too totalitarian

### ISSUE THREAD

**Issue by elibarzilay** [magit/magit#1811]
(I'm using the `next` branch, so if it's not appropriate for bug reports feel free to ignore this.)

I just did a `git rebase` on the command line, and to my surprise magit took over editing todo list file.  It's an interesting feature, but IMO it's too invasive.  For example, I have never done rebases in magit, and had no clue what key bindings could be used -- and the default ones for editing text didn't work.  So again, it seems interesting, and I'm sure that it took a bunch of effort, but Emacs invading this way to places where I use the command line is questionable etiquette.

One of the reasons I always rebased on the command line is to specifically avoid magit's bad behavior in reverting buffers behind my back -- IIUC, it's turned off by default now, but I shudder to think about running into the next bug while trying to rebase in a rush.

An additional problem is that the text in the todo buffer is (again, AFAICT) left as is, and there's no hint or help on how to edit the file.

**Comment by elibarzilay** [comment]
And indeed there was some ensuing mess.  I have a hook for emacsclient buffers that allows me to simply save+kill a buffer and the client frame goes away as if I `C-c C-c`ed it.  Looks like that doesn't make magit happy, leaving me with a pile of open frames, a message telling me to not kill buffers, even though it looks like things worked fine in git.  Obviously, I restarted Emacs since I have no idea what internal state got messed up.

(And to clarify, as with many people, restarting Emacs for me is as traumatic as restarting a server.)

**Comment by tarsius** [comment]
What version did you use previously? `1.4.*` (and before that was released the "master branch" (which is what most people were using)) depended on `git-rebase-mode.el` which also kicked in automatically. (On the `next` branch magit includes the library `git-rebase.el` directly. It's the same as `git-rebase-mode.el` just without the `-mode` suffix. The `git-rebase-mode` package will be deprecated in favor of `git-rebase` once magit 2.1.0 is released.

So far - in over a year - you are the first one to complain about the `git-rebase-mode` automatically being used.

It has to be implemented the way it is. Even when a rebase is initiated from within Emacs, it's actually an external executable (git) which requests that the user edit the list of commits (by invoking `$GIT_EDITOR` which we arrange to be the emacsclient.

Generally I am also not so happy when just loading a library enables a mode for certain files, but here I feel it makes sense. I am not going to change it.

You can prevent the mode from kicking in using:

```lisp
(setq auto-mode-alist
      (delete (cons git-rebase-filename-regexp 'git-rebase-mode) auto-mode-alist)))
```

> I have never done rebases in magit, and had no clue what key bindings could be used -- and the default ones for editing text didn't work.

Like in any buffer `C-h m` and `C-h b` will tell you more about the available key bindings.

> An additional problem is that the text in the todo buffer is (again, AFAICT) left as is, and there's no hint or help on how to edit the file.

Except for "Type C-c C-c to finish, or C-c C-k to cancel" in the echo area, and the list of keybindings insert into the buffer. Sure that list is not complete (also give `M-n` and `M-p` a try), but "no hint or help" seems to be not quite accurate...

... generally speaking you might tone down the hyperbole.

**Comment by elibarzilay** [comment]
> What version did you use previously?

I don't know, but it was an old one.  Probably somewhere around 305
years old.  I have heard about the `git-rebase-mode` thing, but have not
used it.

> So far - in well over a year - you are the first one to complain about
> the git-rebase-mode automatically kicking in.

[I'm surprised, since it is an extremely surprising thing for someone who
expects to just edit a file.]


> It has to be implemented the way it is. Even when a rebase is
> initiated from within Emacs, it's actually an external executable
> (git) which requests that the user edit the list of commits (by
> invoking $GIT_EDITOR which we arrange to be the emacsclient).

Yes, I'm aware of that, and I'm trying to get used to it.  (I have
client windows pop up in new frames and otherwise I disable frame popups
for other things, which makes a weird interaction when something that is
supposed to happen inside Emacs pops up a frame.)


> Generally I am also not so happy when just loading a library enables a
> mode for certain files, but here I feel it makes sense. I am not going
> to change it.

In that case, please consider making it more well behaved.  See below
for suggestions to mitigate things.  It'll be a little verbose, but
please read it.

First, start with the first sentence you wrote here.  It is indeed
something that is generally not great when loading a library changes how
emacs behaves -- but, of course, a change of openning a file in some
different mode is perfectly fine.  However, there are several factors
that make this an irregular situation.  The main one is that it's
something that gets used via emacsclient, which leads to inconsistencies
like:

* If your emacs server process didn't load magit, it will behave as
  usual, once it's loaded, the behavior changes.

* If you haven't started the server (even if you have used magit),
  emacsclient will fire up a new process for the editing, which, again,
  leads to a different behavior.

* And of course, you might have no emacs running at all, which again
  will not have the new stuff unless loaded explictly on startup.

Now, *if* this is *just* a mode -- that is, some nice coloring and
possibly useful key bindings, then this should be made very clear.
Before anything else, this means not rebinding modifier-less keys, or
any of the other standard bindings.  If that's done, then instead of
being surprised that I can't just edit the text and being grumpy about
being forced to learn a bunch of stuff at a point where I'm completely
focused on something else, I'd be just *positively* surprised at having
some nice coloring etc, and potentially useful commands for doing more
complicated things.

To be clear, the most important suggestion I'm making here is to not
rebind plain keys.  For basic pick/squash/fixup/whatever, git is already
making things super simple by requiring very little -- essentially a
single key per command.  This goes for slightly more complex operations
like reordering lines: AFAICT, `M-up` in a rebase todo bufer doesn't
have any advantage over, say, `C-x C-t`.  Yes, the latter is a more
complex key sequence, but it's part of Emacs, so I already know how to
use it, and I already made it simpler to use if I use it often.

This leads to an obvious user setting: have a way to not bind any
editing keys in these todo buffers.  Also, and make it easy to get to
that option: like some information "to disable special bindings do this"
text, or add a key to disable the keys and go back to the usual map.

One way that makes the problem of overriding plain keys is "k": it's
very easy to hit, and you're presented with a strikethrough that makes
what's going to happen very clear.  But -- there's no obvious way to
bring the line back in.  There's "g" which is unintive (and will ask
about reverting) and there's an undo remaping which is nice in that it's
working, but for gui-like things it's not a usual expectation in emacs.
(Note that this ties back to avoiding changing regular keys: if that was
done, I'd intuitively know that it's still just a text buffer, and then
I *would* expect undo to work.)  I finally found "c", but that's far
from being an obvious key...


> Like in any buffer C-h m and C-h b will tell you more about the
> available key bindings.

Yes, that's true -- but neither of these is doing a good job when you're
already in the middle of an operation like rebase.  One thing is that
they tend to be very verbose, especially when you add up minor modes,
making it hard to find things.  But more importantly, the information is
terse to the point of making it hard to get anything useful from it
*unless* you're in an "I'm going to spend some time to learn what I can
do with this thing" mode.  As a quick example, take that "k" thing:
there's nothing obvious in either the mode or the keybinding help text
that tells you how to get a line back -- it's just command names, with
help text being even further away in what you need to do to get to it.
In addition, the information tends to leak implementation details: for
example, why is "n" bound to `forward-line` but "p" is
`magit-rebase-backward-line`?  (BTW, *why* does that function exist?
Why not use the usual `previous-` functions, or better, leave it as the
default -- again -- since your users are Emacs users, then they already
expect some behavior.)


> > An additional problem is that the text in the todo buffer is (again,
> > AFAICT) left as is, and there's no hint or help on how to edit the
> > file.
>
> Except for "Type C-c C-c to finish, or C-c C-k to cancel" in the echo
> area,

That's a standard Emacs message -- not helping with the behavior changes
to editing the file.

> and the list of keybindings insert into the buffer. Sure that
> list is not complete (also give M-n and M-p a try), but "no hint or
> help" seems to be not quite accurate...

I just double checked it: I get no such list.  All I see is git's
default text.  It even leads to a confusion where git adds a line saying

    p, pick = use commit

but magit binds that to the navigation command.


> ... generally speaking you might tone down the hyperbole. And refrain
> from calling features you don't like "bugs".

Apologies if it sounded harsh, but for all practical purposes, running
into this whole thing was certainly something that I consider a bug.
What I planned was a quick reorder of two commits: run `git rebase`,
swap two lines, exit, and done.  Simple enough that there's no big
difference between doing it in emacs (`C-x C-t`) and vi (`ddp`).
Instead, I had a completely different interface, one that disabled most
of my editor, sending me off to a tangent that distracted me from the
actual work that I was doing at the time.  For a tool that exist to make
my git work quicker, this is most certainly a bug.

**Comment by garyo** [comment]
I think Eli's onto something here re: keybindings. I'd prefer regular keys
to still work in git-rebase buffers, with modifier keys to supplement/speed
up common operations.

If people like the single-key commands, maybe git-rebase mode could put a
little header in the buffer explaining the common bindings?  Egg-mode does
a lot of that and I always found it very nice.  As it is now, the buffer
*looks* like a regular git rebase file (which git users are used to) but
simple stuff like "p" doesn't work as expected, so it would be nice to make
it more clear.

On Fri, Apr 17, 2015 at 10:55 AM, Eli Barzilay <notifications@github.com>
wrote:

> What version did you use previously?
>
> I don't know, but it was an old one. Probably somewhere around 305
> years old. I have heard about the git-rebase-mode thing, but have not
> used it.
>
> So far - in well over a year - you are the first one to complain about
> the git-rebase-mode automatically kicking in.
>
> [I'm surprised, since it is an extremely surprising thing for someone who
> expects to just edit a file.]
>
> It has to be implemented the way it is. Even when a rebase is
> initiated from within Emacs, it's actually an external executable
> (git) which requests that the user edit the list of commits (by
> invoking $GIT_EDITOR which we arrange to be the emacsclient).
>
> Yes, I'm aware of that, and I'm trying to get used to it. (I have
> client windows pop up in new frames and otherwise I disable frame popups
> for other things, which makes a weird interaction when something that is
> supposed to happen inside Emacs pops up a frame.)
>
> Generally I am also not so happy when just loading a library enables a
> mode for certain files, but here I feel it makes sense. I am not going
> to change it.
>
> In that case, please consider making it more well behaved. See below
> for suggestions to mitigate things. It'll be a little verbose, but
> please read it.
>
> First, start with the first sentence you wrote here. It is indeed
> something that is generally not great when loading a library changes how
> emacs behaves -- but, of course, a change of openning a file in some
> different mode is perfectly fine. However, there are several factors
> that make this an irregular situation. The main one is that it's
> something that gets used via emacsclient, which leads to inconsistencies
> like:
>
>    -
>
>    If your emacs server process didn't load magit, it will behave as
>    usual, once it's loaded, the behavior changes.
>    -
>
>    If you haven't started the server (even if you have used magit),
>    emacsclient will fire up a new process for the editing, which, again,
>    leads to a different behavior.
>    -
>
>    And of course, you might have no emacs running at all, which again
>    will not have the new stuff unless loaded explictly on startup.
>
> Now, *if* this is *just* a mode -- that is, some nice coloring and
> possibly useful key bindings, then this should be made very clear.
> Before anything else, this means not rebinding modifier-less keys, or
> any of the other standard bindings. If that's done, then instead of
> being surprised that I can't just edit the text and being grumpy about
> being forced to learn a bunch of stuff at a point where I'm completely
> focused on something else, I'd be just *positively* surprised at having
> some nice coloring etc, and potentially useful commands for doing more
> complicated things.
>
> To be clear, the most important suggestion I'm making here is to not
> rebind plain keys. For basic pick/squash/fixup/whatever, git is already
> making things super simple by requiring very little -- essentially a
> single key per command. This goes for slightly more complex operations
> like reordering lines: AFAICT, M-up in a rebase todo bufer doesn't
> have any advantage over, say, C-x C-t. Yes, the latter is a more
> complex key sequence, but it's part of Emacs, so I already know how to
> use it, and I already made it simpler to use if I use it often.
>
> This leads to an obvious user setting: have a way to not bind any
> editing keys in these todo buffers. Also, and make it easy to get to
> that option: like some information "to disable special bindings do this"
> text, or add a key to disable the keys and go back to the usual map.
>
> One way that makes the problem of overriding plain keys is "k": it's
> very easy to hit, and you're presented with a strikethrough that makes
> what's going to happen very clear. But -- there's no obvious way to
> bring the line back in. There's "g" which is unintive (and will ask
> about reverting) and there's an undo remaping which is nice in that it's
> working, but for gui-like things it's not a usual expectation in emacs.
> (Note that this ties back to avoiding changing regular keys: if that was
> done, I'd intuitively know that it's still just a text buffer, and then
> I *would* expect undo to work.) I finally found "c", but that's far
> from being an obvious key...
>
> Like in any buffer C-h m and C-h b will tell you more about the
> available key bindings.
>
> Yes, that's true -- but neither of these is doing a good job when you're
> already in the middle of an operation like rebase. One thing is that
> they tend to be very verbose, especially when you add up minor modes,
> making it hard to find things. But more importantly, the information is
> terse to the point of making it hard to get anything useful from it
> *unless* you're in an "I'm going to spend some time to learn what I can
> do with this thing" mode. As a quick example, take that "k" thing:
> there's nothing obvious in either the mode or the keybinding help text
> that tells you how to get a line back -- it's just command names, with
> help text being even further away in what you need to do to get to it.
> In addition, the information tends to leak implementation details: for
> example, why is "n" bound to forward-line but "p" is
> magit-rebase-backward-line? (BTW, *why* does that function exist?
> Why not use the usual previous- functions, or better, leave it as the
> default -- again -- since your users are Emacs users, then they already
> expect some behavior.)
>
>  An additional problem is that the text in the todo buffer is (again,
> AFAICT) left as is, and there's no hint or help on how to edit the
> file.
>
> Except for "Type C-c C-c to finish, or C-c C-k to cancel" in the echo
> area,
>
> That's a standard Emacs message -- not helping with the behavior changes
> to editing the file.
>
> and the list of keybindings insert into the buffer. Sure that
> list is not complete (also give M-n and M-p a try), but "no hint or
> help" seems to be not quite accurate...
>
> I just double checked it: I get no such list. All I see is git's
> default text. It even leads to a confusion where git adds a line saying
>
> p, pick = use commit
>
> but magit binds that to the navigation command.
>
> ... generally speaking you might tone down the hyperbole. And refrain
> from calling features you don't like "bugs".
>
> Apologies if it sounded harsh, but for all practical purposes, running
> into this whole thing was certainly something that I consider a bug.
> What I planned was a quick reorder of two commits: run git rebase,
> swap two lines, exit, and done. Simple enough that there's no big
> difference between doing it in emacs (C-x C-t) and vi (ddp).
> Instead, I had a completely different interface, one that disabled most
> of my editor, sending me off to a tangent that distracted me from the
> actual work that I was doing at the time. For a tool that exist to make
> my git work quicker, this is most certainly a bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magit/magit/issues/1811#issuecomment-94002290>.
>



-- 
Gary

**Comment by tarsius** [comment]
> AFAICT, `M-up` in a rebase todo bufer doesn't have any advantage over, say, `C-x C-t`. 

Except that it has a logical inverse in `M-down`. And `C-x C-t` is now bound to the same command as  `M-up`.

> why is "n" bound to `forward-line` but "p" is `magit-rebase-backward-line`? (BTW, *why* does that function exist?

Because Emacs sadly does not define `backward-line`, and `previous-line` - unlike `forward-line` does not move to the beginning of the line.

> > > An additional problem is that the text in the todo buffer is (again,
> > > AFAICT) left as is, and there's no hint or help on how to edit the
> > > file.
> >
> > Except for "Type C-c C-c to finish, or C-c C-k to cancel" in the echo
> > area,
>
> That's a standard Emacs message -- not helping with the behavior changes
> to editing the file.

That's not true.

> > and the list of keybindings insert into the buffer. Sure that
> > list is not complete (also give M-n and M-p a try), but "no hint or
> > help" seems to be not quite accurate...
>
> I just double checked it: I get no such list.  All I see is git's default text.

That's the list I was talking about. I now have completed that list and because it now contains things like `C-c C-c` it is obvious that these are Emacs commands.

> It even leads to a confusion where git adds a line saying `p, pick = use commit` but magit binds that to the navigation command.

The code which was supposed to replace the p with c was broken. It no longer is.

**Comment by tarsius** [comment]
> As it is now, the buffer *looks* like a regular git rebase file (which git users are used to) but simple stuff like "p" doesn't work as expected, so it would be nice to make it more clear.

With the improved list of available commands it is sufficiently clear now.

I don't think of this buffer visiting a file - that's just how this is implemented by Git because that's what editors do: let users edit files. It's more useful to think of it as a list of commits with associated actions. There is a limited number of ways in which this list can be modified in a meaningful way, `git-rebase.el` supports them all (except for one border case).

The only meaningful operations are: moving lines, changing the action (the first word) on a line, and removing lines (which `git-rebase.el` does better by commenting them instead). Changing anything but the first is not meaningful. The only thing that is not possible because the buffer is read-only, is inserting commits that weren't in the list to  begin with. But I consider doing that an abuse of `git rebase`, this is what `git cherry-pick` is for (possibly during a rebase). If you want to do it anyway once in a blue moon, you can make the buffer writable.

> I'd prefer regular keys to still work in git-rebase buffers, with modifier keys to supplement/speed up common operations.

When thinking of the buffer content as a list instead of text then... well it makes sense to use list operations. `git-rebase.el` was designed using this observations.  Maybe that's not immediately obvious when using it for the first few times, but *many* users have learned to think of it this way by now, at least intuitively.

Forcing these users to use modifiers would be a major inconvenience. So I am not going to do it. Note that using modifier-less keybindings is *not* an un-emacsy thing to do - there are a lot of built-in modes that do not require modifiers for the most essential commands, e.g. `dired` and `view-mode`.

I try to not needlessly force workflows and restrictions on users, but in some cases I do have make a design decision because supporting every possible variation would be to much work and/or compromise the variant which I consider the best approach.

Both applies here. Modifiers would be an inconvenience, and while I could add some options (e.g. to make the keybindings and read-only-mode optional and to only use `git-rebase-mode` if the rebase was invoked using Magit) that would add a considerable overhead. Implementation-wise it might not be all that bad (of course it's non-trivial and would require maintenance of course) but adding options also adds an overhead for users who are quite happy with the defaults (and I expect that's the majority by far, because previously I have not heard any complains) but still would like to fine-tune.

**Comment by tarsius** [comment]
It's also important to note that Magit features several "list related to rebasing". There's the list we are talking about, the log used to select which commit to begin with, and the list of rebased and to-be-rebased commits shown in the status buffer while a rebase is in progress. The latter two are lists which are impossible to edit as text - for consistency sake it makes sense for the former to behave the same way.

**Comment by garyo** [comment]
On Sat, Apr 18, 2015 at 7:28 AM, Jonas Bernoulli <notifications@github.com>
wrote:

> As it is now, the buffer *looks* like a regular git rebase file (which
> git users are used to) but simple stuff like "p" doesn't work as expected,
> so it would be nice to make it more clear.
>
> With the improved list of available commands it is sufficiently clear now.
>
That's good enough for me.  All the rest of what you write, I agree with.


-- 
Gary

**Comment by garyo** [comment]
On Sat, Apr 18, 2015 at 7:35 AM, Jonas Bernoulli <notifications@github.com>
wrote:

> It's also important to note that Magit features several "list related to
> rebasing". There's the list we are talking about, the log used to select
> which commit to begin with, and the list of rebased and to-be-rebased
> commits shown in the status buffer while a rebase is in progress. The
> latter two are lists which are impossible to edit as text - for consistency
> sake it makes sense for the former to behave the same way.
>

I admit I've found those other lists a bit confusing - I wasn't sure what
was what, but that's probably just me being a hard-core git guy.  I always
just start my rebases on the cmd line, and while in progress again I use
the cmd line to inspect what needs to be done, add my fixes, and
continue/abort.  I haven't tried using those buffers recently; maybe
they're more self-documenting than before.

-- 
Gary

**Comment by tarsius** [comment]
> However, there are several factors that make this an irregular situation. The main one is that it's
something that gets used via emacsclient, which leads to inconsistencies like:

These irregularities exist regardless of the keybindings in the buffer and whether it can be edited as text. So I don't quite see how is relevant here. You seem to argue that because not only the appearance is changed but also the keybindings, this is not acceptable.

`git-rebase-mode.el` was written under the assumption that its users would usually invoke rebase from within Magit. It's perfectly fine to do it from the command line, but that's not the use case this library was optimized for. While I could improve consistency by loading the server when Magit is (auto)loaded, this would not be well received, as it would increase the startup time. There is no way for me to ensure that loading Emacs also (auto)loads Magit and there is no way for me to ensure that Emacs is running when a user types `git rebase` into a terminal.

A user who wants to invoke a rebase session from a terminal is welcome to do so, but is responsible for ensuring that `git-rebase-mode` always kicks in, or live with it not always doing so. It's simply impossible for me to do it for him.

A user who does not like `git-rebase-mode` is welcome to disable it. This admittedly is a bit complicated to do, but the only choices I have here are to either inconvenient 99% of the user base or 1%. I have chosen the latter. But I can write a faq entry (which would be a misnomer in this case) if absolutely necessary.

**Comment by tarsius** [comment]
> I haven't tried using those buffers recently; maybe they're more self-documenting than before.

There not I believe, but this will be covered by the manual in-depth. Meanwhile https://github.com/magit/magit/wiki/History-Manipulation touches on this. You should give it a try - it does to `git rebase` what "magit diffs" did to `git add -p`.

**Comment by garyo** [comment]
Thanks, I will. In general, the more of those self-documenting headers you
can add as reminders (both keybindings and higher level info, like "you are
in the middle of a rebase, 10 of 35 commits applied, stopped due to
conflict - use status buffer to resolve and continue", the happier I'll be.
:-)  To me this was by far the most attractive feature of egg-mode.

On Sat, Apr 18, 2015 at 7:54 AM, Jonas Bernoulli <notifications@github.com>
wrote:

> I haven't tried using those buffers recently; maybe they're more
> self-documenting than before.
>
> There not I believe, but this will be covered by the manual in-depth.
> Meanwhile https://github.com/magit/magit/wiki/History-Manipulation
> touches on this. You should give it a try - it does to git rebase what
> "magit diffs" did to git add -p.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magit/magit/issues/1811#issuecomment-94160783>.
>



-- 
Gary

**Comment by tarsius** [comment]
Oh, those are there (but use somewhat critic action prefixes (inspired by those in the todo list (yes consistency))) . But better.

**Comment by elibarzilay** [comment]
> > AFAICT, `M-up` in a rebase todo bufer doesn't have any advantage over, say, `C-x C-t`.
> Except that it has a logical inverse in M-down.

Like other commands, `transpose-lines` has an obvious inverse operation: `C-- C-x C-t`.  Undoing works too.

> > why is "n" bound to forward-line but "p" is magit-rebase-backward-line? (BTW, why does that function exist?
> Because Emacs sadly does not define `backward-line`, and `previous-line` - unlike `forward-line` does not move to the beginning of the line.

So your goal is to "enhance" the view that it's a list over text: if so, then you'd be better off using an `intangible` property: it'll achieve this goal in a better way.


> > I just double checked it: I get no such list. All I see is git's
> > default text.
> That's the list I was talking about. I now have completed that list
> and because it now contains things like C-c C-c it is obvious that
> these are Emacs commands.

I don't know which text you're talking about.  I'm talking about the
following text example:

    pick a4c4289 ...
    pick ff895f6 ...
    pick c41610c ...
    
    # Rebase 87646e8..c41610c onto 87646e8 (3 command(s))
    #
    # Commands:
    # p, pick = use commit
    # r, reword = use commit, but edit the commit message
    # e, edit = use commit, but stop for amending
    # s, squash = use commit, but meld into previous commit
    # f, fixup = like "squash", but discard this commit's log message
    # x, exec = run command (the rest of the line) using shell
    #
    # These lines can be re-ordered; they are executed from top to bottom.
    #
    # If you remove a line here THAT COMMIT WILL BE LOST.
    #
    # However, if you remove everything, the rebase will be aborted.
    #
    # Note that empty commits are commented out

I get this exact text in the list buffer either with magit or not.


> I don't think of this buffer visiting a file - that's just how this is
> implemented by Git because that's what editors do: let users edit
> files.

Git is not an editor.  But IMO the decision to implement the rebasing
todo list *via* an editor is brilliant.  In fact, it's so good, that
even though the magit thing is trying to compete with it by showing it
as a list, I have not seen any advantage in it, neither in terms of
keypresses or of presented information.

(I have looked for such advantages, BTW.  Pretty much the only one I
found is very mild: hitting enter on a commit to see it.  Mild because I
don't remember ever needing that information while editing the list, and
because if it is needed, then plain emacs editing still makes it easy to
see via a quick copy + a shell command.

OTOH, there *is* at least one use case that would be a significant
advantage over a plain editor that I'd love to have: in the common case
when I use rebase over the past N commits I sometimes miss the count and
not incluse enough commits.  In such cases it would be nice to be able
to "go up" when the cursor is at the top, and have that bring more
commits into the rebase list.)


> It's more useful to think of it as a list of commits with associated
> actions.

Since you've made this very clear and will not change it, please add a
straightforward way to disable the whole rebase thing completely.  (Ie,
*not* post-hacking the mode alist.)


> Note that using modifier-less keybindings is not an un-emacsy thing to do - there are a lot of built-in modes that do not require modifiers for the most essential commands, e.g. `dired` and `view-mode`.

These are both different cases: `view-mode` is for cases where you want to explicitly only view some text (and is much more often used with made up text (like documentation text) rather than plain files); `dired` (as well as buffer/process lists, etc) is editing virtual text, not a file.  In addition, even if there is some mode that rebinds base keys somehow (maybe some todo mode) -- even in that case I have `find-file-literally`, but in the rebase case I don't do the loading of the file from emacs so I don't even have that option.

> [...] while I could add some options (e.g. to make the keybindings and read-only-mode optional and to only use `git-rebase-mode` if the rebase was invoked using Magit) that would add a considerable overhead.

I asked for a way to just disable the whole thing given that you say it's too much work, but otherwise this would be the best option, IMO.


> It's also important to note that Magit features several "list related to rebasing". There's the list we are talking about, the log used to select which commit to begin with, and the list of rebased and to-be-rebased commits shown in the status buffer while a rebase is in progress. The latter two are lists which are impossible to edit as text - for consistency sake it makes sense for the former to behave the same way.

I'm assuming that you're talking about some rebase functionality within magit.  This makes my point even better: I'd like to get to learn how to do that *in magit*, but until I get to have time for that, I don't want to be forced to use it.  By blocking plain editing of the todo lists you're essentially forcing me to learn more than I wanted ATM.  This is why making the rebinding + read-only happen only when invoked from inside magit makes perfect sense.  And the *lack* of this is exactly why I chose the title of this report.


> You seem to argue that because not only the appearance is changed but also the keybindings, this is not acceptable.

Yes, the keybindings, and I'd also include hiding the "#" for killed commits.


> `git-rebase-mode.el` was written under the assumption that its users would usually invoke rebase from within Magit.

Exactly -- making the above point yet again.  I don't see any problem with *that* (having this behavior happen when invoked from magit), which is why I don't see starting the emacs server as a good way to resolve things.


Finally, some side notes about the file:

* Its contents is bogus in that it says that "p" is for picking a commit.

* I think that using "p" for previous-line is a mistake, it would be much less intrusive to stick with the git keys.  (And the above makes me thing that this was the original goal.)

* Finally, if I were implementing such a mode, I'd do my best to make the functionality that you want happen without killing regular editing:
  - Avoid changes to text that shouldn't be modified via some barf message when people do that, or just making those lines intangible.
  - Detect changes to the first character on a line, and if it's one of the rebase commands, complete the command text.  I therefore let people enter text as usual, and I help them in completing the word they started to write for them.
  - If this is a command like `execute` that requires a new line, open up that new line once the character is entered, and have no intangible property there, so that the text is edited as usual on that line.  I'd also indicate that using a different face.
  - If the first character is `#` then show the commit as deleted -- but don't hide that `#`.  This, again, reduces the "magic is happening that you don't see" effect, and reassures people that they're just editing text.
  - Note that all of the above makes most of the plain-key functionality still avilable, without rebinding them.  I'd add a minimal set of other bindings, trying to avoid overriding existing functionality:
    - probably leave the `M-up` and `M-down` things in, since many people don't know how to transpose lines
    - use some prefixed key for "show commit" instead of enter.  It's true that there's not much use for enter, but breaking it is a major change -- a major step away from "you're just editing a file".
    - make `C-k` do what it does now when invoked at the beginning of an item line and do the usual thing when used elsewhere; *but* also remember this killed commit (or a few of them if it's used a few consecutive times), and rebind `C-y` so it pastes the killed commits when used (and actually removes the original now-commented lines).  This, again, is following normal editing sequences that people use often to transpose lines (without knowing about the commands to do that).

**Comment by tarsius** [comment]
> I just double checked it: I get no such list. All I see is git's default text.
>> That's the list I was talking about. I now have completed that list and because it now contains things like C-c C-c it is obvious that these are Emacs commands.
>>> I don't know which text you're talking about. I'm talking about the following text example:

I am still talking about the same list of commands. By "I now have completed that list" I mean "in response to this issue, I have made some change to the code which takes the list created by git and modifies it in order to inform the user about additions made by `git-commit.el`. I.e. you have to update, because I *changed* that text.

There might be a problem though: it appears that different versions of git intend differently and I am not accounting for that yet:

```diff
-# p, pick = use commit           your git
+#  p, pick = use commit          my git
```

Does your git version really not insert to spaces after the `#`? What version is that?

The instructions are supposed to look like this now:

```
# Rebase be6507a..e3c4103 onto be6507a
#
# Commands:
#  C-c C-c  tell Git to make it happen
#  C-c C-k  tell Git that you changed your mind, i.e. abort
#  p        move point to previous line
#  n        move point to next line
#  M-p      move the commit at point up
#  M-n      move the commit at point down
#  RET      show the commit at point in another buffer
#  C-/      undo last change
#  k        drop the commit at point
#  c        pick = use commit
#  r        reword = use commit, but edit the commit message
#  e        edit = use commit, but stop for amending
#  s        squash = use commit, but meld into previous commit
#  f        fixup = like "squash", but discard this commit's log message
#  x        exec = run command (the rest of the line) using shell
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```

----

> Since you've made this very clear and will not change it, please add a straightforward way to disable the whole rebase thing completely. (Ie, not post-hacking the mode alist.)

I am afraid I cannot do that (as in I don't know how to technically do it). For the benefit of the majority of users who do want to use `git-rebase.el` we do need to modify `auto-mode-alist` and to be sure that this is effective even for users who do load Magit/`git-commit.el` lazily, we have to *autoload* that even. This greatly increases the odds that users will always get the same `git-rebase-todo` experience.

So you are stuck with having to manipulate `auto-mode-alist` manually, or - and that might be more to you liking - remove the unwanted bindings from `git-rebase-mode-map` and make the buffer writable using `git-rebase-mode-hook`.

**Comment by kyleam** [comment]
> Does your git version really not insert two spaces after the #? What version is that?

I think the spacing varies across git versions.  With version 2.3.5, the output has only one space.
