### ISSUE TITLE
User mistakes should throw user-error, not error.

### ISSUE THREAD

**Issue by Malabarba** [magit/magit#1818]
Both `magit-invoke-popup-switch` and `magit-invoke-popup-option` throw
errors when the user hits a key that doesn't make sense. This frequently popus
up a backtrace if I happen to have `debug-on-error` turned on.

In cases where there's nothing wrong the code, it's preferable to a throw `user-error`:

> (user-error FORMAT &rest ARGS)  
>
> This is just like `error' except that `user-error's are expected to be the  
> result of an incorrect manipulation on the part of the user, rather than the  
> result of an actual problem.

**Comment by tarsius** [comment]
I just fixed that yesterday on a feature branch, but since that is not ready yet, I have pushed just that one commit to `next` now.

**Comment by Malabarba** [comment]
Great. Thanks a lot!
