### ISSUE TITLE
Large git log hangs emacs

### ISSUE THREAD

**Issue by j-mckitrick** [magit/magit#1819]
In the last couple of days, I've noticed that a project I work on with a rather involved and convoluted log hangs emacs.  I have to ctrl-G to get out of it, with a partial log shown on the screen.

**Comment by tarsius** [comment]
Which means it doesn't hang, it just ain't done yet. Which of course isn't great either. It's a long time goal to address that, see https://github.com/magit/magit/issues/1425.

**Comment by j-mckitrick** [comment]
@tarsius even though it's gone from a 30 second delay to over 18 minutes and still counting now in the last couple of weeks?

**Comment by tarsius** [comment]
For the most part Git is to blame, because it does something stupid when creating the graph. So disabling the graph helps a lot.

**Comment by j-mckitrick** [comment]
Perfect!  That does the trick.
