### ISSUE TITLE
status (or show commit) is very slow when having lots of changes

### ISSUE THREAD

**Issue by Silex** [magit/magit#1820]
Hello,

If you have a directory with lots of text files in it, and you move it into another directory, magit status is _very_ slow because it tries to show all the diffs by default. It's even worse if you "git add" the new directory.

The same happens when displaying such commit later on. This happens because by default all sections are expanded. It'd probably be possible to automatically collapse all sections when the number of displayed characters exceed a certain size in the buffer.

Maybe the section expansions has nothing to do with it, I need to test wether setting the option for sections to be collapsed by defaults affects the speed or not. For now I just use the command line when having to create such commits because magit-status is unusable.

**Comment by tarsius** [comment]
> Maybe the section expansions has nothing to do with it, I need to test wether setting the option for sections to be collapsed by defaults affects the speed or not.

It should. But once it has been expanded, even just moving over the again collapsed sections does re-highlight it (invisibly for the most part). That I will fix before the release.

> It'd probably be possible to automatically collapse all sections when the number of displayed characters exceed a certain size in the buffer.

You could do that using `magit-section-set-visibility-hook`.

**Comment by Silex** [comment]
Just had an idea: what about some kind of official "test" repo where we could test performance regressions? Like one with a bunch of sketchy commits for testing.

**Comment by tarsius** [comment]
> You could do that using `magit-section-set-visibility-hook`.

This and other improvements were implemented in #1830.

**Comment by Silex** [comment]
Alright, I'll test. Thanks!

**Comment by Silex** [comment]
Okay, I confirm it is better now, but still pretty slow when trying to amend/reword such giant commits.

**Comment by tarsius** [comment]
Try lowering `magit-diff-expansion-treshold`.

If that doesn't help then they delay is probably due to many files that potentially have to be reverted being open. See #1807. Note that rebasing is not one of the places where the reverting is being avoided now.
