### ISSUE TITLE
unexpected behaviour with git symlinked to a different executable

### ISSUE THREAD

**Issue by holomorph** [magit/magit#1825]
I use a wrapper for gpg-agent called envoy.  It is useful for me to have a local symlink from git to the envoy-exec executable, i.e. `~/.local/bin/git -> /usr/bin/envoy-exec`. In short, this irons out idiosyncracies with pinentry. The long of it is here:
https://github.com/vodik/envoy/issues/37#issuecomment-87529974

With this symlink in place, magit does not function. It cannot find or create git repositories. When the working directory is a git repository, `magit-status` queries for a repository (in this case, the working directory as a default) and will ask to create a git repository.

Emacs' VC also fails (and errors) with this symlink present, but I haven't been able to figure it out so far, and I can only guess that VC's behavior and magit's behavior are separate issues.

**Comment by holomorph** [comment]
For what it's worth, I know I can work around this by customizing `magit-git-executable` and `magit-git-standard-options`

**Comment by tarsius** [comment]
I am afraid you'll have to investigate this yourself.

> I can only guess that VC's behavior and magit's behavior are separate issues.

I guess the opposite.

**Comment by tarsius** [comment]
Envoy is the odd one here, not Git or Emacs. I suggest you bring this up on a stackexchange site, maybe you find someone who uses these three together and has figure out what's going on.

**Comment by holomorph** [comment]
> Envoy is the odd one here, not Git or Emacs.

I am curious how you reached this conclusion.  I won't argue against the setup being unusual, but I still don't get why Git in Emacs fails, but succeeds with the envoy wrapper in place everywhere else it gets used (e.g. the shell). In any case, thanks for the response.

**Comment by tarsius** [comment]
>> Envoy is the odd one here, not Git or Emacs.

> I am curious how you reached this conclusion. ...

Well that's just a slightly more negative way of saying what you go on to say:

> I won't argue against the setup being unusual,

:-)

**Comment by holomorph** [comment]
Haha, alright
