### ISSUE TITLE
magit fails to start from dired buffer: Key sequence * O starts with non-prefix key *

### ISSUE THREAD

**Issue by hyOzd** [magit/magit#1826]
Steps to reproduce:

1. Start Emacs
2. `M-x dired` `git/repository/folder/` `RET`
3. `M-x` `magit-status`

Magit doesn't start. Message buffer shows this error:

    Eager macro-expansion failure: (error "Key sequence * O starts with non-prefix key *")
    byte-code: Key sequence * O starts with non-prefix key *

After this failure, any magit command gives the same error until I restart emacs.

Emacs version is 24.5.1, magit version is melpa 20150424.1706.

Note: I cannot reproduce this problem on another machine with a similar emacs setup, but emacs version is 24.3.

**Comment by tarsius** [comment]
The cause for this very likely is in you setup not magit. Normally the key sequence `* 0` isn't involved in bringing up the magit status buffer at all, some third-party code that does some fiddling with input events seems to be messing up. So start with `emacs -Q`, if that works move on to commenting stuff in your init file until you find what is responsible for the error.

**Comment by hyOzd** [comment]
You are right about my .emacs file. Problem doesn't occur without it.

But I was able to get closer to source of the problem. It's triggered when magit tries to load dired-x. But it also happens when I run `(require 'dired-x)` in a fresh dired buffer. So issue seems to be unrelated to magit.

By the way I noticed running `M-:` `(magit-status)` `RET` instead M-x method gives a more detailed error message.

**Comment by hyOzd** [comment]
Aha. I found it. It's the "discover" mode. This mode will assign key `*` to a command. After that when `(require 'dired-x)` is called in a dired buffer, dired-x is trying to assign key sequence `*` `O` to some another command. But since `*` is already assigned, it cannot be used as a prefix key.

Removing "discover" mode solved the problem. It's just bad luck this is triggered when I run magit.

**Comment by apnewberry** [comment]
I also had a problem caused by `discover` bindings in `dired`, but this solved it without having to remove `discover` altogether:

```elisp
(define-key dired-mode-map (kbd "*") nil)
(define-key dired-mode-map (kbd "%") nil)
```
