### ISSUE TITLE
magit-get-top-dir: d:/cygdrive/d/Users/sva/org/ isn't an existing directory

### ISSUE THREAD

**Issue by svauban** [magit/magit#1828]
When calling `M-x magit-status` (on a Git-controlled directory, on my
Windows machine), I get:

`magit-get-top-dir: d:/cygdrive/d/Users/sva/org/ isn't an existing directory`

Any idea where to specifically look for?  Thanks...

I do have the package `cygwin-mount` installed, but I do not call
`cygwin-mount-activate` in my Emacs...

**Comment by johnmastro** [comment]
What's the result  of `M-: (buffer-file-name) RET` when visiting a file in that repository?

I think there's basically a conflict between how git refers to files there and how Emacs does. I'm not sure what the right fix is in general, but it can probably be papered over with advice.

**Comment by svauban** [comment]
"d:/Users/sva/org/notes.org" for example.

**Comment by svauban** [comment]
Eli wrote (on g.e.help): "I believe cygwin-mount does it thing via expand-file-name, so I'm
guessing some call to expand-file-name is missing somehere in magit."

Could it be so?

**Comment by tarsius** [comment]
Maybe this can be fixed by backporting 8467f15a6c9eadd8ef87b320584ab7f06c78dab9.

**Comment by tarsius** [comment]
Probably also related is #1318.

**Comment by tarsius** [comment]
See http://unix.stackexchange.com/questions/44677/how-do-i-get-rid-of-cygwins-cygdrive-prefix-in-all-paths. I think that question sums up the problem pretty well :-)

Then check whether the accepted answer fixes the issue.

**Comment by tarsius** [comment]
Also please test whether the version from the next branch works *without* using an advice or editing fstab.

**Comment by tarsius** [comment]
Closing in favor of #1318.
