### ISSUE TITLE
magit(-diff?) seems to ignore per-repository options

### ISSUE THREAD

**Issue by rrthomas** [magit/magit#1831]
I have a repository with core.autocrlf=input set. magit seems to ignore this.

I tried adding "-c" "core.autocrlf=input" to `magit-standard-options`, but that doesn't change the format of diffs either.

I'm using magit 1.4.1-6-g40f33c9. I'm sorry, I'm sure this has been dealt with somewhere, but I can't find it in the issues or the manual or the FAQ or by searching online, and I had a look at the code, but can't see why magit's git invocations would be ignoring either my per-user or per-repo configuration.

**Comment by tarsius** [comment]
I think it is Emacs which fixes the line endings so that when the process output is inserted into the buffer its line endings match what is already used in the buffer. Without this you would end up with many files ending with ^M I believe. Magit itself does not enforce any line ending style or encoding and just leaves that stuff to Emacs.

**Comment by tarsius** [comment]
Does this actually cause problems, i.e. do you end up with bogus changes showing up as diffs?

**Comment by rrthomas** [comment]
Exactly. If I run git from the command-line, the diffs are much smaller, as it catches the setting.

**Comment by tarsius** [comment]
Do you have a repository that I can clone for testing purposes?

Please also check whether `next` has this issue too.

**Comment by rrthomas** [comment]
Sorry, I don't have such a repo at present. I'll try to make something if I have a moment. Can I deduce from the fact that you want one that magit should normally respect per-user and per-repo settings? As I say, I can't find anything in the documentation about that.

**Comment by tarsius** [comment]
> Can I deduce from the fact that you want one that magit should normally respect per-user and per-repo settings?

Yes. There are a few exceptions where we explicitly override a potential setting because it is known that respecting the user configuration would break magit.

**Comment by rrthomas** [comment]
In trying to make such a repo, I found that my diagnosis is wrong. The problem is that I need `--ignore-space-at-eol` as an argument to `git log`. I had this as an alias in my per-repo config. However, I still can't see how to get this into `magit-diff-options`!

**Comment by tarsius** [comment]
Closing in favor of #1782.
