### ISSUE TITLE
slow staging after fixing up a conflict during git interactive rebase.

### ISSUE THREAD

**Issue by kvaneesh** [magit/magit#1832]
I see that we run the below command and it takes a lot of time on large repo. I have both auto-revert and backup-mode nil
(setq magit-auto-revert-mode nil))
(setq magit-backup-mode nil)

/usr/bin/git --no-pager --literal-pathspecs -c core.preloadindex=true update-index --add --remove --

**Comment by tarsius** [comment]
`magit-backup-mode` is known to be slow and there is nothing that can be done about it. In a later release there will be a more performant implementation which doesn't use stashes but to independent refs.

For `magit-auto-revert-mode` see #1807.

**Comment by kvaneesh** [comment]
But i have disabled both, as shown in the issue. Are you suggesting that even after 

(setq magit-auto-revert-mode nil))
(setq magit-backup-mode nil)

Some part of magit will run backup mode ?

-aneesh

**Comment by kvaneesh** [comment]
What slowed the command was the staging was running update-index with all the files which i haven't even touched. May be diff -z --name-only got the file list wrong ?

**Comment by tarsius** [comment]
Meeep. Sorry I did not read that properly. Reopening.

**Comment by tarsius** [comment]
Still I don't understand why this would be slow only during interactive rebase but not otherwise.

It's a shot in the dark, but maybe you don't have good ignore rules setup? https://github.com/magit/magit/wiki/FAQ#what-can-i-do-about-poor-performance (That entry is out-of-date but still has some useful hints).

**Comment by tarsius** [comment]
Do you visit dozens of files from the same repository and *then* do a rebase?

**Comment by kvaneesh** [comment]
yes. I work on Linux kernel. But then i didn't touch all those files that got added to the git update-index command line. I will try to reproduce this again and add more information as i find them. My plan is to see if git diff -z --name-only got the file list wrong after running any command.

**Comment by tarsius** [comment]
Please see #1807 and #1820 - am pretty sure that the two issues together cover the delay you see.
