### ISSUE TITLE
git interactive rebase squash doesn't work after a conflict.

### ISSUE THREAD

**Issue by kvaneesh** [magit/magit#1833]
It opens the editor asking to merge the commit message. But we really ends up with two commits. Something like below
07f85d470ce78c4a3c82db05 powerpc/thp: Remove _PAGE_SPLITTING and related code
cfe377f4159e98f620d15fd09 powerpc/thp: Remove _PAGE_SPLITTING and related code

**Comment by tarsius** [comment]
You have to be more specific. I don't what "after" means here. Steps to reproduce would help.

**Comment by kvaneesh** [comment]
I tried to reproduce this again. I can't. So will close this for now. May be i messed up because auto-revert was nil for me and that plays strangely while rebasing. 

-aneesh
