### ISSUE TITLE
1.4.1 contains references to removed 'git-commit-mode'

### ISSUE THREAD

**Issue by dunn** [magit/magit#1834]
Trying to update the Homebrew formula for magit, and I run into this error when doing `make install`:

```
==> make install PREFIX=/usr/local/Cellar/magit/1.4.1

In toplevel form:
magit-key-mode.el:34:1:Error: Cannot open load file: no such file or directory, git-commit-mode

In toplevel form:
magit-blame.el:36:1:Error: Cannot open load file: no such file or directory, git-commit-mode

In toplevel form:
magit.el:68:1:Error: Cannot open load file: no such file or directory, git-commit-mode

In toplevel form:
magit-wip.el:48:1:Error: Cannot open load file: no such file or directory, git-commit-mode
```

([Full logs with configuration info](https://gist.github.com/dunn/327d86ced7b9b4e7b4ee))

The readme says that `git-commit-mode.el` and `git-rebase-mode.el` are now `git-commit.el` and `git-rebase.el`, and that's true in the `next` branch, but not on `master`, nor at the `1.4.1` tag.  There, `magit.el` [still looks for `git-commit-mode` and `git-rebase-mode`](https://github.com/magit/magit/blob/master/magit.el#L68-L69), neither of which exist [in the tree](https://github.com/magit/magit/tree/master).

**Comment by johnmastro** [comment]
You can download them from [the master branch of the git-modes repo](https://github.com/magit/git-modes/tree/master). 

They used to be distributed separately from Magit, whereas on the `next` branch they've essentially been incorporated.

**Comment by dunn** [comment]
Oh, got it. Thanks!

**Comment by tarsius** [comment]
Could you please inform the homebrew team  that they need to add this dependency.

**Comment by dunn** [comment]
On it: Homebrew/homebrew#39266
