### ISSUE TITLE
Duplicate overlays in commit headers

### ISSUE THREAD

**Issue by simenheg** [magit/magit#1836]
When looking at a commit that includes changes to binary files, the diff header that follows those files receives duplicate overlays of types `magit-diff-hunk-header` and `magit-diff-file-header`.

For instance, when looking at the following commit:

```diff
5 files changed, 2 insertions(+)
 a.jpg     | Bin 5068963 -> 0 bytes
 b.jpg     | Bin 5073092 -> 0 bytes
 c.jpg     | Bin 4118723 -> 0 bytes
 text.txt  |   1 +
 text2.txt |   1 +

	Deleted    a.jpg
diff --git a/a.jpg b/a.jpg
deleted file mode 100755
index 2cbe709..0000000
Binary files a/a.jpg and /dev/null differ
	Deleted    b.jpg
diff --git a/b.jpg b/b.jpg
deleted file mode 100755
index 7269416..0000000
Binary files a/b.jpg and /dev/null differ
	Deleted    c.jpg
diff --git a/c.jpg b/c.jpg
deleted file mode 100755
index e37ee1b..0000000
Binary files a/c.jpg and /dev/null differ
	Modified   text.txt
diff --git a/text.txt b/text.txt
index 3e71550..b66a20f 100644
--- a/text.txt
+++ b/text.txt
@@ -1 +1,2 @@
 Some text.
+Changed.
	New        text2.txt
diff --git a/text2.txt b/text2.txt
new file mode 100644
index 0000000..202e967
--- /dev/null
+++ b/text2.txt
@@ -0,0 +1 @@
+Some more text.
```

The header for `text.txt` now receives extra overlays of types `magit-diff-hunk-header` and `magit-diff-file-header` equal to the number of binary files changed. Inspecting the header with `describe-char` reveals the following:

```
There are 9 overlays here:
 From 775 to 925
  face                 magit-item-highlight
 From 859 to 889
  evaporate            t
  face                 magit-diff-hunk-header
 From 859 to 889
  evaporate            t
  face                 magit-diff-hunk-header
 From 859 to 889
  evaporate            t
  face                 magit-diff-hunk-header
 From 859 to 889
  evaporate            t
  face                 magit-diff-hunk-header
 From 863 to 873
  evaporate            t
  face                 magit-diff-file-header
 From 863 to 873
  evaporate            t
  face                 magit-diff-file-header
 From 863 to 873
  evaporate            t
  face                 magit-diff-file-header
 From 863 to 873
  evaporate            t
  face                 magit-diff-file-header
```

This becomes evident when using a theme that scales the size of `magit-diff-file-header`, as it will be applied multiple times, and the size blows up proportionally to the number of changed binary files.

**Comment by tarsius** [comment]
Please update to the `next` branch. This must be a very old bug and so far it didn't bother anyone (though it might in part be responsible for the performance issues - so everyone was affected I guess). Anyway I haven't looked at that code in a long time - on `next` there is a new and shiny implementation.

Also see  #1645.
