### ISSUE TITLE
magit 1.4.1, emacs 24.5.1: magit-status fails with `cl-struct-define` undefined error.

### ISSUE THREAD

**Issue by timvisher** [magit/magit#1838]
Here's the full error:

```
Symbol's function definition is void: cl-struct-define
```

And at byte compile time:

```

Compiling file /Users/tvisher/.emacs.d/elpa/magit-1.4.1/magit.el at Tue May  5 11:43:42 2015
magit.el:7831:1:Error: Symbol's function definition is void: cl-struct-define

Compiling no file at Tue May  5 11:43:50 2015

Compiling file /Users/tvisher/.emacs.d/elpa/magit-1.4.1/magit-key-mode.el at Tue May  5 11:45:46 2015
magit-key-mode.el:34:1:Error: Symbol's function definition is void: cl-struct-define

Compiling no file at Tue May  5 11:45:50 2015

Compiling file /Users/tvisher/.emacs.d/elpa/magit-1.4.1/magit.el at Tue May  5 11:47:37 2015

In magit-builtin-completing-read:
magit.el:1801:8:Warning: function magit-builtin-completing-read used to take
    0+ arguments, now takes 2-7
magit.el:7831:1:Error: Symbol's function definition is void: cl-struct-define
```

I can't find a reference to `cl-struct-define` in magit though… At least not in the elpa dir.

Thoughts?

**Comment by tarsius** [comment]
Check whether you have installed `cl-lib` as a package from GNU Elpa. When using an Emacsen which has that library included, then still having the backward compatibility package installed separately causes such errors.

**Comment by tarsius** [comment]
I am closing because it is very unlikely this has anything to do with magit. Shouldn't keep you from commenting here though.

**Comment by timvisher** [comment]
@tarsius `cl-lib` isn't in my `elpa` and `M-x find-library RET cl-lib RET` returns `/usr/local/Cellar/emacs/24.5/share/emacs/24.5/lisp/emacs-lisp/cl-lib.el.gz`

**Comment by tarsius** [comment]
Apparently `cl-struct-define` hasn't made it into an Emacs release yet. Maybe you have a package installed which assumes you use the development version. Grep all your third-party packages for that symbol. Magit does not use it, but maybe loading it triggers that other package to be loaded too.

**Comment by timvisher** [comment]
```
-*- mode: ag; default-directory: "~/.emacs.d/" -*-
Ag started at Tue May  5 21:11:08

ag --nocolor --literal --line-number --smart-case --nogroup --column -u -- cl-struct-define .
Binary file elpa/magit-1.4.1/magit.elc matches.

Ag finished at Tue May  5 21:11:08
```

**Comment by timvisher** [comment]
```
(byte-code "\300\301\302\303#\210\304\305\306\307\306\211\310\311\312\303&  \207" [function-put make-magit-sectio\
n side-effect-free t cl-struct-define magit-section nil cl-structure-object ((cl-tag-slot) (type) (info) (beginni\
ng) (content-beginning) (end) (hidden) (needs-refresh-on-show) (highlight) (diff-status) (diff-file2) (diff-range\
) (process) (parent) (children)) cl-struct-magit-section-tags cl-struct-magit-section] 10)
```

**Comment by timvisher** [comment]
So i have no idea what happened but blowing that `elc` file way and recompiling it seems to have solved this issue for me. \( ﾟ◡ﾟ)/

Thanks as always!

**Comment by jasonm23** [comment]
@timvisher Perhaps it was because the elc was compiled on a different/later emacs version than it's being run on when causing the err?

**Comment by timvisher** [comment]
@jasonm23 Perhaps. I'm not sure how that would have happened though. I don't have any later versions of emacs.

**Comment by jasonm23** [comment]
Is it possible that the elc was not compiled on your machine?

It's difficult to see how Emacs would include a function call that it doesn't know about.

**Comment by timvisher** [comment]
I guess? I wouldn't think so though.

**Comment by decoursin** [comment]
I had this same issue, which for me was that the elc was compiled by a different version. This helped me very much and thank you for that!

**Comment by offby1** [comment]
What @decoursin said.  I switch between emacs 25 and emacs 24 a lot, and have found that .elc files created by emacs 25 will sometimes cause this problem under emacs 24.

**Comment by wolfgangwayland7** [comment]
THANKS-> tarsius commented on May 5, 2015
For some dumb reason my newly compiled emacs24.5 [linux mint17.4] puked out  "can't find a reference to cl-struct-define".
I installed the  cl-lib-0.5 along with the present cl-lib-1.0 but I put in (add-to-list 'load-path "/root/.emacs.d/elpa/cl-lib-0.5") in my .emacs and it worked... who knew . 
This will come back to bite me latter,  some how.
