### ISSUE TITLE
magit over tramp locks up for 60 seconds or more and then fails

### ISSUE THREAD

**Issue by timvisher** [magit/magit#1840]
I think I've pinned this down to magit. All my other packages with tramp support (dired, etc.) all seem to be working fine.

Whenever execute a command like `push` or `pull`, something like the following shows up in the magit-process buffer

```
git --no-pager -c core.preloadindex=true pull



are you awake
#$
```

And I get the following in the mini-buffer:

```
Opening connection for core using scp... \
```

And then after about 60 seconds, 

```
Tramp: Opening connection for core using scp...done
```

Messages has

```
Running git pull
Tramp: Opening connection for core using scp...
Tramp: Sending command `exec ssh -q   -o ControlMaster=auto -o ControlPath='tramp.%r@%h:%p' -o ControlPersist=no \
-e none core'
Tramp: Opening connection for core using scp...
Tramp: Sending command `exec ssh -q   -o ControlMaster=auto -o ControlPath='tramp.%r@%h:%p' -o ControlPersist=no \
-e none core'
Tramp: Waiting for prompts from remote shell...
Timeout reached, see buffer `*tramp/scp core*' for details
Tramp: Waiting for prompts from remote shell...failed
Tramp: Opening connection for core using scp...failed [2 times]
byte-code: Can't send string to remote host -- not logged in
Tramp: Opening connection for core using scp...
Tramp: Sending command `exec ssh   -o ControlMaster=auto -o ControlPath='tramp.%r@%h:%p' -o ControlPersist=no -e \
none core'
Tramp: Waiting for prompts from remote shell...done
Tramp: Found remote shell prompt on `core'
Tramp: Opening connection for core using scp...done
```

**Comment by timvisher** [comment]
It's definitely strange that this has worked before for me though. I'm not sure what could be happening that would make the way magit is connecting to the box fail in this way, nor what could allow the other packages i'm using to work fine.

**Comment by timvisher** [comment]
Also, magit-status seems to work fine.

**Comment by timvisher** [comment]
Actually, I just noticed this issue with `ag.el` as well.

**Comment by timvisher** [comment]
There's no slowness on the command line with eg `ssh -t core charnock` so I'm assuming bugginess in tramp. I'm bumping from emacs 24.5 to HEAD to see if that helps. I'll close this issue but if you have any ideas and time enough to share them do let me know. :)

**Comment by timvisher** [comment]
hmm… bumping to `HEAD` did nothing… :(

**Comment by timvisher** [comment]
magit is definitely the most consistent experiencer of this issue though… `ag` works most of the time.

**Comment by Silex** [comment]
@timvisher: are you using `projectile`? this sounds typically like https://github.com/bbatsov/projectile/issues/523

**Comment by timvisher** [comment]
I am using projectile. i'll see if i can disable that. wouldn't loose too much i don't think while it gets worked out.

**Comment by Silex** [comment]
Just use `(setq projectile-mode-line " Projectile")` as a workaround until projectile fixes it.

**Comment by timvisher** [comment]
@Silex You're a life saver! :)

**Comment by Silex** [comment]
You're welcome :wink:
