### ISSUE TITLE
Magit on windows doesnt work with cygwin git + console emacs in a cygwin shell

### ISSUE THREAD

**Issue by pete-lee** [magit/magit#1841]
It seems code was added to address this issue:

Magit on windows no longer works with Cygwin Git #1318

```
(defun magit-expand-git-file-name (filename &optional localname)
  (setq filename
        (if (file-name-absolute-p filename)
            (if localname
                filename
              (concat (file-remote-p default-directory) filename))
          (expand-file-name
           filename
           (and localname (file-remote-p default-directory 'localname)))))
  **(if (and (memq system-type '(cygwin windows-nt)) ; #1318**
           **(string-match "^/\\(cygdrive/\\)?\\([a-z]\\)/\\(.*\\)" filename))**
      **(concat (match-string 2 filename) ":/"**
              **(match-string 3 filename))**
    **filename)**
  )
```

I run console emacs within cygwin and the conversion from /cygdrive/ to :/ breaks magit-status.

Commenting out that fix works for me.

If system-type is 'cygwin... then I dont think you want to run that code... I believe it should be constrained to windows-nt.  It makes sense to do if running non-cygwin emacs + cygwin git... it doesn't make sense for console emacs in a cygwin shell + cygwin git.

**Comment by tarsius** [comment]
Could you please post that on #1318 to keep the discussion in one place. Thanks.
