### ISSUE TITLE
hunk highlighting without 'magit-section-highlight

### ISSUE THREAD

**Issue by holomorph** [magit/magit#1842]
Some recent changes affecting how hunks are highlighted have introduced what seems to be broken behavior with the following: 
```elisp
(remove-hook 'magit-section-highlight-hook 'magit-section-highlight)
```
Sections are initially being highlighted when they shouldn't ever be. This can be seen in a repository where a file (modified or staged, for instance) has multiple hunks

 After doing `magit-status` and hitting `TAB` on a file to expand and see the diff, hunks other than the first use the "highlight" faces. Subsequent actions make these faces go away.
![expanding diff](https://i.imgur.com/uiwFreh.png) (point is on the m in modified)
![subsequent action](https://i.imgur.com/7pYCyl2.png) (after hitting `p`, point is on the S in Staged)
It need not be `p`: alternatively, I can `TAB` twice to collapse and expand the diff, and the highlight faces go away.  Now that I look at the screenshots back and forth, I notice the modeline indicates the buffer is modified when the "highlight" faces occur; then after doing something to make them go away, the indicator returns to `%%`

**Comment by tarsius** [comment]
So you want to disable highlighting of the current section completely, do I understand that right?

If so you should also remove `magit-diff-highlight`.

But it is quite likely that after doing it still doesn't work as expected. I didn't take this into account when I made some recent changes.

Could you please also post a screenshot of what it is supposed to look like. While I have used zenburn too in the past, this doesn't look like zenburn to me. By the way you might want to give my (temporary) fork a try.

**Comment by holomorph** [comment]
The second screenshot is what it's always supposed to look like. Sorry, I should have disabled the theme and left it vanilla.  It's the zenburn port I wrote.

**Comment by holomorph** [comment]
Removing `magit-diff-highlight` didn't change the behavior.

**Comment by holomorph** [comment]
Updated screens, same recipe, same order as above:
![expanded diff](https://i.imgur.com/LOxbWx7.png)

![subsequent action](https://i.imgur.com/u2PEvq5.png)

**Comment by tarsius** [comment]
Ah yes, I noticed that too. I don't think it has anything to do with disabling highlighting - it gets wrongfully highlighted even when highlighting should happen (but not here and now).

I'll investigate soon.

**Comment by tarsius** [comment]
I think this only ever happens if the buffer ends with a hunk. Which is quite strange.

**Comment by tarsius** [comment]
This commit fixes the common sure.

I am not quite sure whether and if so to what extend you want to turn of highlighting of the current section but these are the options:

* If you only don't want to highlight hunk bodies (makes theming easier, gives a slight performance boost), then set `magit-diff-highlight-hunk-body` to nil.
* If you don't want any highlighting then remove `magit-diff-highlight` and `magit-section-highlight` from `magit-section-highlight-hook`.
* You may also remove only the diff variant from the hook, which causes diff related sections to be highlighted using the common highlighter. This means that hunk bodies lose background colors when they are highlighted. If that doesn't matter because they don't have a background color, then this gives a slight performance boost.

**Comment by holomorph** [comment]
Thanks for looking at this.  I haven't yet read your changes, but here is what I see having just pulled:

> If you only don't want to highlight hunk bodies (makes theming easier, gives a slight performance boost), then set `magit-diff-highlight-hunk-body` to nil.

In this case (setting this option/hook and no other), the diff's first appearance is different from its subsequent appearance by collapsing and expanding it.

> If you don't want any highlighting then remove `magit-diff-highlight` and `magit-section-highlight` from `magit-section-highlight-hook`.

Removing only `magit-section-highlight`, all hunks in a file other than the first will be highlighted the first time, then subsequently (after movement or collapse/expand) will not be highlighted.  The presence of `magit-diff-highlight` doesn't, by inspection, appear to have an effect. The behavior appears to be the same with only the `magit-diff-highlight` removed.

**Comment by tarsius** [comment]
Okay that too should work now.

**Comment by holomorph** [comment]
Thanks, first thing fixed.

> Removing only magit-section-highlight, all hunks in a file other than the first will be highlighted the first time, then subsequently (after movement or collapse/expand) will not be highlighted. 

However, this still happens

**Comment by tarsius** [comment]
Hm, that doesn't appear to happen for me.

**Comment by holomorph** [comment]
Oh boy, weird.  I'll try to be very specific in case it's something else going on.

On `Magit 1.4.1-2169-g37ea5aa, Git 2.4.0, Emacs 25.0.50.2` and `GNU Emacs 25.0.50.2 (x86_64-unknown-linux-gnu, X toolkit, Xaw scroll bars) of 2015-05-06 on logos`, from `emacs -Q` I did
```elisp
(add-to-list 'load-path "~/.emacs.d/site-lisp/magit")
(add-to-list 'load-path "~/.emacs.d/site-lisp/dash")
(remove-hook 'magit-section-highlight-hook 'magit-section-highlight)
(require 'magit)
```
then `C-u M-x magit-status` and picked a repo. The repo had one modified file with three hunks, and expanding it the first time the highlighting was wrong.  I didn't have magit or dash byte compiled.
