### ISSUE TITLE
emacs-24.5 breaks magit-revert-buffers

### ISSUE THREAD

**Issue by robohack** [magit/magit#1844]
`magit-revert-buffers` stopped working for me when I upgraded to 24.5.

The original code looks broken to me (I don't understand why `let` was used instead of `progn`), but it used to work up until I upgraded to 24.5.

The following change fixes the problem for me:

```diff
diff -u /Users/gaw/.emacs.d/elpa/magit-1.4.1/magit.el\~ /Users/gaw/.emacs.d/elpa/magit-1.4.1/magit.el
--- /Users/gaw/.emacs.d/elpa/magit-1.4.1/magit.el~	2015-05-09 12:37:36.000000000 -0700
+++ /Users/gaw/.emacs.d/elpa/magit-1.4.1/magit.el	2015-05-09 13:04:57.000000000 -0700
@@ -4065,7 +4065,8 @@
               (and file (string-prefix-p topdir file)
                    (not (string-prefix-p gitdir file))
                    (member (file-relative-name file topdir) tracked)
-                   (let ((auto-revert-mode t))
+                   (progn
+                     (auto-revert-mode t)
                      (auto-revert-handler)
                      (run-hooks 'magit-revert-buffer-hook))))))))))
 
```

**Comment by tarsius** [comment]
See #1821.

**Comment by tarsius** [comment]
Ah wait, 24.5.

**Comment by tarsius** [comment]
Let-binding a mode variable (to trick some code into believing it is on) isn't the same permanently enabling the mode.

This doesn't work anymore with the development version, nor with the 24.5 release it seems.

**Comment by robohack** [comment]
Ah, now I think I understand -- I was confused between the function name and the variable name, and perhaps edebug was as well as it appeared that neither the binding nor the call were being made when I stepped through the execution.

So, my fix is probably not correct  as I think it will enable `auto-revert-mode` in each buffer unconditionally.

The problem must be that `auto-revert-handler` isn't working quite the same as it did in 24.4.

**Comment by tarsius** [comment]
Should be fixed now.
