### ISSUE TITLE
Keep 'r c' as a binding for continuing a rebase

### ISSUE THREAD

**Issue by jwiegley** [magit/magit#1850]
I like the idea that `r r` is used for rebasing, but I keep tripping up on the fact that `r c` is no longer the obvious keybinding for "rebase continue", but that `r r` has been overloaded for this task.  I would like to see `r c` return as the binding for continue, as this seems to be more consistent, and makes the meaning of `r r` not modally dependent.

**Comment by tarsius** [comment]
I'll think about it.

**Comment by tarsius** [comment]
`r r` always does the thing the user most likely wants. It starts the most common rebase type, or if a rebase is already in progress it continues that rebase. Seems very dwimy to me. Your muscle memory tells you otherwise but I am sure you'll get the hang of it.

I don't intend to revert this.

**Comment by jwiegley** [comment]
I really don't like DWIMy behavior, *especially* not where commit surgery is involved; but I can add a binding for `r c` myself, thanks.
