### ISSUE TITLE
"fatal: patch with only garbage at line 3" when killing a hunk on a chmoded file

### ISSUE THREAD

**Issue by whirm** [magit/magit#1852]
If I modify a file's permissions and its contents,  the resulting change shown in magit will trigger that git error when calling ```magit-discard``` on it.

**Comment by tarsius** [comment]
What versions of the involved tools are you using?

**Comment by whirm** [comment]
Sorry:
  - Magit 90150116-1958-gdfcdea9
  - Git 2.1.4
  - Emacs 24.4.1

**Comment by whirm** [comment]
I've just tried with current ```next``` and it also fails.

I also noticed that you need more than one hunk on that file and you need to kill one of them. Not the whole thing.

**Comment by tarsius** [comment]
The `901*****` tags were a bad idea of mine. Could you please prune the old tags as described in the second answer to http://stackoverflow.com/questions/1841341/remove-local-tags-that-are-no-longer-on-the-remote-repository and then report the version again.

Sounds like you are using the `master` branch, but I am not sure.

**Comment by whirm** [comment]
heh :) right now I'm at bbe2d07017debebf220be4b098b219b97c37a1d5, current ```next```'s head

**Comment by tarsius** [comment]
Just pushed the fix to `next`.

**Comment by whirm** [comment]
Works great now, thanks! :)
