### ISSUE TITLE
Split a hunk into smaller hunks

### ISSUE THREAD

**Issue by tuhdo** [magit/magit#1853]
Since we can already do this with `C-c C-s` (diff-split-hunk) in a `diff-mode` buffer, couuld it be reused for `magit`?

**Comment by tarsius** [comment]
No, we use diffs exactly as given to use by Git.

However you can use `git diff -U{N}` for a similar effect. From the popup use `-u`, or `+` and `-` in a buffer that contains diffs.

**Comment by tuhdo** [comment]
Yes `magit-status` uses diffs exactly as given by Git. I mean a user should be able to split a hunk into smaller hunks when needed, similar to how you can do it in `vc-diff`. For example, run `vc-diff` and then select part of a hunk, `C-c C-s` to split.

**Comment by tarsius** [comment]
And Magit provides something way better than that. Use the region Luke :-)

When there is a hunk-internal region, then the various apply variants (stage...) only operate on the lines in the region. On the `next` branch that is even visualized nicely.

**Comment by johnmastro** [comment]
Try `+` and `-` in a Magit diff buffer and see if they do what you have in mind. I think they're what you're looking for (they tell git to adjust the hunk sizes) but I may be misunderstanding.

**Comment by tuhdo** [comment]
I know I can select a region inside a hunk and press `s` to stage it. But as soon as I do that the second time for the same hunk and press `s`, it merges the two smaller hunks I split into one hunk in the stage area.

**Comment by tarsius** [comment]
```
-U<n>, --unified=<n>
           Generate diffs with <n> lines of context instead of the usual
           three. Implies -p.
```

Did you actually try that as suggested? Of course if there is no context between the changes, then that doesn't work. (But you can go as low as zero context lines (but then won't be apply to apply the hunks anymore, so in reality one context line is required).

Also why is it a problem if "hunks are merged"? You can just use the region again to operate on just one part of the hunk.

If that doesn't help, then maybe two screenshots might help.

**Comment by tuhdo** [comment]
Yes I tried that. What I meant by smaller hunk is that I want a big hunk to have smaller hunks with its own indexes. I know about stage region and press `s` but I wanted to have many small hunks in a stage area. Then I realized that if I do that then basically everything is committed and it should be merged into one hunk. My bad then. But good to know about `+` and `-` anyway, though not related.

**Comment by tarsius** [comment]
> I want a big hunk to have smaller hunks with its own indexes

A hunk cannot "have hunks" it just is. It also cannot have an index - there is but one index, and in a sense hunks can be "inside the index", but not the other way around. In other words I don't understand what you are talking about. You'll have copy the relevant part of a Magit buffer, post it, and then also post a modified copy which demonstrates what you are after.

**Comment by tuhdo** [comment]
It's just the same thing as `C-c C-s` in `ediff` i.e. you split a hunk into smaller hunks and create a new patch.
