### ISSUE TITLE
Large number of gitignored files slows down magit

### ISSUE THREAD

**Issue by ef4** [magit/magit#1854]
Running master branch, I've noticed that several magit-mode operations got much slower for certain repos. I suspect that the slowdown is related to having a repo with a large number of gitignored files. 

For example, in a fairly typical node project, you will have `/node_modules` in `.gitignore`, and that directory will be a fairly deep tree with many files. In a project like that, operations like `magit-discard` are taking over six seconds. If I delete the ignored directory, magit runs fast again.

My guess is that magit is doing some operation for every untracked file, without pruning the tree based on gitignore.

**Comment by tarsius** [comment]
Actually if the directory is being ignored then it should not matter how many files are in it. Are you sure the files are not being ignored based on file extensions?

**Comment by tarsius** [comment]
And the obligatory link to the faq: https://github.com/magit/magit/wiki/FAQ#what-can-i-do-about-poor-performance.

Does that help? If not then please provide more information so that we can narrow it down.

**Comment by ef4** [comment]
I drilled down deeper. `magit-file-status` is doing `git status -u --ignored`, which is apparently quite expensive in a repo with a huge ignored subtree. And it returns a giant list of files to magit.

**Comment by ef4** [comment]
If we can drop the `--ignored` the operation will be orders of magnitude faster.

**Comment by tarsius** [comment]
That's useful information.

Indeed we don't need to know about untracked files here.

That could make quite a difference for some people. Thanks!

**Comment by ef4** [comment]
Nice, the speedup is very noticeable.
