### ISSUE TITLE
buffer-stale--default-function used instead of buffer-stale-function

### ISSUE THREAD

**Issue by thierryvolpiatto** [magit/magit#1857]
I guess it is just a typo error, you use `(funcall buffer-stale--default-function)` instead of
`(funcall buffer-stale-function)` which cause an error.

**Comment by tarsius** [comment]
It's just for file visiting buffers - so the "typo" was the `funcall ` part.

**Comment by art-solopov** [comment]
I'm not sure if it's connected in any way, but here's an error I get almost every time I have a modified and saved buffer when committing/pushing:
```
Running git push -v origin master:refs/heads/master --force
Git finished
error in process sentinel: magit-revert-buffers: Symbol's function definition is void: buffer-stale--default-function
error in process sentinel: Symbol's function definition is void: buffer-stale--default-function
```
The only thing that mentions `buffer-stale--default-function` in my .emacs.d is magit.

**Comment by art-solopov** [comment]
I see, thanks! Will try to update my Emacs then.

21.05.2015 19:49, Noam Postavsky пишет:
