### ISSUE TITLE
`make lisp` produces invalid autoloads file

### ISSUE THREAD

**Issue by Malabarba** [magit/magit#1859]
To install the next branch, I ran `make lisp` in the repo directory as instructed in the readme.
This generated an invalid autoloads file.

All of the autoloads pointed to the files like `"../../../../.emacs.d/packages/magit/magit-extras"` which is one level too deep. Changing all of them to things like `"magit-extras"` was enough to fix it.
This happened even though I ran the make command inside the `magit` directory

**Comment by npostavs** [comment]
Are there any symlinks involved?

**Comment by Malabarba** [comment]
Yes, the `.emacs.d` is a symlink to `~/Otherdir/emacs.d`.

**Comment by npostavs** [comment]
Maybe it would work if you ran it from the non symlink location (but make sure you delete the bad one first)?

**Comment by Malabarba** [comment]
Yes, that does generate a valid file. Thanks for the suggestion.

**Comment by tarsius** [comment]
That should fix it.

**Comment by tarsius** [comment]
It might be worth fixing this in Emacs itself too. It wouldn't surprise me if `package.el` had problems to when `~/.emacs.d` is a symlink.

**Comment by Malabarba** [comment]
My `.emacs.d` (and my `elpa/` by extension) has always been inside a symlink and it never caused me any problems with `package.el` and looking at this part of the code I don't see any mentions of truename. All it does is call `update-directory-autoloads` with the package's directory.

But then, I see your setup is a bit more complicated because of `make`, so maybe that's not enough for your case.
