### ISSUE TITLE
Support jump from “-” diff line to the commit that created the line

### ISSUE THREAD

**Issue by brandon-rhodes** [magit/magit#1860]
I love the convenience of `magit-blame-mode` followed by `l` to see the comment and diff for the commit. But I often want to step backwards from there to see what previous commit was responsible for one of the lines being replaced. For example, when I am trying to figure out who added an import of `walk` and run `magit-blame-mode`, the diff often shows me:

```
-    from os import walk
+    from os import stat, walk
```

That is, the most recent change touching this line was unrelated to my question — `walk` was already there when the last change took place.

What I would love to be able to do is to move point to the `-` line, the line that was taken away by that most recent change, and be warped back to whichever *previous* change put the `from os import walk` line there in the first place.

Is there a magit command I have missed that, when run with point on a `-` line, already understands that the line was produced by some previous commit that it could jump back and visit in the log? Thanks!

**Comment by npostavs** [comment]
> the line was produced by some previous commit that it could jump back and visit in the log?

I don't think this information is directly available to git, you have to run `git blame` again to discover which previous commit it was. The `magit-blame` command (`b b` from the original blaming buffer) does this:
```
magit-blame is an interactive compiled Lisp function in `magit-blame.el'.
...
If Magit-Blame mode is already turned on then blame recursively, by
visiting REVISION:FILE (using `magit-find-file'), where revision
is the revision before the revision that added the lines at
point.
```

**Comment by tarsius** [comment]
Closing in favor of #1566 where I group such requests until I am ready to tackle this problem domain.
