### ISSUE TITLE
magit-rebase-from is confusing

### ISSUE THREAD

**Issue by Silex** [magit/magit#1862]
Hello,

I'm sorry because I know you meant to do good but `magit-rebase-from` is still confusing because no matter how you twist it, it is "incomplete". I mean `magit-rebase-onto` lacks the "from" part and `magit-rebase-from` lacks the "to" part. I think the semantic we want is `(magit-rebase-commits first-commit-in-range last-commit-in-range position-where-to-apply-range)`.

Based on the discussion at https://github.com/magit/magit/commit/88fa789b190bb1259d245c5d509e697caa658906, I propose the following changes:

- The popup says "Rebase to different place" (or maybe "Rebase commits"? "onto"?)
- The function that does rebase asks the following interactive questions:
  - "First commit to rebase? (default cursor position)" 
  - "last commit to rebase? (default HEAD or branch tip)"
  - "Where to rebase these commits? (no default but refs autocompletion)"

What do you think?

**Comment by tarsius** [comment]
> I mean `magit-rebase-onto` lacks the "from" part and `magit-rebase-from` lacks the "to" part.

Isn't that implied because every rebase moves commits [on]to something?

> What do you think?

I am willing to change strings, but I don't want to change the order in which the user provides information and the interface used to get it from her.

> "last commit to rebase? (default HEAD or branch tip)"

This doesn't make sense. The last commit *always* is HEAD.

**Comment by Silex** [comment]
>> I mean magit-rebase-onto lacks the "from" part and magit-rebase-from lacks the "to" part.

> Isn't that implied because every rebase moves commits [on]to something?

Hum... yes.
 
>> What do you think?

> I am willing to change strings, but I don't want to change the order in which the user provides information and the interface used to get it from her.

Alright.

>> "last commit to rebase? (default HEAD or branch tip)"

> This doesn't make sense. The last commit always is HEAD.

Right, I got under the impression that you could specify *any* ref but apprently you can only specify a branch name.

Anyway, I see that you renamed it to "rebase subset". This is much clearer and works for me!

Thanks.
