### ISSUE TITLE
For staging/unstaging all, the behavior of S/U should be consistent

### ISSUE THREAD

**Issue by jwiegley** [magit/magit#1864]
I miss being able to just type "U" and unstage all files, the direct opposite of what "S" stage does.  Now I'm prompted for a ref, and I'm sometimes not 100% sure which ref to specify.  I liked the old magit that never asked.  What does it even mean to upstage wrt to a ref other than whatever my index is based on?

**Comment by npostavs** [comment]
> What does it even mean to upstage wrt to a ref other than whatever my index is based on?

`U` isn't bound to unstage anymore, it's `magit-reset-index`

```
Reset the index to COMMIT.
Keep the head and working tree as-is, so if COMMIT refers to the
head this effectivley unstages all changes.
```

**Comment by Silex** [comment]
@jwiegley: soft reset is what you use to "undo commit/staging" while still keeping the changes in your worktree.

Personally I much prefer the current behavior, and most of the time I just type <kbd>U ret</kbd> because the proposed ref is the correct one.

If you are unsure, simply always select "HEAD" and you get the old `U` behavior.

**Comment by Silex** [comment]
Maybe a good idea would to propose HEAD as a list of possible completions instead of having to type it?

**Comment by tarsius** [comment]
> Maybe a good idea would to propose HEAD as a list of possible completions instead of having to type it?

I have done that, now `RET` always resets the index to HEAD, i.e. does "unstage everything".

As explained in #1858, that is a form of confirming a dangerous operation, with the added possibility to act on something other than the default.

**Comment by tarsius** [comment]
On the other hand it would be desirable if staging and unstaging were symmetric. I have restored `magit-unstage-all` but you'll have to bind it yourself:

    (define-key magit-mode-map "U" 'magit-unstage-all)

**Comment by jwiegley** [comment]
@tarsius Thank you!
