### ISSUE TITLE
Staging/unstaging/diffing on the status screen are slow

### ISSUE THREAD

**Issue by SohumB** [magit/magit#1865]
Hey! I just upgraded to `magit-20150516.412` from `magit-20141228.1413`, and I've noticed some serious slowdown in the status window. Tab to open a diff, s to stage a diff, or u to unstage a diff, all take a couple of seconds before they complete.

I've disabled the following vars
```
 '(magit-diff-refine-hunk nil)
 '(magit-highlight-indentation nil)
 '(magit-highlight-trailing-whitespace nil)
 '(magit-highlight-whitespace nil)
 '(magit-use-overlays t)
```

But that shows no improvement.

Any ideas? Thanks!

**Comment by SohumB** [comment]
Ah, one more thing. This slowdown only seems to happen on larger repositories!

**Comment by npostavs** [comment]
>  '(magit-use-overlays t)

https://github.com/magit/magit/wiki/FAQ#what-can-i-do-about-poor-performance

> Additionally when viewing large diffs, setting magit-use-overlays to nil will color diffs using text properties instead of overlays, which scale much better.

**Comment by SohumB** [comment]
They're not large diffs, though! They're, like, three or four line diffs. The slowdown happens in larger _repositories_.

**Comment by npostavs** [comment]
Does the ignore thing in that FAQ entry apply? Other than that... try the [`next`](https://github.com/magit/magit/wiki/Installation#installing-from-the-next-branch) branch maybe?

> Tell Git to ignore files not only by extension but, (also) by location. E.g. if all generated files go into a dedicated directory, then ignoring that complete directory. Git then doesn't have to individually check every single file in that directory.

**Comment by SohumB** [comment]
git on the cli itself is just as fast as always, so I don't think the ignoring thing is relevant. (And the .gitignore does ignore whole directories anyway.) I'll try out the next branch, then!

**Comment by tarsius** [comment]
Yes please try next.

**Comment by SohumB** [comment]
I see the same behaviour on `next`. Should this be reopened?

**Comment by tarsius** [comment]
Yes, but you'll have to run benchmarks and such to find the bottleneck - because for most people Magit is getting faster.

**Comment by SohumB** [comment]
I'm willing to do so. What do you want me to do.

**Comment by johnmastro** [comment]
I don't know if it's what tarsius had in mind, but it's probably worth giving [the profiler](https://www.gnu.org/software/emacs/manual/html_node/elisp/Profiling.html) a shot.

**Comment by SohumB** [comment]
CPU and Memory profiles [here](https://gist.github.com/SohumB/4e0a99915d2944843672).

Thanks!

**Comment by tarsius** [comment]
I was thinking of elp.

1. make sure magit is loaded
2. M-x elp-instrument-package RET "magit-" RET
3. M-x magit-status
4. M-x elp-results

Then repeat that for the other expensive actions. Then please post the results here, not in a gist.

**Comment by SohumB** [comment]
elp does not seem to be instrumenting actions initiated from the status screen. It's not `magit-status` itself that's slow, but opening a diff or staging or unstaging from the status screen, and elp does not return any results whatsoever when I do those actions. (Even if I M-x magit-toggle-section or magit-stage-item.)

**Comment by tarsius** [comment]
Turns out you have to use `M-x elp-instrument-package RET magit- RET` (without the quotes).

**Comment by tarsius** [comment]
> It's not `magit-status` itself that's slow, but

Obviously you know better what actions are slow :-) Benchmark those.

**Comment by SohumB** [comment]
Well, here are the results. They seem much less useful than the earlier profiles, because they don't seem granular enough.

```
magit-toggle-section       1           1.126187859   1.126187859
magit-get-current-tag      1           0.040596076   0.040596076
magit-get-next-tag         1           0.018743231   0.018743231
magit-get-tracked-branch   3           0.017802781   0.0059342603
magit-get                  10          0.015837675   0.0015837675
magit-get-current-branch   4           0.008588863   0.0021472157
magit-get-ref              4           0.008491994   0.0021229985
magit-get-all              3           0.004596602   0.0015322006
magit-get-boolean          1           0.001981251   0.001981251
magit-get-top-dir          1           0.001298894   0.001298894
```

```
magit-unstage-item         1           1.084916486   1.084916486
magit-get-current-tag      1           0.03271647    0.03271647
magit-get-tracked-branch   3           0.018231397   0.0060771323
magit-get-next-tag         1           0.016908798   0.016908798
magit-get                  10          0.016590772   0.0016590772
magit-get-current-branch   4           0.008032272   0.002008068
magit-get-ref              4           0.0079457440  0.0019864360
magit-get-all              3           0.0049051660  0.0016350553
magit-get-boolean          1           0.001959492   0.001959492
magit-get-top-dir          1           0.001723658   0.001723658
```

```
magit-stage-item           1           1.048836716   1.048836716
magit-get-current-tag      1           0.035360782   0.035360782
magit-get-tracked-branch   3           0.018288632   0.0060962106
magit-get-next-tag         1           0.017924988   0.017924988
magit-get                  10          0.016696365   0.0016696365
magit-get-current-branch   4           0.007963555   0.0019908887
magit-get-ref              4           0.0078390910  0.0019597727
magit-get-all              3           0.0050414299  0.0016804766
magit-get-boolean          1           0.00204199    0.00204199
magit-get-top-dir          1           0.001419933   0.001419933
```

**Comment by johnmastro** [comment]
Here's what I see on `next` (Ubuntu Server 12.05, Emacs 24.5, git 2.4.1). I did all three actions on a single-line diff, as SohumB did.

**Toggle:**
```
magit-section-show                        2           0.001805568   0.000902784
magit-section-toggle                      1           0.000931992   0.000931992
magit-diff-highlight-recursive            3           0.000520187   0.0001733956
magit-section-update-highlight            3           0.0005165629  0.0001721876
magit-diff-paint-hunk                     2           0.000467598   0.000233799
magit-diff-highlight                      2           0.000430179   0.0002150895
magit-unhighlight-region                  51          0.0002375129  4.657...e-06
magit-diff-highlight-file                 2           0.000226918   0.000113459
magit-section-ident                       10          0.000140086   1.400...e-05
magit-section-match                       3           0.000138857   4.628...e-05
```

**Stage:**
```
magit-stage                               1           0.201214632   0.201214632
magit-run-git                             1           0.201091858   0.201091858
magit-refresh                             1           0.140858195   0.140858195
magit-refresh-buffer                      1           0.140805226   0.140805226
magit-status-refresh-buffer               1           0.140070959   0.140070959
magit-git-str                             27          0.091530008   0.0033900002
magit-call-git                            1           0.060206591   0.060206591
magit-rev-parse-safe                      17          0.058923574   0.0034660925
magit-git-insert                          12          0.058806013   0.0049005010
magit-call-process                        1           0.054956697   0.054956697
```

**Unstage**:
```
magit-unstage                             1           0.174287351   0.174287351
magit-unstage-1                           1           0.174164977   0.174164977
magit-run-git                             1           0.170070067   0.170070067
magit-refresh                             1           0.143053066   0.143053066
magit-refresh-buffer                      1           0.143007292   0.143007292
magit-status-refresh-buffer               1           0.142270964   0.142270964
magit-git-str                             26          0.0898798350  0.0034569167
magit-rev-parse-safe                      16          0.0564902620  0.0035306413
magit-git-insert                          11          0.0557834620  0.0050712238
magit-insert-status-headers               1           0.041405176   0.041405176

```

**Comment by tarsius** [comment]
@SohumB You are *not* using the `next` branch of Magit. These benchmarks contain functions which do not exist in that version.

**Comment by tarsius** [comment]
@SohumB You are *not* using the `next` branch of Magit. These benchmarks contain functions which do not exist in that version.

**Comment by SohumB** [comment]
Ah! You're completely right; I apologise. I apparently haven't figured out how to tell `prelude` to not simply download the elpa magit again, even though magit is sitting there in `vendor`.

In any case, the good news is that `next` does not have the slowdown I described! So thank you very much for bearing with me, and I look forward to many more years of enjoying magit :)

**Comment by felliott** [comment]
Hello!  I am also seeing a major slowdown in the most recent 1.4 release.  I ran the profiler as suggested and got the following results after toggling the diff display in the status buffer:

````
magit-section-set-hidden                      11          2.853365      0.2593968181
magit-toggle-section                          1           2.85323       2.85323
magit-section-hideshow                        1           2.853221      2.853221
magit-refresh                                 1           2.853187      2.853187
magit-revert-buffers                          1           2.636102      2.636102
magit-mode-refresh-buffer                     1           0.217056      0.217056
magit-refresh-status                          1           0.216874      0.216874
magit-git-string                              24          0.126691      0.0052787916
magit-git-lines                               3           0.070609      0.0235363333
magit-git-dir                                 9           0.049121      0.0054578888
magit-insert-stashes                          1           0.042847      0.042847
magit-get-tracked-branch                      3           0.04045       0.0134833333
magit-get                                     6           0.029638      0.0049396666
magit-git-exit-code                           3           0.022354      0.0074513333
magit-get-current-branch                      4           0.0213989999  0.0053497499
````
I dug around a little bit, and found that the new implementation of `magit-revert-buffers` seems to be the source of the slowness.  `vc-find-file-hook` and the `run-hooks` functions are being run on every open file in the repository whether they need to be reverted or not.  I don't know enough about those functions to say if that is the desired behavior, but I think that's the culprit.  Below is a profile I ran with one file needing reversion and 111 open project files total:

````
magit-revert-buffers  1           2.954625      2.954625
vc-find-file-hook     111         2.902504      0.0261486846
run-hooks             905         0.0052550000  5.806...e-06
revert-buffer         1           0.000538      0.000538
````

Please let me know if I can provide any more information, and thank you very much for such a fantastic package!

Cheers,
Fitz

**Comment by tarsius** [comment]
`vc-find-file-hook` has to be run if one wants to ensure that the information vc displays in the mode-line is up-to-date, even when the file does not change. For example if you checkout another branch, then the branch name in the mode-line needs to be changed, regardless of whether the file is the same on that branch and the one that was previously checked out.

But some people might not care about that information, so I will move the call to `vc-find-file-hook` to a hook making it possible to disable this. But only on the `next` branch.

I didn't realize that most of the time `magit-revert-buffers`  uses to do its thing, is actually spend in `vc-find-file-hook`. Very useful information. (And I am happy that once more it turns that the delay is not due to inefficient code in Magit itself, but because we use some slow external code :-)

> 111 open project files

I never manage to get there, but there have been a lot of reports from users lately for whom this is normal. So I am considering not only moving `vc-find-file-hook` to magit hooks, but to remove the hard coded call to it and *not* adding it to the hooks by default.

**Comment by tarsius** [comment]
@felliott 46460e1267d140db92d5f2b284f565612c13cc12 should make this much more efficient. It might still be to slow with so many buffers though, in which you can remove `magit-refresh-vc-mode-line` from `magit-after-refresh-hook` and `magit-not-reverted-hook`. Please let me know how this works for you.

**Comment by felliott** [comment]
> @felliott 46460e1 should make this much more efficient. It might still be to slow with so many buffers though, in which you can remove magit-refresh-vc-mode-line from magit-after-refresh-hook and magit-not-reverted-hook. Please let me know how this works for you.


@tarsius  Thanks!  I can confirm that this works quickly with my 111 open buffers and with magit-refresh-vc-mode-line still in my magit-after-revert-hook.

Cheers,
Fitz

**Comment by vjohansen** [comment]
I  am using version 20150525.1145

Diffing, for example, unstaged changes for a single file is very slow. I have four files with small diffs. Going through each and pressing TAB twice (which I usually do before committing) takes 8 seconds.

    magit-section-set-hidden                      104         8.937         0.0859326923
    magit-section-hideshow                        8           8.936         1.117
    magit-toggle-section                          8           8.936         1.117
    magit-refresh                                 4           8.935         2.23375
    magit-mode-refresh-buffer                     4           8.0369999999  2.0092499999
    magit-refresh-status                          4           8.0369999999  2.0092499999
    magit-git-string                              116         4.122         0.0355344827
    magit-git-lines                               24          3.087         0.1286250000
    magit-insert-stashes                          4           2.3449999999  0.5862499999


With profiler-start (cpu), profiler-report:

    - ...                                                              87  85%
     - yas/fallback                                                    68  66%
      - cond                                                           68  66%
       - let*                                                          68  66%
        - if                                                           68  66%
         - progn                                                       68  66%
          - call-interactively                                         68  66%
           - magit-toggle-section                                      68  66%
            - magit-section-hideshow                                   68  66%
             - #<compiled 0x1040fc1>                                   68  66%
              - magit-section-set-hidden                               68  66%
               - magit-refresh                                         68  66%
                - magit-mode-refresh-buffer                            59  57%
                 - apply                                               59  57%
                  - magit-refresh-status                               59  57%
                   - run-hooks                                         58  56%
                    + magit-insert-unpushed-commits                    12  11%
                    + magit-insert-status-remote-line                   7   6%
                    + magit-insert-unpulled-commits                     7   6%
                    + magit-insert-status-head-line                     4   3%
                    + magit-insert-rebase-sequence                      3   2%
                    + magit-insert-unstaged-changes                     3   2%
                    + magit-insert-staged-changes                       3   2%
                    + magit-insert-status-tags-line                     3   2%
                    + magit-insert-status-rebase-lines                  2   1%
                    + magit-insert-bisect-output                        2   1%
                    + magit-insert-untracked-files                      2   1%
                    + magit-insert-pending-commits                      2   1%
                    + magit-insert-status-local-line                    2   1%
                    + magit-insert-bisect-rest                          2   1%
                    + magit-insert-bisect-log                           2   1%
                    + magit-insert-status-merge-line                    1   0%
                    + magit-insert-stashes                              1   0%
                   + magit-git-exit-code                                1   0%
                - magit-revert-buffers                                  9   8%
                 + magit-git-lines                                      3   2%
                 + vc-find-file-hook                                    3   2%
                 + magit-git-dir                                        2   1%
                 + magit-get-top-dir                                    1   0%
       Automatic GC                                                    13  12%
     - vc-mode-line                                                     2   1%
      + vc-call-backend                                                 2   1%
     + vc-state                                                         2   1%
     + helm--compute-sources                                            2   1%
    - command-execute                                                  14  13%
     + call-interactively                                              14  13%
      timer-event-handler                                               1   0%

It seems that a lot of updating is happening which should not be necessary when magit should just insert the diff in the magit buffer.

**Comment by tarsius** [comment]
@vjohansen Please try the `next` branch. I am not backporting anymore improvements.

**Comment by vjohansen** [comment]
With the `next` branch show/hide of a diff for a file is instantaneous.

**Comment by tarsius** [comment]
Great! :-)
