### ISSUE TITLE
Point does not always reset when showing next commit

### ISSUE THREAD

**Issue by kyleam** [magit/magit#1871]
When viewing the log and a revision side-by-side, there are cases
where, after moving to the next commit, point stays at the end of the
revision window instead of resetting to the beginning of the buffer.

For example, running with `emacs -Q` and using the magit repo:

-   `lo` next
-   Go to commit 3026b56182c767e16f57707d440a680b60fc337a and show it with
    SPC.
-   Scroll to very end of the magit-rev buffer.
-   Go the next commit (9d7145a04de149aafbb8dc02e95c339133e2f360).

When I do this, point ends up at the end of the new magit-rev window.

**Comment by kyleam** [comment]
Thank you!

**Comment by bradyt** [comment]
Was using `C-M-v` and `C-M-S-v` and running into this issue, now I see `RET` and `SPC` is better. But I'm also using the trackpad so for example I can bring a paragraph into full view, and running into this issue.
