### ISSUE TITLE
M-enter does not open file

### ISSUE THREAD

**Issue by JoeRiel** [magit/magit#1874]
This may be my misunderstanding, but should M-enter on a file name in the magit process buffer, say the output from running a git grep, open that file? It does not. The call to magit-file-at-point returns nil, so instead the default action is used, which opens dired at the main directory.

**Comment by tarsius** [comment]
Process output is just dumped into that buffer without being parsed, it's just arbitrary text. Diffs on the other hand are parsed and for each file a section of type `file` is created. `magit-file-at-point` finds the file by checking if the section at point is of type `file` (in which case the file name is stored as the value of the section).

So no, this isn't expected to work in the process buffer and it probably never will.
