### ISSUE TITLE
Colorise *magit-process* buffer

### ISSUE THREAD

**Issue by hmgibson23** [magit/magit#1878]
If you have any git hooks that output color if hey fail (or pass) magit does not colorise the the buffer before the output. So it looks like: 

```[31m[[39m[33mL44[39m[31m:[39m[33mC17[39m[31m][39m [33mW117[39m[31m:[39m [33m'console' is not defined.[39m```

Should be pretty simple to apply the ANSI colours to this. If someone points me in the right direction I'm happy to contribute.

**Comment by Silex** [comment]
I think using `ansi-color-region` should work.

**Comment by hmgibson23** [comment]
Absolutely it will work...

**Comment by tarsius** [comment]
Seems these hook scripts should respect `color.ui` (whose value should be `auto`*). Running `ansi-color-region` just in case would be overkill, because we do call git itself with `--no-color`.

* Hm, that complicates it a bit though. To respect `auto` these scripts would have to determine whether output goes to a terminal.

**Comment by tarsius** [comment]
If you really want the colors, or prefer editing Magit instead of the Git hooks, then you'll need to advise `magit-process-sentinel`, `magit-process-filter`, or some other related function. But I don't think it is worth it.

**Comment by kyleam** [comment]
> Is there a potential solution for that?

Did you try the suggestion above: "advise magit-process-sentinel, magit-process-filter, or some other related function" to call `ansi-color-apply-on-region`?

**Comment by geoffp** [comment]
@kyleam, I would gladly try that, but admittedly, I'd need a little help to point me in the right direction to do it. My elisp skills are in the early stages of development. :)

**Comment by LaloHao** [comment]
@geoffp 

```emacs-lisp
(defun color-buffer (proc &rest args)
  (interactive)
  (with-current-buffer (process-buffer proc)
    (read-only-mode -1)
    (ansi-color-apply-on-region (point-min) (point-max))
    (read-only-mode 1)))

(advice-add 'magit-process-filter :after #'color-buffer)
```

**Comment by npostavs** [comment]
@geoffp's escape sequences are for cursor movement, not ansi colours. See #3549.

**Comment by geoffp** [comment]
@npostavs has nailed it. #3549 is **precisely** my issue.
