### ISSUE TITLE
Display of the commit time of last commit in magit-log-mode

### ISSUE THREAD

**Issue by abo-abo** [magit/magit#1880]
When in `magit-log-mode`, after calling `beginning-of-buffer`, possibly twice for good measure, the modification time of the last commit vanishes.  After a few `forward-char` it re-appears. The commit message is moderately long and there are 3 branches on it, so everything together is longer than 80 lines.

**Comment by tarsius** [comment]
Aaaaah do those property stickiness issues never end!

**Comment by tarsius** [comment]
That kludge should do the trick.

**Comment by npostavs** [comment]
I can't seem to reproduce this in Emacs 25.3 or 26.2 after applying
```diff
modified   lisp/magit-margin.el
@@ -154,8 +154,7 @@ (defun magit-make-margin-overlay (&optional string previous-line)
       (save-excursion
         (forward-line -1)
         (magit-make-margin-overlay string))
-    ;; Don't put the overlay on the complete line to work around #1880.
-    (let ((o (make-overlay (1+ (line-beginning-position))
+    (let ((o (make-overlay (line-beginning-position)
                            (line-end-position)
                            nil t)))
       (overlay-put o 'evaporate t)
```

so perhaps this has been fixed in Emacs meanwhile?
