### ISSUE TITLE
How to get old-style magit-ediff?

### ISSUE THREAD

**Issue by abo-abo** [magit/magit#1883]
I never want to see the C: buffer, only A: and B:. `magit-ediff-dwim` works as I want for revisions, but not for uncommitted changes.

**Comment by Silex** [comment]
#1743

**Comment by abo-abo** [comment]
But that one was closed without solving it.

**Comment by Silex** [comment]
It was solved. The solution is to rebind to `magit-ediff-compare` instead of `...-dwim`.

**Comment by abo-abo** [comment]
> It was solved. The solution is to rebind the key to magit-ediff-compare instead of ...-dwim.

I tried it, and it doesn't do it for me. It requires at least two inputs, which I don't want to provide.  I don't even know what I'm supposed to put in to get the effect of <kbd>e</kbd> (without a third buffer).

**Comment by tarsius** [comment]
@abo-abo I don't remember what exactly the old implementation did, just that it was very incomplete. And your description of what you want to do is not complete enough to fill in the details.

What do you want to see in the ediff buffers? Some commit vs. its parent? Unstaged changes?

**Comment by abo-abo** [comment]
> What do you want to see in the ediff buffers?

I want to see the (staged or unstaged) change vs. index, in two buffers, vertically. No questions asked. That is the behavior of <kbd>e</kbd> in `master`.

**Comment by tarsius** [comment]
Do you then want to stage and/or unstage (and/or discard) or do you just want to look at it?

**Comment by abo-abo** [comment]
Just to look at it.

**Comment by tarsius** [comment]
That surprises me, but yeah then I can understand why you want just two buffers. Magit doesn't support this and you'll have to kill the buffer that you don't want.

Again I *might* do something about this after the release, but not before.

**Comment by tarsius** [comment]
Okay I have implemented two new variants now. For more details see #1743.

**Comment by tarsius** [comment]
```elisp
(define-key magit-file-section-map "e" 'magit-ediff-old-school)

(defun magit-ediff-old-school ()
  "This is a bit like `magit-ediff-dwim' but much much worse."
  (interactive)
  (magit-section-case
    ([*   staged] (call-interactively #'magit-ediff-show-staged))
    ([* unstaged] (call-interactively #'magit-ediff-show-unstaged))
    (t            (call-interactively #'magit-ediff-dwim))))
```

**Comment by abo-abo** [comment]
To go from "much much" to just "much":

```elisp
(define-key magit-file-section-map "e" 'magit-ediff-old-school)

(defun magit-ediff-old-school ()
  "This is a bit like `magit-ediff-dwim' but much worse."
  (interactive)
  (magit-section-case
    ([*   staged] (magit-ediff-show-staged (magit-current-file)))
    ([* unstaged] (magit-ediff-show-unstaged (magit-current-file)))
    (t            (call-interactively #'magit-ediff-dwim))))
```

**Comment by fredRos** [comment]
thank @tarsius and @abo-abo , your solution serves me well

**Comment by kyleam** [comment]
@fredRos You can now set magit-ediff-dwim-show-on-hunks to t to get
this behavior.  (I think I gave that option a poor name, but I still
can't come up with anything better.)
