### ISSUE TITLE
How to disable the highlighting of groups?

### ISSUE THREAD

**Issue by abo-abo** [magit/magit#1884]
I find the behavior of highlighting groups very distracting.  I'd like `magit-section-make-overlay` to be called only for single items, never for groups.

**Comment by tarsius** [comment]
What do you mean by "group". The current section and its subsections? Sibling sections selected using the region?

**Comment by abo-abo** [comment]
I mean:

- the status group at the top
- Stashes
- Untracked files
- Unstaged changes

I don't want the whole section highlighted when the cursor moves there.  I want to highlight only atoms (single stashes, files etc).

**Comment by abo-abo** [comment]
Also, there's little point to highlight anything in the status group, since all lines there aren't actionable.

**Comment by tarsius** [comment]
Except for the first one.

**Comment by abo-abo** [comment]
> Except for the first one.

?

**Comment by tarsius** [comment]
It can be expanded and collapsed. And the other sections too. E.g. the Head line is a section of type `branch`. There are commands that behave differently when point is on a branch.

**Comment by abo-abo** [comment]
> It can be expanded and collapsed.

But that's useless. I meant actual actions, like staging, deleting, discarding, resurrecting etc.

**Comment by tarsius** [comment]
I am not gonna do anything about this before the release.

Meanwhile I recommend you use a background color for the highlighting that is very close to the default background. That's how it is supposed to be anyway, but themes haven't been adjusted yet.

**Comment by abo-abo** [comment]
As you wish. I like to use `:weight bold` for the highlighting. The issue becomes more pronounced for that face.

**Comment by tarsius** [comment]
This reduces the highlighting for most of the mentioned sections.

```lisp
(defun magit-section-highlight-less (section _)
  (magit-section-case
    ((untracked unstaged staged unpushed unpulled)
     ;; ^ You will likely have to add more here,
     ;; `magit-describe-section' is your friend.
     (magit-section-make-overlay (magit-section-start   section)
                                 (magit-section-content section)
                                 'magit-section-highlight)
     t)))

(add-hook 'magit-section-highlight-hook 'magit-section-highlight-less)
```

It does not work for the header sections in the status buffer.

**Comment by tarsius** [comment]
Or if you don't even want the heading to be highlighted just drop  the `magit-section-make-overlay` altogether.
