### ISSUE TITLE
magit-branch-delete fails on ambiguous refs

### ISSUE THREAD

**Issue by kyleam** [magit/magit#1888]
`magit-branch-delete` fails when, for some unconvincing reason,
someone decides to have a tag and a branch have the same name.

With a local branch and tag "ambig", `magit-ref-fullname` returns nil,
resulting in the following error

    Debugger entered--Lisp error: (wrong-type-argument stringp nil)
      string-match("^refs/remotes/\\([^/]+\\)" nil)
      (cond ((string-match "^refs/remotes/\\([^/]+\\)" ref) (let* ((remote (match-string 1 ref)) (offset (1+ (length remote)))) (magit-run-git-async "push" remote (mapcar (function (lambda (it) (concat ":" ...))) branches)))) ((> (length branches) 1) (magit-run-git "branch" (if force "-D" "-d") (delete (magit-get-current-branch) branches))) (t (let* ((branch (car branches)) (prompt (format "Branch %s is checked out.  " branch))) (if (equal branch (magit-get-current-branch)) (progn (let* ((val ...)) (cond (... ...) (... ...) (... ...) (t nil))) (setq force t))) (magit-run-git "branch" (if force "-D" "-d") branch))))
      (let ((ref (magit-ref-fullname (car branches)))) (cond ((string-match "^refs/remotes/\\([^/]+\\)" ref) (let* ((remote (match-string 1 ref)) (offset (1+ (length remote)))) (magit-run-git-async "push" remote (mapcar (function (lambda ... ...)) branches)))) ((> (length branches) 1) (magit-run-git "branch" (if force "-D" "-d") (delete (magit-get-current-branch) branches))) (t (let* ((branch (car branches)) (prompt (format "Branch %s is checked out.  " branch))) (if (equal branch (magit-get-current-branch)) (progn (let* (...) (cond ... ... ... ...)) (setq force t))) (magit-run-git "branch" (if force "-D" "-d") branch)))))
      magit-branch-delete(("ambig") nil)
      call-interactively(magit-branch-delete nil nil)
      command-execute(magit-branch-delete)

Trying to delete a remote branch "ambig" results in the following
message from git.

    1 git … push remote :ambig
    error: dst refspec ambig matches more than one.
    ...

**Comment by tarsius** [comment]
> `magit-branch-delete` fails when, for some unconvincing reason, someone decides to have a tag and a branch have the same name.

So how did you learn about this?
That's why we need other people testing - I would never do such a thing :-)
![enhanced-buzz-26206-1358984150-8](https://cloud.githubusercontent.com/assets/25046/7938771/7c9e9f7c-0947-11e5-920a-284e9e1581ba.jpg)

**Comment by kyleam** [comment]
> So how did you learn about this?

Unfortunately, I had no luck persuading past me against the decision.

**Comment by kyleam** [comment]
Thank you, but I don't think 3b7dbecaa188014f45f64f6ee859b16f98b22aff fixes the issue.

When I try to delete an ambiguous remote branch, it now tries to
delete it like it is a local branch

      1 git … branch -d origin/ambig
    error: branch 'origin/ambig' not found.

instead of running

    gp origin :heads/ambig

Deleting a local branch also fails.  If it is called from the refs
buffer with the branch at point, you can select ambig and it will
cause the string-match-p call in magit-ref-fullname to fail with a
string-p error.

However, if you don't call it with the branch at point, you don't have
the option to select ambig, only heads/ambig, because of how

    git for-each-ref --format='%(refname:short)' refs/heads

lists ambiguous refs.  This then leads to the error

      1 git … branch -d heads/ambig
    error: branch 'heads/ambig' not found.

Also, I don't understand the new dialog.

    (magit-read-char-case "Ambigious ref(s).  Do you want to delete " nil
      (?r "[r]emote branch(es)"
          (setq ref (concat "refs/remotes/" (car branches))))
      (?l "or [l]ocal branch(es)"
          (setq ref (concat "refs/heads/" (car branches))))))

The issue is with a tag and a branch name being ambiguous, not whether
to delete local or remote branch.

Using

    git branch -d ambig

for the local branch will work, because "git branch" knows that you
want to delete a branch, not a tag.  It's just that the ambiguous
ref was causing an issue for magit-ref-fullname.

On the other hand, the remote branch origin/ambig got through
magit-ref-fullname fine but was failing at

    git push origin :ambig

because "git push", unlike "git branch", doesn't know whether ambig
refers to the remote branch or tag, so

    git push origin :heads/ambig

is needed to delete the branch.

---

What do you think about just having magit-ref-fullname or
magit-branch-delete raise a user error reporting that a ref is
ambiguous?  I don't think it is something that you should waste time
trying to support, as it isn't a good idea or common.  I was just
bringing up a edge case where I found that magit-delete-branch gives
an error.

**Comment by tarsius** [comment]
You're right the fix is very incomplete to the point of not making a difference at all :-/

**Comment by tarsius** [comment]
The problem is that `magit-branch-delete` already is a heavily overloaded function which does way to much. In the past I have tried removing some of these features but that always caused protests. Guess I have to disfigure it some more to fix this issue.

> What do you think about just having magit-ref-fullname or magit-branch-delete raise a user error reporting that a ref is ambiguous?

Or that. Yeah, that's probably what I am going to do.

**Comment by kyleam** [comment]
Great, thanks.

I'm seeing appropriate error messages on my end: a Magit user-error when trying to delete an ambiguous local branch and the a git ambiguous error in the process buffer when trying to delete an ambiguous remote branch.

I'm not sure that this is worth fixing, but magit-list-branch-names will return "heads/ambig" (for the reason I described above) rather than head (although a plain "ambig" may still be in the magit-read-branch collection if point is on ambig or ambig was the previous branch).  Selecting heads/ambig for deletion will give

```
  1 git … branch -d heads/ambig
error: branch 'heads/ambig' not found.
```

Again, not sure it's worth filtering out, but it does lead to a git process error that doesn't make it clear that ambiguous references is the issue.

Thanks for the fixes.
