### ISSUE TITLE
Selected region adds one extra pixel at top and bottom

### ISSUE THREAD

**Issue by wasamasa** [magit/magit#1891]
If I select a region with the mouse in my changes, I can see two lines with 1px height at top and bottom which makes for a sort of neat effect, but introduces some visual artefacts. The most obvious one is that once the region goes beyond the changes, I get the regular region face instead of the overlay (?) applied on it. The other one is that movement of the region end makes the text "wobble" as it gets moved up and down around the borders.

Judging by the sources this is the fault of `magit-diff-update-hunk-region`. I wonder why this experimental looking approach was chosen and why just using a face with the box property and a value of -1 to make the border point *inwards* (which avoids the text wobbling) wasn't considered. Another problem of it is that it works even worse in the terminal as the 1px high lines are turned into full-height lines which are even more intrusive than the old approach to this. Using a regular face would allow to make use of this gimmick in non-textual Emacs instances only.

**Comment by tarsius** [comment]
> The most obvious one is that once the region goes beyond the changes, I get the regular region face instead of the overlay (?) applied on it.

That's a feature not a defect. If you the region in a Magit buffer looks it would look in another buffer, then it is neither a "hunk-internal region" nor a "sibling-selection region", i.e. an invalid region as far as Magit is concerned. By using the regular region look this is being signaled to the user. In other words it's only possible to stage lines from within the same hunk, not the end of one hunk and the beginning of another hunk *in one go*.

> The other one is that movement of the region end makes the text "wobble" as it gets moved up and down around the borders.

That also bothered me at first. But that was because I concentrated on it, eventually I stopped noticing it at all.

> I wonder why this experimental looking approach was chosen

I quite like it, that's why :-)

> and why just using a face with the box property and a value of -1 to make the border point inwards (which avoids the text wobbling) wasn't considered.

It was considered but does not work. It would no longer be possible to have the line span the complete window width.

> Another problem of it is that it works even worse in the terminal as the 1px high lines are turned into full-height lines

That's not good and will be fixed. Maybe I will also add an option to disable this even when using a window system.

**Comment by wasamasa** [comment]
I see, thank you!

**Comment by wasamasa** [comment]
Hmm, I've noticed another annoying thing, the mere act of *clicking* to place point somewhere else triggers the hunk region handler and makes the lines around it appear and colors the hunk header with the respective face, then undoes these changes as point is moved.

I do realize that I can just customize `magit-region-highlight-hook` to be empty, but maybe testing the defaults for their usability would be a better idea.

**Comment by tarsius** [comment]
I have noticed that and have not found the time to investigate it yet. It's quite a mystery.

**Comment by tarsius** [comment]
Anyway I have added a kludge for that now.

**Comment by wasamasa** [comment]
Thanks, the kludge does the trick here.

**Comment by Malabarba** [comment]
> > Another problem of it is that it works even worse in the terminal as the 1px high lines are turned into full-height lines

> That's not good and will be fixed. Maybe I will also add an option to disable this even when using a window system.

Wait, is the line supposed to have 1 pixel of height? It's always been a full line for me, and I'm always on a windowed system. How can I debug that?

**Comment by Malabarba** [comment]
`C-u C-x =` tells me there's an overlay there whose `after-string` prop is 

    #(" \n" 0 1
      (display
       (space :height (1))
       face magit-diff-lines-boundary)
      1 2
      (line-height t face magit-diff-lines-boundary))

Doesn't this mean that the `:height` is only applies to the first char (the space) and not the second char (the newline)?

**Comment by npostavs** [comment]
The `line-height` property applies to the newline

http://www.gnu.org/software/emacs/manual/html_node/elisp/Line-Height.html

>   A newline can have a ‘line-height’ text or overlay property that
controls the total height of the display line ending in that newline.
>
>   If the property value is ‘t’, the newline character has no effect on
the displayed height of the line—the visible contents alone determine
the height.

**Comment by tarsius** [comment]
It seems to be broken in Emacs 25.0.50. But I've only known that for two days 'cause that's when I updated. Or maybe this now has to be done differently - I haven't checked yet.

**Comment by Malabarba** [comment]
It's very possibly a bug in the display engine. I've seen some line-height related bugs and commits floating around.
