### ISSUE TITLE
ediff3 to resolve merge conflicts

### ISSUE THREAD

**Issue by To1ne** [magit/magit#1893]
Feature request:
Use `ediff3` to resolve merge conflicts. Emacs would look like something like this:

    |their|base|ours|
    |---------------|
    |    result     |

**Comment by tarsius** [comment]
Install Magit from it's `next` branch, press `e` on a file with conflicts.

**Comment by To1ne** [comment]
Thx! You rock!
![homer rocks](http://media.giphy.com/media/KYMR9VsDGs3PW/giphy.gif)

**Comment by tarsius** [comment]
Have fun trying out the new stuff!

**Comment by To1ne** [comment]
Should this work in v2.1 too?

**Comment by tarsius** [comment]
Yes.

**Comment by To1ne** [comment]
It doesn't. Well in fact, in this case I was rebasing.

**Comment by tarsius** [comment]
`e` dwims based on the context. Put point on a line that sais "unmerged filename" and press `e`.

Alternatively you can use `E m` and then provide the filename.

**Comment by To1ne** [comment]
I've tried several things, but I haven't find any way to show 3 windows at the top (theirs, base, ours).

**Comment by To1ne** [comment]
Can you reopen this issue? Or won't it be supported?

**Comment by kyleam** [comment]
I don't think there's a builtin way in Ediff to get the 4-panel view you
want.  ediff-merge-files-with-ancestor doesn't display the ancestor
buffer, but you can view it with '/'.

    (info "(ediff)Merging and diff3")

    Although the ancestor buffer is normally invisible, Ediff maintains
    difference regions there and advances the current difference region
    accordingly.  All highlighting of difference regions is provided in
    the ancestor buffer, except for the fine differences.  Therefore, if
    desired, the user can put the ancestor buffer in a separate frame
    and watch it there.  However, on a TTY, only one frame can be
    visible at any given time, and Ediff doesn’t support any
    single-frame window configuration where all buffers, including the
    ancestor buffer, would be visible.  However, the ancestor buffer can
    be displayed by typing ‘/’ to the control window.  (Type ‘C-l’ to
    hide it again.)

Here is the current state of things in Magit.  If you have conflicts,
magit-ediff-dwim calls magit-ediff-resolve, which in turn calls
smerge-ediff.  smerge-ediff decides whether to call ediff-merge-buffers
or ediff-merge-buffers-with-ancestor based on the conflict style of the
buffer.  If you have Git's merge.conflictStyle set to 'diff3',
ediff-merge-buffers-with-ancestor will be called, and you can use '/' to
see the ancestor buffer.

**Comment by To1ne** [comment]
Fine... I look into it myself and create a PR if I've found it...

**Comment by kyleam** [comment]
ediff-window-setup-function is the variable to have a look at, although
I suspect this may not be straightforward to implement given that Ediff
explicitly does not support this view.

Because Ediff's window configuration for merges isn't Magit-specific,
perhaps the "Tips and Tricks" section of the wiki, rather than a PR,
would be the best place for a custom ediff-window-setup-function
function.

https://github.com/magit/magit/wiki/Tips-and-Tricks

**Comment by timclassic** [comment]
@kyleam This is great info, thank you!

> smerge-ediff decides whether to call ediff-merge-buffers or ediff-merge-buffers-with-ancestor based on the conflict style of the buffer. If you have Git's merge.conflictStyle set to 'diff3', ediff-merge-buffers-with-ancestor will be called, and you can use '/' to see the ancestor buffer.

I'd like a sanity-check: If I have conflictstyle set to 'diff3', do I still get the benefit of the conflict resolutions that Git *was* able to figure out in the file?  If so, this seems like a great alternative to using ediff-merge-revisions-with-ancestor directly just to get access to what the ancestor revision looked like during the merge.

Perhaps the conflictstyle setting should be mentioned in the Magit docs?

**Comment by tarsius** [comment]
> I'd like a sanity-check: If I have conflictstyle set to 'diff3', do I still get the benefit of the conflict resolutions that Git was able to figure out in the file? If so, this seems like a great alternative to using ediff-merge-revisions-with-ancestor directly just to get access to what the ancestor revision looked like during the merge.

Exactly! See http://magit.vc/manual/magit/Can-Magit-be-used-as-ediff_002dversion_002dcontrol_002dpackage_003f.html

> Perhaps the conflictstyle setting should be mentioned in the Magit docs?

Probably. We also have to test what happens when another conflict style is used. Things might fall apart then.

**Comment by tarsius** [comment]
Okay it doesn't fall apart otherwise, `/` just won't work. `merge.conflictstyle=diff3` is now mentioned in the `magit-ediff-resolve`s entry in the manual.

**Comment by timclassic** [comment]
@tarsius Thank you for confirming, and for the manual update!
