### ISSUE TITLE
Losing local changes with bad key combo

### ISSUE THREAD

**Issue by catalin-hritcu** [magit/magit#1894]
Today something strange happened to me: I accidentally typed stuff in the magit-status buffer and that caused all my local changes to disappear. I looked in the magit-process buffer and the command that was run was this:
```
git --no-pager apply --reverse --ignore-space-change -
```
Any idea what might have happened?

**Comment by tarsius** [comment]
Assuming that you not using `next`, you pressed `k` and then `yes` or `v` and have in the past set `magit-revert-item-confirm` to nil.

I recommend you update to the `next` branch. Turn on all the global modes defined in `magit-wip.el` and then familiarize yourself with how to restore from those work-in-progress refs.

**Comment by tarsius** [comment]
I have just updated the documentation about the wip modes. See "Wip Modes" in http://magit.vc/manual/next/magit.html.
