### ISSUE TITLE
commit message in a new window

### ISSUE THREAD

**Issue by yitang** [magit/magit#1895]
Hi, how to configure magit so that it will open an new window for commit message?

**Comment by tarsius** [comment]
It should already be doing that. At least on the `next` branch but I think that's also the case when using `1.4.*`. Not sure though.

I recommend you update to the `next` branch or wait a few more weeks until `2.1.0` is released.

**Comment by tarsius** [comment]
By the way please don't use the issue tracker for support requests, see https://github.com/magit/magit#getting-help.

**Comment by yitang** [comment]
Thanks for your responses. I will wait for the next release. 

I read that section but skip the second paragraph...
