### ISSUE TITLE
Diff of gpg-encrypted file in magit-status

### ISSUE THREAD

**Issue by DamienCassou** [magit/magit#1896]
When a gpg-encrypted file is versionned and modified, the `magit-status` buffer says that the diff is binary and cannot be shown:

```
Unstaged changes:
    Modified dotfiles/authinfo.gpg
diff --git a/dotfiles/authinfo.gpg b/dotfiles/authinfo.gpg
index f9a05ca..8366ce2 100644
Binary files a/dotfiles/authinfo.gpg and b/dotfiles/authinfo.gpg differ
```

It would be nice if a future version of magit (not the only currently being released obviously) could show the diff as soon as Emacs can decrypt the file.

**Comment by vanicat** [comment]
Git can do it, and magit can use git capabilty for this:

    git config --global diff.gpg.textconv "gpg --no-tty --decrypt"
    echo "*.gpg filter=gpg diff=gpg" > .gitattributes

Then git will use gpg when diffing .gpg files.

**Comment by tarsius** [comment]
I have added this to the FAQ, which is a bit of an exaggeration, but this has been asked before.
