### ISSUE TITLE
Intelligent pushing to remote branches

### ISSUE THREAD

**Issue by j-mckitrick** [magit/magit#1897]
Sorry in advance if this has been answered or implemented recently....

When I create a branch and push to a remote, I currently:

1.  set the 'upstream' flag
2.  select 'elsewhere' for the destination
3.  accept the currently selected branch
4. type the name of the current branch, only with 'origin' before it

Is there a better way to do this workflow?

thanks!

**Comment by tarsius** [comment]
Could you please take this to one of the support channels mentioned here https://github.com/magit/magit#getting-help.

**Comment by j-mckitrick** [comment]
Sorry about that!  I missed that part of the wiki.  Thanks!
