### ISSUE TITLE
Too many git subprocesses

### ISSUE THREAD

**Issue by Zert** [magit/magit#1898]
When I trying to see diff in magit buffer (magit-20150608) using TAB, emacs does it too slow. When I dig it using strace, I saw that it runs 756 git subprocesses sequentially. Before this update I had no such problem with magit.

**Comment by tarsius** [comment]
Are you sure all these subprocesses are started right after pressing TAB, or might most of them be older? I can only speculate what is wrong, and my guess would be that you have very many open buffers visiting files inside the repository.

Anyway performance is much better on the `next` branch, which will be released as `2.1.0` later this month. I recommend you update to that now. It's ready except that the documentation needs some final touches.

**Comment by Zert** [comment]
Yes, I had a large amount of opened buffers inside the repo. When I killed almost all of buffers, problem disappeared, but I need to keep all files opened to fast switch between them.
Thank you, I'll switch to the new version of magit of course.

**Comment by tarsius** [comment]
Updating should do the trick here, see #1865.

If it doesn't, then enable asynchronous reverting by customizing `magit-revert-buffers`.
