### ISSUE TITLE
wrong-type-argument integer-or-marker-p nil when trying to apply

### ISSUE THREAD

**Issue by Malabarba** [magit/magit#1900]
On the `next` branch, with a magit status buffer like the following

    Head:     5de5766 elpa packages/names: Version bump
    Upstream: 5de5766 origin/elpa packages/names: Version bump
    
    Untracked files:
    0001-New-names-pprint-command-to-pretty-print-entire-name.patch

The patch file was previously created with `W`.
If I place point on the patch line and hit `a`, I get the following error:

    Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
      buffer-substring(nil #<marker at 269 in *magit: ~/Git-Projects/names/*>)
      (concat (magit-diff-file-header section) (buffer-substring (progn nil (or (progn nil (and (vectorp section) (>= (length section) 14) (memq (aref section 0) cl-struct-magit-section-tags) t)) (signal (quote wrong-type-argument) (list (quote magit-section) section))) (aref section 4)) (progn nil (or (progn nil (and (vectorp section) (>= (length section) 14) (memq (aref section 0) cl-struct-magit-section-tags) t)) (signal (quote wrong-type-argument) (list (quote magit-section) section))) (aref section 5))))
      (magit-apply-patch (concat (magit-diff-file-header section) (buffer-substring (progn nil (or (progn nil (and (vectorp section) (>= ... 14) (memq ... cl-struct-magit-section-tags) t)) (signal (quote wrong-type-argument) (list (quote magit-section) section))) (aref section 4)) (progn nil (or (progn nil (and (vectorp section) (>= ... 14) (memq ... cl-struct-magit-section-tags) t)) (signal (quote wrong-type-argument) (list (quote magit-section) section))) (aref section 5)))) args)
      magit-apply-diff([cl-struct-magit-section file "0001-New-names-pprint-command-to-pretty-print-entire-name.patch" #<marker (moves after insertion) at 205 in *magit: ~/Git-Projects/names/*> nil #<marker at 269 in *magit: ~/Git-Projects/names/*> nil nil nil nil nil nil [cl-struct-magit-section untracked nil #<marker (moves after insertion) at 113 in *magit: ~/Git-Projects/names/*> #<marker at 130 in *magit: ~/Git-Projects/names/*> #<marker at 269 in *magit: ~/Git-Projects/names/*> nil nil nil nil nil nil [cl-struct-magit-section status nil #<marker (moves after insertion) at 1 in *magit: ~/Git-Projects/names/*> nil #<marker at 270 in *magit: ~/Git-Projects/names/*> nil nil nil nil nil nil nil ([cl-struct-magit-section branch "elpa" #<marker (moves after insertion) at 1 in *magit: ~/Git-Projects/names/*> #<marker at 53 in *magit: ~/Git-Projects/names/*> #<marker at 113 in *magit: ~/Git-Projects/names/*> nil nil nil nil nil nil #2 ([cl-struct-magit-section branch "origin/elpa" #<marker (moves after insertion) at 53 in *magit: ~/Git-Projects/names/*> nil #<marker at 112 in *magit: ~/Git-Projects/names/*> nil nil nil nil nil nil #4 nil])] #1)] ([cl-struct-magit-section file "0001-Improve-names-top-of-namespace.patch" #<marker (moves after insertion) at 130 in *magit: ~/Git-Projects/names/*> nil #<marker at 172 in *magit: ~/Git-Projects/names/*> nil nil nil nil nil nil #1 nil] [cl-struct-magit-section file "0001-Improve-usage-example.patch" #<marker (moves after insertion) at 172 in *magit: ~/Git-Projects/names/*> nil #<marker at 205 in *magit: ~/Git-Projects/names/*> nil nil nil nil nil nil #1 nil] #0)] nil] nil)
      (let nil (magit-apply-diff it args))
      (if (null x) (let nil (magit-apply-diff it args)) nil)
      (let* ((x (cdr x))) (if (null x) (let nil (magit-apply-diff it args)) nil))
      (cond ((eq x (quote region)) (let* ((x (cdr x))) (if (null x) (let nil (magit-apply-region it args)) nil))) ((eq x (quote hunk)) (let* ((x (cdr x))) (if (null x) (let nil (magit-apply-hunk it args)) nil))) ((eq x (quote file)) (let* ((x (cdr x))) (if (null x) (let nil (magit-apply-diff it args)) nil))) (t nil))
      (let* ((x (car x))) (cond ((eq x (quote region)) (let* ((x (cdr x))) (if (null x) (let nil (magit-apply-region it args)) nil))) ((eq x (quote hunk)) (let* ((x (cdr x))) (if (null x) (let nil (magit-apply-hunk it args)) nil))) ((eq x (quote file)) (let* ((x (cdr x))) (if (null x) (let nil (magit-apply-diff it args)) nil))) (t nil)))
      (if (consp x) (let* ((x (car x))) (cond ((eq x (quote region)) (let* ((x (cdr x))) (if (null x) (let nil (magit-apply-region it args)) nil))) ((eq x (quote hunk)) (let* ((x (cdr x))) (if (null x) (let nil (magit-apply-hunk it args)) nil))) ((eq x (quote file)) (let* ((x (cdr x))) (if (null x) (let nil (magit-apply-diff it args)) nil))) (t nil))) nil)
      (let* ((x (cdr val))) (if (consp x) (let* ((x (car x))) (cond ((eq x (quote region)) (let* ((x ...)) (if (null x) (let nil ...) nil))) ((eq x (quote hunk)) (let* ((x ...)) (if (null x) (let nil ...) nil))) ((eq x (quote file)) (let* ((x ...)) (if (null x) (let nil ...) nil))) (t nil))) nil))
      (if (memq x (quote (staged unstaged))) (let* ((x (cdr val))) (if (consp x) (let* ((x (cdr x))) (if (null x) (let nil (user-error "Change is already in the working tree")) nil)) nil)) (let* ((x (cdr val))) (if (consp x) (let* ((x (car x))) (cond ((eq x (quote region)) (let* (...) (if ... ... nil))) ((eq x (quote hunk)) (let* (...) (if ... ... nil))) ((eq x (quote file)) (let* (...) (if ... ... nil))) (t nil))) nil)))
      (let* ((x (car val))) (if (memq x (quote (staged unstaged))) (let* ((x (cdr val))) (if (consp x) (let* ((x (cdr x))) (if (null x) (let nil (user-error "Change is already in the working tree")) nil)) nil)) (let* ((x (cdr val))) (if (consp x) (let* ((x (car x))) (cond ((eq x ...) (let* ... ...)) ((eq x ...) (let* ... ...)) ((eq x ...) (let* ... ...)) (t nil))) nil))))
      (if (consp val) (let* ((x (car val))) (if (memq x (quote (staged unstaged))) (let* ((x (cdr val))) (if (consp x) (let* ((x ...)) (if (null x) (let nil ...) nil)) nil)) (let* ((x (cdr val))) (if (consp x) (let* ((x ...)) (cond (... ...) (... ...) (... ...) (t nil))) nil)))) nil)
      (let* ((val (list (magit-diff-type) (magit-diff-scope)))) (if (consp val) (let* ((x (car val))) (if (memq x (quote (staged unstaged))) (let* ((x (cdr val))) (if (consp x) (let* (...) (if ... ... nil)) nil)) (let* ((x (cdr val))) (if (consp x) (let* (...) (cond ... ... ... ...)) nil)))) nil))
      (progn (magit-maybe-backup) (let* ((val (list (magit-diff-type) (magit-diff-scope)))) (if (consp val) (let* ((x (car val))) (if (memq x (quote (staged unstaged))) (let* ((x ...)) (if (consp x) (let* ... ...) nil)) (let* ((x ...)) (if (consp x) (let* ... ...) nil)))) nil)))
      (if it (progn (magit-maybe-backup) (let* ((val (list (magit-diff-type) (magit-diff-scope)))) (if (consp val) (let* ((x (car val))) (if (memq x (quote ...)) (let* (...) (if ... ... nil)) (let* (...) (if ... ... nil)))) nil))))
      (let ((it (magit-current-section))) (if it (progn (magit-maybe-backup) (let* ((val (list (magit-diff-type) (magit-diff-scope)))) (if (consp val) (let* ((x ...)) (if (memq x ...) (let* ... ...) (let* ... ...))) nil)))))
      magit-apply()
      funcall-interactively(magit-apply)
      call-interactively(magit-apply nil nil)
      command-execute(magit-apply)

Whereas if I hit `: am 0001-FULLPATCHNAME-.patch RET` the patch applies correctly.

Did I use the `a` key wrong? Is there a way to invoke `git am` from magit?

**Comment by tarsius** [comment]
Use `W p` (I might change that to `W W` for consistency with other popups) to create a patch and `w w` (`magit-am-apply-patches`) to apply it. `a` (`magit-apply`) is only for applying diffs. Unfortunately the same "section type" `file` is currently used for diffs as well as actual files - resulting in this error instead of some more useful error message explaining that `magit-apply` only works on diffs.

**Comment by Malabarba** [comment]
I see. Thanks for the clarification!

**Comment by Malabarba** [comment]
By the way, if you'd like to have a more informative error, you could do something like this inside `magit-apply`:

    (condition-case-unless-debug er
          (--when-let ...)
        (error (if (eq (car er) 'user-error)
                   (signal (car er) (cadr er))
                 (message "Failed with the following error. If you're applying a maildir patch, use `W m' instead.\n%S" er))))

Might be a little to “guessy” though.

**Comment by tarsius** [comment]
I have taught `magit-apply` about the "two types of files". For untracked files it now calls `magit-am-popup`. I hesitated to do this because it might break the consistency between the various "apply variants". But since `magit-discard` and possibly others also act on untracked files, this might actually increase the consistency. While it is not very likely it is possible that I change my mind about this and then change this to just an error message.

**Comment by Malabarba** [comment]
Nice! Thanks.
