### ISSUE TITLE
Advice about magit-process

### ISSUE THREAD

**Issue by Silex** [magit/magit#1902]
Hello,

I'm in need of pretty much exactly what magit-process does for another project. That is, run commands and get their output, all this in a sometimes asynchronous manner (e.g I don't want to hang emacs for long operations, but allow the user to show what's happening if he desires to like when we press `$`).

Do you think I should just inspire-copy-paste-adapt from magit-process.el or is it maybe meant to be reusable as a whole?

Thanks! :)

**Comment by tarsius** [comment]
> Do you think I should just inspire-copy-paste-adapt from magit-process.el or is it maybe meant to be reusable as a whole?

I would recommend that you just depend on magit for the time being. `magit-process` depends on quite a few other magit libraries, so while I have the intention to eventually turn it into an independent library, that's probably not gonna happen anytime soon.

As you said, just copying the relevant parts might also be an option. But see `makey` for an example where that did not pan out so well. So again - at least while `docker.el` is still under construction - it seems best to just depend on magit.

**Comment by Silex** [comment]
Ah, so it'd be feasible to just reuse magit-process with a bit of configuration/glue code. That's good news! I'll give it a try & report.

As always, thanks a lot!

**Comment by tarsius** [comment]
Yeah, `magit-start-process` and `magit-call-process` should work.
