### ISSUE TITLE
magit should add --find-renames to (most) issued git diff commands

### ISSUE THREAD

**Issue by doublep** [magit/magit#1904]
Currently, if you rename a file, change one line in it and stage the change, `magit-diff-staged`, for example, shows utterly useless diff from which you cannot understand what happened at all: all lines in the "old" file are shown as deleted, all lines in the "new" as added, including the modified line.

The output would be massively improved if diff added `--find-renames` option to the command line.

**Comment by tarsius** [comment]
Wait two weeks until `2.1.0` is released (or install the development branch now).

Then
* `d` bring up the diff popup
* `- m` add `--find-renames`
* `C-x C-s` save default arguments

This only affects `magit-diff-mode` buffers, to get the same effect in the status buffer, start with `D` and repeat the steps above.
