### ISSUE TITLE
magit-next + Tramp is not working

### ISSUE THREAD

**Issue by tshatrov** [magit/magit#1905]
When I go to magit-status on a file opened through Tramp pretty much every string is replaced with the following:

    /bin/sh: 172: cd: can't cd to /ssh:tshatrov@dev.[redacted]:/home/tshatrov/dev/[redacted]

I installed the latest Emacs version 24.5.1 and Git version 2.4.4 (on target machine) and it still doesn't work.

**Comment by tarsius** [comment]
I can reproduce this and have found the issue. Piuu, good thing you noticed this before the release.

I have a fix but first have to verify that it doesn't break anything else.

**Comment by tarsius** [comment]
Fixed in 34f99aea33fe9cb3cdb44472429161f85689eeb4.

**Comment by tshatrov** [comment]
Can confirm that this fixed magit-status for me.
