### ISSUE TITLE
Invalid function: with-current-buffer-window

### ISSUE THREAD

**Issue by tshatrov** [magit/magit#1906]
Also on magit-next. I go to "Show refs", select several branches with a region and press "k". The message "Invalid function: with-current-buffer-window" appears in minibuffer and nothing happens. Same happens if I press "b k". Deleting branches one by one works.

rgrep shows that with-current-buffer-window appears only once, in magit-utils.el, function magit-confirm, when multiple items need to be confirmed.

**Comment by tarsius** [comment]
Are you sure you are not using `24.4`? In `24.5` that function exists; it is defined in `window.el`. I need to double check that it exists in `24.4` too.

**Comment by tshatrov** [comment]
Magit 1.4.2-2277-gf7edcb7, Git 2.4.4, Emacs 24.5.1

    with-current-buffer-window is a Lisp macro in `window.el'.

I think the issue is that it's a macro, not a function? I recompiled the sources a few times and with-current-buffer-window still ends up in magit-utils.elc for some reason.

**Comment by tshatrov** [comment]
Actually now that I successfully compiled it I cannot reproduce the issue anymore, even after deleting all *.elc files and doing "make lisp". I guess it was some sort of glitch.

**Comment by tarsius** [comment]
I suspect you first compiled magit while still using an older emacs release.
