### ISSUE TITLE
idea: show merge commits with different (dimmed) face

### ISSUE THREAD

**Issue by vjohansen** [magit/magit#1909]
This is an idea for the 'next' branch.

I work with a lot of people who are new to git. They never rebase so the log is full of merge commits.

It could be nice if the subject lines for commits where greyed out via a face for this (even if you can use -s in log popup).

**Comment by tarsius** [comment]
Currently Magit doesn't know whether a commit is a merge when displaying a log. It can display the graph but as far as the code that deals with that this is just text.

I plan to improve logging eventually. The biggest problem with logging is the constant overhead that comes with `--graph`. We might end up drawing our own logs, based on information we get using `--parents`. Once (if) we do that we could also paint certain commits differently.

I am closing this in favor of #1425.
