### ISSUE TITLE
magit-revision-mode: no convenient way to copy the revision hash

### ISSUE THREAD

**Issue by npostavs** [magit/magit#1913]
Since 9d7145a04de149aafbb8dc02e95c339133e2f360 (use header-line in log and diff buffers), the hash of the commit is put in the header line, which means there is no convenient way to copy it.

**Comment by tarsius** [comment]
What about making `M-w` behave similarly to `C-w` but for the "thing in the buffer" instead of "at point"?

**Comment by npostavs** [comment]
I'm not sure what "thing in the buffer" would be in most cases. For `magit-revision-mode` in particular, copying the revision hash with `M-w` does seem sensible.

**Comment by tarsius** [comment]
That's bit of a hack.

There's already an issue about making "copy as kill" better: #1586.
