### ISSUE TITLE
Build with older emacs versions

### ISSUE THREAD

**Issue by elibarzilay** [magit/magit#1915]
It would be nicer (and easy) to check the `emacs` version and die if it's too old instead of barfing at a randomly undefined function...

**Comment by tarsius** [comment]
`2.1.0` which will be released in a few days already does that. But the check is performed pretty late in the loading process. Does it not kick in soon enough? With what Emacs version? What is the exact error?

**Comment by elibarzilay** [comment]
> `2.1.0` which will be released in a few days already does that.

I'm working off of the `next` branch -- does that correspond to
something else?

> But the check is performed pretty late in the loading process. Does it not kick in soon enough? With what Emacs version? What is the exact error?

I didn't see any check...  This is with 24.3.1, on a Fedora 20 machine.
Here's the full text:

```
make[1]: Entering directory `/home/eli/MyEmacs/magit/lisp'
Compiling with-editor.el

In toplevel form:
with-editor.el:444:1:Warning: Unused lexical variable `localname'

In end of data:
with-editor.el:687:1:Warning: the function `internal-default-process-filter'
    is not known to be defined.
Compiling git-commit.el

In end of data:
git-commit.el:667:1:Warning: the function `dired-get-filename' is not known to
    be defined.
Compiling magit-popup.el

In end of data:
magit-popup.el:1058:1:Warning: the function `string-suffix-p' is not known to
    be defined.
Compiling magit-utils.el

In end of data:
magit-utils.el:353:1:Warning: the function `with-current-buffer-window' is not
    known to be defined.
Compiling magit-section.el
Compiling magit-git.el
Compiling magit-mode.el

In magit-mode:
magit-mode.el:332:52:Warning: assignment to free variable
    `redisplay-highlight-region-function'
magit-mode.el:333:54:Warning: assignment to free variable
    `redisplay-unhighlight-region-function'
Compiling magit-process.el

In end of data:
magit-process.el:725:1:Warning: the function `dired-get-filename' might not be
    defined at runtime.
Compiling magit-core.el

In end of data:
magit-core.el:77:1:Warning: the function `dired-get-filename' is not known to
    be defined.
Compiling magit-diff.el

In toplevel form:
magit-diff.el:460:1:Error: Symbol's function definition is void: string-suffix-p
make[1]: *** [magit-diff.elc] Error 1
make[1]: Leaving directory `/home/eli/MyEmacs/magit/lisp'
make: *** [lisp] Error 2
```

**Comment by tarsius** [comment]
The `next` branch is what will be released as `2.1.0` - so they are "the same thing" as far as this discussion is concerned.

Once `2.1.0` has been released, most users will get it from an Elpa archive and then `package.el` takes care of telling users that emacs `24.4` is required. And the installation instructions very clearly state what the minimal required versions of Emacs and Git are. I don't think it is necessary to complicate the Makefiles further to display a more meaning full error. Users who build software manually should always read the installation instructions.

**Comment by tarsius** [comment]
Any suggestions on how to make this prettier?

**Comment by elibarzilay** [comment]
(Um, I was about to disagree, saying that there are still many people who will build from source, and that's with the habit of quickly skimming some INSTALL or README file very quickly, but you *did* fix it...  Thanks!)

As for making it easy -- yes, I thought about using Emacs itself, which doesn't rely on anything.  But seems that a bit easier than what you did would be to throw the error inside emacs.  So I think that one slight improvement would be to make it an elisp error in what you wrote (and make it a target so an error aborts the build).  But even better would be to add some `eval-when-compile` with the test and the error, and put it in some base utility file that all files require so no compilations will be successful and you'll get the error quickly.

(I would have suggested a patch, but I've dug myself into a hole of updating my distribution, motivated by switching to a newer Emacs but avoiding yet another full emacs build on top of the one in the system and the one from git.)

**Comment by tarsius** [comment]
That sounds more complicated - so I think I'll stick with what we have now.

**Comment by elibarzilay** [comment]
No complications -- I'm talking about putting this simple bit somewhere:

    (eval-when-compile
      (when (version< emacs-version "24.5")
        (error "\n\nYour emacs is too old\n")))

**Comment by tarsius** [comment]
Ah yes, that would work too.
