### ISSUE TITLE
2.1.0 -- Extension compatibility

### ISSUE THREAD

**Issue by tarsius** [magit/magit#1921]
* Magit `2.1.0` will be released on the **1th of July**. See #1645.
* Magit `2.1.0` was released on the **1th of July**! See #1941.

Maintainers of packages which depend on Magit are kindly asked to update as soon as possible.  If you can do it before Magit `2.1.0` is released that would be great, but I admit the notice is a bit short.

If you work on this before Magit `2.1.0` is released, then I recommend you use a separate branch and merge that into your `master` shortly after Magit's `next` is merged into `master`.

| Name                                                                                   | Maintainer     | Compatible   | Notes                         |
| -------------------------------------------------------------------------------------- | -------------- | ------------ | ----------------------------- |
| [cask-package-toolset](https://github.com/AdrieanKhisbe/cask-package-toolset.el)       | @AdrieanKhisbe | yes          |     |
| [gerrit-download](https://github.com/chmouel/gerrit-download.el)                       | @chmouel       | yes    |                               |
| [github-clone](https://github.com/dgtized/github-clone.el) | @dgtized       | yes          |   dgtized/github-clone.el#7                      |
| [jist](https://github.com/emacs-pe/jist.el)                                            | @emacs-pe      | yes     |                               |
| [magit-annex](https://github.com/magit/magit-annex/tree/master)                        | @kyleam        | yes |                               |
| [magit-filenotify](https://github.com/magit/magit-filenotify)                          | @ruediger      | yes        |                    |
| [magit-find-file](https://github.com/bradleywright/magit-find-file.el)                 | @bradleywright | yes           | bradleywright/magit-find-file.el#4 |
| [magit-gerrit](https://github.com/terranpro/magit-gerrit)                              | @terranpro     | yes | https://github.com/terranpro/magit-gerrit/commit/53b30ab4be0ac595c9226dacd4ec2216af7813be#commitcomment-11971914   |
| [magit-gh-pulls](https://github.com/sigma/magit-gh-pulls)                              | @sigma         | yes           | sigma/magit-gh-pulls#31       |
| [magit-gitflow](https://github.com/jtatarik/magit-gitflow)                             | @jtatarik      | yes |                               |
| [magit-stgit](https://github.com/magit/magit-stgit)                                    | @tarsius       | yes |                               |
| [magit-svn](https://github.com/magit/magit-svn)                                        | @tarsius       | yes | but:      https://github.com/milkypostman/melpa/issues/2895                         |
| [magit-topgit](https://github.com/magit/magit-topgit)                                  | @tarsius       | yes |                               |
| [magit-tramp](https://github.com/magit/magit-tramp)                                    | @sigma         | no           |  magit/magit-tramp#4      |
| [org-magit](https://github.com/magit/org-magit)                                        | @sigma         | no           | use successor `orgit` instead |
| [orgit](https://github.com/magit/orgit)                                                | @tarsius       | yes          |                               |
| [git-commit-training-wheels-mode](https://github.com/yasuyk/git-commit-training-wheels-mode) | @yasuky | no (not yet?) | [.../#1](https://github.com/yasuyk/git-commit-training-wheels-mode/issues/1) |

**Other packages**

| Name                                                                                   | Maintainer     | Compatible   | Notes                         |
| -------------------------------------------------------------------------------------- | -------------- | ------------ | ----------------------------- |
| [evil](https://bitbucket.org/lyro/evil/wiki/Home) | | pending | https://bitbucket.org/lyro/evil/pull-request/16/adapt-for-magit-v210/diff |

**Comment by AdrieanKhisbe** [comment]
@tarsius, why did you annotated cask-package-toolset with *should not depend on magit*? :)

I would say it's I only rely on `magit-get` so far, so it's a bit overkill to bring all magit as a dependancy. not entirely false :D
However I'm soon gonna need more for commit, tagging.

*Is there any other reason ?* or recommandation? :)

**Comment by tarsius** [comment]
@AdrieanKhisbe Because all you use is `magit-get` which could be trivially reimplemented but since you are going to use more from magit, I have removed that note now.

**Comment by AdrieanKhisbe** [comment]
@tarsius no problem :)

**Comment by bradleywright** [comment]
Thanks for the heads up, will see if I can get to this in time (looking forward to Magit 2.1.0!)

**Comment by ruediger** [comment]
magit-filenotify seems to work fine with the `next` branch. Thanks for the heads up.

(The el-get recipe will need updating though.)

**Comment by bradleywright** [comment]
:+1: just wanted to say thanks for the PR.

**Comment by chmouel** [comment]
:+1: and thanks!

**Comment by tarsius** [comment]
I have pushed the Magit release now!

**Comment by tarsius** [comment]
@chmouel So I assume that you have verified that gerrit-download works with v2.1.0, right? By the way you should change Package-Requires to depend on a release instead of a snapshot and create a tag. That way it can be installed from Melpa-Stable.

**Comment by chmouel** [comment]
yes just pushed my changes :)
