### ISSUE TITLE
2.1.0 -- Theme compatibility

### ISSUE THREAD

**Issue by tarsius** [magit/magit#1922]
* Magit `2.1.0` will be released on the **1th of July**. See #1645.
* Magit `2.1.0` was released on the **1th of July**! See #1941.

Maintainers of popular themes are kindly asked to update as soon as possible.  If you can do it before Magit `2.1.0` is released that would be great, but I admit the notice is a bit short.

If you work on this before Magit `2.1.0` is released, then I recommend you use a separate branch and merge that into your `master` shortly after Magit's `next` is merged into `master`.

The new manual has a section on [theming](http://magit.vc/manual/magit/Theming-Faces.html). TL;DR the quickest way to make a theme at least compatible with Magit `2.1.0` is to remove all current customization and then, at least in the first step, only theme the faces that conflict with `default` and possibly other essential faces.

You might also want to look at (my fork of) the light variant of the solarized theme. That's what I am using and the theme with the most complete theming for Magit. The screenshots on http://magit.vc use that theme, but they are a bit outdated.

| Name                                                                                          | Maintainer      | Compatible                          |
| --------------------------------------------------------------------------------------------- | --------------- | ----------------------------------- |
| light "default" theme                                                                         |                 | yes                                 |
| dark "default" theme                                                                          |                 | yes                                 |
| [zenburn](https://github.com/bbatsov/zenburn-emacs)                                           | @bbatsov        | yes bbatsov/zenburn-emacs#200   |
| [solarized](https://github.com/bbatsov/solarized-emacs)                                       | @thomasf        | yes bbatsov/solarized-emacs#189 |
| - [sanityinc's solarized variant](https://github.com/purcell/color-theme-sanityinc-solarized) | @purcell        | yes                             |
| - [sellout's solarized variant](https://github.com/sellout/emacs-color-theme-solarized)       | @sellout        | unknown                             |
| [sanityinc-tomorrow](https://github.com/purcell/color-theme-sanityinc-tomorrow)               | @purcell        | yes                            |
| [monokai](https://github.com/oneKelvinSmith/monokai-emacs)                                    | @oneKelvinSmith | unknown                             |
| [leuven](https://github.com/fniessen/emacs-leuven-theme)                                      | @fniessen       | unknown                             |
| [base16](https://github.com/mkaito/base16-emacs)                                              | @mkaito         | unknown                             |
| [ample](https://github.com/jordonbiondo/ample-theme)                                          | @jordonbiondo   | in progress                             |
| [moe](https://github.com/kuanyui/moe-theme.el)                                                | @kuanyui        | yes                             |
| [various themes by owainlewis](https://github.com/owainlewis/emacs-color-themes)              | @owainlewis     | unknown                             |
| [cyberpunk](https://github.com/n3mo/cyberpunk-theme.el)                                       | @n3mo           | unknown                             |
| [anti-zenburn](https://github.com/m00natic/anti-zenburn-theme)                                | @m00natic       | unknown                             |
| [molokai](https://github.com/alloy-d/color-theme-molokai)                                     | @alloy-d        | unknown                             |
| [alect](https://github.com/alezost/alect-themes)                                              | @alezost        | yes                             |
| [grandshell](https://github.com/steckerhalter/grandshell-theme)                               | @steckerhalter  | yes                             |
| [tangotango](https://github.com/juba/color-theme-tangotango)                                  | @juba           | yes (default)                             |
| [ample-zen](https://github.com/mjwall/ample-zen)                                              | @mjwall         | unknown                             |
| [noctilux](https://github.com/sjrmanning/noctilux-theme)                                      | @sjrmanning     | unknown                             |
| [afternoon](https://github.com/osener/emacs-afternoon-theme)                                  | @osener         | unknown                             |
| [soothe](https://github.com/emacsfodder/emacs-soothe-theme)                                   | @emacsfodder    | unknown                             |
| [subatomic](https://github.com/cryon/subatomic)                                               | @cryon          | yes                             |

**Comment by tarsius** [comment]
The light and dark variant of the "default" theme (i.e. no theme) should work for many values for `default`s foreground and background.

* For the dark variant I used `:background "gray15" :foreground "gray80"` for the `default` face
* For the light variant I used `:background "gray90" :foreground "gray15"` for the `default` face

If the actual default `:background` and `:foreground` depart to much from that, then the highlighting might be to light/dark - but everything should still be readable.

**Comment by steckerhalter** [comment]
@tarsius I have already adapted `grandshell` to work with the next branch (since I'm using that myself). cheers...

**Comment by mkaito** [comment]
I do not use magit, but the base16 themes include some magit-specific stuff. If anyone would like to take a shot, you will need to send a pull request to base16-builder. My repo only provides a MELPA compatible package of the resulting files.

Specifically, this is where you need to do your edits: https://github.com/chriskempson/base16-builder/tree/master/templates/emacs

**Comment by n3mo** [comment]
Thanks for the heads up. I'll take a look asap and update cyberpunk. Cheers!

**Comment by alezost** [comment]
I added support for new magit faces to `alect-themes` several months ago: 
https://github.com/alezost/alect-themes/commit/1b7a25caaeadb46e7a6b2b4451c72b168cde8731.

And thank you very much for your **tremendous** work on the new shiny magit!

**Comment by jordonbiondo** [comment]
Thanks for the heads up, I'll work getting compliant as soon as I can.

**Comment by cryon** [comment]
Just started to add the new faces to Subatomic. Will hopefully be done within a few days.

**Comment by kuanyui** [comment]
The support of `moe-theme` for Magit 2.x has been under progress.
But I'm using an older version Git, and cannot understand the meanings of some new faces (e.g. `magit-sequence-*`).

**Comment by tarsius** [comment]
A sequence is any operation that applies several commit in a row. In Git that term isn't used as prominently as I am using it. In Git "sequencer" is used for code shared between `revert` and `cherry-pick`.

**Comment by kuanyui** [comment]
@tarsius Can I have a screeshot, or the way to show the buffer which contains these faces?

**Comment by cryon** [comment]
@kuanyui @tarsius I would appreciate some guidance regarding the new faces as well. My plan is to color all the faces I can find and let the ones I can't find inherit _default_ for now.

**Comment by tarsius** [comment]
I have pushed the Magit release now!

**Comment by cryon** [comment]
Great Job! Magit is the best! :beers: :cake: :dancers:

**Comment by kuanyui** [comment]
Support for Magit2 has been done in `moe-theme`.

**Comment by juba** [comment]
`tangotango-theme` doesn't have many custom magit faces, so I reverted to the default magit 2.1.0 faces  which seem to look fine. Thanks !

**Comment by cryon** [comment]
@tarsius Initial support for magit 2.1.0 is now availible in subatomic-theme.

**Comment by purcell** [comment]
I've updated the `sanityinc-solarized` and `sanityinc-tomorrow` themes too, at least partially. Thanks, @tarsius, for outlining the necessary changes and making it easy for us.

**Comment by tarsius** [comment]
Great. Thanks!

**Comment by n3mo** [comment]
I've been delayed by other things of late, but I've updated by falling back to the default faces in cyberpunk for now. I will, hopefully very soon, be adding explicit support. To be continued...

**Comment by jordonbiondo** [comment]
I've pushed some basic support for ample-theme and ample-flat theme, alot of the default colors look nice so I may not even change anything else. Magit 2.1 has been an improvement in every way, keep up the awesome work @tarsius!

**Comment by mkaito** [comment]
I've sent a PR upstream removing any magit faces from base16. As far as I can tell, the defaults look fine. If there are any issues, please submit an issue or PR to https://github.com/chriskempson/base16-builder
