### ISSUE TITLE
2.1.0 -- Starter-Kit compatibility

### ISSUE THREAD

**Issue by tarsius** [magit/magit#1923]
* Magit `2.1.0` will be released on the **1th of July**. See #1645.
* Magit `2.1.0` was released on the **1th of July**! See #1941.

Maintainers of starter-kits are kindly asked to update as soon as possible.  If you can do it before Magit `2.1.0` is released that would be great, but I admit the notice is a bit short.

| Name              | Maintainer   | Compatible                                                    |
| ----------------- | ------------ | ------------------------------------------------------------- |
| spacemacs         | @syl20bnr    | yes https://github.com/magit/magit/issues/1918,  https://github.com/syl20bnr/spacemacs/pull/2130         |
| bbatsov's prelude | @bbatsov     | yes https://github.com/bbatsov/prelude/pull/868          |
| purcell's emacs.d | @purcell     | yes https://github.com/purcell/emacs.d/pull/275          |
| starter-kit v2    | @technomancy | no |
| [eschulte's starter-kit](https://github.com/eschulte/emacs24-starter-kit)| @eschulte | pending  eschulte/emacs24-starter-kit#75, #1944 |

**Comment by technomancy** [comment]
I'd imagine there's lots of broken stuff in ESK at this point; one more package isn't going to make much of a difference. =)

**Comment by tarsius** [comment]
@technomancy I figured that was the case :-) Thanks for replying.

**Comment by purcell** [comment]
So awesome that you've provided this fixes. Thanks again for all your hard work @tarsius.

**Comment by syl20bnr** [comment]
Thank you @tarsius :+1: 
I merged/squashed a bunch of PR with magit 2.1 and I think Spacemacs is now ready.

**Comment by tarsius** [comment]
I have pushed the Magit release now!

**Comment by log0ymxm** [comment]
Prelude mode with prelude-evil doesn't look to have been addressed yet. It seems to mostly work, [here's the relevant el](https://github.com/bbatsov/prelude/blob/master/modules/prelude-evil.el#L110-L121). Is there anything that should be updated here?

One issue, the `k` key will call `evil-previous-line` unless an item is highlighted, which will then call `magit-discard`. Even if I try to manually set `(define-key magit-status-mode-map (kbd "k") 'evil-previous-line)` it doesn't seem to work. What can I look at to fix this?

**Comment by tarsius** [comment]
I would like to ship an evil configuration with magit. See #1968.

**Comment by eschulte** [comment]
I've applied the referenced commit to my starter kit.  Please let me know if there is anything else I can do that would be helpful.

Thanks,
Eric

**Comment by tarsius** [comment]
Thanks @eschulte.

You probably want to add:

```lisp
(global-set-key (kbd "C-x g") 'magit-status)
(global-set-key (kbd "C-x M-g") 'magit-dispatch-popup)
```

**Comment by eschulte** [comment]
Applied
