### ISSUE TITLE
Push process hangs over

### ISSUE THREAD

**Issue by llcc** [magit/magit#1924]
I am attempting to push to  my GitHub repository using Magit in Emacs 24.5 on windows. I committed my update, then magit buffer shows there are unpushed commits, then I call P twice to push it. But the process seems to hang over there. 

I use `list-process` to open the magit-process buffer, the message is 
```
c:\Program Files (x86)\Git\bin\git.exe --no-pager -c core.preloadindex=true push -v origin gh-pages:refs/heads/gh-pages
Pushing to git@github.com:llcc/layatjpy.git
```
it shows "pushing", but seems no end. So what happened?

**Comment by npostavs** [comment]
Hi, have you read https://github.com/magit/magit/wiki/Pushing-with-Magit-from-Windows?

**Comment by llcc** [comment]
@npostavs  I tried "(setenv "GIT_ASKPASS" "git-gui--askpass")", but no effect. And I can push it to github from command line successfully.

**Comment by npostavs** [comment]
It looks you are using an ssh url, do have to enter your passphrase from the command line? Or have you setup ssh-agent?

**Comment by llcc** [comment]
Yes, I entered my passphrase from command line.

**Comment by npostavs** [comment]
Okay, so https://github.com/magit/magit/wiki/Pushing-with-Magit-from-Windows#openssh-passphrase-caching-via-ssh-agent applies, but I'm about to replace the text of that section with pretty much just "install [ssh-agency]".

[ssh-agency]: https://github.com/magit/ssh-agency

**Comment by llcc** [comment]
Hi @npostavs ,

How can i:
Add the following lines to Github's agent_start function:
```
sed -rn 's/^([^=]+)=([^;]+);.*/set \1=\2/p' "$env" > "$env".cmd
sed -rn 's/^([^=]+)=([^;]+);.*/(setenv "\1" "\2")/p' "$env" > "$env".el
```

**Comment by llcc** [comment]
when i try to paste it to command line, error appears:
`sed: -e expression #1, char 1: unknown command: `''`

**Comment by npostavs** [comment]
Yeah the setup there is a bit complicated, which is why I wrote ssh-agency.

I haven't uploaded to MELPA yet, but you can try downloading https://github.com/magit/ssh-agency/raw/master/ssh-agency.el, and then running `M-x package-install-file RET path/to/ssh-agency.el RET`, that should (in theory) just make it all work.

**Comment by llcc** [comment]
@npostavs  I opened `ssh-agency.el` in emacs, and `eval-buffer`. Therefore, all the configuration should be done according to your description. Then I tried to push again, but still can not make it.

**Comment by npostavs** [comment]
Hmm, I think the problem may be that I was testing ssh-agency using magit `next`, but I guess you're using magit from melpa which is 1.4.x.

Try `M-: (ssh-agency-ensure) RET`. It should ask for your passphrase from a console (aka dosbox). Pushing with magit should work after that.

**Comment by llcc** [comment]
The produced console disappeared immediately, so could not input passphrase.

**Comment by npostavs** [comment]
I guess maybe you have ssh exes in a non-standard place, or you have non-default name for your ssh key?

Can you check the result of evaluating:
```elisp
(list ssh-agency-add-executable (file-executable-p ssh-agency-add-executable)
      ssh-agency-agent-executable (file-executable-p ssh-agency-agent-executable))
```

You should get something like
`("c:/Program Files (x86)/Git/bin/ssh-add.exe" t "c:/Program Files (x86)/Git/bin/ssh-agent.exe" t)`

Also try running
```elisp
(call-process-shell-command
 (concat "start /WAIT \"ssh-add\" cmd /K" (shell-quote-argument ssh-agency-add-executable)))
```
You'll have to exit the console before continuing with Emacs.

**Comment by llcc** [comment]
Exactly as what you said.

**Comment by npostavs** [comment]
> Exactly as what you said.

??

What was the output on the console for the second command?

**Comment by llcc** [comment]
![image](https://cloud.githubusercontent.com/assets/3996879/8395643/47f27610-1db8-11e5-9abe-72fd5abb15c2.png)
nothing else..

**Comment by npostavs** [comment]
Huh. What happens if you run `"c:/Program Files (x86)/Git/bin/ssh-add.exe"` at that console?

**Comment by llcc** [comment]
With "" and path both input, actually nothing happens.

**Comment by npostavs** [comment]
Do you know the path to your ssh key? Does running `"c:/Program Files (x86)/Git/bin/ssh-add.exe" path/to/your/key` work? What does `"c:/Program Files (x86)/Git/bin/ssh-add.exe" -l` output?

**Comment by llcc** [comment]
Okay, it seems like that this time the input prompt can appear, like:
![image](https://cloud.githubusercontent.com/assets/3996879/8395695/ba7569a2-1dba-11e5-967d-3dcc5a75e383.png)

**Comment by npostavs** [comment]
Oh, I think the problem is that you don't set `HOME` as a Windows env variable, so from a Windows application point of view, your key is in a non-standard place. Whereas, when you open Git Bash, it sets `HOME` to `c:/Users/admin`, so ssh finds key where it expects.

So now that you have added your key, you should be able to push with magit. I will update `ssh-agency` so you don't have to go through this dance every time you startup.

**Comment by llcc** [comment]
It is really weird. As you told, the key has been already added by my operation just now. But the same problem still exist. And I should tell you that, every time when try to `git push origin gh-pages`, I need to input the passphrase.

**Comment by npostavs** [comment]
> It is really weird. As you told, the key has been already added by my operation just now. But the same problem still exists.

Hmm, that is weird. What's the return value of `M-: (ssh-agency-status) RET`?

> And I should tell you that, every time when I try to `git push origin gh-pages`, I need to input the passphrase.

Well, if you didn't tell bash where to find the agent that is expected. If you do `export SSH_AUTH_SOCK=xxx; export SSH_AGENT_PID=yyy` where `xxx` and `yyy` would be the values from `(getenv "SSH_AUTH_SOCK")` and `(getenv "SSH_AGENT_PID")` respectively then it might work.

**Comment by llcc** [comment]
>Hmm, that is weird. What's the return value of M-: (ssh-agency-status) RET?

Its value is t.

Okay, I will assign the value to the respective key. But the `(getenv "SSH_AUTH_SOCK")` result is ` "/tmp/ssh-9fDDO6nDBHug/agent.8956`, which does not point to the default location. Is that normal? I am afraid even I do it, but next time another temp file will be generated.

**Comment by npostavs** [comment]
> Its value is t.

In that case, you should be able to push, unless you have multiple keys and you added the wrong one? I'm pretty much stumped. Maybe try using putty instead: https://github.com/magit/magit/wiki/Pushing-with-Magit-from-Windows#using-ssh-keys-with-putty

> But the (getenv "SSH_AUTH_SOCK") result is "/tmp/ssh-9fDDO6nDBHug/agent.8956, which does not point to the default location. Is that normal?

It's normal for the socket file to be a temporary that changes each time you start ssh-agent (which should happen only once per login).

> I am afraid even I do it, but next time another temp file will be generated.

Well `ssh-agency` was supposed to write `~/.ssh/agent.env` with those temp settings, so you would be able to just source that file from bash, but I think that ends up at `C:\Users\admin\AppData\Roaming\.ssh/agent.env` for you, and since `C:\Users\admin\AppData\Roaming\.ssh` probably doesn't exist the write likely failed.

**Comment by llcc** [comment]
>In that case, you should be able to push, unless you have multiple keys and you added the wrong one? I'm pretty much stumped.

I just installed and configured it once, and I search my files. There is one agent.env file for sure. ......But still can not push... Confused.

Thanks for the explaining, but there must something into it.

**Comment by npostavs** [comment]
> There is one agent.env file for sure.

Oh, then maybe I was wrong about the different `HOME`s thing. What exactly is the value you have for `ssh-agency-env-file`?

> Thanks for the explaining, but there must something into it.

We can try a bit more troubleshooting, post the output from running the following commands in Git Bash:
```shell
. ~/.ssh/agent.env # adjust the path here, if necessary
ps | grep '[s]sh-agent' # no pgrep :(
ssh-add -l
ssh -vT git@github.com
```

**Comment by tarsius** [comment]
I made a slight change to your recipe, for clarity.

**Comment by llcc** [comment]
>Oh, then maybe I was wrong about the different HOMEs thing. What exactly is the value you have for ssh-agency-env-file?

Its value is `"c:/Users/admin/GoogleDrive/Git/Configurations/Emacs/.ssh/agent.env"`

>post the output from running the following commands in Git Bash:
![image](https://cloud.githubusercontent.com/assets/3996879/8398826/35df4102-1e39-11e5-943e-0c9fa7c4850a.png)

**Comment by npostavs** [comment]
In that screen shot, it looks like ssh *didn't* ask for passphrase, so things are working. Does a `git push` (or `git fetch`) from that shell ask for a passphrase? If yes, then is it possible you have multiple ssh installations, and git is using a different one (does `echo $GIT_SSH` print anything?)?

**Comment by llcc** [comment]
>.If you do export `SSH_AUTH_SOCK=xxx; export SSH_AGENT_PID=yyy` where `xxx` and `yyy` would be the values from `(getenv "SSH_AUTH_SOCK")` and `(getenv "SSH_AGENT_PID")` respectively then it might work.

I tried this, then i do not need to input passphrase in git bash, but still can not push in Magit.
When i reopen a new git bash, need to input again.

>In that screen shot, it looks like ssh didn't ask for passphrase, so things are working. Does a git push (or git fetch) from that shell ask for a passphrase? If yes, then is it possible you have multiple ssh installations, and git is using a different one (does echo $GIT_SSH print anything?)?

Yes, after apply that snippet, do not need to input anymore. But if I reopen git bash again, still need.

>does echo `$GIT_SSH` print anything?

It prints nothing.

PS: I need to mention that i am using portable msysgit.
Thanks for your patience^-^.

**Comment by npostavs** [comment]
> I tried this, then i do not need to input passphrase in git bash, ...
> When i reopen a new git bash, need to input again.
> 
> Yes, after apply that snippet, do not need to input anymore. But if I reopen git bash again, still need.

This is expected (you can source the agent.env file from your .bashrc so it automatically happens every time you open git bash).

> but still can not push in Magit.

This is still a mystery.

Try writing the following in `c:/users/admin/.ssh/config`:
```ini
# -*- mode: conf-unix -*-
Host github.com
     LogLevel DEBUG1
```
then in Emacs `M-: (setenv "GIT_TRACE" "1")`, and do a push from magit. Magit's process buffer should get a bunch of debug info. Then let's compare that output to running `GIT_TRACE=1 git push` from git bash (after you sourced agent.env).

> I need to mention that i am using portable msysgit.

Where did you get it from? I can't find a recent link (only links to the obsolete Google code page).

**Comment by llcc** [comment]
I tried, but still no effect, still need to input.
Then i applied the git command in shell, and found that I can not push it from shell but can from git bash with inputting the passphrase. Here is the output of shell:

![image](https://cloud.githubusercontent.com/assets/3996879/8406206/244051a0-1e95-11e5-9018-5e98e35f2216.png)

**Comment by llcc** [comment]
I reset my windows before, so I still use the execute files of previous windows.

**Comment by npostavs** [comment]
> I tried, but still no effect, still need to input.

I'm a bit lost, which part did you try? What do you mean by "need to input" exactly?

> Here is the output of shell:

It looks like the `c:/users/admin/.ssh/config` didn't take effect. Not sure why. Also, github didn't like your public key??

> I reset my windows before, so I still use the execute files of previous windows.

I'm not sure what this refers to? The portable msysgit? Maybe your git is too old for magit? What's the output of `git --version`?

**Comment by llcc** [comment]
>I'm a bit lost, which part did you try? What do you mean by"need to input" exactly?

Sorry, I tried what you told me: new config file and apply `(setenv "GIT_TRACE" "1")`, and this is the trace output from emacs:
![image](https://cloud.githubusercontent.com/assets/3996879/8407004/60cfbaa4-1e9d-11e5-9a7f-0038f3f1dab7.png)

And, this is the output in git bash:
![image](https://cloud.githubusercontent.com/assets/3996879/8407014/7631970a-1e9d-11e5-8f40-af8fcdeb3449.png)
![image](https://cloud.githubusercontent.com/assets/3996879/8407022/888878e2-1e9d-11e5-9297-529936273748.png)

Magit almost does nothing.

>I'm not sure what this refers to? The portable msysgit? Maybe your git is too old for magit? What's the output of git --version?

I reinstalled my windows 7 and still use the git files of previous windows. My git version is `1.9.2.msysgit.0`

**Comment by npostavs** [comment]
> and this is the trace output from emacs:

Ah, that's interesting, apparently the ssh config didn't apply Emacs, but it does in git bash. How do you tell Emacs where to find your init.el? Are you setting `HOME`? Perhaps this confuses msysgit/ssh.

**Comment by llcc** [comment]
Yes, I add Emacs HOME in the registry, and let emacs find its init file.  

>Are you setting HOME? Perhaps this confuses msysgit/ssh.

Can you tell me other way to setup this?

**Comment by npostavs** [comment]
> Yes, I add Emacs HOME in the registry, and let emacs find its init file.

Ah, I think it all makes sense now. Emacs sets the `HOME` environment variable from the registry, while msysgit's computes `HOME` in a different way. Except when you call git from Emacs, it see the `HOME` that Emacs set, so it looks for all the known_hosts, key, and config files in the wrong place.

> Can you tell me other way to setup this?

Probably the simplest thing is to set `HOME` globally for all Windows programs. See http://www.computerhope.com/issues/ch000549.htm#windows7 (but make a new User `HOME` variable, instead of editing the System `PATH` variable).

This means you'll have to move your Emacs config, or your ssh config to the new common `HOME`.

**Comment by llcc** [comment]
Okay, thanks @npostavs , i will give it a shot and tell you results. Thanks for your great help!

**Comment by llcc** [comment]
@npostavs  Finally it turned out it is really a  `HOME` setup problem. Now everything works very well, both in magit and git bash, thanks a lot for your help!!

**Comment by npostavs** [comment]
I think missing a setting for `HOME` is probably the reason behind a lot of previous reports of not being able to push (I had previously assumed it was just a matter of passphrases). I have always set `HOME` (because I don't like Emacs' default choice for it) but it never occurred to me that this was the reason it was working for me and not for others.

I updated [Pushing-with-Magit-from-Windows](https://github.com/magit/magit/wiki/Pushing-with-Magit-from-Windows) with this info, along with some of the troubleshooting steps we used here; all in all I think this issue turned out to be very productive! Thanks for your persistence, I was about to give up half way! :D

**Comment by tarsius** [comment]
Thanks @npostavs and @llcc!

@npostavs when I last checked I saw you added some `$HOME` magic and then removed it again because it did not work as expected. Do you think there might be a way to detect whether `$HOME` is correct and then semi-automatically fix it?

**Comment by npostavs** [comment]
The original `$HOME` is overwritten on Emacs startup, so it's impossible to detect this from within Emacs short of delving into the registry (Emacswiki [claims this is possible][1], but that idea seems way too scary for me).

Maybe we could provide a bat file for the user to run.

[1]: http://www.emacswiki.org/emacs/MsWindowsRegistry#toc14

**Comment by tarsius** [comment]
> I updated Pushing-with-Magit-from-Windows with this info,

Looks good.
