### ISSUE TITLE
git stash clear in magit

### ISSUE THREAD

**Issue by ChillarAnand** [magit/magit#1926]
i have to remove all stashes from a repo. from command line i would do `git stash clear`. i couldn't find anything such in magit.

**Comment by tarsius** [comment]
For support please use one of the places suggest here: https://github.com/magit/magit#support.

**Comment by ChillarAnand** [comment]
@tarsius there is an option to drop all stashes(https://github.com/magit/magit/blob/master/lisp/magit-stash.el#L163) and it is not working for me and other users http://emacs.stackexchange.com/questions/14024/magit-how-to-drop-all-stashes-at-once

**Comment by kyleam** [comment]
If you have your point on the "Stashes" header, `k` will offer to drop all stashes.  You can also highlight several stash lines and press `k`, and it will offer to drop all of those lines.

**Comment by ChillarAnand** [comment]
@kyleam  that was the expected behaviour. i am not able to get it work.

**Comment by kyleam** [comment]
I can't reproduce this with "emacs -Q".  

Please provide more information than "not working".  Is it prompting you like it should?  Is it giving an error?  Printing any messages?  What is in the process buffer?

**Comment by ChillarAnand** [comment]
> If you have your point on the "Stashes" header, k will offer to drop all stashes.

It is just asking for a number to drop stash.

> You can also highlight several stash lines and press k, and it will offer to drop all of those lines.

Even for this it is asking for a stash number to drop

**Comment by tarsius** [comment]
I think you are using an old Magit version.

**Comment by rafadc** [comment]
@tarsius , you are right. This was happening to me. For some reason package list said that there weren't any updates. I uninstalled magit using the package manager a new version was there.

The old version number from melpa was magit-90150116 so maybe it was thinking that 2.1.1 was older.
