### ISSUE TITLE
Should SPC and RET show commits consistently?

### ISSUE THREAD

**Issue by kyleam** [magit/magit#1927]
In magit-log-mode, hitting SPC on a commit will display the relevant
revision buffer, while RET will display and switch to it. I like this
behavior and find myself expecting it throughout Magit. SPC and RET
also behave this way for commits in the main section
magit-status-mode, but in magit-refs-mode or in the headers of
magit-status-mode, both RET and SPC switch to the buffer.  Also,
git-rebase-mode only provides a way to switch to the revision buffer
for the commit at point (bound to RET), but not a way to only display
it.

[Updated wording to clarify.]

**Comment by tarsius** [comment]
> in magit-refs-mode or in the headers of magit-status-mode, both RET and SPC switch to the buffer.

That turned out to be a regression.

> git-rebase-mode only provides a way to switch to the revision buffer for the commit at point (bound to RET), but not a way to only display it.

SPC works here too now.

**Comment by kyleam** [comment]
Great. Thank you.
