### ISSUE TITLE
Interactive magit-diff does not support A...B range

### ISSUE THREAD

**Issue by kyleam** [magit/magit#1931]
The `magit-diff` docstring says that a `A...B` format range can be
used, but `magit-read-range-or-commit` returns `A..B` when `A...B` is
given.

**Comment by tarsius** [comment]
Hm, there is more wrong with `magit-read-range-or-commit` than just that. Don't know whether I can fix this before the release.

**Comment by garyo** [comment]
Is there a workaround to get the diff of a branch?  (master...my-branch)

**Comment by kyleam** [comment]
Here are the workarounds I can think of, but there may be other
obvious ones I'm missing.

-   If the branch tracks the branch you want to diff with, you can call
    magit-diff-dwim with point on the feature branch.

-   Diff with the common ancestor instead (which, depending on how much
    the upstream and feature branch have diverged and on the stucture of
    the project history, may be easy to visually locate and grab from the
    log).

-   Wrap magit-diff with your own interactive function that passes a range
    to magit-diff, sidestepping magit-read-range-or-commit.
    
        (defun my/magit-diff (range)
          (interactive "sRange: ")
          (magit-diff range))

**Comment by kyleam** [comment]
How about following magit-log-read-revs?

```diff
diff --git a/lisp/magit-git.el b/lisp/magit-git.el
index d0e5c2f..fc2c260 100644
--- a/lisp/magit-git.el
+++ b/lisp/magit-git.el
@@ -891,19 +891,27 @@ (defun magit-read-branch-or-commit (prompt &optional secondary-default)
       (user-error "Nothing selected")))
 
 (defun magit-read-range-or-commit (prompt &optional secondary-default)
-  (or (let ((crm-separator "\\.\\.\\.?"))
-        (mapconcat 'identity
-                   (completing-read-multiple
-                    (concat prompt ": ")
-                    (magit-list-refnames) nil nil nil 'magit-revision-history
-                    (--if-let (magit-region-values 'commit 'branch)
-                        (concat (car (last it)) ".." (car it))
-                      (deactivate-mark)
-                      (or (magit-branch-or-commit-at-point)
-                          secondary-default
-                          (magit-get-current-branch))))
-                   ".."))
-      (user-error "Nothing selected")))
+  (let* ((choose-completion-string-functions
+          '(crm--choose-completion-string))
+         (minibuffer-completion-table #'crm--collection-fn)
+         (minibuffer-completion-confirm t)
+         (crm-completion-table (magit-list-branch-names))
+         (crm-separator "\\.\\.\\.?")
+         (default (or (--when-let (magit-region-values 'commit 'branch)
+                        (deactivate-mark)
+                        (concat (car (last it)) ".." (car it)))
+                      (magit-branch-or-commit-at-point)
+                      secondary-default
+                      (magit-get-current-branch)))
+         (input (read-from-minibuffer
+                 (format "%s (%s): " prompt default)
+                 nil crm-local-completion-map
+                 nil 'magit-revision-history
+                 default)))
+    (when (string-equal input "")
+      (or (setq input default)
+          (user-error "Nothing selected")))
+    input))
```

**Comment by tarsius** [comment]
Good suggestion. I have committed the proposed patch.

In the future we might want to abstract this to avoid the duplication. Or not - we'll see.

**Comment by kyleam** [comment]
Thanks (and get some sleep).

**Comment by tarsius** [comment]
Oh, yes. Forgot about that :-)
