### ISSUE TITLE
ediff via magit leaves ediff-related "mess" buffers after exiting

### ISSUE THREAD

**Issue by tee3** [magit/magit#1934]
First, of all, thanks for all the hard work on `magit`, it's an invaluable tool for the Emacs community :)

I suppose behavior could be intended, or considered either a bug or "performance" issue on the `next` branch.

```
(magit-version)
Magit 1.4.2-2307-gc8bb9ef, Git 2.4.5, Emacs 24.5.1
```

When using `ediff` via `magit`, I end up with lots of temporary  `ediff` buffers after quitting.  I just learned that `ediff` provides a mechanism to query to remove the A/B/C files when quitting an `ediff` session by running `C-u q` when quitting an `ediff` session, which provides a way to remove the temporary file version buffers.  I think this is a good approach for these files as one might want to inspect the full files.

However, there are also lots of intermediate buffers that are normally cleaned up when quitting an `ediff` session via `ediff-cleanup-mess`.  This is run by default by the `ediff-quit-hook` when run outside of `magit`.  When run from `magit`, the `ediff-quit-hook` is modified for `magit`-specific purposes, but seems to somehow not include the value of the initial value of `ediff-quit-hook`.  I'm not sure if this is by design or a bug, but the code seems to think `ediff-cleanup-mess` will be run (see `magit-ediff-compare`).

Either way the extra buffers are quite a burden to get rid of after inspecting differences from `magit` in an Emacs session.

The value of `ediff-quit-hook` when started from `magit-diff-compare` is the following on my system via `describe-variable`.  Note that other `magit-ediff-*` commands may have different `ediff-quit-hooks`, but none include `diff-cleanup-mess`.

```
ediff-quit-hook is a variable defined in `ediff-init.el'.
Its value is shown below.

  This variable may be risky if used as a file-local variable.

Documentation:
Hooks to run in the Ediff control buffer after finishing Ediff.

You can customize this variable.

Value: ((lambda nil
   (and
    (buffer-live-p ediff-buffer-B)
    (buffer-modified-p ediff-buffer-B)
    (with-current-buffer ediff-buffer-B
      (magit-update-index)))
   (and
    (buffer-live-p ediff-buffer-C)
    (buffer-modified-p ediff-buffer-C)
    (with-current-buffer ediff-buffer-C
      (when
	  (y-or-n-p
	   (format "Save file %s? "
		   (buffer-file-name)))
	(save-buffer))))
   (ediff-kill-buffer-carefully ediff-buffer-A)
   (ediff-kill-buffer-carefully ediff-buffer-B)
   (ediff-kill-buffer-carefully ediff-buffer-C)
   (set-window-configuration #<window-configuration>))
 t)

Original value was nil
Local in buffer *Ediff Control Panel*; global value is 
(ediff-cleanup-mess)
```

**Comment by tarsius** [comment]
Actually `ediff-cleanup-mess` is run, because `t` is a member of the local value of the hook. But it had no effect as explained in the commit which fixes this issue.

**Comment by tee3** [comment]
Thanks and thanks for the explanation!
