### ISSUE TITLE
MAGIT 2.1.0 RELEASED

### ISSUE THREAD

**Issue by tarsius** [magit/magit#1941]
**[Related issues](https://github.com/magit/magit/milestones/2.1.0)** | **[Update instructions](http://magit.vc/manual/magit/Installation.html)** | **[Old release roadmap](https://github.com/magit/magit/issues/1645)**

----

**Please carefully read the [update instructions](http://magit.vc/manual/magit/Installation.html) and possibly the [release notes](https://raw.githubusercontent.com/magit/magit/master/Documentation/RelNotes/2.1.0.txt).**

----

## Compatibility

* Extensions #1921
* Themes #1922
* Starter-kits #1923
* Package Archives #1952

**Comment by dunn** [comment]
Should be in Homebrew soon: Homebrew/homebrew#41258

**Comment by tarsius** [comment]
Thanks!

**Comment by stshine** [comment]
Thanks for the epic work. Great success!

**Comment by Sarcasm** [comment]
Hi tarsius, I was super enthusiastic to test the new release but I saw the following in the install notes:

```
Also note that starting with the 2.1.0 release, Magit requires at least Emacs 24.4 and Git 1.9.4. You should make sure you have at least these releases installed before updating Magit. 
```

It's written after it the desinstall instruction (
http://magit.vc/manual/magit/Updating-from-an-older-release.html#Updating-from-an-older-release)

So I removed the packages `magit`, `git-commit-mode`, and `git-rebase-mode`, and THEN saw that I didn't have the proper emacs version or git version.

Now I cannot easily go back to the old version, can I?

It's a little bit of a surprise for me that the new version isn't supported by Ubuntu 14.04 without "manual modification of the system (install git and emacs from somewhere)". FYI, Ubuntu 14.04 ships with Emacs 24.3.1 and git 1.9.1.

Anyway, that was just so you know some people may have the same issues, a lot of companies use the Ubuntu LTS versions until the next comes out which we will have to wait for another year for Ubuntu. I will be glad to try it at home though.

**Comment by tarsius** [comment]
> Now I cannot easily go back to the old version, can I?

If installing from magit's repository is an option, then it shouldn't be to hard. It might also still be possible to download the melpa snapshots from before the release and then install them using `package-install-file`.

> and THEN saw that I didn't have the proper emacs version or git version.

Well it sais that *right below* the removal instructions. And nothing follows after that, so I would expect it is pretty hard to miss this information. Of course it can happen, but it's not like this information is only available from the next *node* (also separate page on web).

> It's a little bit of a surprise for me that the new version isn't supported by Ubuntu 14.04 without "manual modification of the system (install git and emacs from somewhere)".

Doesn't surprise me - unfortunately Ubuntu doesn't consider Magit an essential package :-)

Oh, you meant me!? Well, at some point one has to drop support for older versions. (I did wait for Debian stable though). I picked this version as the new minimum because it's available for MS Windows (see e3aeb6639e202ac973af6a7c2f585ebcd4e60b6b).

There was not one particular reason I dropped support for older releases. But often new features were broken from the start for users of ancient releases because I often did not check whether some argument I started using was available when using what we had declared to be the minimal Git version. Unfortunately these errors were difficult to debug, because they usually happened in contexts where it is impossible to get to git's error message and things just broke in the UI.

Since `1.9.4` is the minimal version, this has not happened anymore, seems Git took a leap forward around then.

**Comment by Sarcasm** [comment]
Thank you for you answer,

I rebuilt the old packages via the melpa git directory and changing the recipe to point to the 1.0 version, not sure that was the best method but it was straightforward enough.

I will use the new version at home for now.

**Comment by tarsius** [comment]
> 1.0

Did you mean `1.4.*`?! 'cause `1.0` was released more than four years ago!  :-D

> I will use the new version at home for now.

Are you not *allowed* to manually install a newer Git release? Because otherwise you should - it's really quite simple.

**Comment by Silex** [comment]
> Anyway, that was just so you know some people may have the same issues, a lot of companies use the Ubuntu LTS versions until the next comes out which we will have to wait for another year for Ubuntu. I will be glad to try it at home though.

We are also using ubuntu 14.04 LTS at work, and to get the latest git I just install https://launchpad.net/~git-core/+archive/ubuntu/ppa. For emacs I build emacs manually, but I'm sure there's also a PPA available somewhere.

**Comment by tarsius** [comment]
> I'm sure there's also a PPA available somewhere.

Apparently the Emacs PPAs are all undead. If you know of one which features `24.4` and/or `24.5` then let me know. 'cause currently we don't test with those releases on Travis.

**Comment by SvenRieke** [comment]
To update Emacs to 24.4 you can use this PPA (worked fine for me):
https://launchpad.net/~andreas-h/+archive/ubuntu/emacs

But I haven't found any PPA which holds git 1.9.4.
There are a few containing git 2.xx, but I'm afraid of performing this jump.
Is Magit compatible with it.

Inspite of this, I'm really sorry about new Magit breaking magit-svn and magit -gitflow.
Both are still using the old keymap and section insertions, which are not supported any longer by Magit 2.1.0
I do not know where's the source code of these (are they public) and if someone is working on these to use the new magit-popup f.ex.
If this will not be solved soon, I'll have to go back to 1.4.0 (sniff)

**Comment by tarsius** [comment]
> Is Magit compatible with it?

Sure! While I usually don't use the very latest version, you should usually be safe.

> I'm really sorry about new Magit breaking magit-svn and magit -gitflow

These packages have been update. I went to great lengths to ensure that as many extensions work from the get go. I even maintain a compatibility list: #1921.

**Comment by SvenRieke** [comment]
Thanks a lot @tarsius for all your effort.
Finally got **magit-svn** running, with the tips mentioned in your compatibility list:
* deinstall magit-svn package
* reinstall it again
* restart emacs

Same goes for **magit-gitflow**.

Well, seems the emacs package handleris still buggy ;-)

Great work, love magit so much, it's the best git client so ever.

**Comment by mgalgs** [comment]
Any ideas what the stable release cadence will be like moving forward?

**Comment by glasser** [comment]
Thank you so much.  Just the recursive blame support alone will save me lots of frustration every week.
