### ISSUE TITLE
Setting magit-no-confirm to t has no effect

### ISSUE THREAD

**Issue by tuhdo** [magit/magit#1943]
I set it to t, but when I tried to discard a hunk or a stash, it still asks me by showing a prompt to press RET.

**Comment by tarsius** [comment]
This option only affects commands which use `magit-confirm` (which in turn uses `yes-or-no-p`).

Some commands, like the ones you have mentioned, now combine confirmation with selection. See http://magit.vc/manual/magit/Completion-and-confirmation.html and http://magit.vc/manual/magit/Confirmation-and-completion.html.
