### ISSUE TITLE
Invalid face: magit-diff-add

### ISSUE THREAD

**Issue by marcbowes** [magit/magit#1944]
I updated magit. Now it's broken :-(.

When running `magit-status` I get this:

```
ad-handle-definition: `magit-commit-popup' got redefined
set-face-attribute: Invalid face: magit-diff-add
```

```
GNU Emacs 24.4.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2014-10-21 on builder10-9.porkrind.org
Magit 20150701.1326, Git 2.3.2 (Apple Git-55), Emacs 24.4.1
```

**Comment by tarsius** [comment]
Probably the theme you are using has to be adjusted (see https://github.com/magit/magit/issues/1922).

**Comment by marcbowes** [comment]
I was using `tango-dark` via this in `custom.el`:

```
'(custom-enabled-themes (quote (tango-dark)))
```
I found that issue and tried to swap to a theme that was updated. So removed that line, and swapped to https://github.com/juba/color-theme-tangotango (and restarted). Same problem.

**Comment by tarsius** [comment]
Or an extension (see https://github.com/magit/magit/issues/1921), or a starter-kit (see https://github.com/magit/magit/issues/1923), or your local configuration.

The symbol `magit-diff-add` no longer appears anywhere in the magit source. But you might have forgone installing the old version before installing v2.1.0, in which case the old version might still be laying around on the `load-path` and/or has leaked into the new installation of the new version during byte compilation.

**Comment by tarsius** [comment]
Grep `~/.emacs.d` for `magit-diff-add`.

**Comment by marcbowes** [comment]
Ahh - starter-kit.

**Comment by marcbowes** [comment]
```
diff --git a/starter-kit-misc.org b/starter-kit-misc.org
index a9bd449..08ba914 100644
--- a/starter-kit-misc.org
+++ b/starter-kit-misc.org
@@ -167,9 +167,10 @@ let them live in the =backups/= directory inside of the starter kit.
      (set-face-foreground 'diff-added "green4")
      (set-face-foreground 'diff-removed "red3")))

-(eval-after-load 'magit
-  '(progn
-     (set-face-foreground 'magit-diff-add "green3")
-     (set-face-foreground 'magit-diff-del "red3")))
+;; broken after magit 2.1.0
+;; (eval-after-load 'magit
+;;   '(progn
+;;      (set-face-foreground 'magit-diff-add "green3")
+;;      (set-face-foreground 'magit-diff-del "red3")))
 #+end_src
```

That fixed it for me. Other than just removing it, is there anything I should be putting in it's place? I opened some diffs and they seem to be well colored.

**Comment by tarsius** [comment]
Could you please create a pull request for that.

**Comment by marcbowes** [comment]
I'll take a stab at it. My fork is quite long running so it may be harder than you might think.

**Comment by marcbowes** [comment]
Thanks for your help @tarsius. Awesome as usual.

**Comment by krunkosaurus** [comment]
Just ran into this issue today as well. Is there still a way to change the colors?

**Comment by tarsius** [comment]
Yes, the colors can still be changed. Do `M-x customize-group RET magit-faces RET`.

**Comment by beacoder** [comment]
I tried this, seems working.

(custom-set-faces
   '(magit-diff-added ((t (:background "black" :foreground "green3"))))
   '(magit-diff-removed ((t (:background "black" :foreground "red3")))))
