### ISSUE TITLE
Running `magit-blame-mode` enables the mode twice causing every buffer to stay read only.

### ISSUE THREAD

**Issue by jordonbiondo** [magit/magit#1948]
If you run `magit-blame-mode` directly in a non-read-only buffer, it will set `magit-blame-buffer-read-only` to `nil` but will then call `magit-blame` which will (seemingly incorrectly) enable `magit-blame-mode` again causing `magit-blame-buffer-read-only` to be set to `t` because the buffer was already put in `read-only-mode` from the first call to `magit-blame-mode`. Once you disable `magit-blame-mode` the buffer will still be in `read-only-mode` because of this.

If you put a `message` in `magit-blame-mode` then run `magit-blame-mode` on a non-readonly mode buffer, you'll see the message fire twice and you'll see `magit-blame-buffer-read-only` is set incorrectly to `t`.

**Comment by tarsius** [comment]
You should use `magit-blame` or `magit-blame-popup` instead.

But I just tried with `magit-blame-mode` too, and could not reproduce this. Sounds like you are still using `1.4.*`. Try `2.1.0` will it is still oven-fresh.

**Comment by jordonbiondo** [comment]
I did a fresh install of 2.1 this morning, I've verified that only 2.1 is installed.

Even with a very empty config it happens.
When I run `magit-blame` it works as it should but I can still reproduce the issue.

1. start emacs with a config that does nothing but install and load magit from melpa.
2. open a file
3. M-x `magit-blame-mode`
4. M-x `magit-blame-mode`
5. Try to type, `read-only-mode` is still enabled.

If users are not supposed to call `magit-blame-mode` and instead call `magit-blame` perhaps that should be in the docstring of `magit-blame-mode`.

**Comment by npostavs** [comment]
Confirmed.

> If users are not supposed to call magit-blame-mode and instead call magit-blame perhaps that should be in the docstring of magit-blame-mode.

Or even made noninteractive. Though `define-minor-mode` doesn't make that convenient :(

**Comment by jordonbiondo** [comment]
The problem is here:

When enabled `magit-blame-mode` does this:
```
(let ((magit-blame-mode nil))
  (call-interactively 'magit-blame))))
```

And `magit-blame` does this:
```
(unless magit-blame-mode
   ...
  (magit-blame-mode 1)
  ...
)
```

Resulting in the double call.

**Comment by tarsius** [comment]
The mode now refuses to activate if called interactively. Thanks for the suggestion.
