### ISSUE TITLE
Also offer non-branch completion in magit-read-other-branch-or-commit

### ISSUE THREAD

**Issue by Malabarba** [magit/magit#1949]
As seen here: http://emacs.stackexchange.com/q/13625/50

> It would probably make sense if magit-read-other-branch-or-commit (which is used by b b) offered certain non-branch refs for completion. 

The particular case I am interested in is for refs like this:

    fetch = +refs/pull/*/head:refs/pull/origin/*

**Comment by tarsius** [comment]
Done.

**Comment by Malabarba** [comment]
Thanks Jonas!
