### ISSUE TITLE
New Magit release in ELPA fails in popup buffers

### ISSUE THREAD

**Issue by ahungry** [magit/magit#1950]
I'm not sure if this is evil related (or other add on related), but when opening up the magit window and pressing "l l" to view the log, the second window does not detect the key binds at all (it acts as a normal edit buffer).

Also, I repeated get the error about removing git-commit-mode and git-rebase-mode, despite having already uninstalled them from ELPA (and restarted emacs).

**Comment by ahungry** [comment]
Ok, it is evil related, it requires manually swapping into insert mode with evil.

I'm not sure if old magit or old evil was responsible for gracefully handling this, but it doesn't work now.

**Comment by npostavs** [comment]
> Also, I repeated get the error about removing git-commit-mode and git-rebase-mode, despite having already uninstalled them from ELPA (and restarted emacs).

Does `M-x locate-library git-commit-mode` tell you anything?

**Comment by ahungry** [comment]
This is the fix for the evil issue btw:

```lisp
(add-to-list 'evil-emacs-state-modes 'magit-popup-mode)
```

It appears evil mode needs to add 'magit-popup-mode to the variable's defaults.

Checking on the other one, "no library in search path".

**Comment by ahungry** [comment]
Also - anyone have the face name of the diff (add/removed) in the log history for the inactive region?  Updating my theme (ahungry-theme) but I can't target the region and #'describe-face, since moving to the region changes it to the magit-diffstat-added face (which I've already updated in my theme).

**Comment by kyleam** [comment]
> Also - anyone have the face name of the diff (add/removed) in the log history for the inactive region?

`list-faces-display` is handy when you can't get point on the face you want.  It displays sample text, so it's usually easy to narrow it down.

**Comment by npostavs** [comment]
> Checking on the other one, "no library in search path".

Hmm, `M-: (featurep 'git-commit-mode) RET` gives `t` then? Can't see any way that warning could be triggered otherwise.

Do you possibly have a configuration file that `provide`s it?

**Comment by ahungry** [comment]
It returns nil - I tried on a second machine and still get the error message over and over again.

I went through ELPA and uninstalled all 'git' related modules (git-commit-mode, git-rebase-mode, magit, git-commit), restarted emacs.

Re-installed just 'magit', which then installed 'git-commit' and 'magit-popup' as dependencies.

Error still occurs (it happens when I first C-m to open magit buffer, but drops to a background buffer instead of foreground).

**Comment by tarsius** [comment]
This is the relevant code:

```elisp
  (--each '((magit-log-edit  . git-commit)
            (git-commit-mode . git-commit)
            (git-rebase-mode . git-rebase))
    (when (or (featurep (car it)) (locate-library (symbol-name (car it))))
      (display-warning 'magit ...)))
```

Note the `locate-library`.

**Comment by ahungry** [comment]
Ok, I found it under the locate-library call (git-commit-mode) in the OS directory Library is file /usr/share/emacs/site-lisp/git-modes/git-commit-mode.elc

This is under Arch Linux, thanks guys!

**Comment by tarsius** [comment]
And the popup issue, is that resolved too?

**Comment by ahungry** [comment]
For the log and branch buffers, for the merge buffer (m) evil mode is still becoming active.  There aren't any new modes other than magit-popup-mode correct?

**Comment by ahungry** [comment]
Although I suppose technically its an issue with evil-mode not magit.

**Comment by tarsius** [comment]
There's also `magit-popup-sequence-mode`.

**Comment by ahungry** [comment]
That fixes it (adding:
```lisp
(add-to-list 'evil-emacs-state-modes 'magit-popup-sequence-mode)
```
into the ~/.emacs)

Thanks for the awesome package and work guys!

**Comment by tarsius** [comment]
Pending https://bitbucket.org/lyro/evil/pull-request/16/adapt-for-magit-v210/diff.
