### ISSUE TITLE
In log view, the latest commit has no author/date information

### ISSUE THREAD

**Issue by tshatrov** [magit/magit#1951]
![magit log bug](https://cloud.githubusercontent.com/assets/4077725/8485111/0b4579e8-2104-11e5-9f28-010edbf377cc.png)

Note the topmost commit lacking name/date.

This is Emacs 24.4.1 on Windows. I don't think I had this bug on my Linux/Emacs 25 setup, so might be a platform-specific issue. Git version is the latest "Git for Windows", 1.9.5. This happens on every repository.

**Comment by tarsius** [comment]
I think it's more likely that this issue is limited to Emacs v24.4 than to MS Windows. But I don't have access to either of the two right now. Who can confirm this issue?

**Comment by npostavs** [comment]
I see it on Emacs 24.4, 24.5, and an Emacs 25 snapshot (May 29) on Windows (I don't currently have access to a Linux machine).

**Comment by kyleam** [comment]
I don't see it on Linux for 24.5.

**Comment by tarsius** [comment]
Well, color me surprised. But of course I am happy I can stick the `bug-window` label on this instead of just `bug` :-) (On the other hand that makes it harder to figure out what's going on).

**Comment by npostavs** [comment]
The problem appears to be at the end of `magit-log-refresh-buffer`, the margin starts out correctly filled, but then 
```elisp
(defun magit-log-refresh-buffer (style revs args &optional files)
...
  (save-excursion
    (goto-char (point-min))
    (magit-format-log-margin))) ; <--- huh?
```
It goes to the beginning of the buffer and clears the margin. I don't understand how this works correctly on Linux. Is there supposed something else on the first line?
