### ISSUE TITLE
magit-fullscreen is gone

### ISSUE THREAD

**Issue by ihodes** [magit/magit#1953]
Is there a replacement or suggested library/approach to making magit full screen? Previously I did the following:

```elisp
(defadvice magit-status (around magit-fullscreen activate)
    (windowt-configuration-to-register :magit-fullscreen)
    ad-do-it
    (delete-other-windows))

(defun magit-quit-session ()
    "Restores the previous window configuration and kills the magit buffer"
    (interactive)
    (kill-buffer)
    (jump-to-register :magit-fullscreen))

(bind-keys :map magit-status-mode-map
           ("q" . magit-quit-session))
```

**Comment by tarsius** [comment]
Yes.

```lisp
(setq magit-restore-window-configuration t) ; that's the default actually
(setq magit-status-buffer-switch-function
      (lambda (buffer) ; there might already be an Emacs function which does this
        (pop-to-buffer buffer)
        (delete-other-windows)))
```

**Comment by kyleam** [comment]
This also works:

```
(add-hook 'magit-status-mode-hook 'delete-other-windows)
```

**Comment by ihodes** [comment]
@tarsius superb, thank you.

**Comment by tarsius** [comment]
@kyleam So the buffer gets displayed before `(funcall (or switch-function ....))` in `magit-mode-display-buffer`? I don't see where that would happen.

**Comment by kyleam** [comment]
I've been using that since I switched to next.  Seems to work.

**Comment by garyo** [comment]
Kyle's solution works for me too; very nice!

On Thu, Jul 2, 2015 at 4:37 PM, Kyle Meyer <notifications@github.com> wrote:

> I've been using that since I switched to next. Seems to work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magit/magit/issues/1953#issuecomment-118160600>.
>



-- 
Gary

**Comment by codeitagile** [comment]
Excellent.

**Comment by Silex** [comment]
@kyleam 's solution suddenly stopped working :-(

**Comment by jguenther** [comment]
I think the `fullframe` [package](https://github.com/tomterl/fullframe) might be what you're looking for:

```
(require 'fullframe)
(fullframe magit-status magit-mode-quit-window)
```

**Comment by tarsius** [comment]
There were some big changes in that area. Have a look at the "Switching Buffers" node in the magit manual. I would be interested in a solution that goes full screen just using display actions.

**Comment by bmag** [comment]
This is what I am currently trying, and it seems to work:
```elisp
(setq magit-display-buffer-function
      (lambda (buffer)
        (if magit-display-buffer-noselect
            ;; the code that called `magit-display-buffer-function'
            ;; expects the original window to stay alive, we can't go
            ;; fullscreen
            (magit-display-buffer-traditional buffer)
          (delete-other-windows)
          ;; make sure the window isn't dedicated, otherwise
          ;; `set-window-buffer' throws an error
          (set-window-dedicated-p nil nil)
          (set-window-buffer nil buffer)
          ;; return buffer's window
          (get-buffer-window buffer))))
```
I don't know of a display action that goes full screen, but you could extract one from the lambda's else clause:
```elisp
(defun display-buffer-full-screen (buffer alist)
  (delete-other-windows)
  ;; make sure the window isn't dedicated, otherwise
  ;; `set-window-buffer' throws an error
  (set-window-dedicated-p nil nil)
  (set-window-buffer nil buffer)
  ;; return buffer's window
  (get-buffer-window buffer))

(setq magit-display-buffer-function
      (lambda (buffer)
        (if magit-display-buffer-noselect
            ;; the code that called `magit-display-buffer-function'
            ;; expects the original window to stay alive, we can't go
            ;; fullscreen
            (magit-display-buffer-traditional buffer)
          (display-buffer buffer '(display-buffer-full-screen)))))
```

**Comment by Silex** [comment]
@jguenther: yeah it works, thanks

**Comment by aspiers** [comment]
Thanks all!  @tarsius ICBW but it seems likely that enough people will want this behaviour that it would make sense to have it available as a standard function which `M-x customize-variable magit-display-buffer-function` would offer as one of the options - what do you think?

**Comment by lunaryorn** [comment]
I may have missed something, but I think you can achieve the same effect just with `display-buffer-alist`:

```elisp
(defun lunaryorn-display-buffer-fullframe (buffer alist)
  "Display BUFFER in fullscreen.

ALIST is a `display-buffer' ALIST.

Return the new window for BUFFER."
  (let ((window (or (display-buffer-use-some-window buffer alist)
                    (display-buffer-pop-up-window buffer alist))))
    (when window
      (delete-other-windows window))
    window))

(setq display-buffer-alist
      `(
        ;; Magit status window in fullscreen
        (,(rx "*magit: ")
         (lunaryorn-display-buffer-fullframe)
         (reusable-frames . nil)))
```

**Comment by tarsius** [comment]
That works too and there's nothing wrong with doing it that way. Option `magit-display-buffer-function` is basically a way to let users easily switch between different ready to use configuration.

But since I haven't gotten around to actually implement any alternatives and nobody else contributed any, there's but one to choose from. However @kyleam and I have posted some drafts in #2541.

**Comment by ddoherty03** [comment]
So what's now the best answer to the original question.  Run magit-status fullscreen and restore windows on quitting?

**Comment by kyleam** [comment]
You can now make the status buffer fill the entire frame with

    (setq magit-display-buffer-function #'magit-display-buffer-fullframe-status-v1)

**Comment by ddoherty03** [comment]
Just updated from melpa, looking good. Thanks, Kyle.
