### ISSUE TITLE
Why the time stamp shown in `magit-blame` different from that in the commit log

### ISSUE THREAD

**Issue by bixuanzju** [magit/magit#1962]
First of all, thanks very much for the marvellous work on `magit`!

This is the screenshot from running `magit-blame`

<img width="304" alt="screen shot 2015-07-03 at 7 23 28 pm" src="https://cloud.githubusercontent.com/assets/1680704/8498440/35dacdec-21b9-11e5-8f6e-bab1b730589c.png">

And this is the same commit 

<img width="377" alt="screen shot 2015-07-03 at 7 23 44 pm" src="https://cloud.githubusercontent.com/assets/1680704/8498444/3ee429ec-21b9-11e5-8575-51d13045fe3e.png">

As can be seen, the same commit has two different time stamps.

PS: As of writing, it is July 3. I must have somehow time travelled to the future when `magit-blame` :)

**Comment by npostavs** [comment]
Looks like local time vs UTC:

`Jul 3 18:33:59 + 8 == Jul 3 26:33:59 == Jul 4 02:33:59`

**Comment by bixuanzju** [comment]
@npostavs I don't think so. UTC is `Jul 3 18:33:59 - 8 == Jul 3 10:33:59`. I am in GMT+8.

**Comment by tarsius** [comment]
Might be that one as an author date and the other a committer date.

**Comment by bixuanzju** [comment]
@tarsius I am sure three of us (well they sit beside me) are in the same time zone.

**Comment by bixuanzju** [comment]
FYI, I run `git blame` in the command line on the same file gives (author date)

<img width="738" alt="screen shot 2015-07-03 at 8 54 35 pm" src="https://cloud.githubusercontent.com/assets/1680704/8499464/d82f5340-21c5-11e5-87a4-cc98c3cac36f.png">

**Comment by tarsius** [comment]
The distinction between author and committer dates has nothing to do with timezones.

**Comment by tarsius** [comment]
> Might be that one as an author date and the other a committer date.

Indeed this is the case. For blame it is easily configurable using `magit-blame-heading-format`. But note that I think it makes a lot of sense to use the committer date here. For log the format is hardcoded in `magit-insert-log`: "--format=%%h%s %s[%%an][%%at]%%s".

**Comment by tarsius** [comment]
That should answer your question. If you want to argue that it doesn't make sense, feel free to do so, but I am closing for now.
