### ISSUE TITLE
magit-ediff-stage: Please don't set ediff-quit-hook

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#1963]
Hello,

today I got the upgrade to the new Magit version via Melpa, including the new "magit-ediff-stage" command.  I could hardly await it (thanks for working on this!).

However, there is a little problem with this.  I use "ediff-quit-hook" to close the selected frame (I have configured "ediff-window-setup-function" to pop up a new frame).  With the new Magit version, closing the selected frame doesn't work anymore because "magit-ediff-stage" resets the hook.

Apart from my personal problem - such a hook should never be set directly, better use add-hook with the LOCAL parameter.

Didn't look at master, sorry if this issue should already be fixed there.

Thanks,

Michael.

**Comment by tarsius** [comment]
> such a hook should never be set directly, better use add-hook with the LOCAL parameter.

It's not that easy. This is a very recent change (353bc8ef0cc5a2f7ea8ff0ce20e04468836ed096) which fixes #1934.

Taking all that into account, what's your suggestion?

**Comment by madscientist** [comment]
I only read the comment for the commit, not all the code, but it seems to me that if ediff-cleanup-mess is a no-op, why not leave it in ediff-quit-hook?  IOW, just put back the add-hook instead of seq-local, and have your local hook call magit-ediff-cleanup-auxiliary-buffers as it does now to do the cleanup.

Did I miss something?  Yes, it's a bit bizarre that ediff-cleanup-mess is still invoked and basically doesn't do anything, but it doesn't hurt...?

**Comment by tarsius** [comment]
> if ediff-cleanup-mess is a no-op

I am not 100% sure that is the case. It might have undesirable side-effects.

> Did I miss something?

`magit-ediff-resolve` uses `smerge-ediff`, which doesn't use `add-hook`. We cannot change that from within Magit.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> magit-ediff-resolve uses smerge-ediff, which doesn't use add-hook. We
> cannot change that from within Magit.

I consider that a bug, too.

Anyway, this is not too important.  I will not be angry if you just
close this.  I'll find a way to program around this.


Thanks,

Michael.

**Comment by tarsius** [comment]
> I will not be angry if you just close this.

I do intend to do something about this, just cannot promise I will get to it soon. There's just to much going on right now!

**Comment by tarsius** [comment]
Please try #1980.

**Comment by michael-heerdegen** [comment]
Works, thanks.  For specific comments see #1980.

**Comment by tarsius** [comment]
Okay, closing this then. But I'll wait with the merge a little longer, until others had a change to comment.
