### ISSUE TITLE
Branch manager

### ISSUE THREAD

**Issue by ewstearns** [magit/magit#1966]
I like 2.1.0 release, but it took away a feature that I used frequently: Branch Manager. I liked the way I could select a branch from a list and if I selected a branch from a remote it would automatically create a local tracking branch. Are there any plans to bring this back, or will this functionality be added back in a different way?

**Comment by kyleam** [comment]
Try "y" (bound to `magit-show-refs-popup`).

**Comment by ewstearns** [comment]
Thank you, this tip worked for me.
