### ISSUE TITLE
In magit-status and magit-log: Is there a way to move the decorations (branch names etc) to the end of the line?

### ISSUE THREAD

**Issue by bastianbeischer** [magit/magit#1969]
Currently the commits which have a branch ref attached to them are shown like this in magit-log:

![screenshot](https://cloud.githubusercontent.com/assets/394863/8504648/664b3d92-21d5-11e5-864f-8effbcf604a2.png)

As you can see my branch names are rather long. Can I customize the order in which each line is formatted? It's rather tedious at the moment because for me the thing that identifiers a commit in the most recognizable way is the commit message, which I would like to see on the left - given that branch refs are moving around all the time for me...

I'd like to have the commit message first (after the SHA1 and graph) and then (if applicable) the local branch name, and then the remote branch name.

It appears that the order in which lines are formatted now is even inconsistent: Why are remote tracking branches sometimes shown before the local branch name, and sometimes not?

**Comment by tarsius** [comment]
Yikes. (The recommendation is that commit message should be short enough to fit on screen. One could argue that this implies that one should also use reasonably short branch names.)

> Is there a way to move the decorations (branch names etc) to the end of the line?

Not without simply redefining `magit-log-wash-line`.

**Comment by bastianbeischer** [comment]
Ah that's too bad :(

My remote branch names are auto-generated from our issue tracker / code hosting tools and I like my local branch names to be the same, so shortening is not an option.

Also even then I'd still prefer to have the log message first, so that they all align, because as I said, the log message is the thing which helps me identify commits.

I think the format should be configurable, or maybe most people feel like me about the format - in which case the default could be changed? Looking at magit-log-wash-line I can see that it's not trivial to make it configurable...

**Comment by tarsius** [comment]
> Looking at magit-log-wash-line I can see that it's not trivial to make it configurable, though.

Actually it *is* trivial. I am considering adding an option - but no promises yet.

**Comment by tarsius** [comment]
I have added the option `magit-log-show-refname-after-summary`.
