### ISSUE TITLE
Magit 2.0 shadows `kill-ring-save`, preventing one to copy text from a magit buffer

### ISSUE THREAD

**Issue by cpitclaudel** [magit/magit#1971]
Thanks for the cool update!

Pressing M-w in a magit diff (displayed by pressing TAB on a "modified" line in a status buffer) just displays `master` and adds it to the kill ring. The documentation doesn't seem to mention a way to revert to normal copying (`kill-ring-save`). In addition, `kill-ring-save` doesn't seem to be remapped to another key.

**Comment by npostavs** [comment]
dup of #1958

**Comment by cpitclaudel** [comment]
Ah, true, sorry about that!
