### ISSUE TITLE
New faces are hard to read 

### ISSUE THREAD

**Issue by cpitclaudel** [magit/magit#1972]
This is how things look just after installing the new magit:
![screenshot from 2015-07-03 23 56 45](https://cloud.githubusercontent.com/assets/8181630/8506901/467450d4-21e0-11e5-9bb4-e27f4bc53b26.png)

The lack of contrast in the default set up makes things hard to read for me, especially after refining the diff. I used the following snippet to reset Magit faces, but I'm loosing on the fine-tuning that you did:

```elisp
(let ((magit-faces '(magit-diff-added magit-diff-removed magit-diff-our magit-diff-base magit-diff-their
                                        magit-diff-context magit-diff-added-highlight magit-diff-removed-highlight
                                        magit-diff-our-highlight magit-diff-base-highlight magit-diff-their-highlight
                                        magit-diff-context-highlight)))
    (dolist (face magit-faces)
      (set-face-attribute face nil :foreground "#eeeeec"))) ;; Tango's aluminium 1
```

This is the result:
![screenshot from 2015-07-04 00 03 37](https://cloud.githubusercontent.com/assets/8181630/8506902/4689830a-21e0-11e5-8bb1-e2d138eb70c5.png)

The solution that I used is not ideal, because it looses the fine-tuning or foreground colors. However, the defaults are not readable for me. Perhaps Magit could have a contrast setting?

**Comment by tarsius** [comment]
> Perhaps Magit could have a contrast setting?

I'll think about it, but lean toward rejecting this suggestion. There are two problems:

1. I can only see one way to achieve this. Add a variable which has to be set *before* magit is loaded.

2. The appearance and implementation of how diffs are colored have a massive backstory.

I have adjusted this so many times to satisfy users wishes that I frankly have gotten a bit sick of it. Whenever I change something, someone else comes along who is very dissatisfied with that change I made to make someone else happy. I have put a massive amount into this, but it will never be enough. (You can't know this, and it's perfectly fine you made this suggestion. I am just pointing out, why I don't jump to address such requests.)

Personally I am very happy with how diffs are colored now, at least in light themes. So it's more a theming issue, than an essential flaw in the decision to use red-on-red/green-on-green. And I also find that the reconfigurability has reached just the right level. It might be harder than just flipping a switch, bbut most, if not all, things users have asked, can now by achieved.

**Comment by npostavs** [comment]
> The solution that I used is not ideal, because it looses the fine-tuning or foreground colors.

You could try
```elisp
(require 'color)
(let ((lighten-percent 10)
      (magit-faces '(magit-diff-added magit-diff-removed magit-diff-our magit-diff-base magit-diff-their
                                      magit-diff-context magit-diff-added-highlight magit-diff-removed-highlight
                                      magit-diff-our-highlight magit-diff-base-highlight magit-diff-their-highlight
                                      magit-diff-context-highlight)))
  (dolist (face magit-faces)
    (-when-let (fg (face-foreground face))
      (set-face-foreground face (color-lighten-name fg lighten-percent)))))
```
adjust `lighten-percent` to taste. It's also possible to use `color-darken-name` on the backgrounds instead (or in addition).

**Comment by vjohansen** [comment]
It is not just a "theming issue,". I noticed it as well that some faces cause text to be difficult to read (eg. magit-hash). I am using a dark theme.

I suggest you load the tango-dark theme and do a list-faces-display to see if some of magit-* or git-* faces should be brightened.

**Comment by cpitclaudel** [comment]
Thanks for the thoughtful reply. You're right that it may not be worth adding extra customization. On the other hand, I do feel that dark themes could use better defaults. Bright themes are hard on my eyes, but Magit's lack of contrast somewhat negates the benefits of using a dark theme.

Then again, it could also be that Emac's default themes should customize Magit's settings as well.

**Comment by tarsius** [comment]
> I noticed it as well that some faces cause text to be difficult to read (eg. magit-hash).

In this case this is intentional, one usually wants to copy these strings instead of re-typing them.

**Comment by tarsius** [comment]
I have increased the contrast a bit.

If I remember correctly I came up with these colors while I was still using the dark low-contrast theme zenburn, and then just kept using these colors as the defaults when using any dark theme. But since low-contrast themes don't work for everyone, that wasn't such a good idea.

**Comment by tarsius** [comment]
The draw back is that the added/removed lines outside the region but inside the hunk are now less visible. (Try it to see what I mean.) But that's okay.
