### ISSUE TITLE
magit-diff hiding magit-status last log message

### ISSUE THREAD

**Issue by swwwfactory** [magit/magit#1979]
Please allow to disable magit-diff window when call git-commit or dont hide magit-status or show last log message in magit-diff buffer.

Also, when I needed with magit-diff I just pressing d in git-status.

**Comment by tarsius** [comment]
> Please allow to disable magit-diff window when call git-commit or dont hide magit-status

How this is done is a bit surprising, but it's possible:

```elisp
(remove-hook 'server-switch-hook 'magit-commit-diff)
```

> or show last log message in magit-diff buffer.

I am not sure what you are asking. You want to see last changes that have *already* been committed, instead of those you are about to commit?!

> Also, when I needed with magit-diff I just pressing d in git-status.

It's better to type `C-c C-d` in the commit message buffer.

**Comment by swwwfactory** [comment]
(remove-hook 'server-switch-hook 'magit-commit-diff) 
- its nice and works, but I want to see magit-status frame, instead magit-diff then ;)

**Comment by swwwfactory** [comment]
> I am not sure what you are asking. You want to see the last changes that have already been committed, instead of those you are about to commit?!
Just want to see only previous log message

**Comment by tarsius** [comment]
Assuming that you initiate the commit by pressing `c` while in the status buffer, this would do:

```elisp
(remove-hook 'server-switch-hook 'magit-commit-diff)
(setq with-editor-server-window-alist
      (cons (cons git-commit-filename-regexp 'pop-to-buffer)
            (remove (cons git-commit-filename-regexp 'switch-to-buffer)
                    with-editor-server-window-alist)))
```

**Comment by swwwfactory** [comment]
Nice and works! 

Thank you tarsius - that exactly what I needed.

**Comment by tarsius** [comment]
You're welcome.

**Comment by madscientist** [comment]
Is there a place where these kinds of things can be collected, for posterity?  I see a lot of helpful customization suggestions in response to issues here on GitHub but they're not very discoverable after the fact.  If we could collect them somewhere, just for example in a list with a short description, the version of Magit it was used with, and the solution, that could come in very handy I would think.

**Comment by tarsius** [comment]
> I see a lot of helpful customization suggestions in response to issues here on GitHub but they're not very discoverable after the fact.

Yes, that's true. That's why I suggest that users ask for help on the Emacs Stackoverflow site instead.

> If we could collect them somewhere, just for example in a list with a short description, the version of Magit it was used with, and the solution, that could come in very handy I would think.

Users are welcome to add these snippets to https://github.com/magit/magit/wiki/FAQ or https://github.com/magit/magit/wiki/Tips-and-Tricks. And I should probably tell users to do that or just do it myself.

In that spirit, could someone please add the above snippet and an explanation to the FAQ :-)
