### ISSUE TITLE
why I'm getting this error while make

### ISSUE THREAD

**Issue by henry-y** [magit/magit#1983]
Hi, 

I've updated magit today and try to make, but the following error popped up.
There was no problem with commit 93cbf42.

Thanks

```
root@henry-dev:~/.emacs.d/3rd/magit
# make
make[1]: Entering directory `/root/.emacs.d/3rd/magit/lisp'
Compiling with-editor.el
Compiling git-commit.el

In git-commit-propertize-diff:
git-commit.el:640:18:Warning: `font-lock-fontify-buffer' is for interactive
    use only; use `font-lock-ensure' or `font-lock-flush' instead.
Compiling magit-popup.el
Compiling magit-utils.el
Compiling magit-section.el
Compiling magit-git.el
Compiling magit-mode.el
Compiling magit-process.el
Compiling magit-core.el
Compiling magit-diff.el
Compiling magit-wip.el
Compiling magit-apply.el
Compiling magit-log.el
Compiling magit.el
Compiling magit-sequence.el
Cannot determine Magit's version

In toplevel form:
magit-sequence.el:32:1:Error: Wrong type argument: arrayp, nil
make[1]: *** [magit-sequence.elc] Error 1
make[1]: Leaving directory `/root/.emacs.d/3rd/magit/lisp'
make: *** [lisp] Error 2
```

**Comment by tarsius** [comment]
I suspect a incompatible change in Emacs v25.0.50 (likely in `package.el`) is the cause. I have just pulled and recompiled Emacs but could not reproduce. So maybe this was a regression that has already been fixed, or it's something else.

To know for sure you have to reproduce the error in an interactive session and with `M-x toggle-debug-on-error`. Just forgo compiling the libraries, start emacs, turn on debugging, and then try to compile the file using `M-x byte-compile-file RET /path/to/magit-sequence.el RET`.  Post the backtrace here.

Then, provided you actually use Emacs' development version, update your build and try again.

**Comment by triclops200** [comment]
I can confirm I'm having the same error on emacs 24.5.1. The traceback isn't very helpful, it just points to the (require 'magit) line.

**Comment by tarsius** [comment]
Are you building/running magit from the repository or an unpacked tarball?

> The traceback isn't very helpful, it just points to the (require 'magit) line.

Even if you first remove all `*.elc` that were already created? By the way, I suspect the error is in `magit-version`.

**Comment by triclops200** [comment]
I'm using the melpa version, so, the latest git. And, yes, I did remove all the .elc files and it gave the same error.

**Comment by tarsius** [comment]
Please check whether you have an old version of `package.el` laying around on the `load-path`.

This snippet from `magit-version` should return non-nil:

```lisp
(--when-let (assq 'magit package-alist)
  (setq magit-version
        (and (fboundp 'package-desc-version)
             (package-version-join
              (package-desc-version (cadr it))))))
```

**Comment by triclops200** [comment]
I wiped my elpa folder and installed from scratch. You're right, it returns: "20150706.457"
Still having errors, though, I get the same error he was getting when I run magit-status.

**Comment by tarsius** [comment]
Autsch. I think I know what the problem is. `~/.emacs.d` is a git repository right?

**Comment by triclops200** [comment]
Yes.

**Comment by triclops200** [comment]
Also, if you're still interested, by removing the nodebug flag from the package require I get:
```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  substring(nil 12)
  (let ((version (substring (magit-git-string "version") 12))) (if version (progn (if (string-match "^\\([0-9]+\\.[0-9]+\\.[0-9]+\\)" version) (progn (setq version (match-string 1 version)))) (if (version< version "1.9.4") (progn (display-warning (quote magit) (format "Magit requires Git >= 1.9.4, you are using %s.\n\nIf this comes as a surprise to you, because you do actually have\na newer version installed, then that probably means that the\nolder version happens to appear earlier on the `$PATH'.  If you\nalways start Emacs from a shell, then that can be fixed in the\nshell's init file.  If you start Emacs by clicking on an icon,\nor using some sort of application launcher, then you probably\nhave to adjust the environment as seen by graphical interface.\nFor X11 something like ~/.xinitrc should work.\n\nIf you use Tramp to work inside remote Git repositories, then you\nhave to make sure a suitable Git is used on the remote machines\ntoo.\n" version) :error))))))
  magit-startup-asserts()
  (if after-init-time (magit-startup-asserts) (add-hook (quote after-init-hook) (function magit-startup-asserts)))
  eval-buffer()  ; Reading at buffer position 82768
  funcall-interactively(eval-buffer)
  call-interactively(eval-buffer)
  (lambda nil (interactive) (call-interactively (intern (ido-completing-read "M-x " (all-completions "" obarray (quote commandp))))))()
  funcall-interactively((lambda nil (interactive) (call-interactively (intern (ido-completing-read "M-x " (all-completions "" obarray (quote commandp)))))))
  call-interactively((lambda nil (interactive) (call-interactively (intern (ido-completing-read "M-x " (all-completions "" obarray (quote commandp)))))) nil nil)
  command-execute((lambda nil (interactive) (call-interactively (intern (ido-completing-read "M-x " (all-completions "" obarray (quote commandp)))))))
```

**Comment by tarsius** [comment]
> Autsch. I think I know what the problem is. ~/.emacs.d is a git repository, right?

Actually no, there's nothing wrong here.

```
(wrong-type-argument arrayp nil)
substring(nil 12)
(substring (magit-git-string "version") 12)
```

Aha!

What does `(magit-git-string "version")` return? What about `git version` on the command line?

**Comment by triclops200** [comment]
nil and git version 2.1.4, respectively

**Comment by tarsius** [comment]
Sounds like `git` isn't on `exec-path`. Does `(magit-git-string "status")` return a string?

**Comment by triclops200** [comment]
No. I should note, until I updated this morning, it worked fine.

**Comment by triclops200** [comment]
I'm wondering if maybe you are expecting a three number string and getting 4?

**Comment by triclops200** [comment]
Also, updating git fixed the issue.

**Comment by tarsius** [comment]
> I'm wondering if maybe you are expecting a three number string and getting 4?

No we get nil, because git cannot be found.

What's the value of `magit-git-executable`? Are you using MS Windows? Did you update Git also? Have you removed any Magit configuration when updating to `2.1.0`?

**Comment by triclops200** [comment]
magit-git-executable is undefined. Linux. updated git to 2.4.5 from 1.7.10.4. I am using a fresh install of magit completely.

**Comment by tarsius** [comment]
Does `(executable-find "git")` return anything?

**Comment by triclops200** [comment]
/usr/bin/git

**Comment by tarsius** [comment]
This is getting stranger and stranger. Let's start with a functioning Magit. Comment out `(magit-version t)`, and restart Emacs. Is Magit functional now?

**Comment by triclops200** [comment]
No

**Comment by triclops200** [comment]
I will note, upgrading git past 1.7 removes the error

**Comment by tarsius** [comment]
> I should mention, I was not using 2.1.4, that was the wrong vm window. The one that was having issues was 1.7.10.4

I read past that. Now I have to figure out how to detect that and display a more meaningful error message.

**Comment by triclops200** [comment]
Ah.

**Comment by tarsius** [comment]
Do you still have that other vm available? What do these commands return there?

```
git version
git --version
```

**Comment by triclops200** [comment]
They both return git version 1.7.10.3

**Comment by triclops200** [comment]
Found your error. You are calling git with --literal-pathspecs. This causes git to crash with "Unknown option: --literal-pathspecs"

**Comment by tarsius** [comment]
Totally forgot about that. Thanks!

**Comment by triclops200** [comment]
Yeah, looking in magit-git-insert, it's just returning the error code instead of actually updating the buffer and pulling the string out. Thus, it's getting nil. Could be incorrect in that assumption, though.

**Comment by tarsius** [comment]
I have just pushed a change which should result in a more meaningful error message. Once that hits Melpa, could you please check whether that indeed is the case in the "1.7 vm".

**Comment by triclops200** [comment]
I don't know about the melpa branch, but, running make on the newest commit still has the issue.

**Comment by triclops200** [comment]
```
...
Compiling magit-sequence.el

In toplevel form:
magit-sequence.el:32:1:Error: Wrong type argument: arrayp, nil
make[1]: *** [magit-sequence.elc] Error 1
make[1]: Leaving directory `/home/forces/magit/lisp'
```

**Comment by triclops200** [comment]
Also, running eval-buffer on magit.el still causes
```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  substring(nil 12)
  (let ((version (substring (magit-git-string "version") 12))) (if version (progn (if (string-match "^\\([0-9]+\\.[0-9]+\\.[0-9]+\\)" version) (progn (setq version (match-string 1 version)))) (if (version< version "1.9.4") (progn (display-warning (quote magit) (format "Magit requires Git >= 1.9.4, you are using %s.\n\nIf this comes as a surprise to you, because you do actually have\na newer version installed, then that probably means that the\nolder version happens to appear earlier on the `$PATH'.  If you\nalways start Emacs from a shell, then that can be fixed in the\nshell's init file.  If you start Emacs by clicking on an icon,\nor using some sort of application launcher, then you probably\nhave to adjust the environment as seen by graphical interface.\nFor X11 something like ~/.xinitrc should work.\n\nIf you use Tramp to work inside remote Git repositories, then you\nhave to make sure a suitable Git is used on the remote machines\ntoo.\n" version) :error))))))
  magit-startup-asserts()
  (progn (magit-startup-asserts) (magit-version))
  (if after-init-time (progn (magit-startup-asserts) (magit-version)) (add-hook (quote after-init-hook) (function magit-startup-asserts) t) (add-hook (quote after-init-hook) (function magit-version) t))
  eval-buffer()  ; Reading at buffer position 82772
  funcall-interactively(eval-buffer)
  call-interactively(eval-buffer)
  (lambda nil (interactive) (call-interactively (intern (ido-completing-read "M-x " (all-completions "" obarray (quote commandp))))))()
  funcall-interactively((lambda nil (interactive) (call-interactively (intern (ido-completing-read "M-x " (all-completions "" obarray (quote commandp)))))))
  call-interactively((lambda nil (interactive) (call-interactively (intern (ido-completing-read "M-x " (all-completions "" obarray (quote commandp)))))) nil nil)
  command-execute((lambda nil (interactive) (call-interactively (intern (ido-completing-read "M-x " (all-completions "" obarray (quote commandp)))))))
```

**Comment by triclops200** [comment]
I submitted a pull request which fixes the bug.

**Comment by tarsius** [comment]
I just pushed another fix myself. Please try that first.

**Comment by triclops200** [comment]
Your new code works.

**Comment by triclops200** [comment]
:+1:

**Comment by tarsius** [comment]
Piuu... finally. Thanks for your help.

@henry-y Soooo, does this now tell you to get a newer Git?

**Comment by henry-y** [comment]
@triclops200 @tarsius 
Thanks for all your help.

@tarsius 
Yes, it tells me to get a newer Git.
```
Compiling magit-sequence.el
Error (magit): Magit requires Git >= 1.9.4, you are using 1.7.9.
```

*However, why does magit requires Git >= 1.9.4?
Under some circumstances, I may have not this higher version of git installed on the server.*

**Comment by tarsius** [comment]
The cost of supporting older versions was getting to high. The version check only runs locally so you can use older version on remote systems. But some things will break. You might not run into problems, but when you do, then make sure you can reproduce with a supported git, before reporting any issues.
