### ISSUE TITLE
Can't copy SHA refs

### ISSUE THREAD

**Issue by purcell** [magit/magit#1985]
In status or log mode, select the sha hex string for a commit and hit M-w to copy it.

Expected result: the hex string is copied.

Actual result: the HEAD ref name (in my case `master`) is copied instead. In log-mode, it's copied with added parens, e.g. `(master)`.

Very odd! :-)

**Comment by tarsius** [comment]
You might wanna update. 2ac057a4d884c9413b2767b326937e7699412355 should fix this.

**Comment by purcell** [comment]
Ah, thanks, yes -- I had updated, but I hadn't restarted Emacs since the latest `magit` got installed. Sorry for the noise. :-)

**Comment by tarsius** [comment]
No problem. It happens.
