### ISSUE TITLE
Staging hunks with context == 0 lines does not work

### ISSUE THREAD

**Issue by bastianbeischer** [magit/magit#1986]
I use magit regularly to stage individual hunks instead of entire files and this works great.

However, sometimes I need to lower the context size for the hunks, so that some hunks get split into two, which I can then stage individually. This works when the context is lowered to 2 lines, or even 1 line, but it does not work when the context is 0, i.e. one cannot stage individual lines.

I should say that staging does work, but it produces strange results: The change which I want to stage is not staged, but instead a blank new line at the end of the file is staged, but the working tree does not get that additional new line so that the working tree get's an additional diff with respect to the index. It's hard to explain but can be reproduced easily in a git repository of your choice.

I don't know if this is supposed to work, but if not one could think about limitting the context size to a minimum of 1 line?

**Comment by npostavs** [comment]
> sometimes I need to lower the context size for the hunks, so that some hunks get split into two, which I can then stage individually.

You can also stage part of a hunk without having to change the context size by marking the particular lines.

See http://magit.vc/manual/magit/Staging-and-unstaging.html

**Comment by tarsius** [comment]
> but it does not work when the context is 0

Fixed. It was a regression. `magit-diff-context-p` was not adjusted when `magit-diff-section-arguments` was added.

**Comment by bastianbeischer** [comment]
Thanks for the prompt fix and for the info about using the region to stage individual parts of a hunk - very useful!
