### ISSUE TITLE
magit-blame toggle option

### ISSUE THREAD

**Issue by fommil** [magit/magit#1987]
Until today, I used to be able to bind `magit-blame-mode` to a key binding (actually, one of my very few global "Super" bindings because I use it so much). But now this is deprecated, and although `magit-blame` does start blame mode... it does not toggle it off.

It would very much like to have a magit-blame toggle interactive function back, please.

**Comment by fommil** [comment]
workaround:

```elisp
(defun magit-blame-toggle()
  "WORKAROUND https://github.com/magit/magit/issues/1987"
  (interactive)
  (let* ((active (--filter (and (boundp it) (symbol-value it)) minor-mode-list)))
    (if (member 'magit-blame-mode active)
        (magit-blame-quit)
      (magit-blame nil buffer-file-name))))
```

**Comment by tarsius** [comment]
The reason why there cannot be a command that toggles blame information is that blaming is no recursive. Using the same command again (`magit-blame`) doesn't turn of blaming, instead it blames further back.

What's wrong with pressing <kbd>q</kbd> to turn off blame information?

Or if you want to use the same key to turn blaming on and off, then just bind whatever key you have bound in the global map to `magit-blame`, to `magit-blame-quit` in `magit-blame-mode-map`. Of course that makes it harder to blame recursively, so probably you don't want that - and should instead just remember, that <kbd>q</kbd>, like in many other places, quits.

**Comment by fommil** [comment]
hmm, ok wasn't aware that `q` quit from this mode. I'll try that, thanks.
