### ISSUE TITLE
Respect .mailmap for log commands

### ISSUE THREAD

**Issue by glucas** [magit/magit#1991]
When a .mailmap is present it would be great to use it for the author name in magit log buffers. 

I first tried adding `--use-mailmap` to my `magit-log-arguments`, but that didn't work. After digging into the code a bit I found that changing the format string in `magit-insert-log` to use this:

    [%%aN]

instead of 

    [%%an]

works. I believe this change is generally safe: when there is no .mailmap file `%aN` behaves the same as `%an`.

For more on mapping authors with mailmap, see http://git-scm.com/docs/git-shortlog.

**Comment by glucas** [comment]
The format change works for displaying the mapped author name in magit log buffers, but it looks like further changes would be required to also support mapped names for the `--author` filter. From the command line I can use for example `git log --use-mailmap --author="Joe"` to find commits for the user I've locally mapped to `Joe`. 

That isn't working in magit with the changes described above.

**Comment by glucas** [comment]
If I add `"--use-mailmap"` to the log arguments in `magit-insert-log` then the author filter works as well.

I'll submit a pull request with these changes for consideration.

**Comment by tarsius** [comment]
Okay, let's do it. Finish the pr and I will merge.

**Comment by ORESoftware** [comment]
sorry but what does "respecting .mailmap" mean exactly?

**Comment by glucas** [comment]
It means: if a .mailmap file is present, apply it to git log commands as described in the linked git documentation. 

The corresponding PR was merged years ago — I’ve been using this behavior for a long time now!
