### ISSUE TITLE
Need a more efficient way of popping stash@{0}

### ISSUE THREAD

**Issue by mgalgs** [magit/magit#1994]
From `GIT-STASH(1)`:

    pop [--index] [-q|--quiet] [<stash>]
    ...
        When no <stash> is given, stash@{0} is assumed

So it's really quick to pop the stash sitting on the top of your stash stack simply by omitting the `<stash>` argument.  It would be nice if magit had an equivalently efficient method of popping the top stash (a common operation).

**Comment by tarsius** [comment]
More efficient than `z p`?

**Comment by mgalgs** [comment]
But it's not just `z p`, it's `z p <TAB> 0 <TAB>`. And putting point on a stash is also too much work.

**Comment by mgalgs** [comment]
`z p <TAB> 0 <TAB> <RET>`, that is (can't edit as I'm in mobile).

**Comment by npostavs** [comment]
With `magit-ido-completing-read` it's just `z p RET`. How about applying

```diff
diff --git c/lisp/magit-git.el i/lisp/magit-git.el
index 4a690af..ad970fb 100644
--- c/lisp/magit-git.el
+++ i/lisp/magit-git.el
@@ -979,7 +979,7 @@ (defun magit-read-stash (prompt &optional use-at-point)
         (magit-completing-read prompt
                                (--map (car (split-string it ":"))
                                       (magit-git-lines "stash" "list"))
-                               nil t nil nil atpoint))))
+                               nil t nil nil (or atpoint "stash@{0}")))))
 
 (defun magit-read-remote (prompt &optional default use-only)
   (let ((remotes (magit-list-remotes)))
```

Then it would `z p RET` for normal completion too.

**Comment by tarsius** [comment]
@npostavs Sound like a good idea. But we should also make sure that there actually exist at least one stash, before offering the first as default choice.

**Comment by mgalgs** [comment]
Works perfectly.  Thanks @npostavs!
