### ISSUE TITLE
Add --tags flag to pull popup

### ISSUE THREAD

**Issue by mrkkrp** [magit/magit#1995]
Pull popup has enough of space to add more options. Once I created tags using GitHub web interface and to get them to my local copy of repo I needed to resort to command line interface of `git`. Can we add `--tags` switch to pull popup? Push popup has it.

**Comment by bastianbeischer** [comment]
I don't know what pulling a tag would mean. Do you want to merge the commit pointed to by "tag" into your local branch?

If you just want to receive all the tags which have been added on the remote side you "fetch" them. And indeed the "fetch" menu (<kbd>f</kbd>) lets you run 'git fetch' and 'git remote update' which will get the tags from the remote.

**Comment by npostavs** [comment]
[git-pull(1)](http://git-scm.com/docs/git-pull) doesn't list a `--tags` switch, though it does list a `--no-tags` switch.

> --no-tags

>    By default, tags that point at objects that are downloaded from the remote repository are fetched and stored locally. This option disables this automatic tag following. The default behavior for a remote may be specified with the remote.<name>.tagOpt setting. See git-config[1].

**Comment by mrkkrp** [comment]
Sorry, after further investigation I see that tags are downloaded by default when you run `git pull`. There is even an option to disable this (`--no-tags`). So, fetch menu is not necessary either, you just pull to get the tags. This is how it works on the command line. But if I press `F F` tags are not downloaded -- why? I think this is what tricked me into thinking that I need `git pull --tags`.

**Comment by mrkkrp** [comment]
If you want to keep present behavior (not downloading tags on pull), you should allow user to explicitly state that he needs tags too. On the other hand you could download tags by default on `F F`, just like `git pull` does, but add option `--no-tags` then.

**Comment by lbolla** [comment]
Magit does not pull tags if a remote and revision are specified. On "F F" magit does, let's say, "git pull origin master" so tags are not pulled. If it did "git pull", than you would get tags, too.
I much preferred the old behaviour (in Magit 1.x) of doing "git pull" rather than "git pull <remote> <rev>".
Maybe there could be a switch in the "pull popup" to remove <remote> and <revision> and just do a git pull?

**Comment by tarsius** [comment]
I have changed `magit-pull-current` so that it usually does not specify the remote and remote branch.

**Comment by jacobilsoe** [comment]
If I do a `F u` on the develop branch, magit executes `git pull origin develop`. With this issue resolved I  would expect a `git pull`. Is this a regression? I'm using magit 20160119.1409.

**Comment by tarsius** [comment]
`F u` is supposed to pull from the upstream configured for the current branch. This has to be done using `git pull UPSTREAM-REMOTE UPSTREAM-BRANCH` because what `git pull` does may be controlled by many more variables those involved in setting the upstream.

**Comment by jacobilsoe** [comment]
Yeah, that makes sense. So how can you do the equivalent of a `git pull` from magit?

**Comment by tarsius** [comment]
Ups, my last message was a bit confused. That was mostly about pushing. (I've gotten a lot about questions about that lately.) But to some extend, what I said also applies to pulling.

From the `git-pull` manpage:

> git pull [options] [<repository> [<refspec>...]]
>
> Default values for <repository> and <branch> are read from the "remote" and "merge" configuration for the current branch as set by git-branch(1) --track.

So `git pull` should really do the same as `git-pull <remote> <merge>`. Doesn't it do that given your configuration?

**Comment by tarsius** [comment]
Ah, you already said it doesn't...

Check the values of `branch.develop.remote` and `branch.develop.merge` using the branch popup (`b`).

**Comment by tarsius** [comment]
Okay I have read the old posts above. This has indeed changed and I don't think I want to go back to how it was before. But like I restored `magit-push-implicitly` (see its doc-string), I might consider adding `magit-pull-implicitly`.

**Comment by lbolla** [comment]
I think it would be useful to be able to do a simple `git pull`: I do it all the time in the console to get commits and tags at the same time. I never do fetch+merge manually: that's what pull is for.

**Comment by greenrd** [comment]
:+1: on simple git pull.

**Comment by lbolla** [comment]
I ended up hacking `magit-remote.el` by adding this function:

    (defun magit-pull-from-everywhere ()
      (magit-git-pull "" nil))

and adding to `magit-pull-and-fetch-popup` a new "everywhere" location:
    
             (?f "everywhere"              magit-pull-from-everywhere)
             (?p magit-get-push-branch     magit-pull-from-pushremote)
             (?u magit-get-upstream-branch magit-pull-from-upstream)
             (?e "elsewhere"               magit-pull))

So now, "F f" runs `git-pull`.
