### ISSUE TITLE
magit-dired-jump errors on some occasions

### ISSUE THREAD

**Issue by Malabarba** [magit/magit#1996]
In the status buffer, if I place point on an untracked file like the following and call `magit-dired-jump`,

    Untracked files (1)
    debug.gif

I get an error from dired-jump saying that `dired-goto-file: File name debug.gif' is not absolute`.
This seems to be fixed if I add and `expand-file-name` around `(magit-file-at-point)` in the definition of `magit-dired-jump`.

**Comment by tarsius** [comment]
Yep, that does the trick. Thanks
