### ISSUE TITLE
Magit cannot call emacsclient anymore: *ERROR*: Wrong type argument: arrayp, t

### ISSUE THREAD

**Issue by tsdh** [magit/magit#1998]
Since the two last MELPA upgrades (now on magit 20150707.430), when I want to commit my staged changes using `c c` I get the diff buffer but no commit message buffer appears.  The magit process buffer contains:

```
  1 git … commit --
Waiting for Emacs...
*ERROR*: Wrong type argument: arrayp, t
error: There was a problem with the editor '/home/horn/bin/emacsclient --socket-name=/tmp/emacs1000/server'.
Please supply the message using either -m or -F option.
```

Invoking `emacsclient` from the command line still works as expected.  I didn't upgrade emacs in between (still a current git master checkout).

**Comment by tarsius** [comment]
There has just been a major update to Magit. When using Melpa that is hard to notice because it uses timestamps as version strings. You should reinstall Magit as described here: http://magit.vc/manual/magit/Installation.html. That might fix the issue, or not.

**Comment by tsdh** [comment]
@tarsius Yes, I've done that procedure already yesterday.  The first post-2.1.0 release from MELPA worked fine, and only the two versions that appeared this afternoon exhibit the issue.

**Comment by tarsius** [comment]
Hm, I cannot think of a recent commit which I would expect could have an effect on this. Maybe something else changed. Did you also update Emacs?

Please follow the instructions at http://magit.vc/manual/with-editor/Debugging.html, so that we can figure out what's going on.

**Comment by tarsius** [comment]
My guess would be that the version of Git installed on the remote is to old. The debug script does not cover this case I believe, so please check manually what version is installed on the remote.

**Comment by tsdh** [comment]
`M-x with-editor-debug` messages `apply: Searching for program: No such file or directory, emacsclient.c` and then shows this in a new buffer:

```
with-editor: /home/horn/.emacs.d/elpa/with-editor-20150701.1246/with-editor.el
emacs: /home/horn/Repos/el/emacs/src/emacs (25.0.50.2)
system:
  system-type: gnu/linux
  system-configuration: x86_64-unknown-linux-gnu
  system-configuration-options: 'CFLAGS=-g -ggdb3 -O1 -DTRACE_SELECTION'
server:
  server-running-p: t
  server-process: #<process server>
  server-use-tcp: nil
  server-name: server
  server-socket-dir: /tmp/emacs1000
    server
  server-auth-dir: ~/.emacs.d/server/
    WARNING: not an accessible directory
magit-emacsclient-executable:
 value:   /home/horn/bin/emacsclient (25.0.50)
 default: /home/horn/bin/emacsclient (25.0.50)
 funcall: /home/horn/bin/emacsclient (25.0.50)
path:
  $PATH: "/home/horn/.gem/ruby/2.2.0/bin:/home/horn/.cask/bin:/home/horn/Repos/utils:/home/horn/bin:/home/horn/.local/bin:/usr/local/texlive/2015/bin/x86_64-linux:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
  exec-path: (/home/horn/.gem/ruby/2.2.0/bin /home/horn/.cask/bin /home/horn/Repos/utils /home/horn/bin /home/horn/.local/bin /usr/local/texlive/2015/bin/x86_64-linux /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /home/horn/Repos/el/emacs/lib-src)
  with-editor-emacsclient-path:
    /home/horn/Repos/el/emacs/src (t)
    /home/horn/.gem/ruby/2.2.0/bin (t)
    /home/horn/.cask/bin (t)
    /home/horn/Repos/utils (t)
    /home/horn/bin (t)
      emacsclient (25.0.50)
      emacsclient-24 (24.5.50)
    /home/horn/.local/bin (t)
    /usr/local/texlive/2015/bin/x86_64-linux (t)
    /usr/local/sbin (t)
    /usr/local/bin (t)
    /usr/bin (t)
      emacsclient (25.0.50)
    /usr/lib/jvm/default/bin (t)
    /usr/bin/site_perl (t)
    /usr/bin/vendor_perl (t)
    /usr/bin/core_perl (t)
    /home/horn/Repos/el/emacs/lib-src (t)
      emacsclient (25.0.50)
```

`/home/horn/bin/emacsclient` is a symlink to `/home/horn/Repos/el/emacs/lib-src/emacsclient` in my emacs checkout.

What's wrong in the output is that `/usr/bin/emacsclient` was version 25.0.50.  Actually, it is 24.5.

**Comment by tsdh** [comment]
I found the culprit, and it's not a version upgrade.  Between working and broken, I've `(setq magit-diff-highlight-indentation t)`.  With that variable set to `t`, I get the error from this bug report.  As soon as I set it back to its default value `nil`, the commit message buffer appears as intended.

**Comment by tarsius** [comment]
> What's wrong in the output is that `/usr/bin/emacsclient` was version 25.0.50. Actually, it is 24.5.

I strongly doubt that (or misunderstand what you are saying) because that value is retrieved by running `/usr/bin/emacsclient --version`, and unless that lies...

> I've `(setq magit-diff-highlight-indentation t)`.  With that variable set to `t`, I get the error from this bug report.

That must be it.

**Comment by tsdh** [comment]
Jonas Bernoulli <notifications@github.com> writes:

>> What's wrong in the output is that `/usr/bin/emacsclient` was version
>> 25.0.50. Actually, it is 24.5.
>
> I strongly doubt that (or misunderstand what you are saying) because
> that value is retrieved by running `/usr/bin/emacsclient --version`,
> and unless that lies...

I don't know why you get a different value, but here...

,----[ M-! /usr/bin/emacsclient --version RET ]
| emacsclient 24.5
`----

>> I've `(setq magit-diff-highlight-indentation t)`.  With that variable
>> set to `t`, I get the error from this bug report.
>
> That must be it.

After re-reading its docs, I see that `t` is not a valid value for this
variable.  I thought it was boolean because of its name and the other
variables `magit-diff-highlight-hunk-body` and
`magit-diff-highlight-trailing` which are boolean, too.
