### ISSUE TITLE
Ediffing branches

### ISSUE THREAD

**Issue by herbertjones** [magit/magit#1999]
I apologize if this issue has been raised before.  I am seeking out an easier way to do code reviews.  I would like to be able to compare two revisions/branches with each other.  Ideally I would be able to see the list of files changed, then do an ediff on each file individually.

Currently I have figured out how to get a diff of a range of commits, but no way to ediff them easily.  I tried using magit-ediff-dwim, as suggested in other places, from the diff of the range, but it presents me with a list of many files even though only 4 were changed.  After typing in one of the filenames, it ends up displaying the difference between the older range in the diff with one commit earlier than the older range in the diff instead of the newer range.  I also see I can ediff individual files in individual commits.  However this isn't ideal when someone does a pull request with a large number of commits, as it would be more efficient to compare the start to the end once, instead of ediffing each file of each commit.

My question in summary is, is there a way to easily ediff a range of commits, such as would be done when reviewing a large pull request?

**Comment by tarsius** [comment]
> Ideally I would be able to see the list of files changed, then do an ediff on each file individually.

That's not currently supported but it sounds like a good idea. I will probably implement it eventually but am currently prioritizing other things...

> I tried using magit-ediff-dwim, as suggested in other places, from the diff of the range, but it presents me with a list of many files even though only 4 were changed.

... like that for example. I actually just sat down to work on this :-)

**Comment by tarsius** [comment]
But there's a heatwave and I probably won't get anything done today :-/

**Comment by Silex** [comment]
Can't you simple `d r` then input a range like "master..feature" and then press `e` in the individual diffs?

**Comment by Silex** [comment]
> But there's a heatwave and I probably won't get anything done today :-/

Yeah, I'm actually shirtless at work, with a fan directly in my face :-O

**Comment by tarsius** [comment]
Feet in a cannot-think-of-english-or-german-word of cold water, fan at 45d angle.

> with a fan directly in my face

Were did you put the monitor?!

**Comment by Silex** [comment]
>> with a fan directly in my face

> Were did you put the monitor?!

Like you, 45 degree angle.

**Comment by tarsius** [comment]
> I tried using magit-ediff-dwim, as suggested in other places, from the diff of the range, but it presents me with a list of many files even though only 4 were changed.

When point is on a file section then it should now automatically use that. If not you still have to select one and the list of completion candidates still isn't being filtered to remove files that did not actually change in the range.

**Comment by herbertjones** [comment]
Awesome, thanks.  I'll try it out tomorrow.

**Comment by tarsius** [comment]
When you have done that, could you please rehash the points which have not been fully addressed yet.

**Comment by herbert-jones-mediafire** [comment]
I downloaded magit from the current github master, but I get the error ```read-kbd-macro: Args out of range: "C-SPC", 357, 5``` when ```debug-on-error``` is true and ```string-match-p: Wrong type argument: stringp, nil``` when not.  This happens when using magit-ediff-dwim and entering anything for "Compare range or commit (master):".

**Comment by herbertjones** [comment]
I downloaded magit from the current github master, but I get the error read-kbd-macro: Args out of range: "C-SPC", 357, 5 when debug-on-error is true and string-match-p: Wrong type argument: stringp, nil when not. This happens when using magit-ediff-dwim and entering anything for "Compare range or commit (master):".

**Comment by kyleam** [comment]
nil is being passed to magit-changed-files.  I think magit-ediff-compare--read-revisions should construct the range when one isn't given:

```diff
diff --git a/lisp/magit-ediff.el b/lisp/magit-ediff.el
index d4eb687..00afe16 100644
--- a/lisp/magit-ediff.el
+++ b/lisp/magit-ediff.el
@@ -190,7 +190,8 @@ (defun magit-ediff-compare--read-revisions (&optional arg)
                (when (match-string 2 input)
                  (setq revA (magit-git-string "merge-base" revA revB))))
       (setq revA (concat input "^")
-            revB input))
+            revB input
+            range (concat revA ".." revB)))
     (list range revA revB)))
 
 (defun magit-ediff-compare--read-files (range revA revB &optional fileB)
```

**Comment by tarsius** [comment]
That seems right, yes. Applied this change.

**Comment by herbertjones** [comment]
I updated from melpa today.  Currently I am doing the following to get the unexpected behavior.

1. I checkout the branch I want to compare, which happens to be a few commits ahead of ```master```.
2. I select "Log local branches"
3. I move to the commit which matches ```master```.
4. I do a "Diff commits" to get a ```*magit-diff``` buffer of the differences between the checked out branch and ```master```.
5. Selecting any file with ediff dwim will open ediff with ```master^``` and ```master``` instead of ```master``` and ```HEAD```.

I'm not sure that's intended or if maybe I'm doing things in the wrong order.

However, I am able to get the desired behavior by doing an "ediff Compare" from within the ranged diff then entering the range as ```master..HEAD```.

**Comment by kyleam** [comment]
> 4. I do a "Diff commits" to get a ```*magit-diff``` buffer of the differences between the checked out branch and ```master```.
> 5. Selecting any file with ediff dwim will open ediff with ```master^``` and ```master``` instead of ```master``` and ```HEAD```.
>
> I'm not sure that's intended or if maybe I'm doing things in the wrong
> order.

Currently magit-ediff-compare interprets a single revision as
"rev^..rev" when called interactively.  You can diff master with HEAD
using "master.."  (like with git diff).  So, the behavior that you
cannot get interactively is a revision compared to the working tree
(with git diff you would just give a revision as an argument).

Depending on what results from #2059, this may change.  With that, the
arguments would be interpreted just as they are with git diff (i.e., a
single revision would be compared with a working tree).  Depending on
the context of point, the prompt default will be "rev^..rev".

**Comment by tarsius** [comment]
#2059 has been merged.

**Comment by juhp** [comment]
I am still lost - I mean I can ediff a file between branches, but the buffers are read-only!
I want to merge some changes from one branch to another manually, is that possible in 2020 magit?
(Maybe it's better I open a new ticket?)

**Comment by Silex** [comment]
@juhp: display the changes from the other branch, then press `a` to apply hunks.

**Comment by juhp** [comment]
> @juhp: display the changes from the other branch, then press `a` to apply hunks.

Thank you! Will try that next time
