### ISSUE TITLE
Ediff dynamic binding of buffer-file-name breaks flymake

### ISSUE THREAD

**Issue by derek-upham** [magit/magit#2003]
When magit sets up ediff, it assigns major modes to the temporary buffers by:

1. Dynamically binding them to use the same on-disk file as the "real" buffer.
2. Setting the major mode as if the temporary buffer were the real file.
3. Removing the dynamic binding.

I have emacs configured to set up flymake when entering certain major modes, and this technique breaks flymake.  Everything looks normal at the start, but when flymake tries to run, it no longer finds an on-disk file to syntax-check.  That is a sanity check failure.

When you set the on-disk file for the temporary buffers, can you also set some sort of variable that says "this buffer does not have a file"?  It could be dynamically bound, or it could be a buffer-local variable that survives major mode changes.  That would give my code the ability to recognize that special case, and skip flymake setup.

**Comment by tarsius** [comment]
You are talking about things happening inside `magit-find-file-noselect`, right? And using Magit `v2.1.0`?

**Comment by derek-upham** [comment]
Yes, this is with the latest (although it affected earlier versions as well).  Both magit-find-file-noselect and magit-find-file-index-noselect use the technique.

Binding a new `magit-original-buffer-file-name` variable to `buffer-file-name` (before changing `buffer-file-name`) would be enough to distinguish real files from buffers.

**Comment by tarsius** [comment]
I think `(and magit-buffer-file-name (equal buffer-file-name magit-buffer-file-name))` should work too.

I intend to implement a proper file handler in a library `git-handler.el` once things cool down a bit. So I would like to avoid making changes to the current implementation (which I always considered a kludge), if it can be avoided.

**Comment by derek-upham** [comment]
On further reflection, binding `magit-original-buffer-file-name` to `buffer-file-name` wouldn't help, since `magit-original-buffer-file-name` would be `nil` in both these code paths and the "ordinary" code paths.

**Comment by tarsius** [comment]
So does my suggestion work or not?

**Comment by derek-upham** [comment]
`(and magit-buffer-file-name (equal buffer-file-name magit-buffer-file-name))` as a test to distinguish real files from pretend files, in the major mode hook?  I expect that will fail, as the code binds `buffer-file-name` to `magit-buffer-file-name`.  They should always be equal.

I think testing for the existence of `magit-buffer-file-name`, `magit-buffer-revision`, or `magit-buffer-refname` should work for me.  They are permanent buffer-local, they default to `nil`, and they are only set in the two contexts we are discussing.  They are internal, so they aren't documented and aren't guaranteed to exist, but they should last until you write `git-handler.el`.

**Comment by derek-upham** [comment]
Testing for any of those three distinguishes between the two cases, so it's a good workaround.

**Comment by tarsius** [comment]
Great :)

You found the solution, but lets classify it as `support` anyway.

**Comment by derek-upham** [comment]
Like I said, I'd feel more comfortable using documented variables than internal ones, but this will work until 2.2.0.

**Comment by tarsius** [comment]
It most likely will work until `git-handler.el` and when Magit starts using that, then it's probably time for a `3.1.0` release.
