### ISSUE TITLE
Ask user when commit selection leaves it undecided whether to use a...b, a..b, b...a, or b..a

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2006]
When the user selects sibling commits (and branches) using the region and neither end-point is an ancestor of the other, with the intention to use diff or ediff, then it is ambiguous which comparison is actually desired.

Currently we always use a..b, a being the end-point which appears first in the buffer.

A tiny part of the solution can be found in `magit-ediff-compare--read-revisions`.

**Comment by kyleam** [comment]
Another option would be to leave the behavior as is and allow both
these things (the order and range type) to be changed with a key in
magit-diff-refresh-popup or magit-diff-mode-map.

**Comment by kyleam** [comment]
Ahh, but I guess that wouldn't handle ediff (which could do the swapping fine, but not the range change).

**Comment by kyleam** [comment]
As of bd5a2d91ae95e7bf90ee830ddb6f66df0620d81e, it's possible to use a "..." range.  @tarsius I'll close this and let you reopen if you want something other than that solution.
