### ISSUE TITLE
Possible to commit two identical commits

### ISSUE THREAD

**Issue by AlexChesters** [magit/magit#2013]
Magit 2.0+ seems to be slower than 1.4 when dealing with large commits, it seems to take a while after committing for this to be reflected in the buffer, at this point it is possible to commit the same files again, resulting in two identical commits

**Comment by Silex** [comment]
Well, "two identical commits" is a git impossibility. Can you elaborate?

**Comment by tarsius** [comment]
Please reopen when you can reproduce the issue.
