### ISSUE TITLE
branch

### ISSUE THREAD

**Issue by malloc82** [magit/magit#2014]
In the older version I can see all the local branches using branch-manager. I can't find the equivalent in 2.1.0. The only way I can get a list is to issue a checkout and then use tab completion to get all the branches to show up in a separate window. Is this how it's supposed to work now? Is there another way to view current branches, something equivalent of ```git branch -vvv```?

**Comment by tarsius** [comment]
`y`

**Comment by Silex** [comment]
For completeness, this issue is a duplicate of https://github.com/magit/magit/issues/1966

**Comment by malloc82** [comment]
ah, thx guys
