### ISSUE TITLE
question on log

### ISSUE THREAD

**Issue by malloc82** [magit/magit#2015]
In older version there was a long log option, I can't find it in 2.1.0. Is it gone?

**Comment by npostavs** [comment]
From the 2.1.0 release notes

>  * Support for displaying diffs inside the log buffer instead of in a
   separate diff buffer has been removed.  It might come back one day,
   but the old implementation had just fallen behind regular one-line
   log too much.

**Comment by tarsius** [comment]
Yep. Also I never was a fan and have enough other things on my plate, so don't expect a refreshed "long log" anytime soon.

**Comment by malloc82** [comment]
I see, thx
