### ISSUE TITLE
magit-commit

### ISSUE THREAD

**Issue by malloc82** [magit/magit#2016]
In 2.1.0, whenever I try to make a new commit, there is always a magit-diff window pops up first, I have to ```q``` it to move to commit window to edit commit message. Is there anyway to turn this behavior off?

**Comment by tarsius** [comment]
The diff buffer should be shown in some window, but the window displaying the buffer used to edit the message should be selected. Isn't that the case for you?

**Comment by malloc82** [comment]
Only when I have multiple windows open. I suppose I could add the diff buffer to special-display-buffer-names to make it auto split.
