### ISSUE TITLE
Add "branch manager" to the branch popup

### ISSUE THREAD

**Issue by YoungFrog** [magit/magit#2017]
As examplified by #1966 and #2014, some people (me included) didn't find the new command/binding (hit "y") that replaces the old branch manager. In fact I expected to see that command from the branching popup. I thus hereby suggest to add it there.

**Comment by tarsius** [comment]
This will continue to confuse users but I still have no intention to restore the old binding. Occasionally I enter the branch when I intend to merge some branch. I don't know why I make that mistake in this case, but not for other branch-related things. Still I am not adding merge to the branch popup. 

But to reduce the amount of duplicates this should be added to the FAQ. Could someone please do that.

**Comment by YoungFrog** [comment]
I left a note about the problem at https://github.com/magit/magit/wiki/FAQ

**Comment by tarsius** [comment]
Thanks!

**Comment by seh** [comment]
By finding this issue I was finally able to figure out where the "branch manager" went. However, even when I press <kbd>y</kbd> and move the cursor onto a branch name, I can't figure out a keystroke to checkout that branch. That used to be the natural action in the "branch manager". Is there supposed to be such a binding?

**Comment by johnmastro** [comment]
> By finding this issue I was finally able to figure out where the "branch manager" went. However, even when I press y and move the cursor onto a branch name, I can't figure out a keystroke to checkout that branch. That used to be the natural action in the "branch manager". Is there supposed to be such a binding?

You can use `b b RET` to check out the branch at point (`b b` to checkout a branch, `RET` to accept the default, which will be the one at point).

**Comment by seh** [comment]
Ah, so it's still the old thing, just buried inside of a new thing. Got it. Muscle memory can more or less stay as is.
Thank you.

**Comment by tarsius** [comment]
This binding is available in anywhere in any Magit buffer.

**Comment by seh** [comment]
What I miss was being able to press <kbd>b v</kbd>, see  a list of my branches (like what <kbd>y</kbd> summons now), and then, with a single keystroke, check out one of those branches.

Now, <kbd>b b</kbd> prompts me for a branch name, which I may not remember because I can't see the whole list. If instead I use <kbd>y</kbd> and then put the point on the branch I'd like to check out, I can then hit <kbd>b b RET</kbd> or <kbd>C-u b RET</kbd>, which feels like two keystrokes too many.

I really expected <kbd>RET</kbd> to be the keystroke that would check out the branch under the point—though any single keystroke would do.

**Comment by npostavs** [comment]
> Now, b b prompts me for a branch name, which I may not remember because I can't see the whole list.

You can see the list of completions by hitting `TAB` (although there are some non-branch refs in the completion list).

**Comment by seh** [comment]
Right, but compared to the rest of the excellent Magit interface, the completion buffer's display is too spare. It doesn't give me the view I want to make this decision about which branch I'm looking for, even if all the characters are there in plain text.

**Comment by tarsius** [comment]
> Right, but compared to the rest of the excellent Magit interface, the completion buffer's display is too spare.

Only if you use standard completion. I recommend using Ido instead.

> I really expected <kbd>RET</kbd> to be the keystroke that would check out the branch under the point

I don't think that makes much sense. But I start wondering whether showing the tip commit makes any more sense. It's consistent with what would happen in other buffers, but maybe showing `HEAD..<branch>` would make more sense.

**Comment by seh** [comment]
I _am_ using `ido-mode`. Do I need to configure it to do something more pleasant when completing branch names?

When I hit <kbd>TAB</kbd> in the minibuffer, here's what I see in the `*Completions*` buffer:
```
Click on a completion to select it.
In this buffer, type RET to select the completion near point.

Possible completions are:
some-branch
master 	origin/HEAD
origin/something
origin/master
some-other-branch
yet-another-branch
v1.0.0 	v1.0.1
v1.0.3 	v1.0.4
v1.0.5 	v1.0.6
v1.0.7 	v1.0.8
v1.0.9
```
That's not much to recommend. The packing of multiple names onto a single line is distracting.

**Comment by tarsius** [comment]
That's what I use:

```lisp
(use-package ido
  :config
  (ido-mode)
  (ido-everywhere)
  (setq ido-auto-merge-work-directories-length -1
        ido-cannot-complete-command 'ignore
        ido-save-directory-list-file "~/.emacs.d/var/cache/ido.last"
        ido-use-virtual-buffers t)
  (use-package flx-ido
    :load-path "lib/flx"
    :config
    (flx-ido-mode)
    (setq ido-enable-flex-matching t))
  (use-package ido-ubiquitous
    :load-path "lib/ido-ubiquitous"
    :config (ido-ubiquitous-mode))
  (use-package ido-vertical-mode
    :load-path "lib/ido-vertical-mode"
    :init   (setq ido-vertical-define-keys nil)
    :config (ido-vertical-mode)))
```

+ smex but that's not relevant here.

**Comment by tarsius** [comment]
> I don't think that makes much sense.

Well, maybe it does. Have to think about it some more, but I don't find `b b RET` to be terribly inconvenient.

**Comment by seh** [comment]
I activated `ido-everywhere` and `ido-ubiquitous-mode`, and neither changed what I see when I hit <kbd>b b TAB</kbd>.

**Comment by tarsius** [comment]
So a unicorn at my last reply...

> I activated `ido-everywhere` and `ido-ubiquitous-mode`, and neither changed what I see when I hit <kbd>b b TAB</kbd>.

It's really the other two that are relevant here :-)

**Comment by tarsius** [comment]
I think it's fairly important that `RET` only ever *visits* things, at least by default. What "visit" means depends on the context, and I think showing the diff on a branch name in the refs buffer doesn't really make sense. Digging a little deeper it's also clear that it behaves like this in this buffer because that's what happens on branches in any buffer. Changing that is more complicated than changing a key binding. This is needed, and does what I think is the reasonable "visit" action in this buffer:

```lisp
(defun magit-show-branch ()
  "Show branch tip except in refs buffer ..."
  (interactive)
  (if (derived-mode-p 'magit-refs-mode)
      (magit-section-case
        (([branch * branchbuf]
          [tag    * branchbuf])
         (let ((ref (magit-section-value (magit-current-section))))
           (if current-prefix-arg ; TODO option to inverse meaning?
               (magit-checkout ref)
             (magit-show-refs ref))))
        ([commit * branchbuf]
         (call-interactively #'magit-show-commit)))
    (call-interactively #'magit-show-commit)))

(define-key magit-branch-section-map "\r" 'magit-show-branch)
(define-key magit-branch-section-map [return] 'magit-show-branch)
```

And with a prefix argument it does what you think it should do without a prefix argument :-) But notice the TODO.

**Comment by tarsius** [comment]
The original issue has been addressed, but not points raised afterwards.

**Comment by tarsius** [comment]
Well I suppose checking out a branch also qualifies as "visiting", but it is a slightly dangerous way of visiting and might fail. But not dangerous enough to have an option to make it the default.

**Comment by tarsius** [comment]
I have restored the `b v` binding. It shows the successor, but also instructs users to use `y` instead. Eventually this kludge is going to be removed again.

**Comment by tarsius** [comment]
And now, five months later, I have removed that kludge again.

**Comment by semperos** [comment]
@tarsius Thanks for all your hard work on Magit.

For bindings that you retire that aren't being used for anything currently (like `b v`), it might be helpful to make that binding print the deprecation even after you've made the switch. I either missed the warning or didn't update frequently enough to see it and went on the hunt this morning to find where the branch manager had moved to. Usually not a problem if bindings just change, but when things are moved out of the popups (which I think was a good decision in this case) it makes it tough to find things. Just my $0.02.

**Comment by tarsius** [comment]
> I either missed the warning

Yes you did. For almost half a year a deprecation notice was displayed.
