### ISSUE TITLE
magit-reverse can't reverse file deletions or additions

### ISSUE THREAD

**Issue by bastianbeischer** [magit/magit#2019]
It would be great if 'magit-reverse' could reverse file deletions (restore the file to workdir) or file additions (remove the file from workdir).

Currently it doesn't seem to work:

1) Find a commit which removed a file
2) Go to the change in the list of changes
3) Press 'v' to restore the file

-> It does not work.

magit-process shows this:

```
  1 git … apply --reverse --ignore-space-change -
error: scripts/mc-production/HOWTO: No such file or directory
```

It's very well possible that the same holds for magit-apply (<kbd>a</kbd>).

Also, a related question: Can I revert / apply changes from the diffstat part of the commit view?

**Comment by tarsius** [comment]
> It's very well possible that the same holds for magit-apply

Yes, it's the same issue. See #2007.
