### ISSUE TITLE
magit-log popup should get a 'r: log range' option

### ISSUE THREAD

**Issue by bastianbeischer** [magit/magit#2020]
I'd like to get the log view for things like:

master...HEAD

listing only the commits which fall into the given range.

It would be good if the range could be given directly, so that the full flexibility of specifying revision ranges is preserved (three dots, two dots, ...)

**Comment by tarsius** [comment]
`l o` can do that: `l o master...HEAD RET`. With completion and everything.

**Comment by bastianbeischer** [comment]
Thanks!
