### ISSUE TITLE
Viewing stash shows large number of files as deleted

### ISSUE THREAD

**Issue by greenrd** [magit/magit#2023]
I did not delete these files, they appeared as deleted mysteriously.

However, when I apply the stash, the files that are supposedly deleted in the stash, do not get deleted.

**Comment by tarsius** [comment]
I'll need more information to investigate this. What command did you use to create the stash? If you still have the stash, then please don't delete it just yet.

**Comment by tarsius** [comment]
Please reopen when you can reproduce the issue.
