### ISSUE TITLE
kill-ring-save in magit buffers

### ISSUE THREAD

**Issue by ewstearns** [magit/magit#2024]
I could not find a way to copy text from a magit buffer as text. M-w is mapped to magit-copy-buffer-thing-as-kill, which adds the branch name or commit hash to the kill ring, which I almost never want. Is there a configuration or mode where can copy the text in for example the magit-ref buffer to paste in an email?

**Comment by kyleam** [comment]
Selecting the region should behave as you want (with the most up-to-date magit).  See #1958.

**Comment by tarsius** [comment]
This has already been fixed and will be part of `2.2.0`.

In the future please use the search box, which would have given you this: https://github.com/magit/magit/search?q=M-w&type=Issues&utf8=%E2%9C%93
