### ISSUE TITLE
Having to drop to terminal to `git commit --patch` really stinks

### ISSUE THREAD

**Issue by czipperz** [magit/magit#2029]
I would like to be able to use git entirely from within emacs, but one core feature that I have recently discovered is the patch option for commit, especially the `s` option in it, which splits the commit into very small pieces.

Could this somehow be implemented as `-p` of  you please allow figure out somewhere for the patches to be made INCREDIBLY small? That would be great, however I'm not exactly sure how it would be implemented.

In a related note, the `e` option in `--patch` is also severely lacking, it would be nice if it was more integrated instead having to drop to the  command line to use it.

**Comment by kyleam** [comment]
In the status buffer, mark the region you want to stage and hit `s`.
See the manual's section on [staging](http://magit.vc/manual/magit/Staging-and-unstaging.html#Staging-and-unstaging).

**Comment by czipperz** [comment]
Yes I know that but the s option in patch mode allows EVEN SMALLER edits than what are possible. The interface into patch is good enough for most patch usage

**Comment by npostavs** [comment]
> Yes I know that but the s option in patch mode allows EVEN SMALLER edits than what are possible

As far as I can tell, the `s` option doesn't let you split into hunks smaller than a single line. So it's exactly as capable as magit's region staging.

**Comment by tarsius** [comment]
You can get smaller hunks by pressing `-`. And you can stage part of a hunk, by marking that part of the hunk using the region, and only then pressing `s`.

**Comment by czipperz** [comment]
@tarsius this does the trick. Could you add this somewhere on the diff page because I had no idea.

**Comment by npostavs** [comment]
It's already under "[Refreshing diffs][1]".

[1]: http://magit.vc/manual/magit/Refreshing-diffs.html
