### ISSUE TITLE
Checkout commit from log

### ISSUE THREAD

**Issue by holocronweaver** [magit/magit#2034]
Is there an easy way to checkout a particular commit while reading the log? 

Currently I copy/paste the commit hash into the branch dialog (via `b b`), but preferably I could just place the cursor on the log line of a commit and do something like `b b enter` and the default choice would be that commit.

**Comment by tarsius** [comment]
> Currently I copy/paste the commit hash into the branch dialog (via `b b`), 

The quickest way of doing that is `M-w b b C-y RET`. Is that good enough?

Actually there's another possibility but it might not work as well with the standard completion mechanism, with Ido (which is what I use). The first completion candidate is something like `tags/2.1.0~2^2~54`, which clearly isn't a branch, so if you check that out, then you end up with a detached HEAD as desired. With Ido this is as simple as `b b RET`.

**Comment by npostavs** [comment]
> The quickest way of doing that is `M-w b b C-y RET`

You mean `C-w ...`

**Comment by holocronweaver** [comment]
Thanks @tarsius  and @npostavs, that does the trick!

As for the second method @tarsius mentioned, I am not currently using Ido, but this may be the final excuse I need to give it a go.

**Comment by npostavs** [comment]
> Actually there's another possibility but it might not work as well with the standard completion mechanism, as it does when using Ido. The default completion candidate is something like tags/2.1.0~2^2~54, which clearly isn't a branch, so if you check that out, then you end up with a detached HEAD as desired. With Ido this is as simple as b b RET.

Actually, it looks like `b b RET` works for when using standard completion too (was going to suggest passing default like for the stash case, but found it was already done).

**Comment by tarsius** [comment]
> You mean `C-w ...`

Yes. Do you thing `M-w` should fallback to `magit-copy-as-kill` in buffers that have no buffer-thing?

**Comment by holocronweaver** [comment]
@npostavs is right, `b b RET` works using standard completion.

I think the `M-w` fallback sounds like a good idea. It was the first thing I tried before posting here.
