### ISSUE TITLE
magit-ediff-dwim passes nil range

### ISSUE THREAD

**Issue by kyleam** [magit/magit#2035]
In some cases (in revision mode, revision file, and the second case
[1] for commit), magit-ediff-dwim passes nil to
magit-ediff-compare--read-files, so this will cause the same error as
in #1999.

I suppose either magit-ediff-dwim should also make sure that range is
non-nil, like the #1999 patch, or magit-ediff-compare--read-files
should handle the nil range by replacing it with the rev as an
argument to magit-read-changed-file.

While I prefer the first approach (making sure range is always
explicitly set), the second approach seems like it might have been the
original intention because magit-ediff-compare--read-files is written
as though range can be nil even though magit-read-changed-file will
fail if it is:

    (setq fileB (magit-read-changed-file
                 range (if range
                           (format "In range %s compare file" range)
                         (format "Show changes in %s to file" revB))))

[1] On the second call to magit-section-case in magit-ediff-dwim,
commit and branch are tested again, but I don't think this should ever
be reached because it is tested in the first magit-section-case call.

**Comment by tarsius** [comment]
> seems like it might have been the original intention [to allow range to be nil]

That's indeed the case. When the diff for certain commit is shown, then we are technically showing the differences in the range "COMMIT^..COMMIT", but it makes more sense to think of it as showing the changes "in" (introduced by) COMMIT. And we should use use the second prompt "Show changes in COMMIT to file: ". And RANGE being nil was indeed intended to signal that.

I even think we should take it a step further and allow revA to be nil too. (But not change the argument order, since it is the same used everywhere else too.)

```diff
diff --git a/lisp/magit-ediff.el b/lisp/magit-ediff.el
index 00afe16..41fd7cb 100644
--- a/lisp/magit-ediff.el
+++ b/lisp/magit-ediff.el
@@ -189,17 +189,18 @@ (defun magit-ediff-compare--read-revisions (&optional arg)
                      range (match-string 0 input))
                (when (match-string 2 input)
                  (setq revA (magit-git-string "merge-base" revA revB))))
-      (setq revA (concat input "^")
-            revB input
-            range (concat revA ".." revB)))
+      (setq revB input))
     (list range revA revB)))
 
 (defun magit-ediff-compare--read-files (range revA revB &optional fileB)
+  (unless revA
+    (setq revA (concat revB "^")))
   (unless fileB
     (setq fileB (magit-read-changed-file
-                 range (if range
-                           (format "In range %s compare file" range)
-                         (format "Show changes in %s to file" revB)))))
+                 (or range (concat revA ".." revB))
+                 (if range
+                     (format "In range %s compare file" range)
+                   (format "Show changes in %s to file" revB)))))
   (list (or (car (member fileB (magit-revision-files revA)))
             (car (rassoc fileB
                          (cl-mapcan
```

> On the second call to magit-section-case in magit-ediff-dwim, commit and branch are tested again, but I don't think this should ever be reached because it is tested in the first magit-section-case call.

Yes, you're right. Have to look into that too.

**Comment by tarsius** [comment]
I'll have to refactor a bit.

**Comment by kyleam** [comment]
I think there is a problem with using a single revision argument to
mean "revB^..revB".  A single revision, according to
magit-ediff-compare's docstring and code as well as "git diff", means
compare to the working tree.  But right now, if a single rev is passed
interactively, "rev^..rev" will be diffed rather than revB and the
working tree.  So, at the moment, I don't think ediff can be used to
compare to the working tree.

I think it's good for the range/rev arguments to diffing commands to
be consistent with "git diff".  However, then that means that the only
way to use magit-ediff-compare to show change in a single commit would
be for the user to explicitly input the "rev^..rev" syntax (though
magit-ediff-dwim does this in many cases).  magit-diff doesn't have
this problem because there is magit-show-commit, so perhaps it is
worth having a magit-ediff-show-commit.

I've pushed a branch with some changes related to this.  Even though
these might not be in the direction you end up heading with this, I
think some of the commits may be worth incorporating or at the least
be helpful for discussion.

**Comment by tarsius** [comment]
> Even though these might not be in the direction you end up heading with this,

I think this makes a lot of sense and looks very promising.

The part I intended to refactor (by combining and then also improving) is the commit/branch related dwimming performed by `*compare` and `*dwim` (each variant does certain things better than the other but even combined not good enough). Your changes go further than that and concentrate on other aspects.

I have dumped my very unfinished work to https://github.com/magit/magit/tree/jb/dump/compare-dwimming. Feel free to either incorporate *or* ignore that.

**Comment by kyleam** [comment]
> The part I intended to refactor (by combining and then also
> improving) is the commit/branch related dwimming performed by
> *compare and *dwim (each variant does certain things better than the
> other but even combined not good enough).

Hmm, I guess I wasn't viewing magit-ediff-compare as dwim-y, but more
like magit-diff, where it tries to give a helpful default, but its
main advantage is that it let's the user input a range that is
interpreted as a range to git diff would be.  That would put these
functions on the same level as magit-ediff-show-staged,
magit-diff-working-tree, etc.  Then magit-diff-dwim and
magit-ediff-dwim can wrap all of these, and try to choose the best
one.

I've pushed some more changes, which include

* ediff now piggybacks on diff's dwim interface, which should make
  maintaining consistency between them easier.

* Add a few more ediff commands and popup keys.

* Allow for "..." ranges to be specified when selecting a region
  (#2006).

**Comment by tarsius** [comment]
> Hmm, I guess I wasn't viewing magit-ediff-compare as dwim-y, but more like magit-diff, where it tries to give a helpful default,

Oh, I didn't mean it should just start doing stuff, but that it should *suggest* the most reasonable one. And Dwim should *just do* the most reasonable thing. Obviously there's room for sharing code here :-)

> ediff now piggybacks on diff's dwim interface, which should make maintaining consistency between them easier.

It makes sense if these offer approximately the same commands, yes. Maybe stuff can also flow into the other direction.

**Comment by tarsius** [comment]
@kyleam Could you please apply a fix for this. My 87ba6f703b566fae635d76526bc29f2b8385c68a would do so, but it conflicts with the changes you are working on. If you apply that commit anyway, or add another intermediate step, then please rebase  #2059 on top of that.

**Comment by kyleam** [comment]
> Could you please apply a fix for this. My 87ba6f7 would do so,

Sure.  I've pushed a change similar to 87ba6f7.  It sets revA rather
than leaving it nil.  This avoids having
magit-ediff-compare--read-files read from "revB^..revA" and then
magit-ediff-compare diff files from revA and the working tree.

It also catches the second magit-read-changed-file call with a nil
range.

> Oh, I didn't mean it should just start doing stuff, but that it
> should suggest the most reasonable one. And Dwim should just do the
> most reasonable thing. Obviously there's room for sharing code here
> :-)

I see.  I'll try to make the suggestions borrow some of the dwim
logic.

**Comment by kyleam** [comment]
OK, I think this issue should be good to close (moving any other changes and discussion to #2059).

**Comment by tarsius** [comment]
Thanks
