### ISSUE TITLE
Ignore whitespace in diffs

### ISSUE THREAD

**Issue by peweisberg-fadv** [magit/magit#204]
It would be nice if we could do something similar to what setting magit-diff-options to `'("-w")` does in the status buffer, only (a) applied to all diff-showing buffers and (b) not breaking functions that use the diff to generate patches to apply.

**Comment by max0x7ba** [comment]
How do I use this option please?

I am in *magit-status* buffer, I hit `D` and..?

**Comment by tarsius** [comment]
If the problem is that you didn't spot this lines ` -b Ignore whitespace changes (--ignore-space-change)` and ` -w Ignore all whitespace (--ignore-all-space)` then you now know what to look for.

If the problem is that you don't know how to use the infix arguments in the popup in general, then read the documentation about them: http://magit.vc/manual/magit-popup/Usage.html.

**Comment by nickmccurdy** [comment]
I might be missing something simple, but I can't find any flags or variables (including `magit-diff-options`, which doesn't exist for me) to toggle whitespace in the status buffer. Is this still supported?

**Comment by kyleam** [comment]
You can press <kbd>D</kbd> (`magit-diff-refresh-popup`), set the flags
you want (e.g., `-b` for `--ignore-space-change`), and then hit `g`.

**Comment by chaoflow** [comment]
@tarsius Is there a way to use these flags when viewing commits? In `magit-log` when I select a commit I can use `magit-diff-toggle-refine-hunk` to get a word-wise diff, but there seems to be no way to set `-w`. If in contrast I use `d -w d` to view a commit, I can ignore whitespace. It would be great if this (and other diff options?) could be toggled also for the default commit view.

**Comment by kyleam** [comment]
@chaoflow `magit-diff-refresh-popup` (now named `magit-diff-refresh`) is available from magit-revision-mode buffers as well.

**Comment by chaoflow** [comment]
@kyleam Thanks a lot!
