### ISSUE TITLE
magit-popup advices

### ISSUE THREAD

**Issue by Silex** [magit/magit#2040]
Hello,

What would you recommand to have multiple options with the same name?

e.g `docker run -v a -v b -v c foo`

There can be from 0 to N of such `-v` flags.

The only way I see *right now* is to offer a fixed list, let's say 3 and display them like `--volume1` `--volume2` `--volume3` and bind them to different keys. That allows the user to enter from 0 to 3 `-v` flags...

**Comment by tarsius** [comment]
You could turn `-v` into an option `-vN` in the ui and then convert that back to one or more instances of `-v` when it's passed on to actions. See `magit-log-read-args` for inspiration.

----

It seems "point out flaws in magit-popup"-time. https://github.com/magit/magit/issues/2018#issuecomment-120322133 a little while ago, and now this :-)

**Comment by Silex** [comment]
> You could turn -v into an option -vN in the ui and then convert that back to one or more instances of -v when it's passed on to an actions. See magit-log-read-args for inspiration.

Yes, that is the "Fixed List" idea, alright it means "dynamic" options are not possible

> It seems it's "pointing out flaws in magit-popup"-time. #2018 (comment) a little while ago, and now this :-)

The more issues the better transient.el will be :)
