### ISSUE TITLE
FYI: Upgrading today breaks magit: Error: undefined function: (setf ...)

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2045]
I recently today upgraded Magit.  Then I opened a new Emacs, went to some repo and ran "magit-status" .  I got an error like above, Magit was completely unusable.

Then I loaded the .el source files of Magit..  The error disappeared.  I recompiled all .el files, and from now the thing worked again everywhere.

So this is probably a new occurrence of the "code was compiled with outdated macro definitions" problem.

AFAICT this problem is still unsolved in vanilla Emacs.  For Helm we use "async-bytecomp.el"  now (part of the "async" package) to avoid that problem.

**Comment by tarsius** [comment]
I think just restarting Emacs should do the trick in this case.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> I think just restarting Emacs should do the trick in this case.

No, AFAIR it did that and it didn't work.  Once compiled with the
outdated macro versions, the compiled files stay invalid.  I needed to
investigate manually.

**Comment by behaghel** [comment]
Same here. The exact error is `(void-function \(setf\ magit-section-diff-header\))`.

**Comment by behaghel** [comment]
It's gone now. I have just seen a new update in `list-packages`, once installed and Emacs rebooted, it works fine.

**Comment by tarsius** [comment]
I'll leave this open in case my fix does not actually address the issue. But I think it should do the trick (I verified that it does, but not using `package.el`).

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> I'll leave this open in case my fix does not actually address the
> issue. But I think it should do the trick (I verified that it does,
> but not using package.el).

Ok, thanks so far.

**Comment by tarsius** [comment]
Seems this did the trick.
