### ISSUE TITLE
Can not copy magit-blame headers

### ISSUE THREAD

**Issue by baby-gnu** [magit/magit#2046]
Hello,

I'm using magit version 20150709.1022 on GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.16.4) of 2015-06-28 on trouble, modified by Debian.

To reproduce:
* ran ``magit-blame`` in a buffer
* move to a chunk
* hit ``SPC`` to see commit information

The ``Commit <SHA1>`` header can not be copy and yanked, neither from keyboard nor with mouse.

It will be useful to make them copyable instead of reading them and typing them with the keyboard.

Regards.

**Comment by kyleam** [comment]
You can use "M-w" in the magit-rev buffer, but see #2033.

**Comment by tarsius** [comment]
`M-w` now also works in file-visiting buffers in which `magit-blame-mode` is turned on.
