### ISSUE TITLE
Create Magit Reference Card

### ISSUE THREAD

**Issue by mrkkrp** [magit/magit#2047]
I think it's a good idea to add a reference card to the repository, in LaTeX for example. This could be one-page document that lists all main features of Magit and how to access them. People could just print it out and keep before them until they memorize the stuff. What do you think?

**Comment by tarsius** [comment]
I would like it.

**Comment by mrkkrp** [comment]
Should I try to write one and open a pull request?

**Comment by tarsius** [comment]
Yes, please.

I believe @tonini has added a nice one for `alchemist.el` (but it could also have been another package and/or another person). That could serve as inspiration.

**Comment by mrkkrp** [comment]
All right, I will see when I can come up with it.

**Comment by kyleam** [comment]
The [cheatsheet](https://github.com/magit/magit/wiki/Cheatsheet) might be a good starting point for the content. 

You could also have a look at [Org's refcard](http://orgmode.org/w/org-mode.git?p=org-mode.git;a=blob;f=doc/orgcard.tex;h=cf1e309bed79c9a9c93421652408049f018abb8f;hb=HEAD)

**Comment by mrkkrp** [comment]
@kyleam, thank you for these links.

**Comment by tonini** [comment]
The Emacs tabulated-list where my inspiration :-)

http://www.gnu.org/software/emacs/manual/html_node/elisp/Tabulated-List-Mode.html

If you add some default faces/colors, different rows for titles and empty rows to give the different sections some space between it looks not that bad. I used `key-description` to get the current keybindings of the different functions. 

It isn't that big of a thing, but its ok and helpful for the users at the moment how it is. Im open for improvements, so if you guys come up with some nice things, let me know. ;-)

**Comment by tarsius** [comment]
> The Emacs tabulated-list where my inspiration :-)

That one is nice too. (And we should have that too for Magit.) But didn't you also create a pdf using latex or something?

**Comment by tonini** [comment]
Yes you can find it here
https://github.com/tonini/alchemist.el/blob/master/doc/alchemist-refcard.pdf

I used a different font type as the GNU refcards usually use. I just liked
to do it my way and how I think a nice refcard should looks like. :-)

Jonas Bernoulli <notifications@github.com> schrieb am Fr., 10. Juli 2015
21:11:

**Comment by mrkkrp** [comment]
Here is first version of the reference card: https://github.com/magit/magit/pull/2061. See if you like it.

**Comment by tarsius** [comment]
Closing in favor of the pr.
