### ISSUE TITLE
Prevent magit from expanding diffs in Staged Changes

### ISSUE THREAD

**Issue by holocronweaver** [magit/magit#2048]
I am doing a large merge of thousands of commits into my current branch. Magit stalled trying to update the status buffer, so after several minutes of waiting I canceled the operation with `C-g`. I notice the diff of every single staged file is now expanded by default, making it difficult to see at a glance what files have been changed. If I try to collapse to level-one headers using `M-1`, all the staged file headers disappear and the topmost diff remains with dead text. Pressing `Tab` on the Staged Changes section no longer has any effect and I cannot see any staged commits, just the greyed text of the 'dead' diff. I guess this is all due to me using `C-g` to prematurely cancel the loading of all the staged changes. 

Is there an option to avoid expanding diffs in Staged Changes until they are demanded for, thus speeding up the loading of the staged items?

I tried setting `magit-diff-auto-show` to `nil`, but it had no effect even after restarting Emacs.

**Comment by tarsius** [comment]
I have just added this to the FAQ:

Q: I changed several thousand files at once and now Magit is unusable

A: Magit is not expected to work under such conditions. It sure would be nice if it did, and maybe some day it will. But for now I recommend you use the command line to complete this one commit.

----

> Is there an option to avoid expanding diffs in Staged Changes until they are demanded for, thus speeding up the loading of the staged items?

Actually they are not being expanded. You aborted before Magit got a chance to make the section bodies invisible, as part of the initial setup, which involves establishing the initial visibility state (which is this case is *hidden*). After you aborted most (if not all) diffs are probably still not colorized. They are not colorized ("painted") until the are explicitly (or in the diff buffer by default) expanded. That's an optimization which makes quite a difference when there are up to something like a hundred modified files. Then there are thousands it's not enough, and while we could probably optimize the hell out of it, by optimizing the code used to detect the boundaries of the files and hunks (which would be worth doing), that would still not help much here (we would only go down from, lets say 5 minutes to 2.5).

**Comment by holocronweaver** [comment]
Sounds reasonable enough. Is there a way to set Magit to only load the diffs on demand? I would think that would fix the issue for thousands of commits, though perhaps not millions.

**Comment by tarsius** [comment]
> Most of the time all I want is the commit header, not the diff.

Ah sorry, I though you were talking about the status buffer. In diff and revision buffers the diffs actually start out expanded.

> Perhaps the on-demand property could be automatically enabled when large number of commits need to be handled.

That might be doable. But I cannot get to it right away. Reopening to make sure I don't forget about this.

Hm, actually I though I had already installed some code to do something like this. Will have to check.

Just to make sure: the performance is okay in the status buffer, even with so many changed files?

**Comment by holocronweaver** [comment]
> Just to make sure: the performance is okay in the status buffer, even with so many changed files?
No, I am referring to the status buffer. Sorry, when I referred to the 'commit header', I meant the hash + message of all the commits in the status buffer (i.e., the sorts of commit data you would see in a log). I only occasionally need to look at diffs while inside the status buffer, even less so during large merges, so loading them on demand would be handy.

**Comment by phil-s** [comment]
The vast majority of the time the status buffer is rendered sufficiently quickly, and the effectively-instantaneous expansion that you consequently gain is very desirable.

If an on-demand facility were added. there would presumably need to be some heuristic (perhaps simply based on the number of changes) to decide whether to use the default behaviour, or whether to defer diff expansion to a manual request?

**Comment by holocronweaver** [comment]
@phil-s Yep, that is what I suggested above and @tarsius said he may have already implemented such.

It would be nice if the 'large number of commits' cutoff was user customizable so that slower machines could set the value lower.

**Comment by tarsius** [comment]
I'll look into adding this argument unconditionally to all calls to `git diff`.

**Comment by tarsius** [comment]
The option is `magit-diff-expansion-threshold` and that is enabled by default. But it doesn't avoid all work that could (probably) be avoided. I'll have to look into this some more.

Note to self: delay `(magit-wash-sequence #'magit-diff-wash-hunk)` in `magit-diff-insert-file-section`.

**Comment by tarsius** [comment]
In v2.3 I will just list the changed files instead of showing the diffs, see #2180. In the long run I intend to delay creating the diffs, but still allow to expand them in place. You are suggesting that they should just not be expanded them.

To some extend we already do that and as I have mentioned that could be improved by delaying more work until a diff is expanded (and by more aggressively avoiding premature expansion, as you suggest). 

But that won't be enough - for very large diffs even just running `git diff ...` can take several seconds, and the only way to prevent that is to do what was suggested in #2105.

**Comment by holocronweaver** [comment]
Sounds like a good short and long-term plan. v2.3 is going to be quite the goody bag for me. Will definitely be donating to support development. It may sound like an exaggeration, but Magit has literally improved my quality of life by saving time and thus decreasing the probability that I work late.

**Comment by tarsius** [comment]
Thanks!
