### ISSUE TITLE
Add spacing between files in the `Dwim` diff

### ISSUE THREAD

**Issue by czipperz** [magit/magit#2052]
It is very hard for me to see the distinction between two files in the diff when I am viewing it.

I propose that you add a blank line separator between the file name and the previous files, as there already exists between the sumary and the first file. Just move that line down to the top of the file diff instead of the bottom of the summary and it would be great.

**Comment by tarsius** [comment]
I would rather not do that and suggest that you instead give the various file heading faces a background color, like this is done for hunk headings already.

**Comment by tarsius** [comment]
It might seem that adding the newline should be trivial to do, even when that would be optional behavior (and it would have to be because I, and I suspect many others, would not want it). But it's not, it would require special cases in a lot of places. So no we cannot do that.
