### ISSUE TITLE
(magit-status "/other/foo") from a *magit-status: foo* buffer doesn't create new buffer

### ISSUE THREAD

**Issue by npostavs** [magit/magit#2054]
when using a `%b` in `magit-status-buffer-name-format`. It's the same for the interactive case: `C-u magit-status RET /other/foo RET`.

### Recipe
`emacs -Q -L ..\dash -L lisp -l magit -l testing.el` where `testing.el` contains
```elisp
(require 'magit)
(setq magit-status-buffer-name-format "*magit-status: %b*")

(magit-status "~/src/dash")
;; (switch-to-buffer "*scratch*")
(magit-status "~/.emacs.d/el-get/dash")
(setq Buffer-menu-name-width 40)
(call-interactively 'list-buffers)
```

Then `*Buffer List*` will contain only
```
.%  *magit-status: dash*                        164 Magit            
    *scratch*                                      0 Lisp Interaction 
 %* *Messages*                                   155 Messages         
```
Uncommenting the `(switch-to-buffer "*scratch*")` line in `testing.el` results in 2 `magit-status` buffers as expected:
```
.%  *magit-status: dash*<2>                      164 Magit            
    *scratch*                                      0 Lisp Interaction 
 %  *magit-status: dash*                         152 Magit            
 %* *Messages*                                   155 Messages               
```

### Analysis

The problem is `magit-status-internal` let-binds `default-directory` to `/other/foo` but this affects the buffer local binding, so then `magit-mode-get-buffer` thinks `*magit-status: foo*` is already at `/other/foo` and reuses it.

This is kind of a weird corner case: I only found it because I was looking at using `uniquify.el` with magit. Though I guess it might actually be fairly common to want to see the status of your other/foo while looking your first foo.

This could be fixed by wrapping the body of `magit-status-internal` in a `with-temp-buffer`, although that feels kind of silly. Thoughts?

**Comment by tarsius** [comment]
That seems like a good solution, but not exactly obvious, so write it like `(with-temp-buffer ; #2054`.
