### ISSUE TITLE
Show last process' output in magit-process even after it's finished

### ISSUE THREAD

**Issue by glasser** [magit/magit#2058]
If I understand correctly, the default behavior of the magit-process buffer is to hide a process' section when the process ends, if it exits 0.

But usually, when I open the magit-process buffer with `$`, it's because I want to see what happened in the last command.  This is pretty frequent after a push or fetch command (in fact, I've defined advice around fetch to set `magit-process-popup-time` to 0 since I always want to see what branches have been updated).  I have to then always open the last section.

Would it be reasonable to change the behavior (maybe with an option) to keep the *last* section open even if it exited 0?  eg, I guess you could put a flag on the section that says "left open after run, not explicitly opened by the user" and when starting a new process, if the previous section still has that flag set, close it then.  (Or I wouldn't complain if the "hide successful commands on close" code was entirely disable-able; I'd rather have too much visible in my buffer than not enough.)

**Comment by tarsius** [comment]
That's the best we can do at this point.

**Comment by glasser** [comment]
Thanks, that's great!
