### ISSUE TITLE
Checking out branches from the branch manager is cumbersome

### ISSUE THREAD

**Issue by kzar** [magit/magit#2062]
Hi there,

First of all thanks for all your work, the 2.1 release seems to be a huge upgrade and I've donated you some money. So this is not meant as criticism!

Anyway, I've found since the big upgrade that it's now more work to check out a branch from the branch manager. Previously I could just hit `RET` when my cursor was over the branch name. Now I have to hit `b b RET` and just hitting `RET` seems to show the latest commit for the branch which is something I almost never want to do at that stage. I gave the new way a chance but I keep tripping up on this.

Please could you consider changing that behaviour back?

Thanks, Dave.

**Comment by tarsius** [comment]
I am already working on restoring that behavior.

**Comment by kzar** [comment]
Awesome, thanks!

**Comment by holocronweaver** [comment]
How do you access the branch manager in 2.1? I can't seem to find it in the documentation. IIRC it was something like `b v` before.

**Comment by tarsius** [comment]
It's now on `y`. If you update from Melpa now, or once `2.2.0` is released, you also get back `b v`. But it now comes with a message, telling you to use `y` instead. You're not the only one who didn't find the new binding, to say the least.

**Comment by holocronweaver** [comment]
Thanks! The new interface is great. I skipped the `y` option in the popup because the label `Show Refs` doesn't mean anything to me as I do not not know what `Ref` refers to. I see there are git commands using the phrase `ref`, but I have never used these commands in my 3 years of using git on large projects. I probably should learn since it seems important to git plumbing, but I think I am not alone in having completely ignored whatever refs are in git.

**Comment by tarsius** [comment]
Refs stands for "references". Think "pointers". The most important ref types are (local) branches (`refs/heads/*`), remote branches (`refs/remotes/*`), and tags (`refs/tags/*`) , i.e. what is being listed in the "refs buffer" :-) But yeah, you should read about those.

**Comment by tarsius** [comment]
> Previously I could just hit `RET` when my cursor was over the branch name.

That's possible again. You can also use `C-u RET` to just "focus" on the branch at point. The cherry commits that are shown when expanding a branch are then relative to that focused branch instead of `HEAD`.

**Comment by kzar** [comment]
Thanks, can confirm it's now working for me :+1:
