### ISSUE TITLE
How to apply filter on unstaged changes?

### ISSUE THREAD

**Issue by enzochiau** [magit/magit#2066]
Is it possible to apply filter on unstaged changes list?

For example:

    1. Only display unstaged files in particular directory
    2. Only display unstange files based on type (.py or .cpp, etc)

**Comment by tarsius** [comment]
Implemented in #2119 (which will be merged soon).

With the changes in that branch you can set a file filter in any buffer which may contain diffs, using the `magit-diff-refresh-popup` (`D`).
