### ISSUE TITLE
magit-branch-reset: Default branch to reset to should be upstream of branch.

### ISSUE THREAD

**Issue by bastianbeischer** [magit/magit#2067]
I really apprecate the new magit-branch-reset feature.

I use it to fast-forward my local branches to changes in the upstream ref without checking out the branch itself.

This is very useful for many reasons, mostly because using the traditonal approach:

git checkout other
git pull
git checkout previous
... continue to work ...

would cause simple build systems like GNU Make to think that all source files which differ from other to previous changed, due to updated modification times of the files. Using magit-branch-reset I'm able to update 'other' without ever leaving 'previous' which is really nice...

But as it is I have to:

b x 'other' 'origin/other'

or in the ref manager:

go to other, b x 'RET 'origin/other' RET

 while it could be as simple as b x 'RET' 'RET'... What do you think?

**Comment by tarsius** [comment]
It does that now.
