### ISSUE TITLE
magit-version: "Cannot determine Magit's version" error

### ISSUE THREAD

**Issue by srustamo** [magit/magit#2070]
`magit-version` returns "Cannot determine Magit's version". 
`describe-package` `RET` `magit`:
magit is an installed package.

    Status: Installed in `~/.emacs.d/elpa/magit-20150712.2220/' (unsigned).
    Archive: n/a
    Version: 20150712.2220

GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21)

**Comment by tarsius** [comment]
Just tried with the same Emacs version and it works for me.

Check whether you have an ancient version of `package.el` laying around on the load path.

What does

```lisp
(--when-let (assq 'magit package-alist)
  (setq magit-version
        (and (fboundp 'package-desc-version)
             (package-version-join
              (package-desc-version (cadr it))))))
```

return?

**Comment by srustamo** [comment]
Checked for package.el on the path. No such file. Evaluating the forms does not, it seems, have any effect, and I still get "Cannot determine Magit's version" running `magit-version`.

**Comment by tarsius** [comment]
> Evaluating the forms does not, it seems, have any effect,

I think you misunderstood. I am not interested in their (side-)effect, but in the value they print (to the echo area and `*Messages*` buffer.

**Comment by srustamo** [comment]
Just tried pasting the above forms into scratch buffer and evaluate the buffer. The messages buffer does not show anything.

**Comment by tarsius** [comment]
> Just tried pasting the above forms into scratch buffer and evaluate the buffer. The messages buffer does not show anything.

You have to evaluate the expression, not "all" expressions in the buffer, to get the return value of the expression. Move point behind the last parenthesis and press `C-x C-e`, the return value will probably be `nil`. So now we know *something* is going wrong inside that expression, and we have to figure out where exactly. Evaluate this expression and post the return value:

```lisp
(list (assq 'magit package-alist)
      (fboundp 'package-desc-version)
      (ignore-errors (package-desc-version (cadr it)))
      (ignore-errors (package-version-join (package-desc-version (cadr it)))))
```

**Comment by tarsius** [comment]
Could you post your init file?

**Comment by srustamo** [comment]
Below is the output of:

```lisp
(list (assq 'magit package-alist)
      (fboundp 'package-desc-version)
      (condition-case nil
          (package-desc-version (cadr (assq 'magit package-alist)))
        (error 'error))
      (condition-case nil
          (package-version-join
           (package-desc-version (cadr (assq 'magit package-alist))))
        (error 'error)))
```
Output
```lisp
((magit [cl-struct-package-desc magit (20150712 2220) "A Git porcelain inside Emacs" 
(... ... ... ... ...) nil nil "/Users/s3/.emacs.d/elpa/magit-20150712.2220" (... ...) nil]) t 
(20150712 2220) "20150712.2220")
```

**Comment by srustamo** [comment]
I uploaded all related init files to a private Github gist, a link to it was sent to your email listed on your Git profile page (the reason it is private is that I tried to sanitise private data, but not sure if all was removed).

**Comment by tarsius** [comment]
The primary thing I was looking for in your init file was whether you call `package-initialize` before loading `magit`. That appears to be the case, but you also seem to be very undecided where to do that. I counted three places where you at one point did it (two of them commented out). If you are accidentally loading outdated `*.elc` files of you configuration, then that might contribute to the issue.

The output you provided for the form I posted above seems sane.

Could you please add `(message "--- %s %s" gitdir static)` to `magit-version`, right before the `cond`. Then check what that prints during startup and also if you later call `magit-version` interactively.

Also you might have multiple version of Magit installed, use `find -name magit.el` to make sure you don't.

**Comment by srustamo** [comment]
I noticed that nowhere in my init I call `(requre  'magit)`. I added this after `package-initialize`. I got a message at start-up that magit.elc file is older than magit.el. Find file shows only one directory on the path where magit is installed (and that is in elpa).

I deleted magit.elc, byte compiled magit.el. No more 'elc older' error. 

Added `(message "--- %s %s" gitdir static)` before `cond`. Output is below:
`--- /Users/srmba3/.emacs.d/elpa/.git /Users/srmba3/.emacs.d/elpa/magit-20150712.2220/magit-version.el Cannot determine Magit's version`

**Comment by srustamo** [comment]
Incidentally, `M x ! echo $PATH` starts with `/usr/bin`, where Apple's git lives. However, `exec-path` variable puts `/usr/local/bin` in front of `/usr/bin`. 

I'm having trouble differentiating these, perhaps these are related to this issue.

**Comment by tarsius** [comment]
Oh, I am sorry, I actually need the output of `(message "--- %s %s" (file-exists-p gitdir) (file-exists-p static))`.

**Comment by srustamo** [comment]
`(message "--- %s %s" (file-exists-p gitdir) (file-exists-p static))`

output

`--- /Users/srmba3/.emacs.d/elpa/.git /Users/srmba3/.emacs.d/elpa/magit-20150718.2257/magit-version.el Cannot determine Magit's version`

**Comment by tarsius** [comment]
`--- /Users/s3/.emacs.d/elpa/.git /Users/s3/.emacs.d/elpa/magit-20150718.2257/magit-version.el`

That's not possible, because `file-exists-p` always returns a boolean, not the argument. You probably forgot to re-evaluate the definition after modifying it.

Anyway I have just pushed a more defensive version of the `magit-version` function (cad4e70764f1ba37a6333d8318d426b2c52760d5). Please give that a try.

**Comment by srustamo** [comment]
All is well now. Thank you for your time.

**Comment by tarsius** [comment]
Your welcome.

**Comment by jwiegley** [comment]
@tarsius I just started getting this same error in Nix:

```
Cannot determine Magit’s version (error "/nix/store/z9inj6a8sbh9scs1ghsivlis35zwsvyh-emacs-magit-20181226/share/emacs/site-lisp/elpa/magit-20181226/magit.el" repo static elpa dirname)
```

**Comment by taigacute** [comment]
@tarsius  got the same error on mac , use straight.
```
Cannot determine Magit’s version (error "/Users/stephen/.config/emacs/.local/straight/repos/magit/lisp/magit.el" repo t static elpa dirname)

```

**Comment by tarsius** [comment]
The package manager is supposed to generate `magit-version.el` and place it next to the other libraries. If it doesn't do that, then that is a packaging bug, which should be reported to the maintainer of the package.

**Comment by progfolio** [comment]
Related: https://github.com/progfolio/elpaca/issues/331

User is using Windows 11 sans symlinks.
Straight.el specific kludge does not work for Elpaca.
Still seems odd to signal an error in this case instead of reporting a version of "unknown" or something similar.

**Comment by tarsius** [comment]
> Still seems odd to signal an error in this case ...

No error is being signaled. This is a warning (shown using `message`). The `(error...`) at the end may have lead you astray. I could replace it with `failed` or something to avoid that. (The list at the end records what has been tried to determine the version.)

> ... instead of magit-version reporting "unknown" or something similar.

Looking at the code I can see that it did try to do that at one point. I'll have to do some history spelunking to find out more.

However, the goal of the warning is to get people's attention, so that we can figure out how to determine the version in their specific situation.

> Straight.el specific kludge does not work for Elpaca.

Could you please tell me how I can determine the version when elpaca is being used?

**Comment by progfolio** [comment]
Jonas Bernoulli ***@***.***> writes:

> No error is being signaled. This is a warning (shown using 
> message). The (error...) at the
> end may have lead you astray. I could replace it with failed or 
> something to avoid that.
> (The list at the end records what has been tried to determine 
> the version.)

Apologies. I see that now that I've tried to reproduce the issue 
on my end.
I was going off what was posted in the issue I linked. 
 
> Could you please tell me how I can determine the version when 
> elpaca is being used?

See #5171. Should work with both straight.el and Elpaca.
The CI failures seem unrelated to the actual PR at a quick glance.
