### ISSUE TITLE
Could use a way to control pre-computation of diffs in Magit

### ISSUE THREAD

**Issue by dpkatz** [magit/magit#2071]
I'm having a problem where Magit interacts badly with changes in files which use an external executable for diff generation and viewing rather than Emacs.

I work on a system where some of the source tree files are diagrams rather than text.  Since the diagrams are generated with a particular diagram editor ([Dia](https://wiki.gnome.org/Apps/Dia)), I "taught" git how to handle diffs using that editor with something like this in the local *.gitattributes* file: `*.dia    diff=dia` and a stanza in my *.gitconfig* about where to find the editor executable and how to pass it the two relevant versions and so on (`[diff "dia"] command = c:/Users/dpkatz/bin/dia-diff` where `dia-diff` is a script which encapsulates all the relevant magic).  

If I've edited one of these diagrams (i.e. an unstaged change) then every time I do `M-x magit-status` (or any of a variety of commands in the status buffer), Magit automatically launches the *Dia* editor to show me a diagram diff of the edited diagram.  (The first time I saw this behavior, I'd edited 6 diagrams and got 6 *Dia* processes launched as a result of running `magit-status` - not really what I wanted at all. :-))  After this happens, if I close the *Dia* process which has the diff in it, I end up with a corrupted "Unstaged changes" section of the status buffer:
```
Unstaged changes:
Canvas size change...
Canvas size change...
Canvas size change...
Canvas size change...
```
where the text "Canvas size change..." is clearly coming from the diagram application.

In an ideal world there would be some way to limit Magit's desire to pre-compute diffs for some set of files (e.g. the ".dia" files in this case) so that I could stop the external diff tool from being called automatically.  Does such a way exist?  I went skimming through the manual but didn't find anything obvious to try.  If it doesn't exist, could it?  I saw `magit-diff-auto-show`, but it doesn't seem relevant here.  I also noticed Issue #2048 which looks like it might be relevant depending on the approach taken.

I should say that the 1.4 version of Magit did not have this issue.  Changes to diagrams would just show up in the status buffer without problems, and if I wanted a diff I'd activate the `E` (ediff) command and up would pop the diagram editor.  It was very slick and worked fine.

Currently, I'm using Magit from melpa:
`M-x magit-version => Magit 20150712.2220, Git 2.4.5, Emacs 24.5.1`

**Comment by tarsius** [comment]
Magit just runs `git diff` and then presents the result, which it hopefully was able to parse. In the long run we should support commonly used `gitattributes` configuration. You might be able to use your gitattributes settings in a terminal and disable them in Magit by using different files.

Experiment with appending  `("-c" "core.attributesFile=something")` to `magit-git-global-arguments`.

**Comment by tarsius** [comment]
What I suggested in #2071, is probably the better approach.

**Comment by npostavs** [comment]
> What I suggested in #2071, is probably the better approach.

@tarsius: github's autocomplete strikes again? This *is* 2071...

**Comment by tarsius** [comment]
#2069.

And I am probably going to add `--no-ext-diff` to the popup, so you won't have to do that manually.
