### ISSUE TITLE
Warning: the function `-non-nil' is not known to be defined

### ISSUE THREAD

**Issue by exu** [magit/magit#2072]
When making magit I've got errors:

```
make[1]: Wejście do katalogu '/home/exu/Dropbox/Dotfiles/emacs.d/vendor/magit/lisp'
Compiling magit-popup.el
Compiling magit-section.el
Compiling magit-git.el
Compiling magit-mode.el

In end of data:
magit-mode.el:831:1:Warning: the function `-non-nil' is not known to be
    defined.
Compiling magit-process.el
Compiling magit-core.el
Compiling magit-diff.el
Compiling magit-wip.el
```

I have also this "Warning: the function \`-non-nil' is not known to be defined."  message when trying to `commit --amend`

I've installed new dash.el, what I'm missing?

**Comment by kyleam** [comment]
Have you told make where your dash is installed (overriding DASH_DIR)?  I think it will find it automatically if it is .emacs.d/elpa, but you have to set it otherwise.

**Comment by kyleam** [comment]
That's not the error you would get if dash wasn't found at all, so I think it fiinding an earlier version of dash.

**Comment by exu** [comment]
Thanks for help!  It was old elpa version of dash which was overriding new one.

**Comment by jfkw** [comment]
Thanks so much for the tip. dash was installed by el-get as the magit dependency, but I had not updated dash in almost a year. Works now.
