### ISSUE TITLE
magit warns of non-empty second line, but it's actually empty

### ISSUE THREAD

**Issue by mbertheau** [magit/magit#2074]
With a commit message like this:
```
Default to setting the domain to what's in the config

This allows you to change the domain of the currently running system by
....
```

when `C-c C-c`ing magit correctly warns about the summary line being too long. I confirm that and then magit warns about the second line being non-empty, which is not the case.

**Comment by kyleam** [comment]
Have you tested this with "emacs -Q"?  I can't reproduce this with your snippet.

**Comment by npostavs** [comment]
Is it possible there are some invisible characters hiding in the second line?

**Comment by mbertheau** [comment]
No invisible characters in the second line. I also couldn't reproduce with emacs -Q. Maybe it's a spacemacs issue. Thanks for your help!
