### ISSUE TITLE
magit-popup: show popup only after a certain amount of time

### ISSUE THREAD

**Issue by tsdh** [magit/magit#2075]
Magit's popups are really nice (especially the discoverability), and I think about replacing at least my private (partly nested) keymaps with it. However, when you want to use the magit popups for your custom commands in "normal" text and programming modes like `lisp-mode` you don't want the popups to be shown while quickly typing a command's binding which you've already memorized.

So I imagine a customize option `magit-popup-defer-time` which would create and display the popup buffer only after that amount of time.  Until that point in time, the keymap induced by the popup would be made the current `overriding-local-map` in the buffer from which the popup command has been executed.

**Comment by tarsius** [comment]
While I would like this feature too, I am not going to implement it in `magit-popup`. I am already planning to write a successor, which will probably be named `transient`.

It sounds like `magit-popup` isn't the right package for what you are trying to do anyway. Use `hydra` instead (it does support the feature you are requesting). The `magit-popup` manual has more to say on the subject: http://magit.vc/manual/magit-popup/Defining-prefix-and-suffix-commands.html#Defining-prefix-and-suffix-commands.

**Comment by tsdh** [comment]
Yep, `hydra` seems to be a better fit for my use-case right now.  Thanks for the pointer.

Out of interest: I guess `transient` will be suited best for running external commands with switches and options just like `magit-popup`, so when I just want a nice interface for dispatching between many related lisp commands, I'll be served best with `hydra` even after `transient` is there, right?

**Comment by tarsius** [comment]
Most likely yes. But nothing is fixed in stone yet.
