### ISSUE TITLE
magit-log-buffer-file does not follow renames

### ISSUE THREAD

**Issue by rymndhng** [magit/magit#2078]
Follow up on discussion on: 
http://emacs.stackexchange.com/questions/13620/how-to-log-file-following-all-renames

I myself have encountered this myself. Admittedly I'm not interested in setting a default of `—follow` because it breaks logging the repository.

**Comment by doublep** [comment]
I'm sure magit can be smart enough to special-case --follow and just omit it when creating a log for more than one file. I.e. one would be able to set it as default, but that would be ignored in most cases and would apply only in certain specific cases.

As far as I'm concerned, --follow is not even needed in the interface, just add it silently where applicable. Can't really think of a case where you'd explicitly want to *not* follow renames when logging a single file.

**Comment by rymndhng** [comment]
Yep, I agree with @doublep. I think it would be sane to make it implicitly default if possible.

**Comment by tarsius** [comment]
I intend to add it to the popup and enable it by default. But I ran into a bug along the way, which I have to fix first.

**Comment by tarsius** [comment]
Implemented in #2119 (which will be merged soon).

To follow renames, either call `magit-log-buffer-file` with a prefix argument, or enable `--follow` in the popup and save that as the default (`l -f C-x C-s`).

**Comment by rymndhng** [comment]
Thanks alot!  Looking forward to using this.
