### ISSUE TITLE
Checking out a remote branch locally is difficult

### ISSUE THREAD

**Issue by dgtized** [magit/magit#2079]
This may be duplicate of #2009, but I believe it's a slightly different. I frequently switch from my laptop to my desktop, and will push a branch to origin and then check it out on another machine. Likewise if a team member works on a branch and I want to check it out locally.

Previously I could simply do `b b` and checkout a remote branch from origin and it would prompt to create a local copy tracking that upstream branch with the same name. Now it simply checks out the detached HEAD. After reading http://magit.vc/manual/magit.html#Branching, the recommended way appears to do this is with `b B` create and checkout. Unfortunately that forces one to name the local branch without the completion option to match the upstream branch name.

Is there some other method to easily create a local branch from a remote branch that I just missed while reading the documentation, or is it just that local branch creation is harder then it used to be?

**Comment by tarsius** [comment]
Actually in `2.1.0` that was very comfortable to do, but in #2009 I was urged to change the order in which the name of the new branch and the starting point are read. And I changed it and provided the option `magit-branch-read-upstream-first` so that I and others can revert to the behavior that is useful in the case you are describing here. I might change the default of that option before releasing `2.2.0`.

**Comment by tarsius** [comment]
Once you have modified the option you can create the branch by pressing `b b RET RET` on an existing branch (or `b b origin/... RET RET` elsewhere).

**Comment by tarsius** [comment]
> the recommended way appears to do this is with `b B` create and checkout.

I don't see how you got that impression and how it would help.

**Comment by kyleam** [comment]
@tarsius I think what you're saying currently applies to `b B` (`magit-branch-and-checkout`) and `b c` (`magit-branch`).  `b b` (`magit-checkout`) just uses `magit-read-other-branch-or-commit`.

**Comment by tarsius** [comment]
Yes I meant `b c` not `b b`. Corrected.

**Comment by dgtized** [comment]
Ok, I changed it to use `magit-branch-read-upstream-first` and `b c` and `b B` actually allow you to quickly checkout a remote branch. I think that does make sense as the default. My muscle memory from previous magit is definitely still to just default to switch branch with `b b` but I do understand there is some value in keeping branch creation (local or otherwise) separate from branch switching.

Just to clarify though my impression then was correct on using create and checkout?

**Comment by tarsius** [comment]
> Just to clarify though my impression then was correct on using create and checkout?

I don't think so, no.

**Comment by dgtized** [comment]
Ok, now I'm confused. With the most recent change, if I want to create a new local branch, I use either `b c` or `b B` to create a local branch from the remote. If I use `b b` it will checkout the branch as a detached head. How was my impression wrong to create local branches from remote with `b B` given that it now works. Especially given that `b b`'s behavior to checkout a remote branch and create a local copy was last seen in 1.4?

**Comment by tarsius** [comment]
> Ok, now I'm confused. With the most recent change, if I want to create a new local branch, I use either `b c` or `b B` to create a local branch from the remote.

Correct.

> If I use `b b` it will checkout the branch as a detached head.

Correct.

> How was my impression wrong to create local branches from remote with `b B` given that it now works.

I was under the impression that you were saying that while `b B` did what you wanted `b c` did not. But I have probably misread something. The only difference between these two should be that the former *also* checks the new branch out. How user input is read and how upstream is set does not differ. Checking out or not checking out, that is the *only* question :-)

> Especially given that `b b`'s behavior to checkout a remote branch and create a local copy was last seen in 1.4?

I didn't remember that and missed when you told me about it. Anyway `b b` is now checkout-and-nothing-else-ever, `b c` is create-new-branch, and `b C` is create-new-branch-and-then-also-check-it-out.

**Comment by tarsius** [comment]
> I might change the default of that option before releasing 2.2.0.

I have done that now.
