### ISSUE TITLE
magit shows ANSI color sequences from git

### ISSUE THREAD

**Issue by Wilfred** [magit/magit#208]
If colour is enabled for git, e.g.:

```
$ git config --global color.diff always
```

then `M-x magit-status` shows the colour sequences, e.g:

```
Head:   [33md47a03d[m my last commit message
```

Thanks for a great utility :)

**Comment by bronger** [comment]
FWIW, I see the ANSI sequences with `diff = always` in the `[color]` section even with Magit 20209313.1657. Of course, I amend my Git configuration and the problem goes away but still, the sequences are not just “filtered out”.

**Comment by bronger** [comment]
_I_ unassigned pjweisberg? Okaaay …

**Comment by tarsius** [comment]
Try >= `20209318.nnn` instead. Post 68b5a13fa1b6b122d4a2547b8c415aadff83d8ca.
You waited all these years and then you were off by less than a week. :grinning:
