### ISSUE TITLE
diminish: magit-auto-revert-mode is not currently registered as a minor mode when execute magit-status

### ISSUE THREAD

**Issue by jilen** [magit/magit#2081]
magit-status ` Magit 20150715.1602, Git 2.4.5, Emacs 24.5.1`

When I execute `magit-status` it complains `diminish: magit-auto-revert-mode is not currently registered as a minor mode` and no status buffer is open

**Comment by tarsius** [comment]
`magit-auto-revert-mode` was removed from Magit, in favor of a plain option `magit-revert-buffers`. 

Somewhere in your configuration you are telling `diminish` about `magit-auto-revert-mode`. Find and remove that.

**Comment by jilen** [comment]
@tarsius  Thanks very much!
