### ISSUE TITLE
the new diff/rev view

### ISSUE THREAD

**Issue by pank** [magit/magit#2085]
Hi,

Thanks for putting all the work into Magit 2.1!  I really like the way rebase and patches are integrated. 

However, in Magit 2.1 the new diff view is pretty different from previous versions and from the "normal" diff view.  Here are the things that I still feel uncomfortable about since I installed Magit 2.1.

1. I don't understand the need for different from standard region behaviour.  ATM when I activate the region to kill something, I get weird red bars denoting my region (though only to the precision of the line above and below, not to the actual point).  It confuses me every time.  I looked for a `magit-revision-*` variable to disable this, but couldn't find one.
2. Why does Magit use different colors from normal diff?  The contrast on my system is bad (e.g. red on red and green on green, using the AFC theme).  I guess I could customize magit faces, but this sounds like a tedious exercise.
3. I think in the "old" Magit `RET` was bound to what now corresponds to `magit-diff-visit-file-worktree` (`C-RET`).  I think this is a more sensible default for `RET`, even if it cannot always get the line exactly correct.  It unfortunate when I browse the log file, click `RET` and get some old version of the file, as I might not notice and edit the wrong file.  If I explicitly want an old version of a file I'll happily go through the trouble of clicking a less intuitive key combination.  I can rebind this, but to me the default is wrong (you may of course disagree).

There are probably benefits of the above that are not obvious to me.  I'd be happy with just a variable enabling a more "conservative" take on the magit-rev.

Thanks,
Rasmus

**Comment by npostavs** [comment]
> I don't understand the need for different from standard region behaviour. ATM when I activate the region to kill something, I get weird red bars denoting my region (though only to the precision of the line above and below, not to the actual point)

Because you can stage/unstage/discard the lines included in the region, but not parts of line.

**Comment by pank** [comment]
On July 16, 2015 9:03:42 PM GMT+02:00, Noam Postavsky <notifications@github.com> wrote:
>> I don't understand the need for different from standard region
>behaviour. ATM when I activate the region to kill something, I get
>weird red bars denoting my region (though only to the precision of the
>line above and below, not to the actual point)
>
>Because you can stage/unstage/discard the lines included in the region,
>but not parts of line.

Why is this relevant for, say an unpushed commit?

I enjoy the (un)staging keys and using (plain) region for staging things before commit. But that seems irrelevant in this context.

**Comment by npostavs** [comment]
You can apply/reverse lines of a commit.

**Comment by tarsius** [comment]
(3)

> I think this is a more sensible default ...

For the reasons given by @npostavs I disagree.

> I might not notice and edit the wrong file.

If it's "the wrong file", then the buffer is read-only and not actually visiting a file.

> I can rebind this ...  I'd be happy with just a variable 

I almost never add a variable when using `define-key` also works.

**Comment by tarsius** [comment]
(3)

```lisp
(define-key magit-file-section-map [C-return] 'magit-diff-visit-file)
(define-key magit-file-section-map "\r" 'magit-diff-visit-file-worktree)
(define-key magit-hunk-section-map [C-return] 'magit-diff-visit-file)
(define-key magit-hunk-section-map "\r" 'magit-diff-visit-file-worktree)
```

**Comment by tarsius** [comment]
(2)

> Why does Magit use different colors from normal diff?

To avoid many issues that result of theming that was done before the days of magit (or at least the current version).

Theming of diffs in Magit is highly complex for two reasons. Magit provides many features which change the appearance of diffs. Magit has many users with mutually exclusive opinions what is obviously the right thing to do and what alternatives are obviously wrong. The current implementation takes a long history of such discussions into account. It provides a default which might not be the best approach to anyone, but which can be customized in many ways to many of the possible appearances that have in the past been declared to be the right way. There is a lot of flexibility, but customization is not trivial.

> The contrast on my system is bad (e.g. red on red and green on green, using the AFC theme). I guess I could customize magit faces, but this sounds like a tedious exercise.

The contrast of the default faces has been increased recently. You can get Magit from Melpa (non-stable) to get that now or wait for 2.2. If that's not enough then you will have to invest some time theming the faces to your liking.

**Comment by tarsius** [comment]
(I have edited my answers so you might want to read them in a browser.)

**Comment by tarsius** [comment]
(1)

I am working on an option to allow users to display the region. I haven't installed that yet, but here is the doc-string -- it explains why you *should* not change it's value, and hopefully answers your questions:

> Whether to keep the region overlay when there is a valid selection.
> 
> By default Magit only keeps the regular region highlighting
> overlay created by Emacs intact, if the region does not
> constitute a valid selection as understood by Magit commands.
> 
> There are two types of such valid selections: hunk-internal
> regions and regions that select two or more sibling sections.
> If the region does not constitute such a selection, then Magit
> does never touch the regular region highlighting overlay at all.
> 
> If the region does constitute a valid selection, then Magit
> removes the region overlay and instead highlights a slight larger
> range.  All text (for hunk-internal regions) or all sections (for
> sibling selections) that are inside that range (not just inside
> the region) are acted on by the appropriate Magit commands.  This
> buffer range begins at the beginning of the line on which the
> region begins and ends at the end of the line on which the region
> ends.
> 
> Why we act on this larger range instead of the region, is beyond
> the scope of this doc-string, but let me assure you that this
> was not done without careful consideration.  I also hope that
> you understand that, because Magit act on the larger range and
> not the region, it is actually quite important to visualize that
> larger range, because if we don't do that, then one might think
> that these commands act on the region instead.
> 
> If you want to *also* visualize the region, then set this option
> to t.  But please note that when the region does *not* constitute
> a valid selection, then the region is *always* visualized as
> usual, and that it is usually under such circumstances that you
> want to use a non-magit command to act on the region.
> 
> Besides keeping the region overlay, setting this option to t also
> causes all face properties, except for `:foreground', of the
> faces that are used to highlight the headings of selected
> sections, to be ignored.  This avoids the worst conflicts that
> result from displaying the region and the selection overlays at
> the same time.  We are not interested in dealing with any other
> conflicts.  (In fact we *already* provide a way to avoid all of
> these conflicts: *not* changing the value of this option.)

**Comment by pank** [comment]
Hi,

Thanks for your replies.

Jonas Bernoulli <notifications@github.com> writes:

> ```lisp
> (define-key magit-file-section-map [C-return] 'magit-diff-visit-file)
> (define-key magit-file-section-map "\r" 'magit-diff-visit-file-worktree)
> (define-key magit-hunk-section-map [C-return] 'magit-diff-visit-file)
> (define-key magit-hunk-section-map "\r" 'magit-diff-visit-file-worktree)
> ```

I know it can be fixed in my `init.el`.  I don't understand why the change
was needed compared to Magit 1.8.  Anyway, let's not dwell on it as we
probably won't find agreement.

Jonas Bernoulli <notifications@github.com> writes:

>> Why does Magit use different colors from normal diff?
>
> To avoid many issues that result of theming that was done before the
> days of magit (or at least the current version).

In recent GNU Emacs versions there's `deftheme` which can be used for
providing themes.  They stack.  So in principle you could have
`magit-night`, and `margit-day`, and `magit-fancy` themes that only change
magit faces irrespective of what other themes might be loaded.

> The contrast of the default faces has been increased recently. You can
> get Magit from Melpa (non-stable) to get that now or wait for 2.2. If
> that's not enough then you will have to invest some time theming the
> faces to your liking.

I updated.  It's still green foreground on green background etc.  It looks
very stylish, but in terms of usability the default faces of `diff-mode`
are more readable.  In AFC it is black foreground on green background.

Jonas Bernoulli <notifications@github.com> writes:

> I am working on an option to allow users to display the region. I
> haven't installed that yet, but here is the doc-string -- it explains
> why you *should* not change it's value, and hopefully answers your
> questions:

Perhaps I'm a naive git user. When I want to change a commit I use
`rebase` or append.  I don't know the methods mentioned by you and Noam.
I tried to reproduce what Noam was hinting at, but when I hit for example
`k` in a `magit-rev` buffer it tell me that I cannot "discard commit
change" (as I would expect).

Here's what I use the diff-view/magit-rev for.  I receive a patch on the
ML.  I apply it and test it.  When I reply, I want to talk about chunks of
the patch.  I simply want to copy these from the magit-rev view to the
message-buffer.  This workflow is severely distracted by magit reinventing
regions.  However, I think we also won't find agreement here.

Feel free to close.

Rasmus

-- 
I almost cut my hair, it happened just the other day

**Comment by npostavs** [comment]
> I tried to reproduce what Noam was hinting at, but when I hit for example `k` in a `magit-rev` buffer it tell me that I cannot "discard commit change" (as I would expect).

Right, but if you hit `a` (for apply) or `v` (for reverse) then it uses the lines in the region.

**Comment by tarsius** [comment]
> Feel free to close.

Thanks! I might at a later time write theming guides and a justification of these design decisions (you are not the only one not happy about them). But that will be a lot of work, and I am quite busy right now: https://github.com/magit/magit/pulse/monthly.
