### ISSUE TITLE
How do I turn off background highlighting in magit's diff view?

### ISSUE THREAD

**Issue by nikolas** [magit/magit#2089]
Just the plusses and minuses are all I want, like git on the command line, maybe with the foreground text colored red/green. If there's an option to turn off highlighting, it would be good to add it to the documentation. Magit's default diff setup is unreadable on a black terminal, just using emacs's default theme. I turned off `magit-diff-highlight-hunk-body` but the style is the same.

I realize the diff style is a long ongoing discussion.. but even if the solution is complicated, since this subject isn't in the magit manual, how do I do it?

**Comment by kyleam** [comment]
You can see all faces (along with sample text) with list-faces-display
(search for magit-diff-*).  Customize these to your liking.

**Comment by nikolas** [comment]
Thanks, I will do some research and maybe come up with a PR to add some notes on this to the manual.

**Comment by kyleam** [comment]
Not sure what information you have in mind.  The manual contains advice
for theming, but the details of how to list and change faces aren't
Magit-specific.

http://magit.vc/manual/magit/Theming-Faces.html#Theming-Face

**Comment by r2evans** [comment]
Way after-the-fact, but I came looking for something similar. While the Theming-face page in the manual is good, for me it made more sense to use `M-x customize-group RET magit-faces RET` (per https://stackoverflow.com/a/6004727/3358272).

magit rocks, I use it daily, thank you!
