### ISSUE TITLE
magit does not show file in "Unstaged changes" with external diff tool

### ISSUE THREAD

**Issue by tkren** [magit/magit#2090]
I've setup git to use an external diff tool for files with gpg suffix.  My `~/.gitconfig` has the following entry:
```
[diff "gpg"]
        binary = true
        command = /usr/local/bin/git-gpg-diff.sh
```
When I update a gpg file, magit wouldn't list it under "Unstaged changes".  If I remove the diff-setting from `.gitconfig`, magit shows the changed file.

**Comment by tarsius** [comment]
Try this instead: http://magit.vc/manual/magit/How-to-show-diffs-for-gpg_002dencrypted-files_003f.html.

Your script should also work, provided what comes out of it looks exactly how the diff would look if `git diff` were showing it directly for an unencrypted file.

**Comment by tkren** [comment]
thanks, this worked nicely. i need to figure out why my script wouldn't work, it is imho a simple diff.
