### ISSUE TITLE
On a personal note

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2095]
As you are probably aware (assuming you have read the [release notes (v2.1)](https://raw.githubusercontent.com/magit/magit/master/Documentation/RelNotes/2.1.0.txt)), I am looking for a job and/or sponsorship for my work on Magit and related projects.

> I am also looking for corporate sponsorship and/or employment.  One area where Magit actually lags behind other Git clients is integration with Git hosting platforms and code review tools.  I hope that these platforms have an interest in being supported by the best Git client and are willing to pay for it.
> 
> I am very interested in a job that would let me work on Magit *and* on other projects, which would benefit from the skills I have acquired integrating two complex systems and dealing with all the social and technical challenges that arise when running a popular project.

I have just created a LinkedIn profile and contacted a few fellow Magitians and Emacsians. (But for some reason my list of "pending invitations" contains only one person. So I am not sure if that actually worked). If you think that doing so could help me, then please "connect" with me there.

Or refer me to people who might be interested. If you have any questions, or advice, then please send me an email (jonas@bernoul.li).

**Comment by Silex** [comment]
Not sure your linkedin invite worked, or maybe you didn't invite me :) Anyway I invited you.

**Comment by tarsius** [comment]
I will again try to send the requests and if that doesn't work contact those who have offered me help before by mail.
