### ISSUE TITLE
magit becomes extremely slow after being upgraded to v2.1.0

### ISSUE THREAD

**Issue by c02y** [magit/magit#2099]
I know `Magit v2.1.0` has been released more than half of month now, but I never try it, and all my packages are upgraded from `package.el`, today I gave it a try, followed the instructions from http://magit.vc/manual/magit/Updating-from-an-older-release.html#Updating-from-an-older-release. 

After that, use `magit-status` toe get the magit buffer for the repo, but the command took more time (it took more than 5s) than the old version, and I didn't give much attention, and then I tried to `s` to track one untracked package directory which contains only several files in my `elpa`, it took **almost forever** to put it into stage and of course it will stuck Emacs, and Emacs took more than 70% of the CPU in `top`, I tried to restart my Emacs several times and it didn't get better, and I tried to reinstall Magit for another several times and same results.

Finally I couldn't take the slow speed anymore and got the old version of magit back using git command in terminal, and the speed of old version is much better than v2.1.0.

So what's wrong with it?

FYI:
Fedora 22, 32-bit
GNU Emacs 24.5.1
git 2.4.3

**Comment by tarsius** [comment]
> So what's wrong with it?

Hard to tell, you don't provide much information.

> I tried to `s` at one package directory in my `elpa`

Does adding individual files take long too?

Have you turned on the new wip modes? Because otherwise all that magit does when staging all files in directory, is basically running `git add -u -- directory` which shouldn't cause Emacs itself to use much resources.

**Comment by c02y** [comment]
> I tried to `s` at one package directory in my elpa

Sorry I didn't tell it clearly, I mean I update some packages in my `elpa` using `package.el`, and then new version of packages are not tracked by git, so they are under the `Untracked files` to track, one whole directory will be in one line, and I use `s` to put one package directory into `Unstaged changes`, this will takes a lot time. And basically everything will takes much more time than the old version of Magi, **even when I didn't any configuration about magit.**

**Comment by tarsius** [comment]
> And basically every action takes more time than the old version of Magit,

Is there a particular reason why you singled out the "staging an untracked directory" case then? Or should I start from "everything is slower"? By the way is that the case in every repository?

**Comment by phil-s** [comment]
c02y: Try installing Magit in an empty Emacs config (temporarily rename `.emacs.d`) and repeat your test, to establish the default performance. You can also use ELP to instrument the `magit` package and provide benchmarks.

**Comment by c02y** [comment]
@tarsius I was trying to update (track, stage, commit, update) my Emacs configuration to Github, so all I tried is to `M-x magit-status` and track the untracked files (directories), because the `tracking` action is too slow, I also tried to undo the files (untrack the directory) and found it was also very slow, because all of the actions I mentioned (including `M-x magit-status`) were very slow, so I tried to restart my Emacs and it didn't get better and then reinstall magit several times and it didn't get better, so I gave up.

I can say everything is slow in the new version of Emacs, but I only tried 3 actions , the `track untracked files` is the first action I found intolerable and I did it for many times, and the `undo` is also intolerable, but I only did it twice. That's why I singled `track the untracked files` out.

As I said, I **only** tried the new version of Magit in my `.emacs.d` repo.

If you know any configuration that might slow Magit down, such as `linum-mode` or `font-lock`, please point them out or check my [init.el](https://github.com/c02y/dotemacs.d/blob/master/init.el) file.

**Comment by c02y** [comment]
@tarsius  @phil-s I tried to mv my .emacs.d, and install Magit with completely empty configuration, and tried Magit in my old .emacs.d repo I just mved, it is still very slow, even `M-x magit-status`, and I tried it in another repo, it is quite fast, so I guess the problem is the repo size, since the buffer size of magit buffer (the buffer after `M-x magit-status` ) my old .emacs.d is about 20MB, and another one is just 300KB.

But like I said, the old version of Magit is way more faster than Magit v2.1.0 in the same big repo.

**Comment by phil-s** [comment]
You can use ELP to provide some timing data.

`M-x elp-instrument-package` `RET` `magit` `RET` to enable profiling. Once you're done, use `M-x elp-restore-all` to disable profileing.

With profiling enabled, get ready to run a command, use `M-x elp-reset-all` to clear current data, then run the Magit command, and finally use `M-x elp-results` to see the data.

**Comment by c02y** [comment]
@phil-s This is the `elp-results` after hitting `s` to track an untracked directory which contains only 3 elisp files, 2 elc files and 1 temporary `*~` file.

    Function Name                                   Call Count  Elapseed Time Average Time 
    magit-wash-sequence                             5281        242.51283241  0.0459217633
    magit-refresh-buffer                            2           132.70429716  66.352148581
    magit-status-refresh-buffer                     2           132.60965405  66.304827027
    magit-git-wash                                  8           129.76028879  16.220036099
    magit-diff-wash-diffs                           4           127.46178739  31.865446847
    magit-diff-wash-diff                            5277        127.19468356  0.0241035974
    magit-diff-insert-file-section                  5277        116.39740885  0.0220574964
    magit-insert-unstaged-changes                   2           116.25633638  58.12816819
    magit-diff-wash-hunk                            10558       115.23754436  0.0109147134
    magit-stage                                     1           113.89925583  113.89925583
    magit-stage-untracked                           1           113.89918067  113.89918067
    magit-run-git-no-revert                         1           113.89893832  113.89893832
    magit-run-git                                   1           113.89893212  113.89893212
    magit-refresh                                   1           113.83235059  113.83235059
    magit-status                                    1           18.892394256  18.892394256
    magit-status-internal                           1           18.892388908  18.892388908
    magit-insert-staged-changes                     2           13.968403484  6.984201742
    magit-delete-line                               31594       7.6273929460  0.0002414190
    magit-git-insert                                26          2.7310812460  0.1050415863
    magit-section-show                              150         1.198069113   0.0079871274
    magit-get-section                               2724        0.7324945610  0.0002689040
    magit-section-hide                              5277        0.5794951320  0.0001098152
    magit-insert-untracked-files                    2           0.342029133   0.1710145665
    magit-git-items                                 2           0.299598022   0.149799011
    magit-git-exit-code                             2           0.272760153   0.1363800765
    magit-diff-wash-diffstat                        4           0.2369822190  0.0592455547
    magit-insert-status-headers                     2           0.2281763180  0.1140881590
    magit-insert-headers                            2           0.20046965    0.100234825
    magit-insert-head-header                        2           0.200456492   0.100228246
    magit-git-str                                   51          0.192258092   0.0037697665
    magit-section-ident                             10810       0.1684089270  1.557...e-05
    magit-git-string                                14          0.1596660329  0.0114047166
    magit-rev-format                                4           0.141593565   0.0353983912
    magit-rev-parse-safe                            31          0.1354369169  0.0043689328
    magit-toplevel                                  9           0.0785269     0.0087252111
    magit-insert-heading                            10575       0.0745992909  7.054...e-06
    magit-insert-remaining-headers                  2           0.0734748520  0.0367374260
    magit-call-git                                  1           0.066572385   0.066572385
    magit-call-process                              1           0.061337671   0.061337671
    magit-diff-expansion-threshold                  10717       0.048515596   4.526...e-06
    magit-insert-child-count                        10713       0.0462601039  4.318...e-06
    magit-insert-upstream-header                    2           0.038551316   0.019275658
    magit-insert-tags-header                        2           0.034534641   0.0172673205
    magit-insert                                    14          0.032613487   0.0023295347
    magit-rev-verify                                4           0.0310115260  0.0077528815
    magit-get-current-tag                           2           0.0304426719  0.0152213359
    magit-git-dir                                   18          0.027751023   0.0015417235
    magit-get                                       16          0.024171622   0.0015107263
    magit-insert-unpushed-commits                   2           0.017713874   0.008856937
    magit-status-mode                               1           0.016861041   0.016861041
    magit-get-tracked-ref                           4           0.016739055   0.0041847637
    magit-insert-unpulled-commits                   2           0.015632435   0.0078162175
    magit-mode                                      2           0.015452735   0.0077263675
    magit-get-current-branch                        8           0.014105844   0.0017632305
    magit-process-setup                             1           0.01371197    0.01371197
    magit-revision-set-visibility                   5443        0.0108514859  1.993...e-06
    magit-process-buffer                            2           0.010454138   0.005227069
    magit-bisect-in-progress-p                      6           0.009474501   0.0015790835
    magit-decode-git-path                           10554       0.0089214199  8.453...e-07
    magit-get-tracked-branch                        2           0.008275163   0.0041375815
    magit-mode-get-buffer                           4           0.0079609570  0.0019902392
    magit-maybe-save-repository-buffers             3           0.006850615   0.0022835383
    magit-save-repository-buffers                   2           0.006822186   0.003411093
    magit-insert-rebase-sequence                    2           0.006437063   0.0032185315
    magit-rebase-in-progress-p                      2           0.006425277   0.0032126385
    magit-insert-sequencer-sequence                 2           0.006318008   0.003159004
    magit-mode-get-buffers                          2           0.0046887149  0.0023443574
    magit-get-next-tag                              2           0.004069849   0.0020349245
    magit-load-config-extensions                    2           0.003636978   0.001818489
    magit-get-all                                   2           0.003623582   0.001811791
    magit-git-lines                                 2           0.0036068660  0.0018034330
    magit-section-update-highlight                  14          0.0034191459  0.0002442247
    magit-insert-stashes                            2           0.003336308   0.001668154
    magit-insert-bisect-rest                        2           0.003246298   0.001623149
    magit-insert-bisect-output                      2           0.0031867859  0.0015933929
    magit-revert-in-progress-p                      2           0.00316951    0.001584755
    magit-cherry-pick-in-progress-p                 2           0.003127127   0.0015635635
    magit-process-set-mode-line                     1           0.003112922   0.003112922
    magit-insert-am-sequence                        2           0.003107728   0.001553864
    magit-am-in-progress-p                          2           0.003096041   0.0015480205
    magit-insert-bisect-log                         2           0.003074413   0.0015372065
    magit-mode-get-buffer-create                    2           0.002969337   0.0014846685
    magit-insert-merge-log                          2           0.002933797   0.0014668985
    magit-get-boolean                               2           0.002800121   0.0014000605
    magit-git-true                                  2           0.002784499   0.0013922495
    magit-process-mode                              1           0.002609164   0.002609164
    magit-section-highlight                         12          0.001801036   0.0001500863
    magit-section-make-overlay                      12          0.0016940759  0.000141173
    magit-process-finish                            1           0.001670021   0.001670021
    magit-process-unset-mode-line                   1           0.001598092   0.001598092
    magit-process-git-arguments                     80          0.000487343   6.091...e-06
    magit-mode-display-buffer                       1           0.00044109    0.00044109
    magit-expand-git-file-name                      27          0.000319815   1.1845e-05
    magit-diff-highlight                            12          0.000308245   2.568...e-05
    magit-pre-command-hook                          107         0.0002889739  2.700...e-06
    magit-unhighlight-region                        61          0.0002651229  4.346...e-06
    magit-diff-scope                                14          0.0002523929  1.802...e-05
    magit-section-goto-successor                    1           0.00020917    0.00020917
    magit-git-repo-p                                1           0.00017717    0.00017717
    magit-process-insert-section                    1           0.000110724   0.000110724
    magit-diff-type                                 13          9.336...e-05  7.181...e-06
    magit-put-face-property                         19          7.918...e-05  4.167...e-06
    magit-current-section                           22          5.765...e-05  2.620...e-06
    magit-log-format-max-count                      4           4.648...e-05  1.162...e-05
    magit-file-lines                                2           4.3867e-05    2.19335e-05
    magit-region-sections                           14          3.8147e-05    2.724...e-06
    magit-section-goto-successor-1                  1           2.2324e-05    2.2324e-05
    magit-xref-insert-buttons                       4           1.2826e-05    3.2065e-06
    magit-section-siblings                          1           3.009e-06     3.009e-06
    magit-wip-commit-before-change                  1           2.304e-06     2.304e-06
    magit-revert-buffers                            1           1.17e-06      1.17e-06
    magit-cancel-section                            4           0             0.0
    magit-insert-log                                4           0             0.0

**Comment by AlexChesters** [comment]
+1. Magit 2+ is unbearably slow for large commits

**Comment by alamaison** [comment]
+1 Same here.  Merge commits are especially painful, probably because they tend to be large.  Magit 1.4.1 was not noticeably slower than git itself.  Magit 2+ locks up Emacs for a while using 100% of one (of 8) CPU cores, just to update magit-status or to stage a single file.

**Comment by tarsius** [comment]
When it does that are then many (hundreds if not thousands) files with changes listed under Unstaged and Staged changes? If everything is committed, is it still slower than 1.4 then?

**Comment by AlexChesters** [comment]
Magit 2+ seems to be very slow in general when interacting with large commits (e.g `magit-status` whilst updating 5 emacs packages), it will contain to be slow for the staging and committing of these files, but will be fine once the commit has been made

**Comment by c02y** [comment]
@tarsius When it does, there are many files with changes listed under Untracked, Unstaged and Staged, and like I said, the size of the magit buffer after executing `M-x magit-status` is about 20MB.

I didn't try it the situation that everything is committed, couldn't make it far.

**Comment by phil-s** [comment]
That's massive. Commit it from the command line (i.e. outside of Emacs), and then refresh the Magit status buffer.

**Comment by c02y** [comment]
@phil-s  Magit v2.1.0 is instant in the same big repo if everything in it is committed, since nothing is shown in the magit buffer after `M-x magit-status`.

**Comment by alamaison** [comment]
My magit-status buffer is nowhere near 20MB, not even on a merge, but it is still really slow where 1.4 was really fast.

**Comment by alamaison** [comment]
I've profiled refreshing the magit-status buffer `g`, while a merge is in progress.  The CPU profile report is as follows:
```
- command-execute                                               22968  99%
 - call-interactively                                           22968  99%
  - magit-refresh                                               22879  99%
   - magit-refresh-buffer                                       22845  99%
    - apply                                                     22738  98%
     - magit-status-refresh-buffer                              22738  98%
      - byte-code                                               22626  98%
       - run-hooks                                              22590  98%
        - magit-insert-staged-changes                           22279  96%
         - byte-code                                            22203  96%
          - magit-git-wash                                      22203  96%
           - magit-diff-wash-diffs                              22064  95%
            - magit-wash-sequence                               22041  95%
             - #<compiled 0xa16867>                             22041  95%
              - magit-diff-wash-diff                            21965  95%
               - magit-diff-insert-file-section                 20806  90%
                - byte-code                                     20694  89%
                 - magit-wash-sequence                          20690  89%
                  - magit-diff-wash-hunk                        20686  89%
                     byte-code                                    184   0%
                     magit-delete-line                            164   0%
                 magit-delete-line                                339   1%
              magit-diff-wash-diffstat                             23   0%
           + magit-git-insert                                     139   0%
        + magit-insert-merge-log                                  276   1%
        + magit-insert-stashes                                     11   0%
        + magit-insert-unstaged-changes                             9   0%
        + magit-insert-unpushed-commits                             6   0%
        + magit-insert-unpulled-commits                             5   0%
        + magit-insert-status-headers                               4   0%
       + magit-section-show                                        36   0%
   + magit-revert-buffers                                          27   0%
   + run-hooks                                                      7   0%
  + byte-code                                                      74   0%
  + execute-extended-command                                       15   0%
```
As you can see,`magit-diff-wash-hunk` seems to be responsible for this.

**Comment by alamaison** [comment]
In case the memory profile is also revealing:

```
- command-execute                                         151,340,937  98%
 - call-interactively                                     151,340,937  98%
  - magit-refresh                                         135,309,402  88%
   - magit-refresh-buffer                                  83,113,199  54%
    - apply                                                83,113,199  54%
     - magit-status-refresh-buffer                         83,113,199  54%
      - byte-code                                          83,047,613  54%
       - run-hooks                                         82,985,017  54%
        - magit-insert-staged-changes                      67,546,807  44%
         - byte-code                                       67,546,807  44%
          - magit-git-wash                                 67,543,722  44%
           - magit-git-insert                              65,924,334  43%
            - apply                                        65,924,334  43%
             - process-file                                65,924,334  43%
                apply                                      65,924,334  43%
           + magit-diff-wash-diffs                          1,619,388   1%
            magit-insert-child-count                            2,056   0%
          + magit-insert-heading                                1,029   0%
        + magit-insert-unpushed-commits                     7,812,786   5%
        + magit-insert-merge-log                            2,032,034   1%
        + magit-insert-status-headers                       1,605,988   1%
        + magit-insert-unpulled-commits                       825,015   0%
        + magit-insert-sequencer-sequence                     536,324   0%
        + magit-insert-rebase-sequence                        528,140   0%
        + magit-insert-untracked-files                        502,602   0%
        + magit-insert-stashes                                382,100   0%
        + magit-insert-am-sequence                            264,083   0%
        + magit-insert-bisect-output                          264,061   0%
        + magit-insert-bisect-rest                            264,061   0%
        + magit-insert-bisect-log                             264,061   0%
        + magit-insert-unstaged-changes                       156,955   0%
       + magit-section-show                                    62,596   0%
      + magit-git-exit-code                                    65,586   0%
   - magit-revert-buffers                                  51,995,783  33%
    - file-in-directory-p                                  37,053,274  24%
     - file-truename                                       19,615,348  12%
      - file-truename                                      16,325,248  10%
       - file-truename                                     13,027,880   8%
        + file-truename                                     9,731,262   6%
     - file-equal-p                                        15,771,664  10%
      - file-truename                                      12,623,440   8%
       + file-truename                                      9,458,840   6%
       split-string                                             1,024   0%
    + mapcar                                               10,214,704   6%
    + magit-revision-files                                  4,518,126   2%
    + magit-toplevel                                          198,443   0%
      file-relative-name                                        8,188   0%
   + run-hooks                                                200,420   0%
  + byte-code                                              11,151,811   7%
  + execute-extended-command                                4,879,724   3%
```

**Comment by alamaison** [comment]
The result of `magit-version`: `Magit 20150727.1535, Git 1.9.1, Emacs 24.4.1`

**Comment by alamaison** [comment]
Also, making a change in the status buffer, for example staging a file, triggers a similar long wait.

**Comment by goofansu** [comment]
+1. It's about 1-2 seconds to open any window.

Version: `Magit 20150802.1333, Git 2.4.4, Emacs 24.5.1`

**Comment by tarsius** [comment]
I am closing this in favor of the "umbrella issue" #2104.
