### ISSUE TITLE
Checking out a remote branch from the branch manager doesn't DWIM

### ISSUE THREAD

**Issue by Jell** [magit/magit#2101]
If I bring up the branch manager with `y` and press return on a remote branch I want to check out, I mean I want to create a local copy of that branch with the same name and maybe set tracking for it.

This was the default in magit 1.0, and the first time I tried I remember thinking "wow! that's exactly what I expected!" so I think this is a reasonable default.

Right now I end up in a "detached" branch instead, I don't think that's ever a state I want to be in?

**Comment by tarsius** [comment]
`RET` usually means "show it". I have convinced myself that checking out a branch is just another form of "showing it", when I was asked to make `RET` checkout in the "branch manager" (now known as ("refs buffer" because it also shows tags). See  #2062.

Creating a *new* branch cannot really be defined as yet another form of simply "showing something". So I hesitate to go back to the old behavior here too. Besides I find it useful occasionally to work with a detached HEAD.

I might eventually do what you are suggesting here, but I'll first let this issue rest for a while.

**Comment by Jell** [comment]
Fair enough! Perhaps I haven't played enough with the new version to see the consistency. I myself kind of built up the impression that `SPC` was "show" and `RET` was "go there" when using v1.

**Comment by AlexChesters** [comment]
+1. It makes it a chore to checkout a branch, I very rarely want to be in a detached state

**Comment by domtronn** [comment]
+1  Having to press `b B RET RET` to create a local copy of a branch. I think I had a similar impression to @Jell, in that I saw `RET` as _'go there'_ from v1, because this is what I want to work on.

**Comment by tarsius** [comment]
I have added a new option `magit-visit-ref-create`. Set it to `t` to get the old behavior.

**Comment by Jell** [comment]
Thanks! Although IMHO this should be the default, I can only see the detached behaviour being useful for advanced users (I never have needed this behaviour and I use git every day).

Anyway, thanks again and keep up the good work! :+1:

**Comment by AlexChesters** [comment]
+1 for this being the default

**Comment by davidw** [comment]
I don't know if this is really related, but even with b B, there's still something that seems a bit off to me (maybe I'm doing something wrong?): it leaves the upstream as master.  I'd prefer it to point to something else so as to not accidentally push to master, like I just did.

**Comment by AlexChesters** [comment]
+1 what @davidw said

**Comment by tarsius** [comment]
> I don't know if this is really related,

It's not, see #2076 instead

> seems a bit off to me (maybe I'm doing something wrong?): it leaves the upstream as master.

As [documented](http://magit.vc/manual/magit/Branching.html), this is the intended behavior.
