### ISSUE TITLE
Not easy to create a branch from a detached state

### ISSUE THREAD

**Issue by Jell** [magit/magit#2102]
If I try to create a branch from a detached state, I do not get a default `HEAD` suggestion for the starting branch (took me a while to figure out I should use HEAD to begin with). That would perhaps be a sensitive default?

**Comment by tarsius** [comment]
Yes, indeed. But I'll have to check to what other commands this extends and where I should therefore add this as a default.

**Comment by tarsius** [comment]
I had another look and noticed that `HEAD` is already offered as the second completion candidate. When `HEAD` is detached, then the first completion candidate, i.e. the default choice (which is shown in the prompt) refers to the same commit as `HEAD` does. It's something like `master`, `master~1`, `v4`, `v4~2`, or in rare cases an abbreviated hash. But it always refers to the same commit as `HEAD` would in this situation. And these other names for the same commit are better defaults, so I won't add `HEAD` as the default.
