### ISSUE TITLE
Some suggestions to make key bindings more discoverable

### ISSUE THREAD

**Issue by jsyjr** [magit/magit#2106]
Original title was: **support reseting individual hunks within unstage changes section**, it was changed because the focus of this issue has quickly shifted elsewhere. -- @tarsius

----

Recently I was looking at a diff in a magit-status buffer showing an unstaged change that was nothing more than corrupted indentation.  It would have be very convenient to hit 'x' on that hunk and have it vanish.

**Comment by npostavs** [comment]
You can discard (which is what I think you mean by "resetting") a hunk with `k`.

**Comment by jsyjr** [comment]
Right you are...

But not very discoverable.  When I do [C-h m] (describe-mode) in the status buffer, even  with the cursor sitting on the chunk header, no binding for 'k' gets displayed; nor does any other binding mention magit-discard.

**Comment by npostavs** [comment]
Hmm yeah, discard seems pretty fundamental (i.e. status mode seems quite deficient without it); I've added a mention to the docstring of `magit-status-mode` in 95509a5b097e937a7a29177b154330bd3400a3b1

**Comment by jsyjr** [comment]
On Wed, Jul 22, 2015 at 2:13 AM, Noam Postavsky <notifications@github.com>
 wrote:

> Hmm yeah, discard seems pretty fundamental (i.e. status mode seems quite
> deficient without it); I've added a mention to the docstring of
> magit-status-mode in 95509a5
> <https://github.com/magit/magit/commit/95509a5b097e937a7a29177b154330bd3400a3b1>
>

That is a pretty lame solution.  Nowhere else in emacs do I look at the doc
string for a (massively complex) major mode to discover obscure bindings.

The whole pop-up mechanism is intended to make magit more discoverable and
easier to learn.  An inability to locate important functionality via that
interface is an important short coming.  I understand that 'k' does not
conform to the pop-up protocol.  Still there should be a means from that
interface to learn of _all_ such 'immediate' bindings.

As I mentioned previously, [C-h m] (describe-mode) is the other
conventional means of discovering the full set of available bindings.  The
fact that 'k' (and others too?) are not listed there represents an
additional barrier to discoverability.

That being said, I looked at your commit and it is indeed and improvement.
Thank you.

**Comment by npostavs** [comment]
>> I've added a mention to the docstring of magit-status-mode
>
> Nowhere else in emacs do I look at the doc string for a (massively complex) major mode to discover obscure bindings.
> [...]
> As I mentioned previously, `C-h m` (describe-mode) is the other conventional means of discovering the full set of available bindings. The fact that 'k' (and others too?) are not listed there represents an additional barrier to discoverability.

Ah, I was kind of in implementer mode when I wrote that; I said "docstring", but `describe-mode` shows that docstring, so from a user's point of view I added it to the "mode description".

> The whole pop-up mechanism is intended to make magit more discoverable and easier to learn.

I disagree. The pop-up mechanism is intended to make commands that have many different options usable, instead of having some impossible to remember system of prefix arguments.

> Still there should be a means from that interface to learn of _all_ such 'immediate' bindings.
 
The more stuff we add to the catch all popup, the harder it is to read.

**Comment by jsyjr** [comment]
On Wed, Jul 22, 2015 at 2:57 PM, Noam Postavsky <notifications@github.com>
wrote:

> Ah, I was kind of in implementer mode when I wrote that; I said
> "docstring", but describe-mode shows that docstring, so from a user's
> point of view I added it to the "mode description".
>
I failed to catch that implication.  Still it is strange that of all the
keys provided a "Type ..." description (i.e.: 'g', '?', TAB, RET, 's', 'u',
'k' and 'c') only RET and 'k' lack entries in the subsequent table of
bindings.  Why is that?

> I disagree. The pop-up mechanism is intended to make commands that have
> many different options usable, instead of having some impossible to
> remember system of prefix arguments.
>
Point well taken.

> The more stuff we add to the catch all popup, the harder it is to read.
>
Again, I agree.

/john

**Comment by npostavs** [comment]
> Still it is strange that of all the keys provided a "Type ..." description (i.e.: 'g', '?', TAB, RET, 's', 'u', 'k' and 'c') only RET and 'k' lack entries in the subsequent table of bindings. Why is that?

Simply because they are not bound in `magit-status-mode-map`. They are bound in section-specific keymaps instead.

**Comment by jsyjr** [comment]
On Wed, Jul 22, 2015 at 10:23 PM, Noam Postavsky <notifications@github.com>
wrote:

> Still it is strange that of all the keys provided a "Type ..." description
> (i.e.: 'g', '?', TAB, RET, 's', 'u', 'k' and 'c') only RET and 'k' lack
> entries in the subsequent table of bindings. Why is that?
>
> Simply because they are not bound in magit-status-mode-map. They are
> bound in section-specific keymaps instead.
>

Come on Noam!  That is a lousy response: "There is no rationale to our UI,
it merely falls out of our implementation".

Operationally 's' and 'u' are implemented exactly like 'k'.  But someone
(Jonas?) also saw fit to provide mode-wide bindings implementing default
behaviors where if the cursor is not appropriately positioned magit prompts
for a file.  'k' by contrast reports "k is undefined" and, worse, RET
reports "Buffer is read-only: #<buffer *magit: ...*>".  Surely 'k' could
receive exactly the same treatment as 's' and 'u'.  And for simple
regularity should not an inappropriately positioned RET prompt for a file
to open?

With such changes I would argue that the 'crib sheet' at the top of the
describe-mode *Help* buffer become superfluous as it barely does more that
repeat information in the subsequent table.

I am not arguing that a crib sheet is inappropriate.  Quite the contrary.
Perhaps 'H' could pop up such a buffer.

/john

**Comment by npostavs** [comment]
> Come on Noam! That is a lousy response: "There is no rationale to our UI, it merely falls out of our implementation".

Well there is some rationale to the UI, but for this particular case it really does just fall out of the implementation. :p

> Surely 'k' could receive exactly the same treatment as 's' and 'u'.

That sounds reasonable. 

> And for simple regularity should not an inappropriately positioned RET prompt for a file to open?

I think it might be more useful (as in, more likely to be something the user wants to do) to prompt for a commit to open.

> With such changes I would argue that the 'crib sheet' at the top of the describe-mode *Help* buffer become superfluous as it barely does more that repeat information in the subsequent table.

Having a tl;dr version is still worth something, the keymap table is pretty long.

---

@kyleam, @tarsius thoughts?

**Comment by tarsius** [comment]
@jsyjr Do yourself a favor and skip such summaries of how you perceived someone else's response: "That is a pretty lame solution.", "That is a lousy response:". Leaving that out increases the odds of the feature request being prioritized. It's just more enjoyable to implement a suggestion, simply because it's a good idea, than to do it (also) in order to avoid being criticized for being brief. There is a reason why we are at times brief, we have a lot of other things to do, and sometimes a brief reply fully satisfies a user. So we not always write an in-depth reply upfront, just in case.

@npostavs "Buffer is read-only: #<buffer *magit: ...*>" isn't nice. For keys which are only bound in section keymaps we could add noop-bindings to `magit-mode-map`, which say something like "There is no thing we know how to visit at point" (for RET).

It is not completely arbitrary whether a key which is bound in section maps is also bound in mode maps. For example in magit buffer (excluding popups) `s` only ever stages changes, while `k` performs some kind of deletion. For files and hunks we call that "discard", but that's just a specialized term for "delete". So `k` is used to delete something and we don't know what, because there's no deletable thing at point, then what should we offer instead? Discard all changes, all staged changes, all unstaged changes, prompt for a file, prompt for a branch, prompt for a remote ...?

Maybe there's a fallback that makes more sense than others. I am just saying that there currently aren't any for the keys mentioned above, not because I forgot about it, but because it's not obvious what the best solution would be.

**Comment by jsyjr** [comment]
On Thu, Jul 23, 2015 at 10:00 AM, Noam Postavsky <notifications@github.com>
wrote:

> That sounds reasonable.
>
Glad I could persuade you.

> I think it might be more useful (as in, more likely to be something the
> user wants to do) to prompt for a commit to open.
>
I was arguing for a regular - and therefore easily internalized - model for
the UI.  I do not have strong feelings about RET.

> Having a tl;dr version is still worth something, the keymap table is
> pretty long.
>
Yes but the table is (or at least should be) authoritative.  I pop it up
specifically to scan that characteristically formatted table of bindings,
no matter how long it is.  My eyes (and I suspect many others) skip over
anything preceding that table as describe-mode supplied boilerplate.  So
rather than embed a tl;dr version into the buffer formatted by
describe-mode I would suggest two paths to a dedicated summary usage buffer:

   - By augmenting the initial text with a hyperlink:

*Magit* mode defined in ‘*magit.el*’:

Mode for looking at Git status.

A *summary of common usage* is available.
>
Detailed documentation is in info node ‘*(magit)Status*’.


   - By binding 'H' to magit-summary-of-common-usage

/john

**Comment by jsyjr** [comment]
On Thu, Jul 23, 2015 at 10:22 AM, Jonas Bernoulli <notifications@github.com>
wrote:

> @jsyjr <https://github.com/jsyjr> Do yourself a favor and skip such
> summaries of how you perceived someone else's response: "That is a pretty
> lame solution.", "That is a lousy response:". Leaving that out increases
> the odds of the feature request being prioritized. It's just more enjoyable
> to implement a suggestion, simply because it's a good idea, than to do it
> (also) in order to avoid being criticized for being brief.
>
Jonas,

You are right to point out my poor behavior.  My apologies to everyone
working on magit.  In the future will endeavor to keep such comments out of
my postings.

Thanks for the wonderful tool.

/john

**Comment by tarsius** [comment]
It's okay, and thanks for the apology.

**Comment by jsyjr** [comment]
On Thu, Jul 23, 2015 at 10:22 AM, Jonas Bernoulli <notifications@github.com>
wrote:

> It is not completely arbitrary whether a key which is bound in section
> maps is also bound in mode maps. For example in magit buffer (excluding
> popups) s only ever stages changes, while k performs some kind of
> deletion. For files and hunks we call that "discard", but that's just a
> specialized term for "delete". So k is used to delete something and we
> don't know what, because there's no deletable thing at point, then what
> should we offer instead? Discard all changes, all staged changes, all
> unstaged changes, prompt for a file, prompt for a branch, prompt for a
> remote ...?
>
Parallels between the behaviors of s, u and k are great enough that users
internalize them as a pattern.  Continuing that pattern by having k with
nothing to discard/delete prompt for a file fosters ease of learning and
discoverability.

**Comment by npostavs** [comment]
> Yes but the table is (or at least should be) authoritative. I pop it up specifically to scan that characteristically formatted table of bindings, no matter how long it is. My eyes (and I suspect many others) skip over anything preceding that table as describe-mode supplied boilerplate.

It sounds like you really want to be using `describe-bindings` (`C-h b`) instead of `describe-mode`.  Unfortunately this command orders the keymaps by precedence so the major-mode goes next to last, which makes it a bit inconvenient for quick lookup.

> rather than embed a tl;dr version into the buffer formatted by
> describe-mode I would suggest two paths to a dedicated summary usage buffer:
>  - By augmenting the initial [mode description] text with a hyperlink:
>
> [...]
>
>  - By binding 'H' to magit-summary-of-common-usage

Having a usage summary before the bindings in the mode description is pretty standard in Emacs, I don't know of any Emacs mode that puts the summary usage elsewhere.

> For keys which are only bound in section keymaps we could add noop-bindings to magit-mode-map, which say something like "There is no thing we know how to visit at point" (for RET).

Makes sense. That would be `K` `R` `<C-return>` `a` `C` `v` `k` `RET`, right? (produced by following code)

```elisp
(let ((keys ()))
  (mapatoms
   (lambda (sym)
     (when (and (boundp sym)
                (string-match-p "\\`magit.*-section-map\\'" (symbol-name sym)))
       (map-keymap
        (lambda (event _def)
          (cl-pushnew event keys))
        (symbol-value sym)))))
  (mapcar #'single-key-description
          (cl-remove-if (lambda (k) (lookup-key magit-mode-map (vector k)))
                        keys)))
```

**Comment by jsyjr** [comment]
@npostavs: Astute diagnosis.  I would indeed be content with a describe-major-mode-bindings.  (Interestingly C-h B is currently unbound :-)  I tried describe-mode on a number of random modes and see that your point is well taken: there is a pattern of providing a limited usage summary.  I seem always to have skipped it in the past.

**Comment by npostavs** [comment]
> I would indeed be content with a describe-major-mode-bindings.

Quick and dirty:
```elisp
(defun describe-major-mode-bindings ()
  (interactive)
  (call-interactively 'describe-bindings)
  (with-current-buffer (help-buffer)
    (search-forward "Major Mode Bindings")
    (narrow-to-page)))
```

Huh, that was easy, I should have done it ages ago.

> Interestingly C-h B is currently unbound

I've decided to override `C-h b` myself.

**Comment by jsyjr** [comment]
Being primarily a C++ programmer who writes elisp by mimicking patterns I
am always grateful for snippets like this.  I copied your choice and
overrode [C-h b] as well. Your implementation has the nice virtue that [C-x
n w] (widen) shows the original describe-bindings output.

**Comment by Jell** [comment]
+1 on @tarsius no-op idea of showing a message explaining why an operation cannot be run ("nothing to show at point", "nothing to kill at point"...)

This should also help build the intuition of the user with regard to the keys (`RET` is show, `k` is kill).

**Comment by tarsius** [comment]
This is being worked on in #2116 and #2120.
