### ISSUE TITLE
Performance with virtualbox-mounted directories (vboxsf)

### ISSUE THREAD

**Issue by phil-s** [magit/magit#2108]
FWIW (as performance issues are being looked at) I've just noted that the status buffer refresh is very slow for me when accessing a repository on a VM when the repository actually lives on the VM's host machine, and is mounted using vboxsf.

This isn't Magit's fault -- `git status` on the command line is taking 4 seconds to complete in a pristine working copy in my example, so clearly it's a filesystem issue -- but the result is that `magit-status` with its extra calls to git takes ~10 seconds.

I've raised this simply as another data point for potential sources of slowness (albeit surely not one which could have been particularly different under Magit 1).

That said, this scenario might benefit from any changes which can reduce the number of calls to git when performance is poor.

**Comment by daveloyall** [comment]
@phil-s Yes. Personally, I have a ~/src on vboxfs and a ~/src-e2 on ext2 for this reason.

**Comment by tarsius** [comment]
https://github.com/magit/magit/wiki/Tips-and-Tricks might be a better place for this. Here it will move "below the fold" quite quickly.

**Comment by tarsius** [comment]
I added a stub to Tips and Tricks.
