### ISSUE TITLE
Weird behavior when pushing first commit without upstream set

### ISSUE THREAD

**Issue by aengelberg** [magit/magit#2112]
Steps:

- started off with a fresh git repo (`git init`)
- opened Magit
- committed all files into initial commit
- added remote "origin"
- `P -u P origin [RET]`

Push failed with this output:
```
128 git … push -v --set-upstream master
Pushing to master
fatal: 'master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Looks like "origin" is not getting inserted into the push command as it is supposed to.

Ubuntu 14.04
Git 2.4.5
Emacs 24.4.1
Magit 20150707.1335

**Comment by tarsius** [comment]
You have to specify what remote branch you want to push to as in `P -u P origin/master RET`, `origin/master` should be offered as a completion candidate.

**Comment by aengelberg** [comment]
Thanks, I did not realize that was the syntax (the "Push ___ to:" message threw me off).

**Comment by yamatakau08** [comment]
I'm using the following "Magit" version.
(magit-version)
"20180512.1350"

"P -u P origin/master RET"
But it seems to be "-u" is no longer supported.
How do I use the same command to Magit?

**Comment by kyleam** [comment]
@yamatakau08, see [this emacs stackexchange answer][0].  In the future, please ask support questions a [channel][1] listed in the readme rather than posting to old issues.

[0]: https://emacs.stackexchange.com/a/6023
[1]: https://github.com/magit/magit#support
