### ISSUE TITLE
"Push Current" always asks where to push

### ISSUE THREAD

**Issue by mrkkrp** [magit/magit#2115]
It seems like `Push Current` <kbd>P P</kbd> now always asks where to push, every time I push I see IDO interface with only one option `origin/master`. I've tried to set upstream again (although it's set already), but it doesn't work.

I believe it's due to some recent change in Magit. I can't say I'm happy with this new behavior because pushing is a bit harder now. Can you clarify whether it's new feature or a bug?

If this is on purpose, how can I return to old-fashioned `Push Current`?

**Comment by mrkkrp** [comment]
I've just read #2076, so I see it's on purpose. This works:

```emacs-lisp
(setq magit-push-always-verify nil)
```

I would add this to Magit FAQ.

**Comment by tarsius** [comment]
Indeed I recently made such a change to protect the innocent (see #2115). I did not only change the behavior, I also added a note about it to the prompt:

```
Push somebranch to [also see option magit-push-always-verify]
```

Not the part in brackets. Doing that will answer your questions.

**Comment by tarsius** [comment]
Ah, you've seen it.

**Comment by syl20bnr** [comment]
@tarsius  I'm not sure about what is different in Spacemacs but when I push the  `develop` branch I got a helm popup with `origin/develop` as the default selection which is different than OP. Moreover the helm buffer is populated with all the existing branches which again is different than OP.
