### ISSUE TITLE
the bind of 'V' key in magit-status buffer

### ISSUE THREAD

**Issue by unknownzerx** [magit/magit#2118]
If I press 'V' directly in magit-status buffer, it will popup something related to 'Revert'.

But if I press '?' first and then 'V', it goes to 'Show File'. Is this inconsistency a bug?

**Comment by tarsius** [comment]
Yes, it's a bug, but quite insignificant, so I classify it as a `fly`.

**Comment by tarsius** [comment]
I fixed this binding and removed another. But this is to be further improved, see #2120.

**Comment by unknownzerx** [comment]
@tarsius
The inconsistency has gone.
Well I think 'show file' is quite useful... How to toggle it now?

**Comment by tarsius** [comment]
Update and then see the "File-buffer mode" section in the manual.
