### ISSUE TITLE
q is bound to magit-invoke-popup-action

### ISSUE THREAD

**Issue by syl20bnr** [magit/magit#2121]
In magit 1.4 I pressed `q` to exit a popup, I also used this technique in evil-escape (send a `q` event to close the popup).
I just pushed to origin when pressing `q` in the Push popup.

Is `q` now used in some popups so it cannot be used reliably to quit a popup ? Did I dream about `q` quitting the popup in magit 1.4 ? I'm confused.

**Comment by tarsius** [comment]
> some popups

I think the push popup was the only one.
