### ISSUE TITLE
Which version?

### ISSUE THREAD

**Issue by nayefc** [magit/magit#2123]
Emacs shows versions in this format: `20150728.1019`

Whats the best way to cross-check this version with the release number on Github? Is there a way to display magit release number in Emacs?

**Comment by tarsius** [comment]
No there's not. That's a limitation of Melpa. But there is hope: https://github.com/milkypostman/melpa/issues/2955.

You could however convert the Melpa timestamp into a format understood by Git and then look for a corresponding commit. (If you write this, then please post it here.)

**Comment by nayefc** [comment]
@tarsius Is the Melpa timestamp the date of the release on Magit's Github Releases page?

**Comment by tarsius** [comment]
No, it's the committer date of the latest commit (at the time melpa created the snapshot-release).
