### ISSUE TITLE
Bindings from magit-file-buffer-mode and dired, ag, and other directory specific modes

### ISSUE THREAD

**Issue by dgtized** [magit/magit#2131]
I recently switched to using `global-magit-file-buffer-mode`, and temporarily stripped my top level binding for <kbd>C-x g</kbd>. However the enabling logic in:

```elisp
(defun magit-file-buffer-mode-turn-on ()
  (and buffer-file-name
       (ignore-errors (magit-inside-worktree-p))
       (magit-file-buffer-mode)))
```

Doesn't detect that a dired buffer for the root or a subdirectory of the git repo is a valid target to enable for. It's not clear to me if this is the intended use case for the mode, but I'm going to re-add the two top level bindings since it's more useful for `magit-status` and `magit-dispatch-popup` to always be available.

I follow the utility of optionally enabling the file specific buffer binding, but I think that `magit-status` and `magit-dispatch-popup` bindings should not be limited to file buffers. Perhaps they should have their own global minor mode that is not toggling automatically, or the use case for this mode should be clarified?

**Comment by tarsius** [comment]
> It's not clear to me if this is the intended use case for the mode, but I'm going to re-add the two top level bindings since it's more useful for `magit-status` and `magit-dispatch-popup` to always be available.

Yes. That's the intention. `global-magit-file-buffer-mode` is an addition, not a substitute.
