### ISSUE TITLE
magit-log-buffer-file errors

### ISSUE THREAD

**Issue by ilohmar** [magit/magit#2134]
The above function, called in a source buffer in a repo, yields `Args out of range: 0` and shows no commits in the log (this is with default or with nil `magit-log-section-arguments`).  Worse, it seems that the default args for logging are messed up internally from then on, and calling the log *popup* already errors:
```
(wrong-type-argument stringp nil)
  string-match("^--author=\\(.*\\)" nil)
  [...]
```
and leaves a split window behind etc..

It appears that the `magit-log-arguments` call in l.544 has to be wrapped in a `car` (it returns a list of args and files, the latter is not used here):
```
(let ((args (car (magit-log-arguments))))
  (if (and follow (not (member "--follow" args)))
      (cons "--follow" args)
    args))
```

I do not know if this is the right place to add the car, or if something else is afoul, hence no pull request.

In any case, it would be good if such bugs would not leave magit in a confused state afterwards; again, I am sorry not to offer any concrete code suggestions, but I just stumbled upon this bug doing sth completely unrelated :)

**Comment by kyleam** [comment]
Thanks for the report and suggested change, which I've pushed.  I'll
leave this open for a bit in case @tarsius wants to comment on the
confused state bit.

**Comment by tarsius** [comment]
> In any case, it would be good if such bugs would not leave magit in a confused state afterwards;

That's one of those "nice to have, but not worth it" things.

In this case you could have gotten back to a sane state by killing the status buffer.
