### ISSUE TITLE
Symlinks to subdirectories of repos are not followed

### ISSUE THREAD

**Issue by chep** [magit/magit#2135]
HI,

I don't know if this is a regression or a feature but magit does not follow
symbolic links anymore.

Example:

/home/chep
|
|---- folder1 -> gitRepo/folder1
|
|---- gitRepo
|     |
|     |---- folder1
|     |
|     |---- folder2
...

When I use C-u M-x magit-status RET /home/chep/folder1 RET I have the message:

/home/chep/ is a repository.  Create another in /home/chep/folder1/? (y or n)

It used to notice that folder1 is in gitRepo and was opening gitRepo status but
since a couple of weeks it does not work anymore.

Regards.

**Comment by tarsius** [comment]
Works for me. What does `M-x magit-version` say?

```
/tmp/test
├── extern
│   ├── .git
│   └── subdir
└── outer
    ├── .git
    └── inner -> ../extern
```

Entering `/tmp/test/outer/inner/` shows the status for that repository. `/tmp/test/outer/inner/subdir/` asks whether I want to create a new repository in there.

**Comment by chep** [comment]
M-x magit-version:
Magit 20150802.1333, Git 2.4.6, Emacs 25.0.50.1

**Comment by tarsius** [comment]
Indeed I get that behavior too.

We now just ask where the repository is, doing the equivalent of:

```
cd /home/chep/folder1
git rev-parse --git-dir
```

I suppose we could add an option analogous to `find-file-visit-truename` which would cause `/home/chep/gitRepo/folder1` to be substituted for `/home/chep/folder1`. But I don't think this sort of symlink is common, so I am not sure this is worth it.

**Comment by tarsius** [comment]
Hm... actually this should work without such a hack. I think. Will check later.

**Comment by tarsius** [comment]
What I wrote before was all non-sense. Will have to check later.

Just so much for now: the relevant commit is 65787d92910a77f0528fc4623c41af0e0b8e0e91.

**Comment by tarsius** [comment]
* We cannot use `--show-toplevel` because it always follows symlinks (anywhere leading up to pwd).
* `--show-cdup` doesn't work properly when a symlink points to a *subdirectory* of repository.
* We currently use `--show-toplevel` because that also respects `--work-tree`, `GIT_WORK_TREE`, and `core.worktree`.

Looks like we have to implement `--show-toplevel` in elisp and make it respect `find-file-visit-truename`.

**Comment by tarsius** [comment]
I have gone through the history of `magit-toplevel` and its predecessors and it is back and forth between various approaches, to address whatever issue was last raised by a user. Obviously we have to think about this more carefully than before.

The issue essentially boils down to this: http://harmful.cat-v.org/software/symlinks

> Symbolic links make the Unix file system non-hierarchical, resulting in multiple valid path names for a given file. This ambiguity is a source of confusion, especially since some shells work overtime to present a consistent view from programs such as pwd, while other programs and the kernel itself do nothing about the problem.

What we have done in the past in Magit is to flip between siding with the shell or the kernel. We have to make up our mind and clearly state what does and what does not work "as it obviously should" and why. And then stick with it. There will be trade-offs.

**Comment by tarsius** [comment]
This is the current implementation:

```lisp
(defmacro magit--with-safe-default-directory (file &rest body)
  (declare (indent 1) (debug (form body)))
  `(catch 'unsafe-default-dir
     (let ((default-directory
             (let ((file ,file))
               (file-name-as-directory (if file
                                           (expand-file-name file)
                                         default-directory)))))
       (while (not (file-accessible-directory-p default-directory))
         (when (string-equal default-directory "/")
           (throw 'unsafe-default-dir nil))
         (setq default-directory
               (file-name-directory
                (directory-file-name default-directory))))
       ,@body)))

(defun magit-toplevel (&optional file strict)
  (magit--with-safe-default-directory file
    (-if-let (cdup (magit-rev-parse-safe "--show-cdup"))
        (magit-expand-git-file-name
         (file-name-as-directory (expand-file-name cdup)))
      ;; Ignore this part:
      (unless strict
        (-when-let (gitdir (magit-git-dir))
          (if (magit-bare-repo-p)
              gitdir
            (file-name-directory (directory-file-name gitdir))))))))
```

**Comment by tarsius** [comment]
Please checkout out #2209 which will be part of v2.2.2.
