### ISSUE TITLE
magit-status only works if already in git repo

### ISSUE THREAD

**Issue by joonoro** [magit/magit#2136]
`magit-status` only works if already in a git repository. Running `magit-status` outside of a repo and entering the path at the prompt `Git repository: ~/git/myrepo` gives the message `user-error: Not inside a Git repository`. Prefix args don't seem to make a difference. If however, you `C-x C-f` into the directory and run `magit-status` it works as expected.

    magit-version
    Magit 20150802.1333, Git 2.3.2 (Apple Git-55), Emacs 24.5.1

**Comment by tarsius** [comment]
Are symlinks involved?

**Comment by joonoro** [comment]
Nope.

**Comment by tarsius** [comment]
Ah. At that prompt you are supposed to select one of the known repositories by name. What repositories are known is controlled by the variables `magit-repository-directories` and `magit-repository-directories-depth`. You can also show the status buffer for an arbitrary repository using two prefix arguments.

**Comment by tarsius** [comment]
Or you can set `magit-repository-directories` to nil, then `magit-status` will read a path when called outside a repository (and no prefix argument) or with a single prefix argument, not just when called with two prefix arguments.

**Comment by joonoro** [comment]
`magit-repository-directories` is already nil, I just upgraded to the latest version of Magit and it stopped working as expected.

**Comment by tarsius** [comment]
Actually you can insert the path to a repository at that prompt. My commit from a few minutes ago prevented that, so I have reverted it.

**Comment by joonoro** [comment]
I'm a little confused, so just to make sure we are on the same page:

I've never used `magit-repository-directories`, it's always been nil. I've never used the prefix args either. Every time I run `M-x magit-status` I simply enter the path to a repository and it opens. However with the latest version on melpa this no longer works and it says that my git repository is not a git repository. Entering a path to a valid git repository when `magit-status` asks for it does not work.

If Emacs is in the actual directory, i.e. `M-! pwd` prints the directory name, `magit-status` works as expected.

**Comment by tarsius** [comment]
```lisp
(defun magit-read-repository (&optional read-directory-name)
  (if (and (not read-directory-name) magit-repository-directories)
      (let* ((repos (magit-list-repos-uniquify
                     (--map (cons (file-name-nondirectory it) it)
                            (magit-list-repos))))
             (reply (magit-completing-read "[A] Git repository" repos)))
        (file-name-as-directory
         (or (cdr (assoc reply repos))
             (if (file-directory-p reply)
                 (expand-file-name reply)
               (user-error "Not a repository or a directory: %s" reply)))))
    (file-name-as-directory
     (expand-file-name ;; <==== added this
      (read-directory-name "[B] Git repository: "
                           (or (magit-toplevel) default-directory))))))
```

Does this make a difference? Also, do you get the prompt with the "[B]" in it?

**Comment by joonoro** [comment]
I get the [B], but it doesn't make a difference.

**Comment by tarsius** [comment]
I'm at a loss. I'll look into this tomorrow.

Just to make sure neither `/home`, `/home/you`, `/home/you/git`, nor `/home/you/git/myrepo` are symlinks, right?

**Comment by joonoro** [comment]
No, none of them are symlinks. Thanks for the help though, I'll look into it myself for now.

**Comment by joonoro** [comment]
Hmm I got it working. I think it was something on my end that messed up the upgrade. I noticed that `magit-status-internal` wasn't showing its docstring on the help page (even though it's there in the definition) and that if I re-evaluated its definition manually it started working normally. I uninstalled magit and downloaded it again and it's working fine now, so in any case the problem seems solved.

**Comment by tarsius** [comment]
Ah, good. I though it maybe was because I was really tired, but didn't see how this could possibly happen. :-)

**Comment by robohack** [comment]
something like this also just happened to me due to failed compilation during the upgrade from 2.1.0 to 2.2.0

In my case it happened even though completion worked on the repository name.

A full removal and clean re-install of 2.2.0 seems to have fixed it.

**Comment by vendethiel** [comment]
Hi,

I had the same issue when specifying a directory explicitly (like here), so I wiped out my `magit` directory (in case of miscompilation)

Now I get this error, trying to commit (when I hit enter)

```
There was a problem with the editor '/usr/local/Cellar/emacs/25.1/bin/emacsclient --socket-name=/var/folders/y3/v39p3kc96w9cv48g5g0x_hz00000gn/T/emacs501/server'. ... [Hit $ to see buffer *magit-process: mydir for details] [2 times]
```

This is from said buffer:

```
      1 git … commit --
      Waiting for Emacs...
      *ERROR*: Not inside a Git repository
      error: There was a problem with the editor '/usr/local/Cellar/emacs/25.1/bin/emacsclient --socket-name=/var/folders/y3/v39p3kc96w9cv48g5g0x_hz00000gn/T/emacs501/server'.
      Please supply the message using either -m or -F option.
```

I'm using spacemacs, btw, so if you think I should report the issue there, I'd do it. Or if you want me to open a separate issue, as this one was "fixed"?
