### ISSUE TITLE
Make commit sections expandable (show the diff inline)

### ISSUE THREAD

**Issue by jsyjr** [magit/magit#2138]
Currently it silently does nothing.

**Comment by kyleam** [comment]
Showing the commit is already covered by SPC and RET, so I don't see an
advantage of making TAB do something beyond toggling the visibility for
the section body, which may or may not exist.

**Comment by tarsius** [comment]
I agree with @kyleam.

**Comment by jsyjr** [comment]
I agree that there is already today a way to show commits from the Unpushed commits section.  That is not the point.  When I am grooming a list of commit before pushing they tend to be rather small edits.  I can see the title of each commit.  I am interested solely in reviewing the actual diff portions.  Often this diff is swamped by the prefix of the full commit display (all headers, message, refs, histogram, etc).  Further SPC and RET display the entire commit in a new window.  And, unlike expanding and collapsing sections in the dashboard, the commit window allows only a single commit to be visible at a time.

I just want to quickly see my diffs.  The most natural way would be one that is an obvious generalization of the behavior of TAB on an entry in Unstaged changes and Staged changes sections.  The visual presentation of the dashboard already encourages one to expect uniform behavior across various sections.

This is not a suggestion for an incompatible UI change.  I understand that at present it is in tension with performance issues within the current implementation.  But if diffs ever become lazily evaluated supporting this behavior for TAB in the Unpushed commits section would be a nice improvement that would lead to a more uniform UI.

**Comment by tarsius** [comment]
Okay I understand now what you mean. I *might* implement this at a later time.

**Comment by tarsius** [comment]
By the way, you can show the changes for the commit at point in the diff buffer by pressing `dd` (instead of `RET` which shows it in the revision buffer along with the metadata).

**Comment by jsyjr** [comment]
Thanks Jonas.  I get that it is merely polishing the UI and hence low priority.

**Comment by jsyjr** [comment]
I am not sure that I understand the dd suggestion.  AFAICS dd on an individual unpushed commit is identical to RET.  dd on the Unpushed commits section header does indeed display the total effect of all of the unpushed commits.  (I was unaware of that behavior so thanks for pointing it out.)

**Comment by kyleam** [comment]
magit-diff-dwim runs magit-show-commit, so the output is the same as RET.  Jonas might have been thinking of `dr RET`.

**Comment by tarsius** [comment]
Hm, indeed. @kyleam did you intentionally change this? Or did it work that way before your recent changes?

**Comment by tarsius** [comment]
In any case I think it should just show the diff.

**Comment by kyleam** [comment]
> Or did it work that way before your recent changes?

It worked that way before my changes.  

> In any case I think it should just show the diff.

I don't have strong feelings one way or the other, but since RET/SPC will already show the commit, I think that makes sense.

**Comment by tarsius** [comment]
Exactly my reasoning :-)

**Comment by tarsius** [comment]
@jsyjr What you are suggesting has been suggested before and I rejected it then. I cannot rule out 100% that I won't implement this eventually, but I have strong reservations. And therefore I think it is best I make this clear now instead of putting it on hold for a long time.

I like the status buffer and its here to stay (but I might make it easier to do things without having to use that buffer). But I don't think it is a good idea to cram ever more information into that buffer. I think it is perfectly okay if the only way to see the diff for a commit is to view it in a different buffer.

**Comment by jsyjr** [comment]
Hey Jonas.  Thanks for keep me apprised of your thinking.  I cannot say
strongly enough how impressed I am with the way that you are running this
project.  Magit has become my absolute #1 show off point when trying to
interest vim colleagues in emacs.  Keep up the good work.  And I hope that
you find the sort of employment you seek very soon.

/john

**Comment by tarsius** [comment]
Thanks a lot!
