### ISSUE TITLE
void-function magit-popup-import-file-args

### ISSUE THREAD

**Issue by Malabarba** [magit/magit#2139]
I get the following error whenever I type `D` at the status buffer.

    Debugger entered--Lisp error: (void-function magit-popup-import-file-args)
      magit-popup-import-file-args(("--no-ext-diff") nil)
      magit-diff-refresh-popup(nil)
      funcall-interactively(magit-diff-refresh-popup nil)
      call-interactively(magit-diff-refresh-popup nil nil)
      command-execute(magit-diff-refresh-popup)

I also get the following when I type `l l`:

    Debugger entered--Lisp error: (void-function magit-popup-export-file-args)
      magit-popup-export-file-args(("--graph" "--decorate"))
      magit-log-arguments()
      byte-code("\300\301!\302 B\207" [magit-log-read-revs t magit-log-arguments] 2)
      call-interactively(magit-log-current)
      magit-invoke-popup-action(108)
      funcall-interactively(magit-invoke-popup-action 108)
      call-interactively(magit-invoke-popup-action nil nil)
      command-execute(magit-invoke-popup-action)

**Comment by kyleam** [comment]
magit-popup-import-file-args was added in e34ba7e
("magit-popup-export-file-args: new function", 2015-07-30).  I'd guess
that things got into a confused state after you updated.

**Comment by Malabarba** [comment]
I think I see the problem. That function was added on the master branch, but is not released in a stable version yet. The version of `magit-popup` that I have installed is `2.1.0` (I didn't do that explicitly, it's just the version that got pulled in because Magit depends on it).

It might be best to tag new functionalities on a package as stable before making other packages depend on them. Either that or make the unstable Magit depend on the unstable version of magit-popup.

**Comment by glucas** [comment]
Hit the same problem. To me it makes sense to have the unstable magit depend on the corresponding unstable magit-popup, and keep the stable versions in sync.

**Comment by tarsius** [comment]
> It might be best to tag new functionalities on a package as stable before making other packages depend on them

Yeah, I intend to start doing that after we have released `2.2.0`.

**Comment by tarsius** [comment]
And that release should happen soon.
