### ISSUE TITLE
Arguments that someone suggested be added to some popup

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2141]
Every so often someone suggests that some argument (or action) be added to some popup. I do think there is some value in *not* following each and every of these suggestion, and concentrate on the arguments that many users would find useful.

It is very easy for a user to add a new argument to an existing popup. Almost as easy as adding a new key binding to a keymap. This is described in the manual: http://magit.vc/manual/magit-popup/Customizing-existing-popups.html.

But lets record what arguments are being suggested, so that we can add the ones that are being suggested over and over again:

* dispatch
  * [ ] reset +1 (here)
* log
  * [ ] --no-merge +1 (#2137)

**Comment by Wilfred** [comment]
It would be nice if the default popup showed `x`. Should I file a separate bug to propose this?

**Comment by tarsius** [comment]
No, that's not necessary.

**Comment by tarsius** [comment]
I am now tracking this on the wiki: https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands. That page also features code snippets.
