### ISSUE TITLE
No visible notification when rebase fails

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2142]
Hello,

no big thing, but quite irritating for new users:

Type r s in the log buffer, and suppose you have unstaged changes.  I get the message "(No buffers need to be reverted)" and think "ok, fine".  The I'm trying to figure out how to continue.  Just after a while I noticed that the rebase command had actually failed, and the "fail" message had been hidden by the following "revert" messages.  I think we need to make the fact that rebasing failed more visible.  Thanks!

**Comment by michael-heerdegen** [comment]
Version is current Melpa version btw.

**Comment by tarsius** [comment]
I believe there's a way to make a message "stick around", i.e. being displayed again after another message was displayed. I don't remember how to do that.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> I believe there's a way to make a message "stick around", i.e. being
> displayed again after another message was displayed. I don't remember
> how to do that.

There is "with-temp-message", but we probably can't use it in this case
(because the later messages are messages in a different part of the
code).  Anyway, all it does is to remember the current message and
message it again after the body had been run.  You can do this manually.

Personally, in such situation I often use something like

   (with-temp-message "Something bad happened!" (sit-for 3))

sometimes combined with "ding".

**Comment by tarsius** [comment]
Actually in this case we cannot do anything about it, but not for technical reasons.

The messages about buffers being reverted are being displayed for the benefit of the few users (I know of one) who use work flows where these reverts could lead to data loss. So the final "reverted buffers" message is the most important message, not the "failed to do what you asked me to do" message.

But for 99% of users the revert messages are quite relevant and they can turn them off by setting `magit-revert-buffers` to `silent`.
