### ISSUE TITLE
magit ediff confused when called via "magit-dispatch-popup"

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2143]
Hello,

I'm developing a single file package in Gnu Elpa.  I've a local clone of the Gnu Elpa archive, my file is under /home/micha/software/elpa/packages/el-search/el-search.el - at the right place for such a file.

As advertised in the Info manual, I did M-x magit-dispatch-popup e s RET.  But Ediff buffer C (which should show the current file version from the worktree) is empty.  It seems that magit gets confused about the command being called with a pwd other than the archive root: "buffer-file" of buffer C is
"/home/micha/software/elpa/packages/el-search/packages/el-search/el-search.el".

That does not happen the long way round via "magit-status".

BTW, It would be good when command "ediff-dwim" would work even as stand-alone command directly from the file buffer, i.e. even without "magit-dispatch-popup".

Thanks!

**Comment by michael-heerdegen** [comment]
Oh, again: My magit version is the current Melpa version.

**Comment by michael-heerdegen** [comment]
Thanks, that was fast.  I'll try it as soon as the Melpa version can be updated.

**Comment by kyleam** [comment]
Thanks for the report.

> It would be good when command "ediff-dwim" would work even as
> stand-alone command directly from the file buffer, i.e. even without
> "magit-dispatch-popup".

You should be able to call ediff-dwim (and all other magit-ediff
commands) directly, although it isn't particularly useful because it
doesn't currently guess a command when called from files, so it will end
up asking you for the command.

**Comment by michael-heerdegen** [comment]
Kyle Meyer <notifications@github.com> writes:

> Thanks for the report.

Magit has been updated on Melpa now.  I can confirm that the problem is
fixed now.

> You should be able to call ediff-dwim (and all other magit-ediff
> commands) directly, although it isn't particularly useful because it
> doesn't currently guess a command when called from files, so it will end
> up asking you for the command.

Yes, that's what it does, and is exactly what I prefer: a menu selection
with one key.

Thanks again for the quick fix!
