### ISSUE TITLE
magit-wip-after-apply-mode does not behave as documented

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2144]
Hi!

magit version is that from Melpa.

The info manual says that at least staging, unstaging, discarding, reversing, and regularly applying would fire wip-save with magit-wip-after-apply-mode on.  That's not true in my version: staging and unstaging don't cause wip-saving.  Calling "magit-wip-commit-after-apply" manually does what is expected.

It's easy to understand the current behavior by grepping for "magit-wip-commit-after-apply" in the sources.  Dunno whether the code or the manual must be corrected.

Thanks!

Michael.

**Comment by tarsius** [comment]
Probably the code should be changed. But I'll have to think about it a little more before I do so.

**Comment by michael-heerdegen** [comment]
Thanks!

**Comment by michael-heerdegen** [comment]
The mode (still) doesn't fire when updating the index after performing a "magit-ediff-stage".  I think it should.  I guess "magit-update-index" is the function to change.

**Comment by tarsius** [comment]
Fixes.
