### ISSUE TITLE
Remote urls and spaces

### ISSUE THREAD

**Issue by laynor** [magit/magit#2145]
Today I changed the remote of a repo using <kbd>M u</kbd>.
By mistake, i inserted a space before the usual git@server:repo url. This resulted the insertion of 

[remote "origin"]
     url = " git@xxxxxxx:yyyy.git"

in .git/config, which, in turn, made git behave "strange", asking the password of the user git (or was it actually ' git'?).

```lisp
(defun magit-remote-set-url (remote url)
  "Change the url of the remote named REMOTE to URL."
  (interactive
   (let  ((remote (magit-read-remote "Set url of remote")))
     (list remote (magit-read-string "Url" (magit-get "remote" remote "url"))))) 
  (magit-set url "remote" remote "url")) ;; trimming the whitespace in `remote'  would be nice!
```

**Comment by npostavs** [comment]
Is an extra space different from any random typo in the URL?

**Comment by laynor** [comment]
well, it's certainly easy to spot as opposed to any random typo. A user id starting with whitespace is certainly fishy.

**Comment by tarsius** [comment]
There are keymaps intended for the minibuffer which make it impossible to insert whitespace. But I don't know if there is a non-hacky way to make `completing-read` and friends use one of those instead of the default.

**Comment by laynor** [comment]
What's so bad about left trimming the remote URLs after the user inserts
them? Am I missing something?

**Comment by tarsius** [comment]
It's no longer possible to type whitespace at these prompts. But it's possible to yank whitespace. If you do that and don't fix it, then you get an error (no automatic trimming).
