### ISSUE TITLE
way to switch between different histories of given file?

### ISSUE THREAD

**Issue by blaenk** [magit/magit#2147]
When I read through the magit manual I vaguely remember seeing something about this, but now I can't find it. I'm new to emacs and something vim-fugitive had was the ability to cycle through the history of a file. I think the git-timemachine package enables something like this, but I would absolutely love it if I could use existing magit constructs to do this, especially because it seems (or perhaps I'm mistaken) that magit is most of the way there.

I found out about `magit-log-buffer-file` which opens a split window of the git log of commits that affected the current file. What I'm envisioning is the ability to enable some sort of 'follow mode' so that when I traversed this list it would automatically set the contents of the buffer to the version of the file at that commit. If no follow mode ability, then at least some way to set the buffer contents via a binding?

**Comment by tarsius** [comment]
This is not currently possible and I recommend you just use `git-timemachine` for now.

> but I would absolutely love it if I could use existing magit constructs to do this, especially because it seems (or perhaps I'm mistaken) that magit is most of the way there.

You are kinda mistaken. The current implementation is a bit of a hack (like those in vc and git-timemachine). I intend to implement a proper file-handler `git-handler.el` and not add any related functionality until I have done that.

**Comment by blaenk** [comment]
Thanks for the response. I meant in terms of UI mainly, with the log window opening underneath the file, since I'm not at all familiar with the implementation of magit.

I look forward to this! But in the meantime I'll go ahead and use git-timemachine then :)

**Comment by tarsius** [comment]
I have implemented basic blob navigation in #2195. This is merged into `pu` and will likely make it into `v2.3`.
