### ISSUE TITLE
magit-wip-after-save-mode doesn't work when set using setq

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2150]
Hi,

my Magit version is the current Melpa version.

The Magit info manual introduces "magit-wip-after-save-mode" as a user option.  However, setting the variable via "setq", e.g.  in the user's init file, doesn't have any effect.

The reason is simple: we define  "magit-wip-after-save-mode" with "define-globalized-minor-mode", so it's normal that setting the mode's variable doesn't have an effect - one must call the mode function to enable the thing.  OTOH setting via customize will work (since customize will us an appropriate setter).

I think the implementation we have is good and reasonable.  I would just change the doc and name the thing a "mode" instead of an "option".  Thanks!

**Comment by tarsius** [comment]
It *is* a user option. It's also a mode. Symbols ending with "-mode" are always modes. Modes should never be set using `setq`.

> I would just change the doc and name the thing a "mode" instead of an "option".

1. This is not easily possible, I would have to make changes to the ort->texi exporter and possibly also the texi->{info,...} exporters.
2. I want users to know that they can the Custom interface to enable this mode.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> It is a user option. It's also a mode. Symbols ending with "-mode" are always modes.
> Modes should never be set using setq.
>
>  I would just change the doc and name the thing a "mode" instead of an "option".
>
> 1 This is not easily possible, I would have to make changes to the ort->texi exporter
>  and possibly also the texi->{info,...} exporters. 
> 2 I want users to know that they can the Custom interface to enable this mode. 

Ok.  Maybe you could add something like the automatically created
docstring already says:

"Setting this variable directly does not take effect;
either customize it (see the info node ‘Easy Customization’)
or call the function ‘magit-wip-after-save-mode’."

maybe a bit shorter, e.g.

"Setting this variable directly does not take effect;
either customize it or call the function."

**Comment by tarsius** [comment]
I'll think about it.

**Comment by tarsius** [comment]
I've done it.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> I've done it.

Thanks.
