### ISSUE TITLE
Go back to previous window configuration after commiting

### ISSUE THREAD

**Issue by tuhdo** [magit/magit#2153]
Currently, after committing, Magit also closes `magit-status` buffer. This is inconvenient since I want to do more, and every time I finish a commit I have to open `magit-status` again for next commit. I just want Magit to keep previous window configuration before pressing `c c`.

**Comment by tarsius** [comment]
This shouldn't happen. Please try to reproduce without your configuration.

**Comment by tarsius** [comment]
Let me know if you can reproduce this with a clean configuration.

**Comment by tarsius** [comment]
Fixed in  #2197.
