### ISSUE TITLE
`magit-status' doesn't accept alternate directory names

### ISSUE THREAD

**Issue by seh** [magit/magit#2154]
If one calls `(magit-status "~/repo")` but `(expand-file-name "~/repo")` yields something different, such as "/Users/me/repo"), then Magit refuses to open a status buffer for that repository, and instead falls back to the default directory (`default-directory`).

This is due to `magit-status` demanding exact equivalence between the supplied path and the expanded path:
```lisp
(if (and toplevel (string-equal directory toplevel))
    (magit-status-internal directory)
```
What's the reason for being so strict here? My normal workflow is to type <kbd>C-u</kbd> <kbd>M-x</kbd> <kbd>magit-status</kbd> <kbd>RET</kbd> <kbd>~/some/path</kbd> <kbd>RET</kbd>, but Magit just ignores the supplied path because it's not already in the canonical form.

**Comment by tarsius** [comment]
> What's the reason for being so strict here?

Git doesn't understand the meaning of `~/`.

**Comment by tarsius** [comment]
> If one calls `(magit-status "~/repo")`

You probably only mention that for demonstration purposes, but note that this command is only intended for interactive use. Use `magit-status-internal` in code.

> Magit just ignores the supplied path because it's not already in the canonical form.

That's not true, the line right above the code you quoted does it:

```lisp
(setq directory (file-name-as-directory (expand-file-name directory)))
```

And what comes out of `magit-toplevel` also is in canonical form.

Another user had a similar issue recently: #2136. Maybe recompiling or even reinstalling solves your problem too.

**Comment by seh** [comment]
That's fine, but if I request Magit to open the repository at the path that _I_ call "~/", and that happens to expand to "/Users/me/", why won't magit use that expanded path? In other words, why can't it trust my request?

**Comment by seh** [comment]
I'll try restarting Emacs to see if that resolves the problem.

**Comment by tarsius** [comment]
> why won't magit use that expanded path?

For me it does, and looking at the code I think it should do it for you too.

So again: I don't think you are running the code you think you are running. Evaluate the definition of `magit-status` using `eval-defun` and then try again. If it now works, then something most be wrong with your installation.

**Comment by seh** [comment]
Well, restarting Emacs fixed the problem, so I apologize for the complaint.
Is there any way to get Emacs to start using the new code after running `package-list-packages` and installing the updates?

**Comment by tarsius** [comment]
Usually that's not required and when it is required, then there unfortunately is no way to do it. That's just how `package.el` is. The only thing you can do is to uninstall, restart, and only then reinstall. By the way, when you updated from <2 to >2 did you follow the update instructions and did the mentioned uninstall, restart, reinstall dance?

**Comment by seh** [comment]
I did not follow the instructions, as I never noticed them. One day `package-install-packages` offered a newer version that crossed the version 2 threshold. I typed <kbd>U</kbd> <kbd>x</kbd> without paying much attention.

I've restarted since then, but I try not to do so more than once per month.

**Comment by npostavs** [comment]
> Usually that's not required and when it is required, then there unfortunately is no way to do it.

In theory, I think [unloading] everything first could work:

```elisp
(dolist (feat features)
  (when (or (string-prefix-p "magit" (symbol-name feat))
            (memq feat '(git-rebase git-commit)))
    (unload-feature feat 'force)))
```

but some `magit-*-unload-function`s would have to be written to make it work right, and that's probably more trouble than it's worth.

[unloading]: http://www.gnu.org/software/emacs/manual/html_node/elisp/Unloading.html

**Comment by tarsius** [comment]
I am getting really sick of these issues that are the result of `package.el` creating tainted builds. I think we should ship a `Makefile` with the melpa and marmalade builds. Of course that might not work on MS Windows so we should probably ship `magit-q.sh` and `magit-q.bat` scripts instead of a Makefile. What ever language we use it should support recompiling and `emacs -Q -L ... -l magit` (also in a "only use the source files" variant).

**Comment by vanicat** [comment]
May be a solution would be to wrote the build script in Emacs lisp, to easily have it on every platform.
