### ISSUE TITLE
Intrusive overwrites of default keybindings

### ISSUE THREAD

**Issue by jaroslawr** [magit/magit#2159]
The behaviour in 2.1.0 of overwriting M-w and basically disabling the posibility to copy raw text from magit buffers is very unintuitive and intrusive. Personally I think it would be better to use other key binding for this "intelligent" copying, and leave M-w like it is in any other Emacs buffer. At the very least, I think there should be an option to easily disable intrusive changes of defaults of this type. Emacs is a text editor, after all ;)

**Comment by npostavs** [comment]
> basically disabling the posibility to copy raw text from magit buffers

Copying the text works if region is active, see #1958 for previous discussion.

**Comment by tarsius** [comment]
> At the very least,

This is the one baned phrase because for me it is a trigger phrase which causes my willingness to have a conversation approach zero. See https://github.com/magit/magit/blob/master/CONTRIBUTING.md.

> basically disabling the posibility to copy raw text

This is not true for versions *past* 2.1.0, i.e. what you get from Melpa.

**Comment by jaroslawr** [comment]
@npostavs @tarsius Thanks!
