### ISSUE TITLE
"renamed: old -> new" shows as "New" plus "Deleted"

### ISSUE THREAD

**Issue by drews** [magit/magit#216]
Using `git status` I receive a message like:

>   renamed:            old_name -> new_name

From the magit status buffer:

>  Staged changes:
>         New new_name
>         Deleted old_name

It would be nice if magit could notice the single rename instead of two separate line items.

**Comment by blaenk** [comment]
What ever happened to rename detection in magit-status? I'm referring to what the OP says, that a rename shows up as a delete and an add (which is technically correct I guess), whereas git status can detect that it's a rename taking place.

It's kind of difficult to follow the thread of issues. [This comment](https://github.com/magit/magit/issues/1280#issuecomment-38389710) seems to show that it was never merged into master?

**Comment by npostavs** [comment]
> What ever happened to rename detection in magit-status?

You can enable it with `D =M RET g`, I guess it's off by default for performance reasons?

**Comment by blaenk** [comment]
Ah thanks! And if I want it to be the default then I just do `C-x C-s` AFAIK. Yeah I wonder why it's off, I do imagine performance reasons. Perhaps @tarsius could tell us?

**Comment by tarsius** [comment]
Yes, it's off for performance reasons.
