### ISSUE TITLE
Moving through magit-log-mode often shows improper revision in magit-revision-mode

### ISSUE THREAD

**Issue by bsuh** [magit/magit#2161]
Using 'n' and 'p' keys repeated in quick succession to move through commits in magit-log-mode and then stopping on a certain commit, the revision that shows up in magit-revision-mode is often not the one where you've stopped. After getting to the commit I have to 'Ctrl-n' and 'p' to reset magit-revision-mode.

From a black box perspective, it seems magit is asynchronous now fetching the revision details, but doesn't cancel any previous git commands for fetching revision details when sending off multiple commands, and accepts the first response.

**Comment by npostavs** [comment]
> After getting to the commit I have to 'Ctrl-n' and 'p' to reset magit-revision-mode.

SPC should work too.

**Comment by kyleam** [comment]
@tarsius 405f64d What about ignoring the commit value when the timer is set and instead using the current value when the timer runs out?

**Comment by tarsius** [comment]
That makes sense. Please install your commit.

**Comment by bsuh** [comment]
Wow. Transitioning to magit 2.0 has been rocky, but it's great to see such bugs being fixed so quickly! Thanks, magit team :+1:
