### ISSUE TITLE
magit-show-refs extremely slow

### ISSUE THREAD

**Issue by ndimiduk** [magit/magit#2162]
In comparison to magit 1.x, the 2.x magit-refs (replacement for branch manager, yes?) is quite slow. My usual use-case is (1) list local branches, (2) switch local branches (3) delete local branches after they've been merged (4) create a new local branch from upstream. For instance, hitting 'g' on this screen causes a very long pause, as does creating a new local branch from upstream.

Sorry this is vague, let me know how I can help quantify/diagnose my experience.

Emacs 24.5 (9.0)
magit 2.1.0 (I think from marmalade, but I can't actually tell)
git 1.9.5 (Apple Git-50.3)

**Comment by tarsius** [comment]
How many refs are being displayed? It sounds like you are not interested in seeing the tags, so edit `magit-refs-sections-hook` accordingly.

**Comment by ndimiduk** [comment]
31 local branches; 4 remotes with 46, 45, 146, and 13 branches; and 499 tags.

**Comment by tarsius** [comment]
So ... is not showing those 499 tags good enough?

**Comment by tarsius** [comment]
Also do all those remote branches actually still exist on the remotes? If not then you can get ride of them using `f-pa`.

**Comment by oldhaapi** [comment]
Ah, thanks. Removingmagit-insert-tags from the Refs Section hook greatly sped things up in my environment.

**Comment by tarsius** [comment]
I have added a note about this to the manual (will be pushed in an hour or so).

**Comment by ndimiduk** [comment]
Excluding tags does help immensely. Would it be helpful to get some profile information about where time is spent with default settings?

**Comment by tarsius** [comment]
Might be helpful yes. (That would help in case it's not just the mere number of tags but `magit-insert-tags` is somehow less efficient than the related functions that insert branches.) So yes please, use `profiler` and report the results.
