### ISSUE TITLE
Manually edit hunk.

### ISSUE THREAD

**Issue by lethjakman** [magit/magit#2165]
I may be missing the feature, but it'd be really nice to be able to manually edit a hunk before staging it. Fox example when you git add --patch and press the "e" key on a hunk you can manually toggle which lines are being added.

**Comment by npostavs** [comment]
http://magit.vc/manual/magit/Staging-and-unstaging.html should cover it.

**Comment by lethjakman** [comment]
Unless I'm misunderstanding something this isn't what I'm talking about. I want to stage smaller hunks than "s" will allow me to. Sometimes "-" won't break up a hunk to a small enough chunk of code and I need to enter the "manually edit hunk" mode which allows me full control over what I'm staging. Is that possible?

**Comment by madscientist** [comment]
You mean, smaller than a single line?  Using "-" often enough gets you down to each line being a separate hunk.  Also, note this from the documentation: _To operate on just parts of a hunk, mark the changes that should be un-/staged using the region and then press the same key that would be used to un-/stage._  If this still isn't enough maybe you can give a more concrete example of what you're trying to do.

**Comment by lethjakman** [comment]
With my experience no matter how many times I press - it's not down to a single line. For example in the following screenshot I may want to commit the first two functions but not the last one. That is after pressing the - key until it isn't doing anything anymore. 

![screen shot 2015-08-14 at 8 00 48 am](https://cloud.githubusercontent.com/assets/2230555/9275493/aa80d580-425a-11e5-97de-e8ff1edd3031.png)

**Comment by npostavs** [comment]
> To operate on just parts of a hunk, mark the changes that should be un-/staged using the region and then press the same key that would be used to un-/stage.

"mark the changes" means press `C-SPC` on the `(defun my-setup-indent (n)` line and then move point down to just before `(my-office-code-style)` line.

**Comment by tarsius** [comment]
Showing less context lines (lines that are the same before and after the change) won't make a difference in places where there are no context lines (inside a region of added and/or removed lines).

What you want to do here is to stage a *region* which contains just the lines you want to stage. To mark a block of text as  the region you first press `C-x SPC` and then you move to the other end of the block. Now you have a region. Then you press `s` to stage the region.

This is explained in the manual node @npostavs pointed you to:

> To operate on just parts of a hunk, mark the changes that should be un-/staged using the region and then press the same key that would be used to un-/stage.

Of course that assumes that you know what "the region" is. Just in case you don't I have provided an example above. But if you really don't know about the region, then you should learn about it, by reading the respective node in the "Emacs" manual.

**Comment by lethjakman** [comment]
Ok, maybe this is why I'm confused. I tried that thinking that I'd be able to stage a region, but when I try to move down over that region it just skips all the way down over that region highlighting the whole thing. Then when I press s I get  a message that "(No files need saving)" I've tried both C-SPC and C-x SPC and neither will allow me to stage sections. However it does look like I can select these regions with my mouse. Strange.

**Comment by tarsius** [comment]
Instead of moving by section (`n`, `p`) you should move by line (`C-n`, `C-p`).

**Comment by vanicat** [comment]
I see a point to be able to do edit the file that will be committed when git's diff misunderstood how change are made. For example:

    -def walk(path):
    -    for subdir, dirs, files in os.walk(path):
    +def walk_free(path):
           if ".git" in dirs:
               dirs.remove(".git")

Imagine I want to commit the changed  function name, but not the removed line. Even when using region to stage only the `-def walk(path):` and `+def walk_free(path):` lines, the commit will be incorrect because the modified line is added after the first line of the function. The only way I know to solve this is to stage the change, remove the change one do not want to commit, then stage and commit, the bring back the other change. Such possibility would be awesome, but at best of my knowledge, is not easily doable with the command line. It would be an awesome amelioration of magit.

**Comment by kyleam** [comment]
> Such possibility would be awesome, but at best of my knowledge, is not
> easily doable with the command line.

Hmm, I like the "e - manually edit the current hunk" interface available
from 'git add -p'.  I think the ability to edit an unstaged hunk in
magit would be a neat feature (reminds me of Wdired).

**Comment by tarsius** [comment]
Please open a new issue for that.

**Comment by lethjakman** [comment]
Ahhh, that certainly helps a lot! That's pretty much what I was looking for, however I wouldn't mind the e interface as well. Thank you!
