### ISSUE TITLE
Making Magit part of Emacs

### ISSUE THREAD

**Issue by pajatopmr** [magit/magit#2166]
Would the Magit maintainers/developers be inclined to make Magit a part of standard Emacs if the Emacs maintainers reached out to make this request?  The advantage would be eliminating all installation friction to using Magit.  A second order question, assuming the basic concept has merit, would be to determine if dependencies, like Dash, can be eliminated.

**Comment by tarsius** [comment]
This has been suggested before and while I am open to the idea (but not sold on it) my answer still is the same as before: I don't have the time to do this now. Past conversations have shown that the Emacs maintainers would be interested in making it a GNU project and adding it th GNU Elpa, but not so much in making it a part of Emacs itself. Even just turning it into a GNU project would be a lot of work, and as far as I can tell the only benefit of that would be that it then would be a GNU project.

I think it would be much better to abstract parts of Magit and then make them part of Emacs (or just GNU Elpa) one by one.

So no, I am not currently interested in working on this.
