### ISSUE TITLE
Won't install on emacs 24.3.1 from melpa

### ISSUE THREAD

**Issue by jackcviers** [magit/magit#2169]
Emacs --version is 24.3.1

Error is `Package `emacs-24.4 is unavailable`

**Comment by xuchunyang** [comment]
http://magit.vc/manual/magit/I-am-using-an-Emacs-release-older-than-244.html#I-am-using-an-Emacs-release-older-than-244

**Comment by jackcviers** [comment]
Wow. So it not only requires a source install of emacs but also git!

Do you know what the last available version was for <24.4?

**Comment by tarsius** [comment]
Use `1.4.2`.
