### ISSUE TITLE
"magit-wip-save is an alias for `magit-wip-save', which is not defined."

### ISSUE THREAD

**Issue by Peeja** [magit/magit#2170]
From `magit-status`, I press <kbd>z ? r</kbd> and get a help buffer which says,

> magit-wip-save is an alias for `magit-wip-save', which is not defined.  Please make a bug report.

Here it is.

**Comment by tarsius** [comment]
I have pushed a fix. The command is now named `magit-wip-commit`.

Thanks.

**Comment by Peeja** [comment]
:beers:
