### ISSUE TITLE
Support patch editing for staging

### ISSUE THREAD

**Issue by kyleam** [magit/magit#2173]
This stemmed from a comment by @vanicat in #2165.  

@vanicat:

I see a point to be able to do edit the file that will be committed when git's diff misunderstood how change are made. For example:

```diff
-def walk(path):
-    for subdir, dirs, files in os.walk(path):
+def walk_free(path):
       if ".git" in dirs:
           dirs.remove(".git")
```

Imagine I want to commit the changed function name, but not the removed line. Even when using region to stage only the `-def walk(path):` and `+def walk_free(path):` lines, the commit will be incorrect because the modified line is added after the first line of the function. The only way I know to solve this is to stage the change, remove the change one do not want to commit, then stage and commit, the bring back the other change. Such possibility would be awesome, but at best of my knowledge, is not easily doable with the command line. It would be an awesome amelioration of magit.

@kyleam:

> Such possibility would be awesome, but at best of my knowledge, is not
> easily doable with the command line.

Hmm, I like the "e - manually edit the current hunk" interface available
from 'git add -p'.  I think the ability to edit an unstaged hunk in
magit would be a neat feature (reminds me of Wdired).

**Comment by kyleam** [comment]
This is of course just for discussion and not a suggestion that users do
this, but you can stage the intended change in the above example in a
very unsupported way:

* C-x C-q
* C-x C-t (with point on walk_free line)
* C-x C-q
- Stage the function name change.

**Comment by kyleam** [comment]
Thinking about this a bit more, I'm not sure there are very many cases
where you'd want to move more than a single line around.  (Examples
where moving a single line wouldn't do would be very helpful.)  Most
of the actions possible with 'git add -e', like deleting + lines or
s/-/ / don't make too much sense in the context of a magit hunk, where
you can easily stage the lines you want and leave the rest.

So I think we could just make a wrapper around transpose-lines for
unstaged hunk regions.  While this wouldn't support undo, it's easy
enough to manually refresh the buffer to get back to the original
state.  If the patch gets into a state that won't apply, trying to
apply it will error in the process buffer and revert the status
buffer.

**Comment by vanicat** [comment]
There is a case I had several time is when closing TODO in org files and at the same time correcting the heading: the closing and the correcting should be in different commit:

```diff
-* TODO go to debnf
+* DONE go to debconf
```
It would be interesting to be able to add and commit:
```diff
-* TODO go to debnf
+* TODO go to debconf
```
commit and then add and commit:
```diff
-* TODO go to debconf
+* DONE go to debconf
```
But as `magit-ediff-dwim` solve this, the simpler solution to only allow transpose-lines may be enough.

**Comment by tarsius** [comment]
> the simpler solution to only allow transpose-lines may be enough.

I don't think it's a good idea to only support one particular use-case, even if that should really cover the majority of all cases. If we add such a feature then we will inevitably get requests for a generic solution, so me might as well do that from the start.

And actually that already exists, as you have mentioned. Maybe we just need to advertise that Ediff can be used for this purpose.

**Comment by tarsius** [comment]
We could also add an "edit this hunk" command which would show the hunk at point in a special editable diff buffer. The user could then edit that buffer and use the appropriate apply variant when done. (We could also make `C-c C-c` and `C-c C-k` do the expected thing in that buffer.)

Or we could add a command (likely a mode) which would make the diffs in any buffer editable. This should be done in a way that only allows editing the body of hunks, but anything else should remain read-only. Doing that properly could be difficult.

Another issue would be that if the buffer is refreshed (not necessarily explicitly), then all edits would be lost. Maybe we should refuse to refresh the buffer when it has been edited. But it would probably be quite difficult to detect that only one hunk has been edited, the user just applied that, and we therefore should no longer consider the buffer to be modified.

I fear that implementing this would make the existing code more complicated and would therefore make the changes I am planning (mostly for speed) more difficult. So I think we should delay this for quite some time.

**Comment by kyleam** [comment]
That all sounds reasonable to me.  It's interesting to consider other
interfaces, but magit-ediff-stage does already make these things
possible.

**Comment by tarsius** [comment]
I have added a note about this to the manual.

Since we are not going to implement something else anytime soon, or ever, I am closing this. But feel free to discuss more and if someone comes up with a nice implementation, then I won't oppose that.
