### ISSUE TITLE
rebase section of manual incomplete / inconsistent

### ISSUE THREAD

**Issue by aspiers** [magit/magit#2174]
The popup menu describes `r o` as "Rebase subset" but the manual describes it as `magit-rebase-from`.

Also the manual doesn't describe `r l` ("Rebase unpushed").

**Comment by tarsius** [comment]
> The popup menu describes `r o` as "Rebase subset" but the manual describes it as `magit-rebase-from`.

These things don't *have to* match, but I suppose if they don't then that could be confusing. Also see #1862.

> Also the manual doesn't describe `r l` ("Rebase unpushed").

It does now.
