### ISSUE TITLE
Cannot open commit popup on Linux

### ISSUE THREAD

**Issue by Goobley** [magit/magit#2176]
Hi, I use the same config for emacs on mac and Linux (with the exception of fonts). Today I removed my elpa folder to force all my plugins to be updated on Linux and now when I press `c` in magit-status I get the following error:
`magit-commit-popup: Wrong type argument: symbolp, (quote magit-commit-arguments)`
and here is the backtrace:
```
Debugger entered--Lisp error: (wrong-type-argument symbolp (quote magit-commit-arguments))
  magit-invoke-popup(magit-commit-popup nil nil)
  magit-commit-popup(nil)
  call-interactively(magit-commit-popup nil nil)
  command-execute(magit-commit-popup)
```

Versions: `Magit 20150815.800, Git 2.1.4, Emacs 24.4.1`, `emacs` and `git` installed by `apt-get` and magit installed via `elpa`.

I can however still use the magit commands separately by calling `magit-commit` and rebase functionality is also working fine. 
Any thoughts?

**Comment by kyleam** [comment]
Unfortunately, the MELPA build must have included
fdefb34fd8f97cd845ca8243f104d13e5e7b2ca9, but not the fix that followed
it (3109b70e40374492456cac6393b3e00fa2a7345b).  This should be fixed
with the next build.

**Comment by Goobley** [comment]
Okay, thanks for the rapid response, I'll leave this open for a day or 
so and close it if it's just resolved by an easy update - it's not 
causing me any major trouble.

**Comment by tarsius** [comment]
The current snapshot has the fix.
