### ISSUE TITLE
upgrading from 2.1.0 to 2.2.0 with the package manager gives compilation error

### ISSUE THREAD

**Issue by robohack** [magit/magit#2182]
Upgrading today from 2.1.0 to 2.2.0 in emacs-24.5 (via the package manager) resulted in the following error during compilation:

    magit-diff.el:1389:1:Error: (magit-section-diff-header section) is not a valid place expression

There are also many many many warnings about functions being called with the wrong number of arguments (both the "called with N, but only accepts X" and "used to take N, now takes X" forms), all referring to `magit-` functions.

Also this:

    In end of data:
    magit.el:2325:1:Warning: the following functions are not known to be defined: magit-changed-files,
        magit-read-string-ns

Perhaps these are all due to the fact magit modules were already loaded into the emacs instance doing the compilation?  If so then I suppose this is really about a bug with the package manager and the only current solution would be to install magit "manually" such that separate `emacs -q -no-site-file -batch` processes are used to compile it.

**Comment by tarsius** [comment]
Actually, starting with v2.2.0 Magit depends on the `async` package to prevent exactly those kind of errors. See the top bullet point in the [release notes](https://raw.githubusercontent.com/magit/magit/master/Documentation/RelNotes/2.2.0.txt).

* Did `async` get installed?
* Is `async-bytecomp-package-mode` enabled?
* Are you using Melpa-Stable or Marmalade?
* Are you using Spacemacs?

**Comment by robohack** [comment]
yes, async-1.4 was installed (presumably when I first installed 2.1.0, though I don't remember explicitly).

    async-bytecomp-allowed-packages is a variable defined in `async-bytecomp.el'.
    Its value is (async helm helm-core helm-ls-git helm-ls-hg magit)

I'm using the marmalade repo.

I don't think I even know what spacemacs is, so I doubt it.  (it's not mentioned in my *Packages* buffer either)

I should note that the only way I got 2.1.0 working cleanly the other day was also to first carefully remove magit and all traces, then restart emacs.  After doing that it did install cleanly and work well.

Another complete and careful removal of all magit and magit-related packages, restart of emacs, and re-install of just the "magit-2.2.0" package seems to have worked.  (though in reality I went through several iterations before getting everything removed and learning to just try the "magit" package alone first)

I now find though that 2.2.0 is incompatible with org-magit (0.2.2) and magit-find-file (1.0.4) (both from marmalade).  I get some wrong type error during their installation, and any attempt to install them in parallel with the main "magit" package causes the same failure.

**Comment by npostavs** [comment]
> yes, async-1.4 was installed (presumably when I first installed 2.1.0, though I don't remember explicitly).

The dependency was only added in 2.2.0, so you probably didn't get it when installing 2.1.0. Therefore, it's not going to help the 2.1.0 -> 2.2.0 upgrade, i.e the problem is fixed, but not fixed retroactively. It should prevent recurrence for future upgrades starting from 2.2.0 though.

**Comment by robohack** [comment]
I should look more closely at the package manager myself, but I wonder if there's some way to have it un-install and force a restart before re-installing -- or alternately write an explicit "upgrade" package that will do the right thing using async-bytecompile.....  I suspect such a feature would be applicable to many other packages as time goes one.

**Comment by tarsius** [comment]
> I now find though that 2.2.0 is incompatible with org-magit (0.2.2) and magit-find-file (1.0.4) (both from marmalade).

`org-magit` is deprecated. Instead use `orgit`. They use incompatible link formats so you might want to stick to `org-magit` anyway. `org-magit` has been made compatible with magit v2 a while ago, but I have only now created a tag. `magit-find-file` has also been adjusted to work with magit v2.

Only the "owner" of a package can upload a release to Marmalade. I don't know who the "owners" of these packages are on Marmalade, and I don't think there is any way to figure it out except for asking @nicferrier. But I do suspect that the owners of these particular packages are @sigma and @bradleywright.
