### ISSUE TITLE
Process error after reversing changes: 'fatal: cannot describe '6b4fd44...'

### ISSUE THREAD

**Issue by miabrahams** [magit/magit#2183]
In Windows I get a recurring error after reverse blob commands.  The SHA refers to HEAD.

      0 c:/Program Files (x86)/Git/bin/git.exe … apply --reverse -p0 --ignore-space-change -
    128 c:/Program Files (x86)/Git/bin/git.exe … describe --contains 6b5fd44b4125914339479ff578f7bbe605b6ae23
    fatal: cannot describe '6b5fd44b4125914339479ff578f7bbe605b6ae23'

Occasionally Emacs hangs at these times, and the top of my backtrace stack is `magit-process-wait()`

**Comment by kyleam** [comment]
> In Windows I get a recurring error after reverse blob commands.  The
> SHA refers to HEAD.
>
>       0 c:/Program Files (x86)/Git/bin/git.exe … apply --reverse -p0 --ignore-space-change -
>     128 c:/Program Files (x86)/Git/bin/git.exe … describe --contains 6b5fd44b4125914339479ff578f7bbe605b6ae23
>     fatal: cannot describe '6b5fd44b4125914339479ff578f7bbe605b6ae23'

There is only one place in the current code that calls
'git describe --contains' (the function magit-get-next-tag).  When the
that git command doesn't contain any standard output (i.e., no tagged
commits come after HEAD), magit-get-next-tag returns nil.  You shouldn't
see stderr (as above) in the process buffer unless you have set
magit-git-debug.

Nothing in the process buffer output you show indicates an issue with
Magit, assuming you have magit-git-debug set to a non-nil (which is just
intended for debugging purposes).

> Occasionally Emacs hangs at these times, and the top of my backtrace
> stack is `magit-process-wait()`

I'd guess that the describe error above does not contribute to this.

**Comment by tarsius** [comment]
I would expect 80aea7a6f1daf485337116f615640bcc7090190a takes care of this. If not, then let us know and provide additional information to help us narrow down the issue.

**Comment by kyleam** [comment]
> I would expect 80aea7a6f1daf485337116f615640bcc7090190a takes care of this.

Just to clarify: Looking into this issue, I spotted the problem fixed in
80aea7a, but it isn't relevant for this issue.  Assuming that
magit-git-debug is non-nil, the 'git describe' error that is showing up
in the process buffer is expected, so there really is nothing to fix
with respect to that.
