### ISSUE TITLE
Ability to check out a version of a file from a different rev

### ISSUE THREAD

**Issue by emosesSfdc** [magit/magit#2184]
I've got a file foo.txt in branch A, and I want to check out foo.txt from branch B into the index (and working tree). On the command line, I would do this:

    $ git checkout B -- foo.txt

I want to be able to do this in magit by going to log, finding the commit I'm interested in (e.g `l o B`), finding foo.txt, and running some command.

**Comment by kyleam** [comment]
For others:
http://emacs.stackexchange.com/questions/14463/how-do-i-checkout-a-file-from-another-commit-in-magit/14464

**Comment by emosesSfdc** [comment]
Thanks, wasn't sure whether to link that here or not.

**Comment by tarsius** [comment]
@kyleam Feel free to add a command similar to the one on SE. If this doesn't affect anything else, then you can add directly on `master`.

I think the *checkout* variant is more useful than *reset*, so you should probably make that the default. Or maybe add two commands.

If you add keybindings, then it would probably better to do this on a feature branch.

**Comment by kyleam** [comment]
Sounds good.  I'll have a look at it later today, but I'm leaning
towards just adding a magit-checkout-file command without any binding or
reset variant.  This would offer good defaults in the revision mode
buffer, so M-x magit-checkout-file (or whatever binding is chosen by the
user) followed by RET RET will checkout the file at point for the
revision.

**Comment by kyleam** [comment]
OK, I've pushed a magit-checkout-file command to the km/checkout-file
branch.  I pushed there instead of master mainly because I'm unsure if I
picked the best place to document it in the manual.  (I put it in the
resetting section because I think it belongs with those commands in
spirit despite its name.)

@emosesSfdc Calling magit-checkout-file followed by RET RET when on a
file in the revision buffer will checkout the file from that revision.

**Comment by emosesSfdc** [comment]
Awesome, thanks a lot.

On Wed, Aug 19, 2015 at 5:06 PM, Kyle Meyer <notifications@github.com>
wrote:

> OK, I've pushed a magit-checkout-file command to the km/checkout-file
> branch. I pushed there instead of master mainly because I'm unsure if I
> picked the best place to document it in the manual. (I put it in the
> resetting section because I think it belongs with those commands in
> spirit despite its name.)
>
> @emosesSfdc Calling magit-checkout-file followed by RET RET when on a
> file in the revision buffer will checkout the file from that revision.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magit/magit/issues/2184#issuecomment-132830279>.
>



-- 
Evan Moses
emoses@salesforce.com

**Comment by tarsius** [comment]
Also merged into `pu`.
