### ISSUE TITLE
log buffer is missing several commits

### ISSUE THREAD

**Issue by pbostrom** [magit/magit#2185]
I noticed that the log buffer is missing several of my commits. Here is a screenshot of magit-log:
<img width="122" alt="screen shot 2015-08-18 at 4 46 53 pm" src="https://cloud.githubusercontent.com/assets/1334481/9342429/92bf360e-45c9-11e5-8be0-a9bc1f574e4a.png">

Here is the same repo/branch logged from the command line with `git log --pretty=oneline`
<img width="320" alt="screen shot 2015-08-18 at 4 52 25 pm" src="https://cloud.githubusercontent.com/assets/1334481/9342476/e19c84ca-45c9-11e5-8546-f3beccb0200e.png">

You'll notice there are 4 commits not shown in the magit-log buffer.
Sorry, this repo is private. I can try to recreate in a public repo if that would help.

**Comment by kyleam** [comment]
Are you sure you're not limiting the log in any way (by files,
message/patch search, author...)?  The log popup will indicate if this
is the case (as of v2.2.0, switches and options now stick around between
log popup calls in the same repo if that log buffer still exists).

> Sorry, this repo is private. I can try to recreate in a public repo if
> that would help.

Yes, please try to find an example of this in the magit repo or some
other public repo.

**Comment by pbostrom** [comment]
Oops, sorry, I just realized magit's default is to show the commit graph while the command line `git log` does not show the graph by default.
