### ISSUE TITLE
Two little issues with blaming

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2188]
Hi,

Magit version is the current Melpa one.

(1)  The manual (info "(magit) Blaming") says:

    ‘M-x magit-blame-popup’     (‘magit-blame-popup’)
    
         By default this behaves just like ‘magit-blame’.  With a prefix
         argument instead show a popup buffer featuring a few infix
         arguments and a single suffix command (‘magit-blame’).

AFAIK this is outdated.  The default is to show a popup buffer, and the behavior when using a prefix arg depends on `magit-popup-use-prefix-argument`.

(2)  When blaming a file takes long, a user might kill the buffer instead of hitting q.  In this case, the hell breaks loose and you are flooded with

    error in process sentinel: selecting deleted buffer

errors.  Sometimes only kill -9 helped.  It would be better handle the case of the buffer having been killed.

Thanks.

**Comment by tarsius** [comment]
I have updated the documentation and added a kludge to abort when the buffer was killed. You still get more than one error, but the process, filter, and sentinel are put out of their misery fairly quickly:

```
Running git blame --incremental -w -L 1,60 -- lisp/magit.el [2 times]
error in process filter: if: Buffer being blamed has been killed
error in process filter: Buffer being blamed has been killed
Git failed ... [See buffer *magit-process: ~/.emacs.d/lib/magit/* for details]
error in process sentinel: if: Process git is not active
error in process sentinel: Process git is not active
```

(no more messages after that)

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> Running git blame --incremental -w -L 1,60 -- lisp/magit.el [2 times]
> error in process filter: if: Buffer being blamed has been killed
> error in process filter: Buffer being blamed has been killed
> Git failed ... [See buffer *magit-process: ~/.emacs.d/lib/magit/* for details]
> error in process sentinel: if: Process git is not active
> error in process sentinel: Process git is not active
>
>
> (no more messages after that)

That's probably good enough.  Many thanks!
