### ISSUE TITLE
Something like `vc-region-history`?

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2189]
Hello,

Is it possible to integrate something like `vc-region-history` into magit - presumably within the log popup?  Or does it already exist and I missed it, though I have read the manual?

This feature would be especially useful with `magit-wip-after-save-mode`.  I hacked `vc-region-history` to work with Magit's wip saves like this:

```
(defvar my-vc-git-region-history--branch nil)

(defun my-vc-git-region-history (file buffer lfrom lto)
  (apply #'vc-git-command
         `(,buffer async nil "log"
                   ,@`(,my-vc-git-region-history--branch)
                   "-p"
                   ,(format "-L%d,%d:%s" lfrom lto (file-relative-name file)))))

(advice-add #'vc-git-region-history :override #'my-vc-git-region-history)

(defun my-vc-annotate ()
  (interactive)
  (if (region-active-p)
      (let ((my-vc-git-region-history--branch (when current-prefix-arg
                                                "refs/wip/wtree/refs/heads/master")))
        (call-interactively #'vc-region-history))
    (call-interactively #'vc-annotate)))
```

I can use this to find all auto saves that include changes to a specific region.  This is very handy if you find out that a dismissed idea you had implemented but removed later was not so bad at all and want to have the code back - in the ideal case by just hitting  "a".

Thanks.

**Comment by tarsius** [comment]
See #1717.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> See #1717.

Ah, thanks.  Just added a short note there.
