### ISSUE TITLE
stash (z z) is super slow

### ISSUE THREAD

**Issue by vjohansen** [magit/magit#2190]
Magit 20150816.1106, Git 1.9.5.msysgit.1, Emacs 24.4.1
Windows 7 

z z RET sdf RET

takes 90 seconds

: stash RET

takes 2 seconds

magit seems to be running a cryptic command for a long time:

![image](https://cloud.githubusercontent.com/assets/634765/9360331/f1c568a4-4695-11e5-8235-e047177a4f45.png)

**Comment by tarsius** [comment]
See #2049.
