### ISSUE TITLE
magit does not recognize git 2.5 linked worktrees

### ISSUE THREAD

**Issue by thkoch2001** [magit/magit#2196]
Git 2.5 adds the new [worktree](https://git-scm.com/docs/git-worktree) command. In those linked worktrees there is no `.git` folder but a file with that name. Magit does not seem to recognize such worktrees as git repositories. `magit-status` instead asks me whether I want to create a new git repository in such a folder.

**Comment by tarsius** [comment]
Support for `.git` files has existed for a long time. Submodules by default also use such a file and I have been using that without any problems whatsoever. `v2` for sure supports this and `v1.4` too I think. Are you still using `v1.2`?!

**Comment by thkoch2001** [comment]
I tried again now and can't reproduce. Sorry for the noise.
