### ISSUE TITLE
magit doesn't return to magit-status buffer after commit

### ISSUE THREAD

**Issue by Bronsa** [magit/magit#2197]
This happens more or less randomly, sometimes it will, sometimes it will return to the buffer I invoked magit-status from.

I'm using magit 2.2.0 with emacs 24.5

**Comment by Bronsa** [comment]
Looks like this was already reported as #2153

**Comment by tarsius** [comment]
Maybe *you* can narrow it down. I have never seen this, so that would be the only way to get me to fix it. (Start with `emacs -Q`.)

**Comment by Bronsa** [comment]
@tarsius I was only able to reproduce this using emacsclient, here are the steps:
```
[~]> cat .emacs.d/init.el
(add-to-list 'load-path "/home/bronsa/src/emacs.d/lib/magit/lisp")
(add-lib-path "/home/bronsa/src/emacs.d/lib/dash")
(require 'magit)
[~]> mkdir test
[~]> cd test
[~/test]> git init
Initialized empty Git repository in /home/bronsa/test/.git/
[~/test]> touch foo
[~/test]> EDITOR="" emacsclient -c -nw foo
emacsclient: can't find socket; have you started the server?
To start the server in Emacs, type "M-x server-start".

Warning: due to a long standing Gtk+ bug
http://bugzilla.gnome.org/show_bug.cgi?id=85715
Emacs might crash when run in daemon mode and the X11 connection is unexpectedly lost.
Using an Emacs configured with --with-x-toolkit=lucid does not have this problem.
Starting Emacs daemon.
Emacs daemon should have started, trying to connect again
```
once inside emacs:
```
(typed foo)
C-x C-s
M-x magit-status
(scrolled to foo)
s
c c
(typed foo)
C-c C-c
```
and I found myself with two frames pointing at the `foo` buffer rather than a `foo` buffer and a `*magit: ~/test/*` buffer

Note that I could only reproduce this with emacsclient, and only when invoked with the filename as argument

**Comment by tarsius** [comment]
> Note that I could only reproduce this with emacsclient, and only when invoked with the filename as argument 

That's not what we do when creating a commit from inside Magit, so this does not really help figuring out what goes wrong when doing that.

But I'll try to make something out of this information. Do you usually invoke commits from inside Magit? Do you sometimes use the `emacsclient` before using Magit (and you then get the "emacsclient: can't find socket; have you started the server?" as above)? If so, try to narrow it down to "if I use the emacsclient before using magit, then it always fails, if I use magit before emacsclient, then it always succeeds". Also check whether the "two frames" are actually two Emacs instances.

**Comment by Bronsa** [comment]
@tarsius the "emacsclient: can't find socket; have you started the server?"  message is because I intentionally killed the emacs server instance I was using to find the minimal steps required to reproduce.

My workflow consists of starting an emacs server instance in background and connecting to it using emacsclient, so I'm always invoking magit from inside emacsclient.

**Comment by Bronsa** [comment]
BTW this is a regression -- magit 1.x behaved as expected

**Comment by tarsius** [comment]
> the "emacsclient: can't find socket; have you started the server?" message is because I intentionally killed the emacs server instance I was using to find the minimal steps required to reproduce.

In other words, you were not able to reproduce the issue when using just that minimal init file. That's the information I was after. That means that without your personal configuration magit behaves as expected. And that in turn means that the issue is either in your configuration or at least triggered by something in it. So now you have to isolate the cause of this by commenting out parts of you configuration, restarting Emacs and checking whether you can still reproduce the issue, until you find the part that triggers the issue.

**Comment by Bronsa** [comment]
I *was* able to reproduce that using the minimal init file, take a look at the screencast I attached, I'm running an emacs server with no configuration other than those three lines to load magit + connecting to it with emacsclient

**Comment by tarsius** [comment]
```
[~/test]> EDITOR="" emacsclient -c -nw foo
emacsclient: can't find socket; have you started the server?
To start the server in Emacs, type "M-x server-start".

Warning: due to a long standing Gtk+ bug
http://bugzilla.gnome.org/show_bug.cgi?id=85715
Emacs might crash when run in daemon mode and the X11 connection is unexpectedly lost.
Using an Emacs configured with --with-x-toolkit=lucid does not have this problem.
Starting Emacs daemon.
Emacs daemon should have started, trying to connect again
```

Start the server explicitly, in the minimal init file. I suspect what is happening here is that a second emacs instance is started.

**Comment by Bronsa** [comment]
I added `(server-start)` to the init file and ran emacs --daemon to start the server in background.
running emacsclient -c foo and committing still reproduces the bug.

**Comment by Bronsa** [comment]
Here's the recorded session demonstrating how to reproduce the issue explicitely starting an emacs server:
http://kimochi.desrever.org/up/fc12917ff3c27e5f499b54a22643d7e4.webm

As you can see It's a very trivial and minimal setup to reproduce the bug, just an emacs server in daemon mode with magit loaded and opening a file with emacsclient -c filename

**Comment by andschwa** [comment]
@Bronsa Doing both those things starts the server twice. Either use `(server-start)` and load Emacs, *or* use `emacs --daemon`.

**Comment by Bronsa** [comment]
@andschwa that's good to know, thanks. The bug still manifests itself though.

**Comment by tarsius** [comment]
I can reproduce now and will look into it after getting some sleep.

**Comment by tarsius** [comment]
Okay so we can narrow it down to situations in which the user connects to the daemon to edit a file, then shows the status buffer, and then makes a commit. That's really strange. I can only guess that it might be due two "recursive" use of `emacsclient` (magit's commit commands call git which then uses the `emacsclient` as editor). I can't really see why that would make a difference, but it sure looks like that's what's triggering it.

(What put me on the wrong path in your original problem description is the unrelated error in the output. Sure I saw that at the end it said "Emacs daemon should have started, trying to connect again", but to many times before I have add problems helping with issues related to committing, that could have been avoided if the user had just been a bit more careful to follow instructions. So I wanted to really make sure this was out of the way before proceeding. You latest video was much better - it included all relevant steps and there were no unrelated errors.)
