### ISSUE TITLE
Declare hooks as special using defvar

### ISSUE THREAD

**Issue by tsdh** [magit/magit#2198]
If a hook isn't declared as special variable using `defvar`, it cannot be bound dynamically from code with `lexical-binding` (see emacs bug 21311).  One can work around that like in https://github.com/tsdh/magit-filenotify/blob/master/magit-filenotify.el#L84, but it isn't very obvious why it doesn't work as expected.

So could you please declare your hooks explicitly?

I think the following  are the hooks which are not declared: `magit-find-file-hook`, `magit-find-index-hook`, `with-editor-filter-visit-hook`, `magit-mode-setup-hook`, `magit-pre-refresh-hook`, `magit-pre-call-git-hook`, `magit-pre-start-git-hook`, `magit-wip-before-change-hook`, `magit-refresh-popup-buffer-hook`,

**Comment by tarsius** [comment]
Many of these hooks are not intended to be changes by users. Which one are you interested in?

**Comment by tarsius** [comment]
`magit-find-file-hook`, `magit-find-index-hook`, `magit-refresh-popup-buffer-hook`, and `with-editor-filter-visit-hook` should probably declared and documented.

`magit-wip-before-change-hook` only existed as a leftover in a doc-string, I will fix that.

The other hooks are used like this:

```lisp
(defun magit-maybe-save-repository-buffers ()
  ...)

(add-hook 'magit-mode-setup-hook #'magit-maybe-save-repository-buffers)
(add-hook 'magit-pre-refresh-hook #'magit-maybe-save-repository-buffers)
(add-hook 'magit-pre-call-git-hook #'magit-maybe-save-repository-buffers)
(add-hook 'magit-pre-start-git-hook #'magit-maybe-save-repository-buffers)
```

And that pretty much concludes their intended use.

**Comment by tarsius** [comment]
`magit-find-file-hook`, `magit-find-index-hook`, and `magit-refresh-popup-buffer-hook` are now defined explicitly. I think that should do it.

**Comment by tsdh** [comment]
I'm mainly interested in disabling `magit-pre-refresh-hook` temporarily when `magit-filenotify` refreshes the status buffer. The refresh happens in an idle timer where the do you want to save some buffers query is most annoying. The user saving a second before is most probably the cause of the refresh, he just didn't stop typing thereafter thus deferring the timer.

**Comment by tarsius** [comment]
I might as well... All hooks are now properly defined.

**Comment by tsdh** [comment]
Thank you!
