### ISSUE TITLE
j doesn't work on truncated filename in diffstat

### ISSUE THREAD

**Issue by greenrd** [magit/magit#2199]
If I am on a filename in a diffstat which has been truncated and so is displayed starting with an ellipsis (three . characters) then the error message "No diffstat in this buffer" is displayed in the minibuffer and point doesn't move.

**Comment by tarsius** [comment]
That's because of c64bb994d905d0daf3162abce4c425e6c097b8d2, which is part of some ongoing cleanup. Unfortunately I did not think of truncated (only encoded) filenames when I made that change. It will probably take a while until this is fixed.

**Comment by tarsius** [comment]
I am considering to revert this commit, but will first check whether I can implement the ongoing work which is based on this quickly enough.
