### ISSUE TITLE
Getting `error: Need package 'with-editor-20150824', but only 20150823.520 is available`

### ISSUE THREAD

**Issue by mattbanister** [magit/magit#2202]
Hi  

I'm getting the following error when installing emacs prelude:

 `error: Need package 'with-editor-20150824', but only 20150823.520 is available`

It seems like its caused by the latest version of magit.

**Comment by tarsius** [comment]
It takes some time for all packages that are part of the magit repository to be updated on melpa, because packages are updated in alphabetic order and there is quite a distance between g - m - w. But now they are all at `20150824.1010`.

**Comment by mattbanister** [comment]
Okay thanks Jonas.  It's working now!

**Comment by izuo** [comment]
>It takes some time for all packages that are part of the magit repository to be updated on melpa, because packages are updated in alphabetic order and there is quite a distance between g - m - w. But now they are all at 20150824.1010.

Hi, maybe rename "with-editor" to "magit-with-editor" would avoid this problem?

**Comment by seudut** [comment]
I am also seeing this problem now
error: Need package ‘with-editor-20160118’, but only 20160117.1513 is availabl

is there any better solution to avoid the problem.
