### ISSUE TITLE
Stash popping of point merely applies stash, does not pop it

### ISSUE THREAD

**Issue by greenrd** [magit/magit#2205]
This can be confirmed by pressing `$` to see the command line afterwards.

IIRC popping when point is not on a stash, does pop.

**Comment by tarsius** [comment]
`a` is supposed to apply, `A` to pop. What are you using? For me both commands work as expected.

**Comment by greenrd** [comment]
Ah sorry, I forgot to specify. I am using `z p`.

**Comment by tarsius** [comment]
That's the same as `A` which you can verify using `C-h c A` and, from the popup `?p`.

`magit-stash-pop` is implemented using `git stash apply` not `git stash pop` to make it more flexible and safer:

```lisp
(defun magit-stash-pop (stash)
  "Apply a stash to the working tree and remove it from stash list.
Try to preserve the stash index.  If that fails because there
are staged changes, apply without preserving the stash index
and forgo removing the stash."
  (interactive (list (magit-read-stash "Apply pop" t)))
  (if (= (magit-call-git "stash" "apply" "--index" stash) 0)
      (magit-stash-drop stash)
    (magit-run-git "stash" "apply" stash)))
```

And this is taken from the description of `apply` (referenced in the description of `pop`):

> If the --index option is used, then tries to reinstate not only the working tree’s changes, but also the index’s ones. However, this can fail, when you have conflicts (which are stored in the index,  where you therefore can no longer apply the changes as they were originally).

Therefore `magit-stash-{apply,pop}` unlike `git stash [apply|pop], always try to preserve the stashed index by using `--index` and if that fails give up on that and try again without `--index`. "Pop" should fall back to "apply" if there are conflicts, which is just what we do in `magit-stash-pop`. If applying without `--index` succeeds, but with `--index` it fails, then there is still some information contained in the stash, which was lost in the process of applying it, and it would therefore not be appropriate to drop it, the user might still want to get it out of the stash by other means.
