### ISSUE TITLE
magit-blame no longer works over Tramp

### ISSUE THREAD

**Issue by jinnovation** [magit/magit#2206]
I believe commit 8fba616 breaks `magit-blame` over Tramp.

Specifically, when calling `magit-blame` in a Git repository over Tramp, I receive the error:
``` 
user-error: Buffer isn't visiting a tracked file.
 ```
Reverting the change to `magit-blame.el` made in the commit allows it to work as expected again.

**Comment by kyleam** [comment]
Thanks.
