### ISSUE TITLE
blame =M switch requires entering a number, although git blame -M argument is optional

### ISSUE THREAD

**Issue by Niluge-KiWi** [magit/magit#2208]
With magit 2.1.0, `magit-blame` popup `=M` switch, `RET` (without any entry) results in error `Please enter a number.`.

From git blame man:
```
-M|<num>|
...
<num> is optional
```

Same issue with `=C`.

**Comment by tarsius** [comment]
This issue can be addressed by anyone knowing elisp - no magit knowledge required. For now I am leaving this for someone else to implement.
