### ISSUE TITLE
Single file log improvements

### ISSUE THREAD

**Issue by rgtk** [magit/magit#2210]
It would be really handy to see single file history. The closest thing we have is `magit-log-buffer-file`. 

I can see two ways to deal with it:

1. Create function that after selecting commit from list, show us content of current file at given time.
2. Make `magit-log-buffer-file` move pointer to the location in log buffer when we can see diff of current file.

I believe that option 2 is the most simple and sufficient.

**Comment by tarsius** [comment]
1. `M-x magit-find-file`
2. I have a hard time parsing that sentence but I believe pressing `RET` in a revision buffer could be doing something close to what you are talking about. You could for example show a log and move around in it until you find the commit you are interested in. While you move around in the log buffer, the revision buffer is being updated. You could now go to the revision buffer, move to a file, and press `RET` which would take you to the file as it was at that particular revision.

There are also some related changes in  #2195 (not merged yet).

**Comment by rgtk** [comment]
Sorry for difficulties in understanding.
It would be really convenient if pointer in revision buffer will point at current buffer filename. By doing so, moving between revision and examining changes will be faster.

**Comment by tarsius** [comment]
I think that by "revision buffer" you mean a buffer created with `M-x magit-find-file RET <commit> RET <filename> RET` and by "examining changes" you mean "looking at a buffer which contains the diff for the changes introduced by a commit". We actually call that *second* buffer a "revision buffer".

To make this more clear talk about the "blob buffer" and the "diff buffer". ("blog" ~= "contents of a file as stored in a commit")

I do not understand at all what that "pointer [which] point[s] at [the] current buffer['s] filename" could be. Are you talking about "[point](http://www.gnu.org/software/emacs/manual/html_node/elisp/Point.html)"? Or are you talking about a variable containing the "name of the current file"?

I am not sure in which buffer you are, but I think that (depending on what buffer it is) either `RET` or `M-x magit-diff RET RET` does what you want to do.

**Comment by rgtk** [comment]
By pointer I meant cursor.

I meant buffer that I can access with `M-x magit-log-buffer-file RET <commit> RET`.
When I do this, pointer/cursor is at the begining of the buffer. I suggest moving it to the line when file of the buffer when function was called.

**Comment by tarsius** [comment]
Ah, now I understand. Yes that is planned, as are other variations of this. See #1566. I have bumped this a bit on my list of things to do soon.
