### ISSUE TITLE
magit-status-refresh-buffer fails with unmerged binary file changes

### ISSUE THREAD

**Issue by phil-s** [magit/magit#2211]
Triggering upon `magit-status-refresh-buffer`.

Truncated backtrace:

    Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
     aref(nil 0)
     (eq (aref path 0) 34)
     (if (eq (aref path 0) 34) (string-as-multibyte (read path)) path)
     magit-decode-git-path(nil)

     (setq file (magit-decode-git-path file))
     (let ((status (cond ((equal (match-string 1) "git") "modified") ((derived-mode-p (quote magit-revision-mode)) "resolved") (t "unmerged"))) (orig (match-string 2)) (file (match-string 2)) (beg (point)) header modes) (save-excursion (forward-line 1) (setq header (buffer-substring beg (if (re-search-forward magit-diff-headline-re nil t) (match-beginning 0) (point-max))))) (magit-delete-line) (while (not (or (eobp) (looking-at magit-diff-headline-re))) (if (looking-at "^old mode \\([^\n]+\\)\nnew mode \\([^\n]+\\)\n") (progn (setq modes (match-string 0)) (magit-delete-match)) (cond ((looking-at "^--- \\([^/].*?\\)  ?$") (setq orig (match-string 1))) ((looking-at "^\\+\\+\\+ \\([^/].*?\\)   ?$") (setq file (match-string 1))) ((looking-at "^\\(copy\\|rename\\) from \\(.+\\)$") (setq orig (match-string 2))) ((looking-at "^\\(copy\\|rename\\) to \\(.+\\)$") (setq file (match-string 2)) (setq status (if (equal ... "copy") "new file" "renamed"))) ((looking-at "^\\(new file\\|deleted\\)") (setq status (match-string 1)))) (magit-delete-line))) (if orig (progn (setq orig (magit-decode-git-path orig)))) (setq file (magit-decode-git-path file)) (magit-diff-insert-file-section file orig status modes header))
     (cond ((looking-at magit-diff-submodule-re) (magit-diff-wash-submodule)) ((looking-at "^\\* Unmerged path \\(.*\\)") (let ((file (magit-decode-git-path (match-string 1)))) (magit-delete-line) (if (and (derived-mode-p (quote magit-status-mode)) (not (member "--cached" args))) nil (let* ((section8996 (progn ...))) (progn (or (and ... ... ...) (error "%s accessing a non-%s" ... ...)) (let* (...) (aset v 6 ...))) (let ((magit-insert-section--current section8996) (magit-insert-section--parent section8996) (magit-insert-section--oldroot ...)) (catch (quote cancel-section) (magit-insert ... nil 10) (run-hooks ...) (magit-insert-child-count section8996) (set-marker-insertion-type ... t) (let* ... ...) (if ... ... ...)) section8996)))) t) ((looking-at "^\\(merged\\|changed in both\\)") (let ((status (if (equal (match-string 1) "merged") (quote merged) (quote conflict))) file orig modes) (magit-delete-line) (while (looking-at "^  \\([^ ]+\\) +[0-9]\\{6\\} \\([a-z0-9]\\{40\\}\\) \\(.+\\)$") (let ((string8997 nil)) (let ((side ...) (blob ...) (name ...)) (cond (... ...) (... ...) (... ...) (t nil)))) (magit-delete-line)) (setq orig (magit-decode-git-path orig)) (setq file (magit-decode-git-path file)) (magit-diff-insert-file-section file orig status modes nil))) ((looking-at "^diff --\\(git\\|cc\\|combined\\) \\(?:\\(.+?\\) \\2\\)?") (let ((status (cond ((equal ... "git") "modified") ((derived-mode-p ...) "resolved") (t "unmerged"))) (orig (match-string 2)) (file (match-string 2)) (beg (point)) header modes) (save-excursion (forward-line 1) (setq header (buffer-substring beg (if (re-search-forward magit-diff-headline-re nil t) (match-beginning 0) (point-max))))) (magit-delete-line) (while (not (or (eobp) (looking-at magit-diff-headline-re))) (if (looking-at "^old mode \\([^\n]+\\)\nnew mode \\([^\n]+\\)\n") (progn (setq modes (match-string 0)) (magit-delete-match)) (cond ((looking-at "^--- \\([^/].*?\\)   ?$") (setq orig ...)) ((looking-at "^\\+\\+\\+ \\([^/].*?\\)    ?$") (setq file ...)) ((looking-at "^\\(copy\\|rename\\) from \\(.+\\)$") (setq orig ...)) ((looking-at "^\\(copy\\|rename\\) to \\(.+\\)$") (setq file ...) (setq status ...)) ((looking-at "^\\(new file\\|deleted\\)") (setq status ...))) (magit-delete-line))) (if orig (progn (setq orig (magit-decode-git-path orig)))) (setq file (magit-decode-git-path file)) (magit-diff-insert-file-section file orig status modes header))))
     magit-diff-wash-diff(("diff" ("--no-ext-diff") "--no-prefix" "--" nil))

     apply(magit-diff-wash-diff ("diff" ("--no-ext-diff") "--no-prefix" "--" nil) nil)
     (closure (t) (&rest args) (apply (quote magit-diff-wash-diff) (quote ("diff" ("--no-ext-diff") "--no-prefix" "--" nil)) args))()
     funcall((closure (t) (&rest args) (apply (quote magit-diff-wash-diff) (quote ("diff" ("--no-ext-diff") "--no-prefix" "--" nil)) args)))
     (and (not (eobp)) (funcall function))
     (while (and (not (eobp)) (funcall function)))
     magit-wash-sequence((closure (t) (&rest args) (apply (quote magit-diff-wash-diff) (quote ("diff" ("--no-ext-diff") "--no-prefix" "--" nil)) args)))

     (progn (goto-char (line-beginning-position)) (magit-wash-sequence (apply-partially (quote magit-diff-wash-diff) args)) (insert 10))
     (if (re-search-forward magit-diff-headline-re nil t) (progn (goto-char (line-beginning-position)) (magit-wash-sequence (apply-partially (quote magit-diff-wash-diff) args)) (insert 10)))
     magit-diff-wash-diffs(("diff" ("--no-ext-diff") "--no-prefix" "--" nil))

     magit-git-wash(magit-diff-wash-diffs "diff" ("--no-ext-diff") "--no-prefix" "--" nil)

     magit-insert-unstaged-changes()

     magit-status-refresh-buffer()

**Comment by phil-s** [comment]
Got diverted. I'll try to give you some more context later.

**Comment by phil-s** [comment]
Currently happening when applying a stash which has conflicts.

In the final form before ` (setq file (magit-decode-git-path file))` I can see (via eval) that `(match-string 0)` is `"diff"`, and so the let-bound `(file (match-string 2))` is `nil` (as is `orig` which uses the same match).

**Comment by tarsius** [comment]
Using `master`?

**Comment by phil-s** [comment]
Updated the above.

Yes, and initially on `HEAD`, but I rolled back to the last tag and got the same result.

**Comment by phil-s** [comment]
Same result with an empty Emacs config and freshly-installed Magit from melpa.

With melpa-stable, the installation doesn't quite complete: `async-bytecomp-get-allowed-pkgs: Wrong type argument: arrayp, nil` (but after manually loading the libraries, I get the same eventual outcome).

2.1.0 works.

**Comment by phil-s** [comment]
No issue in 1.4.2, FWIW. Nothing else to add right now. I guess I'll switch back to master HEAD for further investigation.

**Comment by phil-s** [comment]
Yeah. That might be the one. I created a new branch based on my stash, reset the changes to `sauron.elc`, re-stashed everything, and checked out the original branch again.

Applying the original stash still produced the error.
Applying the new stash instead worked.

I'll do a few some more sanity checks...

**Comment by phil-s** [comment]
Well, not too hard to recreate something similar...

I created two branches with conflicting changes to sauron.elc and then tried to merge one into the other.

git status tells me:

	On branch foo
	Your branch is ahead of 'master' by 1 commit.
	  (use "git push" to publish your local commits)

	You have unmerged paths.
	  (fix conflicts and run "git commit")

	Unmerged paths:
	  (use "git add <file>..." to mark resolution)

			both modified:   el-get/sauron/sauron.elc

Whereas magit status tells me:

	Head:     5cbe305 foo foo
	Upstream: ffcbba5 master testing

	Merging bar (1)
	c3fff4c bar bar

	Unstaged changes:

Which is at minimum a related problem of not showing the change at all.
