### ISSUE TITLE
with-editor  fails to find emacsclient.emacs25 on Debian

### ISSUE THREAD

**Issue by bgamari** [magit/magit#2217]
I am using a self-built Debian package of emacs25 due to a [bug](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=16737) in emacs24. Unfortunately it seems that magit is unable to find `emacsclient`,
```
Warning (with-editor): Cannot determine a suitable Emacsclient

Determining an Emacsclient executable suitable for the
current Emacs instance failed.  For more information
please see https://github.com/magit/magit/wiki/Emacsclient.
```
This despite the fact that it can be found in the usual location (for Debian at least), `/usr/bin/emacsclient.emacs25`,
```
$ which emacsclient.emacs25
/usr/bin/emacsclient.emacs25
$ emacsclient.emacs25 --version
emacsclient 25.0.50
```

**Comment by phil-s** [comment]
`emacsclient.emacs25` is surely not a standard name, though? Are you expecting Magit to *guess* that?

**Comment by phil-s** [comment]
http://magit.vc/manual/with-editor.html#Configuring-With_002dEditor

**Comment by bgamari** [comment]
This is the naming convention that Debian-based distributions use for these binaries (with `emacsclient` symlinked to the binary corresponding to the emacs version selected by `alternatives`). Given the number of users that use Debian, Ubuntu, etc. I don't think it's entirely unreasonable to expect that magit would include a name of this form in its typical search set.

**Comment by phil-s** [comment]
Ah, I see. I took "self-built" to mean something less standard than that. My apologies for misunderstanding.

**Comment by bgamari** [comment]
phil-s <notifications@github.com> writes:

> Ah, I see. I took "self-built" to mean something less standard than that. My apologies for misunderstanding.
>
No worries. I should have been more clear. This package is built with
the usual Debian packaging, just with an emacs snapshot.
