### ISSUE TITLE
magit-diff-unstaged-and-staged

### ISSUE THREAD

**Issue by gleb** [magit/magit#2219]
Feature request - I'd like to have this function.  Naive attempt to implement it runs into problems, see below.

Use case: want to see both kinds of diffs, and be able to stage/unstage hunks all from one buffer.   Not unlike status buffer but without other sections.

Naive implementation:
```elisp
(defun magit-diff-unstaged-and-staged (&optional args files)
  "Show both unstaged and staged changes in the same buffer.
Shows changes between the working tree and the index.  And also
shows changes between the index and the `HEAD' commit."
  (interactive (magit-diff-arguments))
  (magit-mode-setup magit-diff-buffer-name-format
                    magit-diff-switch-buffer-function
                    #'magit-diff-mode
                    ;; #'magit-status-mode
                    #'magit-diff-unstaged-and-staged-refresh-buffer
                    args files))
(defun magit-diff-unstaged-and-staged-refresh-buffer (args files)
  (magit-insert-section (unstaged)
    (magit-insert-heading "Unstaged changes:")
    (magit-git-wash #'magit-diff-wash-diffs
      "diff" "-p" (and magit-diff-show-diffstat "--stat")
      "--no-prefix" args "--" files))
  (magit-insert-section (staged)
    (magit-insert-heading "Staged changes:")
    (magit-git-wash #'magit-diff-wash-diffs
      "diff" "-p" (and magit-diff-show-diffstat "--stat")
      "--no-prefix" (list "--cached") args "--" files))
  (cond ((derived-mode-p 'magit-status-mode)
         ;; expand diffs
         (goto-char (point-min))
         (magit-section-show-level-4)
         (goto-char (point-max))
         (magit-section-show-level-4))))
```

There are different problems depending on whether I use magit-diff-mode or magit-status-mode for this buffer.

With magit-diff-mode:
* stage works, unstage does not - "Already unstaged"
* -/+ do not work
* g - does not preserve point location
* "[back]" links get inserted

WIth magit-status-mode:
* g and -/+ - do not preserve point location
* need to manually expand sections

I am thinking the right mode for this should be magit-diff-mode.  But looking through magit code it looks some code is parametrized depending on current mode, and I am guessing assumes there will be only 1 section in the buffer.

**Comment by tarsius** [comment]
I think I have implemented that once but it seems I did not install it and have lost it...

**Comment by gleb** [comment]
Debugging why unstaging doesn't work in magit-diff-mode I see why - in magit-diff-type function "In buffers whose major mode is `magit-diff-mode' SECTION is ignored and the type is determined using other means."   It looks like a lot of code makes particular assumptions about magit-diff-mode

**Comment by tarsius** [comment]
> I am thinking the right mode for this should be magit-diff-mode.

No, that's for showing one and only one diff. `magit-status-mode` is capable of showing various things at once including several diffs and logs and much more. We can just reuse the functions that insert the un-/staged changes in the status buffer in this new buffer also.

A minimal viable implementation looks like this.

```
(defun magit-staging ()
  (interactive)
  (magit-mode-setup "*magit-staging: %a*" nil
                    #'magit-status-mode
                    (lambda ()
                      (magit-insert-section (status)
                        (magit-insert-unstaged-changes)
                        (magit-insert-staged-changes)))))
```

**Comment by tarsius** [comment]
Do you want to use this new buffer *instead* of the status buffer, or do you want to use it *in addition* to the status buffer?

**Comment by gleb** [comment]
Thanks.  I am guessing `(magit-insert-section (status)` is  the key thing I was missing.

In addition. I am working on something like global-magit-mode.

For some commonly used commands, I want to be able to use Magit
without switching to status buffer.  In particular I want to be able
to invoke commands like log and diff on the current file with minimum
number of keystrokes.

You could think of it as a replacement for VC.  But I am more
influenced by p4.el which functions entirely without status buffer.

**Comment by gleb** [comment]
Btw, where is the code that hides diffs by default in magit-status-mode?   I tried to find it in the debugger but failed.

**Comment by tarsius** [comment]
> where is the code that hides diffs by default in magit-status-mode?

The HIDE argument of `magit-insert-section` sets the initial visibility. Also see the doc-string of that macro and the code surrounding the use of `magit-section-set-visibility-hook` in that macro, as well as the functions on that hook. 

> I am working on something like global-magit-mode.

In the long run I too would like to better support work flows that are not centered around the status buffer so much.

> For some commonly used commands, I want to be able to use Magit without switching to status buffer. In particular I want to be able to invoke commands like log and diff on the current file with minimum number of keystrokes.

The new `magit-file-buffer-mode` and its keymap could be of use here.

**Comment by tarsius** [comment]
I have added the above snippet to the [Tips-and-Tricks](https://github.com/magit/magit/wiki/Tips-and-Tricks) wiki page. As for supporting a less status-buffer-centered work flow goes, I don't intend to work on this anytime soon. So I am closing this issue, but if you make some progress, then feel free to inform me about it here.

**Comment by gleb** [comment]
Agreed.

**Comment by fommil** [comment]
the proposed workaround no longer works 

```
magit-generate-buffer-name-default-function: Wrong type argument: symbolp, "*magit-staging: %a*"
```

**Comment by kyleam** [comment]
Hmm, that underlying code has changed quite a bit.  Something like below is the simplest way I can think of with the current mechanism.

```
(define-derived-mode magit-staging-mode magit-status-mode "Magit staging"
  "Mode for showing staged and unstaged changes."
  :group 'magit-status)

(defun magit-staging-refresh-buffer ()
  (magit-insert-section (status)
    (magit-insert-unstaged-changes)
    (magit-insert-staged-changes)))

(defun magit-staging ()
  (interactive)
  (magit-mode-setup #'magit-staging-mode))
```

**Comment by fommil** [comment]
excellent! This may go some ways toward helping workaround #2395

**Comment by daedsidog** [comment]
I advise reconsidering to open this issue as Windows performance is still abysmal to this day.
