### ISSUE TITLE
magit error committing: Unexpected error while determining toplevel

### ISSUE THREAD

**Issue by krig** [magit/magit#2220]
After updating to the latest version of magit, I can't commit any longer. Attempting to commit fails with this message:

```
  1 git … commit --
Waiting for Emacs...
*ERROR*: Unexpected error while determining toplevel
error: There was a problem with the editor '/usr/bin/emacsclient --socket-name=/tmp/emacs1000/server'.
Please supply the message using either -m or -F option.
```

Versions:

```
GNU Emacs 24.5.1
git version 2.1.4
  magit              20150830.544  installed             A Git porcelain inside Emacs
  dash               20150829.433  installed             A modern list library for Emacs
  git-commit         20150824.1010 installed             Edit Git commit messages
```

**Comment by tarsius** [comment]
What OS are you using?

In the status buffer (or if you invoked the commit from another buffer, then in that buffer) determine the value of `default-directory` using `C-h v default-directory RET`. Then go to that directory in a shell and run these commands:

```
$ pwd
$ git rev-parse --show-toplevel
$ git rev-parse --show-cdup
$ git rev-parse --git-dir
$ cd ./git
$ git rev-parse --show-toplevel
$ git rev-parse --show-cdup
$ git rev-parse --git-dir
```

**Comment by krig** [comment]
OS is openSUSE 13.2.

Your suggested commands gave me a hint: Maybe this is because the git folder I am in is a submodule in another repository. So `.git` is not a directory, it's a file pointing to the submodule location in the parent repository.

```
> pwd
/home/krig/.emacs.d
> git rev-parse --show-toplevel
/home/krig/dots/emacs.d
> git rev-parse --show-cdup

> git rev-parse --git-dir
/home/krig/dots/.git/modules/emacs.d
> cat .git
gitdir: ../.git/modules/emacs.d
```

**Comment by krig** [comment]
```
> pwd
/home/krig/dots/.git/modules/emacs.d
> git rev-parse --show-toplevel
/home/krig/dots/emacs.d
> git rev-parse --show-cdup
/home/krig/dots/emacs.d
> git rev-parse --git-dir
.
```

**Comment by krig** [comment]
> Are there any symlinks in the path leading up to the `default-directory`?

Oh, yes. Here's the structure:

I have a git directory in `~/dots` which has a submodule `~/dots/emacs.d`. I have a symlink to that directory in `~/.emacs.d`. I realise this is ridiculously complicated, but it hasn't caused any issues for me before.

**Comment by tarsius** [comment]
Hm, I thought I tested that case, apparently not. I'll probably fix this tomorrow.

**Comment by krig** [comment]
Great, thanks! I'd try to fix it myself, but looking at `magit-toplevel` I'm pretty sure I'll end up breaking it in the process.

**Comment by tarsius** [comment]
You can just revert fd688cb2192393a18c28ff3b92d5a01634b1779e for now.

**Comment by krig** [comment]
Thanks, reverting to that version of `magit-toplevel` makes it commit successfully.

**Comment by tarsius** [comment]
I have reverted that commit for now. I understand the problem in this case and will make sure to add tests covering it before installing a second revision of this change. But there are other issues too, so that might take a while. Anyway we are back to how it was before for now.
