### ISSUE TITLE
magit-ediff-dwim vs binary changes

### ISSUE THREAD

**Issue by phil-s** [magit/magit#2223]
Now that #2211 has been resolved (thank you!), I can see that the `magit-ediff-dwim` (bound to `e`) behaviour is also getting things a bit wrong for this change type.

If I merge two conflicting changes, one binary and one not, then `e` still does the right thing with the non-binary change -- ediff shows me both versions of the text for merging as usual (this ediff integration is completely brilliant, btw!).

For the binary change, `e` still invokes ediff, but both the MINE and the OTHER windows are showing the same (MINE) content.

Admittedly, I'm not entirely sure what *should* happen when invoking ediff on binary changes? My test (tweaking a `elc` file) is contrived and using a very small file, and the normal ediff works fine. There would be many situations in which the binary files may be too large to sensible load, and/or for which `hexl-mode` may be a more appropriate way to render the buffers. ( http://trey-jackson.blogspot.co.nz/2010/10/emacs-tip-38-automatically-diff-binary.html shows an example of using `hexl-mode` with ediff.)

**Comment by tarsius** [comment]
> For the binary change, `e` still invokes ediff, but both the MINE and the OTHER windows are showing the same (MINE) content.

I think that either Git is doing that or that you are mistaken and there actually are hard-to-see difference.

> Admittedly, I'm not entirely sure what *should* happen when invoking ediff on binary changes? My test (tweaking a `elc` file) is contrived and using a very small file, and the normal ediff works fine.

For true binary files diffs are not very useful, not without first converting them into some text representation and even then that's only useful for looking at, not for merging. I think `elc` files should be treated as text files, you can tell Git to do so. See the `gitattributes(5)` in particular "Performing text diffs of binary files".

I don't Magit (or Ediff for that matter) is the right place to deal with diffs for binary files. This should be configured at the Git level.

**Comment by phil-s** [comment]
Aha. Yes, with binary files we don't actually get resolvable output.

With a text file, `smerge-ediff` processes a `(current-buffer)` containing conflicts like:
```
<<<<<<< variant A
;; foo
>>>>>>> variant B
;; bar
======= end
```
Whereas with a binary file, that buffer simply contains the unmodified `MINE` content, and hence both variants in the merge are also identical to that.

So there may be no benefit to `magit-ediff-dwim` doing anything more than issuing a message in this circumstance? (Some kind of pointer to that manpage info would certainly be helpful to users.)

**Comment by phil-s** [comment]
A quick test of a non-conflicting binary change generates a different error, but presumably for essentially similar reasons.

> /usr/bin/diff3: subsidiary program 'diff' failed (exit status 2)

So I suspect that with binary changes in general, `magit-ediff-dwim` should only notify the user that such an action isn't possible, and point them at the aforementioned documentation.

**Comment by tarsius** [comment]
> Git must be making the (not unreasonable) assumption that binary conflicts are always a "them or us" situation,

But that seems to be configurable, see "Performing a three-way merge" in `gitattributes(5)`.

> So I imagine there is no benefit to magit-ediff-dwim doing anything more than issuing a "no can do" message in this circumstance?

Since some files might be wrongfully classified as binary files but can still be shown in a meaningful diff, saying "I can't do that Dave" is less helpful than just doing it (and in some, but not all, cases displaying some garbage).

**Comment by phil-s** [comment]
In which case I was wrong to broaden the scope of this issue. I'll revert the title.

For the original case of unmerged binary changes, my current understanding is that `magit-ediff-dwim` *can't* ever do anything useful (because git won't update the file with merge syntax if it considers it a binary file).

OTOH `magit-ediff-dwim` can (and does) do something quite confusing in this situation, by attempting to do conflict resolution on a file which contains no conflicts.

To my mind, saying "I can't do that -- but here's how you can fix it, if you need to" would be *much* better for this particular use case than the current behaviour (which will always be unhelpful and/or confusing).

Can we log this one as a feature request?
