### ISSUE TITLE
Can't add (stage) file after conflict type "deleted by us"

### ISSUE THREAD

**Issue by mbertheau** [magit/magit#2224]
This is git status:
```
~/src/machtfit $ git status
rebase in progress; onto 6e5f697
You are currently rebasing branch 'simple-settlements' on '6e5f697'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   accounting/__init__.py
	new file:   accounting/meat.py
	modified:   apps/dashboard/invoices/tables.py
	modified:   apps/dashboard/invoices/views.py
	modified:   apps/views.py
	new file:   search.py
	modified:   templates/dashboard/invoices/invoice_row_settlements.html

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add/rm <file>..." as appropriate to mark resolution)

	deleted by us:      accounting/io.py

```

This is *magit-status*:
```
Head:     66926fd Add buttons for new code to generate settlements
Tag:      deployed-2015-08-27-13-42-01+02-00 (15)

Rebasing simple-settlements onto simple-settlements~9
pick c455647 Add django-debug-toolbar
pick 1e6fdb6 Start real tests for new settlement code
join 9840c7a Move invoice list over to new settlement code
done 66926fd Add buttons for new code to generate settlements
done 14baf78 Compare old and new ways to generate settlements
done 3bd35fa Move supplier code to supplier module
done ae9e184 Move subscription code to subscription.py
done 356f608 Move retrieve_first_numbers to vendor
done 37f5264 Add new, simpler code to generate invoices and settlements
onto 6e5f697 TEMP pytest conf for fast pure-python testing

Staged changes (8)
modified   accounting/__init__.py
unmerged   accounting/io.py (deleted by us)
new file   accounting/meat.py
modified   apps/dashboard/invoices/tables.py
modified   apps/dashboard/invoices/views.py
modified   templates/dashboard/invoices/invoice_row_settlements.html
```

I see no way to add `accounting/io.py` so that I can continue the rebase. `s` on `io.py` says "Already staged"

After doing git add on the command line, I could continue the rebase.

I'm using git 1.9.1, ignoring the warning on every startup, and `magit-20150817.2214`

**Comment by tarsius** [comment]
> I'm using git 1.9.1, ignoring the warning on every startup, 

That's probably the problem. Try to reproduce with a supported Git version.

**Comment by mbertheau** [comment]
I reproduces this with current versions:
```
~/src/machtfit $ ls -1d ~/.emacs.d/elpa/magit-*
/home/markus/.emacs.d/elpa/magit-20150909.1359
/home/markus/.emacs.d/elpa/magit-gitflow-20150905.39
/home/markus/.emacs.d/elpa/magit-popup-20150903.1204
Mo Sep 14 20:10:21 markus@machtfit
~/src/machtfit $ git --version
git version 2.5.1
~/src/machtfit $ git status
rebase in progress; onto ecb583d
You are currently rebasing branch 'simple-settlements' on 'ecb583d'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   apps/company/models.py
... lots of files
	deleted:    tests/unit/finance/test_invoice.py

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add/rm <file>..." as appropriate to mark resolution)

	deleted by them: apps/finance/management/commands/is_functional_style_better.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.style.yapf
	doc/settlement.md
```

*magit-status*:
```
Head:     45c864c Generate both settlement types with one button
Tag:      deployed-2015-09-14-14-39-35+02-00 (14)

Rebasing simple-settlements onto simple-settlements~14
...
pick e45d4fa Handle zero settlements generated
join c2adc73 Delete old settlement code
done 45c864c Generate both settlement types with one button
done a3e6795 Generate old and new bank transfer lists in parallel for comparison
...

Staged changes (28)
modified   apps/company/models.py
...
unmerged   apps/finance/management/commands/is_functional_style_better.py (deleted by them)
...
modified   apps/finance/managers.py

Untracked files (2)
.style.yapf
doc/settlement.md
```

<kbd>s</kbd> on the line `^unmerged` says "Already staged".

(@tarsius I don't have a reopen button here, so I can't reopen myself.)

Btw, magit is great! :100:

**Comment by tarsius** [comment]
Magit doesn't show unmerged files in a separate section like `git status` does, which is something I've been aware of a long time and intended to address eventually. But so far I wasn't aware that this actually causes any issues and so I didn't. The only issue I was aware of was that this sometimes caused the unmerged file to appear in both "Unstaged" and "Staged changes". I believe the case you are bringing up, is the only one in which an unmerged change *only* appears in "Staged changes". This is pretty rare, but I guess I have to do something about it now.

Meanwhile you can proceed like this. Unstage the unmerged file, it now appears in "Untracked files" (you might have to expand subsections to see it). Then, if you want to keep our side (the delete), just delete the file. Or if you want to keep their side (with the edit), then just stage it.

**Comment by tarsius** [comment]
Better yet, you can just use <kbd>,</kbd>, for unmerged files, this ultimately uses `magit-checkout-stage` which lets you pick one of the sides to keep. This makes the creation of a "Unmerged changes" section less urgent. It's a bit confusing that an unmerged change appears as a "staged" change, but that's just how it comes out of Git.

**Comment by tarsius** [comment]
I should mention that in the manual though.

**Comment by kyleam** [comment]
> Meanwhile you can proceed like this. Unstage the unmerged file, it now
> appears in "Untracked files" (you might have to expand subsections to
> see it). Then, if you want to keep our side (the delete), just delete
> the file. Or if you want to keep their side (with the edit), then just
> stage it.

IIRC from briefly confirming/debugging this issue last night, using 'k'
on the file in the staged changes section also lets you select
ours/theirs.

**Comment by tarsius** [comment]
@kyleam Fetch your mail again :-)

I am actually not so sure I really want to add an additional "Unmerged changes" section, since it is not necessary due to the existence of `magit-checkout-stage`. I'll check what the cost would be.

**Comment by tarsius** [comment]
(@kyleam but also note that I made some small adjustments since the original revs of my comments were mailed to you. Since I do that a lot, you should probably read these conversations using the webinterface, instead of your mail program. (And yeah, that has advantages too. Eventually I will write a mode for reading and commenting directly in Emacs.)

**Comment by tarsius** [comment]
I have pushed an naive early implementation to #2263. Let's continue the conversation there. I'll probably try to get this into v2.3.
