### ISSUE TITLE
New revert messages are obscuring important errors

### ISSUE THREAD

**Issue by vspinu** [magit/magit#2229]
After upgrade I am seeing only "revert" messages. For example 

```
The following untracked working tree files would be overwritten by checkout: ... [See buffer *magit-process: ~/VC/projectile/* for details]
Reverting (up to) 1 file-visiting buffer(s)...
(No buffers need to be reverted)
```

Two useless messages obscured the important problem. I don't want to see those revert messages at all. is there a way to disable those?  

Thanks.

**Comment by kyleam** [comment]
You can set magit-revert-buffers to silent.

**Comment by vspinu** [comment]
Great. Thanks.
