### ISSUE TITLE
Pickaxe (etc?) on selected region?

### ISSUE THREAD

**Issue by phil-s** [magit/magit#2234]
I was reading http://gitster.livejournal.com/35628.html and section **3. Pickaxe** caught my attention. It immediately made me think it would be nice if we could select a region in a tracked file, and then simply invoke a command to pickaxe that text.

It also occurred to me that this notion has similarities to #1717 / #2226, and maybe there are other applications for the general idea?

**Comment by tarsius** [comment]
> It also occurred to me that this notion has similarities to ... #2226,

Which contains:

```
;; TODO ? (?S "Pickaxe search"          "-S"        read-from-minibuffer)
```

So yes, I intend to get started with that soonish.

**Comment by phil-s** [comment]
Excellent :)
