### ISSUE TITLE
don't bind key q in rebase-todo buffer

### ISSUE THREAD

**Issue by thomas-koch-comsolit** [magit/magit#2238]
I just updated magit from 1.2.1 to version 20150903.1204 (oh melpa...). In the old version I finished editing the rebase-todo list by pressing q. Now pressing q just burries the buffer. Of course I accidentally press q when I should press C-c C-c several times a day.

I think it doesn't make sense, to have q bound in this way for this particular buffer.

**Comment by tarsius** [comment]
> I just updated magit from 1.2.1 to version 20150903.1204 

Well, that was about time :-)

> Of course I accidentally press q when I should press C-c C-c several times a day.

That most be why that buffer sometimes has disappeared for me too - just never bothered me enough to investigate. The binding comes from `special-mode-map`. I tend to agree that we should remove that binding. Will do that soon, unless someone objects.
