### ISSUE TITLE
document available extensions

### ISSUE THREAD

**Issue by thomas-koch-comsolit** [magit/magit#2239]
By accident I saw in my emacs package manager that there are several magit extension packages like magit-annex, magit-filenotify, magit-gerrit, etc.

Please add a Section to the magit homepage that links to those extensions with a one-line description. Of course this only makes sense for extensions that are still compatible with the stable magit release.

Thank you!

**Comment by tarsius** [comment]
I maintain a [list of Git related Emacs packages](https://github.com/tarsius/git-elisp). I do intend to comment on the individual packages and also create a section dedicated to extensions to Magit. I might also add such a list to the manual at some point.

> By accident I saw in my emacs package manager that there are several magit extension packages

You might have done it by accident, but that's what most people intentionally do to find such packages.

Like all "this particular thing isn't documented sufficiently" issues, I am closing this one too. I am aware of these gaps and should I ever find the time, then I will do something about them.

**Comment by tarsius** [comment]
Here's an other list: https://github.com/magit/magit/issues/1921.
