### ISSUE TITLE
magit-format-patch can work with stashes

### ISSUE THREAD

**Issue by sandinmyjoints** [magit/magit#2240]
When I press `W` then `p` with point on a stash, I'd love to get a patch of that stash.

**Comment by tarsius** [comment]
It's not that simple - a stash may consist of up to three commits.

**Comment by tarsius** [comment]
Furthermore the final commit always is merge commit. If you try to create a patch from that *commit*, i.e. by doing `l o stash@{0} RET` and then `W p`, then you always get an empty patch file. So no, `magit-format-patch` *cannot* work with stashes and I don't intend to change that, it would be difficult to implement *and* the ui would be ambiguous.

**Comment by sandinmyjoints** [comment]
OK, thanks for the explanation. I didn’t know a stash could consist of multiple commits!

**Comment by sandinmyjoints** [comment]
What about a command that runs `git stash show -p <whatever stash point is on>` and puts the output into a new buffer? That would be fantastic!

**Comment by tarsius** [comment]
<kbd>RET</kbd> already does that, except that it shows you all the commits individually.

**Comment by sandinmyjoints** [comment]
Yeah, and that's great, but it lacks the headers that are necessary to actually apply a patch. In other words, you get:

```diff
modified   assets.json
@@ -4,9 +4,9 @@
     "/css/desktop-ie8.css": "/dist/desktop-ie8-f7fed1e39cc45ed918639c01178e6dc6.css",
     "/css/desktop-rw.css": "/dist/desktop-rw-4fc3ba26740122412c5c71a8eed1b94a.css",
     "/css/desktop.css": "/dist/desktop-da8f0a26a1d56d554bc7c32c2c2e6515.css",
-    "/js/mobile-min.js": "/dist/mobile-min-3cb508a81900f7ffd2903fa0853bc26c.js",
-    "/js/desktop-min.js": "/dist/desktop-min-feedb5670357e087a81bca7c84b1020b.js",
-    "/js/desktop-rw-min.js": "/dist/desktop-rw-min-c6b109f62157dfe364b630c3dd71df4d.js",
+    "/js/mobile-min.js": "/dist/mobile-min-7003d6277f97b702ce45bab6daa92160.js",
+    "/js/desktop-min.js": "/dist/desktop-min-545194739815e80a8c6773531a01ee89.js",
+    "/js/desktop-rw-min.js": "/dist/desktop-rw-min-e3b18178ba35dd252ab383f8eec315c5.js",
     "/js/wmd-min.js": "/dist/wmd-min-662d74cd324b3e2a5f5c16eeec265268.js",
     "/js/vendor/jquery-min-1-11-1.js": "/dist/vendor/jquery-min-1-11-1-8101d596b2b8fa35fe3a634ea342d7c3.js",
     "/js/vendor/zepto-min-1-1-0.js": "/dist/vendor/zepto-min-1-1-0-1ef10fbd970deb84ec7a271f6dbbfbba.js"
```

but if you save this to a file and try to `git apply` it, it will die with `fatal: patch fragment without header at line 2: @@ -49,9 +49,9 @@ whatever the code is`

`$ git stash show -p stash@{0}` gives you:

```diff
diff --git a/assets.json b/assets.json
index 7491314..ea6ce61 100644
--- a/assets.json
+++ b/assets.json
@@ -4,9 +4,9 @@
     "/css/desktop-ie8.css": "/dist/desktop-ie8-f7fed1e39cc45ed918639c01178e6dc6.css",
     "/css/desktop-rw.css": "/dist/desktop-rw-4fc3ba26740122412c5c71a8eed1b94a.css",
     "/css/desktop.css": "/dist/desktop-da8f0a26a1d56d554bc7c32c2c2e6515.css",
-    "/js/mobile-min.js": "/dist/mobile-min-3cb508a81900f7ffd2903fa0853bc26c.js",
-    "/js/desktop-min.js": "/dist/desktop-min-feedb5670357e087a81bca7c84b1020b.js",
-    "/js/desktop-rw-min.js": "/dist/desktop-rw-min-c6b109f62157dfe364b630c3dd71df4d.js",
+    "/js/mobile-min.js": "/dist/mobile-min-7003d6277f97b702ce45bab6daa92160.js",
+    "/js/desktop-min.js": "/dist/desktop-min-545194739815e80a8c6773531a01ee89.js",
+    "/js/desktop-rw-min.js": "/dist/desktop-rw-min-e3b18178ba35dd252ab383f8eec315c5.js",
     "/js/wmd-min.js": "/dist/wmd-min-662d74cd324b3e2a5f5c16eeec265268.js",
     "/js/vendor/jquery-min-1-11-1.js": "/dist/vendor/jquery-min-1-11-1-8101d596b2b8fa35fe3a634ea342d7c3.js",
     "/js/vendor/zepto-min-1-1-0.js": "/dist/vendor/zepto-min-1-1-0-1ef10fbd970deb84ec7a271f6dbbfbba.js"
```

which contains the headers needed to apply the patch.

Older Magit had the `git stash show` behavior which I guess combines all the commits. I used it in my workflow fairly regularly -- view a stash, kill it to a new buffer, save as a file, send it to a teammate to apply. 

I'm sure seeing the individual commits is useful to someone out there, maybe that's why you reworked it to be the way it is now. The previous way was useful to me, and I'd love if it were available again. I'm not great at Emacs Lisp but I'd be willing to give it a shot if you could even just point me in the right direction.

**Comment by tarsius** [comment]
You can create a patch from the "working tree" commit in the stash buffer using <kbd>W p</kbd>. You cannot do the same for the "index" commit because it is a merge commit and it is not possible to create patches from merge commits.

So you have to stage the changes before creating the stash in order to later be able to create a patch with commit information from the stash. But I think it would be better to create an actual commit with a proper commit message and then create a patch from that. Your teammate will appreciate getting a real commit message instead of "On some-branch: abdcefg message about unrelated commit".

**Comment by tarsius** [comment]
Also I have added a new "Format patch" action to the stash popup at <kbd>z f</kbd>. That gives you the same patch as `show -p STASH` and you don't even have to manually copy it into a file.

**Comment by sandinmyjoints** [comment]
Cool, thanks, I look forward to trying that out!
