### ISSUE TITLE
(font-info)

### ISSUE THREAD

**Issue by holomorph** [magit/magit#2241]
I'm getting an error from this line in `magit-diff.el` using Emacs 25:

```elisp
 (font-info (font-info (face-font 'default)))
;; => Debugger entered--Lisp error: (wrong-type-argument stringp nil)
;;      font-info(nil)
```
Also, isn't this a 25-only function?

**Comment by kljohann** [comment]
As this may be related, `(aref font-info 10)` produces `args-out-of-range` for me:

```elisp
(face-font 'default)
"-unknown-PragmataPro-normal-normal-normal-*-16-*-*-*-*-0-iso10646-1"

(font-info (face-font 'default))
["-unknown-PragmataPro-normal-normal-normal-*-16-*-*-*-*-0-iso10646-1"
"PragmataPro:pixelsize=16:foundry=unknown:weight=normal:slant=normal:width=normal:scalable=true"
16 20 0 0 0]

(aref (font-info (face-font 'default)) 3)
20

(aref (font-info (face-font 'default)) 10) ;; -> args-out-of-range
```

**Comment by holomorph** [comment]
FWIW, `(font-at (point))` is `nil` in terminals so the new form still errors

**Comment by holomorph** [comment]
In GUI Emacs:
```
Debugger entered--Lisp error: (error "Specified window is not displaying the current buffer")
  font-at(54)
```

**Comment by tarsius** [comment]
And can you reproduce that after restarting emacs?

**Comment by holomorph** [comment]
Yep

**Comment by tarsius** [comment]
Well this function is being called while the current buffer is being displayed in the selected window. The code doesn't fiddle with the buffer or window. Can you figure out why that is not the case for you?

**Comment by johnmastro** [comment]
> FWIW, (font-at (point)) is nil in terminals so the new form still errors

I ran into this too

**Comment by tarsius** [comment]
> I ran into this too

That has been fixed. If `window-system` returns nil, then we don't insert any images.

**Comment by johnmastro** [comment]
Nice, thanks!

**Comment by holomorph** [comment]
Sorry, should have provided recipe: using g56e7d23

1. `C-x C-f /path/to/repo RET`
2. `M-x magit-status`
3. Go to the log `l l`
4. View a diff `n`

`Specified window...` gets thrown.  At this point the log view is broken in that doing `n` `p` in the log buffer never updates the diff window.  Doing `RET` on a commit will successfully bring up the diff, however

**Comment by tarsius** [comment]
> At this point the log view is broken in that doing `n` `p` in the log buffer never updates the diff window.

That's because that is done using one of those hooks that detect errors in hook functions and then remove the faulty function. Now that you mention it, I think I have seen that too.

**Comment by tarsius** [comment]
Hopefully that was the last one...

**Comment by tarsius** [comment]
Thanks for the reports!

**Comment by holomorph** [comment]
Nice, seems to be all fixed. Thank you
