### ISSUE TITLE
What happened to the "C" command?

### ISSUE THREAD

**Issue by peti** [magit/magit#2245]
Earlier versions of Magit allowed me to start a commit by pressing "C", which was equivalent to hitting "c c", only the message buffer would start up showing the name of the edited file in the first line. I find this very convenient, because I often preface my commit messages with the name of the file, i.e. 

> source-file-a: fixed bla bla bla issue

Is this functionality still present in current versions?

**Comment by tarsius** [comment]
It's only bound when point is on a hunk, which I felt makes sense because it always inserts a symbol name, not just the file name, and the function name is determined by searching the hunk.

**Comment by peti** [comment]
I see. Thank you for the quick answer.

From my point of view, it would be nice if "C" would also work when the point is over a modified file. That would save me at least two key presses (tab + <down>).

Also, I notice that the message is inserted at the *end* of the commit buffer now rather than on top, i.e.:

~~~~~


# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch work
# Your branch is ahead of 'origin/work' by 1 commit.
#   (use "git push" to publish your local commits)
#
# Changes to be committed:
#	modified:   .nixpkgs/config.nix
#

* .nixpkgs/config.nix: 
~~~~~

Is that intentional?

**Comment by tarsius** [comment]
> it would be nice if "C" would also work when the point is over a modified file

... in if it then only inserted the file name?

```lisp
(define-key magit-file-section-map "C"  'magit-commit-add-log)
```

Lets you use `C` on the file name, but I find it odd that it also inserts the first found symbol. (Did it behave like that in v1?)

> Is that intentional?

No of course not, but this feature has always been rather wacky, and I just haven't gotten around to fixing all the quirks.

**Comment by peti** [comment]
>> it would be nice if "C" would also work when the point is over a modified file
>
> ... in if it then only inserted the file name?

Yes, exactly.

> (define-key magit-file-section-map "C"  'magit-commit-add-log)

I am sorry for being dense, but how can I configure that setting in my ~/.emacs file while relying on autoloading magit? I don't require `magit` from the outset; so when I try to run that expression I get an error about undefined symbols. I am sorry, but my Emacs-fu is very weak.

**Comment by tarsius** [comment]
>>> it would be nice if "C" would also work when the point is over a modified file
>>
>> ... and if it then only inserted the file name?
>
> Yes, exactly.

And did it behave like that in an older release?

> how can I configure that setting ... while relying on autoloading magit

```lisp
(eval-after-load 'magit
  '(define-key ...))
```

**Comment by peti** [comment]
Ah, thank you very much. With that definition added to me ~/.emacs, the old behavior is (almost) restored. What is new is that `magit` adds information about the function or code section that was changed. When I committed the ~/.emacs change, for example, it offered

> * .emacs (magit): 

wereas old versions would have inserted only the file name. But this is a welcome feature, actually.

**Comment by tarsius** [comment]
> the message is inserted at the end of the commit buffer

That's because `(forward-comment -1000)` no longer works due to 5ffb4ce9c373c7b1f87b0d06bc1b531c12236ee1.

**Comment by tarsius** [comment]
I have reinstated the binding, but I have changed it so that it only inserts the file name again. It doesn't make much sense to insert only the the first change in this case, either all or none should be inserted. Inserting all is a task for another time.

**Comment by thierryvolpiatto** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> I have reinstated the binding, but I have changed it so that it only
> inserts the file name again.

Please consider reverting this, it was great as it was.
(Much better than in 1.4.2)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tarsius** [comment]
> Please consider reverting this, it was great as it was.

Which state was better? Did you also reinstate the file section binding locally and then press `C` on a file and expected that to also insert the first change. Because if not, then nothing changed in this regard.

By the way I intend to make some improvements here soonish.

**Comment by thierryvolpiatto** [comment]
Jonas Bernoulli <notifications@github.com> writes:

>     Please consider reverting this, it was great as it was.
>    
> Which state was better?

I have in my init file:

(with-eval-after-load "magit.el"
  (define-key magit-diff-mode-map (kbd "C") 'magit-commit-add-log))

When I commit I have the diff in other window, from this window, when I
move cursor on a part of the diff, magit insert in commit buffer:

* filename (function_or_var_at_point):

I would keep this behavior.

IIUC what you did is reverting to what 1.4.2 behavior, which was only:

* filename: 

Maybe I am wrong as I am actually locked to magit-2.2 (melpa-stable)
because current magit is broken for me.

-- 
Thierry

https://emacs-helm.github.io/helm/
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
