### ISSUE TITLE
Option or command for two-buffer non-read-only Ediff

### ISSUE THREAD

**Issue by noctuid** [magit/magit#2247]
Most of the time with `magit-ediff-stage`, I only want to have B and C shown (the index version and the buffer as on disk) like in `magit-ediff-show-unstaged` (but with A not read-only). If there isn't anything that I want to unstage, I'd rather be able to just use `b` instead of `cb` and not have an extra pane occupied by the head version that I don't really want to look at. I think it would be nice to have an optional argument or different commands to be able to have only the head and index version diffed (just unstaging) or only the index and on-buffer version diffed (just staging).

**Comment by tarsius** [comment]
* In https://github.com/magit/magit/issues/1743#issuecomment-76592075 (skip the bullet points) I explain why we actually need three buffers.
* #1883 (and related pressure elsewhere) is why I have added ediff variants with just two read-only buffers. I don't think they are very useful.

**Comment by noctuid** [comment]
I see this as a more safe default, but I'm not sure I understand why it's necessary. If I only want to just stage or just unstage and don't make any mistakes, aren't only two buffers needed?

> But to unstage (without risking losing work) them you also need the unstaged buffer.

I'm not sure I understand the meaning behind this. Is the implication that parts of the file as it exists on disk have been deleted or modified since part or all of it was staged? I'm not as interested in a command for unstaging with just two buffers, but in that case, I would be fine with losing those changes. It would be completely my fault. I've never had something like this happen either, so I'm not particularly concerned about this risk.

>  When you realize, that no, what you just unstaged should have remained staged, then you also need the unstaged changes in addition to the staged ones, or you would not be able to stage them again, as in Ediff that is done by copying from unstaged to staged.

Well to undo everything you did for the current ediff session, there is `ediff-restore-diff`. If I messed up just a specific part so that reverting everything wouldn't be convenient, as long as the file on disk hadn't been deleted or altered, I could just exit the current ediff session and then open one between the file in the staging area and the file as on disk. Again, if I did somehow lose staged changes doing this, I'd consider that to be my fault. Am I misunderstanding your point?

**Comment by tarsius** [comment]
a | b
c | d

**Comment by tarsius** [comment]
I'll probably write documentation that demonstrates what can go wrong when using two buffers. And maybe I will add wrappers for some of the ediff commands so that you could e.g. <kbd>s</kbd> instead of <kbd>cb</kbd>.

But this isn't a top priority and it might take a while until I get to this.

**Comment by tarsius** [comment]
I'll keep this in the back of my head, but since I don't actually have any intentions to implement this, I think the honest thing to do is to close this.

**Comment by cenouro** [comment]
Has this been implemented?

**Comment by noctuid** [comment]
No, but depending on you want, [vdiff](https://github.com/justbur/emacs-vdiff) might work instead of ediff.
