### ISSUE TITLE
Cannot stage changes

### ISSUE THREAD

**Issue by mrkkrp** [magit/magit#2248]
Currently when I press <kbd>s</kbd> in status buffer when point is on unstaged changes I get the following message:

> magit-mode-get-buffer: Wrong type argument: stringp, nil [13 times]

…and the changes are not staged, of course.

**Comment by mrkkrp** [comment]
Correction: this happens for a variety of actions, not only staging.

**Comment by tarsius** [comment]
I just pushed a fix.

**Comment by mrkkrp** [comment]
@tarsius, Thanks for the quick response!
