### ISSUE TITLE
20150908.806 - 's' results in 'Wrong type argument: stringp, nil'

### ISSUE THREAD

**Issue by gaydenko** [magit/magit#2249]
Hi! After update to 20150908.806 hitting `s` results in `Wrong type argument: stringp, nil` instead of staging.

**Comment by sooheon** [comment]
I have the same problem, and it is due to 69831f3. Reverting that commit solves the problem.

**Comment by tarsius** [comment]
I have already fixed this half an hour ago (#2248), but it may take up to two hours until a change hit Melpa.

**Comment by sooheon** [comment]
Ah you did, thanks!

**Comment by gaydenko** [comment]
@tarsius , thanks!
