### ISSUE TITLE
Stash creation error on W32+Cygwin

### ISSUE THREAD

**Issue by johnmastro** [magit/magit#2251]
I mentioned this in issue #2246 but an opening a separate issue since they appear to have different causes. I'm using Emacs 25, `git` 2.4.5 from Cygwin, Windows 7, and Magit from MELPA.

When I attempt to create a stash with `z z` I receive this backtrace:

    Debugger entered--Lisp error: (error "Cannot save the current worktree state")
      signal(error ("Cannot save the current worktree state"))
      error("Cannot save the current worktree state")
      magit-stash-create("On master: test-stash" t t nil)
      magit-stash-save("On master: test-stash" t t nil t)
      magit-stash("On master: test-stash" nil)
      funcall-interactively(magit-stash "On master: test-stash" nil)
      #<subr call-interactively>(magit-stash nil nil)
      ad-Advice-call-interactively(#<subr call-interactively> magit-stash)
      apply(ad-Advice-call-interactively #<subr call-interactively> magit-stash)
      call-interactively(magit-stash)
      magit-invoke-popup-action(122)
      funcall-interactively(magit-invoke-popup-action 122)
      #<subr call-interactively>(magit-invoke-popup-action nil nil)
      ad-Advice-call-interactively(#<subr call-interactively> magit-invoke-popup-action nil nil)
      apply(ad-Advice-call-interactively #<subr call-interactively> (magit-invoke-popup-action nil nil))
      call-interactively(magit-invoke-popup-action nil nil)
      command-execute(magit-invoke-popup-action)

Here are the things I've noticed stepping through `magit-stash-create` while trying to figure this out:

`conflicts` is `nil` and setting `index` here appears to succeed (`magit-commit-tree` returns a hash):

    (setq index (if conflicts
                    [...]
                  (magit-commit-tree (concat "index on " summary)
                                     nil head)))

Here's where I hit the error:

    (magit-with-temp-index index
      (when worktree
        (or (magit-update-files (magit-git-items "diff" "-z" "--name-only" head))
            (error "Cannot save the current worktree state"))) ; <- error
      [...])

But if I evaluate `(magit-update-files (magit-git-items "diff" "-z" "--name-only" "HEAD")` separately (outside `(magit-with-temp-index ...)` it successfully stages my unstaged changes.

`: stash save RET` works without error.

Let me know what other info I can provide.

**Comment by tarsius** [comment]
This very likely is a dublicate of #2049, just different symptoms. I have applied a fix.

**Comment by johnmastro** [comment]
I'm still seeing this error. I updated Magit, confirmed I have commit `5fdfe9d`, and recompiled in a fresh Emacs (a couple times). I also added `"CYGWIN=noglob"` to `process-environment`, which seems to fix the other issue.

If I set `magit-git-debug` to `t`, this is what I get in the `*magit-process*` buffer:

    128 c:/bin/git.exe … show --no-patch --format=%h %s ^{commit} --
    fatal: bad revision '^{commit}'

**Comment by tarsius** [comment]
I'll also need a backtrace with this because there are many places that could end up calling git like this by using `(magit-rev-format "%h %s" REV)`. The problem is that REV is nil, but where?

**Comment by et2010** [comment]
I have the same problem with emacs w64 24.5.1, cygwin git 2.6.2. I've tried previous release of magit but still got this error. I removed cygwin git, installed current [git for windows](https://git-scm.com/download/win) and problem solved. Hope this will help.

**Comment by npostavs** [comment]
Ah, we're missing a `magit-convert-git-filename` call.

@tarsius it's a bit unfortunate that `magit-git-debug` doesn't catch things like `(or (magit-git-success ...) (error "something went wrong"))`. Maybe we should have a separate function for git calls that we expect to succeed?
