### ISSUE TITLE
Log becomes empty in magit

### ISSUE THREAD

**Issue by cheunghy** [magit/magit#2252]
After upgrade to newest magic, when `magit-status`, and `l l`, the log just show `Commits in branch name (empty)`.

**Comment by Silex** [comment]
This is weird. Does git from console work as expected (e.g git status etc)?

How did you install magit?

**Comment by cheunghy** [comment]
@silex I upgrade from melpa. The gig on my command line still works, and all other commends work except log

**Comment by Silex** [comment]
Hum, try reinstalling magit and make sure no older version lurks around.

You can do that with `M-x find-function magit-status` then delete the directory (careful) that file is in and after you are sure no more magit is installed, `M-x package-install magit`.

**Comment by Silex** [comment]
Also, test with another repository.

**Comment by xuchunyang** [comment]
I just come across same issue for just one repo, can't reproduce for any other repos.

after `git checkout -b new-branch`, `git log` from shell is not empty, while `l l` after magit-status is.

**Comment by Silex** [comment]
what does `git status` say for that repo? any weird upstream?

**Comment by xuchunyang** [comment]
It does't matter what result of `git status` is, even working directory is clean. no special upstream

```
 helm-ls-git git:(improve-performance) gst
On branch improve-performance
nothing to commit, working directory clean

 helm-ls-git git:(improve-performance) PAGER= git log --oneline -3
0239e40 Check if sources are loaded by looping in helm-ls-git-default-sources.
7feb2c9 Merge branch 'master' of github.com:emacs-helm/helm-ls-git
4c10172 Allow customizing sources for `helm-ls-git-ls'(#37)

 helm-ls-git git:(improve-performance) git remote -v
origin	git@github.com:xuchunyang/helm-ls-git.git (fetch)
origin	git@github.com:xuchunyang/helm-ls-git.git (push)
upstream	git@github.com:emacs-helm/helm-ls-git.git (fetch)
upstream	git@github.com:emacs-helm/helm-ls-git.git (push)
```

**Comment by tarsius** [comment]
Set `magit-git-debug` to `t` and then check the process buffer (`$`).

**Comment by xuchunyang** [comment]
> Set magit-git-debug to t and then check the process buffer ($).

cannot describe '095aa15359fed953870a8f24edced6f80a893085'

PS. it is of https://github.com/emacs-helm/helm-ls-git

**Comment by xuchunyang** [comment]
Sorry, the previous is from `*Message*`, tried again, and in the process buffer, it now becomes:

```
128 git … log -256 --format=%h%d [%aN][%at]%s --decorate=full --graph --use-mailmap master~148..master --
fatal: bad revision 'master~148..master'
```

**Comment by tarsius** [comment]
Ah that's what I was afraid of. You can revert 55a61d15e85fe46409e512cc60815e61b4843066 to fix this for now.

**Comment by tarsius** [comment]
But also quickly check whether this is an off-by-one error, i.e. try `git rev-parse --verify master~147`.

**Comment by thierryvolpiatto** [comment]
Philippe Vaucher <notifications@github.com> writes:

> what does git status say for that repo? any weird upstream?

No, there is no problem with magit-2.2, this is just broken with last
magit.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997
