### ISSUE TITLE
magit-log-buffer-file shows (empty) for files not in the vcs root

### ISSUE THREAD

**Issue by arongp** [magit/magit#2254]
magit-version: Magit 20150909.1359, Git 2.5.1, Emacs 24.5.1

Open the magit.el and run M-x magit-log-buffer-file, the Magit Log buffer shows:
>Commits in master touching lisp/lisp/magit.el
>(empty)

You can see that threre are two lisp folders before the file name.

Tested with Windows 8.1 and Centos 7.

**Comment by kyleam** [comment]
Thanks.
