### ISSUE TITLE
Menu setting for Verbose Log

### ISSUE THREAD

**Issue by strow** [magit/magit#2257]
I'd like verbose logs.  Trying the menu for Log->Verbose Log I get the error:  Symbol's function definition is void: magit-log-verbose.   I cannot find this variable in the manual either.   I can see that this functionality probably isn't needed since the full log is shown after pressing l.

**Comment by tarsius** [comment]
The command `magit-log-verbose` no longer exists and a few days ago I have removed the leftover entry from the menu.

> I can see that this functionality probably isn't needed since the full log is shown after pressing l.

Normally  a "online" log is shown. To get a "verbose" log use one of the switches `--patch` or `--stat`.

**Comment by tarsius** [comment]
In any case it isn't possible to add "verbose log" to the menu.
