### ISSUE TITLE
`C-c p` binding for `magit-file-mode` should not be bound to mode specific map

### ISSUE THREAD

**Issue by dgtized** [magit/magit#2261]
http://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html

`C-c p` is reserved for users. That is the reason why modes such as projectile that do use it go to all the trouble of making it easy to change the default prefix for the mode, and heavily document that they use that binding. I think this would be better suited to show up in the magit-file-popup, and if a user personally wants to bind `C-c p` to `magit-blob-previous` then they are welcome to.

In the meantime a temporary fix is of course:

```
(eval-after-load 'magit
  '(define-key magit-file-mode-map "\C-cp" nil))
```

**Comment by tarsius** [comment]
Apparently I didn't spend to much time when I picked the key binding...

Any suggestion for a better binding? Would `C-c C-p` be better?

**Comment by dgtized** [comment]
`C-c c-p` would certainly be an improvement over `C-c p`. I do maintain that this should be part of the per file popup menu under `C-c M-g`, along with a binding for `magit-blame`. Alternatively `C-x v p` is open under the vc prefix and there are other available bindings there.

**Comment by tarsius** [comment]
Okay. Done what you suggested. Thanks for bringing this to my attention.
