### ISSUE TITLE
Sometimes diff is shown in "raw" form in status buffer

### ISSUE THREAD

**Issue by mrkkrp** [magit/magit#2262]
I could not find out specific preconditions to that, sometimes diff is shown in “raw” form, as plain text and it's not possible to interact with it in any way:

```
Unstaged changes:
diff --git README.md README.md
index 40886e4..2796629 100644
--- README.md
+++ README.md
@@ -1,6 +1,7 @@
…diff goes here…
```

**Comment by mrkkrp** [comment]
Now I'm sure it happens always (but it happened before in somewhat random fashion).

**Comment by mrkkrp** [comment]
By the way it's currently impossible to use Magit at all. Am I the only one who experience this?

**Comment by mrkkrp** [comment]
I cannot stage "manually" too (or can I can't say, minibuffer says "Quit"). Then if I try to commit I see "error in process sentinel: quit".

**Comment by tarsius** [comment]
Do you use Windows? That's always a good first question when "nothing works" :-/

Also what Git version do you use? Maybe a very old version or to the contrary a v2.6 pre-release? (I saw some things in the relnotes that sounded like I might have to make adjustments.)

> By the way it's currently impossible to use Magit at all. Am I the only one who is experiencing this?

Try `emacs -Q ...`.

**Comment by mrkkrp** [comment]
@tarsius, Arch Linux, recently updated stuff, may that's the problem. As I understand my case is somewhat unique... I'll try to investigate.

**Comment by mrkkrp** [comment]
Git 2.5.1

**Comment by mrkkrp** [comment]
@tarsius, OK, it seems to work without config. I'll try gradually enable stuff until I find out what is cause of this. I'll report here it is something that others may encounter as well.

**Comment by mrkkrp** [comment]
This causes it:

```emacs-lisp
(advice-add 'narrow-to-region :after (η #'keyboard-quit))

;; where η is defined like this:

(defmacro η (fnc)
  "Return function that ignores its arguments and invokes FNC."
  `(lambda (&rest _rest)
     (funcall ,fnc)))
```

I cannot imagine why it is so. Can you tell me why I cannot advise this function?

**Comment by npostavs** [comment]
Um, you know `keyboard-quit` throws a signal right? That means anyplace that calls `narrow-to-region` gets broken by your advice.

**Comment by mrkkrp** [comment]
OK, this is understandable. Another question is that what if I want to disable region every time I run this command? Since it's interactive function I thought it's rather for end-users. Of course it's Emacs and everything is interconnected. Now I'll need to define special version of this command for me to use...

**Comment by npostavs** [comment]
> Another question is that what if I want to disable region every time I run this command?

`deactivate-mark`?

**Comment by mrkkrp** [comment]
@npostavs, yeah, that piece of code was quite old. But now I would rather write new function. Who knows, maybe Magit depends on existence of region after narrowing?

**Comment by npostavs** [comment]
> maybe Magit depends on existence of region after narrowing?

It doesn't even depend on the existence of the region before narrowing. When calling `narrow-to-region` it passes 2 positions, as per the doc string:

```
narrow-to-region is an interactive built-in function in `C source
code'.
....
When calling from a program, pass two arguments; positions (integers
or markers) bounding the text that should remain visible.
```
