### ISSUE TITLE
(require 'magit) blocked by something?

### ISSUE THREAD

**Issue by unknownzerx** [magit/magit#2266]
OS X 10.11 GM, Magit 20150916.450, Git 2.3.2 (Apple Git-55), Emacs 24.5.1

I found that if I have connected to the VPN (crossing the China F*** Wall), M-x `magit-status` will run normally. Else `(require 'magit)` seems to be blocked by something.

If I run `magit-status` with VPN connected and then disconnect it, subsequent magit operations seem to be normal.

I have tried remove `init.el`, deleting tramp file or any emacs history file. It doesn't help.

**Comment by npostavs** [comment]
Try setting `tramp-ssh-controlmaster-options`?

See [Emacs 24.5 hangs when loading Magit](http://magit.vc/manual/magit/Emacs-245-hangs-when-loading-Magit.html)

**Comment by unknownzerx** [comment]
@npostavs thanks,

Well the blocking is caused by, in `tramp-loaddefs.el`:
```elisp
;; ...
(call-process "ssh" nil t nil
  "-o" "ControlPath=%C" "host.does.not.exist")
;; ...
```
`ssh -o ControlPath=%C host.does.not.exist` stuck instead of going error quickly. It should has something to do with my router configuration.
