### ISSUE TITLE
Retain point while staging chunk by chunk.

### ISSUE THREAD

**Issue by ChillarAnand** [magit/magit#2267]
https://emacs.stackexchange.com/questions/16671/retain-point-in-magit-while-staging-chunk-by-chunk

**Comment by ChillarAnand** [comment]
@tarsius `magit-stage` is changing vertical scroll position, i guess it shouldn't do it by default?

**Comment by tarsius** [comment]
That's expected since the buffer content is being recreated and we make no attempt to *restore* the vertical scroll position. I don't think it would be worth it.

**Comment by ChillarAnand** [comment]
is there any way for users to preserve it?

**Comment by tarsius** [comment]
You could try advising `magit-refresh-buffer` to store the value and then use `magit-refresh-buffer-hook` to restore it.
