### ISSUE TITLE
Backporting Magit v2 to Git v1.8

### ISSUE THREAD

**Issue by fommil** [magit/magit#2269]
I've read the FAQ on this and unfortunately I have absolutely no possibility of upgrading git in my corporate environment. I'm sure they will eventually but it will be years.

What are the technical challenges involved in supporting git 1.8? How much work would it be to write a backport or compatibility layer to support git 1.8 in magit? Which features would never be available?

**Comment by fommil** [comment]
(btw, I cannot use any of the other comm channels due to firewall rules, so feel free to close and we can continue discussing in the closed ticket)

**Comment by tarsius** [comment]
I don't know what features should break. You'll have to just try and whenever something doesn't work as expected, assume that the old git is the reason. You won't always get lucky and get an error message.

One thing that will probably happen is that no diffs will be shown (at least not in the diff buffer, where you would see `(empty)` instead). Setting `magit-git-debug` to `t` will insert the error message into the process log buffer. Probably we use an argument that didn't exist in 1.8 yet. You might or might not be able to drop it.

Setting `magit-git-debug` to `t` causes a slow down and you will also get many false-positives, for example you will get many messages about `git describe ...` having exited with 128 - those are expected and can just be ignored.

**Comment by phil-s** [comment]
Remember that you can still use Magit 1.x instead.

**Comment by Silex** [comment]
@fommil: can't you build & install git locally? that doens't require administrative rights

**Comment by fommil** [comment]
All use of software is strictly controlled.

1.x was good at the time, but 2.1 is so much better :-)

**Comment by Silex** [comment]
@fommil: ah, sad. I'm always amazed by companies that put such restrictions on developers, it never made sense to me...

**Comment by fommil** [comment]
I just tried, even `magit-status` is empty. All it says, even with debugging on, is `(No files need saving)` in the minibuffer :-(

I'll have to investigate further when I'm at home. But it looks like magit 1.x is the only option for now.

**Comment by fommil** [comment]
uuuh, actually, how do I install magit 1.x? The instructions on the wiki are a bit old and I can't find `git-commit-mode` anymore.

**Comment by tarsius** [comment]
Well if you can get your company to move some $$$$ my way... (I hope you're doing these experiments during work hours, because then at least one of us is getting payed for dealing with their stubbornness).

**Comment by fommil** [comment]
I wish. No, all experimentation will be on my time. Although I'd personally be willing to pay you to add git 1.8 support if it wasn't an astronomical charge :-/

**Comment by tarsius** [comment]
You'll need to clone the `git-modes` repository and checkout a revision before `git-commit-mode.el` and `git-rebase-mode.el` were removed (actually I think they were first renamed, so you will need a revision before that).

**Comment by fommil** [comment]
ok. Well I am not allowed to download sources in work until they are approved, so I will have to experiment at home later before I raise a request to have it approved for internal use.

**Comment by tarsius** [comment]
> Although I'd personally be willing to pay you to add git 1.8 support if it wasn't an astronomical charge :-/

Problem is I have to figure out how to get payed at all (well more than what is currently being donated). So I am afraid unless I do ask for a large sum, this would actually set me back. It would delay other work I intend to finish before finally doing a proper fund raiser.

**Comment by fommil** [comment]
what is a large sum? (probably more than I can afford)

**Comment by tarsius** [comment]
$4000. For that I would maintain a `git-1.8` branch for a year. As I said, I don't remember what current features require a more recent version. That sum is probably a pretty good pay for the amount of work required to determine that and provide workarounds (though some features might have top be dropped altogether). But there's also the recurring work load of having to check all new features for compatibility and then possibly doing the work twice. And it's only work and nothing else - I would find very little pleasure in maintaining a backport, which is why I would want to be compensated accordingly.

**Comment by fommil** [comment]
Yeah, too rich for me :-) I could probably stretch to $750 without the one year support because of the incredible value that magit gives me.

**Comment by fommil** [comment]
I probably don't use most features. Heavy user of status, rebase, and diff/stage.

**Comment by tarsius** [comment]
@fommil A generous offer and almost to much to take from a single person. I'll release v2.3 and then decide whether I want to do it.

**Comment by fommil** [comment]
:-)

**Comment by tarsius** [comment]
I've just pushed this a few minutes ago: http://magit.vc/elpa/v1/.

**Comment by fommil** [comment]
BTW, I've been using magit 1 on a windows machine on a humongous repository. Git is slow (5 secs for status) and magit is really slow. Not much I can do about git (even assume unchanged on whole trees doesn't seem to make a difference) but I'll try to do a profile to work out what is causing the slowdown and see if I can optimise it somehow.

**Comment by tarsius** [comment]
Good `.gitignore` rules help and so does showing logs without `--graph`.

**Comment by fommil** [comment]
good news! My work had a trial version of git 2.1 all along, so I no longer need this support :-)

**Comment by fommil** [comment]
But thank you so much for creating the magit v1 ELPA repo. It was incredibly useful and, if any issues come up with this trial version of git, at least I have a magit fallback.
