### ISSUE TITLE
fetch a specific revision or maybe a repo

### ISSUE THREAD

**Issue by stardiviner** [magit/magit#2272]
Here is my case:

When someone give me a link, which could be a repo link, or a revision blob, or patch, or diff etc.
I hope I can use magit to input this link, and fill in some other info, then magit can auto fetch what I need.
Magit doesn't need to fetch whole repositor at first unless explicityly specified. if visit a revision blob, just fetch that. when magit open it, and user press some keybinding, like jump to next blob (This maybe need to download whole git repo info to get all blob index?), then magit continue to fetch the next blob.
I don't know whethere Git can allow user to apply on this case. (I hope it can)
Anyway, what do you think?

**Comment by tarsius** [comment]
A repository link you can consume by creating a new clone with `M-x magit-clone` or by adding it as an additional remote using `Ma`. A branch associated with a pull request you can fetch with `magit-branch-pull-request` from [`magit-rockstar.el`](https://github.com/magit/magit-rockstar).

> if visit a revision blob, just fetch that

It seems to be possible to fetch individual blobs using `git archive`, see http://stackoverflow.com/questions/1125476/retrieve-a-single-file-from-a-repository and other search results for "git fetch individual blob" or such.

> and user press some keybinding, like jump to next blob

And this is where things start to get complicated. You could look at a blob that was somehow retrieved but that blob isn't connected to anything. So you can just look at it and nothing else. With a lot of effort we could implement navigational features and then fix the resulting bugs, but I don't think it is worth the effort. Just add the remote, look at the blob, delete the remote, and wait for the garbage man.

**Comment by stardiviner** [comment]
@tarsius I see, thanks very much for giving out details about how to do upper steps.

About the last complicated thing, will it possible to fetch whole blob history index, download it, then user can navigate on it.

**Comment by tarsius** [comment]
A blob index exists, but it is equivalent to just fetching all refs, more or less.

**Comment by stardiviner** [comment]
I see, right, fetch a specific revison is still a good idea. thanks if you can implement it. really help on checking out people send links. I will use your mentioned method currently. And I think that function can be bind to global keybinding. So user can use it anywhere.

**Comment by tarsius** [comment]
I don't intend to implement this, sorry.
