### ISSUE TITLE
Is it possible to automatically switch to magit-status buffer after magit-commit in magit 2.1+?

### ISSUE THREAD

**Issue by zmwangx** [magit/magit#2273]
My typical workflow in magit is `magit-status` ==> do the necessary diffing and staging ==> `c c` (`magit-commit`) when it's time for a commit ==> followed immediately by a `P P` (`magit-push-current`) most of the time. If memory serves, in magit 1.4, after finishing `magit-commit`, the active buffer will automatically switch back to the `magit-status` buffer, allowing me to `P P`. However, in magit 2.1+, the active buffer automatically switches to the buffer I'm editing prior to `magit-status`, and by habit I'll type `P P` immediately nevertheless, which is very annoying.

I wonder if there's an option to customize this behavior? I've read the [relevant section of the manual](http://magit.vc/manual/magit/Committing.html) and briefly browsed through the source code, without seeing such an option. If it's indeed not there, please consider this a feature request. Thank you.

**Comment by tarsius** [comment]
This should still work, because we actually restore the window configuration after finishing the commit. See `with-editor-return` which is called by `with-editor-finish`. You could add a debug statement in there to assert that `winconf` is non-nil to narrow the issue down.

**Comment by zmwangx** [comment]
Thanks for the suggestions. I inserted `(assert winconf)` into `with-editor-return` and indeed, `winconf` appears to be `nil` if I simply open a file with Emacs, bring up `magit-status`, then `magit-commit`. I noticed that this isn't an issue if I run Emacs directly — the `magit-status` buffer is restored after the commit; however, the issue I described occurs when running an `emacsclient`, which is what I use all the time. Any ideas?

**Comment by tarsius** [comment]
Yes, the previous window configuration is stored by the Magit command which invokes `git commit`, so when you commit from outside Magit then it is not stored. You could try replacing this:

```lisp
(add-to-list 'with-editor-server-window-alist
             (cons git-commit-filename-regexp 'switch-to-buffer))
```

with something that does store the configuration.

**Comment by zmwangx** [comment]
Thank you for your patience. Please excuse me for being thick (not into elisp, sorry), but I don't quite get

> the previous window configuration is stored by the Magit command which invokes `git commit`, so when you commit from outside Magit then it is not stored.

I mean, when I `c c` from the magit status buffer, is that considered "commit from outside Magit"? I thought that the winconf ought to be saved by `with-editor`, which is called in `magit-run-git-with-editor`, which is in turn called in `magit-commit`, which is called with `c c`? And why does that restore the correct window configuration (despite `winconf` being `nil`) in a standalone Emacs instance, but not in client-server mode (as I pointed out above)? And my theory is: since `with-editor` uses an Emacsclient as editor, it can't restore winconf in another client that I explicitly spun up in the first place (I can't understand the entirety of `with-editor.el`, so I can't say anything for sure)?

And please let me know if it's too much hassle to answer questions on the issue tracker, and I'll move to mailing list or SE instead.

**Comment by tarsius** [comment]
I misunderstood that's of course not "outside of magit" (committing from the command line would be).

> And please let me know if it's too much hassle to answer questions on the issue tracker, and I'll move to mailing list or SE instead.

No let's keep investigating here.

**Comment by zmwangx** [comment]
Sorry, I think I was misleading you all along. I noticed that `with-editor-previous-winconf`, and hence `winconf`, is **not `nil`** after `magit-commit` (and hence `magit-commit-diff`) is invoked, whether in client mode or not. I probably inserted the `assert` statement in the wrong scope previous testing. Sorry about that.

**Comment by zmwangx** [comment]
After another round of grinding, I think I might have tracked down the issue. The problem is that the `with-editor-previous-winconf` saved from `magit-commit-diff` is the window configuration with the `COMMIT_EDITMSG` buffer selected. When the window configuration is restored in `with-editor-return`, the `COMMIT_EDITMSG` buffer is either already gone or will be gone the next instant, so there's no guarantee which buffer will be selected when the editor returns.

**Comment by tarsius** [comment]
That seems to be the case indeed. But somehow it worked as intended until now, at least for me. How many windows are in the frame? I'll look into migrating this feature into `with-editor` since that already advises functions from `server`, which is necessary because that isn't customizable enough for our needs.

**Comment by zmwangx** [comment]
> How many windows are in the frame?

For me, usually just two: one for file editing, one for magit status; or during magit-commit, one for editing commit message, and one for diffs.

**Comment by zmwangx** [comment]
Btw, the buffer selection issue isn't only present when using client-server. Even in the standalone case, if you do something funny during commit message editing, say switch to the `*scratch*` buffer in `COMMIT_EDITMSG`'s window and back, what you'll get after `with-editor-return` will be `*scratch*` instead of the magit status buffer.
