### ISSUE TITLE
Make a separate magit-1 ELPA package available for easy installation of 1.x

### ISSUE THREAD

**Issue by phil-s** [magit/magit#2277]
Issue #2269 was the latest one to make me think that an easy way to install 1.x would be valuable for people who lack the pre-requisites for 2.x (and who are not in a position to remedy that situation).

**Comment by tarsius** [comment]
Please test http://magit.vc/elpa/v1.

**Comment by phil-s** [comment]
Thanks tarsius, that works well.

What are your thoughts on the package name including the version? i.e. So people can explicitly `package-install magit-v1` rather than `magit` (which might conflict with what they can see in other package archives).

I guess if the name was different, people could easily have conflicting versions installed simultaneously, and might manage to load them both?

I'll test installing v2 and then downgrading to v1...

**Comment by phil-s** [comment]
It's probably worth telling people to pin `git-commit-mode` as well? AFAIK it's unlikely to conflict with any other package, but you *do* need it to come from the correct archive if that situation ever arose. I guess that's a far more generic ELPA issue, really, but I'd probably still be inclined to get people to do it, so I'd say the following should go in the documentation:

    (add-to-list 'package-pinned-packages '(magit . "magit-v1"))
    (add-to-list 'package-pinned-packages '(git-commit-mode . "magit-v1"))

**Comment by tarsius** [comment]
I have added instructions to remove v2 and `git-commit`. The other packages don't conflict, and might be required by other, unrelated packages. I have also added code showing how to add an entry to `package-pinned-packages`. I am not suggesting that `git-{commit,rebase}-mode` be pinned because I think that the changes of that appearing on some other archive are minimal.

**Comment by phil-s** [comment]
Cheers tarsius. I'd suggest that you reference this in each of the following sections of the manual:

* http://magit.vc/manual/magit/I-am-using-an-Emacs-release-older-than-244.html
* http://magit.vc/manual/magit/I-am-using-a-Git-release-older-than-194.html
* http://magit.vc/manual/magit/Installation.html

I've added a mention to the FAQ+ on the Wiki.
