### ISSUE TITLE
Handle prompts that arise from git commands that result in remote access (password/2fa etc.)

### ISSUE THREAD

**Issue by IvanMalison** [magit/magit#2283]

**Comment by tarsius** [comment]
`magit-process-match-prompt`

**Comment by IvanMalison** [comment]
Cool, that is pretty similar to what I need, but it seems like there should be a way to match arbitrary prompts without having to completely override the filter function completely.

**Comment by npostavs** [comment]
`magit-process-password-prompt-regexps`?

**Comment by IvanMalison** [comment]
This would be for things that aren't password prompts.

**Comment by npostavs** [comment]
> This would be for things that aren't password prompts.

Like what? Your title says "password/2fa", and `magit-process-password-prompt-regexps` already contains `"^Yubikey for .*: ?$"`. I believe yubikey would an example of 2fa, no?

**Comment by tarsius** [comment]
Please open a pr which adds the appropriate regexps to `magit-process-password-prompt-regexps`, and provide example prompts in the commit message.
