### ISSUE TITLE
magit get stuck at "Running git pull"

### ISSUE THREAD

**Issue by seudut** [magit/magit#2285]
when I runing Pulling to current, I see the "Running git pull" in minibuffer, and never disappear. then I check the magit-process buffer, here is the output, looks like it open vim in the magit-process which cause the stuck.

run git … pull

~                                                                               [9;1H~                                                                               [10;1H~                                                                               [11;1H~                                                                               [12;1H~                                                                               [13;1H~                                                                               [14;1H~                                                                               [15;1H~                                                                               [16;1H~                                                                               [17;1H~                                                                               [18;1H~                                                                               [19;1H~                                                                               [20;1H~                                                                               [21;1H~                                                                               [22;1H~                                                                               [23;1H~                                                                               [1;1H

**Comment by seudut** [comment]
I checked my git config, the core.editor is vim. I don't know if this is related.

**Comment by tarsius** [comment]
Check for git variables `*.color` whose value you have set to `always`. Set them to `true` instead (which is the default, so you might as well just remove your customization).

**Comment by seudut** [comment]
thanks, tarsius,
but which variables do you mean? I don't find any `*.color` variable in `git config -l` except `color.ui`, which is set `color.ui=auto`. do you mean this variable? I also tried by setting this to `false`, but it doesn't work, `git pull` still stuck

**Comment by tarsius** [comment]
Then it's probably not that.

Do you see control characters in the output of all git invocations? If not then do you see them for all remotes when using `git pull` or just this one (the remote might seen some message with control characters I supposed)? What makes you think that vim, or any other editor for that matter, is involved (I don't think `git pull` ever needs an editor)?

Regardless of what mess you see in the process log buffer, it shouldn't really matter. `git pull` might ask for a username and password, but you should configure git to not do so. Normally you should use a public key. If that doesn't work and you are on Windows, then see https://github.com/magit/magit/wiki/Pushing-with-Magit-from-Windows.

**Comment by seudut** [comment]
When I use `git pull` on terminal on Mac OSX, it indeed open vim with a merge message. and I am using a public key,  and don't need any credentials.

here is the output, it similar to my vim (you can see the 'NERDTree' in the last line, it my vim's plugin) .  I am not sure if it's required to open a editor for  `git pull`, maybe there are some config for this.



run git … pull
remote: Compressing objects: 100% (2/2), done.        
remote: Total 3 (delta 1), reused 3 (delta 1), pack-reused 0        
Unpacking objects: 100% (3/3), done.
From github.com:seudut/Calculator
   3ca8ce9..3dee2b8  master     -> origin/master
[?1002h[24;1H"~/temp/Calculator/.git/MERGE_MSG"                                             [24;36H7L, 281C[1;1H 1 .g/MERGE_MSG                                                      X  tabs [2;1H1   Merge branch 'master' of github.com:seudut/Calculator                       [3;1H  1                                                                             [4;1H  2 # Please enter a commit message to explain why this merge is necessary,     [5;1H  3 # especially if it merges an updated upstream into a topic branch.          [6;1H  4 #                                                                           [7;1H  5 # Lines starting with '#' will be ignored, and an empty message aborts      [8;1H  6 # the commit.                                                               [9;1H~                                                                               [10;1H~                                                                               [11;1H~                                                                               [12;1H~                                                                               [13;1H~                                                                               [14;1H~                                                                               [15;1H~                                                                               [16;1H~                                                                               [17;1H~                                                                               [18;1H~                                                                               [19;1H~                                                                               [20;1H~                                                                               [21;1H~                                                                               [22;1H~                                                                               [23;1H N  .git/MERGE_MSG                         [~/temp/Calculator]  1, 1/7 14% [24;1HNERDTree: 1 invalid bookmarks w...NERDTreeInvalidBookmarks for info.[2;5H

**Comment by tarsius** [comment]
I think I can do something about that, stay tuned for more :-)

**Comment by seudut** [comment]
Just update,
Yes, there is a config of asking for commit message when `git pull` 

<http://stackoverflow.com/questions/14649929/git-asks-for-commit-message-when-pulling-from-other-branch>

 put export GIT_MERGE_AUTOEDIT=no` in `.bashrc`, then the issue is gone. no need to open editor for `git pull` any more.

**Comment by tarsius** [comment]
Meanwhile, setting the GIT_EDITOR to emacsclient should do the trick.

**Comment by seudut** [comment]
I just tried this setting, looks like I don't config emacsclint or emacs daemon. it output the following error.
P.S. I have never use emacsclient or emacs darmon before.


 1 git … pull
emacsclient: can't find socket; have you started the server?
To start the server in Emacs, type "M-x server-start".
emacsclient: No socket or alternate editor.  Please use:

        --socket-name
        --server-file      (or environment variable EMACS_SERVER_FILE)
        --alternate-editor (or environment variable ALTERNATE_EDITOR)
error: There was a problem with the editor 'emacsclient'.
Not committing merge; use 'git commit' to complete the merge.

**Comment by tarsius** [comment]
Unless the upstream branch actually is a local feature branch, one should avoid merging that into the current branch. Otherwise you end up with commits like `Merging remote tracking branch 'origin/master`, and may people don't like that. The remotes are not in the "correct" order, the published history should be the first parent of the merge and your new work should be the second parent. I am sure a tone of blob posts on the subject can be found, so I don't want to go into that more.

And instead concentrate on the technical issue ... (heading back to emacs) ...

**Comment by tarsius** [comment]
That should fix it.
