### ISSUE TITLE
Log results unexpectedly limited

### ISSUE THREAD

**Issue by phil-s** [magit/magit#2287]
Magit 2.2.2-108-gcee8490, Git 2.3.5, Emacs 24.5.1

I'm seeing unexpectedly-truncated log results when examining a single file with `l l` (or `l h` or `l o master`, but those should indeed be the same as one another in this instance).

I was looking at the repository for Emacs, and searching the changes to `lisp/dired.el`. I was initially getting no results at all with the log search options for something I was sure must be present.

I then used `l =f lisp/dired.el l` to do a plain "Log current" (with no search filters) for that file, and found that the log only went back 4 months / a dozen changes.

If I use any of `l L`, `l b`, or `l a` with the same `=f` filter, I see far more history.

If I use `l l` *without* a file filter, the log also goes back a long way, and lists commits which were only visible with `l L`, `l b`, or `l a` when the file filter was active.

**Comment by phil-s** [comment]
I see that ultimately (in the git command) `l l` here is using a range of `master~1024..master` which at least explains the output I'm seeing.

**Comment by phil-s** [comment]
Looks like this is from #2243 ?

If this is intended as a more-than-short-term-temporary change, I feel that the UI needs to reflect the range constraint.

**Comment by tarsius** [comment]
This should do the trick:

```lisp
diff --git a/lisp/magit-log.el b/lisp/magit-log.el
index 363dfaa..8f54aff 100644
--- a/lisp/magit-log.el
+++ b/lisp/magit-log.el
@@ -655,6 +655,12 @@ (defvar magit-log-remove-graph-re
   (concat "^" (regexp-opt '("-G" "--grep" "--follow")))
   "Regexp matching arguments which are not compatible with `--graph'.")
 
+(defvar magit-log-disable-graph-hack-args
+  '("-G" "--grep" "--author")
+  "Regexp matching arguments which disable the graph speedup hack.
+Because using that hack when these arguments are present would
+actually cause a slowdown.")
+
 (defvar magit-log-use-verbose-re
   (concat "^" (regexp-opt '("--patch" "--stat")))
   "Regexp matching arguments which trigger the use of verbose log.")
@@ -675,8 +681,12 @@ (defun magit-log-refresh-buffer (revs args files)
                    (setq revs (car revs))
                    (not (string-match-p "\\.\\." revs))
                    (not (member revs '("--all" "--branches")))
-                   (magit-git-string "rev-list" "--count"
-                                     "--first-parent" revs))
+                   (let ((re (concat "^" (regexp-opt
+                                          magit-log-disable-graph-hack-args))))
+                     (--none-p (string-match-p re it) args))
+                   (--none-p (string-prefix-p it "") args)
+                   (magit-git-string "rev-list" "--count" "--first-parent"
+                                     args revs))
     (setq revs (let ((cutoff (max 1024 (* 2 magit-log-cutoff-length))))
                  (if (< (string-to-number it) cutoff)
                      revs
```
