### ISSUE TITLE
Cannot bisect run?

### ISSUE THREAD

**Issue by Silex** [magit/magit#2290]
Hello,

`bisect run` seems a bit weird at the moment... it's directly available on the bisect popup instead of being available *after* you did bisect start. If you try to use it it (rightly) complains that bisect hasn't started yet.

Atm that forces me to use bisect run from the command line.

**Comment by tarsius** [comment]
`run` doesn't have to be invoked manually at every step I believe. I have never actually used this, but the documentation makes it sound that way in my ears. It talks about exit codes and such, not printing "this is bad/good". So I would assume that this automatically calls `good` or `bad`, and that causes the search to continue (unless we already found the first bad commit).

So it seems that I assumed that `run` could also be used to begin the search, without actually testing it. Assuming that the above is correct, we can implement that by teaching `magit-bisect-run` to first do what `magit-bisect-start` does if no sequence is in progress yet. I think it would make sense if one could specify the test script along with a known good and a known bad commit up front.

**Comment by tarsius** [comment]
Maybe you could look into that some more?

**Comment by Silex** [comment]
The workflow is like this:

* You start a bisect: `git bisect start GOOD_REV BAD_REV`
* You then have two choices:
  * Mark a revision as good/bad (`git bisect good`)
  * Run `git bisect run` which will mark revisions as good/bad for you.

**Comment by Silex** [comment]
I think it makes more sense to mimic the natural git workflow... that is the first popup only offers "start" and then the 2nd popup offers reset/good/bad/run/visualize/etc

That said, maybe on the first popup there could be an option like "Start & Run" which would do what you suggested.

**Comment by Silex** [comment]
See the examples section of http://git-scm.com/docs/git-bisect to see how to use `run`.

**Comment by tarsius** [comment]
Since the discussion has move to #2294, I am closing this.
