### ISSUE TITLE
magit-reset-index resets HEAD

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2296]
Hello,

my magit version is the current Melpa one.

Whenever I use U on a commit (magit-reset-index), the HEAD points to the same commit afterwards (which it should not).  If I hit U on a wip index backup, the HEAD even points to the wip branch!  I have to use the reflog to restore the previous state.

Magit uses

    git reset <commit> --

which should not change the head according to its doc, but it does.  Is this even a bug in git reset, or am I missing something?

Thanks,

Michael.

**Comment by michael-heerdegen** [comment]
BTW, what works for me (as I expect) is

     reset && read-tree <commit>

**Comment by kyleam** [comment]
The docstring for magit-reset-index is wrong (except for the special but
frequent case when commit is HEAD).  'git reset <commit> --' falls under
the third form described in its man page, which involves HEAD being
moved to the commit.

**Comment by michael-heerdegen** [comment]
Kyle Meyer <notifications@github.com> writes:

> The docstring for magit-reset-index is wrong (except for the special but
> frequent case when commit is HEAD).

Mmh, ok, though, the functionality described in docstring seemed useful
to me.  E.g to restore a wip save of a previous index.  And it seems the
name is wrong as well?  I wonder which behavior was originally intended.

> 'git reset <commit> --' falls under the third form described in its
> man page, which involves HEAD being moved to the commit.

Ahh - because no paths are given?  I don't like these man page pseudo
grammers...

Thanks, Michael.

**Comment by kyleam** [comment]
> Mmh, ok, though, the functionality described in docstring seemed useful
> to me.  E.g to restore a wip save of a previous index.  And it seems the
> name is wrong as well?  I wonder which behavior was originally intended.

I suspect you're right that it describes the intended behavior,
especially since magit-reset-head currently does the same thing as
magit-reset-index.  Perhaps a "." was intended for the path.

>> 'git reset <commit> --' falls under the third form described in its
>> man page, which involves HEAD being moved to the commit.
>
> Ahh - because no paths are given?  I don't like these man page pseudo
> grammers...

Yep.  In the first form, paths aren't optional, and, in the second,
paths are optional, but --patch or -p must be given.

**Comment by tarsius** [comment]
> I wonder which behavior was originally intended.

Me too :-)

**Comment by tarsius** [comment]
Will have to look into that.

**Comment by tarsius** [comment]
I'll have to look into the past, but since I am currently working on pickaxe support, I'll delay that until I am done with that.

I have however bound <kbd>U</kbd> to `magit-unstage-all` again, instead of this command. This is supposed a generalization (that much I remember), but at least I never actually used this command for anything expect for the "unstage all" case. There was some discussion about this some time back, and I have changed my mind about it. The default should be what most users would expect, they shouldn't have to change a key binding to get that, and advanced users can get the advanced variant by changing a key binding.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> I have however bound U to magit-unstage-all again, instead of this
> command.

Ok by me.

FWIW, in my original use case, I wanted to restore a former index state
that had been recorded by a wip save.  That U can't do this is not a
problem, but there should be mean to do that from within Magit (or is
there one I oversaw?), else, the wip saves of the index are of not much
use.

**Comment by tarsius** [comment]
> That U can't do this is not a problem, but there should be mean to do that from within Magit (or is there one I oversaw?)

Well <kbd>a</kbd> doesn't quite cut it, and what you are mentioning is indeed a useful use case. I think I will fix `magit-reset-index` to do what it's documentation promises and create a new command which does what that command used to do.

**Comment by kyleam** [comment]
> I think I will fix magit-reset-index to do what it's documentation promises 

I think that can be done just by adding a period as the path argument.

> and create a new command which does what that command used to do.

There is already magit-reset-head, which currently runs the same command.

**Comment by tarsius** [comment]
> > I think I will fix magit-reset-index to do what it's documentation promises 

> I think that can be done just by adding a period as the path argument.

Almost. The path has to come at the end of the command line.

> > and create a new command which does what that command used to do.

> There is already magit-reset-head, which currently runs the same command.

Now that you mention it ... :-)

Or <kbd>x</kbd> (`magit-reset` without a prefix argument), which I use every day ...

**Comment by michael-heerdegen** [comment]
Would it make sense to let x (magit-reset) with a negative prefix arg call the new `magit-reset-index'?  The latter is hard to discover without having any key binding at all.
