### ISSUE TITLE
reflog shows the "wrong" dates

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2297]
Hello,

I recently wondered why what I got with r l was not in chronological order.  Then I recognized that it actually was.  But unlike vanilla git reflog, Magit shows the dates of the referenced commits, instead of the dates of the reference update.

Not the end of the world, but not very useful and confusing.  Not so urgent anyway.

Thanks in advance,

Michael.

**Comment by tarsius** [comment]
> But unlike vanilla git reflog, Magit shows the dates of the referenced commits, instead of the dates of the reference update.

`git reflog show REF` doesn't show any dates at all. As far as I can tell the only way to do that is to use `--format`. Which is what Magit does - it uses `--format="%h [%aN] %ct %gd %gs"`, i.e. `%ct`, the committer date. There's no "update reflog entry date" different from the committer date, the files in `.git/log/refs/` record the committer date I think.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> git reflog show REF doesn't show any dates at all. As far as I can
> tell the only way to do that is to use --format. Which is what Magit
> does - it uses --format="%h [%aN] %ct %gd %gs", i.e. %ct, the
> committer date. There's no "update reflog entry date" different from
> the committer date, the files in .git/log/refs/ record the committer
> date I think.

As far as I learned yesterday - no.  Try "git reflog --date=relative".
git reflog does accept all args git log does (says the manpage).

Have a look at the logs in .git/logs.  There are timestamps, dunno what
format this is, but they look chronological.


Michael.

**Comment by tarsius** [comment]
You can confirm that the "update the reflog entry date" is the same thing as the committer date using this:

```
$ git init .
Initialized empty Git repository in /tmp/testibus/.git/
$ git commit -m "first" --allow-empty
[master (root-commit) 596be23] first
$ git commit -m "second" --allow-empty
[master f70e657] second
$ GIT_COMMITTER_DATE="Thu Jan 1 00:00:00 2015 +0000" git commit -m "time travel" --allow-empty
[master 0082fb5] time travel
$ git reflog --date=relative          
0082fb5 HEAD@{9 months ago}: commit: time travel
f70e657 HEAD@{20 seconds ago}: commit: second
596be23 HEAD@{29 seconds ago}: commit (initial): first
```

There are a few commands in Magit that do explicitly set GIT_COMMITTER_DATE to an older date by default: `magit-commit-extend` and `magit-commit-reword`. But that can be changed using the options `magit-commit-{extend,reword}-override-date`.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> $ git init .
> Initialized empty Git repository in /tmp/testibus/.git/
> $ git commit -m "first" --allow-empty
> [master (root-commit) 596be23] first
> $ git commit -m "second" --allow-empty
> [master f70e657] second
> $ GIT_COMMITTER_DATE="Thu Jan 1 00:00:00 2015 +0000" git commit -m "time travel" --allow-empty
> [master 0082fb5] time travel
> $ git reflog --date=relative          
> 0082fb5 HEAD@{9 months ago}: commit: time travel
> f70e657 HEAD@{20 seconds ago}: commit: second
> 596be23 HEAD@{29 seconds ago}: commit (initial): first

That doesn't prove the ref logs don't their own time stamps.  I think
the timestamp of the reflog just reflects the GIT_COMMITTER_DATE in this
example.  Time traveling is a complicated matter.

Try this:

> git init
Initialized empty Git repository in /home/micha/Treasure/today/test/.git/
> git commit -m "first" --allow-empty
[master (root-commit) ec94570] first
> git commit -m "second" --allow-empty
[master 4792f49] second
> git reset --soft HEAD^
> git reflog --date=relative
ec94570 HEAD@{4 seconds ago}: reset: moving to HEAD^
4792f49 HEAD@{9 seconds ago}: commit: second
ec94570 HEAD@{15 seconds ago}: commit (initial): first

Note the equal commit hashes and the different times in the first and
the third log entry.  This information is useful.

**Comment by michael-heerdegen** [comment]
After having used r H again, I also found it not appropriate to see the commit authors so prominently.  These are rarely useful in the reflog (a bit, maybe, but like for the time shown, it's similarly confusing).

**Comment by tarsius** [comment]
Okay, I have implemented this. Please give it a try. Not sure whether I like dropping the author name. This might make it into v2.3, but maybe not.

**Comment by michael-heerdegen** [comment]
Looks great!  Totally satisfied...thanks.

**Comment by tarsius** [comment]
I've now also changed the defaults of the mentioned commands.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> I've now also changed the defaults of the mentioned commands.

Maybe we can do better.  Can we use the --date=<date> arg of git commit
for those commands, instead of the environment variable?  After a short
test, this seems to do what we want: the commit date is reset into the
past, but the reflog shows the date where "that was done", i.e., unlike
for the environment variable, --date doesn't influence the reflog time
stamp.

**Comment by tarsius** [comment]
That affects the author date, not the committer date.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> That affects the author date, not the committer date.

I see, too bad.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> I've now also changed the defaults of the mentioned commands.

If we keep the change, you will probably want to correct the doc strings
of the affected commands - they now lie about the default behavior.

**Comment by tarsius** [comment]
Noted. Thx.
