### ISSUE TITLE
cl-lib, lexical binding, cl-labels, magit-diff

### ISSUE THREAD

**Issue by Bad-ptr** [magit/magit#2298]
Hmm... If you use functions such as `cl-labels`(and/or expect `let` to behave as the `lexical-let`) in file then you need to enable the lexical-binding for that file.
For example in magit-diff you call `cl-labels` https://github.com/magit/magit/blob/master/lisp/magit-diff.el#L2022
This function is intended to be used with lexical-binding enabled, as far as I know.
To enable lexical-binding for a file you must add the `-*- lexical-binding: t; -*-` string to the file header:
https://github.com/magit/magit/blob/master/lisp/magit-diff.el#L1
`;;; magit-diff.el --- inspect Git diffs -*- lexical-binding: t; -*-`

//may be the same applies to `cl-letf` and `cl-flet`.

Am I wrong?

**Comment by tarsius** [comment]
> This function is intended to be used with lexical-binding enabled, as far as I know.

```
cl-labels is an autoloaded Lisp macro in ‘cl-macs.el’.

(cl-labels ((FUNC ARGLIST BODY...) ...) FORM...)

Make temporary function bindings.
The bindings can be recursive and the scoping is lexical, but capturing them
in closures will only work if ‘lexical-binding’ is in use.
```

This doesn't say that this form won't work at all if `lexical-binding` is not enabled. And it doesn't even matter here. Whether closures are used or not is irrelevant in the case you mentioned.

> //may be the same applies to `cl-letf` and `cl-flet`.

When the dynamically scoped `flet` was removed and many users started looking for an alternative, `cl-letf` was recommended to us as a substitute.
