### ISSUE TITLE
Error when trying to commit over tramp

### ISSUE THREAD

**Issue by dkm** [magit/magit#2305]
I'm using magit ac2588908 (installed with el-get) : Magit 2.2.2-121-gac25889, Git 2.4.3, Emacs 25.0.50.1

I'm working over ssh using tramp. Status and staging operations work correctly, but when magit should open the commit message buffer, I get this error : 

```
  apply: Setting current directory: No such file or directory, /the/remote/directory/mymodule
```

I guess the problem is that the pathname does not contain the tramp prefix, as seen in other commands : 
```
Tramp: Inserting ‘/ssh:remote_hostname:/the/remote/directory/.git/modules/mymodule/COMMIT_EDITMSG’...done
```

**Comment by dkm** [comment]
I've also tried to use MELPA version, but it also has the bug.

After hitting 'c' from the status buffer, I have the error + the COMMIT_EDITMSG is created with the correct path (ie. with tramp prefix).

**Comment by tarsius** [comment]
I cannot reproduce this. Could I have a backtrace with this please? (`M-x toggle-debug-on-error`, then create another commit).

**Comment by dkm** [comment]
On 01-10-2015 21:25, Jonas Bernoulli wrote:
> I cannot reproduce this. Could I have a backtrace with this please?
> (M-x toggle-debug-on-error, then create another commit).

Sure ! Here is the backtrace :

Debugger entered--Lisp error: (file-error "Setting current directory" 
"No such file or directory" "/path/to/gitroot/documents/")
   call-process("git" nil (t nil) nil "--no-pager" "--literal-pathspecs" 
"-c" "core.preloadindex=true" "rev-parse" "--show-cdup")
   apply(call-process "git" nil (t nil) nil ("--no-pager" 
"--literal-pathspecs" "-c" "core.preloadindex=true" "rev-parse" 
"--show-cdup"))
   process-file("git" nil (t nil) nil "--no-pager" "--literal-pathspecs" 
"-c" "core.preloadindex=true" "rev-parse" "--show-cdup")
   apply(process-file ("git" nil (t nil) nil "--no-pager" 
"--literal-pathspecs" "-c" "core.preloadindex=true" "rev-parse" 
"--show-cdup"))
   magit-process-file("git" nil (t nil) nil "--no-pager" 
"--literal-pathspecs" "-c" "core.preloadindex=true" "rev-parse" 
"--show-cdup")
   apply(magit-process-file "git" nil (t nil) nil ("--no-pager" 
"--literal-pathspecs" "-c" "core.preloadindex=true" "rev-parse" 
"--show-cdup"))
   magit-git-str("rev-parse" "--show-cdup")
   apply(magit-git-str "rev-parse" "--show-cdup")
   magit-rev-parse-safe("--show-cdup")
   magit-toplevel()
   magit-revert-buffers()
   run-hooks(git-commit-setup-hook)
   git-commit-setup()
   git-commit-setup-check-buffer()
   run-hooks(find-file-hook)
   after-find-file(nil t)
   find-file-noselect-1(#<buffer COMMIT_EDITMSG> 
"/scp:remote_hostname:/path/to/gitroot/.git/modules/documents/COMMIT_EDITMSG" 
nil nil 
"/scp:remote_hostname:/path/to/gitroot/.git/modules/documents/COMMIT_EDITMSG" 
((2320 . 3609) (-1 . 2)))
   
find-file-noselect("/scp:remote_hostname:/path/to/gitroot/.git/modules/documents/COMMIT_EDITMSG")
   with-editor-output-filter("WITH-EDITOR: 9779 OPEN 
/path/to/gitroot/.git/modules/documents/COMMIT_EDITMSG\n")
   with-editor-process-filter(#<process git<1>> "WITH-EDITOR: 9779 OPEN 
/path/to/gitroot/.git/modules/documents/COMMIT_EDITMSG\n" t)
   (lambda (proc str) (magit-process-filter proc str) 
(with-editor-process-filter proc str t))(#<process git<1>> "WITH-EDITOR: 
9779 OPEN /path/to/gitroot/.git/modules/documents/COMMIT_EDITMSG\n")

**Comment by tarsius** [comment]
> (sorry, I can't find out how to properly format the code... the preview shows correct lisp code with proper syntax highlighting, but the final comment does not...)

Once you have answered by mail, a lot of markdown syntax remain disabled, even if you edit the message through the web interface. Just post a new message.

---

I still cannot reproduce and there are tests which should cover this case. Could you please remove all traces of magit and then reinstall from scratch. I suspect there might be some old files laying around and getting in the way.

**Comment by dkm** [comment]
I wiped all my .emacs files from my homedir, then started emacs, installed el-get, then magit, added the simplest config item required (preserving tramp PATH in order to get correct git binary, el-get init).
Always the same error.

I've tried with emacs 25.0.50.1 from a git around 2014-11-19 and 2015-09-29.
Maybe I could try with a stable release of emacs instead of a dev version, or even with all my shell customizations switched off...

**Comment by npostavs** [comment]
> I wiped all my .emacs files from my homedir

Does that include wiping `~/.emacs.d/el-get/`? It's possible an el-get bug could leave some old magit traces lying around.

It may be more convenient to make a temporary HOME directory instead of wiping your current one.

**Comment by dkm** [comment]
yes, I've removed all .emacs* files, that includes the .d directory.

I could try setting $HOME in a new directory if you think it's worth trying, but moving current home is not possible (not root).

thanks for the help :-)

**Comment by npostavs** [comment]
> I could try setting $HOME in a new directory if you think it's worth trying

Yeah, that's what I meant. But if you've wiped `~/.emacs.d` I don't think that adds anything.

**Comment by dkm** [comment]
I've tried with latest stable emacs (GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.8.8) of 2015-10-07 on xxxxx) and I get the exact same error. Maybe this is related to the context... I'll try to edit something on a different remote host.

**Comment by dkm** [comment]
I've tested against a totally different remote host with the exact same result...

**Comment by dkm** [comment]
Magit 2.1.0, Git 2.4.3, Emacs 25.0.50.1
Same result also. Must be something in my env, but I don't know what to look next...

**Comment by tarsius** [comment]
Try updating to v2.2.2

**Comment by dkm** [comment]
That's where the problem was first encountered. Not a real 2.2.2, but a fresh master from less than 2 weeks. I'm now using "Magit 2.2.2-213-g30a1b1c, Git 2.4.3, Emacs 25.0.50.1" and do the commit from the command line...
I've been trying 2.1.0 to see if that was a regression in between 2.x versions...

**Comment by tarsius** [comment]
Ah sorry, lost track of that.

**Comment by dkm** [comment]
Maybe this is related... I have .tramp_history file in directories where I've tried to commit from magit.
I think all that garbage around the command may be the problem. I'll try to clean that.
```
unset correct autocorrect MAILPATH MAILCHECK MAIL HISTORY CDPATH
cd /remote/path/to/git/module/ && exec  env GIT_EDITOR\=sh\ -c\ \'echo\ \"WITH-EDITOR\:\ \$\$\ OPEN\ \$0\"\;\ sleep\ 604800\ \&\ sleep\=\$\!\;\ trap\ \"kill\ \$sleep\;\ exit\ 0\"\ USR1\;\ trap\ \"kill\ \$sleep\;\ exit\ 1\"\ USR2\;\ wait\ \$sleep\' PS1\=/scp\:remote_host\:/remote/path/to/git/module/\ \#\$\  env GIT_EDITOR\=sh\ -c\ \'echo\ \"WITH-EDITOR\:\ \$\$\ OPEN\ \$0\"\;\ sleep\ 604800\ \&\ sleep\=\$\!\;\ trap\ \"kill\ \$sleep\;\ exit\ 0\"\ USR1\;\ trap\ \"kill\ \$sleep\;\ exit\ 1\"\ USR2\;\ wait\ \$sleep\' git --no-pager --literal-pathspecs -c core.preloadindex\=true commit --signoff
```

**Comment by dkm** [comment]
All these are not related to my env, that's handled by tramp/emacs itself, so that must be wanted.

**Comment by tarsius** [comment]
Could you please post a new properly formatted backtrace.

**Comment by dkm** [comment]
Sure !

 ```lisp
Debugger entered--Lisp error: (file-error "Setting current directory" "No such file or directory" "/path/to/git/root/mymodule/")
  call-process("git" nil (t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "rev-parse" "--show-cdup")
  apply(call-process "git" nil (t nil) nil ("--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "rev-parse" "--show-cdup"))
  process-file("git" nil (t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "rev-parse" "--show-cdup")
  apply(process-file ("git" nil (t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "rev-parse" "--show-cdup"))
  magit-process-file("git" nil (t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "rev-parse" "--show-cdup")
  apply(magit-process-file "git" nil (t nil) nil ("--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "rev-parse" "--show-cdup"))
  magit-git-str("rev-parse" "--show-cdup")
  apply(magit-git-str "rev-parse" "--show-cdup")
  magit-rev-parse-safe("--show-cdup")
  magit-toplevel()
  magit-revert-buffers()
  run-hooks(git-commit-setup-hook)
  git-commit-setup()
  git-commit-setup-check-buffer()
  run-hooks(find-file-hook)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer COMMIT_EDITMSG> "/ssh:remote_hostname:/path/to/git/root/.git/modules/mymodule/COMMIT_EDITMSG" nil nil "/ssh:remote_hostname:/path/to/git/root/.git/modules/mymodule/COMMIT_EDITMSG" ((2396 . 8944) (-1 . 2)))
  find-file-noselect("/ssh:remote_hostname:/path/to/git/root/.git/modules/mymodule/COMMIT_EDITMSG")
  with-editor-output-filter("WITH-EDITOR: 20495 OPEN /path/to/git/root/.git/modules/mymodule/COMMIT_EDITMSG\n")
  with-editor-process-filter(#<process git> "WITH-EDITOR: 20495 OPEN /path/to/git/root/.git/modules/mymodule/COMMIT_EDITMSG\n" t)
  (lambda (proc str) (magit-process-filter proc str) (with-editor-process-filter proc str t))(#<process git> "WITH-EDITOR: 20495 OPEN /path/to/git/root/.git/modules/mymodule/COMMIT_EDITMSG\n")
 ```

**Comment by tarsius** [comment]
What does that print?

```lisp
(add-hook 'git-commit-setup-hook
          (lambda ()
            (message "-- current-buffer:    %s" (current-buffer))
            (message "-- default-directory: %s" default-directory)
            (message "-- magit-toplevel:    %s" (magit-toplevel))))
```

**Comment by dkm** [comment]
Here's the output : 
```
-- current-buffer:    COMMIT_EDITMSG
-- default-directory: /ssh:remote_hostname:/path/to/gitroot/.git/modules/module_name/
-- magit-toplevel:    /path/to/gitroot/module_name/
```

Strangely, this debug-print made the thing work correctly : the commit message is opened in a new buffer and the commit is correctly done when closing...

**Comment by Silex** [comment]
Just jumping in here, but maybe it's a bug related to `submodule`? It'd make sense, not many giters use them so it went undetected.

**Comment by dkm** [comment]
My main usage implies submodules, but I've also tested with a regular git repository also... :'(

**Comment by dkm** [comment]
Thanks, works correctly now !
