### ISSUE TITLE
magit-commit-popup: add --date option?

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2307]
Hello,

in the magit-popup-commit, we have an option for --author (?A), but none for --date.  Can we add one?

Background: when a committed patch has a different author, I want to provide the date the patch had been created/published as author date.

Thanks in advance.

**Comment by tarsius** [comment]
For now, please add this to the popup yourself. Also see, and please add an entry to, https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands.

**Comment by michael-heerdegen** [comment]
Thanks, done.

**Comment by michael-heerdegen** [comment]
BTW, maybe there should be a simple way for the user in the interface to specify an argument (that has not been officially defined as popup switch or option) on the fly.  Or is it forbidden by intent?
