### ISSUE TITLE
Magit doesn't work well with git credential.helper

### ISSUE THREAD

**Issue by ghost** [magit/magit#2309]
Sometimes I use pubkeys, but other times https auth is needed.

https://help.github.com/articles/caching-your-github-password-in-git/

github has baked in support for an authentication cache, so you don't
have to enter your credentials at every push, if you'd like to avoid putting
them in the remote url.

From the command line, once you've activated the helper with 
```
git config --global credential.helper 'cache --timeout=3600'
```

You are prompted for credentials once, and subsequent pushes
work without entering them again.

In magit, I get asked for credentials every time even with this turned on.
The above sets a key in config so It doesn't look like missing envars are
the issue (unlike ssh-agent).

If it's relevent, I have SSH_ASKPASS="", which I believe is used as a 
pass prompt whatever the mechanism if set.

**Comment by npostavs** [comment]
magit, OS, and git versions?

> The above sets a key in config so It doesn't look like missing envars are
> the issue (unlike ssh-agent).

On Windows, mismatching `HOME` values can cause config to be skipped.

> If it's relevent, I have SSH_ASKPASS="", which I believe is used as a
> pass prompt whatever the mechanism if set.

I think that's only if you use ssh, otherwise `GIT_ASKPASS` is relevant.

**Comment by MikeSanMichel2** [comment]
linux, magit.20151003, git 2.4.3, emacs 24.5.1, 

>>    If it's relevent, I have SSH_ASKPASS="", which I believe is used as a
>>    pass prompt whatever the mechanism if set.

> I think that's only if you use ssh, otherwise GIT_ASKPASS is relevant.

`(setenv `SSH_ASKPASS` ""` stopped the GUI pass prompt from appearing when
pushing to an https remote, so you may not be right there. 
But likely GIT_ASKPASS has precedence in that case. It's just not set in my shell.

**Comment by npostavs** [comment]
Works for me. 

What's do you get from evaluating `(magit-git-string "config" "credential.helper")` and is it different from running `git config credential.helper` in your shell where it works?

---

> [...] But likely GIT_ASKPASS has precedence in that case.

Ah right, it does fall back to SSH_ASKPASS, it's explained here: http://git-scm.com/docs/gitcredentials#_requesting_credentials

**Comment by npostavs** [comment]
Okay after l seeing [this stackexchange question][1] I notice that entering the password from magit doesn't get cached, although magit does use the existing cached credentials when they have been entered from the shell.

[1]: https://emacs.stackexchange.com/questions/17124/how-can-i-paste-my-password-when-pushing

**Comment by npostavs** [comment]
Setting `GIT_TRACE=1` shows the same calls in both cases, but somehow the credential daemon doesn't stick around in the magit case.
```
  0 git … push -v origin master:refs/heads/master
23:12:37.070396 git.c:348               trace: built-in: git 'push' '-v' 'origin' 'master:refs/heads/master'
23:12:37.072151 run-command.c:335       trace: run_command: 'git-remote-https' 'origin' 'https://github.com/npostavs/magit.git'
Pushing to https://github.com/npostavs/magit.git
23:12:37.925722 run-command.c:335       trace: run_command: 'git credential-cache --timeout=3600 get'
23:12:37.928587 run-command.c:195       trace: exec: '/bin/sh' '-c' 'git credential-cache --timeout=3600 get' 'git credential-cache --timeout=3600 get'
23:12:37.936611 git.c:558               trace: exec: 'git-credential-cache' '--timeout=3600' 'get'
23:12:37.936776 run-command.c:335       trace: run_command: 'git-credential-cache' '--timeout=3600' 'get'
Username for 'https://github.com': Password for 'https://npostavs@github.com': 
23:12:43.239777 run-command.c:335       trace: run_command: 'git credential-cache --timeout=3600 store'
23:12:43.242646 run-command.c:195       trace: exec: '/bin/sh' '-c' 'git credential-cache --timeout=3600 store' 'git credential-cache --timeout=3600 store'
23:12:43.251837 git.c:558               trace: exec: 'git-credential-cache' '--timeout=3600' 'store'
23:12:43.252030 run-command.c:335       trace: run_command: 'git-credential-cache' '--timeout=3600' 'store'
23:12:43.254959 run-command.c:335       trace: run_command: 'git-credential-cache--daemon' '/home/npostavs/.git-credential-cache/socket'
To https://github.com/npostavs/magit.git
 = [up to date]      master -> master
updating local tracking ref 'refs/remotes/origin/master'
Everything up-to-date
```
```
% GIT_TRACE=1 git push -v origin
23:26:53.101703 git.c:348               trace: built-in: git 'push' '-v' 'origin'
23:26:53.102352 run-command.c:335       trace: run_command: 'git-remote-https' 'origin' 'https://github.com/npostavs/magit.git'
Pushing to https://github.com/npostavs/magit.git
23:26:54.199798 run-command.c:335       trace: run_command: 'git credential-cache --timeout=3600 get'
23:26:54.202737 run-command.c:195       trace: exec: '/bin/sh' '-c' 'git credential-cache --timeout=3600 get' 'git credential-cache --timeout=3600 get'
23:26:54.237910 git.c:558               trace: exec: 'git-credential-cache' '--timeout=3600' 'get'
23:26:54.238086 run-command.c:335       trace: run_command: 'git-credential-cache' '--timeout=3600' 'get'
Username for 'https://github.com': npostavs
Password for 'https://npostavs@github.com': [...]

23:26:59.132814 run-command.c:335       trace: run_command: 'git credential-cache --timeout=3600 store'
23:26:59.136011 run-command.c:195       trace: exec: '/bin/sh' '-c' 'git credential-cache --timeout=3600 store' 'git credential-cache --timeout=3600 store'
23:26:59.147095 git.c:558               trace: exec: 'git-credential-cache' '--timeout=3600' 'store'
23:26:59.147351 run-command.c:335       trace: run_command: 'git-credential-cache' '--timeout=3600' 'store'
23:26:59.151491 run-command.c:335       trace: run_command: 'git-credential-cache--daemon' '/home/npostavs/.git-credential-cache/socket'
To https://github.com/npostavs/magit.git
 = [up to date]      master -> master
updating local tracking ref 'refs/remotes/origin/master'
Everything up-to-date
```

**Comment by npostavs** [comment]
Seems to be something about Emacs subprocess handling. I see the problem when using `start-process` and `eshell`, but not when using `M-x shell`.

**Comment by npostavs** [comment]
1. `git-credential-cache--daemon` receives a SIGHUP when `git push` is started from `start-process`. I'm not sure if this is a bug or not.
2. `git-credential-cache--daemon` deletes its socket file and quits after receiving `SIGHUP`. This looks like a bug to me (SIGHUP should not kill daemons).

**Comment by MikeSanMichel2** [comment]
Good work.

https://github.com/git/git/blob/77bd3ea9f54f1584147b594abc04c26ca516d987/credential-cache--daemon.c#L15

The wikipedia article is actually quite informative:
- The default action on POSIX-compliant systems is an abnormal termination.
- On POSIX-compliant platforms, SIGHUP is a signal sent to a process when its controlling terminal is closed. 

The daemon shouldn't really have a controlling terminal so (1) shouldn't happen, but if a
signal is sent th daemon is within its rights to cleanup and die in response.

as mentioned in the wiki page `nohup` abd bash's `detach` exist, but I'm not sure they're any
help here.

**Comment by npostavs** [comment]
> I'm assuming it's that shell exiting that does it

In our case there is no shell, Emacs sends SIGHUP when `git` exits. So `detach`/`disown` are not applicable, and `nohup` doesn't help because the daemon explicitly sets a handler.

**Comment by MikeSanMichel2** [comment]
> > >   git-credential-cache--daemon receives a SIGHUP when git push is started 

> > I'm assuming it's that shell exiting that does it

> In our case there is no shell, Emacs sends SIGHUP when git exits.

Fine, but it's the "process" *exiting* that triggers a HUP, not its start.

> So detach/disown are not applicable,

Where available, you *could* use `/bin/sh -c` to run commands if that made a difference,

>  and nohup doesn't help because the daemon explicitly sets a handler.

But you didn't actually test that. The handler is hooked in to a handler [chain](https://www.kernel.org/pub/software/scm/git/docs/technical/api-sigchain.html) and it doesn't 
clobber its predecessor. nohup gets there first and simply swallows the signal.

**Comment by npostavs** [comment]
> But you didn't actually check that. The handler is hooked into a handler chain and it doesn't
> clobber its predecessor. nohup gets there first and simply swallows the signal.

I was under the impression that the handler runs *before* its predecessor (I can't tell from the page you linked whether the handlers are run starting from the top or bottom of the stack), hence the socket path will already be erased and the daemon unreachable when nohup's ignore sighup happens. When I attempted to use `nohup` it didn't help. Since I already had an explanation as to why it shouldn't work I didn't investigate carefully, but it's possible I just didn't do it right.

**Comment by MikeSanMichel2** [comment]
> the socket path will already be erased and the daemon unreachable when nohup's 
> ignore sighup happens. 

Good point. I verified that running under nohup makes the process ignore the signal, I did not verify in which order they run. Thinking about it some more I think you're probably right about the ordering, otherwise the default handler (TERM) would run first and there'd be no point. It could (maybe)
check whether the handler prior to it was the default or someone else's, but... it doesn't:
I tested this again with nohup, the process doesn't die but it does cleanup. 

What about running under git `/bin/sh`?

**Comment by npostavs** [comment]
> What about running under git /bin/sh?

I think this would involve rewriting a lot of magit's code to talk to a long running shell to start git commands instead of running them directly. I forsee a lot of work and a lot of breakage in this direction.

---

Something that I have found to work is starting up the daemon directly from Emacs, so that any git commands will use it instead of starting their own. The tricky part is deciding if, when, and how to run the daemon. Remember that `credential.helper` can be an arbitrary shell command, and the daemon has to be run [within 30 seconds of its 1st use or else it exits][1]. 

Some similarities to [ssh-agency][2] here. I'm using the default path of `"~/.git-credential-cache/socket"`, we could attempt to extract it from `credential.helper` or else add a magit config var?

```elisp
(defvar git-credential-cache--daemon-process nil)
(defun start-git-credential-cache--daemon ()
  ;; TODO: also check for daemons started outside of Emacs?
  (unless (process-live-p git-credential-cache--daemon-process)
    (setq git-credential-cache--daemon-process
          (start-process "git-credential-cache--daemon" "*git-credential-cache--daemon*"
                         "git-credential-cache--daemon" "~/.git-credential-cache/socket"))))

(dolist (sym-fun '(magit-push magit-push-matching magit-push-tag magit-push-tags
                              magit-pull magit-pull-current
                              magit-fetch magit-fetch-current magit-fetch-all))
  (advice-add sym-fun :before #'start-git-credential-cache--daemon))
```

[1]: https://github.com/git/git/blob/v2.6.1/credential-cache--daemon.c#L58-L62
[2]: https://github.com/magit/ssh-agency

**Comment by MikeSanMichel2** [comment]
> >   What about running under git /bin/sh?
> I think this would involve rewriting a lot of magit's code to talk to a long running shell 

Why ? `/bin/sh -c git` isn't long running. I'm just guessing the HUP wouldn't reach the
the daemon though, haven't checked.  

> Something that I have found to work is starting up the daemon directly from Emacs

Good. But you do need to check whether there's a running daemon already, a
case which currently does work.

**Comment by npostavs** [comment]
> Why ? /bin/sh -c git isn't long running. I'm just guessing the HUP wouldn't reach the
> the daemon though, haven't checked.

I haven't actually checked either, but I believe Emacs would send all subprocesses SIGHUP when the initiating process (be it `git` or `sh`) ends.

> check whether there's a running daemon already for this user, a
> case which currently does work.

Yup, I just edited in some code for that, it's untested, please try it out.

**Comment by tarsius** [comment]
Wouldn't just using `git config credential.helper "cache --debug" do the trick?

From `git-credential-cache--daemon(1)`:

> If the --debug option is specified, the daemon does not close its stderr stream, and may output extra diagnostics to it even after it has begun listening for clients.

I would hope that `git-credential-cache` would pass along `--debug` to `git-credential-cache--daemon`.

**Comment by tarsius** [comment]
That statement was added in the same commit @MikeSanMichel2 linked to and which taught the daemon to commit harakiri.

**Comment by npostavs** [comment]
> I would hope that git-credential-cache would pass along --debug to git-credential-cache--daemon.

`git-credential-cache` doesn't take a `--debug` option and [doesn't pass extra args to the daemon][1] which caused me some annoyance while trying to debug this. But even if it did, I don't think passing `--debug` to the daemon changes the SIGHUP behaviour.

[1]: https://github.com/git/git/blob/v2.6.1/credential-cache.c#L41-L49

**Comment by tarsius** [comment]
`nohup` seems to do the trick:

```
$ emacs -Q -batch --eval '(start-process "nohup" nil "nohup" "xterm")'
$ killall emacs                                                      
emacs: no process found
```

so `emacs` has exited and the `xterm` is still live and kicking.

> and `nohup` doesn't help because the daemon explicitly sets a handler.

Why does that make a difference? Doesn't the use of `nohup` prevent the daemon from even just receiving the signal? Guess I have to read up on that stuff.

**Comment by npostavs** [comment]
> Why does that make a difference? Doesn't the use of nohup prevent the daemon from even just receiving the signal?

No, it doesn't block the signal, it just sets the signal behaviour to SIG_IGN (ignore), before `exec`ing.

**Comment by MikeSanMichel2** [comment]
> I haven't actually checked either, but I believe Emacs would send all subprocesses SIGHUP when 
> the initiating process (be it git or sh) ends.

well, I hoped a subprocess of a subprocess would be spared somehow (perhaps sh propagates it),
but replacing git with 
```
#!/bin/sh

git.real $@
```

makes no difference.

**Comment by npostavs** [comment]
Could you try with `setsid git.real "$@"`, depending on how Emacs decides to send signals it could help.

**Comment by MikeSanMichel2** [comment]
That borks the input stream for the password

**Comment by MikeSanMichel2** [comment]
`alias huntgit="ps xao pid,ppid,pgid,sid,comm | grep git"; while true; do huntgit;done`
 
magit push:
```
8019     1  6770  6770 git-credential- 
8019     1  6770  6770 git-credential- 
8019     1  6770  6770 git-credential-
...
```
shell push
```
10537     1  9598  3725 git-credential-
10537     1  9598  3725 git-credential-
10537     1  9598  3725 git-credential-
10537     1  9598  3725 git-credential-
10537     1  9598  3725 git-credential-
...
```

sid and pgid look different in each case. I have no idea what sid=pgid implies
and why (if) that makes the difference here.

**Comment by MikeSanMichel2** [comment]
bingo. I think.

https://askubuntu.com/a/360253
```
PROCESS STATE CODES
       Here are the different values that the s, stat and state output specifiers (header "STAT" or "S") will display to describe the state of a process:
       D    uninterruptible sleep (usually IO)
       R    running or runnable (on run queue)
       S    interruptible sleep (waiting for an event to complete)
       T    stopped, either by a job control signal or because it is being traced.
       W    paging (not valid since the 2.6.xx kernel)
       X    dead (should never be seen)
       Z    defunct ("zombie") process, terminated but not reaped by its parent.

       For BSD formats and when the stat keyword is used, additional characters may be displayed:
       <    high-priority (not nice to other users)
       N    low-priority (nice to other users)
       L    has pages locked into memory (for real-time and custom IO)
       s    is a session leader
       l    is multi-threaded (using CLONE_THREAD, like NPTL pthreads do)
       +    is in the foreground process group <------------
```

**Comment by MikeSanMichel2** [comment]
`magit-process-connection-type` seems to be the crucial settings here. the default makes emacs
communicate with the process as `pty` which has the side-effect of making the daemon die on exit.
If you set it it `nil`, the daemon persists but  [git_terminal_prompt](https://github.com/git/git/blob/77bd3ea9f54f1584147b594abc04c26ca516d987/compat/terminal.c#L100) can't read
the input for the password and dies with `no such file or device` error.

For now, I've just reluctantly gone back to using `gnome-ssh-askpass.sh` and setting 
`magit-process-connection-type` to `nil`. Of course using a public key or netrc, or putting the password in the remote's url would also work.

**Comment by tarsius** [comment]
From [Pushing with Magit from Windows](https://github.com/magit/magit/wiki/Pushing-with-Magit-from-Windows):

> Under Windows, Magit is unable to intercept the password prompt from Git, so operations requiring a password will hang indefinitely.

Is this still true? Considering what @MikeSanMichel2 just said, I think it is, but potentially only when using `cygwin` - only then does `magit-process-connection-type` default to `nil` (i.e. use a pipe no pty). In any case if this only doesn't work when using Cygwin Emacs, then we should say that, instead of claiming that it never works on Windows.

We started not using a pty in 2acc8be62357015205123fa7f1a7b4e9f3ef3891 (five years ago):

> Make the process-connection-type customizable.
>
> We need process-connection-type to be nil on cygwin
> We need process-connection-type to be t for magit to ask for password
> So we now use the new variable magit-process-connection-type for this,
> defaulting to nil on cygwin, and to t on others platform.

Maybe that wasn't actually necessary?

**Comment by npostavs** [comment]
This issue is all on GNU/Linux. https://github.com/magit/magit/issues/2309#issuecomment-145353791

I'm pretty sure password interception still fails on win32.
I don't currently have Cygwin Emacs installed anywhere.

**Comment by MikeSanMichel2** [comment]
That's a separate issue and I haven't used windows in a decade.
But both have disadvantages:
1. Using a pty magit **can** prompt for a password, but the password **isn't cached** (this issue).
2. Using pipes, magit **can't** prompt for a password, but the password **is cached**. 

In both cases if GIT_ASKPASS is set git invokes the specificed program on its own when it needs a password, without any terminal input, so case (2) can work if you set it GIT_ASKPASS up. However,  magit can't assume all its users have. 

You could set `magit-process-connection-type` according to whether GIT_ASKPASS is set
and the program can be found on the path though. Assuming this all behaves the same way
on windows.

**Comment by tarsius** [comment]
Yeah, I was hijacking the thread.

**Comment by MikeSanMichel2** [comment]
Hey, it's your repo... :)

**Comment by tarsius** [comment]
... and I did it because I see a real change that we resolve all of these issues now (as in "provide workarounds and/or document accurately why things don't work as expected"). There are already a bunch of issues open and I start loosing track (e.g. @npostavs posted some code which advices `magit-push` and friends - I wanted to comment on that but cannot find it anymore).

> *In both cases* if GIT_ASKPASS is set git invokes the specificed program on its own when it needs a password, without any terminal input, so case (2) can work if you set it GIT_ASKPASS up. However, magit can't assume all its users have. 

See, it's related :-) That's an interesting note, maybe we should just set it ourselves when appropriate (but of course that won't work with `emacs -nw`, there's always one special-case that needs a different approach :(

Also I don't know whether the irony in (1) and (2) should make me laugh or cry...

**Comment by tarsius** [comment]
> I wanted to comment on that but cannot find it anymore

Ah, found it, it's this issue but longer back than I thought.

**Comment by MikeSanMichel2** [comment]
> maybe we should just set it (GIT_ASKPASS) ourselves when appropriate 

As a separate change, perhaps we should check whether it's set and adjust `magit-process-connection-type` accordingly, that way things "just work" for at least some users.
Assuming windows behaves the same way, that is, which no one has verified yet.

**Comment by npostavs** [comment]
I believe the problem is simply that Windows doesn't have the concept of a pty. I just checked that native Windows Emacs never uses ptys: even if `process-connection-type` is t, `process-tty-name` always returns nil.

> (e.g. @npostavs posted some code which advices magit-push and friends - I wanted to comment on that but cannot find it anymore).

Should I push it to a branch?

**Comment by tarsius** [comment]
Yes please.

**Comment by npostavs** [comment]
Ok, see https://github.com/magit/magit/compare/np/cache-daemon-hack

**Comment by tarsius** [comment]
Well it looks like we have no choice but to use this hack, which is fine with me, it looks sane in principle. I have added a new hook `magit-credential-hook` for use by this and the `ssh-agency` and pushed the result to this branch.

I would like to release soon, and this and #2317 are the last two blockers. Could you please take care of these issues soon? How can I help you with these issues?

**Comment by PetrKryslUCSD** [comment]
Has this really been resolved? I still see magit constantly asking for password even though I use the credential helper. Using git in the terminal works fine: I used 

git config --global credential.helper "cache --timeout=604800"

and git in the bash does not ask for passwords anymore.

**Comment by kyleam** [comment]
> Has this really been resolved?

I just tested multiple clones of an https URL with `credential.helper` set to "cache --timeout=600".  The first prompted for my credentials and subsequent ones didn't.  `magit-credential-cache-daemon-socket` is set to the value I'd expect.

testing info: latest Magit (873da4a6), vanilla configuration with Emacs 30.0.92 on a GNU/Linux machine, Git 2.47.1.404.ge66fd72e97

So, yes, the fix still looks to be in effect, at least on some platforms.  If based on your troubleshooting you think there's a (perhaps platform-specific) bug with this functionality, please open a dedicated issue with system details and any debugging info you've gathered.
