### ISSUE TITLE
Cannot properly use shift selection of lines to stage in status buffer

### ISSUE THREAD

**Issue by DarwinAwardWinner** [magit/magit#2313]
When I try to use shift+up/down to select which lines I want to stage in the Magit status buffer, the first press selects the current line and the next one, but then the second press moves down another line and deselects the previous two lines that were selected. Then this repeats: select 2 lines, move down and deselect. I can successfully use the mouse to select the lines I want.

magit-version: 20151003.2156

**Comment by npostavs** [comment]
Seems to be working for me. Do you see this with `emacs -Q`? Does `C-SPC` then up/down work?

**Comment by DarwinAwardWinner** [comment]
Ok, I'll try those out when I get the chance.

**Comment by tarsius** [comment]
The "region" of lines that will be staged actually last from the beginning of the line on which `region-beginning` is to the end of the line on which `region-end` is. So if `mark` and `point` are at the same position, then that line would be acted on.

Therefore I recommend you use <kbd>C-SPC</kbd> to select one line, and then, if you actually want to apply more than one line <kbd>n</kbd> as many times as necessary.

I too cannot reproduce the behavior you are describing by the way.

**Comment by tarsius** [comment]
Please reopen if you can reproduce with `emacs -Q` or need help figuring out why it doesn't work with your configuration.
