### ISSUE TITLE
(staging) diff view disrupts code indentation when displaying diff context lines

### ISSUE THREAD

**Issue by MikeSanMichel2** [magit/magit#2314]
The "+"/"-" prefix the changed rows, but a blank " " isn't prefixed to the the unchanged context.
So you get:

```python
def foo():
    x = "bar"
+    y = "xyz"
```

For significant-whitespace languages in particular (python), this is disturbing.

**Comment by tarsius** [comment]
Can you reproduce that with `emacs -Q`?

**Comment by MikeSanMichel2** [comment]
I should have figured out by now that any emacs package bug report starts with that. Sorry.

**Comment by MikeSanMichel2** [comment]
FWIW, I traced this back to a spaces-vs-tabs issue. When the same file mixes tabs and space indentation, the file looks ok if whitespace-mode is off, but the diff ends up looking off.

Don't expect magit to do anything about this though.

**Comment by tarsius** [comment]
Ah yes, one of the reasons why I prefer spaces :-)
