### ISSUE TITLE
Bad git version silently ignored

### ISSUE THREAD

**Issue by timvisher** [magit/magit#2315]
I made the mistake of installing a later version of git over top of a version installed by `apt-get` on a server. While my shell configured the later version of git to be selected over the former version, emacs did not. This lead me down a 3 hour rabitt hole where I was trying to track down TRAMP errors or SSH errors or whatever, when all that was happening was that emacs was using the old version of git.

Would it be possible to have magit check once per session if the version of git works or not? Maybe the first time the command is executed per server?

**Comment by tarsius** [comment]
Could you please investigate how that would be done on the Tramp side? There might be a hook for this, or not.

**Comment by timvisher** [comment]
@tarsius Meaning support for exit code hooks or something? I'm not sure how TRAMP itself could possible be able to generally support `git` specific version information.

Ah, or are you saying registering as a `on-connected` hook or something? i.e. magit would register an `on-connect` hook that would be executed once per host? That wouldn't cover local git versions but it would be a step in the right direction.

**Comment by tarsius** [comment]
> Ah, or are you saying registering as a on-connected hook or something? i.e. magit would register an on-connect hook that would be executed once per host?

Yes.

> That wouldn't cover local git versions but it would be a step in the right direction.

We already check that at startup.

**Comment by tarsius** [comment]
`magit-status` now checks that the version on the remote is good.

**Comment by timvisher** [comment]
:+1:
