### ISSUE TITLE
Option "magit-log-show-refname-after-summary" broken with 2809a24

### ISSUE THREAD

**Issue by bastianbeischer** [magit/magit#2316]
I'm using the 'magit-log-show-refname-after-summary' variable set to 't' (see my original bug report #1969).

Since upgrading magit I have seen various problems with this mode. I have run a bisect and found the first bad commit: 2809a24.

Most noticable symptoms:

1) log lines which used to be on one line are broken into two - also there are some left over things at the end from git log
2) getting the log sometimes takes infinitely long.

I think it should be reproducible by setting 'magit-log-show-refname-after-summary' to 't'.

**Comment by bastianbeischer** [comment]
I now think that 2) is a different bug: it also happens when not settings magit-log-show-refname-after-summary. 

This only happens for my large repository and I can see that my log buffer does not limit the number of shown commits anmore like it used to (in the past one had to use 'e' to show more commits) which seems to be reason for the slow wash...

**Comment by tarsius** [comment]
1. I'll look into that.

2. See a244d9b6790c44e8bd9978412eb4ae20d215703e.

**Comment by bastianbeischer** [comment]
Thanks, I figured out the problem with '2.':

I had magit-log-arguments configured because I wanted to print the graph in color:

 '(magit-log-arguments (quote ("--graph" "--color" "--decorate")))

It appears that you have added '-n256' there, which I also added and now '2.' is fixed.
