### ISSUE TITLE
It would be nice if `magit-git-command` would `magit-refresh` afterwards

### ISSUE THREAD

**Issue by Peeja** [magit/magit#2320]
When I use `magit-git-command`, I'm typically doing something which changes the state of the things that appear in `magit-status`, and I almost always have to `magit-refresh` to see my changes. It would be nice if that happened automatically. (Unless I'm missing a reason why that would be a problem.)

**Comment by tarsius** [comment]
That's a regression in 561e05bbe8da19189825b911f210780aad0d840e. I'll fix that tomorrow after I have installed a feature branch which would conflict with the fix for this issue.

**Comment by Peeja** [comment]
Ah, cheers!

**Comment by tarsius** [comment]
Fixed in 14a4ef60e01a33988ca2ebe046742f92f5c20c2c and 985bd218073e1a89cca33fd76579b21e2c24aea0.

**Comment by Peeja** [comment]
Thanks!
