### ISSUE TITLE
magit-blame doesn't work over TRAMP

### ISSUE THREAD

**Issue by timvisher** [magit/magit#2321]
It looks like the full TRAMP path is used in [this function](https://github.com/magit/magit/blob/master/lisp/magit-git.el#L448-L449) and of course that file doesn't exist locally on disk.

```diff
diff --git a/lisp/magit-git.el b/lisp/magit-git.el
index 14af84b..56f1f88 100644
--- a/lisp/magit-git.el
+++ b/lisp/magit-git.el
@@ -446,8 +446,12 @@ tracked file."
       (file-relative-name file it))))

 (defun magit-file-tracked-p (file)
+  (setq *charnock* file)
   (magit-git-success "ls-files" "--error-unmatch" file))

+*charnock*
+"/scp:core:/-redacted-"
+
 (defun magit-list-files (&rest args)
   (apply #'magit-git-items "ls-files" "-z" "--full-name" args))
```

**Comment by tarsius** [comment]
90680cad8004b42b54d56e5da57c02a33374a050 is supposed to fix that.

**Comment by timvisher** [comment]
Yep. Sorry I didn't find that issue in my searching. :|

**Comment by tarsius** [comment]
And does that fix the issue for you? Or are you using the releases? By the way there will be another release soonish.

**Comment by timvisher** [comment]
@tarsius I've applied it manually as a patch because I am using the releases. Looking forward to getting the new release!
