### ISSUE TITLE
Save part of change to index file by 3-way magit-ediff cause coding-system changed

### ISSUE THREAD

**Issue by aligua** [magit/magit#2327]
Magit 20151006.1359, Git 2.5.3, Emacs 24.5.1

my file in git is utf-8-unix, while I have (setq buffer-file-coding-system 'utf-8-dos) in init file.

after copy part change from unstaged buffer to index buffer, and choose y when quit from ediff to save content change to index file. Then after magit status refresh and commit, will see the commit message include every line of whole file because of coding-system changed to utf-8-dos.

if I (setq-default buffer-file-coding-system 'utf-8-unix), or if all the changes from unstaged buffer are copied to index buffer, then this issue is not seen.

100% reproducing at my side.

**Comment by tarsius** [comment]
#2326
