### ISSUE TITLE
Not compatible with fci-mode

### ISSUE THREAD

**Issue by villem** [magit/magit#2328]
This is bit hard to describe, but I've got screenshot that should help to give understanding.

The issue is as follows
Selecting first changed file in unstated or staged area works fine if my cursor start of line, but if I press down arrow, to select next file, the file is not actually highlighted and if for example press 4 to see diffs I see changes of the previous line. If move cursor to column 2 in the current line, the current line gets highlighted and I can operate with file correctly.

In first image I've got first line selected and cursor is first char in the line
<img width="355" alt="select_file_1_magit" src="https://cloud.githubusercontent.com/assets/123159/10409592/3f33f558-6f2f-11e5-848a-26440b881e69.png">

 In this image I've got second line NOT selected and cursor is first char in the line 
<img width="364" alt="select_file_2_magit_problem" src="https://cloud.githubusercontent.com/assets/123159/10409594/3f670a42-6f2f-11e5-92b2-87b38ded9448.png">

 In this image I've got second line selected and cursor is second char in the line
<img width="373" alt="select_file_3_magit_ok" src="https://cloud.githubusercontent.com/assets/123159/10409593/3f62d544-6f2f-11e5-87b3-52161fe23eb6.png">

**Comment by villem** [comment]
Hmm, with clean emacs environment without any other packages than magit things seems to work correctly. I'll investigate which package causes this issue.

**Comment by villem** [comment]
Ok it is the `fill-column-indicator`package. 
If I enable 
```emacs-lisp
(setq fci-rule-column 80)                                                                
(setq fci-rule-width 1)                                                                   
(add-hook 'after-change-major-mode-hook 'fci-mode)                                        
(define-globalized-minor-mode global-fci-mode fci-mode (lambda () (fci-mode 1)))         
(global-fci-mode 1)
```
I get the problem. I can probably workaround this problem by enabling the mode in the source files, but it would be interesting know what causes the issue. You can close this invalid if this is a problem in FCI package.

Thanks!

**Comment by tarsius** [comment]
I use `fci-mode` too, but I only enable it in text and prog modes.

The problem is that `fci-mode` fiddles with text-properties in ways that often conflict with other packages. For example I currently have that mode enabled when editing commit messages, but will probably have to disable it because strange things happen when I use the new `magit-pop-revision-stack` command. Generally speaking I would say it is `fci-mode`s responsibility to deal with incompatibilies, since it is the minor-mode.

**Comment by villem** [comment]
Ok. I'll close this seem not be be magit problem. Thanks for great great tool!

**Comment by tarsius** [comment]
You're welcome.
