### ISSUE TITLE
What is v2.x equiv of v1's "rewrite" feature?

### ISSUE THREAD

**Issue by MikeSanMichel2** [magit/magit#2330]
Note: *My OP was too ZOMG, rewritten for productive discussion.*

After much "spirited" discussion in #966, the "rewrite" feature of v1 was removed.
I depended on "rewrite" heavily for rewriting PRs before submission. Where the primary task is moving multiple hunks between multiple commits.

I'm aware of new and improved features of v2 and use them extensively, including the interactive rebase, cherry picking, amending, fixup, extend, etc' . They are excellent, but do not perform nearly as well when I need to rewrite a dozen already completed commits. I find myself going through this rewriting stage for most every PR I submit. It  sometimes feels like have a dozen balls in the air so having as little additional complexity introduced by the tool really matters.

Several alternative ways to do such rewriting with v2 have been suggested:

1. **Using interactive-rebase instead**: again, great for commit-level changes, but not for moving hunks between commits.
2. **Use reset-HEAD** and reconstruct the commits from the working directory: - forces you to reenter all commit messages, and restage every commit from scratch, only now the working directory contains the aggregate of *all* the changes you've made in all the commits. This is laborious and error prone.
3. **The [wiki]((https://github.com/magit/magit/wiki/History-Manipulation))** describes a flow for moving hunks between commits. Which involves two reverses (a feature I haven't internalized yet),  a jump to a revision buffer and back, per commit. This seems like a **lot** more work than what the "rewrite" mechanism required.

The advantages of the "rewrite" feature as I see it were:

1. Gave you control over **individual hunks** by reusing the familiar stage/unstage mechanism
in the status view.
2. Allowed you to perform the whole thing (which can be complicated) in a **single screen** (status buffer) without switching views.
3. Allowed you to progress incrementally, with the **current state always visible**, showing you a fully tab-expandable history of every commit you've done so far, and what remains to be done.

I realize I'm very late to raise an objection (I'm returning to emacs from a long hiatus, partly because I missed magit), but this was my favorite part of magit and I miss it dearly. Is there something in v2 which provides the same convenience, or did perhaps the suggestion that the "rewrite" feature would be broken out into a new package materialize into something I can `package-install`?
 
"[Rewriting](http://magit.vc/manual/1.4/magit/Rewriting.html#Rewriting)" - From the 1.4 manual.

**Comment by MikeSanMichel2** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO!!!! :crying_cat_face: 

```
 * The magit-specific "rewriting" feature has been removed because it
   was a hybrid of "rebasing" and "cherry-picking" and vastly
   inferior to both of them.
```

That's terrible new. That was my favorite feature in magit and the reason I started using it years ago.
It was far superior to any other way of cleaning up the commits in a multi-step PR before submitting.

Really sad about this.

**Comment by Silex** [comment]
Well, you'd have made your voice heard when we discussed this _two years ago_ :smirk: 

I guess maybe this feature was useful for people learning git through magit? To me (who learned git through the command line), I find `git rebase -i` to be straight-forward and `rewrite` to be extremely confusing.

So far all the scenarios I have seen in favor of `rewrite` were the ones where things were pretty weird to start with, and still even for those I'd have done things with plain rebase anyway.

**Comment by MikeSanMichel2** [comment]
@Silex , I know I know, I had trouble at first too. But, I have to say most people I've talked to found **git** extremely confusing, until they get used to it. emacs too for that matter. But once you get that "aha" moment and finally understand what it can do - it becomes indispensible. That's what "rewrite" is to me.

I'm not a zealot, If there's a way to do the same thing in a better way in v2, I'll learn. But I've been looking and I can't find any. I've rewritten my OP to try to clearer (and less whiny), please help if you can.

**Comment by npostavs** [comment]
> The wiki describes a flow for moving hunks between commits. This involvs two reverses (which I haven't internalized yet) and a jump to and from the status buffer, per commit. It involves a lot more work than the "rewrite" mechanism provided.

I think the 2 reverses are equivalent to a single reversal of the index. Using [np/extract-change](https://github.com/magit/magit/compare/np/extract-change), the instructions would be

*(a) Move change after original commit.*

* Show the commit in the revision buffer.
* Move to the change in question and use `V e` to reverse it in the index.

At this point the index contains the reversal and the working tree does not. If you did unstage the staged changes you would end up with an unmodified working tree.

* Now amend the staged changes (the partial reversal) to HEAD using c e.
* And finally stage and then commit the extracted changes, or stash them for later.

**Comment by MikeSanMichel2** [comment]
Thanks @npostavs. 

This isn't working for me. Here's a step by step (comparing with my usual "rewrite" flow):

1. "Log current", move to base commit for rebase, "R i"
2. "git-rebase-todo" pops up, unnecessary but not hard to mark everything for edit and hit `C-c C-c`.
3. For some reason, this returns me to the log window instead of sending me to the status buffer where the rebase is in progress (P1). 
4. In the status, all the commits for rebase are listed with a nice status but  unlike "rewrite",
I can't tab-expand them to see their hunks using the familiar stage/unstage commands. (P2)
5. I *can` hit RET and see the revision window, but I will have to jump back and forth between
two buffers quit a lot. (P3)
6. In the revision buffer, I go to a hunk and hit V. `magit-revert-popup` appears but there's no `e` command as you said.

What's my next step, How do I move one or more hunks out of one commit and into another?

**Comment by npostavs** [comment]
> In the revision buffer, I go to a hunk and hit V. magit-revert-popup appears but there's no e there.

Sorry if that was unclear, `V e` needs to be added to magit, see  the [np/extract-change](https://github.com/magit/magit/compare/np/extract-change) branch for the patch.

**Comment by MikeSanMichel2** [comment]
Ok.  Copied and evaluated. 

@npostavs , yes this is just the thing that was missing. 

7. so I can Apply commit (cherry pick) or apply changes from commit (put them in the index)
like in rewrite. that's good.
8. One thing that's annoying is that hitting Apply (commit or changes) still prompts me to confirm which commit (with the correct default), which wasn't the case with rewrite (I think) (P4).
9.  if I "apply changes" and hit "Commit" immediately, it pops up with the right commit mesage which is nice.
10. with (8) I can apply and stage the  hunks I want from the next commit, which is great.
11. with "V e" / `magit-reverse-index` I can mark a hunk for "removal" from the last commit,
which puts the reverse diff in the index, and If I immediately commit-amend that removes
the hunk from the commit, but it keeps it in the working directory, so it's an unstaged hunk
ready for me to use on the next commit.

Yep, that's good enough for me. :trophy: 

@npostavs , thanks! will this be merged soon? I'll write up a wiki page about this flow.

**Comment by npostavs** [comment]
> One thing that's annoying is that hitting Apply (commit or changes) still prompts me to confirm which commit (with the correct default), which wasn't the case with rewrite (I think) (P4).

http://magit.vc/manual/magit/Confirmation-and-completion.html

> with (8) I can apply and stage the hunks I want from the next commit, which is great.

What is "(8)" ?

> will this be merged soon?

I'm not sure about the naming/binding. I used "e" for "Extract" because I was thinking about this particular use case, but I'm don't know if it's such a great description of what the command actually does in general. Another possibility could be to simply add it as on option to the revert popup, so you would use `V -i v` (i for index). Slightly less convenient than `V e`, but perhaps more self-explanatory.

**Comment by MikeSanMichel2** [comment]
(8) is (2). GFM mangles renumbers lists if they don't begin with 1, so (8) is actually (2),
I was refering to magit-reverse-index

The V menu isn't very "crowded" and this (to me at least) will be a common operation, I hope it ends up as a command and not an option. Also, It isn't really a modifier for the other actions, so that
doesn't fit well with how other popups work.

Naming things is always tough. "Revert Hunk"/"Stage Hunk for Removal"/"Stage Anti-Hunk"?

**Comment by MikeSanMichel2** [comment]
Actually, I'd like this even better if the command actually amended the commit right there and then,
and just left the detached hunk staged in the index: "Uncommit Hunk". Easier to understand
and saves on keystrokes, I can't think of a scenario where my next step wouldn't be "C e".

**Comment by npostavs** [comment]
Let's continue the discussion about reverse in index at #2332.

**Comment by MikeSanMichel2** [comment]
https://github.com/magit/magit/wiki/How-to-%22Rewrite%22-in-Magit-2.x

**Comment by MikeSanMichel2** [comment]
Once the revert popup has some kind of command for `magit-reverse`, preferably one that targets  hunks specifically and performs the "C e" immediately, I think this can be closed.

**Comment by npostavs** [comment]
So you don't care so much about (P1), (P2), and (P3)?

**Comment by MikeSanMichel2** [comment]
They are all (minor) inconveniences compared to original "rewrite" but none of them is a dealbreaker.

**Comment by MikeSanMichel2** [comment]
P2/P3 is really the same thing. I'm not sure why the seperation between "revision buffer" was introduced instead of using the same hirearchical commit/hunk stage/unstage mechanism. It works perfectly, always has.

**Comment by npostavs** [comment]
> I'm not sure why the "revision buffer" was introduced for selection instead of using the same hierarchical commit/hunk stage/unstage mechanism.

Actually, now I seem to recall @tarsius specifically rejected adding more diffs to the status buffer when it was suggested some time before, performance may have been one of the reasons?

**Comment by tarsius** [comment]
That was and is one reason for that to be undesirable, but I think the main reason was that it would require some refactoring which I would have liked to avoid (and also that I would like the status buffer to become even more crowded). I have done the refactoring now, for different reasons, so at least the low-level support exists, and I should probably review that decision. A lot has been said today and I'll first have to read up on that before I can really join the discussion though.

**Comment by tarsius** [comment]
> 1. "Log current", move to base commit for rebase, "Rebase interactive".
> 2. "git-rebase-todo" pops up, unnecessary for a "rewrite" but I'm fine with marking everything for edit and hitting `C-c C-c`.

Alternatively you can just skip the first step and just press <kbd>r i</kbd> without first putting point on a commit section (in the log buffer or one of the log sections inside the status buffer). If you do that, then you do however have to make sure point is not on an arbitrary commit when you do so.

**Comment by MikeSanMichel2** [comment]
@tarsius, those "little inconveniences" do add up...

I really admire your heroic work on magit and having looked at your code more closely today, even more so. But, In this one part of the new magit, I honestly find that the old tool provided a much better experience. That's how I feel.

**Comment by tarsius** [comment]
> I'm not sure why the "revision buffer" was introduced for selection instead of using the same hierarchical commit/hunk stage/unstage mechanism. It works perfectly, always has.

The status buffer shows the staged and unstaged changes, but no such changes exist in that case so no changes are shown. We could show other, already committed, changes right in the status buffer in this particular situation (while a rebase is in progress).

That would be implemented using an additional "section inserter" which inserts a section similar to `magit-insert-{staged,unstaged}-changes`, but the body would additionally be wrapped with `(when (magit-rebase-in-progress-p) ...)`. Implementing such an inserter is easy, and I would be happy to do so, but I would not want to add it to the default value of `magit-status-sections-hook`.

I am not sure what diff you want to see though. `HEAD~..HEAD`, `HEAD~...<tip-before-rebase-started>`, `HEAD...<tip-before-rebase-started>`?

**Comment by tarsius** [comment]
I like the "extract" idea. "Extract and extend" also seems reasonable. I also agree that we have to think about the name and binding some more (but let's do that in #2332).

**Comment by MikeSanMichel2** [comment]
>>    I'm not sure why the "revision buffer" was introduced for selection instead of using the same 
>> hierarchical commit/hunk stage/unstage mechanism. It works perfectly, always has.
>
> The status buffer shows the staged and unstaged changes, but no such changes exist in that case 
> so no changes are shown. We could show other, already committed, changes right in the status
> buffer in this particular situation (while a rebase is in progress).

I'm not sure how this worked in the old rewrite. In fact I can't rememeber if `git-reverse` was available then or not. But, having the status screen show a single expanded list of the commits in the rebase,
with a status that is one of only "commited/applied (to wd)/pending" and every entry's expands into a diff is what I would have liked most. `Uncommit` would just be  "tab-expand", mark, "uncommit".
I also really liked the one-keystroke per action aspect of the old "rewrite".

**Comment by tarsius** [comment]
> But, having the status screen show a single expanded list of the commits in the rebase,

That will have to wait until v2.5 when general refactoring to how diffs and logs are inserted into buffers will take place. In particular what we want here is that the diffs are not generated until the commit section is explicitly expanded by the user (for performance reasons).

Personally I am getting less and less exited about doing everything in the status buffer. I won't remove the status buffer, but the trend is toward *also* better supporting work flows which use separate buffers to accomplish certain things. Of course that means that means that window management has to be improved and in particular "jumping to the position in the switched to buffer which corresponds to the position in the previously selected buffer". That's still a lot of work, major changes are not to be expected before v2.5.

So coming back to

> I am not sure what diff you want to see though. `HEAD~..HEAD`, `HEAD~...<tip-before-rebase-started>`, `HEAD...<tip-before-rebase-started>`?

> I'm not sure how this worked in the old rewrite.

Please try to figure out what diff you want if you can only have one.

**Comment by MikeSanMichel2** [comment]
Anything already cherry picked should show a diff relative to its ancestor as commited.
Anything pending should show the diff relative to its ancestor as it was prior to the rebase.
If you apply commits out of order, you can of course hit a conflict when you try to apply.

I don't diffst changing as I applied cherry picked commits, so I'm fairly sure that's how it 
worked. Usually, the process involved shifting hunks between adjacent commits, so
conflicts weren't an issue, and so the diff-as-before-rebase was fine.

**Comment by tarsius** [comment]
In #2340 we have agreed to disagree.
