### ISSUE TITLE
magit-rebase-popup is missing "finish" command

### ISSUE THREAD

**Issue by MikeSanMichel2** [magit/magit#2333]
I've been trying to recreate the ["Rewrite"](https://github.com/magit/magit/wiki/How-to-%22Rewrite%22-in-Magit-2.x) workflow I had with v1.x today (#2330) and one that is missing is the old "Rebase - Finish" command. Which wass equivalent to hitting "r r" repeatedly until the rebase concludes or a conflict occurs.

**Comment by npostavs** [comment]
You can do `r e` (`magit-rebase-edit`) hold down `c` until all commits are marked `pick`, `C-c C-c` finishes editing, then `r r` continues rebase which now doesn't stop on any commit.

It shouldn't be too hard to write a command that does this (essentially edit a text file, and call rebase continue).

**Comment by MikeSanMichel2** [comment]
This is a recurring pattern with really pro emacs users.

Normal person: Can i have a button labeled "X" that does X?
emacs person: Why do you need that? You just press Left shift with your
nose, and right control with your ear lobe, Hit C-x twice, flip your keyboard
over and revese the polarity on batteries, then flip it back, Hit C-c Meta-Meta
S-x n, and then use the macro recorder to capture the whole thing into the kill
ring and save it under "the-thing-the-does-X-alist-caddr".

Please. Can we have a "Finish" button? ;)

**Comment by npostavs** [comment]
I was trying to stealthily lure you into implementing it yourself. ;)

**Comment by MikeSanMichel2** [comment]
Ohhhhhh. You want a PR?

**Comment by npostavs** [comment]
> The Rewrite feature in 1.x was exquisitely useful to some users and incomprehensible to others.

**Comment by npostavs** [comment]
On the wiki you wrote

> The Rewrite feature in 1.x was exquisitely useful to some users and incomprehensible to others.

I think the thing that really killed the rewrite feature is that all of people working on magit were in the 2nd group. So getting some contributions from the 1st groups would help.

**Comment by MikeSanMichel2** [comment]
That wiki *is* the help ;)

Will send PR.

**Comment by MikeSanMichel2** [comment]
More difficult than I thought. 

The old "Rewrite" tool kept track of the status of each commit included in the rebase sequence.
When you cherry-picked the commit OR when you applied it to the working directory, the
commit was marked as "spent" and out of the game. The current impl only does this 
for the cherry-picking action.

Because the 1.4x "rewrite" implemented "finish" by running "cherry-pick" for all "remaining" commits this information is still required. The todo-list, and the "done" queue are fed by the log instead of
any state magit keeps track off. That's not enough for this.

**Comment by tarsius** [comment]
So "finish" means "keep what I have already done, but don't make me do all the other things I originally intended to do". This differs from "abort" which also throws away the work you have already done, as well as from "continue" which makes you do all the things you said you would do.

Do you often find yourself in a situation where you want to "finish" like that? If so, I would recommend that you schedule less upfront. Personally I prefer to run rebase multiple times in a row. If something goes wrong or to be more complicated than expected, then I can more easily abort while losing less partial work.

The instructions provided by Noam allow you to cancel planned edits, rewords, and squashes. They do not allow you to cancel planned rearrangements. It is not possible to cancel rearrangements because Git does not keep track of the original order, it just maintains an ordered list of commits still to be applied - but that order is the modified order.

So it is not possible to implement "finish" in a way that cancels all changes that have not been carried out yet. And that makes it less useful and more surprising, which I think we should not add such a command.

**Comment by MikeSanMichel2** [comment]
As a side note (sorry, I'm still missing rewrite) the way magit shows what's done so far
during interactive rebase with "same" and "done" and "gone" and so on... I find it confusing. 

The old "Rewrite" always had the list of commits marked for inclusion in the rebase, and their
status label was simply updated as you applied them. You never saw the same hash appear twice,
You didn't to mix the rebase actions (edit/fixup) with the apply status.

I'm really having a hard time figuring out how this all works, and I'm pretty motivated.

**Comment by MikeSanMichel2** [comment]
@tarsius , it does now but back then the "selection actions" step didn't exist. You just selected
the commit range and directly went to work. so "Finish" meant "no more work, continue rebase till end".

**Comment by MikeSanMichel2** [comment]
"Finish" doesn't fit in with the new "rebase interactive". And I'm still wishing "Rewrite" was still supported. Sorry.

**Comment by MikeSanMichel2** [comment]
Final note, this action doesn't make sense because of the design of the feature. 
On the one hand you edit a manifest in the form of "rebase-todo" upfront, and then you're sent to the status screen where you can perform all those actions manually as well. 
You really only need the latter, and that was the old "rewrite" tool.

**Comment by npostavs** [comment]
> The old "Rewrite" tool kept track of the status of each commit included in the rebase sequence.
> When you cherry-picked the commit OR when you applied it to the working directory, the
> commit was marked as "spent" and out of the game.

What happened if you applied only part of a commit? What happened if you applied and then discarded the changes from the working directory?

> The current impl only does this for the cherry-picking action.

I can imagine changing so it updates the todo list on the apply action too.

**Comment by MikeSanMichel2** [comment]
> What happened if you applied only part of a commit? 

No such thing. "Apply" meant either cherry-pick or apply to working directory and both actions
"spent" the commit.  

> What happened if you applied and then discarded the changes from the working directory?

What you did with the index/wd was your own business. You needed to clean house before 
"rebase continue", or apply something else and make more commits.

After discussing this yesterday and today I realize that biggest change was the introduction
of the "rebase-todo" step, which wasn't necessary with "rewrite". You just chose your range
and performed operations. In a sense I think "rewrite" was swallowed by "interactive rebase"
when in fact it eas the other way around. "rewrite" was the more general one.
