### ISSUE TITLE
magit buffer names lack final asterisk

### ISSUE THREAD

**Issue by joostkremers** [magit/magit#2334]
After a recent update, the buffers that magit creates have names that start with an asterisk, but they do not end with an asterisk. Not sure if this is intentional or an oversight, but I thought I should mention it.

**Comment by kyleam** [comment]
Thanks for checking.  AFAIU it was an intentional change as part of
the recent uniquify-related changes (52f858a, 082fd09).  You can
specify magit-buffer-name-format to what you like, but, as the
docstring mentions, it should end with "%t" if
magit-uniquify-buffer-name is non-nil.

**Comment by joostkremers** [comment]
Ah ok, thanks for the pointers. I thought it might be an error because internal buffers often have names that begin and end with an asterisk and magit used to follow this practice.

**Comment by tarsius** [comment]
I do intend to look into whether it is possible to have a star at the end at some point. But it's not a priority and it might not be possible anyway - at least not without patching `uniquify.el`.

**Comment by kyleam** [comment]
> I do intend to look into whether it is possible to have a star at
> the end at some point. But it's not a priority and it might not be
> possible anyway - at least not without patching uniquify.el.

FWIW I looked into uniquify a bit today and couldn't come up with a
clean way to use a trailing star.  So I think it would require some
ugly post-processing on our end or some deep changes to uniquify.
Perhaps too much hassle for a trailing star.

**Comment by joostkremers** [comment]
> Perhaps too much hassle for a trailing star.

Definitely. Thanks for looking into it. All that's really important to me is that there is at least some part of the name that makes it possible to identify a buffer as a magit buffer, so I can exclude them from my buffer switcher. Since they still start with `*magit` under the current scheme, that's not a problem.
