### ISSUE TITLE
--no-verify doesn't work with fixup

### ISSUE THREAD

**Issue by mgalgs** [magit/magit#2339]
When I use the `--no-verify` switch with `Commit -> Fixup` the resulting git command (from the `*magit-process*` buffer) does not actually include `--no-verify`.

**Comment by tarsius** [comment]
Actually all the fixup variants ignore all of the popup arguments. Should we change that?

**Comment by npostavs** [comment]
> Should we change that?

I think yes, ignoring the args sounds like a simple mistake to me (I can't think why you would want to ignore them).

**Comment by tarsius** [comment]
Well I think I did it that way because I though the arguments were simply irrelevant because their effect would vanish once the fixup commit gets combined with the target commit. But at least for `--no-verify` that's not actually how it works. So I tend to agree.

**Comment by mgalgs** [comment]
Right, pre-commit hooks can fail on a fixup commit but pass on the result of squashing that fixup with the commit being fixed up.  So bypassing the hooks when committing the fixup itself is crucial.
