### ISSUE TITLE
staged changes preview when commiting always shows what's staged in main (not current) worktree

### ISSUE THREAD

**Issue by jamienicol** [magit/magit#2341]
Steps to reproduce:
* (Optional), make some changes and stage them in the main repo
* From terminal, run `git worktree add ../worktree2`
* Make and stage some changes in worktree2
* From the worktree2 magit-status buffer, type `c c` to commit the changes

As well as popping up a COMMIT_EDITMSG buffer, this also pops up a magit-diff buffer showing the changes. In this case it should show the changes you've staged in worktree2, but instead shows what you've staged in the main worktree (or says nothing is staged, depending on if you did the optional step).

The commit works as expected, it's just the staged changes preview that is wrong.

**Comment by tarsius** [comment]
That should do the trick.
