### ISSUE TITLE
magit-log-format-graph-function not called on all graph lines

### ISSUE THREAD

**Issue by csrhodes** [magit/magit#2343]
Hi,

`magit-log-format-graph-function` (which is settable to `magit-log-format-unicode-graph`) does not seem to be called on all lines of the log: only those associated with a commit.  Setting it to `magit-log-format-unicode-graph` then gives an uncomfortable mixture in a log for a repository with a complicated history.

I attach a screenshot to illustrate what I see:

![screenshot from 2015-10-16 19-35-40](https://cloud.githubusercontent.com/assets/1670142/10550156/2795bf18-743d-11e5-80a5-70166fe1f88b.png)

I tried adapting `magit-log-wash-rev` to handle this, and got something that works for me, but I'm far from sure it's correct or harmless in all cases (since that function handles a lot of options).  How can I test that?

```diff
@@ -949,5 +994,9 @@
                   (save-excursion (insert align)))
                 (magit-format-log-margin)
-                (forward-line))
+                (cond
+                 ((looking-at "[-_/|\\*0. ]*$")
+                  (insert (funcall magit-log-format-graph-function (match-string 0)) ?\n)
+                  (kill-region (point) (progn (forward-line) (point))))
+                 (t (forward-line))))
               ;; When `--format' is used and its value isn't one of the
               ;; predefined formats, then `git-log' does not insert a
```

Thanks,

Christophe

**Comment by tarsius** [comment]
I was wondering why nobody every reported that. That broke a long time ago I think and I am not sure if I am going to fix or remove it. In about three releases it will be replaced with something better anyway.

**Comment by tarsius** [comment]
I'll checkout your fix though, that might be good enough.

**Comment by tarsius** [comment]
Ps: `magit-log-wash-rev` is one of the grossest functions in all of Magit.

**Comment by tarsius** [comment]
I am most likely going to just remove this feature for the time being.

**Comment by tarsius** [comment]
I have removed the broken support for unicode graphs. That implementation only was an intermediate step anyway. See  #1425 for where we are headed.
