### ISSUE TITLE
Make sections more reusable with fancier keymap resolution

### ISSUE THREAD

**Issue by MikeSanMichel2** [magit/magit#2344]
After downgrading to 1.4.2 to get the Rewrite tool back I quickly realized I'm already used to some of the new features and don't want to give them up. predictable. So I caved and now I've got a semi-working update of magit Rewrite to v2.x.

One problem I'm facing is the coupling between keymaps, washing and section types.
Reusing the canned `commit`/`hunk` types is easy and the washing (quite tricky to implement) simply works then, but the type also forces the section keymap which blocks me from providing
my own.

What I'd like to have is something akin to what `magit-section-match` [code](https://github.com/magit/magit/blob/4f0525ad19c6558e17ebf88cf4e00fdf74ae3e10/lisp/magit-section.el#L527) provides, which is to looks at not only the type but optionally those of the parent sections as well, all the way to the root.
One way to make this work would be to extend the name-based resolution of in the obious way. So if a section nesting looks like:
```
bar
   foo
     baz
     baz
```
You would first look for a `magit-baz-foo-bar-section-map`, then `magit-foo-baz-map`
and finally the `magit-baz-section-map` (which currently, is always used if defined). This should break no code in magit or outside of it. Of course there may be other, better,  ways to solve this.

**Comment by tarsius** [comment]
What about

```lisp
(defun some-rewrite-command ()
  (interactive)
  (magit-section-case
    ([commit * rewrite]
     ...)
    (t (user-error "Cannot do that here"))))

(define-key magit-commit-section-map KEY 'some-rewrite-command)
```

**Comment by MikeSanMichel2** [comment]
That'll work, but what if some other package does the same thing?

**Comment by tarsius** [comment]
Let's worry about that when it happens.

**Comment by MikeSanMichel2** [comment]
If the key overriden exists in the builtin map, the snippet above would cause the same command to bork with "cannot do that here" under any section other than `rewrite`. Here's a version that takes care of that:

```elisp
(defmacro magit-override-section-map-key (map key command type)
  (let ((next-command (eval `(cdr (assq ,key (cdr ,map))))))
    `(define-key ,map [,key] (lambda ()
                               (interactive)
                               (magit-section-case
                                 (,type
                                  (,command))
                                 (t
                                  (when ,next-command
                                    (,next-command))
                                  ))
                               ))))

```

**Comment by npostavs** [comment]
> ``(eval `(cdr (assq ,key (cdr ,map))))``

I'm pretty sure this is the same as `(cdr (assq key (cdr map)))`, though it might be nicer to use `(lookup-key map key)`.

**Comment by MikeSanMichel2** [comment]
@npostavs,  yes on `lookup-key`, but I think no on `eval`. It has to be evaluated outside the lambda, so we use the value we're replacing as a fallback.

**Comment by npostavs** [comment]
> We need to evaluate the form beforehand

right, so don't quote it, and then the eval is not needed.

**Comment by MikeSanMichel2** [comment]
For crying out loud. no. macro arguments are not evaluated unless you do so explicitly or the form returned by the macro is evaluated.

**Comment by npostavs** [comment]
Oh right, I was confused by the quoting, the other possibility is actually `(cdr (assq (eval key) (cdr (eval map))))`, not really better.

**Comment by tarsius** [comment]
```lisp
(defun magit-rewrite-apply (commit)
  (interactive (list (magit-commit-at-point)))
  (magit-section-case
    ([commit pending]
     (magit-apply-commit commit)
     (magit-rewrite-set-commit-property commit 'used t))
    (t
     (call-interactively #'magit-apply))))

(define-key magit-commit-section-map "a" 'magit-rewrite-apply)
;;                ^^^^^^^^^^^^^^
```

**Comment by MikeSanMichel2** [comment]
@tarsius, not sure what change in particular you've recommending. I should use `call-interactively` to call the fallback instead, yead, but why the emphasis `^^^^^^^^` added  on `magit-commit-section-map`?

**Comment by MikeSanMichel2** [comment]
```elisp
(defmacro magit-override-section-map-key (map key command type)
  (let* ((next-command (eval `(lookup-key ,map [,key] )))
         (sym (gensym (format "override-%s-%s-" (symbol-name map) key)))
         )
    `(progn (defun ,sym ()
              (interactive)
              (magit-section-case
                (,type
                 (,command))
                (t
                 (when ,next-command
                   (call-interactively ,next-command))
                 )))
            (put ',sym 'previous-handler ',next-command)
            (define-key ,map [,key] ',sym))))

(magit-override-section-map-key magit-commit-section-map ?a magit-rewrite-apply [commit pending])
(magit-override-section-map-key magit-commit-section-map ?A magit-rewrite-pick [commit pending])
; get the symbol for the previous handler, to unhook
;; (get (lookup-key magit-commit-section-map [?a] ) 'previous-handler)
```
- generates a defun with a descriptive name, using gensym
- stores the handler it replaces in a 'previous-handler` property on the symbol. Could also have been a lambda that actually restores it instead

There's still the problem of hooking order:
```
(hook [commit foo rewrite])
(hook [commit foo]) ; this will always trump the above, but is actually *less specific*
```

But after looking at the magit extension packages on MELPA, it seems @tarsius is the one
who wrote nearly all of them, so coordination should't be much of an issue ;)

**Comment by tarsius** [comment]
> There's still the problem of hooking order:

There is a very easy solution to that issue. Use this:

```lisp
(defun magit-rewrite-apply ()
  (interactive)
  (magit-section-case
    ([commit pending]
     (let ((commit (magit-section-value it)))
       (magit-cherry-apply commit)
       (magit-rewrite-set-commit-property commit 'used t)))
    (t
     (call-interactively #'magit-apply))))

(define-key magit-commit-section-map "a" 'magit-rewrite-apply)
```

and completely discard your `magit-override-section-map-key` idea.

**Comment by tarsius** [comment]
> why the emphasis `^^^^^^^^` added  on `magit-commit-section-map`

Because earlier you said

> If the key overriden exists in the builtin map, the snippet above would cause the same command to bork with "cannot do that here" under any section other than `rewrite`.

And that cannot happen unless you use a keymap different from `magit-commit-section-map`.

**Comment by MikeSanMichel2** [comment]
> There is a very easy solution to that issue. Use this:
> ...
> (define-key magit-commit-section-map "a" 'magit-rewrite-apply)

Sorry for being blunt, @tarsius, but this is fugly.
a function that is concerned with applying a diff should not be contaminated with
completely unrelated noise about method resolution logic. The solution still requires
explicit cooperation between all participants, rewriting the function everytime a new
case is added.... it's a bad solution and I think a macro makes far more sense here.

> and completely discard your magit-override-section-map-key idea.

nah.

**Comment by MikeSanMichel2** [comment]
>> If the key overriden exists in the builtin map, the snippet above would cause the same command to > bork with "cannot do that here" under any section other than rewrite.

> that cannot actually happen unless you use a keymap different from magit-commit-section-map.

Right, it can't happen now that you've fixed your version, no.

**Comment by tarsius** [comment]
> Sorry for being blunt, @tarsius, but this is fugly.

I strongly favor a little dirty hack over an unnecessary, complicated, badly implemented, and equally ugly "abstraction". You are focusing on the wrong thing. First get "rewriting" working, ignoring all potential conflicts (use `f1`... as the key bindings to avoid conflicts for the time being). *Then*, once rewriting actually works, publish that, and now you can start worrying about the issue you would rather have tackled first. Hint: I am pretty sure it is a non-issue, but since you have not published any code that I could inspect to confirm that, all I am left with is telling you to keep it simple and listening to you insisting on adding abstractions. There is *no way* I am going to add `magit-override-section-map-key` to Magit.

**Comment by MikeSanMichel2** [comment]
> I strongly favor a little dirty hack over an unnecessary, complicated, badly implemented, and 
> equally ugly "abstraction".

That's your right. I prefer a reasonable solution written without too much effort to both those alternatives.

> all I am left with is telling you to keep it simple and listening to you insisting on adding abstractions.

I insisted on nothing. Your original sketch had a serious bug (not an aesthetic issue, a bug), so I rolled my own solution and thought it would be helpful to point out the problem and sharing a working solution in case a future visitor sees this issue and needs something that works. Sharing code is fairly common practice on github.

> There is no way I am going to add magit-override-section-map-key to Magit.

No one has asked you to, I closed this issue yesterday.

**Comment by tarsius** [comment]
> a function that is concerned with applying a diff should not be contaminated with completely unrelated noise about choosing handlers.

For an alternative approach consider this snippet:

```lisp
(magit-insert-section section (commit commit)
  (insert ...)
  (put-text-property (magit-section-start section)
                     (magit-section-end section)
                     'keymap 'magit-stgit-patch-map))
```

and see https://github.com/magit/magit-stgit/blob/master/magit-stgit.el#L643 for an example.

**Comment by MikeSanMichel2** [comment]
hmmm.
