### ISSUE TITLE
Magit does not ask for SSH passphrase when doing a push

### ISSUE THREAD

**Issue by arvindkhadri** [magit/magit#2346]
I am using magit 2.2.2. from marmalade. When I push a commit, magit has stopped asking for SSH pass phrase.
I evaled this expression ``` (magit-git-string "config" "credential.helper") ``` and got ``` nil ``` as a value. 
``` M-x setenv SSH_AUTH_SOCK ``` and ``` M-x setenv SSH_ASKPASS ``` to an empty value brings back the expected behaviour of asking pass phrase.

**Comment by npostavs** [comment]
OS and git versions?

> M-x setenv SSH_AUTH_SOCK and M-x setenv SSH_ASKPASS to an empty value brings back the expected behaviour of asking pass phrase.

What non-empty values do they have before you do that?

**Comment by arvindkhadri** [comment]
Arch Linux, and git 2.6.1. I didn't check inside emacs, but the values on my shell for SSH_AUTH_SOCK is ``` /run/user/1000/keyring/ssh ``` and for SSH_ASKPASS ``` /usr/lib/ssh/x11-ssh-askpass ```

**Comment by npostavs** [comment]
> When I push a commit, magit has stopped asking for SSH pass phrase.

But the push still succeeds?

> the values on my shell for SSH_AUTH_SOCK is /run/user/1000/keyring/ssh

This sounds like you are running ssh-agent, so it's expected that you only need to enter your ssh passphrase once per login session.

**Comment by arvindkhadri** [comment]
I see, thanks for clarifying. How can I remove/stop ssh-agent?

**Comment by tarsius** [comment]
Why do you *want* to enter the password more than once?

`ssh-agent -k`

From the manpage:

> -k      Kill the current agent (given by the SSH_AGENT_PID environment variable).

**Comment by arvindkhadri** [comment]
Well, I just do not like the fact that push succeeds without me entering the pass phrase. It seems like I have gnome-keyring-daemon which is running the agent. 
Thanks for the help. Shall I close the issue?

**Comment by tarsius** [comment]
You are welcome.

**Comment by igoralmeida** [comment]
I think I'm having a problem similar to this, but I don't have ssh-agent running. I'm trying to do a fetch but the passphrase prompt is not shown to me, even though I can see it with `$`.
How could I debug this? (By the way, I'm on the [ancient] spacemacs master with magit "20180205.629")

**Comment by rndusr** [comment]
@igoralmeida This is probably the same issue as #3843 fixed in #3849.
