### ISSUE TITLE
`magit-log-buffer-file` side effect

### ISSUE THREAD

**Issue by YorkZ** [magit/magit#2347]
Hi,

I'm using the latest version, commit 6c60435, and noticed that the command `magit-log-buffer-file` has persistent side effect. Once I run `M-x magit-log-buffer-file` to view the logs for the current buffer file, any log commands I run later will be locked to show only the logs for the file I previously viewed the log history. The side effect lasts until I restart Emacs.

Thanks,

York

**Comment by kyleam** [comment]
> Once I run M-x magit-log-buffer-file to view the logs for the current
> buffer file, any log commands I run later will be locked to show only
> the logs for the file I previously viewed the log history.

The switches and options are local to a repo's log buffer and persist
with the buffer across log calls.  The PR #2146 has some discussion
related to this.

> The side effect lasts until I restart Emacs.

To remove the restriction, you can remove the file argument in the log
popup, or you can kill the log buffer instead of burying it.

**Comment by YorkZ** [comment]
Thank you very much Kyle, I didn't notice that. Have the benefits of this behavior been discussed in #2146 already? I'll take a look if so.

By the way, what does "30 support" label mean?

**Comment by tarsius** [comment]
It means "support" and the "30" is there to order the various labels. I'll probably drop these prefixes at some point, as I haven't added them for newer labels anyway.

**Comment by kyleam** [comment]
> Have the benefits of this behavior been discussed in #2146 already?

The main benefit is that you can build off of and tweak previous calls
without having to go through the whole sequence again.

PR #2164 was mostly me saying, despite these benefits, I don't prefer
this behavior and wanted to add an option to disable.  However, in that
thread, @uu1101 mentioned the already planned idea of making the
previous popup state history available.  That way, new popups would have
the default state, but you could get to old ones easily with M-p or
something.  The conclusion of the thread was that we should go in that
direction and not bother with adding an option in the meantime, which I
think is a good idea.

**Comment by YorkZ** [comment]
Thanks for the explanation Kyle and Jonas. I like the idea of having the default and user can always press M-p to get the history.

By the way, thank you so much for you guys' hard work, the new Magit is really nice! I love it!

**Comment by kyleam** [comment]
> Thanks for the explanation Kyle and Jonas.

You're welcome.  Glad to help.

> By the way, thank you so much for you guys' hard work, the new Magit is really nice! I love it!

s/guys/Jonas/ :)
