### ISSUE TITLE
magit-status fails with Wrong type argument: symbolp, (cyg . win)

### ISSUE THREAD

**Issue by calve** [magit/magit#2350]
After a fresh install of magit (d2a7885), ``magit-status`` fails with ``Wrong type argument: symbolp, (cyg . win)``.

This behaviour disappears if I checkout my local installation of magit to 6c60435, and `magit-status` work as expected. So this bug may have been introduced by a2322af.

Let me know if I can provide any other information to fix the problem.

**Comment by npostavs** [comment]
What is your `dash` version?

**Comment by calve** [comment]
I was using 2.9.0. Upgrading to 2.12.0 indeed fixed the issue.

It looks like the line ``;; Package-Requires: ((emacs "24.4") (async "20150812") (dash "2.11.0")``  in magit.el have not been fully honored .

**Comment by tarsius** [comment]
The problem is that e.g. `19700101` is "bigger" than `2.11.0`, so *any* version that was ever available from Melpa will satisfy `2.11.0`. I'll fix that by depending on `20151021` (aka `2.12.1` which comes with an important fix).
