### ISSUE TITLE
magit-log doesn't handle different length commit hashes correctly

### ISSUE THREAD

**Issue by mbertheau** [magit/magit#2351]
Sometimes a hash is 8 instead of 7 characters long. Then it looks like this:
![image](https://cloud.githubusercontent.com/assets/133575/10625911/cfb6e202-77a9-11e5-89f4-01bb1fddee24.png)

This is by no means a big problem for me or anybody else I'd imagine, just a fyi.

**Comment by kyleam** [comment]
Do you see the same thing with 'git log --graph --oneline'?  Git will
extend the length of the hash if the hash isn't unique at the specified
abbreviation length (the default is 7).  You could test this by calling
'git rev-parse --short=7 f2b790a0' on the command line to see if all 8
characters are retained.

**Comment by mbertheau** [comment]
@kyleam git log --graph puts the edges and nodes of the tree in front of the hash, so it doesn't break:
```
* 6cf195f Phrase condition more naturally
* f98fd92 Add a clarifying comment
* f2b790a0 Introduce symbol to clarify the meaning of some numbers
* 544c937 Free service fee functions from the joch of the model
* 5f77d88 The new url tag is the default now
```

**Comment by tarsius** [comment]
Someone sometime decided to put the hashes first, presumingly because it "looks better". It that happens a lot and if you are sufficiently bothered by it, then you can increase the value of the Git variable ` core.abbrev` to make it go away.
