### ISSUE TITLE
magit-popup keybinding convenience functions don't support sequence-actions

### ISSUE THREAD

**Issue by MikeSanMichel2** [magit/magit#2353]
`magit-remove-popup-key` doesn't support an `:action-sequence` argument.
There's also no `magit-define-popup-sequence-action` like the provided `magit-define-popup-action`, `magit-define-popup-switch`, etc'

**Comment by tarsius** [comment]
Actually it does, but it is not documented and the key is named `:sequence-actions`. For each popup `magit-*-popup` there is a variable by the same name, whose value is a plist. The valid keys are describe in `magit-define-popup`.

```lisp
(magit-remove-popup-key 'magit-rebase-popup :sequence-actions ?r)
```

But I suspect what you actually want to do is this:

```lisp
(magit-change-popup-key 'magit-rebase-popup :sequence-actions ?r ?c)
```

But there is no `magit-define-popup-sequence-action` function, and `magit-define-popup-key` did not support the key `:sequence-actions` (or `:sequence-action`). I have added the former now and adjusted the documentation.

**Comment by MikeSanMichel2** [comment]
Thank you.
