### ISSUE TITLE
git-commit dependencies are unavailable

### ISSUE THREAD

**Issue by gmmeyer** [magit/magit#2355]
git-commit requires with-editor "20151022", the latest available on MELPA is "20151010.1026", making it impossible to install.

**Comment by agzam** [comment]
ouch... it broke my Emacs... ;(

**Comment by tarsius** [comment]
Packages on Melpa are build in alphabetic order, even when multiple packages come from the same repository. Unfortunately in case of the Magit repository the packages are spread across the alphabet about as far as possible and so it can take a few hours until all "internal-dependencies" become available when I bump them.

**Comment by tarsius** [comment]
All dependencies are available now.

**Comment by gmmeyer** [comment]
:+1:
