### ISSUE TITLE
It is non-obvious when a rebase fails to start

### ISSUE THREAD

**Issue by thiderman** [magit/magit#2356]
I was trying to do an autosquash with a newly added `fixup!` commit, but nothing happened. The only message show by magit was the default `(No buffers need to be reverted)`, which I take as "nothing happened". It took me a couple of minutes to realize I had unstaged changes, and I verified it with `magit-process`:

```
  1 git … rebase -i --autosquash ee252d67d10ebcc5f85e13f984f6e5d54200a476
Cannot rebase: You have unstaged changes.
Please commit or stash them.   
```
(there was like 25 of these :P)

The error is obviously on me, but magit did not do anything obvious to tell me what I was doing wrong. My suggestion is to do something that improves the UX when a command fails like this. Perhaps a more visible message somewhere in the `magit-status` buffer.

I'd also recommend adding a warning to the `*magit-rebase-popup*` buffer when there are unstaged changes or other states that would not allow a rebase. To my knowledge, no `git rebase` commands work with a dirty tree, so magit could definitely be helpful and say "hey this won't actually work until you stash or commit!". Maybe it could even do a `stash - rebase - pop stash` workflow, just to be helpful?

**Comment by tarsius** [comment]
Please see the doc-string of `magit-revert-buffers`.
