### ISSUE TITLE
colorize diff like vc-diff

### ISSUE THREAD

**Issue by Dushistov** [magit/magit#2358]
For example let's I have such content of *magit-revision*

diff --git a/cmake/FindLibClang.cmake b/cmake/FindLibClang.cmake
index 8aa7689..62b5b08 100644
--- a/cmake/FindLibClang.cmake
+++ b/cmake/FindLibClang.cmake
@@ -72,7 +72,7 @@ if (NOT LIBCLANG_CXXFLAGS)
     endif ()
     set(LIBCLANG_CXXFLAGS "-I${LIBCLANG_CXXFLAGS}")
   endif ()
-  string(REGEX REPLACE "-([Og][0-9]*|std=c\\+\\+..|(W|f)[a-zA-Z-]*|DNDEBUG) ?" 
"" LIBCLANG_CXXFLAGS "${LIBCLANG_CXXFLAGS}")
+  string(REGEX REPLACE "-([Og][0-9]*|std=c\\+\\+..|(W|f)[=a-zA-Z-]*|DNDEBUG) 
?" "" LIBCLANG_CXXFLAGS "${LIBCLANG_CXXFLAGS}")
   set(LIBCLANG_CXXFLAGS ${LIBCLANG_CXXFLAGS} CACHE STRING "The LLVM C++ 
compiler flags needed to compile LLVM based applications.")
   unset(LIBCLANG_CXXFLAGS_HACK_CMAKECACHE_DOT_TEXT_BULLSHIT CACHE)
 endif ()

the diff-mode highlight string with starting "-" with red, and starting "+" 
with green,
it would be great if it  highlight also difference between strings.
There is only "=" symbol difference between two lines above, so it would be 
great
if emacs highlight also "=" in the second string.

You can see how github doing this:
https://github.com/Dushistov/rtags/commit/5d0419c453dde58bf3a37a00bf0e63bd186154bc

In *vc-diff* mode if you choose chunk of diff with "n" or "p", the "=" will be highlited,
it would be great if in magit this work too.

**Comment by npostavs** [comment]
Are you looking for `magit-refine-hunk`?

**Comment by Dushistov** [comment]
>Are you looking for magit-refine-hunk?

Yes, it would be great if it works automatically by default

**Comment by tarsius** [comment]
I intend to change the default value of `magit-refine-hunk` eventually, but not until the basic diff coloring has gotten faster, so probably in v2.5 or so (see #2180). Until then you'll have to customize it.
