### ISSUE TITLE
magit-insert-diff isn't customizable, in particular for adding --ignore-space-change

### ISSUE THREAD

**Issue by MikeSanMichel2** [magit/magit#2361]
This is a particular pain point a lot of users must suffer from when contributing patches.

I often end up with a lot of whitespace noise in my diff when contributing patches to other projects.
dozens of these can turn up in the staging diffs which I have to tediously skip over and over and over again.
git knows things. in particular `git diff` has `--ignore-space-change` which just ignores them. But
since the args for `magit-insert-diff` aren't customizable I can't easily use it.

Note that sometime I want to see those (like when I just fixed a whitespace issue) and sometimes not,
so really a way to easily toggle this would be so so so useful.

**Correction**: I actually care about `magit-insert-unstaged-changes` which calls wash directly, but same applies.

**Update**: need to be careful, or "unstaged changes" would shows nothing while the working directory would be unclean which could cause some confusing errors for git operations that demand a clean wd.

**Comment by npostavs** [comment]
I think you are looking for `magit-diff-refresh-popup` (`D`).

**Comment by MikeSanMichel2** [comment]
Oh, so I am, didn't know it was there nor that it controlled the status display. Thank you.

**Comment by MikeSanMichel2** [comment]
Added to wiki tricks page.
