### ISSUE TITLE
.git file not recognized?

### ISSUE THREAD

**Issue by kccai** [magit/magit#2364]
I am using the latest magit version in melpa 
```
    Archive: melpa
    Version: 20151024.220
```

I have a .git file in my working directory which is pointing to a .git folder in another directory. The content of the .git file is in the following
```
gitdir: /home/me/Documents/myprj/.git/
```

When I stage the changed files and press `c`, I see the following errors in `*magit-process...*` buffer. And I cannot commit using magit. But committing in commandline works fine.

```
*ERROR*: Not inside a Git repository
error: There was a problem with the editor '/usr/bin/emacsclient --socket-name=/tmp/emacs1000/server'.
Please supply the message using either -m or -F option.
```

Can anyone help? Thanks!

**Comment by tarsius** [comment]
I am using such ".git files" myself and am not having any problems with it.

E.g. `~/.emacs.d/lib/macrostep/.git`:

```
gitdir: ../../.git/modules/lib/macrostep
```

Try if you can fix this by using a relative file name. So far I have only encountered relative file names in these files. How did you create that file? It's possible that absolute file names are not handled correctly yet, at least I did not explicitly handle that case and there also are no tests for it.

**Comment by tarsius** [comment]
What OS are you using? If Windows, then what Git build and what Emacs build?

**Comment by kccai** [comment]
Hi, @tarsius , my system information is in the following. 

```
- OS: Arch linux (x86_64 Linux 4.2.3-1-ARCH)
- Emacs: 24.5.1
- magit: Version: 20151024.220
```
I changed the path described in the .git file to a relative path, but I still get that `Not inside a Git repository` error. Now I installed the magit stable version 2.2.2 and everything is fine. I think maybe some commits broke magit in the master branch.

**Comment by kyleam** [comment]
I can reproduce this with

    gitdir: ../magit/.git/

in a directory at the same level as the magit repo.  I've bisected it
to 4d035b5 (magit-toplevel: return correct wtree from within
.git/worktrees/ID, 2015-10-15).

**Comment by kyleam** [comment]
1156e6d37 seems to do the trick, although I'm not sure whether .git/gitdir, if it exists, always contains just ".git".

**Comment by kccai** [comment]
@kyleam  Your fix works! Thanks!

**Comment by tarsius** [comment]
`gitrepository-layout(5)` does not mention a file `.git/gitdir`, just `.git/worktrees/<id>/gitdir`. So the existence of the former might be the result of a bug somewhere, as far as I know. Please explain, using an example, what (git) commands I have to use for that file to appear. I have tried `submodule` and `worktree`, but neither created that file.

**Comment by kyleam** [comment]
> `gitrepository-layout(5)` does not mention a file `.git/gitdir`, just
> `.git/worktrees/<id>/gitdir`. So the existence of the former might be
> the result of a bug somewhere, as far as I know.

I haven't been able to find any information about ".git/gitdir" when
searching the documentation, mailing list, or by grepping git's repo.
It's probably worth asking about on the list.

> Please explain, using an example, what (git) commands I have to use
> for that file to appear. I have tried `submodule` and `worktree`, but
> neither created that file.

The example I gave above does it for me (git version 2.6.1).  If I have
a directory next to magit's with ".git" as

    gitdir: ../magit/.git/

then magit's main repo has a ".git/gitidir" file (containing just
".git") after invoking git from the secondary directory.

In general, if I have repo A with a ".git" file that points to repo B, I
see a ".git/gitdir" file in repo B after a git command (e.g., git
status, but probably any git command) is called in repo A.

**Comment by kyleam** [comment]
I've asked about ".git/gitdir" on the git list: http://thread.gmane.org/gmane.comp.version-control.git/280307
