### ISSUE TITLE
Unstaged/staged section items don't seem to obey section keymap

### ISSUE THREAD

**Issue by maio** [magit/magit#2368]
How to reproduce:
1. `make magit`
2. Replace binding in section map (e.g. `(define-key magit-unstaged-section-map "k" 'unknown-fn)`)
3. Navigate to section item and hit the key

- Expected result: `Symbol's function definition is void: unknown-fn`
- Actual result: `Discard unstaged changes in ...?`

![image](https://cloud.githubusercontent.com/assets/18138/10786861/ff6ee2b0-7d6c-11e5-8d3d-c084efb8e524.png)

**Comment by tarsius** [comment]
That keymap is only used for the `untracked` section itself, but not for its children. So it is only used on the heading (and the separator line that follows the last child).

To define a binding for the children, you have to use the `magit-commit-sections-map`. But that affects all `commit` sections, not just children of `untracked`. So you would have to differentiate between the different kinds of `commit`s inside the command, which can be done using `magit-section-case`.

**Comment by maio** [comment]
Ah OK I see. Thank you for quick reply! (It seems that I have to use `magit-file-section-map` for this particular binding).

**Comment by tarsius** [comment]
Yes right, don't know why I kept mentioning commits.
