### ISSUE TITLE
How to auto update VC mode line?

### ISSUE THREAD

**Issue by zwb-ict** [magit/magit#2371]
My OS is Mac OS X 10.11.1
Emacs version: 24.5.1 (brew)
Magit version is lastest
Emacs config: Prelude

After I commit or create and checkout a new branch with magit, then swtich to the file buffer,  and found, the VC mode line is still old.

I saw magit has a function called *magit-refresh-vc-mode-line* but I don't know how to use it. Would you please give me a hand? Thank you very much.

**Comment by tarsius** [comment]
That function is run by the hooks `magit-after-revert-hook` and `magit-not-reverted-hook`. One of these hooks is run by `magit-revert-buffer` for each file-visiting buffer belonging to the repository. That function in turn is run after most Magit commands, provided the value of `magit-revert-buffers` is non-nil.

Check the values of these three options to figure out where the chain is broken.

---

In the future, please use http://emacs.stackexchange.com to get support. When you opened this issue you did see this message: **"Please review the [guidelines for contributing](https://github.com/magit/magit/blob/master/CONTRIBUTING.md) to this repository"**, which you apparently ignored. Following that link would have brought you to a page that requests that you use the Stackexchange site to get support. We also make the same request on the [Github landing page](https://github.com/magit/magit#support), the [wiki](https://github.com/magit/magit/wiki#support), and the [homepage](http://magit.vc/). -- Thanks

**Comment by zwb-ict** [comment]
@tarsius Thank you for your help, and I do a apologize to you that I didn't see the <https://github.com/magit/magit/blob/master/CONTRIBUTING.md/> carefully. In the future, I'll use  <http://emacs.stackexchange.com/> to get support.

I checked those three options, all of them are OK. 

Then I found  <https://github.com/Malabarba/smart-mode-line/issues/95/> is in the same situation as I met. 
After I set (auto-revert-check-vc-info t), everything works OK now.
