### ISSUE TITLE
Why not allow users to specify arguments in the popup interface that are not defined?

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2376]
Hello,

maybe there should be a simple way for the user to specify an argument (that has not been officially defined as popup switch or option by the package or the user) on the fly in the interface. Or is it forbidden by intent?

Currently, the popups show only a small subset of options (which is good because it concentrates on the most important aspects).  OTOH all options are potentially useful; adding them all to the popup for these rare cases seems wrong.

So, why not just add a generic option that let's you add arbitrary arguments for the respective git command?

TIA.

**Comment by tarsius** [comment]
There's a lot of accidental complexity in `magit-popup` and will eventually write a new library from scratch. But I haven't gotten around to that yet and have decided to avoid implementing new features now unless absolutely necessary.

One reason for not adding any new features now is that I don't know yet in what user-visible way the new implementation will differ, so anything I add now might be something that I later "take away" from users again.

So no, I don't intend to implement anything like that before v3.1, and it is very much in the open whether I will do so in v3.1's successor to `magit-popup`.
