### ISSUE TITLE
*ERROR*: Symbol's value as variable is void: magit-mode-setup--topdir

### ISSUE THREAD

**Issue by juszczakn** [magit/magit#2377]
magit-process buffer shows following error whenever trying to initiate a commit.

      1 git … commit --
    Waiting for Emacs...
    *ERROR*: Symbol's value as variable is void: magit-mode-setup--topdir
    error: There was a problem with the editor '/usr/local/bin/emacsclient --socket-name=/tmp/emacs1000/server'.
    Please supply the message using either -m or -F option.

Also see a similar message about this variable when trying to open a commit via log.

Using magit-20151028.1649 and magit-popup-20151031.903 from elpa. Will try investigating more later.

**Comment by tarsius** [comment]
The new Magit version was compiled while the old version was already loaded and a macro was modified. This resulted in the old definition of the macro to leak into the byte-compiled library. To fix this uninstall `magit`, restart Emacs, and only then install `magit` again. Recent versions of Magit depends on `async` to prevent this sort of thing, but that only kicks in when the currently installed version already depends on `async`, not when updating from a version which does not depend on `async` to one that does.

**Comment by juszczakn** [comment]
Yea just to confirm, that did fix the issue. Thanks!
