### ISSUE TITLE
magit 2.3.0: Key "C" seems to hang emacs when magit-status when repo dir is a symlink

### ISSUE THREAD

**Issue by absurd34** [magit/magit#2378]
Hi,

with 2.3.0, key "C" is bound again (which I appreciate ;).

However, it (shows the commit buffer and then) seems it's entering and endless loop, both when used on a bulk or a file.

Could someone please verify this (so I can rule out some local hickup ;)?

Thx!

Stephan

**Comment by tarsius** [comment]
I cannot reproduce this. I tried when a commit was already in progress and also when no commit was in progress yet.

**Comment by absurd34** [comment]
Hi Jonas,

On Di, 2015-11-03 at 06:39 -0800, Jonas Bernoulli wrote:
> I cannot reproduce this. I tried when a commit was already in progress and also when no commit was in progress yet.

ok thanks for trying this. So I did some more testing ;).

It seems it does occur when the repo directory is a symlink (which
happens to be my setup at hand); i.e., you should be able to reproduce
doing something like this:

---
#!/bin/bash -e
mkdir git-repo
cd git-repo/
git init .
touch file
git add file
cd ..
ln -s git-repo git-repo-link
cd git-repo-link
emacs --execute="(magit-status)"
---

This also happens with 2.2 btw, I was mislead in thinking this was due to 2.3.

Not sure really what's going on here though; strace indicates some file
access being endlessly retried...

Hope this helps at all,

S

**Comment by tarsius** [comment]
That doesn't make a difference for me.

**Comment by kovrik** [comment]
Hmm, sometimes I'm getting weird errors in Magit that crash Emacs (actually, not crash, but make it unusable).
I think that's the same issue.

This happens not very often, will try to provide more info when it happens again.

**Comment by absurd34** [comment]
Hi Jonas,

On Mi, 2015-11-04 at 05:26 -0800, Jonas Bernoulli wrote:
> That doesn't make a difference for me.

hmm, utterly odd indeed ;).

I certainly can reproduce this *always* the way described, on many
different setups (which, for example, includes virgin Debian sid via
virtualbox).

Fwiw, when this happens, I see the hanging emacs process getting
SIGCHILD endlessly:


--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=21239, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
wait4(1596, 0x7ffd91c67844, WNOHANG|WSTOPPED|WCONTINUED, NULL) = 0
rt_sigreturn({mask=[]})                 = 21239
close(18)                               = 0
mmap(NULL, 69632, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff30e870000
munmap(0x7ff30e870000, 69632)           = 0
faccessat(AT_FDCWD, "/home/absurd/git-repo/.git/gitdir", F_OK) = -1 ENOENT (No such file or directory)
mmap(NULL, 69632, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff30e870000
munmap(0x7ff30e870000, 69632)           = 0
faccessat(AT_FDCWD, "/home/absurd/git-repo/.git/.", F_OK) = 0
open("/dev/null", O_RDONLY|O_CLOEXEC)   = 17
mmap(NULL, 69632, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff30e870000
munmap(0x7ff30e870000, 69632)           = 0
faccessat(AT_FDCWD, "/home/absurd/git-repo/.git/.", F_OK) = 0
mmap(NULL, 69632, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff30e870000
munmap(0x7ff30e870000, 69632)           = 0
faccessat(AT_FDCWD, "/usr/local/bin/git", X_OK) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/usr/bin/git", X_OK) = 0
stat("/usr/bin/git", {st_mode=S_IFREG|0755, st_size=1846000, ...}) = 0
pipe2([18, 19], O_CLOEXEC)              = 0
open("/dev/null", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 20
rt_sigprocmask(SIG_BLOCK, [CHLD], NULL, 8) = 0
vfork()                                 = 21240
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
close(19)                               = 0
close(20)                               = 0
close(17)                               = 0
read(18, "", 16384)                     = 0
wait4(21240, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 21240
---

Hope this is helpful -- and hopefully I will find time to pin this down
further, as no one else seems to experience this ;).

Thx!

S

**Comment by npostavs** [comment]
> I certainly can reproduce this *always* the way described,

You didn't exactly describe what you did, only that you ended up in a loop and you pressed "C" somewhere along the way..

**Comment by absurd34** [comment]
Hi Noam,

On Fr, 2015-11-06 at 07:34 -0800, Noam Postavsky wrote:
> > I certainly can reproduce this *always* the way described,
> 
> You didn't exactly describe what you did, only that you ended up in a loop and you pressed "C" somewhere along the way..

hmm, I did provide a little script in my 1st comment that should make it
pretty clear how I produce this:

https://github.com/magit/magit/issues/2378#issuecomment-154374235

I have also updated the issue title now.

Hth!

Stephan

**Comment by npostavs** [comment]
> hmm, I did provide a little script in my 1st comment that should make it pretty clear how I produce this: #2378 (comment)

Oh, sorry, I see it now. In the web view that part was folded as if it was a quote, so I overlooked it before. Github, tends to screw up formatting in email replies.  :(

**Comment by npostavs** [comment]
I see the same problem here. I think 4f5309fe271edcde185d8606f889149053fd2857 should fix it, but we need to check that "git uses the truename of COMMIT_EDITMSG" is the case for all git versions we support, otherwise this would probably cause the same bug in the opposite direction.

**Comment by npostavs** [comment]
> we need to check that "git uses the truename of COMMIT_EDITMSG" is the case for all git versions we support, otherwise this would probably cause the same bug in the opposite direction.

Um, this is wrong: if git doesn't use the truename it just means we waste a little extra time chasing symlinks, but that's fairly harmless.

**Comment by absurd34** [comment]
Hi Noam,

On Di, 2015-11-10 at 19:28 -0800, Noam Postavsky wrote:
> Closed #2378 via 5e2a53a99c8135e9f9c6b0d7deaa5f2e4df5e154.

fwiw, I have just verified that this actually solves my issue.

So -- great, thanks! As to anyone else maintaining magit, it's really
an excellent tool ;).

MfG,

S
