### ISSUE TITLE
after "git worktree"

### ISSUE THREAD

**Issue by andreineculau** [magit/magit#2380]
I'm running

* GNU Emacs 24.5.1 (x86_64-apple-darwin15.0.0) of 2015-09-13 on elcapitanvm.local
* magit 20151028.1649
* git 2.6.2

but I'm having similar issues to #2364, `magit-blame` for instance errors in `user-error: Buffer isn't visiting a tracked file`.

This only happens in checkouts (work dirs) made by `git worktree` e.g. `git worktree add -b dev ../dev origin/dev`.

Can I provide you with some more (debug) info?
Thank you,
Andrei

PS: As a side-note, for anyone searching the issue, similarly `vc-annotate` fails with `... is not under version control`but AFAICS `vc-git.el` is not handling `.git`as a file altogether...

**Comment by tarsius** [comment]
I cannot reproduce this.

> Can I provide you with some more (debug) info?

Please provide steps to reproduce the issue, and list all the things that don't work.

**Comment by andreineculau** [comment]
Sure thing.

```
pwd # /Users/andrei/tmp/magit
git clone git@github.com:magit/magit.git
cd magit
git worktree add -b jb/unmerged-changes ../unmerged-changes
origin/jb/unmerged-changes
cd ../unmerged-changes
cat .git # gitdir:
/Users/andrei/tmp/magit/magit/.git/worktrees/unmerged-changes
emacs Makefile # magit-blame gives "Buffer isn't visiting a tracked file"
```


On Wed, Nov 4, 2015 at 2:32 PM, Jonas Bernoulli <notifications@github.com>
wrote:

> I cannot reproduce this.
>
> Can I provide you with some more (debug) info?
>
> Please provide steps to reproduce the issue, and list all the things that
> don't work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magit/magit/issues/2380#issuecomment-153719857>.
>



-- 
andreineculau.com <http://www.andreineculau.com>

**Comment by npostavs** [comment]
I saw [a similar case][1] of git-worktree stuff failing on OSX, it turned out that there was an older git installed which magit was using.

[1]: https://gitter.im/magit/magit?at=5630081690cea42a0583a7b7

**Comment by andreineculau** [comment]
hmm, I think we have bingo :) Thanks, Noam!
I tested this quickly with M-x magit-git-command RET version RET -> git
version 2.4.9 (Apple Git-60)

also M-x describe-variable RET exec-path RET show indeed that /usr/bin gets
put before /usr/local/bin (homebrew's git)

I guess I can set exec-path manually in my init.el (or I'm now going to
test https://github.com/purcell/exec-path-from-shell ), but is there smth
better?
In any case, maybe a FAQ entry is good once there's a recommendation.


On Wed, Nov 4, 2015 at 3:07 PM, Noam Postavsky <notifications@github.com>
wrote:

> I saw a similar case
> <https://gitter.im/magit/magit?at=5630081690cea42a0583a7b7> of
> git-worktree stuff failing on OSX, it turned out that there was an older
> git installed which magit was using.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magit/magit/issues/2380#issuecomment-153729661>.
>



-- 
andreineculau.com <http://www.andreineculau.com>

**Comment by npostavs** [comment]
> I guess I can set exec-path manually in my init.el (or I'm now going to test https://github.com/purcell/exec-path-from-shell ), but is there smth better?

Not sure if it's better, but you can set `magit-git-executable`.

**Comment by andreineculau** [comment]
true, I went (and I can now confirm it works) with
https://github.com/purcell/exec-path-from-shell just because it fixes
"everything", rather than just magit

On Wed, Nov 4, 2015 at 3:59 PM, Noam Postavsky <notifications@github.com>
wrote:

> I guess I can set exec-path manually in my init.el (or I'm now going to
> test https://github.com/purcell/exec-path-from-shell ), but is there smth
> better?
>
> Not sure if it's better, but you can set magit-git-executable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magit/magit/issues/2380#issuecomment-153753863>.
>



-- 
andreineculau.com <http://www.andreineculau.com>
