### ISSUE TITLE
make clean; make lisp 

### ISSUE THREAD

**Issue by villem** [magit/magit#2382]
I'm trying to compile HEAD from 02de262982c81dc63d8f978bbdea9c10663a9d79 and compilation fails to
 make lisp
make[1]: Entering directory 'emacs/magit/lisp'
Compiling with-editor.el
Compiling git-commit.el
Compiling magit-popup.el
Compiling magit-utils.el
Compiling magit-section.el
Compiling magit-git.el
Compiling magit-mode.el
Compiling magit-process.el
Compiling magit-core.el

In toplevel form:
magit-core.el:38:1:Error: Symbol's function definition is void: --some
Makefile:38: recipe for target 'magit-core.elc' failed
make[1]: *** [magit-core.elc] Error 1

If I revert 0f30dfbb0075ac2e99b65a2c7fac360197a989c1 things start to work again.

**Comment by kyleam** [comment]
Your installed dash predates `--some`.

**Comment by villem** [comment]
Ok, I'll update dash. Would be good if there would be dependency check for correct dash version when building magit. I'll close this one. Thank you for speedy reply!
