### ISSUE TITLE
Add "magit-wip-after-stash-mode"?

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2383]
Hello,

a standard way of saving uncommitted changes in git or Magit is to use a stash.

But if you accidentally drop the stash, it is hard to find out its hash to recover its contents, because the hash is not present in any reflog (there is a reflog for the "stash" ref, but AFAIK it's used to maintain the stack of stashes, and when you drop a stash, it's gone from there).

So, would it make sense to add a "magit-wip-after-stash-mode", in analogy to the other wip modes?  Like for them, all those additional blobs would be garbage collected after some time, but one could still find the ids of recent stashes with l O refs/wip/stash/refs/heads/master even if you have created commits in the meantime.  I think that would be useful.  TIA.

**Comment by tarsius** [comment]
That seems like overkill. What about the change I just pushed, is that good enough for you?

**Comment by michael-heerdegen** [comment]
Mmh, it probably is.  Let's try with this.  If I find it's not enough, I can just reopen.  Thanks!
