### ISSUE TITLE
allow files to be marked for staging

### ISSUE THREAD

**Issue by dscherger** [magit/magit#2391]
Currently staging a file takes a few seconds and if one has many files to stage or unstage it takes quite a long time to do them individually. it would be great if one could mark a bunch of files and then stage them all.

**Comment by npostavs** [comment]
Dup of #2384?

**Comment by dscherger** [comment]
Yes, sounds like this might be a duplicate... for the record I'm on OSX and staging a single file sometimes takes a few seconds which becomes *very* tedious when there are many files to stage.

If staging/unstaging was instantaneous then I guess there would be no need to mark and then stage.

using Magit 20151023.1140, Git 2.6.1, Emacs 24.5.1

OSX 10.11.1 
MacBook Pro (Retina, 15-inch, Mid 2014)
2.8 GHz Intel Core i7
16 GB 1600 MHz DDR3

**Comment by dscherger** [comment]
For the record, cua-mode selections allow multiple files to be staged or unstaged.

**Comment by npostavs** [comment]
> For the record, cua-mode selections allow multiple files to be staged or unstaged.

Works without cua-mode too (doesn't help if you want to stage every other file though).

https://github.com/magit/magit/issues/2384#issuecomment-155054721
