### ISSUE TITLE
compilation under cygwin fails

### ISSUE THREAD

**Issue by pete-lee** [magit/magit#2392]
in default.mk:
LOAD_PATH ?= -L $(TOP)/lisp -L $(shell cygpath --mixed $(DASH_DIR))

doesn't work and generates windows sytle paths.  So compilation fails because it can't find dash.

Removing the "--mixed" option allows compilation to finish.

**Comment by tarsius** [comment]
As so often when Cygwin is involved, one user's fix is another user's regression :-(

This was added in 2ee7fdc6b45cb24bb022ed8164566e14345b0aec by @ilohmar. Maybe he can help with this.

**Comment by ilohmar** [comment]
Not directed at the OP, of course, but I need to vent it: This whole windows nonsense... so tired of it.

Unfortunately (well.. not really), I am away from my work machine running windows, so I will have poke around in the dark.  At the time, the option was necessary to run the makefile in a cygwin bash.

In which shell are you trying to compile?  Do you maybe happen to run things in cmd.exe, and have a path that includes some non-cygwin binaries (such as for make)?  Please let me know the shell, the installed unix-y environments (MinGW, cygwin etc), and which make and which cygpath your shell is trying to use.

**Comment by pete-lee** [comment]
This was compiling from cygwin bash shell.  I've avoided running anything via cmd.exe as I've found mixing the two to be problematic (particularly with path issues as you point out).

The make version is:
$ make --version
GNU Make 4.1

$ cygpath --version
cygpath (cygwin) 2.2.1

$ cygpath c:/foo
/cygdrive/c/foo

$ cygpath --mixed c:/foo
C:/foo

$ cygpath --mixed c:\\foo
C:/foo

--mixed seems to just normalize to forward slashes, but preserves "c:".

I'm not sure when I last updated cygwin... so perhaps cygpath impl has changed at some point.

Let me know if there's anything else I can help with.

**Comment by npostavs** [comment]
I think the difference might be whether you're using cygwin Emacs or not.

**Comment by pete-lee** [comment]
I am using cygwin emacs.

**Comment by ilohmar** [comment]
Oooh, that's a good point.  I am using NTEmacs when I have to work on windows.  So I guess we have to find out in the makefile which emacs it is, and only use the cygpath translation if it's for NTEmacs.  I will probably not get to that before next week myself, if anybody else could check and fix that, that would be great.

**Comment by tarsius** [comment]
> So I guess we have to find out in the makefile which emacs it is, and only use the cygpath translation if it's for NTEmacs.

Looking forward to a patch doing just that :-)

**Comment by ilohmar** [comment]
I'm afraid I spoke too soon..  I have never touched cygwin emacs and my only windows machine is a work machine --- will not do install it there.  I can write a patch "blindly" (end-of-week-ish) if that helps anybody?  It would run `emacs -Q --batch --eval '(message "%s" system-type)'` and compare w/ `"windows-nt"`, in which case to add the "--mixed" option...  Cannot do it on the fly as my makefile syntax knowledge is close to nil.

**Comment by johnmastro** [comment]
My `make`-foo is very weak, but based on ilohmar's description I think this might work.

The duplicated definition of `LOAD_PATH` without `--mixed` is pretty ugly but I don't know how to `and` the two tests.

Anyway, I was only able to give this a few minutes for now but will come back to it this evening. If anyone sees me doing anything terribly wrong, please let me know.

```
diff --git a/default.mk b/default.mk
index 32dfdcf..0bbd238 100644
--- a/default.mk
+++ b/default.mk
@@ -72,9 +72,14 @@ ifeq "$(DASH_DIR)" ""
 endif
 
 CYGPATH := $(shell cygpath --version 2>/dev/null)
+SYSTYPE := $(shell $(EMACSBIN) -Q --batch --eval "(princ system-type)")
 
 ifdef CYGPATH
-  LOAD_PATH ?= -L $(TOP)/lisp -L $(shell cygpath --mixed $(DASH_DIR))
+  ifeq "$(SYSTYPE)" "cygwin"
+    LOAD_PATH ?= -L $(TOP)/lisp -L $(shell cygpath --mixed $(DASH_DIR))
+  else
+    LOAD_PATH ?= -L $(TOP)/lisp -L $(DASH_DIR)
+  endif
 else
   LOAD_PATH ?= -L $(TOP)/lisp -L $(DASH_DIR)
 endif
```

**Comment by johnmastro** [comment]
Hm, I see now I didn't do the right thing. But as I said, I'll pick it back up this evening.

**Comment by johnmastro** [comment]
I updated the patch above again. It works for me with Cygwin `make` and both Cygwin `emacs` and NT `emacs`, though I'm not sure if it's the cleanest way to do it. Review/feedback appreciated.

**Comment by npostavs** [comment]
My reading of [Conditional-Syntax][1] tells me that you could write it like this:

```
ifndef CYGPATH
  LOAD_PATH ?= -L $(TOP)/lisp -L $(DASH_DIR)
else ifeq "$(SYSTYPE)" "cygwin"
  LOAD_PATH ?= -L $(TOP)/lisp -L $(shell cygpath $(DASH_DIR))
else
  LOAD_PATH ?= -L $(TOP)/lisp -L $(shell cygpath --mixed $(DASH_DIR))
endif
```

[1]: http://www.gnu.org/software/make/manual/html_node/Conditional-Syntax.html

**Comment by johnmastro** [comment]
Thanks @npostavs, I missed that.

I pushed it to my fork as johnmastro@320ff7d and opened pull request #2398.

**Comment by npostavs** [comment]
Although, I wonder, is `$(shell cygpath $(DASH_DIR))` actually needed with a Cygwin Emacs?

**Comment by johnmastro** [comment]
> Although, I wonder, is $(shell cygpath $(DASH_DIR)) actually needed with a Cygwin Emacs?

I wondered that too, and that's actually what I did the first time, but I chickened out and just removed "--mixed" (which is also what @ilohmar described).

It works for me without the call to `cygpath`, including when invoked like...

```sh
make lisp DASH_DIR=c:\\home\\jbm\\.emacs.d\\elpa\\dash-20151021.113
```

... which is when I would have thought it might be necessary.

So I suspect it is not necessary. I'll wait a bit before updating the PR in case there are further comments or I can come up with a way to prove it one way or the other.

**Comment by PierreTechoueyres** [comment]
@johnmastro This works here too with an Cygwin's emacs and without the call to `cygpath`. I also checked with msys2 with and without the built-in emacs.

```
LOAD_PATH ?= -L $(TOP)/lisp -L $(DASH_DIR)
ifdef CYGPATH
  ifneq "$(SYSTYPE)" "cygwin"
    LOAD_PATH ?= -L $(TOP)/lisp -L $(shell cygpath --mixed $(DASH_DIR))
  endif
endif
```

**Comment by johnmastro** [comment]
@PierreTechoueyres, thanks for testing it. I haven't found a case where `cygpath` is necessary with Cygwin Emacs either.

If I understand correctly, the second assignment to `LOAD_PATH` in the code you posted wouldn't be effective, because `?=` only makes the assignment if the variable is not yet defined. And we can't just change it to to `:=` or `=` because that would override a `LOAD_PATH` specified by the user. However, it sounds like it did work for you, so I may have that wrong (or maybe something about your configuration makes it unnecessary to call `cygpath`).

I'm starting to wonder if something like the below would be best - shell out to get `&&`, which really strikes me as a strange omission from `make`.

```
SYSTYPE := $(shell $(EMACSBIN) -Q --batch --eval "(princ system-type)")

CYGWIN_MIXED := $(shell \
  command -v cygpath >/dev/null 2>&1\
  && [ "$(SYSTYPE)" = "windows-nt" ]\
  && echo "true")

ifeq "$(CYGWIN_MIXED)" "true"
  LOAD_PATH ?= -L $(TOP)/lisp -L $(shell cygpath --mixed $(DASH_DIR))
else
  LOAD_PATH ?= -L $(TOP)/lisp -L $(DASH_DIR)
endif
```

It works for me with both Cygwin Emacs and NT Emacs. @npostavs, what do you think, is this reasonable?

**Comment by npostavs** [comment]
> However, it sounds like it did work for you, so I may have that wrong (or maybe something about your configuration makes it unnecessary to call cygpath).

Msys automagically converts paths into native when calling a non-msys program (which can cause problems if you actually want to pass an argument starting in `/` that's not a path) so cygpath is generally not needed.

> shell out to get &&, which really strikes me as a strange omission from make.

I agree lacking `&&` is odd, but in this case I don't think shelling out buys you much; how about

```
SYSTYPE := $(shell $(EMACSBIN) -Q --batch --eval "(princ system-type)")
ifeq ($(SYSTYPE), windows-nt)
  CYGPATH := $(shell cygpath --version 2>/dev/null)
endif

ifdef CYGPATH
  LOAD_PATH ?= -L $(TOP)/lisp -L $(shell cygpath --mixed $(DASH_DIR))
else
  LOAD_PATH ?= -L $(TOP)/lisp -L $(DASH_DIR)
endif
```

**Comment by johnmastro** [comment]
Works for me - thanks for the review. I force-pushed to my fork and updated the pull request.

**Comment by tarsius** [comment]
Thanks everyone.
