### ISSUE TITLE
`magit-status` under git 2.6.2 causes (wrong-type-argument char-or-string-p nil) (backtrace in description)

### ISSUE THREAD

**Issue by zackp30** [magit/magit#2393]
```
Debugger entered--Lisp error: (wrong-type-argument char-or-string-p nil)
  magit-insert-pull-branch-header()
  funcall(magit-insert-pull-branch-header)
  mapc(funcall (magit-insert-pull-branch-header magit-insert-push-branch-header magit-insert-tags-header))
  magit-insert-remaining-headers()
  run-hooks(magit-insert-section-hook)
  magit-insert-head-branch-header()
  magit-insert-headers((magit-insert-diff-filter-header magit-insert-head-branch-header magit-insert-pull-branch-header magit-insert-push-branch-header magit-insert-tags-header))
  magit-insert-status-headers()
  run-hooks(magit-status-sections-hook)
  magit-status-refresh-buffer()
  apply(magit-status-refresh-buffer nil)
  magit-refresh-buffer()
  magit-mode-setup(magit-status-mode)
  magit-status-internal("~/documents/")
  magit-status(nil)
  funcall-interactively(magit-status nil)
  call-interactively(magit-status record nil)
  command-execute(magit-status record)
  helm-M-x(nil "magit-status")
  funcall-interactively(helm-M-x nil "magit-status")
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```

Thanks!

**Comment by zackp30** [comment]
Same issue under 2.6.3.

**Comment by kyleam** [comment]
Hmm, I not able to trigger this.  It looks like
magit-insert-pull-branch-header handles nil values properly (which
happen when using a detached head or the current branch isn't tracking
another).  Can you debug magit-insert-pull-branch-header (e.g., C-u
C-M-x) and see what nil value is causing the issue when you call
magit-status?

**Comment by zackp30** [comment]
Sorry for the inconvenience, I use a VNC session for Emacs and the keys aren't being sent, is there another way to debug this? Thanks!

**Comment by npostavs** [comment]
Evaluating
```elisp
(require 'magit)
(require 'edebug)
(edebug-instrument-function 'magit-insert-pull-branch-header)
```
should be equivalent.

---

Also, the output of `M-x magit-version` may be useful to have.

**Comment by zackp30** [comment]
```emacs
(cl-defun magit-insert-pull-branch-header                                                
=>  (&optional (branch (magit-get-current-branch))                                       
              (pull   (magit-get-tracked-branch branch))                                
              keyword)                                
```emacs

Magit version:

```
Magit 20151111.1855, Git 2.6.3, Emacs 25.0.50.37                                        

```

**Comment by npostavs** [comment]
> `=> (&optional (branch (magit-get-current-branch))`

Can you elaborate?

**Comment by zackp30** [comment]
The arrow is what Edebug is I believe.

**Comment by zackp30** [comment]
So I guess `branch` is nil? or more specifically the return result of `magit-get-current-branch` is returning nil, however it returns "master" when in a repo...

**Comment by npostavs** [comment]
> The arrow is what Edebug is I believe.

Okay, so if you hit `SPC` a few times to step forward where does the error get thrown from exactly?

**Comment by zackp30** [comment]
```
      (if (magit-rev-verify pull)                                                        
=>    │   (insert (magit-rev-format "%s" pull)) 
```

**Comment by kyleam** [comment]
Does of the tracked branch have an empty commit message?

**Comment by npostavs** [comment]
> ```
>       (if (magit-rev-verify pull)                                                        
> =>    │   (insert (magit-rev-format "%s" pull)) 
> ```

I don't understand, where was the cursor exactly when the error was thrown? The place where you put `|` doesn't make sense because it's not after a close paren, so it can't be the result of an edebug step.

**Comment by zackp30** [comment]
@kyleam Yes, many of them, bad habit of mine. :smile:

**Comment by zackp30** [comment]
@npostavs That was my indent guide, sorry!

**Comment by zackp30** [comment]
@kyleam Your patch works! Thanks! (I guess this should be merged now)

**Comment by kyleam** [comment]
Applied.

**Comment by mgsloan** [comment]
Note for fellow searchers of the web:  This can happen when your git repo is corrupted.
