### ISSUE TITLE
magit-add-remote - adding a relative path as local remote

### ISSUE THREAD

**Issue by drorbemet** [magit/magit#2394]
Should magit-add-remote mirror the behaviour of git?

- git expands relative local paths, 
```git remote add someremote ~/local-git-repo.git``` results in:
./.git./config:
[remote "someremote"]
	url = /home/username/local-git-repo.git

- magit exposes a different behaviour than git at this point, 
```magit-add-remote someremote ~/local-git-repo.git``` results in:
./.git./config:
[remote "someremote"]
	url = ~/local-git-repo.git

- Having relative paths in a config file of a git working copy can result in the DELETION of all files in the current linux user's home directory. I experienced this two times before figuring that out. I don't know the exact git command that caused the deletion though.

- also path completion for local directories with magit-add-remote would be nice to have, but that is not relevant at this point

**Comment by npostavs** [comment]
> git expands relative local paths,

I think that's your shell doing that, but probably magit should too. Does this work for you? https://github.com/magit/magit/compare/np/set-url

**Comment by drorbemet** [comment]
With these changes loaded https://github.com/magit/magit/compare/np/set-url
and after entering a local path and hitting enter.
This error message is printed to minibuffer ``Wrong number of arguments: (2 . 3), 1``.

**Comment by npostavs** [comment]
Uh, right made a stupid mistake. I added a commit to fix it.

**Comment by npostavs** [comment]
Actually I think maybe we should use `substitute-in-file-name` instead of `expand-file-name`, since that is close to what the shell does. That is, if you use an actually relative path, it's *not* expanded: `git remote add someremote ../local-git-repo.git` gives
```
[remote "someremote"]
	url = ../local-git-repo.git
	fetch = +refs/heads/*:refs/remotes/someremote/*
```

**Comment by drorbemet** [comment]
Yes, preventing "~/" to endanger the content of the user home directory is the main motive I think.

**Comment by npostavs** [comment]
> Actually I think maybe we should use substitute-in-file-name instead of expand-file-name

Except that `substitute-in-file-name` doesn't substitute `~`, only variables like `$FOO`. I'm not sure how I decided otherwise.

**Comment by drorbemet** [comment]
Yea, just figured that out too. So if it does not violate some convention in magit, I would suggest to accept anything resembling a local file system path expand it to a full path and optionally creating a bare repo if it does not exist.

**Comment by npostavs** [comment]
> So if it does not violate some convention in magit, I would suggest to accept anything resembling a local file system path and expand it to a full path.

I think it might be better not to disallow relative paths, so my current idea is to `expand-file-name` if the url starts with `~`: b8ad8a2d8bbf75c4c8ec0f749f99e8e018e64510

**Comment by drorbemet** [comment]
Yes that would narrow it down to this exceptional case.
