### ISSUE TITLE
error: Required feature `magit-autoloads' was not provided

### ISSUE THREAD

**Issue by targzeta** [magit/magit#2396]
Hi, 
I use to load magit with these code lines:
```lisp
(require 'magit-version)
(require 'magit-autoloads)
```
now I receive the error on subject. I guess that *magit-autoloads.el* leaks to **provide** magit-autoloads :)

Emanuele

**Comment by npostavs** [comment]
`magit-version` is autoloaded now, so you don't need to `(require 'magit-version)`.

**Comment by targzeta** [comment]
Oh, thank you npostavs (I have removed the line)! Anyway, the problem is another ;)

Thank you again,
Emanuele

**Comment by npostavs** [comment]
Can you explain exactly how you are installing magit? Which of the methods described here: http://magit.vc/manual/magit/Installation.html

**Comment by npostavs** [comment]
> Can you explain exactly how you are installing magit?

Uh, never mind. Looking at it now, I see `lisp/Makefile` indeed does not put a `(provide 'magit-autoloads)` in magit-autoloads.el, so I guess you could use `(load "magit-autoloads")` instead.

**Comment by tarsius** [comment]
... and I think that's the correct behavior. `package.el` (or as far as I know anything else in Emacs) also does not insert a `provide` form into `*-autoload.el` files. And since these files don't provide any functionality, that makes sense.
