### ISSUE TITLE
Staging hunk leaves an unstaged "no change" change

### ISSUE THREAD

**Issue by TomAndrews** [magit/magit#2401]
I have an intermittent problem with magit on Windows whereby I stage a hunk it leaves an unstaged "change" with no differences.  For example staging the first hunk in the file below:

![before](https://cloud.githubusercontent.com/assets/13886890/11277165/39b9ed08-8edd-11e5-97d6-ccf98626c148.png)

Gives this as a result:
![after](https://cloud.githubusercontent.com/assets/13886890/11277226/7eac1a58-8edd-11e5-92fe-a954543e9974.png)

Note that the hunk has staged (see the bottom of the picture) but the 'Unstaged changes' section is showing a diff but with no change.

If I unstage the staged hunk, it goes back to the state in the first picture (as you'd expect).  If I then try staging the hunk using `git add -i` from the command line and refresh the magit status buffer then everything seems to have worked as expected.

I'm afraid I haven't worked out how to reproduce this problem.  It only seems to happen on windows (I also use magit on linux but have never seen the problem there).  If I restart emacs then the problem goes away for a while.  I am using the latest master from github, compiled using `C-u 0 M-x byte-recompile-directory`.  I am using emacs 0.25.0.50.1 from http://sourceforge.net/projects/emacsbinw64/

I realise you don't really stand a chance of helping me fix this when I can't reliably reproduce the problem.  If you could let me know of anything I can try when the problem does occur to try and narrow down the problem I'm keen to try!

Thanks very much for your help (and for writing such a great piece of software!).

**Comment by johnmastro** [comment]
@TomAndrews, is it possible you have any raw bytes in your file? Something like this happened to me once and it turned out to be because I'd ended up with a null byte in the file, causing `git` to detect it as a binary file. I deleted the null byte and things went back to normal - I didn't pursue it further than that.

Hm, however, I just tried to recreate the issue, unsuccessfully.

**Comment by npostavs** [comment]
> Note that the hunk has staged (see the bottom of the picture) but the 'Unstaged changes' section is showing a diff but with no change.

Is the change gone or just collapsed? i.e. Does doing `M-4` restore it?

**Comment by TomAndrews** [comment]
@johnmastro Thanks for the suggestion.  I tried this: http://www.emacswiki.org/emacs/FindingNonAsciiCharacters
but it didn't find any non-ascii characters in my file

**Comment by TomAndrews** [comment]
@npostavs Sorry, I don't understand.  I'm trying to stage the first hunk in the first picture, beginning

```
outdir <- ...
outname <- ...
```

Once I press `s` (and collapse the other unstaged hunks so that you can see the `Staged changes` section), I see the second picture.

The hunk I tried to stage is now showing in **both** the `Unstaged changes` **and** `Staged changes` sections.  In the `Unstaged` section, it's showing the new lines being added and removed.  This shouldn't be there.

In the `Staged` section it has what you'd expect - the old lines being removed and the new ones added.

**Comment by johnmastro** [comment]
@TomAndrews, it probably is something else but, just to be sure, try `git diff HEAD your-file` on the command line. If `git` is detecting the file as binary it will show something like this:

```
diff --git a/init.el b/init.el
index ef7fbf2..b7277aa 100644
Binary files a/init.el and b/init.el differ
```

The reason I suggest this is that e.g. `[[:nonascii:]]` doesn't match null bytes but they still cause `git` to detect the file as binary.

**Comment by TomAndrews** [comment]
@johnmastro Thanks.  Putting in a small change and running `git diff HEAD my-file` gives this output:

```
$ git diff HEAD ValueFXSystem.r
diff --git a/code/latest/valuefx/sys/ValueFXSystem.r b/code/latest/valuefx/sys/ValueFXSystem.r
index 78268b0..701bc20 100644
--- a/code/latest/valuefx/sys/ValueFXSystem.r
+++ b/code/latest/valuefx/sys/ValueFXSystem.r
@@ -8,6 +8,7 @@ dal.clear.cache()
 if (interactive()) options(error = quote(recover()))

 ## config
+
 cpus <- 6
 outdir <- "Test_ConsForc2_Oct15"
 outname <- "Signals_TopN_window"
```

So I think git is correctly treating it as a text file.

**Comment by npostavs** [comment]
> The hunk I tried to stage is now showing in both the Unstaged changes and Staged changes sections.

Oh, right, I missed that before, sorry.

> If I restart emacs then the problem goes away for a while.

I think this means it's probably not a problem with the file contents.

**Comment by johnmastro** [comment]
>> If I restart emacs then the problem goes away for a while.

> I think this means it's probably not a problem with the file contents.

Indeed, ignore me :)

**Comment by npostavs** [comment]
> I am using the latest master from github, compiled using C-u 0 M-x byte-recompile-directory. I am using emacs 0.25.0.50.1 from http://sourceforge.net/projects/emacsbinw64/

Can you also list git version please? (It's probably not relevant, but just in case)

**Comment by npostavs** [comment]
> If you could let me know of anything I can try when the problem does occur to try and narrow down the problem I'm keen to try!

If you just refresh the magit status buffer without doing any further (un)staging, does it stay broken? What if you close the status buffer and reopen it?

Compare the output of `git diff` from the command line, and `: diff` (or `M-x magit-git-command RET diff RET`) from magit.

Try stepping into `magit-diff-wash-diff` and see what's going on.

**Comment by TomAndrews** [comment]
> Can you also list git version please? (It's probably not relevant, but just in case)

I am currently using Git for Windows 2.6.3 but I'm pretty sure I've seen this issue with every version of git from the old 1.9.5 preview onwards.

**Comment by TomAndrews** [comment]
> If you just refresh the magit status buffer without doing any further (un)staging, does it stay broken? What if you close the status buffer and reopen it?

Refreshing or closing or opening the buffer doesn't fix the problem

> Compare the output of git diff from the command line

Staging the hunk containing the `outdir` and `outname` section gave me this:

```
$ git diff
diff --git a/code/latest/valuefx/sys/ValueFXSystem.r b/code/latest/valuefx/sys/ValueFXSystem.r
index 97f7368..78268b0 100644
--- a/code/latest/valuefx/sys/ValueFXSystem.r
+++ b/code/latest/valuefx/sys/ValueFXSystem.r
@@ -9,8 +9,8 @@ if (interactive()) options(error = quote(recover()))

 ## config
 cpus <- 6
-outdir <- "Test_ConsForc2_Oct15"
-outname <- "Signals_TopN_window"
+outdir <- "Test_ConsForc2_Oct15"
+outname <- "Signals_TopN_window"
 progpath = "latest/valuefx/sys/"

 systems <- c("Fx")
@@ -24,7 +24,7 @@ startout = "1-Jan-1970"
 finish = date

 ## setup
-outmain <- paste(outDir(), "latest/ValueFX/", outdir, "/", outname, "_to_", date, "/", sep="")
+outmain <- paste(outDir(), "test/ValueFX/", outdir, "/", outname, "_to_", date, "/", sep="")
 dir.create(outmain, recursive=TRUE, showWarnings = FALSE)

 ## start snowfall cluster
```

So `git` is also showing the strange unstaged hunk.  The output of `: diff` matches the above.

Once the problem has happened once, staging **any** hunk from magit results in the same problem.

However, I **can** stage the hunk using `git add -i`.  Once I do this, and refresh the status buffer, everything shows as expected.  No bogus "unstaged" hunk, and the hunk shows up as "staged" as you would expect.

**Comment by TomAndrews** [comment]
> Try stepping into magit-diff-wash-diff and see what's going on.

I've never done this before, so please let me know if I'm not doing the right thing.

Starting with nothing staged, I ran `(debug-on-entry 'magit-diff-wash-diff)` in the `*scratch*` buffer.  I then tried to stage a hunk.

The debugger opens, another window pops up with what seems to be the output from `git diff` for changed file.

```
diff --git code/latest/valuefx/sys/ValueFXSystem.r code/latest/valuefx/sys/ValueFXSystem.r
index 97f7368..78268b0 100644
--- code/latest/valuefx/sys/ValueFXSystem.r
+++ code/latest/valuefx/sys/ValueFXSystem.r
@@ -9,8 +9,8 @@ if (interactive()) options(error = quote(recover()))
 
 ## config
 cpus <- 6
-outdir <- "Test_ConsForc2_Oct15"
-outname <- "Signals_TopN_window"
+outdir <- "Test_ConsForc2_Oct15"
+outname <- "Signals_TopN_window"
 progpath = "latest/valuefx/sys/"
 
 systems <- c("Fx")
@@ -24,7 +24,7 @@ startout = "1-Jan-1970"
 finish = date
 
 ## setup
-outmain <- paste(outDir(), "latest/ValueFX/", outdir, "/", outname, "_to_", date, "/", sep="")
+outmain <- paste(outDir(), "test/ValueFX/", outdir, "/", outname, "_to_", date, "/", sep="")
 dir.create(outmain, recursive=TRUE, showWarnings = FALSE)
 
 ## start snowfall cluster
```

This has the bogus "unstaged" hunk in it.

My (very uneducated) guess is that when staging the hunk `magit` is passing something slightly malformed to `git`, which is then getting confused.  `git` then starts producing strange diffs, though `magit` is parsing them correctly.

I'll see if I can find out what `magit` is sending to `git` to stage.

**Comment by TomAndrews** [comment]
Something else thing that may or may not be relevant: I can actually commit the "no-change" change that I'm left with after staging a hunk.

   * Start with nothing staged
   * Stage the first hunk.
      * This gives the correct staged hunk and the unstaged bogus hunk
   * Commit the staged hunk (commit 1)
   * Stage the whole file, including the unstaged bogus hunk.  This always works correctly.
   * Commit again (commit 2)

The log of commit 2 shows the "no change" change as if it were a real one.

**Comment by TomAndrews** [comment]
Sorry for bombarding you with comments...  I've done a bit more digging.

> I'll see if I can find out what magit is sending to git to stage.

I put a breakpoint in `magit-run-git-with-input` and tried staging a hunk.  When the debugger opened, I executed `(save-buffer)`.  As I understand it, this is the patch that `magit` will give to `git` to apply.  I've attached the file.
[patch.txt](https://github.com/magit/magit/files/39963/patch.txt)

The top line of my `*Backtrace*` window looked like this:
```
* magit-run-git-with-input(nil "apply" ("--cached") "-p0" nil "--ignore-space-change" "-")
```

so I ran

```
git apply --cached -p0 --ignore-space-change - < patch.txt
git diff
```

Which gave me
```
$ git diff
diff --git a/code/latest/valuefx/sys/ValueFXSystem.r b/code/latest/valuefx/sys/ValueFXSystem.r
index 97f7368..78268b0 100644
--- a/code/latest/valuefx/sys/ValueFXSystem.r
+++ b/code/latest/valuefx/sys/ValueFXSystem.r
@@ -9,8 +9,8 @@ if (interactive()) options(error = quote(recover()))

 ## config
 cpus <- 6
-outdir <- "Test_ConsForc2_Oct15"
-outname <- "Signals_TopN_window"
+outdir <- "Test_ConsForc2_Oct15"
+outname <- "Signals_TopN_window"
 progpath = "latest/valuefx/sys/"

 systems <- c("Fx")
@@ -24,7 +24,7 @@ startout = "1-Jan-1970"
 finish = date

 ## setup
-outmain <- paste(outDir(), "latest/ValueFX/", outdir, "/", outname, "_to_", date, "/", sep="")
+outmain <- paste(outDir(), "test/ValueFX/", outdir, "/", outname, "_to_", date, "/", sep="")
 dir.create(outmain, recursive=TRUE, showWarnings = FALSE)

 ## start snowfall cluster
```

So I think there is something wrong with [patch.txt](https://github.com/magit/magit/files/39963/patch.txt)

**Comment by TomAndrews** [comment]
I tried to recreate what `magit` is doing manually.  I ran

```
git diff > patch3.txt
```

I deleted the second hunk from the file and removed the `a/` and `b/` from the  filenames, so that the `-p0` option works.  I then ran:

```
git apply --cached -p0 --ignore-space-change - < patch3.txt
```

And everything worked as expected.  There was no "unstaged" hunk.
[patch3.txt](https://github.com/magit/magit/files/40007/patch3.txt)

The only difference between `patch.txt` and `patch3.txt` is the line endings - `patch.txt` has `CRLF` and `patch3.txt` has `LF`.

**Comment by TomAndrews** [comment]
I just tried opening up a new instance of `emacs` and staging a hunk.  It worked as expected (since it's a new instance).  I tried saving the patch buffer again and it also contained `CRLF` line endings.
[patch_good.txt](https://github.com/magit/magit/files/40010/patch_good.txt)

However, if I run
```
git apply --cached -p0 --ignore-space-change - < patch_good.txt
```

Then it leaves behind the 'no-change' change.

It it possible that `magit` is somehow losing an option that tells `git` to play nicely with `CRLF` line endings?

My repository is set up to check in `LF` and check out `CRLF` on windows.  My `.gitattributes` looks like this:
```
# Following http://stackoverflow.com/questions/170961/whats-the-best-crlf-carriage-return-line-feed-handling-strategy-with-git

# Set the default behavior, in case people don't have core.autocrlf set.
* text=auto

# Explicitly declare text files you want to always be normalized and converted
# to native line endings on checkout.
*.q text
*.r text
*.csv text
*.c text
*.cpp text
*.f text
*.txt text
*.site text

# Explicitly set bash/perl scripts to have unix endings
*.sh text eol=lf
*.pl text eol=lf

# Explicitly set windows scripts to have windows endings
*.cmd text eol=crlf

# Denote all files that are truly binary and should not be modified.
*.RData binary
*.xls binary
*.xlsx binary
*.dll binary
*.so binary
*.o binary
*.pdf binary
```

**Comment by npostavs** [comment]
> I've never done this before, so please let me know if I'm not doing the right thing.

Looks like you figured out the right thing, even though I directed you to the wrong function :) 
(I mistakenly thought it was a display problem which is why I suggested `magit-diff-wash-diff`)

> The only difference between patch.txt and patch3.txt is the line endings - patch.txt has CRLF and patch3.txt has LF.

Aha, line endings, of course.

> It it possible that magit is somehow losing an option that tells git to play nicely with CRLF line endings?

I think it's more likely the line endings go wrong either in `magit-apply-hunk` where `(buffer-substring (magit-section-start section) (magit-section-end section))` computes the patch, or in `magit-apply-patch` where it calls `(insert patch)` in a temp buffer, perhaps that buffer's `buffer-file-coding-system` or `coding-system-for-write` is set to a unix one.

> Then it leaves behind the 'no-change' change.

By the way, activatating whitespace-mode may show the change better (this might also destroy magit's highlighting such that you'll have to kill and reopen the buffer to restore it).

**Comment by TomAndrews** [comment]
Heh, thanks for reading that massive wall of posts!

The thing I found surprising was that even when magit is working correctly it's using `CRLF` line endings in that patch buffer.  I don't really understand how that then is applied correctly in one case and not in the other.  I tried looking at `process-connection-type` (thinking it was related to #20) but didn't get anywhere...

**Comment by tarsius** [comment]
> My repository is set up to check in `LF` and check out `CRLF` on windows.

Would it be to much hassle to checkout with `LF` too? Git allows configuring line-endings per file, but Magit buffers may contain parts of files which are configured to use different line-endings, and since an Emacs buffers uses the same line-ending for the complete content, that obviously is problematic. So Magit just assumes `LF`.

**Comment by TomAndrews** [comment]
> Would it be to much hassle to checkout with LF too?

Some other users prefer to code in Notepad so unfortunately I can't make a general switch to using `LF`.  It would also break various `.cmd` scripts we use.

I'll see if I can reliably reproduce the problem by generating some diffs on a mix of `CRLF` and `LF` files.  If that turns out to be the problem then I guess I'll just have to live with it but at least I'll have an idea of how to work around it.  Thanks for the suggestion.

**Comment by npostavs** [comment]
> I tried looking at process-connection-type

FYI, `process-connection-type` has no effect on Windows, because there are no ptys.

> Some other users prefer to code in Notepad

:O

**Comment by TomAndrews** [comment]
> >Some other users prefer to code in Notepad

> :O

I need to brush up on my emacs proselytizing skills...

**Comment by tarsius** [comment]
I am closing this as "Magit assumes unix line-endings, and there are no plans to change that anytime soon".
