### ISSUE TITLE
magit stash

### ISSUE THREAD

**Issue by marcelino-m** [magit/magit#2402]
Is possible stash only specific hunks in modifies files with magit?.

**Comment by kyleam** [comment]
Yes, you can stage what you want and then use `zi`
(`magit-stash-index`).

In the future, please use some other channel (like Emacs StackExchange
or the mailing list) to ask help-related questions.

**Comment by marcelino-m** [comment]
Ok. Sorry for my neglect.

**Comment by kyleam** [comment]
No worries.  Hopefully `magit-stash-index` does the trick.
