### ISSUE TITLE
magit-clone-github (new feature request)

### ISSUE THREAD

**Issue by decoursin** [magit/magit#2405]
```magit-clone``` is fine, but I should be able to say magit-clone [magit/magit](https://github.com/magit/magit) or [justbur/evil-magit](https://github.com/justbur/evil-magit). Instead of passing the entire url, an "account/repo" and you should automatically clone it from github.

**Comment by johnmastro** [comment]
How would you want it to handle the protocol?

I can't speak for whether the Magit developers will be interested in adding this as a feature, but here's a quick (and very lightly tested) implementation. The protocol defaults to `git` but, if you call it with a prefix arg (`C-u`), it prompts for it.

```emacs-lisp
(defun magit-clone-github (repository directory protocol)
  (interactive
   (let ((protocol (if current-prefix-arg
                       (magit-read-string-ns "Protocol")
                     "git"))
         (repostory (magit-read-string-ns "Clone repository")))
     (list repostory
           (read-directory-name
            "Clone to: " nil nil nil
            (and (string-match "\\([^/]+\\)\\'" repostory)
                 (match-string 1 repostory)))
           protocol)))
  (magit-clone (if (string= protocol "ssh")
                   (format "git@github.com:%s.git" repository)
                 (format "%s://github.com/%s.git" protocol repository))
               directory))
```

**Comment by decoursin** [comment]
Looks great I'll test it some. I like the protocol implementation. Thank you.

**Comment by tarsius** [comment]
There's an extension for that (tm): https://github.com/dgtized/github-clone.el

**Comment by tarsius** [comment]
In the long run I want to add support for various repository hosts, but for the time being I think `github-clone.el` does the trick.

**Comment by decoursin** [comment]
```github-clone.el``` doesn't work! It's only for forking & cloning not just cloning. Please reopen.

**Comment by tarsius** [comment]
I see. So both `magit` and `github-clone` don't support cloning from github without typing the full url. But since the latter is closer to having the feature you are after (after all its name suggests that it already does), I would suggest you ask for that feature to be added there instead.

Before I remembered `github-clone` I was going to suggest that you open a pull request against `magit-rockstar`. I sometimes add features to that package, which aren't quite there yet, but which are useful even just a minimal viable implementation exists (more about that can be found in the library header).

**Comment by Silex** [comment]
Hum, except if I'm missing something `github-clone` works for cloning & without typing the full url. Only after it cloned it asks wether you want to fork or not.

**Comment by Silex** [comment]
`M-x github-clone will prompt for a repository and directory and clone the repository as origin to that directory. It will then optionally fork the repo and add a remote named after the github user.`

**Comment by decoursin** [comment]
@Silex have you tried ```github-clone``` yet, or are you just judging from that description? I tried ```github-clone``` and maybe I'm not giving it an honest look but it wasn't great.

Anyways, my opinion is that this could be a useful feature, but whether or not it's added for whatever reason is fine, and obviously not up to me. @johnmastro made a nice defun which I'm just going to use. Thank you.

**Comment by Silex** [comment]
@decoursin: yes, and it seems that you didn't try it at all

From the repository own description: `(github-clone "dgtized/github-clone.el" "~")`

So, if you want to test do this:

<kbd>M-x github-clone RET dgtized/github-clone.el RET n RET</kbd>

Here an example (sorry, gif quality is not so good):

![github-clone](https://cloud.githubusercontent.com/assets/16015/11437023/7e140ac0-94ea-11e5-9cad-365a80c83f29.gif)

**Comment by Silex** [comment]
Hehe, it works for all repos but `magit/magit` because one of the URL regex checks if it ends with "git" :) I'm making a PR to fix it, the good thing is that I'm using it to clone & fork it :P

**Comment by decoursin** [comment]
Thanks yeah something like that was going on for me.

**Comment by Silex** [comment]
https://github.com/dgtized/github-clone.el/pull/11

**Comment by tarsius** [comment]
I am closing this again. @decoursin seems happy with the above snippet, and `github-clone` supports many of the things I intend to eventually implement in `magit` (but lacks the tight integration).

**Comment by Silex** [comment]
@decoursin: the PR has been merged FYI

**Comment by decoursin** [comment]
Thanks! I'll probably switch over to that.
