### ISSUE TITLE
Error: Symbol's function definition is void: --some

### ISSUE THREAD

**Issue by malloc82** [magit/magit#2406]
Just upgraded to 2.3.1 from 2.1.0, and I got this error when I try to run magit-status:
```
eval: Symbol's function definition is void: --some
```
:S

**Comment by malloc82** [comment]
It's emacs 24.5 on OS X Yosemite, git 2.5.0

**Comment by syohex** [comment]
Please upgrade `dash`(https://github.com/magnars/dash.el) package and try again.

**Comment by malloc82** [comment]
Great! That fixed it. 
Thanks.
