### ISSUE TITLE
Can't see git-commit-mode

### ISSUE THREAD

**Issue by andreas-roehler** [magit/magit#2410]
magit.el requires 'git-commit-mode, while git-commit seems to deliver just git-commit.

git-commit-mode is a minor mode there.

**Comment by tarsius** [comment]
> magit.el requires 'git-commit-mode

No, it does not: magit.el requires 'git-commit-mode.

You probably need to update Magit. Or if you have updated Magit, then you probably have another instance of it laying around on the `load-path`.

**Comment by andreas-roehler** [comment]
Ah, sorry, see it.
