### ISSUE TITLE
C-h c is not useful with many magit keys

### ISSUE THREAD

**Issue by offby1** [magit/magit#2415]
I ran `M-x magit-status`, then got a log buffer by typing `l l`, then wanted to explore the various ways of showing diffs.  I typed `C-h c d`, and saw 

    d runs the command magit-diff-popup

in the echo area; then I typed `d`, saw the popup, and again typed `C-h c d`.  I was hoping to see something like "d runs the command magit-diff-dwim".  But instead I saw 

    d runs the command magit-invoke-popup-action

The same message appears with the various other diff keys.

This makes it a little hard to explore those options.  In order to learn about them, I have to either invoke each, and guess what it's doing; or read the manual; it'd be more convenient if `C-h c` would tell
me the names of the elisp functions that the various keys run.

**Comment by tarsius** [comment]
Yes that's not very nice but also correct, these keys *are* bound to `magit-invoke-popup-{action,switch,option}`.  You can use `?` instead of `C-h c` to get information about actions, switches and options, and `C-h c` for commands actually bound in `magit-popup-mode-map`.

**Comment by tarsius** [comment]
But I could probably wrap `describe-key-briefly` with a command that know how to deal with the `magit-invoke-{*}` special case.

**Comment by tarsius** [comment]
That seems quite complicated to do, and since I intend to replace `magit-popup.el` with a better abstraction anyway, I am not motivated enough to attempt it anyway. If someone else wants to implement a temporary hack, then please go ahead.
