### ISSUE TITLE
restoring from wip-mode is counter-intuitive

### ISSUE THREAD

**Issue by weeshy** [magit/magit#2416]
I activated wip after safe mode and do save after each line / short function (habit from times when computers shut-down unexpectedly pretty frequent). That gives me extended history of file modification placed inside wip refs. I have tried to revert to some intermediate point. But nothing changes, "no buffers need to be reverted". I was puzzled for a short time. And then tried to look inside *magit-process* buffer. It contains 

> 1 git … checkout wip/wtree/refs/heads/feature~1
> error: Your local changes to the following files would be overwritten by checkout:
>	333
> Please, commit your changes or stash them before you can switch branches.
> Aborting

That is pretty verbose and obvious when you read it. But without looking to the process buffer you would stay in confusion. wip mode seemingly cease to work although it shows full history of changes.

**Comment by tarsius** [comment]
> I have tried to revert to some intermediate point.

No you tried to *checkout* some intermediate point. A hard-revert (<kbd>C-u x</kbd>) would have worked (but it would also have thrown away all uncommitted changes).

> But nothing changes, "no buffers need to be reverted". I was puzzled for a short time.

You saw a message about buffers (not) being reverted because you haven't configure `magit-revert-buffers`, to not show you that. Otherwise ...

> And then tried to look inside magit-process buffer. It contained [...]

... you would have seen the essential part of that right in the echo area.

**Comment by tarsius** [comment]
> wip mode seemingly cease to work

What exactly ceases to work? Are no more wip commits being created?

Does setting `magit-revert-buffers` to `silent` address your issue. Otherwise, what are you suggesting?

**Comment by weeshy** [comment]
I suggest do not output "no buffers need to be reverted" when an error occur. It has no meaning in that case and shadows useful error message in echo area.

**Comment by tarsius** [comment]
The code which reverts the buffers does not know whether the previous command failed (and whether that failure means that reverting would not make sense, which might not be the case for all failures), so this is not possible.

But I think these messages about buffers (not) being reverted are never really useful and should be turned of by all users. The reason they are shown by default anyway are described [here](http://magit.vc/manual/magit/Safety.html). But I am considering getting back to the decision to do it like that, there are just too many users who don't notice the message that instructs them to customize `magit-revert-buffers`.

**Comment by npostavs** [comment]
Maybe it could be a temporary message, using `minibuffer-message`?

**Comment by tarsius** [comment]
That doesn't seem to do the trick (I think I have tried it before). The purpose of this, as the name suggests, seems to be to show a message while reading input in the minibuffer. It does not allow displaying two messages at once, which is what we would need here, I suppose.

I am considering to once more revert in silence by default and instead add a section like this to the status buffer:

```
Settings: revert file buffers: true,  refresh status: true,  refresh current: true  [C-c C-t change]
```

and in a similar spirit

```
Error: whatever git had to complain about  [$ details]
```

**Comment by npostavs** [comment]
> displaying two messages at once, which is what we would need here

Maybe this?
```elisp
(defun add-message (format &rest args)
  (--if-let (current-message)
      (apply #'message (concat "%s\n" format) it args)
    (apply #'message format args)))
```

> add a section like this to the status buffer:

What happens if the status buffer is not visible?

**Comment by tarsius** [comment]
If added the error message section.

**Comment by tarsius** [comment]
Which makes it pretty hard to miss these errors, at least in the status and refs buffers. As before the error is also shown in the echo area.

Displaying "the relevant variables" in a "non-intrusive but visible manner" is harder, mainly because the things in quotes aren't well defined. I'll have to think about that much more and don't intend to do it before the next release.
