### ISSUE TITLE
Which key do the people assign to magit-status?

### ISSUE THREAD

**Issue by zonuexe** [magit/magit#2417]
It's a just for curiosity...

We are able to know what are using which key people.
https://github.com/search?p=1&q=magit-status+bind-key+OR+global-set-key&ref=searchresults&type=Code&utf8=%E2%9C%93

Has anyone statistically investigated this, before?
(If it is outside of you interest, please this issue is quickly closed.)

**Comment by tarsius** [comment]
I would assume most users use `<modifier>-[x|c] [<modifier->]g`. Since the manual recommends <kbd>C-x g</kbd> in many places, that's probably the most common.

> (If it is outside of you interest, please this issue is quickly closed.)

It would have been better to ask on the mailing list.

**Comment by npostavs** [comment]
> We are able to know what are using which key people.
> https://github.com/search?p=1&q=magit-status+bind-key+OR+global-set-key&ref=searchresults&type=Code&utf8=%E2%9C%93

You should also search for `define-key` I guess. Then you just need to use https://developer.github.com/v3/search/#search-code and sum up all the results ;)
