### ISSUE TITLE
Symbol's value as function is void --some

### ISSUE THREAD

**Issue by ajsteven130** [magit/magit#2420]
Using Emacs 24.5.1 on WIndows 7 and installing from both MELPA-Stable (Magit 2.3.1) and MELPA (Magit-20151129.2010) I get the error "Symbol's value as function is void --some". 

It appears to come from /lisp/magit-process.el at line 92. Removing the custom variable that contains "--some", magit-credential-cache-daemon-socket, and re-byte compiling everything seems to make it work fine.

**Comment by tarsius** [comment]
Aaaaaaaaaaaaaaaa! Not **again**.

**Comment by ajsteven130** [comment]
after your comment, I found the duplicate. Sorry

**Comment by tarsius** [comment]
#2382, #2406, #2379

**Comment by tarsius** [comment]
It's okay, but next time please consult a search engine oO

**Comment by npostavs** [comment]
How is this happening for users installing via MELPA? Do we have an incorrect `Package-Requires:`?

**Comment by tarsius** [comment]
No `(dash "20151021.113")` should be recent enough.

**Comment by ajsteven130** [comment]
`(dash "20151021.113")` is what I have installed now with everything working, but for some reason dash did not update automatically when installing Magit through MELPA. Really not sure how I could have screwed that part up.

**Comment by tonyg** [comment]
I have the following packages installed from MELPA, on Emacs 24.5.1 on x86_64 Debian linux:

```
  async              20151123.256  installed             Asynchronous processing in Emacs
  dash               20151021.113  installed             A modern list library for Emacs
  git-commit         20151111.418  installed             Edit Git commit messages
  magit              20151129.2010 installed             A Git porcelain inside Emacs
  magit-popup        20151126.343  installed             Define prefix-infix-suffix command combos
  with-editor        20151126.323  installed             Use the Emacsclient as $EDITOR
```

Every time I run `magit-status`, I get `Symbol's function definition is void: --some`.

I have tried uninstalling and reinstalling `magit`; same error. Then I tried uninstalling *all* those packages, and reinstalling `magit`; same error.

Is there anything I can do to get insight into the problem? Or perhaps there is some stale state somewhere I need to find and dispose of?

**Comment by fakedrake** [comment]
For anyone who like me stumbled upon this issue try updating `dash` and then removing all magit's `.elc` files.
