### ISSUE TITLE
Niceties related to log -L

### ISSUE THREAD

**Issue by Drup** [magit/magit#2421]
I think it would be quite convenient to have a command running `log -L` on the current selected region (in a buffer, chunk, blame ...). 

There is already `magit-log-buffer-file` that presents the log on the current file, but I couldn't find a more specialized version.

**Comment by tarsius** [comment]
Yes, that is planned.

**Comment by Drup** [comment]
Great, thanks.

**Comment by tarsius** [comment]
Actually I already implemented that. Mark some text and then use `M-x magit-log-buffer-file`.

**Comment by Drup** [comment]
Wow, great. I think you should add that to the manual/cheatsheet.
