### ISSUE TITLE
Why are branches with "(" in the branch name shown as detached?

### ISSUE THREAD

**Issue by ojw** [magit/magit#2422]
I can see that in line 808/809 in magit.el, in `magit-insert-local-branches`, `branch` is set to `nil` if the branch name matches "(".  This actually happened today at work, and now my intern is no longer allowed to use parens in branch names.

Why are branch names with parens set to nil and rendered as detached?  I would be happy to try to come up with a patch to allow whatever the intended behavior is while also allowing parens in branch names, if I understood the original intent.

**Comment by kyleam** [comment]
Thanks for catching this.  The code was using "(" as an indicator for "* (HEAD detached at" line in the "git branch -vv" output, leading to false positives in your case (although I think parentheses in branch names are quite uncommon in general).

**Comment by tarsius** [comment]
> This actually happened today at work, and now my intern is no longer allowed to use parens in branch names.

Maybe not such a bad idea :-) I wasn't aware that parens where allowed in branch names.
