### ISSUE TITLE
"M-x magit-show-commit" errors

### ISSUE THREAD

**Issue by alezost** [magit/magit#2426]
Hello, if I run `M-x magit-show-commit` in a fresh emacs (before
running `M-x magit-status` or any other magit command), I get the
following error:

    Symbol's value as variable is void: magit-blame-mode

Checked on the latest master (commit 9ad32d573e5f909c7581d5d55ffaba5898ffdb48)

**Comment by tarsius** [comment]
Loading `magit` also loads `magit-blame`, which in turn defined `magit-blame-mode`.  This sounds like there is something wrong with your installation. Do you have other installations of magit laying around - due to `load-path` issues you might be loading an old version.

**Comment by npostavs** [comment]
Confirmed with `emacs -Q -L ..\dash -L lisp -l lisp/magit-autoloads.el -f magit-show-commit`

> Loading magit also loads magit-blame, which in turn defines magit-blame-mode

Running `magit-show-commit` loads `magit-diff` which loads `magit-core` which loads a few other magit things, but apparently not `magit-blame`.

**Comment by tarsius** [comment]
It's ... a bit complicated. In short, internal dependencies are not strictly linear and that doesn't work well with autoloading.

I think for now we should just require `magit-blame` inside `magit-show-commit` and be done with it.

**Comment by alezost** [comment]
Now (after commit b0c77f5b60b9fe360cb679ed7fdee81718ba6d4b), it
complains about the other thing.  After `M-x magit-show-commit`
it prompts for a commit and then errors:

    run-hooks: Symbol's function definition is void: magit-maybe-show-margin

**Comment by tarsius** [comment]
So far I was operating under the assumption that `magit-status` would have been called at least once before other Magit commands are called. Other issues like this might bubble up when that is not the case.

**Comment by alezost** [comment]
So if `M-x magit-show-commit` (and maybe other commands) wouldn't
work without `M-x magit-status`, then I think it shouldn't be
autoloaded.  Because if it is available right away, a user would expect
it to work, WDYT?

**Comment by tarsius** [comment]
Yes. But because not many users do that, those issues have not been reported yet.

**Comment by alezost** [comment]
Ah, sorry, I thought you meant `magit-show-commit` was not
supposed to be used before `magit-status`, so this issue still
presents then.

**Comment by tarsius** [comment]
After the latest fix `emacs -Q -L ../dash -L lisp -l lisp/magit-autoloads.el -eval '(magit-show-commit "HEAD")'` works for me.

**Comment by alezost** [comment]
Oh, you mean commit 068135377ff3c87c1aec94c4ff90beeaa8fff366; sorry for
bothering, I missed that one.  Yes, I confirm that it works now, thanks!

**Comment by gromgull** [comment]
@tarsius `magit-diff` also breaks if `magit-status` wasn't run first.
