### ISSUE TITLE
Feature Request: Option to strip Leading 'git ' in magit-read-shell-command for easy instructions copy&paste

### ISSUE THREAD

**Issue by MrBones118** [magit/magit#2427]
On the rare occasions when I need to run commands (like git remote add blargh) against some repo, because of some copy n pasted instructions, I use magit's (!).

I often copy the whole line, because I don't think about it, and end up with a leading 'git ' prefix that I don't want.

It'd be nice if there was an option to just drop the leading 'git ' in a command intended to be run against git itself.

I believe the appropriate place to check would be in magit-read-shell-command.

An alternative to a flag might be to ask the user if they really wanted that leading 'git ' and would they like it removing (Y/n)

**Comment by tarsius** [comment]
I'm afraid that's a case of "I have to draw the line *somewhere*". Sure this might prevent a few users a few times from using invalid input. But that is a harmless mistake and then doing it right is hardly any work.

**Comment by tarsius** [comment]
By the way, I would recommend using a terminal for following along a Git tutorial.

**Comment by tarsius** [comment]
Or you could just use `!s` instead of `!!`.
