### ISSUE TITLE
git push is asking for my ssh passphrase whereas I have gpg-agent running

### ISSUE THREAD

**Issue by xmaillard** [magit/magit#2428]
Hi,

When running

```
git push -u origin master
```

This asks for nothing but my PIN code when running from the terminal whereas when doing asame from the magit CLI, it just asks for my ssh passphrase.

I am not sure where to start looking at and I am not even sure it is magit fault at all (maybe something more for the GNU emacs folks ?). 

Happens on GNU emacs 24.x and GNU emacs 25.x.

Here my settings for magit (pretty light :D) :
```
(use-package magit :load-path "lisp/magit/lisp")
```

Thank you.

**Comment by npostavs** [comment]
OS?

How are you setting up gpg-agent? I don't have any experience with this, but according to http://www.incenp.org/notes/2014/gnupg-for-ssh-authentication.html you need environment variables `GPG_AGENT_INFO` and `SSH_AUTH_SOCK`. Perhaps you've set them in your shell but not in Emacs?

**Comment by tarsius** [comment]
If you have problems configuring that, then please ask for help on the Emacs Stackexchange site.
