### ISSUE TITLE
Request for evil-magit

### ISSUE THREAD

**Issue by justbur** [magit/magit#2433]
Hi, I was wondering if you would entertain making an additional change like the one in https://github.com/magit/magit/commit/cc92034cf76ba4f355b203741cfa9d71c6f99088 for the "v" keybindings in section maps. 

I'm doing [this](https://github.com/justbur/evil-magit/blob/master/evil-magit.el#L367-L375) in evil-magit, which seems fine right now, but I'm working on making evil-magit more maintainable and using remap for the "v" bindings in the section maps would make my job easier. 

The other kind of ugly thing I'm doing is [this with the dispatch popup](https://github.com/justbur/evil-magit/blob/master/evil-magit.el#L406-L447). It's not easy to change the popup keys, reorder them, and change the strings in the popup using built-in functions so I just redefine the whole thing, but if you have any thoughts on how the dispatch popup could be manipulated easier I'd like to hear them. 

Thanks

**Comment by tarsius** [comment]
I've done the "v" thing.

> It's not easy to change the popup keys

I don't see a better way.

**Comment by justbur** [comment]
Thank you!
