### ISSUE TITLE
How can I undelete a file?

### ISSUE THREAD

**Issue by andreicristianpetcu** [magit/magit#2437]
I have a file commited in git, and I deleted in from my working tree. 

```bash
$git status
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    my-file.sh
```
I want to do the equivalent of 
```bash
$git checkout -- my-file.sh
$git status
Your branch is up-to-date with 'origin/develop'.
nothing to commit, working directory clean
```
How do I do this in magit? Thank you!

**Comment by kyleam** [comment]
Press 'k' on the file.  (Please ask these sorts of questions on Emacs
Stack Exchange rather than GitHub.)

**Comment by andreicristianpetcu** [comment]
Thank you! I will do that next time! Sorry for bothering you on github :)

**Comment by kyleam** [comment]
No worries :)
