### ISSUE TITLE
Set-upstream is broken / useless

### ISSUE THREAD

**Issue by least-olegs** [magit/magit#2443]
When I specify `-u` in push dialog the command generated is both absurd and harmful:

```
git … push -v --set-upstream origin :
```

This will cause **all** local branches to be pushed to whatever they are tracking... Definitely, what you expect is that only the current branch will be pushed with `-u` option.

I've already seen this: #2441 and related tickets, and... sorry, you broke something that didn't need fixing. It's really easier now to just type the Git command than jump through the Magit hoops to get things done.

**Comment by tarsius** [comment]
You pressed <kbd>m</kbd>, which according to the popup does "Push matching branches". The doc-string of that command is

>  Push all matching branches to another repository. If multiple remotes exit, then read one from the user. If just one exists, use that without requiring confirmation.

The command did what it is supposed to do.

> Definitely, what you expect is that only the current branch will be pushed

No, "branches" is plural.

> ... with `-u` option.

Using `-u` with this command just doesn't make sense. Use <kbd>e</kbd> instead.

**Comment by tarsius** [comment]
> I've already seen this: #2441 and related tickets, and... sorry, you broke something that didn't need fixing.

This command already existed in `v2.1` (but not `v1.4`). I did not change a command I added one which is useful in special cases. You are apparently trying to use it for something it is not intended for.
