### ISSUE TITLE
Magit can't open files that have changed permissions, unchanged content

### ISSUE THREAD

**Issue by wordempire** [magit/magit#2446]
# Context

When changing just the permissions of a file (e.g., `chmod +x test.sh`), while leaving the contents unchanged, Magit shows these changes under Unstaged changes (e.g.: `modified test.sh`). Staging and committing these changes is possible. Pressing tab while the mark is on the relevant line shows something like:
```
modified   test.sh
old mode 100644
new mode 100755
```

# What happens
Trying to open the modified file by having the mark on the relevant line and pressing the return key, leads to the following trace:
```
Debugger entered--Lisp error: (wrong-type-argument markerp nil)
  marker-position(nil)
  magit-diff-hunk-line([cl-struct-magit-section hunk nil #<marker (moves after insertion) at 62 in *magit: problem> nil #<marker at 94 in *magit: problem> nil nil nil nil nil nil [cl-struct-magit-section file "test.sh" #<marker (moves after insertion) at 43 in *magit: problem> #<marker at 62 in *magit: problem> #<marker at 94 in *magit: problem> nil nil nil nil "diff --git test.sh test.sh\nold mode 100644\nnew mode 100755\n" nil [cl-struct-magit-section unstaged nil #<marker (moves after insertion) at 22 in *magit: problem> #<marker at 43 in *magit: problem> #<marker at 95 in *magit: problem> nil nil nil nil nil nil [cl-struct-magit-section status nil #<marker (moves after insertion) at 1 in *magit: problem> nil #<marker at 95 in *magit: problem> nil nil nil nil nil nil nil ([cl-struct-magit-section branch "master" #<marker (moves after insertion) at 1 in *magit: problem> #<marker at 21 in *magit: problem> #<marker at 22 in *magit: problem> nil nil nil nil nil nil #3 nil] #2)] (#1)] (#0)] nil])
  magit-diff-visit-file("/home/wordempire/Projects/problem" nil)
  call-interactively(magit-diff-visit-file nil nil)
  command-execute(magit-diff-visit-file)
```

# What I expect to happen
Magit should open the file that is currently under the mark when pressing return, or should at least signal that opening this file/changeset does not make sense in the current context, instead of crashing.

**Comment by tarsius** [comment]
Thanks for reporting.

I know what the issue is, but it could be quite some work to address it.

**Comment by tarsius** [comment]
Well, fixing this *properly* would be complicated, but adding a kludge is easy. I have done that now.
