### ISSUE TITLE
Show "Unpulled from [push-remote]" above "Unpulled from [upstream]"

### ISSUE THREAD

**Issue by Peeja** [magit/magit#2450]
The situation I'm in today:

I have a feature branch (call it `new-feature`) that's been running for a couple of days. Since then, a whole lot of stuff has been added to `origin/master` (my branch's upstream). I've been pairing on this new feature with someone else, working on my machine. Last night, they added a few tweaks to the branch from their machine, and pushed to `origin/new-feature` (my branch's push-remote branch).

When I glance at my `magit-status` this morning, the most important thing for me to see (once I've fetched) is that there are unpulled commits on the branch. Even knowing that those commits should be there from talking to my teammate, I'd like to be able to quickly see whether I've pulled them into my local branch yet. Unfortunately, the big list of new commits on `origin/master` pushes them off the screen.

I'd suggest moving "Unpulled from [push-remote]" above "Unpulled from [upstream]". In fact, since the next most important thing is knowing what I haven't pushed yet, I *think* this is the order that makes the most sense to me:

* Unpulled from [push-remote]
* Unpushed to [push-remote]
* Unpulled from [upstream]
* Unpushed to [upstream]

Rather than the current:

* Unpulled from [upstream]
* Unpulled from [push-remote]
* Unpushed to [upstream]
* Unpushed to [push-remote]

**Comment by tarsius** [comment]
I am undecided on the order. But not that I made a change yesterday which makes sure that these sections stay collapsed after the user has explicitly collapsed them (even if the section temporarily disappears, e.g. because another branch is checked out or at the end of a rebase). So one could argue that it is better if the most important of these sections comes last. After collapsing the other sections their headers are still visible, informing us of how many commits are unpulled/unpushed. If the most important section came first, were expanded, and contained many commits, then the other sections would be completely off-window.

**Comment by tarsius** [comment]
But maybe we'll get more comments from others.

**Comment by Peeja** [comment]
Oh, that's awesome. If they're collapsed by default, the order matters a lot less to me, I think.

**Comment by tarsius** [comment]
They are *not* collapsed by default, but after you have collapsed them, they will stay that way - even if they should temporarily disappear.

But I am considering adding an option which would allow users to specify initial visibility based on section type. (You can already achieve that now by adding a function to `magit-section-set-visibility-hook`.)

You can also change the order yourself by customizing `magit-status-sections-hook`.

I am considering changing the default order to:

* Unpulled from [upstream]
* Unpushed to [upstream]
* Unpulled from [push-remote]
* Unpushed to [push-remote]

**Comment by tarsius** [comment]
I think I'll keep the current order.

**Comment by tarsius** [comment]
The order can be changed using `magit-status-sections-hook`.

**Comment by Peeja** [comment]
That's awesome. Thanks!
