### ISSUE TITLE
Stash pop enhancement (or at least food for thought)

### ISSUE THREAD

**Issue by jsyjr** [magit/magit#2451]
On emacs-devel Renaud Casenave-Péré posted an interesting note in the thread "Git help requested: "git stash pop" is doing an unwanted "git add". Why?":

> In my experience, if some files are in conflict, git will add to index all
> non-conflicting files to clearly separate the conflicting ones.
> You are then expected to resolve the conflicts, stage the files to tell git to
> accept the resolved files, and do a git reset to put everything back in the
> working area.
>
> I think this is something that is not (properly) documented and quite confusing
> but when you know what to do, you get used to it…

I have run into this stash pop behavior and not understood what had happened.  Renaud's explanation definitely makes things clearer.  I wonder if there is anything that magit can do to clarify the workflow.

**Comment by tarsius** [comment]
I can't think of anything. (And don't really think we have to do anything.)
