### ISSUE TITLE
finding commits by filename

### ISSUE THREAD

**Issue by drorbemet** [magit/magit#2457]
How can magit-log-popup be used to find commits which contain files matching a pattern in all references?
Example:
magit-log-popup with =G *.file-extension$ and e.g. (Log all references)

will not match a commit who's log contains:

new file some-dir/some-file.file-extension

**Comment by tarsius** [comment]
Please don't use this issue tracker for support requests. From the very top of the README:

> When something doesn't work as expected, then please first consult the FAQ and ask a search engine. If that doesn't solve your problem, then please ask for help on Emacs.Stackexchange.
