### ISSUE TITLE
Credential helper doesn't respect set timeout

### ISSUE THREAD

**Issue by mrkkrp** [magit/magit#2460]
Not sure if it's a Magit problem, but after I've set timeout to be 86400 seconds, i.e. one day, I'm asked to enter my credentials way too often. Here is part of my `~/.gitconfig`:

```
[credential]
	helper = cache --timeout=86400
```

It looks like `git` uses its default timeout — 15 minutes. I don't know why. I cannot find anything on the internet about this issue, because

```
git config --global credential.helper 'cache --timeout=86400'
```

seems to work for everybody. I decided to ask you if it may be a Magit issue, because I remember Magit had some issues with credential helpers.

**Comment by npostavs** [comment]
Well, can you see if you get this issue from the command line, without Magit?

I don't think it's a Magit issue, because the workaround for the credential helpers problem is just to execute `git-credential-cache--daemon` from Magit, and that program is not responsible for handling the `--timeout` argument.

However, if "too often" means *every time*, then check the values of `magit-credential-cache-daemon-socket` and `magit-credential-hook`, perhaps the workaround is not activating for you.

**Comment by mrkkrp** [comment]
Value of `magit-credential-hook` is `(magit-maybe-start-credential-cache-daemon)`. Value of `magit-credential-cache-deamon-socket` is `"/home/mark/.git-credential-cache/socket"`. This file does not exist in `.git-credential-cache` directory.

**Comment by mrkkrp** [comment]
Ah, you create it temprarily... Anyway, somehow it doesn't last longer than several minutes. Even worse sometimes I push and enter password, then push right after that and still it asks password again. I don't know what to think. I cannot use `store` helper because password will be written in file system unencrypted. What a disaster.

**Comment by npostavs** [comment]
> Ah, you create it temprarily...

`git-credential-cache--daemon` creates it.

> Even worse sometimes I push and enter password, then push right after that and still it asks password again.

Can you clarify if this also happens from the command line or not?

**Comment by mrkkrp** [comment]
> Can you clarify if this also happens from the command line or not?

Ahhh. Of course it doesn't work from the command line too. There is no typo… no idea why it doesn't work. I'm just lucky. Anyway, sorry, I had to check this first before opening an issue here. I just thought that if all resources mention that

```
$ git --global config credential.helper 'cache --timeout=9999'
```

works, it should work for me too. And since not everyone is using Magit, it may have something to do with it. Closing.

**Comment by npostavs** [comment]
> Of course it doesn't work from the command line too.

Okay, so not a Magit problem.

> Anyway, somehow it doesn't last longer than several minutes.

Well, it sounds like someone is telling your `git-credential-cache--daemon` to quit. Maybe there is some way to intercept the signals it receives? Good luck.

**Comment by mrkkrp** [comment]
In case someone runs into this from seach engines or something. My problem had to do with `git-deamon`. I use Arch Linux and `git-daemon` seems to be needed for this to work, so:

```
$ sudo systemctl enable git-daemon.socket
# if you want to start using it immediately:
$ sudo systemctl start git-daemon.socket
```

This seems to work, although there is not a single place on the internet to tell about this.
