### ISSUE TITLE
What Magit wants from me when it asks to setup upstream?

### ISSUE THREAD

**Issue by mrkkrp** [magit/magit#2464]
I created a repository. I added a remote called `origin` with its location. Now for the weird part, I need to setup upstream, but I cannot. When I hit <kbd>P u</kbd> (which should push upstream after setting it), I'm getting empty list of completions. When I go to <kbd>b u</kbd> it prompts with “change upstream of master: ” and again empty list of completions.

Status buffer has this:

    Head:     master Initial commit
    Push:     origin/master is missing

What does Magit want from me? Previously it all worked much more intuitive. I always used something like `--set-upstream` in push popup when pushing for the first time, and then it's set and no problems.

**Comment by tarsius** [comment]
I made some changes related to this today, but with the latest commit everything seems to be working as expected. Please check if you are using the very latest commit, maybe there was a bug in an intermediate commit.

**Comment by mrkkrp** [comment]
Oh, sorry, indeed upgrading solves it.
