### ISSUE TITLE
Wrong type argument

### ISSUE THREAD

**Issue by powellb** [magit/magit#2465]
Greetings, I am running gnu emacs version 25.0.50.1 compiled with homebrew on Mac OS X. I installed magit through MELPA (current version 20160105.1035). For all but one of my git projects, magit works perfectly well.

The one project where it fails is a clone from my private github repository. When I enter magit-status, I get:

if: Wrong type argument: stringp, nil

This is the only bit reported in the *Messages* buffer. I'm happy to provide more information required to track it down.

**Comment by kyleam** [comment]
Can you set `debug-on-error` to t to get a backtrace?  Also, please try to find a public repository where the error occurs.

**Comment by powellb** [comment]
kyle, I tested with `debug-on-error`, and it made me realize that I had added a .dir-locals.el file to the root of the git repository. Somehow this code is interfering with `magit`. I'll have to track down why, but it isn't `magit` issue. Feel free to close.

If you are interested, the code defines that .h files in that directory should be loaded into a different mode. The code:

`((nil (eval . (if (string-match ".h$" (buffer-file-name))(fortran-mode)))))`

However, the debugger when trying to start `magit` states:

`Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match(".h$" nil)
  (if (string-match ".h$" (buffer-file-name)) (fortran-mode))
  eval((if (string-match ".h$" (buffer-file-name)) (fortran-mode)))
  #[514 "\301=\203\302\303!\227\304P!\305!\305!=?\205\211 \207\306=\203g\211:\203a\211@\211\307=\203`A\211:\203_\211@\211:\203^\211@\211\310=\203]A\211:\203\\\211@A\211\204Z\311!\266\266\210\210\210\210\210\212\306!)\207\311!\210\211;\203x\312\313G\314$\210\315!L\207" [major-mode mode intern symbol-name "-mode" indirect-function eval add-hook quote hack-one-local-variable--obsolete set-text-properties 0 nil make-local-variable] 12 1910273](eval (if (string-match ".h$" (buffer-file-name)) (fortran-mode)))
  ad-Advice-hack-one-local-variable(#[514 "\301=\203\302\303!\227\304P!\305!\305!=?\205\211 \207\306=\203g\211:\203a\211@\211\307=\203`A\211:\203_\211@\211:\203^\211@\211\310=\203]A\211:\203\\\211@A\211\204Z\311!\266\266\210\210\210\210\210\212\306!)\207\311!\210\211;\203x\312\313G\314$\210\315!L\207" [major-mode mode intern symbol-name "-mode" indirect-function eval add-hook quote hack-one-local-variable--obsolete set-text-properties 0 nil make-local-variable] 12 1910273] eval (if (string-match ".h$" (buffer-file-name)) (fortran-mode)))
  apply(ad-Advice-hack-one-local-variable #[514 "\301=\203\302\303!\227\304P!\305!\305!=?\205\211 \207\306=\203g\211:\203a\211@\211\307=\203`A\211:\203_\211@\211:\203^\211@\211\310=\203]A\211:\203\\\211@A\211\204Z\311!\266\266\210\210\210\210\210\212\306!)\207\311!\210\211;\203x\312\313G\314$\210\315!L\207" [major-mode mode intern symbol-name "-mode" indirect-function eval add-hook quote hack-one-local-variable--obsolete set-text-properties 0 nil make-local-variable] 12 1910273] (eval (if (string-match ".h$" (buffer-file-name)) (fortran-mode))))
  hack-one-local-variable(eval (if (string-match ".h$" (buffer-file-name)) (fortran-mode)))
  hack-local-variables-apply()
  hack-dir-local-variables-non-file-buffer()
  magit-mode()
  magit-status-mode()
`
