### ISSUE TITLE
Rebase conflict with deleted files is not present in unstaged changes

### ISSUE THREAD

**Issue by immerrr** [magit/magit#2466]
If you rebase a branch that modifies a file that was deleted in the destination, i.e. in `git status` output you see
```
# Unmerged paths:
#   (use "git reset HEAD <file>..." to unstage)
#   (use "git add/rm <file>..." as appropriate to mark resolution)
#
#	deleted by us:   foobar
```
while in magit status window it is displayed as staged, something like this:
```
Staged changes (10)
unmerged   foobar (deleted by us)
```

And when you try to continue rebasing it will rightly refuse to do so:
```
user-error: Cannot continue rebase with unstaged changes
```

**Comment by tarsius** [comment]
Could you please provide some dummy history to make it easier to see what exactly you are taking about. Please use graphs and messages like "edit file", "create file", and "delete file", and provide a before and after rebase history.

Also, is the deleted file really not also appearing in *Unstaged changes*?

**Comment by kyleam** [comment]
I believe this is related to #2263.  Not sure what the best way for us to handle this is, but you can currently deal with this using "k" on the file in the staged changes.

**Comment by immerrr** [comment]
Here's a reproduction script: https://gist.github.com/immerrr/2c835d886b23b70ebd28

**Comment by immerrr** [comment]
And yes, <kbd>k</kbd> works as expected. It does counterintuitively call the branch I'm currently rebasing "their stage" and the destination revision as "our stage", but I guess that's just git things.

**Comment by tarsius** [comment]
I do not intend to make any changes here until I start refactoring how diffs are created (which will be done mostly to improve performance).

> It does counterintuitively call the branch I'm currently rebasing as "their stage" and the destination revision as "our stage", but I guess that's just git things.

Yes, it's a git thing and not very intuitive, but it makes sense. *Our* side is always reachable from HEAD, and *their* side is what is coming from somewhere else to be applied here onto HEAD. When merging terminology that feels natural but during rebases it's a bit odd.
