### ISSUE TITLE
Make `magit-popup-mode-display-buffer' reliable and flexible

### ISSUE THREAD

**Issue by Alexander-Shukaev** [magit/magit#2467]
As is currently implemented

```
(defun magit-popup-mode-display-buffer (buffer mode)
  (let ((winconf (current-window-configuration)))
    (split-window-vertically)
    (other-window 1)
    (switch-to-buffer buffer)
    (funcall mode)
    (setq magit-popup-previous-winconf winconf)))
```

`magit-popup-mode-display-buffer` appears to be rigid and unusable with certain configurations.  Let me give you an example.  I have

```
(setq-default
  window-min-height 20
  window-min-width  20)
```

which makes `magit-popup-mode-display-buffer` throw error about not being able to split quite often.  Furthermore, even if one specifies lower limits, one could still potentially hit this problem.

Instead, the implementation of `magit-popup-mode-display-buffer` should be both reliable and flexible.  No need to reinvent the wheel here, utilize `display-buffer`.  One of the good points about it is that it calls `split-window-preferred-function` internally which could be customized easily and defaults to the reasonable `split-window-sensibly`.  I believe that the reasonable algorithm of popping up should be as follows:

1.  Try `split-window-sensibly`, if it works, then display buffer there;
2.  else reuse some other already existing window and display buffer there.

And that is exactly what `display-buffer` does by default.

**Comment by tarsius** [comment]
Please try this change: https://github.com/magit/magit/compare/jb/display-buffer?expand=1.

**Comment by tarsius** [comment]
I've installed that change now.

**Comment by Alexander-Shukaev** [comment]
Reviewed and tested.  Simply perfect!  GJ, Jonas.  Thank you!
