### ISSUE TITLE
Warning (with-editor): Cannot determine a suitable Emacsclient

### ISSUE THREAD

**Issue by wd** [magit/magit#2472]
Do not know how to fix this error, it will cause my emacs stuck about 1min.

```
(custom-set-variables
 '(with-editor-emacsclient-executable "/usr/local/bin/emacsclient"))
```
with-editor-debug output
```
with-editor: /Users/wd/.emacs.d/elpa/with-editor-20151223.1341/with-editor.el
emacs: /Applications/Emacs.app/Contents/MacOS/Emacs (24.5.1)
system:
  system-type: darwin
  system-configuration: x86_64-apple-darwin15.2.0
  system-configuration-options: --prefix=/usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15 --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/share/info/emacs --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15
server:
  server-running-p: t
  server-process: #<process server>
  server-use-tcp: nil
  server-name: server
  server-socket-dir: /var/folders/3g/pnxgfhzn13vfcgk15ggzd1zw0000gn/T//emacs501
    server
  server-auth-dir: ~/.emacs.d/server/
magit-emacsclient-executable:
 value:   /usr/local/bin/emacsclient (DLL)
 default: /usr/local/bin/emacsclient (DLL)
 funcall: nil (nil)
path:
  $PATH: "/Users/wd/.pyenv/shims:/Users/wd/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  exec-path: (/Users/wd/.pyenv/shims /Users/wd/bin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/libexec/emacs/24.5/x86_64-apple-darwin15.2.0 /usr/local/bin ~/bin/)
  with-editor-emacsclient-path:
    /Applications/Emacs.app/Contents/MacOS (t)
    /Users/wd/.pyenv/shims (t)
    /Users/wd/bin (t)
    /usr/bin (t)
      /usr/bin/emacsclient (22.1)
    /bin (t)
    /usr/sbin (t)
    /sbin (t)
    /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/libexec/emacs/24.5/x86_64-apple-darwin15.2.0 (t)
    /usr/local/bin (t)
      /usr/local/bin/emacsclient (DLL)
    ~/bin/ (t)
```

```
$ ls -alh /usr/local/opt/emacs-mac/bin/emacsclient
-r-xr-xr-x  1 wd  admin    29K Dec 23 13:59 /usr/local/opt/emacs-mac/bin/emacsclient
$ ls -alh /usr/local/bin/emacsclient
lrwxr-xr-x  1 wd  admin    57B Dec 23 13:59 /usr/local/bin/emacsclient -> ../Cellar/emacs-mac/emacs-24.5-z-mac-5.15/bin/emacsclient
```

**Comment by tarsius** [comment]
> ```
> emacs: /Applications/Emacs.app/Contents/MacOS/Emacs (24.5.1)
> magit-emacsclient-executable:
>  value:   /usr/local/bin/emacsclient (DLL)
>  default: /usr/local/bin/emacsclient (DLL)
>
> /usr/local/bin/emacsclient -> ../Cellar/emacs-mac/emacs-24.5-z-mac-5.15/bin/emacsclient
> ```

Currently you are using an `emacsclient` installed using homebrew (magit-emacsclient-executable: usr/local/bin/emacsclient -> ../Cellar/emacs-mac/emacs-24.5-z-mac-5.15/bin/emacsclient) to connect to an Emacs instance which comes from another installation (Emacs.app).

Since both installations are at the same version `24.5.*` I would have expected this to work and the code which determines a suitable emacsclient works under the same assumption. You have set `with-editor-emasclient-exectutable` explicitly, but the same value would have been picked automatically.

> ```
> magit-emacsclient-executable:
>  value:   /usr/local/bin/emacsclient (DLL)  <= what you have set               <---.
>  default: /usr/local/bin/emacsclient (DLL)  <= what would have been used, same as -'
> ```

If you always start Emacs by clicking on an icon, then a quick fix would be to uninstall the version installed with homebrew.

**Comment by tarsius** [comment]
Please post the output of `git commit` from the process buffer. To show the process buffer go to the status buffer in which you tried to commit  and then press `$`. You might then have to expand the appropriate section using `TAB`.

**Comment by tarsius** [comment]
> `Cellar/emacs-mac`

Does homebrew now offer an `emacs-mac` package in addition to an `emacs` package?

**Comment by tarsius** [comment]
Please post the output of `grep /usr/local/Cellar/emacs-mac/ -name 'emacsclient*'`.

**Comment by wd** [comment]
Emacs.app in Application is just a link from /usr/local/opt/emacs-mac, these emacs are all the same install from https://github.com/railwaycat/emacs-mac-port .
```
wd @  ❯❯❯ ls -alh /usr/local/bin/emacsclient
lrwxr-xr-x  1 wd  admin    57B Dec 23 13:59 /usr/local/bin/emacsclient -> ../Cellar/emacs-mac/emacs-24.5-z-mac-5.15/bin/emacsclient
wd @  ❯❯❯ ls -alh /usr/local/opt/emacs-mac
lrwxr-xr-x  1 wd  admin    41B Dec 23 13:59 /usr/local/opt/emacs-mac -> ../Cellar/emacs-mac/emacs-24.5-z-mac-5.15
wd @  ❯❯❯ ls -alh /Applications/Emacs.app
lrwxr-xr-x  1 wd  admin    34B Dec 23 14:13 /Applications/Emacs.app -> /usr/local/opt/emacs-mac/Emacs.app
wd @  ❯❯❯ ls -alh /usr/local/opt/emacs-mac/bin/emacsclient
-r-xr-xr-x  1 wd  admin    29K Dec 23 13:59 /usr/local/opt/emacs-mac/bin/emacsclient
wd @  ❯❯❯ md5 /usr/local/opt/emacs-mac/bin/emacsclient
MD5 (/usr/local/opt/emacs-mac/bin/emacsclient) = b5b64ec76f62e72f80c8259be18ec1a3
wd @  ❯❯❯ md5 /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/bin/emacsclient
MD5 (/usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/bin/emacsclient) = b5b64ec76f62e72f80c8259be18ec1a3
```

**Comment by tarsius** [comment]
Did you create some of these symlinks yourself, or did homebrew do that? How exactly do you install `emacs-mac` using homebrew?

Please also answer my other questions and post the output from the process buffer as requested.

**Comment by wd** [comment]
Sorry for not answer your questions, I just understand what to do..

```
  0 git … commit --
Waiting for Emacs...
[test_branch df6f33c] a test commit
 1 file changed, 1 insertion(+)
```

It seems the warning didn't prevent me to commit, but why it will hung 1min at startup..

I install emacs-mac use these command as the guid says
```
$ brew tap railwaycat/emacsmacport
$ brew install emacs-mac
```

The symbol link in /Application is done by me. The link for /usr/local/opt/emacs-mac is following the guide
```
Emacs.app was installed to:
  /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15

To link the application to default Homebrew App location:
  brew linkapps
or:
  ln -s /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/Emacs.app /Applications
```

And I tried execute Emacs.app in terminal like ` /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/Emacs.app/Contents/MacOS/Emacs`, get the same problem.

**Comment by tarsius** [comment]
Please post the output of `emacsclient --version`. It should output something like `emacsclient 25.0.50`, but I am guessing it instead outputs `emacsclient DLL ...`.

**Comment by wd** [comment]
```
wd @ ~ ❯❯❯ /usr/local/opt/emacs-mac/bin/emacsclient --version
emacsclient 24.5
wd @ ~ ❯❯❯ /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/bin/emacsclient --version
emacsclient 24.5
```

Do I have a choice to disable the auto detect to avoid the hanging time at emacs startup?

**Comment by tarsius** [comment]
> Do I have a choice to disable the auto detect to avoid the hanging time at emacs startup?

No. If you set `with-editor-emacsclient-executable` before `with-editor` is loaded, then that value will be used, but `(with-editor-locate-emacsclient)` is evaluated anyway (to obtain the default  value).

I know the value should be the same due to symlinks and all, but please also test what `/usr/local/bin/emacsclient --version` prints.

```lisp
(defcustom with-editor-emacsclient-executable (with-editor-locate-emacsclient)
   ...)
```

**Comment by wd** [comment]
```
wd @ ~ ❯❯❯ /usr/local/bin/emacsclient --version
emacsclient 24.5

MD5 (/usr/local/bin/emacsclient) = b5b64ec76f62e72f80c8259be18ec1a3
MD5 (/usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/bin/emacsclient) = b5b64ec76f62e72f80c8259be18ec1a3
MD5 (/usr/local/opt/emacs-mac/bin/emacsclient) = b5b64ec76f62e72f80c8259be18ec1a3
```
I think this problem happens only about in 2 or 3 weeks, I'm a magit user about 1 or 2 years ago ..

**Comment by wd** [comment]
I'm almost crazy, after reboot my mac, it's finally worked. Do not know what's the problem, because I can't reproduce this problem, so close it first. :(
```
with-editor: /Users/wd/.emacs.d/elpa/with-editor-20160101.32/with-editor.el
emacs: /usr/local/opt/emacs-mac/Emacs.app/Contents/MacOS/Emacs (24.5.1)
system:
  system-type: darwin
  system-configuration: x86_64-apple-darwin15.2.0
  system-configuration-options: --prefix=/usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15 --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/share/info/emacs --with-mac --enable-mac-app=/usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15
server:
  server-running-p: t
  server-process: #<process server>
  server-use-tcp: nil
  server-name: server
  server-socket-dir: /var/folders/3g/pnxgfhzn13vfcgk15ggzd1zw0000gn/T//emacs501
    server
  server-auth-dir: ~/.emacs.d/server/
magit-emacsclient-executable:
 value:   /usr/local/bin/emacsclient (24.5)
 default: /usr/local/bin/emacsclient (24.5)
 funcall: /usr/local/bin/emacsclient (24.5)
path:
  $PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  exec-path: (/usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/libexec/emacs/24.5/x86_64-apple-darwin15.2.0 /usr/local/bin ~/bin/)
  with-editor-emacsclient-path:
    /usr/local/opt/emacs-mac/Emacs.app/Contents/MacOS (t)
    /usr/bin (t)
      /usr/bin/emacsclient (22.1)
    /bin (t)
    /usr/sbin (t)
    /sbin (t)
    /usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.15/libexec/emacs/24.5/x86_64-apple-darwin15.2.0 (t)
    /usr/local/bin (t)
      /usr/local/bin/emacsclient (24.5)
    ~/bin/ (t)
```

**Comment by wd** [comment]
Finally, I found the 1min stuck is caused by tramp.
I use `emacs -q` start a clean emacs, and do ```(require `tramp)``` will stuck eamcs.

Thanks @tarsius.

**Comment by tarsius** [comment]
See http://emacs.stackexchange.com/a/19110/306.

**Comment by wd** [comment]
GOD! you saved me, it's worked... tears...

**Comment by tarsius** [comment]
It's a pretty annoying issue - *many* users have had this problem.
