### ISSUE TITLE
Changing branch after pull gets characters added to branch name

### ISSUE THREAD

**Issue by chasrmartin** [magit/magit#2473]
Using magit-90150116

1. Pull a repo with P P
2. Choose a branch with b b
3. Choose default branch

`pbb` is prepended to the banch name, or used as the autocomplete branch name.

**Comment by tarsius** [comment]
This is an extremely old version. Please follow [these]( http://magit.vc/manual/magit/Installation.html) update instructions.

**Comment by chasrmartin** [comment]
Well, that's annoying. I update packages every day or two, but for some
reason magit disappeared from the list. I had to delete the whole package
and reinstall.
