### ISSUE TITLE
git-appraise support

### ISSUE THREAD

**Issue by the-kenny** [magit/magit#2478]
[git-appraise](https://github.com/google/git-appraise) is a distributed code review system by Google using the git-repository that's been worked on as the storage backend.

It supports comments, CI status, upvote/downvote, and everything you want from a code review system. The only thing lacking is a good emacs interface! As the data is stored in git I'm quite sure magit could even integrate it without resorting to the implementation in Go.

I'd personally *love* to see this integrated in magit. We're evaluating it at work and I'd start implementing it right now if I wasn't way too busy with work-projects already.

**Comment by tarsius** [comment]
I do intend to implement code review tools. This is a vague description from the `3.1.0` milestone:

>  - Tight integration with github, gitlab, bitbucket etc.
>    - Mirror issues as a ref
>	  - Use api to "fetch" and "push" changes (using git hooks)
>	  - Store each post in separate file, to require fewer manual merges
>	  - Maybe implement the core as a shell-script
>      - Implement a variant that does not depend on any of the apis as backend

And of course I will review existing tools before I do so. Including `git-appraise`.

Magit support for `git-appraise` itself is also feasible, but I think that should be implemented as a separate package. (And not by me.)

**Comment by tarsius** [comment]
While I cannot rule out that I will add support for `git-appraise` once I start concentrating on "collaboration features" and inspect `git-appraise` more, I think it is more likely that I won't ever support this particular tool inside Magit itself.

**Comment by abourget** [comment]
It'd be *ssssooo* great to have appraise support in there :)
