### ISSUE TITLE
ad-Advice-require: Cannot open load file: no such file or directory, magit-autorevert

### ISSUE THREAD

**Issue by seanhagen** [magit/magit#2479]
Installed the latest version of Magit from ELPA ( magit-20161112.1357 ), and I started getting the error from the title:

`ad-Advice-require: Cannot open load file: no such file or directory, magit-autorevert`

When searching, I noticed that in magit-mode.el, `(require 'magit-autorevert)` is commented out, but in magit-core.el, it's not. Is that what's causing this issue?

**Comment by seanhagen** [comment]
Commenting out `(require 'magit-autorevert)` in magit-core.el seems to solve the issue.

**Comment by syohex** [comment]
MELPA recipe lacks `magit-autorevert.el`. Please see https://github.com/milkypostman/melpa/pull/3488

**Comment by seanhagen** [comment]
@syohex guess I just updated my packages at precisely the wrong time :disappointed:

**Comment by tarsius** [comment]
Sorry. I completely forgot about that.

**Comment by syohex** [comment]
My PR has been merged. This issue will be fixed soon.

**Comment by ckruse** [comment]
Temporary fix until new package has arrived: copy `https://raw.githubusercontent.com/magit/magit/master/lisp/magit-autorevert.el

**Comment by parkouss** [comment]
Thanks @ckruse for the trick!

**Comment by martinp** [comment]
Needs https://github.com/milkypostman/melpa/pull/3491 to fix it.

**Comment by martinp** [comment]
Broken in MELPA stable as well, unfortunately.

**Comment by tarsius** [comment]
There's a good snapshot package available from Melpa now.
