### ISSUE TITLE
Magit broken on Melpa

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2480]
Hi,

after upgrading, the thing is broken.  magit-core has 
```
(require 'magit-autorevert)
```

but that file is not available, neither as part of the package, nor as a separate package.

TIA, Michael.

**Comment by syohex** [comment]
This is same as #2479.
And see https://github.com/milkypostman/melpa/pull/3488.

**Comment by michael-heerdegen** [comment]
Indeed.  Sorry, I missed that issue due to this weird "ad-Advice-require" in the title, and didn't read further cause I didn't think it would be related.  And that after you have reduced your number of issues to three...

Thanks, Michael.
