### ISSUE TITLE
No such file or directory "magit-autorevert"

### ISSUE THREAD

**Issue by caisah** [magit/magit#2481]
When I require `magit` I get the following:

`Debugger entered--Lisp error: (file-error "Cannot open load file" "no such file or directory" "magit-autorevert")
  require(magit-autorevert)
  eval-buffer(#<buffer  *load*-537362> nil "/home/vlad/.emacs.d/.cask/24.5.1/elpa/magit-20160112.1357/magit-core.el" nil t)  ; Reading at buffer position 1429
  load-with-code-conversion("/home/vlad/.emacs.d/.cask/24.5.1/elpa/magit-20160112.1357/magit-core.el" "/home/vlad/.emacs.d/.cask/24.5.1/elpa/magit-20160112.1357/magit-core.el" nil t)
  require(magit-core)
  eval-buffer(#<buffer  *load*> nil "/home/vlad/.emacs.d/.cask/24.5.1/elpa/magit-20160112.1357/magit.el" nil t)  ; Reading at buffer position 2244
  load-with-code-conversion("/home/vlad/.emacs.d/.cask/24.5.1/elpa/magit-20160112.1357/magit.el" "/home/vlad/.emacs.d/.cask/24.5.1/elpa/magit-20160112.1357/magit.el" nil t)
  require(magit)
  eval((require (quote magit)) nil)
  eval-expression((require (quote magit)) nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
`

Do you know how I could fix this? Thanks.

**Comment by jixiuf** [comment]
https://github.com/milkypostman/melpa/issues/3487

**Comment by caisah** [comment]
@jixiuf Thanks!
