### ISSUE TITLE
Git auto packing freezing emacs when interfacing w/ git through magit

### ISSUE THREAD

**Issue by mk0x9** [magit/magit#2482]
Sometime git triggers auto gc whenever I commit/rebase/etc and this usually takes some time on big repos. Problem is that it's completely freezing emacs until it's done.

`Magit 2.3.1-217-g455c8f2, Git 2.5.4 (Apple Git-61), Emacs 24.5.1`

**Comment by tarsius** [comment]
> ```
> gc.autoDetach
>    Make git gc --auto return immediately and run in background if the
>    system supports it. Default is true.
> ```

I don't know whether OS X "supports it". Please confirm by running `git gc --auto` manually.

**Comment by mk0x9** [comment]
Wow, that's awesome option. Yeah, it works fine on OS X with git
bundled with Xcode.

close #2482
