### ISSUE TITLE
latest from elpa: command-execute: Symbol's function definition is void: magit-status

### ISSUE THREAD

**Issue by twillis** [magit/magit#2484]
grepping the code I could not find a defun either. magit-20160112.1357 there was also no magit.el

**Comment by syohex** [comment]
Sorry I mistook to update magit recipe of MELPA.

See also
- https://github.com/magit/magit/issues/2485#issuecomment-171336479
- https://github.com/magit/magit/issues/2485#issuecomment-171337047

**Comment by npostavs** [comment]
(I guess technically #2485 is the duplicate, but it was responded to first)
