### ISSUE TITLE
File error: Cannot open load file, no such file or directory, magit

### ISSUE THREAD

**Issue by yamafaktory** [magit/magit#2485]
After a fresh install of Magit via **MELPA** (_magit-20160112.1357_), I get the following error at startup:

```
File error: Cannot open load file, no such file or directory, magit
```

I tried it multiple times and also tried to use the fix provided by #2479, without any success.

**Comment by syohex** [comment]
Sorry I mistake to update magit recipe.

Please wait until https://github.com/milkypostman/melpa/pull/3491 will be merged.

**Comment by syohex** [comment]
Workaround: download magit.el and put it into load-path directory

**Comment by Titan-C** [comment]
Not sure if the workaround is enough, I also had to download with-editor.el manually

**Comment by syohex** [comment]
`with-editor` is not contained in magit. It is different package.

See also
- http://melpa.org/#/with-editor

**Comment by Gnouc** [comment]
@Titan-C Just use `magit` from melpa-stable, like I [did](https://github.com/Gnouc/emacs.d/commit/75f31af8e351fdd1e2bf6750ad72283310fe9fc0)

**Comment by yamafaktory** [comment]
@syohex Many thanks for the quick fix (and do not be sorry for it)! Keep up the great work!

As other files were missing, the easiest way to get everything fixed was to download then copy all the files from the lisp directory.

**Comment by jonathanchu** [comment]
Thanks for the quick fix here @syohex, and help from @yamafaktory @Titan-C @Gnouc!

Can we keep this open until https://github.com/milkypostman/melpa/pull/3491 is merged in?  I spent a good amount of time trying to debug this (thinking I broke things without knowing) and finally looked into the closed issues to see the info that helped the most.

Cheers for all the great work! :beers:

**Comment by npostavs** [comment]
> Can we keep this open until milkypostman/melpa#3491 is merged in?

Well it's merged, but it doesn't seem to have rebuilt yet, so I'll reopen. According to Murphy's Law, it will be fixed a few minutes after I reopen, you're welcome ;)

**Comment by jonathanchu** [comment]
@npostavs :laughing: Thanks!  Hopefully it will save others some time as there are some temporary workarounds in this thread that can be helpful.

**Comment by tarsius** [comment]
I've just pushed a commit which fixes some typos. That should trigger the creation of a new Melpa snapshot.

**Comment by jonathanchu** [comment]
Cheers, thanks @tarsius!

**Comment by jonathanchu** [comment]
I can confirm this specific issue is fixed now, please feel free to close at your convenience. Thank you for the great work!
