### ISSUE TITLE
Cannot find file magit-autorevert

### ISSUE THREAD

**Issue by gongzhitaao** [magit/magit#2486]
According to #2081, `magit-auto-revert-mode` is removed.  But I still find use of the variable `magit-auto-revert-mode` in `magit-apply.el` [Line 216][1] and [Line 234][2].

And also, I got error 

>Cannot open load file: no such file or directory, magit-autorevert

At `magit-core.el` [Line 39][3], i.e. `(require 'magit-autorevert)`

[1]: https://github.com/magit/magit/blob/master/lisp/magit-apply.el#L216
[2]: https://github.com/magit/magit/blob/master/lisp/magit-apply.el#L234
[3]: https://github.com/magit/magit/blob/master/lisp/magit-core.el#L39

**Comment by tarsius** [comment]
> According to #2081, `magit-auto-revert-mode` is removed.  But I still find use of the variable `magit-auto-revert-mode` in `magit-apply.el` [Line 216][1] and [Line 234][2].

A new implementation was added yesterday, which again uses `magit-auto-revert-mode`: #2474.

> And also, I got error 

> > Cannot open load file: no such file or directory, magit-autorevert

That's a known issue, see #2479, #2485, and several other duplicates.

**Comment by gongzhitaao** [comment]
Oops, sorry.  Missed those two thread.  I must have searched the known issue with wrong keywords.
