### ISSUE TITLE
Performance regression....

### ISSUE THREAD

**Issue by smandy** [magit/magit#2487]
HI All,

I've seen a noticeable regression in performance when performing recent upgrade. Specifically when trying to get log with 'l l' ( i.e. lower-case letter 'L' pressed twice), emacs becomes unresponsive. I've reverted my magit to 20150826.1244 and the issue is no longer there. ( I had this release on another box so replaced the new magit directory with this old one).

I'm working with a very 'branchy' repo so this is a problem that may not be apparent for straight-line workflows.

Sorry about quite vague report but thought best to mention. I'll have limited cycles to try further diagnoses. I'm not very familiar with melpa does it allow reverting to specific revisions? One way I could help would be to do a manual bisectional search through recent releases to try to pinpoint the exact change that spawned this regression. 

Or maybe would installing magit manually and doing a git bisect be the way to go?

Cheers,

A

**Comment by tarsius** [comment]
Make sure that `-n<NUMBER>` is one of the log arguments (by default `-n256` is). In the log buffer press <kbd>L -n 256 RET</kbd> and then <kbd>C-x C-s</kbd>.

**Comment by smandy** [comment]
Much better - thanks!
