### ISSUE TITLE
Strange behavior of `magit-clone`

### ISSUE THREAD

**Issue by mrkkrp** [magit/magit#2488]
I have the following function to install packages directly from Git repositories (I know about QUELPA, but this function is good enough for me):

```emacs-lisp
(defun package-install-git (address)
  "Install package directly from git repository at ADDRESS.

This functionality requires git installed."
  (interactive (list (read-string "Address: ")))
  (save-window-excursion
    (let ((temp-dir (make-temp-file "emacs-package-" t))
          (magit-clone-set-remote.pushDefault t))
      (magit-clone address temp-dir)
      (package-install-file temp-dir))))
```

It is called when my config sets itself up. When it happens on the first start-up, I get this:

> Not inside a Git repository

I didn't have problems with it in the past. Also, if I evaluate it “manually”, i.e. via `eval-last-sexp`, I see Magit status buffers temporarily appearing and all goes well. How can I make it work on first start-up as well?

**Comment by tarsius** [comment]
I've just fixed a bug in `magit-clone`. Please try again.

**Comment by mrkkrp** [comment]
I can confirm that it's fixed now. Thanks for the quick response!
