### ISSUE TITLE
Several "Wrong type argument: timerp, nil" warnings

### ISSUE THREAD

**Issue by unixpipecentipede** [magit/magit#2489]
Hello,
Since the latest Melpa release `20160113.1407` I'm seeing a lot of apparently harmless but annoying warnings in the echo area/messages buffer:

```
cancel-timer: Wrong type argument: timerp, nil
cancel-timer: Wrong type argument: timerp, nil [2 times]
error in process sentinel: cancel-timer: Wrong type argument: timerp, nil
error in process sentinel: Wrong type argument: timerp, nil
```

It happened when I was: changing branches through `magit-show-refs-popup`, running the `magit-refresh` command and typing `F u` to fetch changes from upstream.

**Comment by lvguowei** [comment]
the same happened to me when I do fetching from a branch.

**Comment by tarsius** [comment]
Did you restart Emacs after the update?

**Comment by flamingbear** [comment]
+1  `Magit 20160114.343, Git 2.6.4, Emacs 24.5.1`




```
Debugger entered--Lisp error: (wrong-type-argument timerp nil)
  signal(wrong-type-argument (timerp nil))
  cancel-timer(nil)
  auto-revert-buffers()
  magit-auto-revert-buffers()
  magit-refresh()
  magit-run-git("checkout" "master")
  magit-visit-ref()
  call-interactively(magit-visit-ref nil nil)
  command-execute(magit-visit-ref)
```
