### ISSUE TITLE
Error in post-command-hook after ":e" a file under a non-existing directory in evil-mode

### ISSUE THREAD

**Issue by zhangkun83** [magit/magit#2493]
I am using magit with evil-mode.

Under a git-managed directory, if I try to open a file under a __non-existing__ directory with the vim `:e` command, I get an error like this:
```
Error in post-command-hook (magit-auto-revert-mode-check-buffers):
(file-error "Setting current directory" "no such file or directory"
"/home/zhangkun/projects/grpc/non-exist-directory/")
```

From this point, I cannot enter any `C-x`, `M-x` or vim `:` commands, on any buffer. Each attempt would raise the above error. I can only get out of it by creating the directory or kill emacs from outside.

**Comment by zhangkun83** [comment]
Thanks for the quick response. I tried the latest version that contains your fix, but it doesn't make any difference.

**Comment by tarsius** [comment]
I reverted my previous attempt at fixing this and added another. I am not sure whether the first isn't also required, so please let me know if you still experience problems after this.

**Comment by zhangkun83** [comment]
The bug is fixed at HEAD. Thanks!
