### ISSUE TITLE
Suspicious message when setting upstream of a branch

### ISSUE THREAD

**Issue by mrkkrp** [magit/magit#2494]
To reproduce:

1. Create a new branch.

2. <kbd>b u</kbd> to set its upstream.

3. From proposed options, choose `origin/my-new-branch` (or probably it doesn't really matter).

4. Note that there is a message in the echo area:

   > magit-insert-push-branch-header: Wrong type argument: stringp, nil

   And status buffer is not refreshed.

**Comment by tarsius** [comment]
I have pushed a fix. Thanks for reporting!

**Comment by mrkkrp** [comment]
Actually it's worse than that — status buffer doesn't work anymore (it doesn't display list of diffs at all).

**Comment by mrkkrp** [comment]
Ah, great to know!
