### ISSUE TITLE
Feature request: surface git errors in a foreground buffer

### ISSUE THREAD

**Issue by dcorking** [magit/magit#2498]
Would it be practical to surface git errors that magit doesn't otherwise handle?  For example, when I tried to commit, git failed but magit didn't tell my why it didn't make a commit message buffer. I had to remember to hit `$` to see the process buffer:
```
128 git … commit --
fatal: Unable to create '/home/david1/workspace/curve/.git/index.lock': File exists.

If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue.
```

This could slow down or frustrate new users (or forgetful users like me.)

Could we make the git stderr show up in the minibuffer or in a popup?

**Comment by tarsius** [comment]
The error messages already show up in the echo area as well as at the top of the status buffer. You might have to update Magit. Now might be a good time to do that - I just created a new release.

**Comment by dcorking** [comment]
:+1: It as though you had a time machine that anticipated my request.
