### ISSUE TITLE
git send-email support

### ISSUE THREAD

**Issue by zabbal** [magit/magit#2499]
The magit already looks like one-stop-shop for all my git activities... except for sending patches to mailing list for review (which is pretty common activity among open source contributors). Would be nice if I could call popup or function equivalent to "git send-email -4" or smth like that (with all the niceties like selection of multiple commits etc). It would be especially handy cause if I'd like to write cover letter before sending my patch series than I've got to call emacsclient anyway.

**Comment by kyleam** [comment]
This is planned for 3.1.0 (see #1800).

**Comment by tarsius** [comment]
@kyleam I believe you implemented basic support for this at one point. Do you still have that laying around? If so, then I might add it to the `magit-rockstar` package (which I use for minimal viable implementations I don't want to make any promises about).

**Comment by kyleam** [comment]
No, I haven't worked on send-email support.  Are you thinking of
@andschwa's work on #1747?  Or perhaps my #2125, which is just about
format-patch?

[I do use `git send-email` from the command-line frequently enough that
I considered volunteering when you asked for someone else to look into
it (in #1800), but I haven't really thought about what a Magit
implementation would look like.]
