### ISSUE TITLE
add concise walkthrough tutorials

### ISSUE THREAD

**Issue by zabbal** [magit/magit#2500]
The magic manual is impressive and definitely worth time I've spent reading it. However, it would be nice to have small, easy to read tutorial (or set of those actually) dealing with particular workflow based on typical user's case studies.

For instance:
1. Regular developer: clone, make a feature branch, push it to upstream, make couple of changes, rebase it on master which have changed in a meantime, squash couple of commits, use send-email to send patches for review.
2. Maintainer: walk through use of git-am, merging from feature branches, pruning old branches etc.
3. GNU/Linux kernel hacker: walk from cloning kernel all the way till your patch in LKML.
4. Something else which I've never used but it's absolute must-have for some people.

Some of this is already covered in "getting started" section but it's too brief and does not cover all things mentioned above.

**Comment by tarsius** [comment]
I intended to write such a tutorial about "branching" before releasing v2.4, but I just couldn't get myself to do it. Writers block I guess.

Eventually I intend to write such tutorials - after all I *just* created a blog for that purpose (mostly).

But that shouldn't keep *others* from describing *their* favorite workflows *now*.

**Comment by tarsius** [comment]
I am closing this like all "there has to be more documention/tests/..." issues. If I did not close such issues then they would be open forever as there won't ever be documentation and tests for everything.

That doesn't mean that I am not aware of such issues, or don't intend to put time into addressing them. But I don't need a reminder for that.
