### ISSUE TITLE
git flow support

### ISSUE THREAD

**Issue by zabbal** [magit/magit#2501]
I don't mean that magit got to wrap actual "git flow" command but the branching model described in https://github.com/nvie/gitflow looks pretty interesting and rather widespread so it might be good idea to add various missing bits and pieces (including corresponding tutorial!) which are necessary to implement it from within magit.

**Comment by tarsius** [comment]
There already exists a wrapper around gitflow: [magit-gitflow](https://github.com/jtatarik/magit-gitflow).  Implementing support for this workflow and/or similar workflows directly in Magit is an option I am considering too.

But actually my focus is a different one at the moment. The primary focus is to take a break. The second is to perform the refactorings that are necessary to improve performance. Third is to polish existing features (bug fixes and things like better defaults for completion). Adding support for things that aren't supported at all yet is very low priority right now.

**Comment by zabbal** [comment]
Thanks for the link - that should do it till magit 7.3 or whenever you've got time and desire for this :)

**Comment by tarsius** [comment]
I would guess `v3.2` or `v3.3` :-)

**Comment by tarsius** [comment]
Closing this because (1) gitflow support already exists as a third-party extension, (2) I intend to implement **something like** gitflow eventually, not necessarily something that is fully compatible, (3) that won't happen for quite some time, and while it is somewhat likely that it will (4) I don't promise anything.
