### ISSUE TITLE
with-editor version problem

### ISSUE THREAD

**Issue by MerlinDMC** [magit/magit#2504]
```
--> installing package: magit@git... [1/13]
An error occurred while installing magit (error: (error Need package ‘with-editor-20160119’, but only 20160118.635 is available))
--> installing package: git-commit@git... [6/13]
An error occurred while installing git-commit (error: (error Need package ‘with-editor-20160119’, but only 20160118.635 is available))
```

We're hitting the version miss match again.

**Comment by tarsius** [comment]
See #2497, which happens to have the exact same title as the issue you just opened.

**Comment by tarsius** [comment]
Ah, I see you realized that. Guess I keep it open for a while.

**Comment by tarsius** [comment]
The part which is still relevant starts here: https://github.com/magit/magit/issues/2497#issuecomment-172621312.

**Comment by tarsius** [comment]
All dependencies are up to date now.
