### ISSUE TITLE
magit-refresh touches all open buffers, including tramp connections

### ISSUE THREAD

**Issue by ndimiduk** [magit/magit#2505]
This behavior is particularly annoying when offline or, for instance, disconnected from the VPN. Hitting 'g' in a magit buffer for a local repo effectively freezes while the tramp process attempts to reestablish a non-existent connection. Maybe it can be a little smarter about which buffers it examines?

**Comment by tarsius** [comment]
Try setting `magit-auto-revert-immediately` to `nil`.  Provided that file notifications can be used, the reverts should still be near immediate (except probably for files visited over Tramp).

**Comment by tarsius** [comment]
I'll probably have to redefine `auto-revert-buffers` to properly address this.

**Comment by tarsius** [comment]
Please try  #2513 with `(setq auto-revert-buffer-list-filter 'magit-auto-revert-repository-buffers-p)`.
