### ISSUE TITLE
with-editor should depend on saveplace

### ISSUE THREAD

**Issue by hyperair** [magit/magit#2508]
Attempting to commit was consistently failing with the error message:

    Symbol's function definition is void: toggle-save-place

This snippet works around it nicely:

    (autoload 'toggle-save-place "saveplace")

**Comment by tarsius** [comment]
Nowhere in `with-editor.el` (or `git-commit.el`) is this function being called. Maybe it was at some point, so make sure you are using the latest version. Or maybe you yourself have added a function to a relevant hook which does call `toggle-save-place`.

However the variable `save-place` is being set to `nil`, but only if it is defined. In `git-commit.el` we have to make sure that saved places are *not* being restored. `with-editor` doesn't care whether point is restored - its users `git-commit and `git-rebase` have to make sure it is not, but other users of `with-editor` might want point to be restored.

**Comment by tarsius** [comment]
I.e. no it should not.

**Comment by hyperair** [comment]
You're right, I grepped around a bit in my dotfiles, and found it in git-commit-mode-hook. Sorry for the noise.
