### ISSUE TITLE
After pull hook

### ISSUE THREAD

**Issue by jtamagnan** [magit/magit#2509]
What would people think about having a hook to be run after a successful pull?

**Comment by tarsius** [comment]
What do you want to use that for? Would using Git's `post-commit` work too?

**Comment by jtamagnan** [comment]
There are some files that I would like to move to a different directory immediately after puling from upstream. I can also see this being useful if you know that you will be running a certain set of commands immediately after pulling. For example perhaps if you are puling from the emacs repository you know that you will want to build it immediately after pulling. Or perhaps it could allow for tracking of the last time you pulled.

**Comment by tarsius** [comment]
Well yes, but wouldn't it be better do do these things in a shell-script instead of blocking Emacs?

**Comment by jtamagnan** [comment]
Well ideally yes, I just didn't think there was a post-pull hook. After further investigation I realize that the post-merge hook is run after after any file is changed after a pull. Thank you for your help and sorry for the trouble.
