### ISSUE TITLE
Issues with Elpa archives

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2510]
* Melpa (non-stable) uses timestamps as version strings. Unfortunately that means that a package cannot depend on (at least) a particular version of a dependency, and expect that to be automatically installed for all users. For example, the timestamp of `0.0.1` might be `20150101.666`, which would always be larger than say `2.0`.

  The Melpa maintainers recommend that users update all packages at once, as that bypasses this issue. That's good advice - unfortunately there is no way to make sure that users actually do that.

  I work around this by depending on different "versions" in releases and during development. When I create a release, then I change all dependencies to actual versions for the sake of Melpa-stable. I then commit and tag that. In the very next release I change the "versions" back to date snapshots for the sake of Melpa (non-stable).

  Unfortunately that triggers another problem: Melpa builds packages in alphabetic order and the packages build from the `magit` repository (`with-editor`, `git-commit`, `magit-popup`, and `magit`) are distributed across the alphabet quite evenly. That combined with my version hack means that Magit stops being installable  from Melpa (non-stable) for a few hours after every release, until all of these packages have been rebuild.

* With Marmalade there is a new issue every time I try to make a release. For example the `2.4.0` and `2.4.1` tarballs were too large. I had to remove the manual to be able to upload. I would not have bothered, but the uploads of the other packages `with-editor`, `git-commit`, and `magit-popup` had already succeeded, making it impossible to install a functioning `magit` from Marmalade.

  The main issue however is that Nic does not seem to care anymore. It's very hard to get him to reply and when he does, then it's usually after a long delay. Also I think that Marmalade is effectively dead. Other maintainers are also affected by Nic's slow response times. For example there are currently two dozen people waiting for him to create them an account, so that they can upload their packages.

But I don't wanna whine. Just thought I would give you a status report. I also think that Steve and Donald do a wonderful job maintaining Melpa. And they are open to the idea of changing the version numbering scheme - they just requested that someone else implements it. Unfortunately nobody has volunteered to do so yet. It's understandable they don't want to do it themselves; from my work on the Emacsmirror I know how much work it is to even just keep things going and to add new packages. Actually I was planing on blogging about the Emacsmirror and releasing some tools related to that soon, but I might delay that to instead try to give the Melpa folks a hand with implementing a better version numbering scheme, as outlined in https://github.com/milkypostman/melpa/issues/2955.

I cannot additionally take over Marmalade. I don't even personally use `package.el`! But improving Melpa's version numbering scheme should not be more work in the long run, than to keep on adding hacks to Magit and closing duplicated "with-editor-YYYYMMDD.SSS" isn't available" issues.

**Comment by syl20bnr** [comment]
Thank you for the summary of the situation.

This is not the greatest thing but at Spacemacs level I can add a protection against this by checking that all dependency constraints are satisfied before actually updating a package. It should be rather easy to do by reading the ELPA repository archive and it should work for the specific Magit case, this is not a silver bullet since it still can break with shared dependencies but if I can contribute a little bit to reduce the number of opened Magit issues when it happens I will be happy to help at my scale. The error message when a dependency issue is detected can be something like

> "Dependencies requirements for X package are not met, wait a few hours for them to be available on MELPA. You still can open on issue on the Spacemacs issue tracker on Github".  

Of course it can be implemented at the `packages.el` level but in a first step I guess I can do it in Spacemacs and see how it goes. At some point I will try to contribute to Emacs a bit.

**Comment by syl20bnr** [comment]
It makes me think that if MELPA just wait the end of an update iteration to update the archive it can solve your specific issue.

**Comment by tarsius** [comment]
> Actually I was planing on blogging about the Emacsmirror and releasing some tools related to that soon, but I might delay that to instead try to give the Melpa folks a hand with implementing a better version numbering scheme, as outlined in milkypostman/melpa#2955.

I have decided to inverse that.

In the short run I will either stop bumping all versions at the same time or at least not bump the dependencies. In the second case releasing `magit-n` would continue to result in the release of `{with-editor,git-commit,magit-popup}-n`, but if the changes in these releases are minimal, then I can continue to depend on `{with-editor,git-commit,magit-popup}-(n-1)`.
