### ISSUE TITLE
forced push

### ISSUE THREAD

**Issue by zabbal** [magit/magit#2511]
I'd like to have an option to run "git push --force" from magit.

My use case looks as follows: I create feature/topicXXX branch (both locally and in the repo) based on current master. I work on it, do implementation and some bugfixing (1) later on. While I do so, master branch moves forward, so I have to rebase my work on top of it periodically.

The net result of my work is set of patches I sent to mailing list. The branch is essentially for me to keep track of current work and for some automated test tools.

In case of 1) I've got to make r i     (magit-rebase-interactive), in case 2) r e     (magit-rebase)

Both produce set of commits which cannot be pushed via P u     (magit-push-current-to-upstream) because of divergence. The workaround I use right now is to run "git push --force" from console to enforce history rewrite, but of course I would rather not switch away from magit.

**Comment by kyleam** [comment]
There's a `--force-with-lease` switch in the push popup.
