### ISSUE TITLE
Stashes are lost in worktrees.

### ISSUE THREAD

**Issue by tvaughan** [magit/magit#2515]
When I run `M-x magit-stash` in a [worktree](https://git-scm.com/docs/git-worktree), the stash - all of my blood, sweat, and tears -  is lost. However, `git stash` on the command-line works.

**Comment by tvaughan** [comment]
Magit v2.4.1, Git 2.7.0, Emacs 24.5.1. Mac OS X El Capitan.

**Comment by tarsius** [comment]
I found the problem and will probably push a fix today.

Meanwhile you can create stashes in worktrees, provided that another stash already exists.

**Comment by tarsius** [comment]
By the way, the stash commits were properly created, they just weren't stored anywhere. So you should still be able to find the lost changes somewhere among the dangling commits.

**Comment by tvaughan** [comment]
Awesome. Thanks @tarsius for the quick response!

**Comment by tarsius** [comment]
I've pushed the fix.

**Comment by tvaughan** [comment]
Works for me in the latest v2.5.0 release. Thanks!
