### ISSUE TITLE
Error with uniquify

### ISSUE THREAD

**Issue by thierryvolpiatto** [magit/magit#2516]
Hi when not using uniquify, i.e `uniquify-buffer-name-style` is nil, magit fails to create buffer.
Perhaps you should test with:

``` elisp
    (when (and magit-uniquify-buffer-names
               uniquify-buffer-name-style)
``` 
in `magit-generate-new-buffer`.

Of course, if I set `magit-uniquify-buffer-names` to nil I have no error.

Thanks.

**Comment by tarsius** [comment]
Thanks. I've pushed a fix.
