### ISSUE TITLE
resetting branch to HEAD~ should not error on setting upstream

### ISSUE THREAD

**Issue by anders-memsql** [magit/magit#2517]
from `b x <Enter> HEAD~ <Enter>`

the magit-process buffer reads
```
  0 git … reset --hard HEAD~ --
HEAD is now at 9f5de69 Removes old entries from codegen_fallback blacklist

128 git … branch --set-upstream-to=HEAD~ keycolsset
fatal: Cannot setup tracking information; starting point 'HEAD~' is not a branch.
```
if HEAD~ isn't a branch the second command should be skipped/silenced

magit-version is 2.3.0

**Comment by npostavs** [comment]
> magit-version is 2.3.0

With latest `master` 707540eaea7a90bd9215722ffa97133e83e01ee5, `b x HEAD~ <Enter>` tells me `[no match]` and no git commands are run.

**Comment by anders-memsql** [comment]
@npostavs I misreported the sequence, which I've corrected above. The error comes from

`b x <Enter> HEAD~ <Enter>`

**Comment by tarsius** [comment]
As @npostavs said, in other words, this has already been fixed, please update Magit.

**Comment by npostavs** [comment]
Hold on, doing `b x <Enter> HEAD~ <Enter>` I do get a ``GitError! Git failed  [Type `$' for details]``, although there aren't many details:

```
  0 C:/Git-2.x/mingw64/libexec/git-core/git … reset --hard HEAD~ --
HEAD is now at 7658820 magit.org: minor improvements and typo fixes

  1 C:/Git-2.x/mingw64/libexec/git-core/git … config branch.foo.remote
  0 C:/Git-2.x/mingw64/libexec/git-core/git … config branch.foo.merge refs/heads/
```

**Comment by tarsius** [comment]
Hm... there's something fishy indeed.

**Comment by npostavs** [comment]
I think `(magit-set-branch*merge/remote branch to)` should only be called when `(magit-branch-p to)`.

**Comment by tarsius** [comment]
Just came to the same conclusion. I'll push a fix.

I also think this behavior should be optional, and probably not even the default:

> When resetting to another branch, then also set that branch as the upstream of the branch being reset.

I'll also add an option for that.
