### ISSUE TITLE
feature request - support soft reset

### ISSUE THREAD

**Issue by anders-memsql** [magit/magit#2518]
for example

`git reset HEAD~`

doesn't appear to currently be exposed through the magit interface, so I have to drop back to the command line if I want to do this.

magit version is 2.3.0

**Comment by tarsius** [comment]
As [described in the manual](http://magit.vc/manual/magit/Resetting.html), the command to do that is named `magit-reset-soft`. No key is bound to it by default, you'll have to find a suitable binding yourself or use `M-x`.

**Comment by npostavs** [comment]
> for example
> 
> `git reset HEAD~`

That is actually mixed reset, which is bound to `x`.

**Comment by tarsius** [comment]
Indeed.
