### ISSUE TITLE
`magit.texi` mentions non-existent variable `magit-insert-status-headers`

### ISSUE THREAD

**Issue by oscarfv** [magit/magit#2519]
I guess that the correct one is `magit-status-headers-hook`.

**Comment by npostavs** [comment]
It mentions the *function* `magit-insert-status-headers`. Or is there somewhere that claims it is a variable?

**Comment by oscarfv** [comment]
Oh, you are right. I was looking for `magit-status-headers-hook` and somehow expected to see it there.

Sorry for the noise
