### ISSUE TITLE
format patches with cover letter

### ISSUE THREAD

**Issue by zabbal** [magit/magit#2521]
A rather common [1] workflow is to format patch series with cover letter describing all the patches. This can (almost) be done from magit, however there are couple of improvements possible:
1) It seems like right now magit does not have an option to add cover letter to the patch series (at least I have not found one after pressing W).
2) I did not find a way to specify just ref (like origin/master for example) for which to make a patch series so (ma)git would figure out number of patches automatically.

Would be nice if after checking cover-letter option in W popup I'd be directed straight to editing patch 0000-* in output directory so I could write it up without leaving emacs/magit - the same way it currently works for commit messages.

[1] https://git-scm.com/docs/git-send-email - see example

**Comment by kyleam** [comment]
> 1) It seems like right now magit does not have an option to add cover
> letter to the patch series (at least I have not found one after
> pressing W)

This has been requested a few times.  You can add this yourself for
now.  #2512

> 2) I did not find a way to specify just ref (like origin/master for
> example) for which to make a patch series so (ma)git would figure
> out number of patches automatically

You can specify the range you want (e.g., origin/master..) or, before
pressing W, can mark commits with a region. (Related: #2125)

> Would be nice if after checking cover-letter option in W popup I'd
> be directed straight to editing patch 0000-* in output directory so
> I could write it up without leaving emacs/magit - the same way it
> currently works for commit messages

Isn't this the same as your request in #2499?

**Comment by tarsius** [comment]
> This has been requested a few times. 

So often that I have decided to just add it.

> Would be nice if after checking cover-letter option in W popup I'd be directed straight to editing patch 0000-*

And that too.

**Comment by zabbal** [comment]
> Isn't this the same as your request in #2499?

Not entirely - #2499 is about firing git send-email (as external command) or sending email(s) via mu4e or some other email client.

This one is about extending patch formatting. Technically, #2499 does not even depend on this feature request because not all the use cases require writing separate cover letter for patch series.
