### ISSUE TITLE
Stashing is likely broken after recent magit update 

### ISSUE THREAD

**Issue by geraldus** [magit/magit#2522]
Hi folks!  Thank you for such great and handy plugin!

I've updated my magit today, now when I'm trying to stash changes I see this message in mini-buffer
```
Invalid version syntax: '2.5.4 (Apple Git-61)'
```

```
GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org

magit              20160126.1546 installed
magit-popup        20160119.1409 installed

 ```

**Comment by tarsius** [comment]
Please restart Emacs. Do you now get that error at the time magit is loaded?

**Comment by tarsius** [comment]
What does `M-x magit-version` print?

**Comment by tarsius** [comment]
Never mind, the above commit should do the trick.

**Comment by geraldus** [comment]
Thank you!
