### ISSUE TITLE
error when magit-completing-read-function customized to helm-completing-read-with-cands-in-buffer

### ISSUE THREAD

**Issue by glyph** [magit/magit#2525]
1. `M-x customize-variable RET helm-completing-read-function RET`
2. select `helm-completing-read-with-cands-in-buffer`, the 3rd option presented
3. `M-x magit-status RET`
4. `m` `m`
5. 
```
(wrong-number-of-arguments (10 . 10) 7)
  helm-completing-read-with-cands-in-buffer("Merge: " ("dornkirk/master" "dornkirk/other" "elfa/master" "fermion/master" "rem/master" "splinter/master" "vetinari/master" "vimes/master" "windows/master") nil nil nil magit-revision-history #("splinter/master" 0 15 (face magit-branch-remote)))
  magit-completing-read("Merge" ("dornkirk/master" "dornkirk/other" "elfa/master" "fermion/master" "rem/master" "splinter/master" "vetinari/master" "vimes/master" "windows/master") nil nil nil magit-revision-history #("splinter/master" 0 15 (face magit-branch-remote)))
  magit-read-other-branch-or-commit("Merge")
  byte-code("\301\302!\303 E\207" [current-prefix-arg magit-read-other-branch-or-commit "Merge" magit-merge-arguments] 3)
  call-interactively(magit-merge)
  magit-invoke-popup-action(109)
  call-interactively(magit-invoke-popup-action nil nil)
  command-execute(magit-invoke-popup-action)
```

**Comment by kyleam** [comment]
I don't think you need to anything special on Magit's side to use helm completion, provided you've called `(helm-mode 1)`.

**Comment by glyph** [comment]
If that's the case, perhaps this option should not be presented as a predefined customization option?

**Comment by kyleam** [comment]
Agreed.  Later tonight I'll take some time to look into your error and whether option/documentation should be updated.

**Comment by tarsius** [comment]
Not that many Helm users would want that, but it is possible to use Helm completion selectively without turning on `helm-mode`. At some point `helm-completing-read-with-cands-in-buffer` apparently was the right function for that because it used to have the same signature as `completing-read`. Now that it no longer does, `helm-completing-read-default-1` seems to be the best choice. But we should probably also mention `helm-mode` in `magit-completing-read-functions`'s doc-string.

**Comment by glyph** [comment]
I definitely use helm that way. As a result of this discussion I'm giving `(helm-mode t)` a try, but helm has a lot of trouble with general-purpose filename completion.

**Comment by tarsius** [comment]
Please also try `helm-completing-read-default-1` a try.
