### ISSUE TITLE
magit-status throws error Symbol nil may not be buffer-local

### ISSUE THREAD

**Issue by robbyoconnor** [magit/magit#2532]
#### Reproduction guide
- Start Emacs
- have `magit` installed
- do`M-x magit-status`

*Observed behaviour:*
Throws an error `Symbol nil may not be buffer-local`

*Expected behaviour:*
`magit-status` screen should show or the helm and/or ivy popup should come up to select the VCS root.

#### System Info
- OS: gnu/linux
- Emacs: 24.4.1
- Spacemacs `develop` branch -- I was using ivy but switched back to helm to check if that was the case. 

#### Backtrace 
```
Debugger entered--Lisp error: (error "Symbol nil may not be buffer-local")
  make-local-variable(nil)
  hack-one-local-variable(nil nil)
  hack-local-variables-apply()
  hack-dir-local-variables-non-file-buffer()
  magit-mode()
  magit-status-mode()
  magit-mode-setup(magit-status-mode)
  magit-status-internal("~/.spacemacs.d/")
  magit-status(nil)
  call-interactively(magit-status nil nil)
  command-execute(magit-status)
```

**Comment by robbyoconnor** [comment]
I reported this to spacemacs as https://github.com/syl20bnr/spacemacs/issues/4875

**Comment by kyleam** [comment]
It looks like somewhere `(nil nil)` is being added to `file-local-variables-alist`. I don't think this is on Magit's end.

**Comment by robbyoconnor** [comment]
I figured it couldn't hurt to bring it up -- did something change in `magit`?

**Comment by kyleam** [comment]
I don't think the code path in your backtrace has changed recently.  What value do you see for file-local-variables-alist before you call magit-status?  Are you setting up any local variables?  Is the error happening for all repos?

**Comment by robbyoconnor** [comment]
It seems to be happening elsewhere in Spacemacs, so I don't think it's in `magit` -- but somewhere in spacemacs...I've never dug deep into the core of it
