### ISSUE TITLE
Improve order of GUI sections

### ISSUE THREAD

**Issue by floli** [magit/magit#2533]
Hello,

when I push b magit-branch-popup appairs:

```
Configure existing branches
 d branch.parallelRBF_i1.description unset
 u branch.parallelRBF_i1.merge       refs/heads/parallelRBF_i1
   branch.parallelRBF_i1.remote      origin
 r branch.parallelRBF_i1.rebase      [true|false|default:false]
 p branch.parallelRBF_i1.pushRemote  [origin|peter]

Configure repository defaults
 M-r pull.rebase        [true|false|default:false]
 M-p remote.pushDefault [origin|peter]

Configure branch creation
 U branch.autoSetupMerge  [always|true|false|default:true]
 R branch.autoSetupRebase [always|local|remote|never|default:never]

Actions
 c Create and checkout    b Checkout
 n Create                 m Rename
 s Create spin-off        x Reset
                          k Delete

Common Commands
 C-c C-c Set defaults       C-h i View popup manual    C-t Toggle this section
 C-x C-s Save defaults      ?     Popup help prefix    C-g Abort
```
for me the ordering appears not optimal.
On top are three configuration sections, something you probably do not need very often. On the very bottom is the common section, also not needed too frequently. Somewhere in the middle are the Actions, what is I am looking for most of the time. You usually start scanning a window from top. The same applies to a lot of other popups (merge, stash).
I would suggest moving the Action section to top.

**Comment by kyleam** [comment]
I know that your main suggestion is about the top portion, but regarding the bottom part that you also mention, you can remove that by setting `magit-popup-show-common-commands` to nil.

**Comment by npostavs** [comment]
I've been thinking that it might be better to move the branch configuration to a separate (nested?) popup, partly because all the options are a bit noisy, and also because on Windows querying the config options takes just long enough to make opening the branch popup annoying (around 50-100 ms, I guess).

**Comment by floli** [comment]
This ordering (actions, i.e. what you mostly look at, are at the bottom or inbetween) are also at the popups for stash, commit and merge.

**Comment by tarsius** [comment]
The actions in *all* popups are at the bottom and I think that makes sense because the minibuffer is at the bottom too. I do not intend to change that.

**Comment by tarsius** [comment]
> I've been thinking that it might be better to move the branch configuration to a separate (nested?) popup,

Might be a good idea, but should probably be opt-in to avoid upsetting any muscle memory. If we decide to go with a nested popup, then we should probably also make it available from the push popup.
