### ISSUE TITLE
Feature request: Commit messages in helm for magit-checkout

### ISSUE THREAD

**Issue by Peeja** [magit/magit#2536]
I don't know a lot about how this is implemented, so this may be too much to ask for, but when using helm to select a branch with `magit-checkout` (or with several other command, but especially `magit-checkout`), it would be great to see the commit message (and maybe a bit more metadata, if it fits) of the commit for each branch displayed.

**Comment by tarsius** [comment]
Magit itself is not the right place to implement this. It should go into a separate, non-official package, which is maintained by someone else.

**Comment by Peeja** [comment]
Ah, that makes sense. Thanks!
