### ISSUE TITLE
Use libgit2 in addition to git plumbing and porcelain

### ISSUE THREAD

**Issue by fommil** [magit/magit#2539]
This has the potential to speed up performance on Windows considerably.

But obviously a huge undertaking.

**Comment by npostavs** [comment]
Mentioned at https://github.com/magit/magit/issues/2442#issuecomment-165093660 and https://github.com/magit/magit/issues/1327#issuecomment-39678570, but I don't see this happening any time soon.

**Comment by fommil** [comment]
@npostavs yes, I know, but now seems like a good time to be discussing what will be in the roadmap for 3.0. This is something I may be interested in helping with as it impacts my day to day a **lot**.

**Comment by fommil** [comment]
just for completeness, this won't speed up everything in git: there is still a need for https://github.com/git-for-windows/git/issues/596 to be implemented via a C or perl/libgit rewrite of the shell script. That should , however, be independent of any work in magit.

**Comment by tarsius** [comment]
> This is something I may be interested in helping with as it impacts my day to day a lot.

Maybe you could look into the upcoming ffi interface and create an Emacs C module that wraps `libgit`. That would be a very useful contribution.

**Comment by fommil** [comment]
cool! Thanks for the pointer. What is the minimal set of APIs that would give some benefit? I'm primarily concerned with speeding up the screens that show lots of info, like the status. Rebasing and so on is just fundamentally slow on Windows, so it won't benefit.

**Comment by tarsius** [comment]
> What is the minimal set of APIs that would give some benefit?

It compiles and there is one function that can be called to prove that something happens. :-)

"Raw" log and diff would probably be most useful.

> I'm primarily concerned with speeding up the screens that show lots of info, like the status.

And functions that could replace calls to `git rev-parse` and such would be useful. That would probably go a long way towards mitigating the Windows-specific slowness.

**Comment by fommil** [comment]
nice! I have a few other bits of firefighting to do on windows at the moment so I'll come back to this in a few weeks (it's insane... a process holding a file handle means that no other process can delete that file. There isn't even a way to force it.)

**Comment by fommil** [comment]
I don't think this is possible from a legal point of view. git is GPLv2 (incompatible with GPLv3 of Emacs) https://github.com/git/git/blob/master/COPYING and I don't believe that libgit can claim to be MIT https://github.com/libgit2/libgit2.github.com/issues/66 their website also says "GPLv2 with Linking Exception." but I don't see how they are allowed to do that without the permission of all git contributors.

**Comment by fommil** [comment]
crisis averted, looks like they have gone to some efforts to get contributors to re-license their work.

**Comment by npostavs** [comment]
> crisis averted,

Their crisis is averted, but for Emacs there is still the GPLv2 vs GPLv3 problem, right?

**Comment by fommil** [comment]
@npostavs no, because it is GPLv2 with classpath exception it means we can dynamically link to it from GPLv3 code as if it were a system library.

**Comment by npostavs** [comment]
Oh, I thought the exception was only for static linking. Carry on then.

**Comment by ksjogo** [comment]
@fommil did you start working on it? I was recently forced to move to windows, and would be interested in helping with the module.

**Comment by fommil** [comment]
@ksjogo no, it's been in my TODO list for a long time but other things keep getting in the way :cry:

**Comment by ksjogo** [comment]
Ok, I will look into it then.

**Comment by ksjogo** [comment]
Starting here: https://github.com/ksjogo/emacs-libgit2
Module is loading, libgit2 init working and I can get back the current branch name. Yeah.

@tarsius What would be the best places in the beginning to patch a direct integration into magit for better speed? Just checking were rev-parse is used?

**Comment by ksjogo** [comment]
Modules are only supported with 25, yes. At the moment I am only running it again a locally compiled cygwin emacs. But *should* work on GNU/Linux as well.
Will add some actual commands in the next days.

**Comment by tarsius** [comment]
Thanks for working on this!

> What would be the best places in the beginning to patch a direct integration into magit for better speed?

That and querying Git variables would be a useful start.

**Comment by tarsius** [comment]
Closing in favor of #2959.
