### ISSUE TITLE
Magit status taking around 45 seconds on first load

### ISSUE THREAD

**Issue by AlexChesters** [magit/magit#2540]
This is a strange one that's just started occurring within the past few days.

Whenever I first launch emacs and run `magit-status`, it takes around 45 seconds to do anything, preventing any interaction with emacs during this. (before it shows the `magit-status` buffer, which I can then interact with as normal). After that first launch, all subsequent `magit-status` behave as normal.

**Comment by npostavs** [comment]
Sounds like http://magit.vc/manual/magit/Emacs-245-hangs-when-loading-Magit.html

Maybe something changed with your DNS setup, or else you updated to Emacs 24.5?

**Comment by AlexChesters** [comment]
That would make sense actually @npostavs given that it only happens when I'm at home and not at work, I'll check my home DNS settings when I'm next home

**Comment by tarsius** [comment]
If that's not it, then please let us know.

**Comment by AlexChesters** [comment]
Apologies, that was indeed the issue. Thanks for helping to resolve! :-)
