### ISSUE TITLE
Default for branch upstream

### ISSUE THREAD

**Issue by ivan-m** [magit/magit#2543]
When pushing to upstream (using `P u`) for the first time, you're asked for the branch to be considered "upstream".  As I tend to branch from my local master, the default selection for this tends to be `master`, with `origin/<branch name>` second.

Is it possible to make the `origin/<branch name>` option appear first?  I've had a couple of times when I've accidentally hit Enter and chosen `master` as the upstream, which then required me to edit `.git/config` (as I couldn't find any way of changing/resetting it within magit).

**Comment by kyleam** [comment]
> Is it possible to make the origin/<branch name> option appear first?

You can set `magit-prefer-remote-upstream` to a non-nil value:

    Whether to favor remote branches when reading the upstream branch.

    This controls whether commands that read a branch from the user
    and then set it as the upstream branch, offer a local or a remote
    branch as default completion candidate, when they have the choice.

    This affects all commands that use `magit-read-upstream-branch'
    or `magit-read-starting-point', which includes all commands that
    change the upstream and many which create new branches.

For support questions, please use one of the channels listed in the [README](https://github.com/magit/magit#support).

**Comment by ivan-m** [comment]
Sorry, I must have missed that option when searching through the config settings.  I had tried checking the manual and searching the web to no avail.

**Comment by ivan-m** [comment]
As it stands, this doesn't do what I want anyway: after creating a branch, it defaults to `origin/master` being the upstream rather than `origin/<name of branch>`.

**Comment by kyleam** [comment]
> As it stands, this doesn't do what I want anyway: after creating a
> branch, it defaults to origin/master being the upstream rather than
> origin/<name of branch>.

Sorry, I didn't read your question closely enough.  You can set
`magit-push-current-set-remote-if-missing` to nil (make sure you do
this *before* Magit is loaded) and then set the upstream on pushing
with `P-ue`.

> which then required me to edit .git/config (as I couldn't find any
> way of changing/resetting it within magit).

You can change the upstream with `bu`.

**Comment by kyleam** [comment]
Also, you might consider just setting origin/<branch name> as the pushRemote when pushing with `Pp`.

**Comment by JasonMFry** [comment]
@kyleam This issue is the second result for me when searching how to do this, so I'm sorry to revisit this but hopefully it will help others.

I'd like new branches to have their upstream set automatically to `origin/<branch_name>` instead of `origin/master`, even when the branch starts at `origin/master`. I think that's what the OP was asking. Is this possible in 2021?

In other words, 
1. `M-x magit-branch-create`
2. Create branch starting at: `origin/master`
3. Name for new branch: `fry/107/add-cool-thing`

would result in a local branch `fry/107/add-cool-thing` whose upstream is `origin/fry/107/add-cool-thing`

**Comment by tarsius** [comment]
There's no support for that and maybe you don't want that anymore after reading https://magit.vc/manual/magit/The-Two-Remotes.html.

**Comment by JasonMFry** [comment]
@tarsius you're right, I don't 😄 But now I want to automatically set push remote to `origin/<branch_name>`. Is this possible?

**Comment by tarsius** [comment]
Yes and no. It comes down how it is implemented (in git). The "push-remote" is a remote, not a branch. So `origin` is a possible value, while `origin/foobar` is not. However, given a local branch named `foobar` and `origin` being set as the push-remote, then "pushing `foobar` to its push-remote" does indeed update `origin/foobar`.

You can set the push remote for all branches using `remote.pushDefault`. You can override that for a single branch using `branch.<name>.pushRemote`. This is documented in a sibling section of the one I pointed you at above. Ah and I see they are also mentioned in the node I pointed you at:

> But luckily Git has long ago gained support for a push-remote which
> can be configured separately from the upstream branch, using the
> variables ‘branch.<name>.pushRemote’ and ‘remote.pushDefault’.  So we no
> longer have to choose which of the two remotes should be used as "the
remote".

These (and other) variables can be set using `b` (`magit-branch`) or its sub-menu `b C`, which are mostly self-explanatory but are also documented in yet another sibling section. In fact it might be a good idea to read all off https://magit.vc/manual/magit/Branching.html.
