### ISSUE TITLE
inline merge conflict resolution

### ISSUE THREAD

**Issue by blaenk** [magit/magit#2544]
I'm not sure if this would be possible or desirable, but I saw [this atom package](https://github.com/smashwilson/merge-conflicts) which lets you interactively resolve a merge conflict in-line in the actual code file. I thought it was interesting so I wanted to bring it up in case it might give some ideas.

**Comment by kyleam** [comment]
At first glance, it seems like smerge offers the same functionality (with less pointing and clicking).  Does it have any major features that smerge lacks?

**Comment by blaenk** [comment]
I haven't used it, I just saw the little screencast image and thought it looked neat. Thanks for telling me about smerge, I had no idea about it. I'm gonna go learn it now :)

Feel free to close this.
