### ISSUE TITLE
magit diffs show ^Ms for dos line endings

### ISSUE THREAD

**Issue by thepickle** [magit/magit#2545]
A minor gripe, but magit is showing ^Ms for dos line-endings which have been committed to git.
Any quick way to fix this?

**Comment by thepickle** [comment]
I should note that this issue is not present in the Windows version of Emacs.. only the Linux version.

**Comment by kyleam** [comment]
Does this differ from what `git diff` shows in a terminal?  Knowing
very little about Windows, I suspect this should be dealt with by
configuring git directly (for example, one of the settings suggested
[here](http://stackoverflow.com/questions/1889559/git-diff-to-ignore-m)).

This question seems more appropriate for one of the channels mentioned
at the top of the README.

**Comment by thepickle** [comment]
The ^Ms do show in the terminal, until I do the following (in both Windows/Linux)

`git config --global core.whitespace cr-at-eol`

I'm thinking, maybe `magit` is just not noticing this flag is set, and putting the ^Ms in, as a normal `git` terminal would?

**Comment by tarsius** [comment]
See #1497. And if you need help, then ask on Stackexchange.

**Comment by thepickle** [comment]
@tarsius, 

- `echo $HOME` from emacs `shell` reports the correct `home` directory.
- `git config --global --list` shows the correct `core.whitepace=cr-at-eol` setting
- I've even tried added `"-c" "core.whitespace=cr-at-eol"` to `magit-git-global-arguments`

Nothing seems to work.
I've searched StackExchange and found a bunch of guys that suggest using `core.autocrlf` .. that's not an option for me.

Any ideas about why magit is showing me `^M` where `git` in console is not?

**Comment by tarsius** [comment]
> `echo $HOME` from emacs `shell` reports the correct `home` directory.

That is entirely irrelevant here. `shell` runs a shell subprocess such as `bash` and `bash` loads it config files regardless of whether you run it in `xterm` or `emacs`. Magit on the other hand does not run a shell, it runs `git` directly, so any shell configuration is irrelevant. Try `(getenv "HOME")` instead. Also see [this](https://github.com/magit/magit/wiki/Pushing-with-Magit-from-Windows#before-starting-set-home).

Ps: [I am on a break](http://emacsair.me/2016/02/10/magit-2.5), so you won't get anymore help from me here. Someone else might help you out though, or not. Asking on Stackexchange would probably mean that more people who could potentially help you would see your question. Which is one of the reasons why we ask users to take their support requests there.
