### ISSUE TITLE
Magit-merge-preview-mode diff parsing breaks on "added in remote"

### ISSUE THREAD

**Issue by aaron-em** [magit/magit#2546]
Specifically, it looks like the first instance of the line `added in remote` causes magit-diff-mode to stop highlighting.

Here's a screenshot example:
![magit example 1](https://cloud.githubusercontent.com/assets/5650970/12979609/3233cf08-d0a6-11e5-93d7-439ceaf25190.PNG)
The entire remainder of the diff is unhighlighted. Tab-folding hunks, RET to visit thing at point, etc., don't work, either.

Regular diff-mode doesn't seem to have the same problem:
![magit example 2](https://cloud.githubusercontent.com/assets/5650970/12979631/67ae71ec-d0a6-11e5-9856-83065775ac94.PNG)
In this case, the entire diff is highlighted correctly.

It's not that I mind doing `M-x diff-mode RET` in the infrequent case that I'm looking at a merge preview, and generally they're short enough that losing out on tab-folding et cetera isn't a real handicap.

At the moment, I don't have test cases specifically for this issue; the report is based on what I've seen in the course of using Magit. If you'd like test cases (e.g. to see whether it's only "added in remote" that breaks parsing, or whether other sorts of hunk headers do likewise), let me know, and I'll find the time. Thanks!

**Comment by kyleam** [comment]
Thanks for the report.  I can reproduce the issue.
