### ISSUE TITLE
M-x magit-clone doesn't cd into repo

### ISSUE THREAD

**Issue by bendlas** [magit/magit#2549]
Instead, there is an error message and no window shows up

**\*Messages***
```
Cloning git@github.com:**redacted**.git...
Set `remote.pushDefault' to "origin"? (y or n) y
user-error: Not inside a Git repository
```
**EDIT** Observed on `GNU Emacs 24.5.2` with `elpa/magit-20160202.2138`

**Comment by kyleam** [comment]
Thanks.  This was fixed in 8d328c5 (magit-clone: unset remote head
from within the repo, 2016-02-12).

**Comment by bendlas** [comment]
Oh, sorry for not checking, thanks for magit, I love it!

**Comment by kyleam** [comment]
> Oh, sorry for not checking

No worries.  The other report was on the mailing list, so it wasn't
even present as an issue.
