### ISSUE TITLE
Unable to push to remote repos via https

### ISSUE THREAD

**Issue by bbatsov** [magit/magit#255]
I'm using magit 1.0 with Emacs 23.3. I'm able to push to remote repos via ssh, but via https magit just hangs forever. I get no errors/messages. Older versions of magit asked me about my credentials so I assume that the problem has something to do with missing credentials.

**Comment by drozzy** [comment]
Push does nothing on windows... I am using ssh-based authentication (to github). It just hangs there.

**Comment by drozzy** [comment]
@npostavs I am not sure what that does.

**Comment by npostavs** [comment]
@drozzy: sorry for really delayed response, if you are still interested in fixing this, I have written [OpenSSH passphrase caching, via ssh-agent][1], which is an expanded version of the FAQ I linked, including some troubleshooting guidelines. Take a look and see if it helps (and if it doesn't, how can it be improved to be more helpful).

[1]: https://github.com/magit/magit/wiki/Pushing-with-Magit-from-Windows#openssh-passphrase-caching-via-ssh-agent
