### ISSUE TITLE
Make magit-diff support single file diff

### ISSUE THREAD

**Issue by dov** [magit/magit#2553]
I would like to be able to view the difference between a single file (e.g. the current file) and the same file in another branch:

The git command to do this is:

    git diff other-branch path/to/file

An easy way to support this would be to allow the user to edit the actual git command if `magit-diff` was invoked  after C-u.

**Comment by dov** [comment]
I managed to write the following function that does more or less what I need. I guess I should create a pull request:

```
;;;###autoload
(defun magit-diff-file (rev-or-range &optional file args)
  "Show changes between the a file from another branch"
  (interactive (list (magit-diff-read-range-or-commit "Diff for range" nil current-prefix-arg)
                     (if current-prefix-arg 
                       (read-file-name "File: ")
                       buffer-file-name))) 
  (magit-diff-setup rev-or-range nil args
                    (list (replace-regexp-in-string (magit-toplevel) "" (expand-file-name file)))))

```

**Comment by npostavs** [comment]
You should already be able to do that with `d =f path/to/file RET r other-branch RET`

**Comment by dov** [comment]
Nice. But I still feel that the shortcut provide by `magit-diff-file` is justified as it is much faster to do a file comparison of a file being visited, since there is no need to enter `path/to/file`.

**Comment by npostavs** [comment]
Oh, I missed the part where you said it was supposed to be from a file buffer. Would probably make sense to add this to `magit-file-popup`.

**Comment by dov** [comment]
Makes sense. I didn't even know about the `magit-file-popup` function before.

**Comment by tarsius** [comment]
> Would probably make sense to add this to `magit-file-popup`.

I agree. @dov could you please prepare a commit.

* Should be named `magit-diff-buffer-file`, like existing `magit-log-buffer-file`.
* Should behalf the same as that function with regards to the ref and not visiting a file.
* Use `file-relative-name`.

**Comment by dov** [comment]
Done! My first git pull request. Go easy on me. ;-)

See: https://github.com/magit/magit/pull/2556

**Comment by kyleam** [comment]
Closing in favor of #2556.
