### ISSUE TITLE
Allow performing many actions using the mouse

### ISSUE THREAD

**Issue by chris-martin** [magit/magit#2554]
It would be great to have a quick way to jump to a file from the diff buffer.

**Comment by timvisher** [comment]
@chris-martin Doesn't pressing enter on a line do what you're asking for? Or is it specifically that you'd like to drive it with the mouse?

**Comment by chris-martin** [comment]
Ah, I didn't notice that presing enter on a line worked. Yeah, then, specifically mouse usage is the request.

**Comment by kyleam** [comment]
I suspect \*vc-diff* in the title is referring to Magit's revision and
diff buffers.  Otherwise, your request should go to emacs.devel for
vc.el.

Magit doesn't try very hard to support clicking tendencies.  The two
places I know of in Magit that use buttons are the back/forward
history navigation and "Type + to show more history" at the end of the
log buffer.

I suggest adding something like this to your configuration:

```elisp
(define-key magit-hunk-section-map [mouse-1] #'magit-diff-visit-file)
(define-key magit-file-section-map [mouse-1] #'magit-diff-visit-file)
```

**Comment by tarsius** [comment]
I do intend to make many things clickable eventually. A right click menu with more actions would be nice too.

**Comment by tarsius** [comment]
I've changed the subject because I feel this should be done in just a few large steps. Being able to click to see the file as suggested above will be useful to some users, but I would rather not add just this one "mouse command" by itself. The snippet posted by @kyleam above, should do the trick for users who want this now.

**Comment by tobimensch** [comment]
I want this badly! kyleam's lines didn't work for me. For example I want to see the log/commit branch tree, and to click on a commit to show its diff. I also want to jump from a diff to the real file to which that hunk belongs.

**Comment by kyleam** [comment]
> For example I want to see the log/commit branch tree, and to click
> on a commit to show its diff.

That could be done with something like this:

```elisp
(define-key magit-commit-section-map [mouse-1] #'magit-diff-show-or-scroll-up)
```

> I also want to jump from a diff to the real file to which that hunk
> belongs.

I just retested the earlier snippet I gave above, and it worked for
me.  Or are you saying you'd like it to always visit the worktree
file?  In that case, you can replace `magit-diff-visit-file` with
`magit-diff-visit-file-worktree`.

**Comment by tobimensch** [comment]
@kyleam 

I'm new to emacs. I started out with spacemacs. I added your lines (including the latest one) in the user config section of the .spacemacs config file. But without any effect.

Update:
Github is showing me a # before the 'magit-diff-show-or-scroll-up (is that intended?), when I remove it, that line starts working as expected! So thanks.

**Comment by tobimensch** [comment]
This is what I put in my user config section now (and works):

`  (eval-after-load 'magit
    '(define-key magit-hunk-section-map [mouse-1] 'magit-diff-visit-file))
  (eval-after-load 'magit
    '(define-key magit-file-section-map [mouse-1] 'magit-diff-visit-file))
  (eval-after-load 'magit
    '(define-key magit-commit-section-map [mouse-1] 'magit-diff-show-or-scroll-up))`

**Comment by tobimensch** [comment]
@kyleam 

Is it possible to do the same for the stash section in the status view?

**Comment by kyleam** [comment]
> Is it possible to do the same for the stash section in the status
> view?

Yes.  Until a more complete patch is put together, you can use the
following approach to define the mouse actions you want based on a key
binding.

Go to the location and press 'C-h k <binding>' (describe-key).  In the
case of the stash line in the status buffer, 'C-h k RET'.  This will pop
up a help page that tells you something like

    RET runs the command magit-stash-show (found in
    magit-stash-section-map), which is an interactive autoloaded Lisp
    closure in ‘magit-stash.el’.

So, using the same pattern as the snippets above, you want to bind
[mouse-1] to magit-stash-show in magit-stash-section-map.

(I know you said you use spacemacs, which I know nothing about.
spacemacs may give describe-key a different binding.)

**Comment by tobimensch** [comment]
thank you!

By the way, I'm using double-mouse-1 instead for all bindings. One click can happen by accident or have the intention of marking/highlighting something. A double click also feels right in this situation.

**Comment by medranocalvo** [comment]
A little snippet to toggle sections with the mouse by clicking on the fringe indicator:
```elisp
(defun medranocalvo-magit-fringe-section-toggle (event)
  "Toggle section when clicking the fringe indicators.
The section in the EVENT's column is toggled."
  (interactive "e")
  (goto-char (posn-point (event-start event)))
  (let ((section (magit-current-section)))
    (when (= (point) (oref section start))
      (magit-section-toggle section))))
(define-key magit-mode-map (kbd "<left-fringe> <mouse-1>")
  'medranocalvo-magit-fringe-section-toggle)
```

**Comment by tarsius** [comment]
Cheese is ready: #4645!

**Comment by tarsius** [comment]
2016 is done.

**Comment by medranocalvo** [comment]
:-)
