### ISSUE TITLE
Unify popup and menu definition

### ISSUE THREAD

**Issue by llvilanova** [magit/magit#2555]
Right now, defining popups and menus is done separately. A single macro could handle both to make sure the list of commands and their names is consistent. For example:

<pre>
(magit-define-popup-and-menu
  ;; popup-specific
  magit-stgit-popup
  "Popup console for StGit commands."
  'magit-popups

  ;; menu-specific
  magit-stgit-mode-menu
  "StGit"
  :visible magit-stgit-mode

  ;; shared actions
  :actions '(
             ;; menu docs taken from 1st phrase in command docs
             (?i "Initialize" magit-stgit-init)
             ;; special value ignored on popups and showing separator in menu
             (nil)
             ;; only shown in popup
             (?z "Undo" magit-stgit-undo-popup :visible-menu nil)))
</pre>

**Comment by tarsius** [comment]
I don't think that this would be a good idea. This would further restrict the popup implementation and interface (little by little) and it already is to restrictive now. Many of Magit's own popups are already not being defined using this macro.

Ps: I am on a break, so I am just letting you know how I think about this. I won't have the time to discuss it now.

**Comment by llvilanova** [comment]
Mmmm, what you're saying sounds right, but it's still too easy to let popups and menus to desynchronize and show inconsistent names.

**Comment by tarsius** [comment]
Same goes for code and documentation. And callers and callees etc.

We just have to remember to update both. And if we don't then we might have to fix that later, which also isn't the end of the world.
