### ISSUE TITLE
magit-commit does not work

### ISSUE THREAD

**Issue by batalyx** [magit/magit#2558]
When I try to commit staged changes, commit fails with error
> magit-invoke-popup: Wrong type argument: commandp, (quote magit-commit)

This seems to be fixed by unquoting magit-commit at
  https://github.com/magit/magit/blob/master/lisp/magit-commit.el#L119
but I think the correct fix would be to use
  `(magit-define-popup magit-commit-popup ...)`
instead of
  `(defvar magit-commit-popup ...)`

Sorry, that I'm not able to do pull request now.

My Emacs version is GNU Emacs 25.0.50.1 on x86_64-apple-darwin14.3.0.
My magit version is Magit 20160218.2137, Git 2.5.4 (Apple Git-61).
My magit-popup is version 20160130.649 from elpa.

**Comment by tarsius** [comment]
> This seems to be fixed by unquoting magit-commit 

Yes. I have done that now. Thanks for reporting.

> but I think the correct fix would be to use magit-define-popup

No, unfortunately that macro isn't flexible enough to be used for all popups. In this case the use of the macro would mean that the command `magit-commit-popup` would have to be advised.

**Comment by batalyx** [comment]
Ok, I'll then not spend time trying to make that macro work. Thanks for fast fix & info.
