### ISSUE TITLE
magit-auto-revert-mode slowness during load-library

### ISSUE THREAD

**Issue by warner** [magit/magit#2559]
This came up in the comments on #2552, but appears to be a distinct issue, so I'm leaving that bug to its original problem report and moving the auto-revert issues here. Most of this comment is copied from that bug.

This slowness appears when loading the magit library in an emacs with lots (~240 on my box) of buffers that are under git control (and thus might need to be examined or reverted when magit has run git commands). This also happens during the autoload of magit, so it can masquerade as a slowness in running `magit-status`, but is actually during the eval of `magit.el` (and related files) themselves.

Thanks to @danrharms and @ilohmar , I tried the following function to temporarily disable the mode, just while loading, then put it back to whatever it was before:

```elisp
(defun my-load-magit ()
  (interactive)
  (let ((magit-auto-revert-mode nil)
        (start (float-time)))
    (load-library "magit")
    (message "elapsed: %f" (- (float-time) start))
    ))
```

Calling this (right after startup and calling any magit functions) takes about 0.5 seconds. Restarting emacs and calling again with `t` instead of `nil` takes 11 seconds. I have about 240 buffers open at startup (via desktop-save-mode), most of which are probably under git control, which implies something in eval is taking about 40ms per buffer.

I guess the easiest workaround is to force-load magit (with a function like above) from my `emacs.el` at startup. I use magit every day, so it's not like I'm saving any time or memory by deferring to an autoload.

A better fix would be to somehow rig the autoload function to change `magit-auto-revert-mode` before and after loading.. can the autoloader call a function instead of loading the library directly?

The best fix would be to isolate where in magit this delay is coming from and wrap *that*. It's happening at eval time, which should narrow down the possible location somewhat. If we're right and this really is a recent issue, then bisecting the magit history might be a quick way to narrow it down.

It's just a hunch, but I'd bet that the auto-revert changes for #2513 is involved, since they landed on 26-Jan, and I think that's in-between the updates I did when I first noticed the problem.

**Comment by warner** [comment]
No, I'm wrong about #2513, it looks like the commit that changed behavior for me was f916cd03066d3d3f61413c2b8fb07c256c507172 or ddcf4f648e28a4d2043d2af324b5ecda8096c422 (I get an error with f916cd0, and slowness with ddcf4f6, and fast loading with the previous 455c8f2). These commits were dated 12-Jan, and introduced `magit-auto-revert-mode` for the first time.

**Comment by npostavs** [comment]
Are you sure loading has anything to do with it? What do you get from
```elisp
(defun my-load-magit ()
  (interactive)
  (setq magit-auto-revert-mode nil)
  (let ((start (float-time)))
    (load-library "magit")
    (message "magit loading: %f" (- (float-time) start)))
  (let ((start (float-time)))
    (magit-auto-revert-mode +1)
    (message "magit auto revert: %f" (- (float-time) start))))
```

**Comment by warner** [comment]
```
magit loading: 0.572440
magit auto revert: 9.977342
```
(using magit-2.5.0, emacs-24.5.1, git-2.7.1)

If I just repeat that last clause, I see `(magit-auto-revert-mode +1)` taking an extra 10.5 seconds for each invocation. So there must be a lot of work going on inside that function, more than just setting a flag.

I'm sure I'm confused about the relationship between `magit-auto-revert-mode` as a value, and as a function. Changing the value from `nil` to `t` after magit has loaded doesn't take significant time (I was speculating that it had some sort of magic property-setter function or on-change trigger, but that doesn't seem to be the case).

At this point I'm guessing that allowing the *value* to be `t` during load causes the *function* of the same name to be called during eval.

So I suspect my workaround (allowing `let` to restore the value to `t` after loading, but not calling the revert *function*) isn't leaving my buffers in the same useful state as calling revert explicitly or allowing load-library to call it during eval. I haven't tried using magit at all in these two states, to see whether buffers get reverted automatically or not.

Guess I should dig into the auto-revert functionality and understand how it works a bit better.

**Comment by npostavs** [comment]
> So I suspect my workaround (allowing let to restore the value to t after loading, but not calling the revert function) isn't leaving my buffers in the same useful state as calling revert explicitly or allowing load-library to call it during eval.

Yeah.

```
magit-auto-revert-mode is an interactive Lisp closure in `magit-autorevert.el'.
...
This global mode works by turning on the buffer-local mode
`auto-revert-mode' at the time a buffer is first created.  The
local mode is turned on if the visited file is being tracked in
a Git repository at the time when the buffer is created.
```

When the mode is started, it goes through all existing buffers to enable `auto-revert-mode` as needed, this means there is one call to `magit-turn-on-auto-revert-mode-if-desired` per buffer.

**Comment by tarsius** [comment]
I've extended the existing kludge which avoided turning on the mode if the user set the obsolete variable `magit-revert-buffers` to nil any time during startup, to do the same if they set `magit-auto-revert-mode` to nil.

But note that this only has an effect during startup. If startup is over and `magit-revert` has already been loaded, and the user then sets one of these variables to nil, then this won't have an effect. Minor-modes, including and especially global minor-modes, have to be toggled using the mode command.

But since this mode is a bit odd implementation wise anyway, it makes sense to allow users to set the initial value by setting the variable using `setq`. But that doesn't make it good practice to do so - this is a kludge and this won't work with other modes.

**Comment by ilohmar** [comment]
I have to admit that I have no idea how this is supposed to work..  I still have to set magit-auto-revert-mode to nil on startup (ie, before magit is loaded) --- setting it `(with-eval-after-load 'magit ...)` does not avoid the slowness when I call magit-status for the first time.  But setting it in init.el unconditionally already worked before the change, right?

Mind you, I am not complaining, I would just like to understand how the commit has changed the situation.

**Comment by npostavs** [comment]
> I would just like to understand how the commit has changed the situation.

In the case that the user has something like `(require 'magit) (setq magit-auto-revert-mode nil)` in their init.el, then `magit-auto-revert-mode` would be turned off in the `after-init-hook`, previously it was left on.

It doesn't avoid the initial slowness from turning it on though. And it can't help if you used `(with-eval-after-load 'magit ...)` and magit is loaded after the `after-init-hook` is run.

**Comment by ilohmar** [comment]
Understood, thanks.
