### ISSUE TITLE
improve closing with-editor buffers in evil-mode

### ISSUE THREAD

**Issue by wbolster** [magit/magit#2561]
closing a `with-editor` buffer while using `evil-mode` is a bit clunky because it expects the user to use `C-c C-c` or `C-c C-k` to either finish or cancel the operation. this does not feel very evil. :)

with vim-fugitive (vim git integration) i always typed `ZZ` or `ZQ` to close the buffer, which in `evil` translates to

* `(evil-save-modified-and-close)`, bound to `ZZ`
* `(evil-quit)`, bound to `ZQ`

perhaps the mode map can be extended to include

```lisp
(define-key map [remap evil-save-modified-and-close] 'with-editor-finish)
(define-key map [remap evil-quit] 'with-editor-cancel)
```

(fwiw, i'm an emacs newbie, so please point out my mistakes, if any).

**Comment by wbolster** [comment]
as a work-around i currently have this in my `init.el`:

```elisp
(evil-define-key 'normal with-editor-mode-map
  "ZQ" 'with-editor-cancel
  "ZZ" 'with-editor-finish)
```

**Comment by kyleam** [comment]
I'm closing this in favor of the issue you opened with evil-magit.  I don't see anything to be done on Magit's end.

**Comment by wbolster** [comment]
ok, fair enough

**Comment by wbolster** [comment]
@kyleam maybe you can chime in on the discussion on justbur/evil-magit#18 for a sec? thanks!
