### ISSUE TITLE
unapplicable commit message warning is shown

### ISSUE THREAD

**Issue by wbolster** [magit/magit#2564]
when making a commit and typing a message, magit performs a few checks on the message. when i enter a summary line that is a bit too long for magit's taste, it asks me whether to proceed, and when i choose yes, magit prompts me again, claiming that the second line of the message is not empty, while it actually was. so i get two prompts instead of one.

sample single-line commit message triggering this erroneous behaviour:

     this is a summary line which magit does not really like since it thinks it is too long for its rather sensitive tastes

**Comment by kyleam** [comment]
I cannot reproduce this with your example line and emacs -Q.  Related to #2074?
