### ISSUE TITLE
magit-diff-arguments default includes --stat, makes patches (empty) 

### ISSUE THREAD

**Issue by simonmichael** [magit/magit#2565]
I reset magit-diff-arguments to its default value, which includes --stat . On my system (OSX, git 2.7.0) this causes git diff to show a diffstat only, and causes magit patch views to show (empty) instead of the diff, which doesn't seem to have much use.

**Comment by tarsius** [comment]
Provided that there actually are changes, they should always be shown. Make sure no file filter is in effect and that there are actually are any changes. If you still don't see them, then try to reproduce with `emacs -Q`.
