### ISSUE TITLE
Finding 'git reset' option in magit

### ISSUE THREAD

**Issue by lboogaard** [magit/magit#2566]
While trying to reset to a previous commit in the reflog I spent quite some time looking for the 'git reset' option in magit. The "help window" (`?`) does not show a reset option anywhere (at least, as far as I could see...)

I finally found the key (`x`) in the [docs](http://magit.vc/manual/magit/Resetting.html#Resetting), which did exactly what I expected. Though hitting `x` did not give me any options (--soft, --hard, etc.). Can those only be done by calling the specific functions via `M-x`?

In any case, I think it is useful to have a reference to the reset option `x` in the popup window (`?`) ?

B.t.w. I'm on: Magit 20160227.433, Git 2.7.2, Emacs 24.5.1

**Comment by kyleam** [comment]
> In any case, I think it is useful to have a reference to the reset
> option x in the popup window (?) ?

Others have suggested this too:

* https://github.com/magit/magit/issues/2141
* https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands#add-command-magit-reset

I don't feel too strongly about it, but I'd prefer not add it.  The
most common use of reset is already available and in the dispatch
popup as `magit-unstage`.  If a user knows they want to call some
other git reset variant, they could discover the other reset commands
in several other ways, including `command-apropos` for "magit" and
"reset", or `C-h m` in a magit buffer and search for "reset", in
addition to looking at the manual like you did.

**Comment by phil-s** [comment]
> Though hitting x did not give me any options (--soft, --hard, etc.). Can those only be done by calling the specific functions via M-x?

* `x` is a soft reset
* `C-u x` is a hard reset

**Comment by tarsius** [comment]
> I don't feel too strongly about it, but I'd prefer not add it.

I also don't really think it is necessary, but since this keeps coming up and isn't much work to implement, and `X` was still free, I have just added a new reset popup. It's also available from the dispatch popup.

Personally I will continue to use `x` and `C-u x`, but I guess it was a bit confusing that there was no reset popup even though there's a popup for most other things.

**Comment by lboogaard** [comment]
> Personally I will continue to use x and C-u x, but I guess it was a bit confusing that there was no reset popup even though there's a popup for most other things.

This was indeed exactly what confused me. 

Great stuff, thanks for explaining and the very fast implementation!
