### ISSUE TITLE
Trying to commit when using emacsclient results in an error

### ISSUE THREAD

**Issue by kalentia** [magit/magit#2567]
When I am using emacsclient (either in the command line or the gui), attempting to commit a change causes the following error:

`Waiting for Emacs...
*ERROR*: Wrong type argument: processp, nowait
error: There was a problem with the editor '/usr/bin/emacsclient --socket-name=/tmp/emacs1000/server'.
Please supply the message using either -m or -F option.`

If I do the same thing without emacsclient, the commit process works fine. I'm running Arch Linux with spacemacs if that affects anything.

**Comment by tarsius** [comment]
Please see http://magit.vc/manual/with-editor/Debugging.html.

**Comment by kalentia** [comment]
Well, I feel pretty stupid. I had a typo in my `export EDITOR` section that was causing it to error out. Thanks for the help.

**Comment by tarsius** [comment]
Typos happen :-)
