### ISSUE TITLE
Support magit-log-buffer-file in Dired buffers

### ISSUE THREAD

**Issue by tomjakubowski** [magit/magit#2571]
It seems reasonable to me to allow magit-log-buffer-file in dired; after all, `git log -- some/path/in/tree` works as you'd expect.

**Comment by tarsius** [comment]
Alternatively it could show the log for the file at point in Dired buffers too, just like in Magit buffers.

This uses the function `magit-file-relative-name` which feels quite strange to me. The various functions involved in getting the "current file" though probably thought about some more and refactored to provide a more reasonable interface.

So while it would be easy to "change something", i.e. to make that command do what you are suggesting, figuring out what this command and other commands that do something with the "current file", is quite a bit harder.

I am [on a break](http://emacsair.me/2016/02/10/magit-2.5). So that probably won't happen soon.

**Comment by tarsius** [comment]
Meanwhile you may use the above patch. The commit message contains usage instructions.

**Comment by Fuco1** [comment]
It would be cool if it also worked from the log popup, with some option to automatically set "default" file.  I find =f quite bothersome to use (plus for some reason completion doesn't work for me in that dialog).

I prefer the version where it works on the file at point.  If you want the directory, you can always put the point on the `.` file.

The "get current file" function could be further extended to work with `ffap` and similar functions.  That would be bomb :)

Should we start a new discussion?  I would be willing to give it some time to implement this.

**Comment by npostavs** [comment]
> (plus for some reason completion doesn't work for me in that dialog).

It takes mutiple values so it uses `completing-read-multiple` which doesn't support fancier completion modes, but if you hit TAB you should get completion candidates.

**Comment by Fuco1** [comment]
@npostavs Ah, yea that would explain it, I use my own fancy magical nonsense instead of `minibuffer-complete`, so there is some incompatibility somewhere probably. Thanks for the pointer :)

**Comment by tarsius** [comment]
I have decided against teaching `magit-log-buffer-file` to show the log for the `default-directory` of a Dired buffer.

Instead I will create `magit-{log,diff}-files`, replacing `magit-log-buffer-file` and `magit-diff-buffer-file-popup`. These will be available from the `magit-file-popup` and you will be able to bind them in Dired and Magit buffers  where they act on the file at point (or the files selected using the region).

The hard part will be having separate regluar-log/diff buffers and file-log/diff buffers, and then figuring out which arguments should be used when either variant is used. I am currently trying to rethink some related problems, and the issue for tracking that is #2585.

**Comment by tarsius** [comment]
This patch would implement the requested feature:

```diff
diff --git a/lisp/magit-diff.el b/lisp/magit-diff.el
index 38efd56..d9d332f 100644
--- a/lisp/magit-diff.el
+++ b/lisp/magit-diff.el
@@ -581,7 +581,9 @@ (defun magit-diff-buffer-file-popup ()
 but which limits the diff to the file being visited in the current
 buffer."
   (interactive)
-  (-if-let (file (magit-file-relative-name))
+  (-if-let (file (or (magit-file-relative-name)
+                     (and (derived-mode-p 'dired-mode)
+                          (magit-file-relative-name default-directory))))
       (let ((magit-diff-arguments
              (magit-popup-import-file-args
               (-if-let (buffer (magit-mode-get-buffer 'magit-diff-mode))
diff --git a/lisp/magit-log.el b/lisp/magit-log.el
index 618d9ba..dfe2286 100644
--- a/lisp/magit-log.el
+++ b/lisp/magit-log.el
@@ -600,7 +600,9 @@ (defun magit-log-buffer-file (&optional follow beg end)
                          (1- (line-number-at-pos (region-beginning)))
                          (1- (line-number-at-pos (region-end))))
                  (list current-prefix-arg)))
-  (-if-let (file (magit-file-relative-name))
+  (-if-let (file (or (magit-file-relative-name)
+                     (and (derived-mode-p 'dired-mode)
+                          (magit-file-relative-name default-directory))))
       (magit-mode-setup-internal
        #'magit-log-mode
        (list (list (or magit-buffer-refname
```
