### ISSUE TITLE
magit-status fails with "Unknown upattern"

### ISSUE THREAD

**Issue by tim-teufel** [magit/magit#2572]
After updating to the latest MELPA version of magit, `magit-status` shows empty `*magit: trunk` buffer for my repository.

Magit packages (installed from MELPA):
* magit-20160302.155
* magit-popup-20160302.102

I've reproduced the error in `emacs -Q`:
1. `(package-initialize)`
2. `M-x magit-status`
3. An empty magit status buffer appears
4. In the `*Messages*` buffer, we see the following errors
```
Eager macro-expansion failure: (error "Unknown upattern `(quote staged)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote prev)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote magit-invoke-popup-switch)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote woman)'")
Turning on magit-auto-revert-mode...done
Eager macro-expansion failure: (error "Unknown upattern `(quote magit-revision-mode)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote unstaged)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote hunk)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote scroll-up)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote (68 68))'")
Eager macro-expansion failure: (error "Unknown upattern `(quote file)'")
Compiler-macro error for cl--block-wrapper: (error "Unknown upattern `(quote (hunk t t nil))'")
Eager macro-expansion failure: (error "Unknown upattern `(quote (hunk t t nil))'")
Eager macro-expansion failure: (error "Unknown upattern `(quote list)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote (file t))'")
Compiler-macro error for cl--block-wrapper: (error "Unknown upattern `(quote (< nil))'")
Eager macro-expansion failure: (error "Unknown upattern `(quote (< nil))'")
Eager macro-expansion failure: (error "Unknown upattern `(quote (t nil t))'")
Eager macro-expansion failure: (error "Unknown upattern `(quote magit-log-mode)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote log)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote magit-log-mode)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote unstaged)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote hunk)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote (unstaged region))'")
Eager macro-expansion failure: (error "Unknown upattern `(quote file)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote (staged region))'")
Eager macro-expansion failure: (error "Unknown upattern `(quote (90))'")
Eager macro-expansion failure: (error "Unknown upattern `(quote detach)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote magit-commit)'")
Eager macro-expansion failure: (error "Unknown upattern `(quote (ask-if-unset nil))'")
(No files need saving)
Eager macro-expansion failure: (error "Unknown upattern `(quote (ask-if-unset nil))'")
pcase--u1: Unknown upattern `(quote magit-log-mode)'
```

**Comment by tarsius** [comment]
Ah crap. Apparently my initial impression (see 5d39492d47f0ce4e91f33292259b28f36169c806) was correct - at least for older Emacsen. What version are you using?

**Comment by tarsius** [comment]
https://github.com/jwiegley/emacs/commit/13b1840d23f1f214bec11a3c6823d675cbd82f28

**Comment by thierryvolpiatto** [comment]
In many places cl-case should be enough and simpler (no need to quote/backquote).

**Comment by tarsius** [comment]
I like `pcase`. I also used to like `case`, but now that it is called `cl-case` not so much anymore.

**Comment by thierryvolpiatto** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> I like pcase.

Me too, but not for simple use.
(Seems it was a general consensus on emacs-dev to not use pcase on such
simple patterns)

> I also used to like case, but now that it is called cl-case not so
> much anymore.

Hmm, yes that's true for all "cl-" prefixed stuff.

-- 
Thierry

**Comment by mforsyth** [comment]
I have the same issue after having just updated.  I'm on Emacs 24.4.1, using Spacemacs 0.105.11

**Comment by tim-teufel** [comment]
Wow, how fast…
I use GNU Emacs 24.4.1.

**Comment by joodie** [comment]
Same problem here with emacs 24.5.1 x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21

**Comment by kstrempel** [comment]
I have the same problem with emacs 
GNU Emacs 24.5.1 (x86_64-apple-darwin15.3.0, Carbon Version 157 AppKit 1404.34)

**Comment by twillis** [comment]
same here. 24.5.1 and spacemacs 0.105.11

**Comment by tarsius** [comment]
> me too

As you might have seen I have already reverted the commit. Unfortunately the original commit was pushed just minutes before Melpa rebuild `magit` and as a result it will take about five hours until Melpa gets around to building a new snapshot.

> (Seems it was a general consensus on emacs-dev to not use pcase on such simple patterns)

That happened about a year after I decided to use `pcase`.

> Hmm, yes that's true for all "cl-" prefixed stuff.

To some extend. In this particular case I really don't like it. In others I don't care that much.

**Comment by youRFate** [comment]
Hi, same problem here, versions: Magit 20160302.155, Git 2.7.2.windows.1, Emacs 24.5.1

It happened after updating. The installation of magit had several errors, here is the log:

[magit_error.txt](https://github.com/magit/magit/files/155080/magit_error.txt)

I replaced my username with the word 'username' in there.

**Comment by johnbellone** [comment]
I updated via melpa and having the same issues.

**Comment by mordocai** [comment]
@johnbellone  melpa hasn't finished building after the fix yet

**Comment by patefacio** [comment]
I'm having issues with 20160302.322 for emacs "GNU Emacs 24.5.1 (x86_64-redhat-linux-gnu, GTK+ Version 2.20.1) of 2016-03-02 on c167b822117f"

How do you know when melpa is finished?
What is the best way to install a previous working version?

**Comment by thierryvolpiatto** [comment]
Daniel Davidson <notifications@github.com> writes:

> I'm having issues with 20160302.322 for emacs "GNU Emacs 24.5.1 (x86_64-redhat-linux-gnu, GTK+ Version 2.20.1) of 2016-03-02 on c167b822117f"
>
> How do you know when melpa is finished?

From the melpa web page:

Current build started: 5 hours ago, last took 5 hours

> What is the best way to install a previous working version?

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("melpa-stable" . "https://stable.melpa.org/packages/")
                         ("gnu" . "https://elpa.gnu.org/packages/")
                         ))

(setq package-pinned-packages '((magit . "melpa-stable")
                                (magit-popup . "melpa-stable")))

-- 
Thierry

**Comment by tarsius** [comment]
A snapshot with the bad commit reverted has been available for a while now.
