### ISSUE TITLE
 Malformed magit-pull-popup output

### ISSUE THREAD

**Issue by peti** [magit/magit#2573]
I have a strange issue running recent versions of Magit that shows up only on one particular Linux machine. I'm using Magit 20160219.1702, Git 2.7.1, Emacs 24.5.2, and when I enter the `magit-pull-popup` by pressing `F`, then I see the following menu:

~~~~~
Actions
 <lambda> nil
 p magit-get-push-branch
 u magit-get-upstream-branch
 e elsewhere
~~~~~

Note the strange "lambda" bit there. This is happening with older versions, too. On all my other machines, that menu contains no "lambda"line and shows a concrete branch name for "u". I'm using the exact same `.emacs` file on all systems. The only difference is that the malfunctioning installation has an Emacs installed by Nix on an openSUSE Linux box and the other machines run NixOS (and consequently have Emacs installed by Nix, too).

I have no clue how I would go about debugging this phenomenon. Do you have any idea what might be causing this strange issue?

P.S. I've reported this in the Nix repository as https://github.com/NixOS/nixpkgs/issues/12962, but apparently no-one could reproduce the error.

**Comment by kyleam** [comment]
I'd guess that you have an older version of magit-popup on that machine.

**Comment by kyleam** [comment]
More specifically, older than 4d59336 (popup: support functions as descriptions of actions, 2015-11-28).

**Comment by tarsius** [comment]
And if you don't then you might still have to recompile `magit`.

**Comment by kyleam** [comment]
Closing.  Please let use know if this isn't fixed by using an up-to-date magit-popup.

**Comment by peti** [comment]
The issue was caused by a bug in the Nix package set, so it's not caused by Magit. Thank you very much for your feedback!
