### ISSUE TITLE
Windows ediff "file name, directory name or volume label syntax is incorrect"

### ISSUE THREAD

**Issue by fommil** [magit/magit#2574]
Firstly, many apologies for the poor quality of this bug report. When it happens, it happens every time I want to do an ediff, but when I try to reproduce it, it seems to start working again. I am using `(setq ediff-window-setup-function 'ediff-setup-windows-plain)` such that the menu controls are in the same window.

If I am resolving a conflict in a merge or cherry pick and I type `e` to resolve using ediff, I expect the ediff editor to come up (and indeed this works without fail on Linux). However, on Windows, most of the time a **new frame pops up** containing the two identical lines for buffer `*ediff-fine-diff*`

```
file name, directory name or volume label syntax is incorrect^M
file name, directory name or volume label syntax is incorrect^M
```

in `*Message*` it says 

```
ediff-prepare-error-list: Errors in diff output.  Diff output is in #<buffer *ediff-fine-diff*>
```

and I can find no other relevant information in `*Messages*` or temporary buffers. The standard `ediff` controls no longer work and the only thing to do is to kill all the buffers / windows and open the file directly and merge manually.

Any help on debugging the cause of this would be greatly appreciated. Perhaps the temporary files are somehow not compatible with Windows?

**Comment by fommil** [comment]
caught a stack trace! Not sure it's any use, although it is hinting at missing newlines.

This happened when I pressed `n` for the first time in an ediff, at which point the external frame popped up.

```
Debugger entered--Lisp error: (error "Errors in diff output.  Diff output is in #<buffer *ediff-fine-diff*>")
  signal(error ("Errors in diff output.  Diff output is in #<buffer *ediff-fine-diff*>"))
  error("Errors in diff output.  Diff output is in %S" #<buffer *ediff-fine-diff*>)
  ediff-prepare-error-list("^\\([1-3]:\\|====\\|  \\|.*Warning *:\\|.*No newline\\|.*missing newline\\|^
$\\)" #<buffer *ediff-fine-diff*>)
  ediff-setup-fine-diff-regions("c:/MSDE/samhalli/temp/fineDiffA11420AVG" "c:/MSDE/samhalli/temp/fineDiffB11420NfM" nil 0)
  ediff-make-fine-diffs(0 noforce)
  ediff-install-fine-diff-if-necessary(0)
  ediff-next-difference(1)
  call-interactively(ediff-next-difference nil nil)
  command-execute(ediff-next-difference)
```

**Comment by johnmastro** [comment]
I set up the following advice for a similar-sounding error. However, I think my setup is a bit different (I'm using Cygwin) and I didn't reproduce your error or confirm that this will fix it. Might be worth a shot though.

```emacs-lisp
(defun ediff-expand-tmp-name (args)
  "Advice for `ediff-make-empty-tmp-file'.
Call `expand-file-name' on the proposed file name. Only necessary
on Windows."
  (pcase-let ((`(,proposed-name . ,rest) args))
    (cons (expand-file-name proposed-name) rest)))

(with-eval-after-load 'ediff
  (when (eq system-type 'windows-nt)
    (advice-add 'ediff-make-empty-tmp-file
                :filter-args
                #'ediff-expand-tmp-name)))
```

**Comment by tarsius** [comment]
@johnmastro Please but that on https://github.com/magit/magit/wiki/Tips-and-Tricks, preferably after porting to `advice-add`.

**Comment by fommil** [comment]
like I said, reproducing this bug is pretty tough, but in my first conflict resolution of the day with this advice applied, things *seem* to be working :smile:

**Comment by fommil** [comment]
If this is a bug in ediff, we should flag it up for fixing in Emacs 25.

If it's a bug in the way magit calls ediff, it sounds like there could be an easy fix.

**Comment by fommil** [comment]
darn, just got the popup on the second file (which was in the same folder as the one that worked).

```
Debugger entered--Lisp error: (error "Errors in diff output.  Diff output is in #<buffer *ediff-fine-diff*>")
  signal(error ("Errors in diff output.  Diff output is in #<buffer *ediff-fine-diff*>"))
  error("Errors in diff output.  Diff output is in %S" #<buffer *ediff-fine-diff*>)
  ediff-prepare-error-list("^\\([1-3]:\\|====\\|  \\|.*Warning *:\\|.*No newline\\|.*missing newline\\|^
$\\)" #<buffer *ediff-fine-diff*>)
  ediff-setup-fine-diff-regions("c:/FOO/samhalli/temp/fineDiffA11420nBB" "c:/FOO/samhalli/temp/fineDiffB114200LH" nil 1)
  ediff-make-fine-diffs(1 noforce)
  ediff-install-fine-diff-if-necessary(1)
  ediff-next-difference(1)
  call-interactively(ediff-next-difference nil nil)
  command-execute(ediff-next-difference)
```

**Comment by tarsius** [comment]
My guess is that it isn't Magit that is to blame... but then how would I know?

**Comment by fommil** [comment]
FWIW, this is my workaround until we can get to the bottom of this, use `RET` to enter `smerge-mode` and fake the ediff/emerge commands

```
   (defhydra hydra-smerge nil "smerge"
     ("p" smerge-prev)
     ("n" smerge-next)
     ("a" smerge-keep-mine)
     ("b" smerge-keep-other)))

  (add-hook 'smerge-mode-hook (lambda () (hydra-smerge/body)))
```

**Comment by johnmastro** [comment]
> @johnmastro Please but that on https://github.com/magit/magit/wiki/Tips-and-Tricks, preferably after porting to advice-add.

@tarsius, I would be happy to. However, I encountered the error in a non-Magit context (`ediff-buffers`) and it seems it didn't work for Sam anyway. Do you still think it's appropriate for there?

**Comment by tarsius** [comment]
> Do you still think it's appropriate for there?

@johnmastro Let's not add it for now.

> If this is a bug in ediff, we should flag it up for fixing in Emacs 25.

@fommil We just don't know. Someone will have to narrow this down and then either open a bug against Emacs or reopen this.
