### ISSUE TITLE
Let magit-ediff-dwim behave more usefully over a stash

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2575]
Hi,

currently, the command doesn't guess anything and uses the most general fallback ("can't read your mind" etc.).  The user will most likely  want to ediff against the stash's parent, but maybe against an arbitrary different commit.

I think it should be doable quite easily: in `magit-ediff-dwim` replace the

```
(commit . ,value)
```

pattern with

```
(,(or `commit `stash) . ,value)
```

to treat it the same as commits.  You may also want to change `magit-diff-read-range-or-commit` similarly for that purpose.

Thanks,

Michael.

**Comment by kyleam** [comment]
Thank you.  I think both of those are good suggestions and you proposed changes should work.  Want to submit a PR?

**Comment by tarsius** [comment]
It's a bit more complicated than that.

* Multiple files might have changed. Unless only one has changed we have to ask the user.
* A stash may consist of up to 3 commits (but let's ignore the "new files" commit)

I have written the boilerplate, but reading the file is still missing: https://github.com/magit/magit/compare/jb/ediff-stash?expand=1.

**Comment by kyleam** [comment]
> Multiple files might have changed. Unless only one has changed we have to ask the user.

That's true for the commit too, but `magit-ediff-compare--read-files` takes care of it in `magit-ediff-show-commit`.  It seems to handle `stash@{N}` fine.

**Comment by kyleam** [comment]
> A stash may consist of up to 3 commits (but let's ignore the "new files" commit)

I think the initial suggest would allow you to select a file for ediffing the working tree relative to `stash@{N}`, as with `git diff stash@{N}`.

**Comment by michael-heerdegen** [comment]
Kyle Meyer <notifications@github.com> writes:

> Thank you. I think both of those are good suggestions and you proposed
> changes should work. Want to submit a PR?

I'm not sure if I have sufficing knowledge about the internals...  Let's
discuss the stuff a bit more for now.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> It's a bit more complicated than that.
>
> * Multiple files might have changed. Unless only one has changed we have to ask the
>  user. 
> * A stash may consist of up to 3 commits (but let's ignore the "new
>  files" commit)

I guess you mean workspace vs. index changes?  (Where can I read about
how this works internally, btw?)

I'm not sure which behavior would be the most useful, but at the first
look, using ediff3 seems a bit of overkill to me.


> I have written the boilerplate, but reading the file is still missing:
> https://github.com/magit/magit/compare/jb/ediff-stash?expand=1.

(Oh, you are still not using lexical binding?)

Yeah, makes sense.  But yes, I want to able to ediff against workspace
or index too (since the stash can also be a snapshot of these) or even
against an arbitrary commit.


Thanks so far,

Michael.

**Comment by kyleam** [comment]
> I guess you mean workspace vs. index changes?  (Where can I read
> about how this works internally, btw?)

A stash has potentially three parents:

- `stash@{N}^1` The commit it was made on.

  Diffing `stash@{N}^1..stash@{N}` gives you all changes in the stash.

- `stash@{N}^2` The index of the stashed changes.

  Diffing `stash@{N}^..stash@{N}^2` gives you the stashed changes that
  were staged.

- `stash@{N}^3` If present, this is the untracked files.

Have a look at `git log --graph stash@{0}`

**Comment by michael-heerdegen** [comment]
Kyle Meyer <notifications@github.com> writes:

> Have a look at git log --graph stash@{0}

Ah, I see, it's internally just a normal commit with potentially
multiple parents (that are commits created as well when creating a
stash).  I always thought it would be something different.

l o stash@{N} works fine too btw.

Thanks!

**Comment by kyleam** [comment]
I think what you originally suggested works nicely for a DWIM command:
it offers to ediff a tracked file that changed in the stash, showing
all changes in the stash for that file and ignoring any distinction
between which changes were staged or unstaged.

Of course, using ediff3, as @tarsius suggests, you can keep that
distinction.  I'm fine with that, too, but was just pointing out that
using `stash@{N}` as the commit works as *I* mean.

**Comment by tarsius** [comment]
The three buffer variant I suggested can wait and we can install something else now. Eventually there probably has to be an option so that we can "d" what a particular user "wim".

**Comment by kyleam** [comment]
OK, at some point this weekend, I'll flesh out jb/ediff-stash.  Then let's decide depending on how that looks.

**Comment by kyleam** [comment]
> OK, at some point this weekend, I'll flesh out jb/ediff-stash.

A draft of this is in [km/ediff-stash](https://github.com/magit/magit/compare/km/ediff-stash).

**Comment by michael-heerdegen** [comment]
Kyle Meyer <notifications@github.com> writes:

> A draft of this is in km/ediff-stash.

Thanks for working on this!

Personally, for "magit-ediff-show-stash-with-index" I would prefer a
third value, doing the following: if stash@{N}^2 exists, always use
ediff3.  If not, use normal ediff.  Or does t already do this?

**Comment by kyleam** [comment]
> I would prefer a third value, doing the following: if stash@{N}^2
> exists, always use ediff3. If not, use normal ediff.

Even if a stash is created when there are no staged changes,
stash@{N}^2 still exists.  (It is stash@{N}^3 that only sometimes
exists.)  So I'm taking your suggestion as: use ediff3 only when there
is a difference in that file between stash@{N}^ and stash@{N}^2.  I'm
fine doing that, but I don't see the need for a third option rather
than just rolling that into a non-nil value for
magit-ediff-show-stash-with-index.

**Comment by kyleam** [comment]
Updated to only use ediff3 if stash@{N}^2 has changes.

**Comment by michael-heerdegen** [comment]
Kyle Meyer <notifications@github.com> writes:

> Even if a stash is created when there are no staged changes,
> stash@{N}^2 still exists. (It is stash@{N}^3 that only sometimes
> exists.) So I'm taking your suggestion as: use ediff3 only when there
> is a difference in that file between stash@{N}^ and stash@{N}^2.

Yes, that's what I want then.

> I'm fine doing that, but I don't see the need for a third option
> rather than just rolling that into a non-nil value for
> magit-ediff-show-stash-with-index.

That's actually what I meant (I guess it was just to late to notice that
I used the term "option" with a different meaning than what it actually
means in Emacs).

**Comment by michael-heerdegen** [comment]
Kyle Meyer <notifications@github.com> writes:

> Updated to only use ediff3 if stash@{N}^2 has changes.

Great, thanks!

Is this code already working (i.e., can it be safely tested)?

**Comment by kyleam** [comment]
> Is this code already working (i.e., can it be safely tested)?

As far as I can tell, but there might be edge cases.  I'm particularly
interested in knowing if there's a case where the file selection
approach fails to recognize a file rename, indicating that the logic
in the commit message of 25846b5c1 is wrong.

Anyway, it's not doing anything that should eat data.

**Comment by kyleam** [comment]
I'm closing this in favor of #2581.  If we decide not to go that route, we can reopen this issue.
