### ISSUE TITLE
Any interest in making TAB more dwim?

### ISSUE THREAD

**Issue by justbur** [magit/magit#2576]
TAB toggles the section visibility, but does nothing on individual commits, while SPC on a commit brings up the commit in another window, which is like toggling the visibility. I was wondering if there might be interest in combining the functions into a more powerful TAB? Here's a rough mock-up of what I mean which comes from https://github.com/justbur/evil-magit/issues/20. I don't know that it works in all cases. I was just playing around with the possibility.

```elisp
;; New TAB
(defun magit-section-toggle-or-show-diff-up ()
  (interactive)
  (magit-section-case
    ((magit-root-section))
    ((commit stash branch)
     (call-interactively 'magit-diff-show-or-scroll-up))
    (t
     (call-interactively 'magit-section-toggle))))

;; New S-TAB
(defun magit-section-toggle-or-show-diff-down ()
  (interactive)
  (magit-section-case
    ((magit-root-section))
    ((commit stash branch)
     (call-interactively 'magit-diff-show-or-scroll-down))
    (t
     (call-interactively 'magit-section-cycle-global))))
```

**Comment by tarsius** [comment]
Unless `SPC` is unavailable, I don't really see a need for this. So I think this should go into `evil-magit`/Spacemacs instead.

Even then, this would be a rather confusing change. If `TAB` fails to expand, then its easy to conclude that there is nothing to expand, but if it instead creates or scrolls another buffer, that could be confusing enough to be reported as a bug.

**Comment by justbur** [comment]
@tarsius That's fair. I'm not sure about it either, which is why I asked. With SPC available as you said, I think the current behavior is probably best. Thanks
