### ISSUE TITLE
silent failure when cherry picking or committing whitespace only changes

### ISSUE THREAD

**Issue by fommil** [magit/magit#2577]
This could very well be a result of the ancient version of git (2.1) that I have to use on Windows 7.

If I make a whitespace change (or cherry pick a whitespace commit) then nothing happens and the commit is never saved to the branch.

On the command line, the user must respond "y" to acknowledge that they are committing whitespace changes. Perhaps a git process is getting lost?

**Comment by npostavs** [comment]
> On the command line, the user must respond "y" to acknowledge that they are committing whitespace changes. Perhaps a git process is getting lost?

Windows doesn't have ptys, so prompts can't be intercepted. I suppose there must be some git config to avoid this prompt?

**Comment by npostavs** [comment]
> On the command line, the user must respond "y" to acknowledge that they are committing whitespace changes.

I tried this now and I got no prompt. So this must be some setting you have turned on?

**Comment by tarsius** [comment]
`apply.whitespace` and `apply --whitespace` seem relevant, but their documentations don't say anything about the user being asked questions.

**Comment by tarsius** [comment]
Any news on this?

**Comment by fommil** [comment]
nothing yet, I'll report back if I discover anything.
