### ISSUE TITLE
Show log for a line while diffing

### ISSUE THREAD

**Issue by troysurrett** [magit/magit#2588]
As a developer on a team, while doing code review on a branch, sometimes I see a change that seems unjustified or far away from other code which may justify it. Focusing in on the commit that introduced the change would give me a chance to see the commit message and other changes committed with the change under scrutiny.

Currently, I hit `<ret>` then enter magit-blame-mode, and hit `<ret>` again to get this for additions, but a simple deletion requires that I use the shell and run `git log -S "<deleted line>" /path/to/file`. I'd like to be able to hit a single key while diffing and see the commit message and diff for that commit, then hit `q` to return to the diff once I'm satisfied.

**Comment by tarsius** [comment]
I'll look into this eventually but probably not anytime soon. I do plan some big changes in the "jump to other representation and/or version of this thing" department, but this will require some big changes because the code that does these things currently isn't very robust. So I am afraid until v3 I won't get around to implement such things.

**Comment by tarsius** [comment]
I have implemented something *similar*. You can now press `C-c C-t` in a hunk (or `C-c M-g t` in a file-visiting buffer) to get a `-L :definition-at-point:this-file` log. I am not sold on the key binding. Also this is a rather optimistic implementation at point, it relies on Emacs as well as Git being able to determine the correct definition. For some languages Git can do that out of the box - for others it has to be taught how to do that. E.g. for lisp: 

```
[diff "sexp"]
	xfuncname = "^\\(.*$"
```

You can also trace an explicit line range, but that currently is only possible from file-visiting buffers, so from a diff you would have to first use `RET`, before marking some lines and then `C-c M-g l`.
