### ISSUE TITLE
Pushing a newly cloned branch puts commits on the wrong upstream branch

### ISSUE THREAD

**Issue by nrnrnr** [magit/magit#2591]
I'm relatively new to magit.  Very happy with it, but I have now shot myself in the foot twice, through the following scenario:

1. Used magit to clone and checkout branch `brackets` from branch `adt`
2. Created many find commits on branch `brackets`
3. Attempted to push using `P`---when prompted where to push to, answered `origin`
4. Received an error message that I didn't completely understand, but to the effect of, "D'oh! There is no upstream branch at `origin` corresponding to `brackets`."
5. Responded by dropping down to the command line to do `git push -u origin brackets`

The real problem here: **the commits on the `brackets` branch got pushed to the upstream `adt` branch.**  This was a Very Bad Thing.   (After some searching, I was able to recover by using `git update-ref` on the remote repo.)

What I would like to see happen here is one of two things:

- Magit could offer to create the upstream branch for me, as with `git push -u`
- Magit could squawk and refrain from pushing any commits

**Comment by tarsius** [comment]
Are you using the latest Magit and what's the full key sequence you used to push, <kbd>P u</kbd>, <kbd>P p</kbd>, or something else?

**Comment by tarsius** [comment]
Also please read http://magit.vc/manual/magit/Branching.html and  http://magit.vc/manual/magit/Pushing.html. <kbd>P p</kbd> should actually do what you wanted to do - push to a remote using the same branch name on the remote as what is the name of the branch locally.

And if the push remote is not configured yet, then it will ask you which remote should be used as the push remote for the current branch. From your description it sound like that's what happened, but without the error message you got, it's hard to tell.

Also are your sure that (3) pushed to the wrong branch and not (5)?

**Comment by nrnrnr** [comment]
Function `magit-version` reports `Magit 20151008.1042, Git 2.1.4, Emacs 24.4.1`.  It's quite possible I need to upgrade; I no longer recall how I installed Magit, but the version number suggests perhaps the github repo.

My popup is offering `P P` not `P p`.  

Yes I am sure that (3) pushed to the wrong branch and not (5).

I will figure out how to update to the latest version, and then I will try to duplicate the problem.  I'm pretty sure I created the branch using `b B` (create and checkout), which is not mentioned on the manual page to which you referred to me.

If I am able to duplicate the problem using the latest version, I will post another comment to this thread.

**Comment by tarsius** [comment]
> I no longer recall how I installed Magit, but the version number suggests perhaps the github repo.

No that means that you installed it from Melpa (non-stable) using `package.el`.

> Yes I am sure that (3) pushed to the wrong branch and not (5).

What happened, and that took several other users by surprise when I made that change, is that creating a branch using Magit started to set the starting-point as the new branches upstream branch. The push command then pushed to that configured upstream (like it would previously have done too).

After several users reported that this took them by surprise I added a safety net in the form of a prompt which informed users about what was going to happen when pushing. And later I implemented a completely new pushing interface, which is described in the documentation I linked to.

But you are using a much older version from even before I added the intermediate safety net. You should indeed update. The new push popup will tell you where each key will push to, which should make it much more unlikely that you push somewhere you did not intend.

**Comment by nrnrnr** [comment]
I have upgraded.  Wow!  Lots of new key combinations.

I really, really like magit and am recommending it to all my friends.  But I wasn't expecting this much churn in the user interface.  Ah well, I will cope.

Given how much has changed, I think it is pointless to try to reproduce the problem.  If Magit should happen to surprise me again in the future, I will be sure to upgrade to the latest version before filing any kind of issue.

Thank you for the very, very, very useful tool.  I particularly like that the magit window enables me to visualize a lot of important state, including stashes.  Well done!

**Comment by tarsius** [comment]
> But I wasn't expecting this much churn in the user interface. Ah well, I will cope.

Yeah, that wasn't particularly well received by some users. But I feel it was necessary because the functionality also changed a lot - some muscle memory had to be sacrificed. Anyway in the making of the latest release no key bindings were harmed in the making of the latest release, and I intend to keep future changes to a minimum.

**Comment by nrnrnr** [comment]
> I feel it was necessary 

No worries!  If you're not free to break backward compatibility, your hands are tied.  Especially something like magit, parts of which have not been done before.
