### ISSUE TITLE
re-label some of the popup actions

### ISSUE THREAD

**Issue by pvinis** [magit/magit#2594]
Hello. i use bisect for as bad/good for finding when something broke, but i also use it as earlier/later for finding when something was added. for my terminal, i have `bsb` mapped to `bisect bad`, `bsg` mapped to `bisect good`, `bse` mapped to `bisect bad` and `bsl` mapped to `bisect good`.

In magit, in the popup for bisect, I would like to re-label the `b` action to Bad/Earlier and the `g` to Good/Later.
How can I do that?

**Comment by kyleam** [comment]
You should be able to do that with something like

```
(magit-define-popup-sequence-action 'magit-bisect-popup
    ?b "Bad/Earlier" #'magit-bisect-bad)
(magit-define-popup-sequence-action 'magit-bisect-popup
    ?g "Good/Later" #'magit-bisect-good)
```

[Please ask help questions through one of the channels mentioned in the README.]
