### ISSUE TITLE
Broken behaviour with diff-hl

### ISSUE THREAD

**Issue by Balooga** [magit/magit#2598]
I am experiencing an issue using both Magit and diff-hl.  I have created a ticket in the diff-hl repo reporting this.  Attempting to load a file checked into Git causes the following errors;

> File mode specification error: (error "Lisp nesting exceeds 'max-lisp-eval-depth'")
> Error in post-command-hook (magit-auto-revert-mode-check-buffers): (error "Lisp nesting exceeds 'max-lisp-eval-depth'")

https://github.com/dgutov/diff-hl/issues/65

**Comment by npostavs** [comment]
Note: seems to occur on OSX only (I could not reproduce on GNU/Linux, and see https://github.com/dgutov/diff-hl/issues/65#issuecomment-201685931).

**Comment by tarsius** [comment]
Well, I'm gonna assume it is indeed the same issue for now. @Balooga please give me a hand with https://github.com/magit/magit/issues/2295#issuecomment-202459908.
