### ISSUE TITLE
Reference manager issues when symbolic references are present

### ISSUE THREAD

**Issue by phil-s** [magit/magit#2602]
A word of warning up front: You can trash your actual branch references so easily using `git symbolic-ref` that I suggest using this `git-branch-alias` script in order to use aliases safely: http://www.mail-archive.com/git%40vger.kernel.org/msg49171.html (edit: or the newer should-be-POSIX-compatible version here: http://stackoverflow.com/a/23532744 ).

That warning out of the way... Symbolic references can be used to create branch name aliases, but magit's reference manager exhibits problems when they are present.

In many cases the reference manager errors out entirely, leaving only what it had processed thus far in its buffer. For me this includes when the name of a reference is alphanumerically first in the branch list (in which case the buffer is left empty, save for the "Branches" heading).

Curiously enough, the reference manager sometimes works when references appear elsewhere in the branch listing, only leaving an empty line where the reference would be.

**Comment by tarsius** [comment]
I didn't know that some people put symbolic refs into `.git/refs/`, except for `origin/HEAD` and such. When is that useful? Why don't you put them in `.git`, I taught that's what we are supposed to do.

Anyway as a quick fix I taught `magit-insert-local-branch` to ignore symbolic refs. We might still teach it to instead display something useful. But `git branch` itself doesn't really seem to do that either:

```
$ git symbolic-ref refs/heads/FOO refs/heads/master
$ git branch 
  FOO -> FOO
* master
$ git branch -vv                                         
  FOO    -> FOO
* master 804131c [origin/master] use font-lock-flush instead of font-lock-ensure
```

**Comment by tarsius** [comment]
Is silently skipping the symbolic refs good enough are do you want something to be displayed? What, and what git command has to be run to get that?

**Comment by phil-s** [comment]
For my purposes at least, silently skipping symbolic refs is fine. In magit I'm perfectly happy to interact with the actual branch rather than its alias because (unlike at the command line) there's no extra typing involved.

Personally I use symbolic refs a lot because my real branch names are frequently long (which makes them a pain to type in full) and beginning with a issue number (which makes auto-completion difficult), and so short aliases are often very useful. That script uses .git/refs because that's what was shown in http://stackoverflow.com/a/549949 when I first went looking for a way to create aliases.

Mayyybe it would be nice if magit displayed any symbolic references to branch foo alongside the "foo" in the Magit Refs buffer?

**Comment by phil-s** [comment]
In your example output, `FOO -> FOO` should read `FOO -> master`. Was that a typo, or is that what you're actually seeing? (And maybe hence why you said it didn't display anything useful?)

**Comment by tarsius** [comment]
I really do see `FOO -> FOO` and the file contains `ref: refs/heads/master`. This is with v2.7.2, so maybe this is a regression. But `branch -r` shows `remotes/origin/HEAD -> origin/master`, and so does `branch -a`, which for some reason doesn't show FOO at all.

I'll consider displaying the respective symbolic refs on the same line as the respective refs (or otherwise not just skipping them), but I don't consider this a high priority and probably won't get to it soon.

**Comment by phil-s** [comment]
Yes, surely a regression. I used to use this with 1.7.12.4 and am currently using 2.5.4, and have never seen that issue.

> I don't consider this a high priority and probably won't get to it soon.

All good. Your quick fix has dealt with the important bit. Thanks again!

**Comment by phil-s** [comment]
FYI, in case it affects anything you do in magit... While reviewing release notes for relevant changes, I learned that, up until git v2.6.5, the exit status from `git symbolic-ref` when *creating* symrefs has always been `0`, even if the command failed. "This appears to have been broken since the beginning of time" says the commit message for 3e4068ed90fd3c6f24303560113aae6dbb758699

**Comment by tarsius** [comment]
Symbolic refs are now shown alongside branches similar to how `git branch -v` does it. The used section type is simply `commit`. In other words no special features are associated with these sections.

**Comment by phil-s** [comment]
Thank you tarsius, that works perfectly.
