### ISSUE TITLE
Color codes possibly break status buffer

### ISSUE THREAD

**Issue by dredozubov** [magit/magit#2603]
Screenshot shows how looking list of staged files in magit on my machine:
https://www.dropbox.com/s/4f6e3eni3g0k0r0/Screenshot%202016-03-28%2013.42.48.png?dl=0

Here's the git configuration changes that caused this:
https://github.com/dredozubov/dotfiles/commit/5298e2ee745605d12442abf8a62866fe7fb69aba

Basically it changes the diff coloring and use diff-highlight that's distributed with recent git versions.

It looks like magit parses the output that's not completely stripped from color codes or something similar.

**Comment by tarsius** [comment]
```diff
 [color]
-	ui = true
+	ui = always
```

Revert that. `color.ui=true` means "use colors when it makes sense", while `color.ui=always` means "use colors even when it doesn't make any sense" ;-)

But if you actually need that for some other tool, then you can always override variables just for Magit using `magit-git-global-arguments`.

**Comment by tarsius** [comment]
> It looks like magit parses the output that's not completely stripped from color codes or something similar.

Stripping the control sequences would be one approach, but a very costly one. So we don't do that. Appending `("-C" "color.ui=true" "-C" "color.diff=true")` would be another option but that would be a major when viewing backtraces for completely unrelated defects which happen to involve calls to git. So we won't do that either.

But you are not the first who had this problem. I will add something to the FAQ.

**Comment by dredozubov** [comment]
@tarsius thank you for providing the solution!
