### ISSUE TITLE
Don't collapse file after staging/discarding hunk

### ISSUE THREAD

**Issue by dstcruz** [magit/magit#2606]
In a magit status buffer:
 - Expand a file that has more than one hunk worth of changes (by pressing TAB on it)
 - Traverse to a desired hunk
 - Discard the hunk

The current behavior is that, after confirming with the user, the hunk is discarded/staged and the current expanded file is collapsed.

It seems that it would be very helpful to keep the currently expanded file expanded, as it is very likely that there are other nearby hunks of interest.

**Comment by tarsius** [comment]
That's not supposed to happen, the file section should remain expanded. What Magit version are you using? Are you discarding staged or unstaged changes?

**Comment by npostavs** [comment]
Possible dup of #2388? Does increasing `magit-diff-expansion-threshold` help?

**Comment by dstcruz** [comment]
I'm using:
Magit 20160331.1149, Git 2.8.0.windows.1, Emacs 24.5.1, windows-nt

**Comment by npostavs** [comment]
Does increasing `magit-diff-expansion-threshold` help?
