### ISSUE TITLE
commit.gpgsign = true also signs wip mode commits

### ISSUE THREAD

**Issue by blaenk** [magit/magit#2609]
I have `commit.gpgsign = true` in my gitconfig and I've noticed something and I'm wondering if it's just me:

* if I save changes to a file that is tracked by git, I'm immediately prompted for my gpg passphrase
* if I stage changes in magit-status, I'm immediately prompted for my gpg passphrase

I have no idea what may be causing this. I don't think it's my gpg setup. I have gpg-agent running and it does remember my passphrase for a while when I enter it. What I describe above is in the scenario where gpg-agent just started and so doesn't have the passphrase in its cache. The thing is I don't understand why these actions would require my gpg passphrase. I would have imagined it would only be necessary at the time of committing changes, no? For example, I staged some changes with `git add` in the terminal and I wasn't prompted for my gpg passphrase.

The only seemingly related thing I found was #1647 but I'm not sure if it's relevant.

**Comment by blaenk** [comment]
I'm pretty sure that it has to do with the `wip` features. I removed these lines and it stopped nagging me:

``` elisp
(magit-wip-after-save-mode)
(magit-wip-after-apply-mode)
(magit-wip-before-change-mode)
```

I guess each of those things create commits for the little changes, that's the whole point, but an unfortunate consequence of `commit.gpgsign` is that it ends up signing those too.

I looked at `git help commit` and found that it's possible to ignore that setting for specific invocations of `git commit`:

```
--no-gpg-sign
    Countermand commit.gpgSign configuration variable that is set to force each and every
    commit to be signed.
```

Any chance we can introduce an option to use `--no-gpg-sign` for the "wip" modes commits?

**Comment by blaenk** [comment]
Also, it would be very nice if magit detected that `commit.gpgSign` was set to `true` and would automatically highlight that setting in the commit popup, so that someone could then press `=S` manually to have the effect of `--no-gpg-sign`.

**Comment by tarsius** [comment]
When creating stashes and wipref commits `--no-gpg-sign` is used now. I haven't added that argument to any popup - the commit popup does not affect these special commits, so it would only affect the commits which you always want to sign.

**Comment by blaenk** [comment]
Thanks! It's much appreciated.

I'm not sure I understand this part though:

> I haven't added that argument to any popup - the commit popup does not affect these special commits, so it would only affect the commits which you always want to sign.

I think it's my fault for mixing these two separate things up in the same issue. I mean this as a separate feature.

What I meant was, separate to this issue, if magit were capable of realizing that `commit.gpgsign` was true, which means that all commits are always signed. Then, since all commits are always signed anyways, `=S` would already be "bolded" (conveying to the user that it's on), so that pressing `=S` would _then_ mean `--no-gpg-sign`, to exempt the commit from being signed.

It's just an idea. I think like it would be pretty intuitive.

**Comment by blaenk** [comment]
I created #2610 to keep these features separate.

**Comment by blaenk** [comment]
I'm noticing this happening again (?). I've updated to the latest magit. I have this:

``` elisp
  (magit-wip-after-save-mode)
  (magit-wip-after-apply-mode)
  (magit-wip-before-change-mode)
```

Let me know if there's more information I could provide.

**Comment by blaenk** [comment]
I have no idea, but perhaps one of the `magit-update-ref`'s was missed? Specifically [here](https://github.com/magit/magit/blob/master/lisp/magit-wip.el#L209-L216).

**Comment by tarsius** [comment]
Ah, sorry about that. I've fixed this one too now.

**Comment by blaenk** [comment]
Thanks!
