### ISSUE TITLE
git-commit: "Second line is not empty" if it doesn't exist

### ISSUE THREAD

**Issue by CyberShadow** [magit/magit#2611]
Attempting to commit with a commit message consisting of a single line, with no newline at the end, produces a spurious "Second line is not empty" message.

Normally, git will place some comments at the bottom of `COMMIT_EDITMSG` before launching the editor, describing the state of the index and working directory. However, that will not happen if a custom `prepare-commit-msg` hook exists.

To reproduce, attempt to create a commit with a commit message consisting of a single line, with no newline at the end.

Git seems to add a newline at the end either way, so there doesn't seem to be any harm with leaving `COMMIT_EDITMSG` without a trailing newline.

**Comment by npostavs** [comment]
Modifying `git-commit-summary-regexp` to not match an empty 2nd line (and then don't expect an empty 2nd line in `git-commit-check-style-conventions`) seems to fix it: https://github.com/magit/magit/compare/np/nonempty-2nd-line

**Comment by tarsius** [comment]
Works for me too. I've applied the change. Thanks!

**Comment by CyberShadow** [comment]
Thanks all!
