### ISSUE TITLE
git-commit-buffer-message does not remove diffs when committing with the --verbose flag

### ISSUE THREAD

**Issue by zmwangx** [magit/magit#2612]
`magit-version`: `Magit 20160406.121, Git 2.8.1, Emacs 24.5.1, darwin`.

Consider running `git commit --verbose` within Magit via `c -v c`. An example commit message would be

```diff
Add file tmp

Lorem ipsum.

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch master
# Your branch is up-to-date with 'origin/master'.
#
# Changes to be committed:
#	new file:   tmp
#
# ------------------------ >8 ------------------------
# Do not touch the line above.
# Everything below will be removed.
diff --git a/tmp b/tmp
new file mode 100644
index 0000000..f75ba05
--- /dev/null
+++ b/tmp
@@ -0,0 +1 @@
+Hello, world.
```

Now `M-: (git-commit-buffer-message)`, and the output is

```diff
"Add file tmp

Lorem ipsum.

diff --git a/tmp b/tmp
new file mode 100644
index 0000000..f75ba05
--- /dev/null
+++ b/tmp
@@ -0,0 +1 @@
+Hello, world.
"
```

As you can see, the comments are stripped, but diffs below the line `# ------------------------ >8 ------------------------` are kept. This will later be saved into `log-edit-comment-ring`, and affect future invocations of `git-commit-prev-message` and `git-commit-next-message`.

**Comment by tarsius** [comment]
I'll look into this.

**Comment by tarsius** [comment]
(@npostavs @kyleam which isn't to say that I would mind if you beat me to it - just letting op know that I intend to do something about this.)

**Comment by kyleam** [comment]
> which isn't to say that I would mind if you beat me to it 

I'll look into it today.

**Comment by zmwangx** [comment]
It works, thanks :+1:
