### ISSUE TITLE
Emacs hangs when expanding long line file hunk

### ISSUE THREAD

**Issue by edvorg** [magit/magit#2613]
Magit 20160402.2219, Git 2.7.4, Emacs 24.5.1, darwin

steps:
1) create a file with very long line or use the one from attach
[keys-arrays-method.clj.zip](https://github.com/magit/magit/files/209487/keys-arrays-method.clj.zip)
2) stage file
3) open magit
4) move to file entry
5) hit tab

Actual behaviour
- emacs hangs

Expected behaviour
- emacs doesn't

**Comment by tarsius** [comment]
I don't think it hangs - it just takes very very long. That's a common issue in Emacs, try to even just move to the end of that line - that also takes forever.

There's probably not much I could do about this. I suggest you avoid expanding such files (how meaningful would it actually be to look at the diff for this?). However  when you commit then all staged files are automatically expanded in a separate diff buffer, but that can be aborted by pressing `C-g`.

**Comment by edvorg** [comment]
Isn't it possible to cut long files on magit's side? Currently it break user's workflow, because one has to kill emacs and start again. Unfortunately C-g doesn't help in my case on cocoa emacs..

**Comment by tarsius** [comment]
I am afraid the cost of that would be to high. Moderately larger diffs are already slow and having to peak into each and every modified file to determine whether we might want to forgo displaying it altogether would be a price we would have to pay all the time.

In the long run I plan to wash asynchronously which should help a lot in cases like this. See https://magit.vc/manual/magit/Performance.html.

**Comment by edvorg** [comment]
I see, thank you for explanation!

**Comment by tarsius** [comment]
Sorry I cannot do anything in the short run!
