### ISSUE TITLE
Add support for worktree

### ISSUE THREAD

**Issue by phillord** [magit/magit#2614]
It would be nice it magit supported git worktree. In the branch manager, instead of "Create and Checkout", something like "Create and make new Worktree", which would prompt for the appropriate directory.

**Comment by tarsius** [comment]
I'll add something like that.

**Comment by phillord** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> I'll add something like that.


Thank you!

**Comment by tarsius** [comment]
Closing in favor of pr #2644.

**Comment by phillord** [comment]
Thank you! Will check out the new functionality as soon as I can.
