### ISSUE TITLE
support for git archive

### ISSUE THREAD

**Issue by simon-f** [magit/magit#2615]
It would be great if magit would support `git archive` ([git-archive](https://git-scm.com/docs/git-archive)). 

Also, since I am new on here: are there any design policies on which git features magit wants to support or is it all just a question of somebody implementing a particular feature?

**Comment by tarsius** [comment]
There's no such policy but sometimes things do get rejected, so it's always a good idea to ask before starting to work on something. When something does get rejected then it's usually an extension to some existing functionality (on grounds of it being considered a complication, not an improvement). Completely new and additionally fairly self-contained features like what you are suggesting have a high change of being merged. However there might be some nitpicking ;-)

Personally I don't have much need for this. I would think that if one uses this feature, then that should happen in an automated fashion, i.e. in a makefile to build a release archive, in which case Magit support doesn't really help much. But there are probably use cases where it makes sense to regularly enough use this feature to be inconvenienced by having to drop to the shell.

So feel free to implement this. It should be probably come in form of a popup.

**Comment by tarsius** [comment]
It's unlikely that I will ever implement this or encourage someone else to do so; so I am closing this.
