### ISSUE TITLE
git-commit-mode failed to display the last line of change correctly

### ISSUE THREAD

**Issue by xuhdev** [magit/magit#2616]
After adding `(global-git-commit-mode)` to my init.el, editing a file to change its last line in a git repository, and committing on the command line with `git commit -a --verbose`, then the diff does not display correctly for the last line. The screenshot below shows the situation. This issue does not exist if committing with `magit-commit`.

![emacs-git-commit](https://cloud.githubusercontent.com/assets/325476/14406174/b8b5b7ea-fe54-11e5-914a-7a63680da840.png)

Version: Magit 2.6.0-12-g71ec624a3ad9-dirty, Git 2.1.4, Emacs 24.5.1, gnu/linux

**Comment by tarsius** [comment]
It looks like this buffer's major-mode is `diff-mode`. A screenshot which includes the complete window including the mode-line might be helpful to diagnose what's going on.

**Comment by xuhdev** [comment]
Here is the whole frame...

![emacs-git-commit](https://cloud.githubusercontent.com/assets/325476/14406316/4e956da6-fe59-11e5-9ff3-9db0ed7124a6.png)

**Comment by tarsius** [comment]
Ah right, we use code from `diff-mode` in that case. That explains why the diff doesn't look like diffs usually look in magit. I'll try to have a look soon. I am guessing it has something to do with a missing trailing newline.
