### ISSUE TITLE
magit-git-executable magit-cygwin-mount-points interaction

### ISSUE THREAD

**Issue by ilohmar** [magit/magit#2619]
I use magit on NTEmacs with git for windows (set via a full path in `magit-git-executable`), but I have cygwin's git first in my path (for reasons unrelated to magit).  The `magit-cygwin-mount-points` default value uses a plain "git" call to check the path of the executable, gets the path to the cygwin git, and (as I do use cygwin at all) populates the mount points variable.  Therefore some file name arguments are later transformed for cygwin git, breaking, eg, stash saving.  The problem disappears when I manually set `magit-cygwin-mount-points` to nil.

I think it would make sense to use `magit-git-executable` (instead of "git") in the `defcustom` default for `magit-cygwin-mount-points` --- then those who set the former correctly do not have to mess with the latter.  It took me quite some time to find the issue because it's deep in the git interface and I never even thought of the cygwin git (after setting the executable).

Does that make sense?  I realize that the windows/cygwin issues are annoying... hardly a week passes without me fighting one of them (not exclusively in magit, of course)...

**Comment by npostavs** [comment]
> Does that make sense?

Yes. There is some complication because we try to use the `libexec/git-core/git` executable for performance and that requires some extra path settings. I've pushed a fix to [np/cygmount-init], still need to check that it doesn't break with Git for Windows, Cygwin, or Msys2 git...

[np/cygmount-init]: https://github.com/magit/magit/compare/np/cygmount-init

**Comment by npostavs** [comment]
> I've pushed a fix to np/cygmount-init, still need to check that it doesn't break with Git for Windows, Cygwin, or Msys2 git...

Seems to work okay, I've pushed to `master` (50a7f49b8f9e9f42f02aa3b2304f5c9e75267885).
