### ISSUE TITLE
Merge but don't commit should probably set the --no-ff flag

### ISSUE THREAD

**Issue by cpaulik** [magit/magit#2620]
Magit merge but don't commit `m n` actually creates the commits if the merge is possible through fast forwarding. This can be solved by setting the `--no-ff` flag manually but my guess would be that this should be the default since it is quite confusing otherwise.

`Magit 20160414.251, Git 2.8.0, Emacs 24.5.1, gnu/linux`

**Comment by tarsius** [comment]
Indeed it's rather silly that `git merge --no-commit` does that. I've added a workaround.

**Comment by kyleam** [comment]
Doesn't the same logic apply to `magit-merge-editmsg`?

**Comment by tarsius** [comment]
Fixed that one too. I should have checked, but I just couldn't imagine that it would behave that way. @cpaulik could you please bring this to the intention of the Git maintainers? I cannot imagine a justification which would allow classifying this behavior as anything but a bug.

**Comment by tarsius** [comment]
Oh, and it might actually be a regression. I am pretty sure I have used `magit-commit-edit-msg` to merge rebased feature branches, so that I could add `[#NNNN]` to the commit message. Without ever seeing this behavior.

**Comment by kyleam** [comment]
> Oh, and it might actually be a regression. 

Hmm, looks like it has at least been around since 2014, because back then I
[advised magit-commit-edit-msg](https://github.com/kyleam/emacs.d/commit/f3cbf040687265c01f26057b3b3b1f0867b982ff) to use the `--no-ff` flag.

**Comment by cpaulik** [comment]
@tarsius Thanks for the quick fix. I've sent an email to the git mailing list about it.
