### ISSUE TITLE
Um, version 9999?

### ISSUE THREAD

**Issue by mdorman** [magit/magit#2621]
This seems like an inadvertent error, and it's confusing code that's trying to figure out the latest melpa-stable release: https://github.com/magit/magit/releases/tag/9999

Maybe it could be removed?

**Comment by tarsius** [comment]
Someone, e.g. @npostavs, @kyleam, or me, managed to push some old tags again, which have been removed a long time ago.

Luckily Melpa-Stable did not actually pick this up yet, as far as I can tell.

To prevent that from happening again could you please run <kbd>t p</kbd> in all `magit` clones.

**Comment by kyleam** [comment]
I did have that tag locally, so it could very well have been me (sorry), though I don't know when I would've pushed tags.

**Comment by npostavs** [comment]
Ah sorry, it was definitely me, I recently added `push.followTags = true` to my git config (seemed like a good idea at the time).

```
  0 git … push -v upstream np/cygmount-init:refs/heads/np/cygmount-init
Pushing to git@github.com:magit/magit.git
Counting objects: 9, done.
Writing objects: 100% (9/9), 1.50 KiB | 0 bytes/s, done.
Total 9 (delta 3), reused 4 (delta 0)
To git@github.com:magit/magit.git
 * [new branch]      np/cygmount-init -> np/cygmount-init
 * [new tag]         9999 -> 9999
 * [new tag]         magit_0.5-1 -> magit_0.5-1
 * [new tag]         magit_0.6-1 -> magit_0.6-1
 * [new tag]         magit_0.6.1 -> magit_0.6.1
 * [new tag]         magit_0.7 -> magit_0.7
updating local tracking ref 'refs/remotes/upstream/np/cygmount-init'
```

**Comment by tarsius** [comment]
It's okay ;-)

**Comment by mdorman** [comment]
Thanks all!
