### ISSUE TITLE
magit-discard fails

### ISSUE THREAD

**Issue by chris-martin** [magit/magit#2623]
### How to reproduce

In a file that has an unstaged diff:

* `C-x v =`
* `k`

The `*vc-diff*` buffer is erased, and the minibuffer displays the message

> Error running timer: (error "Can't find the beginning of the file")

And no change is made to the file.

### Other info

`magit-version`: `Magit 20160219.1702, Git 2.7.4, Emacs 24.5.2`

**Comment by kyleam** [comment]
I can reproduce this, but vc is not part of Magit.  Please send a
report to Emacs's bug list.

**Comment by chris-martin** [comment]
I'm confused; I thought `k` was bound to `magit-discard`?

**Comment by kyleam** [comment]
I think you're mixing up your diff buffers.  What does `C-h k` report
for `k`?  `diff-hunk-kill`?

**Comment by chris-martin** [comment]
Sorry, yeah, you're right. I didn't know Emacs came with VC tools, I just thought it was all from magit. Thanks.

**Comment by johnmastro** [comment]
This isn't directly related to your question, but it may be of interest anyway. Magit has `magit-file-popup`, which will let you get at some of its functionality without going through `magit-status`.

It's not autoloaded or bound to a key by default, but you could put something like this in your init file if you want to check it out:

```emacs-lisp
(autoload 'magit-file-popup "magit"
  "Popup console for Magit commands in file-visiting buffers." t)

(global-set-key (kbd "C-c M-g") #'magit-file-popup)
```

With that, `C-c M-g d d` will diff the current buffer's file against `HEAD`.

**Comment by chris-martin** [comment]
@johnmastro That is interesting, thanks.

**Comment by chris-martin** [comment]
When I run `magit-diff` and then try to use `k` from that view, I still just get an error message:

> Cannot discard committed changed

even though all of the diffs it shows are uncommitted.

**Comment by kyleam** [comment]
I'm unable to reproduce your issue.  When I call `magit-file-popup`,
and then `du` in a file unstaged changes, I can discared those changes
with `k`.  Can you open a new issue with a recipe to reproduce?

**Comment by johnmastro** [comment]
I see the same error as @chris-martin so I opened issue #2627 for it.
