### ISSUE TITLE
Cannot save stash using Magit 2.6.1

### ISSUE THREAD

**Issue by jwiegley** [magit/magit#2624]
Hello, I recently upgraded from 2.5.0 to 2.6.1.  In a fresh Emacs loading only Magit, this is error I receive on a Mac running 10.10 and Git 2.8.0:

```
Cannot create temporary name for prefix: Bad file descriptor, index.magit.
```

It worked with 2.5.0 in the same environment (I'm using the Emacs 25 pretest).

**Comment by tarsius** [comment]
Can you reproduce with just `emacs -Q` and `(make-temp-name "index.magit.")`? If so, then I would think this is a bug in Emacs, not Magit.

**Comment by jwiegley** [comment]
Thanks @tarsius, this isn't a Magit problem.
