### ISSUE TITLE
Make it possible to run "git rebase" without any params

### ISSUE THREAD

**Issue by Havner** [magit/magit#2625]
With a rebase-popup it would be nice to have just "git rebase", eg:

```
(defun magit-rebase-notarget (args)
  (interactive (list (magit-rebase-arguments)))
  (magit-run-git-sequencer "rebase"))
(magit-define-popup-action 'magit-rebase-popup ?r "Rebase" 'magit-rebase-notarget)
```

Current git versions behave differently when you just type "git rebase' on a branch that has an upstream set contrary to specifying the same upstream explicitly in command line (e.g. magit-rebase-onto-upstream)

**Comment by Havner** [comment]
[magit-rebase.diff.txt](https://github.com/magit/magit/files/229958/magit-rebase.diff.txt)

**Comment by Havner** [comment]
[magit-rebase.diff.txt](https://github.com/magit/magit/files/229960/magit-rebase.diff.txt)

**Comment by Havner** [comment]
[magit-rebase.diff.txt](https://github.com/magit/magit/files/229969/magit-rebase.diff.txt)

**Comment by tarsius** [comment]
> Current git versions behave differently when you just type "git rebase' on a branch that has an upstream set contrary to specifying the same upstream explicitly in command line (e.g. magit-rebase-onto-upstream)

This?:

>       If <upstream> is not specified, the upstream configured in
>       branch.<name>.remote and branch.<name>.merge options will be used (see
>       git-config(1) for details) and the --fork-point option is assumed. If
>       you are currently not on any branch or if the current branch does not
>       have a configured upstream, the rebase will abort.

If so, then adding `--no-fork-point` could also be an option:

>       --fork-point, --no-fork-point
>           Use reflog to find a better common ancestor between <upstream> and
>           <branch> when calculating which commits have been introduced by
>           <branch>.
>
>           When --fork-point is active, fork_point will be used instead of
>           <upstream> to calculate the set of commits to rebase, where
>           fork_point is the result of git merge-base --fork-point <upstream>
>           <branch> command (see git-merge-base(1)). If fork_point ends up
>           being empty, the <upstream> will be used as a fallback.
>
>           If either <upstream> or --root is given on the command line, then
>           the default is --no-fork-point, otherwise the default is
>           --fork-point.

Could you please make an example (with diagram) of when not using the fork point would be useful.

**Comment by Havner** [comment]
> This?:

Yes, that's it. I was actually not aware that there is a separate option for that (of course there has to be). And I checked, this is the reason for the different behaviour.

> If so, then adding --no-fork-point could also be an option:

You mean "adding --fork-option".

> Could you please make an example (with diagram) of when not using the fork point would be useful.

I can't make an exmaple when --no-fork-option would be more useful, as my long standing work flow always uses --fork-option (implied with 'git rebase'). And I can make you an example when using it is actually better.

```
$ git init .
Initialized empty Git repository in /home/havner/repo/.git/
$ echo test > test.txt
$ git add test.txt
$ git commit -a -m 'initial'
[master (root-commit) 803b87c] initial
 1 file changed, 1 insertion(+)
 create mode 100644 test.txt
$ echo new >> test.txt 
$ git commit -a -m 'new'
[master 7a84a79] new
 1 file changed, 1 insertion(+)
$ git branch new
$ echo final >> test.txt 
$ git commit -a -m 'final'
[master 2629744] final
 1 file changed, 1 insertion(+)
$ git branch final
```
We have 3 commits now:
```
I      N      F
* ---> * ---> *
```
Now, let's modify the commit "new" (N)
```
$ git checkout new 
Switched to branch 'new'
$ echo another-new >> test.txt 
$ git commit -a --amend --no-edit 
[new 21eb4c7] new
 Date: Thu Apr 21 16:17:18 2016 +0200
 1 file changed, 2 insertions(+)
```
Now we have:
```
I      N      F
* ---> * ---> *
 \     N`
  \--> *
```
We will be able to clearly see the difference with rebasing F
```
$ git checkout final 
Switched to branch 'final'
$ git branch -vv
* final  2629744 [new: ahead 2, behind 1] final
  master 2629744 final
  new    21eb4c7 new
```
Variant 1:
```
$ git rebase -i --fork-point new
```
or:
```
$ git branch -u new
Branch final set up to track local branch new.
$ git rebase -i
```
Variant 2:
```
$ git rebase -i new
```
Variant 1 will try to properly rebase both commits, final and old N only N`.
--fork-point will understand that N` is a derivative of N and will only try to rebase F.
If you ommit -i in both variants, variant 1 will just succeed. Variant 2 will fail because of a conflict. It can also fail because one of the changes after the 'merge' might end up empty. In any case you might have tho N commits after the rebase.

**Comment by tarsius** [comment]
> In any case you might have two N commits after the rebase in the log.

Only if you are not being careful.

In any case, I don't think this distinction is going to matter for most users. In fact it seems to me that `--fork-point` is a bit too smart to be used by default. So I think it is a good thing that Magit does not use it implicitly.

I also don't think `--fork-point` should be added to the popup by default. We need to strike a balance between "this is very important for my work flow" and "there are to many arguments I am never ever going to use", which are both valid arguments coming from different users :-)

So please add this argument in your local configuration as described [in the manual](https://magit.vc/manual/magit-popup/Customizing-existing-popups.html). Maybe you also want to document this [on the wiki](https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands).

**Comment by Havner** [comment]
I never said it should be turned on by default. I said it should be an option to choose from.

**Comment by tarsius** [comment]
Sorry for being too sloppy to avoid misunderstandings.

I wasn't trying to suggest that you are saying that this should be on by default. What I was trying to say is that I do not want to even add this argument in disabled state to the popup for two reasons.

1. For people who do want this argument (enabled or not), it is trivial to do that (marginally harder than creating a "regular key binding").
2. For every argument someone cares deeply about there are others who would only be confused by it. I try to expose only subset of the arguments that might be potentially useful in the popups. This is done to avoid overwhelming users.
