### ISSUE TITLE
on Windows: magit-commit-popup returns error. Buffer is read-only

### ISSUE THREAD

**Issue by sudurais** [magit/magit#2629]
When key 'c' is pressed from magit-status window, it takes to magit-commit-popup buffer and another key 'c' press, it returns error saying 
call-interactively: Buffer is read-only: #<buffer *magit-commit-popup*> [6 times]

key 'a' works for amend. Couldn't find out why only key 'c' doesnt work. Appreciate any help in resolving it. 

Magit 20160425.430, Git 2.8.1.windows.1, Emacs 24.5.1, windows-nt

**Comment by sudurais** [comment]
I changed action key 'c' to 'g' to check if it works. That seems to be working. Now, its c - g key presses. Not sure what is the issue with 'c'.

**Comment by npostavs** [comment]
Sounds like a problem with your configuration. Can you reproduce this from [`emacs -Q`][emacs-Q]? Setting `debug-on-error` to t, and posting the resulting `*Backtrace*` may also be helpful.

[emacs-Q]: http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html

**Comment by sudurais** [comment]
Right. C-h b points to

c               mykie:global-map:c:self-insert-command
