### ISSUE TITLE
magit-diff-hide-trailing-cr-characters is not respected in ediff

### ISSUE THREAD

**Issue by thepickle** [magit/magit#2637]
Title says it all..
Setting `magit-diff-hide-trailing-cr-characters` has no effect in whether ^Ms are shown in ediff mode.

To demonstrate, magit log, navigate to some revision, and hit e (for ediff)

![image](https://cloud.githubusercontent.com/assets/11797552/15026114/cf752ffa-120a-11e6-9054-055b6ed86ece.png)

**Comment by kyleam** [comment]
That variable only influences diffs within Magit.  `magit-ediff-*`
functions set up the Ediff calls and leave the rest to Ediff, so the
`magit-diff-*` settings don't apply.

Perhaps there is an Ediff variable that does what you want.

**Comment by thepickle** [comment]
There does not seem to be any `magit-ediff` configuration variables..  Would this be able to be added?

**Comment by kyleam** [comment]
> There does not seem to be any magit-ediff configuration variables.

I was suggesting that Ediff, not magit-ediff.el, might have
configuration variable related to this.

> Would this be able to be added?

This is related to Ediff, not Magit.  Magit just sets up the
appropriate buffers to feed to Ediff.  If you want this behavior, I
think the Ediff-side is where it should be configured.

**Comment by tarsius** [comment]
Yes, this cannot be fixed by editing Magit files, Ediff has to be modified. Please report this to the Emacs maintainers.
