### ISSUE TITLE
Branch names aren't changed if the file is not reverted

### ISSUE THREAD

**Issue by fice-t** [magit/magit#2642]
Currently, even with `magit-auto-revert-mode` on (as it doesn't revert), buffer mode lines don't change when switching branches and the current file is the same between the branches. I have to manually revert the buffer for it to change the name.

It would be nice if the mode lines were updated regardless of the file content differences between branches whenever changing branches in magit.

Magit version: `Magit 20160506.459, Git 2.5.5, Emacs 24.5.1, gnu/linux`

**Comment by tarsius** [comment]
If just added a FAQ entry about this: https://github.com/magit/magit/blob/master/Documentation/magit.org#the-mode-line-information-isnt-always-up-to-date.

**Comment by fice-t** [comment]
Thanks, that works. Though as you say it isn't fantastic for performance as it checks at an interval.

Is it out of scope for magit to optionally call, for example, `vc-find-file-hook` on relevant buffers after changing branches? That seems to update things appropriately.

**Comment by fice-t** [comment]
@tarsius Would it be feasible to add an "after change branch" hook to deal with this?

**Comment by tarsius** [comment]
Please have a look at [this wiki page](https://github.com/magit/magit/wiki/magit-update-uncommitted-buffer-hook), which I added a few days ago.
