### ISSUE TITLE
Recent magit-display-buffer-traditional commits change behaviour significantly

### ISSUE THREAD

**Issue by sjrmanning** [magit/magit#2646]
I'm not sure if this is the new intended behaviour, but after pulling in the most recent version via MELPA I'm seeing some weird behaviour during commits. I use magit in fullscreen as a single buffer, and when I stage and commit on master I'm seeing first the `magit-diff` window on its own, then after pressing `q` the `COMMIT_EDITMSG` buffer on its own. Previously I'd get both buffers split vertically.

Confirmed that restoring `magit-display-buffer-traditional` to the below restores how it used to function.

```elisp
(defun magit-display-buffer-traditional (buffer)
  "Display BUFFER the way this has traditionally been done."
  (display-buffer
   buffer (if (and (derived-mode-p 'magit-mode)
                   (not (memq (with-current-buffer buffer major-mode)
                              '(magit-process-mode
                                magit-revision-mode
                                magit-diff-mode
                                magit-stash-mode
                                magit-status-mode))))
              '(display-buffer-same-window)
            nil)))
```

If this is an intended behaviour change, how can I get the old behaviour back? I use some `defadvice` hooks to use magit in fullscreen and restore old buffers afterwards, so I was also wondering if that was having an effect, but disabling it didn't seem to help.

**Comment by tarsius** [comment]
That's not the intended behavior. I added it to deal with the really strange case described here #2632. I've now made further changes to limit the effect of the kludge to the case it is supposed to deal with.
