### ISSUE TITLE
What arguments should be passed to magit-push-to-remote ?

### ISSUE THREAD

**Issue by robstewart57** [magit/magit#2652]
Using magit version: Magit 20160512.1510, Git 2.5.5, Emacs 24.5.1, gnu/linux

Following up on this suggestion on reddit:
https://www.reddit.com/r/emacs/comments/4iw8rk/magit_addcommitpush_a_file_on_every_emacs_exit/d323wyr

I have the following code in my init file:

    (require 'magit)
    (defun commit-and-push-todos ()
      (interactive)
      (let* ((default-directory (expand-file-name "org" "~"))
             (todo-file (expand-file-name "TODOs.org" default-directory)))
        (when (magit-anything-modified-p nil todo-file)
          (magit-stage-file todo-file)
          (magit-commit "-m \"TODOs.org update\"")
          (magit-push-to-remote "origin"))))

It appears that all but the last magit commands work. When I look at the status of the git repository, I see that when I run `commit-and-push-todos`, I see that a commt has been made but it has not been pushed. After running this code above, the *Messages* buffer shows:

    progn: Wrong number of arguments: (2 . 2), 1

Which I assume relates to

     (magit-push-to-remote "origin")

What is the correct use of the recently added `magit-push-to-remote` command?

**Comment by tarsius** [comment]
Use `M-x toggle-debug-on-error` to get more insight into the error.

**Comment by tarsius** [comment]
... which will reveal that you are calling `magit-commit` wrong (and `magit-push-to-remote` too, but that you won't see until you fix the first issue.

```lisp
(magit-commit (list "-m" "TODOs.org update"))
(magit-push-to-remote "origin" nil
```

Also these are commands that are only intended for interactive use. You should probably use this instead:

```lisp
(magit-call-git "add" todo-file)
(magit-call-git "commit" "-m" "TODO.org update")
(magit-call-git "push" "origin")
(magit-refresh)
```

**Comment by robstewart57** [comment]
@tarsius  Perfect thank you. Thanks for the correction about how to call the interactive commands. And yes, I understand why the magit-call-git command is more appropriate. Thanks! Closing.

**Comment by jonazzen** [comment]
Oh this is cool can i make it so that it only commit and push if there is file changes?
