### ISSUE TITLE
Typos in 2.7.0 release notes

### ISSUE THREAD

**Issue by phil-s** [magit/magit#2653]
1. With a prefix argument it reads **a the** branch to be configured in the minibuffer instead of using the current branch.

2. Added new command `magit-diff-buffer-file` and new option `magit-diff-buffer-file-locked`.  **The the** value of the option is non-nil, the default, then the command uses a dedicated buffer.

(And while I'm here: Thanks for the new release! Great work, as always.)

**Comment by tarsius** [comment]
Thanks!

**Comment by phil-s** [comment]
Whoops. I should have pointed out that the second one wasn't just a redundant doubled word. I think "The the" should have been "When the".

**Comment by kyleam** [comment]
> "The the" should have been "When the"

Thanks.  Fixed.
