### ISSUE TITLE
`magit-diff-show-or-scroll-up` doesn't scroll stashes?

### ISSUE THREAD

**Issue by phil-s** [magit/magit#2654]
I'm not sure if this is a regression or not. This command still scrolls for the likes of unpulled commits in the status buffer, and commits in the log buffer. With stashes it displays the stash, but doesn't scroll.

If I manually scroll the stash buffer and then repeat the command in the status buffer, it tends to jump the stash to a different position than the one I'd left it in, but then won't move it again.

Tested with Melpa package Magit 20160519.950, Git 2.3.5, Emacs 24.5.1, gnu/linux and no other Emacs config.

**Comment by npostavs** [comment]
Looks like a bug to me, fixed by bfc6183b14d93d7d7aaebe940d856b64c7ba2941, but I'm not entirely sure about the `(concat rev "^2^.." rev)` thing.

**Comment by kyleam** [comment]
> Looks like a bug to me, fixed by bfc6183, but I'm not entirely sure about the (concat rev "^2^.." rev)   thing.

Switching it to `rev` seems right.  I think the old form was for
`magit-diff-stash`.

I believe 3b80c7a (magit-show-or-scroll: use correct range when
showing stash, 2014-04-09) and bbb08e2 (magit-stash-show: new command,
2014-10-05) are the relevant commits.
