### ISSUE TITLE
magit-gerrit-section: Symbol's function definition is void: section

### ISSUE THREAD

**Issue by jdees** [magit/magit#2663]
Hello,

after a lot of debuggin I find that this becomes problematic:

(require 'magit)
(require 'magit-popup)
(require 'magit-gerrit)

If removing (require 'magit-popup) everything runs fine (very difficult to find for me).

The problem I got was: Symbol's function definition is void: section
from magit-gerrit-section in this code snippet:
(-when-let (section (magit-current-section))
(list
(nconc (list it section)
(magit-refresh-get-relative-position))))

I don't know how relevant this is - but not being able to require magit-pop is not really nice. Also caused me some headache.
If you just want to ignore and close it and hope nobody does this also fine ^^.

Used versions latest from melpa, e.g.:
  magit              20160525.1745 installed             A Git porcelain inside Emacs
  magit-gerrit       20160226.130  installed             Magit plugin for Gerrit Code Review
  magit-popup        20160521.1221 installed             Define prefix-infix-suffix command combos

**Comment by npostavs** [comment]
> If removing (require 'magit-popup) everything runs fine (very difficult to find for me).

This sounds like the opposite of what you said in the gerrit issue:

> uncommenting (require 'magit-popup) makes it work again.

---

You didn't explain exactly what you did to trigger the bug on either issue (just evaluating those `require` statements is not enough).

**Comment by jdees** [comment]
go to any git repository:
M-x magit-status
M-x magit-refresh

=> the mentioned error appears

**Comment by npostavs** [comment]
Nothing happens. I guess some configuration of magit-gerrit is also needed?

**Comment by tarsius** [comment]
Let's discuss this on the `magit-gerrit` issue.

**Comment by tarsius** [comment]
Just for the record. The `section` in `(-when-let (section (magit-current-section))` also isn't supposed to be a function. See https://github.com/magnars/dash.el#-when-let-var-val-rest-body.
