### ISSUE TITLE
C-w and M-w don't act nice in magit-blame

### ISSUE THREAD

**Issue by fice-t** [magit/magit#2664]
According to the manual:

`Outside of Magit M-w and C-w are usually bound to kill-ring-save and kill-region, and these commands would also be useful in Magit buffers. Therefore when the region is active, then both of these commands behave like kill-ring-save instead of as described above. `

I think one could consider a file buffer that is being blamed to be a "Magit buffer" in a sense.

Currently M-w does not copy the region if it is being used (it copies the hash unconditionally). C-w in this case is not rebound to `kill-ring-save` but is still the same `kill-region`.

**Comment by npostavs** [comment]
> Currently M-w does not copy the region if it is being used (it copies the hash unconditionally).

Yep, fixed.

> C-w in this case is not rebound to `kill-ring-save` but is still the same `kill-region`.

But due to the buffer being read-only it has the same effect as `kill-ring-save`.

**Comment by fice-t** [comment]
@npostavs Thanks. I was mainly concerned about M-w. C-w did work, but it gave off the warning `Buffer is read-only: #<buffer *<file>*>` each time it was used. That's not really a problem though.

**Comment by npostavs** [comment]
> C-w did work, but it gave off the warning `Buffer is read-only: #<buffer *<file>*>` each time it was used.

Oh, I have `cua-selection-mode` on, so I don't see that warning (it can also be demoted to a message by setting `kill-read-only-ok`).
