### ISSUE TITLE
`magit-revert-buffers` is ignored

### ISSUE THREAD

**Issue by elibarzilay** [magit/magit#2665]
I just updated magit today, and it turns auto-revert-mode globally, again.  I have this bit in my environment:

    (eval-after-load "magit" '(progn
      ...
      (setq magit-revert-buffers nil
            ...)
      ...)

So it's set after loading magit, but the 2.6.0.txt file has this:

> If the user sets the variable \`magit-auto-revert-mode' or the obsolete alias \`magit-revert-buffers' to nil anytime during startup, before **or after** \`magit-autorevert' is loaded, then the mode is now no longer turned on (actually it is explicitly turned off).

So either there's a bug in the code that is supposed for doing this, or that "or after" should be removed.

**Comment by npostavs** [comment]
The "or after" is in the context of "during startup", i.e. putting `(require 'magit) (setq magit-revert-buffers nil)` into your init.el would work, but setting `magit-revert-buffers` after startup (meaning after `after-init-hook` has run) is too late.

**Comment by elibarzilay** [comment]
Then the text is wrong.  The usual meaning of "X, Y or Z" in English is a flat disjunction of all three.

It should be very clear especially since it's a potentially destructive change.  (And it *is* a change, since code that worked before wrt this variable now does not.)

**Comment by npostavs** [comment]
> Then the text is wrong. The usual meaning of "X, Y or Z" in English is a flat disjunction of all three.

Okay, would using parens be better?

```
* If the user sets the variable `magit-auto-revert-mode' or the
  obsolete alias `magit-revert-buffers' to nil anytime during startup
  (before or after `magit-autorevert' is loaded) then the mode is now
  no longer turned on (actually it is explicitly turned off).
```

> (And it is a change, since code that worked before wrt this variable now does not.)

That change happened in 2.3.0, I think

```
* The new mode `magit-auto-revert-mode', a magit-specific globalized
  variant of `auto-revert-mode', replaces the old implementation, which
  was configured using the option `magit-revert-buffers'.  The new
  mode is enabled for all users by default, except for those who have
  set `magit-revert-buffers' to nil while the old implementation was
  still in use.  #2474
```

**Comment by elibarzilay** [comment]
> Okay, would using parens be better?

Yes.  Even better would be some indication that this is potentially breaking old setups.

> That change happened in 2.3.0, I think

I think that 2.3 is what I had before I updated today, so it looks like the ignore-the-value-when-set-after-loading thing is new.

BTW, to clarify: what I had in the above is setting the value after right after loading magit, but before using it.  IOW, it sounds like the old behavior would be restored if whatever is included in that "startup" work that you referred to above happened lazily on the first actual invocation of magit.

**Comment by npostavs** [comment]
> I think that 2.3 is what I had before I updated today, so it looks like the ignore-the-value-when-set-after-loading thing is new.

Sorry, typo, I meant 2.4.0 (the quoted excerpt is from `Documentation/RelNotes/2.4.0.txt`).

**Comment by npostavs** [comment]
> Yes. Even better would be some indication that this is potentially breaking old setups.

Is this new wording for the 2.4.0 change clear enough?

```
* The new mode `magit-auto-revert-mode', a magit-specific globalized
  variant of `auto-revert-mode', replaces the old implementation, which
  was configured using the option `magit-revert-buffers'.  The new mode
  is enabled for all users by default.  It may be disabled before
  loading magit by setting `magit-auto-revert-mode' (or the obsolete
  alias `magit-revert-buffers') to nil.  To disable the mode after
  loading magit, a call to (magit-auto-revert-mode -1) is required.
  #2474
```

**Comment by tarsius** [comment]
Yes. That covers it nicely.

**Comment by elibarzilay** [comment]
(Looks fine, sorry for the late reply.)
