### ISSUE TITLE
Hide trailing carriage returns in commit messages?

### ISSUE THREAD

**Issue by npostavs** [magit/magit#2666]
There seems to be a github bug that inserts carriage returns in commit messages (except for 1st and last lines) when creating a commit through the web interface.

`git show` seems to hide the carriage returns, so magit should too, right? (the carriage returns can be seen by `git cat-file -p`).

**Comment by tarsius** [comment]
Yes, Magit should do that. I wasn't aware Github messes this up, so while I have seen some such messages, I though this was a very rare occurance, which is why I haven't done anything about it yet.
