### ISSUE TITLE
Commit doesn't work when using certain shells (at least csh)

### ISSUE THREAD

**Issue by madand** [magit/magit#2672]
Magit invokes sudo to read the git repo, but somewhere its invocation of `git commit` fails, and I'm not seeing any meaningful error in the *Messages* buffer:

```
Tramp: Opening connection for root@hostname net using sudo...
Tramp: Sending command `exec env SHELL=/bin/sh sudo -u root -s -H -p
Password:'
Tramp: Waiting for prompts from remote shell...
Tramp: Sending Password
Tramp: Waiting for prompts from remote shell...done
Tramp: Found remote shell prompt on `hostname'
Tramp: Opening connection for root@hostname using sudo...done
Tramp: Inserting `/sudo:root@hostname:/path/.git/COMMIT_EDITMSG'...
Copying /sudo:root@hostname:/path/.git/COMMIT_EDITMSG to
/tmp/tramp.99342UqK...done
Tramp: Inserting `/sudo:root@hostname:/path/.git/COMMIT_EDITMSG'...done
Tramp: Checking `vc-registered' for
/sudo:root@hostname:/path/.git/COMMIT_EDITMSG...
Type C-c C-c to finish, or C-c C-k to cancel
Tramp: Checking `vc-registered' for
/sudo:root@hostname:/path/.git/COMMIT_EDITMSG...done
Tramp: Inserting `/sudo:root@hostname:/path/.git/COMMIT_EDITMSG'...done
Saving file /sudo:root@hostname:/path/.git/COMMIT_EDITMSG...
Copying /tmp/tramp.99342h0Q to
/sudo:root@hostname:/path/.git/COMMIT_EDITMSG...done
Wrote /sudo:root@hostname:/path/.git/COMMIT_EDITMSG
```

At this point I've saved the commit message via C-c C-c, but when Emacs returns to the *magit* buffer, the staged commits are still uncommitted.

[Original report](https://groups.google.com/forum/#!topic/magit/wCIXt71DwsE)

**Comment by kyleam** [comment]
I'm not able to reproduce this.  Does your Magit process buffer
contain any useful information?

**Comment by MadAnd** [comment]
Process buffer provides no useful information it this case:
```
run git … commit --
WITH-EDITOR: 38140 OPEN /usr/local/etc/.git/COMMIT_EDITMSG
```
Maybe the bug is specific to a remote user being `root` or a remote OS being FreeBSD. Will test this with a remote Linux box when I have more time.

BTW, here is my TRAMP proxy config:
```
(add-to-list 'tramp-default-proxies-alist
                     (list host "\\`root\\'" "/ssh:host:"))
```

**Comment by kyleam** [comment]
I tested /sudo:root@hostname for my etc repo (which I reached by calling dired with "/sudo::/etc") on GNU/Linux.  I wonder if the OP on the mailing list was also on FreeBSD.

**Comment by MadAnd** [comment]
I have set up a VM with Ubuntu 16.04 and tested using similar config: `/sudo:ubuntu@host:/etc/hosts`. And Magit commit worked OK.

Also, the versions of Git (2.7.4), OpenSSH (7.2p2) and sudo (1.8.16) all are the same on both my FreeBSD box and the test VM. It seems that the issue is indeed FreeBSD specific. At this point I have no idea how to further investigate the issue.

**Comment by tarsius** [comment]
Do you use `csh` as `sh`? According to [this](https://www.freebsd.org/cgi/man.cgi?trap%281%29) `csh` lacks `trap`, which is used by the script stored in `with-editor-sleeping-editor`.

**Comment by MadAnd** [comment]
I checked the login shell of root and it was indeed `csh`. Changed it to `sh` and rebooted the system. Unfortunately no luck here - the issue persisted.

Moreover in `* Messages *` I see that tramp's invocation of a shell looks like:
```bash
exec env SHELL=/bin/sh sudo -u root -s -H -p P""a""s""s""w""o""r""d""
```
As you can see it tries to enforce use of `/bin/sh`. I invoked the above command manually and experimented with `trap` in that environment. `trap` was available and worked correctly.

I went further and replaced `/bin/sh` with a symlink to Bash. This did the trick and finally commit was successful in Magit. Thank you @tarsius for giving the right direction!

Not sure where to report this further. `with-editor` or `tramp`?

**Comment by MadAnd** [comment]
For refernce, in FreeBSD It is worked around with the following code:
```
(setq with-editor-sleeping-editor "\
/usr/local/bin/bash -c '\
echo \"WITH-EDITOR: $$ OPEN $0\"; \
sleep 604800 & sleep=$!; \
trap \"kill $sleep; exit 0\" USR1; \
trap \"kill $sleep; exit 1\" USR2; \
wait $sleep'")
```

@tarsius maybe we should mention this somwhere in the `with-editor` or Magit docs?

**Comment by npostavs** [comment]
> For refernce, in FreeBSD It is worked around with the following code:

Do you know which part FreeBSD's `sh` doesn't support? (signal name maybe?) Can the script be changed to work on both `bash` and `sh`?

**Comment by MadAnd** [comment]
I just experimented with `sh`. 

It handles `wait` differently than Bash. No registered `trap` handles are being executed until `wait` returns control. So the current implementation will try wait 604800 seconds before reacting to any `trap`ed signals.

At the moment, I have no idea how to rewrite the code to work with `sh`.

**Comment by npostavs** [comment]
I guess the old looping editor from before 88e65e532b8b8c56652e322c9fd70b7bb466108b would be more portable, but it's less responsive.

Found this in [FreeBDS's  `sh` manpage](http://www.freebsd.org/cgi/man.cgi?sh%281%29) (though I'm not sure if it applies or not).

>     -T	trapsasync
>	       When waiting for a	child, execute traps immediately.  If this
	     option is not set,	traps are executed after the child exits, as
	     specified in IEEE Std 1003.2 (``POSIX.2'').  This nonstandard
	     option is useful for putting guarding shells around children that
	     block signals.  The surrounding shell may kill the	child or it
	     may just return control to	the tty	and leave the child alone,
	     like this:

>		       sh -T -c "trap 'exit	1' 2 ; some-blocking-program"

**Comment by tarsius** [comment]
@madand please try if you can commit after

```lisp
(setq with-editor-sleeping-editor "\
sh -T -c '\
echo \"WITH-EDITOR: $$ OPEN $0\"; \
sleep 604800 & sleep=$!; \
trap \"kill $sleep; exit 0\" USR1; \
trap \"kill $sleep; exit 1\" USR2; \
wait $sleep')
```

**Comment by madand** [comment]
@tarsius no luck with this one, it misbehaves the same as in OP.

**Comment by tarsius** [comment]
Since this is a `with-editor` issue, let's take this to https://github.com/magit/with-editor/issues/9.

**Comment by tarsius** [comment]
I've updated the documentation with instructions on how to deal with this.
