### ISSUE TITLE
No visible region in magit status buffers

### ISSUE THREAD

**Issue by elibarzilay** [magit/magit#2678]
It's kind of annoying that there is a selected region somewhere, but it's not visible.  I've had this simple hack for a while, and it works fine -- added this line at the end of `magit-diff-update-hunk-region`:

    (ov (region-beginning) (region-end) 'face 'region)

It looks nice even with `magit-diff-lines-boundary`.  (Similar to a diff that highlights different words in a more visible way on top of different lines.)

**Comment by npostavs** [comment]
Does `magit-keep-region-overlay` do what you want?

**Comment by elibarzilay** [comment]
Indeed it does.

(Sidenote: with an overly verbose docstring.  The bottom line is that it's still text, and therefore there are perfectly valid uses for showing the region -- like copying, or like highlighting text when talking about code.)

**Comment by npostavs** [comment]
Yeah, despite the warnings in the docstring, I've had this set to `t` since it was introduced and I've been pretty happy with it, see also #2091.

**Comment by elibarzilay** [comment]
Re the highlighting, I don't see any reason for the fuss -- what I see with this keep option on is a nice mix of selected text and selected lines for text and for magit operations respectively.

I'm guessing that the real debate is was about the behavior, where there are differences between the two.  Two examples of that which *do* seem a bit weird: if you're on a BOL and you hit S-home, then there is no region highlighted, but there's a magit selection for the current line.  IMO this is a bit odd, but the the combined highlights make it clear.

The second example that I see is that if I use S-arrows to select  region that covers two chunks, then the magit line selection disappears (when I cross the boundary).  When I look at the combined marks this is also very sensible-looking.

*However*, there is one bad result in that last example: if I press `s` with such a selection, I get the chunk that the cursor is in to be staged (all of it) -- not the chunk that I came from (none of it).  This looks like the kind of bad results @tarsius was talking about where the two selection modes are mixed.  (Except that this confusion is there when the keep option is off too: once the boundary is crossed the normal region appears which ends up being confusing in the same way.)  Two ways that I can see to improve this:

1. When `s` etc are used, then if there is no "magit selection" of lines but there *is* a textual selection, then show some "it's unclear what you want to ---" error.

2. If a magit selection is extended across a chunk boundary, then make both boundaries be selected (all of them).

Doing the first is most likely much easier than the second.  (But I don't care much, since I never used this feature of selecting lines anyway, so this is not a request to do anything about it.)
