### ISSUE TITLE
Make it a bit easier to rename branches

### ISSUE THREAD

**Issue by offby1** [magit/magit#2679]
This is in `Magit 20160524.2018, Git 2.7.3.AMZN, Emacs 25.0.93.1, gnu/linux`.

When I rename a branch, here's what I do:

- I start with the `*magit-refs: Whatever` buffer
- I move point to the line that names the branch I'm interested in
- I type `b m`
- That prompts me for the branch to rename; I hit the Enter key since the default is correct
- Now here's the point: when I start typing the new branch name, I would like some way to fill in the minibuffer with the _old_ branch name, since typically my new branch name is similar to the old one, _and_ I give my branches comically-long names; hence I want to avoid lots of typing.  For example, I have a branch named `EMS-205-dont-start-duplicate-remediations-with-terminator`, and I'd like to rename it to `dumb-idea-EMS-205-dont-start-duplicate-remediations-with-terminator`.  As far as I can tell, I have to (*horror of horrors*) type that entire name, character by character; however I would love to be able to instead type e.g. `M-p d u m b - i d e a RET` and have that suffice.

I can't remember precisely, but I'm pretty sure that _some_ interaction in magit already works this way: when renaming something or other, I can hit `M-p` to pre-fill the minibuffer with the current name.  I just can't remember which bit of magit that is.

**Comment by npostavs** [comment]
As it happens, I implemented this just last week, try updating magit. :)

7eac94f22cddc727142d80a277a4f8452e557fc1

**Comment by offby1** [comment]
Now, that's what I call _service_!  Thanks.
