### ISSUE TITLE
Commands which recognise a Branch ref at point do not also recognise Tag refs

### ISSUE THREAD

**Issue by phil-s** [magit/magit#2682]
Magit 20160606.1254, Git 2.6.6, Emacs 24.5.1, gnu/linux

When a command needs a ref as a default value (e.g. `l o`, or `b b`, etc...) it is automatically populated (as the default value in the prompt) using the current line in the ref manager for the various branch refs; but with Tags the current ref is not used, and the default value will be something else.

I think that tags should behave like the other refs? Certainly it's the behaviour I always want when I try this (usually for obtaining a log).

**Comment by tarsius** [comment]
This isn't specific to the refs manager. Keys do the same thing on a tag as in other buffers (likewise for branches). In the case of branches `RET` is a nasty exception for historic reasons.

So this is more about teaching a great many commands that currently default to the branch at point, to alternatively default to the tag at point. I'll have to think about that. It certainly would be quite a bit of work.

**Comment by phil-s** [comment]
I note that if I add `(tag (magit-tag-at-point))` to the `magit-section-case` statement in `magit-branch-or-commit-at-point`, then my original scenario is handled, even if there are numerous other situations where that function is not used?

Offhand I'm wondering whether there a reason why `magit-branch-or-commit-at-point` shouldn't be `magit-ref-at-point` and be as generic as possible?

**Comment by tarsius** [comment]
> Would that have any undesirable side-effects?

Quite possibly and we have to check. That's why I said "It certainly would be quite a bit of work." :-)
