### ISSUE TITLE
recenter-top after staging a hunk

### ISSUE THREAD

**Issue by blaenk** [magit/magit#2683]
Oftentimes I'll go through different things to stage and I do so by pressing `C-l` to set the beginning of the hunk at the very top of the window so that I can see the most of the hunk that I can. However, then I press `s` to stage it and it correctly moves the cursor to the beginning of the next hunk, but the window seems to reposition so that the cursor is now at the bottom of the window, which is very disorienting and breaks my flow because I have to press `C-l` three times to get it back to the top.

Here's some before and after screenshots of what I mean in case that's not clear enough:

Before: position the cursor on the beginning of the hunk (most likely by pressing `n` to jump to the correct position), then press `C-l` twice so that the window repositions so that the top of the hunk is at the top of the window. Then press `s` to stage the hunk.

![before](https://i.imgur.com/ncvDFCl.png)

After: the cursor correctly jumped to the beginning of the next hunk, but the window repositioned so that it's now at the bottom of the window, forcing one to press `C-l` _three more times_ to get it back at the top of the window.

![after](https://i.imgur.com/Gpk7Fmy.png)

The reason I want to position the hunk at the top of the window is so that I can see the most of it. If this were to happen automatically then I could very quickly go over the hunks to ensure that they are the changes I want to include in a given commit.

If this isn't behavior you'd like to include by default, I would greatly appreciate it if it could be provided as an opt-in behavior, or even if there were some hook exposed or something so that I could call the appropriate function to do this.

It looks like `recenter-top-bottom`, the function that `C-l` is bound to, has this relevant section:

``` elisp
    (let ((this-scroll-margin
	   (min (max 0 scroll-margin)
		(truncate (/ (window-body-height) 4.0)))))
      (cond ((eq recenter-last-op 'middle)
	     (recenter))
	    ((eq recenter-last-op 'top)
	     (recenter this-scroll-margin))     ;; <---- code to set cursor top of window
	    ((eq recenter-last-op 'bottom)
	     (recenter (- -1 this-scroll-margin)))
	    ((integerp recenter-last-op)
	     (recenter recenter-last-op))
	    ((floatp recenter-last-op)
	     (recenter (round (* recenter-last-op (window-height))))))))))
```

**Comment by blaenk** [comment]
It looks like there's already code and infrastructure for this, it's just not triggering after pressing `s`. Pressing `s` causes the point to move to the next hunk, so I feel like it should trigger `magit-section-movement-hook` which already by default contains `(magit-hunk-set-window-start magit-log-maybe-update-revision-buffer magit-log-maybe-show-more-commits`, where `magit-hunk-set-window-start` apparently is in charge of ensuring that:

``` elisp
"Ensure the beginning of the `hunk' SECTION is visible.
It the SECTION has a different type, then do nothing."
```

So it seems after pressing `s` to stage a hunk, if `magit-hunk-set-window-start` were called, my problem would be resolved.

**Comment by tarsius** [comment]
> I feel like it should trigger `magit-section-movement-hook`

Here "it" is "the buffer is being recreated from scratch (after staging)". So no, the movement hook is only intended for movement commands such as "go to next section".

The current Magit buffer is refreshed from scratch after (almost) every Magit command that might have side-effects which might have to be reflected in the buffer. `magit-refresh-buffer` calls `magit-section-goto-successor` to make sure point is position correctly and that approximately the same portion of the buffer is displayed as before.

After staging a hunk that is longer than the window, that apparently doesn't work so well.

> where magit-hunk-set-window-start apparently is in charge of ensuring that: "Ensure the beginning of the `hunk' SECTION is visible. It the SECTION has a different type, then do nothing."

This only ensures that the beginning of the section is *visible*, not that as much of it as possible is visible, or even that it begins at the beginning of the window.

---

After calling `magit-section-goto-successor`, `magit-refresh-buffer` also runs `magit-refresh-buffer-hook`, which we can use like this:

```lisp
(defun magit-hunk-recenter-top ()
  (when (and (eq this-command 'magit-stage)
             (magit-section-when '((hunk file)) t)
             ;; TODO also check if previously at beg of window.
             ;; using information saved before the refresh
             )
    (recenter (min (max 0 scroll-margin)
                   (truncate (/ (window-body-height) 4.0))))))
```

Please give this a try.

**Comment by blaenk** [comment]
Ah thanks, I wasn't aware that it was being recreated from scratch, though that makes sense.

Thanks for reminding me about that hook! Your function works very well, though I made a tiny change so that it also applies to `magit-unstage`:

``` elisp
  (defun my-magit-hunk-recenter-top ()
    (when (and (memq this-command '(magit-stage magit-unstage))
               (magit-section-when '((hunk file)) t)
               ;; TODO also check if previously at beg of window.
               ;; using information saved before the refresh
               )
      (recenter (min (max 0 scroll-margin)
                     (truncate (/ (window-body-height) 4.0))))
      ))
```

I'm not sure what to do about that TODO though. Do you intend to add this function to magit so that perhaps users can opt-in, similar to `magit-display-buffer-fullframe-status-v1`? (Thanks so much for adding that btw).

**Comment by blaenk** [comment]
I've been using it for a while and I've decided that it can be pretty jarring. I wonder if instead it would be possible to only do this if the next hunk is not entirely in view, but I'm not sure how feasible that is.
