### ISSUE TITLE
magit-get fails to retrieve branch with upcase letters

### ISSUE THREAD

**Issue by ptrv** [magit/magit#2684]
Hi,

since commit c3d55c81d24fb6694b155bad74566e81beb30914 `magit-get` retrieves the information from cache if activated.
However it fails to get remote branch if the branch name consists upper-case letters because `mapconcat` is used with `'downcase`. Why `downcase`?

The observed behavior is that in `magit-status` buffer in the header there is nor `Merge:` line anymore, even with upstream branch configured. Also pushing works and upstream branch is shown.

Repro steps:
Create branch with uppercase letters and configure as `branch.*name*.merge`.

Thanks

**Comment by npostavs** [comment]
> because `mapconcat` is used with `'downcase`. Why `downcase`?

Because `git config --list` outputs the keys downcased, except for branch names (and possibly some others?) apparently.

**Comment by npostavs** [comment]
Okay, I got it, git lowercases the outer components of the key, i.e. only `prefix` and `suffix` in `prefix.Key.suffix`.
