### ISSUE TITLE
Bisect Rest as branches (like log)

### ISSUE THREAD

**Issue by pvinis** [magit/magit#2689]
When bisecting, the `Rest` part is just a list of commits.
I think it would be must easier to understand if we could have the log (like `lb` or something) so we can see in the tree where the bad commits and good commits are.

**Comment by npostavs** [comment]
I think the good and bad tags show up in `la` (at least that's what I remember from last time I bisected, which was a while ago).

**Comment by pvinis** [comment]
yea, like that, but also pruned, like the bisect rest section. maybe it could be an option?

**Comment by npostavs** [comment]
I tried implementing this in #2706, please take a look.

**Comment by pvinis** [comment]
awesome. I will try it at the office in a few minutes.

**Comment by pvinis** [comment]
@npostavs wow that is just awesomeness. thats exactly what i wanted.
now how would i integrate it in the bisect view so i get that instead of the normal log? will it be a variable or something?

**Comment by npostavs** [comment]
> now how would i integrate it in the bisect view so i get that instead of the normal log?

Ah, that would need slightly different code, I added it there now: b72ded12bbe92091cd4561c26612c1caf7a58a87
