### ISSUE TITLE
magit-merge fails when commit.gpgsign=true

### ISSUE THREAD

**Issue by jgkamat** [magit/magit#2693]
When issuing a `magit-merge` (to master in my case) and `commit.gpgsign=true`, magit fails.

The error in `*magit-process*` is:

```
gpg: cannot open tty `/dev/tty': No such device or address
error: gpg failed to sign the data
fatal: failed to write commit object
```

Magit version: `Magit 20160610.1949, Git 2.8.1, Emacs 24.5.1, gnu/linux`
Emacs version: `GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-04-08 on binet, modified by Debian`

The easiest solution would be to drop the gpg-sign for merge commands via a flag, but I would prefer fixing the tty issue so I can sign merge commits. Thanks for making such an amazing git plugin for emacs! :smile:

**Comment by tarsius** [comment]
> The easiest solution would be to drop the gpg-sign for merge commands via a flag

Do you really see a different behavior when creating a non-merge commits?

**Comment by jgkamat** [comment]
Yes! When I create non merge commits magit prompts for my gpg password, and
commits work as expected. Is that not normal for magit?

**Comment by nwolfe** [comment]
I believe I just ran into this as well.  I enabled gpg signing a week ago and everything has been great so far, until today when I tried reviewing some PRs via magit.

I was able to fetch the changes, but when I tried creating a branch from them it failed to commit with the same error above.  After the error the changes were Staged, and I was able to manually Commit them and the GPG signing worked.
