### ISSUE TITLE
push explicit refspec should fill-in commit at point?

### ISSUE THREAD

**Issue by blaenk** [magit/magit#2694]
So say I have a couple of commits that haven't been pushed/merged to origin/master. I only want to push up to a certain commit though. I can do this by doing `P` to push then `o` to push explicit refspecs. Then I choose `origin` as the remote and the refspec is `4fed9ca:master`, i.e. I only want to push up to and including commit 4fed9ca to origin/master.

Is it possible for me to create a custom action on the push menu called for example "up to" which auto-selects the commit the point is on? Or better yet one that acts like in other actions where it then lets me interactively choose the commit with `C-c C-c`?

**Comment by kyleam** [comment]
> So say I have a couple of commits that haven't been pushed/merged to
> origin/master. I only want to push up to a certain commit though. I
> can do this by doing P to push then o to push explicit
> refspecs.

Do you have a none standard binding here?  Isn't <kbd>Po</kbd> bound
to `magit-push` by default, and <kbd>Pr</kbd> to `magit-push-refspecs`?

> Then I choose origin as the remote and the refspec is
> 4fed9ca:master, i.e. I only want to push up to and including commit
> 4fed9ca to origin/master.
>
> Is it possible for me to create a custom action on the push menu
> called for example "up to" which auto-selects the commit the point
> is on?

Using `magit-push` gets close the behavior you're asking for, I think.
The first prompt asks what to push, with the default set to the commit
at point.  The second prompt asks where to push it.

For example, with point on `47eb9be` of the Magit repo, using
<kbd>Po</kbd> lets me default to that commit and then push to
`origin/km/log-parent`:

```
  1 git … push -v --dry-run origin 47eb9be:refs/heads/km/log-parent
Pushing to gh:magit/magit.git
To gh:magit/magit.git
 ! [rejected]        47eb9be -> km/log-parent (non-fast-forward)
error: failed to push some refs to 'gh:magit/magit.git'
```

**Comment by blaenk** [comment]
You're right I meant `P r`, push explicit refspecs.

You're also absolutely right! `P o` works perfectly! I guess since it says branches I figured it wouldn't apply to arbitrary references/commits. Thanks!!

**Comment by kyleam** [comment]
Great, glad that works for you.

(Related to #2084.)
