### ISSUE TITLE
M-r and M-p not working in branch popup (b).

### ISSUE THREAD

**Issue by jaccarmac** [magit/magit#2695]
Based on previous experiences with Magit, I expect to be able to open the branch popup and use `M-r` and `M-p` to change push-and-pull-related configurations per-branch per-repo. Recently this has stopped working, with Emacs giving me an error that those keybinds are undefined. Navigating to the line in the popup buffer and pressing `RET` still activates the toggle.

My speculations about the cause of the problem are below the following debug information, as they may be more annoying than helpful.

Magit: `Magit 20160612.1221, Git 2.8.4.windows.1, Emacs 25.0.94.2, windows-nt`
Emacs: `GNU Emacs 25.0.94.2 (x86_64-w64-mingw32) of 2016-05-26`

Tested using both a minimal configuration containing only:

```emacs
(package-initialize)
(require 'magit)
```

and my full configuration as of https://github.com/jaccarmac/dot-emacs-dot-d/blob/8dcba4571532aa03fe4057fc16dd3da43f046250/init.el.

Based on my cursory examination of the Magit source, I would guess that the problem arises when only insert commands are intercepted to fire events in the buffer, while meta commands are not caught as insert commands. What's strange is that changes to the invoke framework, at least in `magit-popup.el`, only date back to 2014-2015. Since the regression happened only within the last few weeks, I figure it can only be due to some removal I didn't catch or a peculiarity with Git on Windows.

**Comment by kyleam** [comment]
Thanks for the report.  I can reproduce the issue and have bisected it
to 75abae8 (magit-branch-popup-setup: remove unnecessary function,
2016-05-12).

**Comment by jaccarmac** [comment]
Thanks much! Should've thought to bisect myself, that's my bad :-).
