### ISSUE TITLE
navigate back to previous popup?

### ISSUE THREAD

**Issue by blaenk** [magit/magit#2698]
I vaguely remember noticing and even commenting on a commit that added support for navigating back to the previous popup. For example if you pressed `P` to go into the push section, then I pressed `C-g` (or was it `ESC`?) it would take me back to the previous popup. It seems like that behavior is gone now though. Is it opt-in? What happened to it?

**Comment by npostavs** [comment]
> For example if you pressed `P` to go into the push section, then I pressed `C-g` (or was it `ESC`?)

It was `q` I think.

**Comment by blaenk** [comment]
Oh yeah that's right, and that does do what I meant. Thanks!
