### ISSUE TITLE
magit's autoloading is incomplete after M-x magit-log-buffer-file

### ISSUE THREAD

**Issue by catern** [magit/magit#2702]
I did M-x magit-log-buffer-file in an Emacs without having run any other magit commands before in that session. The log showed up. I then did RET on one of the commits.

>(1) what behavior you expected

The commit summary would show up.

>(2) what behavior you observed

The commit buffer did not show up, and I got the following in *Messages*:

Invalid face reference: magit-hash [6 times]
Invalid face reference: magit-header-line
call-interactively: Symbol's value as variable is void: magit-blame-modeInvalid face reference: magit-hash
Invalid face reference: magit-hash [5 times]
Invalid face reference: magit-header-line
Invalid face reference: magit-hash [6 times]
Invalid face reference: magit-header-line

>(3) and how we can reproduce the issue.

Do M-x magit-log-buffer-file in an Emacs without having run any other magit commands before in that session, and RET on one of the commits.

>M-x magit-version RET

Magit 20151028.1649, Git 2.8.2, Emacs 24.5.1

I suspect something is wrong with Magit's autoloading, but I have not tried to reproduce the issue without other packages.

**Comment by johnmastro** [comment]
I believe this is the same issue as #2426, which has some background. The short version is that Magit implicitly assumes you'll have run `magit-status` at least once before running most other commands.

To get around this, you could bind `magit-file-popup` (which does not suffer from the same issue) to a key and invoke `magit-log-buffer-file` from there (it's bound to `l`). There's also [a minor mode](https://magit.vc/manual/magit.html#Minor-mode-for-buffers-visiting-files) that binds a key for the file popup (on `C-c M-g`) and a few other commands.

> Magit 20151028.1649, Git 2.8.2, Emacs 24.5.1

Hm, however, `magit-file-popup` was not yet autoloaded in the version of Magit you're using. Sticking something like the below in your init file should work (or, of course, you could upgrade Magit).

```emacs-lisp
(autoload 'magit-file-popup "magit" nil t)
```

(I'm not a Magit developer/maintainer, just another user)

**Comment by npostavs** [comment]
> Magit 20151028.1649, Git 2.8.2, Emacs 24.5.1

Yeah, can you recheck with a more recent magit please?

**Comment by kyleam** [comment]
> Yeah, can you recheck with a more recent magit please?

I just rechecked with the latest, and I see the issue there as well.

**Comment by kyleam** [comment]
@johnmastro
> To get around this, you could bind magit-file-popup (which does not
> suffer from the same issue)

Oops, that means my comment to you in #2628 was nonsense because
magit-file-popup is in magit.el, so the autload will resolve the issue
instead of exposing it.

---

If I understand correctly, this will show up for autloaded functions
that load magit-core.el but not magit.el.  I'll go through all these
cases and make a list of ones that currently have problems.
