### ISSUE TITLE
Add remote url parsing functions

### ISSUE THREAD

**Issue by IvanMalison** [magit/magit#2703]
It would be nice to be able to see the current url of remotes that are selectable as completion candidates for various types of changes (rename, set url etc.). I was surprised to find that magit does not seem to have any functions for parsing the output of 'git remote -v' which seems to be the only way to obtain this information.

Is this something you might consider accepting into magit?

**Comment by npostavs** [comment]
The `*magit-refs*` buffer (accessible via `y`) shows remote urls.

**Comment by IvanMalison** [comment]
> The *magit-refs* buffer (accessible via y) shows remote urls.

Cool, this helped me find that `(magit-get "remote" remote "url")` does exactly what i need.

Perhaps there should be an elisp function like `(magit-get-remote-for-url remote-name)` to make it easy to find this for elisp developers looking to leverage magit's git interface who are unfamiliar with the code base.
