### ISSUE TITLE
Add support for bare repos?

### ISSUE THREAD

**Issue by phil-s** [magit/magit#2713]
Magit 2.7.0, Git 2.6.6, Emacs 24.5.1, gnu/linux

It would be really nice if Magit had at least some rudimentary support for bare repos.

At present, `magit-status` in a bare repo will generate a diff for deleting all of the tracked files, which is obviously going to tie Emacs up for ages, and never be what the user actually wanted to happen.

It looks like a bare repo can be detected with:

    git config --get core.bare

The bare repo root can be found with:

    git rev-parse --git-dir

If magit-status detected this and refrained from generating the usual diffs, that would be excellent.

**Comment by kyleam** [comment]
> never be what the user actually wanted to happen.

Agreed.  6d9c138 prevents magit-insert-staged-changes from populating
the status buffer in bare repos.

> It would be really nice if Magit had at least some rudimentary
> support for bare repos.

This makes it seems like there are at least a few things you have in
mind aside from the one you report, but nothing else obvious is
jumping out to me.  Things that rely on the working tree will fail,
but that's to be expected given that bare repositories aren't meant to
be worked from.

**Comment by phil-s** [comment]
> This makes it seems like there are at least a few things you have in
mind aside from the one you report, but nothing else obvious is
jumping out to me.

It's more that I hadn't spent enough time thinking about it to be confident that this was the only thing necessary.

Commands for [converting a bare repo to a working copy][1] and vice versa could be nice additions, and maybe there are other useful features which could be added. I so rarely deal with bare repos that it's not something I've felt a significant need for, but the main issue I raised here did seem worth doing something about.

[1]: http://stackoverflow.com/q/10637378

**Comment by kyleam** [comment]
> but the main issue I raised here did seem worth doing something
> about

Agreed, thanks for raising the issue.  With 923fdb9, the status buffer
no longer shows staged changes in bare repos.

> Commands for converting a bare repo to a working copy and vice versa
> could be nice additions, and maybe there are other useful features
> which could be added.

I don't consider the bare conversion commands something worth
supporting, but feel free to leave this open if you want to wait for
others to weigh in on those commands or other bare repository related
additions.

**Comment by phil-s** [comment]
If it's of any interest, I just noticed that if I copied foo/.git as foo.git and changed its core.bare setting to true, magit didn't generate any diffs. But when creating the bare repo with clone --bare it does generate the diffs.

It turned out that the presence of an `index` file made the difference. Even a zero-length `index` file in a bare repo seems to prevent the issue I was seeing.

I'm wondering whether that facilitates a solution which doesn't require calling git at all? (or only makes the call to git to double-check, if there is no index file?)

**Comment by npostavs** [comment]
> Commands for [converting a bare repo to a working copy][1] and vice versa could be nice additions

All the steps listed there can already be performed from magit/Emacs if you really want. I don't think it's worth cluttering magit with a special command to perform them in sequence automatically (that kind of repo operation is pretty delicate, so automating it too much is probably a bad idea anyway).

> I'm wondering whether that facilitates a solution which doesn't require calling git at all? (or only makes the call to git to double-check, if there is no index file?)

I think it's preferable to rely on git, to avoid being tied to the details of repository format more than necessary.


[1]: http://stackoverflow.com/q/10637378

**Comment by phil-s** [comment]
> I think it's preferable to rely on git, to avoid being tied to the details of repository format more than necessary.

I was thinking mostly of the Windows users, for whom I understand git calls are expensive; but I certainly concur that asking git is the most robust approach.

I'll close this once I've had a chance to test the change. Thanks again!

**Comment by npostavs** [comment]
> I was thinking mostly of the Windows users, for whom I understand git calls are expensive

Ah, yes, that's indeed why we switched to the approach used in 923fdb9 which only checks this once when first creating the status buffer (vs 6d9c138 which is once per refresh).

**Comment by phil-s** [comment]
That works great, thanks. Closing.

**Comment by ryukinix** [comment]
Sorry, but I don't understand the conclusion of this. This was added or dropped?

**Comment by npostavs** [comment]
It was added (that is, magit detects when you open a bare repo, and doesn't show it as having all files deleted).

**Comment by ryukinix** [comment]
I understand, but I still have problems handling bare repos with magit. Editing a file with a bare repo and using magit is that flow for me: magit ask for me where is the GIT_DIR every time I open the magit-status buffer. I think this is expected, but it would be nice if only one time. However, even if I do that, I do not receive any update status (on stage or unstage files) in this buffer.

This is expected? I should do something like this to magit acts like a normal git repo? Can this be a bug?

On my personal setup, on command line, I use a wrapper to handle the git usage:

```
alias dot-tig=GIT_DIR=/home/lerax/.dot/ tig
```

I do not know if I should open a new issue ...

**Comment by npostavs** [comment]
A bare repo is a git repo without any working copy, i.e., it is just the `.git` directory (see [1], [2]). Using alternate `GIT_DIR` and `GIT_WORK_TREE` settings is not related to this issue. You should instead look at #460.

[1]: http://www.saintsjd.com/2011/01/what-is-a-bare-git-repository/
[2]: https://stackoverflow.com/questions/5540883/whats-the-practical-difference-between-a-bare-and-non-bare-repository

**Comment by ryukinix** [comment]
Thanks for the clarification! Sorry for the mess.
