### ISSUE TITLE
Cannot commit c:/emacs/bin/emacsclient.exe $@: No such file or directory (Windows, msys git)

### ISSUE THREAD

**Issue by kimmok** [magit/magit#2714]
The emacsclient.exe can not be executed, it appears as if the executable is invoked so that filename argument is part of the executable name.

I don't know if this is related to the other bug I reported, related to .bat file parameter expansion.
This is running the git.exe hardcoded.
 
```
  1 c:\Users\kkinnunen\depot_tools\git-2.8.3-64_bin\bin\git.exe … commit --
\c:/emacs/bin/emacsclient.exe\: line 2: c:/emacs/bin/emacsclient.exe $@: No such file or directory
error: There was a problem with the editor '"c:/emacs/bin/emacsclient.exe"'.
Please supply the message using either -m or -F option.
```

```
with-editor: c:/Users/kkinnunen/AppData/Roaming/.emacs.d/elpa/with-editor-2.5.1/with-editor.el
emacs: c:/emacs/bin/emacs (24.5.1)
system:
  system-type: windows-nt
  system-configuration: i686-pc-mingw32
  system-configuration-options: --prefix=/c/usr --host=i686-pc-mingw32
server:
  server-running-p: t
  server-process: #<process server>
  server-use-tcp: t
  server-name: server
  server-socket-dir: nil
    WARNING: not an accessible directory
  server-auth-dir: ~\.emacs.d\server\
    server
magit-emacsclient-executable:
 value:   c:/emacs/bin/emacsclient.exe (24.5)
 default: c:/emacs/bin/emacsclient.exe (24.5)
 funcall: c:/emacs/bin/emacsclient.exe (24.5)
path:
  $PATH:C:\\Users\\kkinnunen\\depot_tools\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Users\\kkinnunen\\.dnx\\bin;C:\\Program Files\\Microsoft DNX\\Dnvm\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\Perforce;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\;c:\\emacs\\bin"
  exec-path: (c:/Program Files/SlickEditV19.0.1 x64/win/ C:/Users/kkinnunen/depot_tools/ C:/Windows/system32 C:/Windows C:/Windows/System32/Wbem C:/Windows/System32/WindowsPowerShell/v1.0/ C:/Users/kkinnunen/.dnx/bin C:/Program Files/Microsoft DNX/Dnvm/ C:/Program Files/Microsoft SQL Server/130/Tools/Binn/ C:/Program Files/Perforce C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ c:/emacs/bin c:/emacs/libexec/emacs/24.5/i686-pc-mingw32)
  with-editor-emacsclient-path:
    C:/Users/kkinnunen/depot_tools/ (t)
    C:/Windows/system32 (t)
    C:/Windows (t)
    C:/Windows/System32/Wbem (t)
    C:/Windows/System32/WindowsPowerShell/v1.0/ (t)
    C:/Users/kkinnunen/.dnx/bin (nil)
    C:/Program Files/Microsoft DNX/Dnvm/ (t)
    C:/Program Files/Microsoft SQL Server/130/Tools/Binn/ (t)
    C:/Program Files/Perforce (t)
    C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common (t)
    C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/ (t)
    c:/emacs/bin (t)
      c:/emacs/bin/emacsclient.exe (24.5)
      c:/emacs/bin/emacsclientw.exe (nil)
    c:/emacs/libexec/emacs/24.5/i686-pc-mingw32 (t)

```

Note also: I originally had emacs installed in "c:\Program Files (x86)\emacs". This fails with different error, namely the system tries to execute "c:\Program" when it tries to execute the editor (emacsclient.exe).

**Comment by npostavs** [comment]
I'm not able to reproduce this error (I've installed the depot_tools thing, hit the bat file problem, set `magit-git-executable` the same way).

> Note also: I originally had emacs installed in "c:\Program Files (x86)\emacs". This fails with different error, namely the system tries to execute "c:\Program" when it tries to execute the editor (emacsclient.exe).

How did you move to Emacs? Is there some symlink trickery involved?

**Comment by kimmok** [comment]
Strange. I moved the emacs by just dragging and dropping the folder to C:\

I start my emacs with a shortcut `C:\emacs\bin\emacsclient.exe -na runemacs.exe -c ""` and the home directory is my users home directory.

Maybe I should try the master version of magit?

**Comment by npostavs** [comment]
What does evaluating this
```elisp
(with-editor
  (let ((magit-git-debug t)
        (process-environment
         (cons "GIT_EDITOR=printf '[%s]\n' \"$EDITOR\"" process-environment)))
    (magit-git-insert "commit")))
```
from a buffer inside a git repository give you?

**Comment by kimmok** [comment]
So I create a file with elisp content above, then stage that file as a new change to the repo, then eval that expression with C-x C-e

It appends `[$EDITOR $@]` to the elisp buffer.
(If I don't stage anything, it appends some magit/git msg about repo being up to date)

**Comment by npostavs** [comment]
> It appends `[$EDITOR $@]` to the elisp buffer.

Hmm, that's not what I got. So it seems your copy of git is not calling the shell where it should.

Can you try again with `GIT_TRACE` turned on:
```elisp
(with-editor
  (let ((magit-git-debug t)
        (process-environment
         (cons "GIT_TRACE=1"
          (cons "GIT_EDITOR=printf '[%s]\n' \"$EDITOR\"" process-environment))))
    (magit-git-insert "commit")))
```

The tracing output will show up in the corresponding `*magit-process: REPO` buffer.

Also try the equivalent from git bash: `GIT_TRACE=1 GIT_EDITOR='printf "[%s]\n" "$EDITOR"' git commit`
and cmd.exe:
```
set GIT_TRACE=1
set GIT_EDITOR=printf "[%s]\n" "$EDITOR"
git commit
```


> (If I don't stage anything, it appends some magit/git msg about repo being up to date)

Right, sorry, I forgot to mention you would need something staged.

**Comment by kimmok** [comment]
Output of the expression:
```
1 c:\Users\kkinnunen\depot_tools\git-2.8.3-64_bin\bin\git.exe … commit
13:46:19.683135 git.c:350               trace: built-in: git 'commit'
13:46:21.592102 run-command.c:336       trace: run_command: 'printf '\''[%s]
'\'' "$EDITOR"' 'c:/Users/kkinnunen/chromium/src/.git/COMMIT_EDITMSG'
Aborting commit due to empty commit message.
```

Output of `C:\Users\kkinnunen\depot_tools\git-2.8.3-64_bin\git-bash.exe`

```
 kkinnunen@kkinnunen-dt MINGW64 ~/chromium/src (master)
$ GIT_TRACE=1 GIT_EDITOR='printf "[%s]\n" "$EDITOR"' git commit
13:49:05.899033 git.c:350               trace: built-in: git 'commit'
warning: LF will be replaced by CRLF in AUTHORS.
The file will have its original line endings in your working directory.
13:49:07.823128 run-command.c:336       trace: run_command: 'printf "[%s]\n" "$EDITOR"' 'C:/Users/kkinnunen/chromium/src/.git/COMMIT_EDITMSG'
[]
[C:/Users/kkinnunen/chromium/src/.git/COMMIT_EDITMSG]
Aborting commit due to empty commit message.
```

Output of cmd.exe:

```
C:\Users\kkinnunen\chromium\src>set GIT_TRACE=1
C:\Users\kkinnunen\chromium\src>set GIT_EDITOR=printf "[%s]\n" "$EDITOR"
C:\Users\kkinnunen\chromium\src>git commit
13:50:57.896097 git.c:350               trace: built-in: git 'commit'
warning: LF will be replaced by CRLF in AUTHORS.
The file will have its original line endings in your working directory.
13:50:59.783102 run-command.c:336       trace: run_command: 'printf "[%s]\n" "$EDITOR"' 'C:/Users/kkinnunen/chromium/src/.git/COMMIT_EDITMSG'
[notepad]
[C:/Users/kkinnunen/chromium/src/.git/COMMIT_EDITMSG]
Aborting commit due to empty commit message.
about:blank
```

**Comment by npostavs** [comment]
The traces are the same as what I'm getting. So the only difference is this funny `[$EDITOR $@]` output when running from Emacs. For the record, I get
```
["c:/emacs-24.5/bin/emacsclient.exe"]
[c:/Users/npostavs/src/magit/.git/COMMIT_EDITMSG]
```
----

Aha! I get `[$EDITOR $@]` also after setting `magit-need-cygwin-noglob` to `t`. So the problem must be that magit erroneously thinks `magit-need-cygwin-noglob` should be `t` in your case. What do get when 
- running `git -c alias.echo=!echo echo x{0}` in cmd.exe
- running `git -c 'alias.echo=!echo' echo x{0}` in git bash
- and evaluating
```elisp
(with-temp-buffer
  (let ((process-environment
         (append magit-git-environment process-environment)))
    (process-file magit-git-executable
                  nil (current-buffer) nil
                  "-c" "alias.echo=!echo" "echo" "x{0}"))
  (buffer-string))
```
in Emacs?

**Comment by kimmok** [comment]
Ah! so I tried to force the cygwin-noglob t when debugging the previous issue. So there's no error in magit, only in the user. Sorry for the trouble. I erased the customization and commit seems to work.
Thank you and sorry for the trouble. I'll close this issue.

**Comment by npostavs** [comment]
Okay, thanks for confirming. This thread was still useful because I learned something new: I was under the false impression that cygwin-noglob had no effect on Git for Windows 2.x (https://github.com/magit/magit/issues/2246#issuecomment-141302273).
