### ISSUE TITLE
Side by side blame

### ISSUE THREAD

**Issue by quicknir** [magit/magit#2717]
Hello,

I don't know if this idea has already been discussed or not, I tried to search the github issues and didn't see it. Currently, magit's blame puts commit information "inline" as I tend to think of it. You get lines that exclusively contain commit information, interspersed with the actual code.

For source that is the result of relatively few commits, this is absolutely fine. The problem is that as codebases tend to scale up in both size and age, you often see that core files will accumulate many, many smaller commits. To take a concrete datapoint: opening a random core file at a random spot in the codebase I work on, there are 13 commits accounting for 20 lines of code. To provide more interesting metrics: the file is about 1900 lines of code with 74 unique commits. This doesn't seem so bad with over 20 lines per commit on average. But obviously, magit blame needs to show a line of commit info anytime a line is from a different commit than the previous line. According to a quick python script I whipped up, there will be about 800 lines of magit blame info. That means that on average, you will see 2-3 lines of source between magit lines, and some regions will be much worse.

What would be really nice (IMHO) is to have the option of pulling up a git blame that is visually similar to fugitive, where the commit info is on the left, side-by-side with the actual code.  This especially makes sense (IMHO) in the modern age of very wide screens. Example: http://minkod.se/wp-content/uploads/2015/05/Screenshot-2015-05-09-20.02.00.png. The original code is untouched, and even still has syntax highlighting. Obviously there are many variants on this; you can apply some kind of effect to either the background or foreground to color lines from the same commit together.

Since the current blame mode obviously already works and is fine for many people/circumstances, this new git blame style could be optional/switchable.

Any thoughts? Fwiw I'm willing to chip in a donation ($20 ?) if it helps get the ball rolling on this commit (I appreciate that one donation isn't a ton, but maybe if other people feel the same then a not-completely-trivial amount can be raised).

Edit: I should mention that vc-annotate can do something like this, but it's not great for other reasons, cannot AFAIK do the neat "reblame" thing that's so easy in magit, etc. I'd much rather strictly stick with magit.

**Comment by danrharms** [comment]
Try vc-annotate (C-x v g). It takes longer to load than magit's equivalent, but offers a side by side view.

**Comment by quicknir** [comment]
@danrharms Maybe we crossed posts/edits but as I wrote in edit, vc-annotate has some issues. The first and most obvious is that it's not part of and not integrated with magit, which is what I/we use for everything else, so that's already a major shortcoming. It means different keybindings, different options, etc. In spacemacs, there are excellent evilified bindings for magit, but vc-annotate is a complete mess.

It's also quite ugly; you have to choose a fixed background color and then you colorize by age. I'd much rather keep syntax coloring and have a few background colors to indicate grouping of commits while on a particular screen. in vc-annotate, commits made a short time apart can look almost identical unless you look very closely.

If a file has changed locations, then it shows the entire file path as part of the commit line, on every line. It also shows the timezone by default, and the time in seconds. All this means that it takes a crazy amount of vertical space. Ideally there should just be easy keyboard shortcuts to switch these on and off. Instead you have to (AFAIK) hard customize the git command to make the blame look the way you want, and then it's not easy to add the column back if you want it.

I guess from my perspective, I think that vc-annotate overall just falls quite a bit below the very high bar that magit sets. So while it does roughly do what I'm suggesting, it does it much more poorly than magit does all of the things that it does. I'd like to see this done by magit, because judging from everything else, magit would do it way better and solve many of these issues. This is all on top of the fundamental benefit of integration and consistency with the rest of magit.

**Comment by kyleam** [comment]
Related [mailing list thread](https://groups.google.com/d/msg/magit/ALSWQ0vNK0g/On6dM5HMqWcJ)

**Comment by phil-s** [comment]
What do you mean by the "neat reblame thing"?

**Comment by gaugau** [comment]
:+1:  side by side mode will be great! I found that the inline mode is pretty hard to read, especially for file that has many commits touched.

**Comment by kvaneesh** [comment]
There is a toggle option that can hide that commit details. For me, I really liked the inline mode and will hate to see that go away. I regularly use this on a project that has really large number of commits.

**Comment by dscole** [comment]
:+1: I completely agree that having a side-by-side mode for magit-blame would be a really good addition. @kvaneesh I don't think anyone was saying anything about removing inline mode, people just want an _additional_ option to see the blame in side-by-side mode as well.
I think that there is a reason that this side-by-side view is the standard in _all_ git blame tools that I'm aware of (including the core git blame and git gui blame), it simply is very convenient.
Also, while vc-annotate could provide a temporary remedy (with all the issues listed by @quicknir and the thread @kyleam linked), I feel this should really be an integrated part of magit.

**Comment by jflombera** [comment]
I am migrating from Vim to Spacemacs (it's been good so far, e.g. Magit is great!!) and would really like to have the side-by-side blame fugitive provides.

However, it always annoyed me that in fugitive, the blame buffer has a commit info for every line, even if consecutive lines belong to the same commit.  This makes harder to interpret since you have look at the message/hash to determine if two or more consecutive lines belong to the same/different commit.

If this side-by-side blame is implemented in Magit, it would be good if in the blame buffer, all the consecutive lines belonging to the same commit were collapsed into a single commit info line (or at least make it configurable), something like this:
```
<commit1>
BLANK_LINE # belongs to commit1
BLANK_LINE # belongs to commit1
<commit2>
<commit3>
BLANK_LINE # belongs to commit3
<commit4>
...
```

**Comment by fice-t** [comment]
@jflombera I like that idea, but if that was to be done I'd also like the restriction that every visible commit section must have at least one visible line on the side that shows the commit information.

That seems like a harder job as it would involve changing the overlays' display text depending on `(window-start)`. If that's infeasible then I suppose just hitting RET to preview the commit is a small price to pay for an uncluttered interface.

**Comment by quicknir** [comment]
@jflombera I don't honestly see a lot of upside for this. as @fice-t noted, you now have to deal with issues where the first line of the commit is not visible (e.g. off-buffer). I don't find it difficult to tell if commits are same/different from line to line if the commit hash is lined up.

IMHO a better solution is to have some kind of reasonable coloring scheme. If you just pick a set of say 6 colors, and rotate to the next one on each commit change, then it will be very easy to see commit blocks. Ideally this would match up with a tint in the background of the code on the right. Do you think this would address your concern? It would also be far easier to implement then dealing with the edge cases in your proposal.

**Comment by fice-t** [comment]
@quicknir Another alternative would be to only omit part of the information for consecutive lines. Then you would at least have some of the information all the time, but it would be easier to group commits.

As for the colouring scheme, apparently that would also have to be done carefully if you want to do it properly. I've just tested `tig`'s blame on my `init.el` and it doesn't seem to care much about consecutive unique same-coloured commits. Without lookahead I don't think there's a guarantee that you won't run into consecutive unique same-coloured commits if you want the same commit to be the same colour in the entire buffer.

Ideally there would be multiple options for people to choose their poison.

**Comment by jflombera** [comment]
@quicknir I still believe the "single-line-of-info-per-chunk" approach is better for the sake of readability, of course addressing the requirement of at least one visible line of commit info per chunk that @fice-t pointed out.  Even if the commit hashes are lined up, it still requires mental processing to analyze them.  It is much easier to parse "visual" chunks.

However, if it is difficult to achieve (as I pointed out, I am new to Emacs and completely ignore what it takes and how difficult it would be; I completely trust you here), the coloring approach could address my concern as well (although less visually appealing, again still more info/noise to process).  This approach has its own challenges too, for example, which colors to use?  will they be fixed or adjusted to the color theme?

**Comment by quicknir** [comment]
@fice-t So my initial thought was simply to rotate through a list of colors as you encounter new commits, processing sequentially. So no attempt would be made to ensure that the same commit was the same color in different commit blocks. Obviously this is not 100% ideal, but it is quite simple, useful, and addresses (IMHO) the original issue.

The notion of giving every commit a consistent color seems pretty hard. It's not uncommon to see files that have been touched by 100 commits. Having a sufficient number of distinguishable colors is not really realistic. Once you concede that, the only thing you can do is pick some reasonable large number of colors, get the "commit adjacency matrix" (two commits have an edge iff at some point in the file they appear sequentially), and try to do some kind of optimization so that you never assign the same color to two adjacent nodes. This is already getting pretty intense; though it is a fun problem.

I think just rotating through a fixed list of colors at every transition has reasonable utility and is the easiest to implement of everything being suggested.

@jflombera I guess I don't fully agree; if you do the color thing as a tint to the background of the code as well, then you can instantly see the scope of a contiguous commit code block. You don't need to deal with aligning with info on the left. It's also more of a departure from the standard git diff, and fugitive. But the whole point of my initial issue was to have something much more similar to those two; I guess most people that upvoted feel the same (though naturally I can't say for certain, maybe more people would prefer your suggestion).

Colors IMHO are easier insofar as you try to pick something reasonable, if the ones you pick don't suit a given theme well then theme authors are welcome to customize the colors themselves. Even the number of colors used is easy to customize. Checking whether or not the line is on the screen involves writing more complicated error prone logic. It's totally doable, just harder. And I think the color thing has value already for the background of the code.

Anyway I guess we have both presented our view, I guess the people actually doing the work will make the decision ;-).

**Comment by tarsius** [comment]
> I guess the people actually doing the work will make the decision

Yeah, and once actually start working on it ;-) But the input so far was certainly helpful.

> (or at least make it configurable)

I indeed plan to give users options here.

Without having thought too much about it lately, I tend to favor not showing the same information on each line of a commit (further lines could be blank or show additional information) and I am a bit skeptical about coloring different commits (for the reasons mentioned above). In addition to whatever method is used to display information about commits, they can additionally be separated using thin lines if necessary (you can already check that now, press `t`).

**Comment by tarsius** [comment]
Closing in favor of #2937.
