### ISSUE TITLE
magit-insert-branch-description discards description body

### ISSUE THREAD

**Issue by mquander** [magit/magit#2719]
As per the `git branch` [documentation](https://git-scm.com/docs/git-branch), branch descriptions may be multi-line, with a header and a body. [`magit-insert-branch-description`](https://github.com/magit/magit/blob/master/lisp/magit.el#L865) used to produce a section with a header and body to match, but this regressed in [a recent commit](https://github.com/magit/magit/commit/4394f5f5333c1f3ae408fc03d3a29d4ddb6c3ed4) such that the body is not present. (This is caused by `magit-get` and `magit-git-str`'s behavior of discarding all output lines except the first.)

To reproduce, create a multi-line description for any branch, check out that branch, and open the ref manager. You can see the section produced by `magit-insert-branch-description` at the top. It will not include the body when expanded.

Observed using Magit 20160713.1658, Git 2.9.0.windows.1, Emacs 24.5.1, windows-nt.

**Comment by npostavs** [comment]
> (This is caused by `magit-get` and `magit-git-str`'s behavior of discarding all output lines except the first.)

Oh, huh. I didn't realize `magit-get` returns only one line. I think it shouldn't. See #2720.
