### ISSUE TITLE
Interactive rebase initiated from cmd-line no longer works

### ISSUE THREAD

**Issue by bobbyrullo** [magit/magit#2723]
Version: Magit 20160713.1658, Git 2.9.0, Emacs 24.5.1, darwin

If it initiate a rebase from magit - eg `(magit-status)`, then `r` , then`i` then all is well.

However I tend to blend cmd line git workflow with magit, from within an Emacs shell. So I used to do this (for example) from bash:

```~$ git rebase master -i``` 

and then, since my EDITOR is `emacsclient -n` , the magit rebase editor would pop up and I would do what I need to do and execute the rebase (this was version 1.x I believe)

Now what happens is, the editor pops up like normal, but when I go to execute I get a prompt "Directory /path/to/repo/.git/rebase-merge/ does not exist - create? (y or n)" and when I do I get dumped back to the (emacs) shell but the rebase hasn't happened. However, the directory is still there, so git thinks I'm in a rebase so I try `git rebase --continue'  and I get this output

```
cat: /path/to/repo/.git/rebase-merge/onto_name: No such file or directory
cat: /path/to/repo/.git/rebase-merge/current: No such file or directory
Already applied: 0000 fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
/usr/local/Cellar/git/2.9.0/libexec/git-core/git-rebase--merge: line 120: test: : integer expression expected
All done.
``` 

Is my workflow no longer supported? I am not sure if the last magit I had that worked - it was at my previous job, and I didn't take note ( since it was working :) ) but probably 1.x

Thanks!

**Comment by kyleam** [comment]
I'm surprised that it used to work with the `--no-wait` flag.  Testing
with the latest Magit, it works fine for me if I remove `-n`.

**Comment by bobbyrullo** [comment]
Ah! removing the 'n' works! Thanks!
