### ISSUE TITLE
Ediff staging returns an error

### ISSUE THREAD

**Issue by tarwatirno** [magit/magit#2732]
When staging a file with ediff, the error `(wrong-argument-type arrayp nil)` is thrown when exiting the ediff session:

1) From magit status buffer, select a file to stage with ediff
2) Select changes to stage
3) Quit the ediff session, and select `y` when asked to "Update index with contents of buffer.~index~"

Output of magit-version: `Magit 20160803.1451, Git 2.8.0, Emacs 24.5.1, gnu/linux`

From looking at a backtrace it looks like the error is being thrown from this line: https://github.com/magit/magit/blob/master/lisp/magit.el#L1285 which is in turn called from here: https://github.com/magit/magit/blob/master/lisp/magit-ediff.el#L185

**Comment by tarsius** [comment]
Wrong issue.
