### ISSUE TITLE
scroll-conservatively over 100 messes with magit-blame

### ISSUE THREAD

**Issue by fice-t** [magit/magit#2735]
If `scroll-conservatively` is over 100, then the cursor position is sometimes wrong when moving down with `n` or `C-n` in magit-blame-mode. It should be going to the next section, but it instead appears at the top line of the screen.

Reproduction:
1. Start in `emacs -Q`. and load magit.
2. Go to `magit-blame.el` in the master branch of magit's repo.
3. `M-g g 207 RET`
4. Set `scroll-conservatively` to a value higher than 100.
5. `magit-blame`.
6. Scroll down either with `n` or `C-n`.

`Magit 20160805.1421, Git 2.7.4, Emacs 25.1.1, gnu/linux`

**Comment by tarsius** [comment]
This appears to be a bug in Emacs (likely in `try_scrolling` in `xdisp.c` or in `pos-visible-in-window-p`). It occurs when moving to the first "invisible" line when that visible line has an overlay which covers a whole line and that overlay line is partially visible both vertically (the lower part is cutoff) and vertically (the end of the line is cutoff, as indicated by the arrow).

Moving forward a line or section from here triggers the bug:

![demo](https://cloud.githubusercontent.com/assets/25046/17463640/7738a852-5cca-11e6-8fd9-9159657d4d07.png)

**Comment by tarsius** [comment]
Please report this upstream.

**Comment by fice-t** [comment]
I seem to be able to trigger it even when the end of the line isn't cut off.

I'm finding it a bit hard to get a nice reproduction recipe without magit, though I did get it to trigger accidentally once.

Anyway, I reported it here: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24179

**Comment by fice-t** [comment]
@tarsius The bug was resolved in the master branch, but there does seem to be some delays that still occur (e.g. with M-g g when already in magit-blame with scroll-conservatively set >100). Eli Zaretskii mentioned the cursor property as something that may help:

>Btw, magit-blame could be nicer to the display engine by placing a
'cursor' property on the first character of each before-string it
creates to show the blamed commit.

**Comment by tarsius** [comment]
I'll look into that. Thanks!

**Comment by tarsius** [comment]
> placing a 'cursor' property on the first character of each before-string

According to Eli, that isn't possible after all.
