### ISSUE TITLE
Improve Git config variable interface

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2744]
Following the `2.7.0` release we made some changes to functions that deal with Git config variables, or which use these functions. Most of these changes had to be reverted. We have to do this more carefully and keep the result on a feature branch before merging into `master` again.
### Relevant commits

`=` commit that hasn't been reverted
`+` commit that has been reverted
`-` revert commit, or commit that undoes a change
- b11f666a2b53e98d0923fa52000a1b7f381a3dbb - remove entry for reverted change
- f3918df18257ed8cb899b847a8d4924b8c02757d - Revert "magit-insert-branch: use magit-get"
- 37c7cbd8b4a59e1f9dc698cbceba10fab1776bd2 - Revert "magit-branch-description: Fix for detached head"
- 3d7caeaa84a4bfa4423e701874307994c0e629db - Revert "magit-get: don't return only first line of value"
- 4a1c432d280f79f2cd3af035d6a0caed1868045c = update manual [partially reverted in ]
- 4835b978509ad01d1dbb8ce2bf2a2121d28eb6d6 + magit-get: fix typo [reverted in 3d7caea]
- 11e14785fba9e2476e195af272fff3a4f5dc149b + magit-get: don't return only first line of value
- fbf07740224e7baa9740a15bb4a6e0bb3c464834 = magit-get-all: don't split multi-line values
- 5c006c2f2a1d9573eaa5de1ce71a8645483029b5 - Revert "magit-get{,-all,-boolean}: improve cache"
- 4f5fa2a4839d7e5ff28ee169f1431ae4258db831 - Revert "magit-config-slurp: handle empty value config vars"
- ade8dd9d08e3c75ea18e80c5883a336ed804f6ed + magit-branch-description: Fix for detached head
- 815d4ed6f0a4a56a8c4c969de861a4bfd5c440b6 = Make magit-get setf'able
- f330168621f1168a07b4f51a54485c05ea07da6c = magit-popup-set-variable: use magit-set
- 780ce427b0db64b30c36746c29b2f59ac905a7ca = magit-popup-format-variable-1: use magit-get
- 6c305d427bc18b3cb7a8f8f32693784a32662cc3 + magit-config-slurp: handle empty value config vars
- c3d55c81d24fb6694b155bad74566e81beb30914 + magit-get{,-all,-boolean}: improve cache
- 4394f5f5333c1f3ae408fc03d3a29d4ddb6c3ed4 + magit-insert-branch: use magit-get
### Relevant pull requests, issues, and branches
- [`reconfig`](https://github.com/magit/magit/compare/reconfig?expand=1) (very experimental)
- #2743 cache git config more aggressively (v2)
- #2720 magit-get: return all lines of config value
- #2688 Fix cached config --list lookup
- #2677 Make magit-get setf'able
- #2670 cache git config more aggressively

**Comment by tarsius** [comment]
Also remove config sections that have become empty (in other contexts too).

**Comment by tarsius** [comment]
* Meanwhile the cache has been implemented.
* We should use libgit2 here and for many other things as described in #2959.

Which leaves us with:

* [ ] Change the order of arguments. Put VARIABLE before VALUE. VARIABLE can be a string or a list of strings which are concatenated as before. But it's no longer a &rest argument but that's a small cost compared to the benefit of using the same order of any other setter function.
* [ ] `magit-get-boolean` should return t for true and nil for false as before, but for another value or when the variable is undefined, then it should raise an error. Other functions such as `magit-git-true` should be changed the same way.

I might end up keeping some of the existing functions (but declare them to be obsolete) and add new functions with the new behavior.

**Comment by vermiculus** [comment]
I'd be happy to write a module that'll handle git config variables if we have a solid plan/approach to distribute that module. Last I heard, that was still up in the air.

**Comment by tarsius** [comment]
Working on this I cannot help but wonder whether this is really worth the effort.

* Changing the order of arguments is a cosmetic change. I would prefer to do it but it is not necessary. It would be a breaking change so we would have to either create new functions or make sure that we also implement all the other changes we might want at the same time (to avoid breaking packages that use these functions more than once).

* Handling non-booleans when asking for a boolean seems more important. Then again, what we have now works and this change would be just for correctness. But if we do that then we should also make sure that our functions work exactly like the git equivalents in other situations too. That would be a lot of work and it seems unnecessary.

So I am closing this for now. Maybe I will change my mind at a latter time - keeping my experiments around just in case.

---

Also it might be a waste of time to do this now using something ultimately involving `process-file` when eventually we might switch to using `libgit`.

> I'd be happy to write a module that'll handle git config variables if we have a solid plan/approach to distribute that module. Last I heard, that was still up in the air.

Well what I just said probably didn't put things firmly on the ground. :wink: That being said, I would welcome it if you wrote such a module.

Are you unsure about the interface you should implement? Then the above certainly didn't help. Or are you unsure how to *distribute* the module, as in you don't know how to make sure that the module ends up on users machine in a way that allows them to use it?

If it is the latter, then I don't think that should keep you from working on this. I don't think distribution of modules using `package.el` and its archives is a solved problem, but we will get there eventually.

**Comment by vermiculus** [comment]
>Are you unsure about the interface you should implement? Then the above certainly didn't help. Or are you unsure how to *distribute* the module, as in you don't know how to make sure that the module ends up on users machine in a way that allows them to use it?

That's more the concern for me presently. I can work on something in the coming weeks.
