### ISSUE TITLE
Always log the hash in the process buffer when deleting a ref

### ISSUE THREAD

**Issue by phil-s** [magit/magit#2746]
Magit 2.8.0, Git 2.6.6, Emacs 24.5.1, gnu/linux

I just (stupidly) deleted a stash instead of applying it.

It would be really super useful if magit had logged the hash for that stash at the point it was deleted, so that I could still trivially identify and apply it.

The actual log entry is:

   0 git … reflog delete --updateref --rewrite stash@{0}

As stash@{0} has a new value after that, there's no record of what was actually deleted, even though git could still access it by its hash.

Offhand I'm not sure if there are other similar scenarios (other than stashes) which would need to be accounted for?

Branches and Tags do seem to be covered by git (2.6.6).

   0 git … branch -D foo
 Deleted branch foo (was 9a5b49f).

   0 git … tag -d 20160822-1
 Deleted tag '20160822-1' (was f5e9dd2)

In each case the stated ref is indeed for the thing which was deleted.

(I don't know whether all versions of git supported by Magit 2 provide that info, mind.)

**Comment by kyleam** [comment]
I think this was the motivation behind #2383, which was addressed with
36815c0 (magit-stash-drop: verbosely to be able to undo mistakes,
2015-11-09).  With that commit, the abbreviated hash of the dropped
stash is displayed as a message.

It'd be nice to have the hash in the log buffer rather than the
messages buffer, but git reflog will signal an error if you feed it a
hash directly:

```
255 git … reflog delete --updateref --rewrite 460a24a9268d2d85951310d2b49e62470ad0632b
error: Not a reflog: 460a24a9268d2d85951310d2b49e62470ad0632b
```

**Comment by phil-s** [comment]
Oh, nice! I can see that hash I wanted in my messages log. Thank you kyleam.

I completely missed that at the time, of course -- and while I'm unlikely to forget it now, I can imagine other people doing the same thing...

Honestly, I'm not sure I've *ever* looked at `*Messages*` for information from Magit regarding git commands it has invoked. I kinda expect to find it all in the process log buffer. Is that just foolishness on my part? I realise as I write this that it makes perfect sense for the "process log" buffer to only log messages which were actually generated by git, but it would certainly be nice in situations like this if messages which we *wish* git had output also appeared there.

I think it would be great if Magit would log at least selected messages in the process log buffer. It might employ a different face to indicate that it wasn't from git.

Is that a reasonable feature request?

**Comment by tarsius** [comment]
I've added the above kludge. For now that is all we can do.

In the long run it would be nice if it were possible to log messages that don't come from a process in the "process buffer". It would also be nice to group related sections; if a magit command calls multiple git commands, then all of them should appear inside a `magit-some-command` section. I was already planning to do that eventually and have now added a note to the [`3.1.0` milestone](https://github.com/magit/magit/milestone/22).

**Comment by phil-s** [comment]
That's great, thank you.
