### ISSUE TITLE
magit-list-repositories stringp error

### ISSUE THREAD

**Issue by jojojames** [magit/magit#2748]
1. Run magit-list-repos without error
2. Type error stringp - passed in string
3.  (Tried formatting the code, sorry about the bad formatting, it should paste into emacs relatively well though). [*you were just missing some backquotes - npostavs*]

```elisp
;; pulled out body of magit-list-repositories
    (mapcar (-lambda ((id . path))
              (let ((default-directory path))
                (list path
                      (vconcat (--map (or (funcall (nth 2 it) id) "")
                                      magit-repolist-columns)))))
            ;; (magit-list-repos-uniquify
            ;;  (--map (progn
            ;;           (cons (file-name-nondirectory (directory-file-name it))
            ;;                it))
            ;;         (magit-list-repos)))
            (magit-list-repos-uniquify-stub)
            ;; '(("zzclient2" . "/Users/james/Developer/zzclient2")
            ;;   ("SocketRocket-Sharp" . "/Users/james/Developer/SocketRocket-Sharp"))
            )
    
    (defun magit-list-repos-uniquify-stub ()
      (magit-list-repos-uniquify (map-alist-test)))
    
    (defun map-alist-test ()
      (--map (progn
               (message (concat "uni: " it))
               (message (concat "dir: " (file-name-nondirectory (directory-file-name it))))
               (cons (file-name-nondirectory (directory-file-name it))
                     it))
             ;; (magit-list-repos)
             (magit-list-repos-stub)))
    
    (defun magit-list-repos-stub ()
      '("/Users/james/Developer/SocketRocket-Sharp"
        "/Users/james/Developer/zzclient2"))
```

magit version-
Magit 20160821.1338, Git 2.7.4 (Apple Git-66), Emacs 25.1.1, darwin

It looks like the code might be choking on the '2' in 'zzclient2'. Commenting out that line lets the code proceed as expected but leaving it in causes the stringp type error.

**Comment by marsam** [comment]
Hi:
I can reproduce this. It happens in repositories without a remote.

<details>
<summary>error in a repository without a remote</summary>
128 git … rev-list --count --left-right HEAD...origin/master
fatal: ambiguous argument 'HEAD...origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
</details>

`magit-list-repositories` uses [`magit-rev-diff-count`](https://github.com/magit/magit/blob/0dcebfe/lisp/magit-git.el#L1081-L1089) and `magit-git-string` return `nil`.

**Comment by kyleam** [comment]
Hmm, I'm not able to reproduce these issues.  magit-list-repositories
works fine on a repository with the name zzclient2.  It also works for
me on a repo without a remote (looking at the magit-repolist-*
functions, they seem to do the right checks).

I did find an issue with the handling of empty repositories, which
should be fixed with 09fac02.

**Comment by marsam** [comment]
Hi:
I investigated a bit, and you are right `magit-list-repositories` does the right checks. 
In my case, the error was that my `~/.gitconfig` contained the following snippet.
```cfg
;; I don't know how this ended it here :(
[branch "master"]
	remote = origin
```
which caused to `git config branch.master.remote` return `origin` even in repositories without a remote.

@jojojames can you share the output of the following in the `zzclient2`  repository?
- `cat .git/config`
- `git config branch.master.remote`

**Comment by jojojames** [comment]
I'll have some more time to look at this with more info in the next few days.

**Comment by jojojames** [comment]
@kyleam 

Your changes may have fixed it (not sure). I don't see the issue anymore after updating magit.

**Comment by kyleam** [comment]
@jojojames OK, thanks for the update.  Please report back if you run
into the issue again.
