### ISSUE TITLE
Finishing feature with --squash not working

### ISSUE THREAD

**Issue by jluttine** [magit/magit#2751]
Finishing a feature branch with `--squash` does not work. The end state has develop branch checked out but the feature branch commits have not been merged, they've been only staged or something like that.

I'm using Spacemacs, so the key bindings might be different than in normal Emacs. Anyway, here are the steps to reproduce:

```
$ mkdir tmp
$ cd tmp
$ git init
$ git flow init
$ emacs
```

- Open magit: `SPC g s`
- Create feature branch: `% f s featurebranch`
- Create a file: `SPC f f foobar`
- Save the file: `SPC f s`
- Open magit: `SPC g s`
- Stage and commit the file.
- Finish feature branch with squash: `% f f -s f`

Emacs seems like it hangs, but you can press CTRL g. The feature branch finishing is in some weird non-finished state.

magit-version: Magit 29160815.1946, Git 2.9.3, Emacs 24.5.2, gnu/linux

**Comment by tarsius** [comment]
This sounds like you might be using [magit-gitflow](https://github.com/jtatarik/magit-gitflow). If so, please report the issue there.

**Comment by jluttine** [comment]
Oh, yes, thanks for that! Didn't realize it's a separate package. I opened an issue there: https://github.com/jtatarik/magit-gitflow/issues/18
