### ISSUE TITLE
magit-diff-visit-file to visit a file at revision~1

### ISSUE THREAD

**Issue by kvaneesh** [magit/magit#2755]
I have done a similar request as part of issue #1777 . We are now able to follow the lines added. But i want to recursive blame from where the line got removed. For that It would nice to have something like ALT-RET that shows the file/buffer content before that commit. Right now i use magit log file got to the revision before and blame it. But if magit-diff-visit-file can take an option to show the version before it would make it all easy ?

**Comment by tarsius** [comment]
I'll look into that eventually. Actually I was already planning to implement that, together with other "go to the logical place in some other view" features. I probably won't get to it until I begin work on `v3`.

**Comment by tarsius** [comment]
`magit-diff-visit-file` now visits the "previous commit" if point is on a removed line in a hunk. See the doc-string for more information.

**Comment by tarsius** [comment]
I have temporarily reverted this change for the status buffer because that code path has a bug I have to look into.
