### ISSUE TITLE
Confirm cloning into non-empty directory

### ISSUE THREAD

**Issue by xiongtx** [magit/magit#2757]
## Problem
I just accidentally `magit-clone`'ed into my `github` directory, thinking that Magit would create a new directory with the same name as the GitHub repository. This is the behavior if you `cd` into the `github` directory and run `git clone <repo>` there.

Unfortunately, Magit cloned the repo directly into the `github` directory, overwriting existing contents.

## Suggestion
It would be useful for Magit to prompt the user if they are attempting to clone into a non-empty directory. Overwriting the contents of an existing directory is rarely what users would want to do, and is a destructive operation that warrants a warning.

**Comment by tarsius** [comment]
What Magit version are you using? I just tried to reproduce this but couldn't.

`magit-clone` uses `git clone URL DIRECTORY` and if directory already exists and is not empty, then this results in this error from git: `destination path '/tmp/foobar' already exists and is not an empty directory.`

**Comment by xiongtx** [comment]
You know, I'm an absolute dolt. I mixed up some directories. I see now that `magit-clone` fails when attempting to clone into a non-empty directory.
