### ISSUE TITLE
gpg: signing failed: No secret key

### ISSUE THREAD

**Issue by tmarble** [magit/magit#2761]
* what behavior you expected
When running `magic-commit-popup` that when accepting the default to GPG sign a commit 
`=S Sign using gpg (--gpg-sign="40BFEE868B055D9A Tom Marble <tmarble@info9.net>")`
if I select `c Commit`, enter a commit message and enter `C-c` that magit will sign
the commit using the long hex id of the key chosen.

* what behavior you observed
The entire string of the default shown above is used to populate the value for `--gpg-sign=`  which includes the UID and thus causes the following output in `*magic-process: my-project-name*` to be
````
128 src/main/clj/pamela/ git … commit --all --signoff --gpg-sign=40BFEE868B055D9A Tom Marble <tmarble@info9.net>
Waiting for Emacs...
gpg: skipped "40BFEE868B055D9A Tom Marble <tmarble@info9.net>": No secret key
gpg: signing failed: No secret key
error: gpg failed to sign the data
fatal: failed to write commit object
````
* and how we can reproduce the issue.<br/>
Attempt to gpg sign a commit (possibly where the version of gpg is >= 2).
  * Note: Debian unstable just migrated gpg to version 2.1.15
  * Also post the output of M-x magit-version RET<br/>
Magit 20160902.1451, Git 2.9.3, Emacs 24.5.1, gnu/linux

* Workaround

In `magic-commit-popup` by unselecting and selecting "Sign using gpg" (by presing **=S** twice) the user is prompted for *just* the long hexid of the previous GPG key, and then the correct gpg command line string is used and the signed commit succeeds.

**Comment by tarsius** [comment]
I haven't noticed this before because I am using Ido and seems to have a bug of its own which cancels this out. I'll try to fix this soon.

**Comment by tarsius** [comment]
```
magit-gpg-secret-key-hist: strip everything but the actual key
But keep displaying the name and email address anyway
as that makes it easier to identifying the correct key.
```

Thanks for making us aware of this issue.
