### ISSUE TITLE
First gpg-sign default does not respect default-key in ~/.gnupg/gpg.conf

### ISSUE THREAD

**Issue by tmarble** [magit/magit#2764]
This is a follow on to #2761 .. thank you for fixing magit-read-gpg-secret-key!

I updated magit from MELPA today and found that when I call `magit-commit-popup`
it populates the signing option with:
`=S Sign using gpg (--gpg-sign="40BFEE868B055D9A Tom Marble <tmarble@info9.net>")`
which is correct.

However when I make the commit it still fails with
````
128 src/main/clj/pamela/ git … commit --all --signoff --gpg-sign=40BFEE868B055D9A Tom Marble <tmarble@info9.net>
Waiting for Emacs...
gpg: skipped "40BFEE868B055D9A Tom Marble <tmarble@info9.net>": No secret key
````
I tried to read the `magit-invoke-popup` function, but it's a little complex but more importantly it's generalized to handle all sorts of popups.  It seems that when the commit is started `c Commit` it is at that point that the first token of the `=S` string should be used. I'm not sure of the correct place to put this sort of processing (i.e. if it should be when the popup closes -or- when the commit is actually done and the --gpg-sign argument is created)?

As a separate issue (which is the title of this bug) if I enter `=S` to clear gpg-signing and then enter `=S` again it prompts me for  a value which matches my UID, but it is for my old key. This actually may be a limitation of `'epa` as `(epa-list-secret-keys "tmarble@info9.net")` lists both my old key and new key. Ideally magit (perhaps via epa) would respect the setting of **default-key**  in `~/.gnupg/gpg.conf`.

As a potential workaround could you explain briefly how you have `'ido` setup to avoid this problem?

Thanks!

--Tom

**Comment by tarsius** [comment]
> when I call `magit-commit-popup` it populates the signing option with: `=S Sign using gpg (--gpg-sign="40BFEE868B055D9A Tom Marble <tmarble@info9.net>")` which is correct.

No that's not correct. It should be just `--gpg-sign="40BFEE868B055D9A`. The name part should only appear when completing.

The reason why you see `--gpg-sign="40BFEE868B055D9A Tom Marble <tmarble@info9.net>"` is that at one point you saved that using `C-x C-s`. You now have to press `= S` to disable the option and then `= S 40BFEE868B055D9A RET` followed by `C-x C-s` to save a new valid default.

**Comment by tmarble** [comment]
Indeed ensuring that the following is set in my `custom.el`...
````
 '(magit-commit-arguments
   (quote
    ("--all" "--signoff" "--gpg-sign=40BFEE868B055D9A")))
````
... resolves this issue.

Thanks!

--Tom
