### ISSUE TITLE
With-edit cannot be made to set EDITOR correctly when running Z-shell in an ansi term.

### ISSUE THREAD

**Issue by BernardHurley** [magit/magit#2767]
The correct command that Z-shell needs to set EDITOR to be the sleeping editor is:

````sh
export EDITOR=(  sh -c 'echo "WITH-EDITOR: $$ OPEN $0"; sleep 604800 & sleep=$!; trap "kill $sleep; exit 0" USR1; trap "kill $sleep; exit 1\" USR2; wait $sleep' )
````

The important thing to note is that a Z-shell array is required not a string.  When you enter term-mode, the variable `with-editor-sleeping-editor' gets wrapped in a string so there is no way of getting the correct setting for the Z-shell without changing the code.

A temporary solution I am using is to patch with-editor.el as follows but this is just to get it working for me!

*** with-editor.el-old  2016-09-13 14:39:16.078819068 +0100
--- with-editor.el      2016-09-13 14:38:39.287973295 +0100
***************
*** 548,554 ****
        (goto-char (process-mark process))
        (process-send-string
         process (format "export %s=%s\n" envvar
!                        (shell-quote-argument with-editor-sleeping-editor)))
        (while (accept-process-output process 0.1))
        (set-process-filter process filter)
        (if (derived-mode-p 'term-mode)
--- 548,554 ----
        (goto-char (process-mark process))
        (process-send-string
         process (format "export %s=%s\n" envvar
!                        "( sh -c 'echo \"WITH-EDITOR: $$ OPEN $0\"; sleep 604800 & sleep=$!; trap \"kill $sleep; exit 0\" USR1; trap \"kill $sleep; exit 1\" USR2; wait $sleep' )"))
        (while (accept-process-output process 0.1))
        (set-process-filter process filter)
        (if (derived-mode-p 'term-mode)

**Comment by tarsius** [comment]
> The correct command that Z-shell needs to set EDITOR to be the sleeping editor is:

For me the default works too. Zsh is backward compatible with bourne shells, so the syntax of the latter is supposed to work too.

Please describe what issue you are encountering and how to reproduce that. Use a new issue in the [`with-editor` repository](https://github.com/magit/with-editor) for that.

**Comment by BernardHurley** [comment]
>>>>> "Jonas" == Jonas Bernoulli <notifications@github.com> writes:

    >> The correct command that Z-shell needs to set EDITOR to be the
    >> sleeping editor is:
    Jonas> For me the default works too. Zsh is backward compatible with
    Jonas> bourne shells, so the syntax of the latter is supposed to
    Jonas> work too.

Zsh is not backward compatible with bourne shells[1]. This is particularly
noticeable in its treatment of spaces. For instance if I do:

% test="ls -l"
% $test

I get the error message:
zsh: command not found: ls -l

This is because, by default, zsh does not parse strings into words
separated by spaces and treats ��ls -l�� as the name of a command. If you
want separate words you need to use an array like so:

% test=(ls -l)
% $test

And it works as expected.

    Jonas> Please describe what issue you are encountering and how to
    Jonas> reproduce that. Use a new issue in the [`with-editor`
    Jonas> repository](https://github.com/magit/with-editor) for that.

    Jonas> -- You are receiving this because you authored the thread.
    Jonas> Reply to this email directly or view it on GitHub:
    Jonas> https://github.com/magit/magit/issues/2767#issuecomment-247169828

I will do that.


Footnotes: 
[1]  It can be configures to be more compatible with other shells.

-- 

Your fortune cookie for today:

Men use thought only to justify their wrong doings, and speech only to
conceal their thoughts.
		-- Voltaire

** Fortune cookies are brought to you by GNU/Linux "fortunes" **
