### ISSUE TITLE
Compute the contents of more collapsed sections lazily

### ISSUE THREAD

**Issue by dabrahams** [magit/magit#2768]
Magit 20160629.1156, Git 2.8.4 (Apple Git-73), Emacs 25.1.2, darwin

For example, Magit-over-TRAMP is extremely slow during a rebase with many commits—it spends an inordinate amount of time transferring the contents of rebase-apply/—, but that's an extreme case.  I've also seen this slowness when running locally.

My theory is that magit is gathering all the information it needs to display everything in every section even if it's going to be collapsed.  The big win would be to compute these contents on-demand and cache them.

I've also seen this phenomenon with local (non-TRAMP) usage.

**Comment by tarsius** [comment]
> Magit could compute the contents of collapsed sections lazily

Yes, we should. That's one of the big changes planned for `v3`.

> ... and cache them.

That too.

> My theory is that magit is gathering all the information it needs to display everything in every section even if it's going to be collapsed.

In some cases we actually already do that, for example the cherries in the refs buffer. But that has to be generalized.

**Comment by dabrahams** [comment]
on Wed Sep 14 2016, Jonas Bernoulli <notifications-AT-github.com> wrote:

>> Magit could compute the contents of collapsed sections lazily
>
> Yes, we should. That's one of the big changes planned for `v3`.

That's great news, thanks.

-- 
-Dave

**Comment by unhammer** [comment]
Will this also help with large files? I had a change to a megabytes-large file that made magit-status really slow – it'd be nice if magit could have some heuristic of not showing large diffs until explicitly requested (this goes for the diff shown on committing too).

**Comment by tarsius** [comment]
@unhammer yes, but only part of the work is delayed, i.e. the diffs are not painted until expanded, but some work happens before then. In the future all of it will be delayed.

Also see `magit-diff-expansion-threshold`, but that's a hack.

**Comment by dgtized** [comment]
Perhaps this should be a separate issue (happy to split it out), but I just realized the main reason that `magit-refs` was slow on a large repo was from regenerating the list of 3087 tags on every refresh.

By customizing 

```elisp
(setq magit-refs-sections-hook
      '(magit-insert-error-header
        magit-insert-branch-description
        magit-insert-local-branches
        magit-insert-remote-branches
        ;; magit-insert-tags
))
```

And removing the `magit-insert-tags` I sped up the `magit-refs` buffer considerably. However on other repos where there are not thousands of deploy tags it would be great if I could toggle the display of tags.

I presume this is an example of what you mean by "computing the contents of collapsed sections lazily", but thought I would mention this as a specific performance issue and the temporary work around.

**Comment by tarsius** [comment]
> Perhaps this should be a separate issue (happy to split it out)

I'll soonish open a bunch of issues for big unresolved issues.

> I presume this is an example of what you mean by "computing the contents of collapsed sections lazily", but thought I would mention this as a specific performance issue

Other things play into it as well. Such as caching and/or not recreating that part of the buffer at all. And `magit-tag` knowing it has to invalidate the cache, and what about `git tag` outside of Magit... ;-)

> and the temporary work around.

You could also add a wrapper  function that does nothing in certain repositories.
