### ISSUE TITLE
git-rebase-show-commit asks to save git-rebase-todo

### ISSUE THREAD

**Issue by fice-t** [magit/magit#2770]
1) `emacs -Q`
2) `magit-status` a repo and do an interactive rebase with several commits
3) Press RET on any of the commits

Perhaps this is an intended safety measure in this case, but I find it more annoying than anything. However, I usually like the save prompt in other situations.

Could `git-rebase-todo` be exempt from ` magit-save-repository-buffers` at least in the case of `git-rebase-show-commit`?

`Magit 20160902.1451, Git 2.9.3, Emacs 25.1.3, gnu/linux`

**Comment by tarsius** [comment]
> Could `git-rebase-todo` be exempt from ` magit-save-repository-buffers` at least in the case of `git-rebase-show-commit`?

It seems to me that this is one of those situations when you *really* want to save the buffer. Say you edit file but don't save it, then you start a rebase and a conflict occurs in exactly that file? What now? You have to save your work manually in some other file, resolve the conflict, and finish the rebase. Then you have to recover the changes from the temporary file, but it might not be as simple as just copying it to the proper location and Magit won't be able to help you merging.

**Comment by tarsius** [comment]
Instead I would recommend that you set `magit-save-repository-buffers` to `t` and permanently enable `---autostash` in the rebase popup.

**Comment by fice-t** [comment]
I believe there's been some miscommunication. What I meant by that was: could the file `git-rebase-todo` itself be exempt from the save prompt (not the other files in the git repository).

i.e. I'd rather not be prompted with `Save file <repo>/.git/rebase-merge/git-rebase-todo? (y, n, ...)` when viewing commits using RET in `git-rebase-mode` even when no other files in the repository are modified.

**Comment by tarsius** [comment]
Well, it's late here... will look at this in a few days.

**Comment by kyleam** [comment]
I've looked into a bit and don't think asking to save the buffer is a
useful behavior (see commit message of #2771).

**Comment by fice-t** [comment]
@kyleam That works for me, thanks.
