### ISSUE TITLE
git-commit font-lock improvements

### ISSUE THREAD

**Issue by fice-t** [magit/magit#2772]
- [x] Was a non-empty 2nd line intended to be highlighted like an overly long summary line? It's currently not highlighted at all for me.
- [ ] It would be nice if the branches in the following comment lines were highlighted just like `# On branch master` is:

`# Your branch is up-to-date with 'origin/master'.`
`# Your branch and 'origin/master' have diverged,`
`# Your branch is ahead of 'origin/master' by 1 commit.`
`# Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.`
- [ ] It'd also be nice if the numbers used in the above were highlighted as well.
  The diverged case has the extra line: `# and have 1 and 1 different commits each, respectively.`
- [ ] Highlighting squash commit comments would be great as well. Some example lines that could be highlighted:

```
# This is a combination of 27 commits.
# The first commit's message is:
# This is the 2nd commit message:
# This is the 3rd commit message:
# This is the n{th,st,nd,rd} commit message:

# Author:    name <email>
# Date:      Fri Oct 31 10:13:44 2014 -0400
# interactive rebase in progress; onto 7e16917

# Last commands done (35 commands done):
#    squash ad6b85d Some commit
#    squash 75bd5c7 Other commit

# Next commands to do (30 remaining commands):
#    pick 1523650 Some commit
#    pick 458b500 Other commit

# You are currently editing a commit while rebasing branch 'master' on '7e16917'.
```

`Magit 20160902.1451, Git 2.9.3, Emacs 25.1.3, gnu/linux`

**Comment by npostavs** [comment]
> 1) Was a non-empty 2nd line intended to be highlighted like an overly long summary line? It's currently not highlighted at all for me.

The highlighting seems to be delayed. Hitting <kbd>M-o M-o</kbd> makes it show up.

**Comment by fice-t** [comment]
> The highlighting seems to be delayed. Hitting M-o M-o makes it show up.

That's interesting. Hopefully that can be fixed.

**Comment by npostavs** [comment]
>> The highlighting seems to be delayed. Hitting <kbd>M-o M-o</kbd> makes it show up.
> 
> That's interesting. Hopefully that can be fixed.

I think I got it, see #2777.

**Comment by fice-t** [comment]
Oh, I didn't know about `font-lock-extend-region-functions` -- neat.

The PR works for me, thanks.

**Comment by tarsius** [comment]
If started with a feature branch for the rest: https://github.com/magit/magit/compare/jb/more-font-lock?expand=1

**Comment by tarsius** [comment]
@fice-t Before diving into the rebase thing, you might want to implement your above suggestions instead. That seems much easier.

**Comment by fice-t** [comment]
Sure, I implemented them in #2803. I have a few questions though:

* Should the author name/email and date be highlighted (as opposed to just the Author/Date headers)?

* Should the number face be made bold by default? I ask since I noticed that you made `git-rebase-comment-hash` bold.

* Should different commit actions be highlighted in different colours to better distinguish between modified/deleted/added?

**Comment by tarsius** [comment]
1. No.
2. Maybe it should be made bold *instead*. Also `# This is the commit message #2:` isn't fontified.
3. No. And I think the commit messages should use the regular comment color. Maybe even the command.

**Comment by fice-t** [comment]
> Maybe it should be made bold instead.

Sure. I suppose it does look better in the default theme.

> Also `# This is the commit message #2:` isn't fontified.

Apparently that's new in Git 2.10. The wording is a bit awkward. Anyways, I added it with a note that previous regex is obsolete.

> And I think the commit messages should use the regular comment color. Maybe even the command.

Would you elaborate on that? What part of the commit messages are you referring to, and which command?

**Comment by tarsius** [comment]
```
# Last commands done (35 commands done):
#    squash ad6b85d Some commit
     ~~~~~~         ~~~~~~~~~~~            THIS
```

Unfortunately these changes make the comments look like an attempt to win the competition for the flashiest Christmas decoration in the neighborhood. Taken together, these changes distract to much from the important part; the commit message. Without some moderation, this would be a step backward in my opinion.

I suggest you put most of this into one or more separate functions, which could then be added to a hook by users who want all this.

**Comment by fice-t** [comment]
> Unfortunately these changes make the comments look like an attempt to win the competition for the flashiest Christmas decoration in the neighborhood ;-)

Well, I like to do things flashily :-)

> I suggest you put most of this into one or several separate functions, which could then be added to a hook by users who want all this.

I pushed a new version of it that implements `git-commit-font-lock-extra-hook` to do this.

I only put the rebase command and file actions (which was present before) as optional keywords.

Should I make other classes (headers, branches, numbers, etc.) optional as well?

Also, should I make the flashier stuff opt-in or opt-out?

**Comment by tarsius** [comment]
https://github.com/magit/magit/pull/3307#issuecomment-351782635
