### ISSUE TITLE
Support optional positional arguments in magit-popup

### ISSUE THREAD

**Issue by vermiculus** [magit/magit#2773]
It would be handy for `magit-popup` to support optional positional arguments. While poking around, I had these 'working' as `:options` with no `OPTION`:

``` elisp
:options '((?o "Optional positional argument" "")) ; leaving as nil crashes
```

It's hacky, but this might give a clue on how the feature could be implemented.

I eventually took the functionality out because of the hackiness – true support for this kind of argument would be much appreciated 😄

Here's my use case:
- [the `magithub` emacs package](https://github.com/vermiculus/magithub)
- [the `hub` command line tool](https://hub.github.com)
  
  Specifically, the `create` command has `NAME` as an optional positional argument:
  
  ```
  hub create [NAME] [-p] [-d DESCRIPTION] [-h HOMEPAGE]`
  ```

**Comment by tarsius** [comment]
I plan to replace `magit-popup` eventually, currently it is a huge mess and I don't want to add any more features. Currently you do have to "translate" the argument inside the `interactive` form of each action command. If there are multiple such commands you might want to create a helper function. The commands should have a signature like `(POSARG &rest ARGS)` and the helper function should remove POSARG from ARGS, transform POSARG by removing the fake argument from the value, and then return `(list POSARG ARGS)`. In your case I would recommend `"Name: "` as the fake argument, which makes clear that it is not a regular `--argument=`.

**Comment by tarsius** [comment]
Transient implements some support for this, but some work on the part of the author of the suffix command is required.

The values of switches and options are strings by default. `transient-args` supports splitting strings from other values.

Magit uses one positional argument right now, the complete implementation is this

```emacs-lisp
;;; from transient.el

(defclass transient-files (transient-infix) ()
  "Class used for the \"--\" argument.
All remaining arguments are treated as files.
They become the value of this this argument.")

(cl-defmethod transient-init-value ((obj transient-files))
  (oset obj value
        (cdr (assoc "--" (oref transient--prefix value)))))

(cl-defmethod transient-infix-value ((obj transient-files))
  (when-let ((value (oref obj value)))
    (cons (oref obj argument) value)))

(cl-defmethod transient-format-value ((obj transient-files))
  (let ((argument (oref obj argument)))
    (if-let ((value (oref obj value)))
        (propertize (concat argument " "
                            (mapconcat (lambda (f) (format "%S" f))
                                       (oref obj value) " "))
                    'face 'transient-argument)
      (propertize argument 'face 'transient-inactive-argument))))

;;; from magit-diff.el

(define-infix-argument magit:-- ()
  :description "Limit to files"
  :class 'transient-files
  :key "--"
  :argument "--"
  :prompt "Limit to file(s): "
  :reader 'magit-read-files
  :multi-value t)

;; There are some unrelated complications so this is not
;; the code that is actually being used right now

(defun magit-diff-dwim (&optional args files)
  "Show changes for the thing at point."
  (interactive
   (pcase-let ((`(,args ,plist))(transient-args 'magit-diff nil #'stringp))
     (list args (cadr (assoc "--" plist)))))
  ...)
```

There is no generic `transient-positional-option` class yet. I'll probably create that eventually. For now people who want to use positional arguments will have to define their own class and implement these methods. Eventually only ` :class 'transient-files` and

```emacs-lisp
   (pcase-let ((`(,args ,plist))(transient-args 'magit-diff nil #'stringp))
     (list args (cadr (assoc "--" plist)))))
```

should be necessary. But I consider this supported already. It just needs a bit of code.
