### ISSUE TITLE
FR: key prefix registry for plugins

### ISSUE THREAD

**Issue by aspiers** [magit/magit#2779]
Whilst discussing what prefix key the new `magithub` should use, @vermiculus came up with [the very nice suggestion of starting a key prefix registry for magit plugins](https://github.com/vermiculus/magithub/issues/10#issuecomment-247864544).  It could also list the currently unused prefixes remaining.  This would make it easier and safer for plugins to choose a non-conflicting key prefix. 

I guess this could be a simple wiki page, or part of the official docs.

**Comment by tarsius** [comment]
Contributions welcome ;-)

> I guess this could be a simple wiki page, or part of the official docs.

That seems best.

**Comment by aspiers** [comment]
Which one, or don't you mind which?

**Comment by vermiculus** [comment]
If the wiki can be edited by anyone without intervention, I think the formal PR process would help curate the list and keep it tidy (and prevent bloating).

**Comment by npostavs** [comment]
Based on the experience with https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands, even though anyone can edit the wiki, it seldom actually happens.

**Comment by tarsius** [comment]
> Which one, or don't you mind which?

Ups, copy-pasted too much. The wiki.

**Comment by vermiculus** [comment]
How does this look?

https://github.com/magit/magit/wiki/Plugin-Dispatch-Key-Registry

**Comment by aspiers** [comment]
Cool, thanks! I think it would also be worth having a list of unused prefixes.

**Comment by vermiculus** [comment]
@aspiers such a list would be very, very large, wouldn't it?

**Comment by aspiers** [comment]
If limited to single 7-bit ASCII printable characters, no - it would be a very small list.

**Comment by aspiers** [comment]
(Another better way of describing this restriction would be "limit it to characters typeable on a standard English-alphabet keyboard".)

**Comment by vermiculus** [comment]
Updated

**Comment by tarsius** [comment]
That looks very useful now. Thanks!

**Comment by aspiers** [comment]
@tarsius I guess it only remains to provide a link to it from other appropriate places in the docs, and then we can close this.

**Comment by tarsius** [comment]
Where would you put such a notice? I guess the FAQ would work.

**Comment by aspiers** [comment]
Is there a guide anywhere for plugin developers? If so that would be the best place.

**Comment by vermiculus** [comment]
If it's going to make it in the repository, would it be worthwhile throwing a pointer in a few `magit-popup` docstrings?

**Comment by tarsius** [comment]
> Is there a guide anywhere for plugin developers?

If added a note to the Plumbing node.

> If it's going to make it in the repository,

I want to keep it on the wiki.

> would it be worthwhile throwing a pointer in a few magit-popup docstrings?

That doesn't seem appropriate. Despite the name `magit-popup` is actually usable by itself.

**Comment by tarsius** [comment]
Thanks everyone!

**Comment by vermiculus** [comment]
> I want to keep it on the wiki.

The pointer, I meant -- the wiki is fine for the actual registry :+1: 

Just for my own education, is this [the Plumbing node you're talking about](https://github.com/magit/magit/blob/cb964fe52b598cdbcac060af2f24de096523edf4/Documentation/magit.texi#L252)?

**Comment by tarsius** [comment]
Yes, that node.
