### ISSUE TITLE
Git developers are asking for feedback from Magit users

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2781]
They asked on our (mostly dormant) mailing list: https://groups.google.com/forum/?fromgroups#!topic/magit/0VX0TwWnttI.

Please use this link to go to the survey: https://survs.com/survey/iewjiz0o8u.

Thanks!

**Comment by tarsius** [comment]
The survey ends at the 20th of October.

**Comment by aspiers** [comment]
Thanks for the heads-up - filling this in now!
