### ISSUE TITLE
magit-log-buffer-file: list commits before rename

### ISSUE THREAD

**Issue by benma** [magit/magit#2784]
Calling `magit-log-buffer-file` shows a list of commits which touch the current file. It ignores renames though, so if a commit added the file through a rename (deletion of another file), the log stops there. I would like to see the full history of the file, including renames.

(magit-blame seems to be able to trace through renames).

**Comment by benma** [comment]
Using `magit-log-buffer-file` and enabling

` -f Follow renames when showing single-file log (--follow)`

did not show more commits, unfortunately.

**Comment by tarsius** [comment]
Please consult the documentation:

```lisp
(defun magit-log-buffer-file (&optional follow beg end)
  "Show log for the blob or file visited in the current buffer.
With a prefix argument or when `--follow' is part of
`magit-log-arguments', then follow renames."
  ...)
```

**Comment by tarsius** [comment]
You have to save `--follow` to be used by default. To do so enter the regular log popup, enable the argument, and then press `C-x C-s`.
