### ISSUE TITLE
Customizing magit-auto-revert-mode to nil is overriden outside of customize

### ISSUE THREAD

**Issue by Blaisorblade** [magit/magit#2786]
After customizing it to nil (from `M-x customize-group RET magit RET`) and rebooting, I expect the feature to be disabled.
Instead, the variable is still enabled, magit-auto-revert-mode is still loaded when starting magit, and it says "CHANGED outside Customize." and it is on.
I've also confirmed that if I boot Emacs, not run `magit-status` (which loads the mode) but just `(require 'magit)`, customize still shows the same status.

The only way to disable it, for me, was the following code in `.emacs`:

```elisp
(defun after-packages-loaded-hook ()
  (require 'magit)
  (setq magit-auto-revert-mode nil))
(add-hook 'after-init-hook
          #'(lambda ()
              (after-packages-loaded-hook)))
```
(I had most of the infrastructure already, still this seems a bit much).

To debug this, I already commented out most of my `.emacs`. The above trick fixed this immediately.

I only found info on 4619be586fc9ed8a267a96be41929933541425b5—I see it is initialized to true through the `:init-value`, but shouldn't customization override that? `custom-set-variables` is called with `'(magit-auto-revert-mode nil)` as expected.

Magit version: `Magit 20160919.605, Git 2.9.3, Emacs 24.5.1, darwin`.

## Reproducing with Magit alone

I tried but ended up with #2785. Also, what should be tested requires a more involved procedure, because `magit-auto-revert-mode` is already enabled after `-l magit`. Indeed, running 

```
/Applications/Emacs.app/Contents/MacOS/Emacs -Q --debug-init --eval "(setq debug-on-error t)" -L ../dash-20160820.501 -L ../with-editor-20160828.1025/ -L ../git-commit-20160917.2127/ -L ../magit-popup-20160821.1338/ -L . -L lisp -l magit
```

Gives these messages:
```
Turning on magit-auto-revert-mode...done
Cannot determine Magit's version (error "/Users/pgiarrusso/.emacs.d/elpa/magit-20160919.605/magit.el" repo static elpa)
```

However, somehow, using customization in that context seems to work O_O:
```
/Applications/Emacs.app/Contents/MacOS/Emacs -Q --debug-init --eval "(setq debug-on-error t)" --eval "(custom-set-variables '(magit-auto-revert-mode nil))" -L ../dash-20160820.501 -L ../with-editor-20160828.1025/ -L ../git-commit-20160917.2127/ -L ../magit-popup-20160821.1338/ -L . -L lisp -l magit
```
Does that mean I need to bisect this further?

**Comment by npostavs** [comment]
I'm not able to reproduce. Since this involves customization, to check this I created a new `HOME` directory, with the following `.emacs.d/init.el`:
```elisp
(package-initialize)
(setq package-archives
    '(("gnu" . "http://elpa.gnu.org/packages/")
     ("melpa" . "http://melpa.milkbox.net/packages/")))
```
Then,
- `M-x package-install RET magit RET`
- `M-x customize-option RET magit-auto-revert-mode RET`
- Click the `toggle` button, to set it to `off`.
- Click the `Apply and Save` button.
- `C-x C-c`
- Start Emacs again
- `M-: (require 'magit)`
- `M-x customize-option RET magit-auto-revert-mode RET`

`magit-auto-revert-mode` is `off (nil)`, State: `SAVED and Set`.

> However, somehow, using customization in that context seems to work O_O:

Maybe something else in your init is turning it on?

**Comment by Blaisorblade** [comment]
Thanks for the prompt attempt. FWIW, my customization config (for magit) is:

```
 '(magit-auto-revert-mode nil)
 '(magit-diff-arguments (quote ("--no-ext-diff" "-M" "-C")))
 '(magit-diff-refine-hunk t)
 '(magit-expand-staged-on-commit (quote full))
 '(magit-fetch-arguments (quote ("--prune")))
 '(magit-log-auto-more t)
 '(magit-log-cutoff-length 20)
 '(magit-no-confirm (quote (stage-all-changes unstage-all-changes)))
 '(magit-process-connection-type nil)
 '(magit-push-always-verify nil)
 '(magit-push-arguments (quote ("--set-upstream")))
 '(magit-refresh-file-buffer-hook nil)
 '(magit-save-some-buffers nil)
 '(magit-set-upstream-on-push (quote askifnotset))
 '(magit-stage-all-confirm nil)
 '(magit-status-verbose-untracked nil)
 '(magit-unstage-all-confirm nil)
 '(magithub-message-confirm-cancellation nil)
 '(magithub-use-ssl t)
```

But feel free to close for now—I should probably debug this harder (later).
