### ISSUE TITLE
Add [ci-skip] automatically when all files in a commit match any of a set of regexps

### ISSUE THREAD

**Issue by vermiculus** [magit/magit#2788]
It'd be nice be able to auto-skip CI testing for changes to the README, for instance.  Something like

```elisp
(defvar magit-commit-ci-skipped-regexps '("\\`*.md\\'")
  "List of filepath regexps.
If all files in a commit match any of these regexps, the ommit
message is automatically appended with [ci-skip].")
```

**Comment by tarsius** [comment]
I think the CI implementation itself would be a more appropriate place to implement this. It should allow specifying that regexp in its configuration file. I for one don't want to litter my commit messages just so CI can avoid some inefficiency. I'll leave this open for a while, maybe I'll change my mind.

**Comment by vermiculus** [comment]
Fair enough – CI is indeed extraneous to git 👍

**Comment by npostavs** [comment]
You might be able to implement this in `prepare-commit-msg` hook.

**Comment by vermiculus** [comment]
@npostavs I've rekindled an issue for this on Travis particularly, but I am still interested in workarounds for now 😄 however, that variable isn't defined for me…

**Comment by npostavs** [comment]
It's not an Emacs variable, it's a [githook](https://git-scm.com/docs/githooks).
