### ISSUE TITLE
recursive magit-blame broken

### ISSUE THREAD

**Issue by dscole** [magit/magit#2790]
I'm running magit from spacemacs and this is the magit-version:
Magit 20160710.1341, Git 2.9.3, Emacs 24.5.1, gnu/linux

The problem is when I try to reblame something. First magit-blame always works, but reblaming seems to only work if the file in question is in the top directory. I think the issue is that the underlying git blame command is being run while the cwd is the file's directory, instead of running it from the top directory in the repo. I think it's easiest to see it from the *magit-process buffer. For example when I run magit-blame on core/core-auto-completion.el (a file in spacemacs git repo) I get this:
```
  0 git … blame --incremental -w -L 1,36 -- core/core-auto-completion.el
  0 git … blame --incremental -w -- core/core-auto-completion.el
128 core/ git … blame --incremental -w -L 1,37 d29ef7f3393a31fa0491fb86d6299254cbdbee71 -- core/core-auto-completion.el
128 core/ git … blame --incremental -w d29ef7f3393a31fa0491fb86d6299254cbdbee71 -- core/core-auto-completion.el
```

The first 2 commands are run by the original magit-blame (run using SPC g b). The following 2 are the result of hitting 'b' on some blamed section (the 3rd line in the output of the first magit-blame).

This issue doesn't exist if I blame a file at the top directory. So for example in the spacemacs repo if I blame the file README.md, I can continue to recursively blame with no issue. This is the output in *magit-process when I use README.md:
```
  0 git … blame --incremental -w -L 1,37 -- README.md
  0 git … blame --incremental -w -- README.md
  0 git … blame --incremental -w -L 1,37 c9bcb65fa14682577eaff33191b04f42bc0d77d4 -- README.md
  0 git … blame --incremental -w c9bcb65fa14682577eaff33191b04f42bc0d77d4 -- README.md
```
I hope what I wrote makes sense, please let me know if you need more info.

**Comment by npostavs** [comment]
> Magit 20160710.1341

Try updating, I believe this is a dup of #2731, and so should be fixed.

**Comment by dscole** [comment]
Yeah that solved it thanks.
