### ISSUE TITLE
user-error: Not inside a Git repository in emacsclient

### ISSUE THREAD

**Issue by m31271n** [magit/magit#2793]
Hi, i came across a strange problem.

1. I have a command `ec` which alias to `emacsclient -c -a "" $@`. 
2. Start emacs with `ec`.
3. When running <kbd>M-x magit-status</kbd> in a emacs client, it will occur an err: 

```
Create repository in /tmp/repo/? (y or n) y
user-error: Not inside a Git repository
```

* Above messages are copied from buffer `*Message*`.
* `/tmp/repo/` is a valid git repo.

* * *

When I start emacs with command `emacs`, everything is ok.

* * *

Save me, man.

**Comment by tarsius** [comment]
What Magit version are you using? I think this is an issue that has been fixed already.

**Comment by m31271n** [comment]
I have updated to 20160921.834. The issue is fixed. TX for your efforts.
