### ISSUE TITLE
Missing expand-file-name

### ISSUE THREAD

**Issue by dabrahams** [magit/magit#2796]
When doing \`b W', when the path specified starts with `~`, it creates the new worktree in a subdirectory of the repository's main worktree called "~".

The magit-process buffer contains the following:

  0 git … worktree add -b swift-2.2-with-migration-attributes ~/src/s/swift-2.2-with-migration origin/swift-2.2-with-migration-attributes
Branch swift-2.2-with-migration-attributes set up to track remote branch swift-2.2-with-migration-attributes from origin.
Preparing ~/src/s/swift-2.2-with-migration (identifier swift-2.2-with-migration)

The path should be expanded before it's passed to Git.

**Comment by tarsius** [comment]
Thanks for reporting!
