### ISSUE TITLE
Show extra PGP information?

### ISSUE THREAD

**Issue by fice-t** [magit/magit#2797]
In `magit-log` with `-S` a trusted signed commit message is highlighted as expected, but it doesn't show the GPG user/key ID as it does in `git log --show-signatures`.

Could this extra info be put into the revision buffer (maybe also in the log buffer optionally)?

PS: I noticed magit does not handle the case when the commit is GPG-signed but the key is not in your keyring. In `git log --show-signatures` it shows `gpg: Can't check signature: public key not found`, but nothing happens in magit. Could magit detect this case and associate a new face to it?

`Magit 20160902.1451, Git 2.9.3, Emacs 25.1.3, gnu/linux`

**Comment by fice-t** [comment]
> PS: I noticed magit does not handle the case when the commit is GPG-signed but the key is not in your keyring. In git log --show-signatures it shows gpg: Can't check signature: public key not found, but nothing happens in magit. Could magit detect this case and associate a new face to it?

Oh, I found out that it was as simple as adding an `N` case to the pcase in `magit-log-wash-rev`. Should that be added with a corresponding face?

**Comment by tarsius** [comment]
> Could this extra info be put into the revision buffer

Add `%GG` or a related placeholder to `magit-revision-headers-format`.

**Comment by tarsius** [comment]
> Oh, I found out that it was as simple as adding an `N` case to the pcase in `magit-log-wash-rev`. Should that be added with a corresponding face?

`N` means "no signature". In that case `nil` is used as the face, which is the same as specifying no face at all, so the `default` face will be used. There already is a case for each of the other possible values of `%G?`.

> I noticed magit does not handle the case when the commit is GPG-signed but the key is not in your keyring.

The `U` case should handle that. Check what `magit-signature-untrusted` looks like; maybe the author of the theme you are using does not care to differentiate between unsigned and signed with unknown key and changed the appearance of that face accordingly.

**Comment by fice-t** [comment]
> Add %GG or a related placeholder to magit-revision-headers-format.

Thanks, that gets the proper info there.

Is it possible to both only show `%GG` when the revision is GPG-signed, and also to fontify the block with the proper `magit-signature-*` face?

**Comment by fice-t** [comment]
> N means "no signature". In that case nil is used as the face, which is the same as specifying no face at all, so the default face will be used. There already is a case for each of the other possible values of %G?.

Sorry, I made a mistake last night. Indeed `N` means "no signature" instead of "not a valid signature".

> The U case should handle that. Check what magit-signature-untrusted looks like; maybe the author of the theme you are using does not care to differentiate between unsigned and signed with unknown key and changed the appearance of that face accordingly.

I thought that at first, but that's not the case. There is a difference and it shows in `emacs -Q`. The untrusted key is highlighted in `magit-signature-untrusted`, but the missing key isn't highlighted at all.

Doing `git verify-commit` on a commit with an untrusted key results in (with no error):

````
gpg: Signature made <time> using RSA key ID <id>
gpg: Good signature from <user ID>
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: <key>
```

Doing the same with a missing key yields (with error code 1):

```
gpg: Signature made <time> using RSA key ID <id>
gpg: Can't check signature: public key not found
```

To note, `git verify-commit` on a non-signed commit just yields an error code of 1 with no message.

**Comment by tarsius** [comment]
`git-log(1)` sais:

> %G?: show "G" for a good (valid) signature, "B" for a bad
> signature, "U" for a good signature with unknown validity and
> "N" for no signature

but actually `N` is printed for all commits which are either not signed at all, or are signed with a key whose pulbic part is not available. Or it other words `%G?` is `N` if `git verify-commit` either prints

```
gpg: Signature made Sun 18 Sep 2016 06:00:24 AM CEST
gpg:                using RSA key 834D7DFD71EBA988
gpg: Can't check signature: public key not found
```

or nothing at all.

Maybe I am missing something, but it seems impossible to differentiate not-signed/no-public-key using `%G?`.

**Comment by tarsius** [comment]
> Is it possible to fontify the block (or part of it) with the proper `magit-signature-*` face?

No.

Also, is there a way to perhaps a way to add this section only when there's GPG information? It's a minor issue, but it would be nice to add `\n%GG` to `magit-revision-headers-format` without having that extra newline appear in unsigned commits.

Not possible either.

Well, you could add an additional "section inserter" to `magit-revision-sections-hook` and make that do whatever is necessary to make this happen.

**Comment by fice-t** [comment]
> Maybe I am missing something, but it seems impossible to differentiate not-signed/no-public-key using %G?.

It unfortunately seems that way. I tried using `%GG` and changing `magit-log-heading-re` accordingly, but it seems the newlines present in `%GG` make magit angry. Perhaps I could ask git to support it upstream?

**Comment by tarsius** [comment]
> it seems the newlines present in `%GG` make magit angry

;-) Indeed.

**Comment by tarsius** [comment]
> Perhaps I could ask git to support it upstream?

Worth a try.

I am closing this as I don't intend to implement prettier gpg information in revision buffers. At least not anytime soon.

**Comment by fice-t** [comment]
@tarsius 
> Well, you could add an additional "section inserter" to magit-revision-sections-hook and make that do whatever is necessary to make this happen.

Alright. What do you think of the following? Do you suppose something like it could be added to magit? It just colorizes the whole block, but with a bit more regexp work it can be fine-tuned.

```elisp
(defface magit-signature-missing
  '((t :foreground "blue"))
  "Missing"
  :group 'magit-faces)

(defun magit-insert-revision-gpg (rev)
  (-when-let (gpg (magit-rev-format-all "%GG" rev))
    (let ((key-id (progn (string-match (concat "^gpg: Signature made .* using [RD]SA "
                                               "key ID \\(?1:[[:xdigit:]]+\\)\n")
                                       gpg)
                         (match-string 1 gpg)))
          (good (string-match "^gpg: Good signature from \"[^\"]+\"$" gpg))
          (bad (string-match "^gpg: BAD signature from \"[^\"]+\"$" gpg))
          (untrusted (string-match "^gpg: WARNING: This key is not certified" gpg))
          (missing (string-match "^gpg: Can't check signature: public key not found$" gpg)))
      (magit-insert-section (gpg key-id)
        (let ((face (cond (untrusted 'magit-signature-untrusted)
                          (good 'magit-signature-good)
                          (bad 'magit-signature-bad)
                          (missing 'magit-signature-missing))))
          (insert (propertize gpg 'face face) "\n\n"))))))
```

To set it up:
```elisp
(setq magit-revision-sections-hook '(magit-insert-revision-tag magit-insert-revision-headers magit-insert-revision-gpg magit-insert-revision-message magit-insert-revision-notes magit-insert-revision-diff magit-insert-xref-buttons))
```

It also uses this new function, of which I'm not sure if there's an equivalent. Is there a better way to get all of a git format's output as a string? `magit-rev-format` just gets the first line.

```elisp
(defun magit-rev-format-all (format &optional rev args)
  (let ((str (magit-git-lines "show" "--no-patch"
                               (concat "--format=" format) args
                               (if rev (concat rev "^{commit}") "HEAD") "--")))
    (when str
      (string-join str "\n"))))
```

**Comment by basil-conto** [comment]
> I don't intend to implement prettier gpg information in revision buffers. At least not anytime soon.

Just curious: any status change on this? What about including the solution of @fice-t above or similar?

**Comment by tarsius** [comment]
> any status change on this?

I think it fell through the cracks. Having a look now.

**Comment by tarsius** [comment]
@fice-t Could you open a pr to make it easier to try this out and do a review.

Just add the `magit-rev-format-all` as-is for the time being.

**Comment by fice-t** [comment]
@tarsius 
> Could you open a pr to make it easier to try this out and do a review.

I could, but I think the situation has changed a bit.

I don't think the above `magit-rev-format-all` is good since `magit-git-lines` creates a list of strings just for `magit-rev-format-all` to `string-join` them. I think it would be better to just find and replace any empty elements and return the output string directly (or don't omit the nulls).

Also, I'm not sure why `magit-rev-format` only considers the first line. It would be nice if it were documented to explain this, as well as possibly renamed to something like `magit-rev-format-line`.

I also don't use the above `magit-rev-format-all` in my 2nd implementation of this feature, though I use a different helper procedure which I'll post below.

**Comment by fice-t** [comment]
[I put my current implementation in a gist. If it's on the right track, then I can make a PR for it.](https://gist.github.com/fice-t/c84c3bc7007d0d4bcacfeb2c0e42ac27)


@basil-conto If you're interested in this feature, then would you see if the above is good for you?

@tarsius Is there any way to have to have a hidden sections of the parent sections from the children? For instance, suppose I have:

```
GPG Status: VALID (press TAB to toggle raw output)
GPG Signer: <signer>
GPG Key:    <key>

gpg: Signature made <date>
gpg:                using RSA key <key>
gpg: Good signature from <signer>
```

Where the `GPG Signer:` and `GPG Key:` lines are each their own sections. I would like to be able to press TAB on the Signer/Key lines and have it toggle the `gpg: ` raw output lines just like I can in the parent section (the `GPG Status:` line).

**Comment by basil-conto** [comment]
@fice-t Looks great, thanks! :)

Personally I would prefer to place the GPG headers after the ones in `magit-revision-headers-format` and before the ones controlled by `magit-revision-insert-related-refs`, so as to keep authorship information closer together, but that would probably require some extra work and it's not a big issue for me.

FYI you can avoid having to set the entire value of `magit-revision-sections-hook` by writing the following:

```el
(magit-add-section-hook 'magit-revision-sections-hook
                        #'magit-insert-revision-gpg
                        #'magit-insert-revision-headers
                        t)
```

**Comment by npostavs** [comment]
> I don't think the above magit-rev-format-all is good since magit-git-lines creates a list of strings just for magit-rev-format-all to string-join them. I think it would be better to just find and replace any empty elements and return the output string directly (or don't omit the nulls).

The time spent making and destroying strings is likely neglible next to the time spent calling the external git process. But if you really can't get past it, the most efficient way is to use `magit-git-insert`, use a temp buffer to gather into a string (or just operate on the buffer text directly).

> I put my current implementation in a gist. If it's on the right track, then I can make a PR for it.

You can make a PR even if it's on the wrong track, I promise we won't run out of PR numbers ;)

**Comment by tarsius** [comment]
While we are at it, we should also look into #3015.
