### ISSUE TITLE
Author and date aren't highlighted when selecting commits in magit-log-mode

### ISSUE THREAD

**Issue by fice-t** [magit/magit#2798]
If you select multiple commits in the log buffer then the authors and dates don't get highlighted with `magit-section-heading-selection` like the rest of the lines.

Is this an implementation limitation?

`Magit 20160902.1451, Git 2.9.3, Emacs 25.1.3, gnu/linux`

**Comment by tarsius** [comment]
Yes, it's a limitation of how this is implemented. While theoretically possible, I don't think it would be worth the effort to give the text in the margin the same appearance as the selected text.

**Comment by tarsius** [comment]
The background color does change. That's good enough for me.

**Comment by fice-t** [comment]
That's fine for me as well, but how is it that the background colour is not restricted in this case but the foreground is?
