### ISSUE TITLE
gpg signing fails only when using instant fixup

### ISSUE THREAD

**Issue by paulyoung** [magit/magit#2799]
I recently started using gpg signing and it all works as expected except when trying to do an instant fixup:

```
128 git … commit --no-edit --fixup=1a9746d --gpg-sign=<redacted>
gpg: cannot open tty `/dev/tty': Device not configured
error: gpg failed to sign the data
fatal: failed to write commit object

  0 git … rebase -i --autosquash --autostash 1a9746d^
```

To reiterate, gpg signing in magit works for all of my other workflows

### Behavior expected
The changes were committed.

### behavior observed
The commit failed.

### how to reproduce
Attempt to do an instant fixup.

### Output of M-x `magit-version RET`
Magit 20160830.731, Git 2.9.0, Emacs 24.5.1, darwin

**Comment by tarsius** [comment]
Am I correct in assuming that you enter the passphrase every time you create a commit?

**Comment by paulyoung** [comment]
> Am I correct in assuming that you enter the passphrase every time you create a commit? And that everything works as expected when doing a non-instant fixup?

@tarsius you are correct on both of those

**Comment by tarsius** [comment]
And my commit fixed the issue, right?

**Comment by paulyoung** [comment]
Appears to have! Thank you!

(as an aside – it would be great if when using features like instant fixup and interactive rebase, commits didn't "lose" their signature)

**Comment by aaronjensen** [comment]
@tarsius this is still actually an issue for people that `commit.gpgsign true` in their `.gitconfig`. 

In my case, OSX enters my password for me, so I don't know why magit is failing to sign.

**Comment by npostavs** [comment]
> In my case, OSX enters my password for me, so I don't know why magit is failing to sign.

Missing environment variables?
https://magit.vc/manual/magit/I-am-using-OS-X-and-SOMETHING-works-in-shell-but-not-in-Magit.html

**Comment by aaronjensen** [comment]
@npostavs For whatever reason, gpg signing works normally in magit already even w/o that. I added that and it still does not work in instant fixup.

```
  0 git … add -u -- styleguide.config.js
128 git … commit --no-edit --fixup=660a5ab --
error: gpg failed to sign the data
fatal: failed to write commit object

  0 git … rebase -i --autosquash --autostash 660a5ab^
```

**Comment by tarsius** [comment]
Have you set `commit.gpgSign`?

We should probably should not just drop `--gpg-sign` but additionally add `--no-gpg-sign` to deal with such configurations.

**Comment by aaronjensen** [comment]
Yes, that's mentioned in my op. Why doesn't it work in this case?

**Comment by tarsius** [comment]
> Yes, that's mentioned in my op.

I overlooked that sorry.

> Why doesn't it work in this case?

Not sure what you mean - setting `commit.gpgSign` to a true value causes all commits to be signed unless that setting is overridden by something that takes precedence, i.e. by adding `--no-gpg-sign` as I have done now.

**Comment by aaronjensen** [comment]
I mean, why does it fail in magit during quick fix, but works fine for normal commits in magit?

**Comment by tarsius** [comment]
Ah, in this case `git commit` is run synchronously (so that we don't start rebasing before we are done committing), which prevents us from seeing git's passphrase prompt and then forwarding it to the user. Somehow git recognizes that (maybe a timeout?) and errors out.

**Comment by aaronjensen** [comment]
I see. I'm guessing that because the rebase is still signed this will still maintain signatures at the end, which is great.

Either way, it looks like fe5817262570e88bd1b1f2349dcf67bc79e88b5c should fix what I was experiencing, so thank you!
