### ISSUE TITLE
Cannot discard changes for some files even after removing it on a filesystem.

### ISSUE THREAD

**Issue by saqw3r** [magit/magit#2800]
Github Desktop does not allow properly discard the changes for some files in my repository. It says: "Could not discard all changes.". If I try to discard each one of the group of files, which "left in the GitHub", then I see "Could not discard changes to the file: '{filepath}'. This file may be in use by another application.". But it is not! (I can easy delete or rename them or put some data and reboot did not help as well). When I deleted them from filesystem I see the message "This file is empty" instead of content, but still cannot remove any from this group of files.

**Comment by tarsius** [comment]
This is the issue tracker of Magit not that of Github Desktop.
