### ISSUE TITLE
Can't stash untracked files

### ISSUE THREAD

**Issue by MatthewRock** [magit/magit#2802]
**Expected behaviour:**

The files have been stashed.

**Observed behaviour:**

"Can't save the current index state" error.

**Steps to reproduce:**

1. Go to the repository with no local changes and few untracked files and folders.
2. `C-g x` to open the magit buffer, `z` to open stash menu,  `-u` to add untracked, `z` to save.
3. The error occurs.

Additional info:
Running "git stash -u" (or `!` `!` `stash -u` in magit) stashes files properly.

`M-x magit-version`:
Magit 20160924.1314 Git 1.9.1, Emacs 24.4.1, gnu/linux

**Comment by tarsius** [comment]
I cannot reproduce this error following these steps.

> Git 1.9.1

Aha! You need at least `v1.9.4`, see https://magit.vc/manual/magit/I-am-using-a-Git-release-older-than-v194.html.
