### ISSUE TITLE
Rething magit-convert-git-filename

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2807]
Without doing so `magit-clone` and possibly other commands are broken over Tramp. Re #2806.

**Comment by tarsius** [comment]
A first, completely untested, draft:

```lisp
(defun magit-convert-filename-for-git (filename)
  "Convert FILENAME so that it can be passed to git.
1. Possibly remove the remote part of a Tramp filename.
2. Expand \"~/\", git isn't a shell and does not understand it.
3. Deal with an Cygwin Emacs vs. `windows-nt' Git incompatibility."
  (if (file-name-absolute-p filename)
      (-if-let ((cyg . win)
                (cl-rassoc filename magit-cygwin-mount-points
                           :test (lambda (f win) (string-prefix-p win f))))
          ;; FIXME can tramp be involved if we get here?
          (concat cyg (substring filename (length win)))
        (or (file-remote-p filename 'localname) filename))
    filename))
```

**Comment by npostavs** [comment]
> ```3. Deal with an Cygwin Emacs vs. `windows-nt' Git incompatibility.```

It's the other way around: ``` `windows-nt' Emacs vs. Cygwin Git incompatibility.``` I don't recall that we ever got a report from someone using Cygwin Emacs with Windows Git; I'm not sure if it works or not.

> ```;; FIXME can tramp be involved if we get here?```

I think not: if we are TRAMPing to a remote machine, the interface used to access the remote (ssh or whatever) should hide file-name incompatibilities of Windows vs Cygwin. And a remote name should never match any Cygwin mount points. I don't recall any reports of someone using NTEmacs+CygwinGit *and* accessing a remote repo with TRAMP, so I'm not sure what actually ends up happening in this case.

**Comment by tarsius** [comment]
I've fixed the doc-string, tested, and pushed.

**Comment by npostavs** [comment]
> 2. Expand \"~/\", git isn't a shell and does not understand it.

So today I noticed that this function doesn't actually expand `~`. Not sure if we should fix the docstring or the function.

**Comment by tarsius** [comment]
I have changed the doc-string a while ago.
