### ISSUE TITLE
Same git command (magit-git-executable) is used for local and remote (accessed through TRAMP) repositories

### ISSUE THREAD

**Issue by Kurvivor19** [magit/magit#2810]
Current magit behaviour when running magit commands (starting with magit-status) over remote buffer (accessed wtih TRAMP) result in trying to invoke command stored in magit-git-executable.

This results in failure to work when remote host does not have git executable accessible in the same way as local one.

A simple example would be running Emacs on Windows host where git.exe is located somewhere in Program Files and magit-git-executable is set accordingly, then trying to access remote git repository over tramp.

Example tramp output:

> tramp-send-command (6) # ( \cd /home/tc/development/aerostat/; c\:/Program\ Files\ \(x86\)/Git/bin/git.exe --no-pager --literal-pathspecs -c core.preloadindex\=true rev-parse --show-toplevel </dev/null 2>/dev/null; echo tramp_exit_status $? )

Such kind of assumptions with regard to remote environment should not be made. There must be a possibility of configuring magit for remote environment, on per-session, probably with ability to save those settings between sessions.

**Comment by tarsius** [comment]
Only on Windows does `magit-git-executable` not default to just "git", because if we don't do that here, then an expensive wrapper script is used in place of the actual executable. Try setting the variable to "git" and see if it affects performance in your case.

**Comment by tarsius** [comment]
Or in other words I sympathies with the sentiment ("Such kind of assumptions [...] should not be made."). But this is a performance hack specific for Windows. To not make those assumptions would require to check whether we are in a remote location,  which is an expensive operation and that would defeat the intention for the original change (using an absolute path on Windows). But worse it would affect users of all OSs.

So I will leave it as is. Windows users who do not tramp get a performance boost, and those that do tramp have to customize `magit-git-executable` to what is the default on other OSs.

**Comment by Kurvivor19** [comment]
So noted.
