### ISSUE TITLE
e6d86ae: Visiting diff from magit-status opens read-only buffer with parent revision

### ISSUE THREAD

**Issue by bastianbeischer** [magit/magit#2816]
The commit e6d86ae introduces the following behavior:

In magit-status, when a file is modified with a removed line, putting the cursor on that line and pressing RET opens the parent commit of the HEAD in a read-only buffer.

This behaviour is inconvenient because from magit-status I always want to go to the worktree version of the file, with point at the location where I pressed RET in the diff hunk. This makes continuing to work on the file easy and convenient.

**Comment by bastianbeischer** [comment]
P.S.: I also had problems when trying to visit a hunk for a merge conflict, I got some error message, by I can't remember the exact message and I can't reproduce it at the moment.

**Comment by tarsius** [comment]
> In magit-status, when a file is modified with a removed line, putting the cursor on that line and pressing RET opens the parent commit of the HEAD in a read-only buffer.

If by "that line" you mean "the removed line", then this is an intended change in behavior. One could even argue that it is a bugfix - if you request to be taken to a change which no longer exists in the working tree, then you should be taken to it in a place where it still exits, i.e. the commit before it was removed.

You can still jump to the buffer visiting the file, but you have to place point on an added line or a context line.

> P.S.: I also had problems when trying to visit a hunk for a merge conflict, I got some error message, by I can't remember the exact message and I can't reproduce it at the moment.

I'll look into that.

**Comment by tarsius** [comment]
On the hunk header it does go to the previous commit too. That's obviously wrong. Will fix.

**Comment by bastianbeischer** [comment]
Thanks a lot for looking into fixing the problems so that behavious is as intended.

Now, about whether the new behavior is good or bad: I can see how the change makes sense when looking at some commit in the log view of a branch, where pressing RET on a diff would always take you a file which can't be edited, be it the new or the old verssion. However in magit-status, when looking at a diff, my opinion is that one should always be taken to the file in the working tree, regardless of the exact position of the cursor in the hunk because most often the intention of the user (at least for me) is to continue working on this hunk. I think it's an inconvenience that users will have to worry about the _exact_ position of the cursor in the hunk in order to continue working. But maybe that's just me.

**Comment by tarsius** [comment]
Fixes all the unintended changes I think.

This change was in response to #2805 where @kvaneesh said:

> I have done a similar request as part of issue #1777 . We are now able to follow the lines added. But i want to recursive blame from where the line got removed. For that It would nice to have something like ALT-RET that shows the file/buffer content before that commit. Right now i use magit log file got to the revision before and blame it. But if magit-diff-visit-file can take an option to show the version before it would make it all easy ?

But I had been planing to do this even before that. He suggested using `M-Ret`, but I think it is better to just make `RET` automatically detect the special case. For the reasons given by @kvaneesh I think this is a useful feature. And I wouldn't want to use a separate key binding.

> I think it's an inconvenience that users will have to worry about the exact position of the cursor in the hunk in order to continue working.

I think that in practice most users who want to go to the "current version" would press `RET` either while point is on the hunk header or after navigate to the precise location they want to jump to, which would be a context or added line (because going to something that isn't there, isn't very precise).

But lets see how others respond to this change.

**Comment by tarsius** [comment]
I have temporarily reverted this change but only for the status buffer, but only because that code path had a bug, not because I changed my mind about this.

**Comment by alexander-yakushev** [comment]
Chiming in on this issue, I don't mind if Magit jumps to the previous revision if I hover over the deleted line, but what's slightly annoying is that it will do so if I hover over the whole file (collapsed or expanded, it doesn't matter).

**Comment by tarsius** [comment]
I don't think that ever was the case (but didn't check, maybe I am wrong) and if it was, then it no longer is. Did you update Magit today?

Also I just pushed a feature branch, #2828, that improves upon these somewhat rushed changes and should be merged soon.

**Comment by alexander-yakushev** [comment]
With today's version, everything is back to normal (i.e. how it used to be), but if I understood you correctly this is a temporary; so I wanted to let you know about this case.

**Comment by tarsius** [comment]
I have decided to extend the "temporarily" to "for the foreseeable future". Also the thing that I reverted temporarily is the ability to jump to the previous revision for staged and unstaged changes - not the bugs ;-)

Compared to how things were a week ago these will be the changes:
* When point is on a removed line of a diff for a *committed* change, then jump to the last commit which still had that line.
* There will be an option to revert that change of behavior.
* Point will be on the correct line in more cases.

**Comment by alexander-yakushev** [comment]
> There will be an option to revert that change of behavior.

I wonder how scalable is that. There could be just so many "revert to my previous workflow" levers until the code becomes a mess. Besides, people are grumpy about the changes only for a while, and you, as the author and maintainer, have ultimately a better judgment.

From the top of my head, what if it was possible to jump from the read-only revision buffer to the worktree file by pressing RET again? This could be a middleground until people get used to the new RET behavior in the status window (like, if you pressed RET and ended up in the revision, just press RET again). There could be a hint in the minibuffer.
