### ISSUE TITLE
Wrong type argument: stringp, nil when trying to visit unmerged change in status buffer

### ISSUE THREAD

**Issue by greenrd** [magit/magit#2817]
Magit 20161010.229, Git 2.7.4, Emacs 25.1.1, gnu/linux

I go to an unstaged changed in a magit status buffer, after a git merge on the command line failed with conflicts, and press Enter. Previously, this used to visit the file mentioned at point. Now, I get the error message "Wrong type argument: stringp, nil"

**Comment by kvaneesh** [comment]
I am also facing this. I am going to test with the  https://github.com/magit/magit/commit/716db032d1e7239b8e8f715aca0c56c896029583

**Comment by tarsius** [comment]
See #2816.
