### ISSUE TITLE
Push only part of the local history

### ISSUE THREAD

**Issue by gergelypolonkai** [magit/magit#2820]
Original question is at [emacs.SE](http://emacs.stackexchange.com/q/27724/507)

Actually, it can be done by <kbd>P</kbd> <kbd>x</kbd> (Push explicit refspecs), but specifying a remote and the exact refspec (e.g. `affec75:my-cool-feature` or `HEAD^:my-other-very-cool-feature`) is a bit tedious. It would be awesome if I could somehow specify the ref I want to push.

I could think of moving point to the local commit I want to push, and then in the Push dialog I could choose if I want to push the whole local `my-cool-feature` branch, or just up to the commit I have “selected”.

**Comment by tarsius** [comment]
Okay, the sequence now is:

1. Move to the commit.
2. <kbd>P o</kbd> to push other branch (actually commit in this case).
3. <kbd>RET</kbd> confirm the default, which should be the abbreviated commit hash. If a branch points at the commit, then the commit is the second choice.
4. <kbd>RET</kbd> confirm the default, which should be the current branch. (But only if the commit is reachable from `HEAD`.
