### ISSUE TITLE
More flexibility for magit-branch-prefer-remote-upstream

### ISSUE THREAD

**Issue by aspiers** [magit/magit#2823]
I've just discovered `magit-branch-prefer-remote-upstream`, and while it's an awesome step in the right direction towards what I need, it's not quite the full solution.  Specifically:

- I work on a bunch of repositories all related to the same project, and they all have the same branch naming scheme, i.e. `master`, plus one branch per release, e.g. `stable/3.0`, `stable/2.0` etc.
- I work on countless other repositories with many other branch naming schemes.

So ideally this option would be more flexible in at least two respects:

1. It could match branches via regexps
2. It could be configurable per repository

## Proposal 1

Both of these requirements (and an infinite number of other arbitrarily sophisticated approaches) could be accommodated very easily simply by allowing the option to specify an elisp function to call which could return `t` if the new branch being spun off should have its upstream set to the remote branch, or `nil` otherwise.

## Proposal 2

In fact it could be made even more flexible if the function instead returned the upstream branch for the newly spun off branch.  This way it could even pick upstream branches with names which didn't match the base branch.  I'm not 100% sure, but I'm guessing this might come in handy in more complicated git development workflows.  Or maybe it's overkill compared to proposal 1.

**Comment by tarsius** [comment]
I'll look into making this more flexible, but it will probably be a while until I get to it.

> It could be configurable per repository

That's already possible [using directory-local variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html).

**Comment by tarsius** [comment]
> It could match branches via regexps

That I'll probably do soon.

**Comment by aspiers** [comment]
Yes, exactly. Thanks so much for the quick response and also the hint about directory-local variables which is a nice trick! :-)

**Comment by tarsius** [comment]
Members of `magit-branch-prefer-remote-upstream` can now be regexps. But not all characters that you might expect to do so actually trigger interpretation as a regexp. See the doc-string for more information.

I haven't implemented support for members that are functions, I would first want to see a use-case. Redefining or advising `magit-get-indirect-upstream-branch` would also work. And I don't intend to implement any per-repository support, since directory-local fulfill that role well enough. So we are done here, right?

**Comment by aspiers** [comment]
Sounds great, thanks a lot!  Yes, I think this is probably good enough - I will try it out and if there are other unsatisfied use-cases then I'll report back!
