### ISSUE TITLE
require: Symbol’s value as variable is void: with-editor-file-name-history-exclude with Emacs git 26.0.50.1

### ISSUE THREAD

**Issue by jfkw** [magit/magit#2824]
Using GNU Emacs 26.0.50.1 (x86_64-pc-linux-gnu, X toolkit, cairo version 1.14.6) of 2016-10-11 upstream git 8b4aebf, calling Magit functions including magit-status raises error:

```
require: Symbol’s value as variable is void: with-editor-file-name-history-exclude
```

M-x magit-version Output doesn't work with above bug, but git rev is 8331e3e96.

make emacs-Q output:
```
Debugger entered--Lisp error: (void-variable with-editor-file-name-history-exclude)

  (member git-commit-filename-regexp with-editor-file-name-history-exclude)

  (if (member git-commit-filename-regexp with-editor-file-name-history-exclude) with-editor-file-name-history-exclude (setq with-editor-file-name-history-exclude (cons git-commit-filename-regexp with-editor-file-name-history-exclude)))

  eval-buffer(#<buffer  *load*-586132> nil "/home/jtk/.emacs.d/el-get/magit/lisp/git-commit.el" nil t)  ; Reading at buffer position 13823

  load-with-code-conversion("/home/jtk/.emacs.d/el-get/magit/lisp/git-commit.el" "/home/jtk/.emacs.d/el-get/magit/lisp/git-commit.el" nil t)

  require(git-commit)

  eval-buffer(#<buffer  *load*> nil "/home/jtk/.emacs.d/el-get/magit/lisp/magit.el" nil t)  ; Reading at buffer position 2233

  load-with-code-conversion("/home/jtk/.emacs.d/el-get/magit/lisp/magit.el" "/home/jtk/.emacs.d/el-get/magit/lisp/magit.el" nil t)

  require(magit)

  (progn (setq debug-on-error t) (require (quote magit)) (global-set-key "g" (quote magit-status)))

  eval((progn (setq debug-on-error t) (require (quote magit)) (global-set-key "g" (quote magit-status))))

  command-line-1(("-L" ".//lisp" "-L" "./../dash" "-L" "./../with-editor" "--eval" "(progn(setq debug-on-error t)(require 'magit)(global-set-key \"\\C-xg\" 'magit-status))"))

  command-line()

  normal-top-level()
```

**Comment by tarsius** [comment]
How did you install Magit? If you didn't use `package.el` (which would have taken care of that), did you install `with-editor`?

**Comment by tarsius** [comment]
Never mind, you probably have. But you have to *update* it.

**Comment by tarsius** [comment]
If just bumped the Melpa dependency.

**Comment by jfkw** [comment]
I install magit via el-get. As with melpa, a reinstall fixed the issue, thanks for the suggestion.

el-get magit recipe does have a proper dependency:

https://github.com/dimitri/el-get/blob/master/recipes/magit.rcp#L8

Date added was 2015-07-15:

https://github.com/dimitri/el-get/commits/master/recipes/magit.rcp

However I never had any issue with the missing dependency until yesterday when I moved from emacs git 25.x to 26.x. My usual magit update is:

```
(cd ~/.emacs.d/el-get/magit && git fetch && git pull && make clean && make) ;
```

Going forward I will do periodic M-x el-get-reinstall magit to ensure I pick up future packaging changes.

Thanks again for your help.

**Comment by npostavs** [comment]
> el-get magit recipe does have a proper dependency:

Not exactly, el-get doesn't support versioning in dependencies.
