### ISSUE TITLE
Revert the ability to navigate to files

### ISSUE THREAD

**Issue by chillum** [magit/magit#2826]
Hi,

I'm using magit for some years and recently I updated to 20161009.1658 from MELPA.

I'm normally using `magit-status` to navigate to edited files (I just select them and press return, but in new release return just displays their version from the current branch (which makes no sense for me, especially for files that are not commited yet). And I heavily depend on that this navigation returns the current working copy, not the last commited revision.

Can we please revert the old behaviour, at least with a user option?

I've read commit messages and release notes, but did not find when this was introduced.

**Comment by tarsius** [comment]
It's a recent change that hasn't quite gone as intended, though some issues have already been fixed (update Magit). Unless point is on a removed line, things should behave as before. I have a feature branch cooking with smarter behavior.

**Comment by chillum** [comment]
Thanks, the latest update worked for me.
