### ISSUE TITLE
Allow repos with a leading period to show up in magit-list-repositories

### ISSUE THREAD

**Issue by fice-t** [magit/magit#2830]
In `magit-list-repos-1` ([here](https://github.com/magit/magit/blob/122c4137341b4d9838004db96f0cdc564f683978/lisp/magit.el#L3079)) directories starting with dot are filtered out. I would expect that such git repos are shown in `magit-list-repositories`, at least optionally.

**Comment by tarsius** [comment]
`directory-files` unfortunately always includes "." and "..", the regexp was supposed to filter that out. But because the regex is a whitelist not a blacklist, it is impossible to just filter out those two files, so it has to be done in the map.

**Comment by fice-t** [comment]
@tarsius Thanks. Though I just found out from [here](https://stackoverflow.com/questions/17164767/emacs-lisp-directory-files) that one could use `directory-files-no-dot-files-regexp` as well.

I don't know which is preferable, though.

**Comment by tarsius** [comment]
Ah, nice. Thanks for pointing me to that.
