### ISSUE TITLE
Magit commit error. (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by Nigiss** [magit/magit#2831]
When I commit staged changes, I got this error:
**(wrong-type-argument stringp nil)**
propertize(nil face magit-hash)
(insert (propertize hash (quote face) (quote magit-hash)) 32)
...
magit-log-wash-rev(log 7)
...
Then I trace the error into **magit-log-wash-rev**, the problem is that value of **hash** is NIL.
But why? It seems that it's value is set auto.
I couldn't solve this problem, who can help me?
My eamcs version is 25.1.1, OS is OS X EL Capitan 10.11.5.

**Comment by tarsius** [comment]
Can you reproduce this with `emacs -Q`?

**Comment by Nigiss** [comment]
Emacs hasn't magit package with -Q, what should I do then?

**Comment by kyleam** [comment]
On top of using `emacs -Q`, you need to put Magit and its requirements
(`dash` and `with-editor`) in your load path.  In the Magit source
directory, running `make emacs-Q` after tweaking the variables defined
in default.mk is one way to do this.

**Comment by Nigiss** [comment]
I still have this problem while I loaded only magit and it's deps.

**Comment by kyleam** [comment]
Do you see this for every repo you try to commit in?  Also, what's
your Magit version?

**Comment by Nigiss** [comment]
All commits in all my repos would cause this problem.
magit-version: Magit 20161019.2021, Git 2.10.1, Emacs 25.1.1, darwin

**Comment by Nigiss** [comment]
In Ubuntu VM with emacs 24.5, I haven't meet this problem. 
Is it caused by latest eamcs?

**Comment by kyleam** [comment]
I haven't seen any issues with Emacs 25.1.1 on GNU/Linux.

**Comment by Nigiss** [comment]
Or OSX? I have no idea, cause all my configs is same, but magit behaved different in two envs.

**Comment by Nigiss** [comment]
I reinstall emacs 24.5, but this problem still exists. I guess it's caused by OSX.

**Comment by tarsius** [comment]
I don't really have any ideas as to what you could try.

> cause all my configs is same, but magit behaved different in two envs.

Or maybe that's not really the case? I suppose that either the two Emacsen are "different" or the two configurations are different. The latter seems somewhat more likely.

**Comment by Nigiss** [comment]
I solved this problem by removed Chinese character of user name in .gitconfig.
And I found when user name of commits contain Chinese character, magit diff was empty.
Is it a bug?
