### ISSUE TITLE
Emacs occasionally freezes after exiting from ediff mode...

### ISSUE THREAD

**Issue by smandy** [magit/magit#2837]
Occasionally after using 'e' to enter ediff in magit status window, when ediff has been exited the point ends up 'stuck' in the magit window and emacs becomes unresponsive. Occasionally for me means around 20-40% of the time I enter ediff I'll end up 'stuck after I exit.

Can move to other windows using the mouse, but other movement commands 'C-o' et al have no effect. Normal magit commands in the magit window have no effect either. i.e. the only action I can do in emacs at all is to move the cursor using the mouse. Only remedy is to restart emacs.

I've had this for a while but have just updated to ensure it's not a fixed bug, but can reproduce this with magit-20161022.1845 from melpa (i.e. most recent in melpa as of writing).

**Comment by tarsius** [comment]
Well in this case it would also be nice to know the Emacs version (I suspect this is an issue in Emacs and/or your configuration, not Magit).

**Comment by smandy** [comment]
Okay so I've just tried stripping down my emacs config to a bare minimum and looks like it's still there..

Emacs version..... (running ubuntu 15.0.4)

```
andy@raffles:/mnt/hdd/andy/repos/gem/python$ emacs -version
GNU Emacs 24.4.1
Copyright (C) 2014 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

I've moved my ~/.emacs.d off to the side to get a fresh config. New `init.el` contains..

```elisp
(require 'package)

(add-to-list 'package-archives '("melpa"     . "http://melpa.org/packages/"))
```

I still manage to get this 'freezing' problem after ~3/4 iterations of calling ediff on a modified file and quitting out.

Anything else to try?

Cheers,

A.

**Comment by npostavs** [comment]
Can you get a backtrace if you send SIGUSR2 to emacs?

**Comment by smandy** [comment]
Ooh didn't know you could do that... okay I sent it SIGUSR2 in a hung state. A window popped up with the following ...

```
Debugger entered--entering a function
* magit-pre-command-hook()

```

Sent signal a few more times. Copy/Paste not working from emacs so here's screenshot...

![image](https://cloud.githubusercontent.com/assets/342785/19671828/7eb27284-9a69-11e6-80bd-27b5e71b0694.png)

Cheers,

A.

**Comment by smandy** [comment]
Hi There,

I'm on  24.4.1 ( i.e. the stock emacs from ubuntu 15.04).

I'll try stripping my .emacs to contain nothing but melpa. Install magit
then try again...

Cheers,

A.

**Comment by npostavs** [comment]
> Ooh didn't know you could do that... okay I sent it SIGUSR2 in a hung state. A window popped up with the following ...
> ```
> Debugger entered--entering a function
> * magit-pre-command-hook()
> ```

Hmm, well that doesn't seem possible. Seems to be a problem in Emacs then. I'm not able to reproduce it here.

You might try running under gdb. And maybe check if it still occurs in Emacs 25.1.

[emacs-Q]: http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html

**Comment by smandy** [comment]
Okay so I had some time today - I built emacs25 from source and so far haven't been able to reproduce. ( Did around 20 ediff->move->quit cycles with 25 and unable to reproduce the locking). Went back to 24 doing ediffs on same file in same repository managed to get it to freeze approx 4-5 cycles.

Thanks for time responding - I guess if it recurs for anyone else we now know the fix. I'll consider this closed.

**Comment by smandy** [comment]
Reopening.... it's an intermittent problem but I've just had the same locking problem with emacs 25.1.1

Might still be an emacs problem but has an adverse affect on magit :-(

**Comment by tarsius** [comment]
Does this happen with all "Ediff variants" (instead of `e` (which picks the appropriate one), press `E` to see the available variants).

> ```
> Debugger entered--entering a function
> * magit-pre-command-hook()
> ```

That's a rather harmless function:

```lisp
(defun magit-pre-command-hook ()
  (setq disable-magit-save-buffers nil))
```

**Comment by Hylen** [comment]
I believe this has nothing to do with Magit. I've experienced exactly this myself and found https://lists.gnu.org/archive/html/bug-gnu-emacs/2015-03/msg00902.html.

I get this on an Ubuntu machine even when exiting ediff not started from Magit. I found a workaround though, configuring `ediff-window-setup-function` to be `ediff-setup-windows-plain`.
This will skip opening the separate frame and instead use a third window, which I prefer anyway.

**Comment by tarsius** [comment]
I wasn't able to reproduce this with 25.1, so the solution seems to be to update Emacs. Or if that is not an option do what you suggested:

> I found a workaround though, configuring `ediff-window-setup-function` to be `ediff-setup-windows-plain`.

> which I prefer anyway.

Ditto.

**Comment by npostavs** [comment]
> I wasn't able to reproduce this with 25.1, so the solution seems to be to update Emacs.

https://github.com/magit/magit/issues/2837#issuecomment-258220499 suggests it still occurs in Emacs 25. It could depend on the window manager too? Anyway, followups should probably go to [the Emacs bug](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=20175) rather than here.

**Comment by Quiigi** [comment]
This is still broken in Gnu Emacs 26.3, which comes with Ubuntu 18.04.4 LTS.
I believe it has nothing to do with magit, because I never used magit.
