### ISSUE TITLE
Consider using asterisks at both ends of magit buffer names

### ISSUE THREAD

**Issue by Wilfred** [magit/magit#2841]
I'd like to propose that magit names its buffers `*magit: foo*` instead of `*magit: foo`. This is more in line with Emacs convention: for example, `*Help*` or `*Customize: foo*`.

This should be a matter of changing the default value of `magit-buffer-name-format` to `"*%M%v: %t*"`. The docstring warns that it should end with `%t` if `magit-uniquify-buffer-names`, but `%t*` does not break it when I tested.

**Comment by npostavs** [comment]
The uniquifying part of the name doesn't land inside the asterisks if you do this. Example: I have a magit repos under `~/src/magit` and also `~/.emacs.d/el-get/magit/`, opening both gives `*magit: magit*<el-get>` and `*magit: magit*<src>`. I seem to recall this could confuse magit such that it might fail to find some buffers, although I'm not able to reproduce a failure right now.

**Comment by kyleam** [comment]
This was also discussed in #2334.

**Comment by tarsius** [comment]
An asterisk is now appended when the buffer names are not being uniquified. Otherwise (the default) this still does not happen. If someone really cares about that little `*`, then s/he will have to teach `uniquify` about that her-/himself.
