### ISSUE TITLE
magit-save-repository-buffers set to Ask but magit neither asks nor saves

### ISSUE THREAD

**Issue by dabrahams** [magit/magit#2843]
This happens when the repository is accessed via a symlink.  For example, 

```
/tmp
   /tmp/a -> /tmp/b
   /tmp/b/
       /tmp/b/.git 
       X
```

If X is checked into the repo at b and I navigate to /tmp/a/X, modify it, and then `M-x magit-status', it is not saved nor am I prompted.

**Comment by kyleam** [comment]
Thanks.  Should be fixed with 1ff4225.
