### ISSUE TITLE
Implement magit-diff-buffer-with-file similar to diff-buffer-with-file

### ISSUE THREAD

**Issue by jtamagnan** [magit/magit#2844]
The magit diff interface is really great and it would be great if there was a way to compare the current buffer and the file which backs it. The use case is the same as diff-buffer-with-file, to view and interact with the unsaved changes.

**Comment by kyleam** [comment]
Is there specific functionality you have in mind that's not available
with `diff-buffer-with-file`?

**Comment by jtamagnan** [comment]
There are a few things that can't be done in `diff-buffer-with-file`. I don't think its possible to collapse hunks in the same way as with the magit interface. In general though the issue is that the workflow is much more limiting and it is nice to have a common interface for common tasks. For example reversing regions of a hunk require splitting the hunk and then reverting that section.

**Comment by kyleam** [comment]
You could get a Magit diff pretty easily by dumping the current buffer
to a temp file (as `diff-buffer-with-file` does) and using
`--no-index` (like in `magit-diff-paths`).  However, I think making
the buffer behave reasonably in terms of apply operations, including
deciding what those behaviors should be, would be fairly complicated.
Another consideration is that unless the user has set
`magit-save-repository-buffers` to nil, many Magit commands will be
saving or asking to save the buffer.  At the very least, it would have
to be overriden before generating the diff buffer.  I'm not sure it's
worth the effort, but perhaps it's simpler than I'm imaginging.

Out of curiousity, do you have a Git workflow that involves
selectively "applying" unsaved changes?

**Comment by tarsius** [comment]
Closing because we got no answer to

> Out of curiousity, do you have a Git workflow that involves selectively "applying" unsaved changes?

while I myself have a hard time imagining an often occurring use-case. And because I suspect this is true:

> I think making the buffer behave reasonably in terms of apply operations, including deciding what those behaviors should be, would be fairly complicated.
