### ISSUE TITLE
.dir-locals.el does not seem to be respected in COMMIT_EDITMSG buffers

### ISSUE THREAD

**Issue by rrthomas** [magit/magit#2848]
magit-version: 2.8.0

I am working on Emacs (i.e. the source code of Emacs), which has a top-level .dir-locals.el part of which goes:

    ((nil . ((tab-width . 8)
             (sentence-end-double-space . t)
             (fill-column . 70)))

These settings are intended to apply to commit messages, as well as source code.

When I do a commit (c c), the COMMIT_EDITMSG buffer does not have these settings. For example, sentence-end-double-space is nil (my global setting) and fill-column is 72 (is that a magit default? my global setting is 76).

As COMMIT_EDITMSG is a text-mode file under emacs/.git, it should respect emacs/.dir-locals.el, I think?

The settings from .dir-locals.el *are* correctly applied in the git-rebase-mode buffer I get when I do an interactive rebase.

I tried reproducing with emacs -Q using the following instructions:

  $ cd ~/.emacs.d/elpa/magit-N
  $ emacs -Q --debug-init --eval '(setq debug-on-error t)' -L ../dash-N -L ../git-commit-N -L ../magit-popup-N -L ../with-editor-N -L . -l magit

But I got an error:

    (file-error "Cannot open load file" "No such file or directory" "dash")
      require(dash)
      byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\210\300\306!\210\300\307!\210\300\310!\210\300\311!\210\300\312\313\314#\207" [require cl-lib dash with-editor git-commit magit-core magit-diff magit-apply magit-log format-spec package nil t] 4)
      load("magit" nil t)

**Comment by npostavs** [comment]
> I tried reproducing with emacs -Q using the following instructions:
> 
> $ cd ~/.emacs.d/elpa/magit-N
> $ emacs -Q --debug-init --eval '(setq debug-on-error t)' -L ../dash-N -L ../git-commit-N -L ../magit-popup-N -L ../with-editor-N -L . -l magit
> 
> But I got an error:

Did you use a literal `N` (or otherwise get the path to dash wrong)? It's supposed to represent the version number of each package.

**Comment by rrthomas** [comment]
Sorry, I cut and pasted the command verbatim. I will try again. Because of the other capital letters, it isn't very obvious that there is some form-filling to do!

**Comment by rrthomas** [comment]
Having filled in the Ns, I get, on start-up:

    Cannot determine Magit’s version (error "/home/rrt/.emacs.d/elpa/magit-2.8.0/magit.el" repo static elpa)

**Comment by rrthomas** [comment]
Assuming that the above error/warning is not a problem, I can confirm that I can reproduce the issue I describe in my initial report with `emacs -Q`.

**Comment by npostavs** [comment]
Hmm, works for me, after I added the missing paren to what you posted (I tested in a magit repo checkout). Are you using symlinks, and/or git worktrees?

**Comment by rrthomas** [comment]
I'm not using worktrees (which I hadn't heard of; thanks!) or symlinks. I'll attempt an MWE.

**Comment by rrthomas** [comment]
I can reproduce using the following steps:

1. Start Emacs-Q-with-magit as above.

2. Run the following shell commands:

```
mkdir foo
cd foo
git init
echo hello > bar
git add bar
git ci -m "initial checkin"
```
3. Create `foo/.dir-locals.el` with the following contents:

```
((nil . ((tab-width . 8)
     (sentence-end-double-space . t)
     (fill-column . 70))))
```

4. C-x C-f foo/bar RET
5. Add some text, C-x C-s
6. M-x magit-status
7. Stage bar, c c (commit)
8. M-x describe-variable fill-column RET

fill-column has the value 72, but in `.dir-locals.el` it is set to 70. The buffer we are currently editing is `~/foo/.git/COMMIT_EDITMSG`, so it should be respecting `.dir-locals.el`.

**Comment by npostavs** [comment]
Can you post Emacs and OS versions too please?

**Comment by npostavs** [comment]
Oh, sorry, I think I *was* seeing it before, but I was confused as to the default value of `fill-column`.

**Comment by npostavs** [comment]
So the problem is simply that `git-commit-turn-on-auto-fill` sets `fill-column` to `git-commit-fill-column` and `git-commit-fill-column` defaults to 72.

**Comment by npostavs** [comment]
Ah, but also `git-commit-setup` does

```elisp
  (when git-commit-major-mode
    (funcall git-commit-major-mode))
```
Which kills local variables, but doesn't call `hack-dir-local-variables` (this is usually done by `normal-mode`).

**Comment by rrthomas** [comment]
Thanks very much for looking into this. I'm not sure at this point whether you're saying there is actually a bug, or whether e.g. I need to call `hack-dir-local-variables` somewhere else?

**Comment by rrthomas** [comment]
Thanks very much for looking into this. I'm not sure at this point whether you're saying there is actually a bug, or whether e.g. I need to call `hack-dir-local-variables` somewhere else?

**Comment by rrthomas** [comment]
Thanks very much for looking into this. I'm not sure at this point whether you're saying there is actually a bug, or whether e.g. I need to call `hack-dir-local-variables` somewhere else?

**Comment by npostavs** [comment]
I think we should change `git-commit-setup` to call `hack-local-variables`, preferably by using `normal-mode` (let-bind the auto mode list around the call?)

**Comment by rrthomas** [comment]
(Just in case it's not obvious, I'm staying quiet here, I'm not familiar with magit internals!)

**Comment by npostavs** [comment]
#2852 should fix it for all variables except `fill-column`.

**Comment by rrthomas** [comment]
That's great, thanks! (Actually, the `fill-column` discrepancy was the one thing that the reviewer of my commit messages didn't pick up! But is it not possible to overcome by ensuring that the call of `hack-local-variables` occurs after `git-commit-turn-on-auto-fill`, thereby allowing local settings to override the global one?)

**Comment by npostavs** [comment]
Hmm, but then you can't override dir/file local settings from git-commit mode hooks. Perhaps it's better to fix in your configuration with
```elisp
(remove-hook 'git-commit-setup-hook #'git-commit-turn-on-auto-fill)
(add-hook 'git-commit-setup-hook #'turn-on-auto-fill)
```

**Comment by rrthomas** [comment]
I may be missing something, but isn't the point of `.dir-locals.el` to be more local than global settings, and in turn be overridden by per-file settings? `.dir-locals.el` can of course specify something to do in `git-commit-mode` if I want.

It is not obvious that I should have to do something to my configuration merely to make `.dir-locals.el` work with `git-commit-mode` the way it does with other modes. In particular, the `git-commit-turn-on-auto-fill` setting appears to be a default (I can't see anything in my customization or other init files that mentions it).

If I want to ignore certain settings in `.dir-locals.el` or per-file settings, there are already ways to do that: for example, I can declare them "insecure", and they will be ignored by Emacs.

**Comment by npostavs** [comment]
There is no distinction between the parts of  `git-commit-setup-hook` which are default and non-default. Generally, Emacs applies dir/file local variables before hooks, so hooks are able to override those settings.

Personally, I don't see the point of `git-commit-fill-column` (why not just let the user set `fill-column` directly?), so I would be in favour of removing it altogether. @tarsius, @kyleam thoughts?

**Comment by rrthomas** [comment]
That makes sense.

**Comment by kyleam** [comment]
> I don't see the point of git-commit-fill-column (why not just let
> the user set fill-column directly?), so I would be in favour of
> removing it altogether. @tarsius, @kyleam thoughts?

Yeah, I also don't understand why it exists.  When I saw your comment
yesterday, my first thought was that maybe it was left over from when
git-commit-mode was a major mode rather than a minor mode, but I don't
understand why it would have been needed in that case either.

**Comment by tarsius** [comment]
> Personally, I don't see the point of `git-commit-fill-column`

History, I suppose. I kept the option but restricted its effect in 2087cce6c021c3f985e5c53caa74bf56ebdd30fe.

One problem with setting `fill-column` in `.dir-locals.el` is that it might not have an effect regardless of whether `git-commit` messes with `fill-column` at all. If the actual Git directory is not located inside the repository, as is the case when using submodules or separate working trees (in which case `.git` is a regular file), then `.dir-locals.el` doesn't kick in. (Which might be worth fixing in Emacs.)

But that doesn't really justify the existence of `git-commit-fill-column` either.

**Comment by rrthomas** [comment]
Thanks! I agree that if the file isn't actually under the directory, that's a different problem.

**Comment by npostavs** [comment]
> I kept the option but restricted its effect in 2087cce.

I was thinking to propose something like that, but additionally mark `git-commit-fill-column` obsolete. It seems its only benefit is saving a call to `add-hook` in the user's config.

**Comment by tarsius** [comment]
I have no objections to that.
