### ISSUE TITLE
Support all git porcelain commands

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2849]
#### Legend
- subcommand (comment)
- done
- [x] done-recently
- [ ] todo
- ~~wont-add~~

#### Main porcelain commands
- add
- am
- ~~archive~~
- bisect
- branch
- [ ] bundle
- checkout
- cherry-pick
- [ ] citool
- clean
- clone
- commit
- describe
- diff
- fetch
- format-patch
- gc
- [ ] grep
- gui
- init
- log
- merge
- mv
- notes
- pull
- push
- rebase
- reset
- revert
- rm
- [ ] shortlog
- show
- stash
- status
- submodule
- tag
- worktree
- gitk

##### Manipulators
- config
- ~~fast-export~~
- ~~fast-import~~
- [ ] filter-branch
- [ ] mergetool (maybe)
- [ ] pack-refs (maybe)
- [ ] prune (maybe)
- reflog
- remote
- [ ] repack (maybe)
- [ ] replace

##### Interrogators
- ~~annotate~~ (use blame instead)
- blame
- cherry
- ~~count-objects~~
- [ ] difftool (maybe)
- ~~fsck~~
- ~~get-tar-commit-id~~
- ~~help~~ (but we do provide access to git documentation)
- ~~instaweb~~
- merge-tree
- [ ] rerere
- rev-parse
- [ ] show-branch
- [ ] verify-commit (but I think we do something equivalent)
- verify-tag
- ~~whatchanged~~ (deprecated)
- ~~gitweb~~

##### Interacting with Others
- ~~archimport~~
- ~~cvsexportcommit~~
- ~~cvsimport~~
- ~~cvsserver~~
- imap-send
- ~~p4~~
- ~~quiltimport~~
- request-pull
- send-email
- svn (via `magit-svn` package)

**Comment by kyleam** [comment]
> This is of the top of my head, there might be more

Based on the list in git(1), there are some others, but I think your
list has best candidates for adding.  (`git-show-branch` is the one
that I often drop into a shell for.)  A lot of the remaining ones seem
pretty obscure (e.g., commands for importing from other SCM systems,
`git-relink`), and I think leaving them to `magit-git-command` or the
terminal makes sense.

Of the remaining ones, maybe `git-bundle` and `git-archive` are also
worth considering.

**Comment by mgeisler** [comment]
The only command that I still run from a shell is `git mergetool` to start KDiff3.

**Comment by tarsius** [comment]
> A lot of the remaining ones seem pretty obscure

I agree that we don't need to / should not wrap those.

**Comment by jacobilsoe** [comment]
Is git-difftool supported by Magit?

**Comment by kyleam** [comment]
> Is git-difftool supported by Magit?

No, it's not.

I imagine that for Magit users that frequently call git-difftool (I
wonder what proportion of users this is), it'd be convient to be able
to specify ranges and files from Magit, as they would for either
magit-diff or magit-ediff commands.

Anyway, I've added it to the list above for consideration.

**Comment by hexmode** [comment]
git-archive ++

**Comment by tarsius** [comment]
Yeah... I don't think this is going to happen.

I never really thought this is necessary but that it would be nice to say "Magit supports **every** Git command".

Still plan to support some of these, but I am not in a hurry at all and there are much more important things to do first.
