### ISSUE TITLE
magit-log does not distinguish notes from the commit message

### ISSUE THREAD

**Issue by LemmingAvalanche** [magit/magit#2855]
When viewing the commit message of a commit which has some note
associated with it which is also shown, there is no visual indication or
hint that the note is not part of the commit message. Instead, the note
is just appended to the commit message with a newline in between, and 
with no difference in font etc. (to my eyes), thus:

``` example
Initial commit

Test note.
```

Where the first line is the commit message, and the last is the note.

I have tested this with my usual setup and with a “barebones” setup, as
per the instructions you get from the template you are presented with
when you try to open an issue here. Namely:

``` shell
emacs -Q --debug-init --eval '(setq debug-on-error t)' \
    -L ../dash-20161106.410/  -L ../git-commit-20161011.1738/ \
    -L ../git-commit-20161011.1738/  -L ../with-editor-20161009.917/ \
    -L . -L ../magit-popup-20161009.1506/ -l magit
```

The following is how it looks in my setup (Spacemacs) and the barebones
setup, respectively.

![notes-not-distinguished-spacemacs](https://cloud.githubusercontent.com/assets/2229597/20153190/de054b30-a6c1-11e6-83ff-c6add88beaf4.png)

![notes-not-distinguished-plain-emacs](https://cloud.githubusercontent.com/assets/2229597/20153197/e1f0550a-a6c1-11e6-9f70-b2f359bf738b.png)

Steps to reproduce
==================

Execute the following in a terminal:

``` shell
mkdir gnotes
cd gnotes
git init
echo "Hello!" > hello.txt
git add hello.txt
git commit -m "Initial commit"
git notes add -m "Test note."
```

Visit `gnotes/hello.txt` and `M-x magit-log RET @ RET`.

Version
=======

`Magit 20161105.1602, Git 2.10.2, Emacs 24.5.1, gnu/linux`

How `git log` does it
=====================

From `man git-log` (`git version 2.10.2`):

> Notes can be shown by git log along with the original commit message.
> To distinguish these notes from the message stored in the commit
> object, the notes are indented like the message, after an unindented
> line saying "Notes (&lt;refname&gt;):" (or "Notes:" for
> refs/notes/commits).

**Comment by tarsius** [comment]
The text in the body of the message as well as in the body of the note use the `default` face, while the summary of both the message and the note use dedicated faces, which by default are just bold. So if you see *two* bold lines "in the message", then the second bold line is actually the summary line of the note.

**Comment by LemmingAvalanche** [comment]
Thank you for the explanation.
