### ISSUE TITLE
Provide a function for launching “barebones Emacs” with Magit

### ISSUE THREAD

**Issue by LemmingAvalanche** [magit/magit#2856]
Right now, people who use Magit through Elpa is advised to test any
issues, bugs etc. by opening a “barebones” Emacs instance in order to
not let the specifics of ones setup interfere with reproduction of the
issue. These are the current instructions in `./ISSUES_TEMPLATE` on
this:

```
If you installed Magit from Melpa, then run commands similar to the ones below, but use tab completion to replace the various Ns with the correct versions:

  $ cd ~/.emacs.d/elpa/magit-N
  $ emacs -Q --debug-init --eval '(setq debug-on-error t)' -L ../dash-N -L ../git-commit-N -L ../magit-popup-N -L ../with-editor-N -L . -l magit
```

While this is already very helpful, it can be error-prone since you have
to replace all the `N`s with the specific suffix (version) that you
have in your own `.emacs.d`. While you’re in the middle of shuffling
strings around, trying to tab-complete on paths in the shell, etc. you
can forget to put some parts of it together. You might for example forget to
include one of the libraries.

What would be super-convenient would be if there was some Magit function
that searches all the relevant paths in your Elpa directory and tries to
complete these paths, and then launches the above command. In case that
is harder than I imagine that it is, or perhaps a bit ambigious (I don’t
know how Elpa works and if these paths can deviate from the general
pattern, if there can be several different versions, etc.), the function
can choose to be conservative and report that it wasn’t able to
automatically “deduce” the command in question, and that the programmer
should fill in the blank themselves. In either case, it seems that a
function like this would be super-helpful whenever Emacs/Magit is able
to deduce all the relevant Elpa paths (which I *imagine* is the common
case).

Alternatively, the function could just fill in the command and copy the
string to the kill ring, for the programmer to paste into their
terminal.

Context
=======

This came up on <https://gitter.im/magit/magit> today.

**Comment by tarsius** [comment]
Are you suggesting a command/function such as `magit-start-a-new-emacs-with-just-magit` or a script such as `./magit-Q.sh`?

**Comment by npostavs** [comment]
The command we suggest for users is much more difficult than what the developers use to test things (`make emacs-Q`). And @LemmingAvalanche is the 2nd person in the past week to have difficulty with it, so we really need something simpler.

Either a function or script would suffice, but I think writing a function will be easier to do portably than a script (in particular, starting Emacs on Windows from a script can be tricky, because there's no standard location to install it, and it's not necessarily on the `$PATH`). From within Emacs we have `invocation-directory`.

> Alternatively, the function could just fill in the command and copy the
> string to the kill ring, for the programmer to paste into their
> terminal.

This would be safer, since it avoids contamination of environment variables from the current Emacs.

**Comment by tarsius** [comment]
This might be a nice interface `emacs -Q --debug-magit -l /path/to/magit.el`.

(But I don't want to begin `magit.el` with that kludge... instead that should just load `magit-utils.el` first (and with an explicit path), and the rest should happen in that file.)

**Comment by npostavs** [comment]
But that still requires picking out `/path/to/`, which is annoying enough that we would want a function that should place the correct incantation into the clipboard. And if we have that, I don't see a particular need to make the interface nice (since the interface is essentially `<paste>`).

**Comment by LemmingAvalanche** [comment]
> Are you suggesting a command/function such as `magit-start-a-new-emacs-with-just-magit` or a script such as ./magit-Q.sh?

I think the first would be ideal, as a user. But you guys know best what would be most practical to implement.

**Comment by npostavs** [comment]
Something like this:
```elisp
(defun magit-emacs-Q-command ()
  (interactive)
  (let ((cmd (mapconcat
              #'shell-quote-argument
              `(,(concat invocation-directory invocation-name)
                "-Q" "--eval" "(setq debug-on-error t)"
                ,@(cl-mapcan
                   (lambda (dir) (list "-L" dir))
                   (delete-dups
                    (mapcar (lambda (lib)
                              (file-name-directory (locate-library lib)))
                            '("magit" "magit-popup" "with-editor"
                              "git-commit" "dash"))))
                "-l" "magit")
              " ")))
    (kill-new cmd)
    (message "Uncustomized magit command saved to kill-ring")))
```

**Comment by tarsius** [comment]
> I don't see a particular need to make the interface nice

It might be nice in cases where the installation is so messed up that the user can't even run the `magit-emacs-Q-command`. That being said, let's start with the command you have proposed.

> `(message "Uncustomized magit command saved to kill-ring")`

It might be better to show the actual command, possibly prefixed with instructions.
