### ISSUE TITLE
Error - gpg failed to sign the data

### ISSUE THREAD

**Issue by anildigital** [magit/magit#2859]
Getting following error

```
error: gpg failed to sign the data
fatal: failed to write commit object
```

I have following set
```
[user]
	signingkey = anildigital@gmail.com
[commit]
	gpgsign = true
```

What could be issue? Thanks.

**Comment by kyleam** [comment]
Please provide more information on your system (OS and versions for
magit, emacs, gpg, git).  Do you see this error when you try to commit
from the command line?

This could be related to #2776, but that should now be fixed.

**Comment by anildigital** [comment]
@kyleam I resolved using this https://gist.github.com/bmhatfield/cc21ec0a3a2df963bffa3c1f884b676b
