### ISSUE TITLE
Symbol’s value as variable is void when running "make"

### ISSUE THREAD

**Issue by YorkZ** [magit/magit#2862]
I got "Symbol’s value as variable is void: with-editor-file-name-history-exclude" error when running "make", and build stopped there.

I'm using git commit ca2b82b by the way.

**Comment by npostavs** [comment]
What version of `with-editor` are you using? I would guess it's too old.

`with-editor-file-name-history-exclude` was introducted in https://github.com/magit/with-editor/commit/ecff6bb717c7a775228c7171c2b2fe67868b849f

**Comment by YorkZ** [comment]
Thanks for reminding me of the `with-editor` package. Turns out that this is a problem of the Makefile. I've fixed it and have sent a pull request https://github.com/magit/magit/pull/2864, please review my changes and let me know whether it is acceptable.

Thanks,

York

**Comment by tarsius** [comment]
I've merge that, thanks.
