### ISSUE TITLE
Missing expand-file-name (or something)

### ISSUE THREAD

**Issue by dabrahams** [magit/magit#2866]
> Please explain
>   1. what behavior you expected

I expected a new worktree to be created at /Users/dave/src/disttest-swift

>  2. what behavior you observed

  A worktree was created under `$(pwd)`/~/src/disttest-swift`

>  3. and how we can reproduce the issue.

  in some magit buffer, do \`b W ~/src/disttest-swift'

> Also post the output of
>
>  M-x magit-version RET

  Magit 20160629.1156, Git 2.9.3 (Apple Git-75), Emacs 25.1.1, darwin

**Comment by kyleam** [comment]
Isn't this the same issue as the one you reported in #2796?  That
should be fixed by f1e65ba (magit-worktree-{checkout,branch}: expand
path, 2016-09-24).

**Comment by dabrahams** [comment]
@kyleam must be the same issue; I guess melpa hasn't got the fix yet.

**Comment by kyleam** [comment]
> I guess melpa hasn't got the fix yet.

Hmm, it should have it.  melpa's currently at 20161120.1223, but your
version output above indicates that you're at 20160629.1156.

**Comment by dabrahams** [comment]
on Mon Nov 21 2016, Kyle Meyer <notifications-AT-github.com> wrote:

>> I guess melpa hasn't got the fix yet.
>
> Hmm, it should have it.  melpa's currently at 20161120.1223, but your
> version output above indicates that you're at 20160629.1156.

Heh, so it was.  I think I had a leftover customization that pinned the
version at v1.

Thanks,
-- 
-Dave
