### ISSUE TITLE
Return key in dispatch popup signals error

### ISSUE THREAD

**Issue by kyleam** [magit/magit#2870]
I'm pulling this issue out from the [discussion] in #2868 so that it's
not lost in a merged PR.

The error is due to the approach used in `magit-visit-thing`, where
`(key-binding [return])` returns `nil`.  `(key-binding "\^M")` returns
the intended command.

```
Debugger entered--Lisp error: (wrong-type-argument commandp nil)
  call-interactively(nil)
  (progn (setq magit-current-popup nil) (call-interactively (key-binding (this-command-keys))))
  (if (eq magit-current-popup (quote magit-dispatch-popup)) (progn (setq magit-current-popup nil) (call-interactively (key-binding (this-command-keys)))) (user-error "There is no thing at point that could be visited"))
  magit-visit-thing()
  funcall-interactively(magit-visit-thing)
  call-interactively(magit-visit-thing)
  [...]
  call-interactively(magit-invoke-popup-action nil nil)
  command-execute(magit-invoke-popup-action)
```

The fix I suggested in #2868 was to not bind `[return]` explicitly in
the local map of the dispatch popup, allowing it be translated to C-m.
Another option is to replace `(key-binding (this-command-keys))` with
`(key-binding "\^M")`.  I don't think hardcoding it here introduces
any additional assumptions to the current approach.

[discussion]: https://github.com/magit/magit/pull/2868#discussion_r89324847

**Comment by tarsius** [comment]
Thanks, but I was getting there anyway ;-)
