### ISSUE TITLE
Appreciate your work

### ISSUE THREAD

**Issue by deech** [magit/magit#2871]
No issue, just wanted to thank you for all of your hard work on Magit. I use it daily and it works great. Happy Thanksgiving!

**Comment by tarsius** [comment]
Thank you too!

**Comment by tarsius** [comment]
And thanks to @kyleam and @npostavs for helping me!

**Comment by johnmastro** [comment]
Thanks to the Magit developers from me too!

(Seeing this reminded me to [make a donation](https://magit.vc/donations/), which I hope others will also consider)

**Comment by tarsius** [comment]
Thanks @johnmastro!
