### ISSUE TITLE
Sort branch names by commit date

### ISSUE THREAD

**Issue by mgeisler** [magit/magit#2872]
I often find myself switching between the same few branch names and recently I started having two branches with the same prefix: `release-2.0` and `release-2.1`. I use magit-ido-completing-read, and with the shared prefix, I end up typing `rel21` again and again.

I would therefore like to see `--sort=-committerdate` included in magit-list-refnames as @kyleam kindly suggested:
```diff
diff --git a/lisp/magit-git.el b/lisp/magit-git.el
index af9134c..7af3975 100644
--- a/lisp/magit-git.el
+++ b/lisp/magit-git.el
@@ -1012,6 +1012,7 @@ (defun magit-list-unmerged-to-upstream-branches ()

 (defun magit-list-refnames (&rest args)
   (magit-git-lines "for-each-ref" "--format=%(refname:short)"
+                   "--sort=-committerdate"
                    (or args magit-list-refs-namespaces)))

 (defun magit-list-branch-names ()
```

In my testing, this makes it much faster to select the "right" branch -- which in my case means the most recently active branch.

**Comment by tarsius** [comment]
That is already possible by <kbd>C-u y = s</kbd> `c` `<kbd>RET</kbd>. However the next time you want to list references you have to do it all over. I noticed that while working on #2894 and am going to fix it while working on that.

**Comment by kyleam** [comment]
As far as I understand, this isn't about the magit-refs-mode.  It's
about changing the order of the refs in completion prompts.

**Comment by tarsius** [comment]
Ups ;-)

**Comment by kyleam** [comment]
@mgeisler As of 9c003a936, setting `magit-list-refs-sortby` to
"-creatordate" should provide the behavior you want.

**Comment by mgeisler** [comment]
@kyleam I just tested it and it works, thanks a lot! :-)

**Comment by alexanderkjeldaas** [comment]
This should be the default IMO - it's such an efficiency gain.
