### ISSUE TITLE
Can't use smerge (any more)

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2876]
Hi,

Magit 20161128.1456, Git 2.10.2, Emacs 25.1.50.10, gnu/linux

I wanted to add to a commit, HEAD~3 or so.  I commit these changes as a new commit and envoked r i to make this new commit a fixup to be applied to the commit I wanted to change.

As expected, there were conflicts when this commit was tried to be applied.  The files appeared as "unmerged" both in "Unstaged" and in "Staged".  But when I hit RET on a file in either section, I did not get the file in smerge-mode.  I could enable smerge-mode manually, but it said there were no conflicts.

OTOH, E m worked totally as expected.

FWIW, after rebase had stopped, the "staged" section contained blank files, and the "unstaged" section contained the expected content including the conflict markers.

TIA,

Michael.

**Comment by tarsius** [comment]
Can you reproduce this? (If not, then you maybe accidentally removed the conflicts somehow.)

**Comment by michael-heerdegen** [comment]
It will be some work to reproduce this.  But it can't be true that I accidentally removed the conflicts since E m was able to resolve conflicts _after_ I had tried to do that with smerge unsuccessfully as described.

**Comment by kyleam** [comment]
> I could enable smerge-mode manually, but it said there were no conflicts.

This suggests that it will be an issue with smerge, not magit.

**Comment by michael-heerdegen** [comment]
I tried to recreate the situation: I reset HEAD to the HEAD commit before I had started the rebase.  And started the very same rebase operation.  Indeed could I not reproduce this time, smerge worked as expected.  Very strange...

**Comment by michael-heerdegen** [comment]
Anyway, you probably won't be able to do much about this then, so closing for now - thanks so far.
