### ISSUE TITLE
The situation after magit-rebase-edit-commit

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2877]
Hi,

Magit 20161128.1456, Git 2.10.2, Emacs 25.1.50.10, gnu/linux

After calling r m, the commit to be changed is blue and entitled "same".  The manual:
```
(info "(magit) Information about in-progress rebase")
```
says blue means "HEAD commit".  OTOH, it says that "When a commit is prefixed with ‘goal’, ‘same’, or ‘work’, then that indicates that you reset to an earlier commit (and that this commit therefore is no longer reachable from ‘HEAD’)".  That seems a contradiction to me: if it is the HEAD commit, how can it be unreachable from HEAD?

And then: "When a commit is prefixed with ‘same’, then that indicates
that it is no longer possible to create a commit with the
exact same tree, but that it is still possible to create a
commit with the same patch-id.  This would be the case if you
created a new commit with other changes, but the changes from
the original commit still exist in the index and/or working
tree in untainted form."

This description also seems not to apply.

**Comment by michael-heerdegen** [comment]
BTW, a more general issue is that for the user it's not obvious how a commit should be altered with "magit-rebase-edit-commit" - should I just stage, or use c e, or something else?

**Comment by tarsius** [comment]
Indeed something seems to go wrong here.

> BTW, a more general issue is that for the user it's not obvious how a commit should be altered with "magit-rebase-edit-commit" - should I just stage, or use c e, or something else?

Either stage and amend `c e`, and then continue the rebase `r r`. Or skip the amend step, continuing the rebase will then do it for you. This doesn't work any different in Magit than when using Git directly. The `git-rebase` manpage has this to say on the matter:

> By replacing the command "pick" with the command "edit", you can tell git rebase to stop after applying that commit, so that you can edit the files and/or the commit message, amend the commit, and continue rebasing.

It does not appear that the manpage mentions that staged changes will automatically be committed when continuing though.

**Comment by michael-heerdegen** [comment]
BTW, a more general issue is that for the user it's not obvious how a commit should be altered with "magit-rebase-edit-commit" - should I just stage, or use c e, or something else?

**Comment by michael-heerdegen** [comment]
> Indeed something seems to go wrong here.

Ok.

>  BTW, a more general issue is that for the user it's not obvious how a
>  commit should be altered with "magit-rebase-edit-commit" - should I
>  just stage, or use c e, or something else?
>
> Either stage and amend c e, and then continue the rebase r r. Or skip
> the amend step, continuing the rebase will then do it for you. This
> doesn't work any different in Magit than when using Git directly. The
> git-rebase manpage has this to say on the matter:
>
>  By replacing the command "pick" with the command "edit", you can tell
>  git rebase to stop after applying that commit, so that you can edit
>  the files and/or the commit message, amend the commit, and continue
>  rebasing.
>
> It does not appear that the manpage mentions that staged changes will
> automatically be committed when continuing though.

Can we make the Magit manual tell users everything you said here (two
sentences, in effect)?  Because, as a separate, self-contained user
command, I think r m deserves to be documented exhaustively.  I know we
can't document every git internal, but I think the goal should be that
the basic Magit commands should be usable without consulting the (mostly
quite poor) git docs.

**Comment by tarsius** [comment]
There's still another case where the displayed information isn't correct. That's part of a bigger bug, which I will address shortly.

**Comment by michael-heerdegen** [comment]
The blue commit is marked as `stopped' now.  I guess this is a new type of keyword - shouldn't it be described in the listing in ```(info "(magit) Information about in-progress rebase")```?

**Comment by tarsius** [comment]
It isn't really new, it just never appeared due to the bug. I'll look into this at a later time. (I already did and I am unsure whether I just want to correct the documentation or also improve the behavior.)

**Comment by tarsius** [comment]
Closing in favor of the pr #2913.
