### ISSUE TITLE
Git 2.11 with autosized SHA1 abbreviations breaks magit log popup with graph

### ISSUE THREAD

**Issue by bsuh** [magit/magit#2880]
## Expected behavior
Graph lines looks correct

## Actual behavior
Graph is misaligned because magit assumes that SHA1 abbreviations are always 7 characters in the absence of core.abbrev setting
![image](https://cloud.githubusercontent.com/assets/47231/20816007/1ccd307a-b7d5-11e6-8996-009f9a5e3ef4.png)

## Steps to reproduce
```
cd
git clone https://github.com/magit/magit
cd magit/
emacs
```
Use magit log with --graph with git 2.11 installed

https://hackernoon.com/whats-new-in-git-2-11-64860aea6c4f#.2sje4k2ot

**Comment by kyleam** [comment]
Thanks.  I'll try to find out what's the best way to get the auto-size
value when it's available.

**Comment by kyleam** [comment]
The commit in the `km/auto-abbrev` fixes the issue.  Does that
approach look reasonable to others?

**Comment by npostavs** [comment]
The extra call to git bugs me, but probably it's not significant relative to the cost of producing the log.

**Comment by kyleam** [comment]
Yeah, it bugs me too.  But given a dynamic default length, I don't see
a way around some form of a git call.

**Comment by Silex** [comment]
Can't we force the sha1 length to be 7 instead?

**Comment by tarsius** [comment]
I don't see an alternative to the proposed solution, short of putting the hash behind the graph like Git does.

> Can't we force the sha1 length to be 7 instead?

Somewhere down the line that would be reported as a bug. But you can do that locally.

**Comment by kyleam** [comment]
[Reply to @Silex before I saw @tarsius's comment]

> Can't we force the sha1 length to be 7 instead?

Yes, thanks for mentioning that as an option.  I was making the
assumption that magit-abbrev-length should honor the default used by
git.  We could pass an abbrev length specifically to the git log calls
(core.abbrev if set or 7).

I find the idea of diverging from git here unappealing.  If we
explicitly pass a size to the main git log calls, should we also do this
for calls for other log-like outputs like cherry and bisect?  Should we
use our forced value anywhere "%h" is used?

I think I don't like the inconsistency for a few reasons: 1) auto-sizing
is a nice feature that we should support, 2) it adds an extra layer of
complexity to a user figuring why the abbreviated hash is being shown at
a some length, and 3) if the user is concerned by the performance impact
of an extra git call (like @npostavs, I suspect it'd be swamped by other
factors), they can short-circuit it by setting their global core.abbrev
to 7 or whatever they want.

**Comment by Silex** [comment]
Yeah, keep in mind my suggestion is a short term fix, because the log atm is annoying.

In the long run, I think we should support auto-sizing.

**Comment by tarsius** [comment]
Since the I just updated to v2.11 and the size changed to 8 for Magit itself, I just merged this ;-)
