### ISSUE TITLE
staging hunks collapses diffs in magit-status

### ISSUE THREAD

**Issue by holomorph** [magit/magit#2886]
From -Q:

1. Load magit 2.8.0
2. Navigate to a large repository with changes to the work tree. For whatever reason, this does not happen in a small repo, but happens for me all the time in emacs.git
3. M-x magit-status
4. Expand an unstaged file's hunks
5. Hit n some times to go to an arbitrary hunk
6. Hit s.

IIRC, the usual behavior is for the selected hunk to now be collapsed under the "Staged changes" section, and point is to remain among the unstaged hunks, moving to another hunk header. AFAICT this does happen, however there is additional unexpected behavior.  The unstaged file section gets collapsed, and point is inside the now invisible overlay. Hitting tab will show another hunk without its header.

```
  M-x magit-version RET => Magit 2.8.0, Git 2.10.2, Emacs 26.0.50.1, gnu/linux
```

**Comment by npostavs** [comment]
> For whatever reason, this does not happen in a small repo, but happens for me all the time in emacs.git

Does setting `magit-diff-expansion-threshold` help?

https://magit.vc/manual/magit/Diffs-are-collapsed-after-un_002d_002fstaging.html

**Comment by holomorph** [comment]
It does, thanks. The behavior when the threshold is reached is still pretty troublesome, as it makes accidentally collapsing hunks easy, which in turns causes me to miss them when expanding the file diff again.

**Comment by tarsius** [comment]
Maybe should disable this by default now? We would trade reports like this for complains about performance, but I now think that might be preferable. We made some performance improvements over the last few months so maybe we would get less complains now. I also still plan to further improve performance, but that probably shouldn't affect our decision on what we do here.

**Comment by npostavs** [comment]
> Maybe should disable this by default now?

Yes, I've been thinking that too. The current default threshold behaviour isn't that great in terms of perceived performance anyway, because there's a noticeable wait until the threshold is hit.
