### ISSUE TITLE
[Makefile] don't escape dbl-quotes in template

### ISSUE THREAD

**Issue by vp1981** [magit/magit#2887]
Hello,
after switching to template based 'magit-version.el' generation, commit https://github.com/magit/magit/commit/dd5620bec2e4013d2f9ba6a792370b218abe8b01, Emacs "complains" about the file. It seems that it is not necessary to escape double quotes while they are in template, as well as it is not necessary to use explicit '\n' for last lines in template (cp. with previous template in the same Makefile).

I made small patch to fix the problem:
```
diff --git a/lisp/Makefile b/lisp/Makefile
index 8d8b2e8..4e35013 100644
--- a/lisp/Makefile
+++ b/lisp/Makefile
@@ -106,16 +106,16 @@ export LOADDEFS_TMPL
 define VERSIONLIB_TMPL
 ;;; $(PKG)-version.el --- the Magit version you are using

-(setq $(PKG)-version \""$(VERSION)"\")
+(setq $(PKG)-version "$(VERSION)")

 (provide '$(PKG)-version)

-;; Local Variables:\n
-;; version-control: never\n
-;; no-byte-compile: t\n
-;; no-update-autoloads: t\n
-;; coding: utf-8\n
-;; End:\n
+;; Local Variables:
+;; version-control: never
+;; no-byte-compile: t
+;; no-update-autoloads: t
+;; coding: utf-8
+;; End:
 ;;; $(PKG)-version.el ends here
 endef
 export VERSIONLIB_TMPL
```

Some info about my environment:
distribution: Archlinux x86_64
Emacs: compiled from git
magit: packaged and installed by means of distro tools (makepkg and pacman)
bash: 4.4.5

P.S. There is a 'comment' form at the end of the commit page but I'm not sure if it is more suitable to use that form or just make a new issue.

**Comment by tarsius** [comment]
Thanks!

> P.S. There is a 'comment' form at the end of the commit page but I'm not sure if it is more suitable to use that form or just make a new issue.

Since you did provide a patch, a pull-request would have been suitable. But commenting on the commit *or* opening a new issue are also fine.
