### ISSUE TITLE
allow bash alias as magit-git-executable

### ISSUE THREAD

**Issue by pvinis** [magit/magit#2889]
is there a way to do that? should that be added? i have an alias like `alias dfgit='git --git-dir=$HOME/.dotfiles --work-tree=$HOME` and i would like to use `dfgit` as the `magit-git-executable` when im opening magit in the home dir. makes sense?

**Comment by tarsius** [comment]
Magit runs `git` directly, not inside a shell. So customizing `magit-git-excecutable` would not work because without a shell there are no shell aliases. But you can customize `magit-git-global-arguments` instead and duplicate your shell configuration there.

**Comment by pvinis** [comment]
aha. ok i will try that.

**Comment by pvinis** [comment]
oh, works like magi[ct]! thanks tarsius. now i just have to hook it up so it adds the args when i want to manage my dotfiles and remove it again afterwards. dont know what happens if i have my dotfiles repo and another repo open though.. i guess since its named `global` its for all magit buffers?

**Comment by tarsius** [comment]
Yes, it's for all buffers/repositories. You would have to advice all the functions with use it to get some dynamic behavior.
