### ISSUE TITLE
Release notes for 2.9.0

### ISSUE THREAD

**Issue by phil-s** [magit/magit#2890]
Opening this as somewhere for people to post any errors they've spotted.

**Comment by phil-s** [comment]
These two function names are the same:

<blockquote>
  The new functions `magit-diff-highlight-hunk-region-using-overlay'
  and `magit-diff-highlight-hunk-region-using-overlay' draw one-pixel
  lines before and after the hunk-internal region.  Both of these
  functions have (different) glitches and due to limitations of Emacs'
  display engine it is not possible to fix those.  #2293, #2758, #2791
</blockquote>

**Comment by phil-s** [comment]
"now jump" should be "now jumps" or "will now jump" ?

<blockquote>* If, and only if, point is on a removed line in a diff, then "RET"
  now jump to the last commit which still had that line, not the
  commit which removed that line.</blockquote>

**Comment by phil-s** [comment]
`RET` should be "RET"

<blockquote>
* When visiting a file or blob buffer by pressing `RET` 
</blockquote>

**Comment by phil-s** [comment]
`magit-diff-highlight-hunk-region-using-overlay` should be plural: `magit-diff-highlight-hunk-region-using-overlays`

**Comment by phil-s** [comment]
Not a release notes error, but the docstring for new command `magit-find-git-config-file` has a typo:

"Edit a located in the current repository's git directory."

Should be "Edit a file ..." ?

**Comment by phil-s** [comment]
"now allows specify" should be "now allows specifying" ?

"using a function that return a different value" should be "using a function that returns a different value".

<blockquote>* `magit-define-popup' now allows specify `:max-action-columns' per
  section by using a function that return a different value based on
  the heading, which is passed as argument.  964fcbe0</blockquote>

Likewise in the associated docstring for `magit-define-popup`, "return a number" should be "returns a number":
<blockquote>`:max-action-columns'
  The maximum number of actions to display on a single line, a
  number or a function that return a number</blockquote>

**Comment by phil-s** [comment]
"32-bit" is typically hyphenated. Maybe just author's preference.

<blockquote>* On 32bit systems `magit-format-log-margin' failed</blockquote>

**Comment by phil-s** [comment]
"handed of to git" should be "handed off to git"

<blockquote>
* The user name and email, which are displayed when reading a gpg key
  from the user, were not stripped from the chosen value before being
  handed of to git.  #2761
</blockquote>

**Comment by phil-s** [comment]
That's all from me. It sounds like another great release! Thanks for your continual hard work on this excellent software.

**Comment by Yevgnen** [comment]
When I rebase, I get 
```
error in process sentinel: magit-log-wash-rev: Wrong type argument: number-or-marker-p, nil
error in process sentinel: Wrong type argument: number-or-marker-p, nil
```
each time. I'm not sure whether this is related to the release. Also, the logs become a bit different from the older version and before rebasing, both of which will not show the [name][number] part.
<img width="462" alt="screen shot 2016-12-08 at 10 32 09 pm" src="https://cloud.githubusercontent.com/assets/16749790/21013765/39e99a7e-bd96-11e6-9f96-c0ee037396ed.png">

**Comment by kyleam** [comment]
@Yevgnen, please open a separate issue for that.  It will help if you
can point to a public repo that we can use to reproduce the error.
