### ISSUE TITLE
Commit message and magit-display-buffer-fullcolumn-most-v1

### ISSUE THREAD

**Issue by a3ammar** [magit/magit#2891]
Using `magit-display-buffer-fullcolumn-most-v1` as the value for `magit-display-buffer-function` I expect the commit message buffer to behave like in `magit-display-buffer-traditional`: a horizontal split between it and the diff buffer. What happens is the diff buffer uses the full window and buries the commit message buffer.

Magit 20161001.1454, Git 2.10.0, Emacs 25.1.1, darwin

**Comment by kyleam** [comment]
Thanks, confirmed.  Can you check that the change on the km/fullcolumn
branch behaves as you expect?

**Comment by a3ammar** [comment]
Yes it fixes the issue perfectly. Thank you!
