### ISSUE TITLE
error in process sentinel: magit-log-wash-rev: Wrong type argument: number-or-marker-p, nil

### ISSUE THREAD

**Issue by Yevgnen** [magit/magit#2892]
When running a instant Fixup or rebasing, if the result diverges from the remote,  the error
```
error in process sentinel: magit-log-wash-rev: Wrong type argument: number-or-marker-p, nil
error in process sentinel: Wrong type argument: number-or-marker-p, nil
```
happens. Also,  the logs become a bit different from the older version and before rebasing, both of which will not show the [name][number] part and should show the rebased unpush commits. 
<img width="462" alt="screen shot 2016-12-08 at 10 32 09 pm" src="https://cloud.githubusercontent.com/assets/16749790/21015232/2c7cefb6-bd9c-11e6-96b0-1d94db50121c.png">

There are two differences compared to normal situation.
1. The log styles changed
2. The rebased unpush commit is not shown now.

A possible reproduce way maybe first create somewhat remote repo, and run 
```
mkdir temp
cd temp
git init .
echo "111111111111" > a
git add a
git commit -m "1"
echo "222222222222" > a
git add a
git commit -m "2"
echo "333333333333" > a
git add a
git commit -m "3"
git remote add origin git@github.com:Yevgnen/a.git
git push -u origin master
echo "2222222222-1" > a
git add a
```

Then run a instant Fixup in magit in to the second commit(to change 22222...2 into a fix 222...2-1). Fix the conflicts and continue rebase. The error describe happens after the rebasing is finished, given the error and 

<img width="197" alt="screen shot 2016-12-08 at 11 20 49 pm" src="https://cloud.githubusercontent.com/assets/16749790/21015447/f942ed0c-bd9c-11e6-8bf5-c28398d59e28.png">

Magit version is : `Magit 20161206.2039, Git 2.11.0, Emacs 25.1.1, darwin`

Emacs version is : `GNU Emacs 25.1.1 (x86_64-apple-darwin16.1.0, Carbon Version 157 AppKit 1504.6) of 2016-11-02`

I got this error since the latest update of `magit`, and I have no idea whether this is related to it. Any help will be appreciated !

**Comment by kyleam** [comment]
Thanks for providing steps to reproduce.  I've tried, but the logs are
washed fine on my end.

Do you see the same error with emacs -Q?

You could also try stepping through magit-log-wash-rev to get more
information about what's tripping up the washer.

**Comment by Yevgnen** [comment]
@kyleam I figured out that this is because I've customized the value of `magit-status-margin` and the latest version seems put a different default 

```(list nil
        (nth 1 magit-log-margin)
        'magit-log-margin-width nil
        (nth 4 magit-log-margin))
```

than the old value `'(nil nil (nth 2 magit-log-margin))`.

**Comment by Yevgnen** [comment]
@kyleam By the way, can you tell me what is the proper way to avoid show commit time(or hiding the whole margin) in the `magic-status`? The margin always shows after I fetched from remote or rebased in the recent version of magit.

**Comment by kyleam** [comment]
> I figured out that this is because I've customized the value of
> magit-status-margin and the latest version seems put a different
> default

Great, thanks for reporting back.

> can you tell me what is the proper way to avoid show commit time(or
> hiding the whole margin) in the magic-status?

Hmm, having nil as the first element of `magit-status-margin` should
do it.

**Comment by Yevgnen** [comment]
Thanks for you reply. I'm used to set it to `'(nil nil nil)` in the previous version but got no luck as the default value also has the first element of `nil`. I'll try it in latest version.
