### ISSUE TITLE
-p instead of -u for --patch?

### ISSUE THREAD

**Issue by fice-t** [magit/magit#2897]
I think `-u` in the log popup should be changed to `-p`. It appears first in the `git log` manpage (and `git log -p` appears in the manpage while `git log -u` doesn't), is ostensibly more popular (19,400 results for `git log -p` vs. 1,690 for `git log -u` in Google), and is more mnemonic than `-u`.

**Comment by kyleam** [comment]
[Related to discussion in #2622.]

I prefer p to u, but I'm not sure if it's worth changing now.  I also
wonder how many people use that flag regularly instead of following
along with the revision buffer.  (I think the only time I've used it
is when fixing the bug that you reported in #2622.)

**Comment by tarsius** [comment]
> I prefer p to u, but I'm not sure if it's worth changing now.

That sums it up for me too. To elaborate on "not worth changing": changing key bindings tends to cause protest, so we only do it when there is (in our opinion) a real benefit to be had. But in this case, because `git log` understands both `-u` and `-p` I don't see such a benefit.

**Comment by fice-t** [comment]
Right, I was just reminded of this when reading about key binding changes in the latest release notes. I figured that this key binding, since it's not used that much, wouldn't cause nearly the amount of protest, if any, that occurred in earlier 2.x versions of magit.

What about changing this key binding during the 3.0 release? I believe people wouldn't be surprised to see some form of key binding changes during a major release, so it would be a good time to make some key bindings a little nicer.

**Comment by tarsius** [comment]
> What about changing this key binding during the 3.0 release?

That's definitely a possibility, especially since I intend to add a "show all the arguments git supports (and which are not incompatible with magit), using the same arguments as on the command line" mode.
