### ISSUE TITLE
Customizations to `git-commit-setup-hook` are overwritten

### ISSUE THREAD

**Issue by Jehops** [magit/magit#2902]
I customize `git-commit-setup-hook` to include `git-commit-turn-on-flyspell`.  However, after running `magit-status` for the first time, the variable no longer includes `git-commit-turn-on-flyspell` and it's reported to have been `CHANGED outside Customize`.  If I remove the lines below from `git-commit.el`, everything works as expected.

    (unless (find-lisp-object-file-name 'git-commit-setup-hook 'defvar)
     (add-hook 'git-commit-setup-hook 'with-editor-usage-message)
     (add-hook 'git-commit-setup-hook 'git-commit-propertize-diff)
     (add-hook 'git-commit-setup-hook 'git-commit-turn-on-auto-fill)
     (add-hook 'git-commit-setup-hook 'git-commit-setup-changelog-support)
     (add-hook 'git-commit-setup-hook 'git-commit-save-message))

This is with `Magit 20161214.1516, Git 2.11.0, Emacs 25.1.90.1, berkeley-unix`.

**Comment by tarsius** [comment]
I cannot reproduce that and it also seems unlikely that the code that you removed would have any influence on this. Are you sure `git-commit-turn-on-flyspell` really isn't on the hook, i.e. maybe its entry isn't ticked off in the Custom interface, but it appears at the end of the list as an additional item?

> it's reported to have been `CHANGED outside Customize`.

Yeah, package authors aren't really supposed to define hooks as customizable options - `defcustom` isn't up to the task. That's why there is that strange form is there in front of the definition. That's supposed to ensure that the default functions are on the hook, even if a user uses `add-hook` before the library is loaded. But one effect is that an option may be reported as being changed outside of Custom even when that is not really the case.

**Comment by Jehops** [comment]
I can reproduce the problem with this recipe.

1. Stop running emacs (client and daemon) then move all configuration out of the way.
` mv ~/.emacs.d ~/.emacs.d.bak
2. Create an empty configuration
`mkdir ~/.emacs.d && touch ~/.emacs.d/init.el`
3. Add these contents to `~/.emacs.d/init.el`.
 ```
    (setq custom-file "~/.emacs.d/custom.el")
    (setq package-archives
           '(("gnu" . "https://elpa.gnu.org/packages/")
    	    ("melpa" . "https://melpa.org/packages/")))
    (package-initialize)
```
4. Start emacs (daemon and client)
`emacsclient -a '' -nc`
5. Install magit from melpa
6. Run `magit-status`
7. Customize `git-commit-setup-hook` so that it includes `git-commit-turn-on-flyspell`
`~/.emacs.d/custom.el` now contains
```
 '(git-commit-setup-hook
   (quote
    (git-commit-save-message git-commit-setup-changelog-support git-commit-turn-on-auto-fill git-commit-turn-on-flyspell git-commit-propertize-diff with-editor-usage-message))))
```
8. Stop the emacs daemon/client
`M-x kill-emacs RET`
9. Start emacs (daemon and client)
`emacsclient -a '' -nc`
10. Run `magit-status`
11. Check `git-commit-setup-hook` and it will not include `git-commit-turn-on-flyspell`.

**Comment by npostavs** [comment]
Look like the problem is that `custom-initialize-reset` ignores the custom value if the variable is already initialized:

```elisp
(defun custom-initialize-reset (symbol exp)
  "Initialize SYMBOL based on EXP.
Set the symbol, using its `:set' function (or `set-default' if it has none).
The value is either the symbol's current value
 (as obtained using the `:get' function), if any,
or the value in the symbol's `saved-value' property if any,
or (last of all) the value of EXP."
  (funcall (or (get symbol 'custom-set) #'set-default-toplevel-value)
           symbol
           (condition-case nil
               (let ((def (default-toplevel-value symbol)) ;<--- go to error case if unbound
                     (getter (get symbol 'custom-get)))
                 (if getter (funcall getter symbol) def))
             (error
              (eval (let ((sv (get symbol 'saved-value))) ;<--- the value saved by customize
                      (if sv (car sv) exp)))))))
```

**Comment by phil-s** [comment]
Jehops:

You've told Emacs where to save customized values:

    (setq custom-file "~/.emacs.d/custom.el")

But you're not *loading them* in your init file at all. You need to add:

    (load custom-file)

**Comment by Jehops** [comment]
Ah, right.  Thanks.  I've updated the recipe, but the result is the same.
