### ISSUE TITLE
'Checkout or create' branch

### ISSUE THREAD

**Issue by DamienCassou** [magit/magit#2906]
This is a feature request. Our team creates plenty of branches that are pushed to the remote. When starting to work on something I have to either:

1. create a local branch by checking out an existing remote branch (i.e., a colleague already worked on the task) (the name of the new branch is the same as in remote): <kbd>b c</kbd>
2. checkout a local branch that's already dedicated to the task (i.e., I already worked on the task earlier) (the branch already has a name): <kbd>b b</kbd>
3. create a local branch on top of master (i.e., nobody worked on the task yet) (in this case I have to give the branch a name): <kbd>b j</kbd> (personal shortcut that computes the new branch name by [looking at the Jira issue tracker](https://gist.github.com/DamienCassou/d5d05c2501271ac4b55281b4c7aef4fc))

The problem is that I have to know in which case I am (either 1, 2 or 3) before doing the right shortcut.

**Comment by tarsius** [comment]
This seems doable. I'll probably implement such a command eventually, but not very soon.

**Comment by DamienCassou** [comment]
@tarsius can you please tell us what you have in mind for this? This would allow others (maybe me) to implement it myself. Thanks

**Comment by tarsius** [comment]
I haven't given it too much thought yet, but it seems fairly straight forward:

- Read a branch name from the user offering both local and remote branches as candidates.
- Do not offer any remote branches whose names match that of a local branch.
- The user can also enter a new branch name.

Based on the user input use one of your three variants:

1. A remote branch was chosen.
2. A local branch was chosen.
3. A new branch name was given.

Of course there are some details to be considered, but those are already covered by the existing commands that are dedicated to just one of those variants, i.e. look at their implementation to avoid dropping some feature that those commands provide on top of plain `git [branch|checkout] ...`.

**Comment by DamienCassou** [comment]
I think some of the code referenced in https://github.com/magit/magit/issues/3104 are a step forward on this.

**Comment by tarsius** [comment]
I am working on this in #3232.

**Comment by tarsius** [comment]
Okay now it is in #3247. Ready for review and all.

**Comment by tarsius** [comment]
See https://github.com/magit/magit/pull/3247#issuecomment-342934247 ff.
