### ISSUE TITLE
magit-list-repositories with indicator of need of commit

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [magit/magit#2907]
Hi,

I have started using magit-list-repositories. It must be convenient.

It would become much better if I could know whether a repo needs commit or not. 
"Changed" flag for example.

I sometimes forget to commit and push before I go home.

**Comment by tarsius** [comment]
If added such a column. To use it you have to add an entry such as `("D" 1 magit-repolist-column-dirty nil)` to `magit-repolist-columns`. (I recommend you use Custom to do so.)

**Comment by HIRANO-Satoshi** [comment]
Thank you very much!!

I cannot live without magit.
