### ISSUE TITLE
magit-branch-spinoff should support a single commit

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2920]
It already supports spinning off fewer than all unpushed commits by using the region to mark multiple commits. It is not possible to select a single commit (or any section) using this selection mechanism and so it is not possible to spin off a single commit yet.

This command should be taught to spin off just the `HEAD` if point is on it in the list of unpushed commits, but not when it is on e.g. if it is on the `Head: ...` line at the top of the buffer.

There are complications to think about.

**Comment by kyleam** [comment]
Hmm, but there is a docstring/code mismatch [1], right? If the code
followed the region behavior currently described in
magit-branch-spinoff's docstring, wouldn't that make it possible to
select one commit?  In the case of a region spanning two commits, the
original branch would be reset to the bottom commit and only the top
commit would be in the spinoff branch.

[1] https://groups.google.com/d/msg/magit/GzX3EKK6sj4/fj3oYCgBEgAJ

**Comment by tarsius** [comment]
Yes, there is a docstring/code mismatch.

**Comment by tarsius** [comment]
And the code is who is right.

**Comment by tarsius** [comment]
I have fixed the documentation now.

**Comment by kyleam** [comment]
> I have fixed the documentation now.

Thanks.  I would have liked to see some explanation here or in the
commit message of why that was the chosen way.  I had a slight
preference for making the code match the docstring.

**Comment by kyleam** [comment]
Ah, sorry for the noise.  I see that there is some discussion at #3013.  Going there to read...

**Comment by tarsius** [comment]
Please discuss here instead of in #2920, quoting bits from there as necessary.

**Comment by tarsius** [comment]
Cooking in #3234.
