### ISSUE TITLE
Embrace ivy (and support other frameworks better too)

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2926]
[`ivy`](https://github.com/abo-abo/swiper) is "a generic completion mechanism", which "aims to be more efficient, smaller, simpler, and smoother to use yet highly customizable" than the alternatives.

Coming from `ido` (which is complex and set in stone), that's exactly what I wished for. And it does deliver on that promise! With `ido` I had to install half a dozen packages that monkey-patch it to get something reasonably useful, and then I still had to work with the maintainers of those packages to fix a variety of issues.

With `ivy` things just work. Sure I had to customize some things and I am not quite done changing key bindings to my liking and such (and getting over muscle memory from `ido`), but it has been a smooth ride right from the start. I should have switched earlier and am not going back.

So I intend to eventually recommend on my blog that users switch to `ivy`, at least for Magit. But things should be improved a bit before I do that.

Magit's "completion framework wrapper" is a bit strange...

1. Should we really append ": " if that isn't there yet?
2. Should we really unconditionally add " (default: DEFAULT)"?
   * When using `ivy` (and potentially `helm`) we probably shouldn't since the default is initially highlighted anyway.
3. Maybe (probably not) we can remove the `magit-completing-read-function` option.
   * For `ivy` the correct function actually is `magit-builtin-completing-read`, a very thin wrapper around `completing-read` (which does nothing but implement the strange features mentioned above). Therefore enabling `ivy-mode` does the job already.
    * However `ivy`'s documentation claims that `(setq magit-completing-read-function 'ivy-completing-read)` is necessary. Maybe that is true for Magit v1.4.2, which is what `ivy`'s maintainer uses I believe (1). For v2 it is not, and the documentation should be updated accordingly in both places (though that is not urgent as this setting does no harm either).
   * For `ido` we probably need a wrapper because `ido-completing-read` is not actually a sufficient drop-in replacement for `completing-read`. `ido-completing-read+` from the package by the same name is a sufficient replacement though, and that's what we use.
    * `ido-completing-read+.el` contains code that prevents it from being used unless explicitly enabled using this option. It might be possible to remove that code and just rely on `ido-ubiquitous-mode` (from the same author). Not sure if that is desirable though.
   * For `helm` we wrap `helm--completing-read-default`. I don't really know whether that's the appropriate thing to do. *Edit: the doc-string says it is not necessary.* ~~I also don't know if `helm` contains could which actively prevents it from being used unless this is explicitly enabled using this option.~~

---

* (1) @abo-abo I vaguely remember that v2 broke some of your expectations and that you "have no need for the new features" in that release. For obvious reasons I think you too would benefit greatly from updating to v2 and if you share your issues with that, then I would be willing to give you some one-on-one help. (Though I have little time for that this month.)

**Comment by abo-abo** [comment]
@tarsius I'm glad you like `ivy`. I'll update the documentation at some point before the `0.9.0` release, but just like you I don't have a lot of time.

**Comment by tarsius** [comment]
1. Yes. By now our wrapper is fully justified and it is okay if it behaves a bit differently.
2. No. And since 43efcf5179e9ae50e6d42fdab5da8c772502d8e3 we no longer do.
3. We still need it in order to support unknown completion frameworks.

But the documentation still has to be updated, which I am doing as part of #3232.
