### ISSUE TITLE
magit-file-{rename,remove,untrack} should support acting on multiple files at once

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2930]

**Comment by ryanprior** [comment]
Do you picture a dired-like interface to mark and operate on files? Or maybe a dired integration of some kind? I sometimes use a workflow in dired with `dired-mark-files-regexp` or similar into `dired-do-shell-command` `git rm`.

**Comment by tarsius** [comment]
I have done so for `magit-file-remove` and `magit-file-untrack`, but have also decided to not do it for `magit-file-rename`. The latter would be quite a bit more complex and can also be done using e.g. Dired and then staging the pairs of additions and removals.

> Do you picture a dired-like interface to mark and operate on files?

No, this uses Magit's usual "select multiple things of the same type using the region" selection mechanism.

**Comment by yashi** [comment]
I'm sorry to jump in but where is `magit-file-remove`? I've searched in the git repo but none is found.  The reason I'm looking for the function is to remove a file listed in the Untracked files (4) section of Magit buffer.  Would that function does what I'm looking for?

**Comment by tarsius** [comment]
There is a function named `magit-file-delete`. You can press `k` on a file listed below "Untracked files" to "kill" it.

**Comment by jdnrg** [comment]
please reopen this feature request, it would be great.

**Comment by DrWaleedAYousef** [comment]
Actually, I am not sure whether I should jump in here or create a new issue, although it is exactly the same issue. [This reply](https://github.com/magit/magit/issues/2930#issuecomment-339796199) does not work in my case because I am using `helm`. More precisely, when I hit `K` in the magit buffer, `helm` populate a list of files. I cannot do multiple selection from this list!

**Comment by tarsius** [comment]
> No, this uses Magit's usual "select multiple things of the same type using the region" selection mechanism.

This means that you have to use the region to select multiple files and then press `K`. If you press `K` without selecting multiple files first, then you get a prompt that asks you to select exactly one file, regardless of completion framework.
