### ISSUE TITLE
Massage certain error messages before showing them to user

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2932]
When git exits with a non-zero exit-code, then Magit inserts "the" error message at the top of the status buffer. The complete output can also be seen in the process buffer. In some cases these messages are rather misleading, e.g.:

```
GitError! There was a problem with the editor '/usr/local/bin/emacsclient-25.1 --socket-name=/tmp/emacs1000/server'.  [Type `$' for details]
Head:     master Autoload ido-enter-magit-status
...
```

```
  1 git … commit --allow-empty
Waiting for Emacs...
*ERROR*: Canceled by user
error: There was a problem with the editor '/usr/local/bin/emacsclient-25.1 --socket-name=/tmp/emacs1000/server'.
Please supply the message using either -m or -F option.
```

For known problematic messages we should display something more meaningful in the status buffer and possibly append an explanation to the output in the process buffer.

**Comment by brendan-r** [comment]
Just out of interest, is there a way around this error (e.g. to make commits), outside of restarting Emacs?

**Comment by kyleam** [comment]
@brendan-r  I think this issue is just about how things are displayed
in the status buffer when Git has a non-zero exit code.  The error
shown above results from the _user_ aborting while writing the commit
message.  There should be no need to restart Emacs---or to do anything
at all---to recover.

**Comment by tarsius** [comment]
I don't think restarting Emacs would help with this particular error. It's either a misconfiguration (which doesn't magically fix itself in most cases) or you have explicitly aborted the commit yourself (in which case it isn't an error, which is one of the reasons why we should not display this particular error).

In any case this is not related to this feature issue (it only serves as an example), so if you need help configuring `with-editor` after having read https://magit.vc/manual/with-editor/Debugging.html, then you should open a new issue.

**Comment by tarsius** [comment]
I have implemented a mechanism that can be used to *suppress non-errors*. The only one I can actually think of is the "error" shown when the user aborts a commit. That is being suppressed now.

I have *not* implemented a mechanism for modifying messages because I cannot remember any instance where that would have been necessary. But what we have now could easily be extended to support that too.
