### ISSUE TITLE
Get Magit additions into Emacs

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2933]
Magit contains some features that should instead be implemented directly in Emacs.  This list is not exhaustive, I intend to add to it as I run into more things.

- [ ] Ediff provides two commands for resolving conflicts with the help of some vcs.  For each vcs and/or vcs interface some parts have to be implemented separately.  The issues are in the common part: most importantly the user has to resolve all conflict, including those that the vcs already resolved successfully.  Also see [Can Magit be used as ediff-version-control-package?](https://magit.vc/manual/magit/Can-Magit-be-used-as-ediff_002dversion_002dcontrol_002dpackage_003f.html).

- [ ] Emacs provides the option `server-window` to allow users to customize what function should be used to show the buffer and optionally switch to the used window. But sometimes that isn't enough because a user or package wants to use different function for different files. The `with-editor` package (which was  written for the benefit of Magit and was originally part of it) defines an additional option `with-editor-server-window-alist` and advices `server-switch-buffer` to respect that. Emacs should just provide such an option itself.

- [ ] Teach `tabulated-list` about `:help-echo`. See #3233.

- [X] Fix `auth-source` bug. See https://github.com/magit/ghub/commit/3ba864662920fee7c9e880376201e048a6570678. Done, will be fixed in Emacs 26.2 (emacs-mirror/emacs@5e42c349a0533602c23bf651d6b28eca25e95a46)

**Comment by npostavs** [comment]
> Fix auth-source bug. See magit/ghub@3ba8646.

This one is fixed in `emacs-master` now (specificallly, emacs-mirror/emacs@60ff8101449eea3a5ca4961299501efd83d011bd). Do you think it's worth backporting to 26.2?

**Comment by tarsius** [comment]
I don't no the policy, but this is clearly a bug and the fix comes with tests and all. I think this should make it into the next release because the fixed issue is rather confusing.

**Comment by npostavs** [comment]
I've pushed it to emacs-26 (and updated the OP here).

**Comment by tarsius** [comment]
I am busy improving magit instead (and already had to extend the "year" of magit to 15 months). Maybe next year...
