### ISSUE TITLE
Get Magit additions into Git

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2934]
Magit contains some features that should instead be implemented directly in Git.  This list is not exhaustive, I intend to add to it as I run into more things.

- [ ] Stashing improvements.

  Magit uses its own code for creating stashes.  To implement the following changes in `git-submodule.sh` some functions have to be split up and the individual functions have to be exposed as sub-commands.  But if I remember correctly the actual functionality is there already.

  - Magit supports creating a stash without simultaneously removing the stashed changes from the working tree.  This is useful because it allows creating snapshots e.g. for backup purposes.  With Git one has to apply the just created stash to achieve the same, which is cumbersome and messes with time-stamp based build-systems.

  - Magit supports stashing only the working tree or only the index instead of both. (`--keep-index` isn't the same.)

- [ ] Sequencer improvements.

  See below.

**Comment by nmorey** [comment]
Magit's handling of the sequencer status (during rebase, merge, cherry picks, etc.) should also be upstreamed.
There was a little talks about this here: https://public-inbox.org/git/8e25c42f-80f2-e0d4-38e4-b4fe9c8074e0@morey-chaisemartin.com/

**Comment by tarsius** [comment]
I am busy improving magit instead (and already had to extend the "year" of magit to 15 months). Maybe next year...
