### ISSUE TITLE
Support applying simple diff patch files

### ISSUE THREAD

**Issue by phil-s** [magit/magit#2940]
Magit 2.10.0-dirty, Git 2.6.6, Emacs 24.5.1, gnu/linux

On the command line one can `git apply foo.patch` where foo.patch is unadorned `git diff` output, without any of the additional patch file formatting that magit supports/requires.

It would be helpful if one could apply such unformatted patch files in magit.

Attempting to do so via the patch popup with `w w`causes a `git am` command, which fails with "Patch format detection failed."

Presumably magit would itself need to detect the file format (or lack thereof) in order to intelligently issue a `git apply` command instead of a `git am` command, but I think an `a` for `git apply` Action could usefully be added to that menu alongside "`w Apply patches    m Apply maildir`" (the `w` label would then need to be differentiated). That would seem like a least-effort approach to achieving the goal?

**Comment by phil-s** [comment]
And tangentially, if deferred diff generation in the status buffer becomes a feature at some point, it would be pretty awesome if `TAB` on a patch file went ahead and expanded it as a diff in the status buffer, with all the expected functionality available.

**Comment by tarsius** [comment]
Both suggestions are reasonable and doable. Not sure I will get to it soon though.

> That's not part of this feature request, but I could raise it separately if you like.

Please do that.

**Comment by amosbird** [comment]
I just ran into this. It would be a very useful feature to have, especially for those old git projects.

**Comment by tarsius** [comment]
Someone asked on gitter for a command to add the diff to the kill ring. Once it is possible to save the diff to a file it will also be easy to do that. So I am just adding this here, instead of opening a new issue.
