### ISSUE TITLE
Warn the user before rewriting public history

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2945]
When the user is about to modify public history, then s/he should be warned.  This affects existing methods of history manipulation such as explicitly invoking an interactive rebase using <kbd>r i</kbd> and starting from a commit that has already been pushed to a public branch "which should not be modified".

Adding such protection is even more important for the new methods of initiating history manipulation proposed in #2943 and #2944, because those make it more likely that a user accidentially attempts to modify a commit that is further back in history than expected.

Beside finding the correct places where to check whether the user is about to modify history s/he shouldn't be modifying, the main challenge here is to determine whether a certain commit/branch falls into that category.

Obviously all commits that haven't been pushed anywhere yet are fair game, but just because a commit has been pushed, that doesn't necessarily make it "history".  It is common to modify commits on feature branches during review, and to enable such review feature branches are usually pushed somewhere.

A minimal-viable implementation could use an option that allows users to specify a list of "final" branches.  The default could include "master" and "maint", but something like "next" is already not so clear cut, those the need for an option.

**Comment by tarsius** [comment]
When amending to a published commit or doing an interactive rebase affecting published commits you should be asked for confirmation now. Customize `magit-published-branches` to control which branches are considered to be published.

**Comment by EuAndreh** [comment]
Thanks for the detailed explanation on the reasoning behind it.

I true Emacs thinking, I wanted to tweak this behaviour, and imagined that the authors did add a possible customization variable. I was easily able to find this issue due to it's rich reasoning behind it.

:bow:
