### ISSUE TITLE
Make untracked patch files expandable in the status buffer

### ISSUE THREAD

**Issue by phil-s** [magit/magit#2947]
If deferred/on-demand diff generation in the status buffer becomes a feature at some point, then it would be great if typing TAB on an untracked patch file went ahead and loaded/expanded it as a diff in the status buffer, with all the expected functionality available.

(Split from #2940)

**Comment by tarsius** [comment]
If I implement this, then I should probably also give #2844 another chance.

**Comment by tarsius** [comment]
I think having to visit the patch in another buffer is acceptable or even preferable. I don't like squeezing everything into the status buffer :wink: 

I am adding the `wontadd` label. Occasionally I revisit the issues that have that label, so it is still possible that I will eventually implement this, but it has gotten less likely.

**Comment by phil-s** [comment]
> I think having to visit the patch in another buffer is acceptable or even preferable.

Can we currently generate a Magit diff buffer from a patch file?  I've just been trying a few things (patch commands, diff commands, magit-file-popup, visiting and switching to magit-diff-mode), but couldn't see a way to do this.

My original idea was not only about being able to view the patch file, but being able to *interact* with it as a diff.

**Comment by tarsius** [comment]
I already plan to turn `magit-diff-mode` into something that can be used as a substitute of `diff-mode`. Not sure this is properly described in some issue though.

**Comment by tarsius** [comment]
Just in case, I have added a note to #2938.

**Comment by phil-s** [comment]
Nice. Cheers.
