### ISSUE TITLE
Finally replace magit-popup with a more capable implementation

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2957]
*This description was taken from #2956.  I intend to replace it with a more in-depth description at a later time.*

"A successor to `magit-popup`".  Oh boy, I have been talking about that one forever.  `magit-popup` has a number of major issues, which make it desirable to start from scratch, which was the plan all along and isn't surprising considering that it was intended as a temporary solution right from the start.

The working title is **`transient.el`**, but that I will probably only use that for the core part, which provides an alternative to prefix arguments in the form of infix arguments (and be implemented using similar techniques).  I don't know yet what I will call the object oriented part that will be build on top of that, but it will be a lot like `hydra` and `magit-popup`, just more flexible and composable.

----

Features that were suggested for `magit-popup` that I might add to `transient`:

* #2941 Allow users to select [as opposed to add] arguments to be shown in a popup
* ~~#2801~~ [Think about consistency of the "Configure" action/sub-popup]
* #2773 Support optional positional arguments in popups
* #2700 Support manually editing Git commands generated by popups
* #2610 Set initial values of popup arguments based on Git variables

**Comment by nickmccurdy** [comment]
Have you looked into [hydra](https://github.com/abo-abo/hydra)? Do you think it would be a good option? This seems to be one of the most popular menu libraries.

**Comment by tarsius** [comment]
> Have you looked into hydra?

Yes, and I like it and use it for some personal non-magit things. But I don't think it is suitable for Magit.

While `hydra` has gained some support for setting variables, I believe, it has no support for passing arguments to commands. `hydra` essentially is a "command displatcher with visual feedback" while `magit-popup` and its successor additionally implement "infix arguments, which are a bit like prefix arguments but more visual".

It doesn't cover `hydra`, but the `magit-popup` manual does contain [a comparison](https://magit.vc/manual/magit-popup/Introduction.html) of some dispatch and/or argument mechanisms work.

**Comment by nickmccurdy** [comment]
Thanks. If I understand correctly using Hydra's universal argument support wouldn't be enough because we need default and user based configs, right? Would it make sense to propose custom argument support as a feature for Hydra or do you think it would be too difficult/messy?

**Comment by Blaisorblade** [comment]
FWIW: Spacemacs has a form of transient commands as well that might (or not) be worth looking into. Can't say whether the code itself is reusable though:
https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#transient-states

**Comment by bmag** [comment]
Actually Spacemacs' transient state is a wrapper around Hydra, and probably not worth looking into in this context.

(implementation: https://github.com/syl20bnr/spacemacs/blob/develop/core/core-transient-state.el; usage: see various calls to `spacemacs|define-transient-state` in the source)

**Comment by Blaisorblade** [comment]
Whoops, sorry for the noise then!

**Comment by vermiculus** [comment]
As discussed on Gitter, it would be super neat for the user to be able to select at which level git variables are set (local, global, etc.).

Would be very useful for vermiculus/magithub#287 as well as general git variables like `user.{name,email}`.

**Comment by phil-s** [comment]
It sounds like this issue is about done :)

Nice work!

Per https://github.com/magit/magit/issues/2956#issuecomment-276632556 is the plan still to get transient into GNU ELPA?  I'm sure this would be a really nice feature for other ELPA packages to be able to use as a dependency.

I look forward to exploring this.

**Comment by tarsius** [comment]
It has been a busy day... but 24 hours after the release I have finally found the time to come here.

It's done. :grinning: 

> is the plan still to get transient into GNU ELPA?

Yes, but I want it to mature a bit first. But thanks for the reminder; I'll have to ask contributors if they are willing to sign the copyright assignment.
