### ISSUE TITLE
Possible problem with magit-repolist-column-unpushed-to-upstream and magit-repolist-column-unpulled-from-upstream

### ISSUE THREAD

**Issue by thblt** [magit/magit#2960]
(1) **Expected behavior:** out of the box, `magit-list-repositories` should print a count of unpushed/unpulled commits to upstream.  If it doesn't, then `magit-repolist-column-upstream` should return nothing, and not the name of a remote branch.

 (2) **Observed behavior:** `magit-repolist-column-unpulled-from-upstream`, `magit-repolist-column-unpushed-to-upstream` (the "L<U" and "L>U" columns) behave as if there was no upstream remote configured:  they print nothing, not even zeros.  Yet, `magit-repolist-column-upstream` print the name of a remote.

**A solution I found** To fix this, I've modified the corresponding magit functions (`magit-repolist-column-unpulled-from-upstream`, `magit-repolist-column-unpushed-to-upstream`) to replace:

~~~
 (--when-let (magit-get-upstream-branch nil t)
~~~

with 

~~~
 (--when-let (magit-get-upstream-branch)
~~~

I'm not sure if this is Magit issue, maybe it's just something broken with my repositories configuration.  Yet it's a weird behavior, since `magit-repolist-column-upstream` behaves inconsistently with the unpulled-from/unpushed-to functions.

Please tell me if you need more information.  Apologies in advance if the error is mine: in this case feel free to close this immediately.

**Comment by kyleam** [comment]
Thanks.  I can reproduce it and will push a fix soon.

**Comment by tarsius** [comment]
I haven't looked into this yet, but if the upstream is configured but does not actually exist, then it is intentional that a space is displayed instead of a zero. So please don't fix that.

**Comment by kyleam** [comment]
I'm not changing the behavior when upstream doesn't exist. The current functions always return nil because they pass nil  to the branch argument of magit-get-upstream.

**Comment by kyleam** [comment]
@tarsius I've pushed the change to the km/fix-repolist-counts branch.

**Comment by tarsius** [comment]
I think it would be better to stop using `cl-defun`: https://github.com/magit/magit/compare/no-cl-defun?expand=1.

**Comment by kyleam** [comment]
That's fine.  I was working under the assumption that you preferred it.
