### ISSUE TITLE
corrupted minibuffer-history

### ISSUE THREAD

**Issue by littlehome-eugene** [magit/magit#2964]
I use savehist to store various stuff including M-x command line histories.

The `savehist` mode uses a file ~/.emacs.d/history to store them.

When I open multiple `emacs -nw`, sometimes (not always) emacs fails to parse the history file.

Offending line looks like 

(setq minibuffer-history '("/home/eugenekim/.emacs.d/init.el" "Enabled" #("stash" 0 5 (face magit-hash magit-section [cl-struct-magit-section stash "stash@{9}" #<marker (moves after insertion) at 918 in *magit: zibann> nil #<marker at 962 in *magit: zibann> nil nil nil n\
il nil nil [cl-struct-magit-section stashes "refs/stash" #<marker (moves after insertion) at 602 in *magit: zibann> #<marker at 615 in *magit: zibann> #<marker at 1129 in *magit: zibann> nil nil nil nil nil nil [cl-struct-magit-section status nil #<marker (moves after in\
sertion) at 1 in *magit: zibann> nil #<marker at 1129 in *magit: zibann> nil nil nil nil nil nil nil ([cl-struct-magit-section branch "feature/review-tag" #<marker (moves after insertion) at 1 in *magit: zibann> #<marker at 47 in *magit: zibann> #<marker at 125 in *magit\
: zibann> nil nil nil nil nil nil #7 ([cl-struct-magit-section branch #("origin/feature/review-tag" 0 25 (face magit-branch-remote)) #<marker (moves after insertion) at 47 in *magit: zibann> nil #<marker at 100 in *magit: zibann> nil nil nil nil nil nil #9 nil] [cl-struc\
t-magit-section tag "saleor" #<marker (moves after insertion) at 100 in *magit: zibann> nil #<marker at 124 in *magit: zibann> nil nil nil nil nil nil #9 nil])] [cl-struct-magit-section unstaged nil #<marker (moves after insertion) at 125 in *magit: zibann> #<marker at 1\
46 in *magit: zibann> #<marker at 602 in *magit: zibann> nil nil nil nil nil nil #7 ([cl-struct-magit-section file "ios/littlehome/Externals/CTAssetsPickerController" #<marker (moves after insertion) at 146 in *magit: zibann> #<marker at 207 in *magit: zibann> #<marker a\
t 339 in *magit: zibann> t nil nil nil "diff --git ios/littlehome/Externals/CTAssetsPickerController ios/littlehome/Externals/CTAssetsPickerController
)

That might mean magit is the problem. (might not)

I've asked the question in emacs stack exchange, other people seem to have same problem. 
(at least our teammates with similar setup has the same problems) 
http://emacs.stackexchange.com/questions/28794/emacs-history-invalid-read-syntax

It is very hard to pinpoint or find a way to reproduce it :(

magit 20161219.1449, Git 2.7.4, Emacs 25.1.2, gnu/linux

**Comment by tarsius** [comment]
> That might mean magit is the problem. (might not)

As I said on that issue, I don't think Magit is to blame here.

Never-the-less I have now invested quite some time writing everything I know on the subject down and posting it as an answer to your SE question.
