### ISSUE TITLE
show stash, kill stash, show stash does not update displayed stash

### ISSUE THREAD

**Issue by oscarfv** [magit/magit#2966]
Magit 2.10.0-28-g5b45742, Git 2.9.3, Emacs 26.0.50.1, gnu/linux

(The problem exists since Magit 2.9, at least.)

emacs -Q, load Magit

Stash some change, stash some other change. You have 2 stashes. In the magit status buffer, put the point on `stash@{0}` and press `Space` to show the diff on a window. Don't delete that window. On the magit status buffer, kill `stash@{0}`. Now `stash@{1}` becomes `stash@{0}`. Press `Space` on `stash@{0}` to show its contents. The window is not updated, the contents of the previous stash (the one we killed) remain.

Something similar happens if you create a new stash (`stash@{0}`) and display it, then create another stash and try to display it: the previous one (which is now `stash@{1}`) is still shown.

**Comment by phil-s** [comment]
Yes, I recall seeing this as well. I presume Magit knows that the commit for `stash@{0}` is already displayed, but is unaware that the name `stash@{0}` now references an entirely different stash to the one it has displayed.

**Comment by tarsius** [comment]
I've pushed a fix to https://github.com/magit/magit/compare/fix-2966?expand=1. This also takes care of a similar bug for branches. It doesn't do the same for diffs yet, and because taking care of that will probably involve renaming the variable added here, I have not yet merged this into `master`.
