### ISSUE TITLE
magit-branch-and-checkout: put START branch on kill ring

### ISSUE THREAD

**Issue by offby1** [magit/magit#2969]
This will require a bit of explanation ...

... I often type `b c` to create a new branch, and about half the time, I misread the prompt that says `Create and checkout branch starting at (default whatever-is-currently-checked-out):`.  Instead of simply hitting `RET`, which is what I _should_ do, I type the name of the branch I want to create.  Naturally, this fails, because no such branch exists.

I then slap myself upside the haid, and start over.  This time, I press `RET` where I should.  But now, when it prompts me `Branch name:`, I HAVE TO TYPE THE NEW BRANCH NAME ALL OVER AGAIN!  The horror!  

I always wish I could just type `C-y` and get back the name of my new branch.

**Comment by kyleam** [comment]
Would setting magit-branch-read-upstream-first to fallback solve your
issue?

**Comment by offby1** [comment]
@kyleam That sure does solve it!  Thanks!
