### ISSUE TITLE
Document --autostash

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#2979]
Hi,

magit-version => 
Magit 20170128.745, Git 2.11.0, Emacs 26.0.50.5, gnu/linux (i.e. current Melpa version)

When I'm interactively rebasing and running into conflicts, I'm getting an "autostash".  If it is not an accident that this autostash is visible to the user (I guess it isn't) - shouldn't we document when such autostashes are created, what they contain, and how they can be used in a typical scenario, and when they can be safely deleted?

Thanks in advance.

**Comment by tarsius** [comment]
Done.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> Done.

Looks good to me - thanks!
