### ISSUE TITLE
Use `git replace` to locally "merge" wip-refs

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2984]
[From the manual](https://magit.vc/manual/magit/Wip-Modes.html):

```
   Creating a commit and then making a change causes the wip refs to be
recreated to fork from the new commit.  But the old commits on the wip
refs are not lost.  They are still available from the reflog.  To make
it easier to see when the fork point of a wip ref was changed, an
additional commit with the message "restart autosaving" is created on it
(‘xxO’ commits below are such boundary commits).

   Starting with

           BI0---BI1    refs/wip/index/refs/heads/master
          /
     A---B              refs/heads/master
          \
           BW0---BW1    refs/wip/wtree/refs/heads/master

   and committing the staged changes and editing and saving a file would
result in

           BI0---BI1        refs/wip/index/refs/heads/master
          /
     A---B---C              refs/heads/master
          \   \
           \   CW0---CW1    refs/wip/wtree/refs/heads/master
            \
             BW0---BW1      refs/wip/wtree/refs/heads/master@{2}
```

I think that *sometimes* it would be more useful if the history *looked* like this instead:

```
           ...
          /
     A---B---------------C              refs/heads/master
          \             / \
           \           /   CW0---CW1    refs/wip/wtree/refs/heads/master
            \         /
             BW0---BW1                  refs/wip/wtree/refs/heads/master@{2}
```

`BW{N}` are automatically created wip revisions, you don't want them to be part of the actual history. But while retracing your last steps at least I would occasionally find it useful to have history like above. 

- This would make disaster recovery somewhat easier.

- Also, while most of the commits on the wip refs are created automatically, it is also possible to explicitly create a commit using the command `magit-wip-commit` and providing a short summary.

  This can be used to create snapshots, i.e. once the feature you are working on functions properly (but the code is a mess), and you are about to reorganize the code (which may cause breakage). Now would be a good time to create a snapshot.

  I usually do so by creating a wip commit on the real branch. If the "side-history" in the wip refs were "merged" as above, then I would prefer that. One major benefit of that would be that the side-history would remain easily accessible after making the "final commit".

This can be achieved using `git replace`. There should be a Magit command to quickly toggle the existence of the necessary replacement references. And the replacement refs have to be automatically updated when creating real commits.

**Comment by hedning** [comment]
There might be another way of achieving this while leaving regular commits untouched.

When committing, create a new save commit which points to the commit just created and the last wip commit. So something like this:

![image](https://user-images.githubusercontent.com/71978/33884737-c91befc0-df38-11e7-8ab6-11c88de99918.png)

Where the circles are regular commits and the squares are wip commits. The orange ones being the merges created after creating a regular commit (they would in effect take the place of the autosave wips, being the state of the working tree when the commit took place).

I think this could be a nice way of doing wip commits (if I haven't overlooked something of course :). Making the wip graph a superset of the commit graph means we can have a full connected save history while leaving the commit graph untouched.

Hope that makes sense (love magit btw) :)

**Comment by tarsius** [comment]
I now think it is better to create actual merge commits as @hedning suggested instead of using replace objects in `refs/replace`.

* git-replace(1) mentions some known bugs and suggests that there probably are more.
* Using replacement objects may interfere with other features that might start using it in the future.
* `--no-replace-objects` allows disabling the use of replacement objects, but there are no namespaces -- we cannot use our own replacement objects without messing with the replacement objects created by something else.

Another difference is the *direction* of the merges (fake or not). I am currently experimenting with both approaches. (Drop the last commit on #3534 to change the direction).

The direction I originally suggested has the benefit that it mirrors how feature branches relate to `master`. Such branches should be merged into `master`, which should never be merged into a feature branch. My original suggestion was that we do the equivalent here by merging the wipref into the actual branch. But it seems that results in messier graphs and might thus be less useful than merging in the "wrong" direction.

If you would like to experiment too, I suggest you use `git update-ref -d refs/wip/index/refs/head/master` etc. and comment out `magit-wip-commit-index` in `magit-wip-commit` before doing so.

**Comment by tarsius** [comment]
I have merged the branch. The new feature isn't enabled by default yet. The branch is being merged into the wip ref.

**Comment by kyleam** [comment]
I just got around to giving this a try.  I think it's really nice.

FWIW I prefer the current merge direction (wipref as the first parent).
