### ISSUE TITLE
magit is requiring emacs-24.4 and using pcase-dolist.

### ISSUE THREAD

**Issue by thierryvolpiatto** [magit/magit#2987]
This is in magit-worktree.el, I don't use this feature yet but may use it with emacs-24.5, a simple cl-loop can do the same, i.e `(cl-loop for (foo . bar) in list do [...]`.

I have installed this time magit from git (last master).

Thanks.

**Comment by phil-s** [comment]
`pcase.el` in 24.4 provides `pcase-dolist`

**Comment by thierryvolpiatto** [comment]
phil-s <notifications@github.com> writes:

> pcase.el in 24.4 provides pcase-dolist

Ah yes, you are right, it is not autoloaded though, ince the warning when
compiling.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Still have warning when compiling:

In magit-insert-worktrees:
magit-worktree.el:120:59:Warning: `(\` ((\, head) \, path))' is a malformed
    function
magit-worktree.el:122:45:Warning: reference to free variable `path'
magit-worktree.el:123:23:Warning: reference to free variable `head'

**Comment by tarsius** [comment]
Status: installing v24.4 again...

**Comment by phil-s** [comment]
I get no such warnings when installing magit-20170226.1208 from MELPA using emacs-24.4.

**Comment by thierryvolpiatto** [comment]
phil-s <notifications@github.com> writes:

> I get no such warnings when installing magit-20170226.1208 from MELPA using emacs-24.4.

I have the warning when compiling from git with make.
IMHO it is much simpler using a destructuring cl-loop instead of
pcase-dolist here (i.e the additional features of pcase-dolist are not
needed here).

-- 
Thierry

**Comment by phil-s** [comment]
> I have the warning when compiling from git with make.

I can't replicate it that way either.

* Empty config
* Cloned magit repository
* Installed dash, async, with-editor from MELPA (and added symlinks for magit to find them)
* env PATH=/path/to/emacs-24.4/bin:$PATH make lisp

No warnings.

magit-worktree.elc says:

;;; Compiled
;;; in Emacs version 24.4.2
;;; with all optimizations.

**Comment by thierryvolpiatto** [comment]
phil-s <notifications@github.com> writes:

>     I have the warning when compiling from git with make.
>    
> I can't replicate it that way either.

Ah! I can reproduce now only in the magit process buffer when running
make from `magit-shell-command`.

But yes it is working fine from a terminal even eshell.

So perhaps this can be closed, sorry for the noise.

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> phil-s <notifications@github.com> writes:
>
>>     I have the warning when compiling from git with make.
>>    
>> I can't replicate it that way either.
>
> Ah! I can reproduce now only in the magit process buffer when running
> make from `magit-shell-command`.
>
> But yes it is working fine from a terminal even eshell.

Reproductible also when compiling from emacs shell (M-x shell).

-- 
Thierry

**Comment by npostavs** [comment]
> Reproductible also when compiling from emacs shell (M-x shell).

I can't reproduce it here. Perhaps you are setting some environment variable in your .bashrc?

**Comment by thierryvolpiatto** [comment]
Noam Postavsky <notifications@github.com> writes:

>     Reproductible also when compiling from emacs shell (M-x shell).
>    
> I can't reproduce it here. Perhaps you are setting some environment variable in your .bashrc?

No, nothing that could affect this.
But it is reproductible only with 24.5, not emacs-26, didn't try other
versions though.

-- 
Thierry

**Comment by npostavs** [comment]
I was trying with 24.4.

**Comment by tarsius** [comment]
I did `make clean lisp` with `24.4`, `24.5`, `25.1`, `25.2-rc2`, and `26.0.50` and got no such warning. (The only warning I got was `26.0.50` complaining about `string-as-multibyte` being obsolete.)
