### ISSUE TITLE
Renaming can't be undone if the directory doesn't exist

### ISSUE THREAD

**Issue by neongreen** [magit/magit#2998]
Steps:

* Create `src/A.txt` and commit.
* Rename to `lib/A.txt` and stage the renaming with Magit.
* Delete the `src` directory.
* Try to undo the renaming with Magit.

Since `src` was deleted, Git won't be able to do `mv lib/A.txt src/A.txt` and will fail with an uninformative error message:

```
128 git … mv lib/A.txt src/A.txt
fatal: renaming 'lib/A.txt' failed: No such file or directory
```

I'm using Magit 20170119.1803, Git 2.11.0, Emacs 25.1.1, gnu/linux.

**Comment by kyleam** [comment]
Thanks for the report.
