### ISSUE TITLE
Onward to the next major version

### ISSUE THREAD

**Issue by tarsius** [magit/magit#3000]
Over the last few weeks I have opened [many new issues](https://github.com/magit/magit/issues/created_by/tarsius) outlining new features I intend to implement and/or describing limitations of the current implementation and my plans to address those.

Some of these issues are still a bit vague in their present form. For the most part each these issues "translates" a one-line entry in my `magit-todo.org` file to something more suitable for others to think about and comment on. I intend to improve these issues over time (by editing the original post in many cases).

Even though development has slowed over the last few months I am not out of ideas at all. I was just busy outlining my future work!

**Comment by phil-s** [comment]
I'm impressed by the sheer quantity of feature request issues you've created for yourself, when you could well be resting on your laurels.

Magit clearly isn't in danger of dropping off of anyone's list of favourite packages...

**Comment by tarsius** [comment]
I've now also categorized my future work in a "[project](https://github.com/magit/magit/projects/1)".

**Comment by DamienCassou** [comment]
Should this issue be closed?

**Comment by tarsius** [comment]
As much as I like closing issues - this isn't quite done yet. :stuck_out_tongue_winking_eye:

I also like shiny things and round numbers, so guess what - #3000 stays open until `v3.0.0` is released. I might even tag it as `v3.0.0.0`, just because.

**Comment by tarsius** [comment]
Tadaaaaaaaaaaaaaaaaa! <sub>dada<sub> dada</sub></sub>

I've finally [released](https://emacsair.me/2021/05/25/magit-3.0) version 3.0.0. [Two months ago.]
