### ISSUE TITLE
The rebase sequence does not handle exec actions

### ISSUE THREAD

**Issue by snogge** [magit/magit#3002]
I'm using the `exec` command in rebase to execute `make test` for each
commit.  If the `make` command fails, the rebase stops at that point
and lets me fix the commit before proceeding.  However, magit (more
specifically `magit-insert-rebase-sequence`) can't handle `exec` steps
in the rebase. 

I see a `(wrong-type-argument char-or-string-p nil)` in
`magit-sequence-insert-commit`.

The problem is that `magit-rebase-insert-merge-sequence` expects each
`line` to either be a comment or match _action hash commitmsg_ while
an exec line looks like _exec command_.  The first word of _command_
is then passed as the hash to `magit-sequence-insert-commit` and
eventually `magit-sequence-insert-commit` will try to insert nil when
`magit-format-rev-summary` receives _make_ as its input.

Note that the error is only triggered when there are *pending* exec
operations in the rebase.  A single failing command is not enough to
trigger the error. 

Also, the command has to be at least two words.  `exec false` does not
trigger the bug, but `exec false ignore` does.  This is because `exec
false` does not match the not-a-comment regex in
`magit-rebase-insert-merge-sequence` while `exec false ignore` does.

To reproduce, do an interactive rebase over a couple of commits, insert
at least two `exec false ignore` and start the rebase.  I've verified
this using the `magit-emacs-Q-command` command.

Magit 20170221.1917, Git 2.1.4, Emacs 24.4.1, gnu/linux

[magit-exec-backtrace.txt](https://github.com/magit/magit/files/798877/magit-exec-backtrace.txt)

**Comment by tarsius** [comment]
Thanks for the report!

**Comment by kyleam** [comment]
Are we ok removing the exec lines (which is already done for the
one-word exec case)?  If so, this should work:

```diff
diff --git a/lisp/magit-sequence.el b/lisp/magit-sequence.el
index 7e5dbd98..ff11caa8 100644
--- a/lisp/magit-sequence.el
+++ b/lisp/magit-sequence.el
@@ -573,7 +573,8 @@ (defun magit-rebase-insert-merge-sequence (onto)
                                  (or (magit-get "core.commentChar") "#")))
                         line)
       (magit-bind-match-strings (action hash) line
-        (magit-sequence-insert-commit action hash 'magit-sequence-pick))))
+        (unless (equal action "exec")
+          (magit-sequence-insert-commit action hash 'magit-sequence-pick)))))
   (magit-sequence-insert-sequence
    (magit-file-line (magit-git-dir "rebase-merge/stopped-sha"))
    onto
```

**Comment by snogge** [comment]
I would prefer to see the exec lines, but removing them is better than an error. Maybe a user option?

Using the `--exec` option to `git rebase --interactive` will give a potentially very long rebase sequence so there is room for UI improvements here, maybe folding exec lines into the preceding commit or unifying repeating exec commands somehow.  That is all future work of course. 

Another improvement would be to see the result - including output - of already executed exec commands.

**Comment by tarsius** [comment]
> Are we ok removing the exec lines (which is already done for the one-word exec case)?

We should do that now, and then take the time to sort out if/how we want to present those entries in a second step.
