### ISSUE TITLE
magit-edit-dwim fails with an error

### ISSUE THREAD

**Issue by dredozubov** [magit/magit#3006]
When I have a point on any unstaged file during the rebase I expect it to show the diff in ediff, instead i see an error message in the minibuffer: `Wrong type argument: stringp, nil`. `*messages*` shows `file-in-directory-p: Wrong type argument: stringp, nil`. I've used that feature extensively before and it seems like a recent(i don't do elisp updated too often, so recent can mean a month) breakage.

Magit 20170221.1917, Git 2.7.3, Emacs 25.1.1, darwin

I tried launching `make emacs-Q`, but it doesn't really work for me, it open an emacs window which is totally unresponsive to the key combinations(maybe terminal multiplexor is to blame here).

Please tell me if i can assist with debugging this issue.

**Comment by npostavs** [comment]
If you set `debug-on-error` can you get a backtrace?

> I tried launching `make emacs-Q`, but it doesn't really work for me, it open an emacs window which is totally unresponsive to the key combinations(maybe terminal multiplexor is to blame here).

Does the command given by `M-x magit-emacs-Q-command` work? I think on macOS the way to start Emacs from the command line is a bit different though. I've seen people suggesting `open -a /path/to/emacs...`

**Comment by dredozubov** [comment]
> If you set debug-on-error can you get a backtrace?

No, but i've discovered that https://github.com/commercialhaskell/intero was messing with it somehow, disabling intero returns magit behaviour back to normal. Not a magit issue, it seems, closing.

> I think on macOS the way to start Emacs from the command line is a bit different though. I've seen people suggesting open -a /path/to/emacs...

good to know, i'll that next time, thanks!
