### ISSUE TITLE
magit-ediff-dwim key should be "e e", not "e"

### ISSUE THREAD

**Issue by jeffersoncarpenter** [magit/magit#3010]
I was just prompted for "y" or "n" but typed "yes", resulting in magit-ediff-dwim running.  This opened some frames, which I then had to close.  I used to press "e" accidentally all the time, but not so much any more.  Please remove the "e" key binding from the official distribution.  If you would like "e" as magit-ediff-dwim, you should add it to the keymap in your .emacs file.

**Comment by kyleam** [comment]
From your response in PR #2763, it's clear that you feel strongly that
`magit-ediff-dwim` shouldn't be bound to "e", but I'm having a hard
time seeing that way.

The worst case scenario seems to be

 * Someone unintentionally loads ediff and is irritated that they need
   to close it and rearrange their windows.

 * It happens one or two more times, and they think "what a bad
   default binding" and then unset it in their config.

**Comment by tarsius** [comment]
Also Magit can now be configured to ask `yes-or-no-p` questions instead of `y-or-n-p`. I am not sure though if `magit-slow-confirm` covers each and every such question.
