### ISSUE TITLE
Verifying tag signatures

### ISSUE THREAD

**Issue by nidrissi** [magit/magit#3015]
Magit provides some support for verifying commit signatures (they are shown either in green or red in the log if the option `-S` is provided). However no such feature exists for tags. There is a tool [`git-verify-tag`](https://git-scm.com/docs/git-verify-tag) whose output looks like this:

```
$ git verify-tag v0
gpg: Signature made 03/02/17 16:38:10 Paris, Madrid
gpg:                using RSA key 8DD4D303141F56B7
gpg: Can't check signature: No public key
```

Alternatively, the `-v` option of `git-tag` provides an output similar to this one. Could it be possible to integrate that into Magit?

**Comment by tarsius** [comment]
Yes, that would be possible ;-)

In what places would you expect the tags to be verified?

**Comment by nidrissi** [comment]
I think the logs (show the tag name in red/green like the commits perhaps) and the `show-refs` screen (the `y` key) would be the best places.

**Comment by fice-t** [comment]
There's a couple issues I see:

- There's already a face for tags to use, so how should they be coloured differently? Should there be new `magit-tag-signature-*` faces to match all of the `magit-signature-*` faces? If so, then should the log buffer disambiguate tags from commit messages? e.g., `git log` puts all tags inside `(tag: ...)`.

- There doesn't appear to be a tag analogue for the `%G?` format, which helps with determining what face to use. So between `git tag` and `git verify-tag`:

  - I don't think `git-tag` will allow for an easy equivalent of "%G?". Also, maybe it's just me, but I can't seem to get the `--format` argument of `git tag -v` to work. Can anyone else get it to work?
  - `git-verify-commit` doesn't have a format argument, so if that's to be used, then we'd have to parse its `--raw` output ourselves. I guess this is what Git does itself, so while a bit annoying it's probably the best approach.

**Comment by tarsius** [comment]
> Also, maybe it's just me, but I can't seem to get the `--format` argument of `git tag -v` to work.

It expects a format containing "field names" like `%(refname)` as described in `git-for-each-ref(1)`, not "placeholders" like `%H` as described in `git-log(1)`. There does not appear to be a "field name" equivalent to the `%G?` "placeholder".

We should parse the output of `git verify-tag`. Unfortunately I was unable to find a reliable list of all the things this command might tell us. Any help locating or creating such a list would be appreciated. This is what I have got so far.

```
|   | git-log(1) description                | found in gnupg's po/en@quod.po |
|---+---------------------------------------+--------------------------------|
| G | good signature                        | Good signature from \"%s\"     |
| B | bad signature                         | BAD signature from \"%s\"      |
| U | good signature with unknown identity  |                                |
| X | good signature that has expired       | Expired signature from \"%s\"  |
| Y | good signature made by an expired key |                                |
| R | good signature made by a revoked key  |                                |
| E | signaure that cannot be checked       |                                |
| N | no signature                          | no signature found             |
```

However simply completing the last column from the contents of `po/en@quod.po` is not good enough. The best would be if someone could generate a tag for each of the possible states and provide that repository along with the necessary keys and keychains to reproduce a list of all possible answers. I am sure someone has put that on the internet somewhere, but I cannot find it.

If nobody volunteers to do that work then I will give up on parsing the output and just show the raw output in the `magit-revision-mode` buffer. Alternatively a volunteer could ask the Git developers to implement the equivalent of `git log --format="%G?"` for `git verify-tag`.

**Comment by tarsius** [comment]
> If nobody volunteers to do that work then I will give up on parsing the output and just show the raw output in the `magit-revision-mode` buffer.

I have done that.

> Alternatively a volunteer could ask the Git developers to implement the equivalent of `git log --format="%G?"` for `git verify-tag`.

That's actually the best way forward, and until that exists in Git, I don't want to hack around the absence of this feature. If someone else wants to do it. *Please* go a head, but I won't do it. (I added the `wonadd` label, which means I will revisit this eventually, but unless I run out of other things to do, it is unlikely that I will implement this.
