### ISSUE TITLE
Continue/Abort whatever magit is doing

### ISSUE THREAD

**Issue by DamienCassou** [magit/magit#3017]
While using Magit, I regularly face conflicts that I have to solve. It usually takes enough time for me to forget what I was doing (either a merge, or a cherry-pick or a rebase). At the end of the conflict solving process, I'm not sure if I should open the merge popup or the cherry-pick popup or the rebase popup to continue or abort the process. It would be great I could just tell "Continue" or "Abort" to Magit.

**Comment by tarsius** [comment]
I'll probably add something like `magit-dwim-abort`, but note that you should be able to tell what you are doing because there should in each case be a in-progress section that tells you what it is.
