### ISSUE TITLE
Consider adding imenu support

### ISSUE THREAD

**Issue by DamienCassou** [magit/magit#3022]
It would be nice to be able to use imenu in magit buffers:

- in magit-log, imenu could let the user go to a commit rapidly by hash or description
- in magit-rev, imenu could let the user go to a file rapidly by filename
- in magit status, imenu could let the user go to a section rapidly

**Comment by tarsius** [comment]
That would be nice, and implementing it might actually help me use imenu more (in other contexts). But it's not a high priority.

**Comment by tarsius** [comment]
Is there anything else you want to add, or can we close this?

**Comment by DamienCassou** [comment]
We could add it to `magit-rebase-mode` too, I forgot it. What do you think?

**Comment by tarsius** [comment]
Feel free to do that if/when you have time to do it. Eventually someone will ask for it, so why not add it sooner rather than later.

**Comment by kyleam** [comment]
> We could add it to git-rebase-mode too

A few other candidates:

  * `magit-refs-mode`

  * `magit-diff-mode` and `magit-stash-mode`

    I think it'd make sense to define a single set of imenu functions
    for diff/revision/stash buffers, setting these functions in
    `magit-diff-mode` rather than `magit-revision-mode`.
    `magit-revision-mode` and `magit-stash-mode` would then inherit
    these from `magit-diff-mode`.

  * `magit-reflog-mode` and `magit-stashes-mode`

     Right now, these inherit the log's imenu functions, which don't
     return useful results.  If the regexp of the log's imenu
     functions aren't easily extended to work with these, I think
     these mdoes should have their own imenu functions or should at
     least set the imenu functions to nil.
