### ISSUE TITLE
Avoid loading git-commit.el when enabling global-git-commit-mode

### ISSUE THREAD

**Issue by Stebalien** [magit/magit#3027]
I'm currently calling `(global-git-commit-mode t)` on startup which, in turn, loads `git-commit.el`. All-in-all this takes about 2 seconds (1/3 of my startup time). It would be great if `global-git-commit-mode` and related variables/functions (`git-commit-filename-regexp` and `git-commit-setup-check-buffer`) could be moved to a separate file that can be autoloaded independently of `git-commit.el`. This way, I can enable `global-git-commit-mode` at startup but only load `git-commit.el` when needed.

**Comment by tarsius** [comment]
That shouldn't take so long. Loading `git-commit.el` does not cause that many other libraries to be loaded. Also note that you only need to enable `global-git-commit-mode` if you commit from the command line.

**Comment by tarsius** [comment]
Hm, it takes 0.7s here too. That's certainly quite long, will have to investigate.

But splitting the library up isn't an approach I want to take.

**Comment by tarsius** [comment]
I use this init file to figure out where the bottlenecks are:

```lisp
;; That's the package manager I use, you would use `package.el' here.
(progn ;    `borg'
  (add-to-list 'load-path (expand-file-name "lib/borg" user-emacs-directory))
  (require  'borg)
  (borg-initialize))

(progn ;    `use-package'
  (require  'use-package)
  (setq use-package-minimum-reported-time 0.01)
  (setq use-package-verbose t))

;; `git-commit' dependencies:
(use-package dash)
(use-package log-edit)
(use-package magit-utils)
(use-package ring)
(use-package server)
(use-package tramp)    ; `with-editor' dependency
(use-package tramp-sh) ; `with-editor' dependency
(use-package with-editor)

(use-package git-commit)
```

giving

```
Initializing drones...done (55 drones in 0.070s)
Loading package dash...done (0.018s)
Loading package log-edit...done (0.232s)
Loading package magit-utils...done
Loading package ring...done
Loading package server...done (0.019s)
Loading package tramp...done (0.318s)
Loading package tramp-sh...done (0.041s)
Loading package with-editor...done (0.012s)
Loading package git-commit...done
For information about GNU Emacs and the GNU system, type C-h C-a.
```

If loading `tramp` takes much longer for you, then this might be the cause: https://magit.vc/manual/magit/Emacs-245-hangs-when-loading-Magit.html. (What Emacs version are you using? State that upfront the next time.)

I'll look into only requiring `tramp` at compile time and when actually used.

**Comment by Stebalien** [comment]
> What Emacs version are you using? State that upfront the next time.

Sorry about that, I thought this was going to be a feature request.

I'm using emacs 26.0.50 (recent git commit).

---

It turns out the problem is `log-edit`. It pulls in `message` (from
gnus) which takes over 2 seconds.

**Comment by tarsius** [comment]
Please try with this init file too, and report the results here.

**Comment by Stebalien** [comment]
Apparently, github treats triple dashes in email replies as signature separators. Here's the second half of that comment:

> I turns out the problem is `log-edit`. It pulls in `message` (from gnus) which takes over 2 seconds.

On further investigation, this is my fault (well, at least not magit's fault). I was loading notmuch when loading the `message` package to set the mail user agent. Unfortunately, that takes quite a while. I'll talk to the notmuch people about load times...

Sorry for the noise.
