### ISSUE TITLE
Parentheses in a branch name, breaks that commits log entry

### ISSUE THREAD

**Issue by duianto** [magit/magit#3028]
#### What behavior you expected
The magit log shouldn't look any different when there are parentheses in a branch name, or if one should avoid using parentheses, then there probably should be a warning if one tries to use them.

#### What behavior you observed
The log entry looks broken, for a commit with a branch name that has parentheses in it.
The hash, author and date columns are empty. Everything is written in the middle column that usually just shows the branch names, remote branch names and the commits subject line. 

The middle column also shows `(refs/heads/` before the branch name. And there's an empty commit line below it. 

Here's a screenshot:

![emacs_2017-03-16_12-43-17](https://cloud.githubusercontent.com/assets/13420573/23995162/afed8e66-0a48-11e7-943f-da16349ed2f6.png)

When the parentheses are removed from the branch name, then the log entry looks normal again:

![emacs_2017-03-16_13-02-42](https://cloud.githubusercontent.com/assets/13420573/23995224/f3395bd2-0a48-11e7-88aa-4f4279d1fe94.png)

#### How we can reproduce the issue.
1. Start Emacs (with magit installed).
2. Open a repository
3. Rename an existing branch or create a new branch with parentheses in the name.
4. Open the magit-log buffer.

#### System info
Magit 20170312.616, Git 2.11.1.windows.1, Emacs 25.1.1, windows-nt

**Comment by tarsius** [comment]
The "\\(?:\\(?3:([^()]+)\\) \\)?" part of `magit-log-heading-re` is the problem.

**Comment by tarsius** [comment]
Thanks Kyle!
