### ISSUE TITLE
incorrect key binding in documentation for magit-rebase-subset

### ISSUE THREAD

**Issue by plumenator** [magit/magit#3031]
Magit 20170311.925, Git 2.11.0, Emacs 25.1.1, gnu/linux

At https://magit.vc/manual/magit/Rebasing.html, it's listed as `r o`. It should be `r s`.

**Comment by kyleam** [comment]
Thanks for spotting that!

**Comment by tarsius** [comment]
I'll upload the updated manual. I think it was a bit outdated even before this change.
