### ISSUE TITLE
feature request: rebase move selected commits up/down as a unit

### ISSUE THREAD

**Issue by ibrennan-handy** [magit/magit#3036]
While performing an interactive rebase, *git-rebase-move-line-{up,down}* can be used to reorder commits, one commit at a time. I'd like to be able to select a block of adjacent commits and move them up/down as a unit.

Outside of magit, I would select the commits I want to move, cut them and paste them where desired. In order to do this in magit, I'd have to make the buffer writeable and adjust my keybindings to avoid inadvertently executing magit functions as I kill and yank (I also use evil and evil-magit, which might add to the complexity).

Ideally, I'd like to select several commits and run something like *git-rebase-move-line**s**-{up,down}* (plural).

**Comment by kyleam** [comment]
You should be able to do that by selecting a region.

**Comment by tarsius** [comment]
> Ideally, I'd like to select several commits and run something like git-rebase-move-lines-{up,down} (plural).

Even better, you can just select several commits and run git-rebase-move-lines-{up,down} (singular).
