### ISSUE TITLE
Show progress messages in magit-process buffer during fetch

### ISSUE THREAD

**Issue by markshep** [magit/magit#3042]
When doing a fetch using magit I'd like to be able to see how far it's got, but all I see in the ```*magit-process*``` buffer is the following:

```
run git … fetch origin
remote: Counting objects: 160, done.
remote: Compressing objects: 100% (78/78), done.
```

Then nothing else until the fetch completes.  I'm currently waiting for >700MiB to download, but have no idea how far it's got.  When I run ```git fetch``` from the command line I can see output like this:

```
Receiving objects:  20% (28/136), 1.34 MiB | 195.00 KiB/s
```

But magit hides this output.  Please could it not hide this output?

Thanks,
Mark

**Comment by tarsius** [comment]
This will be surprisingly hard to do. Eventually we will probably do it, but it will be a few months until I look into this.

**Comment by tarsius** [comment]
It's highly unlikely that I will implement anything like that anytime soon. To do this properly the code that deals with `git`'s output would have to be taught to act like a shell. The proper way of doing that probably would be use `comint`, but then all the code that inserts the output into sections would have to be replaced. Maybe it isn't even possible to "do sections on top of `comint`".

All in all this is way too much effort for too little gain.
