### ISSUE TITLE
magit-process-popup-time 0 doesn't always pop up process buffer

### ISSUE THREAD

**Issue by schellj** [magit/magit#3045]
**What behavior you expected**

When `magit-process-popup-time` is set to `0`, I would expect that any git command run for side-effects would result in the process buffer being popped up.

**What behavior you observed**

git commands such as `pull`, `checkout`, `add`, `commit`, `stash` or `reset` being cause their command and output to be inserted into the process buffer, but don't cause the process buffer to be popped up.  `push` is the only command that I've seen that does cause the process buffer to pop up, though I'm guessing there are others.

**How we can reproduce the issue.**

(1) Use customize to set `magit-process-popup-time` to `0`
(2) M-x magit-status
(3) Use Magit to pull, checkout, add, commit or reset
(4) Observe that the process buffer is not popped up

Reproduced using emacs with only Magit dependencies loaded.

**Magit version**

Magit 20170403.1234, Git 2.6.4, Emacs 25.0.50.3

**Comment by tarsius** [comment]
The problem is that the macro `magit-with-editor` binds `magit-process-popup-time` to `-1` and is used in places where we don't want that to happen. We'll have that that let-binding out of the macro and explicitly put it into the callers that actually need that.

**Comment by tarsius** [comment]
This could proof difficult to fix. I think we currently have a choice between having certain commands (a) never show the process buffer (b) show the process buffer, including in situations when that would hide a buffer that was just opened to let a user edit some text.

**Comment by schellj** [comment]
Understood.  It's not a huge deal, at least to me.  My motivation for wanting this to work as I expected was basically to try to keep up my knowledge of git commands rather than just letting Magit do everything for me.
