### ISSUE TITLE
Error when adding remote-less subdirectory repo as submodule

### ISSUE THREAD

**Issue by 501st-alpha1** [magit/magit#3047]
I have a submodule in a folder beginning with a `.` (in my case the folder name is `.issues`).  I hit <kbd>s</kbd> on the folder in the `magit-status` buffer, and I get the following error:

```
repo URL: '.issues/' must be absolute or begin with ./|../
```

When I view the process buffer, I notice that this is the command being run:

```
git ... submodule add --name issues .issues/
```

I verified that the following command works:

```
git submodule add --name issues ./.issues/
```

Output of `magit-version`:

```
Magit 20170403.1234, Git 2.1.4, Emacs 24.4.1, gnu/linux
```

**Comment by kyleam** [comment]
Hmm, I don't think that the subdirectory beginning with a period is
relevant.  The issue seems to be that there's no URL set for the
subdirectory repo.  In this case, `magit-stage-untracked` calls
`(magit-submodule-add URL PATH)` with nil for `URL`, leading to `PATH`
being taken as the url argument to `git submodule add`.  (nil's are
removed by `magit-process-git-arguments` before calling git.)

Can you provide more details on your setup?  Are you creating the repo
directly in the subdirectory with `git init` rather than cloning it
from somewhere else?  If so, is there a particular reason for doing it
this way?

Anyway,`git submodule add` does let you specify a relative path with
`./` or `../`, and it will tolerate a relative URL pointing to a
subdirectory.  So we should support it (e.g., with the patch below),
or at least give a meaningful error (catching that the URL is nil).

```diff
diff --git a/lisp/magit-apply.el b/lisp/magit-apply.el
index 81693d37..4b4671f3 100644
--- a/lisp/magit-apply.el
+++ b/lisp/magit-apply.el
@@ -281,7 +281,8 @@ (defun magit-stage-untracked (&optional intent)
         (magit-submodule-add
          (let ((default-directory
                  (file-name-as-directory (expand-file-name repo))))
-           (magit-get "remote" (or (magit-get-remote) "origin") "url"))
+           (or (magit-get "remote" (or (magit-get-remote) "origin") "url")
+               (concat (file-name-as-directory ".") repo)))
          repo
          (magit-submodule-read-name repo))))
     (magit-wip-commit-after-apply files " after stage")))

```

**Comment by 501st-alpha1** [comment]
Okay, that makes sense.  I was trying out [gi](https://github.com/dspinellis/gi) for Git-based issue management, and it creates a submodule to store the issue data in.  Since I was just testing it out locally, I hadn't added a remote for the submodule yet, so that's how I got the error.

**Comment by kyleam** [comment]
> I was trying out gi for Git-based issue management

Interesting.  Thanks for the link.  Perhaps I missed something, but
would it make sense to ignore the ".issues" subdirectory rather than
tracking it as a submodule?  That way each change in the issues repo
wouldn't result in unstaged rev change for the superproject pointer.

**Comment by tarsius** [comment]
Are you creating the repo directly in the subdirectory with `git init` rather than cloning it from somewhere else?  If so, is there a particular reason for doing it this way?

It's useful when creating something that didn't exist before. ;-)

> So we should support it (e.g., with the patch below)

Yes, please apply that.

**Comment by kyleam** [comment]
>> Are you creating the repo directly in the subdirectory with git
>> init rather than cloning it from somewhere else? If so, is there a
>> particular reason for doing it this way?

> It's useful when creating something that didn't exist before. ;-)

I'm not sure that many Magit users -- including you :) -- actually set
things up this way (i.e., `git init` *inside* a new subdirectory of
another project) considering that the issue hasn't been reported until
now.  Instead, my guess is that, when the new repo doesn't exist, it's
usually created in a directory that is *outside* of the superproject
and then added it with `git submodule add`.

**Comment by tarsius** [comment]
When I create a new Emacs package, I create a new repository inside `~/.emacs.d/lib/`. I did not run into this problem because before I add that repository as a submodule, I apparently always add a remote and push there.

**Comment by kyleam** [comment]
Thanks for the details.  That's making your work public quickly :)

**Comment by tarsius** [comment]
I didn't say that I push to a *public* repository ;-)

**Comment by 501st-alpha1** [comment]
Good point, I think that would make more sense.
