### ISSUE TITLE
`m e` doesn't preselect branch as `m m` does in `magit-merge-preview`

### ISSUE THREAD

**Issue by rgtk** [magit/magit#3050]
With commit ff4c52b31c814f0cc89f33d25fb9813bac21598e (reported in #3039), `m m` preselects currently previewed branch in `magit-merge-preview`. This doesn't seem to work for `m e` though.

**Comment by tarsius** [comment]
Okay, now it works for any command using `magit-read-other-branch-or-commit`.

**Comment by rgtk** [comment]
Thanks.
