### ISSUE TITLE
Support reverse blaming

### ISSUE THREAD

**Issue by xged** [magit/magit#3055]
> Walk history forward instead of backward. Instead of showing the revision in which a line appeared, this shows the last revision in which a line has existed.

Showing the revision which 'deleted' a line would be as useful.

**Comment by tarsius** [comment]
Yes, that should be possible. I'll have to think about how to best make this functionality available.

**Comment by tarsius** [comment]
I have added basic support in #3189 (please comment there) and intend to merge that this week.

> I'll have to think about how to best make this functionality available.

I have added it to both `magit-file-popup` and `magit-blame-popup`. The keybindings might still need some tweaking.
