### ISSUE TITLE
Support restricting diff/commit view to current file

### ISSUE THREAD

**Issue by bitti** [magit/magit#3056]
I like the default behaviour of `git-log-files` from the `git-emacs` package better than `magit-log-buffer-file`. If I press `d` to see the diff between two commits in the resulting list from `git-log-files` the diff is restricted to the file in question. In contrast if I press enter in the `magit-log-buffer-file` list, I get to see the whole commit, which is more often than not, not what I need.

The semantic of the diff in `git-log-files` is a little different since it calculates an actual diff between  two commits, whereas `magit-log-buffer-file` shows the actual commit. But git also supports to restrict the diff of a commit to certain files, so it should be easy to support that while keeping current semantic. One way this could work in the UI is to provide a toggle switch in the log view to specify if commit views opened from there should be restricted by file (since the log is already filtered by the file in question, it's clear in this context which file is meant).

I think this is the only feature left from `git-emacs` which I use regularly, so if magit would implement that I could simplify my configuration.

`git-log-files` also supports restricting the log and diff to multiple files, but the most common usecase for me is currently viewing the log and the commits of the current buffer, so that might not be considered part of this request.

**Comment by kyleam** [comment]
> I like the default behaviour of `git-log-files` from the `git-emacs`
> package better than `magit-log-buffer-file`. If I press `D` to see
> the diff between two commits in the resulting list from
> `git-log-files` the diff is restricted to the file in question. In
> contrast if I press enter in the `magit-log-buffer-file` list, I get
> to see the whole commit, which is more often than not, not what I
> need.

Yeah, `git log -p -- <files>` also restricts the diffs to just
`<files>`.  In general, I think wanting the log's file restriction to
be honored is reasonable and should probably be the default behavior.

> One way this could work in the UI is to provide a toggle switch in
> the log view to specify if commit views opened from there should be
> restricted by file (since the log is already filtered by the file in
> question, it's clear in this context which file is meant).

Hmm, I'm not sure if a toggle is needed.  If the repo has an active
diff buffer, we already use the diff's file restriction.  If the
`magit-show-commit` call is from a log buffer, we could just give
precedence to the log's file restriction over the diff's.  Changes
along these lines are on the [km/show-commit-files] branch.

If some people do prefer the diff's restriction in this situation, we
could allow the behavior to be controlled with an option.

[km/show-commit-files]: https://github.com/magit/magit/compare/km/show-commit-files

> `git-log-files` also supports restricting the log and diff to
> multiple files, but the most common usecase for me is currently
> viewing the log and the commits of the current buffer, so that might
> not be considered part of this request.

The `=f` option in the log and diff popups supports multiple files.

**Comment by bitti** [comment]
Sure I also would prefer it as default. The toggle option was only an idea to provide a fallback for people who rely on the old behaviour (every change breaks someones workflow...). But it might be also implemented in the commit view instead (to toggle between a full or restricted diff in case someone wants to see the "whole" commit)

**Comment by kyleam** [comment]
> The toggle option was only an idea to provide a fallback for people [...]

Right, I'm just saying I think the most we'd need would be a standard
Emacs option, but your description seemed a bit more involved ("toggle
switch in the log view").

> It it might be also implemented in the commit view instead

You can already do that with `magit-diff-refresh-popup`.

**Comment by danrharms** [comment]
Is this an acceptable place to mention how nice this behavior would be in relation to magic-log-buffer-file?  Restricting the diffs to only the file in question. Especially since this command originates from a specific file. 

This is how gitk worked, and I miss it a lot. Right now showing diffs from all files obscures that of the file in question, and makes it harder to follow changes in just that file. This seems counter to the intent of the command.

**Comment by kyleam** [comment]
@danrharms Right, `magit-log-buffer-file` is probably the most common
way for most users to generate a Magit log buffer that has a file
restriction.  Regardless of how the user produces a file-restricted
log buffer, I think the "if showing a commit from the log buffer,
honor the log's file restriction" behavior makes sense --- something
along the lines of the km/show-commit-files branch.

**Comment by bitti** [comment]
Great, so what is preventing this commit from getting merged?

**Comment by kyleam** [comment]
> Great, so what is preventing this commit from getting merged?

Others finding the time to review it.
