### ISSUE TITLE
Magit should support git environment veriables

### ISSUE THREAD

**Issue by light2yellow** [magit/magit#3057]
I'm using `direnv` to manage multiple git profiles, thus when I `cd` into the directory that contains the code, it has `.envrc` inside with variables that get exported. Right now there's no way to commit if `.gitconfig` does not contain name and email.

However, Magit should support at least `GIT_AUTHOR_EMAIL, GIT_AUTHOR_NAME, GIT_COMMITTER_EMAIL, GIT_COMMITTER_NAME`. 

For the full list of git variables see [Git - Environment Variables](https://git-scm.com/book/gr/v2/Git-Internals-Environment-Variables).

**Comment by npostavs** [comment]
Doesn't it work if you set those variables in Emacs' environment (e.g., with `setenv`)? It sounds to me that you're just missing an Emacs equivalent to `direnv` (and I don't think magit should be that package).

**Comment by light2yellow** [comment]
@npostavs 
1) I'm not sure how to replicate current behaviour. From what I see on GNU's page, `setenv` just sets the environment variables for Emacs process. Let's imagine I have three dirs, `A`, `B` and `C`. Each of them contains `.envrc` with different environment variables that get exported when I `cd` into any of those three. How do I set up three identities?
2) `direnv` method is generic and can be used with any application, so why inventing more bicycles?
3) I suppose it's not hard to fallback on checking whether Git variables are exported, is it? `direnv` was just an explanation, why do I (and probably others) would be happy to see such behaviour.

**Comment by npostavs** [comment]
> I'm not sure how to replicate current behaviour. From what I see on GNU's page, setenv just sets the environment variables for Emacs process

Sorry for the confusion, I meant `setenv` the Emacs function, not the command line tool.

```
setenv is an interactive compiled Lisp function in ‘env.el’.

(setenv VARIABLE &optional VALUE SUBSTITUTE-ENV-VARS)

Set the value of the environment variable named VARIABLE to VALUE.
VARIABLE should be a string.  VALUE is optional; if not provided or
nil, the environment variable VARIABLE will be removed.
[...]
```

> `direnv` method is generic and can be used with any application, so why inventing more bicycles?

It works for applications you subsequently call from the shell. Try `cd`ing into one of your repositories and then calling emacs from there.

**Comment by light2yellow** [comment]
@npostavs 
I was talking about the function too. Could you link me to an example like [this one](https://collectiveidea.com/blog/archives/2016/04/04/multiple-personalities-in-git) on how do I export different things at different times? Will it work in Emacs server mode, e. g. opening through `emacsclient --no-wait`? Will I be able to open files from inside Emacs too and then commit?

**Comment by npostavs** [comment]
> I was talking about the function too.

Oops, then sorry for the additional confusion I introduced. :/

> Could you link me to an example like this one on how do I export different things at different times?

That's what I meant by "an Emacs equivalent do `direnv`". It looks like there are several implementations:

- https://github.com/wbolster/emacs-direnv
- https://github.com/jml/direnv-el
- https://github.com/christianromney/projectile-direnv
- https://gist.github.com/zph/50c766d6c7aa212896b5

**Comment by light2yellow** [comment]
@npostavs 
oh, sorry for not googling for "Emacs & `direnv` integration" first. I will try this out ASAP, thank you.

**Comment by light2yellow** [comment]
Well, unfortunately Spacemacs cripples its own configuration for some very mysterious reason (puts a newline inside a comment) at loading time, so I wan't able to test `emacs-direnv` (which is the recommended option by `direnv` developers). However, I believe that a proper configuration would've solved this issue.
