### ISSUE TITLE
tramp-like file navigation when visiting file at revision

### ISSUE THREAD

**Issue by Sarcasm** [magit/magit#3066]
I often use `magit-find-file` to visit file in a previous version.
For example, I have done some local commits, and wants to get an eye of the file on the remote to see the state of the code.
I work mostly with C++, and when I visit a source file, I often want to visit the header file or a sibling source file.

One thing that would make this navigation faster, is to have a tramp-like behavior.

When I open a file with tramp, for example to visit a file as sudo, I do:

    C-x C-f /sudo:root@myhost:/etc/foo.conf RET

Then, if I invoke `find-file` again, I get the context `/sudo:root@myhost:/etc/` as default, and I can find sibling files in this "Tramp context".

So, what I imagine for magit, is to visit a file with `magit-find-file`.
If I visit `origin/master:foo.cpp`, I want to have the default proposition for `find-file` to be `origin/master:`.
Today, if I re-invoke `magit-find-file` while I'm already visiting a file at a specific revision, I have to re-enter the revision, the default proposition is usually not what I'm looking for.

I'm not so well versed in Tramp but maybe a Tramp backend would even make sense...and now I feel bad because, I now see that `magit-tramp` "was" a thing:

- https://github.com/emacsattic/magit-tramp

However, I have the feeling this tries to deal with "remote" hosts, while I would already be happy with access to local repository only like `magit-find-file`.

So a few questions:

- What do you think about the idea, is it something worth including to magit?
- Assuming you are somewhat familiar with `magit-tramp`, do you know why it is unmaintained and what is wrong with it?
- Do you think `magit-find-file` should be slightly modified to provide a better default revision, or do you think the Tramp method is better?

I would be happy to do the development but I'd like it to be available upstream if at all possible.

**Comment by kyleam** [comment]
> Today, if I re-invoke magit-find-file while I'm already visiting a
> file at a specific revision, I have to re-enter the revision, the
> default proposition is usually not what I'm looking for.
>
> [...]
>
> Do you think magit-find-file should be slightly modified to provide
> a better default revision, or do you think the Tramp method is
> better?

Yes, I think `magit-find-file` should provide its revision as the
default.  At first glance, I think below should be sufficient.

```diff
diff --git a/lisp/magit-git.el b/lisp/magit-git.el
index 947bb275..d77a0131 100644
--- a/lisp/magit-git.el
+++ b/lisp/magit-git.el
@@ -885,7 +885,8 @@ (defun magit-commit-at-point ()
            (car magit-refresh-args))))

 (defun magit-branch-or-commit-at-point ()
-  (or (magit-section-case
+  (or magit-buffer-revision
+      (magit-section-case
         (branch (magit-section-value it))
         (commit (let ((rev (magit-section-value it)))
                   (or (magit-get-shortname rev) rev)))

```

**Comment by Sarcasm** [comment]
Indeed, this does the job pretty well.
In my case, `magit-buffer-refname` looks even better.
Just need to bind `magit-find-file` and that should be sufficient for my needs.

**Comment by kyleam** [comment]
> In my case, magit-buffer-refname looks even better.

Right, good point.

**Comment by kyleam** [comment]
As of 922de22bd, `magit-buffer-refname` should be offered as the
default revision.

I didn't close this issue with that commit in case you'd like to
discuss or develop your Tramp ideas further.

**Comment by Sarcasm** [comment]
Great, that was fast!
I'm closing since I think this is good enough for me.
The Tramp method has still some merit but is more involved. And I know where to start if I want to.

Thanks!
