### ISSUE TITLE
Why is git-commit-fill-column considered obsolete?

### ISSUE THREAD

**Issue by angrybacon** [magit/magit#3067]
Here is the commit for reference: https://github.com/magit/magit/commit/a277432e806af89c3bdd6046721c4db948443120

While `git-commit-turn-on-auto-fill` still uses it.

**Comment by kyleam** [comment]
`git-commit-turn-on-auto-fill` still uses it to accomadate users that
still set it.

I think #2848 contains most of the background on this.

**Comment by npostavs** [comment]
Yep, short answer is, it's obsolete because it doesn't provide any functionality over plain old `fill-column`.

**Comment by angrybacon** [comment]
Thanks, I'm advicing `git-commit-turn-on-auto-fill` then. Unless you want to keep the issue around, you can close it. 👌
