### ISSUE TITLE
Consider disabling comment-auto-fill-only-comments with git-commit-turn-on-auto-fill

### ISSUE THREAD

**Issue by angrybacon** [magit/magit#3068]
In order to use a specific value for `fill-column` when editing a commit message eg. 72 we need to ensure `comment-auto-fill-only-comments` is `nil` in the buffer, that is because the `COMMIT_EDITMSG` buffer support comments.

Currently, I use:

```elisp
(defun me/git-commit-auto-fill-everywhere ()
  (setq-local comment-auto-fill-only-comments nil))
(advice-add 'git-commit-turn-on-auto-fill :after #'me/git-commit-auto-fill-everywhere))
```

**Comment by kyleam** [comment]
I guess I'd be OK adding

    (setq-local comment-auto-fill-only-comments nil)

to `git-commit-turn-on-auto-fill`.  But I think my main thought is
"that's the purpose of `comment-auto-fill-only-comments`; don't set it
globally if you don't want such behavior".  Doesn't this also mess up
auto-filling in, say, org-mode and latex-mode?  If you find this
convenient in programming modes, why not enable it in
`prog-mode-hook`?

**Comment by angrybacon** [comment]
Nope, Org buffers are correctly auto-filled. Not sure about Latex.

**Comment by kyleam** [comment]
> It's just that text-mode is not supposed to support comments.

I think text based modes can support comments.  That's why both
org-mode and latex-mode came to mind.

As you said, Org mode doesn't honor `comment-auto-fill-only-comments`.
Looking into it, this is because it overrides in
`comment-line-break-function` (in `org-setup-filling`).
`comment-auto-fill-only-comments` is honored in latex-mode.

**Comment by kyleam** [comment]
>> If you find this convenient in programming modes, why not enable it in prog-mode-hook?

> That's the thing, I need auto-fill-mode in text-mode too.

It's `comment-auto-fill-only-comments` that you would enable via
`prog-mode-hook`.

**Comment by kyleam** [comment]
> It's just that text-mode is not supposed to support comments.

Err, but I do see your point here.  Magit puts the commit buffer in
`text-mode` (by default).  It's reasonable for a user to expect the
`comment-auto-fill-only-comments`-behavior to be the same as any
`text-mode` buffer, but it's not because Magit sets up comment-related
variables.
