### ISSUE TITLE
Improve rendering of Unicode characters

### ISSUE THREAD

**Issue by mrkkrp** [magit/magit#3078]
Please, can we render ‘’ “” «» and other Unicode characters properly instead of showing `\xxx` escape codes?

I'm talking about this:

![magit](https://cloud.githubusercontent.com/assets/8165792/26201768/bbb6c4f0-3bfe-11e7-84e6-724dbdf8fdfc.png)

It's also probably absolutely horrible if user commits with non-Latin messages (in other languages…).

**Comment by mrkkrp** [comment]
I'm pretty sure it worked better in the past.

**Comment by kyleam** [comment]
I've looked at the same log from megaparsec and it renders fine on my
end.  Can you reproduce it with a minimal configuration?

**Comment by mrkkrp** [comment]
With Emacs 25 from my package manager, I start `emacs -Q`, evalutae `(package-initialize)` then navigate to my repo and call `magit-status`, then I press `l` `l`. I still see these `\xxx` guys. How else should I try?

**Comment by kyleam** [comment]
Since you recall it working for you in the past, you could try to
bisect the Magit repo.  (If you're looking for a place to start, I
think the parent of 513aeb2f is a good candidate.)

**Comment by mrkkrp** [comment]
Even though you can't reproduce it, it still may be a legit Magit bug affecting many users. I can't promise to spend time hunting this, but if I happen to find the time, I'll comment here.

**Comment by mrkkrp** [comment]
I checked, it looks like `git log` outputs it like this:

```
commit 636b4d58b559073e8b5db3324e5d2ad54d7f9c7c
Author: mrkkrp <markkarpov@opmbx.org>
Date:   Thu May 18 20:32:02 2017 +0700

    Drop <E2><80><98>mu4e<E2><80><99>, I don't read emails from Emacs anymore
```

Is this normal? I'll try to make it output Unicode properly (my locale is `en_US.UTF-8`).

**Comment by mrkkrp** [comment]
OK guys, my bad. (Used Ansible to configure the system and forgot that `locale_gen` does not set locales, only generates them!) Closing.
