### ISSUE TITLE
Improve target directory name guessing in magit-clone

### ISSUE THREAD

**Issue by mrkkrp** [magit/magit#3079]
The `magit-clone` command could do a better job when name of the repo to clone contains dots. For example, if I invoke `magit-clone` with `https://github.com/mrkkrp/mrkkrp.github.io.git`, it thinks that the directory where to clone the repo should be called `io`, while the correct behavior would be to infer `mrkkrp.github.io` and propose that.

**Comment by kyleam** [comment]
Yeah, `io` certainly isn't a useful suggestion here.  This is the
result of the following regexp:

```emacs-lisp
(and (string-match "\\([^./]+\\)\\(\\.git\\)?$" url)
                   (match-string 1 url))
```

Changing this to

```diff
diff --git a/lisp/magit-remote.el b/lisp/magit-remote.el
index 9766ade5..0116339c 100644
--- a/lisp/magit-remote.el
+++ b/lisp/magit-remote.el
@@ -58,7 +58,7 @@ (defun magit-clone (repository directory)
    (let  ((url (magit-read-string-ns "Clone repository")))
      (list url (read-directory-name
                 "Clone to: " nil nil nil
-                (and (string-match "\\([^./]+\\)\\(\\.git\\)?$" url)
+                (and (string-match "\\([^/]+?\\)\\(\\.git\\)?$" url)
                      (match-string 1 url))))))
   (setq directory (file-name-as-directory (expand-file-name directory)))
   (magit-run-git-async "clone" repository
```

should handle your case.  I'm not sure if that leads to undesirable
results in other cases.

**Comment by tarsius** [comment]
> should handle your case. I'm not sure if that leads to undesirable results in other cases.

It's what git does, so let's just do that too.

**Comment by kyleam** [comment]
> It's what git does, so let's just do that too.

I proposed a slightly different regexp in #3080 because I realized we
don't handle the "foo for host.xz:foo/.git" case mentioned in git
clone's manpage.
