### ISSUE TITLE
Stash pop should should show stash message

### ISSUE THREAD

**Issue by zck** [magit/magit#3083]
Magit version: 20170522.1130

When running `stash save` (`z z`), Magit prompts for a message to save with the stash. This is displayed in `stash list` (`z l`), which is great.

But it's not displayed when I run `stash pop` (`z p`). I would like it to be. I use helm (but checked this without helm just to make sure), so it would be nice to have in the helm buffer, as well as in the minibuffer prompt.

**Comment by tarsius** [comment]
The recommended way to pop a stash is to expand the Stashes section in the status buffer and the pressing `A` to apply and discard the stash, or `a` to only apply it.

I can understand the sentiment of wanting to see more information about individual completion candidates. But this also applies to many other areas of Magit also, and so we have to carefully validate the implications before moving into this direction.

**Comment by zck** [comment]
It's definitely good that you're thinking about doing it the right way.

One thought I have about popping a stash via the magit status page is that it's not so obvious that that's an option, because magit suggests that things are done with menu commands. For example, pressing `?` at the magit status page says that stashing commands are done with `z`, and then the stash page says nothing about how to pop stashes from the magit status page. I love that it can be done without going into the stash page, and will try to remember to do so in the future -- but I wonder how it can be made more obvious that it's an option. Thanks.

**Comment by tarsius** [comment]
> I wonder how it can be made more obvious that it's an option.

I don't see a way of doing that. Not that that is very obvious, but in a way, `?` already does say that "Applying changes\n  [a] Apply". I don't see how to make it obvious that anything that can be applied in one way or another by using `a`, except being rather verbose - which I would like to avoid.

**Comment by tarsius** [comment]
I think I am just gonna leave things as-is.
