### ISSUE TITLE
Magit needlessly causes server contact for unsaved disconnected Tramp buffers

### ISSUE THREAD

**Issue by jdtsmith** [magit/magit#3087]
`Magit 2.10.3, Git 2.11.0 (Apple Git-81), Emacs 25.2.1, darwin`

Issue: when you have _unsaved_ Tramp buffers that are no longer contactable (offline, or in another network environment), MAGIT still inquires for the `file-truename` of those files, which causes Tramp to try to contact the uncontactable server, leading to timeouts and interrupts, during e.g., commits.  This is easily reproduced by creating (but not saving) a file on a remote server via Tramp, then disconnecting the network, and performing a commit on an unrelated repository.

Borrowing a bit from the new autorevert code which attempts to prevent this behavior, and adding it to the predicate in `magit-save-repository-buffers` seems to solve this:

```
;; Avoid needlessly connecting to unrelated remotes.
(equal (file-remote-p buffer-file-name)
       (file-remote-p topdir))
```

**Comment by tarsius** [comment]
The existing code already *tries* to accomplish this, but it makes sense that the use of `file-truename` counteracts that effort. However simply drooping that, does not seem to be the proper fix. It is there for a reason; symlinks may be involved, and when that is so, then a file may be inside a repository even when the repository path isn't a prefix of the file path (in one case symlinks might already have been followed, but not in the other).

**Comment by tarsius** [comment]
One possible approach could be to not follow symlinks for *remote* files only.

**Comment by jdtsmith** [comment]
Good point.  But symlinks can't span remotes.  What's wrong with first testing if both `topdir` and the buffer-file in question are on the same remote before worrying about their `file-truename`'s?  I took this idea from [your autorevert fix](https://github.com/magit/magit/commit/f4dc04c20e77756a8386777ce5c43d1e25745263) dealing with Tramp issues and specifically the new `magit-auto-revert-repository-buffer-p`.

```
(defun magit-save-repository-buffers (&optional arg)
  "Save file-visiting buffers belonging to the current repository.
After any buffer where `buffer-save-without-query' is non-nil
is saved without asking, the user is asked about each modified
buffer which visits a file in the current repository.  Optional
argument (the prefix) non-nil means save all with no questions."
  (interactive "P")
  (-when-let (topdir (magit-rev-parse-safe "--show-toplevel"))
    (save-some-buffers
     arg (-partial (lambda (topdir)
                     (and buffer-file-name
                          ;; Avoid needlessly connecting to unrelated remotes.
			  (equal (file-remote-p buffer-file-name)
				 (file-remote-p topdir))
			  (string-prefix-p topdir (file-truename buffer-file-name))
                          (equal (magit-rev-parse-safe "--show-toplevel")
                                 topdir)))
                   topdir))))
```

**Comment by tarsius** [comment]
Ah, I thought you were suggesting that the `(string-prefix-p ...)` be removed.
