### ISSUE TITLE
Magit fails to guess what I want to checkout

### ISSUE THREAD

**Issue by mrkkrp** [magit/magit#3088]
Previously this worked:

1. Open commit log by pressing <kbd>l l</kbd>.
2. Go for example one commit back (on `master`).
3. Type <kbd>b b</kbd> to checkout that commit.
4. Magit should propose something like `master~1`.

Currently it proposes only tag and branch names, but can't guess `master~1`. I liked that feature! I actually learned that syntax through Magit :-)

**Comment by tarsius** [comment]
Hm, still works as before for me, but there was another report about such a regression just today on gitter.

What completion framework do you use? Can you reproduce this following the instructions at https://magit.vc/manual/magit/Debugging-Tools.html?

**Comment by mrkkrp** [comment]
I'm using this: https://github.com/abo-abo/swiper. I think the package that does autocompletion is called `ivy`.

This is my current Magit config:

https://github.com/mrkkrp/dot-emacs/blob/master/mk/mk-magit.el#L26-L38

**Comment by tarsius** [comment]
I use `ivy` too, but I kept the default value of `magit-completing-read-function` and instead simply turned on `ivy-mode`. If you have enabled `ivy-mode` too, then please try resetting `magit-completing-read-function` to see if that fixes the issue.

Note that its doc-string mentions that when using `helm` one should just use the default value. The same is the case for `ivy`, and I'll have to update the doc-string accordingly (but I'll have to first check whether setting the variable works when `ivy-mode` is *not* enabled).

**Comment by mrkkrp** [comment]
I can confirm that if I keep the default value of `magit-completing-read-function` it works.

**Comment by mrkkrp** [comment]
Looks like `magit-push-always-verify` can be dropped as well...

**Comment by tarsius** [comment]
I've opened #3089 to address confusions about `magit-completing-read-function`.
