### ISSUE TITLE
Git log actions (eg. cherry-pick) do not autocomplete commits using ivy

### ISSUE THREAD

**Issue by gilbertw1** [magit/magit#3090]
A recent change was made in ivy where the default value to the completing read function is not automatically added to the collection of auto complete candidates. Most actions taken in the git log, for example cherry-pick, will pop up an autocomplete and pass along a the specific commit under the point as the default value. With the most recent version of ivy, this commit will not be populated in the list and will not be selected, since it does not exist in the collection of completion candidates.

Once specific function which this is happening with is: ```magit-read-other-branch-or-commit```. Which is reading the specific commit at point and passing it along as a default value to ```magit-completing-read```. This same pattern is used very often in magit. I've created a corresponding issue to highlight this on ivy as well: 

https://github.com/abo-abo/swiper/issues/1031

Expected Behavior: Initiating a cherry-pick via ```A A``` in the commit log should open an completion popup and pre-populate the specific commit underpoint.

Observed Behavior: Completion popup opens with no commit selected and specific commit is not in the populated list.

Steps to reproduce: Use the latest version of ivy. Attempt to cherry pick from the commit log using ```A A```.

Thanks!

**Comment by tarsius** [comment]
I am using the latest `ivy` version and am not seeing this. I suspect the issue is the same as in #3088, which is being worked on in #3089.

**Comment by gilbertw1** [comment]
Okay cool, looks like you guys are tracking this already. I'll close this one out.
