### ISSUE TITLE
Now that Emacs has dynamic modules, libgit would make Magit killer fast

### ISSUE THREAD

**Issue by jwiegley** [magit/magit#3094]
libgit2 is an open source project to provide a C library for interacting with Git repositories.  Pretty much anything you can do with Git to the core repository, you can do with the libgit2 API.

It's quite a bit harder to use than command-line Git, and perhaps Magit would only want to use it for certain non-destructive operations (such as getting status, replacing calls to `rev-parse`, accessing recent log history and the stash list, etc). But if Magit were able to use libgit2.so directly, via dynamic module loading, then the UI would become wicked fast.

For example, each time I stage a single hunk from a file (my most common operation), the following commands are executed:

```
git rev-parse --show-toplevel
git rev-parse --show-toplevel
git rev-parse --show-cdup
git rev-parse --show-cdup
git rev-parse --show-toplevel
git rev-parse --show-toplevel
git rev-parse --show-cdup
git rev-parse --show-cdup
git rev-parse --show-toplevel
git rev-parse --show-toplevel
git rev-parse --show-cdup
git rev-parse --show-cdup
git rev-parse --show-toplevel
git update-index --refresh
git rev-parse --verify HEAD
git symbolic-ref --short HEAD
git show --no-patch --format=%h %s master^{commit} --
git rev-parse --show-toplevel
git rev-parse --show-cdup
git config --list -z
git rev-parse --verify origin/master
git show --no-patch --format=%s origin/master^{commit} --
git describe --long --tags
git describe --contains HEAD
git rev-parse --git-dir
git status -z --porcelain
git diff --no-ext-diff --no-prefix --
git diff --cached --no-ext-diff --no-prefix --
```

I'm not quite sure why `rev-parse` needs to be called so often -- since its results for a given buffer  never change -- but all of the commands above, excepting for `update-index`, are harmless calls that would be nearly instantaneous with `libgit2`.

I realize this represents a lot of work, but just posting it here as an idea, since Magit is many people's (mine included) favorite Git mode. The one thing I'd change these days is the speed. When staging 40 hunks from various files, it starts feeling really slow compared to modern Git GUIs.

**Comment by thisch** [comment]
related to #2959 and #2956

**Comment by jwiegley** [comment]
Just in case anyone notices, the following changes dramatically improved my staging performance with current magit:

The following hacky diff:

``` diff
modified   lisp/magit-git.el
@@ -722,16 +722,41 @@ are considered."
 
 ;;; Revisions and References
 
+(defvar magit--rev-parse-toplevel-cache (make-hash-table :test #'equal))
+(defvar magit--rev-parse-cdup-cache (make-hash-table :test #'equal))
+(defvar magit--rev-parse-git-dir-cache (make-hash-table :test #'equal))
+
+(defmacro magit--use-rev-parse-cache (cmd args)
+  `(pcase ,args
+     ('("--show-toplevel")
+      (or (gethash default-directory magit--rev-parse-toplevel-cache)
+          (let ((dir ,cmd))
+            (puthash default-directory dir magit--rev-parse-toplevel-cache)
+            dir)))
+     ('("--show-cdup")
+      (or (gethash default-directory magit--rev-parse-cdup-cache)
+          (let ((dir ,cmd))
+            (puthash default-directory dir magit--rev-parse-cdup-cache)
+            dir)))
+     ('("--git-dir")
+      (or (gethash default-directory magit--rev-parse-git-dir-cache)
+          (let ((dir ,cmd))
+            (puthash default-directory dir magit--rev-parse-git-dir-cache)
+            dir)))
+     (_ ,cmd)))
+
 (defun magit-rev-parse (&rest args)
   "Execute `git rev-parse ARGS', returning first line of output.
 If there is no output return nil."
-  (apply #'magit-git-string "rev-parse" args))
+  (magit--use-rev-parse-cache
+   (apply #'magit-git-string "rev-parse" args) args))
 
 (defun magit-rev-parse-safe (&rest args)
   "Execute `git rev-parse ARGS', returning first line of output.
 If there is no output return nil.  Like `magit-rev-parse' but
 ignore `magit-git-debug'."
-  (apply #'magit-git-str "rev-parse" args))
+  (magit--use-rev-parse-cache
+   (apply #'magit-git-str "rev-parse" args) args))
 
 (defun magit-rev-parse-p (&rest args)
   "Execute `git rev-parse ARGS', returning t if it prints \"true\".
```

- Taking logs and stashes out of `magit-insert-status-headers`
- Turning of all the WIP saving features (which are off by default anyway)
- Turning off auto-revert mode
- Disabling saving of buffers (i.e., settings `magit-pre-refresh-hook` to `nil`)
- Setting `magit-refresh-status-buffer` to `nil`

Before all this, when I was using way too many safety features, staging a single hunk took 4.4 seconds in my not-so-large repository (longer in some others).  Now it's down to 0.24 seconds, which has the sort of snappiness I was looking for.

**Comment by tarsius** [comment]
We use a similar cache for `git config ...`. And we might as well for `git rev-parse ...` too. But I agree, in the (hopefully not so) long run, `libgit2` is the answer.

> compared to modern Git GUIs

Watcha taking about? Magit is a modern Git TUI ;-)

I'll will comment on the other points some other time.

**Comment by npostavs** [comment]
> We use a similar cache for `git config ...`. And we might as well for `git rev-parse ...` too.

Hmm, I have the memory of already writing code to cache those calls, did I just hallucinate that?

**Comment by npostavs** [comment]
Oh, we cache them during refresh, but not during stage, unstage, etc.

@tarsius in https://github.com/magit/magit/issues/2909#issuecomment-269717069 you said 
>> Most of the calls seem to be from `magit-maybe-save-repository-buffers`, `magit-process-setup` (`magit-process-set-mode-line`),  `magit-process-finish` (`magit-process-unset-mode-line`).
>
> Ah, I think we can optimize the process part. We already store the `default-directory` in the process object, now we just have to use it. But it's to late here for me to look into it right now.

Worth looking into now?

**Comment by tarsius** [comment]
> Worth looking into now?

I think so, yes.

Even if such a cache would eventually be made obsolete by `libgit2`, doing this would still be beneficial. Not least because the use of modules will mean that we have to drop support for Emacs 24 - I expect there will be users who cannot update by the time we complete `libgit2` support.

**Comment by npostavs** [comment]
See #3096.

**Comment by phil-s** [comment]
John's cache should also be handled by the `magit-zap-caches` command:

```diff
modified   lisp/magit-mode.el
@@ -1425,6 +1425,11 @@ Remove the repository's entry from `magit-repository-local-cache'
 and set `magit-section-visibility-cache' to nil in all of the
 repository's Magit buffers."
   (interactive)
+  (setq magit--rev-parse-toplevel-cache (make-hash-table :test #'equal))
+  (setq magit--rev-parse-cdup-cache (make-hash-table :test #'equal))
+  (setq magit--rev-parse-git-dir-cache (make-hash-table :test #'equal))
   (magit-with-toplevel
     (setq magit-repository-local-cache
           (cl-delete default-directory
```

**Comment by tarsius** [comment]
Looks like the plan was to do something along these lines, but we never got around to it.

I'll take a stab at it next week or so.

I already looked into it a bit and think it might be better to do the caching at a somewhat higher level, but will have to think about it more.

**Comment by tarsius** [comment]
Exactly.

But that wouldn't necessarily apply to more localized caches, such as the existing refresh cache. (Or at least not to the same extend; for certain commands that does require specialized cache invalidation/suppression.)

`magit-save-repository-buffers` could likely use a similar cache, making it unnecessary to do the work for every buffer, limiting it to each value of `default-directory` among those buffers instead.

Of course there may still be many different values for `default-directory` (and this isn't the only place where calls to `rev-parse --something-path` originate), so this may not enough, making it necessary to have a more generalized cache, which would not be free of the cache invalidation issued. (And additionally we would now have two caches and we would have to think about the interaction between the too. Maybe if the generalized cache were in used, the localized cache would have to be disabled, or maybe something smarter would be possible.)

Doing it at the level of `magit-rev-parse` doesn't give us enough control. 
`magit-save-repository-buffers` is an extreme at the other end of the spectrum. `magit-git-dir` and `magit-toplevel` fall somewhere in between and might be the right spot for the generized cache.
