### ISSUE TITLE
Staged Changes are empty when committing with --all

### ISSUE THREAD

**Issue by jdtsmith** [magit/magit#3095]
When committing using the `-a` flag (which runs `git commit ... --all`) the `*magit-diff` buffer is popped up with empty `Staged Changes`.  This may technically be correct: there are no staged changes at that point, and `commit` will stage and commit in one pass, but it is distracting and unintuitive.   If you have some staged changes and some not yet staged, when using the `--all` flag, only the previously staged changes are shown.  It would be more intuitive if _all_ changes were shown as the pending diff.  

Magit 2.10.3, Git 2.11.0 (Apple Git-81), Emacs 25.2.1, darwin

**Comment by tarsius** [comment]
Agreed!

**Comment by kyleam** [comment]
Yeah, that's a more useful diff to display in this situation.  I had a
quick look at `magit-commit-diff` and couldn't think of a simple or
clean way to add it, though.

**Comment by jdtsmith** [comment]
Could you just remove `--cached` and run and then wash `git diff HEAD` (or the appropriate tree marker upon which the commit will be made) if `--all` is set ?

**Comment by kyleam** [comment]
The difficulty isn't how to get a diff of all changes; it's knowing
that the `--all` flag was used.  Right now, `magit-commit-diff`
decides what the diff call is based `last-command`, but the same
action can be called with and without the `--all` flag.
`magit-commit-diff` needs more information about the call, but I don't
believe `magit-with-editor` currently stores these details.

**Comment by jdtsmith** [comment]
Hmmm, you're right.  Perhaps if `magit-current-popup-args` were saved outside of the dynamical stack, it could be accessed later.
