### ISSUE TITLE
Add `remote list`

### ISSUE THREAD

**Issue by zck** [magit/magit#3097]
There are times I want to make sure my remotes are what I think they are. This happens when, for example, I forget if I've already forked a repository, or if I've just cloned an existing repository.

If I were using the git command line, I'd call `git remote -v`, and it would list all my remotes, and the urls for them (separately for `fetch` and `push`, which I don't understand).

But in magit, it seems like the closest I can get to that is `M u`, which is bound to `#'magit-remote-set-url`, then select a remote, and look at the url at the same time as I can change it. This is more inconvenient, because it's one remote at a time, and going into the place to edit the url is an odd place to go to to find out what the value currently is.

I'd like to be able to see a list of remotes and their urls, something like a `#'magit-remote-list` command. Thanks.

**Comment by npostavs** [comment]
`y` (`magit-show-refs-popup`) does show the remotes with their URLs, in addition to branches and tags.

**Comment by zck** [comment]
This is pretty useful. I'll try to remember to use it in the future. Thanks!

It isn't, however, the most obvious place to look, I think. It seems like the simplest place to look for it is in `magit-remote-popup`.

**Comment by DamianB-BitFlipper** [comment]
@tarsius I've had this need several times already to list all of the remotes, and was also looking under `M` for remotes. I think that's the logical place one looks for a "list all remotes" functionality.

I can implement this, but I would suggest having a `y` under `M` which runs the `magit-show-refs-popup` and it displays a hint in the minibuf that it can be accessed via `y` in the main menu directly.

A similar argument can be made for having `y` under `b` to list all branches.

Thoughts?

**Comment by tarsius** [comment]
That falls into the "reasonable, but no" category.

This command does not actually list just remotes or just branches.  It lists branches below the respective remotes, and also tags, and optionally other things.  As such it doesn't really fit into the branch and/or remote (and tag) menus.

Also all the other commands in the branch/remote/tag menus deal with one branch/remote/tag. Listing things is different.  This also means that there isn't a logical place where this command would fit in these menus.

Even though the number of purely alphabetic top-level bindings is very crowded, this command does get one of those.  So it is pretty privileged already. 

Yes, the used key is not obvious, and you might have to look it up more than once, before committing it to memory, but search engines will tell you the binding.

You can of course add the bindings locally, if you want.
