### ISSUE TITLE
magit-show-commit show the wrong commitid when branche name == tag name 

### ISSUE THREAD

**Issue by jixiuf** [magit/magit#3098]
(2) what behavior you observed
![snip20170608_2](https://user-images.githubusercontent.com/461743/26914798-c9cd605a-4c55-11e7-8fff-1b47768d5f38.png)

  (3) and how we can reproduce the issue.

it can be reproduced by `M-x magit-emacs-Q-command RET`

**Comment by kyleam** [comment]
`magit-branch-or-commit-at-point` (and utlimately `magit-get-shortname`) should be returning a qualified refname here (i.e., "heads/v1").
