### ISSUE TITLE
Browse trees at a given commit

### ISSUE THREAD

**Issue by yurikhan** [magit/magit#3099]
Magit provides support for visiting a blob representing a file at a known revision. It would be nice if one could similarly visit trees.

Ideally, it would be a Dired buffer, where you could type `RET` on individual blobs or subtrees to navigate between them. Additionally, issuing `magit-dired-jump` in a buffer visiting a blob@revision would visit the containing tree@revision, and `magit-dired-jump` from a tree@revision would visit its parent tree@revision.

**Comment by tarsius** [comment]
I plan to do that when implementing `git-blob-handler.el`. See #2958. Since it also supposed to handle trees, it might be better to name it `git-object-handler.el`.

**Comment by tarsius** [comment]
Closing in favor of #2958.
