### ISSUE TITLE
Make it possible to see the details of unstaged directories

### ISSUE THREAD

**Issue by kephas** [magit/magit#3100]
In the main magit buffer, most sections can get more detailed when hitting Tab while point is on them (e.g. a file becomes its patch hunks).

This isn't possible with a directory that is entirely not in Git, which is a problem when you want to stage sepcific files in it. Especially when it is a few files among many others.

For example, if there is the following tree:

    foo/ (in Git)
    bar/ (not followed)
    bar/baz.txt
    bar/quux/ (contain 99 files)

and I want to add bar/baz.txt, right now I must either use git directly or stage bar/ entirely, get 100 files staged and unstage all 99 files in bar/quux/ one by one.

**Comment by npostavs** [comment]
You can get this by setting the git variable `status.showUntrackedFiles` to `all`, see `magit-insert-untracked-files`.

**Comment by kephas** [comment]
But is it possible to get that behavious without messing up Git's behavious in the shell?

**Comment by npostavs** [comment]
I think 
```elisp
(cl-callf append magit-git-global-arguments '("-c" "status.showUntrackedFiles=all"))
```
should do it.

**Comment by arialdomartini** [comment]
Great, both approaches work.
Untracked files, though, can be visited with [RET], but [TAB] seems to have no effect on them. On the contrary, once they are staged, [TAB] would show their content.

Is there a way to use [TAB] to show the details of untracked files?

**Comment by arialdomartini** [comment]
There are some discussions here 

https://emacs.stackexchange.com/questions/27271/how-do-i-toggle-magit-enumerating-untracked-files

**Comment by kephas** [comment]
Also, it seems you don't need to add `status.showUntrackedFiles=all` to magit's config anymore, it is now possible to expand unstaged directories by default.

**Comment by arialdomartini** [comment]
@kephas Yes, but it seems it's still not possible to expand the content of untracked files. Do you know how to do that?

**Comment by kephas** [comment]
@arialdomartini I'm using Magit `20210616.1958` and I can expand untracked files.

**Comment by arialdomartini** [comment]
@kephas I can expand the directories containing untracked files, but Tab would not display their content. I can open them one by one with Return, though.
Are you able to see the content of an untracked file pressing Tab?

**Comment by kephas** [comment]
Ha, I misunderstood you. I guess the problem is that those files' content is not available through git, contrary to files added in git and the list of untracked files.

**Comment by arialdomartini** [comment]
Yes, true. Their content can be visited with Return.
It would be very handy if Magit could provide a consistent experience letting the user visit them without opening a new buffer, and accessing them with the very same keybinding Tab. What do you think?

**Comment by kephas** [comment]
I think it's a good design decision to not have `Magit` implement accessing data that's outside the scope of `git`.

**Comment by arialdomartini** [comment]
@kephas I see. From the user perspective, having a consistent behavior for TAB could be seen an application of dwim.
