### ISSUE TITLE
Apply variant: "discard whitespace-only changes"

### ISSUE THREAD

**Issue by ebpa** [magit/magit#3102]
It would be immensely handy to be able to discard whitespace-only changes for a file or all files (/ files with a common staging status) with a single command in the fashion that the current `magit-discard` command does.  I can imagine subtle variations of behavior, such as whether to include newlines, but `git diff -w` offers a good standard model.

**A generalization suggestion:**
Perhaps it could be added as a common "mask" option to all 'apply' commands?  For example: "stage all *non-whitespace* changes" or "discard *whitespace* changes".  They don't necessarily need to be oriented to emphasize discarding/omitting whitespace.  Conceivably some users may be interested in selectively staging and committing reformatting changes before other substantive non-whitespace changes.

Thanks for your consideration!  Magit rocks!

**Comment by tarsius** [comment]
> It would be immensely handy to be able to discard whitespace-only changes for a file or all files

If doing so on the file level is all you need, then you could just use the built-in `whitespace-cleanup`. But you want something that removes whitespace *changes*, i.e. something that removes newly added whitespace *mistakes*. Again you could use some existing functionality that prevents new whitespace mistakes from being saved to the visited file. [`whitespace-cleanup-mode`](https://melpa.org/#/whitespace-cleanup-mode) might be an option.

**Comment by ebpa** [comment]
@tarsius Thanks for the suggestions.  My intent, however; is to regard the git version as authoritative/correct.  I want to preserve whitespace mistakes if they already exist.  What `whitespace-cleanup` regards as correct may frequently be different from the form of whitespace of the unmodified file.  If the unmodified file has trailing whitespace on a line and I deleted it while reading through the code and making changes I want to be able to unstage/discard that and any other whitespace  changes I made en-masse so that my commit does not include extraneous line modifications.

As I mentioned, a generalized whitespace "mask" for apply operations could be more broadly useful/powerful.  The whitespace *mistakes* could be isolated and corrected in a commit without needing to stash or discard unstaged changes to code.

I currently use `git diff -U0 -w --no-color | git apply --cached --ignore-whitespace --unidiff-zero -` ([original source](https://stackoverflow.com/questions/3515597/add-only-non-whitespace-changes/7149602#7149602)) to isolate non-whitespace changes when staging.

It's not necessarily a *good* idea for implementation of this hypothetical feature, but I can imagine for example using a prefix command with the existing apply commands.  Ex: `C-u S` to stage all non-whitespace changes, `C-u C-u s` to stage all whitespace changes according to the current point (ex: within a file, hunk, or region), or `C-u C-u U` to unstage all whitespace changes. 

I hope that better illustrates that feature that I think would be really cool.

**Comment by tarsius** [comment]
> As I mentioned, a generalized whitespace "mask" for apply operations could be more broadly useful/powerful.

That already exists but is more centered around diff than apply. For example.

1. In the status buffer press <kbd>D</kbd> to enter the "change diff arguments used in this buffer" popup.
2. Enable `--ignore-space-changes` and put it into effect using <kbd>g</kbd>.
3. Stage the non-whitespace changes.
4. Disable `--ignore-space-changes` again.
5. Discard the whitespace-only changes.

* That only works if you work on the sub-file level. Files are added using just `git add FILE`.
* `apply` is already always called with `--ignore-space-change`.
* It might be necessary to also force `--unidiff-zero` to be used.
* It might be a bit inconvenient that this requires two steps, but...
* Git only offers `--ignore-space-changes` but not `--only-space-changes`. It don't want to fake the latter in Magit.
* It might also be inconvenient to have to enter the popup twice. A toggle `--ignore-space-changes` command would help here.

I don't think it is a good idea to have the user look at one diff and then apply another related but different diff instead, which is what your prefix argument suggestion amounts too.

**Comment by ebpa** [comment]
@tarsius 
> - That only works if you work on the sub-file level. Files are added using just git add FILE.

I think most of the value is redeemed when it's possible at the file level.

> - Git only offers --ignore-space-changes but not --only-space-changes. It don't want to fake the latter in Magit.

Quite sensible.

> I don't think it is a good idea to have the user look at one diff and then apply another related but different diff instead, which is what your prefix argument suggestion amounts too.

Agreed.  That would be particularly hairy behavior with respect to the "magic number" characteristic of prefix variation (it's not necessarily apparent that you actually pressed just `C-u` rather than `C-u C-u`).  Although: on that note-- the file-level staging and unstaging also does not abide by this WYSIWYG behavior with respect to the whitespace characteristic of diffs :-)

**Comment by tarsius** [comment]
> I think most of the value is redeemed when it's possible at the file level.

And that's possible now!

**Comment by tarsius** [comment]
See 96cb64e6b426debaf0c0d7b96a76fbee0996b936.
