### ISSUE TITLE
Deleting a partially merged branch is not allowed at all

### ISSUE THREAD

**Issue by redbeardcreator** [magit/magit#3107]
When a feature branch has been merged into HEAD but not into it's own origin, it cannot be deleted, not even offering an option to force delete.

After asking for help with the issue [gitter](https://gitter.im/magit/magit), @tarsius offered the following:

> Given this situation:
> 
> ```
> cb255f9 (HEAD -> feature) c
> | * 269bc5a (origin/feature) b
> |/
> 799f9ed (origin/master, origin/HEAD, master) a
> $ git log --graph --oneline --all
> cb255f9 (feature) c
> | * 269bc5a (origin/feature) b
> |/
> 799f9ed (HEAD -> master, origin/master, origin/HEAD) a
> ```
> 
> I used `b k`, selected `feature`, and was asked whether I want to delete it even though it is unmerged.
> Aha! But not anymore after actually merging.
> 
> ```
> 28a6061 (HEAD -> master) Merge branch 'feature'
> |\
> | cb255f9 (feature) c
> |/
> | 269bc5a (origin/feature) b
> |/
> 799f9ed (origin/master, origin/HEAD) a
> ```
> 
> `magit-branch-merged-p` should probably to behave like "Return non-nil if BRANCH is merged into its
> upstream and TARGET" instead of "... or ...". Please open an issue so that I can fix this when I
> have the time.

This describes my situation. Thank you for the assistance, @tarsius!

**Comment by tarsius** [comment]
Meanwhile you can delete partially merged branches using `b C-u k`, i.e. by explicitly forcing the deletion instead of relying on being asked whether you want to do so.

**Comment by redbeardcreator** [comment]
Ah...I was unaware of the prefix key usage. Nice.

**Comment by kyleam** [comment]
@tarsius It seems that you rebased and deleted origin/fix-3107 a
couple hours ago, but 4eed517af hasn't yet landed in origin/master.
Forget to push your local master?

**Comment by tarsius** [comment]
Yep. Pushed now.
