### ISSUE TITLE
commit popup: make it more convenient to select ORIG_HEAD for =C

### ISSUE THREAD

**Issue by kyleam** [magit/magit#3110]
As mentioned in `man git-reset` (and this Emacs StackExchange
[question]), `ORIG_HEAD` can be useful for undoing a commit and
resuing its message:

```
$ git commit ...
$ git reset --soft HEAD^      (1)
$ edit                        (2)
$ git commit -a -c ORIG_HEAD  (3)
```

Currently, the `=C` prompt doesn't offer any candidates, and
`ORIG_HEAD` isn't fun to type.

[question]: https://emacs.stackexchange.com/questions/33702/magit-undo-last-commit-history-manipulation

**Comment by tarsius** [comment]
Offering at least `ORIG_HEAD` seems like a good idea, if it exists.
