### ISSUE TITLE
How to handle files with Chinese names?

### ISSUE THREAD

**Issue by zhixing2017** [magit/magit#3111]
Thanks for your job! 

I got a problem. I could not handle files with Chinese names. Maybe it is relative with the coding system.

Magit 20170616.1430, Git 2.12.2.windows.2, Emacs 25.2.1, windows-nt (local language: Chinese)

I use `git init` in a `Temp` folder, and creat a file with Chinese name: 好.txt .
In Spacemacs, `SPC g s`, there is untracked file, when i move the cursor on it and press `s`. If it is an English-name file, it will be staged. But now error occured. It told me to press `$` for more details.

Here is the message after pressed `$`.
![default](https://user-images.githubusercontent.com/26316963/27422514-07186ec6-5761-11e7-865c-09a72c8fe980.png)

Can you help me with this? It is so inconvenient for me.

**Comment by npostavs** [comment]
For me the Chinese character gets converted into a space character: (my local language is English, so that probably explains the minor difference)
```
(call-process "git" nil '(t t) nil
	      "-c" "alias.x=!x() { printf '%s' \"$1\" | od -tx1; }; x" "x" "(\u597d)")
0000000 28 20 29
0000003
```

---
~~I think this might be [Emacs Bug#13589](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=13589)~~ Nevermind, it's only vaguely related.

But it does seem to be an Emacs bug and not git specific, since I get the same conversion with a simple C program compiled with Mingw:

```c
#include <windows.h>
#include <stdio.h>

int main(int argc, char **argv)
{
    LPTSTR cmd  = GetCommandLine();
    printf("cmdline: %s\n", cmd);
    for (int i = 0; cmd[i]; i++) {
        printf("%02X", cmd[i]);
    }
    printf("\n");

    for (int i = 0; i < argc; i++) {
        printf("arg%d: %s\n", i, argv[i]);
    }
    return 0;
}
```

**Comment by Eli-Zaretskii** [comment]
GetCommandLine doesn't support Unicode, (unless you define _UNICODE or somesuch).  Even if the program was invoked with "wide" (i.e. UTF-16) characters, GetCommandLine, which resolves into GetCommandLineA as long as _UNICODE is not defined, will get you those characters converted to the current system codepage, with blanks standing for characters that aren't supported by that codepage.

IOW, there are two different parts to this riddle: one is how the calling program invokes the sub-program, the other how the called program reads its command-line arguments.  If one of them doesn't use the "wide" APIs, the result will be the same: conversion to current codepage, performed transparently by Windows behind the program's back.

Git for Windows does read its command-line arguments using wide APIs, but Emacs doesn't use those wide APIs when invoking Git, for technical reasons explained in comments in Emacs sources.

**Comment by Eli-Zaretskii** [comment]
That being said, the OP's system is set up for Chinese, so using Chinese file names on the Git command line ought to work.  Therefore, I'd suggest more digging.

One problem might be the shell run by Magit in that session (does it indeed run a shell?).  If that is indeed a shell, what shell is that?  Could that shell be the problem?

**Comment by npostavs** [comment]
> One problem might be the shell run by Magit in that session (does it indeed run a shell?).

No, magit calls git using `call-process`.

**Comment by Eli-Zaretskii** [comment]
Then perhaps Magit encodes the Git command-line arguments differently from the current codepage (utf-8, for example)?

**Comment by npostavs** [comment]
Oh, I didn't realize magit should apply any encoding to arguments of `call-process`, I think it just passes in the strings without encoding them.

**Comment by Eli-Zaretskii** [comment]
If it doesn't encode the arguments, they get encoded inside `call-process`, and they should be encoded correctly, as long as the defaults for process encoding are set correctly.

I guess it is now up to @zhixing2017 to tell us whether there are any customizations of coding-systems in the init files, and if so, what are they.  Alternatively, maybe try the same commands in `emacs -Q`, if that's feasible.

**Comment by npostavs** [comment]
> If it doesn't encode the arguments, they get encoded inside call-process, and they should be encoded correctly, as long as the defaults for process encoding are set correctly.

That would be the `cdr` of `default-process-coding-system`, right? We do change the `car` to `utf-8`, but that should only affect decoding of git's output, if I understand correctly.

**Comment by Eli-Zaretskii** [comment]
Not necessarily.  Unless the user customized the defaults, the default on Windows is `undecided`, and in that case Emacs tries several fallbacks, see `complement_process_encoding_system`.  It is best simply to step into call_process in the actual use case and on the actual target machine, and see what encoding is being used for the command-line arguments.

And btw, where in the sources does Magit change `default-process-coding-system` for this use case, and where is the command cited by the OP invoked?

**Comment by npostavs** [comment]
> where in the sources does Magit change `default-process-coding-system` for this use case

[`magit-process-file`](https://github.com/magit/magit/blob/2.10.3/lisp/magit-process.el#L328) let-binds `default-process-coding-system` to the result of [`magit--process-coding-system`](https://github.com/magit/magit/blob/2.10.3/lisp/magit-process.el#L708) before calling `process-file`.

> and where is the command cited by the OP invoked?

The OP invoked [`magit-stage`](https://github.com/magit/magit/blob/2.10.3/lisp/magit-apply.el#L199), which dispatches to [`magit-stage-untracked`](https://github.com/magit/magit/blob/2.10.3/lisp/magit-apply.el#L259). Here is an abridged backtrace (I removed most non-funcall frames, and replaced the value of `magit-git-global-arguments` apart from `"--no-pager"` with `...`) which should show the relevant functions:

```
Debugger entered--entering a function:
* call-process("C:/Git-2.x/mingw64/libexec/git-core/git" nil #<buffer *magit-process: magit> nil "--no-pager" ... "add" "--" "好.txt")
  process-file("C:/Git-2.x/mingw64/libexec/git-core/git" nil #<buffer *magit-process: magit> nil "--no-pager" ... "add" "--" "好.txt")
  (let ((process-environment (append (magit-cygwin-env-vars) process-environment)) (default-process-coding-system (magit--process-coding-system))) (apply (function process-file) args))
  magit-process-file("C:/Git-2.x/mingw64/libexec/git-core/git" nil #<buffer *magit-process: magit> nil "--no-pager" ... "add" "--" "好.txt")
  magit-call-process("C:/Git-2.x/mingw64/libexec/git-core/git" "--no-pager" ... "add" "--" "好.txt")
  magit-call-git(("add" nil "--" ("好.txt")))
  magit-run-git("add" nil "--" ("好.txt"))
  magit-stage-untracked(nil)
  magit-stage(nil)
  funcall-interactively(magit-stage nil)
  call-interactively(magit-stage nil nil)
  command-execute(magit-stage)
```

**Comment by Eli-Zaretskii** [comment]
> >  where in the sources does Magit change default-process-coding-system for this use case
> magit-process-file let-binds default-process-coding-system to the result of magit--process-coding-system before calling process-file.

But that just changes the EOL conversion, whereas you said it changes the default to UTF-8.  What am I missing?

**Comment by Eli-Zaretskii** [comment]
OK.  But all this doesn't really matter, as I think what you get is the preferred coding-system.  Which should be according to the user locale, unless the OP customized it.  If they customized it to UTF-8, then that could well be the source of their grief.

**Comment by zhixing2017** [comment]
**Sorry** to be slow replying, it has been exceptionally busy over the last few days. 

I test it using the bare Emacs. No error. Sorry for my mistake.

I think the error occured possibly because of the spacemacs, but I do not know the reason.

**Comment by tarsius** [comment]
> I think the error occured possibly because of the spacemacs, but I do not know the reason.

Have you tried with just vanilla spacemacs and none of you own customizations? If the error occurs in that case also, then you should report that in the spacemacs issue tracker.

**Comment by zhixing2017** [comment]
Yes, I have tried that.

And spacemacs on windows does not work well.
However, on linux, it works very well.

**Comment by tarsius** [comment]
I am closing this as the problem appears to be causes by some customization(s) done by the user and our their starter-kit.

**Comment by zhixing2017** [comment]
The code below obtained from [emacs-china](https://emacs-china.org/t/topic/3894/23?u=zhixing) works well.
```
(when (eq system-type 'windows-nt)
  (set-default 'process-coding-system-alist
			   '(("[pP][lL][iI][nN][kK]" gbk-dos . gbk-dos)
				 ("[cC][mM][dD][pP][rR][oO][xX][yY]" gbk-dos . gbk-dos)
				 ("[rR][gG]" utf-8-dos . gbk-dos)
				 ("[gG][iI][tT]" utf-8-dos . gbk-dos)
				 )))
```

**Comment by Eli-Zaretskii** [comment]
I don't understand why you need to do that for Git: AFAIK Emacs does that automatically.  And I believe you must both encode and decode stuff in UTF-8 when you communicate with Git.

I don't know what `rg` is, but in general having different coding-systems in the DECODE and ENCODE parts of the cons cell is extremely unusual, and you should be very sure this is TRT.

**Comment by zhixing2017** [comment]
It is the code problem. The communication between git and emacs on windows does not work well. 
After the settings, it works fine. 

[rg](https://github.com/BurntSushi/ripgrep) cannot search Chinese on Windows without the code.

**Comment by iquiw** [comment]
For me, in Japanese, similar setting does not work well.
```emacs-lisp
(add-to-list 'process-coding-system-alist '("git" . (utf-8-unix . cp932-dos)))
```
If I set it, Magit can do well for file name, but not for file contents (staging hunks with Japanese characters cause `patch failed` error).
If I don't set it, Magit can do well for file contents, but not for file name (as reported in this issue).

**Comment by Eli-Zaretskii** [comment]
I think for Magit, you need to set both ENCODE and DECODE parts of `process-coding-system` to UTF-8.  I wouldn't necessarily set it to utf-8-dos, I would have left it for Emacs to decode the EOLs.

**Comment by npostavs** [comment]
> I think for Magit, you need to set both ENCODE and DECODE parts of process-coding-system to UTF-8.

Doesn't that mess up encoding of filename arguments, like you said in https://github.com/magit/magit/issues/3111#issuecomment-324118156?

**Comment by Eli-Zaretskii** [comment]
It does, but if that causes trouble, Magit needs to bind `coding-system-for-write` around Git invocations where that could be an issue.

In any case, using cp932 for encoding stuff sent to Git is hardly going to DTRT.

**Comment by npostavs** [comment]
Supposing we want default codepage encoding for the filename arguments, and utf8 encoding for the text sent to the same Git invocation, are we out of luck?

**Comment by Eli-Zaretskii** [comment]
I'd try encoding by hand either the file-name arguments or the text to be sent, before giving up.  But yes, this is a tricky corner on Windows.

**Comment by npostavs** [comment]
Hmm, encoding the text input might be easier since we know it has to be utf-8. Or is there some way to encode in "the current codepage" from lisp?

**Comment by Eli-Zaretskii** [comment]
You could use `w32-ansi-code-page`, I think.

**Comment by npostavs** [comment]
> You could use w32-ansi-code-page, I think.

Thanks, I think finally understand what's going on.

---

@zhixing2017 @iquiw please try the patch in #3250. It should work regardless of your configuration.

**Comment by iquiw** [comment]
@npostavs It works like a charm!  I could stage both Japanese file name and contents.
Thanks! 👏
