### ISSUE TITLE
Magit adds a lambda to `find-file-hook`

### ISSUE THREAD

**Issue by Ambrevar** [magit/magit#3114]
Magit 20170621.710, Git 2.13.1, Emacs 25.2.1, gnu/linux

When I load Magit is this lambda function added to `find-file-hook`:

```
#[0 "\302\301!\210\303\304!8\211\207"
  [buffer-file-name auto-revert-tail-pos make-local-variable 7 file-attributes]
 3]
```

It's bad practice to add lambdas to hook as it makes it harder to remove them.
You should use a named function instead.

**Comment by kyleam** [comment]
I can't locate that in Magit's source.  I'm pretty sure it's from
autorevert.el (line 316 in Emacs 25.2.1).  Please raise the issue
upstream.

**Comment by tarsius** [comment]
@kyleam I just started to type... :smile:

**Comment by tarsius** [comment]
Ha! There was something left to be done :wink:

**Comment by Ambrevar** [comment]
Reported upstream: http://debbugs.gnu.org/cgi/bugreport.cgi?bug=27502
