### ISSUE TITLE
Apple Git-81 doesn't recognize git-name-rev --exclude option. Breaks magit-rev-name

### ISSUE THREAD

**Issue by lambdageek** [magit/magit#3117]
Magit 20170702.858, Git 2.11.0 (Apple Git-81), Emacs 25.2.1, darwin

Expected behavior:
 When I'm looking at a `magit-log` buffer (`l b`) and point is on the name of a branch `b k` should default to the branch at point as the default to delete.

Actual behavior:
  Default branch to be deleted is the currently checked out branch.

(`b k` behaves as expected in a `magit-refs` buffer (`y`))

**Comment by tarsius** [comment]
Magit is supposed to be have the way you want it to behave and I just verified that it does for me.

Are you using a third-party completion framework? (It's supposed to work with those too, but that might help narrow the issue down.)

**Comment by tarsius** [comment]
Also try to reproduce this issue using [`magit-emacs-Q-command `](https://magit.vc/manual/magit/Debugging-Tools.html).

**Comment by lambdageek** [comment]
Confirmed - does the wrong thing with `magit-emacs-Q-command`, too.

**Comment by tarsius** [comment]
I just tried that too and it works for me. Though maybe I misunderstood "point is on the name of a branch". Do you mean "point is on a line on which later a branch name appears"? Or do you mean "Multiple branches point at the same commit, including the current branch. When point is on a branch name in a line in a log (not just anywhere in that line), then offer that command as default."?

**Comment by lambdageek** [comment]
I've tried both.  Doesn't seem to work even when point is on a line where there's just a single branch which is different from the current branch.

I just realized there might be something else in play - I have `hub` installed - `brew install hub`

```
$ brew info hub
hub: stable 2.2.9 (bottled), devel 2.3.0-pre9, HEAD
Add GitHub support to git on the command-line
https://hub.github.com/
/usr/local/Cellar/hub/2.2.9 (10 files, 9MB) *
  Poured from bottle on 2017-06-06 at 13:45:17
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/hub.rb
```

**Comment by lambdageek** [comment]
If I try `magit-checkout` (`b b`) with point on the name of a branch it offers to checkout the numeric commit id instead of the branch name, by the way.  Any git plumbing commands that you'd like me to try?

**Comment by tarsius** [comment]
Try

```lisp
(list (magit-branch-at-point)
      (magit-get-previous-branch)
      (magit-get-current-branch))
```

on that line. The first non-nil one will be offered as the default. (The last one doesn't make much sense for this command, it is used because this shares code with other commands. But usually one of the earlier two is non-nil, so it should not matter.)

**Comment by tarsius** [comment]
Also `(magit-name-branch "<commit-sha>")` should return the appropriate commit.

**Comment by lambdageek** [comment]
(I'm working with https://github.com/lambdageek/Ward).

With point on the line for c14c35d
```
(nil nil "hack-coop-annotations")
```

```
M-: (magit-name-branch "c14c35d")
nil
```

**Comment by tarsius** [comment]
What about

```shell
$ git name-rev --name-only --no-undefined --refs='refs/heads/*' c14c35d
hack-coop-annotations
$ git name-rev --name-only --no-undefined --refs='refs/remotes/*' c14c35d
remotes/origin/hack-coop-annotations
```

**Comment by lambdageek** [comment]
```
$ git name-rev --name-only --no-undefined --refs='refs/heads/*' c14c35d
ward-keyword
$ git name-rev --name-only --no-undefined --refs='refs/remotes/*' c14c35d
remotes/lambdageek/ward-keyword
$ git name-rev --name-only --no-undefined --refs='refs/heads/*' 1d35864
hack-coop-annotations
$ git name-rev --name-only --no-undefined --refs='refs/remotes/*' 1d35864
remotes/lambdageek/hack-coop-annotations
$ git status
On branch hack-coop-annotations
nothing to commit, working tree clean
```

(Same output both in Terminal.app and in M-x shell inside magit-emacs-Q-command)

**Comment by tarsius** [comment]
```lisp
(magit-git-string "name-rev" "--name-only" "--no-undefined" "--refs=refs/heads/*" "c14c35d")
```

**Comment by tarsius** [comment]
Also what does `M-x magit-version` print?

**Comment by lambdageek** [comment]
`M-: (magit-git-string "name-rev" "--name-only" "--no-undefined" "--refs=refs/heads/*" "c14c35d")`

`"ward-keyword"`

**Comment by lambdageek** [comment]
`M-x magit-version`
`Magit 20170702.858, Git 2.11.0 (Apple Git-81), Emacs 25.2.1, darwin`

**Comment by lambdageek** [comment]
I'm happy to keep trying things, but I am going to be a bit busy for the next few hours so might be more delay in my replies.

**Comment by tarsius** [comment]
Yeah me too.

That ... seems impossible.
Add debug statements to `magit-branch-at-point` and the function it calls.

**Comment by lambdageek** [comment]
Got it `--exclude=*/refs/heads/*` is the problem:

```
magit-git-my-string args are <(name-rev --name-only --no-undefined --refs=refs/heads/* --exclude=*/refs/heads/* c14c35d)>
```

(`magit-git-my-string` is just a copy/paste of `magit-git-string` with a couple of `message`s I call it from `magit-rev-name`)

that `--exclude=*/refs/heads/*` is  coming from https://github.com/magit/magit/blob/master/lisp/magit-git.el#L814

and indeed `M-:` `(magit-rev-name "c14c35d" "refs/heads/*")` is `nil`

**Comment by lambdageek** [comment]
It's apple git's fault `--exclude` is not a recorgnized option.

```
$ git name-rev --name-only --no-undefined --exclude='*/refs/heads/*' --re
fs='refs/heads/*' c14c35d
error: unknown option `exclude=*/refs/heads/*'
usage: git name-rev [<options>] <commit>...
   or: git name-rev [<options>] --all
   or: git name-rev [<options>] --stdin

    --name-only           print only names (no SHA-1)
    --tags                only use tags to name the commits
    --refs <pattern>      only use refs matching <pattern>

    --all                 list all commits reachable from all refs
    --stdin               read from stdin
    --undefined           allow to print `undefined` names (default)
    --always              show abbreviated commit object as fallback
```

**Comment by lambdageek** [comment]
Installing git from homebew fixes magit for me.

```
$ git --version
git version 2.13.2
$ git name-rev --name-only --no-undefined --refs='refs/heads/*' --exclude
='*/refs/heads/*' c14c35d
ward-keyword
```

**Comment by tarsius** [comment]
Ah, then I think its a regression in Magit, we started using that argument just recently.

**Comment by kyleam** [comment]
Yes, my mistake.  It seems that `--exclude` was added after Git v2.13.

**Comment by kyleam** [comment]
I've reverted 9ab6d5548 for now, since completely breaking
`magit-rev-name` for many users is obviously worse than going back to
the longstanding but undesirable behavior of returning wip ref names
in some cases.

Sadly, this isn't as simple as just excluding wip names (or more
generally, names that don't start with `pattern`) from the return
value because then we have no way of telling Git we want it to give us
another name.
