### ISSUE TITLE
Release magit-section.el as an independent package

### ISSUE THREAD

**Issue by tarsius** [magit/magit#3118]
... like is already the case for `magit-popup`.

In both cases I plan to write a replacement, taking my knowledge about their limitations and potential into account. See #2956, #2957, and #2958.

However this is taking longer than initially anticipated and there are people who would like to use Magit's ui concepts in other packages now, so I should release `magit-section.el` as an independent package instead of waiting for the replacement.

**Comment by tarsius** [comment]
Also try to reproduce this issue using [`magit-emacs-Q-command `](https://magit.vc/manual/magit/Debugging-Tools.html).

**Comment by tarsius** [comment]
Actually let's not. While it probably still be a few months until the replacement is ready, releasing a `magit-section` package now would cause a few issues:

* Someone (tm) would have to keep maintaining it.
* While I expect to eventually *replace* `magit-section.el` with the new implementation, I will like make some incremental changes to `magit-section.el` before then to make the transition smoother. Some of these changes will likely be breaking changes.
* I wasn't actually asked to release this *recently*.
* If people actually started using it, then it would become necessary to improve the documentation. But I would much rather write an implementation with fewer limitations than to document the limitations.

**Comment by alphapapa** [comment]
@tarsius Forgive the noise, but does that wontadd mean that you've decided to not release the section code as a separate package, or just not the current implementation?  :)

**Comment by tarsius** [comment]
It mostly means that it probably won't be done during the "Year of Magit" (making it more likely the stuff I really want to implement gets done). But I won't lose this issue and come back to it eventually.

I am going to work on `magit-section.el` again soon, but without the goal of separating it from Magit anytime soon.

**Comment by alphapapa** [comment]
Ok, thanks.  I look forward very much to both!

**Comment by alphapapa** [comment]
@tarsius It took a lot of trial-and-error, but I finally came up with this: https://github.com/alphapapa/magit-todos/blob/async-ag/magit-todos.el#L438  It allows me to insert a section asynchronously, after the status buffer has been created.  It's working pretty well so far.  The key was setting `magit-insert-section--parent` to `magit-root-section` before calling `magit-insert-section`.

I don't know if you will find this terrifying or amusing... :)

**Comment by tarsius** [comment]
It might be easier to insert a stub section initially and later only populate it in the callback

**Comment by alphapapa** [comment]
Thanks, that seems like a good idea.  I have noticed that this currently flickers a little bit when it inserts the section, and that might fix it.  But I guess that when there are no items to insert into the section, I'll have to cancel the section after it was created.
