### ISSUE TITLE
Gravatars aren't added to diff view, only shown if cached

### ISSUE THREAD

**Issue by spatz** [magit/magit#3121]
Using: Magit 20170709.1256, Git 2.13.2, Emacs 25.2.1, gnu/linux

When showing a commit for example, if the gravatar isn't cached then it isn't shown and is never added to the buffer. If I close this buffer and show the same commit again then the gravatars are shown.

I've set `magit-revision-show-gravatars` to `'("^Author:     " . "^Commit:     ")`.

**Comment by tarsius** [comment]
Thanks for reporting!

**Comment by spatz** [comment]
Wow that was fast.
Thanks!
