### ISSUE TITLE
Pulling from remote pulls from all branches & not just the current branch

### ISSUE THREAD

**Issue by pawandubey** [magit/magit#3122]
**Reproduction Steps**
- `M-x magit-status`
- `b b` and select master if not already there
- `F u` assuming you have the upstream set to `origin/master`

**Observed behavior**
- Magit runs `git pull origin`, ignoring the `master` part
- Error encountered:
```
$ git … pull origin
remote: Counting objects: 4664, done.        
Resolving deltas: 100% (3559/3559), completed with 1334 local objects.
error: cannot lock ref 'refs/remotes/origin/10f_I18n_tags': is at 901685fa57e4f160dfed80eb7623f0513c84b009 but expected badc4099fef53afea576de82a6f7c55821e28497
```

**Expected Behavior**
- Magit to run `git pull origin master`
- The pull to successfully complete

**Magit Version**
20170528.740 with Emacs 25.2.1 on Git 2.11.0 on macOS Sierra

**Comment by pawandubey** [comment]
I encounter this with great consistency on my company's repository while syncing with master. I don't encounter it with smaller repos. I suppose it's actually git struggling to do it's thing because of a lot of refs in memory or something because it also happens when I run `git pull origin` from the terminal but works perfectly fine when running `git pull origin master`, restricting the branch.

I suppose this can be a problem with Git ultimately but to me it makes more sense for magit to respect the branch name while performing a pull.

**Comment by npostavs** [comment]
Do any of the solutions suggested at https://stackoverflow.com/questions/11796580/git-pull-error-error-remote-ref-is-at-but-expected/27694720 help?

**Comment by pawandubey** [comment]
Ah yes, you are right. I do have two separate branches named:
```
remotes/origin/10F_I18n_tags
remotes/origin/10f_I18n_tags
```
And a case-insensitive HFS+ system.

However I never encounter this because I never wildcard pull with `git pull origin`, I always specify a branch with it. So the issue here is why isn't magit respecting the current branch's tracking branch while performing the pull?

**Comment by kyleam** [comment]
> So the issue here is why isn't magit respecting the current branch's tracking branch while performing the pull?
See fd40b3a9 (magit-pull-from-upstream: don't explicitly specify remote branch, 2016-05-10).

**Comment by pawandubey** [comment]
@kyleam thanks for providing the context. This is not something I do (so I disagree with the expectations part, but then I am just one of many) but since there has been some thought behind this already, I am not going to pursue this and am gonna close this issue. In my opinion it would be better to have the branch specified while pulling but that is a discussion that I'd leave for the core team to think and debate about.

Thanks for the help and making this great tool.
