### ISSUE TITLE
magit melpa package broken for emacs 25.1.1

### ISSUE THREAD

**Issue by aathan** [magit/magit#3123]
M-x package-install magit yields: https://melpa.org/packages/dash-20170523.219.el: Not found

**Comment by npostavs** [comment]
Does `M-x package-refresh-contents` help?

**Comment by tarsius** [comment]
Most likely you just have to update as @npostavs suggested. If that doesn't help, then it might be an issue with Melpa, but it certainly isn't a Magit issue.
