### ISSUE TITLE
View commit details from rebase view

### ISSUE THREAD

**Issue by darkfeline** [magit/magit#3125]
It would be useful to be able to run `magit-show-commit` or similar from `git-rebase-mode` when doing complex/large interactive rebases.

**Comment by npostavs** [comment]
I believe you already can, try hitting `SPC` on a commit line.

**Comment by darkfeline** [comment]
Thanks.  I believe I did not see that documented, so unless it was added in the past three days, can we keep this bug open for getting that documented?
