### ISSUE TITLE
Feature suggestion: provide "binary" or compiled package

### ISSUE THREAD

**Issue by HaraldKi** [magit/magit#3126]
Feature suggestion: provide pre-compiled package for which it is sufficient to

a) untar/unzip to somepath
b) add (load "/path/to/somepath") to some Emacs init file

to get started.

Rationale 1: the quicker the "first install" the easier it is to fascinate new users, or even commiters.

Rationale2: The installation methods provided are just that bit to elaborate for a "sounds cool, let me quickly try it" experience, as there are:

- Elpa -- no idea whatever that is, looks like the N+1st package manager for software and I need to install this one first before even getting to magit.

- Make -- looks easy enough, ehem, wait, you need "dash" (hmm, have seen this on my machine), with-editor (hähhhh?).

- Distro package manager: oh, my, mine provides only 1.ageold, should I really try that one first to get a good impression?

**Comment by tarsius** [comment]
Are you an Emacs user or do you just want to use it so that you can use Magit?

If it is the former then you really have to learn how to use `package.el` (including Melpa, not just GNU Elpa). It is worth the effort, there are other good packages out there that are not distributed with Emacs. If you just want get started and hope for the best, then ten minutes should do it. If you want to understand what's going on, then you should invest half an hour reading documentation.

**Comment by tarsius** [comment]
That being said, I do plan to improve the on-boarding for "non-Emacs users". But that is likely to come in the form of documentation that covers every step including the installation of Emacs, Git and all other dependencies, and setting `$HOME` and configuring Git itself in great detail.

Also see #2994.

**Comment by HaraldKi** [comment]
Indeed I am a long time emacs user, but for years I can rely on just what my distro (ubuntu / mint) provides for installation or I just download a tar.gz, unzip it in my .emacs.d add a curse to my startup file and off it goes.

**Comment by npostavs** [comment]
> Elpa -- no idea whatever that is, looks like the N+1st package manager for software and I need to install this one first before even getting to magit.

For completeness, Emacs 24.3 and above comes with package.el builtin, which will install things from the GNU ELPA repository by default. To get magit, you just need to configure it to access MELPA as well (as [explained in the manual](https://magit.vc/manual/magit/Installing-from-an-Elpa-Archive.html)).

> but for years I can rely on just what my distro (ubuntu / mint) provides for installation

Then I don't see what's wrong with installing the [Ubuntu package](https://packages.ubuntu.com/bionic/elpa-magit).
