### ISSUE TITLE
magit-show-commit to move to a corresponding line in diff

### ISSUE THREAD

**Issue by xged** [magit/magit#3130]
Would be nice if `magit-show-commit` (`magit-blame-mode-map`) would (intuitively) move to a corresponding line (at point or the one that blaming was done on) in diff.

Additionally, I would like that `magit-show-commit` window would be fullscreen (eg git-magit-status-fullscreen).

**Comment by tarsius** [comment]
From #2995:

> Jumping from a diff to a file/blob, is already well supported. But the opposite is not, and that is just as useful. I would say this is the biggest gap that still exists, and one of the few that have been known for a long while without getting stuffed.
