### ISSUE TITLE
Incorrect syntax highlighting with non-default commit.cleanup setting

### ISSUE THREAD

**Issue by Deewiant** [magit/magit#3137]
Magit always treats `#` (or the value of `core.commentChar`) as a comment starter in commits, but non-default values of the `commit.cleanup` setting allow lines beginning with `#` to stay as part of the commit message. Personally I set it to `scissors`, which lets me see metadata while writing a commit message but still allows commit messages to start with `#`. Magit then highlights something like the following incorrectly:

```
# This is highlighted as a comment though it's the summary

This is highlighted as a summary though it's part of the message body.
```

Not a big deal of course, as it's only a minor visual issue and only for commits whose summary begins with `#`.

```
Magit 20170729.2104, Git 2.13.3, Emacs 25.2.1, gnu/linux
```

**Comment by tarsius** [comment]
Could you help me understand this:

```
       --cleanup=<mode>
           This option determines how the supplied commit message should be
           cleaned up before committing. The <mode> can be strip, whitespace,
           verbatim, scissors or default.

           strip
               Strip leading and trailing empty lines, trailing whitespace,
               commentary and collapse consecutive empty lines.

           whitespace
               Same as strip except #commentary is not removed.
```

What is a "commentary". And why is "#commentary", not just "commentary", used in the last sentence?

**Comment by tarsius** [comment]
Anyway, this could be difficult to implement.

```
           scissors
               Same as whitespace, except that everything from (and including)
               the line "# ------------------------ >8
               ------------------------" is truncated if the message is to be
               edited. "#" can be customized with core.commentChar.
```

I don't think `font-lock` can be easily be told to use different rules before and after a certain line. Wouldn't it be easier to set `core.commentChar` to something you expect to never use in a commit message?

**Comment by Deewiant** [comment]
"commentary" refers to comments, I think. I didn't actually notice that it's used without "#", in "#commentary" it seemed like a clarification that comments usually start with "#". Probably an accident that both forms are used.

I prefer the `scissors` approach to an arbitrary `core.commentChar` because it seems safer to me: with the latter I might mess up a commit message accidentally if I'm not paying attention, if that character that I expected to never use *does* come up.

If it can't be done easily (I suppose it can be done *somehow* given things like https://github.com/purcell/mmm-mode) that's fair enough, I can live with the not-entirely-correct syntax highlighting. :-)

**Comment by tarsius** [comment]
I think I'll just leave this as-is. I'll keep #3138 open for the time being, but I might end up not doing anything about that either.
