### ISSUE TITLE
Allow to change repository from magit-status

### ISSUE THREAD

**Issue by TLINDEN** [magit/magit#3139]
Currently, in order to change the current repository, you have to `C-u M-x magit-status` and close the old `magit-status` buffer. It would be great to change the repository inside the running `magit-status` buffer. The command letter `C` would be a good choice for this as it's currently not in use.

Related, but minor: why is it, that `magit-status` stays in the current repository even if I completely kill all magit buffers and start from scratch? I would expect this behavior with burying only.

Thanks in advance,
Tom

**Comment by bastianbeischer** [comment]
Not strictly related, but you may find the emacs extension "projectile" useful in this context. You can get it from MELPA. After installing it I use this function:

```elisp
(defun projectile-use-magit-if-possible ()
  "If the project being switched to is a git repository, invoke
magit-status on the project root directory. Use dired otherwise."
  (interactive)
  (if (and (executable-find "git")
           (eq (projectile-project-vcs) 'git))
      (magit-status (projectile-project-root))
    (dired (projectile-project-root))))

(setq projectile-switch-project-action 'projectile-use-magit-if-possible)
```
It's also possible to work with Magit in several projects at the same time as it sticks to the current project consistently. I also define some quick switch short cuts for projectile:

```elisp
  (define-key projectile-mode-map (kbd "C-c p 1") (lambda() (interactive) (switch-project-by-name "/path/to/project1")))
  (define-key projectile-mode-map (kbd "C-c p 2") (lambda() (interactive) (switch-project-by-name "/path/to/project2")))
  (define-key projectile-mode-map (kbd "C-c p 3") (lambda() (interactive) (switch-project-by-name "/path/to/project3")))
```

Maybe this is helpful for you.

**Comment by TLINDEN** [comment]
Well thanks, but I don't use projectile, my current workaround looks like this:
```elisp
(defun tvd-magit-status ()
  "Always call `magit-status' with prefix arg."
  (interactive)
  (let ((current-prefix-arg t))
    (call-interactively 'magit-status)))
(defalias 'git 'tvd-magit-status)
```
With this I do  just <kbd>M-x git</kbd> and will always asked for the repository.

**Comment by npostavs** [comment]
What do you mean you have to "close the old `magit-status` buffer"? Can't you just leave it open?
Did you know that you can have multiple `magit-status` buffers in different repositories at the same time? 

> Related, but minor: why is it, that `magit-status` stays in the current repository even if I completely kill all magit buffers and start from scratch? I would expect this behavior with burying only.

I don't understand this question at all. Why would killing other buffers change the current directory of the magit-status buffer? (I assume when you say "kill all magit buffers" you exclude the magit-status buffer from this list?)

**Comment by TLINDEN** [comment]
> What do you mean you have to "close the old magit-status buffer"?

I don't have to, I just observed that even when I kill *ALL* buffers, magit-status starts with the same repo as the last time I used it.

> Did you know that you can have multiple magit-status buffers in different repositories at the same time?

Of course, I know, but this is not the point.

I'd expect if there's no magit-status buffer (or any other magit buffer) left anymore, it would restart from scratch and ask me to select from my repository list.

**Comment by TLINDEN** [comment]
Simple demonstration if the idea:
```elisp
(defun my-change-repo ()
  (interactive)
  (let ((dir (magit-read-repository)))
    (magit-mode-bury-buffer)
    (magit-init dir)))
(define-key magit-mode-map (kbd "C") 'my-change-repo)
```

**Comment by npostavs** [comment]
> I don't have to, I just observed that even when I kill ALL buffers, magit-status starts with the same repo as the last time I used it.

The decision of whether to query for a repository is completely unrelated to whether you've killed other buffers or not. It only checks whether the current buffer is in a git repository.

**Comment by tarsius** [comment]
> I'd expect if there's no magit-status buffer (or any other magit buffer) left anymore, it would restart from scratch

`magit-status` does always "start from scratch".

> and ask me to select from my repository list.

The only time `magit-status` (without a prefix argument) does ask you for which repository it show you the status, is when the current buffer's `default-directory` (i.e. the "working directory") is not located inside a repository.

This is very convenient because you can always just press `C-x g` to show that status of the current repository from e.g. a buffer which visits a file that is located in that repository.

So `magit-status` is like `git status`, while you expect it to behave like `cd $(read var; echo var); git status`. `tvd-magit-status ` is a possible implementation of that command. (`my-change-repo` on the other hand is not a good idea `magit-init` isn't intended to show the status of an existing repository, it is used to creates a new repository.)

**Comment by TLINDEN** [comment]
Thanks for the clarification!
