### ISSUE TITLE
Emacs fails to respond with global-git-commit-mode

### ISSUE THREAD

**Issue by akiritsu** [magit/magit#3140]
When I use Emacs 25.2 on my Surface 3 (windows 10), it will fail to respond for more than 10 seconds (up tp 3minutes) if I use some functions. Typically every time executing "shell" and "run-haskell". Casual operation may also trigger this.

I'm sure its caused by this package coz when I blocked up this package, my Emacs turned healthy.

It also increases startup time for about 12 seconds in my Surface. All above won't happened in my laptop.

I don't mean to bother you, there may be someone runs Emacs on weak Laptops and it may happen again.

**Comment by tarsius** [comment]
> I'm sure its caused by this package coz when I blocked up this package, my Emacs turned healthy.

I am not because you didn't mention what actions are slow, except for a few that don't have anything to do with Magit.

See https://magit.vc/manual/magit/Performance.html for information about some performance issues and potential remedies. Also note that I plan to improve performance considerably but that doing so is a lot of work (#2982).

At this point I don't think I can do much to help you, I'm afraid.

**Comment by tarsius** [comment]
Ah, sorry overlooked that you are specifically talking about `global-git-commit-mode`.

**Comment by akiritsu** [comment]
Toggle global-git-commit-mode causes a significant latency.  As well as creating new buffers with other processes. I'm sorry that I didn't record what CASUAL operations will trigger this. (if you need this information, i can do some experiments.) Oh, it seems when guide-key mode creates new buffers, it will happen as well. I'm not sure whether it's a bug.

**Comment by tarsius** [comment]
Anyway, I don't see how that mode can cause unrelated things to become slow. It basically boils down to:

```lisp
(add-hook 'find-file-hook 'git-commit-setup-check-buffer)

(defun git-commit-setup-check-buffer ()
  (and buffer-file-name
       (string-match-p git-commit-filename-regexp buffer-file-name)
       ;; This is hardly ever reached:
       (git-commit-setup)))
```

**Comment by akiritsu** [comment]
I'll try more things on that. Sorry for offhand questioning and thank you for your reply :smile:

**Comment by npostavs** [comment]
Can you `M-x toggle-debug-on-quit` and get a backtrace by hitting `C-g` when it's spinning?

**Comment by akiritsu** [comment]
I've checked the backtrace and it seems not caused by your packages. I'm very sorry about questioning you at here. Thanks anyway!
