### ISSUE TITLE
Add --no-verify switch to rebase popup

### ISSUE THREAD

**Issue by asimpson** [magit/magit#3142]
The rebase popup does not include a switch to add the `--no-verify` flag for rebases.

`Magit 2.10.3, Git 2.10.0, Emacs 25.2.1, darwin`

**Comment by kyleam** [comment]
When a popup doesn't include an option you use, you can [add it]
yourself.

[add it]: https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands

**Comment by asimpson** [comment]
@kyleam great callout! I feel like it should be part of the standard popup since it's there for push ¯\_(ツ)_/¯

**Comment by kyleam** [comment]
> I feel like it should be part of the standard popup since it's there for push

Fair enough.  `--no-verify` is also in the commit popup (though on a
different key :/).

I wouldn't be against adding `--no-verify` to the rebase popup and
making `--no-verify` use a consistent key in the commit, push, and
rebase popups.

**Comment by asimpson** [comment]
I'd be happy to try and contribute the PR that resolves this, but I'd probably take me longer than someone more experienced.

**Comment by kyleam** [comment]
No problem.  I'll let it sit for a bit to give others a chance to
comment/object.

Regarding making the key consistent across popups, I favor push's `-h`
over commit's `-n`.

**Comment by kyleam** [comment]
>> I feel like it should be part of the standard popup since it's there for push
>
> Fair enough. --no-verify is also in the commit popup

Thinking about this more, I don't know.  Yes, `--no-verify` is in the
default options for the push and commit popups, but these are for
different hooks.  So the question is whether users encounter a
pre-rebase hook enough that it's worth adding `--no-verify` as a
default switch in the rebase popup (which already has quite a few
switches).  I'd say "probably not", but let's wait to see if others
feel differently.

Also, note that there is a proposed plan to define nearly all
available arguments, hiding most of them by default and letting users
easily activate them (#2941).

**Comment by asimpson** [comment]
Yeah I see both sides of it which is why I’m happy to have a discussion around it here.

I would :heart: to pick and choose what flags show up in the popups, that would be incredible!

**Comment by tarsius** [comment]
I'm fine with this.

**Comment by kyleam** [comment]
> I'm fine with this.

OK, added in #3144.

**Comment by asimpson** [comment]
:clap: fantastic!
