### ISSUE TITLE
strange indentation in diffs for current branch 

### ISSUE THREAD

**Issue by Pitometsu** [magit/magit#3143]
After merging branch, in *\*magit: reponame\** buffer, at unmerget conflict:
```diff
++<<<<<<< HEAD
 +    _liveStreamingControl = [[LiveStreamingControl alloc] init];
 +    _liveStreamingControl.delegate = self;
 +    [self.view addSubview:_liveStreamingControl];
++=======
+     _slideToStopView = [[SlideToStopView alloc] init];
+     _slideToStopView.delegate = self;
+     [self.view addSubview:_slideToStopView];
++>>>>>>> origin/feature-studio-mode-redesign
```

Shouldn' be instead:

```diff
++<<<<<<< HEAD
+    _liveStreamingControl = [[LiveStreamingControl alloc] init];
+    _liveStreamingControl.delegate = self;
+    [self.view addSubview:_liveStreamingControl];
++=======
+     _slideToStopView = [[SlideToStopView alloc] init];
+     _slideToStopView.delegate = self;
+     [self.view addSubview:_slideToStopView];
++>>>>>>> origin/feature-studio-mode-redesign
```

**Comment by Pitometsu** [comment]
`Magit 2.10.3-209-g0ffd49d4, Git 2.13.3, Emacs 25.2.1, darwin`.

**Comment by tarsius** [comment]
No, that's how it is supposed to be. While the `git-diff` manpage doesn't talk about the text that is put into files that have conflicts, it does describe the "combined diff format". Much of what is said there also applies to the conflict markers put into actual files.

**Comment by npostavs** [comment]
I believe having the `+`/`-` from each merge in different columns is standard git notation. Anyway, this is under git's control, not magit, so I'm closing the issue.
