### ISSUE TITLE
magit-define-popup does not create popup with options

### ISSUE THREAD

**Issue by mrkkrp** [magit/magit#3145]
Some silly code I wrote just to test how easy it is to make a popup:

```emacs-lisp
(magit-define-popup hasky-stack-test-popup
  "Show popup for the stack test command."
  :switches '((?c "Coverage" "--coverage")
              (?p "Pedantic" "--pedantic"))
  :options  '((?b "Benchmark arguments" "--benchmark-arguments"))
  :actions  '((?t "Test" hasky-stack-test))
  :default-action 'hasky-stack-test)

(defun hasky-stack-test (&optional args)
  "Blah blah."
  (interactive (list (hasky-stack-test-arguments)))
  (message "Here we go.")
  (message "%S" args))
```

This does not show options. I went to the docs of `magit-difine-popup` and it sent me to `magit-define-popup-option`, according to which it looks like I did everything correctly. `magit-define-popup-option` does not document `READER` argument at all though, and I'm curious what it does actually.

Can you say why options are not displayed?

**Comment by npostavs** [comment]
Works for me.

After setting the options, I got this in the `*Messages*` buffer:
```
Here we go.
("--coverage" "--pedantic" "--benchmark-argumentsfoo")
```
(I guess you should have a `=` after `--benchmark-arguments`)

**Comment by mrkkrp** [comment]
Hmm, I'll try again tomorrow. Writing from mobile now.

**Comment by tarsius** [comment]
Maybe you added `:options` later`? After editing a `magit-define-popup` form you have to use `eval-defun`, not `eval-last-sexp`.

**Comment by mrkkrp** [comment]
> Maybe you added `:options` later?

Yes, that's what I did. In fresh Emacs everything is working. Closing.

**Comment by mrkkrp** [comment]
Still, it would be good to have that `reader` argument documented.
