### ISSUE TITLE
Branch description buffer opens in “Fundamental” mode

### ISSUE THREAD

**Issue by benf-wspdigital** [magit/magit#3149]
When asking Magit to edit the description for the current branch (function `magit-edit-branch*description`), the `EDIT_DESCRIPTION` buffer opens in “Fundamental” mode.

This is Magit 2.10.3, Git 2.14.1, Emacs 25.1.1, darwin.

I don't recall what mode the buffer used in earlier Magit versions. The result of opening the buffer in Fundamental mode is that expected keys (such as ‘C-c C-c’) are not bound for working on the branch description.

**Comment by kyleam** [comment]
Thanks for the report.  It looks like Git v2.13 (c10388c7d) changed
the file name from "BRANCH_DESCRIPTION" to "EDIT_DESCRIPTION".  I'll
update the regex in `magit-edit-branch*description-check-buffers` to
recognize both.
