### ISSUE TITLE
Magit popup "erases" dynamically bound variable

### ISSUE THREAD

**Issue by mrkkrp** [magit/magit#3152]
OK, this is rather weird and I cannot figure it out. Imagine there is a dynamic aka "special" variable defined:

```emacs-lisp
(defvar my-var nil)
```

Then there is a command that uses that special variable like this:

```emacs-lisp
(defun my-fun (arg)
  (interactive (list my-var))
  (message "%S" arg))
```

So `my-var` provides default value for `arg` when `my-fun` is called interactively.

I can confirm that it works:

```emacs-lisp
(let ((my-var 10))
  (call-interactively #'my-fun))
```

This prints `"10"`, as expected. However, when `my-fun` is called by magit popup machinery, value of `my-var` is always `nil`:

```emacs-lisp
(magit-define-popup my-popup
  "Blah."
  :actions '((?a "Action" my-fun))
  :default-action 'my-fun)

(let ((my-var 10))
  (my-popup)) ;; press a and it'll print "nil"!
```

So my question is: what is going on here and how do I use dynamic binding with magit popup?

**Comment by tarsius** [comment]
After the popup is displayed the command returns and control goes back to the command loop, which then waits for events that can be mapped to another command. So the let-binding is no longer in effect.

This is similar to prefix arguments, which are also implemented as separate commands not some kind of recursive editing. When you invoke `universal-command`, then that sets a global variable and the next command can then do something with the value.

Invoking a popup does not set global variables, but you could instead set a buffer-local variable in `:setup-function`.

**Comment by tarsius** [comment]
Actually, that is not the full story. If you invoke an action from a popup, then that first makes the buffer current from which the popup was originally invoked (so the value local to the popup buffer is not seen by action commands).

**Comment by tarsius** [comment]
Have a look at `magit-invoke-popup-action` for how arguments are passed from the popup buffer to the invoked action. So if you can you should pass values to actions using popup arguments. If that is not an option, then you would likely have to redefine that function or use a global variable outside the control of `magit-popup`.

**Comment by mrkkrp** [comment]
Thanks for your response!
