### ISSUE TITLE
Option for magit-clone to ask what directory to clone _into_?

### ISSUE THREAD

**Issue by blaenk** [magit/magit#3153]
I'm not sure how to phrase this. What I mean is that I almost always want to clone a repository into a directory named the same as the repository. This is the default behavior when you don't provide that argument to the `git` program. On the other hand, magit-clone seems to expect the full path, including the name of the directory that would contain the cloned repo.

I had a feeling something like this would be possible already, but I couldn't find anything on it. I may be missing something.

I was wondering if perhaps you'd be open to adding an option that would make magit-clone ask for a directory to clone _into_ first, and then it would prompt for the name of the directory separately (not a completing read, most likely), which if left empty just gives it the same name as the repo.

Or something that would facilitate that behavior.

**Comment by kyleam** [comment]
> On the other hand, magit-clone seems to expect the full path, including the name of the directory that would contain the cloned repo.

When called interactively, `magit-clone` sets the intial input from
the repository name.  Note the regexp match in its interactive form:

```emacs-lisp
(interactive
   (let  ((url (magit-read-string-ns "Clone repository")))
     (list url (read-directory-name
                "Clone to: " nil nil nil
                (and (string-match "\\([^/:]+?\\)\\(/?\\.git\\)?$" url)
                     (match-string 1 url))))))
(setq directory (file-name-as-directory (expand-file-name directory)))
```

So, entering a URL and hitting enter should give you the same result
as `git clone <url>`.  If a specific URL is giving you trouble, please
provide it.

**Comment by blaenk** [comment]
Weird, I was indeed calling it via M-x, which AFAIK calls it interactively. I'll have to try it again and get back to you. Thanks.
