### ISSUE TITLE
Complete on tags when pushing refspecs

### ISSUE THREAD

**Issue by xendk** [magit/magit#3157]
I often use `P r` to push master, develop and a tag in git flow projects, but the completion only lists branches. Would be nice if it included tags.

**Comment by tarsius** [comment]
I am guessing that the tag is related to the pushed branches, so you could also use `push.followTags` or `--follow-tags` to push the tag without even having to specify it. See #2919.

**Comment by xendk** [comment]
Aaah, excellent, I've simply added the switch to the popup...
