### ISSUE TITLE
Latest Helm/ checkout is broken

### ISSUE THREAD

**Issue by twillis** [magit/magit#3158]
after updating packages in emacs today i was unable to checkout a branch in magit.

the error was 

`simpler-helm-bookmark-keybindings: Symbol’s value as variable is void: helm-bookmark-map`

the fix was to put 

`(require 'helm-bookmark)` in my `.spacemacs` file.

I suspect it is related to this commit. https://github.com/emacs-helm/helm/commit/f2745db231654a358e564633000db8aa7959a4b0

**Comment by tarsius** [comment]
Maybe it would be better to raise this issue in the `helm` or `spacemacs` issue trackers? I know very little about `helm`.
