### ISSUE TITLE
magit-cherry shows same author & timestamp in all lines

### ISSUE THREAD

**Issue by mbunkus** [magit/magit#3163]
Running `magit-cherry` I would expect each commit's margin to contain the author for that commit as well as the timestamp when that commit was made.

However, at the moment all lines show the same author and the same timestamp. See this screenshot for a clearer explanation (with customized `magit-cherry-margin` for more clear-cut output):

As soon as I do something (e.g. cherry-pick one of the entries) and the buffer gets refreshed, all author information is changed in all lines to something different, again with the same information in each line.

This is with magit from Github at revision a5cacae790dd1533de4bf93c880d60c3a10a4209 (`magit-version` = `2.10.3-235-ga5cacae7`).

Reproduction is simple: chose a repository, run `magit-cherry`, select a head and an upstream and observe the problem. I used my MXE repository[1] with head = `2507497adf05b16eedec0face3f46476efe6e50d` and upstream = `e2ecdb2d1584c0757b33cf6758b0240aa354736e`.

[1]  https://gitlab.com/mbunkus/mxe

**Comment by tarsius** [comment]
Thanks!

**Comment by mbunkus** [comment]
No, thank _you_ for this super fast fix. A quick test shows it's working fine for me, too.
