### ISSUE TITLE
Online manual has too little contrast

### ISSUE THREAD

**Issue by alijc** [magit/magit#3166]
Gray text on a beige background doesn't provide enough contrast for me to read the text.

The pdf is black on white, which works better.  But when I increase the font size on a pdf the lines get too long to fit on my screen and I end up having to slide the text from side to side to read it.  html would work much better, since it would automatically reflow when I adjust the font size.

Granted, I could go through the trouble of restyling the pages that all the manuals are served up on.  But, honestly, it's just so much simpler to keep using the command line.

**Comment by tarsius** [comment]
> Gray text on a beige background doesn't provide enough contrast for me to read the text.

I am sorry about that. That's the color theme I use pretty much everywhere, so I did not realize this could cause some people issues.

> it's just so much simpler to keep using the command line.

As in using `git` instead of `magit`? Or are you talking about `info`?

In the short-run I recommend you use the third format beside pdf and html by using `info` inside Emacs beginning with `C-h i`.

I have looked around a bit for a simple style sheet switcher but did not find anything that I could just drop in. I'll look into this again some other time, but I cannot promise to get to it during the next few weeks as I am quite busy right now.

If you know of a simple style sheet switcher (which is properly licensed under some FOSS license) then please let me know.

**Comment by mimischi** [comment]
@tarsius What do you mean by `style sheet switcher`? If I've figured it out correctly, you're using Jekyll to generate a static site from markdown files. The Magit manual uses one [CSS stylesheet](https://github.com/magit/magit.vc/blob/master/assets/page.css), which one would need to tweak.

If it's indeed only some CSS work, I could help you out.

**Comment by tarsius** [comment]
I would like to keep the current appearance by default but would like to offer one or more alternative style sheets. So I need some tool to let users set their reference and store it in a cookie.

**Comment by tarsius** [comment]
Well, at least in the short run I should probably just use black for the text.

**Comment by mimischi** [comment]
Doing a quick search, there are a few very simple JavaScript snippets doing the job of switching. This [SO question](https://stackoverflow.com/q/14292997/4791226) combined with the first answer seems pretty solid. Would only need to add some cookie functionality.

**Comment by tarsius** [comment]
We need something that already does the cookie stuff and that is also released under a free license.

I asked for help on twitter, hoping that a javascript expert among Magit's users will volunteer to do the work.

**Comment by melioratus** [comment]
Is this the manual with the contrast issue?

https://magit.vc/manual/magit/

**Comment by tarsius** [comment]
Yes.

**Comment by tarsius** [comment]
Lots of cats here :smile_cat:

**Comment by melioratus** [comment]
True! 😹

**Comment by npostavs** [comment]
[TheInternetIsForCats](http://tvtropes.org/pmwiki/pmwiki.php/Main/TheInternetIsForCats)  😹 (warning TVTropes)

**Comment by pau4o** [comment]
Just created [Simple CSS Switch](https://github.com/pau4o/simple-css-switch).

If you wont I can integrate it with magit documentation and add some CSS themes.

**Comment by tarsius** [comment]
Thanks a lot!

> If you wont I can integrate it with magit documentation and add some CSS themes.

Please do that, though for now you might want to simply add a plain b&w theme.

**Comment by tarsius** [comment]
Please also try to make [LibreJS](https://www.gnu.org/software/librejs/) happy. See https://github.com/melpa/melpa/issues/3731 for context.

**Comment by tarsius** [comment]
I'll probably be gone for a few hours.

**Comment by gambo** [comment]
Styleswitcher might be more work than necessary.

- Just changing the the font color to a slight off black (#222) already makes a huge difference in legibility.
- Removing "text-align: justify" also improves legibility by removing unnecessary space.
- Limit the amount of colours if you can to avoid distraction. Right now the page has 4 colours which is very colourful for an informational page.
- line-height should typically be greater than 1.3 for body copy for improved flow.
- maybe a slight increase in font-size but thats just a gut feel

Not sure if the theme choice is locked down, but a few css changes should do the trick

![1](https://user-images.githubusercontent.com/652288/31530926-fdd4eb88-afe3-11e7-9805-de8568afcd22.PNG)

**Comment by pau4o** [comment]
@gambo I already integrated themes support, see https://github.com/magit/magit.vc/pull/5
Thumbs up for removing `text-align: justify;`
There are 10 unique colours used in default theme (same number or lower in new themes)

**Comment by gambo** [comment]
Nice one! I didnt see it @pau4o, great stuff

**Comment by tarsius** [comment]
Very nice, thanks!

**Comment by tarsius** [comment]
I have just installed @pau4o's theme switcher and uploaded the latest manuals again. Thanks Kamen!

Older manuals, before `2.11` are not themed yet. Backporting recent changes to the old manuals will be quite some work and I probably won't do that very soon.
