### ISSUE TITLE
error when running `magit-run-git` outside of a repository

### ISSUE THREAD

**Issue by dunn** [magit/magit#3169]
As of 2.11.0, this code succeeds (the repository is created), but it also throws the error `Not inside a Git repository`:
```elisp
;; or anywhere that's not a repo
(let ((default-directory "/Users/alex/Desktop"))
  (magit-run-git "init"))
```

`magit-version` is `Magit 2.11.0, Git 2.14.1, Emacs 25.2.1, darwin`

**Comment by kyleam** [comment]
Thanks.  I can reproduce it.

@npostavs, it bisects to 184a26b2 (Use cache around magit-run-git
calls, 2017-05-31).

**Comment by npostavs** [comment]
Hmm, I didn't consider a bare `(magit-run-git "init")` (as opposed to `(magit-init)`) when I extended the cache. I guess we will have to move the caching up a level to all the `magit-stage`, `magit-unstage`, etc functions (the only alternative I can see would be to check the git args for `"init"` which seems too fragile).

I am travelling away from my normal computer for next little while, so I probably won't get to this until Monday.

**Comment by tarsius** [comment]
> (the only alternative I can see would be to check the git args for "init" which seems too fragile).

I think we should try that first anyway. What kind of breakage do you expect? `git init` not being the only problematic case, or failure to detect that `git init` is being run?

**Comment by npostavs** [comment]
>> (the only alternative I can see would be to check the git args for "init" which seems too fragile).
> 
> I think we should try that first anyway.

Okay, see #3180.

> What kind of breakage do you expect? git init not being the only problematic case, or failure to detect that git init is being run?

Detection failure. Aren't there are all kinds of possibilities with the user making git aliases and similar? Or do we file that under "don't do that then"?

**Comment by tarsius** [comment]
> Or do we file that under "don't do that then"?

Let's go with "we'll deal with it if someone actually does that" :wink:
