### ISSUE TITLE
Possible problem in git or in `magit-insert-upstream-branch-header`

### ISSUE THREAD

**Issue by elibarzilay** [magit/magit#3171]
I'm not sure that the following is clear enough, but I'll try to be clear and as brief as I can...

I have a setup that creates a remote with a fixed name that refers to a random actual remote (I use this to go over PRs conveniently before merging them).    The end result looks like:

    [...usual setup, including origin and master...]
    [remote "pr-remote"]
      url = git@github.com:someone/somerepo.git
      fetch = +refs/heads/somebranch:refs/remotes/pr-remote/pr
      push = +refs/heads/pr:refs/heads/somebranch
    [branch "pr"]
      remote = pr-remote
      merge = refs/heads/somebranch

It looks complicated, but it should be valid since it's done via git:

    $ git remote add -t somebranch pr-remote git@github.com:someone/somerepo.git
    $ git fetch pr-remote
    From github.com:someone/somerepo
     * [new branch]      somebranch -> pr-remote/pr
    $ git checkout --track pr-remote/pr
    Branch pr set up to track remote branch somebranch from pr-remote.
    Switched to a new branch 'pr'

Now, the problem is that this is shown in the magit status buffer with:

    Rebase:   pr-remote/somebranch is missing

I tracked it to `magit-insert-upstream-branch-header` which ultimately
runs the following and fails:

    $ git rev-parse --verify pr-remote/somebranch
    fatal: Needed a single revision

However, running this works:

    git rev-parse --verify pr-remote/pr

The reason magit runs the failing version is the `merge = refs/heads/somebranch` in the config file.  This *does* look strange, as can be seen in the `checkout` that creates the branch -- I expected

    Branch pr set up to track remote branch pr from pr-remote.
                                            ^^

And indeed if I manually tweak the config to have

    [branch "pr"]
      remote = pr-remote
      merge = refs/heads/pr

then magit is happy again.

Is this a git bug that confuses magit, or is magit confused, or maybe I did something wrong?

**Comment by tarsius** [comment]
I have considered changing the wording on that line before. Even though it currently says "... is missing" that isn't supposed to mean that anything is wrong. It just means that the "branch where `p p` would push to does not exist [yet]". So maybe replacing "is missing" with "... does not exist" would be better.

I do want to remove that line completely when the remote branch does not exist yet, because then one could not tell the difference between the push-remote not being configured and the remote branch simply not existing.

> I have a setup that creates a remote

I will merge a similar feature soon. Check it out, it's on the `jb/pr-branch` branch. (I am regularly rebasing that branch, just so you know.)

**Comment by elibarzilay** [comment]
1. So git's behavior is expected?

2. Re the line -- FWIW, the thing that caught my eye is the warning highlight, not just the wording...

3. BTW, my hack is for PRs that come from different forks, and it looks like that won't work with that?

**Comment by tarsius** [comment]
> 1. So git's behavior is expected?

Yes.

> 2. Re the line -- FWIW, the thing that caught my eye is the warning highlight, not just the wording...

Using a warning highlight might be appropriate as in "you haven't pushed this yet, so don't delete it if you want to keep a copy somewhere".

Let's see what others think.

> 3. BTW, my hack is for PRs that come from different forks, and it looks like that won't work with that?

It creates a remote for every fork (and also supports the upstream repository).

**Comment by elibarzilay** [comment]
Well, clearly in my case the branch was pushed, therefore the warning is wrong...

(Re the PR functionality: I intentionally re-use a single `pr-remote` for all of them, since I don't want to keep track of random remotes, or even keep them once I'm done with a PR.)

**Comment by tarsius** [comment]
> (Re the PR functionality: I intentionally re-use a single pr-remote for all of them, since I don't want to keep track of random remotes, or even keep them once I'm done with a PR.)

My implementation automatically removes a "pull-request" remote once its last branch is deleted. So you can have more than one such remote *and* it still doesn't get messy.

**Comment by tarsius** [comment]
> Well, clearly in my case the branch was pushed (or rather, just retrieved from a repo), therefore the warning is wrong...

It's clearly *undesirable* in your case, but still correct for magit to do it that way.

The branch was pulled from somewhere but not from the place you have configured it to be pulled from pushed to. That branch does not exist, so magit tells you that this is the case.

Consider replacing

```
[branch "pr"]
  remote = pr-remote
  merge = refs/heads/somebranch
```

with

```
[branch "pr"]
  remote = .                              # or "origin" if you prefer that
  merge = refs/heads/master   # or whatever branch the pr was actually opened against
```

Or use my implementation, which does that :wink:

**Comment by tarsius** [comment]
All in all I think what magit does is correct and the only thing that we might want to change is how we word and color "is missing". Since nobody else raised any arguments against how we currently do that, I intend to stick with the status-quo. If this comes up again, then I might reconsider.

**Comment by tarsius** [comment]
Feel free to comment further - I only closed because I think there is nothing that has to be changed in magit.

**Comment by elibarzilay** [comment]
Oh, that's most of what I wanted.  The idea behind my single+known branch and remote names are to make it easy to remember git commands that use these.  But in practice I find that I hardly do any of that (probably *because* I'm using it almost exclusively via magit).  So I guess that I'll try it out and maybe switch to it...

**Comment by tarsius** [comment]
You might wanna wait a few more days. I am currently setting up some tests to make sure all cases are handled properly.

**Comment by elibarzilay** [comment]
Sorry if it's already there, but I hope for some quick one-paragraph usage instructions...

**Comment by tarsius** [comment]
Yeah... no that doesn't exist yet.

Simply create a branch using `b r` ... completion ... `RET`. The branch is not automatically being checked out, so you have to do that. When done, delete the branch as usual. If it is the last branch that was setup using `b r` for that particular remote, then the remote is removed too.

You will need to use the `next` branch of `ghub`.

So really... probably wait a few days. After all your tooling seems to have worked for you just fine until now, except for the little annoyance you reported here.
