### ISSUE TITLE
"Patch does not apply" staging individual hunks with file containing Hindi text

### ISSUE THREAD

**Issue by contrapunctus-1** [magit/magit#3172]
**(1) what behavior you expected**
Hunk is staged

  **(2) what behavior you observed**
> GitError! test.txt: patch does not apply  [Type `$' for details]

Typing $ -
> 1 git … apply --cached -p0 --ignore-space-change -
> <stdin>:7: trailing whitespace.
>             
> error: patch failed: test.txt:1
> error: test.txt: patch does not apply

  **(3) and how we can reproduce the issue.**
1. Create directory and repository
2. Create file, enter Hindi text, save file, select utf-8 when prompted for coding system
3. Stage and commit file
4. Add text to file
5. Attempt to stage hunk (staging the whole file works)
(I have attached a ZIP archive containing a MWE, at the state one would arrive after these five steps.)

**M-x magit-version RET**
> Magit 2.11.0-5-g746f2361, Git 2.11.0, Emacs 24.5.1, gnu/linux

When running with `make emacs-Q`, I was not able to reproduce this. However, magit then displays the file contents as garbled text. To make them appear correctly, I evaluated
```
(setq magit-git-output-coding-system 'utf-8
      magit-git-global-arguments (append magit-git-global-arguments '("-c" "i18n.logOutputEncoding=utf-8")))
```
After which the steps above will reproduce the issue.
[test.zip](https://github.com/magit/magit/files/1305770/test.zip)

**Comment by contrapunctus-1** [comment]
A chance discovery which I figured might help -

```
  1 git … apply --cached -p0 --ignore-space-change -
error: patch failed: script.txt:377
error: script.txt: patch does not apply

  0 git … add -u -- script.txt
  0 git … reset HEAD -- script.txt
Unstaged changes after reset:
M	script.txt

  1 git … apply --cached -p0 --ignore-space-change -
<stdin>:25: trailing whitespace.
          
<stdin>:29: trailing whitespace.
                                               ,            costume                                                ,   
<stdin>:30: trailing whitespace.
		                                 Actually,                                                            ,                                                 ,      6                            
<stdin>:31: trailing whitespace.
		         
<stdin>:33: trailing whitespace.
     :		     ,       ,                              -                            
error: patch failed: script.txt:1
error: script.txt: patch does not apply



```
Only ASCII characters appear in the log, and non-ASCII characters seem to be sent as whitespace. (It is impossible for my files to contain trailing whitespace, as I have delete-trailing-whitespace in before-save-hook)

**Comment by npostavs** [comment]
> When running with make emacs-Q, I was not able to reproduce this. However, magit then displays the file contents as garbled text.

I don't have this problem, but I'm using a unicode locale. What's the output from running `locale` on the comand line? What is the default value of `default-process-coding-system` for you?

**Comment by contrapunctus-1** [comment]
locale(1) revealed that LANG and all the other locale variables were set to "en_IN". If one starts Emacs with `LANG=C.UTF-8`, Devanagari text in Magit buffers renders correctly (even without the code I mentioned), and staging of individual hunks works.
