### ISSUE TITLE
magit-popup is unaware of help-window-select and display-buffer-overriding-action

### ISSUE THREAD

**Issue by bmag** [magit/magit#3173]
Specifically, the function `magit-popup-describe-function` implicitly assumes `help-window-select` and `display-buffer-overriding-action` are both nil (that's their default values):

```elisp
(defun magit-popup-describe-function (function)
  (let ((winconf (current-window-configuration)))
    (delete-other-windows)
    (split-window-below)
    (other-window 1)
    (with-no-warnings ; display-buffer-function is obsolete
      (let ((display-buffer-alist '(("" display-buffer-use-some-window)))
            (display-buffer-function nil))
        (describe-function function)))
    (fit-window-to-buffer)
    (other-window 1)
    (setq magit-popup-previous-winconf winconf)
    (magit-popup-help-mode)))
```

Reproduction steps 1: (can provide a more detailed recipe if necessary)
- `M-: (setq help-window-select t)`
- `M-x magit-dispatch-popup`
- `?g`

Reproduction steps 2:
- `M-: (setq display-buffer-overriding-action '(display-help-in-new-frame))`
- `M-x magit-dispatch-popup`
- `?g`
```elisp
(defun display-help-in-new-frame (buffer alist)
  (when (with-current-buffer buffer
          (eq major-mode 'help-mode))
    (display-buffer-pop-up-frame buffer alist)))
```

Observed behavior: the help buffer is displayed in a new frame

I plan to check which other functions in `magit-popup.el` have the same bug and submit a pull request to fix the issue by let-binding these two variables in a similar way to `display-buffer-alist` and `display-buffer-function`. However, I'm not sure if locally overriding `display-buffer-overriding-action` is desirable or not, so I'd like to hear your opinion. (it clashes with `window-purpose`, but I can also fix the clash upstream in `window-purpose`)

See also: https://github.com/syl20bnr/spacemacs/issues/9570

**Comment by bmag** [comment]
PR is now ready: #3177

**Comment by tarsius** [comment]
Thanks a lot! And sorry for not replying earlier.
