### ISSUE TITLE
When error happens during commit, shouldn't lose commit message

### ISSUE THREAD

**Issue by mgsloan** [magit/magit#3178]
I just typed a rather involved commit message twice.  Should have learned the first time and done it in a new buffer!  Here's what happens when I try to make the commit:

```
Waiting for Emacs...
*ERROR*: Fill-column-indicator requires version 25 or later
error: There was a problem with the editor '/usr/bin/emacsclient.emacs24 --socket-name=/tmp/emacs1000/server'.
Please supply the message using either -m or -F option.
```

I recently updated my spacemacs, using magit-20170913.1424, I suspect that I need to update emacs version.

This specific error is not what I'm opening the issue about.  Rather, it's that it's very frustrating that something going wrong during the commit process can cause the commit message to disappear.  Happily, while writing this issue I discovered `.git/COMMIT_EDITMSG`.

So, I think the resolution of this would be to open COMMIT_EDITMSG in a new buffer if the commit fails.  It also seems worthwhile to consider the case that saving to COMMIT_EDITMSG fails, in this case ideally commit buffer would not be abandoned.

Thanks!

**Comment by Silex** [comment]
I think <kbd>M-p</kbd> (or `M-n`) would have cycled throught the old commit messages in this case... can you try to reproduce? That is, try to commit again and press `M-p` when having to fill the commit message.

**Comment by mgsloan** [comment]
@Silex Wow, that's good to know, always good to learn more magit bindings!

**Comment by mgsloan** [comment]
Going to close this, as it's clear that my config is broken, and M-p / M-n work.
