### ISSUE TITLE
Characters are garbled when commit with non-ASCII message is amended or reverted

### ISSUE THREAD

**Issue by yasuhirokimura** [magit/magit#3181]
OS: FreeBSD 11.1-RELEASE
Emacs: 25.3 (Installed by using FreeBSD ports)
Git: 2.14.1 (Installed by using FreeBSD ports)
Magit: 2.11.0 (Installed by using FreeBSD ports)
Result of 'M-x magit-version: "Magit 2.11.0, Git 2.14.1, Emacs 25.3.1, berkeley-unix"
Locale (Value of $LANG): ja_JP.UTF-8

When non-ASCII characters are included in commit message, amending or reverting such a commit results in garbled characters.

How to reproduce this issue is as following.

Step 1.  Clone https://github.com/yasuhirokimura/RepoForMagitBug.git

Hitory of this repository is as following.

```zsh
yasu@eastasia[2067]% pwd
/home/yasu/tmp/RepoForMagitBug
yasu@eastasia[2068]% git log
commit 57da65f218258a620cb237f7a169626df2a368df (HEAD -> master, origin/master)
Author: Yasuhiro KIMURA <yasu@utahime.org>
Date:   Fri Sep 22 11:40:11 2017 +0900

    Add ccc. (cccというファイルを追加)

commit 5a45201029b8691b088ffaef65ad02110a0334cf
Author: Yasuhiro KIMURA <yasu@utahime.org>
Date:   Fri Sep 22 11:39:04 2017 +0900

    Add bbb. (bbbというファイルを追加)

commit 381585325184ccaf2fcb5abeed304a65a79c1853
Author: Yasuhiro KIMURA <yasu@utahime.org>
Date:   Fri Sep 22 11:37:58 2017 +0900

    Add aaa. (aaaというファイルを追加)
yasu@eastasia[2069]% 
```
Step 2. Start Emacs, type 'M-x magit-status' and specify path of repository cloned at step 1.

Step 3. Type 'l l'.

All commit messages are displayed correctly.

![magitbugreport20170924 01](https://user-images.githubusercontent.com/5249848/30777923-5dfc241e-a101-11e7-9d6f-da571b8eb804.png)

Step 4.  Type 'c a'.

Then commit message with garbled characters is displayed.

![magitbugreport20170924 02](https://user-images.githubusercontent.com/5249848/30777957-38ebbff8-a102-11e7-96b4-6a9964ee7515.png)
 
Step 4'. Type 'V V HEAD'

Same problem happens when reverting commit instead of ammending.

![magitbugreport20170924 03](https://user-images.githubusercontent.com/5249848/30777983-236366ee-a103-11e7-9338-8d2d1e9bba53.png)

**Comment by tarsius** [comment]
> Hitory of this repository is as following.

Did you create these commit *in Magit* without issues? (Trying to make sure this really is only about amending and reverting.)

**Comment by yasuhirokimura** [comment]
> Did you create these commit in Magit without issues? (Trying to make sure this really is only about amending and reverting.)

Yes. I created the repository with GitHub Web UI and cloned it to local machine by using command line. But after that I did all works through Emacs and Magit. That is, I created new file with Emacs, staged and committed it with Magit, and also pushed 3 commits with Magit.

Furthermore, since I started using Magit I made hundreds of commit with message including non-ASCII characters through Magit. But I have never experienced problem that commit messages are garbled.

**Comment by tarsius** [comment]
> Step 4. [...] Then commit message with garbled characters is displayed.

This does not happen for me. `buffer-file-coding-system` is `utf-8-unix` and the information displayed at the left edge of the mode-line is `U:---`. In your case it shows `-UUS:----F1`, which seems strange. What is `buffer-file-coding-system` in your case?

**Comment by yasuhirokimura** [comment]
> What is buffer-file-coding-system in your case?

It is `japanese-shift-jis-unix`. It seems Emacs fails to autodetect character set of `.git/COMMIT_EDITMSG`.

**Comment by yasuhirokimura** [comment]
> It seems Emacs fails to autodetect character set of `.git/COMMIT_EDITMSG`.

I found cause of misdetection. There are following settings in my `.emacs`.
```emacs
(set-language-environment "japanese")
(set-default-coding-systems 'utf-8)
(cond ((null window-system)
           (set-terminal-coding-system 'utf-8)
           (set-keyboard-coding-system 'utf-8)))
```
By commenting them out the problem is disappeared. But they are necessary for me to use Emacs with Japanese environment. So I can't simply remove them...

Anyway now it is clear that Magit has nothing to do with characters garbling. So I will close this issue.
