### ISSUE TITLE
Improve how tabs are displayed in diffs

### ISSUE THREAD

**Issue by tarsius** [magit/magit#3185]
1. The first tab stop should be at `1` (for the `[-+ ]` character).
2. Try to use the correct tab width.

**Comment by fice-t** [comment]
> The first tab stop should be at 1 (for the [-+ ] character).

Do you have any ideas on how to implement this in elisp? I was planning on asking Eli about implementing this in Emacs eventually.

Perhaps you could propertize all tabs in a diff with a [`:width` display property](https://www.gnu.org/software/emacs/manual/html_node/elisp/Specified-Space.html#Specified-Space), but it doesn't feel like a good solution.

**Comment by tarsius** [comment]
No, just dumped that here so that I don't forget.

**Comment by tarsius** [comment]
Related to #2929.

**Comment by tarsius** [comment]
> Do you have any ideas on how to implement this in elisp? I was planning on asking Eli about implementing this in Emacs eventually.

Well I was hoping that (1) would be as simple as modifying `tab-stop-list`, but it turned out that doesn't affect display. I don't currently see another solution than to `:width`, but that's not pretty. Have you talked about this with Eli yet? I would love if there were something like `tab-stop-list` but for display not just pressing `tab`.

**Comment by tarsius** [comment]
I have done it anyway. Originally I intended to make this optional but because this uses text properties, not overlays, and because the code that creates those properties is also fast, I don't think that is necessary.

I am closing this - (2) is covered by #2929.

Please let me know if you make any progress making such a hack unnecessary.
