### ISSUE TITLE
magit-submodule-popup does not respect switches added with magit-define-popup-switch

### ISSUE THREAD

**Issue by accatyyc** [magit/magit#3188]
I want to add the functionality to recursively update submodules to magit. I have added the following to my `init.el`:

```elisp
(use-package magit
  :config
  (magit-define-popup-switch 'magit-submodule-popup ?r "Recursive" "--recursive" t))
```

The options show up, and I can activate them, but they are never added to any of the commands. Here's the output in the `*magit-process*` buffer when I type `o -r u`
```
0 git … submodule update
```

Maybe I'm misunderstanding the documentation for `magit-define-popup-switch`, but I've been searching a lot and it seems like this is the correct way to do it, so this might be a bug.

Version: `Magit 20170201.254, Git 2.13.5 (Apple Git-94), Emacs 25.1.1, darwin`

**Comment by tarsius** [comment]
> Maybe I'm misunderstanding the documentation for `magit-define-popup-switch`, but I've been searching a lot and it seems like this is the correct way to do it, so this might be a bug.

No, you understood that correctly, but commands also have to use `(interactive (... (magit-...-arguments))` and then respect those arguments. The submodule commands don't do that (and you can generally assume that if a popup doesn't feature any arguments that the commands won't respect any arguments yourself.

I intend to improve the submodules commands soon. Probably within the next two weeks.

**Comment by accatyyc** [comment]
I see. Thanks for the clarification. Until then, I will resort to the bruteforce solution 😄 

```elisp
(defun magit-submodule-update-recursive ()
  (interactive)
  (magit-run-git-async "submodule" "update" "--init" "--recursive"))

(use-package magit
  :config
  (magit-define-popup-action 'magit-submodule-popup
	?r "Recursive Update" 'magit-submodule-update-recursive ?u))
```

**Comment by tarsius** [comment]
That should do the trick for a while :wine_glass:
