### ISSUE TITLE
s-TAB key binding broke my workflow

### ISSUE THREAD

**Issue by gavenkoa** [magit/magit#3195]
I heavily relay on `s-` key modifier as **standard** Emacs packages don't define any key binding with super/hyper. That allows me to leave from M-x term buffer which s-TAB for instance (as all `C-` and `M-` are passed to program in `term` mode).

It's not wise to broke my workflow just because hypothetical possibility of usage s-TAB by someone else, having that this key binding is just a mistake:

    commit 29ff1ec6a0f65caf5c9c5bf4869015946f12f7aa
    Author: Jonas Bernoulli <jonas@bernoul.li>
    Date:   2016-09-07 17:42:25 +0200

    magit-mode-map: bind S-tab to magit-section-cycle-global
    
    It appears this was always the intention.  Keep the bindings
    for s-tab and backtab, in case someone actually uses those.
    
    Fixes #2759.

**Comment by gavenkoa** [comment]
https://emacs.stackexchange.com/questions/36048/are-super-and-hyper-key-modifier-permitted-in-major-minor-modes

**Comment by npostavs** [comment]
> having that this key binding is just a mistake:

I agree it's a mistake https://github.com/magit/magit/issues/2759#issuecomment-245101877

**Comment by basil-conto** [comment]
@gavenkoa Whether the compatibility binding is kept or dropped as a result of this issue, in the meantime you can

```el
(with-eval-after-load 'magit-mode
  (define-key magit-mode-map [s-tab] nil))
```

**Comment by tarsius** [comment]
Discussion continues in 1d2cf2119351c2128bf5b04ac49c230e3fb26441.
