### ISSUE TITLE
Open diff when editing a commit message during a rebase

### ISSUE THREAD

**Issue by fice-t** [magit/magit#3199]
It would be nice if the diff was shown when editing a commit message in a rebase (interactive, `r w`, etc.), just like it is when committing normally.

`Magit 20171007.431, Git 2.14.2, Emacs 26.0.60, gnu/linux`

**Comment by tarsius** [comment]
The diff is being displayed by `magit-commit-diff`. This could be fixed by adding an "otherwise" clause that uses `(apply-partially 'magit-diff-staged nil)`.

I haven't done that yet because I am not sure whether the other clauses match all the special cases. It is safer to display no diff at all instead of risking displaying changes that won't actually make it into the commit and therefore would be misleading.

On the other hand when I get no diff, then I always <kbd>C-c C-d</kbd> and I cannot remember having seen an incorrect diff being displayed. So maybe we should just add that otherwise clause and see how it goes. Of course if someone would volunteer to try to think of all possible cases first, that would be great, but I would be willing to just add a fallback now.

@npostavs @kyleam what do you think?

**Comment by npostavs** [comment]
> So maybe we should just add that otherwise clause and see how it goes.

Sounds reasonable to me.

**Comment by kyleam** [comment]
> It would be nice if the diff was shown when editing a commit message in a rebase (interactive, r w, etc.)

I don't know what "etc" refers to.  <kbd>c a</kbd> and <kbd>c w</kbd>
should already show a diff.  For <kbd>r w</kbd>, isn't that already
covered by a5a5eb40 (magit-commit-diff: handle
magit-rebase-reword-commit, 2017-10-07)?

I'm assuming "interactive" means that you start an interactive rebase
(<kbd>r i</kbd>) and then mark some commits to reword (<kbd>r</kbd>).
A diff isn't shown in this case but ...

> This could be fixed by adding an "otherwise" clause that uses (apply-partially 'magit-diff-staged nil).

... this would just show an empty diff.

**Comment by tarsius** [comment]
Right, I had a quick look at this when I created the mentioned commit but didn't do anything because of the issue you mention. Seems we would have to check whether there are actually are any staged changes before showing those, and if not show... likely `magit-diff-while-amending`. And it just got more likely that we end up showing the wrong diff.

**Comment by kyleam** [comment]
Fall back to `magit-diff-while-committing` rather than
`magit-diff-staged` and let it handle the checks?  My experience with
<kbd>C-c C-d</kbd> matches what you said above.

**Comment by fice-t** [comment]
@kyleam 
>I don't know what "etc" refers to.

I just left that there since there might be other rebase cases to handle.

>I'm assuming "interactive" means that you start an interactive rebase
(r i) and then mark some commits to reword (r).

I'm also prompted to edit a message after editing a commit (e).

>For r w, isn't that already
covered by a5a5eb4 (magit-commit-diff: handle
magit-rebase-reword-commit, 2017-10-07)?

I just updated to try that out and it doesn't work for me. It looks like it's because `last-command` is `magit-log-select-pick`.

**Comment by kyleam** [comment]
> I'm also prompted to edit a message after editing a commit (e).

That should already be covered.  From `magit-commit-diff`s point of
view, that's just a normal commit operation.  I see a diff on my end.
Do you not?

>> For r w, isn't that already
>> covered by a5a5eb4 (magit-commit-diff: handle
>> magit-rebase-reword-commit, 2017-10-07)?

> I just updated to try that out and it doesn't work for me. It looks like it's because last-command is magit-log-select-pick.

Ah, good point.  I tried it out with point already on a commit, so
`last-command` is `magit-rebase-reword-commit`.  Perhaps
`magit-log-select-pick` should take care of setting `this-command`.

**Comment by fice-t** [comment]
> Do you not?

`last-command` is `magit-rebase-continue`, so `magit-commit-diff` is skipped entirely.

**Comment by kyleam** [comment]
> last-command is magit-rebase-continue

I see.  For whatever reason, I'm in the habit of amending the commit
that I've stopped at and then continuing the rebase.  Obviously simply
running `magit-rebase-continue` with staged changes is also valid and
more direct.

**Comment by kyleam** [comment]
Does

```diff
diff --git a/lisp/magit-commit.el b/lisp/magit-commit.el
index 9b5f29c7..b3045846 100644
--- a/lisp/magit-commit.el
+++ b/lisp/magit-commit.el
@@ -348,7 +348,9 @@ (defun magit-commit-diff ()
                         ((magit-commit-amend
                           magit-commit-reword
                           magit-rebase-reword-commit)
-                         'magit-diff-while-amending))))
+                         'magit-diff-while-amending)
+                        (otherwise
+                         'magit-diff-while-committing))))
     (-when-let (diff-buffer (magit-mode-get-buffer 'magit-diff-mode))
       ;; This window just started displaying the commit message
       ;; buffer.  Without this that buffer would immediately be

```

properly handle all the cases you've raised so far?

**Comment by fice-t** [comment]
It works for some, but it seems finicky for `r w`. For some commits it works fine, but for others it displays an `(empty)` diff with the header line "Staged changes". I'm not sure why it works for some commits and not others.

This seems to work, but I don't know if it's good to use (as you said, it might be good for `magit-log-select-pick` to instead set `this-command`):
```diff
diff --git a/lisp/magit-commit.el b/lisp/magit-commit.el
index 9b5f29c7..cb67d78f 100644
--- a/lisp/magit-commit.el
+++ b/lisp/magit-commit.el
@@ -341,12 +341,14 @@ depending on the value of option `magit-commit-squash-confirm'."
   (-when-let (fn (and git-commit-mode
                       magit-commit-show-diff
                       (cl-case last-command
-                        (magit-commit
+                        ((magit-commit
+                          magit-rebase-continue)
                          (apply-partially 'magit-diff-staged nil))
                         (magit-commit-all
                          (apply-partially 'magit-diff-working-tree nil))
                         ((magit-commit-amend
                           magit-commit-reword
+                          magit-log-select-pick
                           magit-rebase-reword-commit)
                          'magit-diff-while-amending))))
     (-when-let (diff-buffer (magit-mode-get-buffer 'magit-diff-mode))
```

**Comment by fice-t** [comment]
Oh, but it doesn't work in the `then mark some commits to reword (r)` case.

**Comment by fice-t** [comment]
New info: Without either of the above diffs, if I go into a commit and press `C-c C-d`, then if it's a diff that doesn't work with @kyleam's diff, it displays an `(empty)` diff as above, else it shows a seemingly correct diff.

Pressing `q` to close the diff buffer and press `C-c C-d` changes this `(empty)` diff into a seemingly correct diff, and a seemingly correct diff into an `(empty)` diff.

**Comment by tarsius** [comment]
FYI `C-c C-d` is only useful when no diff is being displayed, or when there are two different diffs the user might find interesting, which I believe only happens when amending to an existing commit.

**Comment by fice-t** [comment]
That makes sense. What I see, though, is that sometimes the first call of `C-c C-d` shows the "wrong" diff during a rebase, while sometimes it's the "right" one.

It seems to be related to whether or not there's a diff buffer still alive. If there is, then I see an erroneous `(empty)` diff; but if I make sure to kill the diff buffer, then I get the diff I expected.

**Comment by tarsius** [comment]
> This seems to work, but I don't know if it's good to use (as you said, it might be good for `magit-log-select-pick` to instead set `this-command`):

This won't work well, since you can select different actions for different commits, and then you can even move around in the buffer some more before you actually initiating the rebase. In other words we cannot rely on the value of `this-command`/`last-command` and have to instead determine what the appropriate diff is based on the information we can collect at present.

**Comment by tarsius** [comment]
> It seems to be related to whether or not there's a diff buffer still alive.

That sounds very likely.
