### ISSUE TITLE
When running into a merge conflict, Emacs hangs if the "stage changes" list is long (over 1k)

### ISSUE THREAD

**Issue by NicholasTD07** [magit/magit#3202]
Version
`Magit 20170906.838, Git 2.14.2, Emacs 25.3.1, darwin`

I have run into this problem a few times. Whenever I got a merge conflict, and there a a lot files changed (over a thousand, up to 10K), Emacs hangs for a long time (a minute or so) without responding.

Here's an example:

This is the changed files number magit shows after becoming responsive. 

```
Staged changes (1694)
```

This is a CPU profile I took by running `profiler-start` and `profiler-report`.
```
- command-execute                                               42098  99%
 - call-interactively                                           42098  99%
  - funcall-interactively                                       41758  99%
   - magit-status                                               41753  99%
    - magit-status-internal                                     41753  99%
     - magit-mode-setup                                         41753  99%
      - magit-mode-setup-internal                               41753  99%
       - magit-refresh-buffer                                   41747  99%
        - apply                                                 41690  98%
         - magit-status-refresh-buffer                          41591  98%
          - magit-run-section-hook                              41481  98%
           - run-hooks                                          41481  98%
            - magit-insert-staged-changes                       41248  97%
             - magit-git-wash                                   41242  97%
              - magit-diff-wash-diffs                           41033  97%
               - magit-wash-sequence                            41033  97%
                - #<compiled 0x40d1d4c1>                        41033  97%
                 - apply                                        41032  97%
                  - magit-diff-wash-diff                        40743  96%
                   - magit-diff-insert-file-section              36272  86%
                    - magit-wash-sequence                       36114  85%
                     + magit-diff-wash-hunk                      2680   6%
```

Is it possible that this is caused by getting and rendering all the changes in all changed files? (and the fact that this list is very long)

If it is the case, this might be very naive thinking, but can we change this process so we only get and render the diff when the user expands a file's section in the `Staged changes`? 
I mean, can we do this lazily?

PS.

Thanks for the work you pour into magit. It is now my favorite git client which used to be the command line `git`.

**Comment by tarsius** [comment]
It doesn't hang, it just takes forever :wink: 

This is a known issue and will be addressed, see #2985.

>> Is it possible that this is caused by getting and rendering all the changes in all changed files? (and the fact that this list is very long)

> I suspect that's exactly the case. From what I understand of magit's section plumbing, the entire contents have to be inserted before it can be folded up into the expandable section.

Yes.
