### ISSUE TITLE
`magit-branch-spinoff` doesn't restore state after an error

### ISSUE THREAD

**Issue by fice-t** [magit/magit#3210]
For example, try `b s` and input an invalid name. HEAD will now be before any of the commits that were to be spun off, but the worktree appears to still contain their changes.

What should happen is that the state is reverted to before the spinoff command was issued.
`Magit 20171014.220, Git 2.14.2, Emacs 26.0.60, gnu/linux`

**Comment by tarsius** [comment]
Without looking at any code I would thing that it would be easier to just validate the input before doing anything.

**Comment by tarsius** [comment]
It appears we already try to do that, so what kind of "invalid name" are you talking about? A string that isn't valid as a branch name?

**Comment by fice-t** [comment]
> Without looking at any code I would think that it were easier to just validate the input before doing anything.

Are there other errors that could happen with `git checkout -b`? If not, then that seems reasonable.

> It appears we already try to do that, so what kind of "invalid name" are you talking about? A string that isn't valid as a branch name?

I don't see any validation. By "invalid name", I mean a branch with invalid characters, e.g., a space.

What I see is that `(magit-call-git "checkout" args "-b" branch current)` is called, and even if it returns an error, further down `(magit-call-git "update-ref" "-m"` is called.

So perhaps it should abort if the `git checkout -b` call fails.

**Comment by tarsius** [comment]
> I don't see any validation.

It makes sure that given a valid a new branch can created, which isn't possible when a branch by that name already exists.

**Comment by tarsius** [comment]
I used the strategy that you suggested. That way other possible errors that we didn't think of yet also get automatically caught.

**Comment by fice-t** [comment]
Thanks.

**Comment by fice-t** [comment]
@tarsius I just noticed that `magit-read-string` takes an argument that notifies the user that whitespace isn't allowed in branch names. Perhaps this argument should be used in `magit-branch-spinoff` to make it similar to `magit-branch-and-checkout`?

**Comment by tarsius** [comment]
Done. I see no reason not to.
