### ISSUE TITLE
Diff shown for fixup/squash commits isn't closed at the end

### ISSUE THREAD

**Issue by fice-t** [magit/magit#3211]
Performing a successful instant fixup commit does not close the diff buffer that was shown during the process.

Also, switching to that diff buffer and pressing `q` will result in the status buffer having a right margin containing the commit dates.

`Magit 20171014.220, Git 2.14.2, Emacs 26.0.60, gnu/linux`

**Comment by fice-t** [comment]
This also apparently happens for instant squash commits and the non-instant versions as well.

**Comment by tarsius** [comment]
> Also, switching to that diff buffer and pressing q will result in the status buffer having a right margin containing the commit dates.

That doesn't happen for me. Can you give steps from `emacs -Q` to reproduce this?

**Comment by tarsius** [comment]
Using `magit-mode-bury-buffer` instead of `quit-restore-window` seems to do the trick. See #3213.

**Comment by fice-t** [comment]
It seems to work, thanks.

> That doesn't happen for me. Can you give steps from emacs -Q to reproduce this?

1. Use result of `magit-emacs-Q-command`
2. Open a status buffer
3. Stage something and do an instant fixup
4. `C-c C-c` to select a commit
5. Point should now be in the status buffer, so use `C-x o` to switch to the lingering diff buffer
6. `q` in the diff buffer
7. The selected window is now the status buffer, but there is a margin with dates of the commits, beside any `Stashes` and `Unmerged into` sections (probably more sections too).

**Comment by fice-t** [comment]
@tarsius 
Though while we're on the topic of `magit-log-select-pick`, I noticed that after selecting a commit for a rebase action, the status buffer is momentarily shown. Is there a way to avoid that? It's a bit annoying once you see it.
