### ISSUE TITLE
Calling magit-patch-save with C-x C-w shouldn't use magit-refresh-args

### ISSUE THREAD

**Issue by fice-t** [magit/magit#3218]
I think `C-x C-w` on a diff shouldn't use any diff arguments by default (or at least some should be stripped). This would make it easier to save a "bare" diff to a file. Or, it could take a prefix argument that would enable/disable arguments (I'd prefer enable, myself).

Then, perhaps a new corresponding action can be added to the diff popup that takes the refresh arguments into account.

I made this issue since `-s` is a default argument, which is nice to have in revision/diff buffers, but is unnecessary when saving the diff to a file.

**Comment by tarsius** [comment]
I have chosen the current approach because `C-x C-w` usually saves the buffer as-is. Of course one could argue that we are already not doing that and that we might as well diverge further.

**Comment by fice-t** [comment]
> Of course one could argue that we are already not doing that and that we might as well diverge further.

I would. :)

I imagine that I will mainly use this feature for copying minimal diffs to share with others, so the fluff provided by `-s` and other arguments just gets in the ways.

On that note, it would be nice if there was a way to instead copy the bare diff into the kill ring rather than saving it to a file, but that's less important.

**Comment by tarsius** [comment]
> I think `C-x C-w` on a diff shouldn't use any diff arguments by default (or at least some should be stripped). This would make it easier to save a "bare" diff to a file. Or, it could take a prefix argument that would enable/disable arguments (I'd prefer enable, myself).

All of these variations are possible now using a fairly simple option and the prefix argument.

> Then, perhaps a new corresponding action can be added to the diff popup that takes the refresh arguments into account.

I don't think that that would be convenient.
