### ISSUE TITLE
Staging all changes: only in subdirectories of defaut-directory?

### ISSUE THREAD

**Issue by mookid** [magit/magit#3221]
When commiting from magit (calling directly `magit-commit`), the user gets asked to stage everything.

If yes, magit calls `git add -u .` from the current directory.

I expected that command to be run from the root directory of the current repository, have something similar to running `git commit -a`. Is that a bug, or am I missing a more appropriate command?

**Comment by tarsius** [comment]
Thanks for reporting.

The command wrongly assumed it was called from a magit buffer where the `default-directory` is always equal to the root of the repository.

**Comment by mookid** [comment]
Thanks!
