### ISSUE TITLE
Ambiguous refname woes

### ISSUE THREAD

**Issue by kyleam** [magit/magit#3223]
### Issues

We've had a few issues (#1888, #3098, #3222) about different cases
that fail when a branch and tag share the same name.  Given that most
users don't (and shouldn't!) name things ambiguously, it's not
surprising that there are unreported places where ambiguous refnames
cause problems.

Here are the issues that I'm aware of, though of course there are
likely more.

  * If the names for local and remote branch are ambiguous, we always
    qualify the branch at point to the local name.  Likewise, if a
    branch and a tag are ambiguous, we assume it's a local branch.

    Because local and remote branches have the same section type,
    there really isn't an easy way to know which it is.  We could use
    separate section types, but doing so in order to deal with
    ambiguous names is an overkill.

  * `magit-wip-log` always appends "refs/heads/" to branch, even
    though branch may already be qualified in local name collection

  * There are places where we query branch and tag collections that
    may include the qualified names, but the element we are looking
    for is usually unqualified even when the name is ambiguous.

    More generally, some functions return qualified refs and others
    don't, and we assume their output is compatible.

  * We expect the values we receive from `git symbolic-ref` (through
    `magit-get-current-branch`) and `git for-each-ref` to qualify
    names in the same way, but their output isn't identical.

    `symbolic-ref --short` only qualifies when a local branch name
    conflicts with a tag, not a remote.
    `git for-each-ref --format="%(refname:short)"`, on the other hand,
    qualifies the local branch when it conflicts with a remote if
    `core.warnAmbiguousRefs` is set to the default of `true`.

### What to do?

One option is to try to fix the issues above as well as future ones
that pop up.  The problem is that doing so will involve a lot of
effort, widespread changes, and kludges in support of a naming
practice that we don't want to encourage.

The direction that I'd like to go (or at least test) is removing all
special handling for ambiguous refs.  Use unqualified refs in all of
our collections, prompts, etc, and let the downstream Git commands
succeed when they're happy accepting an unqualified ambiguous ref (git
checkout, git branch, git tag, etc) or fail with a message about
ambiguous refs.

As a result, we'd reintroduce issues like #3098.  But I think it'd be
better to just say "we always use the unqualified name; please don't
use ambiguous names" (and mention this in the manual as well).

I think this is more or less the approach that Jonas advocates in the
message of 3b7dbecaa.  Thoughts?

**Comment by kyleam** [comment]
> The direction that I'd like to go (or at least test) is removing all
> special handling for ambiguous refs. Use unqualified refs in [...]

Looking at this paragraph again, I'd scratch the bits after the first
sentence as being confusing or too strongly worded.  I don't think we
should try to force the short-name variants of Git commands like
`for-each-ref` and `symbolic-ref` to return ambiguous refs as
unqualified.  The suggestion is just that we remove the special
handling and document the assumption that there are no ambiguous refs.

**Comment by tarsius** [comment]
> I think this is more or less the approach that Jonas advocates [by saying:]

> Ambiguous refs are user mistakes and we should
> allow fixing these mistakes using Magit.  But anything that goes beyond
> that would not be worth it because it would force users to deal with
> full refs all the time in many places where we would rather use the
> short branch names.

We have to keep in mind that it's not always the user's mistake - sometimes it's the mistake of their colleges. The issue brought up here falls into the "we should allow fixing these mistakes" category, I think.

I don't think that we should remove existing kludges, provided that they don't make other things impossible or at least harder or inconvenient (for users or us).

> The direction that I'd like to go (or at least test) is removing all special handling for ambiguous refs.

I won't object to you doing that. Even if we end up not merging the result, it would still be nice to see how much things could be easier if we didn't have to deal with this. And that would also serve as documentation.

**Comment by kyleam** [comment]
> The issue brought up in #3222 falls into the "we should allow fixing these mistakes" category, I think. (Is this a regression?)

Not a recent regression, at least.  I just tested 2.3.0, and it has
the same error.  I'd guess it's been around since
`magit-branch-rename` has existed.

**Comment by kyleam** [comment]
> Even if we end up not merging the result, it would still be nice to see how much things could be easier if we didn't have to deal with this.

I've pushed the (untested) result to the [km/drop-ambig] branch.
There's not that much to drop, and I don't think it's much of a
maintenance burden (in the current form).  My desire to drop the
ambiguous ref handling mostly stems from a "we don't want to go
through the effort of making sure we can support it everywhere, so
let's not support it at all".  I'm not sure why that's my leaning in
this case, though, and accept that your more pragmatic "I don't think
that we should remove existing kludges, provided [...]" is probably
the best option.

[km/drop-ambig]: https://github.com/magit/magit/compare/km/drop-ambig

**Comment by tarsius** [comment]
Please add a FAQ entry and then close this.

**Comment by tarsius** [comment]
Thanks!
