### ISSUE TITLE
Magit failes on non-english branch names

### ISSUE THREAD

**Issue by simendsjo** [magit/magit#3225]
Magit 20171023.926, Git 2.14.0.windows.1, Emacs 25.3.1, windows-nt

Seems like magit doesn't work when using non-english branch names.

```
1 C:/Program Files/Git/mingw64/libexec/git-core/git.exe … "checkout" "lån"
error: pathspec 'lÃ¥n' did not match any file(s) known to git.
```

**Comment by npostavs** [comment]
Works for me. Can you reproduce this starting from the command produced by `M-x magit-emacs-Q-command`? #3111 seems similar, and OP reported that spacemacs config seems to cause it.

Magit 2.11.0-146-gf4f4e9b, Git 2.6.2.windows.1, Emacs 25.1.1, windows-nt

```
  0 C:/Git-2.x/mingw64/libexec/git-core/git … "checkout" "lån"
Switched to branch 'lån'
```

**Comment by simendsjo** [comment]
I see in the other thread that spacemacs might be the problem? I tried running `magit-emacs-Q-command`, pasting it in the terminal, which opened another emacs (without spacemacs), and ran checkout again. This yields the same error.

```
  1 C:/Program Files/Git/mingw64/libexec/git-core/git.exe … checkout l\ån

Tag:      master-1.1.0.1255 (6)
error: pathspec 'lÃ¥n' did not match any file(s) known to git.
```

**Comment by simendsjo** [comment]
I testet on Linux, but otherwise very similar setup, without being able to reproduce the issue. I'm using the following emacs installation on windows: https://sourceforge.net/projects/emacsbinw64/

**Comment by npostavs** [comment]
> I tried running magit-emacs-Q-command, pasting it in the terminal

Is this terminal an Msys or cygwin terminal, by any chance? I notice you are getting different quoting, which suggests `$SHELL` is set to `bash`. 

I can reproduce the error when I run from an Msys terminal. Unsetting `$LANG` fixes it.

**Comment by simendsjo** [comment]
Seems like some strange thing from my emacs distribution: `C:/programs/emacs/libexec/emacs/25.3/x86_64-w64-mingw32/cmdproxy.exe`

**Comment by npostavs** [comment]
Hmm, that looks normal.

What do the following give you? The ielm transcript gives my values (using the same Emacs binary as you linked to) for comparison.
```
*** Welcome to IELM ***  Type (describe-mode) for help.
ELISP> (w32-shell-dos-semantics)
("cmd.exe" "command" "command.com" "4nt" "4nt.exe" "4dos" "4dos.exe" "tcc" "tcc.exe" "ndos" "ndos.exe")
ELISP> shell-file-name
"c:/emacs-25.3/libexec/emacs/25.3/x86_64-w64-mingw32/cmdproxy.exe"
ELISP> (getenv "$LANG")
nil
ELISP> current-language-environment
"English"
ELISP> process-coding-system-alist
(("[pP][lL][iI][nN][kK]" undecided-dos . undecided-dos)
 ("[cC][mM][dD][pP][rR][oO][xX][yY]" undecided-dos . undecided-dos))

ELISP> default-process-coding-system
(undecided-dos . undecided-unix)

ELISP> coding-system-for-write
nil
```

**Comment by npostavs** [comment]
Please try the patch in #3250.

**Comment by tarsius** [comment]
@simendsjo Please check whether this fix works for you.

**Comment by simendsjo** [comment]
I'm not actually sure how to do this. I'm new to emacs, and I'm using spacemacs so pretty much everything is magically handled for me.

**Comment by simendsjo** [comment]
@npostavs:

```
ELISP> (w32-shell-dos-semantics)
("cmd.exe" "command" "command.com" "4nt" "4nt.exe" "4dos" "4dos.exe" "tcc" "tcc.exe" "ndos" "ndos.exe")

ELISP> shell-file-name
"C:/programs/emacs/libexec/emacs/25.3/x86_64-w64-mingw32/cmdproxy.exe"
ELISP> (getenv "$LANG")
nil
ELISP> current-language-environment
"Latin-1"
ELISP> process-coding-system-alist
(("[pP][lL][iI][nN][kK]" undecided-dos . undecided-dos)
 ("[cC][mM][dD][pP][rR][oO][xX][yY]" undecided-dos . undecided-dos))

ELISP> default-process-coding-system
(utf-8-dos . utf-8-unix)

ELISP> coding-system-for-write
nil
```

**Comment by npostavs** [comment]
> ```
> ELISP> default-process-coding-system
> (utf-8-dos . utf-8-unix)
> ```

This is the signficant difference, but the new patch which was installed a couple of days ago should make it work regardless.

**Comment by simendsjo** [comment]
Tried again now, and it works now. Thanks!

**Comment by npostavs** [comment]
Thanks for checking. By the way, I think your setting of `default-process-coding-system` to `utf-8` could cause problems for other programs you execute from Emacs, if you want to pass non-ascii arguments to them. I guess that comes the "Latin-1" language environment, though I'm not sure why you get that. The Emacs manual talks only about `LC_ALL`, `LC_CTYPE`  or `LANG` environment variables affecting ([(emacs) Language Environments](https://www.gnu.org/software/emacs/manual/html_node/emacs/Language-Environments.html)).

**Comment by simendsjo** [comment]
I don't actually have a LANG variable set, but Emacs thinks I do, and believes it's NOR. LC_* doesn't exist as expected. I have no idea what kind of magic Emacs is doing on Windows here. I can't remember having other problems related to encoding, but I'm not really a big user of Emacs on Windows.
