### ISSUE TITLE
rebase status is lost with worktrees

### ISSUE THREAD

**Issue by peterhurley** [magit/magit#3228]
Using magit with a normal git repo, perform an interactive rebase (or a reword rebase).
Magit is aware of the state of the rebase; ie., 'r' in the magit buffer invokes the popup with c continue a abort
This is not the case with a git worktree; magit is not aware of the state of the rebase; 'r' in the magit buffer invokes the normal rebase popup.

**Comment by npostavs** [comment]
I use rebase in worktrees all the time, it works fine. Are you expecting the rebase state of one worktree to affect the others?

**Comment by peterhurley** [comment]
Hmm, maybe it's only broken over tramp and with-editor?

And no, I'm not expecting shared rebase state. That would defeat the purpose of git worktrees.

**Comment by npostavs** [comment]
Ah, okay, I don't use magit over tramp, so not sure about that case.

**Comment by tarsius** [comment]
> Hmm, maybe it's only broken over tramp and with-editor?

Could you please narrow the issue down? Does it, or does it not, matter whether Tramp is involved? It would be best if you could come up with same minimal steps from `emacs -Q` to reproduce this.

**Comment by tarsius** [comment]
The issue only appears in *secondary* working trees accessed using Tramp. Or more generally if `.git` is a file containing an absolute path to the actual git directory, then `magit-git-dir` returned a local path instead of one prefixed with Tramp's host information.
