### ISSUE TITLE
Cannot install magit with el-get

### ISSUE THREAD

**Issue by subhacom** [magit/magit#3229]
Using emacs 25.3 on Windows 7 with msys64 I encounter this error when trying install magit:
Error (el-get): while installing magit: el-get: c:/msys64/usr/bin/install-info.exe el-get could not build magit [c:/msys64/usr/bin/install-info.exe c:\Users\UserName\AppData\Roaming\.emacs.d\el-get\magit\Documentation\magit.info dir]

I can, however,  install magit from the usual packages list via list-packages command.

**Comment by npostavs** [comment]
Please report this to the el-get issue tracker.

**Comment by charmoniumQ** [comment]
For posterity's sake, here's a link to the el-get issue el-get/el-get#2574
