### ISSUE TITLE
magit-rebase-reword-commit should auto-stash

### ISSUE THREAD

**Issue by mgeisler** [magit/magit#3231]
I think it would be great if `r w` could default to auto-stash any changes in the working directory. This should be a safe default since there can be no conflicts created when you simply edit the commit message.

**Comment by tarsius** [comment]
Just enable that in the popup and then save it as the default using <kbd>C-x C-s</kbd>. (Use <kbd>C-t</kbd> in any popup to show other "common commands.)

**Comment by mgeisler** [comment]
Hey @tarsius, thanks for the prompt reply! :-)

I was under the impression that it would be the default for all rebase related commands after that. _Testing..._ Yeah, `--auto-stash` is now also the default for normal rebases. I guess that might be okay, but it can potentially lead to unexpected conflicts. I suppose aborting the rebase will still restore the auto-stash in that case, so users can still recover easily from any surprise.

Thanks!
