### ISSUE TITLE
Reverting region from commit in file renamed in that commit creates new file

### ISSUE THREAD

**Issue by greenrd** [magit/magit#3235]
Magit 2.11.0, Git 2.14.1.windows.1, Emacs 25.1.1, windows-nt

I viewed a change from a previous commit on my current branch, selected a region, and pressed 'v' to revert the region in my working tree. This change happened to be in a file which was renamed in that commit. What I expected to happen was for the file (under its new name) to be patched with the region change. What actually happened was a new, untracked file was created under the _old_ name, containing the change I expected.

So it looks like it reverted the rename as well as the selected region. I didn't want to revert the rename, only the region.

What I think magit should do is either (a) not revert the rename when a region inside a renamed file is selected for reverting, or (b) ask whether to revert the rename as well as the region.

**Comment by tarsius** [comment]
If you do a 3-way, then this won't happen. Use a prefix argument to do so.
