### ISSUE TITLE
`magit-reset` and friends do not accept 'HEAD~1' or 'HEAD^1' as an argument.

### ISSUE THREAD

**Issue by bdollard** [magit/magit#3236]
Hi,  I noticed this problem with magit after upgrading this morning. 

Steps to reproduce:
1. Clone magit repo, at 17efbc0 (current master)
2. Run `make emacs-Q`
3. `M-x magit-reset`
4. Attempt to enter `HEAD~1`
5. Observe `[No match]` after pressing `ret`

Regards, and thanks for the good work.

**Comment by tarsius** [comment]
Thanks for reporting that is indeed a recent regression. I have reverted the misguided "cosmetic" change.
