### ISSUE TITLE
Allow picking the key used for tag signing

### ISSUE THREAD

**Issue by rgaiacs** [magit/magit#3237]
# Expected behaviour

I should be able to specify the GPG key that I want to use when sign commits and tags.

# Observed behaviour

When I'm going to create a signed commit, I can select my GPG key.

![screenshot from 2017-11-01 15-38-12](https://user-images.githubusercontent.com/1506457/32282984-0a59a696-bf1b-11e7-9357-ef1f232a8aec.png)

But when I'm going to create a signed tag, I can't select my GPG key.

![screenshot from 2017-11-01 15-38-33](https://user-images.githubusercontent.com/1506457/32283019-278609c6-bf1b-11e7-8fc2-baaef6286161.png)

I think that this might be the cause of

~~~
git … tag --annotate --sign v1.9.0 master
Waiting for Emacs...
error: gpg failed to sign the data
error: unable to sign the tag
The tag message has been left in .git/TAG_EDITMSG
~~~

that I'm experiencing.

# How to reproduce

`M-x magit-version RET` returns `Magit 2.10.3, Git 2.14.2, Emacs 25.3.1, gnu/linux`. 

For the first screenshot, you can press `c` followed by `=S`.

For the second screenshot, you can press `t` followed by `-s`.

**Comment by tarsius** [comment]
`tag`'s `--sign` does not allow specifying a key:

       -s, --sign
           Make a GPG-signed tag, using the default e-mail address’s key.

So you have to make sure there is a key for the address specified by `user.email`.

**Comment by rgaiacs** [comment]
@tarsius Thanks for the great work and all the support.

Would be possible to use `-u`?

~~~
-u <keyid>, --local-user=<keyid>
           Make a GPG-signed tag, using the given key.
~~~

> So you have to make sure there is a key for the address specified by `user.email`.

I have `user.email` on my configurations.

~~~
$ git config --global user.email
raniere@rgaiacs.com
$ gpg -K raniere@rgaiacs.com
sec   rsa4096 2013-03-03 [SC] [expires: 2018-04-23]
      1036E8875F5BFF2B7EC734137BCC72FA54A575CD
uid           [ unknown] Raniere Silva <raniere.silva@software.ac.uk>
uid           [ unknown] Raniere Gaia Costa da Silva <raniere@ime.unicamp.br>
uid           [ unknown] Raniere Gaia Costa da Silva <raniere@rgaiacs.com>
ssb   rsa4096 2013-03-03 [E]
~~~

I will dig more to try to find the cause. Feel free to close this issue.

**Comment by tarsius** [comment]
> Would be possible to use `-u`?

I overlooked that... `git tag` and `git commit` are... not exactly consistent with regards to the arguments used for signing.

I will leave this issue open as it should be possible to use that argument. So it's a feature request :wink:

**Comment by tarsius** [comment]
I think the `[ unknown]` means that you are not trusting your own key.

**Comment by basil-conto** [comment]
> I think the [ unknown] means that you are not trusting your own key. For my own key gpg says [ultimate].

Not the wittiest remark, but it still reminded me of, "I only distrust people for one of two reasons; either because I don't know them, or because I do."
