### ISSUE TITLE
Attempt to stage "overlong" region results in staging everything without confirmation

### ISSUE THREAD

**Issue by greenrd** [magit/magit#3238]
Magit 2.11.0, Git 2.14.1.windows.1, Emacs 25.1.1, windows-nt

I accidentally overshot the end of a file diff when selecting a region in the magit buffer by pressing Shift+Down one time too many. I then pressed 's' to stage, thinking the overshoot wouldn't matter. But it did. Without asking me, magit immediately staged everything that was unstaged (something I don't know how to undo). I have confirmed this issue in another repo, so it wasn't a case of me pressing Shift accidentally when I pressed 's'.

**Comment by tarsius** [comment]
Magit didn't ask you, but it did *show* you that this would happen.

I assume you went from

![1](https://user-images.githubusercontent.com/25046/32293908-e103de04-bf44-11e7-9fe0-3dca3c2c9f60.png)

to

![2](https://user-images.githubusercontent.com/25046/32293941-ff227e0e-bf44-11e7-92e8-4156c33973e5.png)

In a Magit buffer, when the region looks like it looks in any other Emacs buffer, then that indicates that it is not a valid Magit selection. As a result all commands that optionally act on the selection fallback to their normal behavior, in most cases that means they act on the current section. In this case that is the "Unstaged changes" section - as can be seen (*) by the section highlighting.

(*) Or should be. The "Unstaged changes:" line should have the same background color as the rest of the current section (including the children and the trailing newline). That's a minor visual bug in an edge-case, which I will fix. With point on the trailing newline and without an active region that isn't valid as a magit-selection it looks like this:

![3](https://user-images.githubusercontent.com/25046/32294358-3abc7d42-bf46-11e7-8483-5d2cfb6a4688.png)

**Comment by tarsius** [comment]
I have fixed that special case. A list section is now properly highlighted when it contains a region that is not valid as a magit-selection:

![4](https://user-images.githubusercontent.com/25046/32295952-126b2b40-bf4b-11e7-87b4-db9f68571fda.png)

**Comment by tarsius** [comment]
With that applied, I don't think there is anything else to be fixed. This is the expected behavior.

**Comment by greenrd** [comment]
The problem here is I don't think there is any way to undo a "stage all" operation if I make a mistake like this. C-_ justs says the buffer is read-only.

**Comment by npostavs** [comment]
Hmm, pressing <kbd>u</kbd> on the `Unstaged changes` section header and <kbd>U</kbd> anywhere always prompt me for confirmation, but <kbd>s</kbd> on `Staged changes` never does. <kbd>S</kbd> prompts me only when there are some existing staged changes.

All of these commands should rather use the <kbd>S</kbd> prompt behaviour, right?

**Comment by tarsius** [comment]
> All of these commands should rather use the <kbd>S</kbd> prompt behaviour, right?

I think so, yes.

**Comment by npostavs** [comment]
> Hmm, pressing u on the Unstaged changes section header and U anywhere always prompt me for confirmation

Ah, these were "always" prompting me because I happened to have a few untracked files lying around.

Changing the `s` on `Staged changes` to call `magit-stage-modified` solves that case: https://github.com/magit/magit/compare/np/stage-prompt

**Comment by tarsius** [comment]
> https://github.com/magit/magit/compare/np/stage-prompt

With that approach we would also have to deal with the different meanings of the prefix argument. I just moved the confirmation into the function body.
