### ISSUE TITLE
On Windows magit-revert is completed without editing commit message

### ISSUE THREAD

**Issue by yasuhirokimura** [magit/magit#3239]
OS: Japanese Windows 10 Enterprise 64bit version 1709
Git: Version 2.15.0 (Official Windows 64 bit binary)
Emacs: 25.3 ( Private binary build with MSYS2)
Magit: 2.11.0 (Installed by using magit-2.11.0.tar.gz)
Value of `M-x magit-version`: Magit 2.11.0, Git 2.15.0.windows.1, Emacs 25.3.1, windows-nt

On Unix (CentOS, Debian, FreeBSD, etc.), if I type `V V RET` Magit switches to buffer to edit commit message.  And if I type `C-c C-c` then reverting is completed. But on Windows typing `V V RET` results in immediate completion of reverting without editing commit message. I tried `M-x magit-emacs-Q-command RET` method but result didn't changed.

**Comment by tarsius** [comment]
That's because of

```
       -e, --edit
           With this option, git revert will let you edit the commit message
           prior to committing the revert. This is the default if you run the
           command from a terminal.
```

and

```lisp
(defcustom magit-process-connection-type (not (eq system-type 'cygwin))
  "Connection type used for the Git process.

If nil, use pipes: this is usually more efficient, and works on Cygwin.
If t, use ptys: this enables Magit to prompt for passphrases when needed."
  :group 'magit-process
  :type '(choice (const :tag "pipe" nil)
                 (const :tag "pty" t)))
```

I'll probably add `--edit` to the popup and enable it by default.
