### ISSUE TITLE
Supporting git review in magit

### ISSUE THREAD

**Issue by everiori** [magit/magit#3240]
Is there any plan to support git review? I am using magit everyday, and I also need to use git review with gerrit, if magit can support git review, then I do not need to leave emacs anymore for code developing.

**Comment by tarsius** [comment]
> Is there any plan to support git review?

No. My plans concerning collaboration support are outlines in #2972. Something that I mention there is that I don't plan to base Magit's features on one (or multiple) external tools. I will look at existing tools to learn from them and to make Magit compatible where possible though.

I intend to support "git forge"-based (Github, Gitlab...) collaboration first, then mailing list based collaboration. Specialized issue trackers like Gerrit are a low priority I *might* eventually get around to supporting.

However there already exists [`magit-gerrit`](https://github.com/terranpro/magit-gerrit) a "Magit plugin for Gerrit Code Review".
