### ISSUE TITLE
Failures with newline in filename

### ISSUE THREAD

**Issue by SkySkimmer** [magit/magit#3241]
In some git repository, make a file named `foo bar`. Magit sees it in untracked files and `magit-stage` works, but then it displays
```
Staged changes (1)
new file   foo
```
and `magit-discard` fails silently.

A file with a newline also gets staged successfully, after which it is displayed as 
```
Staged changes (1)
new file   new
line
```
However discard fails silently.

Reproduces with `magit-emacs-Q-command`, version `Magit 2.11.0-185-gedbab840, Git 2.14.2, Emacs 25.2.2, gnu/linux` (debian packages for git and emacs, magit installed from git).

**Comment by tarsius** [comment]
I can reproduce this for filenames that contain a newline but not for files containing a space.

**Comment by SkySkimmer** [comment]
Stupid mistake on my part when reporting, the filename with space I actually tested was `bar bar`.
Indeed I can't reproduce with `foo bar`.

**Comment by tarsius** [comment]
Even though I have labeled this as a bug, I am not sure it would really be worth the effort to support newlines in filenames.

**Comment by tarsius** [comment]
I am closing this as `wontfix`. When I do major refactorings, then I do look at such issue. So there is hope this will eventually get addressed, but given the current implementation fixing this *would be* a major refactoring.
