### ISSUE TITLE
Eager macro-expansion failure: (wrong-type-argument keymapp nil) while require magit.

### ISSUE THREAD

**Issue by ogdenwebb** [magit/magit#3242]
Magit 20171103.210, Git 2.15.0, Emacs 25.3.1, Void Linux x86_64.

I'm not sure, but presumably it began to appear one or two days ago.

**Comment by tarsius** [comment]
Please do `M-x toggle-debug-on-error` and then post the resulting backtrace here.

**Comment by ogdenwebb** [comment]
Huh, how strange. I'm using general.el package to bind my keys and I had some bindings for eshell mode, but the error above appears only when I require magit(works well with other packages). I will report this bug in the general.el repo then.

Sorry for the inconvenience.
