### ISSUE TITLE
`magit-branch-or-commit-at-point` returns wrong value on stash line

### ISSUE THREAD

**Issue by fice-t** [magit/magit#3259]
Since b13b0482f81030373ae6ff157df94b8998b3a043, `magit-branch-or-commit-at-point` returns `stash` when the point is on the beginning of `stash@{N}` line.

This means that some completion commands (e.g., `T T`) show `stash` as the default candidate rather than `stash@{N}`.

**Comment by tarsius** [comment]
Thanks!
