### ISSUE TITLE
magit refs, TAB on checked out branch, hides the branch on refresh

### ISSUE THREAD

**Issue by duianto** [magit/magit#3267]
#### Expected behaviour:
In the magit-refs buffer, pressing `TAB` on the checked out branch, and refreshing or closing and reopening the magit-refs buffer, shouldn't hide the checked out branch.

#### Observed behaviour:
The checked out branch becomes hidden, when `TAB` is pressed on it, in the magit-refs buffer, and the buffer is refreshed or closed and reopened.

The checked out branch appears, when the magit-refs buffer is refreshed or reopened again.

#### System Info:
Magit 20171112.348, Git 2.14.1.windows.1, Emacs 26.0.50, windows-nt

#### Steps to reproduce:
In Spacemacs I called `M-x` `magit-emacs-Q-command`, which gave me the command to start Emacs with Magit and it's dependencies. I ran the command in the `cmd` Command Prompt window.

1. Open `M-x` `magit-status` with a repository that has at least two branches (I chose the Spacemacs `.emacs.d` repository)
2. Press `y` to open the magit-refs buffer
3. Press `TAB` on the checked out branch (in this case `develop`), nothing happens (at least not visually)
4. Refresh the magit-refs buffer `g`, the checked out branch disappears and the Branches (nr) counter decrements.
5. Refresh the magit-refs buffer `g` again, the checked out branch appears and the Branches (nr) counter increments.

#### Notes:
The same thing happens with remote branches that have the same name:
`Upstream/develop` and `fork/develop`.

Something seems to be toggled in the background when `TAB` is pressed, because if `TAB` is pressed twice then the checked out branch, doesn't disappear when the magit-refs buffer is refreshed.

Is it by design or a bug, that the checked out branch, doesn't unfold it's commits when `TAB` is pressed? Like the other non-checked out branches do.

**Comment by tarsius** [comment]
> Is it by design or a bug, that the checked out branch, doesn't unfold it's commits when `TAB` is pressed?

Yes, expanding a branch shows the "cherries", i.e. the commits that that branch contains that are missing from the current branch and vice-versa. Obviously those sets are always empty when comparing a branch to itself.

> Refresh the magit-refs buffer `g`, the checked out branch disappears and the Branches (nr) counter decrements.

That's a bug and it is very likely that it is due to the above edge-case not being handled correctly.

**Comment by tarsius** [comment]
Fixed. Thanks for reporting. This actually was a fun bug to fix.
