### ISSUE TITLE
Precedence of `magit-log-section-commit-count` vs `magit-log-section-arguments` in `magit-insert-recent-commits`

### ISSUE THREAD

**Issue by MatthewFluet** [magit/magit#3270]
Late discussion in #3147 (https://github.com/magit/magit/issues/3147#issuecomment-340909015) noted that the `Recent commits` section might show more than `magit-log-section-commit-count` items in the presence of merge commits.

@tarsius wrote:
> The variable `magit-log-section-commit-count` controls how many commits we **try** to display. Obviously if there are fewer commits than that, then we cannot display that many commits. We use the value of that variable as the N in `git log -n N ...`. If there are merge commit in the range `HEAD~N..HEAD`, then that git command may display *more* commits in order to produce a meaningful history.

This is a little surprising, since `git log -n N ...` should only show N commits, regardless of the range.  What seems to be happening is that `magit-insert-recent-commits` forms the arguments for `magit-insert-log` with `(cons (format "%-d" magit-log-section-commit-count) magit-log-section-arguments))` and, in the default configuration, `magit-log-section-arguments` includes `-n256`.  Thus, `magit-insert-log` is actually displaying `git log -N -n256 ...` and the `-n256` "wins", which explains the more than N.

Would it make sense to form the arguments for `magit-insert-log` with `(-snoc magit-log-section-arguments) (format "%-d" magit-log-section-commit-count))` to allow the `-N` to "win"?  The fact that a `-N` argument is constructed seems to imply that it was meant to limit the output.

For a repo where `master` evolves exclusively by merges (i.e., pull requests), the current behavior can lead to a very large `Recent commits` section, essentially 256 commits from the last 10 merges.  While I could remove the `-n256` argument from `magit-log-section-arguments`, I presume that the limit is there avoid accidentally generating a massive log.

As another aside, if the arguments were reversed, could `magit-insert-recent-commits` be further simplified to simply log `HEAD`?  That is, when would `git log -N HEAD~N..HEAD` be different from `git log -N HEAD`?

**Comment by tarsius** [comment]
> This is a little surprising, since `git log -n N ...` should only show N commits,

Yeah, I think now that it also isn't true. I'll have to look into the alternative explanation you provided - that sounds more plausible at least.

**Comment by tarsius** [comment]
> Thus, `magit-insert-log` is actually displaying `git log -N -n256 ...` and the `-n256` "wins", which explains the more than N.

That doesn't happen for me, but given this detailed description I believe you ;-) Most likely that depends on the Git version. What version are you using?

**Comment by MatthewFluet** [comment]
I see the same behavior with git 2.7.4 and git 2.15.0:

```
[mtf@oxygen tmp]$ git --version
git version 2.7.4
[mtf@oxygen tmp]$ git clone -q https://github.com/MLton/mlton
[mtf@oxygen tmp]$ cd mlton/
[mtf@oxygen mlton]$ git log --oneline -10 -n256 HEAD~10..HEAD | wc -l
48
[mtf@oxygen mlton]$ git log --oneline -n256 -10 HEAD~10..HEAD | wc -l
10
```

```
[mtf@uller tmp]$ git --version
git version 2.15.0
[mtf@uller tmp]$ git clone -q https://github.com/MLton/mlton
[mtf@uller tmp]$ cd mlton/
[mtf@uller mlton]$ git log --oneline -10 -n256 HEAD~10..HEAD | wc -l
      48
[mtf@uller mlton]$ git log --oneline -n256 -10 HEAD~10..HEAD | wc -l
      10
```

**Comment by tarsius** [comment]
Okay, I am seeing the same in a repository with many recent merges, even when using v2.15.0.

**Comment by tarsius** [comment]
Thanks for the detailed analysis - it helped a lot.
