### ISSUE TITLE
Error on "make install"

### ISSUE THREAD

**Issue by YorkZ** [magit/magit#3271]
Magit version: Git 88910e68

Details:

    $ sudo make install
    make[1]: Entering directory `/home/york/.emacs.d/lisp/vendor/magit/lisp'
    make[1]: Nothing to be done for `lisp'.
    make[1]: Leaving directory `/home/york/.emacs.d/lisp/vendor/magit/lisp'
    make[1]: Entering directory `/home/york/.emacs.d/lisp/vendor/magit/lisp'
    install -p -m 644 git-commit.el magit-popup.el magit-utils.el magit-section.el magit-git.el magit-mode.el magit-margin.el magit-process.el magit-autorevert.el magit-core.el magit-diff.el magit-log.el magit-wip.el magit-apply.el magit-repos.el magit.el magit-status.el magit-refs.el magit-files.el magit-branch.el magit-worktree.el magit-notes.el magit-obsolete.el magit-sequence.el magit-commit.el magit-remote.el magit-bisect.el magit-stash.el magit-blame.el magit-submodule.el magit-subtree.el magit-ediff.el magit-extras.el git-rebase.el magit-imenu.el magit-bookmark.el magit-autoloads.el magit-version.el git-commit.elc magit-popup.elc magit-utils.elc magit-section.elc magit-git.elc magit-mode.elc magit-margin.elc magit-process.elc magit-autorevert.elc magit-core.elc magit-diff.elc magit-log.elc magit-wip.elc magit-apply.elc magit-repos.elc magit.elc magit-status.elc magit-refs.elc magit-files.elc magit-branch.elc magit-worktree.elc magit-notes.elc magit-obsolete.elc magit-sequence.elc magit-commit.elc magit-remote.elc magit-bisect.elc magit-stash.elc magit-blame.elc magit-submodule.elc magit-subtree.elc magit-ediff.elc magit-extras.elc git-rebase.elc magit-imenu.elc magit-bookmark.elc /usr/local/share/emacs/site-lisp/magit
    install: cannot stat ‘magit-version.el’: No such file or directory
    make[1]: *** [install] Error 1
    make[1]: Leaving directory `/home/york/.emacs.d/lisp/vendor/magit/lisp'
    make: *** [install-lisp] Error 2

**Comment by tarsius** [comment]
Thanks for the report!
