### ISSUE TITLE
"Void variable magit-process-error-message-re" when magit-git-debug is non-nil

### ISSUE THREAD

**Issue by lukertty** [magit/magit#3272]
## To reproduce

1. emacs -Q

2. paste and eval-buffer
```elisp
(setq package-user-dir "/Users/lukertty/.emacs.d/elpa-26.0.90")
(package-initialize)
(require 'magit)
(setq magit-git-debug t)
```
3. M-x magit-log-buffer-file and press enter
4. `Symbol’s value as variable is void: magit-process-error-message-re`

## Environment
macOS 10.11.6
Emacs version: 
```
GNU Emacs 26.0.90 (build 1, x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G17023)) of 2017-11-10
```
magit version: magit-20171117.514

**Comment by tarsius** [comment]
Thanks for the report!

**Comment by tarsius** [comment]
Ups wrong issue.

**Comment by tarsius** [comment]
Thanks for the report.
