### ISSUE TITLE
magit-show-commit is now unusably slow

### ISSUE THREAD

**Issue by trezona-lecomte** [magit/magit#3275]
Hi there,

Looks like a recent update has made `magit-show-commit` unusably slow. 

**Expected behaviour:**
`magit-show-commit` will display a commit within a few seconds.

**Observed behaviour**
`magit-show-commit` takes multiple _minutes_ to show a commit.

**Steps to reproduce**
1. With `magit` version 20171120.1023 installed, run `M-x magit-status` in a git repo.
2. Type `l`, `l` to execute `log current`. I'm using `--graph`, --decorate`, and `-n"256"` flags, but you can observe the behaviour with no flags enabled.
3. With point on any commit in the log buffer, hit `RET` to execute `magit-show-commit`.
4. Wait for about 1-2 minutes for the commit to show.

**M-x magit-version RET**
`Magit 20171120.1023, Git 2.15.0, Emacs 25.3.1, darwin`

Of note, I am using a fork of https://github.com/purcell/emacs.d, but a colleague of mine is using Spacemacs and observes the same behaviour after updating to this version of magit.

**Profiling**
I ran a quick profile to see what might be happening. The below is the output of doing:

- Steps 1-2 from above, so ending up in the log buffer,
- then running `M-x profiler-start` (cpu)
- then hitting `RET` to execute `magit-show-commit` on a commit
- waiting for the commit to show (about 2 minutes)
- then running `M-x profiler-report`

```
- command-execute                                               23735  95%
 - call-interactively                                           23735  95%
  - funcall-interactively                                       23707  94%
   - magit-show-commit                                          23454  93%
    - magit-mode-setup                                          23428  93%
     - magit-mode-setup-internal                                23428  93%
      - magit-refresh-buffer                                    23399  93%
       - apply                                                  23398  93%
        - magit-revision-refresh-buffer                         23398  93%
         - run-hook-with-args                                   23392  93%
          - magit-insert-revision-notes                         23050  92%
           - magit-git-insert                                   22828  91%
            - apply                                             22668  90%
             - magit-process-file                               22620  90%
              - apply                                           22614  90%
               - process-file                                   22582  90%
                - apply                                         22433  89%
                 + call-process                                   983   3%
                magit-cygwin-env-vars                               2   0%
            + magit-process-git-arguments                         160   0%
           + run-hook-with-args-until-success                     111   0%
           + magit-list-active-notes-refs                           9   0%
             magit-get-section                                      9   0%
             magit-section-ident                                    8   0%
             magit-cancel-section                                   5   0%
          + magit-insert-revision-headers                          45   0%
          + magit-insert-revision-message                           4   0%
          + magit-insert-revision-diff                              4   0%
         + magit-rev-parse                                          3   0%
         + magit-object-type                                        2   0%
           magit-section-show                                       1   0%
      + magit-mode-get-buffer                                      11   0%
      + magit-revision-mode                                        11   0%
      + run-hooks                                                   6   0%
      + magit-display-buffer                                        1   0%
    + magit-toplevel                                               12   0%
    + magit-mode-get-buffer                                        11   0%
    + magit-rev-verify-commit                                       3   0%
   + counsel-M-x                                                  252   1%
   + handle-focus-out                                               1   0%
  + byte-code                                                      28   0%
+ timer-event-handler                                             702   2%
+ ...                                                             507   2%
+ redisplay_internal (C function)                                  18   0%
+ magit-section-update-highlight                                    6   0%
+ winner-save-old-configurations                                    1   0%
```

Based on this I suspected that the issue might have been introduced in 88910e686adcb1d480cded614643b430cc298a9c, so I tried reverting `magit-insert-revision-notes` back to what it was prior to that change, so:

```lisp
(defun magit-insert-revision-notes (rev)
  "Insert commit notes into a revision buffer."
  (magit-insert-section (notes)
    (let ((beg (point)))
      (magit-git-insert "notes" "show" rev)
      (if (= (point) beg)
          (magit-cancel-section)
        (goto-char beg)
        (forward-line)
        (put-text-property beg (point) 'face 'magit-section-secondary-heading)
        (magit-insert-heading)
        (goto-char (point-max))
        (insert ?\n)))))
```

This does appear to fix the issue, so perhaps that changes made in 88910e686adcb1d480cded614643b430cc298a9c are a good place to start looking.

Happy to provide more info if needed.

Thanks a lot,

Kieran

**Comment by tarsius** [comment]
Thanks for the report.

**Comment by trezona-lecomte** [comment]
Thanks for the quick fix 👏 

Fantastic package BTW (I use it daily) keep up the great work.

**Comment by tarsius** [comment]
It had me puzzled for a few minutes until I figured out it was not actually not possible. :stuck_out_tongue_closed_eyes: 

On a somewhat related note

> Expected behaviour: `magit-show-commit` will display a commit within a few seconds.

That still sounds way to long (except for huge diffs). Do you use an Emacs with the `nfork` patch applied? https://magit.vc/manual/magit/MacOS-Performance.html

**Comment by trezona-lecomte** [comment]
I wasn't previously (was using https://emacsformacosx.com/ which I don't think had the patch backported?), but have installed `emacs-plus` now so will give that a go - hopefully I'll see some improvement! Note that I use `magit` at work where our repo is quite large, `magit` is much faster (essentially instant) on all my other repos.
