### ISSUE TITLE
Magit doesn't handle corrupt repositories with "fatal: bad object HEAD"

### ISSUE THREAD

**Issue by hrehfeld** [magit/magit#3276]
Version: Magit 20171029.612, Git 2.15.0, Emacs 25.3.1, gnu/linux

Opening magit for a file in a repository where `git status` reports:

```
fatal: bad object HEAD
```

magit crashes with:

```
magit-insert-head-branch-header: Wrong type argument: stringp, nil
```

I would have expected it to show me this or some other error message.

**Comment by tarsius** [comment]
I think it is okay if Magit doesn't function properly in corrupted repositories.
