### ISSUE TITLE
error on make on commit 94980fed

### ISSUE THREAD

**Issue by ninrod** [magit/magit#3279]
I've just git cloned latest master and it is not building (94980fed)

```sh
magit $ make
make[1]: Entering directory '/home/ninrod/code/sources/magit/lisp'
Compiling magit-git.el

In toplevel form:
magit-git.el:33:1:Error: Cannot open load file: Arquivo ou diretório não encontrado, magit-popup
make[1]: *** [Makefile:60: magit-git.elc] Error 1
make[1]: Leaving directory '/home/ninrod/code/sources/magit/lisp'
make: *** [Makefile:73: lisp] Error 2
magit $
```

note: the latest tag, 2.11.0 is building correctly.

**Comment by tarsius** [comment]
`magit-popup` was moved out of the `magit/magit` repository. You have to clone `magit/magit-popup` separately.

**Comment by ninrod** [comment]
oh, thanks @tarsius, so is it like a submodule? how can I teach make to find magit-popup in another dir?

**Comment by tarsius** [comment]
No it is not like a submodule, it is just another depencency like the other dependencies. But I just noticed that I forgot to update the installation instructions until now. But that is updated now: https://magit.vc/manual/magit/Installing-from-the-Git-Repository.html.
