### ISSUE TITLE
refs are clobbered in the first log line

### ISSUE THREAD

**Issue by ninrod** [magit/magit#3280]
Magit 20171117.514, Git 2.15.0, Emacs 25.3.1, gnu/linux

master should come before or after origin/master, but master clobbers origin/master. see screenshot.

observation: this does not happen on latest tag: 2.11.0

![screenshot](https://user-images.githubusercontent.com/8352747/33156837-aee0591a-cfe4-11e7-9680-10797e0a8601.png)

**Comment by tarsius** [comment]
That's a feature. See the end of https://magit.vc/manual/magit/Log-Buffer.html.

**Comment by ninrod** [comment]
Oh, I see. Is there a way to bring back the old behaviour?

**Comment by tarsius** [comment]
> Is there a way to bring back the old behaviour?

Why did I expect this to be the follow up question :wink: 

No there is not. Please try it for a while. Who knows, maybe you will start liking it.

**Comment by ninrod** [comment]
No sweat @tarsius, I know that you have a difficult job ahead of you in maintaining `magit` and is very difficult to account for the various users preferences. Surely I'll try the new way and I can already start to see the benefits. Thank you very much for mantaining the package.
