### ISSUE TITLE
Show changes on other branch when merging change to deleted file

### ISSUE THREAD

**Issue by greenrd** [magit/magit#3282]
If I am doing a merge and there is a file that was deleted in my branch, but changed in the other branch, magit shows it as:

    unmerged  filename (deleted by us)

However,
1. it appears in staged changes, which is surprising, because it's a conflict. All the other conflicts appear in the unstaged changes section.
2. nothing happens when I press TAB. I would like a way to see what has changed on the other branch since I last merged (or since I created the branch, if I have never merged into this branch before), so that I can see determine whether I need to make any changes to other files that take over the functionality of the deleted file (if any). See https://stackoverflow.com/a/44956845/495796

I tried pressing k and then c, but that resulted in this error from git:

    error: path 'foo/bar' does not have all necessary versions

**Comment by tarsius** [comment]
> it appears in staged changes, which is surprising, because it's a conflict.

Git does that. I am not quite sure why, but assume it makes sense from an implementation perspective.

> nothing happens when I press TAB

`git diff --cached` didn't output anything so Magit cannot display anything.

> I would like a way to see what has changed on the other branch 

Go to "Merging other-branch" and type `RET`. Or to the relevant commit(s) listed in that section.

> I tried pressing k and then c, but that resulted in this error from git:

Press `k t` instead to get a diff that adds the complete file including but not limited to the recent changes.

All in all this is a fairly hairy edge-case and improving upon what Git does from a UX perspective will be very hard and might require going behind Git's back. I don't intend to investigate this more any time soon. But once I tackle the big "diff refactoring" I will look into this and other edge-cases in detail.

**Comment by greenrd** [comment]
> Go to "Merging other-branch" and type RET. Or to the relevant commit(s) listed in that section.

Sorry, I meant that I want to see what has changed specifically just in that file, since the last merge or branch creation. I can do that by selecting the filename, doing M-w, pressing d then = (once or twice) then C-y then RET then r then deleting the default range if any, then typing HEAD...MERGE_HEAD, but that's not very convenient. It is also not very discoverable from a UX perspective.

**Comment by tarsius** [comment]
Yeah, that's a bit cumbersome.

**Comment by tarsius** [comment]
You can now press `RET` or `d d` on a "(deleted by us)" file to show their changes in a diff buffer.

I also experimented with inserting that information directly in the status buffer. That turned out to be a bit hairy though. Still, I might add that at a later time.
