### ISSUE TITLE
Stashing no longer works over TRAMP

### ISSUE THREAD

**Issue by cazzola-andrea** [magit/magit#3283]
Stashing changes over TRAMP now results in a "Cannot read tree ..."  message. 

To reproduce, launch emacs in debug:

`emacs -Q --debug-init --eval '(setq debug-on-error t)' -L ./dash-20171028.854/ -L ./git-commit-20171007.346/ -L ./magit-popup-20171121.1110/ -L ./with-editor-20171006.352/ -L ../site-lisp/magit/lisp/ -l magit`

Trying to stash a staged change on a remote repository via TRAMP results in:

```
Debugger entered--Lisp error: (error "Cannot read tree 8a92b8c5f6ead4b7a42323193b3a70088e132fda")
   signal(error ("Cannot read tree 8a92b8c5f6ead4b7a42323193b3a70088e132fda"))
   error("Cannot read tree %s" "8a92b8c5f6ead4b7a42323193b3a70088e132fda")
   magit-stash-create("On public: 6cc898ba3 Bump session-storage on sharding hosts" t t nil)
   magit-stash-save("On public: 6cc898ba3 Bump session-storage on sharding hosts" t t nil t)
   magit-stash("On public: 6cc898ba3 Bump session-storage on sharding hosts" nil)
   funcall-interactively(magit-stash "On public: 6cc898ba3 Bump session-storage on sharding hosts" nil)
   call-interactively(magit-stash)
   magit-invoke-popup-action(122)
   funcall-interactively(magit-invoke-popup-action 122)
   call-interactively(magit-invoke-popup-action nil nil)
   command-execute(magit-invoke-popup-action)
```
`M-x magit-version` returns:

`Magit 2.11.0-193-g201d46c, Git 2.15.0, Emacs 25.3.1, gnu/linux`

This problem started occurring after https://github.com/magit/magit/issues/3228 was fixed.

**Comment by tarsius** [comment]
> This problem started occurring after #3228 was fixed.

Did you actually bisect and determine that 201d46cf88db562f71041336c6949d45e3a9cb10 is the cause of this?

**Comment by tarsius** [comment]
Please add `(message "-- %S" ,file)` before the `unwind-protect` in `magit-with-temp-file` and post the output.

**Comment by cazzola-andrea** [comment]
Yes, that's the first commit with that issue.

**Comment by tarsius** [comment]
Yeah, there is something wrong with that, investigating...

**Comment by tarsius** [comment]
Thanks for the report and pointing me in the right direction.

**Comment by cazzola-andrea** [comment]
Thanks for working on it and fixing it so fast
