### ISSUE TITLE
Some kind of status indicator for asynchronous activity?

### ISSUE THREAD

**Issue by phil-s** [magit/magit#3284]
Magit 2.11.0-4-g6b7dd53-dirty, Git 2.6.6, Emacs 25.2.1, gnu/linux

Sometimes I'll initiate an action (pushing or rebasing are both examples, I think) and Magit remains responsive, but it's waiting for the git command to finish before it can update the status buffer, and there's no visual feedback to tell me that this is happening unless I open the process log buffer.

If I'm expecting an action to happen faster than it does, it can be slightly confusing when the status buffer is not in the state I'm anticipating. Generally I'll open the process log to check what's happening, but I think it would be a useful improvement if we could tell at a glance that a process is running in the background.

Errors are displayed at the top of the status buffer, and I wonder whether other status notices should be displayed there too?  (There's the possibility that doing so would prove to be too distracting in general; or that it would make a change to an error message not distracting enough??)

**Comment by tarsius** [comment]
> there's no visual feedback to tell me that this is happening

In the echo area it says something like **Running git remote update** and in the mode-line *git remote*. The former goes away if you do something obviously and latter depends on `mode-line-format` containing `mode-line-process` and might be hard to notice. I just had to check whether `mode-line-process` survived my own customizations and it did, but I never notice it regardless. You might want to place it at the very beginning of `mode-line-format`.

**Comment by phil-s** [comment]
I was indeed oblivious to the mode line change.

I'll have a look into propertizing `mode-line-process`

Tweaking `magit-process-set-mode-line` to use the following is certainly effective:

    (setq mode-line-process (propertize str 'face 'hi-yellow))

**Comment by tarsius** [comment]
Are you suggesting that Magit should provide such a face?

Another approach could be to wrap `mode-line-emphasis` to always make it more visible regardless of what package sets it. I am not familiar with the `mode-line` dsl, so I cannot show you how to do that, but worst case is that you need a wrapper form which propertizes the value of `mode-line-emphasis` and returns that.

**Comment by phil-s** [comment]
> Are you suggesting that Magit should provide such a face?

Maybe?

I'm not sufficiently familiar with the other uses of `mode-line-process`. If they are *always* temporary, then a solution which highlighted it globally would probably make good sense; but I rather suspect there are numerous long-term uses in other modes for which strong highlighting would just be annoying.

(I think `shell` and other comint-based modes would be examples? I failed to get it to highlight in a brief test of overwriting `mode-line-modes`, but I'm sure that's just me getting it wrong...)

If this is indeed the case, I think there's a reasonable argument for Magit providing a custom face here.

**Comment by tarsius** [comment]
I don't thing that things like `shell` and `term` set `mode-line-process`. Maybe they do so when you run a command in such a terminal, but I wouldn't expect them to set that variable just because they themselves are running.

**Comment by tarsius** [comment]
Actually `term` seems to do it. I also found an example of a package that propertizes `mode-line-format`.

Could you please implement this? You would also have to update the documentation and add a release note entry.

**Comment by phil-s** [comment]
Sure, you can leave this with me. (I'm not sure how quickly I'll do it, but I'll get to it at some point.)

**Comment by phil-s** [comment]
My initial test looks like this.

	(defface magit-mode-line-process
	  '((t :inherit (mode-line-highlight mode-line-emphasis mode-line)))
	  "Face for temporary/asynchronous `mode-line-process' information."
	  :group 'magit-faces)

	(defun magit-process-set-mode-line (program args)
	  (when (equal program magit-git-executable)
		(setq args (nthcdr (length magit-git-global-arguments) args)))
	  (let ((str (concat " " program (and args (concat " " (car args))))))
		(dolist (buf (magit-mode-get-buffers))
		  (with-current-buffer buf
			(setq mode-line-process
				  (propertize str 'face 'magit-mode-line-process))))))

I wasn't sure about including both `mode-line-highlight` *and* `mode-line-emphasis` in the inherit list, but doing so does have the decided benefit of displaying them both to the user when they customize the face, which makes it easy for them to start from some theme-appropriate defaults.

I don't know how most themes handle this set of mode line faces, but the defaults are non-conflicting when used together (emphasis changes the weight, and highlight changes box, color, and style).

**Comment by tarsius** [comment]
I think you should just inherit `mode-line-emphasis`. Grepping shows that no built-in package combines it with one of the other faces. Emacs performs some special magic in the mode-line: all text will use certain settings from either `mode-line` or `mode-line-inactive` (unless overwritten). Deriving from `mode-line` would defeat some of that.

Also don't inherit from both `mode-line-highlight`. That is used when mouse hovers over text that uses it for `mouse-face`.

**Comment by phil-s** [comment]
Ok, sounds good. I've tweaked the suggested `magit-process-set-mode-line` code a bit more to not include the leading space in the propertized text, because that looked bad if a different background colour was set.

Failing further comments, I expect I'll add docs and make a pull request later in the week.

**Comment by tarsius** [comment]
Sounds good too.

**Comment by phil-s** [comment]
With the mode line process being more visible, I was noticing that it didn't go away immediately in all the windows, so I think we want `(force-mode-line-update t)` at the end of `magit-process-sentinel`:

    (when (memq (process-status process) '(exit signal))
      ...
      (force-mode-line-update t))

Other sentinels might also need this or similar.

**Comment by tarsius** [comment]
Explain it in the commit message :wink:

**Comment by phil-s** [comment]
Sure; I was mostly just wanting to confirm how the various process sentinels are used / would be affected.

A second look suggests to me that *all* the other sentinel functions (including some anonymous functions) actually call `magit-process-sentinel` by convention if the process has exited, and consequently I think I can restrict this addition to just that single function.

**Comment by tarsius** [comment]
I think that's correct.

**Comment by phil-s** [comment]
I've written a release notes entry, but I'm struggling to figure out where this might go in the manual.  I've searched it for documentation on faces, customizing, processes, and the mode line, but didn't turn up a really obvious place to put it.

`(magit) Theming Faces` seems to be primarily for theme authors, and in this instance we are just deferring to `mode-line-emphasis` by default, and it's up to the user to do anything more.

`(magit) Calling Git` is somewhat relevant, but it didn't seem an obvious fit.

`(magit) Viewing Git Output` is the best option I've seen.

I've also had difficulty finding any documentation on adding documentation.  I can see that other commits are updating both `magit.org` and `magit.texi`, but there also seems to be some kind of org-mode texi export configuration in the former, which makes me think that you are authoring solely in `magit.org` and everything else is derived from there. However I don't know how to do that, and `org-export-dispatch` has no `.texi` option, so that's as far as I got.

Can I suggest that details on writing documentation be added to `CONTRIBUTING.md` ?

**Comment by tarsius** [comment]
> I'm struggling to figure out where this might go in the manual.

Not sure this really has to be documented. I would hope that placing this in the correct Custom group would do the trick. Users who do not look in Custom for the appropriate face probably also don't look at the manual instead.

I appreciate it that you want to do this properly but it seems that if you create an appropriate place to document this face, that that place would then also have to document all the other faces. I don't really feel like doing that. Writing documentation already takes a lot of time. But if you want to do it... (Of course even then that would still mean that going forward I would have to document all new faces too.) 

> Can I suggest that details on writing documentation be added to `CONTRIBUTING.md` ?

See what I mean? I even have to document how to write documentation! That's okay - it's just a lot of work. I have promised to write this particular piece of documentation a few times now, but so far I could not work up the motivation to do it yet.

So for now just edit `magit.org` and leave `magit.texi` to me.

**Comment by phil-s** [comment]
> I have promised to write this particular piece of documentation a few times now, but so far I could not work up the motivation to do it yet.

It would certainly be very beneficial for contributors.

> So for now just edit magit.org and leave magit.texi to me.

Perhaps you could say as much as an interim edit to CONTRIBUTING.md ?

Documentation is one of those things that almost anyone can contribute to in principle, so it would be great if there were no obvious barriers to doing so.

**Comment by phil-s** [comment]
Thanks for updating CONTRIBUTING.md and working on https://github.com/magit/magit/wiki/Documentation-tools-and-conventions ! :)
