### ISSUE TITLE
VSCode GitLens features

### ISSUE THREAD

**Issue by anildigital** [magit/magit#3287]
I recently tried VSCode, and some of the features like inline git blame with GitLens package is just awesome.

Here is the repo https://github.com/eamodio/vscode-gitlens

Can we list down favorite features of VSCode GitLens package here and upvote them? Thanks!

**Comment by anildigital** [comment]
In line git blame, i.e. if cursor stops at a line, we should see a git blame as Git Lens at the end of the line. i.e. who committed this line last and date.

**Comment by tarsius** [comment]
I plan to provide several alternative ways to visualize blame information, see #2937.

**Comment by tarsius** [comment]
Thanks for the screenshot/video.

**Comment by anildigital** [comment]
👍🏼
