### ISSUE TITLE
Add committer to commit listing when rebasing

### ISSUE THREAD

**Issue by rswgnu** [magit/magit#3288]
I am using Magit "20171127.435".

A common scenario I think is when you want to squash multiple commits of your own into one via rebase.  If I rebase back to a certain commit and multiple people have committed in the interim, the listing of commits that I can mark to be squashed does show who made each commit so I cannot select just mine.  The regular listing of commits, prior to displaying just those in the rebase, does show the committer.

**Comment by tarsius** [comment]
In one case we run `git log --format=FORMAT ...` where FORMAT requests that the committer information be printed. In the other case we open a file that does not contain that information, so we would have to run `git show -q --format=FORMAT` for every listed commit.

**Comment by rswgnu** [comment]
I see.  Well, I explained the use case and think it is common and important, so however it can be implemented, I would urge you to do so.  The whole idea of magit is to make the UI better than the standard git UI, pretty much, right?

**Comment by tarsius** [comment]
Sure it's possible and I will probably implement it eventually. But eventually might take a while.

Also note that features such as this come at a cost because starting many child processes takes an unreasonably long time on Windows. The plan is to use `libgit2` to avoid that and the feature you are requesting likely won't be implemented until that move has been completed.

**Comment by rswgnu** [comment]
On Wed, Nov 29, 2017 at 6:03 PM, Jonas Bernoulli <notifications@github.com>
wrote:

> In one case we run git log --format=FORMAT ... where FORMAT requests that
> the committer information be printed. In the other case we open a file that
> does not contain that information, so we would have to run git show -q
> --format=FORMAT for every listed commit.
>
​What information is missing from the git log command that would prevent
you from using it for the rebase listing and just extracting and
reformatting the needed commit entries?

**Comment by rswgnu** [comment]
On Wed, Nov 29, 2017 at 6:10 PM, Jonas Bernoulli <notifications@github.com>
wrote:

> Sure it's possible and I will probably implement it eventually. But
> eventually might take a while.
>
> Also note that features such as this come at a cost because starting many
> child processes takes an unreasonably long time on Windows.
>
​Definitely you wouldn't want to do that.​
​​

> The plan is to use libgit2 to avoid that and the feature you are
> requesting likely won't be implemented until that move has been completed.
>
​Ok, but maybe it is worth thinking about a simpler solution first that
would not involve major package changes.

**Comment by tarsius** [comment]
Duplicating Git functionality would be a major package change. Doing that now and then later doing it properly would also mean doing it twice, which takes at least twice as long.

**Comment by rswgnu** [comment]
You guys know best how to implement things and when such implementations
are possible.

What I want to encourage is greater usability regardless of what exists now.

I think during a rebase that being able to see and act upon whom made each
commit is
a regular use case and thus should just be added to a list of use
cases/features to implement.

I think that loading a package like magit and doing a M-x magit RET to get
started is also
a perfectly reasonable feature, certainly better than seeing a list of over
a hundred interactive
commands and having no idea which one to start from.

So please just consider these as usability ideas to implement across time.

**Comment by tarsius** [comment]
> What I want to encourage is greater usability regardless of what exists now.

Of course I want to do that too.

> [my rebase suggestion] and thus should just be added to a list of use cases/features to implement.

I haven't closed that issue, have I? :wink:

> I think that loading a package like magit and doing a M-x magit RET to get
> started is also
> a perfectly reasonable feature, certainly better than seeing a list of over
> a hundred interactive
> commands and having no idea which one to start from.

Learning that you can just use a mnemonic key binding to do most things is one of the most important things to learn about Magit. ... Ah fuck it, here you go

**Comment by npostavs** [comment]
> I think during a rebase that being able to see and act upon whom made each commit is a regular use case and thus should just be added to a list of use cases/features to implement.

IMO, this is a pretty specialized use case, as it implies you are rebasing published commits.

https://git-scm.com/docs/git-rebase#_recovering_from_upstream_rebase:

> Rebasing (or any other form of rewriting) a branch that others have based work on is a bad idea: anyone downstream of it is forced to manually fix their history.

**Comment by rswgnu** [comment]
On Thu, Nov 30, 2017 at 10:44 AM, Noam Postavsky <notifications@github.com>
wrote:

> I think during a rebase that being able to see and act upon whom made each
> commit is a regular use case and thus should just be added to a list of use
> cases/features to implement.
>
> IMO, this is a pretty specialized use case, as it implies you are rebasing
> published commits.
>
> https://git-scm.com/docs/git-rebase#_recovering_from_upstream_rebase:
>
> Rebasing (or any other form of rewriting) a branch that others have based
> work on is a bad idea: anyone downstream of it is forced to manually fix
> their history.
>
> ​Fair enough.  I was doing it at the request of the package author to
simplify integration of my fork.

**Comment by tarsius** [comment]
I don't think I will implement this.

> I haven't closed that issue, have I?

Well, now I do. But I have also added the "revisit if I am running out of ideas" label `.`.

**Comment by rswgnu** [comment]
Thanks for considering this; I know you have a lot to do and just having it on some list is good.
