### ISSUE TITLE
Show, update and scroll revisions in other frames

### ISSUE THREAD

**Issue by basil-conto** [magit/magit#3293]
#### Background

- <kbd>M-x</kbd>`magit-version`<kbd>RET</kbd>:

      Magit 20171202.439, Git 2.15.0, Emacs 27.0.50, gnu/linux

- I use a tiling window manager, to which I recently configured Emacs to delegate its own window management by preferring new frames to new windows.

- A common Magit workflow of mine is as follows (tips for improvement welcome):
  1) <kbd>f</kbd><kbd>u</kbd> (fetch latest commits from upstream)
  2) <kbd>l</kbd><kbd>o</kbd>`..<remote>/<branch>` (log unpulled commits from upstream)
  3) Go to oldest commit.
  4) - Show/scroll each commit with consecutive presses of <kbd>SPC</kbd>
     - Move forward in time and automatically update the revision buffer with <kbd>p</kbd>

#### Status quo

Quoth [`(magit) Section Movement`](https://magit.vc/manual/magit.html#index-magit_002dlog_002dmaybe_002dupdate_002drevision_002dbuffer):

    -- Function: magit-log-maybe-update-revision-buffer

    When moving inside a log buffer, then this function updates the
    revision buffer, provided it is already being displayed in another
    window of the same frame.

and [`(magit) Log Buffer`](https://magit.vc/manual/magit.html#index-magit_002ddiff_002dshow_002dor_002dscroll_002dup):

    ‘SPC’     (‘magit-diff-show-or-scroll-up’)

     Update the commit or diff buffer for the thing at point.

     Either show the commit or stash at point in the appropriate buffer,
     or if that buffer is already being displayed in the current frame
     and contains information about that commit or stash, then instead
     scroll the buffer up.  If there is no commit or stash at point,
     then prompt for a commit.

Both of these descriptions make it clear (a pleasant surprise compared to the documentation of some other packages :) that scrolling and auto-updating the revision buffer from a log buffer on a different frame are not supported, as can be confirmed with:

1. `$ make emacs-Q`
2. <kbd>M-x</kbd>`magit-status`<kbd>RET</kbd>
3. <kbd>C-x</kbd><kbd>1</kbd>
4. <kbd>l</kbd><kbd>l</kbd>
5. Alternate between repetitions of <kbd>SPC</kbd> and <kbd>n</kbd>

#### Feature request

Is there a technical or moral reason for restricting log and revision buffers to the same frame in order for them to intercommunicate? Would it be possible/desirable to either conditionally (i.e. with a new user option) or unconditionally lift this restriction?

For now, I can roughly reenable my workflow across frames with the following patch against 198f964b:

```diff
diff --git a/lisp/magit-diff.el b/lisp/magit-diff.el
index 4c9dce89..3b6ac16c 100644
--- a/lisp/magit-diff.el
+++ b/lisp/magit-diff.el
@@ -1423,7 +1423,7 @@ magit-diff-show-or-scroll
          (setq buf (magit-mode-get-buffer 'magit-stash-mode))))))
     (if rev
         (if (and buf
-                 (setq win (get-buffer-window buf))
+                 (setq win (get-buffer-window buf t))
                  (with-current-buffer buf
                    (and (equal rev (car magit-refresh-args))
                         (equal (magit-rev-parse rev)
diff --git a/lisp/magit-log.el b/lisp/magit-log.el
index 63bcedc4..17a63812 100644
--- a/lisp/magit-log.el
+++ b/lisp/magit-log.el
@@ -1160,7 +1160,7 @@ magit-log-maybe-update-revision-buffer
 (defun magit-log-maybe-update-revision-buffer-1 ()
   (unless magit--update-revision-buffer
     (-when-let* ((commit (magit-section-when 'commit))
-                 (buffer (magit-mode-get-buffer 'magit-revision-mode nil t)))
+                 (buffer (magit-mode-get-buffer 'magit-revision-mode)))
       (setq magit--update-revision-buffer (list commit buffer))
       (run-with-idle-timer
        magit-update-other-window-delay nil
```

as can be tested with

1. `$ make emacs-Q`
2. <kbd>M-x</kbd>`magit-status`<kbd>RET</kbd>
3. <kbd>C-x</kbd><kbd>1</kbd>
4. <kbd>l</kbd><kbd>l</kbd>
5. <kbd>M-:</kbd>`(setq pop-up-frames t)`<kbd>RET</kbd>
6. <kbd>SPC</kbd>
7. Select frame displaying log buffer (ideally step 6 should not select the new frame)
8. Alternate between repetitions of <kbd>SPC</kbd> and <kbd>n</kbd> as before

This works for me for now, but I would be grateful both for adding more robust support and for any suggestions for working with multiple frames.

Thanks!

**Comment by basil-conto** [comment]
I'd just like to clarify one point - in step 6, it's probably the interactions between Emacs and my window system, rather than Magit's doing, causing the new revision buffer frame to be selected, but I haven't investigated that yet.

**Comment by tarsius** [comment]
> I use a tiling window manager, to which I recently configured Emacs to delegate its own window management by preferring new frames to new windows.

Good luck :wink: I use a tiling wm too but I don't use any prefer-frames configuration or packages in Emacs. So Emacs packages still get to split frames if they want (usually just once) and if that results in not all information being visible anymore, then I use <kbd>C-x 7</kbd> to `jkl-replace-current-window-with-frame`.

```lisp
(defun jkl-replace-current-window-with-frame ()
  "Delete window but show buffer in a newly created frame."
  (interactive)
  (let ((window (selected-window)))
    (switch-to-buffer-other-frame (current-buffer))
    (with-no-warnings
      (old-delete-window window))))
```

> Is there a technical or moral reason for restricting log and revision buffers to the same frame in order for them to intercommunicate? Would it be possible/desirable to either conditionally (i.e. with a new user option) or unconditionally lift this restriction?

I can add such an option, but please first experiment with your intended workflow and fix the issues you run into. As far as I know, you might still give up on this approach and I wouldn't want to add an option that nobody uses.

**Comment by basil-conto** [comment]
> Good luck 😉

Who needs luck when there's technological masochism. :) In the meantime I came across your [xmonad-emacs](https://github.com/emacsattic/xmonad) package, but I'll be sticking with as many defaults as possible for now. :)

`jkl-replace-current-window-with-frame` looks pretty handy, thanks for the tip!

> I can add such an option, but please first experiment with your intended workflow and fix the issues you run into. As far as I know, you might still give up on this approach and I wouldn't want to add an option that nobody uses.

Fair enough, and thanks. All I have so far, apart from the aforementioned Magit patch, is

```el
(setq-default frame-auto-hide-function #'delete-frame
              pop-up-frames            'graphic-only)
```
There is little significance to the setter - I just use one massive call to `setq-default` as a pretty convenient and consistent alternative to the Customize interface.

FWIW I'll be sticking with this configuration for the foreseeable longterm future (I've sacrificed way too much time to get here) and I'll report back with any issues I come across (none so far). I'm also happy to stick with my patch if multiple frame support is deemed too niche; I was mostly just curious why this well-documented restriction existed in Magit in the first place.

**Comment by tarsius** [comment]
> FWIW I'll be sticking with this configuration for the foreseeable longterm future (I've sacrificed way too much time to get here) and I'll report back with any issues I come across (none so far). I'm also happy to stick with my patch if multiple frame support is deemed too niche; I was mostly just curious why this well-documented restriction existed in Magit in the first place.

So I am closing this for the time being.
