### ISSUE TITLE
Make aborting + repeating a fixup commit a more streamlined experience

### ISSUE THREAD

**Issue by phil-s** [magit/magit#3294]
Magit 2.11.0-4-g6b7dd53-dirty, Git 2.6.6, Emacs 25.2.1, gnu/linux

I have a regular problem when creating fixup commits, which is that my pre-commit git hook *aborts* the commit, and when I re-do the commit I have to find the fixup target all over again.

This is a rather common occurrence for me because my pre-commit git hook will complain if it thinks there is debug code in the revision of a file being committed, and this can often be a false-positive. For certain files which do intentionally contain debug functionality it will trigger for every commit of that file, which necessitates use of `--no-verify`, but it's easy to forget that this is going to happen.

Such false-positives aren't a problem in Magit for normal commits at HEAD, as `c -h c` is very easy to type; but fixups do become annoying.

I doubt Magit can reasonably know why the commit was aborted, and so I'm not sure there's a sensible way to streamline this in an *automated* fashion, but a manual solution would be good.

My current thought is to provide a UI enhancement when committing to say "pre-select the fixup target that I most recently selected".

This could use a prefix argument `c C-u f`, or else it might be a new commit switch/option/action.

Offhand a switch/option seems like it might be good because the "select a ref" functionality occurs in other situations as well, and this "pre-select the most recently-selected ref" feature might therefore be more generally useful.

**Comment by tarsius** [comment]
If you first move to the fixup target in the status buffer and then invoke `c F`, then point is placed on that commit in the target selection log. So you can just verify with `RET`.

After the first attempt failed point is still on the same commit, so you can then just use `c - h F RET`.

**Comment by phil-s** [comment]
Ah, yes, that workflow definitely helps! Thank you; I shall train myself to do that.

I'll note that the issue would still occur when there was no upstream or push remote configured for the branch (noting that potentially there isn't any remote at all), or if the fixup target otherwise isn't displayed in the status buffer.

It would also be a factor with the status buffer workflow if the user simply had reason to move around in that status buffer (which wouldn't happen with the false-positive failures, but might happen if there was an actual error to be fixed).  One could always manually push a mark on that line in the status buffer in order to pop back to it, but one might also forget to do that.  This case does not seem less of a problem to me, though, as genuine errors are less common.

I can still see value in this idea for the previous scenario of the fixup target not being present in the status buffer.

**Comment by tarsius** [comment]
> I'll note that the issue would still occur when there was no upstream or push remote configured for the branch (noting that potentially there isn't any remote at all), or if the fixup target otherwise isn't displayed in the status buffer.

Update Magit. When there are no unpushed-to-master commits, then n-recent commits are displayed by default now.

> It would also be a factor with the status buffer workflow if the user simply had reason to move around in that status buffer

I'll think about some cache that could be used to jump to some commit in the target selection log, in case there is no commit at point in the status buffer.

**Comment by phil-s** [comment]
> Update Magit. When there are no unpushed-to-master commits, then n-recent commits are displayed by default now.

Excellent!

**Comment by tarsius** [comment]
> I'll think about some cache that could be used to jump to some commit in the target selection log, in case there is no commit at point in the status buffer.

... and came to the conclusion that it would probably confuse more users than it would help. Please use the "select first" workflow for a while and eventually report back if you feel something else is still needed.
