### ISSUE TITLE
Use mode-line-process to indicate process errors

### ISSUE THREAD

**Issue by phil-s** [magit/magit#3297]
Following #3284 I'm considering enhancing this so that in the event of an error the `mode-line-process` value is *not* removed, and instead has an error face applied to it.  As before, this would increase the visibility of the process status.

In `magit-process-finish` I've changed:

       (when (buffer-live-p process-buf)
         (with-current-buffer process-buf
    -      (magit-process-unset-mode-line)
    +      (if (= arg 0)
    +          (magit-process-unset-mode-line)
    +        (magit-process-set-mode-line-error mode-line-process))

With the latter looking like:

    (defun magit-process-set-mode-line-error (str)
      "Apply an error face to the string set by `magit-process-set-mode-line'."
      (setq str (concat " " (propertize
                             (substring-no-properties str 1)
                             'face 'magit-mode-line-process-error)))
      (dolist (buf (magit-mode-get-buffers))
        (with-current-buffer buf
          (setq mode-line-process str)))
      (force-mode-line-update t))

Which seems to do the job, but does leaves the question of how and when this `mode-line-process` would be *removed*?

I could put it on a timer, which would at least ensure that it *does* get removed; but I don't really like that idea, because the user might not see it at all.

I thought about using `magit-insert-error-header` to remove it if there was *no* error, and therefore keep the mode line status in sync with the error notice in the Magit status buffer. I liked that idea, but realised there's no guarantee that a status buffer will exist, so this function isn't necessarily called at all.

I thought about removing it as soon as *any* magit buffer was interactively refreshed, and I think this might be the way to go, but I wasn't sure of the correct way to detect that.

What are your thoughts?

(n.b. as an aside, I've also realised my `(force-mode-line-update t)` call belongs in `magit-process-unset-mode-line` rather than `magit-process-sentinel`, and I'm guessing that this should happen when setting the value as well as unsetting it.)

**Comment by tarsius** [comment]
> I'm considering enhancing this so that in the event of an error the `mode-line-process` value is *not* removed, and instead has an error face applied to it.  As before, this would increase the visibility of the process status.

Make it optional.

> I thought about removing it as soon as *any* magit buffer was interactively refreshed, and I think this might be the way to go,

Agreed.

> but I wasn't sure of the correct way to detect that.

Use `'magit-post-refresh-hook`. But `magit-refresh-buffer` doesn't all that, so there might be some situations where that doesn't kick in.

> I've also realised my `(force-mode-line-update t)` call belongs in `magit-process-unset-mode-line` rather than `magit-process-sentinel`, and I'm guessing that this should happen when setting the value as well as unsetting it.

Do these things using two separate commits.

**Comment by phil-s** [comment]
> Use 'magit-post-refresh-hook. But magit-refresh-buffer doesn't all that, so there might be some situations where that doesn't kick in.

I need to distinguish between an automated refresh and a manually-invoked refresh. Generally the status buffer is automatically refreshed immediately after the process failure, so removing the mode line status upon *any* refresh means it disappears just after it's set.

I don't believe testing `this-command` to see whether it was an "acceptable" refresh command would be a sane option.

I think a viable option would be to set a one-time `post-command-hook` function to set a flag which tells us that it's now safe to remove the mode line status upon the next refresh.

Is there an obvious approach to this that I'm not aware of?

**Comment by tarsius** [comment]
> Generally the status buffer (at least) is automatically refreshed immediately after the process failure, so removing the mode line status upon any refresh means it disappears just after it's set.

The same applies to the display of the error in the status buffer. Since that doesn't happen there, we know there is already something in place that prevents this :smiley:

Grep for `magit-this-error` to see how it is implemented. Though you should be able to just use that variable without having to worry about how it is set and invalidated.

**Comment by phil-s** [comment]
`magit-this-error` is problematic in that it is buffer-local and only set in the status buffer (which might not exist at all), and `magit-insert-error-header` then unsets it, and so any other uses become sequence-dependent.

I was initially thinking that the process buffer was the right place to be storing data for this -- but then the process buffer is also not guaranteed to exist.

After mulling this over, and reviewing code, I arrived at the following conclusions:

Any *particular* buffer we knew about when the git process ran might no longer exist by the time we want to refresh the mode lines, so (a) it's hard to rely upon buffer-local values; and (b) that's not really what we want.

The `mode-line-process` value is set for all buffers returned by `magit-mode-get-buffers`, and that is defined as all existing magit buffers which are associated with the current repository, as established by comparing `magit--default-directory` against `(magit-toplevel)`.

I think that what we want here are "repository-local" values.

With such a facility, it no longer matters if buffers have been added and/or deleted in the interim, as the repository-local value can persist independently of any particular buffer.

An implementation might be an alist keyed by `(magit-toplevel)`, with the value of that being a second alist of name/value pairs.  Functions for settings and getting values would therefore use the magit-toplevel of the current buffer to set/get the values of that sub-alist/hash.

As far as I can see, such a thing does not currently exist?

This would be a bit of a detour for my immediate goal, but I think it makes sense as a solution, and I can only imagine that it turn out to be useful for more situations than the one I am presently looking at.

**Comment by phil-s** [comment]
FYI, I'm experimenting with code based on the repository-local idea.  Let me know if you think this notion is a good idea in general?

If it helps to clarify the intent, my initial pass at the feature is as follows.  I'm not certain of the details or the data types, but this implementation is good enough to work with in other WIP code.

    (defvar magit-repository-local-cache nil
      "Alist mapping `magit-toplevel' paths to alists of key/value pairs.")

    (defun magit-repository-local-key ()
      "Return the key for the current repository."
      (or (bound-and-true-p magit--default-directory)
          (magit-toplevel)
          (signal 'magit-git-error '("Not a git repository"))))

    (defun magit-repository-local-get (key &optional default repository)
      "Return the repository-local value for KEY.

    Return DEFAULT if no value for KEY exists.

    Unless specified, REPOSITORY is the current repository."
      (let* ((repokey (or repository (magit-repository-local-key)))
             (cache (assoc repokey magit-repository-local-cache)))
        (if cache
            (let ((keyvalue (assoc key (cdr cache))))
              (if keyvalue
                  (cdr keyvalue) ;; Repository-local value for this key.
                default)) ;; No such key in repository-local cache.
          default))) ;; No cache for this repository.

    (defun magit-repository-local-set (key value &optional repository)
      "Set the repository-local VALUE for KEY.

    Unless specified, REPOSITORY is the current repository."
      (let* ((repokey (or repository (magit-repository-local-key)))
             (cache (assoc repokey magit-repository-local-cache)))
        (if cache
            (let ((keyvalue (assoc key (cdr cache))))
              (if keyvalue
                  ;; Update pre-existing value for key.
                  (setcdr keyvalue value)
                ;; No such key in repository-local cache.
                (push (cons key value) (cdr cache))))
          ;; No cache for this repository.
          (push (cons repokey (list (cons key value)))
                magit-repository-local-cache))))

**Comment by phil-s** [comment]
FYI I believe I have working code for this issue.  I did end up using a one-time pre-command-hook to deal with refresh sequence concerns.  I'll create a branch for you to look at in the next day or so.

**Comment by tarsius** [comment]
Hey! Sorry for not replying earlier.

> I'll create a branch for you to look at in the next day or so.

Looking forward to that.

**Comment by phil-s** [comment]
This is still pending updates to the release notes and manual, but I'm done for tonight.  I've also refactored a few things while grooming the commits, but have not done much testing in the process, so it's possible I've broken something.  It's probably working, though, so if you wanted to take a look in the interim:

https://github.com/magit/magit/compare/master...phil-s:phil-s/mode-line-process-error?expand=1
