### ISSUE TITLE
Magit pull-request can only check out 30 most recent PRs

### ISSUE THREAD

**Issue by orivej** [magit/magit#3300]
When the repository contains many outstanding PRs, all but the 30 most recent ones can not be selected at the `b r` prompt.

(I am working with https://github.com/NixOS/nixpkgs/ that have 530 open PRs at the moment. I don't need the completion functionality in the PR selection prompt, and would rather just paste the number without waiting for GitHub to respond to the `/pulls` API call.)

**Comment by vermiculus** [comment]
Needs to be unpaginated at `magit-read-pull-request`.

**Comment by orivej** [comment]
It takes GitHub 4 to 5 seconds to return the maximum of 100 PRs per page ([test](https://api.github.com/repos/NixOS/nixpkgs/pulls?per_page=100)). I'd rather not wait 20–30 seconds to select the PR.

**Comment by vermiculus** [comment]
Perhaps [a search](https://developer.github.com/v3/search/#search-issues) could be used here.

I'm just not sure pulling by number only is the best option for most people. We could try to do some heuristics with number of responses that will be returned (looking at last page per `rel="last"` and the number of responses per page) – a method could be selected like that.

**Comment by vermiculus** [comment]
Actually, it wouldn't be crazy for `b C-u r` to open a popup of other pull request selection methods and maybe have a customizable option (or probably rather a git variable) for the default method.

**Comment by orivej** [comment]
By default Magit could keep suggesting 30 PRs, but also accept any numeric input and query an unknown number at `/pulls/%d`. (This opens the path for an option to disable PR suggestions, to speed up PR selection even further.)

**Comment by orivej** [comment]
> This opens the path for an option to disable PR suggestions, to speed up PR selection even further.

That option would not be needed if Magit queried `/pulls` after displaying `Checkout pull request:` prompt: either when we user presses `TAB`, or automatically but asynchronously.

**Comment by tarsius** [comment]
> It takes GitHub 4 to 5 seconds to return the maximum of 100 PRs per page (test). I'd rather not wait 20–30 seconds to select the PR.

That's pretty shocking. But appears to be true.

> By default Magit could keep suggesting 30 PRs, but also accept any numeric input and query an unknown number at `/pulls/%d`.

Could you implement that please?

> (This opens the path for an option to disable PR suggestions, to speed up PR selection even further.)

Yes, but let's not do that yet.

There are at least three ways we could get the data:

1. Get it when needed. That's what Magit currently does, but that's just a first iteration.
2. Get missing data when needed, then cache it. That's what Magithub does. The downside is that cache invalidation is hard.
3. Get all the data using an explicit fetch step. (Like `git fetch`.) That's what I want to do eventually in Magit.

So I don't want to add too many kludges to deal with shortcomings of the first approach. But I did assume that getting the list of pull requests would be an operation that would be fast enough to make this a non-issue.

Sadly I was wrong. But your suggestion sounds like a good fix.

**Comment by vermiculus** [comment]
> cache invalidation is hard

*Very* hard – my recommendation would be to put this off until such a time as it's absolutely necessary and experiment with other approaches that might work.

Can you expand on (3)?

**Comment by tarsius** [comment]
@orivej An interest in implementing this or should I get to it?

**Comment by orivej** [comment]
I'll try today.

**Comment by tarsius** [comment]
No hurry, just wanted to know.

**Comment by vermiculus** [comment]
One alternative to knowing the number is to use magithub in the meantime; pull requests are unpaginated before they're inserted into the buffer and it teaches `thing-at-point` to recognize that it's a `github-pull-request`. As of #3332, `magit-read-pull-request` knows to use the PR at point as the default.

**Comment by vermiculus** [comment]
Another possibility is to use [programmed completion](https://www.gnu.org/software/emacs/manual/html_node/elisp/Programmed-Completion.html#Programmed-Completion) to take the current input and search for matching PRs.
