### ISSUE TITLE
Update revision buffer when navigating in log sections of magit-status buffer

### ISSUE THREAD

**Issue by MatthewFluet** [magit/magit#3301]
Perhaps an instance of #2995.

`magit-version`: `Magit 20171209.415, Git 2.13.6, Emacs 25.3.1, gnu/linux`

Observed behavior:
When there is a revision buffer in the same frame, navigating in a log section within the status buffer (e.g., Recent commits) with `n` and `p` **does not** update the revision buffer.

Expected behavior:
When there is a revision buffer in the same frame, navigating in a log section within the status buffer with `n` and `p` *does update* the revision buffer.  (That is, the same behavior as when navigating in a log buffer with `n` and `p`.)

The critical check seems to be `(derived-mode-p 'magit-log-mode)` in `magit-log-maybe-update-revision-buffer`.  I thought that the check could be changed to something like `(magit-section-when 'logbuf)`, but the various log sections within the status buffer don't seem to have a common section type identifying them as log sections.

**Comment by tarsius** [comment]
There's also `magit-status-maybe-update-revision-buffer`. Add that to `magit-section-movement-hook`.

**Comment by MatthewFluet** [comment]
Thanks for the pointer.

BTW, it seems that there is a documentation error.  https://magit.vc/manual/magit/Section-Movement.html suggests that `magit-status-maybe-update-revision-buffer` (and many others functions) is a member of `magit-section-movement-hook` by default, but they seem not to be.

**Comment by kyleam** [comment]
@MatthewFluet 
> it seems that there is a documentation error

Thanks for catching that.  Fixed with 936fb71c2.
