### ISSUE TITLE
json readtable error while magit-checkout-pull-request

### ISSUE THREAD

**Issue by DamienCassou** [magit/magit#3303]
- *magit version*: Magit 2.11.0-329-g368a89a0, Git 2.14.3, Emacs 26.0.90, gnu/linux
- *emacs version*: GNU Emacs 26.0.90 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.26) of 2017-12-07

1. Clone git@github.com:josteink/csharp-mode.git
2. Within magit, press `b r` to create and checkout a branch from a PR
3. you get `json-read: JSON readtable error`

Expected: a list of PRs to create and checkout a branch from

This is apparently due to a server error (github returns a 500 page) but

- status.github.com reports that everything is ok
- github web pages seem to be fine
- a GET request on https://api.github.com/repos/josteink/csharp-mode/pulls works fine too

Also, it would be nice to get a better error message from magit :-).

```
Debugger entered--Lisp error: (json-readtable-error . 60)
  signal(json-readtable-error 60)
  json-read()
  json-read-from-string("<!DOCTYPE html>\n<html>\n  <head>\n    <meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\">\n    <meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src data:; script-src 'self'; style-src 'unsafe-inline'\">\n    <meta content=\"origin\" name=\"referrer\">\n    <title>Server Error &middot; GitHub</title>\n [...]</html>\n")
  ghub--read-json-response()
  ghub-request("GET" "/repos/josteink/csharp-mode/pulls" nil :query nil :payload nil :headers nil :unpaginate nil :noerror nil :reader nil :username nil :auth magit :host nil)
  ghub-get("/repos/josteink/csharp-mode/pulls" nil :auth magit)
  (let* ((origin (magit-upstream-repository)) (url (magit-get "remote" origin "url")) (prs (ghub-get (format "/repos/%s/pulls" (and (string-match "github.com[:/]\\(.+?\\)\\(?:\\.git\\)?\\'" url) (match-string 1 url))) nil :auth 'magit)) (choice (magit-completing-read prompt (mapcar (function (lambda (it) (format "%s  %s" (cdr (assq 'number it)) (cdr (assq 'title it))))) prs) nil t)) (number (and (string-match "\\([0-9]+\\)" choice) (string-to-number (match-string 1 choice))))) (let (needle) (let ((list prs) (continue t) (it-index 0)) (while (and list continue) (let ((it (car list))) (if (not (not needle)) (setq continue nil) (if (eq (cdr (assq 'number it)) number) (progn (setq needle it))))) (setq it-index (1+ it-index)) (setq list (cdr list)))) needle))
  magit-read-pull-request("Checkout pull request")
  byte-code("\300\301!C\207" [magit-read-pull-request "Checkout pull request"] 2)
  call-interactively(magit-checkout-pull-request)
  magit-invoke-popup-action(114)
  funcall-interactively(magit-invoke-popup-action 114)
  call-interactively(magit-invoke-popup-action nil nil)
  command-execute(magit-invoke-popup-action)
```

**Comment by tarsius** [comment]
This *should* be taken care of now. https://github.com/magit/ghub/issues/37

> status.github.com reports that everything is ok

That page doesn't always tell the thruth. When the failure rate is below some unknown threshold, then it claims that "All systems reporting at **100%**". It's a marketing lie.

> github web pages seem to be fine
> a GET request on https://api.github.com/repos/josteink/csharp-mode/pulls works fine too

It appears that when you were having this issue and were investigating it authenticated requests for that particular resource failed, while un-authenticated ones succeeded.
