### ISSUE TITLE
Remove whitespace at the beginning and end in magit-read-string

### ISSUE THREAD

**Issue by brotzeit** [magit/magit#3305]
I just tried to create a branch with a copied string that contained trailing whitespace. Instead of complaining about the whitespace, it would be nice if magit would trim the string.

I would use `s-trim` from s.el, but I'm not sure if you want it as a dependency.

**Comment by tarsius** [comment]
That's something that should be implemented at the level of the completion framework. Otherwise every package that reads non-whitespace strings from the user would have to implement it.

What framework are you using? If it is not a built-in framework, then changes are good that something like this would be implemented.

> I would use `s-trim` from s.el, but I'm not sure if you want it as a dependency.

I don't. Even if I should end up implementing something I would not use `s`. I guess it is okay to use it if your package makes heavy use of it, but I have seen to many packages that save around two dozen characters or less in total by using `s` instead of built-in functions.

**Comment by brotzeit** [comment]
Why does the completion framework matter in this case ? I thought that it (only ?) matters when `completing-read` is used. `magit-read-string` makes use of `read-from-minibuffer` which does not provide completion ?

**Comment by tarsius** [comment]
Yes you are right. Though it is possible that some third-party completion framework actually is a "read stuff in the minibuffer, with or without completion" framework. But probably not. You might still want to bring that up on `emacs-devel` though. (My preference would be that the disallowed whitespace is detected and stripped at the time some string is yanked into the minibuffer, not when the minibuffer is exited.)

**Comment by brotzeit** [comment]
But the whitespace is disallowed in this case and maybe there are use cases where the whitespace shouldn't be disallowed. I can't think of a situation where I would need the possibility, however I don't think it should be forbidden to paste a string with trailing whitespace into the minibuffer.

**Comment by tarsius** [comment]
True `read-string` doesn't let the caller specify that whitespace isn't allowed. Still would be nice if Emacs provided an argument for that or `read-string-no-whitespace`. But I guess I will have to implement this in Magit until it does, if ever.

**Comment by basil-conto** [comment]
Not exactly what you're looking for, but a close fit is `read-no-blanks-input`. It works with quoted whitespace inserted after `C-q` and whitespace as part of yanks, but the fact that all whitespace terminates input is a bit annoying. Maybe tweaking `minibuffer-local-ns-map` would suffice?

**Comment by brotzeit** [comment]
I can give it a try if you want. I would even try to implement this for emacs, but I don't want to do it in c and I don't like mailing lists. Maybe some day in rust :)

**Comment by tarsius** [comment]
> I can give it a try if you want.

Please go ahead.

> I don't like mailing lists

Guess why I asked you to take it there :angel:
