### ISSUE TITLE
magit-describe-section (or similar) for users

### ISSUE THREAD

**Issue by npostavs** [magit/magit#3308]
The existing `magit-describe-section` gives some info useful for developers, but I think users could benefit from easy access to some information about a given section too. Namely:

- Which hook produced it.
- Which function in the hook produced it.
- What git command produced the output (possibly just displaying the docstring of the function would be enough).

**Comment by tarsius** [comment]
I don't plan to implement. Users aren't really asking for it.

**Comment by npostavs** [comment]
I will probably try to implement this at some point, but I'm too busy right now; I might get to this in a month or two.

> Users aren't really asking for it.

Not in so many words, but I perceive that they are "asking for it" when I see questions like
[Meaning of magit status buffer: Head, Merge, Push](https://emacs.stackexchange.com/questions/26247/meaning-of-magit-status-buffer-head-merge-push) and 
[What's the meaning of rebase in magit status buffer?](https://emacs.stackexchange.com/questions/19162/whats-the-meaning-of-rebase-in-magit-status-buffer). Maybe even [why does magit say I haven't pushed the commit?](https://emacs.stackexchange.com/questions/14543/why-does-magit-say-i-havent-pushed-the-commit).
