### ISSUE TITLE
Error message when git executable not found in exec-path could be improved

### ISSUE THREAD

**Issue by brunson** [magit/magit#3310]
I installed magit for the first time and when I tried to run it I repeatedly got the error message "not inside a git repository".  The root cause was that the git executable was located in a directory that was not on my exec-path, but if the error message had said something to the effect of "could not execute git, check that it is found in the exec-path" it would direct users to the proper resolution directly.

**Comment by tarsius** [comment]
Was the error message `Not inside a Git repository: /some/directory` or just `Not inside a Git repository`?

**Comment by tarsius** [comment]
Well I changed all instances to say the former and, more importantly to complain about not finding `git` when appropriate.

**Comment by brunson** [comment]
Friggin amazing, thank you!
