### ISSUE TITLE
Setting `--no-tags` via magit doesn't work (typo maybe?)

### ISSUE THREAD

**Issue by juanedi** [magit/magit#3311]
When trying to set the a remote's config to never fetch tags, I noticed magit sets `remote.<name>.tagOpts` instead of `remote.<name>.tagOpt` (note the final "s").

I'm using git version 2.15.1 and the expected variable (according to `git help config`) is `tagOpt.` This causes magit to ignore the setting. Only way to make it work seems to be manually changing the `./git/config` file.

I'm not sure if this is just a typo or the variable was renamed.

Magit version: `Magit 20171216.1237, Git 2.15.1, Emacs 25.3.1, darwin`

Thanks!

**Comment by tarsius** [comment]
Thanks for reporting.
