### ISSUE TITLE
Support --recursive option for submodle commands in magit-submodule-popup

### ISSUE THREAD

**Issue by lambdageek** [magit/magit#3313]
Some submodule commands such as `submodule update` and `submodule sync` support a `--recursive` option.  It would be really nice if there was a way to trigger these from `magit-submodule-popup`

**Comment by tarsius** [comment]
You can add that argument yourself. After you have done that (and tested it), please add an entry to https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands (which also contains some relevant links.

**Comment by lambdageek** [comment]
I tried:
```elisp
(magit-define-popup-switch 'magit-submodule-popup ?r "Recursive" "--recursive")
```

But when I hit "o -r u" I see in the magit-process buffer that apparently `git submodule update` ran, without the `--recursive` switch.

Looking at `magit-submodule.el` it doesn't look like any of the commands use `magit-submodule-arguments`.

My `magit-version` info:
```
Magit 20171219.510, Git 2.15.1, Emacs 25.3.1, darwin
```

**Comment by tarsius** [comment]
You're right those commands don't try to use any popup arguments. I plan to give these commands an overhaul soon and will look into this particular problem then too.

**Comment by arichiardi** [comment]
Was planning to open an issue against `magit-submodule-update` - could not select `--remote` and `--merge` together. I then saw this closed issue and now I wonder if I should open another?

**Comment by tarsius** [comment]
Well, I don't think that has anything to do with the above, so: new issue. However I just tried and was able to select these arguments together and don't see how that could possibly not work.

**Comment by tarsius** [comment]
If you can't then open an issue.
