### ISSUE TITLE
Make splitting a commit simpler

### ISSUE THREAD

**Issue by madscientist** [magit/magit#3318]
Something I find myself doing constantly during interactive rebase is splitting a commit into multiple commits.  Doing this is kind of non-intuitive today (with both Git and Magit).  I wonder if Magit could provide a better facility for it.

Today, in Magit I use interactive rebase and then change "pick" to "edit" on the commit I want to split.  When the rebase gets there it will stop.  Then I have to use "x" and type in "HEAD~" (which is the non-intuitive part) to unstage all the changes.  Then I can use Magit's excellent facilities to make new commits based on the diff selection.

It would be nice if there was a more obvious way to do this; maybe instead of "edit" there would be an option like "split" that automatically reset the commit and then stopped.

**Comment by kyleam** [comment]
Presumably this stems from your post [here](https://groups.google.com/d/msg/magit/TVys2azEW4A/oMHaWZzTBgAJ)

**Comment by madscientist** [comment]
Yes, thanks.  I tried to summarize the parts of that email that seemed actionable but maybe there's context in that thread that would be useful.

**Comment by tarsius** [comment]
> Today, in Magit I use interactive rebase and then change "pick" to "edit" on the commit I want to split. When the rebase gets there it will stop. Then I have to use "x" and type in "HEAD~" (which is the non-intuitive part) to unstage all the changes.

Since point was placed on the commit that rebase stopped at you can also use <kbd>p</pkg> to move to "HEAD~", and then you can just use <kbd>x RET</kbd> because the commit at point is offered as the default.

> It would be nice if there was a more obvious way to do this; maybe instead of "edit" there would be an option like "split" that automatically reset the commit and then stopped.

This could be a lot of effort and fragile. Currently we just let `git rebase` do its thing and then look at some files to determine the state. To implement a `split` variant we would probably have to keep track of the invoked command.

I haven't read the linked discussion, so maybe I am just repeating what was already said there. https://github.com/magit/magit/wiki/History-Manipulation documents some elegant ways to split a commit than resetting to "HEAD~" and starting over.

**Comment by kyleam** [comment]
> I haven't read the linked discussion, so maybe I am just repeating what was already said there.

No. Over there I said that I'd find a "split" shortcut useful.  But I
agree with your "effort/fragile" point.

**Comment by tarsius** [comment]
@madscientist An off-topic question for the `make` expert:

This works:

```
[/tmp/test] % tree
.
├── Makefile
└── modules
    ├── A
    ├── B
    └── make

4 directories, 1 file
[/tmp/test] % cat Makefile 
# Make all submodules available
bootstrap:
        @git submodule update --init

# FIXME This should not be define here because users never update this
# file, but doing so is necessary because, except for the above target,
# all targets are still subject to change.
.FORCE:
modules/%: .FORCE
        @echo "do stuff in $@"
[/tmp/test] % make modules/A   
do stuff in modules/A
```

This does not

```
[/tmp/test] % tree
.
├── Makefile
└── modules
    ├── A
    ├── B
    └── make
        └── import.mk

4 directories, 2 files
[/tmp/test] % cat Makefile 
-include modules/make/import.mk

nothing:
        @true

# Make all submodules available, including the one containing all the
# other make targets.
bootstrap:
        @git submodule update --init
[/tmp/test] % cat modules/make/import.mk 
.FORCE:
modules/%: .FORCE
        @echo "do stuff in $@"
[/tmp/test] % make nothing
do stuff in modules/make/import.mk                         # ;-(
[/tmp/test] % make modules/make
do stuff in modules/make/import.mk                         # ;-(
do stuff in modules/make
[/tmp/test] % 
```

It appears as if there is an implicit target `modules/make/import.mk` that somehow always gets called. If I don't force, then that doesn't happen, but then `modules/MODULE` is always up-to-date.

```
[/tmp/test] % cat modules/make/import.mk 
modules/%:
        @echo "do stuff in $@"
[/tmp/test] % make modules/make
make: 'modules/make' is up to date.
```

Is there a way to define the `modules/%` target in a file located inside a subdirectory of `modules`?

**Comment by tarsius** [comment]
If you are wondering why one would need such a weird thing; the real files can be found at

* https://github.com/emacscollective/emacs.g/blob/master/Makefile and
* https://github.com/emacscollective/borg/blob/master/borg.mk

**Comment by tarsius** [comment]
Found a work-around:

```
[/tmp/test] % cat modules/make/import.mk 
modules/%/build:
        @echo "do stuff in $@"
[/tmp/test] % make modules/make/build
do stuff in modules/make/build
```

Still, I would prefer if users could just continue to use `make modules/MODULE`.

**Comment by Silex** [comment]
Maybe try using `include` instead of `-include`, so you have better error messages?

**Comment by madscientist** [comment]
Sorry for the delay.  I don't think I really understand the situation you're trying to create so I don't think I can answer your last question.  However, I can tell you why you are seeing the _do stuff in modules/make/import.mk_ message.

It's because you have included this file, and by default make will always try to rebuild all included files in case they can be brought up to date; see [How Makefiles are Remade](https://www.gnu.org/software/make/manual/html_node/Remaking-Makefiles.html).  Normally you don't notice this because normally there's no rule in a makefile telling make how to remake the makefile itself.  But here you've defined a rule `modules/%: .FORCE` (and made it a FORCE rule!) which matches the included file, so make will use that rule to try to rebuild it.  Since the execution of that rule doesn't end up modifying the target file (`modules/make/import.mk`) make simply shrugs and moves on.  If the file _was_ modified, then make would re-exec itself and start all over.  You can get into an infinite loop here, if you FORCE or make PHONY an included makefile.

If you really want to do this you can create a no-op rule for the included makefile, like this:

    modules/make/import.mk: ;

so it won't try to use the pattern rule for that file.

If you want to discuss further I recommend emailing the bug-make@gnu.org mailing list with a longer explanation of your goals; I find it simpler to manage questions / etc. via email (old-school, I guess...)

Cheers!

**Comment by tarsius** [comment]
Thanks @madscientist that works for me.

Back on topic:

I'll leave this issue open but don't plan to implement any new rebase variants soon. But eventually I will get back to this. I hope the linked documentation helps until then.

**Comment by madscientist** [comment]
Maybe the better path forward is to suggest that Git provide a new operation in interactive rebase that implements this common (IMO) use-case.  Then Magit would support it that way.

**Comment by madscientist** [comment]
> Since point was placed on the commit that rebase stopped at you can also use p to move to "HEAD~", and then you can just use x RET because the commit at point is offered as the default.

Maybe there's something weird about my setup, but I actually need to use "n" to move to HEAD~; that is I need to select the commit below the stopped commit because they are ordered from most recent at the top to oldest at the bottom in the rebase list in the git buffer.

However, this is pretty simple... if I can just manage to remember it with my feeble brain.

I took a quick pass through the docs for other ways to handle this but I confess I didn't follow them all.  I may need to actually try out the commands a few times to understand what's being discussed.

Thanks for the notes!  I'll consider whether this feature is worth asking the Git devs to consider for a basic git rebase operation.

**Comment by tarsius** [comment]
I most likely won't implement a "split" command.

**Comment by tarsius** [comment]
I've restored the page.

**Comment by behrmann** [comment]
Since upstream git has now added the (so far) experimental `git history` command that comes with a `git history split` subcommand, could this be revisited?

**Comment by tarsius** [comment]
I saw a blog post about Git v2.54 just yesterday. `git history` and one other new feature caught my attention. I checked what version my distribution currently provides, its v2.52. I made a mental note to look into this again at a later time.

If you want to make sure I won't forget about it, then please open a "idea" [discussion](https://github.com/magit/magit/discussions). I am currently focused on long standing issues, not new features, and I am focused on projects other than Magit. So I won't jump on this any time soon.
