### ISSUE TITLE
Git operations seem to be happening twice?

### ISSUE THREAD

**Issue by kaushalmodi** [magit/magit#3319]
Hello,

I recently noticed that all the git operations are happening twice via Magit (or at least the messages seem to indicate so).

On doing the origin fetch just once (`fu`), I get:

```
[C-t] show common commands, [?] describe events, [C-h i] show manual
Running git fetch origin [2 times]
Git finished
```

On doing origin push just once (`Pu`), I get:

```
[C-t] show common commands, [?] describe events, [C-h i] show manual
Running git push -v origin master:refs/heads/master [2 times]
Git finished
```

I started debugging this because I believe this is related to Worg (orgmode.org/worg) builds hanging up due to my git pushes. I believe the Worg server receives 2 pushes from me simultaneously and so it hangs up on the first of the two builds based off the 2 pushes.
 
>  (1) what behavior you expected

The *[2 times]* next the all the git operations shouldn't be printed. 

>  (2) what behavior you observed

All git operations seem to be happening twice.

>  (3) and how we can reproduce the issue.

Any git command; examples used above: `fu`, `Pu`.

>  M-x magit-version RET

Magit 20180103.1555, Git 2.15.0, Emacs 26.0.90, gnu/linux

>  $ cd /path/to/magit
>  $ make emacs-Q

I can see each message printing twice in the emacs -Q instance running the git cloned Magit version too (as explained above).

**Comment by kyleam** [comment]
It'd be useful to show what the process buffer shows.  (I'd bet a single call.)

**Comment by kaushalmodi** [comment]
> It'd be useful to show what the process buffer shows. (I'd bet a single call.)

You are correct:

```
  0 git … fetch origin
  0 git … push -v origin master\:refs/heads/master
```

So this was a red herring. But then why is that *[2 times]* printed in the \*Messages\* buffer? That is confusing.

**Comment by npostavs** [comment]
If you set `debug-on-message` do you get two backtraces (hitting `c` after the first one)?

**Comment by kaushalmodi** [comment]
For a remote "dev", I did:

```el
(setq debug-on-message "Running git fetch dev")
```

and I got this backtrace.. just once :( :

```
Debugger entered--Lisp error: "Running git fetch dev"
  #<subr message>("Running %s %s" "git" "fetch dev")
  apply(#<subr message> ("Running %s %s" "git" "fetch dev"))
  message("Running %s %s" "git" "fetch dev")
  magit-run-git-async("fetch" "dev" nil)
  magit-git-fetch("dev" nil)
  magit-fetch-from-pushremote(nil)
  funcall-interactively(magit-fetch-from-pushremote nil)
  call-interactively(magit-fetch-from-pushremote)
  magit-invoke-popup-action(112)
  funcall-interactively(magit-invoke-popup-action 112)
  call-interactively(magit-invoke-popup-action nil nil)
  command-execute(magit-invoke-popup-action)
```

On hitting `c` (**just once**), I got:

```
Running git fetch dev
Entering debugger...
Mark set [2 times]
Continuing. [2 times]
Git finished
```

**Comment by npostavs** [comment]
Hmm, actually I just tried now in my current session, and I see the same behaviour as you (I don't usually bother looking at `*Messages*`, so perhaps it's been this way for a while?).

**Comment by tarsius** [comment]
Thanks for the report!
