### ISSUE TITLE
Having magit installed (via MELPA) but not loaded prevents git-commit from working when invoked externally

### ISSUE THREAD

**Issue by aplaice** [magit/magit#3320]
[This bug is reported against `git-commit` rather than `magit` itself.]

1. (On a fresh emacs profile) install `git-commit` and `magit` via (non-stable) MELPA. Set `git-commit`, but not `magit` itself, to be loaded. (Having `magit` not installed at all or both installed and loaded causes the bug to disappear.)

2. In a terminal, run `git commit` (or other similar command) with `emacs` (or `emacsclient`) set as the editor.

### Expected result:

Emacs is opened to edit the commit message, with `git-commit-mode`.

### Actual result:

The following error is displayed:

`apply: Symbol’s function definition is void: magit-process-file`

and emacs does not open a buffer corresponding to the commit message.

### Possible configuration for reproduction of bug

FWIW this is how I tested the bug (following the outline stated above), though it might not be the best method (using `emacs -Q -L ...` as suggested in the issue template can't really work in this case, but there might be alternatives):

```bash
$ mkdir /path/to/temp/emacs/home/
$ cd /path/to/temp/emacs/home/
$ $EDITOR .emacs
```
Set `.emacs` in the newly created directory to the following:

```elisp
(setq package-archives
      '(("gnu" . "https://elpa.gnu.org/packages/")
	("melpa" . "https://melpa.org/packages/")))

(package-initialize)

(dolist (package '(git-commit magit))
  (unless
      (package-installed-p package)
    (package-refresh-contents)
    (package-install package)))

(require 'git-commit)

;; not strictly necessary, since it's the default
(global-git-commit-mode)
```

Run (in some directory under git):

```bash
$ GIT_EDITOR="HOME=/path/to/temp/emacs/home/ emacs" git commit
```

### Extra information

`magit-version` returns `Magit 20180103.1555, Git 2.7.4, Emacs 26.0.90, gnu/linux`.

`git bisect` suggests that the commit responsible is `2a8f6dcfcf9031cdbae5ad8e1a745f0518d8b8a9`.

Thanks for an amazing set of packages!

**Comment by aplaice** [comment]
The "offending" lines appear to be [these](https://github.com/magit/magit/blob/53eeafcdcb12f9deb74548ffa5b17c397ad7def2/lisp/git-commit.el#L791-L795):

```elisp
              (if (featurep 'magit-git)
                  ;; Font-Lock wants every submatch to succeed.
                  (format "\\(%s\\|\\)\\(%s\\|\\)"
                          (regexp-opt (magit-list-local-branch-names))
                          (regexp-opt (magit-list-remote-branch-names)))
``` 


This is a bit of a stab in the dark (I still don't fully understand the effects of `package-initialize`), but adding:

```elisp
(require 'magit-process nil t)
```

to `git-commit.el` solves the issue. (Neither `magit-git.el` nor `magit-utils.el` `require`s `magit-process`, presumably relying on `magit-core.el` to do it.)

**Comment by tarsius** [comment]
Thanks for the detailed report. I am loading `magit` instead of just `magit-core`, which also loads some stuff that isn't actually needed, but more future proof and most users who have a partially loaded Magit would probably load the rest anyway in most cases.

**Comment by aplaice** [comment]
Thanks for the quick response and fix!
