### ISSUE TITLE
Allow stashing a region

### ISSUE THREAD

**Issue by DamienCassou** [magit/magit#3321]
Very often I fix my code before writing the corresponding non-regression test (bad). When the test is written and passes with the fix, I would like to make sure the test *doesn't* pass if the fix is undone.

To do that, one solution could be to stash the fix and run the test. This is a bit difficult with current stashing popup as it requires to first stage the fix and then stash the index. I would like to be able to stash a region of code instead.

This would only work if the fix can be delimited by a region, but this happens frequently enough for me to create this issue.

Maybe `magit-stash` and `magit-stage` are similar enough to have a similar implementation and feature set?

**Comment by DamienCassou** [comment]
`git-stash` provides a `save --patch` option but I'm not sure magit can use it as this is interactive.

A possible way to implement that would be to:

1. backup and clear the index in case there is one (by stashing it)
2. stage the region
3. stash the index
4. restore what was backed up in step 1 if any

With this implementation, `magit-stash` would benefit from all the features of `magit-stage`, including stashing the file at point which can also be useful.

**Comment by tarsius** [comment]
> This is a bit difficult with current stashing popup as it requires to first stage the fix and then stash the index.

The difference is basically <kbd>z X</kbd> vs. <kbd>s z i</kbd> (where `X` is a yet to be determined binding for a yet to be written `magit-stash-selection`), right? If so, then the difference is minimal and supporting the former is probably not worth the effort.

> A possible way to implement that would be to:

Or just 2 and 3, and to abort if there are already staged changes. Or are 1 and 4 major reasons why you want a stash-region command?

**Comment by DamienCassou** [comment]
> The difference is basically `z X` vs. `s z i`

I agree, but only if you know there is nothing in the index. If there is already something or if you don't know because the magit section is not visible on screen, then it's different. Moreover, `s z i` is a workaround the user has to learn instead of a well-visible feature in the stash popup.

> Or are 1 and 4 major reasons why you want a stash-region command?

yes. And also discoverability.

> A secondary index might also come in handy.

I don't know what that is.

**Comment by tarsius** [comment]
I see. That might be useful indeed then, but I'm afraid I probably won't work on this any time soon.

> A secondary index might also come in handy.

>> I don't know what that is.

One can tell Git to treat some other file as the index instead of `.git/index` using an envvar, which is less heavy weight than stashes.

**Comment by tarsius** [comment]
I probably won't implement such a command.
