### ISSUE TITLE
magit-clone errors with "not inside a git repository"

### ISSUE THREAD

**Issue by jabranham** [magit/magit#3324]
I can reproduce this by cd'ing to magit's repo and running make emacs-Q:

M-x magit-clone prompts for a git repo and location, then produces an error "not inside a git repository '~/code'" and doesn't clone anything

magit-version : Magit 2.11.0-379-g4d089c95, Git 2.15.1, Emacs 25.3.1, gnu/linux

**Comment by tarsius** [comment]
Please update Magit, d8e552d3362599ce3fe713092b01f463fd6707da should fix that.

**Comment by jabranham** [comment]
👍 thanks!
