### ISSUE TITLE
Functions in `magit-process-find-password-functions` do not always get called

### ISSUE THREAD

**Issue by akater** [magit/magit#3328]
Docstring of `magit-process-password-prompt` says:
"Find a password based on prompt STRING and send it to git.
First try the functions in `magit-process-find-password-functions'.
If none of them returns a password, then read it from the user
instead."

Functions in `magit-process-find-password-functions` sometimes do not get called at all.

Example (steps):
1. `(setq magit-process-find-password-functions '(magit-process-password-auth-source))`
2. `M-x debug-on-entry magit-process-password-auth-source`
3. Move to a repository with private remotes with ssh access, ensure ssh-agent is not running.
4. `M-x magit-fetch-all`
(Emacs asks for ssh passphrase, debugger not invoked.)
5. `C-g`
6. `M-x cancel-debug-on-entry magit-process-password-auth-source`
7. `M-x debug-on-entry magit-process-password-prompt`
8. `M-x magit-fetch-all`
(Debugger invoked, `magit-process-password-prompt` is called.)

**Comment by akater** [comment]
Notes:
1. The repository doesn't have to be private.

2. In debugger, I see

* magit-process-password-prompt(#<process git> "Fetching origin\n")

then, after I quickly hit “continue”,
* magit-process-password-prompt(#<process git> "Enter passphrase for key '/home/akater/.ssh/akater-rfMNs7gW-rsa': ")

I expected to use this second call to extract key passphrase by a function from `magit-process-find-password-functions`.

**Comment by tarsius** [comment]
That doc-string is not quite accurate. The function first uses `(magit-process-match-prompt magit-process-password-prompt-regexps string)` to find a prompt. If no prompt is found, then it does not call any of the thanks that might be able to handle the prompt (if any). I guess that has to be clarified.

Why is that behavior a problem for you?

**Comment by akater** [comment]
I use auth-password-store (aka auth-source-pass, since Emacs 26) to access all the passwords and passphrases, or at least as many passwords as possible.

With magit, I have to retrieve passphrases manually.

I'm aware of ssh-agent but prefer to use (and configure) as little software as (reasonably) possible. If magit isn't going to allow manual passphrase lookup as hinted in the docstring, then docstring should probably be clarified a bit, and that's it.

**Comment by tarsius** [comment]
I have updated the doc-string, but I don't think

> magit isn't going to allow manual passphrase lookup

is what happens.

If you do not use one of the mechanisms for caching a secret that is supported by `git` directly, then it should just ask for the password every time that is needed. In which case Magit would see the password prompt and call the functions that retrieve it from somewhere else.

Please perform the same action that needs verification twice and post the `git` output of both invocations.
