### ISSUE TITLE
Possible bug with mouse-autoselect-window and magit-log-current

### ISSUE THREAD

**Issue by rlbdv** [magit/magit#3330]
With

- Magit 2.11.0, Git 2.15.1, Emacs 25.2.2, gnu/linux (Debian elpa-magit 2.11.0-1)
- Emacs 25 (Debian emacs25 and emacs25-lucid 25.2+1-6)
- i3 4.14.1 (Debian 4.14.1-1)

and

    (setq mouse-autoselect-window t)

if I split the Emacs frame via `C-x 3` and then run `M-x magit-status` from the right window, so that the status shows up in the left window, and then hit `l l` in the status window, the pointer jumps to the top-right corner of the status window, and loses focus.  That's of course awkward since subsequent movement commands, etc. will be sent to the wrong window.

Someone else (with a very similar configuration) was able to reproduce the same thing after setting the autoselect variable.

Please let me know if I can help diagnose the problem, and thanks much
for Magit.

**Comment by tarsius** [comment]
Please post a before and an after screenshot.

**Comment by rlbdv** [comment]
Happy to, though apparently putting the images here requires drag and drop, which I don't normally have; it then fails when I launch a filesystem chooser temporarily.  That leads to a github error which has a link that brings up Firefox's own chooser (why don't they have a button for that in the first place?), which also fails -- I'll find somewhere else to put them.

**Comment by rlbdv** [comment]
(I did come across some comments that suggest that maybe github's attachments just don't work with Firefox.)

**Comment by rlbdv** [comment]
Here's right before I hit 'l l':

![before](https://user-images.githubusercontent.com/2295838/34919373-54394d2e-f928-11e7-920c-7f870382be3e.png)

And here's just after:

![magit-after-ll-jump](https://user-images.githubusercontent.com/2295838/34919377-6b25c7ba-f928-11e7-87c8-b95d3e1cc9de.png)

I should note that it's not always reproducible.  I had to try a few times, changing splits and/or window/frame sizes, but once it happens, it seems to happen every time from that arrangement.  I was also able to reproduce it in the horizontal direction (focus jumping left to right) with a slightly different configuration.

In the example, above, what you don't see is that a tooltip (maybe for the modeline/split?) comes up for a while after the jump.  I had to wait for that to go away because it confused imagemagick `import -window ID ...`.  When it happens in the horizontal direction, there's no tooltip.

It at least looks like the pointer is jumping just a fraction too far either vertically or horizontally, and triggering the focus change (and sometimes the tooltip).

Thanks again

**Comment by tarsius** [comment]
And where is the mouse cursor through all of this? Does it move?

**Comment by rlbdv** [comment]
Yes.  Before, it's in the status window (don't know that it matters where), and after it's at the top-right, presumably just a bit "over the line", in the vertical case, just a bit into the mode line.

**Comment by tarsius** [comment]
I can more or less reproduce this. My initial layout is a bit different, but `l l` also causes the mouse to jump somewhere and the respective window to be selected. After setting `mouse-autoselect-window` to `nil` again, the mouse no longer jumps, and that probably means that that feature is to blame. There is nothing in Magit that moves the mouse.

I don't really want to investigate this. Sorry.

**Comment by sten0** [comment]
Here is a related data point: Open two files, split the frame into two windows, change to 2nd window                and change that buffer to the second file, 1) `M-x switch-to-buffer-other-frame`  -> the mouse pointer jumps to the right edge of the new X11 window (new Emacs frame).  But 2) `M-x switch-to-buffer-other-window` does not cause the mouse pointer to teleport.  What window switching function does Magit use?  It seems to me that something like 2) is more likely, which is why it's surprising that mouse pointer teleportation occurs.

**Comment by npostavs** [comment]
> What window switching function does Magit use?

`magit-display-buffer` calls `select-window` and `select-frame-set-input-focus`. The docstring of the latter says: 

> ```
> If `mouse-autoselect-window' is non-nil, also move mouse pointer
> to FRAME’s selected window."
> ```

**Comment by spwhitton** [comment]
I've had this workaround in my init.el for the past few months:

    ;; disable mouse-autoselect-window during display-buffer, to avoid
    ;; surprise focus changes -- code that calls display-buffer does not
    ;; expect mouse-autoselect-window to be on.  E.g. M-x magit-status can
    ;; leave focus in the wrong window without this
    (defun display-buffer--disable-mouse-autoselect-window (orig-fun &rest args)
      (let ((mouse-autoselect-window nil))
        (apply orig-fun args)))
    (advice-add 'display-buffer
                :around #'display-buffer--disable-mouse-autoselect-window)

**Comment by npostavs** [comment]
The patch in #3595 seems to fix it for me, please confirm.

**Comment by mrbig033** [comment]
I'm experiencing the same issue.

### Runtime Environment

- OS: MX Linux 18.3
- GNU Emacs 27.0.50
- Magit 20190817.1623, Git 2.11.0
- [i3wm](https://i3wm.org/) version 4.13
- [i3/config](https://github.com/mrbig033/dotfiles/blob/master/i3/config)
- [dotfiles](https://github.com/mrbig033/dotfiles)
- [~/.emacs.d](https://github.com/mrbig033/emacs)

**Comment by sten0** [comment]
@npostavs I'm on 8c7bd03, which I believe includes #3595, and a quick test appears to indicate that @spwhitton's workaround is no longer required (it worked for me) :-)
