### ISSUE TITLE
Please consider providing the mailing list address

### ISSUE THREAD

**Issue by rlbdv** [magit/magit#3331]
Apologies if I've overlooked it, but the wiki and documentation only appear to list the googlegroup url, and I didn't see the group email address there, either.

Thanks

**Comment by tarsius** [comment]
I have added a note at https://groups.google.com/forum/?fromgroups#!forum/magit.

**Comment by rlbdv** [comment]
When looking around before posting this, I wondered what the difference is between what magit has and what bup has: https://groups.google.com/forum/#!forum/bup-list  There's a slight difference in the url layout, but more importantly, the bup-list does support mail to bup-list at googlegroups.com, and it just sends occasional messages summarizing suspicious posts that could be approved (guessing whatever the spam filters are less certain about).  If ignored, they're discarded in a bit.

**Comment by tarsius** [comment]
Please send a mail to magit@googlegroups.com to see if it gets though.

**Comment by rlbdv** [comment]
OK, I'll try again -- I tried originally, when I was attempting to report the original focus issue, but it bounced.  I wondered if that "forumgroups" difference in the urls above hints that the bup and magit "lists" might just be different kinds of things as far as google's concerned (and if so, maybe magit could be converted, if that wasn't undesirable for some other reason).

**Comment by rlbdv** [comment]
No luck.  If magit is a different kind of group somehow, probably won't help, but for what it's worth I think there may have been bup-list settings for email post handling.  (I can poke around there later if you think it might be useful.)

> We're writing to let you know that the group you tried to contact
> (magit) may not exist, or you may not have permission to post
> messages to the group. A few more details on why you weren't able to
> post:
>
>   * You might have spelled or formatted the group name incorrectly.
>   * The owner of the group may have removed this group.
>   * You may need to join the group before receiving permission to post.
>   * This group may not be open to posting.
> 
> If you have questions related to this or any other Google Group,
> visit the Help Center at https://groups.google.com/support/.
> 
> Thanks,
> 
> Google Groups
