### ISSUE TITLE
Magit log won't verify (--show-signature) valid signed commits

### ISSUE THREAD

**Issue by boltronics** [magit/magit#3333]
**(1) what behavior you expected**

When I press `l` (for log) from `magit-status` and press the `-S` switch for `--show-signature` from the popup and then press `l`, I expect it will be possible to identify signed/verified commits, just as if I were to run `git log --show-signature` from a terminal where it will print

```gpg: Signature made Thu 11 Jan 2018 15:50:07 AEDT
gpg:                using RSA key FF3228220E24B76AF1E887A8E00A5640D5D2A487
gpg:                issuer "abolte@systemsaviour.com"
gpg: Good signature from "Adam Bolte <abolte@systemsaviour.com>" [ultimate]
gpg:                 aka "Adam Bolte <adam.bolte@sitepoint.com>" [ultimate]
Primary key fingerprint: 2626 8B66 72ED 7DD8 5ED8  56F3 F51B 7834 F92D 586B
     Subkey fingerprint: FF32 2822 0E24 B76A F1E8  87A8 E00A 5640 D5D2 A487
```
for my verified commits, for example.

  **(2) what behavior you observed**
Nothing changed. If not using graph mode, I see the hash, commit name, author (always in red), and time elapsed since the last commit. I read somewhere the author commits can turn green if signed, but I have never observed that - they have always been red. However I am new to magit.

  **(3) and how we can reproduce the issue.**
Presumably just sign a commit with a GPG key (trusted or not - doesn't matter) and there will be nothing to establish this in the magit log. You will however get a green "Verified" status next to the commit on GitHub, for example.

Running gpg `2.1.18` here as included with Debian Stretch, with git from `stretch-backports` and `magit` from Melpa:

`Magit 20180112.900, Git 2.14.2, Emacs 25.1.1, gnu/linux`

I've also tested the following with a minimal setup - `dash`, `magit-popup` and `with-editor` installed from Melpa-stable, and `Magit` installed into `~/.emacs.d/site-lisp/magit` from git where I checked out the latest stable tag (2.11.0) and ran `make emacs-Q` as per the instructions. This is on another Debian Stretch host, using Debian's stable git package:

`Magit 2.11.0, Git 2.11.0, Emacs 25.1.1, gnu/linux`

No difference.

**Comment by tarsius** [comment]
> I read somewhere the author commits can turn green if signed, but I have never observed that - they have always been red. However I am new to magit.

The *commit message* is supposed to turn green for good signatures. I have just tested this and it works for me.

**Comment by basil-conto** [comment]
> I read somewhere the author commits can turn green if signed, but I have never observed that - they have always been red.

Even signed commits will show up red if the signing key is not your ring, e.g. when viewing the commits of other people.

**Comment by boltronics** [comment]
Thanks, but I can't even see commits in green that I have signed myself on the same machine. That gpg output in my original post is from the output of `git log --show-signature` on the same machine I'm running Emacs on, so it works fine in the terminal.

You can see I'm using a subkey for signing, although I can't imagine why that would make a difference.

**Comment by boltronics** [comment]
Got it figured out. Turns out my main Emacs installation had various hooks added to `'font-lock-mode-hook` that were preventing highlighting from working correctly with Magit (basically the same as #569) as described over at https://www.emacswiki.org/emacs/ShowWhiteSpace. eg

```
(add-hook 'font-lock-mode-hook 'hc-highlight-tabs)
```

and
```
(add-hook 'font-lock-mode-hook
          (lambda ()
            (font-lock-add-keywords
             nil
             '(("\t" 0 'trailing-whitespace prepend)))))
```

I can get similar functionality by using the following instead, which doesn't have the compatibility issue:
```
;; https://www.emacswiki.org/emacs/WhiteSpace
(require 'whitespace)
(global-whitespace-mode 1)
(setq whitespace-style '(face tabs trailing))
;; Make tabs and trailing whitespace yellow                                                                                                                                                          
(modify-face whitespace-tab nil "#FFFF00")                                                                                                                                                           
(modify-face whitespace-trailing nil "#FFFF00")  
```
etc.

I suppose I missed the issue when testing on a clean environment since I was looking at the author name, instead of looking at the commit message comment colour. Perhaps what `-S` does specifically should be documented - unless I overlooked it.

If the emacswiki.org page is wrong, it's sadly been wrong for quite a few years. Feel free to close this if so.

**Comment by tarsius** [comment]
> Perhaps what `-S` does specifically should be documented - unless I overlooked it.

I have added a note to the manual.
