### ISSUE TITLE
Can't stash untracked directories with --include-untracked

### ISSUE THREAD

**Issue by OskarSigvardsson** [magit/magit#3334]
M-x magit-version:

Magit 20180115.1133, Git 2.14.3 (Apple Git-98), Emacs 25.2.1, darwin

Hey, I'm a very new user of both emacs and magit, so forgive if I've missed something obvious, but: I had a repository where it would only stash some untracked files and not others. The difference seems to be that the ones you can't stash are in a directory. 

That is, magit-status just before stashing (after i've pressed `z` to start stashing, and `-u` to turn on `--include-untracked`, and am about to press `z` again to stash): 

<img width="716" alt="screenshot 2018-01-16 16 58 53" src="https://user-images.githubusercontent.com/7059777/34999040-eaa73de8-fae0-11e7-8bd3-015abbcd4fca.png">

and after stashing: 

<img width="713" alt="screenshot 2018-01-16 16 59 08" src="https://user-images.githubusercontent.com/7059777/34999059-f89251a4-fae0-11e7-9027-3b55ed29959b.png">

Notice that `test/` hasn't been stashed (the directory contains an untracked file, which isn't obvious from this view), but the other file has. Note that `git stash -u` stashes the directory just fine. It also works if you stage the directory, then stash normally. I also tried it with the `magit-emacs-Q-command`, same result. 

I searched the issues, and couldn't find any reports like this, so here it is. 

EDIT: just to be clear, I'm not talking about stashing the literal directory, since git doesn't version directories themselves, I'm talking about when you have a new directory with a file in it, it doesn't stash the file inside of it with `--include-untracked`, even though it should.

**Comment by tarsius** [comment]
> Untracked files in sub-directories are staged too, the only part that fails is removing them from the working tree.

Fixed. Untracked files in subdirectories that do not also contain tracked files are removed too now. Those directories are removed too, but `git stash (push|save)` does that too.

> Hm, actually when there are no tracked but modified changes at all, then it seems to fail completely.

I cannot reproduce that anymore.
