### ISSUE TITLE
Cannot cancel interactive rebase from rebase buffer

### ISSUE THREAD

**Issue by brianhlin** [magit/magit#3341]
I ran the following commands to reproduce:

```
$ cd .emacs.d/elpa/magit-20180120.435/
$ emacs -Q --debug-init --eval '(setq debug-on-error t)' -L ../dash-20180118.743 -L ../git-commit-20180118.507/ -L ../magit-popup-20180119.111/ -L ../with-editor-20180111.433/ -L ../ghub-249/ -L . -l magit
```

1. Expected: The ability to cancel an interactive rebase from the `git-rebase-todo` buffer
1. Observed: I cannot cancel the rebase with `C-c C-k` or `M-x with-editor-cancel`. I also can't kill the buffer with `C-x k` or `kill-buffer`. I was able to abort the rebase from the `*magit: <project>*` buffer with `r a`.
1. Reproduce the issue:
    1. Open a git project in `magit-status`
    1. Start an interactive rebase
    1. Choose a commit to rebase with `C-c C-c`
    1. Try to cancel the rebase from the pop-up buffer

**Comment by tarsius** [comment]
`C-c C-k` allows you to abort in the "modify the list of commits to be rebased" buffer. Once you have pressed `C-c C-c` to actually do it (or `C-c C-k`) there you go back to the status buffer. Did pressing `C-c C-k` in that buffer fail? Or did you later, in the status buffer, try to abort using `C-c C-k`? If it is the latter, then press `r a` instead.

**Comment by brianhlin** [comment]
Yes, pressing `C-c C-k` failed in the buffer containing the commit list, which is called `git-rebase-todo` in my emacs session.

**Comment by tarsius** [comment]
Do you get some error message when you press `C-c C-k`?
Is `C-c C-k` actually bound to `magit-log-select-quit`?
Do you use any package, such as `evil`, that changes many key bindings?

**Comment by brianhlin** [comment]
Ah, sorry I misspoke, pressing `C-c C-k` in the commit selection list works. It's the screen after that where it's broken (the one with the selected commits and you can choose to drop, reword, etc).

`C-h k C-c C-k` yields `(with-editor-cancel)`
`M-x with-editor-cancel` suggests that I run the command with `C-c C-k`

With the way I'm invoking emacs, I don't believe I'm running any packages that would interfere

**Comment by tarsius** [comment]
> Ah, sorry I misspoke

Me too ;-)

Anyway `with-editor-cancel` is the correct binding for `C-c C-k` and you seem to be using this as intended.

I am surprised that that doesn't work for you, I use that every day and many other people too. So to figure out why it does not work for you I will need some error message and/or a detailed description of what happens when you press those keys. Also does `C-c C-c` begin the rebase as intended?

**Comment by brianhlin** [comment]
`C-c C-c` seems to work as intended.
`C-u C-c C-k` also seems to work

There doesn't seem to be any messages of interest in the minibuffer or the `*Messages*` buffer. Nothing appears to happen at all.

**Comment by jguenther** [comment]
I'm also having this problem starting today.

In the `git-rebase-todo` buffer, `C-c C-k` is bound to `with-editor-cancel` for me, but it only works as expected if I add a prefix arg to it for some reason. Didn't dig into it too far but it looks like it's because this is evaluating to `nil`:

```lisp
(run-hook-with-args-until-failure
         'with-editor-cancel-query-functions force)
```

But `with-editor-cancel-query-functions` is `nil`, which it seems should mean that `run-hook-with-args-until-failure` should always return non-nil.

**Comment by tarsius** [comment]
That's not a problem. From `run-hook-with-args-until-failure`'s doc-string.

> Otherwise (if all functions return non-nil, or if there are no functions to call), return non-nil (do not rely on the precise return value in this case).

In other words the rest of the code should run. Could you use debug statements to figure out whether we get to `(server-send-string client "-error Canceled by user")`.

**Comment by tarsius** [comment]
Did you recently switch to another Emacs release?

**Comment by brianhlin** [comment]
My last emacs update was on Jan 2 to `emacs-25.3-3.fc27.x86_64` and have definitely aborted interactive rebases since then.

**Comment by jguenther** [comment]
Ah, the hook has a buffer-local value I didn't notice before, `git-rebase-cancel-confirm`. It looks like the call to `magit-confirm` from that function always returns `nil` without prompting for me

**Comment by tarsius** [comment]
Thanks for the report and pointing me in the right direction. I am glad this regression was caught fairly early on.
