### ISSUE TITLE
Whitespace changes in first line unrecognized in magit-blame

### ISSUE THREAD

**Issue by brianhlin** [magit/magit#3342]
I ran emacs with the following:

```
$ emacs --version
GNU Emacs 25.3.1
Copyright (C) 2017 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
$ cd ~/.emacs.d/elpa/magit-20180120.435/
$ emacs -Q --debug-init --eval '(setq debug-on-error t)' -L ../dash-20180118.743 -L ../git-commit-20180118.507/ -L ../magit-popup-20180119.111/ -L ../with-editor-20180111.433/ -L ../ghub-20180117.1249/ -L . -l magit
```

Expected behavior: A more recent commit in the first line of `magit-blame`
Actual behavior: the newest non-whitespace commit
Steps to reproduce:

1. Set up a dummy git repo:

        mkdir test && cd test
        git init
        echo -e "test\nfile" > file
        git add file
        git commit -am "first commit"
        echo -e " test\nfile" > file
        git commit -am "second commit"

1. Open the file in emacs and run `M-x magit-blame`. The second commit doesn't show up.

**Comment by npostavs** [comment]
I think you just need to customize `magit-blame-arguments` to remove `"-w"`.

**Comment by brianhlin** [comment]
Ah, I wasn't aware of that var. Sorry for the noise.
