### ISSUE TITLE
magit-margin makes remote branches disappear

### ISSUE THREAD

**Issue by agzam** [magit/magit#3343]
# steps to repro:

- open magit-status
- show-refs `y`
- make sure you can see all the remote branches
- enable margin `L L`

# observed behavior:

- remote branches disappear from the screen

![magit-bug](https://user-images.githubusercontent.com/1091022/35297035-a4212184-0032-11e8-9059-45f916dc05f5.gif)

**Comment by tarsius** [comment]
I am a little motion sick now. Please post the buffer content (sans margin) as text formatted "as a diff".

**Comment by tarsius** [comment]
At some point I say a wrong-type argument. Please enable debugging and post the backtrace.

**Comment by agzam** [comment]
so with the debug-on-error toggled on, as soon I try enabling margin in refs buffer:

    Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
      magit-refs-format-margin("BR-145-update-serviced-repayment-cols-2")
      magit-insert-branch-1(#<magit-section magit-section> "origin/BR-145-update-serviced-repayment-cols-2" "%1c %-25n %m\n" nil magit-branch-remote "b4f6d339" "Add status filters to repayment-serviced" nil nil nil 7)
      magit-insert-branch("origin/BR-145-update-serviced-repayment-cols-2" "%4c %-25n %m\n" nil magit-branch-remote "b4f6d339" "Add status filters to repayment-serviced" nil nil nil 7)
      magit-insert-remote-branches()
      run-hooks(magit-refs-sections-hook)
      magit-refs-refresh-buffer(nil nil)
      apply(magit-refs-refresh-buffer (nil nil))
      magit-refresh-buffer()
      magit-set-buffer-margin()
      magit-toggle-margin()
      funcall-interactively(magit-toggle-margin)
      call-interactively(magit-toggle-margin)
      magit-invoke-popup-action(76)
      funcall-interactively(magit-invoke-popup-action 76)
      call-interactively(magit-invoke-popup-action nil nil)
      command-execute(magit-invoke-popup-action)

with no margin, getting into Refs - no problems

**Comment by tarsius** [comment]
Could you please remove all `magit*.elc` so we get an error closer to where the error ultimately occurs?

**Comment by tarsius** [comment]
Never mind, the argument to `magit-refs-format-margin` is supposed to be a commit.

**Comment by tarsius** [comment]
Okay I can reproduce it now.

**Comment by tarsius** [comment]
I am glad you have run into this error - thanks for the report! Otherwise a more subtle bug would probably have stuck around for quite some time.

**Comment by agzam** [comment]
Thank you for fixing it so quickly!

**Comment by kivikakk** [comment]
Just wanted to say thanks to both of you for the report and the fix! Been running into this lately, updated `magit`, now all good <3
