### ISSUE TITLE
magit-save-repository-buffers

### ISSUE THREAD

**Issue by kootenpv** [magit/magit#3344]
It drives me crazy that magit keeps asking for saving, even though I once said "`n`" for a file. It would be great if it would be remembered for some time; maybe until a character has been written. Certainly not the chain of "stage, commit, push". This is my feature request: add one more option that does something clever for `magit-save-repository-buffers`.

The docs now only show 2 different options:

```
magit-save-repository-buffers is a variable defined in ‘magit-mode.el’.
Its value is t

Documentation:
Whether to save file-visiting buffers when appropriate.

If non-nil, then all modified file-visiting buffers belonging
to the current repository may be saved before running Magit
commands and before creating or refreshing Magit buffers.
If ‘dontask’, then this is done without user intervention, for
any other non-nil value the user has to confirm each save.

The default is t to avoid surprises, but ‘dontask’ is the
recommended value.

You can customize this variable.

```

**Comment by tarsius** [comment]
The approach you suggested won't work due to implementation details in Emacs. Instead I have added to new keys which remember the choice until the end of the current session.

**Comment by kootenpv** [comment]
Thanks for giving it your own thought and your knowledge of the possibilities :) 
I believe that "y" will not prompt anymore anyway, so no need to remember? Great to see the feature added so quickly; I guess now I'll have to see how to upgrade magit.
