### ISSUE TITLE
`git stash save` deprecated, need to use `git push`

### ISSUE THREAD

**Issue by tobiasBora** [magit/magit#3349]
Hello,

First, thank you for this great tool. I just wanted to let you know that now `git stash save` is deprecated, and that `git stash push` should be used instead. Would it be possible to implement it ? Or maybe there is a reason you chose not to implement it?

Thank you very much!

**Comment by phil-s** [comment]
#3200 discusses "git stash push"

**Comment by phil-s** [comment]
From my reading, the single difference of note between `stash save` and `stash push` is the ability to include optional `<pathspec>` arguments. You can do this in Magit by using the index: stage the things you wish to stash, and then stash the index.

**Comment by tarsius** [comment]
If we need `-- [pathspec ...]`, then explain why that is so in #3200.

I don't think we need that and the only other difference between these two subsubcommands is that `push` is a much worse name than `save`.
