### ISSUE TITLE
magit-copy-buffer-revision leaves mark active in section body

### ISSUE THREAD

**Issue by basil-conto** [magit/magit#3352]
`Magit 2.11.0-474-gf4bef01a, Git 2.15.1, Emacs 27.0.50, gnu/linux`

Further to https://github.com/magit/magit/issues/1958#issuecomment-361724933:

1. `make emacs-Q`
2. <kbd>C-x</kbd><kbd>g</kbd><kbd>y</kbd>
3. <kbd>C-SPC</kbd><kbd>M-f</kbd><kbd>M-w</kbd>
   - Region saved as kill, mark deactivated.
4. <kbd>C-SPC</kbd><kbd>C-n</kbd><kbd>M-w</kbd>
   - Region saved as kill, mark still active.

In other words, <kbd>M-w</kbd> deactivates the mark as expected in sections heads, but not in their body. The body happens to have a `keymap` property, but I don't see how that would be affecting `magit-copy-buffer-revision`/`copy-region-as-kill`.

**Comment by tarsius** [comment]
This is caused by `magit-section-update-highlight` setting `deactivate-mark` to `nil`. I haven't investigated further yet.

**Comment by basil-conto** [comment]
It's déjà vu all over again. :)

Sorry about the noise, just curious - what does the `fly` label mean?

**Comment by tarsius** [comment]
It's an insect like a `bug`, but makes less noise.

**Comment by tarsius** [comment]
Okay that was only there to work around a bug in Emacs 24. I have now limited it to such ancient versions.

I also found and fixed a second, more severe bug in the process.

And possibly a third, but I am still unsure about that. At best that's effectively dead code at worst a small (under normal circumstances) performance issue.

**Comment by basil-conto** [comment]
Thanks!
