### ISSUE TITLE
Order of sections in main status buffer

### ISSUE THREAD

**Issue by elibarzilay** [magit/magit#3353]
Having a `Recent commits` section is nice, but I would prefer it if it
was below sections like the "Unpushed" and "Unmerged" sections, since
these tend to be more of a "stuff I need to deal with" things.  Is there
a way to customize the order of these sections?

(Pre-apologies if there is already a way to customize this, I looked for
one and didn't find any.)

**Comment by tarsius** [comment]
The `Recent commits` section is actually an incarnation of the `Unpushed to <upstream>` section. The same function `magit-insert-unpushed-to-upstream-or-recent` is responsible for inserting either one of these sections and there is actually some trickery going on that causes these two sections to be treated as the same section. One benefit of that is that when one of the sections disappears and the other appears, that the visibility is preserved.

The main reason that we do all this is that it makes less sense to display `Recent commit` when at least a subset of those are being displayed in `Unpushed to <upstream>`. However if you want to always display `Recent commits`, then that is possible also.

But as long as `magit-insert-unpushed-to-upstream-or-recent` is used `Recent commits` and `Unpushed to <upstream>` appear in the same position.

**Comment by MatthewFluet** [comment]
The `magit-status-sections-hook` variable can be used to customize the sections shown in the status buffer.  For example, I like to see both the `Unpushed to <upstream>` **and** `Recent commits`, so I remove `magit-insert-unpushed-to-upstream-or-recent` from `magit-status-sections-hook` and add `magit-insert-unpushed-to-pushremote`, `magit-insert-unpushed-to-upstream`, and `magit-insert-recent-commits` --- yes, some redundancy, but I usually have few unpushed commits, but I am often interested in the recent commits (beyond what has not yet been pushed).

**Comment by tarsius** [comment]
> yes, some redundancy, but I usually have few unpushed commits, but I am often interested in the recent commits (beyond what has not yet been pushed).

I agree and plan to eventually add an option to allow additional *pushed* commits in `Unpushed to <upstream>`. These could be dimmed or something to indicate that they have already been pushed and are just shown to ensure that `magit-log-section-commit-count` are always shown.

**Comment by elibarzilay** [comment]
@MatthewFluet Oh, looks like exactly the tweak that I'm looking for!

**Comment by tarsius** [comment]
That should work as advertised 😄
