### ISSUE TITLE
magit-repolist-column-dirty should favor staged/unstaged over untracked

### ISSUE THREAD

**Issue by articuluxe** [magit/magit#3354]
`magit-repolist-column-dirty ` describes in its doc-string that since only one letter is used, the attributes need to have a priority.  But top priority is given to untracked files, then unstaged, then staged.  I would suggest this should be reversed.  Staged is the most important, followed by unstaged, followed by untracked.  

As is, I can have an unstaged file, but still the status displays N because I also have untracked files.  If I then stage that file, the status still shows N because untracked files take priority.  It's not uncommon for me to have some untracked files in a repo; but this is not as relevant as having [un-]staged changes, IMO.

Thanks for listening.

**Comment by tarsius** [comment]
But top priority is given to untracked files, then unstaged, then staged. I would suggest this should be reversed. Staged is the most important, followed by unstaged, followed by untracked.

The current order was chosen to highlight the degree of dirtiness. If the dirt is already staged, then you are close to completely cleaning it up by creating a commit. If it is unstaged, then it is more likely that the dirt isn't ready for prime time yet. If there are even previously unknown files, then that's a huge mess.

**Comment by articuluxe** [comment]
I think we have different definitions of dirtiness regarding untracked files.  It is not uncommon for me to have temporary files around (e.g. unit-testing a change) before I push a fix.  This does not imply all such files will eventually be committed.  And this does not imply the git ignore rules should be expanded for all such cases; after all, I want to know about such files so I can clean them up afterward.

Still, I appreciate that you have logic that makes sense to you; perhaps it implies a defect in my workflow.

Thank you.

**Comment by tarsius** [comment]
> Still, I appreciate that you have logic that makes sense to you;

I usually do 😜 

> perhaps it implies a defect in my workflow.

I wouldn't go that far, but maybe you should create a `clean` make target so that you don't have to do the cleanup manually.

To get the precedence that you want I suggest you create a copy of the function and make the necessary adjustments.
