### ISSUE TITLE
<TAB> (magit-section-toggle) does not expand section

### ISSUE THREAD

**Issue by SteveLane** [magit/magit#3357]
When I try to expand a section, for example to expand a directory containing files I want to stage, `magit-section-toggle` does not expand that directory.

Output of `magit-version`: Magit 2.11.0, Git 2.16.1, Emacs 25.3.1, darwin

I started emacs with `emacs -Q -nw` (also tried in windowed mode), loaded magit and then tried to expand directories.

Note that expanding with <TAB> 'Untracked files (n)' (for example) works for me.

**Comment by tarsius** [comment]
I suspect that you can fix this by following the instructions in `magit-insert-untracked-files`:

```
  "Maybe insert a list or tree of untracked files.
Do so depending on the value of `status.showUntrackedFiles'.
Note that even if the value is `all', Magit still initially only
shows directories.  But the directory sections can then be expanded
using \"TAB\"."
```

It's a bit unfortunate how Magit relies on the value of `status.showUntrackedFiles`. That might change eventually.

**Comment by SteveLane** [comment]
Thanks @tarsius that indeed does allow me to TAB on those directory sections. If anyone else stumbles across this (and can't remember how to add to the git config) here's how to do it globally:

```
git config --global status.showUntrackedFiles all
```
