### ISSUE TITLE
Push explicit ref spec has strange "Push refspec,s:" history

### ISSUE THREAD

**Issue by villem** [magit/magit#3361]
Usually magit has nice valid history for prompted values. This one has basically kill-buffer history.
It would be nice if magit would show here previous used ref specs. 
Also it would be really nice if the history would be saved between emacs sessions.

Thanks for magit!

 - Ville

Magit version: Magit 2.11.0-292-g67234c1-dirty, Git 2.9.3, Emacs 25.2.50.2, gnu/linux

**Comment by tarsius** [comment]
> Usually magit has nice valid history for prompted values. This one has basically kill-buffer history.

I have added a dedicated history variable `magit-push-refspecs-history`.

> Also it would be really nice if the history would be saved between emacs sessions.

Use e.g. `desktop-save-mode` for this. You will have to add the relevant variables to `desktop-globals-to-save`. Grepping Magit for "history" should give you a fairly complete list.

**Comment by villem** [comment]
Thanks, everything works great with latest HEAD.
