### ISSUE TITLE
New Feature: support changelist

### ISSUE THREAD

**Issue by BrunoBonacci** [magit/magit#3362]
It would be nice to have the ability to create **changelists** (https://www.jetbrains.com/help/idea/changelist.html).

Oftentimes changes to a project are no all related to a single logical change, it would be nice to be able to split the changes to the current worktree into multiple changes sets and commit the separately.
Changelists are like stashed changes but with the possibility to select a region or hunk and add it to a specific changeset. (maybe related to #3321).
So the idea is that you can create 1 or more changelist (or changeset) and progressively add hunks or regions of changes onto them and when you are ready you can commit a chagelist independently from everything else. Stashing is somewhat similar but with stashing is all or nothing and more importantly stashed changes are not applied to the current index.
Changelist are more like *"staging with a named bucket"*, changes are applied to the current index, and can be commited separately. Please refer to the link above for more information.

Operation required are:
  - create/name a changelist 
  - add one or more changes to it (hunk,region,file,folder)
  - remove one or more changes to it (hunk,region,file,folder) or move to another changelist
  - commit a changelist
  - stash a changelist
  - discard a changelist

**Comment by npostavs** [comment]
This seems pretty close to #2670.

I'm not really convinced the benefits outweigh the complexity.

**Comment by BrunoBonacci** [comment]
#2670 ->> cache git config more aggressively ??
are you sure you put the right ticket?

The ability to have multiple staging buckets it really speeds up the development workflow.

**Comment by kyleam** [comment]
> are you sure you put the right ticket?

I'm pretty sure @npostavs meant #2760 rather than #2670 (flipped the 7 and 6)

**Comment by BrunoBonacci** [comment]
ok #2760 now make sense.

**Comment by tarsius** [comment]
Okay I am closing this in favor of #2760, which ... is also closed. Note however that it has the `.` label. That's my semi-secret way of marking an issue as "rejected but cannot hurt to occasionally reconsider".

That shouldn't keep you from outlining in more depth how that feature is useful, but it would probably be best if you just copied your text from above to #2760 and then did that there.
