### ISSUE TITLE
magit-branch-delete looks broken

### ISSUE THREAD

**Issue by isharov** [magit/magit#3364]
I'm getting the error after recent update:
`user-error: nil is ambiguous.  Please cleanup using git directly.`

Magit 20180204.720, Git 2.16.1, Emacs 25.3.3, darwin

**Comment by tarsius** [comment]
He, I saw that too an our ago but then got distracted. Let me check that out. (Probably a recent regression.)

**Comment by vermiculus** [comment]
I'm also getting this. Something to do with `magit-branch-ambiguous-p` if memory serves.

**Comment by kyleam** [comment]
080723d5 (Use --remove or -non-nil instead of --filter when
appropriate, 2018-02-03) didn't preserve the meaning of the check in
`magit-branch-delete`.

**Comment by tarsius** [comment]
Just pushed the fix.

**Comment by isharov** [comment]
Thanks!
