### ISSUE TITLE
magit-am-apply-patches doesn't work with magit over tramp

### ISSUE THREAD

**Issue by hexmode** [magit/magit#3368]
Using magit to browse /ssh:host:/repo and trying to apply a patch
doesn't work since it assumes that it should just pass the path to
“git am” on the remote machine and the remote machine doesn't
understand a path like /ssh:host:/path/to/patch

Magit 20180207.1417, Git 2.11.0, Emacs 27.0.50, gnu/linux

**Comment by kyleam** [comment]
Thanks for the report.

Wrapping the `read-file-name` call in `magit-am-apply-patches` with
`magit-convert-filename-for-git` should fix the issue.  Grepping
through the code base, it seems like there are a few other
`read-file-name` calls that would have the same issue over tramp.
I'll look more closely at all those spots tonight, assuming @tarsius
doesn't fix the issue before then.

**Comment by tarsius** [comment]
He! Didn't refresh before I went to fix this.

> it seems like there are a few other read-file-name calls that would have the same issue over tramp. I'll look more closely at all those spots tonight,

But I didn't do that. If you feel like doing that please do so.
