### ISSUE TITLE
When magit-get is run inside a directory that doesn't exist, --global should be enforced

### ISSUE THREAD

**Issue by vermiculus** [magit/magit#3369]
From vermiculus/magithub#281, `magit-get` will signal an error if it is run inside a directory that does not exist. I'll be fixing this downstream of course, but it's worth considering if `magit-get` should enforce the `--global` argument and run in a parent directory (or some appropriate other behavior) if `default-directory` does not exist.

**Comment by tarsius** [comment]
I am skeptical. I think calling `magit-get` like that should be considered a bug and working around it instead of signaling an error just hides the issue. Actually I plan to make this and related functions raise an error in *more* situations. See #2744, which I am going to update now.

**Comment by vermiculus** [comment]
Fair enough.
