### ISSUE TITLE
Should magit--cherry-move-read-args sometimes use magit-read-branch-or-commit?

### ISSUE THREAD

**Issue by kyleam** [magit/magit#3373]
`magit--cherry-move-read-args` gets the commit to \<verb> with
`magit-read-other-branch-or-commit` when there isn't an active region.
Using the "other" read branch variant makes sense to me for "harvest",
but shouldn't the tip of the current branch be an option for "donate"?

**Comment by tarsius** [comment]
Absolutely.  (For all the "move away" variants.)
