### ISSUE TITLE
Whitespace-Mode isn’t compatible with Magit

### ISSUE THREAD

**Issue by joncol** [magit/magit#3374]
After the latest update of Magit, when trying to run `magit-status` after enabling `global-whitespace-mode` I get the error message: `user-error: Whitespace-Mode isn’t compatible with Magit.  See `magit-diff-paint-whitespace' for an alternative.`

This has not been a problem before.

Version info: `Magit 20180211.700, Git 2.16.1, Emacs 26.0.90, gnu/linux`

**Comment by tarsius** [comment]
> This has not been a problem before.

Nothing changed on Magit's side, but three people reported this over the last 24 hours. Do you use some starter-kit?

**Comment by tarsius** [comment]
For work-arounds see https://emacs.stackexchange.com/questions/38771/magit-status-does-not-open-when-using-global-whitespace-mode-1/38779

**Comment by joncol** [comment]
No starter kit used by me. I also tried starting using the output of `magit-emacs-Q-command`, then running `global-whitespace-mode` followed by `magit-status`, which caused the same error message to appear.

I'll check out the link you provided, thanks!

**Comment by joncol** [comment]
The first answer in the link provided seems to solve the problem for me. It's weird that this issue just started showing up, though. Anyway, do as you want with this issue, close it or leave it open.

Thanks for the good work on Magit!

**Comment by basil-conto** [comment]
FWIW, I committed the same fix as in the link to my dotfiles repo last week, so whatever caused the sudden change happened on or before 2018-02-02. I also periodically build Emacs from `master`, though, so I can't rule out the change being caused or exposed by something in Emacs proper, but the fact that there are multiple reports for this around the same time reduces the chances of that being the case.
