### ISSUE TITLE
Missing local branches in refs buffer

### ISSUE THREAD

**Issue by basil-conto** [magit/magit#3381]
`Magit 20180216.347, Git 2.15.1, Emacs 26.0.91, gnu/linux`
`GNU Emacs 26.0.91 (build 3, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars) of 2018-02-16`

I've bisected the following behaviour to a3e7c24ff6612462715dd8e5e2ce5aa458f2cbde:

1. `make emacs-Q`
2. <kbd>C-x</kbd><kbd>g</kbd>
3. <kbd>y</kbd>

Expected result (from previous commit acea27520c4c3cbcbca1fd9a743a6ef369a26f5f):

![2018-02-17-010954_1600x900_scrot](https://user-images.githubusercontent.com/9121222/36336411-6f8c7170-137f-11e8-8af3-620f0ee4aba2.png)

Actual result:

![2018-02-17-010116_1600x900_scrot](https://user-images.githubusercontent.com/9121222/36336417-7d83a1b8-137f-11e8-868b-8dbec9e01b20.png)

**Comment by kyleam** [comment]
You don't report an error, so I guess it's probably not this, but just to check: You're not in a detached state, are you?  If so, that should be fixed by 61216785 (magit-refs--format-local-branch: don't propertize msg if it's nil, 2018-02-16).

Aside from that issue, the local branches seem to be listed fine on my end.

**Comment by kyleam** [comment]
Doh, never mind, I see that's even in your screenshot, so it's not the detached issue.

**Comment by tarsius** [comment]
Does a5bffd89a4971883f91d16aeb57f70c643e1b069 aka the `fix-3381` branch do the trick?

**Comment by basil-conto** [comment]
> You don't report an error, so I guess it's probably not this, but just to check: You're not in a detached state, are you? If so, that should be fixed by 6121678 (magit-refs--format-local-branch: don't propertize msg if it's nil, 2018-02-16).

I think I may have run into this error while bisecting (didn't dig into it), but...

>  never mind, I see that's even in your screenshot

yeah, I see this behaviour even on current master of 6121678550b74155404624a5e775315418751588

**Comment by basil-conto** [comment]
> Does a5bffd8 aka the `fix-3381` branch do the trick?

No 😆 

![2018-02-17-012624_1600x900_scrot](https://user-images.githubusercontent.com/9121222/36336652-b2830fdc-1381-11e8-8a8d-7661086653d7.png)

**Comment by tarsius** [comment]
Pushed a new revision. It's late at night so this will have to wait until the morning.

**Comment by basil-conto** [comment]
> Pushed a new revision.

Getting there:

![2018-02-17-013705_1600x900_scrot](https://user-images.githubusercontent.com/9121222/36336814-3b7fd68e-1383-11e8-8d00-852e404025e3.png)

> It's late at night so this will have to wait until the morning.

I was about to hit the sack as well until I saw activity here and became hopeful of the fastest bugfix I've ever seen. Thanks for the lightning support! :)

**Comment by kyleam** [comment]
> I was about to hit the sack as well until I saw activity here 

Wait, try just once more :)

**Comment by basil-conto** [comment]
> Wait, try just once more :)

![2018-02-17-014445_1600x900_scrot](https://user-images.githubusercontent.com/9121222/36336891-4382615c-1384-11e8-947e-b97926a3064d.png)

\o/ I reckon there will be good dreams to be had tonight without needing to sacrifice a goat.

**Comment by basil-conto** [comment]
Clocked at 37 minutes.
