### ISSUE TITLE
Log error in magit-refs

### ISSUE THREAD

**Issue by isharov** [magit/magit#3382]
It occurs on opening/refreshing magit-refs buffer:
`magit-log-propertize-keywords: Wrong type argument: stringp, nil`

Backtrace:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("\\[[^[]*\\]" nil 0)
  magit-log-propertize-keywords(nil)
  magit-insert-tags()
  run-hooks(magit-refs-sections-hook)
  magit-refs-refresh-buffer(nil nil)
  apply(magit-refs-refresh-buffer (nil nil))
  magit-refresh-buffer()
  magit-mode-setup-internal(magit-refs-mode (nil nil))
  magit-mode-setup(magit-refs-mode nil nil)
  magit-show-refs(nil nil)
  magit-show-refs-head(nil)
  funcall-interactively(magit-show-refs-head nil)
  call-interactively(magit-show-refs-head)
  magit-invoke-popup(magit-show-refs-popup nil nil)
  magit-show-refs-popup(nil)
  funcall-interactively(magit-show-refs-popup nil)
  call-interactively(magit-show-refs-popup nil nil)
  command-execute(magit-show-refs-popup)
```
Magit 20180218.1125, Git 2.16.2, Emacs 25.3.3, darwin

**Comment by kyleam** [comment]
I'm guessing that you have tags with an empty message.  (I was able to reproduce your issue if I put a lightweight tag on a commit with an empty message.)  Reopen this issue if you don't have empty messages because that means that the regexp or some assumption about the `git tag` output is wrong.

**Comment by isharov** [comment]
@kyleam, you are right, thanks!
