### ISSUE TITLE
`magit-commit` (& others like `--amend`) sometimes freeze with `commit.gpgsign` enabled

### ISSUE THREAD

**Issue by the-kenny** [magit/magit#3383]
I generally sign all my git commits by setting `commit.gpgsign = true` in my global `.gitconfig`. This works fine with magit (including asking for the passphrase via `gpg-agent`).

This causes strange freezes when I do multiple commits using the same `*magit: ...*` buffer. The first commit after opening the buffer works fine, subsequent commits cause magit to freeze with `Running git commit --gpg-sign ...` in the message buffer. This frequently on the second, definitely on the third commit.

I can cancel the command via `C-g`, but I need to kill all magit-buffers (including `magit-process`) and re-open the magit-buffer before I can commit again.

I can mitigate this issue by disabling `commit.gpgsign = false` in `.gitconfig`, re-enabling this option also causes the issue again.

`Magit 2.11.0, Git 2.16.1, Emacs 25.3.1, gnu/linux`

My config:

<details> 
(setq vc-handled-backends nil)       ;Disable internal vc

(autoload 'magit-status "magit.el")

(setq magit-last-seen-setup-instructions "1.4.0"
      magit-popup-use-prefix-argument nil
      magit-restore-window-configuration nil
      magit-refs-show-commit-count 'branch
      magit-save-repository-buffers nil
      magit-revert-buffers 'silent
      magit-status-buffer-switch-function 'switch-to-buffer)

(eval-after-load 'magit
  '(progn
     (require 'magit-blame)))

(eval-after-load 'git-commit
  '(progn
     (remove-hook 'git-commit-finish-query-functions 'git-commit-check-style-conventions)))
</details>

**Comment by tarsius** [comment]
This rings some bells - faintly.

I think this is due to a bug in Emacs, which was fixed recently. But only on `master`, if I remember correctly.

**Comment by tarsius** [comment]
I'm afraid without more information I won't be able to do anything here. Also it seems this is not an issue shared by many users, otherwise we would surely hear more about it.
