### ISSUE TITLE
support for git pull --rebase --autostash ?

### ISSUE THREAD

**Issue by adl** [magit/magit#3386]
Magit 20180224.1651, Git 2.16.1, Emacs 25.2.2, gnu/linux

Hi,

Right now magit supports `git pull --rebase` but I could not find a way to enable `--autostash` while pulling (except by running `git config rebase.autoStash true` in a terminal, but doing things in magit's back is not satisfactory).
It would be nice if `magit-pull-popup` could support the same `-A --autostash` option as in `magit-rebase-popup`.

**Comment by tarsius** [comment]
Please see https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands.

**Comment by hansbogert** [comment]
Would this not be something that every user would want?

**Comment by TheJJ** [comment]
Just for the record: It's supported since magit v3.0.0 04933c61a7b85f84e890e8f97146f05ea424983d, but only visible on level 7 by default. While in the pull-transient (<kbd>F</kbd>), press <kbd>C-x l</kbd> to activate the availability of `--autostash`.

**Comment by sankalp-khare** [comment]
Thanks for that tip, @TheJJ .

Do you also know where this setting gets persisted? I'm using spacemacs and I set pull --autostash's level to 2. It stays across restarts of Emacs but there's not been any update to my `.spacemacs` file that I can see.
