### ISSUE TITLE
fail to install magit with packcage management

### ISSUE THREAD

**Issue by dproc** [magit/magit#3387]
Hi Experts,
I tried to install magit with package management:
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))
package-install magit, then I got below compile errors:
---------compile message-----------
Leaving directory  /root/.emacs.d/elpa/with-editor-20180217.548 

Compiling file /root/.emacs.d/elpa/with-editor-20180217.548/with-editor.el at Thu Mar  1 00:41:57 2018
Entering directory  /root/.emacs.d/elpa/with-editor-20180217.548/ 

Compiling no file at Thu Mar  1 00:42:00 2018
Leaving directory  /root/.emacs.d/elpa/magit-popup-20180217.910 

Compiling file /root/.emacs.d/elpa/magit-popup-20180217.910/magit-popup.el at Thu Mar  1 00:42:00 2018
Entering directory  /root/.emacs.d/elpa/magit-popup-20180217.910/ 

Compiling no file at Thu Mar  1 00:42:03 2018
Leaving directory  /root/.emacs.d/elpa/let-alist-1.0.5 

Compiling file /root/.emacs.d/elpa/let-alist-1.0.5/let-alist.el at Thu Mar  1 00:42:03 2018
Entering directory  /root/.emacs.d/elpa/let-alist-1.0.5/ 

Compiling no file at Thu Mar  1 00:42:05 2018
Leaving directory  /root/.emacs.d/elpa/git-commit-20180202.321 

Compiling file /root/.emacs.d/elpa/git-commit-20180202.321/git-commit.el at Thu Mar  1 00:42:05 2018
Entering directory  /root/.emacs.d/elpa/git-commit-20180202.321/ 

Compiling no file at Thu Mar  1 00:42:11 2018
Leaving directory  /root/.emacs.d/elpa/ghub-20180221.1319 

Compiling file /root/.emacs.d/elpa/ghub-20180221.1319/ghub.el at Thu Mar  1 00:42:11 2018
Entering directory  /root/.emacs.d/elpa/ghub-20180221.1319/ 

Compiling no file at Thu Mar  1 00:43:20 2018
Leaving directory  /root/.emacs.d/elpa/magit-20180224.1651 

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/git-rebase.el at Thu Mar  1 00:43:20 2018
Entering directory  /root/.emacs.d/elpa/magit-20180224.1651/ 
git-rebase.el:73:1:Error: Symbol s function definition is void: --some

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-apply.el at Thu Mar  1 00:43:20 2018
magit-apply.el:33:1:Error: Symbol s function definition is void: --some

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-autorevert.el at Thu Mar  1 00:43:20 2018

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-bisect.el at Thu Mar  1 00:43:20 2018
magit-bisect.el:30:1:Error: Symbol s function definition is void: --some

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-blame.el at Thu Mar  1 00:43:20 2018
magit-blame.el:31:1:Error: Symbol s function definition is void: --some

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-bookmark.el at Thu Mar  1 00:43:20 2018
magit-bookmark.el:30:1:Error: Symbol s function definition is void: --some

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-branch.el at Thu Mar  1 00:43:20 2018
magit-branch.el:34:1:Error: Symbol s function definition is void: --some

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-collab.el at Thu Mar  1 00:43:20 2018
magit-collab.el:37:1:Error: Symbol s function definition is void: --some

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-commit.el at Thu Mar  1 00:43:20 2018
magit-commit.el:32:1:Error: Symbol s function definition is void: --some

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-core.el at Thu Mar  1 00:43:20 2018
magit-core.el:39:1:Error: Symbol s function definition is void: --some

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-diff.el at Thu Mar  1 00:43:20 2018
magit-diff.el:32:1:Error: Symbol s function definition is void: --some

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-ediff.el at Thu Mar  1 00:43:20 2018
magit-ediff.el:30:1:Error: Symbol s function definition is void: --some

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-extras.el at Thu Mar  1 00:43:20 2018
magit-extras.el:27:1:Error: Symbol s function definition is void: --some

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-files.el at Thu Mar  1 00:43:20 2018
magit-files.el:33:1:Error: Symbol s function definition is void: --some

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-git.el at Thu Mar  1 00:43:20 2018

In magit-get-indirect-upstream-branch:
magit-git.el:1041:74:Warning: reference to free variable  it 

In end of data:
magit-git.el:2011:1:Warning: the function  --any  is not known to be defined.

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-imenu.el at Thu Mar  1 00:43:20 2018
magit-imenu.el:38:1:Error: Symbol s function definition is void: --some

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-log.el at Thu Mar  1 00:43:20 2018
magit-log.el:32:1:Error: Symbol s function definition is void: --some

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-margin.el at Thu Mar  1 00:43:20 2018

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-merge.el at Thu Mar  1 00:43:20 2018
magit-merge.el:30:1:Error: Symbol s function definition is void: --some

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-mode.el at Thu Mar  1 00:43:20 2018

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-notes.el at Thu Mar  1 00:43:21 2018
magit-notes.el:30:1:Error: Symbol s function definition is void: --some

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-obsolete.el at Thu Mar  1 00:43:21 2018
magit-obsolete.el:30:1:Error: Symbol s function definition is void: --some

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-process.el at Thu Mar  1 00:43:21 2018
magit-process.el:112:46:Warning: reference to free variable  it 

In end of data:
magit-process.el:1078:1:Warning: the function  --some  is not known to be
    defined.

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-refs.el at Thu Mar  1 00:43:21 2018
magit-refs.el:30:1:Error: Symbol s value as variable is void: it

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-remote.el at Thu Mar  1 00:43:21 2018
magit-remote.el:32:1:Error: Symbol s value as variable is void: it

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-repos.el at Thu Mar  1 00:43:21 2018
magit-repos.el:32:1:Error: Symbol s value as variable is void: it

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-reset.el at Thu Mar  1 00:43:21 2018
magit-reset.el:30:1:Error: Symbol s value as variable is void: it

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-section.el at Thu Mar  1 00:43:21 2018

In magit-section-match-assoc:
magit-section.el:713:41:Warning: reference to free variable  it 

In end of data:
magit-section.el:1329:1:Warning: the function  --some  is not known to be
    defined.

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-sequence.el at Thu Mar  1 00:43:21 2018
magit-sequence.el:32:1:Error: Symbol s value as variable is void: it

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-stash.el at Thu Mar  1 00:43:21 2018
magit-stash.el:30:1:Error: Symbol s value as variable is void: it

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-status.el at Thu Mar  1 00:43:21 2018
magit-status.el:30:1:Error: Symbol s value as variable is void: it

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-submodule.el at Thu Mar  1 00:43:21 2018
magit-submodule.el:26:1:Error: Symbol s value as variable is void: it

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-subtree.el at Thu Mar  1 00:43:21 2018
magit-subtree.el:26:1:Error: Symbol s value as variable is void: it

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-tag.el at Thu Mar  1 00:43:21 2018
magit-tag.el:30:1:Error: Symbol s value as variable is void: it

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-utils.el at Thu Mar  1 00:43:21 2018

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-wip.el at Thu Mar  1 00:43:21 2018
magit-wip.el:33:1:Error: Symbol s value as variable is void: it

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit-worktree.el at Thu Mar  1 00:43:21 2018
magit-worktree.el:33:1:Error: Symbol s value as variable is void: it

Compiling file /root/.emacs.d/elpa/magit-20180224.1651/magit.el at Thu Mar  1 00:43:21 2018
magit.el:55:1:Error: Symbol s value as variable is void: it
---------compile message end-----------

After that "list-packages" shows that magit is already installed, but when I use any of the magit command magit-version, I got an error: 
“funcall: Symbol s value as variable is void: it”

Emacs version: 25.2

Please help me out, Thanks!

**Comment by kyleam** [comment]
[Note: Since this doesn't seem to be a Magit bug or feature request, this question is more appropriate for one of the other channels rather than the issue tracker.]

All the errors you're getting suggest that you're lacking dash.  I'm not sure why that isn't getting pulled in for you.  Did you try to work from [these instructions][0] instead?

[0]: https://magit.vc/manual/magit/Installing-from-an-Elpa-Archive.html#Installing-from-an-Elpa-Archive

**Comment by phil-s** [comment]
It certainly sounds odd.  A workaround might be:

* `M-x package-refresh-contents RET`
* `M-x package-install RET dash RET`
* `M-x package-install RET magit RET`

**Comment by dproc** [comment]
Hi @phil-s ,
Your workaound works. I can use magit now. Thanks a lot!
