### ISSUE TITLE
magit-remote-prune-refspec fails to find stale branches

### ISSUE THREAD

**Issue by gszasz** [magit/magit#3388]
# magit-remote-prune-refspec fails to find stale remote branches

The `magit-remote-prune-refspec` is not able to find stale remote branches that I want to prune. While I can still use `! ! remote prune origin` from `magit-status` buffer to execute `git remote prune origin` shell command, I would be much much more satisfied with the `M p origin` (since `origin` is the default, it would actually be just `M p <ENTER>`).

## Magit/Emacs Version

Magit 20180224.1651, Git 1.9.4, Emacs 25.3.1, gnu/linux

## How reproducible

always

## Steps to reproduce

1. Create local branch, e.g. `test`.
2. Make a commit to `test` branch.
3. Push the commit to `origin`, setting the upstream branch to `origin test`.
4. Merge the upstream `origin test` branch into the upstream `origin master` branch.
5. Delete the upstream `origin test` branch.
6. Checkout to `master` branch 
5. Run Emacs from the local repo directory. 
6. Run `M-x magit-status`, then press `M p` and confirm the default upstream `origin`. 

## Result

```
No stale refspecs for remote "origin"
```

## Expected result

It should find the `remotes/origin/test` stale branch and ask me if I want to delete it.

## Notes

I executed Emacs without any other packages using following commands.

```
[gszasz@achernar test]$ cd ~/.emacs.d/elpa/magit-20180224.1651
[gszasz@achernar test]$ emacs -Q --debug-init --eval '(setq debug-on-error t)' -L ../dash-20180206.2124/ -L ../git-commit-20180202.321/ -L ../magit-popup-20180217.910/ -L ../with-editor-20180217.548/ -L ../ghub-20180221.1319/ -L . -l magit
```

I also tried following two alternative ways how to invoke `magit-remote-prune-refspec` function, but it ended up with the same result.

* `M-x magit-remote-prune-refspec`, and then confirming the default upstream `origin`
* `M-: (magit-remote-prune-refspec "origin")`. 

When I tried to run `git` shell commands in terminal, everything worked as expected:

```
[gszasz@achernar test]$ git branch -a
* master
  test
  remotes/origin/HEAD -> origin/master
  remotes/origin/test
[gszasz@achernar test]$ git remote prune origin --dry-run
Pruning origin
URL: git@github.com:gszasz/test.git
 * [would prune] origin/test
```

It seems that the bug is in the `magit-remote-prune-refspec` code.

**Comment by tarsius** [comment]
The purpose of `magit-remote-prune-refspecs` is to remove ref**specs** that are no longer valid, e.g. `CrackedP0t.fetch = +refs/heads/patch-1:refs/remotes/CrackedP0t/patch-1`. Such refspecs are created by `magit-branch-pull-request`, but this prune command would also find others.

You can prune *branches* from the fetch popup, e.g. <kbd>f -p a</kbd>.

**Comment by gszasz** [comment]
@tarsius Thank you for your quick comment. <kbd>f -p</kbd>+<kbd>u</kbd>/<kbd>e</kbd> does indeed cover the functionality of `git remote prune REMOTE` and solves the issue for me.

I would like to point out that, according to the [Magit User Manual](https://magit.vc/manual/magit/), the *remote popup* was implemented to be related to the [git-remote](https://git-scm.com/docs/git-remote) shell command (see [7.1.1 The Remote Popup](https://magit.vc/manual/magit/The-Remote-Popup.html)). The User Manual also states that <kbd>M p</kbd> (`magit-remote-prune-refspecs`) function actually *does* remove stale tracking branches for the specified remote.

> *M p* (`magit-remote-prune-refspecs`)
> 
> **Remove stale** refspecs and **tracking branches for REMOTE**. If there are only stale refspecs, then  offer to either delete the remote or replace the refspecs with the default refspec instead.

The *fetch popup* was implemented to be related to the [git-fetch](https://git-scm.com/docs/git-fetch) shell command. This shell command indeed encompasses `git fetch --prune` option for pruning (that, in case of a single remote, does essentially the same thing as `git remote prune origin`). However, the corresponding section in the Magit User Manual does not mention any function or configuration switch that is mapped to this option (see [7.2 Fetching](https://magit.vc/manual/magit/Fetching.html)).

I understand that adding the <kbd>f -p</kbd> switch to the *fetch popup* has probably made the documented behavior redundant, and thus recent version of the `magit-remote-prune-refspecs` function does *not* remove tracking branches anymore. Nevertheless, this should be reflected in the Magit User Manual.
