### ISSUE TITLE
A singular mode-line-process value cannot account for multiple concurrent asynchronous processes

### ISSUE THREAD

**Issue by phil-s** [magit/magit#3390]
(n.b. This can possibly be assigned to me, but I'm unlikely to do anything about it in the near future.  I just wanted to log the issue while I was thinking about it.)

A particular failing of #3314 that I've noticed is that if a slow asynchronous git process fails, it might exit while some subsequent process is running, and the new process may have replaced `mode-line-process` with new text. When that happens, the text of the latter `mode-line-process` is retained when the error face is applied, in which case the mode line *appears* to indicate that the newer process has failed, rather than the older one (although IIRC the tool-tip details will be correct for the actual error).

This could be improved by ensuring that the correct text is remembered and restored when the error state is applied, and this is probably a worthwhile initial change to make.  That could also deal with a related scenario whereby the second process successfully finishes before the first process fails -- in this situation the mode line value is first clobbered and then removed upon success, which leaves nothing to apply the error state to, and so the mode line does not highlight the error at all.

However, I feel that a better solution will be to enhance Magit's `mode-line-process` code to account for multiple concurrent processes, so that the user sees a list of running processes, rather than just the latest one, and any error states are applied to the appropriate item in that list.

(OTOH this sounds like quite a lot of effort for an edge-case, so it's probably not a priority for anyone.)

**Comment by tarsius** [comment]
It would be great if you could implement that I agree that there is no hurry.

**Comment by phil-s** [comment]
A brain dump of my initial thoughts on implementing this...

In order to associate a particular string with a particular process, I'm thinking that the process object itself should be used as an index key.

`(magit-process-setup program args)` generates the `mode-line-process` value, based on its arguments, and returns a `(process-buf . section)` cons.  This all happens *before* the process is started, so I'm thinking of extending that return value to include the new string for `mode-line-process` (which would be a member of a list of such strings, to be combined into a single `mode-line-process` string when displaying the mode line).

`magit-process-setup` is called from three places:

* `magit-call-process`
* `magit-run-git-with-input`
* `magit-start-process`

The first two of those call git synchronously, and the last one asynchronously.

In the asynchronous (`magit-call-process`) case, once the process has been started we can associate that new process object with the string already obtained from `magit-process-setup`, and subsequently `magit-process-finish` can use that connection to manipulate the correct string.

In the synchronous cases I don't believe we can do that the same way, as the process starts and finishes in the same call; however, that being the case, we don't actually *need* the process object, because we *know* that we will be dealing with the most recent entry in our list of `mode-line-process` strings.

So `magit-process-finish` can look for a string associated with the process object, and if no such string is found then it knows it was a synchronous call, and to use the last string pushed onto the list.

**Comment by phil-s** [comment]
Yes it's still on my to-do list; it just hasn't been a priority.  I'm perfectly happy for someone else to pick it up if they're keen, but otherwise I will get around to it at some point.

**Comment by tarsius** [comment]
How's it going? :stuck_out_tongue_winking_eye:

**Comment by phil-s** [comment]
On hold while I'm working on something else (I don't have a lot of time for such things), but progress was made, and I'll probably return to this next.

**Comment by tarsius** [comment]
I think that it would be nice to report that multiple subprocesses are still running, it also do not consider this to be very important.

I am closing this because I am not going to implement it, but if you get around to implementing it, then I would still be interested.

**Comment by phil-s** [comment]
It's still in the queue.  That same "something else" is just unfortunately still not done.  All good -- I'll follow up here once I finally get back to this.
