### ISSUE TITLE
error "Variable binding depth exceeds max-specpdl-size"

### ISSUE THREAD

**Issue by gjm** [magit/magit#3391]
I keep getting this error at (seemingly) random times:
 
    Error in post-command-hook (magit-auto-revert-mode-check-buffers): (error "Variable binding depth exceeds max-specpdl-size")

    M-x magit-version RET

    Magit 20180307.631, Git 2.14.1, Emacs 25.2.2, gnu/linux

What can i do to debug this?

Thanks in advance.

**Comment by npostavs** [comment]
Do you have diff-hl installed? Could be another case of #3014 / dgutov/diff-hl#65.

**Comment by gjm** [comment]
Yes i am.

Will try the workarounds and will post feedback.


Atentamente,

Gonçalo Marrafa

**Comment by tarsius** [comment]
If it turns out that this is the same issue, then that should be discussed there.
