### ISSUE TITLE
Consider setting magit-list-refs-sortby to -creatordate by default.

### ISSUE THREAD

**Issue by eklitzke** [magit/magit#3393]
I came across #2872, and this option is extremely helpful if you have a large number of branches. I'd like to propose making this the default behavior.

**Comment by tarsius** [comment]
> this [setting] is extremely helpful if you have a large number of branches.

It also departs from how Emacs usually sorts completion candidates, so I think we should keep the current default.

**Comment by kyleam** [comment]
@eklitzke Out of curiosity: Did you try and fail to find [this option in the manual][0] before searching the issues?  I'm just wondering if we could tweak the description so that it's easier for interested users to find.

[0]: https://magit.vc/manual/magit/Additional-Completion-Options.html#Additional-Completion-Options

**Comment by eklitzke** [comment]
I found it in a kind of round about way, I was trying to see if there was a hook mechanism to customize the names for new branches. Originally I was envisioning something where magit-branch-and-checkout would give me a prompt with the current date filled in as a suggested prefix. This is what I was used to from my pre-magit life when working with lots of branches, and I still see a lot of branch names on GitHub where people are prefixing the branch with the date (also makes cleaning up old branches pushes to the remote easier). I'm not sure I would have found that manual page as I didn't originally think of it as a sorting thing.

Feel free to close this issue, it was just something I wanted to bring up for consideration.

**Comment by WxNzEMof** [comment]
This option is really useful! I discovered it today after many years of using Magit and wish I'd discovered it sooner. What else am I missing?

I think it would be cool to have a page with "a list of options you may want to set, but we can't change the default of because of reasons".
