### ISSUE TITLE
Magit conflicts with rainbow mode. No color shown.

### ISSUE THREAD

**Issue by junhaowww** [magit/magit#3394]
If I set rainbow mode to a global condition, no color except gray and white is applied to the magit mode. I found it strange and took for a while to locate the issue. Thanks a lot!

macOS 10.13.2
Emacs 25.3 

Here is my config.
``` elisp
(require 'rainbow-mode)
;; conflict with magit
(define-globalized-minor-mode my-global-rainbow-mode rainbow-mode
(lambda () (rainbow-mode 1)))
(my-global-rainbow-mode 1)
```

[rainbow-mode.el](https://github.com/emacsmirror/rainbow-mode)

**Comment by tarsius** [comment]
The problem is probably the same as for `whitespace-mode`.

> Because `whitespace-mode' uses font-lock and Magit does not, they are not compatible.  Therefore you cannot turn on that minor-mode in Magit buffers.  If you try to enable it anyway, then this advice prevents that.

**Comment by tarsius** [comment]
These other modes are to blame - they assume that every buffer uses Font-Lock mode and that it is therefore safe for them to enable themselves everywhere.

**Comment by junhaowww** [comment]
I see. Thank you!
