### ISSUE TITLE
Remind me when my log output is being filtered

### ISSUE THREAD

**Issue by offby1** [magit/magit#3395]
Here's a problem that I hope you can solve:
I use magit to look at a subset of the log messages of my current branch -- let's say just those whose author is me.  So I type
```
 l [magit-log-popup]
 = a [magit-invoke-popup-option]
 e [self-insert-command]
 r [self-insert-command]
 i [self-insert-command]
 c [self-insert-command]
 h [self-insert-command]
 a [self-insert-command]
 n [self-insert-command]
 RET [exit-minibuffer]
 l [magit-invoke-popup-action]
```

That works fine.  However, I now go to lunch, and work on something else ... then later I look at my `*magit-log: WotEva*` buffer and wonder why there are so few entries in it (because I've completely forgotten that I typed <kbd>=g</kbd> when I generated it.

Of course if I hit <kbd>l</kbd> again, and carefully examine the options, I'll eventually notice that "Limit to author" is active.  But I wish the `*magit-log:` buffer itself warned me about that, perhaps in the title bar.

**Comment by tarsius** [comment]
I've just added a new option `magit-log-header-line-function` for this. The default, `magit-log-header-line-sentence` should probably include some more arguments, but it is not easy to know where to stop. Over time I will probably add more.

**Comment by kyleam** [comment]
Mostly orthogonal to the solution you have in mind, but it's probably worth mentioning that the problem you describe was the motivation for the `magit-use-sticky-arguments` option.
