### ISSUE TITLE
Using helpful-callable instead of describe-function

### ISSUE THREAD

**Issue by nickdrozd** [magit/magit#3396]
Today while in a Magit status buffer, I hit <kbd>b</kbd> to bring up
the branch popup. I noticed for the first time that there is a command
to create a branch from a pull request, which is something I've wanted
to do for a while. To see how it works, I hit <kbd>C-h k Y</kbd>,
which brought up the usual `*Help*` buffer.

This was an unpleasant surprise to me, as I have replaced the builtin
help functions (`describe-key`, etc) with their counterparts from
[`helpful`](https://github.com/Wilfred/helpful). Normally when I hit
<kbd> C-h k</kbd>, I expect it to call `helpful-key`. `helpful-key` is
like `describe-key` except with a bunch of cool extra stuff, like
source code and manual links. (I highly recommend it.)

Anyway, after poking around a little, I discovered that Magit has its
own key-description system, and that this system ultimately boils down
to a call to `describe-function`:

```
(defun magit-popup-describe-function (function)
  (let ((winconf (current-window-configuration)))
    (delete-other-windows)
    (split-window-below)
    (other-window 1)
    (with-no-warnings ; display-buffer-function is obsolete
      (let ((display-buffer-alist '(("" display-buffer-use-some-window)))
            (display-buffer-function nil)
            (display-buffer-overriding-action nil)
            (help-window-select nil))
        (describe-function function)))
    (fit-window-to-buffer)
    (other-window 1)
    (setq magit-popup-previous-winconf winconf)
    (magit-popup-help-mode)))
```

My request, if it isn't too onerous, is for there to be some way of
getting `magit-popup-describe-function` to use [`helpful-callable`](https://github.com/Wilfred/helpful/blob/d04a7bc38439e97f5c6a9f8bdcb98ef52a6060b8/helpful.el#L1665)
instead of `describe-function`:

```
(defun magit-popup-describe-function (function)
  (let ((winconf (current-window-configuration)))
    (delete-other-windows)
    (split-window-below)
    (other-window 1)
    (with-no-warnings ; display-buffer-function is obsolete
      (let ((display-buffer-alist '(("" display-buffer-use-some-window)))
            (display-buffer-function nil)
            (display-buffer-overriding-action nil)
            (help-window-select nil))
        (helpful-callable function)))  ;; <-- I want that
    (fit-window-to-buffer)
    (other-window 1)
    (setq magit-popup-previous-winconf winconf)
    (magit-popup-help-mode)))
```

I don't know how that should be done exactly. Some kind of
customization variable maybe? I'm sure you can think of something
suitable. (Maybe @Wilfred has some thoughts?)

While I'm here, I'd like to take the opportunity to thank you for
doing such great work on Magit. I had to use command-line Git the
other day and it felt breathing through a straw. I don't know how
people do it.

**Comment by tarsius** [comment]
> `helpful-key` is like `describe-key` except with a bunch of cool extra stuff, like source code and manual links. (I highly recommend it.)

I've already installed it but haven't gotten around to trying it out yet. :wink: 

> Anyway, after poking around a little, I discovered that Magit has its
own key-description system,

It's worse than that. It has it's own command dispatch mechanism, which is what makes it necessary to have `magit-popup-describe-function` in the first place. I would rather (and am going to) fix the former than to make the kludge customizable.

Would you mind dealing with this by either using a local patch or advising `magit-popup-describe-function` (using an around advice and `cl-letf`).

**Comment by nickdrozd** [comment]
Cool, it sounds like this issue will take care of itself in time, so I will close it.
