### ISSUE TITLE
Staging *new* archive files causes tramp error on emacs master (27.x)

### ISSUE THREAD

**Issue by kaushalmodi** [magit/magit#3397]
>  (1) what behavior you expected

Staging new .tar.xz, .zip, etc files should work. By "new", I mean staging/adding a new file to git that didn't exist before.

>  (2) what behavior you observed

Give tramp-error; see https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30858#5 for details.

>  (3) and how we can reproduce the issue.

1. Build emacs from master branch using a commit from 2018/03/19 (example: http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=7a7ee53dbdcf489050653f04ba3d0c491245c5fa ).
2. Create a new .tar.xz file in a git repo.
3. Stage it by hitting `s` in Magit Status buffer.
4. You'll get the *tramp-error* I reported in that debbugs.

>  M-x magit-version RET

Magit 20180313.1552, Git 2.17.0.rc0, Emacs 27.0.50, gnu/linux

---

@npostavs further suggests a solution in that debbugs thread: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30858#14 .. need to somehow resolve a conflict between Magit staging archive files and a change in behavior of tramp on emacs master. 

---

**Current workaround**

- Stage such archive files manually from the terminal using `git stage foo.tar.xz`.
- Back in Magit, commit it.
- Now that that archive file has been committed for the first time, future staging/committing works just fine.

**Comment by tarsius** [comment]
I have just followed @npostavs suggestion. Seems cleaner anyway - even once the issue on Tramp's side is fixed.
