### ISSUE TITLE
magit-browse-pull-request poor default settings for paginated pull requests

### ISSUE THREAD

**Issue by eklitzke** [magit/magit#3398]
I'm working on a GitHub project that has 250 open pull requests. When magit-browse-pull-request is used interactively, it uses ghub-get to pull information about outstanding pull requests. The results for the /pulls endpoint are paginated to 30 at a time. The default behavior of the /pulls endpoint is to list PRs in ascending order. This means that I see 30 open pull requests that are all more than a year old.

Both of the following would be an improvement:
 * Unpaginate (fetch everything)
 * Just fetch the first page, but sort the other direction (can be specified using the `direction` parameter in the API request)

The latter option seems reasonable to me, and is also the experience you get when using the web site.

**Comment by tarsius** [comment]
> Unpaginate (fetch everything)

This can be extremely slow so I won't do that until the responses are being cached.

> Just fetch the first page, but sort the other direction

I am under the impression that we already use the desired direction:

```
(list (cdr (assq 'number
                 (car (ghub-get (format "/repos/syl20bnr/spacemacs/pulls")
                                nil ; this is what we currently use
                                :auth 'magit))))
      (cdr (assq 'number
                 (car (ghub-get (format "/repos/syl20bnr/spacemacs/pulls")
                                '((direction . "desc"))
                                :auth 'magit))))
      (cdr (assq 'number
                 (car (ghub-get (format "/repos/syl20bnr/spacemacs/pulls")
                                '((direction . "asc"))
                                :auth 'magit)))))
==> (10503 10503 2696)
```

From the documentation:

> The direction of the sort. Can be either `asc` or `desc`. **Default: `desc` when sort is `created` or sort is not specified,** otherwise asc.

We don't specify sort so the order is `desc` aka most recent first.

And, at least when using `ivy`, the complication candidates are also sorted in descending order. Maybe your completion framework changes the order?

**Comment by eklitzke** [comment]
Strange, I went to look again and you're right, I see the requests in the correct order. I updated magit and ghub yesterday, not sure if that was the issue or if its just PEBCAK. Thanks for taking a look.
