### ISSUE TITLE
Magit doesn't recognize tramp files

### ISSUE THREAD

**Issue by dov** [magit/magit#34]
When working with a file in a remote repository through tramp, e.g.:

```
/ssh:there:/home/dov/foo/bar.txt
```

magit does not recognize this syntax and thus does not initiate interaction with the remote repository 'foo' on host 'there.

**Comment by sorawee** [comment]
I think this issue was accidentally closed, and it's not resolved. I still experience the same problem.

**Comment by tarsius** [comment]
This is ten years old. You probably should open a new issue. Since this just works for most people you will have to provide some information that allows us to determine what's different about your setup.
