### ISSUE TITLE
Purge old documentation pages from online manual

### ISSUE THREAD

**Issue by tcoffee-google** [magit/magit#3401]
The current manual page for Magit cherry-picking is 

https://magit.vc/manual/magit/Cherry-Picking.html

but Internet searches for "magit cherry pick" return the outdated page from the nearly-identical URL at

https://magit.vc/manual/magit/Cherry-picking.html

**Comment by tarsius** [comment]
Thanks for letting me know!

I have cleaned that up and it shouldn't happen again. (Using `aws s3 sync --delete` now where appropriate.)

I have also cleaned out old manuals, removing all html manuals and for `with-editor` all older manuals including pdfs. There were many gaps anyway and nobody ever complained about that. While it wouldn't be impossible to do so, re-generating the old missing manuals would have been a lot of work and just not worth it. Going forward I will probably start keeping old html manuals again. The `magit-2.11` manuals doesn't use the correct stylesheet, but that isn't worth fixing either.
