### ISSUE TITLE
Fetching with --tags

### ISSUE THREAD

**Issue by mjhoy** [magit/magit#3403]
There are a couple projects I use where I routinely need to fetch all tags that may not be referenced in branches I am fetching. (See [`git-fetch` documentation](https://git-scm.com/docs/git-fetch).) Therefore I need to run `git fetch --all --tags` to get them, and this doesn't seem possible in Magit currently.

Would it be possible to add a `--tags` options to fetch? If so, and it's not too complicated, perhaps I could submit a PR with an attempt.

**Comment by tarsius** [comment]
Please check out https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands.

**Comment by mjhoy** [comment]
Ah, thanks. Should I add this myself to that page?

**Comment by mjhoy** [comment]
Perhaps this is not as simple as I thought.

```lisp
(magit-define-popup-switch 'magit-fetch-popup
  ?t "Fetch all tags" "--tags")
```

Doesn't really work for "fetch all" (`f a`) which runs `git remote update` under the hood which does not accept the `--tags` flag. In this case there is a popup-switch which only applies to a subset of the popup actions, I think.

**Comment by tarsius** [comment]
After 4b9386cd6f250a09574e69e10a74ffb6a71cbf19 you can add `--tags` to the popup and enable it by default if you wish without that causing any problems for `magit-fetch-all`. But you will have to use a command that fetches from a single remote to actually fetch the tags. Then again, doing that might be a good idea anyway, it avoids pulling crappy tags that have been pushed to some fork.

**Comment by mjhoy** [comment]
Curious, why not `git fetch --all` instead?

**Comment by tarsius** [comment]
Can be traced back all the way to 151ae0a8a399dc9cb0881723beeae990edb7defb. So "because it never seemed necessary to change it", I guess.

**Comment by aspiers** [comment]
Sorry if I'm misunderstanding something, but does this mean magit doesn't support `fetch --tags` out of the box?  I have a relatively recent version and can't see how to do it without configuration.

**Comment by tarsius** [comment]
I've added that argument now.

**Comment by aspiers** [comment]
Cool, thanks a lot!
