### ISSUE TITLE
IPv6 support on official website

### ISSUE THREAD

**Issue by tambry** [magit/magit#3405]
[The official website](https://magit.vc) is inaccessible over IPv6.

**Comment by vermiculus** [comment]
Is there a way to test this for folks who know little more than what IPv6 is?

**Comment by tarsius** [comment]
Should work soon.

**Comment by tambry** [comment]
@vermiculus You can use something like [this](http://ipv6-test.com/validate.php) or [this](https://ip6.nl) to test if a website is IPv6-capable.

@tarsius I'm afraid it hasn't worked worked. The TTL of 900s for the AAAA record has most definitely expired, but neither [Google's DNS](https://dns.google.com/query?name=magit.vc&type=AAAA&dnssec=true) nor the DNS server I use see any AAAA records.

**Comment by tambry** [comment]
Re-tested now and it's fixed. I wonder why the propagation took so long? Does Amazon have some kind of additional internal delay for this?

**Comment by tarsius** [comment]
Okay now it works. (And my other pages are under way.)
