### ISSUE TITLE
ediff across rename boundaries from magit-log

### ISSUE THREAD

**Issue by sbroberg** [magit/magit#3406]
**(1) what behavior you expected**

When viewing a log for file with `magit-log-buffer-file` (using the --follow option), I want to be able to select two revisions that span a file rename (highlight spanning the revisions, press "e").  When doing so, I receive the following prompt: "File in cacd1727 to compare with foo/bar/baz.txt in 8f9ce2af:"  Presumably this wants the path within the repo to the file prior to its move.  If I enter the correct path prior to rename (bar/baz.txt), I expect to get an ediff session between the two commits.  

  **(2) what behavior you observed**

However, I just get one buffer with the state of the file in cacd1727 and an empty buffer for the other one.

Note that, from the Terminal, the following command produces the correct diff results (when run from the root of the project):

`git diff 8f9ce2a4 cacd1727  -- foo/bar/baz.txt bar/baz.txt
`

  **(3) and how we can reproduce the issue.**

1.  Create a file bar/baz.txt in your repo, and make several commits against it.
2.  git mv bar/baz.txt foo/bar/baz.txt
3.  Create several more commits
4.  Set the git-log-arguments to include --follow
5.  Do magit-log-buffer-file, highlight two commits that span the move in # 2 above
6.  Enter the path bar/baz.txt

**NOTE ALSO:**

It would be nice if magit was able to figure out what the original location of the file was so that it is not necessary for me to remember it myself.  This is possible via the git log output if --summary is included along with --follow; rename events appear in the log output as:

`rename {bar => foo/bar}/baz.txt (100%)`

If I include --summary into the git-log-arguments, the rename commands do not appear in the magit-log buffer (presumably ignored by the parser/scraper).  But including them would be extremely useful.

## Also post the output of M-x magit-version RET:
Magit 20180329.1311, Git 2.14.3 (Apple Git-98), Emacs 25.2.1, darwin

**Comment by kyleam** [comment]
I'm not able to reproduce this issue.

I've tried both with your recipe and with the Magit repo.  For the Magit test, I've started a branch at 7d80e0c7842d07e95df7bb0691d50c6150e80aef, soon after the move of *.el files to the lisp subdirectory.  Within magit.el, I call `magit-log-buffer-file` (with <kbd>C-u</kbd> for `--follow`).  Calling `magit-ediff-dwim` (<kbd>e</kbd>) with the rename commit in between (e.g., say with the region boundaries at 7d80e0c7842d07e95df7bb0691d50c6150e80aef and d5b841d4a4dd9cf4fd4f14486ad16bcb246238ab), ediff goes immediately to the diff of magit.el and lisp/magit.el.  What happens on your end?

**Comment by kyleam** [comment]
> It would be nice if magit was able to figure out what the original location of the file was so that it is not necessary for me to remember it myself. 

That's the intended behavior (and what I see on my end).

**Comment by JeppeTh** [comment]
I can reprocude this. 
Sometimes it asks about location and not.
For e.g. magit.el it asks for location when running ediff on e.g. "d5b841d" and "3701440" but not on the lines in between and above these...

Regardless of if it asks about location or not - my buffer to the right is always empty.

Magit 2.13.1, Git 2.8.3, Emacs 25.1.1
I couldn't test later version of Magit at the moment since it seems my magit settings is invalid for newer versions.

**Comment by kyleam** [comment]
@JeppeTh Thanks for the information.

> I can reprocude this.

IIUC what you're describing is not an issue with ediffing _across_ boundaries, but ediffing with both revisions on the bottom side of a rename.  That may sound nitpicky, but at least on my end that's the important detail for me to be able to trigger the issue.

> I guess the problem is that it calls magit-find-file-noselect with the current-filename for the new version.
> E.g. it calls:
> magit-find-file-noselect("b4d23d1^" "magit.el")
> magit-find-file-noselect("b4d23d1" "lisp/magit.el")

Right, magit-ediff-show-commit (and maybe other spots in ediff) incorrectly assumes that the file for the right-side of the range is magit-current-file, which of course isn't true for showing a commit from before the rename boundary in a file-restricted log.

> Magit 2.13.1, Git 2.8.3, Emacs 25.1.1
> I couldn't test later version of Magit at the moment since it seems my magit settings is invalid for newer versions.

FTR: You could try with emacs -Q (the magit repo has a make target to help with this).
