### ISSUE TITLE
magit-remote-popup defines two actions for lower-case "p"

### ISSUE THREAD

**Issue by phil-s** [magit/magit#3409]
Magit 2.12.0, Git 2.8.3, Emacs 25.2.1, gnu/linux

    (magit-define-popup magit-remote-popup
      [...]
      :actions  '((?a "Add"                  magit-remote-add)
                  (?C "Configure..."         magit-remote-config-popup)
                  (?r "Rename"               magit-remote-rename)
                  (?p "Prune stale branches" magit-remote-prune)
                  (?k "Remove"               magit-remote-remove)
                  (?p "Prune stale refspecs" magit-remote-prune-refspecs))

`?p` is used for both `magit-remote-prune` and `magit-remote-prune-refspecs`

**Comment by tarsius** [comment]
Fixed. Thanks!
