### ISSUE TITLE
Incompatible dependencies between emacs & let-alist?

### ISSUE THREAD

**Issue by zenspider** [magit/magit#3414]
I've got an "incompat" status on the latest version:

```
   Requires: emacs-24.4, async-20170823, dash-20170810, ghub-20180328,
               git-commit-20180329, let-alist-1.0.5 (not available),
               magit-popup-20180329, with-editor-20180318
```

Since `let-alist` ships with emacs and isn't upgradable, it seems like emacs 24.4 and let-alist 1.0.5 are an incompatible mix. Is there a way around this?

**Comment by npostavs** [comment]
I think `let-alist` should be upgradable. It's in GNU ELPA: https://elpa.gnu.org/packages/let-alist.html

The source comes from `emacs-master` which says `;; Package-Requires: ((emacs "24.1"))`

**Comment by zenspider** [comment]
Ah! I removed `elpa` from my sources. I see it now. I'm still having issues with `package+` not trying to upgrade it, but that's on my end. Closing.
