### ISSUE TITLE
magit-checkout-pull-request: fetch before checkout

### ISSUE THREAD

**Issue by kommen** [magit/magit#3416]
Magit 20180329.1311, Git 2.17.0, Emacs 25.3.1, darwin

To reproduce:

1) somebody else opens a PR on github (i.e you don't have the PR branch in your local repository)
2) you run `magit-checkout-pull-request` and want to checkout this new PR

This results in an git error:
```
128 git … branch pr-2655 origin/index-dropdown
fatal: Not a valid object name: 'origin/index-dropdown'.

  1 git … checkout pr-2655
error: pathspec 'pr-2655' did not match any file(s) known to git.
```

From `*Messages*`:
```
Contacting host: api.github.com:443 [2 times]
Not a valid object name: 'origin/index-dropdown'. ... [Hit $ to see buffer magit-process: xxx for details]
pathspec 'pr-2655' did not match any file(s) known to git. ...
```

After fetching from the origin, `magit-checkout-pull-request` works as expected.

I'd expect either:

a) this branch is fetched automatically
b) a better error message that the PR branch is not available and I have to fetch from the remote before

**Comment by tarsius** [comment]
Thanks for the report!
