### ISSUE TITLE
Magit refs buffer bad formatting

### ISSUE THREAD

**Issue by wrn** [magit/magit#3423]
Following setup:
Magit 20180410.1528, Git 2.8.3, Emacs 24.5.1, gnu/linux

With "y" key, I got a line like this (see those garbage output like "1>" and "<123"):

  feature/wlam/sandbox1>     <123origin/develop My xyz changes here.

But with Magit 2.11
I got the correct output:
  feature/wlam/sandbox      [origin/develop: ahead 1, behind 123] My xyz changes here.

A bit disappointed while trying the fresh 2.12 release. :-(

**Comment by kyleam** [comment]
I don't think what you're describing is garbage output.  It's the new representation introduced by acea2752 (refs: Change look and massive refactor, 2018-02-15).  Also see ee6a6d86 (magit-refs-pad-commit-counts: New option, 2018-02-17).

**Comment by tarsius** [comment]
It's a feature intended to conserve space.

**Comment by phil-s** [comment]
Also covered in the release notes:

> * The look of `magit-refs-mode' buffers was changed to save horizontal
>   space and three new options `magit-refs-primary-column-width',
>   `magit-refs-focus-column-width' and `magit-refs-pad-commit-counts'
>   were added.  #3378

**Comment by wrn** [comment]
Thanks. Did not know this is a feature. But honestly I found it quite ugly with the numbers before/after branch name without any delimiters. Maybe I will get used to it.

**Comment by tarsius** [comment]
> Maybe I will get used to it.

Or you could customize the mentioned `magit-refs-pad-commit-counts` and maybe face `magit-dimmed`.
