### ISSUE TITLE
Add support for --color-moved

### ISSUE THREAD

**Issue by mgalgs** [magit/magit#3424]
`git` v2.15 added a fancy new `--color-moved` option, which is... amazing.  There's a good write-up and demo of it over [here](https://blog.github.com/2018-04-05-git-217-released/#coloring-moved-code).

I made a half-hearted effort at adding support for this by just adding it to the diff popup switches:

```diff
diff --git a/lisp/magit-diff.el b/lisp/magit-diff.el
index 3304935589..3344a41722 100644
--- a/lisp/magit-diff.el
+++ b/lisp/magit-diff.el
@@ -617,7 +617,8 @@ and `:slant'."
                (?b "Ignore whitespace changes"      "--ignore-space-change")
                (?w "Ignore all whitespace"          "--ignore-all-space")
                (?x "Disallow external diff drivers" "--no-ext-diff")
-               (?s "Show stats"                     "--stat"))
+               (?s "Show stats"                     "--stat")
+               (?c "Color moved"                     "--color-moved"))
     :actions  ((?d "Dwim"          magit-diff-dwim)
                (?u "Diff unstaged" magit-diff-unstaged)
                (?c "Show commit"   magit-show-commit)
```

but the switch didn't seem to have any affect.

I'm not sure if we can really even plumb this through since Magit seems to apply its own diff faces by "washing" the raw diff text (discarding any color escape sequences coming through from `git` itself)?  Just wanted to start a discussion about whether or not this is even possible.

**Comment by tarsius** [comment]
> `git` v2.15 added a fancy new `--color-moved` option

I think that is a typo in this announcement about v2.17.

> Magit seems to apply its own diff faces by "washing" the raw diff text (discarding any color escape sequences coming through from git itself)

Yes, that's how it currently works (except we simply ask `git` not to print any control characters), but I plan to support word-diff and that will require that git's output is manipulated beyond adding text properties and overlays. So this too will probably happen eventually, but it could be a while.

**Comment by tarsius** [comment]
Great! I would be interested to see the non-advice version too! :wink:
