### ISSUE TITLE
Magit takes a long time to refresh on Linux Kernel, git is fine

### ISSUE THREAD

**Issue by maindoor** [magit/magit#3426]
(1) what behavior you expected: I expected magit to show the status as fast as the command line.
  (2) what behavior you observed: Magit status took 47 seconds to display the status, where as git on the command line took 7.5secs
  (3) and how we can reproduce the issue: Take linux kernel version 4.4 and run magit-status.  

Magit Version: Magit 20180403.434, Git 2.7.4, Emacs 25.3.2, gnu/linux

Tried running emacs with just magit as the package loaded, still the same issue, load time 47 secs.
Sometimes more, I don't know how to interpret it. 

*Messages*
Refreshing buffer  magit: linux-4.4 ...done (47.085s)
Refreshing buffer  magit: linux-4.4 ...done (87.707s)

emacs running with minimal config as provided by the output of:
magit-emacs-Q-command
/usr/bin/emacs -Q --eval \(setq\ debug-on-error\ t\) -L /home/skumar/.emacs.d/elpa/magit-20180403.434/ -L /home/skumar/.emacs.d/elpa/magit-popup-20180329.1302/ -L /home/skumar/.emacs.d/elpa/with-editor-20180318.1253/ -L /home/skumar/.emacs.d/elpa/git-commit-20180401.314/ -L /home/skumar/.emacs.d/elpa/dash-20180310.1317/ -L /home/skumar/.emacs.d/elpa/ghub-20180328.830/ -l /home/skumar/.emacs.d/elpa/magit-20180403.434/magit

emacs running on the same machine where I issue the git command:
$ time git status
HEAD detached at /trunk
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        user_headers/

It took 5.29 seconds to enumerate untracked files. 'status -uno'
may speed it up, but you have to be careful not to forget to add
new files yourself (see 'git help status').
nothing added to commit but untracked files present (use "git add" to track)

real    0m7.536s
user    0m0.188s
sys     0m0.596s

Tried to debug this by enabling "debug-on-quit" I see this as the first entry in the stack-trace:
  call-process("git" nil (t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "status.showUntrackedFiles=normal" "describe" "--contains" "HEAD")

Why such a huge difference in "git status" time 7 secs on command line vs  47 secs on magit ?
Are there any ways I can optimize this ?

**Comment by tarsius** [comment]
That's a known issue as documented [here](https://magit.vc/manual/magit/Performance.html) and [here](https://github.com/magit/magit/issues/2982).
