### ISSUE TITLE
Split magit-insert-revision-headers in two

### ISSUE THREAD

**Issue by juan-leon** [magit/magit#3430]
I would like to split `magit-insert-revision-headers` in two so that I can have
more configuration flexibility for `magit-revision-sections-hook`.

I like the default value for `magit-revision-sections-hook`, and I typically use
it.  But sometimes I need to work with huge repos (hundreds of thousands of
commits, lots of branches and tags).  So reviewing commits with those repos is
very slow when `magit-insert-revision-headers` belongs to
`magit-revision-sections-hook`, and I need to remove it for those repos.

Reason it is slow it because it spawns things like `git branch --contains SHA`
and `git branch --merged SHA` and I think something else for tags.  Those
commands are very fast for small repos, and very slow for humongous ones.

When I remove `magit-insert-revision-headers`, I lose this part of the headers,
that I find very useful, and introduces no noticeable delays:

```
583a487069aab60aa2d1200afb3c14115fbead6e
Author:     XXX
AuthorDate: Tue Apr 17 21:30:43 2018 -0300
Commit:     XXX
CommitDate: Tue Apr 17 21:30:43 2018 -0300
Parent:     aad3c18 Blah blah
```

When I just want to lose the slow part:

```
Containing: BranchA BranchB BranchC ... (81 more)
Merged:     Foo Bar ... (69 more)
Precedes:   TagX (1115)
Follows:    TagY (4)
```

If we had `magit-insert-revision-headers` and
`magit-insert-revision-extra-headers` users would have more flexibility for
configuring `magit-revision-sections-hook` to their liking.

Does it make sense?

**Comment by tarsius** [comment]
You can do that using `(setq magit-revision-insert-related-refs nil)`.
