### ISSUE TITLE
Exclude merge commits from `l l` - is the `--no-merges` switch gone?

### ISSUE THREAD

**Issue by bzg** [magit/magit#3432]
Hi!

I've checked in magit commit history and found commit 0e75a00 which adds support for `--no-merges` when listing git logs.  It seems that this switch disappeared. I miss it!

Is there a way with latest magit to exclude merge commits from `l l`?

I've read the documentation and FAQ elsewhere but could not find an answer.

Thanks a lot!

**Comment by tarsius** [comment]
(Off-topic) Funny, just yesterday I though I have to talk to you about merges.

```
8f572aa23 *   Merge branch 'master' of code.orgmode.org:bzg/org-mode
          |\  
2e2b08302 | * org-faces: Complete docstring for org-quote, org-verse
011f1c618 * | Let `org-agenda-set-restriction-lock' remove restriction at point
          |/  
bc37b3258 * ox-koma-letter.el Adds from-logo variable

```

What you are creating here is what some people refer to as a twig - a weak branch.

You should avoid that, the first parent of a merge commit should always be the mainline. (Subject to proper configuration) you have several options here:

1. If "rewriting *unpublished* history" is acceptable, use <kbd>r u</kbd>, resulting in:

```
aaaaaaaaa * [master] Let `org-agenda-set-restriction-lock' remove restriction at point
2e2b08302 * [origin/master] org-faces: Complete docstring for org-quote, org-verse
bc37b3258 * ox-koma-letter.el Adds from-logo variable
```

2. If that is not acceptable, then create a "feature" branch (or maybe in this case it should be called a "two people working at the same time, how horrible" branch) and then merge that. <kbd>b s</kbd> `bzg` <kbd>RET</kbd>, followed by <kbd>m i</kbd> `master` <kbd>RET</kbd>, resulting in:

```
aaaaaaaaa *   Merge branch 'bzr'                           # (into master aka "the mainline")
          |\  
2e2b08302 * | org-faces: Complete docstring for org-quote, org-verse
011f1c618 | * Let `org-agenda-set-restriction-lock' remove restriction at point
          |/  
bc37b3258 * ox-koma-letter.el Adds from-logo variable
```

----

If you go with (1) and thereby avoid unnecessary merges your need for `--no-merges` will significantly decrease :stuck_out_tongue_winking_eye: But Org and Emacs history are already full of twigs, so you will probably need it anyway...

See [Additional proposed infix arguments and suffix commands](https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands) - `--no-merges` is even the first example listed there.

**Comment by npostavs** [comment]
Is there a practical difference between the "twig" and "feature branch" cases? Or is it just about the  message of the merge commit?

**Comment by bzg** [comment]
Thanks for the quick reply!

>  1. If "rewriting unpublished history" is acceptable, use r u,

It is perfectly acceptable.  The question is, how do I know I need to use `r u`?

> See Additional proposed infix arguments and suffix commands -
> --no-merges is even the first example listed there.

Oops, sorry I overlooked this, I tried [this search](https://github.com/magit/magit/search?utf8=%E2%9C%93&q=--no-merges&type=) and didn't click on `Wikis`.

Thanks a lot!

**Comment by tarsius** [comment]
There once was a nice blog post about twig branches but now that someone has created a branch manager called twig, search engines no longer find it...

> Or is it just about the message of the merge commit?

It's mostly about the order of parents, which affects search algorithms, though that is probably more important for long-lived branches than branches that result from multiple users doing small things on `master` at the same time.

But I feel that for the human reader it is also important in the later case. As you surely are aware I like to avoid merges altogether by rebasing smaller work onto `master`, but even if everything is merged using non-fast-forward merges (but after rebasing), then it is still nicer to have one and only one mainline.

`Merge branch 'master' of code.orgmode.org:bzg/org-mode` said "for some time there were two versions of the mainline" the published one and the one on the machine of the developer who eventually merged them again. (I.e two versions of `master` none of which eventually got discarded. The merge combines two versions of `master`.)

When rebasing or doing a `Merge branch 'shortlived'` merge on the other hand, there is only one mainline as it is supposed to be - the published mainline.

> The question is, how do I know I need to use `r u`?

When history has diverged, i.e. when both the `Unmerged into origin/master` and the `Unpulled from origin/master` sections exist.

**Comment by bzg** [comment]
> When history has diverged, i.e. when both the Unmerged into origin/master and the Unpulled from origin/master sections exist.

Great, thanks a lot.

**Comment by kyleam** [comment]
> There once was a nice blog post about twig branches but now that someone has created a branch manager called twig, search engines no longer find it...

http://www.howardism.org/Technical/Git/rebasing.html ?
