### ISSUE TITLE
Force English in rebase key descriptions

### ISSUE THREAD

**Issue by pau4o** [magit/magit#3435]
Hello
This issue was discussed in https://github.com/magit/magit/pull/3175 and was fixed.
I'm getting same behaviour as before with `Magit 20180501.124, Git 2.17.0, Emacs 25.2.2, gnu/linux`

best regards
Kamen

**Comment by tarsius** [comment]
I don't see any commits after 8e762d34658208d1c0371095409e1ffbcd822e40 that touched that file and look like they could cause such a regression. Please post the contents of such a buffer so that I can actually test.

**Comment by pau4o** [comment]
here is content of `git-rebase-todo` buffer
```
pick 390f779 done page 2102
pick 971c623 done page 2101
pick f24ef13 done page 2100

# Пребазиране на a4948e2..f24ef13 върху a4948e2 (3 команди)
#
# Команди:
#  p, pick — прилагане на подаването
#  r, reword — прилагане на подаването, но смяна на съобщението му
#  e, edit — прилагане на подаването и спиране при него за още промени
#  s, squash — сливане на подаването към предходното му
#  f, fixup —  сливане на подаването към предходното му, без смяна на съобщението
#  x, exec — изпълнение на команда към обвивката: останалата част на реда
#  d, drop — прескачане на подаването
#
# Може да променяте последователността на редовете — те се изпълняват
# последователно отгоре-надолу.
#
# Ако изтриете ред, съответстващото му подаване ще бъде ИЗТРИТО.
#
# Ако изтриете всичко, пребазирането ще бъде преустановено.
#
# Празните подавания са коментирани
```

Locale is `LANG=bg_BG.UTF-8` and magit version `Magit 20180501.124, Git 2.17.0, Emacs 25.2.2, gnu/linux`


This issue isn't present with magit version `Magit 20180401.1923, Git 2.11.0, Emacs 25.1.1, gnu/linux` with same locale.

**Comment by kyleam** [comment]
I can reproduce locally.  Looks like the spacing in front of "p, pick" varies across git versions.  @pau4o, please re-open if a3dc813 doesn't fix it for you.
