### ISSUE TITLE
Staging and unstaging hunks in renamed files should be inverse operations

### ISSUE THREAD

**Issue by greenrd** [magit/magit#3436]
Magit 20180413.511, Git 2.14.3, Emacs 25.3.1, gnu/linux

When I run `git mv file file.py`, do some changes, and then stage a hunk in `file.py`, it works as I expect - the hunk appears in the index.

When I then unstage a hunk in `file.py`, it does not work as I expect - `file.py` becomes an untracked file and `file` becomes a deleted file, the change of which is unstaged.

**Comment by phil-s** [comment]
I'm actually surprised that this currently works as well as it does, given that (AFAIU) git doesn't really support renaming files, but rather just notices that in a given commit the blob for a deleted file was also added as a new file, and displays those two actions in a friendlier way in the status.

My (possibly-incorrect) notion is that git is more likely to be able to track changes across file renaming if you commit the rename independently of any modifications, so I always commit a rename before making any changes (which side-steps your issue).

**Comment by tarsius** [comment]
As a temporary workaround you can just create a temporary commit for the rename before making other changes and then squash when done.

> That said, my (possibly-incorrect) notion has always been that git is more likely to be able to track changes across file renames if you commit the rename independently of any modifications, so I always do that (which side-steps your issue entirely).

I wouldn't make large changes in the same commit, that usually belongs in a separate commit regardless of whether "the other change" is a file rename or something else, but adjusting for example `;;; FILE.el ends here` should not be a problem.

**Comment by tarsius** [comment]
It's Magit's fault. `magit-apply-hunk` just uses the header as-is. If we manipulate the following lines, then it works:

```
diff --git FROM TO
--- FROM
+++ TO
```

(Replacing FROM with TO.)

To fix that we should properly parse the extended headers when parsing the diff and then reconstructing the text (leaving the parts that are undesired when applying) a hunk. Currently we just store all extended headers as a single string. Moving away from that will be nicer once sections are proper objects, so I'll probably delay fixing this issue until I tackle those refactorings.

**Comment by tarsius** [comment]
Another approach could be to find all occurrences of ` b/` in `FILE1 b/FILE2` and then walk through them until the one that causes `FILE1` to be equal to `FILE2` is found.

**Comment by tarsius** [comment]
Actually I plan to go back to running `git diff --raw` first (to avoid having to calculate and parse collapsed sections upfront anyway. Once that is in place we don't have to parse the `diff --git` line anymore.

In other words, as mentioned earlier, it could be a while until this is fixed.

**Comment by tarsius** [comment]
From Git v2.22.0 release notes:

```
 * Output from "diff --cc" did not show the original paths when the
   merge involved renames.  A new option adds the paths in the
   original trees to the output.
```

**Comment by michalrus** [comment]
:pray: :crossed_fingers:

**Comment by tarsius** [comment]
Such staging is now possible.

However, I did not take care of the complication regarding file names with spaces. That is still being worked on, see https://github.com/magit/magit/commit/d477163d34a22ff7a30597d0fbc70f62355bceff.
