### ISSUE TITLE
Improved reset command confirmation message?

### ISSUE THREAD

**Issue by phil-s** [magit/magit#3438]
If I'm resetting the current branch to a commit from the log of some other branch, it would be reassuring if the confirmation message was explicit about the branch that I'm about to modify.

Would this change ever be incorrect?

    diff --git a/lisp/magit-reset.el b/lisp/magit-reset.el
    index 3dba6219..4f19e8d8 100644
    --- a/lisp/magit-reset.el
    +++ b/lisp/magit-reset.el
    @@ -55,9 +55,14 @@ head this effectively unstages all changes.
     With a prefix argument also reset the working tree.
     \n(git reset --mixed|--hard COMMIT)"
       (interactive (list (magit-read-branch-or-commit
    -                      (if current-prefix-arg
    -                          "Hard reset to"
    -                        "Reset head to"))
    +                      (let ((currentbranch (magit-get-current-branch)))
    +                        (if current-prefix-arg
    +                            (format "Hard reset %s to"
    +                                    (or currentbranch "detached head"))
    +                          (format "Reset %s to"
    +                                  (if currentbranch
    +                                      (format "head of %s" currentbranch)
    +                                    "detached head")))))
                          current-prefix-arg))
       (magit-reset-internal (if hard "--hard" "--mixed") commit))

**Comment by kyleam** [comment]
> Would this change ever be incorrect?

It should handle the detached head case to avoid saying something like "Reset head of nil ...".  Aside from that, I agree that your suggestion is an improvement.

**Comment by phil-s** [comment]
Yes indeed. I actually realised that after posting and updated the code accordingly, but you will have been reading from the initial Github notification.

**Comment by tarsius** [comment]
He, just yesterday I though about improving these prompts too. What always causes me to double check is that because both prompts contain a word that begin with "h" and is four characters long. I always have to make sure I am not accidentally doing a *hard* reset.

I was thinking about making *hard* bold. But maybe with your changes I won't need that anymore.

The other reset commands should be adjusted accordingly.

**Comment by phil-s** [comment]
Well I just learned that Magit has other reset commands :)  I don't think I have ever looked at that menu.

Making the word "hard" bold sounds a good idea.  Whatever makes things clearest, really.  I'd wondered about using the magit-branch-current face on the branch name, but that might prevent the bold text from standing out.

**Comment by tarsius** [comment]
> Making the word "hard" bold sounds a good idea.

Okay then, please open a pull-request including that.

> I'd wondered about using the magit-branch-current face on the branch name, but that might prevent the bold text from standing out.

If we did that here, then we would also have to do it elsewhere (and make it optional because not everyone would like it), so I don't think that would be worth the effort.
