### ISSUE TITLE
magit-checkout-pull-request: setup pushRemote automatically

### ISSUE THREAD

**Issue by kommen** [magit/magit#3439]
Magit 20180506.723, Git 2.17.0, Emacs 26.1, darwin

To reproduce:

1. checkout a new PR by somebody else with `magit-checkout-pull-request`

I'd expect that in `magit-pull-popup` the `pushRemote` is configured already to the origin of the PR. Instead I first have to configure it myself before being able to pull new changes in the PR.

**Comment by tarsius** [comment]
Does that *never* work or just when you would not actually be allowed to push there?

**Comment by kommen** [comment]
It never works. I do have push rights to the PRs I'm checking out.

**Comment by kommen** [comment]
Maybe not `pushRemote` is actually correct for cases where I don't have push rights.

But for PRs checked out with `magit-checkout-pull-request`, in `magit-pull-popup` only offers to
```
Pull into <branchname> from
u master
e elsewhere
```

Where I'd expect some option setup by default to get the latest changes from the PR.

**Comment by kommen** [comment]
```
ELISP> (let ((pr (ghub-get (format "/repos/%s/pulls/%s"
                            "nextjournal/nextjournal" 2804)
                    nil :auth 'magit)))
  (let-alist pr
    (list .head.ref .locked)))
("remove-cell-names" nil)
```

The PR-branch was in the upstream repository.

**Comment by tarsius** [comment]
> The PR-branch was in the upstream repository.

In that case `branch.NAME.pushRemote` is indeed not set, due to the assumption that someone using this command would already have set `remote.pushDefault = origin`. Why don't you do that?

**Comment by kommen** [comment]
> Why don't you do that?

Lack of being aware of this option. 

I can confirm that setting `git config remote.pushDefault origin` makes `magit-checkout-pull-request` set up the branch as expected.

**Comment by tarsius** [comment]
I think I'll leave things as is. If you don't set this option, then you have to explicitly set the push-remote for every branch that *you* create (though `p p` is helpful about it), so I don't think it is a problem if the same applies to your local copy of someone else's pull-request branches.

**Comment by kommen** [comment]
> I think I'll leave things as is. 

I wanted to suggest that.

Thank you for looking into that!

**Comment by tarsius** [comment]
Np
