### ISSUE TITLE
Directory ‘.git/rebase-merge/’ does not exist

### ISSUE THREAD

**Issue by Silex** [magit/magit#3447]
Hello,

`Magit 20180512.1350, Git 2.17.0, Emacs 25.3.1, gnu/linux`

I cannot rebase already-pushed commits, even when answering yes to all the questions:

```
Some of these commits have already been published to origin/master.
Do you really want to modify them? (y or n) y
Saving file /home/philippe/Dropbox/work/emacs/package-utils/.git/rebase-merge/magit-edit-confirmed...
Directory ‘/home/philippe/Dropbox/work/emacs/package-utils/.git/rebase-merge/’ does not exist; create? (y or n) y
Wrote /home/philippe/Dropbox/work/emacs/package-utils/.git/rebase-merge/magit-edit-confirmed
magit--rebase-public-edit-confirmed: Wrong type argument: stringp, nil
```

The line that is not happy is https://github.com/magit/magit/blob/master/lisp/magit-sequence.el#L609

IMHO there are two things to fix: first it should not ask to create `.git/rebase-merge`, then the bug around `with-temp-file`. Btw what is the purpose of with-temp-file here?

**Comment by tarsius** [comment]
I have temporarily removed the faulty code (well the call to it), and will look at this later.

> Btw what is the purpose of with-temp-file here?

On a technical level: to create a file, like `$ touch file`.

**Comment by Silex** [comment]
> Btw what is the purpose of with-temp-file here?
> 
> On a technical level: to create a file, like $ touch file.

Wouldn't the inner `write-file` do that already?

**Comment by tarsius** [comment]
> Wouldn't the inner write-file do that already?

That would write the contents to of the current bufer to that file.

By the way, the purpose of the disabled code is to prevent a second question about editing published commits during the same rebase session. Continuing a rebase may not ask you again.

Also I haven't pushed the temporary fix yet. I'll first check if I can quickly come up with something more solid. Also it is weird, I tested this, but it seems I made some last minute changes that I failed to test again.

**Comment by Silex** [comment]
> By the way, the purpose of the disabled code is to prevent a second question about editing published commits during the same rebase session. Continuing a rebase may now ask you again.

Well, once you try to do a rebase of public commits things start to fail appart and you can abort the rebase but then the next rebase complains about `.git/rebase-merge` not existing, so I usually restart emacs at this point.

Right now I just avoid rebasing public commits until this issue is fixed (or use the console), but no hurry I don't have to do that often anyway :wink:

**Comment by tarsius** [comment]
Pushed a proper fix :stuck_out_tongue_winking_eye: 

Regarding `with-temp-...`: I mixed up `...-file` and `...-buffer`.

**Comment by Silex** [comment]
Perfect, thanks! :+1:
