### ISSUE TITLE
Use trash-cli, if present

### ISSUE THREAD

**Issue by tsoernes** [magit/magit#3459]
When discarding files, it would be nice if they were thrown into the trash bin with trash-cli (https://github.com/andreafrancia/trash-cli) instead of permanently deleted if trash-cli is present on the system.

**Comment by vermiculus** [comment]
Isn't there a defcustom for this already?

**Comment by kyleam** [comment]
IMO that's not something that should be handled at the level of Magit.  Magit sets `delete-by-moving-to-trash` to `magit-delete-by-moving-to-trash` before calling `delete-file`.  You can customize `system-move-file-to-trash` to use trash-cli.

**Comment by tarsius** [comment]
I agree with @kyleam.
