### ISSUE TITLE
Initial value of magit-auto-revert-mode set by package autoload, early-init.el, etc.

### ISSUE THREAD

**Issue by cmccloud** [magit/magit#3460]
I ran into the issue that some others are also having when using `diff-hl`, and spent some time trying to figure out why my configuration was starting up with both global-auto-revert-mode and magit-auto-revert-mode.

The initial value of `magit-auto-revert-mode` is set by the following expression:
`(and (with-no-warnings magit-revert-buffers) (not global-auto-revert-mode) (not noninteractive))`

It isn't clear to me whether the guard which checks for the value of `global-auto-revert-mode` is, by itself, enough to keep Emacs out of a bad state when that value has to be set before the autoload. In my case, using Emacs 26.1, it meant that I had to load my `custom-file` before the call to `package-initialize`. Which I was already doing, as it turned out. Where I noticed the issue was when I switched to a emacs build on --HEAD.

Emacs 27.0.50 introduces `early-init.el` and `package-quickstart`.
```
** Emacs can now be configured using an early init file.
The file is called 'early-init.el', in 'user-emacs-directory'.  It is
loaded very early in the startup process: before graphical elements
such as the tool bar are initialized, and before the package manager
is initialized.  The primary purpose is to allow customizing how the
package system is initialized given that initialization now happens
before loading the regular init file (see below).
```
So now, the user has to set the value of `global-auto-revert-mode` even earlier in order for the initial value of `magit-auto-revert-mode` to be set to nil by the autoload. 

I'm not sure what the best long term solution is, but maybe think about also checking the value of `global-auto-revert-mode` in the `magit-auto-revert--init-kludge`, at least for now. Since this runs on the `after-init-hook` at the earliest, it gives the user more leeway in setting `global-auto-revert-mode` without `magit-auto-revert-mode` being enabled as well. Explicitly setting the value of `magit-auto-revert-mode` to nil works fine as well.

Observed on: 
Magit 20180522.507, Git 2.17.0, Emacs 27.0.50, darwin
Magit 20180522.507, Git 2.17.0, Emacs 26.1, darwin

**Comment by tarsius** [comment]
Wrong issue.

**Comment by tarsius** [comment]
> It isn't clear to me whether the guard which checks for the value of `global-auto-revert-mode` is, by itself, enough to keep Emacs out of a bad state when that value has to be set before the autoload.

I don't think it is, that code is evaluated when the rest of the mode definition is evaluated, so it is always possible to turn on `global-auto-revert-mode` "too late". But at least as far as Magit is concerned that shouldn't put Emacs in a "bad state". It just means that `magit-turn-on-auto-revert-mode-if-desired` is called needlessly, I think.

> In my case, using Emacs 26.1, it meant that I had to load my `custom-file` before the call to `package-initialize`. Which I was already doing, as it turned out.

I don't know whether that is sufficiently documented or even generally agreed upon, but I think it is necessary for `custom-set-variables` to be run before loading the packages that are being customized.

> Emacs 27.0.50 introduces `early-init.el` and `package-quickstart`.

If that is something that hasn't been taken into account when the `early-init.el` stuff was implemented, then it should be discussed as soon as possible I think. Could you bring that up on the mailing-list please? (It would probably be better to find another example instead of this particularly convoluted case.)

> I'm not sure what the best long term solution is, but maybe think about also checking the value of `global-auto-revert-mode` in the `magit-auto-revert--init-kludge`, at least for now.

We could do something like that, but could you please first describe what breaks if we don't?

**Comment by cmccloud** [comment]
Thanks, I appreciate you taking the time to respond. I want to start by addressing your final point, so that the rest is more clear:

> We could do something like that, but could you please first describe what breaks if we don't?

Having `global-auto-revert-mode`, `magit-auto-revert-mode`, and `diff-hl-flycheck-mode` activated at the same time reliably lead to the error described here [diff-hl#65](https://github.com/dgutov/diff-hl/issues/65). I have not seen the issue since taking steps to ensure that `magit-auto-revert-mode` is disabled. 

The reason I'm bring it up here is because of the three modes, `magit-auto-revert-mode` is the only one that was not being explicitly activated in my config, as I believed that was what the magit manual instructed. Here is the relevant entry:

> If you like buffers that visit tracked files to be automatically reverted, then you might also like any buffer to be reverted, not just those visiting tracked files. If that is the case, then enable this mode instead of magit-auto-revert-mode. 

I really don't mind having to manually _disable_ `magit-auto-revert-mode` whenever I intend to use the other two modes, but it looks to me like a few changes could go a long way to keep it from happening in the first place. 

> I don't think it is, that code is evaluated when the rest of the mode definition is evaluated, so it is always possible to turn on global-auto-revert-mode "too late". But at least as far as Magit is concerned that shouldn't put Emacs in a "bad state". It just means that magit-turn-on-auto-revert-mode-if-desired is called needlessly, I think.

Yes - which then activates `magit-auto-revert-mode`, since `magit-turn-on-auto-revert-mode-if-desired` checks for `auto-revert-mode`, but not `global-auto-revert-mode`.

Regarding the rest:
I will take some time to better understand how custom-set-variables works because at the moment I don't see a problem. If I find something that seems out of place I will bring it up with the mailing list. 

Thanks very kindly.

**Comment by tarsius** [comment]
> Yes - which then activates `magit-auto-revert-mode`, since `magit-turn-on-auto-revert-mode-if-desired` checks for `auto-revert-mode`, but not `global-auto-revert-mode`.

I forgot about `global-auto-revert-mode` *not* enabling  `auto-revert-mode`. Both modes being enabled could indeed lead to some complications. For now I changed the `turn-on` function to do nothing if the global mode is on.

> I will take some time to better understand how custom-set-variables works because at the moment I don't see a problem.

One problem that I expect is that the `:set-after` property would not be taken into account if it is unknown that the options that follow are about to be customized.
