### ISSUE TITLE
Support "my fork by default" workflow

### ISSUE THREAD

**Issue by glasserc** [magit/magit#3461]
Sometimes I work on projects which are maintained on GitHub. Typically there is an organization-wide "central" repository (as an example, `magit/magit`), whose `master` is the source of truth for the current version of the software. Releases and issues are also often kept on this repository. Maintainers (including but not limited to myself) have push privileges on this repository. Work is done on feature branches. Different maintainers have different preferences as for where these feature branches belong. Some maintainers prefer that they be in the "central" repository with the intent that they are easier to collaborate on. Personally, I prefer to do as much work as possible on a fork, with the desire that my fork can serve as a workspace where I don't need to see other people's work in progress nor accidentally share with them things that might still be ugly.

Accordingly, I usually have `master` with upstream `origin/master`, and `remote.pushDefault` set to a remote corresponding to my fork (I use my GitHub username).

Today I wanted to work on a PR opened by Greenkeeper on the "central" repo. Greenkeeper does not work on a fork, but rather on the "central" repository directly. I tried using the `b y` command from Magit `master` to check out a PR  the "central" repository, and it checked out a branch, but didn't set `pushDefault` to the "central" repository.

Indeed, the documentation even says:

> If the pull-request branch is located in the upstream repository, then it is not necessary to configure the push-target.
>
> (If you have push access to the upstream repository, then it is usually a good idea to configure that as the push-remote using remote.pushDefault. However even if you are not using that recommended setting, then it is still easy enough to set branch.<name>.pushRemote while pushing using P p.)

But I would not want to set `remote.pushDefault` to the upstream repository, because then my branches would normally go to the central repository instead of my fork.

In my opinion, the correct behavior for creating a branch from a PR should be the same whether or not the branch on which the PR is based is upstream. That is, I would expect the `pushRemote` to be set for the branch to the repo where the branch lives. Personally, I would expect this to be the case even if I didn't have permission to push to that branch/repo (in case the user grants me permission to push to that repo later).

Perhaps my workflow is just invalid/not something that Magit should support. In that case, I would appreciate more explicit documentation about the branching model it expects in a typical project. I was able to find https://magit.vc/manual/magit/The-Two-Remotes.html#The-Two-Remotes and https://emacsair.me/2016/01/18/magit-2.4/, but as far as I can tell, I'm in compliance with what it says (I use `pushDefault` to point to where I expect to push branches, and I have `upstream` set to where I expect them to eventually be merged.)

Refs #3439.

(Sorry if this is technically a "support request" and thus belongs elsewhere -- I felt that I straddled the line between that and "asking for a new feature and other improvements".)

**Comment by tarsius** [comment]
> But I would not want to set `remote.pushDefault` to the upstream repository, because then my branches would normally go to the central repository instead of my fork.

Seems like I didn't consider that use-case. That variable (and a few others) are now always set.

> Personally, I would expect this to be the case even if I didn't have permission to push to that branch/repo (in case the user grants me permission to push to that repo later).

I think the case where a casual contributor worked directly on master and the maintainer wants to push their own version of the pull-request is much more common, so I won't do that.
