### ISSUE TITLE
magit-checkout error: (wrong-type-argument stringp nil)

### ISSUE THREAD

**Issue by rompy** [magit/magit#3462]
`magit-checkout` returns an error when called from `magit-status` or interactively:

> Debugger entered--Lisp error: (wrong-type-argument stringp nil)

>  string-match("\\`heads/\\(.+\\)" nil)

>  #f(compiled-function (revision) "Checkout REVISION, updating the index and the working tree.\nIf REVISION is a local branch, then that becomes the current\nbranch.  If it is something else, then `HEAD' becomes detached.\nCheckout fails if the working tree or the staging area contain\nchanges.\n\n(git checkout REVISION)." (interactive #f(compiled-function () #<bytecode 0x15fc961>)) #<bytecode 0x15b2091>)(nil)

 > apply(#f(compiled-function (revision) "Checkout REVISION, updating the index and the working tree.\nIf REVISION is a local branch, then that becomes the current\nbranch.  If it is something else, then `HEAD' becomes detached.\nCheckout fails if the working tree or the staging area contain\nchanges.\n\n(git checkout REVISION)." (interactive #f(compiled-function () #<bytecode 0x15fca85>)) #<bytecode 0x15b2091>) nil)

>  magit-checkout(nil)
>  funcall-interactively(magit-checkout nil)
>  call-interactively(magit-checkout)
>  magit-invoke-popup-action(98)
>  funcall-interactively(magit-invoke-popup-action 98)
>  call-interactively(magit-invoke-popup-action nil nil)
>  command-execute(magit-invoke-popup-action)

Magit 20180527.658, Git 2.17.0, Emacs 26.1, gnu/linux

This happens only for the following status commands: `b b`, `b c`

**Comment by kyleam** [comment]
Interactively that should never happen because `magit-read-other-branch-or-commit` should raise an error on a nil value:

https://github.com/magit/magit/blob/50d0ea2a52114d3ac88125f0a211c19336d67620/lisp/magit-git.el#L1815-L1817

My only suggestion is to make sure you don't have stale *.elc files hanging around and to debug the code if you still have issues.

**Comment by rompy** [comment]
Found the culprit. It wasn't stale `.elc` files, it was this piece of code:
```
(eval-after-load 'magit-branch
    '(progn
       (advice-add 'magit-checkout
                   :after #'projectile-invalidate-cache)
       (advice-add 'magit-branch-and-checkout
                   :after #'projectile-invalidate-cache)))
```

Thanks for the help!
