### ISSUE TITLE
Git repository not recognized over Tramp

### ISSUE THREAD

**Issue by nithyanandan** [magit/magit#3463]
This is related to issue #3345. Since I can't reopen it, I am creating a new ticket. 

I am trying to edit a git repository on a remote server using SSH via Tramp. 

Info on my local machine:
OS: OS X 10.10.5 (Yosemite)
Emacs version: 25.3
```M-x magit-version``` -->  ```magit-20150124.930```
```git --version``` --> ```2.17.0```

Info on remote server (remote1):
OS: Red Hat Enterprise Linux Workstation release 6.9 (Santiago)
```git --version``` --> ```2.17.0```
```which git``` -->  ```/opt/local/bin/git```
Emacs version: 24.5.1
```M-x magit-version``` --> ```Magit 20180510.1409, Git 2.17.1, Emacs 24.5.1, gnu/linux```

I edit my remote repos using Emacs and magit on my local machine via SSH/Tramp. 

Expected behavior: 
I expected ```M-x magit-status``` will open the git repository in the folder in which it is called.

Observed behavior: 
```M-x magit-status``` --> ```Git repository: /ssh:remote:/path/to/git/repo/```
This itself was unexpected. In any case, pressing carriage return gives 
```There is no Git repository in /ssh:remote:/path/to/git/repo/. Create one? (y on n)```
Pressing ```y``` --> ```Git failed. See magit-process for details```
Contents of magit-process:
```
  1 git --no-pager -c core.preloadindex=true init /ssh:remote:/path/to/git/repo/
Unknown option: -c
usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path]
           [-p|--paginate|--no-pager] [--no-replace-objects]
           [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE]
           [--help] COMMAND [ARGS]
```

The second strange behavior is trying magit on the remote machine from the remote Emacs works perfectly fine (when Tramp is not invoked)

The third strange behavior is that I have used the same magit from my local machine to work on another remote server (Ubuntu 16.04.4 LTS, git version 2.7.4) which works smoothly. So the local magit does not recognize the .git in remote1 but does fine in remote2. 

How to reproduce this issue?

Go to git repo in the remote via tramp, and issue ```M-x magit-status```

I have also added the lines in my .emacs on the local machine:
```
(setenv "PATH" (concat (getenv "PATH") ":/opt/local/bin")) 
(setq exec-path (append exec-path '("/opt/local/bin"))) 
```
That seems to make no difference. 

Adding the line
```(setq magic-git-executable "git")``` 
in the .emacs also makes no difference. 

Magit works on git repos that are local and on remote2 but not on remote1. 

Are there incompatible versions of magit vs. git in play?  I remember trying to upgrade my local magit but it complained that it was expecting Emacs 24.3 but wasn't available. I would have had to downgrade my Emacs and I can't foresee the consequences. So I am afraid of making changes and then unintentionally unleashing a chain of broken parts.
 
Could someone help understand what I am missing?

**Comment by npostavs** [comment]
> Info on remote server (remote1):
> OS: Red Hat Enterprise Linux Workstation release 6.9 (Santiago)
> git --version --> 2.17.0
> which git --> /opt/local/bin/git

Does `which -a git` reveal another older git somewhere else?

> ```
>   1 git --no-pager -c core.preloadindex=true init /ssh:remote:/path/to/git/repo/
> Unknown option: -c
> ```

Can you try <kbd>:</kbd> `git --version` <kbd>RET</kbd> and <kbd>:</kbd> `git --exec-path` <kbd>RET</kbd>

> I remember trying to upgrade my local magit but it complained that it was expecting Emacs 24.3 but wasn't available. I would have had to downgrade my Emacs and I can't foresee the consequences. 

When Emacs complains that it can't find 24.3, it means that 24.3 or greater is required. Is it possible you were accidentally executing the old Emacs 22 which ships with macOS when this happened?

**Comment by tarsius** [comment]
> ```M-x magit-version``` -->  ```magit-20150124.930```

That's an extremely old version. Please update and try again.

**Comment by samwalrus** [comment]
I am also having this issue.
I can magit fine on my local repositories but the remote ones do not work:
If I navigate using dired to a directory that has already been initialised as a git repository  and then
`C-X-g` 
Output: Git repository: /Path/Path
Press `Return`
Output: Create repository in /ssh:blah/path/path (y or n)
Press `y`
OutPut: Not inside Git repository.

If I run magit version when I first open emacs I get:
Magit 20180802.2244
Git 2.18.0
Emacs 26.1 Darwin

However if I tramp into a directory on my remote then run the same command I get:
Magit 20180802.2244
Git unknown
Emacs 26.1 Darwin

If I run `git --version` on my remote shell I get:
git version 2.18.0.rc0

I tried running `which git` on my server and I got:

/cm/shared/tools/git-2.18.0/bin/git

So I tried adding this to my .emacs file:
(require 'tramp)
(push "/cm/shared/tools/git-2.18.0/bin/git" tramp-remote-path)

But it did not change the behaviour.

**Comment by tarsius** [comment]
You probably did not do this bit from the end of `(info "(tramp)Remote programs")`:

> When remote search paths are changed, local TRAMP caches must be
> recomputed.  To force TRAMP to recompute afresh, exit Emacs, remove the
> persistent file (*note Connection caching::), and restart Emacs.

**Comment by samwalrus** [comment]
What/where is the persistent file that needs to be removed?

**Comment by tarsius** [comment]
The above link takes you too:

> 5.13 Reusing connection related information
> 
> For faster initial connection times, TRAMP stores previous connection
> properties in a file specified by the user option
> ‘tramp-persistency-file-name’.
> 
>    The default file name for ‘tramp-persistency-file-name’ is
> ‘~/.emacs.d/tramp’.
> 
>    TRAMP reads this file during Emacs startup, and writes to it when
> exiting Emacs.  Delete this file for TRAMP to recreate a new one on next
> Emacs startup.
> 
>    Set ‘tramp-persistency-file-name’ to ‘nil’ to disable storing
> connections persistently.
> 
>    When TRAMP detects a change in the operating system version in a
> remote host (via the command ‘uname -sr’), it flushes all connection
> related information for that host and creates a new entry.

**Comment by samwalrus** [comment]
Thanks for the response but that did not work.
I deleted the file and have the same behaviour. 
I also tried adding this (setq magit-git-executable "/cm/shared/tools/git-2.18.0/bin/git") to my .emacs this allowed magit to work on the server but when going back to a buffer on my local machine emacs locked up and needed to be forced quit.

**Comment by samwalrus** [comment]
Do I need to change the `exec-path` ? If so how would I do that?

**Comment by samwalrus** [comment]
Some more info: 
If I use dired over tramp to get to a remote folder and then run:

M-! which git
which: no git in (/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/local/bin)

M-! git --version
/bin/sh: git: command not found

M-& which git
which: no git in (/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/local/bin)

M-& git --version
/bin/sh: git: command not found

So these commands are not finding git, but if I M-x shell on the server and run git it works fine.
I am not sure if this is something to do with Mac os?  I have this installed: https://github.com/purcell/exec-path-from-shell to get my paths working

**Comment by nithyanandan** [comment]
> > `M-x magit-version` -->  `magit-20150124.930`
> 
> That's an extremely old version. Please update and try again.
> 
> > I remember trying to upgrade my local magit but it complained that it was expecting Emacs 24.3 but wasn't available.
> 
> 24.3 _or higher_ is required.

I'd like to reopen this thread. 

My local Emacs is now updated to 26.1. My local git is 2.19.0. 

However, I cannot update my local magit which is still `magit-20150124.930`. 

`M-x package install RET magit RET` returns `if: Package ‘emacs-25.1’ is unavailable`

`M-x list-packages` returns `cond: Invalid version list ‘(8 6 -4)’`

**Comment by tarsius** [comment]
I think you are still using an older Emacs version. Ask the running instance using `M-x emacs-version`.

**Comment by nithyanandan** [comment]
`M-x emacs-version` yields 
`GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-06-22`

**Comment by tarsius** [comment]
Maybe you have different ways of starting emacs and depending on what method you use you sometimes start version 26 and sometimes <=24. So my suggestion is to use `M-x emacs-version` to make sure you are running the version you think you are running and then, *in the same instance* try to install `magit` again.

**Comment by nithyanandan** [comment]
I can positively confirm this happens in the same instance, where I check 
`M-x emacs-version` which gives
`GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-06-22` 
and 
`M-x package-install RET magit RET` gives
`Package ‘emacs-25.1’ is unavailable`

**Comment by tarsius** [comment]
A web search revealed that the problem probably is an ancient `package.el` laying around on the `load-path`. See https://stackoverflow.com/questions/16177807/js2-refactor-from-melpa-package-emacs-24-1-is-unavailable#16211305.
