### ISSUE TITLE
Heads-up - window-configuration-change-hook is deprecated

### ISSUE THREAD

**Issue by vxid** [magit/magit#3465]
The `window-configuration-change-hook` is deprecated in Emacs 26. According to the changelog:

> Resizing a frame no longer runs 'window-configuration-change-hook'. 'window-size-change-functions' should be used instead.

In magit's case, `magit-set-buffer-margin` in `magit-margin.el` seems to use this now deprecated hook.

Note that I did **not** observe any bad bahaviour with margins in Magit so far, this really is a heads up. Some other packages that I use (emacs-dashboard especially) have issues because of this hook though.

**Comment by tarsius** [comment]
Thanks for the heads up.

I don't think the hook is obsolete (`describe-variable` doesn't say so). It just isn't run anymore when the frame size changes, but that's not what it is used for here. Emacs margins belong to windows but Magit's margins are about certain buffers so we have to do something when a window starts displaying another buffer.
