### ISSUE TITLE
Some of these commits have already been published to nil

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#3468]
Hi,

I'm working with a clone of the Gnu Elpa repository to which I push changes from time to time.
I have N commits C_i not yet uploaded, so the log looks like

|master| C_n
...
C_1
|origin/master| C_0
...

Now, suppose C_n is a FIXUP commit for C_1, the commit with the latest origin/master commit as a parent.   In magit:elpa I hit r f to autosquash, and then I'm asked "Some of these commits have already been published to nil.\nDo you really want to modify them".  That is uncalled for (this action doesn't affect any commits on origin/master) and useless ("published to nil").  When I answer "y", I can proceed.

With edebug I see that magit-rebase-interactive-assert receives C_0 as SINCE argument, that comes from magit-rebase-interactive-1which delivers the return value of
```
(magit-git-string "merge-base" it "HEAD")
```
as SINCE arg to magit-rebase-interactive-assert.  This seems wrong.

The "have already been published to nil" part comes from magit--rebase-published-symbol bound to nil when magit-confirm gets called - maybe that does only happen in this special erroneous case.

I'm using the current Magit version from Melpa, the problem occurred first 10-20 days ago or so, it is definitely quite new.  I see that Jonas has changed magit-rebase-interactive-assert 3 weeks ago, these commits will likely be the culprit.

TIA, Michael.

**Comment by tarsius** [comment]
> useless ("published to nil")

Fixed that part.

> That is uncalled for (this action doesn't affect any commits on origin/master)

I'll have to figure out how to address that. It violated the assumption that we would always get a revision like `REV^` here, except when `--root` is involved.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> Closed #3468 via 02e6c75.

Great, thanks!

**Comment by tarsius** [comment]
You are welcome!

**Comment by michael-heerdegen** [comment]
FWIW I got the unnecessary warning again, under a bit different circumstances.  AFAIR I was in an interactive rebase, and there had been a conflict with the bottommost unpublished commit.  That action didn't touch any published commit (I got no diverging branches), but I got the warning "had been already published to ... really edit?" nonetheless.

**Comment by tarsius** [comment]
What command complained, `rebase --interactive`, `rebase --continue` or `commit`?

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> What command complained, rebase --interactive, rebase --continue or
> commit?

I think it was rebase --continue.

**Comment by greenrd** [comment]
I have just hit this as well, with rebase --continue. Shall I file a new bug?
