### ISSUE TITLE
Missing remote branches no longer shown in the refs view

### ISSUE THREAD

**Issue by nickjmeyer** [magit/magit#3470]
When looking at the `magit-status` buffer, you can see if the remote branch is missing or not when an upstream is configured.  It used to be the case where the `magit-show-refs` would also show if the remote branches were missing.  For each branch in the refs buffer, it would change the face of the remote branch if it was missing.

Here is what I am seeing in the show refs:
![screenshot from 2018-06-04 17-07-52](https://user-images.githubusercontent.com/9648755/40941772-fdb76ff6-6819-11e8-8275-433b745e2054.png)

What I would expect would be something like what the status buffer shows, but in the refs buffer.
![screenshot from 2018-06-04 17-09-59](https://user-images.githubusercontent.com/9648755/40941823-26c10f10-681a-11e8-8d7b-6208f85e357e.png)

I replicated this error both with my normal emacs config and also a bare bones emacs.

Here is the command I ran to test this with a bare bones config:
`emacs -Q -l ~/.emacs.d/elpa/magit-20180604.958/magit-autoloads.el -l ~/.emacs.d/elpa/dash-20180413.30/dash-autoloads.el -l ~/.emacs.d/elpa/with-editor-20180414.757/with-editor-autoloads.el -l ~/.emacs.d/elpa/git-commit-20180602.1756/git-commit-autoloads.el -l ~/.emacs.d/elpa/magit-popup-20180509.1041/magit-popup-autoloads.el -l ~/.emacs.d/elpa/ghub-20180417.1527/ghub-autoloads.el`

The version of magit is `Magit 20180604.958, Git 2.7.4, Emacs 25.3.50.2, gnu/linux`.

Was this feature removed intentionally or is this a bug?

**Comment by tarsius** [comment]
We switched from using `git branch -vv` to using `git for-each-ref --format=...`.

`%(upstream:trackshort)` might be helpful here `%(upstream:track)` doesn't appear to make a difference between nothing-specified and missing.

**Comment by tarsius** [comment]
Actually it works on Git `2.17.1`, the relevant code is [here](https://github.com/magit/magit/blob/master/lisp/magit-refs.el#L676-L677). It doesn't work on `2.11.0`. I don't know with what version it starts working and I don't think this feature is important enough to add a kludge for older versions.

**Comment by kyleam** [comment]
> I don't know with what version it starts working

Looks like it was v2.13.0, specifically ffd921d31 (ref-filter: make %(upstream:track) prints "[gone]" for invalid upstreams, 2017-01-10).

**Comment by nickjmeyer** [comment]
Confirmed. Updated to 2.17.1.  It works now.  Thanks!
