### ISSUE TITLE
Fuzzy selection of branches with Helm

### ISSUE THREAD

**Issue by m-cat** [magit/magit#3476]
(1) what behavior you expected
  (2) what behavior you observed
  (3) and how we can reproduce the issue.

1. When selecting a branch (`b b`) with the Helm interface, I would like to be able to type part of the branch name and have it available as a selection. For example, if I have a branch named `2650`, I would like to be able to type `50` and have the branch appear. **This used to work, but it seems the behavior has changed in a regression.**

2. Typing `50` in the example above results in no Helm candidates.

3. Try to fuzzy-select a branch with Helm installed and enabled.

**Comment by tarsius** [comment]
I don't think anything changed on Magit's side. I don't use Helm and don't know whether it does fuzzy matching out-of-the-box or if it needs another package, which you might no longer have installed.

**Comment by kyleam** [comment]
I use helm, but I hadn't yet upgraded to a version that has this issue.

I've bisected it to helm's

```
commit 1aca3e84501955b98b824c7ddd221e88f9f2563d
Date:   Thu May 24 12:25:49 2018 +0200
    Always use a sync handler when COLLECTION is a function

    in completing-read.

    * helm-mode.el (helm--completing-read-default): Do it.
```

I haven't looked in detail at that change yet.

**Comment by m-cat** [comment]
> I don't think anything changed on Magit's side. I don't use Helm and don't know whether it does fuzzy matching out-of-the-box or if it needs another package, which you might no longer have installed.

That's odd, Magit is the only package where I've encountered this behavior so far. I use Helm in many places and fuzzy finding has always worked.

If it helps, the revert dialogue (`V V`) is able to fuzzy-select the *current* branch, but no other branches. Weird.

**Comment by kyleam** [comment]
> That's odd, Magit is the only package where I've encountered this behavior so far.

The helm commit that I pointed to changes the behavior based on whether the collection is a function.  `magit-builtin-completing-read` wraps the collection in a function to prevent the collection from being sorted alphabetically by Emacs's built-in completion.  See aa5f098a (completion: override default alphabetical sorting, 2017-03-30).

So if you did

```diff
diff --git a/lisp/magit-utils.el b/lisp/magit-utils.el
index dd1869a4..fcd92c95 100644
--- a/lisp/magit-utils.el
+++ b/lisp/magit-utils.el
@@ -439,7 +439,7 @@ (defun magit-builtin-completing-read
                              (bound-and-true-p ivy-mode))
                          prompt
                        (magit-prompt-with-default prompt def))
-                     (magit--completion-table choices)
+                     choices
                      predicate require-match
                      initial-input hist def)))

```

helm's fuzzy completion would work for you again (and unfortunately the built-in completion would no longer keep the collection's order).

**Comment by tarsius** [comment]
@kyleam Could you please check out https://github.com/abo-abo/swiper/issues/1611? 

> `magit-builtin-completing-read` wraps the collection in a function to prevent the collection from being sorted alphabetically by Emacs's built-in completion.

So my claim on that issue that "the build-in completion doesn't sort by default" is only partially correct, right?

**Comment by kyleam** [comment]
@tarsius yes, at least in all the Emacs versions I've tested, the built-in completion sorts alphabetically by default.
