### ISSUE TITLE
Suggestion: include all commits in region when diffing

### ISSUE THREAD

**Issue by ntc2** [magit/magit#3482]
When I use the region to select a range of commits (in status buffer or log buffer) and then diff, the behavior is different if I select one commit or multiple commits. I would like the same behavior in both cases.

If I select one commit `c` and then diff, I get the diff of `c^..c`, i.e. all of the changes in `c`. If I select a range of commits `c1` through `c2` and diff, then I get the diff `c1..c2`, i.e. all the changes up to `c2` not including `c1`; what I would like is to get `c1^..c2` instead, i.e. to also include the changes in `c1` in the composite diff.

As a special case, note that selecting one commit `c` vs selecting two commits `c` and its single parent `p` do the same thing, since `c^` is `p`. This seems confusing to me: when I select two commits and diff I expect to see more than selecting just one of them.

As an aside, it would be nice if the region remained active when I ran the diff, to remind me which commits I'm diffing.

**Comment by tarsius** [comment]
> As a special case, note that selecting one commit `c` vs selecting two commits `c` and its single parent `p` do the same thing, since `c^` is `p`. This seems confusing to me: when I select two commits and diff I expect to see more than selecting just one of them.

For a long time it was not possible to select a single section. Since 2.12 this is possible, see #3026 and
#3234. `magit-diff-dwim` is one of the (majority of) commands that did not start to treat a single-section selection differently from no selection at all.

> If I select a range of commits `c1` through `c2` and diff, then I get the diff `c1..c2`, i.e. all the changes up to `c2` not including `c1`; what I would like is to get `c1^..c2` instead, i.e. to also include the changes in `c1` in the composite diff.

I don't think I will change this. Both behaviors make sense but the existing behavior is what users are used to and it also matches what one would expect coming from command-line git.

> As an aside, it would be nice if the region remained active when I ran the diff, to remind me which commits I'm diffing.

That's regular Emacs behavior. The region gets deactivated when invoking a command. It might be possible to prevent this without touching Magit code at all, or not.

**Comment by ntc2** [comment]
On Wed, Jun 13, 2018 at 5:05 PM, Jonas Bernoulli
<notifications@github.com> wrote:

> > If I select a range of commits c1 through c2 and diff, then I get the diff c1..c2, i.e. all the changes up to c2 not including c1; what I would like is to get c1^..c2 instead, i.e. to also include the changes in c1 in the composite diff.
>
> I don't think I will change this. Both behaviors make sense but the existing behavior is what users are used to and it also matches what one would expect coming from command-line git.

Fair enough, thanks for considering. I agree that the current behavior
matches command-line Git, in the sense that `diff c1..c2` behaves the
same way that selecting the region from `c1` to `c2` in Magit does.
However, I disagree that it matches what one would expect coming from
command-line Git, since it wasn't what I expected coming from
command-line Git :D

But yes, assuming people are already used to it working this way,
changing may be a bad idea, unless the change is opt-in / hidden
behind a setting and not the default. Now that I know how it works, I
doubt it will confuse me again. And before it confused me, I wouldn't
have known to look for the option to change the confusing behavior
anyway, should that option have existed. So I'll just close this
issue.

**Comment by ntc2** [comment]
> > > If I select a range of commits c1 through c2 and diff, then I get the diff c1..c2, i.e. all the changes up to c2 not including c1; what I would like is to get c1^..c2 instead, i.e. to also include the changes in c1 in the composite diff.
> 
>  > I don't think I will change this. Both behaviors make sense but the existing behavior is what users are used to and it also matches what one would expect coming from command-line git.
>
> Fair enough, thanks for considering. I agree that the current behavior
> matches command-line Git, in the sense that `diff c1..c2` behaves the
> same way that selecting the region from `c1` to `c2` in Magit does.
> However, I disagree that it matches what one would expect coming from
> command-line Git, since it wasn't what I expected coming from
> command-line Git :D

On the point of whether Magit should do or does do what command line Git would make one expect, I just noticed that interactive rebase in Magit does not do what command line git does: when you interactive rebase in Magit, the selected commit and all of its ancestors are selected. With command line Git, on the other hand, only the ancestors of the specified commit are included.

I think what Magit does here for interactive rebase is better than what Git does. Similarly, I think Magit could make a better choice for range diffs ;)

**Comment by kyleam** [comment]
> Similarly, I think Magit could make a better choice for range diffs ;)

I don't see a better choice for magit to make here.  diff is about comparing endpoints, and the region boundaries are just serving as markers for those endpoints.  When you say things like "diff c1..c2, i.e. all the changes up to c2 not including c1", it seems like you are only considering cases where c1 is an ancestor of c2, but we also need to deal with things like diffing f and e:


    f *
    c *
      | * e
      | * d
      | * b
      |/
      * a
