### ISSUE TITLE
Diffing jupyter notebooks using nbdime

### ISSUE THREAD

**Issue by fbergroth** [magit/magit#3484]
Following the instructions in the [nbdime docs](http://nbdime.readthedocs.io/en/stable/#git-integration-quickstart), I get the nice diffs from the command line as shown in the example.

In magit however, I still only see the raw json blobs. I tried removing `"--no-ext-diff"` from `magit-diff-arguments`, but it still didn't work.

Any ideas? 

<details>
<summary>example_notebook.ipynb</summary>

```json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "3"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "1 + 2"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

</details>

**Comment by kyleam** [comment]
> I tried removing "--no-ext-diff" from magit-diff-arguments

Hmm, deactivating that switch should do the trick (it works on my end).  Regardless, the output won't integrate well into Magit because it doesn't know how to parse it.

**Comment by fbergroth** [comment]
Ah, I see. Thanks! I guess one could write a script that rewrites the output from nbdiff. I'll close this for now.

**Comment by galeo** [comment]
Could magit provide an extension for nbdime? In the field of scientific computing, notebooks are used a lot. It would be great if nbdime can be used in magit to obtain the diff output results of the notebook.

**Comment by tarsius** [comment]
Someone could implement an extension to do that, yes. But I do not intend to do it.
