### ISSUE TITLE
magit-blame-copy-hash is broken for defadvice'd message

### ISSUE THREAD

**Issue by akopytov** [magit/magit#3485]
(1) what behavior you expected

I expected `magit-blame-copy-hash` to not depend on the message format produced by the `message` function. That is, just save the commit hash and nothing else to the kill ring as documented

  (2) what behavior you observed

I have a customized message format which prepends each message with a timestamp:

```elisp
(defadvice message (before when-was-that activate)
  "Add timestamps to `message' output."
  (ad-set-arg 0 (concat (format-time-string "[%Y-%m-%d %T %Z] ")
                        (ad-get-arg 0)) ))
```

As a result, when I hit `M-w` in a magit-blame buffer, the string containing both the timestamp and the git hash gets copied.

  (3) and how we can reproduce the issue.

Define the above advice for `message`. Use `magit-blame-copy-hash`, observe unexpected results in the kill ring.

`magit-version: Magit 2.13.0-42-gf987534, Git 2.7.0, Emacs 26.1, darwin`

**Comment by kyleam** [comment]
Your expectation seems fair enough.  This is because we handle displaying a message and killing in one go with `(kill-new (message "%s" ...))`.  Note that you'll also have issues with `magit-copy-section-value` and `magit-copy-buffer-revision`, since they use the same pattern.  Out of curiosity, I grepped emacs proper for this pattern; I found only two offenders:

```
lisp/textmodes/bibtex.el:3151:            (if url (kill-new (message "%s" url))
lisp/textmodes/bibtex.el:3156:          (kill-new (message "%s" (funcall bibtex-summary-function)))
```

**Comment by tarsius** [comment]
I don't think we are doing anything wrong here since we rely on documented behavior: the doc-string contains "Return the message". You should change your advice to:

```lisp
(advice-add 'message :around
            (lambda (fn format-string &rest args)
              (let ((msg (format format-string args)))
                (funcall fn "%s %s"
                         (format-time-string "[%Y-%m-%d %T %Z]")
                         msg)
                msg)))
```

**Comment by akopytov** [comment]
That works perfectly. Thank you for the tip and for magit!

**Comment by kyleam** [comment]
> I don't think we are doing anything wrong here since we rely on documented behavior: the doc-string contains "Return the message".

Right, good point.
