### ISSUE TITLE
Invalid magit-popup-use-prefix-argument value: disabled

### ISSUE THREAD

**Issue by LefterisJP** [magit/magit#3486]
When in a repo and pressing "c" or "b" or anything that would use magit popup I get the error `Invalid magit-popup-use-prefix-argument value: disabled`. It seems to come out of the magit popup module and specifically [here](https://github.com/magit/magit-popup/blob/master/magit-popup.el#L854).

This started happening only today when I updated with the following version:
Magit 2.13.0-56-g06189617, Git 2.17.1, Emacs 26.1, gnu/linux

Using a clean emacs magit setup with `emacs-magit-Q-command` I get the following backtrace when trying to do the above:

```
Debugger entered--Lisp error: (wrong-type-argument listp 0)
  #f(compiled-function (it) #<bytecode 0x12b556d>)(0)
  mapcar(#f(compiled-function (it) #<bytecode 0x12b556d>) #f(compiled-function () #<bytecode 0x134c2e1>))
  magit-popup-convert-variables(nil #f(compiled-function () #<bytecode 0x134c2e1>))
  magit-popup-default-setup(nil (:variable magit-branch-arguments :man-page "git-branch" :variables #f(compiled-function () #<bytecode 0x134c2e1>) :actions ((98 "Checkout" magit-checkout) nil (67 "Configure..." magit-branch-config-popup) (108 "Checkout local branch" magit-branch-checkout) (115 "Create new spin-off" magit-branch-spinoff) (109 "Rename" magit-branch-rename) (99 "Checkout new branch" magit-branch-and-checkout) (110 "Create new branch" magit-branch) (120 "Reset" magit-branch-reset) (121 "Checkout pull-request" magit-checkout-pull-request) (89 "Create from pull-request" magit-branch-pull-request) (107 "Delete" magit-branch-delete) (119 "Checkout new worktree" magit-worktree-checkout) (87 "Create new worktree" magit-worktree-branch)) :default-action magit-checkout :max-action-columns 3 :setup-function magit-branch-popup-setup))
  magit-branch-popup-setup(nil (:variable magit-branch-arguments :man-page "git-branch" :variables #f(compiled-function () #<bytecode 0x134c2e1>) :actions ((98 "Checkout" magit-checkout) nil (67 "Configure..." magit-branch-config-popup) (108 "Checkout local branch" magit-branch-checkout) (115 "Create new spin-off" magit-branch-spinoff) (109 "Rename" magit-branch-rename) (99 "Checkout new branch" magit-branch-and-checkout) (110 "Create new branch" magit-branch) (120 "Reset" magit-branch-reset) (121 "Checkout pull-request" magit-checkout-pull-request) (89 "Create from pull-request" magit-branch-pull-request) (107 "Delete" magit-branch-delete) (119 "Checkout new worktree" magit-worktree-checkout) (87 "Create new worktree" magit-worktree-branch)) :default-action magit-checkout :max-action-columns 3 :setup-function magit-branch-popup-setup))
  magit-popup-mode-setup(magit-branch-popup nil)
  magit-invoke-popup(magit-branch-popup nil nil)
  magit-branch-popup(nil)
  funcall-interactively(magit-branch-popup nil)
  call-interactively(magit-branch-popup nil nil)
  command-execute(magit-branch-popup)
```
Funnily enough if I evaluate:

```lisp
(setq magit-popup-use-prefix-argument  'default)
```

then magit works fine again. But if I put it in my emacs init file it does not work. Has to be done after my init files are all loaded. So something must be puting the `'disabled` value to it.

**Comment by tarsius** [comment]
I don't think anything changed that could affect all popups. It sounds like one of the mysterious issues that can be fixed by reinstalling the relevant packages.

> Using a clean emacs magit setup with `emacs-magit-Q-command`

To make the backtrace more useful, remove `magit-popup.elc` before running that again.

> So something must be puting the `'disabled` value to it.

Putting a debug statement before the `cons` in `magit-invoke-popup` might help narrow things down a bit.

**Comment by LefterisJP** [comment]
Hey @tarsius!

So coming back to your input.

> To make the backtrace more useful, remove magit-popup.elc before running that again.

Here you go:

```
Debugger entered--Lisp error: (wrong-type-argument listp 0)
  #f(compiled-function (it) #<bytecode 0x15b20a1>)(0)
  mapcar(#f(compiled-function (it) #<bytecode 0x15b20a1>) #f(compiled-function () #<bytecode 0x16481e1>))
  magit-popup-convert-variables(nil #f(compiled-function () #<bytecode 0x16481e1>))
  magit-popup-default-setup(nil (:variable magit-branch-arguments :man-page "git-branch" :variables #f(compiled-function () #<bytecode 0x16481e1>) :actions ((98 "Checkout" magit-checkout) nil (67 "Configure..." magit-branch-config-popup) (108 "Checkout local branch" magit-branch-checkout) (115 "Create new spin-off" magit-branch-spinoff) (109 "Rename" magit-branch-rename) (99 "Checkout new branch" magit-branch-and-checkout) (110 "Create new branch" magit-branch) (120 "Reset" magit-branch-reset) (121 "Checkout pull-request" magit-checkout-pull-request) (89 "Create from pull-request" magit-branch-pull-request) (107 "Delete" magit-branch-delete) (119 "Checkout new worktree" magit-worktree-checkout) (87 "Create new worktree" magit-worktree-branch)) :default-action magit-checkout :max-action-columns 3 :setup-function magit-branch-popup-setup))
  magit-branch-popup-setup(nil (:variable magit-branch-arguments :man-page "git-branch" :variables #f(compiled-function () #<bytecode 0x16481e1>) :actions ((98 "Checkout" magit-checkout) nil (67 "Configure..." magit-branch-config-popup) (108 "Checkout local branch" magit-branch-checkout) (115 "Create new spin-off" magit-branch-spinoff) (109 "Rename" magit-branch-rename) (99 "Checkout new branch" magit-branch-and-checkout) (110 "Create new branch" magit-branch) (120 "Reset" magit-branch-reset) (121 "Checkout pull-request" magit-checkout-pull-request) (89 "Create from pull-request" magit-branch-pull-request) (107 "Delete" magit-branch-delete) (119 "Checkout new worktree" magit-worktree-checkout) (87 "Create new worktree" magit-worktree-branch)) :default-action magit-checkout :max-action-columns 3 :setup-function magit-branch-popup-setup))
  magit-popup-mode-setup(magit-branch-popup nil)
  magit-invoke-popup(magit-branch-popup nil nil)
  magit-branch-popup(nil)
  funcall-interactively(magit-branch-popup nil)
  call-interactively(magit-branch-popup nil nil)
  command-execute(magit-branch-popup)
```

> Putting a debug statement before the cond in magit-invoke-popup might help narrow things down a bit.

I tried to add this `  (message "popup: %s, mode: %s, arg: %s" popup mode arg)` before the `cond` in `magit-invoke-popup` but it unfortunately did not appear when I ran emacs with `emacs-magit-Q-command`.

When I did a `load-file` for `magit-popup.el` inside a normal install of emacs to also incoroporate the debugging message all actually worked fine, got both the debugging message

> popup: magit-branch-popup, mode: nil, arg: nil

 and the popup also worked as expected. So I am now really confused.

**Comment by tarsius** [comment]
Sounds like you might have two versions of `magit` and/or `magit-popup` installed.

**Comment by tarsius** [comment]
Any news on this? Can I close?

**Comment by LefterisJP** [comment]
Hey Tarsius sorry for the late reply. No it's not fixed yet. I only experience this on my laptop and I did check if I have two versions installed, but that is not the case. Any tips on how to debug this?

**Comment by tarsius** [comment]
Remove all `*.elc` files.

> I tried to add this `  (message "popup: %s, mode: %s, arg: %s" popup mode arg)` before the `cond` in `magit-invoke-popup` but it unfortunately did not appear when I ran emacs with `emacs-magit-Q-command`.

That cannot happen except if the modified version of that function isn't actually the version that gets called. As mentioned earlier that might be because there is an other installation laying around. If it is not that, then the reason probably is that an outdated `*.elc` gets loaded instead of the modified `*.el`. That's always never what you want, so you should set `load-prefer-newer' to t. You might also want to check out my [`auto-compile`](https://github.com/emacscollective/auto-compile).

**Comment by tarsius** [comment]
I don't know what is going on but I am pretty sure it's some local issue.

**Comment by LefterisJP** [comment]
Probably. I have not had more time to look at it. I will come back here if there is more trouble that indicates something non-local.
