### ISSUE TITLE
UTF log

### ISSUE THREAD

**Issue by Pitometsu** [magit/magit#3489]
Can git log be nicer by using utf symbols?

**Comment by tarsius** [comment]
Yes, and a long time ago that was actually supported. But the feature broke during refactoring and nobody noticed for half a year or so and when I finally noticed during futher refactoring I nuked it to make that easier.

That basically just replaced the ascii graph characters with slightly better looking characters. I do not plan to do that again. But I plan to improve graphs even more and that will also involve using nicer characters. See #2989.
