### ISSUE TITLE
TRAMP-specific configuration

### ISSUE THREAD

**Issue by cg505** [magit/magit#3493]
I add `"--gpg-sign=XXXXX"` to my `magit-commit-arguments` so that my commits are always signed with my GPG key. If I am connected via TRAMP to a machine that doesn't have my private key (which is all of them), this will make committing fail unless I manually disable that argument before hitting `c` the second time. It would be good to have a way to specify configuration options that should only apply for repositories that are local (or vice versa).

This might be possible through TRAMP itself, but I know of no way to do that. Right now I am using dir-locals but this has several disadvantages: you must have `enable-remote-dir-locals` on (which incurs a performance penalty), and you must add a .dir-locals.el file for each repository on each machine you connect to. I obviously am open to alternatives that don't require adding things to magit, but I wasn't able to find anything decent.

I am pretty busy right now personally, but if pointed in the right direction, I might be able to do some work on implementing this (which I would enjoy).

**Comment by npostavs** [comment]
> This might be possible through TRAMP itself, but I know of no way to do that.

This might be relevant:
```
* Changes in Emacs 26.1

** Connection-local variables can be used to specify local variables
with a value depending on the connected remote server.  For details,
see the node "(elisp) Connection Local Variables" in the ELisp manual.
```

> Right now I am using dir-locals but this has several disadvantages: you must have `enable-remote-dir-locals` on (which incurs a performance penalty), and you must add a .dir-locals.el file for each repository on each machine you connect to.

Couldn't you instead use .dir-locals.el only for local repos?

**Comment by cg505** [comment]
>** Connection-local variables can be used to specify local variables
>with a value depending on the connected remote server.

This sounds like exactly what I want! I hadn't spotted this in the release notes. I am checking this out and this may entirely resolve the issue. I am having a little difficulty getting it to work initially, partially because some of the documentation seems a little inconsistent. I'll see if I can get it working.

>Couldn't you instead use .dir-locals.el only for local repos?

This might be better in that it gets rid of the performance hit, but it is worse in that I have one or two orders of magnitude more local repositories than remote ones. I then need to make sure they all have a .dir-locals.el somewhere in their filesystem ancestry, at which point I might as well just put it in /.dir-locals.el. This seems a little ridiculous.

**Comment by cg505** [comment]
It seems like connection-local variables don't actually work like they're supposed to. From the help for `connection-local-criteria-alist`:

>Property names might be ‘:application’, ‘:protocol’, ‘:user’ and ‘:machine’.  The property value of  ':application’ is a symbol, all other property values are strings.  All properties are optional; if CRITERIA is nil, it always applies.

As far as I can tell, the last sentence is just a lie. It seems that none of the properties are optional (except for `:application`, for whatever reason). So having to specify the protocol, user, and machine kind of defeats any sort of generality I was hoping for. This looks like a problem with Emacs itself, and unless someone can point out some silly mistake I'm making, we can close this and I'll file a bug with Emacs.

**Comment by tarsius** [comment]
Can I close this? It doesn't seem like Magit is to blame here. You will likely have to talk to the Emacs maintainers.

**Comment by cg505** [comment]
I opened an upstream bug: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=32090
