### ISSUE TITLE
Render problem on octopus merge.

### ISSUE THREAD

**Issue by huseyinyilmaz** [magit/magit#3494]
When I do an octopus merge (When I merge multiple brances in one merge command like `git merge a b c d`) that particular merge does not get rendered correctly.

https://cl.ly/080b220Q3m20 

I created a new repository and try to reproduce the issue, but in this particular repository I cannot reproduce it. 

  https://github.com/huseyinyilmaz/magit-bug-showcase/network
  
  In short I could not find the actual reason for the bug. But I still wanted to report it to make the issue known to devs.

Thanks.
my emacs version:
  Magit 20180620.1224, Git 2.15.2 (Apple Git-101.1), Emacs 26.1, darwin

**Comment by vermiculus** [comment]
Copying image inline for posterity
![image](https://user-images.githubusercontent.com/2082195/41800054-7ea3b200-7639-11e8-94d5-0b36c8902cb7.png)

**Comment by npostavs** [comment]
I think this might be a git bug that I ran into a long time ago, I have a possible patch sitting on my hard drive. I haven't made so many octopus merges of the right shape to trigger it recently, so I kind of forgot about it.

https://marc.info/?l=git&m=146331754420554&w=2

**Comment by tarsius** [comment]
Closing this because it is a bug in Git that we cannot do anything about (except trying to get it fixed there).

**Comment by npostavs** [comment]
This was fixed in git 2.19.2.

- https://github.com/git/git/blob/v2.19.2/Documentation/RelNotes/2.19.2.txt#L69
- git/git@04005834ed07e0b3a63793f386570c8bcf73f9a3
