### ISSUE TITLE
Consider providing hooks for commiting & staging

### ISSUE THREAD

**Issue by Alexander-Miller** [magit/magit#3496]
Hello there,

I maintain [treemacs](https://github.com/Alexander-Miller/treemacs), and I could use some help in making it and magit (pardon the buzzword) synergize together.

One of the features of treemacs is its `filewatch-mode`, a minor mode that allows treemacs to automatically refresh its view when it detects file system changes in the projects it is displaying. Another is `git-mode` which will fontify files and directories based on their git status. It's obvious how the two work together: you edit or create an untracked file and treemacs displays it in the appropriate color all on its own.

There's just one gap - git commands that don't create, delete or change files in the underlying file system. Making commits and staging untracked files are two actions that I can think of that treemacs cannot detect on its own and it is always slightly inconvenient to have to make that refresh yourself.

I've no solution on how to handle this in general, including the bare command line (I assume you know a bit more about these things) so hooking into magit is the obvious choice. I've also tried watching the .git directory itself for changes, but all that seems to get me is dozens of create/delete events for index.lock for *every* git command, including those I start myself, without really knowing what's actually happening.

So here's the details of I would need: Hooks for staging & committing and other git commands that would fit into the change git state, but not the file system category. They should run after the git command is finished so treemacs can successfully pick up the changes. Ideally the hooks would be called with an exact list of files that were staged or committed, but if that kind of information is not readily available just the git repo root is fine, too.

If you're okay with the proposal I can take a stab at making the changes myself, but I'll probably need some help with the details.

**Comment by vermiculus** [comment]
One idea: you could advise the core magit process communication commands (`magit-git.el`) to give you a notification. `magit-top-dir` (IIRC) is your repository root.

Something I've seen people do in the past is to just open a PR with some proposed changes and use that for discussion/iteration.

**Comment by Alexander-Miller** [comment]
Maybe it's just me, but I think advising is a workaround when the "proper" interface is not available, and I'd rather have the proper interface.

I am also not sure if my ideas are the right way to go about this - there's still the gap of directly using the command line, and the people maintaining magit certainly know more about git than I do - so I'd like to do some talking before I start implementing.

**Comment by vermiculus** [comment]
If you want a proper interface that'll work for all users of git, your best bet is a git-hook. `pre-commit-hook` exists, but I can't find anything for staging. You could feasibly populate a .git/ file with a list of affected project files.

Creating something for staging would involve git development.

**Comment by tarsius** [comment]
https://github.com/magit/magit/wiki/magit-update-uncommitted-buffer-hook contains some code that should get you started, and links to past discussions about alternative approaches and performance issues.

I plan to improve Magit's own refreshing mechanism in a way that would allow other packages to query the current state, but it will be at least another month until I get to that.

**Comment by Alexander-Miller** [comment]
> Creating something for staging would involve git development.

All that stuff is overkill. I'm looking for something elisp-based, without requiring special setup. Sane defaults and all that.

> and performance issues.

Performance should not be a problem. I don't need to visit any buffers or run any other heavy actions. The plan is to generate an event for the same callback mechanism that I already use via `file-notify-add-watch`. All that does is set a flag in what you would call treemacs' dom. An actual redraw only happens 5 seconds later, so the system is able to gather many consecutive events, like the outputs of a compilation process.

> I plan to improve Magit's own refreshing mechanism in a way that would allow other packages to query the current state

Unless that also includes a reason why it's refreshing I'll need to push on here. `magit-refresh` is called much more often than I would need and most of the time treemacs knows about the changes anyway.

I've taken a first look around the codebase now, and while a general hook for (un)staging looks doable for me, committing is a serious challenge. The actual commit happens asynchronously in `with-editor` and outside of changing with-editor to accept some code to run on finish I see no good way to make it work. I tried playing around with let-binding with-editor-post-finish hook so as to inject my own hook into it, but it didn't work.

I'll start properly building a stage hook now, but for commits I'd appreciate some feedback on how to properly architect my intended changes.

**Comment by tarsius** [comment]
`with-editor-post-finish-hook` is run once `git commit` has done its thing.

**Comment by Alexander-Miller** [comment]
True, I've been overthinking this. That's the hook I wanted to let bind. Aside from magit there's 5 other packages depending on with-editor, so it won't be always used for committing, but I assume a call to `magit-toplevel` should be well enough to make sure that at least a git repository is around.

**Comment by tarsius** [comment]
I have added such hooks in #3615.

**Comment by dakra** [comment]
I just want to note someone has to be careful with the commit-post-finish-hook
if you want the last commit.

The git process might not have finished yet when the hook is run.
E.g. I have [this in my config](https://github.com/dakra/dmacs/blob/master/init.org#orgit-org-link-support-for-magit-buffers) which sleeps for an extra 0.5s and with large repos
I still get sometimes the commit hash from before copied.

Just an FYI, don't think there's anything that could be done really.

**Comment by tarsius** [comment]
Something like f2c67ed2e4477c0bf24ba62ae0a5fb7f867ce9bc should help. (I have not tested this *at all* yet.)

**Comment by dakra** [comment]
> Something like f2c67ed should help. (I have not tested this at all yet.)

Nice, thanks. I'm running that branch right now and changed my commit hook to a much simpler version:

```emacs-lisp
(use-package orgit
  ;; Automatically copy orgit link to last commit after commit
  :hook (git-commit-post-finish . orgit-store-after-commit)
  :config
  (defun orgit-store-after-commit ()
    "Store orgit-link for latest commit after commit message editor is finished."
    (let* ((repo (abbreviate-file-name default-directory))
           (rev (magit-git-string "rev-parse" "HEAD"))
           (link (format "orgit-rev:%s::%s" repo rev))
           (summary (substring-no-properties (magit-format-rev-summary rev)))
           (desc (format "%s (%s)" summary repo)))
      (push (list link desc) org-stored-links))))
```

The first few test commits all worked and I got the correct
orgit link copied. I'll report back if I find problems.

**Comment by tarsius** [comment]
Unfortunately it turned out things are much more complicated than this. See the TODO commit on `sit-for-commit`.

**Comment by dakra** [comment]
Bummer.
Is it possible to setup the post-finish-hook locally inside the pre-finish-hook? Then you could pass the commit hash as a closure.. (if that makes sense?)

**Comment by Alexander-Miller** [comment]
Thanks for the delivery. I've gotten around to trying things now, and it looks like the `magit-post-commit-hook` is not run when calling (at least) `magit-commit-extend`. Debugging shows `this-command` to be nil, so https://github.com/magit/magit/pull/3615/files#diff-fb1b027f835b584b4339a07e97a27caeR1021 never matches. I take it this is not intended the behaviour?

This is using emacs 26.1 and the most recent magit master.

**Comment by tarsius** [comment]
@Alexander-Miller 2059e8d37521533ddca832f848ef358de1b01430 should fix that.

**Comment by tarsius** [comment]
> Is it possible to setup the post-finish-hook locally inside the pre-finish-hook? Then you could pass the commit hash as a closure.. (if that makes sense?)

Something like that is possible, but there is more hardcoding involved than I would have liked. Anyway `git-commit-post-finish-hook` should be safer now. It is only run after a new commit has been created. It isn't guaranteed to run though. If no new hook has appeared after one second, then it is not run. It also isn't run when we know that doing so would lead to a race condition (https://github.com/magit/magit/issues/3646#issuecomment-435021442).
