### ISSUE TITLE
let: Args out of range: #<killed buffer>, -1, 0

### ISSUE THREAD

**Issue by DamienCassou** [magit/magit#3497]
Please explain
  (1) what behavior you expected: `magit-status` should open fine
  (2) what behavior you observed: if [latest beacon](https://github.com/Malabarba/beacon) is loaded, `magit-status` in particular and all functions calling `format-spec` in general will trigger an `Args out of range` error
  (3) and how we can reproduce the issue: load latest beacon

There is nothing Magit can do about it. I thought an issue in Magit tracker would still help Magit users as Magit uses `format-spec` quite a lot. 

I reported the issue on beacon's issue tracker: https://github.com/Malabarba/beacon/issues/60

**Comment by tarsius** [comment]
Seems to be fixed upstream already. Thanks for the note.
