### ISSUE TITLE
Add "delete" command to magit-file-popup

### ISSUE THREAD

**Issue by mikecrowe** [magit/magit#3498]
I've searched the documentation and it appears that there's no way to stage deletion of a file from within Magit. https://emacs.stackexchange.com/questions/24030/git-rm-from-magit suggests that a feature request should be opened, but I couldn't find one, so this is one.

IMO magit-file-popup would be a good place to add an option to add a delete command, perhaps bound to "K".

**Comment by kyleam** [comment]
> I've searched the documentation and it appears that there's no way to stage deletion of a file from within Magit.

`magit-file-delete` runs `git rm`.  It was added in f6a6f40f (magit-file-{rename,untrack,delete}: new commands, 2015-03-02)

**Comment by tarsius** [comment]
These commands are now documented in the manual: https://magit.vc/manual/magit/Minor-Mode-for-Buffers-Visiting-Files.html. I have also added the same note about adding them to the file popup to [the wiki](https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands#magit-file-popup).

**Comment by mikecrowe** [comment]
Thanks for updating the documentation.

I've added magit-file-delete and it appears to work perfectly. (I think that having it on the popup by default would aid discoverability, but I'm happy with adding it myself.)
