### ISSUE TITLE
Interactive rebase buffer won't validate, saying it's Read Only

### ISSUE THREAD

**Issue by milouse** [magit/magit#3500]
## what behavior you expected

After having finished to deal with the various commits in the git-rebase-todo buffer, choosing between edit, fixup, …, I enter `C-c C-c` to validate my choice and start rebasing.

## what behavior you observed

The buffer hangs and the following message appears in the minibuffer prompt: 

```
run-hook-with-args-until-success: Buffer is read-only: #<buffer git-rebase-todo>
```

## how we can reproduce the issue

Open any git repository log in Magit `l l`, choose a commit, enter `r i`, modify the commit list with the possible keystrokes and validate with `C-c C-c`

## Magit version

Magit 20180620.1224, Git 2.18.0, Emacs 26.1, gnu/linux

## Good to know

I have two git hooks enabled, which works normally on commit messages: `commit-msg` and `prepare-commit-msg`. As the error messages speaks about hooks, can the problem comes from a misconfigured hooks? Which git hooks are run after submitting the rebase buffer?

The only workaround I found for now is to manually switch off the buffer from read-only-mode and enter `C-c C-c` again. It always works the second time.

The problem is very recent (a week at max), but I can't remember since when exactly it begins, between the emacs upgrade (to 26.1) or magit upgrade (through melpa). It works without any trouble before.

**Comment by milouse** [comment]
The problem occurs without the custom hooks. I cannot use `C-c C-k` too: I'm obliged to switch off manually the read-only-mode before even canceling the rebase.

**Comment by tarsius** [comment]
The problem seems to lay with your configuration or another package. In both cases the issue could be completely unrelated to Magit.

To find out what triggers the issue do a binary search on your init file, possibly using [`elisp-bug-hunter
`](http://irreal.org/blog/?p=3827).

**Comment by hlissner** [comment]
I've struggled with this issue for the past week or so as well, but have isolated it to the `editorconfig` plugin adding `delete-trailing-whitespace` to a buffer-local `write-file-functions` in the git-rebase-mode buffer (if you've got a trim_trailing_whitespace directive in your editorconfig file). 

It tries to modify the buffer, throwing that read-only error and stopping the abort/commit in its tracks. So, for me at least, this wasn't a magit issue.

@milouse if you don't use editorconfig, perhaps you've added `delete-trailing-whitespace` or another destructive hook to `write-file-functions`?

**Comment by milouse** [comment]
Wow, nice catch @hlissner ! I can confirm the problem occurs only on editorconfig-enabled projects (most of my git repos), and I always have this rule enabled.

I'll close this issue as it has nothing to do with magit (I suspect that, but as the problem only occurs in magit, my issue was just an help call). Thank you very much!

**Comment by mathpunk** [comment]
I have done nothing to my configuration in the last hour, and this behavior started popping up. I believe it has something to do with having followed a direction from git to run `rm -rf  ~/MYPROJECT/.git/rebase-merge/` after something went wonky with a rebase-todo. I can't seem to run a rebase from either emacs or the command line. What do I do?

**Comment by mathpunk** [comment]
I tried restarting my machine. Now when I try and continue or abort a rebase, I get `git-rebase-todo has changed since last visted or saved. Save anyway?` What in the fresh hell is going on?

**Comment by mathpunk** [comment]
Also if I run any command while in the `.git` directory (which I'm visiting because, what even is happening) I get `fatal: this operation must be run in a work tree`.

**Comment by mathpunk** [comment]
(Apologies for live-flipping-out on this thread, I was going about doing some work that was challenging enough and now my tools are fighting me.)

There has to be some hidden state happening that I don't know how to find or clear. Having aborted a rebase and starting another one, I'm getting asked if I want to revert to the buffer at `rm -rf ~/MYPROJECT/.git/rebase-merge/git-rebase-todo`. I'm going to try moving magit into a different state and deleting that again. I'm trying things at random here, if anyone can explain what is going on that would be tops.

**Comment by mathpunk** [comment]
Oh, and my `magit-process` buffer currently looks like 

```
run git … rebase -i f5e4abd56\^
Waiting for Emacs...
  0 git … rebase --abort
run git … rebase -i 99173ebe0\^
Waiting for Emacs...
  0 git … rebase --abort
run git … rebase -i 99173ebe0\^
Waiting for Emacs...
  0 git … rebase --abort
  1 git … rebase -i 99173ebe0\^
Waiting for Emacs...
*ERROR*: Quit
Could not execute editor

  1 git … rebase -i 99173ebe0\^
Waiting for Emacs...
*ERROR*: Buffer is read-only: #<buffer git-rebase-todo>
Could not execute editor

  1 git … rebase -i 99173ebe0\^
Waiting for Emacs...
*ERROR*: Buffer is read-only: #<buffer git-rebase-todo>
Could not execute editor
```

but honestly, I don't know what it's *supposed* to look like so this isn't telling me much.

**Comment by mathpunk** [comment]
I finally saw through my panic enough to read this:

> The only workaround I found for now is to manually switch off the buffer from read-only-mode and enter C-c C-c again.

and this workaround *is* solving my immediate, critical problem. But I could still use help understanding what could possibly have started causing this. Again, I didn't do anything to my emacs configuration before this started.

**Comment by npostavs** [comment]
Do you have an open buffer visiting `~/MYPROJECT/.git/rebase-merge/git-rebase-todo`? If you also use desktop mode, that state would be preserved over a reboot.

**Comment by tarsius** [comment]
I think you started a rebase and got the error about the buffer being read-only. Then you tried to fix that by deleting the files were git (and magit) keep state. This fixes things as far as git is concerned, but then you initiated another rebase in magit - at this point Emacs is still visiting the file and things go downhill from there.

So if things go so bad during a rebase that you have to resort to deleting the state directory, then you have to exit Emacs first (or at least manually kill the buffer visiting `git-rebase-todo` (I *think* that should be enough)), before deleting the state directory.

**Comment by milouse** [comment]
Hum, you should NEVER `rm -rf` anything under the `.git` folder. All these files and folders are (for the most part) automatically generated, and modifying them directly is an absolute NO GO.

Sometimes, when things become weird in magit or even in console, git has a special --abort option for most its command, which will rollback what you are doing, even in the most complex situation. Thus when something goes wrong, just do a `git [command] --abort` and try again after having looking for a solution to your problem. Like `git merge --abort`, `git rebase --abort`… I often find myself obliged to abort a rebase, when I f**k up my working copy. Even after one or more intermediary commits. 

`git status` in a terminal will always inform you if you are always running a special command (rebase or merge not finished) or if everything is fine.

Last, this is totally normal to not been able to enter git command inside the `.git` folder. Again, the `.git` folder is reserved to the normal operation of git and you should NEVER visit it.

I hope you finally found the origin of your problem. Surely you commit something or begin another rebase while a merge or a previous rebase was not finished. Be sure to always check and check again  the output of `git status` before beginning sensitive operations.

**Comment by mathpunk** [comment]
I've been more careful to exit out of emacs entirely when manipulating git state lately. For instance, I had to delete an index.lock, and that fixed the issue I was having. I still have to move every rebase buffer out of read-only mode, however. Does anyone know what state I need to clear in order to fix that problem? It's not blocking my work but it sure is irritating.

**Comment by tarsius** [comment]
This is not something that happens due to git state. A likely cause is that some other package for some reason enables read-only mode in this buffer, either due to a bug or due to a misconfiguration on you part. Someone else cannot know what is it, you will have to figure out what part of you configuration is causing it yourself. I can only [suggest](https://github.com/magit/magit/issues/3500#issuecomment-401512056) that you do a binary search on your configuration.

**Comment by mathpunk** [comment]
I don't think that's possible --- I made no configuration changes before this behavior started happening. The only thing out of the ordinary was me, foolishly it turns out, following the git-cli client's direction to delete `~/MYPROJECT/.git/rebase-merge/`.

**Comment by tarsius** [comment]
Well in that case, try in another repository that you know not to be in some wonky state.

**Comment by mathpunk** [comment]
That was a great suggestion @tarsius. Now I can confirm, it really is something to do with the repo and not my configuration. But what could it be :thinking:

**Comment by tarsius** [comment]
File permissions?
