### ISSUE TITLE
Expanding modified files doesn't show content properly

### ISSUE THREAD

**Issue by nayefc** [magit/magit#3504]
This has been happening to me over a long period of time, on different computers on Emacs 25.x and now also in Emacs 26.1.

In magit, when I see a list of all files collapsed, and try to expand a file changes by pressing tab, on it many times it doesn't expand properly. Usually, it shows half of the content of the file above content instead of the current file's content.

Is this a known issue?

**Comment by tarsius** [comment]
Nope, first time I hear about something like that. Are their any weird characters in your files? Can you reproduce with `emacs -Q`?

**Comment by nayefc** [comment]
No weird characters.

When I try to run it with -Q, I can never seem to get `magit-status`. I see a bunch of `magit-popup-` and a few other commands available only.

I ran (where N is the version) from the melpa magit directory:
```
emacs -Q --debug-init --eval '(setq debug-on-error t)' -L ../dash-N -L ../git-commit-N -L ../magit-popup-N -L ../with-editor-N -L ../ghub-N -L . -l magit
```

**Comment by tarsius** [comment]
> When I try to run it with -Q, I can never seem to get `magit-status`.

Are you saying you cannot invoke `magit-status`? That might be because your usual key binding is not available when not using your configuration. Try `M-x magit-status RET`.

**Comment by tarsius** [comment]
Did you follow the instructions at https://magit.vc/manual/magit/Debugging-Tools.html?

**Comment by bittopaz** [comment]
@nayefc Hi, do you still have the problem? I think I am having the same symptom as you did.

**Comment by nayefc** [comment]
I am, on multiple machines. Been having it for a long time now its really annoying.

**Comment by smcallis** [comment]
I was having this problem too.  For future travellers: my issue was that I had fci-mode enabled semi-globally, and I think it was interfering with the section selection.  Not the first time it's caused me problems, so I've turned it off.

**Comment by tarsius** [comment]
Since Emacs 27.1 there's `display-fill-column-indicator`, which works much better than `fci-mode`.

**Comment by smcallis** [comment]
I think I've heard of that.  I'm almost all ported over to 27 so I'll have
to start using that.
