### ISSUE TITLE
(void-function magit-insert-head-header)  error

### ISSUE THREAD

**Issue by srustamo** [magit/magit#3508]
(1) what behavior you expected
Running `magit-status` is expected to show the repo status
  (2) what behavior you observed
Error (void-function magit-insert-head-header)
  (3) and how we can reproduce the issue.
Run `magit-status` on any git repo

output of M-x magit-version RET
Magit 20180630.1235, Git 2.17.1, Emacs 26.1, darwin

Partial backtrace (last lines):
```
Debugger entered--Lisp error: (void-function magit-insert-head-header)
  magit-insert-head-header()
  funcall(magit-insert-head-header)
  mapc(funcall (magit-insert-remote-header magit-insert-head-header magit-insert-tags-header))
  magit-insert-remaining-headers()
  run-hooks(magit-insert-section-hook)
  magit-insert-repo-header()
  magit-insert-headers((magit-insert-repo-header magit-insert-remote-header magit-insert-head-header magit-insert-tags-header))
  magit-insert-status-headers()
  run-hooks(magit-status-sections-hook)
  magit-run-section-hook(magit-status-sections-hook)
  magit-status-refresh-buffer()
  apply(magit-status-refresh-buffer nil)
  magit-refresh-buffer()
  ```

**Comment by kyleam** [comment]
That function has been obsolete since Magit 2.4.0 and was removed completely following 2.13.0 (there are no occurrences of `magit-insert-head-header` in master).  Make sure you don't have stale elc files hanging around, and maybe do the install/uninstall routine.

**Comment by npostavs** [comment]
Also check the custom variable block in your init file, it may have a setting with the obsolete function.

**Comment by srustamo** [comment]
Indeed, this was a local issue. Many thanks.
