### ISSUE TITLE
git rm merge

### ISSUE THREAD

**Issue by Pitometsu** [magit/magit#3510]
```
Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)
```
No options to resolve it via magit for now, error notification only.

**Comment by kyleam** [comment]
The file should show up as something like

```
Staged changes (1)
unmerged   foo (deleted by us)
```

in the status buffer.

Move point there and hit <kbd>k</kbd>, which will let you choose "ours"  (`git rm` for my example) or "theirs" (`git add`).

**Comment by kyleam** [comment]
Duplicate of #2466.
