### ISSUE TITLE
Option to filter log by branches pattern

### ISSUE THREAD

**Issue by bradyt** [magit/magit#3511]
In command line git, I can do

```
git log --oneline --graph --author-date-order --branches=scratch --simplify-by-decoration
```

This way, I can start to make sense of the mess I've made with various scratch branches `scratch/strings`, `scratch/strings2`, etc, and various rebasing of similar commits. (Next step is I would remove `--simplify-by-decoration`.)

I don't see a way to pass a pattern to `--branches` in magit log buffer. Please enable?

I guess this would be on some `=b`. Perhaps there are too many of this similar type, such as `--tags`, `--remotes`, `--glob`, `--exclude`, so maybe there is some way to allow user to easily configure the popup menu with these, and magit is able to parse the output?

**Comment by tarsius** [comment]
Yes, for now I don't want to add all arguments to a popup that could possibly be added. See https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands.

**Comment by bradyt** [comment]
Ah, thank you for getting me in right direction, that was incredibly easy. How awesome!

``` emacs lisp
(magit-define-popup-option 'magit-log-popup
  ?b "Limit branches" "--branches=")
```

**Comment by bradyt** [comment]
Works well with the following.

``` emacs lisp
(magit-define-popup-option 'magit-log-popup
  ?b "Limit branches" "--branches=")
```

Then for example `l = b *strings* RET l`.

**Comment by kuanyui** [comment]
> Yes, for now I don't want to add all arguments to a popup that could possibly be added. See https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands.

This link becomes invalid. Is there any way to do this on latest magit? And `magit-define-popup-option` is not found.

Struggle to read manual of magit  but found nothing... https://magit.vc/manual/magit.html#Transient-Arguments-and-Buffer-Variables

Also dig into the source code of `magit-log.el`, but don't know how to add more options to the transient menu of `M-x magit-log`

**Comment by kyleam** [comment]
@kuanyui 
> This link becomes invalid. Is there any way to do this on latest magit? And `magit-define-popup-option` is not found.

See https://github.com/magit/magit/wiki/Converting-popup-modifications-to-transient-modifications
