### ISSUE TITLE
A magit version of diff-add-change-log-entries-other-window?

### ISSUE THREAD

**Issue by cpitclaudel** [magit/magit#3513]
Hi there,

Thanks for the work on magit.

This is a follow-up to a recent thread on the emacs-devel mailing list (see https://lists.gnu.org/archive/html/emacs-devel/2018-07/msg00438.html for context).  The standard diff-mode provides a command `diff-add-change-log-entries-other-window`, which takes a diff and automatically creates a collection of changelog entries from the diff:

```
C-x 4 A runs the command diff-add-change-log-entries-other-window (found in
diff-mode-map), which is an interactive compiled Lisp function in
‘diff-mode.el’.

It is bound to <menu-bar> <Diff> <Create Change Log entries>, C-x 4 A.

(diff-add-change-log-entries-other-window)

Iterate through the current diff and create ChangeLog entries.
I.e. like ‘add-change-log-entry-other-window’ but applied to all hunks.
```

Magit already has support for C-x 4 a, which creates a single entry, but not C-x 4 A, which would create all entries from a diff.

Additionally, even wile editing a commit, C-x 4 a in a Magit diff places new change log entries in a new ChangeLog buffer.  It might be nice to write them to the current commit-message buffer instead.

This would make writing changelog entries for Emacs commits very smooth: just press C-x 4 A in the magit diff that pops up when you commit changes, and add individual descriptions of the changes.

Thanks!

**Comment by tarsius** [comment]
It should be possible to copy and modify that function to create a variant suitable for Magit, but I would rather wait to see how the Emacs developers respond to my suggestions in #2931 and *link pending* my summary on `emacs-devel`.
