### ISSUE TITLE
Optional date headers in log buffers?

### ISSUE THREAD

**Issue by alphapapa** [magit/magit#3514]
Looking at [this screenshot](http://mutabit.com/grafoscopio/images/timeline-2.png), I thought it would be nice if Magit log buffers could optionally display date headers between entries like that.  Would a PR implementing this be accepted?

**Comment by tarsius** [comment]
Are you aware that Magit can display author dates (and names) in the margin? That's not as pretty, but still.

**Comment by alphapapa** [comment]
Here's an example:
![headings](https://user-images.githubusercontent.com/601365/42721164-6563ebca-86fb-11e8-9f4f-13745f3b1d45.png)

**Comment by tarsius** [comment]
Well this looks nice, but I think that for now this should remain an advice. As you surely have noticed the functions used to wash logs are a huge mess already, and I don't want to add any new features until after cleaning that up.

**Comment by alphapapa** [comment]
I understand.  I'll post it on Reddit or something.

Should this be closed or left open as a "someday maybe we can have this feature built-in" issue?

**Comment by tarsius** [comment]
I have closed and added my secret "look at this later again" label.
