### ISSUE TITLE
GIT_DIR=.git breaks git-commit-mode when magit is installed from cloning

### ISSUE THREAD

**Issue by hlian** [magit/magit#3516]
Hi! Long time user of this package, big fan. My magit-version is `"2.13.0-87-g9b94"`, I'm on macOS 10.13.5. I can reproduce this bug on git 2.16.2. Here are the steps:

- First, install Magit not through `package.el` but through git cloning. I recently switched to straight.el for package management; straight.el clones git repositories rather than using `package.el` and this was the thing that kicked off my discovery of this bug. However, this bug isn't specific to straight.el; I believe anybody who's cloned Magit can hit this. Here's the relevant init.el snippet:

```lisp
(setq-default magit-git-debug t)
;; Only necessary if you want to use straight. But you should also be able
;; to reproduce by git cloning and putting the directory onto the load path.
; (straight-use-package 'magit)
; (straight-use-package 'git-commit)
(require 'magit)
(require 'git-commit)
```

- Set `core.editor` to be Emacs. On macOS, this is something like `git config core.editor '/Applications/Emacs.app/Contents/MacOS/Emacs -nw`.

- Start a git commit in any git repository. `git commit --amend`, for example, will kick it off.

- Expected: git-commit-mode loads, everything looks great

- Actual: a partial load of git-commit-mode occurs. This error appears in `*Messages*`:

```
Not a git repository: '.git'
Cannot determine Magit’s version (error "/Users/h/.emacs.d/straight/repos/magit/lisp/magit.el" repo t static elpa debug)
For information about GNU Emacs and the GNU system, type C-h C-a.
Not a git repository: '.git' [4 times]
file-remote-p: Wrong type argument: stringp, nil
```

## Here's what's happening

- `/usr/local/bin/git` forks Emacs. It sets `GIT_DIR=.git` because that's the default git behavior.

- `magit-version` runs.

- It tries to shell `git describe --tags --dirty`. That's [this line](https://github.com/magit/magit/blob/34af78a98749cf2cdfba306096a764093e408089/lisp/magit.el#L450) in `magit.el`. **That code path executes because Magit was cloned**; if Magit is installed from `package.el` **nothing bad happens**.

- If you installed magit into `/path/to/magit/`, the `default-directory` dynamic elisp variable will be set to `/path/to/magit/lisp`. That's because it's set from `toplib`, which is [defined here](https://github.com/magit/magit/blob/34af78a98749cf2cdfba306096a764093e408089/lisp/magit.el#L425).

- `git describe --tags --dirty`, running with `default-directory` set to `/path/to/magit/lisp`, will shell with `GIT_DIR=.git` inherited. But `/path/to/magit/lisp/.git` does not exist! `/path/to/magit/.git` exists, but `/path/to/magit/lisp/.git` does not. (I believe this is how GIT_DIR resolves when GIT_DIR is a relative path, but I'm not too confident.)

- `git` returns with exit code 128. `magit-version` returns nil.

## Does it affect more than magit-version?

Yes! magit-version has a try-catch around it so you don't even really notice that breakage at first. If you add `(setq debug-on-error t)` to your init.el, you notice that the first break is here:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  find-file-name-handler(nil file-remote-p)
  file-remote-p(nil)
  hack-dir-local-variables()
  (let ((buffer-file-name nil) (major-mode 'git-commit-mode)) (hack-dir-local-variables) (hack-local-variables-apply))
  (let ((default-directory (if (file-exists-p ".dir-locals.el") default-directory (magit-toplevel)))) (let ((buffer-file-name nil) (major-mode 'git-commit-mode)) (hack-dir-local-variables) (hack-local-variables-apply)))
  git-commit-setup()
  (and buffer-file-name (string-match-p git-commit-filename-regexp buffer-file-name) (git-commit-setup))
  git-commit-setup-check-buffer()
  run-hooks(find-file-hook)
  after-find-file(nil t)
[snip]
```

That's because `magit-toplevel` is running into the same problem (it tries to shell `git rev-parse --show-toplevel`, but again GIT_DIR=.git makes git error out with 128).

## Workaround

Create an executable shell script:

```sh
#!/usr/bin/env zsh
unset GIT_DIR
/Applications/Emacs.app/Contents/MacOS/Emacs -nw $@
```

Set this script to be your `git config core.editor`. This unbreaks `magit-version` and `magit-toplevel`. git-commit-mode should now load perfectly when you go to make a commit.

## Anyways

I hope this bug report makes sense. I don't know what the fix should be; maybe magit should be deleting the GIT_DIR key before it shells out. Or maybe `default-directory` should be set correctly so that `GIT_DIR=.git` resolves to the correct path. But, again, not a contributor so I don't really have the expertise.

**Comment by tarsius** [comment]
> `/usr/local/bin/git` forks Emacs. It sets `GIT_DIR=.git` because that's the default git behavior.

That's kinda stupid. Well maybe its the right thing to do when invoking a less flexible editor (though I don't see what is to be gain by doing that). When the editor is Emacs or any editor whose users usually do not lauch a new instance per file (or at least "project"), it is a recipe for disaster. New buffers inherit all environment variables even if they concern a completely different project.

But it appears to be true. In my case it is an absolute path because I use a detached `GIT_DIR`.

I think the solution here is for Magit to detect -- at load time -- when `GIT_DIR` is set and then unset it.

**Comment by tarsius** [comment]
Please try the `fix-3516` branch.

**Comment by hlian** [comment]
The patch worked! Thanks a lot!

By the way, it looks like git 2.18 binary from Homebrew does NOT have this problem. It forks core.editor without setting GIT_DIR. I tested this out on 2.16 (also the Homebrew binary) but not 2.18 when I reported. The commands are

```sh
$ cat /tmp/a.sh
#!/usr/bin/env sh
env | grep GIT_DIR
$ chmod +x /tmp/a.sh
$ git config core.editor /tmp/a.sh

$ homebrew switch git 2.16.2
$ git commit --amend
$ homebrew switch git 2.71.1
$ git commit --amend
$ homebrew switch git 2.18.0
$ git commit --amend
```

if anybody wants a shot at reproducing.

**Comment by tarsius** [comment]
I've applied that to master now.
