### ISSUE TITLE
Interactive rebase on large repositories is now unusably slow

### ISSUE THREAD

**Issue by drobilla** [magit/magit#3519]
At some point in the past couple of months or so (sorry, I haven't narrowed this down more yet), interactively rebasing in magit (from Melpa) has gotten dramatically slower.  So much so that I've had to resort to interactive rebasing from the command line.

`Magit 20180717.1801, Git 2.14.3 (Apple Git-98), Emacs 25.3.1, darwin`

The issue is present with a clean magit-only emacs instance.  Before the interactive rebase window finally pops up, emacs is locked up, and the CPU time is all going to `git` in the command:

`/usr/local/bin/git --no-pager --literal-pathspecs -c core.preloadindex=true -c log.showSignature=false branch --remote --contains xxxxxxxxxxx`

It's possible something has changed with this particular repository, though the issue occurs for me across various checkout and operating systems (Linux and MacOS).  If I run this command manually in a terminal, it also takes a very long time to complete.  However, if I do an interactive rebase from the terminal using a different editor, everything is fine.

Trying this command out manually, I've narrowed it down to the `--remote` option.  Without specifying this, the command is a lot faster (still a bit slow, but usable).  It looks this this arrived in a7da211d29bad8997c9898747a86694c0968f6e3

If this functionality is necessary, could perhaps a configuration option be added to disable it?

**Comment by drobilla** [comment]
Yeah, I ended up digging a little more than anticipated when I started writing that :)

Awesome, seems fine now.  Thanks!

**Comment by Jannis** [comment]
This is still an issue on macOS using Emacs 26.1 and `magit-20190425.210`.

Things that take ~10s in a medium to large repository:

* Updating the magit status buffer
* Stashing or unstashing changes

I'm new to magit and also not familiar with its codebase but if I can do anything to help debug this, I'd be happy to.

**Comment by tarsius** [comment]
Have you read https://magit.vc/manual/magit/Performance.html, in particular https://magit.vc/manual/magit/MacOS-Performance.html#MacOS-Performance (which I should update)?

**Comment by Jannis** [comment]
I'll double check that things are set up well on my end.

Regarding for the `vfork` support: since I'm using Emacs 26.1, I'd assume the slow forking shouldn't play a role anymore? Or was it included in 26.1?

**Comment by tarsius** [comment]
> Or was it included in 26.1?

I think it was. Sorry I overlooked that you mention you were using that. Cannot hurt to update anyway.

**Comment by mclearc** [comment]
I also find magit to be unusably  slow in repos where there have been a large number of changes. For example, if I have to update 10 or more packages in my `emacs.d` directory I need to do commits using git from the command line. Magit takes forever (using emacs 26.2 (emacs-plus) and most recent magit on Mac OS (Mojave 10.14.4)).

**Comment by hrehfeld** [comment]
I'm currently trying to rebase -i a commit about 7500 commits in the past, which is also unusably slow (minutes).
