### ISSUE TITLE
Cannot unset C-x g

### ISSUE THREAD

**Issue by rakanalh** [magit/magit#3522]
Magit sets `C-x g` to execute `magit-status`. This is not unsetting successfully with:
```
(use-package magit
  :config
  (global-unset-key (kbd "C-x g"))
  :bind
  ("C-x g" . nil))
```
Which means that everytime i open up Emacs, magit binds this key sequence and my configs above have no effect whatsoever.

M-x magit-version RET
Magit 20180723.1158, Git 2.18.0, Emacs 26.1, gnu/linux

**Comment by npostavs** [comment]
Try `(unbind-key "C-x g" magit-file-mode-map)`, or `(global-magit-file-mode -1)` (to get rid of <kbd>C-x M-g</kbd> and <kbd>C-c M-g</kbd> too)

**Comment by phil-s** [comment]
Furthermore, note that `magit-file-mode-map` is the *only* keymap where Magit binds that sequence.  No global binding is created (at least not by default).

**Comment by rakanalh** [comment]
Thanks @npostavs  and @phil-s
