### ISSUE TITLE
Confusing option wording, when configuring magit-no-confirm

### ISSUE THREAD

**Issue by dpapavas** [magit/magit#3525]
When configuring the option `magit-no-confirm` via `customize-option` for instance, the setting allowing disabling confirmation on a case-by-case basis reads "Require confirmation only for:", which seems to be the opposite of what the name and description of the configured variable would imply.  Nevertheless, choosing a couple of the provided checkboxes and saving the configuration, results in something like the following:

```lisp
 '(magit-no-confirm (quote (stage-all-changes unstage-all-changes)))
```

Unless I'm missing something, which might well be the case, as I've been using magit only for a couple of days now, it seems that the prompt should read: "Don't require confirmation for".  My Magit version is `Magit 2.13.0, Git 2.11.0, Emacs 25.1.1, gnu/linux`, but this seems to be still relevant (see below).

https://github.com/magit/magit/blob/2196dc601b8330ae14fb040e55461ade865fd208/lisp/magit-utils.el#L275

**Comment by tarsius** [comment]
Thanks!
