### ISSUE TITLE
`I` keybinding incorrect?

### ISSUE THREAD

**Issue by Gastove** [magit/magit#3527]
Expected:
Based on past experience with magit, I would expect that, in a `magit-status` buffer, I could move point to a file and press `i` to add that file to the `.gitignore` of the repo, or `I` (that's capital `i`) to add the file to the local gitignore. 

Actual:
Pressing `I` throws `command-execute: Wrong type argument: commandp, magit-gitignore-popup`

Magit version:
Magit 20180726.2349, Git 2.17.1, Emacs 26.1, gnu/linux

Note:
A quick look in `magit-mode.el` shows `I` is bound to `magit-gitignore-popup` instead of `magit-ignore-locally`. I'm happy to PR the one-word change to `s/popup/locally`, if that's considered the correct fix. If the issue is with `magit-gitignore-popup`, I can't be of as much help.

**Comment by MatthewFluet** [comment]
I believe it was changed in f987534 (and the comments there note that it was discussed in magit/magit-imerge#2).

It seems that `I l` should achieve the same effect (add the file to the local `.gitignore`).

**Comment by Gastove** [comment]
Huh. Though, currently, `I` just... doesn't work at all (for me). Perhaps that's the actual problem?

**Comment by tarsius** [comment]
Thanks for reporting. The autoload definition was broken, preventing the command from being loaded.

**Comment by Gastove** [comment]
AH. That'd do it. Thanks much!
