### ISSUE TITLE
git blame -- copy content of buffer

### ISSUE THREAD

**Issue by Pitometsu** [magit/magit#3528]
magit-blame at any buffer
as a user, I want just to copy few lines (code with author), but can't.

**Comment by tarsius** [comment]
The metadata is displayed using overlays and yes, that makes it impossible to copy it.

**Comment by Pitometsu** [comment]
Is there any way to interact with it as with usual text?

**Comment by tarsius** [comment]
No, but you could use somethink like:

```lisp
(plist-get (overlay-properties (magit-blame--overlay-at (point))) 'magit-blame-revinfo)
```
