### ISSUE TITLE
magit-dwim-selection does not work with magit-tag

### ISSUE THREAD

**Issue by yurikhan** [magit/magit#3529]
To reproduce, from `make emacs-Q`:

1. `(add-to-list 'magit-dwim-selection '(magit-tag nil t))`
2. `(magit-status "~/.emacs.d/magit")`
3. From the Magit status buffer, `l l` (`magit-log`).
4. From the Magit log buffer, `t t` (`magit-tag`).
5. Enter a name for the new tag: `f o o RET`.

Expected: Magit creates a tag named `foo` pointing to the commit at point.

Observed: Magit prompts for the target commit, offering the commit at point as default.

Stepping through the second invocation of `magit-completing-read`, I see `this-command` is set to `exit-minibuffer` instead of `magit-tag`.

I tried on Magit 2.13.0 and current master which is 2.13.0-107-ge2b95c7f. This is on Emacs 25.3.2.

**Comment by tarsius** [comment]
This is a very good bug report and  #3530 is a good feature request. Thanks!

I cannot see a reason why it would every be useful to know that `exit-minibuffer` was used to exit a `magit-completing-read`, so I just taught that function to restore `this-command` after performing completion.

**Comment by tarsius** [comment]
Oh, you need to use `(add-to-list 'magit-dwim-selection '(magit-tag nil t))`. The first prompt also uses `magit-completing-read` and uses the tag at point as the default.

**Comment by yurikhan** [comment]
Thanks!
