### ISSUE TITLE
global-git-commit-mode doesn't work with 'emacsclient -t'

### ISSUE THREAD

**Issue by 23Skidoo** [magit/magit#3535]
I'm using the latest version of the `git-commit` mode from MELPA (20180730.2140). My `EDITOR` is set to `emacsclient -t`. Trying to edit a `.git/COMMIT_EDITMSG` file no longer opens `emacsclient` in the terminal; file is opened in the GUI Emacs instance, but there is no associated server connection and closing it doesn't affect the `git commit` process, which hangs forever waiting for the editor to exit. I can work around this by disabling `global-git-commit-mode`.

**Comment by tarsius** [comment]
This might be the same issue as described in #3415. Please follow instructions you can find there.

**Comment by 23Skidoo** [comment]
I tried adding `(require 'git-commit)` to `~/.emacs`, but it had no effect. I'm using Emacs 26.1 on Ubuntu 16.04.

**Comment by tarsius** [comment]
Is actually emacs running and did you start the server? If I don't do that I get:

```
$ EDITOR="emacsclient" git commit --allow-empty
hint: Waiting for your editor to close the file... /usr/local/bin/emacsclient: can't find socket; have you started the server?
To start the server in Emacs, type "M-x server-start".
/usr/local/bin/emacsclient: No socket or alternate editor.  Please use:

        --socket-name
        --server-file      (or environment variable EMACS_SERVER_FILE)
        --alternate-editor (or environment variable ALTERNATE_EDITOR)
error: There was a problem with the editor 'emacsclient'.
Please supply the message using either -m or -F option.
```

If I use an alternate editor, then it doesn't work:

```
% EDITOR="emacsclient --alternate-editor emacs" git commit --allow-empty
hint: Waiting for your editor to close the file... emacsclient: can't find socket; have you started the server?
To start the server in Emacs, type "M-x server-start".
[master c504b14] test
```

I don't think there is a way to make this work. Above you can see that the commit actually succeeded, but `git-commit` wasn't involved in that. I had to exit emacs to complete the commit.

I'll add a FAQ entry about this.

**Comment by 23Skidoo** [comment]
Yes, the Emacs GUI instance is running, and the server as well. Emacsclient pops up for a moment in the terminal and then vanishes. I can edit `COMMIT_EDITMSG` in the GUI instance if I switch to that buffer, but `C-x #` does nothing and saving and killing the buffer doesn't notify the waiting `git commit` process.

**Comment by 23Skidoo** [comment]
All I see from `git commit` is the

    hint: Waiting for your editor to close the file...

line.

**Comment by tarsius** [comment]
See https://github.com/magit/magit/wiki/FAQ#when-committing-from-the-command-line-then-git-commit-mode-isnt-used. Does that leave anything unanswered?

**Comment by 23Skidoo** [comment]
I've updated to the latest snapshot of `git-commit` from MELPA and now `(require 'git-commit)` solves the problem for me. Before it didn't. I use `zile` as `--alternate-editor`, and that works too. Thanks!
