### ISSUE TITLE
Add defvar for perl command

### ISSUE THREAD

**Issue by Ambrevar** [magit/magit#3537]
Magit 20180731.2119, Git 2.18.0, Emacs 26.1, gnu/linux

Some parts of Magit assume that `perl` is in the user's PATH.
For instance, the `magit--cherry-move' function:

```elisp
                   (push (format "%s=perl -i -ne '/^pick (%s)/ or print'"
                                 "GIT_SEQUENCE_EDITOR"
                                 (mapconcat #'magit-rev-abbrev commits "|"))
                         process-environment)
```
will fail if `perl` is not in the `PATH`.

On systems running [Nix](https://nixos.org) or [Guix](https://www.gnu.org/software/guix), Perl can be installed in the store but not necessarily in the user profile (i.e. in the PATH).  This is why it's good practice to make every system command customizable so that all users and packagers can easily adapt those dependencies.

My suggestion:
```elisp
(defvar magit-perl-command "perl"
  "The Perl interpreter.")

...

                   (push (format "%s=%s -i -ne '/^pick (%s)/ or print'"
                                 magit-perl-command
                                 "GIT_SEQUENCE_EDITOR"
                                 (mapconcat #'magit-rev-abbrev commits "|"))
                         process-environment)
```

N.B.: I'm not sure why "GIT_SEQUENCE_EDITOR" is not directly written into the format string.  Mistake?

**Comment by tarsius** [comment]
How does git itself deal with this? Perl is a runtime dependency of git, so I would assume that "adding git to the user profile" would have to do the same for perl. Or do nix/guix patch git, so that perl can be found even if that is not the case.

I am not against adding an option, but it seems that nix/guix might be a bit broken with regards to this.

> N.B.: I'm not sure why "GIT_SEQUENCE_EDITOR" is not directly written into the format string. Mistake?

It prevents having a line that is longer than 80 characters.

**Comment by Ambrevar** [comment]
> Or do nix/guix patch git, so that perl can
> be found even if that is not the case.

Correct.

In the general case, it's just about patching shebangs, thus this can be
completely automated.

In the case of Emacs, patching `defvar`s is also very easy.

> I am not against adding an option, but it seems that nix/guix might be a bit
> broken with regards to this.

Well, I believe it's best practice for a a program to specify where the
dependencies are to be found (e.g. via environment variables or `./configure`
parameters).  I makes programs more portable and customizable.
Assuming a fixed path is deemed to break at some point.

In practice, there are very few programs that need manual patching to work.
It would be great if Magit wasn't one of them :)

**Comment by kyleam** [comment]
I'm fine with adding a `defvar` (though I think its name should be `magit-perl-executable` for consistency with `magit-git-executable` and `magit-gitk-executable`).  However, I'm surprised that this isn't being patched by Guix on your end.  One my system (where Guix is a bit out of date :/), I see

```
(push (format "%s=/gnu/store/7ifc22sh86zblnzamqimgmv06idyx69v-perl-5.26.1/bin/perl -i -ne '/^pick (%s)/ or print'"
              "GIT_SEQUENCE_EDITOR"
              (mapconcat #'magit-rev-abbrev commits "|"))
      process-environment)
```

in `magit--cherry-move`s definition (/gnu/store/asrn2626xwd27k0c07zpdsw5ga1m62ry-magit-2.13.0).

(I've taken a cursory glance at the recent help-guix thread about this issue, but didn't look at it closely, so perhaps the reason for the change is explained there.)

**Comment by Ambrevar** [comment]
Oopsy!  Looks like I got fooled by ELPA and a package I had installed from there had installed `magit` as a dependency... I was looking at the MELPA version of `magit` the whole time :p 

Guix gets it right indeed, so there is no issue at all in the end.

Well, at any rate my suggestion would only make the patch more reliable, should "perl" appear elsewhere in the code some day.

**Comment by tarsius** [comment]
@Ambrevar Lets do that then. Could you please open a pr?
