### ISSUE TITLE
stash not working with git 1.9.4

### ISSUE THREAD

**Issue by the-eeb** [magit/magit#3544]
I believe magit requires git 1.9.4 or higher, however git 1.9.4 gives an error when you pass the option '-no-gpg-sign' to git-commit-tree.  Since magit uses this option when creating stashes, I'm guessing it actually requires a later version of git.   Patching git 1.9.4 to parse this option works just fine.

**Comment by tarsius** [comment]
Thanks for the notice.

I have dumped the dependency to 2.0.0. Also see 248f55cf7ed98f249f8615ee6f489683e80e1629.
