### ISSUE TITLE
GPG signing for rebase

### ISSUE THREAD

**Issue by Ailrun** [magit/magit#3548]
As far as I know, there is no simple way to preserving (or more correctly, resigning) gpg sign while rebasing in magit.
Could you add similar function like `c =S` (`Sign using gpg` option in `commit-popup`) to `rebase-popup`?

**Comment by kyleam** [comment]
Have you tried adding that option with `magit-define-popup-option`?  That's [one] of the options listed in the proposed arguments wiki (#3422).  

[one]: https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands#magit-rebase-popup

**Comment by Ailrun** [comment]
Oh, sorry. I didn't know that. Thank you for your answer!
