### ISSUE TITLE
Incorrect handling of magit-cherry-pick revision argument

### ISSUE THREAD

**Issue by aoriens** [magit/magit#3551]
Hello!

I'd like to perform a cherry-pick from magit that's equivalent to the following command:
```
git cherry-pick ..origin/my-branch
```
It works in the command line. But when I use `magit-cherry-pick` command in Emacs and specify revision `..origin/my-branch`, magit writes the error message:
```
GitError! bad revision ''  [Type `$' for details]
```
And the following text appears in the `magit-process` buffer:
```
128 git … cherry-pick --ff '' origin/my-branch
fatal: bad revision ''
```
So, magit seems to process a revision argument in a wrong way for some reason. I remember it worked in older versions.

Magit 20180620.1224, Git 2.15.0, Emacs 25.3.1, darwin

**Comment by tarsius** [comment]
At the prompt you can only select a single commit, but you can select multiple commits by marking them using the region. Many commands work like this, see https://magit.vc/manual/magit/The-Selection.html#The-Selection.

**Comment by aoriens** [comment]
Thank you. I've tried to `magit-log` with `..origin/my-branch` argument, then select all the commits and do cherry-picking, it works.
