### ISSUE TITLE
checkout theirs/ours in batches

### ISSUE THREAD

**Issue by CeleritasCelery** [magit/magit#3553]
when you have a file with a merge conflict you can run `magit-discard` to be given the option in checkout `our` or `their` branch. This works great until you have many files (almost 200 in my case) that you want to checkout a particular branch for. This opens up the discard dialog once for each of the files, instead of asking you once and then applying it to all the files as it does with other operations like normal discard. It would be very efficient if the selection was applied to all of the selected files. Alternatively, it could use capital letters as short for "apply this option to the rest of the files".

**Comment by tarsius** [comment]
Thanks for the suggestion. I now plan to do that.
