### ISSUE TITLE
Provide a way to ignore submodules when refreshing the status buffer

### ISSUE THREAD

**Issue by cody-addison** [magit/magit#3555]
I work in a large git repo with several large submodules. I like having the status buffer update regularly, but it takes ~13 seconds between every operation if submodules are included. This is reduced to less than 1 second if submodules are ignored. It would be nice to have a command that causes submodules to be included so I can stage and commit changes via the status buffer.

I was able to achieve this by modifying magit-insert-untracked-files and magit-insert-unstaged-changes to pass --ignore-submodules=dirty to their backing git commands. For the case of untracked files, I'm not sure submodules updates are every needed, so perhaps that command could always use --ignore-submodules?

I implemented this for now by copying the two functions listed above, and added a variable to control the argument to --ignore-submodules. I created a wrapper function for magit-status that causes submodules to be included by changing the variable. I'm not great with elisp and suspect there is a better way to achieve the same results. If you have any ideas on how to support this in the existing framework please let me know.

**Comment by tarsius** [comment]
Thanks for the suggestion. I now plan to do that.

**Comment by cody-addison** [comment]
Great! Thanks for the great package.

**Comment by tarsius** [comment]
I pushed an early implementation to https://github.com/magit/magit/compare/avoid-modules. It makes Magit usable in my 6455 submodules repository, but there is still a lot of detail work, decision making and documentation writing to be done.

**Comment by tarsius** [comment]
I haven't written any documentation yet.

I recommend adding a `.git-locals-2.el` containing something like

```
((magit-status-mode
  (magit-diff-section-arguments
   . ("--ignore-submodules=dirty")))
 (magit-diff-mode
  (magit-diff-arguments
   . ("--ignore-submodules=dirty"
      "--stat" "-M" "--diff-algorithm=patience"))))
```

to the repositories with many modules. You should ignore, not track, that file. If you want to do the latter use `.dir-locals.el` instead, but I recommend against that because then you would force the other arguments onto contributors also.

**Comment by ali5h** [comment]
is this config still valid? I cannot make it work

**Comment by tarsius** [comment]
That doesn't work anymore but you can set the Git variable `diff.ignoreSubmodules` instead.

Note that some parts of Magit that already considered the argument ignored the variable until a7699f868f6fd32aae8aa8e64a72ea989a5c25cf, so you'll want to update.
