### ISSUE TITLE
Harvest cherry-pick continues if git checkout fails

### ISSUE THREAD

**Issue by greenrd** [magit/magit#3556]
Magit 2.13.0, Git 2.15.1.windows.2, Emacs 25.3.1, windows-nt

Steps to reproduce:
* check out branch A
* create new git worktree (i.e. using the git worktree command)
* in the new worktree, check out branch B
* in the new worktree, do magit-status, `l`, `o`, `A`
* move down to a previous commit (that is not in branch B)
* do `A`, `-e`, `-F`, `h`
* press Enter to accept the commit at point
* edit the commit message and do `C-c` `C-c`

Expected results:
* Either commit should be moved from branch A to branch B, or it should fail (due to git checkout failing) and do nothing.

Actual results:
* magit launches git checkout to switch branches. git checkout fails with `fatal: 'A' is already checked out at 'C:/Users/...'`
* magit ignores the error, and continues trying to do the cherry-pick steps regardless of the error
* magit allows the commit message to be edited
* branch B ends up in an undesired state

**Comment by tarsius** [comment]
> * do `A`, `-e`, `-F`, `h`

I.e. use `--edit` but not `--ff`, right?

> Expected results: Either commit should be moved from branch A to branch B,

That's what happened for me using Git 2.18. Additionally the primary worktree where A is checked out did *not* change, resulting in unstaged changes (that is expected, but can be confusing).

> or it should fail (due to git checkout failing) and do nothing.

I pushed a commit that should result in that behavior if the checkout fails for whatever reason.
