### ISSUE TITLE
How to show full commit once restricted to a file

### ISSUE THREAD

**Issue by Silex** [magit/magit#3557]
Hello,

When using `magit-log-buffer-file`, how do I show the commit but not restricted to that file? My use case is that I know some change occured in file X, so I use magit-log-buffer-file to find the change, then I want to view other parts of that commit.

**Comment by kyleam** [comment]
You can use `magit-diff-toggle-file-filter` (bound to <kbd>D F</kbd>).

**Comment by Silex** [comment]
Thanks!
