### ISSUE TITLE
compile error in magit-section.el

### ISSUE THREAD

**Issue by ryofurue** [magit/magit#3558]
Please explain
  (1) what behavior you expected: N/A
  (2) what behavior you observed: Compile error during the installation of the magit package.

    Compiling file /Users/My-User-Name/.emacs.d/elpa/magit-20180820.2042/magit-section.el at Tue Aug 21 20:25:05 2018
    magit-section.el:611:1:Error: `let' bindings can have only one value-form: oref, section, start

  (3) and how we can reproduce the issue.

    M-x package-list-packge
       and install the magit package from the list.

I think the package is from http://melpa.milkbox.net/packages/

Also post the output of

  M-x magit-version RET

    Magit 20180820.2042, Git 2.18.0, Emacs 26.0.50, darwin

**Comment by npostavs** [comment]
> Emacs 26.0.50

Can you try upgrading to 26.1 (or downgrading to 25.3)? 26.0.50 is an out of date snapshot version.
