### ISSUE TITLE
magit-status always jumps to "Recent commits"

### ISSUE THREAD

**Issue by madscientist** [magit/magit#3561]
Magit 20180820.2042, Git 2.18.0, Emacs 26.1, gnu/linux

I can't say for sure if this is new behavior but it _seems_ new.  It's certainly started bothering me recently but perhaps I have just started getting ornery recently :)

I have `C-c g` bound to `magit-status` and when I use that keybinding for the second and subsequent times in a buffer, it brings up the existing magit: buffer for my Git repository but instead of leaving point where it was the last time I visited the status buffer, it always puts point at the "Recent commits" line in the buffer.

This makes me sad because what I almost always want to look at is NOT my "Recent commits" but rather the staged/unstaged changes in my workspace.  And since I have a lot of stashes (25 right now) that come between staged/unstaged changes and "Recent commits", what I want to see and use is always off the window above and I have to scroll or jump back up to get to it.

I'd prefer to have `magit-status` bring the status buffer to the front without moving point from where it was previously.  Or, failing that, I'd rather have the default selected section *not* be "Recent commits" which may be useful but to my mind is much less commonly what one wants to see when opening up the status buffer than unstaged/staged changes (I realize this section might not always exist...)

Thoughts?

**Comment by kyleam** [comment]
> I can't say for sure if this is new behavior but it seems new. 

You're looking for 1ec3d711 (When showing a status buffer for the first time, jump to some log, 2018-08-11).

> Thoughts?

The motivation given in that commit message is to skip the top headers, but, as you describe, it does more than that.  I'm OK with the "skip the status headers" reasoning, but I do think the change should be tweaked.

**Comment by tarsius** [comment]
It's only supposed to do that when the buffer is first created, but I see something went wrong.

**Comment by tarsius** [comment]
Let's continue in #3562.
