### ISSUE TITLE
Lock input keymaps after starting some transactions

### ISSUE THREAD

**Issue by hardaker** [magit/magit#3564]
This is entirely my fault, not magit's, but I suspect i'm not alone that sometimes I hit a bunch of key sequences too quickly expecting emacs to catch up with my keypresses.  But the result is that the wrong key presses go to the wrong frame/window and can result in bad things.  Here's an example fictitious timeline based on what I think I'm doing vs what actually happens:

1. I decide to make a commit to some files
2. I stage the files (hit 's' on a bunch of them)
3. I hit 'c c' to start a commit
4. I immediately start typing my commit message (this is where I go wrong and start doing bad things)
5. emacs is still in the process of creating the COMMIT_EDITMSG buffer (which can take a while in super-large repositories)
6. Eventually the COMMIT_EDITMSG buffer comes up but all my keystrokes in 4 are lost

Now, again, I shouldn't be typing so early in step 4 and I should wait for COMMIT_EDITMSG to appear.  But my mind works faster that emacs apparently.

Here's the real problem with my stupidity: the key presses in step 4 **actually go to the main magit buffer**, which could be really bag if the start of my commit message included keystrokes that, say, deleted things, unstaged things, etc.  In fact, I think I just squashed a commit a minute ago by accident which isn't reversible.

So, my options:

1. Stop doing things that hurt me.  Unfortunately as much as I try to remember to pause, I seem to fail a lot.  (it's not just committing that gets me into this situation; generating history can too, for example)
2. Plead my case and hope for one of two potential solutions to be implemented:
    a. immediately after any command that is known to be eventually creating a new buffer (eg commit edit buffer), switch to a new temp capture buffer ASAP before doing the longer processing.  This would capture keystrokes in 4. above so they could be added to the created buffer after the rest of the processing is done
   b. or simply disallow kesytrokes in the vacating buffer (eg, the main magit buffer) at the start of a more computational task.  IE, change the keymap maybe to have any new strokes be bad until a long running function finishes?  

I think a. is a better solution and fairly easy to implement?

Thanks a gazillion for this wonderful package that I can't live without.

**Comment by tarsius** [comment]
> emacs is still in the process of creating the COMMIT_EDITMSG buffer

This process is actually more complicated than it may seem and Magit also doesn't have much control over it. Magit calls `git`, which calls `$EDITOR`, which has been configured to be `emacsclient`, which connects to the server of the current `emacs` instance. While that is happening Magit cannot "block".

But doing that shouldn't actually take that much time. What may take a long time in large repositories is the creation of the "changes to be committed" diff, but that happens *after* the commit message buffer has already been set up, so input should go to that buffer.

> (it's not just committing that gets me into this situation; generating history can too, for example)

Not sure how that can happen -- all the expensive calculations should happen after the buffer is displayed and selected. Follow `magit-log` -> `magit-mode-setup` -> `magit-mode-setup-internal`, which calls `magit-display-buffer` *before* `magit-refresh-buffer`, where the latter is what may take a long time. 

> In fact, I think I just squashed a commit a minute ago by accident which isn't reversible.

Sure it is. Use `l r` to show the reflog, move point to the commit that hasn't been damaged yet (`l o RET` may help confirming that the history leading to a commit is still intact), and the use `p x RET` with point on that commit to reset the current branch to that.
