### ISSUE TITLE
Magit log buffer unconditionally joins lines of a multiline log message

### ISSUE THREAD

**Issue by c4eater** [magit/magit#3566]
Hi,

Magit log buffer is replacing newlines with whitespace in the log message, effectively displaying every multiline log message as a single very long line.

This is OK to view when visual-line-mode is off (which is the default), but if this mode is on, the output doesn't look very nice as the log formatting is broken.

Expected behavior: Magit should have a setting saying whether to join log lines.

To reproduce the issue, just create a multiline commit message, preferably with long lines (~50-70), and enable visual-line-mode in magit log.

Magit version: Magit 2.13.0-180-g79d510cb, Git 2.14.4, Emacs 26.1, gnu/linux

Thanks

**Comment by tarsius** [comment]
I don't think it does that but I am also not quite sure what you are talking about. Please post a screenshot. Also try to reproduce this using [`magit-emacs-Q-command`](https://magit.vc/manual/magit/Debugging-Tools.html).

**Comment by c4eater** [comment]
See the upper frame. The log lines are unexpectedly joined together. Expected is something like the raw git log output (lower frame). Strangely enough, magit-revision buffer shows the multiline log correctly.

![scrnshot](https://user-images.githubusercontent.com/2597360/44778295-44ea3580-ab85-11e8-971f-82254a4d9def.png)

I also noticed that the log behavior is changed when the log message contains a blank line (in which case, magit-log buffer truncates the message below the blank line). Is there a setting for making Magit display the complete log message?

**Comment by c4eater** [comment]
`("-n256" "--graph" "--decorate")`

**Comment by tarsius** [comment]
In that case the `Comment line 2...." line should not be displayed at all. There should only be one line per commit. Please try to reproduce this using [`magit-emacs-Q-command`](https://magit.vc/manual/magit/Debugging-Tools.html).

**Comment by c4eater** [comment]
The bug reproduces.

**Comment by c4eater** [comment]
OK I get it... probably magit is using --oneline format by design.

Yet, I would really appreciate if magit could do a special processing of such non-conformant format. One cannot expect all git comments in the world to have the line 2 blank.

**Comment by tarsius** [comment]
> Yet, I would really appreciate if magit could do a special processing of such non-conformant format. One cannot expect all git comments in the world to have the line 2 blank.

Ah, you located the condition that triggers this. Thanks!

> In addition, unconditionally using --oneline in magit would mean that this is not possible to have a formatted multiline message in git-log at all.

You can use the `++header` argument and maybe customize `magit-log-revision-headers-format`.

**Comment by tarsius** [comment]
> I think this is just how git works. It joins every line until the first blank one into the summary line.

I overlooked that earlier. In that case that is not a bug in Magit (or Git) but a design decision by the Git maintainers and we cannot do anything about it.
