### ISSUE TITLE
Renaming a file in the current directory throws Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by treese** [magit/magit#3569]
In a git repository with one commit and two files checked in, I did the following:
1. M-x magit-status (while visiting a buffer with one of the files)
2. R to rename (calling magit-rename)
3. Error Wrong type argument: stringp, nil 

It may be necessary to be in the top-level directory of a repository to reproduce this.

magit-version: Magit 20180828.1055, Git 2.15.2 (Apple Git-101.1), Emacs 25.3.50.1, darwin 

I believe the problem is the following code in the function magit-rename-file:
```
(let* ((file (magit-read-file "Rename file"))
          (newname (read-file-name (format "Rename %s to file: " file)
                                   (expand-file-name (file-name-directory file)))))
```
If `file` is just a filename with no directory, `file-name-directory` returns `nil`, and `expand-file-name` throws the error.

If the code expanded the filename first, then there would be a directory present to use: `(file-name-directory (expand-file-name file))`.

**Comment by tarsius** [comment]
Thanks!
