### ISSUE TITLE
Face for upstream branch

### ISSUE THREAD

**Issue by aethertron** [magit/magit#3573]
There is a specific face for Remote Branch Heads ("magit-branch-remote-head").  While this is nice, I think it would be far more useful to have a face for Upstream branches.  I'm requesting a face be added for upstream branches, it can inherit from "magit-branch-remote-head".  

Why would this be more useful?  Well, I find that the remote branch head face does a good job highlighting the current upstream branch.  I don't care whether I have a remote head for that branch, only that it's upstream.  It's easy to have an upstream branch without a remote head, so you can easily get into a situation where you have an upstream branch but it's indistinguishable from the other branches.  By creating a face for upstream branches, you will ensure that upstream branches are distinguishable in all situations.  

There's a good discussion of remote head branches here: - https://stackoverflow.com/questions/17639383/how-to-add-missing-origin-head-in-git-repo

**Comment by tarsius** [comment]
What do you mean by "upstream branches" (plural)? The current (local) branch can only have zero or one upstream branch. Maybe it would make sense to somehow emphasize that branch. Are you asking for that only? I don't think it would be useful to emphasize all remote branches that happen to be the upstream of some, not necessarily current, local branch.

**Comment by aethertron** [comment]
My apologies, I'm asking for exactly what you mentioned: to emphasize the upstream branch for the currently checked out branch.  I agree that the language "upstream branches" was vague and misleading.

**Comment by tarsius** [comment]
I think it is best to almost always use `master` or `origin/master` as the upstream. In particular I don't think that `new-feature`'s upstream should be something like `my-fork/new-feature`. Do you follow that recommendation already? If not see https://magit.vc/manual/magit/The-Two-Remotes.html.
