### ISSUE TITLE
Cannot display list of submodules

### ISSUE THREAD

**Issue by Zaeph** [magit/magit#3575]
Hello,

I’ve encountered a problem with `magit` trying to open the list of submodules on a repo I manage. I can’t be certain that the last update is the one that introduced it, but I can vouch for the fact that it worked two weeks ago.

### Bug
In `magit`, after opening the `*magit-submodule-popup*` with `o`, listing all the modules with `l` result in the following message:
```
progn: ‘magit-mode-get-buffer’s CREATE argument is obsolete
```
After that, I’m dropped back on the main `magit` menu without the list of modules having been displayed.

### Reproduce-ability 
I can reproduce this behaviour with a minimal `init.el` as well as with other repositories making use of submodules.

Here’s the output of `magit-version`:
```
Magit 20180902.101, Git 2.18.0, Emacs 26.1, gnu/linux
```

I’ve searched for similar issues on the tracker or online, but haven’t found anything relevant. Please excuse me if I’ve missed anything.

Thanks for looking into it, and I’m available if you want me to run tests.

HTH

**Comment by kyleam** [comment]
Thanks for the report.  `magit-list-submodules` should have been adjusted in 2113dfc3 (magit-create-buffer-hook: New hook, 2018-08-26).
