### ISSUE TITLE
Add post-hook for magit-clone

### ISSUE THREAD

**Issue by yiufung** [magit/magit#3576]
After I clone a project, I would like to do some one-time setup so Emacs is aware of the new project's existence. For example, add it to `projectile`'s known project list. 

Currently, a workaround is to utilize `magit-status-mode-hook`, which is invoked at the end of `magit-clone` when it calls `magit-status-internal`. However, it will generally slow down `magit-status`.

**Comment by kyleam** [comment]
[somewhat related to #2431, though more general]

> Currently, a workaround is to utilize magit-status-mode-hook, which is invoked at the end of magit-clone when it calls magit-status-internal

Another workaround would be to advise magit-clone.

**Comment by yiufung** [comment]
Indeed I could use advice instead. Thanks.
