### ISSUE TITLE
Allow additional sections to be inserted and cleanly integrated with pre-existing sections?

### ISSUE THREAD

**Issue by phil-s** [magit/magit#3578]
Magit 2.13.0-dirty, Git 2.16.3, Emacs 26.1, gnu/linux

I'm actually not sure whether this is a feature request, a bug report, or a support request.

I wanted to be able to insert a section into the refs buffer on demand, but found that while calling `magit-insert-section` (or `magit-insert-tags` in this case) does insert the content, it also causes side-effects for the overall section functionality in the buffer, such that only some of the sections would be collapsible.

The context is that one of my main projects has a *lot* of refs, and the default refs buffer was always pretty slow to load, and the other day it finally occurred to me that the *bulk* of the refs are tags (all 2263 of them, and growing), and I almost *never* need the tags list, so I removed that from `magit-refs-sections-hook` and oh-my-goodness that's better!!  However I still wanted the *ability* to see that list if I wanted to, so I was experimenting with a refs popup action to insert the Tags section into the existing refs buffer, and it turned out to be a bit problematic.

If I just call `magit-insert-tags` then the new Tags section is not collapsible.

I also tried `(magit-insert-section (branchbuf) (magit-insert-tags))` and then all the sections were individually collapsible, but the likes of `magit-section-show-level-1-all` no longer affected the original sections.

In the end I've gone with refreshing the entire buffer, which seems inefficient -- albeit pretty much ok in practice when the other sections are *relatively* quick to insert.  Nevertheless, being able to cleanly inject a new section into an existing buffer without causing problems seems like a useful feature, and if it's not already supported in some way that I didn't find, perhaps that would be a good enhancement?

Is there a way to do what I want without re-generating the pre-existing sections?

FYI here's what I've ended up with:

    (with-eval-after-load "magit-refs"
      ;; Do not insert Tags into the refs buffer by default. (Slow!)
      (setq magit-refs-sections-hook
            (delq 'magit-insert-tags magit-refs-sections-hook))
      ;; ...but add a new Tags option to the popup, which does so. (y t)
      (magit-define-popup-action 'magit-show-refs-popup ?t
        "Insert tags section" 'my-magit-insert-tags))

    (defun my-magit-insert-tags ()
      "Insert the Tags section at the end of the current buffer."
      (interactive)
      (unless (derived-mode-p 'magit-refs-mode)
        (magit-show-refs-head))
      (widen)
      ;; Use the following to discover the identifier for a section:
      ;; M-: (magit-section-ident (magit-current-section))
      (let ((tags (magit-get-section '((tags) (branchbuf)))))
        (if tags
            (progn
              (goto-char (oref tags start))
              (recenter 0))
          (let ((inhibit-read-only t))
            ;; Calling `magit-insert-tags' directly causes problems.
            (erase-buffer)
            (let ((magit-refs-sections-hook
                   (if (memq 'magit-insert-tags magit-refs-sections-hook)
                       magit-refs-sections-hook
                     (append magit-refs-sections-hook '(magit-insert-tags)))))
              (magit-refs-refresh-buffer nil)
              (setq tags (magit-get-section '((tags) (branchbuf))))
              (if (not tags)
                  (message "No tags found")
                (goto-char (oref tags start))
                (recenter 0)))))))

**Comment by tarsius** [comment]
Inserting new sections at arbitrary positions is probably problematic, but inserting them at the end should work. `magit-process-insert-section` does that for example.

Though in this case it is probably better to configure the `((tags) (branchbuf))` to be collapsed when first created and forgo creating its body until it is expanded. The latter is already being done "one level down", see `magit-refs--insert-cherry-commits` and `magit-refs--insert-cherry-commits-1`. You might want to try doing the same thing by moving `magit-insert-tags`'s `dolist` into a new function.

**Comment by phil-s** [comment]
Thanks tarsius, that makes sense.  I'll let you know how I get on with that (probably in a few days).

I see that the insert-cherry-commits functions actually implement the "Don't even talk to Git about this until the user asks about it" behaviour, which I think has cropped up in a number of discussions about potential performance improvements for the status buffer.  Very nice.  Is that approach used anywhere else at present?

Regardless of when the data is obtained from Git, it seems like it could be smart behaviour *in general* if collapsed-by-default sections were always only created/washed if/when first expanded?  (Although perhaps that would only be of practical benefit in a limited set of cases?  I haven't thought this through at all; I'm just (metaphorically) thinking out loud...)

**Comment by tarsius** [comment]
Yes that's used in other places and yes I plan to use it in even more places. :wink:
