### ISSUE TITLE
Package 'graphql-0' is unavailable

### ISSUE THREAD

**Issue by fth86** [magit/magit#3581]
I just updated all melpa packages via spacemacs' update-packages function, including magit.
On emacs restart, packages did get updated, though magit did not. The magit update failed with

`An error occurred while installing magit (error: (error Package ‘graphql-0’ is unavailable))`

As I cannot downgrade using melpa, and magit seems to be an integral part of spacemacs, this is a major issue.

**Comment by vermiculus** [comment]
@tarsius, I see you've started using that encoding package I wrote :-) I'll release a 'stable' version ASAP for you to depend on. I expect it will be `0.1`.

**Comment by vermiculus** [comment]
That will not happen until I'm at my computer again, though. It will be a few hours.

**Comment by vermiculus** [comment]
For others who find this issue, the package needed is my `graphql.el`

**Comment by vermiculus** [comment]
I may also need to submit it to MELPA if that has not happened already. Someone can open a PR there and get the ball rolling if they want; link it here if you do.

**Comment by npostavs** [comment]
> I may also need to submit it to MELPA if that has not happened already.

It has, see magit/ghub#69

**Comment by vermiculus** [comment]
Excellent

**Comment by GoingFast** [comment]
Also getting "Error (use-package): Cannot load magit". Worked today until I decided to update packages. @vermiculus

**Comment by vermiculus** [comment]
[Looks like you posted the actual errors you're seeing in chat; thanks!](https://gitter.im/vermiculus/magithub?at=5b98730145318b2dfe96dbe4) I'm betting this resolves itself on the next update. Let me know in chat. If it's still buggy for you, we can figure out what to do next.

**Comment by tarsius** [comment]
I have justed test it and installation works as expected again.
