### ISSUE TITLE
Add interactive function for referencing other commits within a commit

### ISSUE THREAD

**Issue by kennyballou** [magit/magit#3588]
I occasionally reference other commits within the current commit I may be
writing.  However, instead of simply pasting the short hash or any hash, I like
to provide some context for when reading in a mode with lower fidelity or
quickly scanning commits.

I have a Git alias for creating the format of the reference which borrows the
format from Git's own referencing guidelines.  However, when within Emacs, I
imagine a "`magit-log-select` -> insert formatted text" function would be a far
superior approach.

Since I didn't see any functions that seem to accomplish this already, I tried
to hack together a function I thought might work.  However, I seem to lack some
basic understanding of 1) (Emacs) Lisp and 2) the `magit-log-select` function.

```lisp
(defun magit-commit-reference ()
  "Add a commit reference to the current point.

This functionality is based on Commit References used in Git itself.
https://git.kernel.org/pub/scm/git/git.git/tree/Documentation/SubmittingPatches"
  (interactive)
  (let ((magit-log-select-pick-function
         (lambda (rev)
           (save-excursion
             (magit-git-string (list "show"
                                     "--no-patch"
                                     "--date=short"
                                     "--pretty=%h (\"%s\", %ad)"
                                     rev))))))
    (magit-log-select)))

```

**Comment by tarsius** [comment]
Similar functionality already exists, see `magit-pop-revision-stack` in [Editing Commit Messages](https://magit.vc/manual/magit/Editing-Commit-Messages.html).

But this doesn't use log-select. Instead you have to use one command to put the revision at point onto a stack and then another command to pop a representation of it into the current buffer. I am not sure that doing this in one step using log-select would be all that useful. That would only work when you want to mention a fairly recent commit. When you want to mention that commit from a year ago that introduced the bug you are fixing how, then it doesn't work.

**Comment by tarsius** [comment]
> I am not sure that doing this in one step using log-select would be all that useful.

How do you feel about that?

**Comment by kennyballou** [comment]
I haven't yet had a chance to try this with `magit-pop-revision-stack` yet.  I'm not attached to `log-select`.  What I would like is simply the ability to run a command that prompts to enter a hash or to select a hash from a list.  The reason I like the latter is because then I don't have to know the hash before running the command, I can scroll through and interrogate the list of commits.  As you've mentioned, `log-select` may be a poor choice for this when trying to select a commit that's a buried in the history.

If we can achieve (essentially) the same in two steps (via `magit-pop-revision-stack` and friends) rather than one, I'm okay with that.

**Comment by kennyballou** [comment]
Maybe I'm missing something, but I don't seem to have the `magit-pop-revision-stack` function and friends available.

The version of `magit` I have installed is: `20180505.1620`.

```
Debugger entered--Lisp error: (void-function magit-pop-revision-stack)
  (magit-pop-revision-stack)
  eval((magit-pop-revision-stack) nil)
  eval-expression((magit-pop-revision-stack) nil)
  funcall-interactively(eval-expression (magit-pop-revision-stack) nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

**Comment by npostavs** [comment]
It's in `magit-extras.el`, perhaps it should get an `;;;###autoload` cookie?

**Comment by kyleam** [comment]
> perhaps it should get an ;;;###autoload cookie?

Maybe.  I'm guessing it doesn't have one because it's only valid after `magit-copy-section-value` or `magit-copy-buffer-revision` are called (which are autoloaded).

**Comment by kyleam** [comment]
>> perhaps it should get an ;;;###autoload cookie?
>
> Maybe. I'm guessing it doesn't have one because it's only valid after magit-copy-section-value or magit-copy-buffer-revision are called (which are autoloaded).

Oh, but it has empty stack behavior, so I'll change my "maybe" to a "yes" :]

**Comment by kennyballou** [comment]
So, to actually implement this, do I simply need to add a function to my git-commit-mode hooks that sets the format (`magit-pop-revision-stack-format`) and I can use `C-c C-w` to do exactly what I'm looking for?  Then when the commit is done, I likely want to reset the format back to the original value (as I don't know where else it's used...)?

I feel like if that's the case, this issue can be closed because it's basically already available functionality.

**Comment by kyleam** [comment]
Nothing aside from `magit-pop-revision-stack` uses `magit-pop-revision-stack-format`. You're free to customize it to whatever value you want without worrying about setting it back to the original value.

**Comment by kennyballou** [comment]
Perfect. I am closing this as I have received what I needed from this discussion.

My apologies for taking an issue for something that probably should have been on the mailing list...
