### ISSUE TITLE
Support date options for the stash section in the status buffer?

### ISSUE THREAD

**Issue by phil-s** [magit/magit#3592]
http://mbork.pl/2018-08-13_A_tip_on_git_stash shows how you can use the `--date` argument to get more useful stash names than `{0}`, `{1}`, etc.

I tried adding `"--date=short"` to the reflog command in `magit-insert-stashes` and (a) it worked, and (b) it didn't appear<sup>1</sup> to confuse Magit in any way when multiple stashes had the same date, so this might be a nice feature to provide an option for?

<sup>1</sup> Minimal testing only, but it differentiated between them when visiting the stashes.  I imagine the full ref hash gets used internally?

**Comment by phil-s** [comment]
I can't say either way, but I was pointing out that when I made this change Magit *did* differentiate between multiple stashes with the same `--date=short` name -- so it didn't *appear* to be reliant on that displayed name.

Maybe I'm just seeing undefined behaviour, though.

I do concur that the output of `git reflog --date=short --format=%gd%x00%aN%x00%at%x00%gs refs/stash` does not unambiguously identify commits (although timestamp means *in theory* the granularity for conflicts is 1 second, which isn't terrible, even if it's not trivial to make use of that).

**Comment by phil-s** [comment]
...or maybe I'm an idiot, and not noticing that what I had taken for "displaying a different stash" when typing SPC was actually "I'm already showing that stash, so SPC scrolls what you're already looking at, and now it looks different."

**Comment by phil-s** [comment]
I thought of leaving the `stash@{...}` alone and just introducing the commit date into the format, but I can't see a way to format the commit date without it also clobbering the `stash@{...}`.

The following isn't bad in practice, though:

`git reflog --date=short --format="%h%x00%aN%x00%at%x00%gs (%cr)" refs/stash`

    (magit-git-wash (apply-partially 'magit-log-wash-log 'stash)
      "reflog" "--date=short" "--format=%h%x00%aN%x00%at%x00%gs (%cr)" ref)

Then they look like:

    <hash> On <branch>: <description> (29 hours ago)

**Comment by kyleam** [comment]
> I'm not desperate to have the feature, though, and it's clearly more work than I originally imagined. 

Also note that it's already possible to see the stash's date by pressing <kbd>LL</kbd> in the status buffer.

**Comment by phil-s** [comment]
That's more than enough reason to close this again. Apologies for the time-wasting!
