### ISSUE TITLE
RET on an unpulled module in status results in "There is no thing at point that could be visited"

### ISSUE THREAD

**Issue by DamienCassou** [magit/magit#3593]
1. Create a repository with a submodule
2. Make sure the submodule contains an update that you haven't pulled in the main repo
3. In the status buffer of the main repo, you should see a section "Modules unpulled from @{upstream}"
4. In this section, press `RET` on the submodule

- Expected: a new magit status buffer showing the submodule repo
- Actual: User error: There is no thing at point that could be visited

Magit version:

> Magit 2.13.0-245-g37299195, Git 2.17.1, Emacs 26.1.50, gnu/linux

I'm using borg to get Magit and all my Emacs packages.

With `make emacs-Q`, I can reproduce the problem if I also execute this:

```emacs
(magit-add-section-hook 'magit-status-sections-hook
                            'magit-insert-modules
                            'magit-insert-unpulled-from-upstream)
```

**Comment by tarsius** [comment]
Thanks for the report.

**Comment by DamienCassou** [comment]
Thanks for fixing this so quick.
