### ISSUE TITLE
Function name typo in the latest version of Magit?

### ISSUE THREAD

**Issue by Reagankm** [magit/magit#3596]
When I upgraded to the latest version of magit in Emacs, I got a Compile-Log message warning that "magit-section.el:1452:1:Warning: the function ‘cl-prin1-to-string’ is not known to be defined."

I tried creating my own fork and changing the name to 'cl-print-to-string' but got the same warning when compiling it locally.  

Magit version: Magit 20180921.1619, Git 2.16.2, Emacs 26.1, darwin

**Comment by npostavs** [comment]
> Emacs 26.1

Hmm, does <kbd>f1 f cl-prin1-to-string</kbd> not give you this:
```
cl-prin1-to-string is an autoloaded Lisp function in ‘cl-print.el’.

(cl-prin1-to-string OBJECT)

Return a string containing the ‘cl-prin1’-printed representation of OBJECT.
```

It's not available in Emacs 25 though (unless you install [GNU ELPA package cl-print](http://elpa.gnu.org/packages/cl-print.html)), so we should probably fall back to `prin1-to-string`.
