### ISSUE TITLE
Travis failing

### ISSUE THREAD

**Issue by tarsius** [magit/magit#3598]
Building magit's `master` branch currently fails on travis because the `master` Emacs build is unavailable. @npostavs could you please look into that?

Building `maint` also fails. Because of the other issue but also others. I am less concerned about that though.

**Comment by npostavs** [comment]
> Building magit's `master` branch currently fails on travis because the `master` Emacs build is unavailable.

It was due to the upload step of `npostavs/emacs-travis` timing out. I reran it, and now `emacs-master` is available again.

The real problem is that I delete the old binary before uploading the new one, which is just asking for trouble (as demonstrated here).

**Comment by npostavs** [comment]
> The real problem is that I delete the old binary before uploading the new one, which is just asking for trouble (as demonstrated here).

Should be mostly fixed, not 100% atomic (since I can't rename to existing name), but probably close enough (though I managed to break things again while try to fix this, thanks to a Github "feature" which prevents the rename operation from changing the file extension).
