### ISSUE TITLE
in log buffer, it's hard to distinguish two commits with a parent-child relationship, from two commits that are unrelated

### ISSUE THREAD

**Issue by offby1** [magit/magit#3602]
This might well be a dup of #2989.

Aanyway, run the following shell script, and follow its directions, to see what I'm talking about:
```
#!/bin/sh

# Create a repo with three commits: two on master, and one on an "orphan" branch.

repos=$(mktemp -d -t git-repoXXXXXX)

trap "echo clean up by deleting $repos." EXIT

# Master branch -- create first commit

cd $repos
git init
touch it
git add it
git commit -m "First commit"

# create child commit
echo "One more thing" > it
git add it
git commit -m "Child of first commit"

# Create orphan commit
git checkout --orphan orphan
touch orphan
git add orphan
git commit -m "I M N orphan"

pwd
echo "OK, now run magit-status on me, type "l a" (magit-log-all-refs) and see how it looks"

# 4697eb8 * master Child of first commit
# 65f03e4 * First commit
# 52c2b6d * orphan I M N orphan
```

Take a look at the magit-log buffer -- it shows the three commits, but doesn't make it at all clear that the "orphan" commit is indeed an orphan, whereas the "child" commit is indeed a child of the first commit.

I don't have any ideas for how this could be done, although the SVG ideas in the related issue would certainly solve this.

**Comment by phil-s** [comment]
Basically the same as:

    git log --all --graph --decorate --oneline

**Comment by tarsius** [comment]
I am aware of the issue and was planning on tackling it when tackling #2989. I have added a note about this to that issue now.
