### ISSUE TITLE
--allow-unrelated-histories flag for merging/pulling

### ISSUE THREAD

**Issue by saskenuba** [magit/magit#3606]
First I initiated a new repo locally and started committing some files, then I created a blank repo here on github with a README and a licence. When I set the remote using magit and tried to fetch and merge, I couldn't because of the unrelated histories error.

Can we have a flag for it on merge or pull? Kind of a dumb error but it would be useful since I had to go manually with the command line to do it.

**Comment by tarsius** [comment]
You can add that argument yourself as described [here](https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands).

**Comment by saskenuba** [comment]
Thanks! Feeling dumb now. Did not find it on my search. Closing.
