### ISSUE TITLE
Bug when staging

### ISSUE THREAD

**Issue by hlambda** [magit/magit#3608]
I made a post in [Emacs stackexchange](https://emacs.stackexchange.com/q/45087/6924) and discovered a possible bug in Magit.

-----------
Here are steps to reproduce the `ssue:

1. Start with an empty git repo and a file `test.org`
2. Do an initial commit with following contents:
```
Hello world
Hello world again
```

3. Change the contents to 
```
   Hello world  
example
  Hello world again  
```
4. `M-x magit-status` and set the flag `-w`, that is, `--ignore-all-space` (`D`, then pressing enter at `-w` and `g` would do this.)
5.  The diff would look like this:
```
modified   test.org
@@ -1,2 +1,3 @@
    Hello world  
+example
   Hello world again  
```
6. Try to stage the hunk and I'm greeted with the message that "the patch does not apply" and the magit-process buffer has 
```
git … apply --cached -p0 --ignore-space-change -
error: patch failed: test.org:1
error: test.org: patch does not apply
```
---------
One can stage the changes if the flag `-w` is unset, but, then the diff gets larger and it sort of defeats the purpose of the `-w` flat. 

I would be willing to help fix the bug if someone could guess what part of the code or what commit might be causing the issue.

-----
Version: Magit 20180928.1153, Git 2.17.0, Emacs 25.3.1, gnu/linux

**Comment by tarsius** [comment]
That is a limitation of Git not Magit. You are telling `git apply` to turn `B` into `C` but the file contains `A`. Your patch doesn't say how to turn `A` into `C`, so it doesn't apply. The `B => C` patch effectively is a lie.

Magit already unconditionally uses `git apply --ignore-space-change`. But that argument doesn't do what is needed here and there is no other whitespace related argument whose description suggests it could be of use here.

I found a way to make a lying patch apply: also use the `-U0` argument. The diff you will see as a result of this won't be the same, but in some cases it might not matter.

Based on that, it might be possible to do something about this in Magit. 

Given a diff

`git diff -w`
```diff
@@ -1,2 +1,3 @@
    Hello world  
+example
   Hello world again  
```

which actually should be

`git diff`
```diff
@@ -1,2 +1,3 @@
-Hello world
-Hello world again
+   Hello world  
+example
+  Hello world again  
```

Magit could turn that into what `git diff -w -U0` would have shown:

```diff
@@ -1,0 +2 @@
+example
```

It would be better if this were implemented in `git apply` itself though, so you might want to bring that up on the Git mailing list.

**Comment by hlambda** [comment]
@tarsius Thanks. I'll bring this up in the git mailing list.

**Comment by tarsius** [comment]
Please also ask if `this -U0` in

```
git diff -w | this -U0 | git apply --cached --ignore-whitespace --unidiff-zero -
```

already exists, either as part of `git` or separately.

**Comment by tarsius** [comment]
Nevermind, an appropriate `apply` argument already exists: `-C0`.

**Comment by hlambda** [comment]
Does Magit have an option to set this flag? I tried looking for a `M-x magit-apply-popup` and it doesn't exist.

**Comment by tarsius** [comment]
No it didn't and still doesn't, but now it automatically uses `-C0` when appropriate.
