### ISSUE TITLE
Add option for auto-filling long commit message lines (when viewing existing commits)

### ISSUE THREAD

**Issue by phil-s** [magit/magit#3610]
I often have to deal with commit messages which are just one massive line (typically entered on the command line via `-m`), and it's pretty annoying, but impractical to fix in the repository (certainly for historical commits).

Obviously I can enable `visual-line-mode` for the buffer when viewing such commits, but (a) it's annoying to need to do anything at all, and (b) it's annoying to have *other* things wrapping if I only wanted the commit message to be wrapped, so that's not a good solution IMO.

I've not thought this through too much, but I've just applied the following change as an initial experiment.

     (defun magit-insert-revision-message (rev)
       "Insert the commit message into a revision buffer."
       (magit-insert-section (commit-message)
         (let ((beg (point)))
           (magit-rev-insert-format "%B" rev)
           (if (= (point) (+ beg 2))
               (progn (backward-delete-char 2)
                      (insert "(no message)\n"))
             (goto-char beg)
             (save-excursion
               (while (search-forward "\r\n" nil t) ; Remove trailing CRs.
                 (delete-region (match-beginning 0) (1+ (match-beginning 0)))))
     +       (let ((fill-column 80))
     +         (fill-region (point) (line-end-position)))

It's not safe to `fill-region` the entire commit message, as there may be particular formatting; so while people *can* create multi-line messages with excessively long lines, I'm not sure that there's a sensible way to tackle that.

I tried using `fill-paragraph` at first, but found `fill-paragraph-handle-comment` was causing issues, so `fill-region` seems safer.  Maybe using `forward-paragraph` would be better than assuming the first paragraph is definitely going to be a single line, although that assumption accounts for the `-m` case at least.

**Comment by phil-s** [comment]
I think the paragraph version would be:

        (save-excursion
          (forward-paragraph)
          (let ((fill-column 80))
            (fill-region beg (point))))

**Comment by phil-s** [comment]
I suppose we could have choices for the user option as to what it should fill:

* `nil`
* `line`
* `paragraph`
* `message`

And I think it would make best sense to do nothing at all if the relevant portion of the message does not exceed `fill-column` at any point?

**Comment by tarsius** [comment]
I don't have an opinion on what kind of filling should be done -- it's likely that different messed up repositories (or even commits within the same repository) need different filling. Please work out the details and I will merge.

What I do care about is this has to be optional behavior that has to be enabled explicitly and that this is implemented in a separate function, called from `magit-insert-revision-message`. Users should probably be discouraged from enabling this globally for all repositories, so we shouldn't use an option and the doc-string of the variable should explain how to use `.dir-locals-2.el` to set it.

**Comment by tarsius** [comment]
I went with a rather simplistic approach.

**Comment by phil-s** [comment]
Oh, that was unexpected.  Cheers tarsius!
