### ISSUE TITLE
Stash selected files

### ISSUE THREAD

**Issue by villem** [magit/magit#3612]
Git 2.13 and later has a nice easy way to stash one file only (https://stackoverflow.com/questions/5506339/how-can-i-git-stash-a-specific-file#5506483)

My use case:
After I've put selected all relevant things of file X to index, I want to do  clean compile, so that there is no any changes in work tree for a file X.
Now I need to do I temporary commit for selected changes, stage rest of changes in the file X, stash index and Compile
Of course I can resort to command line, but that is not so elegant.

Thanks for Magit!!!

**Comment by kyleam** [comment]
duplicate: #3200

**Comment by tarsius** [comment]
> Now I need to do I temporary commit for selected changes, stage rest of changes in the file X, stash index and Compile

You could instead stash just the unstaged changes using <kbd>zw</kbd>.

**Comment by villem** [comment]
> You could instead stash just the unstaged changes using zw.

Sorry I failed to mention that I've got some another changes in work tree that I need to keep around, so that Is why only need to a selected files from worktree to stash. I tested git stash push a little bit myself and it seems that is also stash whole index along the selected files. So it is not perfect
