### ISSUE TITLE
Make may fail trying to export documentation to epub by default

### ISSUE THREAD

**Issue by vermiculus** [magit/magit#3614]
The target file may not exist at the line below. We should probably only publish to epub if this file exists.

https://github.com/magit/magit/blob/b8baec805dd6ca669a7dce50c4d39decd80ba15a/default.mk#L202-L204

Related #3579.

This is probably a fly rather than a bug; it can be easily worked around by customizing variables and only really impacts contributors who don't have this file.

**Comment by tarsius** [comment]
I am the only one who has the necessary permissions to successfully run the publish targets anyway...

**Comment by vermiculus** [comment]
Do those targets publish or just generate the documentation?

**Comment by tarsius** [comment]
`epub` creates `magit.epub`. The only targets that (depending on `PUBLISH_TARGETS`) depend on `epub` are `publish-manuals` and `release-manuals`. Those targets publish (and their dependencies generate).
