### ISSUE TITLE
Rebase popup offers invalid upstream ref

### ISSUE THREAD

**Issue by jamienicol** [magit/magit#3623]
When I open the rebase popup, with `r`, the `u` option it provides me is invalid for one of my remotes. (I'm sure `p` would also be wrong if it was the same remote.)

The remote setup is a bit strange. I use https://github.com/glandium/git-cinnabar to use a mercurial repository. And I have a custom fetch refspec, which is presumably causing issues.

Here are the relevant bits of my git config:
> [remote "mozilla"]
>     url = hg::https://hg.mozilla.org/mozilla-unified
>     fetch = +refs/heads/bookmarks/\*:refs/remotes/mozilla/\*
> [branch "wr-android"]
>     remote = mozilla
>     merge = refs/heads/bookmarks/central

Here is what magit shows me:
![magit-rebase](https://user-images.githubusercontent.com/1907488/47210790-ca22e700-d38b-11e8-8b74-00a3f003521b.png)

On the command line, `git rebase` and `git rebase mozilla/central` do the right thing. I'd expect magit to show "mozilla/central" as the `u` option, rather than "mozilla/bookmarks/central"

If I do press `u`, then I get the following error:
>   1 git … rebase mozilla/bookmarks/central
> fatal: Needed a single revision
> invalid upstream 'mozilla/bookmarks/central'

magit-version: Magit 20181015.1832, Git 2.17.1, Emacs 26.1, gnu/linux

**Comment by tarsius** [comment]
That's because of 54676736f16475bfbb180e272d7269f45af7971f, i.e. I was aware that this wouldn't work -- I just didn't expect it would matter.

**Comment by tarsius** [comment]
I am currently looking into embracing `@{upstream}` instead of re-implementing so much.

**Comment by tarsius** [comment]
Done with #3813. I did some limited testing to verify that those changes fix this issue (a lot of other things changed), but I tested with a repository that doesn't take hours to clone and that repository only had "branches" and no "bookmarks", but `git-cinnabar` fetches branches using a non-standard refspec too, and I could use those branches as usual despite that, so bookmarks should work too.
