### ISSUE TITLE
Reversing binary files doesn't seem to work

### ISSUE THREAD

**Issue by pmiddend** [magit/magit#3625]
`Magit 20180915.659, Git 2.19.1, Emacs 26.1, gnu/linux`

What I did: 

  - opened the commit log (`l l`)
  - selected a commit (`return`)
  - moved point to a binary file that was deleted by that commit (it was an `.ogg` file)
  - pressed `v`

Output:

```
  1 git … apply --reverse --reject -p0 --ignore-space-change -
Checking patch myfile...
error: cannot apply binary patch to 'myfile' without full index line
error: myfile: patch does not apply
```

**Comment by kyleam** [comment]
Related to #1742

The intention is for this to fail with an informative error: d0e04a14 (magit-reverse-files: do not attempt to reverse binary files, 2015-03-06).  It seems `magit-staged-binary-files` isn't detecting your file.

**Comment by pmiddend** [comment]
Oh, so it's somehow not possible at all to reverse binary files? Are there restrictions in git preventing this?

**Comment by kyleam** [comment]
> Oh, so it's somehow not possible at all to reverse binary files?

Not with `magit-reverse`.  There are a couple of other ways you could do it from Magit.  Call `magit-revert-no-commit` on the deletion commit, discarding any other reverted files if needed.  Or you could use `magit-file-checkout` with, say, point on the commit before the deletion commit, and then select the binary file that you want to resurrect.

> Are there restrictions in git preventing this?

To do this with git, the patch needs to be created with `git diff --binary`.  We wouldn't want to insert this into the buffer, and Magit's apply variants work with the text in the buffer.

**Comment by pmiddend** [comment]
Ah, I see, so the method I chose is indended for files that are then displayed in a buffer. Got it. So all that's needed is a better error message.

**Comment by kyleam** [comment]
> So all that's needed is a better error message.

I agree a more informative error message would be nice.

This shouldn't be too much work for revision buffers.  Something like:

```diff
diff --git a/lisp/magit-apply.el b/lisp/magit-apply.el
index e1fcc672..f6a33395 100644
--- a/lisp/magit-apply.el
+++ b/lisp/magit-apply.el
@@ -644,7 +644,9 @@ (defun magit-reverse-file (section args)

 (defun magit-reverse-files (sections args)
   (pcase-let ((`(,binaries ,sections)
-               (let ((bs (magit-staged-binary-files)))
+               (let ((bs (if (derived-mode-p 'magit-revision-mode)
+                             (magit-binary-files (car magit-refresh-args))
+                           (magit-staged-binary-files))))
                  (--separate (member (oref it value) bs)
                              sections))))
     (magit-confirm-files 'reverse (--map (oref it value) sections))
diff --git a/lisp/magit-git.el b/lisp/magit-git.el
index cde4f298..f913dce1 100644
--- a/lisp/magit-git.el
+++ b/lisp/magit-git.el
@@ -759,6 +759,13 @@ (defun magit-revision-files (rev)
   (magit-with-toplevel
     (magit-git-items "ls-tree" "-z" "-r" "--name-only" rev)))

+(defun magit-revision-binary-files (rev)
+  (--mapcat (and (string-match "^-\t-\t\\(.+\\)" it)
+                 (list (match-string 1 it)))
+            (magit-git-items "diff-tree" "-z" "--no-commit-id"
+                             "--numstat" "--ignore-submodules"
+                             revision)))
+
 (defun magit-changed-files (rev-or-range &optional other-rev)
   "Return list of files the have changed between two revisions.
 If OTHER-REV is non-nil, REV-OR-RANGE should be a revision, not a

```

But that doesn't cover diff buffers.  Doing so would bring it to three magit-*-binary-files variants or a combined function that handles three cases.  This doesn't mean it shouldn't be done, but it would require more time and thought than I've given it at the moment.
