### ISSUE TITLE
List unstaged and staged files in a helm-style popup

### ISSUE THREAD

**Issue by gondalez** [magit/magit#3628]
I often find myself wanting to open a helm file popup filled with only staged and unstaged files. I use this list to quickly search and open a file.

I can get this list via the magit status screen but to be able to hone the results with searching would be just that bit more enjoyable :)

**Comment by tarsius** [comment]
By the sound of it [`helm-ls-git`](https://github.com/emacs-helm/helm-ls-git) would be of use.
