### ISSUE TITLE
Allow using an editor different to the one found by "with-editor"

### ISSUE THREAD

**Issue by brainlessdeveloper** [magit/magit#3629]
I use Magit inside of Visual Studio Code:

![image](https://user-images.githubusercontent.com/16181067/47503319-17122c00-d86a-11e8-921c-439f579eb50b.png)

I want to edit commit messages using Visual Studio Code and not Emacs. I've found that Magit uses "with-editor" to find the correct `emacsclient`, but "with-editor" does not offer an option to use anything different than Emacs. I've tried the following:

```emacs-lisp
(setq with-editor-emacsclient-executable "/usr/bin/code")
```

But I need the `--wait` flag, and using spaces in the executable path doesn't work. This variable isn't even meant to be used like I'm trying to use it: it's meant to point to an `emacsclient` executable.

How can I make Magit use a completely different editor? I just want it to actually respect my `$EDITOR` env variable.

By the way: Magit is awesome, so awesome that I use it inside of Visual Studio Code. Thanks for that.

**Comment by tarsius** [comment]
> tarsius closed this in 7c68485 18 hours ago

I believe this addresses the issue (please see the commit message). I should have posted an update here but forgot.

**Comment by brainlessdeveloper** [comment]
It works wonders! Thank you so much.

I'm having a small issue:

- Try to amend a commit
- Visual Studio Code opens :+1: 
- Exit the Visual Studio Code session without saving
- Magit amends the commit anyway

Is cancelling the amend (or whatever commit attempt) a responsibility of Magit or the editor I use with it?

**Comment by tarsius** [comment]
> Is cancelling the amend (or whatever commit attempt) a responsibility of Magit or the editor I use with it?

The editor's. It must exit with a non-zero exit status and/or remove the file it was asked to edit. In other words it has to somehow communicate to `git` whether the user is done editing the message or else whether they *aborted*.

**Comment by brainlessdeveloper** [comment]
@tarsius Alright, thank you so much! Have a nice weekend.

**Comment by tarsius** [comment]
I had to revert this because something broke and I cannot figure out how it broke. See #3632 if you want to help.
