### ISSUE TITLE
Allow merging with unrelated histories

### ISSUE THREAD

**Issue by telmich** [magit/magit#3633]
When trying to merge a branch that has no common history, newer git versions respond with
`
From code.ungleich.ch:ungleich-public/ungleich-otp
 * branch            master     -> FETCH_HEAD
fatal: refusing to merge unrelated histories
`
The git command to allow this is 

`
(venv) [18:28] line:dev-token-otp-vault% git merge origin/master --allow-unrelated-histories 
Merge made by the 'recursive' strategy.
 README.md | 3 +++
 1 file changed, 3 insertions(+)
 create mode 100644 README.md
`
I know it is a rare thing, but it makes me leave magit/emacs from time to time, as newly created repos WITH a README on gitlab/github start with a different history than what I have locally.

I suggest a new switch in the merge menu ("-a") Allow unrelated histories (--allow-unrelated-histories)

**Comment by kyleam** [comment]
> I suggest a new switch in the merge menu ("-a") Allow unrelated histories (--allow-unrelated-histories)

You should be able to easily add that switch yourself: https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands#add-argument---ignore-all-space
