### ISSUE TITLE
Entering `magit-status` from within `ido-mode` does not work anymore

### ISSUE THREAD

**Issue by JulianKniephoff** [magit/magit#3634]
I have the following Emacs configuration:

```elisp
(ido-mode)

(define-key ido-common-completion-map
  [?\C-x ?g] 'ido-enter-magit-status)
```

With that, I should be able to enter `ido` by hitting `C-x C-f`, navigate to a git repository and then hit `C-x g`, to get to `magit-status`. And in fact, this worked for some time, but now it doesn't anymore, probably due to some update. Now, this just drops me to the standard `find-file` interface.

`magit-version` spits out the following:

```
Magit 20181024.2307, Git 2.19.1, Emacs 26.1, gnu/linux
```
And `ido` is apparently packaged with Emacs.

The behavior is reproducible in emacs with only `magit` in it and after having run the commands mentioned above.

**Comment by kyleam** [comment]
This should be fixed with Emacs's 12c77f6918 ([bug report](
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=31707)).

**Comment by drot** [comment]
This happens with `ivy-mode` as well.

**Comment by tarsius** [comment]
> This should be fixed with Emacs's 12c77f6918

Unfortunately the that commit did not make it into Emacs 26, so this command only works in Emacs 25 and how that I have updated it also in Emacs 27.

> This happens with `ivy-mode` as well.

What happens with `ivy-mode` as well? This issue is about not being able to go to the status buffer from an **Ido** prompt. That cannot happen when using **Ivy** because then you are using Ivy not Ido.

**Comment by kyleam** [comment]
> Unfortunately the that commit did not make it into Emacs 26

Right, or more specifically, 26.1.  It will be in 26.2.

**Comment by JulianKniephoff** [comment]
Cool, good to know, thanks! :smile:

**Comment by aksharvarma** [comment]
> > Unfortunately the that commit did not make it into Emacs 26
> 
> Right, or more specifically, 26.1. It will be in 26.2.

Shouldn't the documentation for this function specify this more precisely? 

The doc currently says the following:

> This command does not work in Emacs 26.  It does work in Emacs 25 and Emacs 27.

**Comment by tarsius** [comment]
I've updated the doc-string and some other stuff.
