### ISSUE TITLE
WIP mode features are enabled by default

### ISSUE THREAD

**Issue by nigredo-tori** [magit/magit#3639]
After an update (unstable MELPA), committing creates references that seem to be related to the WIP mode. The mode itself was not explicitly enabled, but it seems that [one of the last Magit changes](https://github.com/magit/magit/commit/ca1a696dd6ceb74572004965b8a7d310799ac944) enabled some part of it by default. This is extremely confusing and annoying for people who are not familiar with the WIP mode, even more so because getting rid of these references require the knowledge of some uncommon Git features (`git update-ref`), or some googling.

As a temporary workaround, customizing `magit-wip-merge-branch` to `nil` seems to have solved the issue for me.

1. what behavior you expected

    Commiting should not create additional references if the WIP mode was not explicitly enabled.

2. what behavior you observed

    WIP mode commits/references (`refs/wip/*`) are created/updated on each commit. These are visible in the log view.

3. and how we can reproduce the issue.

    For me it all started after the update on the new unstable version. My first commit after that was called "WIP" - not sure if that matters.

4. Magit version: `Magit 20181027.1216, Git 2.17.1, Emacs 27.0.50, gnu/linux`

Sorry for not reproducing the issue with a "clean" Emacs - I don't think there's much point in it for this issue.

**Comment by tarsius** [comment]
That wasn't intentional of course. I have pushed a fix. Thanks for the report.

**Comment by tarsius** [comment]
Forgot to mention the issue in the commit message. Here's the link: fa0e336ceaf0e508ff39a9c7443592d3ee0b28b2.
