### ISSUE TITLE
wip mode disrupt previous workflow

### ISSUE THREAD

**Issue by Silex** [magit/magit#3640]
Hello,

Since recently (today?) my git log looks like this:

```
9c00726 *   index/refs/heads/with-advisory-lock merge refs/heads/with-advisory-lock into index
        |\  
b713317 * \   merge refs/heads/with-advisory-lock into index
        |\ \  
00f6e01 * | | start autosaving index
507bb3e | | | *   wtree/refs/heads/with-advisory-lock merge refs/heads/with-advisory-lock into worktree
        | | | |\  
        | | | |/  
        | | |/|   
83f62e3 | | * | Silex/with-advisory-lock Add AdvisoryLock module
e48508a | | * | Silex/drop-old-versions Drop support for Ruby less than 2.3
b1960fe | | | *   merge refs/heads/with-advisory-lock into worktree
        | | | |\  
        | | |_|/  
        | |/| |   
c135c8d | * | | Add AdvisoryLock module
1ef607e | * | | Drop support for Ruby less than 2.2.10
        | |/ /  
1c11233 | | * start autosaving worktree
        | |/  
        |/|   
9534406 * | Add AdvisoryLock module
8c068fc * | Drop support for Ruby less than 2.2.10
        |/  
28c6f4d * Drop support for ActiveRecord less than 4.2
18ef0d4 | * origin/readme/data-integrity-advisory README: Add a note about data integrity
        |/  

```

That is, all sort of weird "autosaving index" with obscure `index/refs/heads` references. A week ago it only displayed the other branches.

I digged a bit and this looks like because of `magit-wip-mode` (which I did not enable). Maybe https://github.com/magit/magit/commit/fa0e336ceaf0e508ff39a9c7443592d3ee0b28b2 is the cause.

Anyway, I reach this view after pressing `l a` (log all refs), and I discovered I can press `l b` to get the same view as before, but I think this change is not intentional so I'm asking/reporting :wink: 

Also I'm not sure how to "clean" this view, right now I suppress the right files in `.git` but there's probably a better way.

**Comment by Silex** [comment]
> The change is intentional. See `magit-wip-merge-branch` in https://magit.vc/manual/magit/Wip-Modes.html. The intention always was that `l b` should be used for day to day work, and that `l a` should only be used when you actually want to look at "those other weird refs that various tools create for internal housekeeping and such".

Alright, I'll switch to `l b`

> There is
> ```
>        --exclude=<glob-pattern>
> ```
> > right now I suppress the right files in `.git` but there's probably a better way.
> 
> I don't know what that means.

Right, I think you missunderstood me. How do I *remove* the refs so `l a` does not show any of these `magit-wip` refs?

I understand I can disable `magit-wip-*` to avoid these refs appearing in my repo (not that I want that but I could), so my question is how to remove them once they are here? I deleted files in `.git/index/refs/heads/*` or some paths like this to removed the refs the first time I encountered them, then finally understood it was something magit created.

**Comment by tarsius** [comment]
> Right, I think you missunderstood me. How do I *remove* the refs so `l a` does not show any of these `magit-wip` refs?

I think you misunderstood me actually. To *exclude* the wiprefs from display only you can `--exclude=THEM`.

```elisp
(defun magit-log-all-except-wip (&optional args files)
  (interactive (magit-log-arguments))
  (magit-git-log (if (magit-get-current-branch)
                     (list "--exclude=refs/wip/*" "--all")
                   (list "HEAD" "--exclude=refs/wip/*" "--all"))
                 args files))
```

**Comment by kukhyun** [comment]
@Silex try this
`git update-ref -d refs/wip/index/refs/heads/master`
`git update-ref -d refs/wip/wtree/refs/heads/master`

**Comment by Silex** [comment]
@kukhyun: thanks, that is basically what I was doing but `rm .git/refs/wip/*/refs/heads/*` instead

@tarsius: yes I know, but I don't want to exclude them. Anyway @kukhyun answered me :smile: Thanks!
