### ISSUE TITLE
package install on windows not working

### ISSUE THREAD

**Issue by andersgb** [magit/magit#3642]
Using a fresh install of emacs 26.1 on windows, trying to install magit from melpa, I get the following
```
Install package ‘magit-20181029.1013’? (y or n) y
Contacting host: melpa.org:80
Parsing tar file...done
Extracting magit-popup-20181003.921/
Extracting magit-popup-20181003.921/magit-popup-pkg.el
Wrote c:/Users/AndersGranskogenBjør/AppData/Roaming/.emacs.d/elpa/magit-popup-20181003.921/magit-popup-pkg.el
Extracting magit-popup-20181003.921/dir
Wrote c:/Users/AndersGranskogenBjør/AppData/Roaming/.emacs.d/elpa/magit-popup-20181003.921/dir
Extracting magit-popup-20181003.921/magit-popup.info
Wrote c:/Users/AndersGranskogenBjør/AppData/Roaming/.emacs.d/elpa/magit-popup-20181003.921/magit-popup.info
Extracting magit-popup-20181003.921/magit-popup.el
Wrote c:/Users/AndersGranskogenBjør/AppData/Roaming/.emacs.d/elpa/magit-popup-20181003.921/magit-popup.el
Generating autoloads for magit-popup-pkg.el...done
Generating autoloads for magit-popup.el...done
Wrote c:/Users/AndersGranskogenBjør/AppData/Roaming/.emacs.d/elpa/magit-popup-20181003.921/magit-popup-autoloads.el [2 times]
Loading async...done
async--transmit-sexp: Writing to process: Invalid argument, emacs
```

Any ideas why I get this error? Is it a windows issue where the process is named `emacs.exe` not `emacs`?

**Comment by npostavs** [comment]
I can't reproduce this, even when I set a temporary home with the `ø` character in it. If you `(setq debug-on-error t)` before install do you get a backtrace?

**Comment by andersgb** [comment]
Hm, tried again today for backtrace and now it just worked.

I explicitly did a `package-refresh-contents` today before installing, could be that my package list was outdated when I first tried this. I see I now installed a more recent version too, namely `magit-20181029.1438` rather than `magit-20181029.1013` which failed yesterday.

Closing this, thanks for your help anyway @npostavs
