### ISSUE TITLE
coding-system-error cp65001

### ISSUE THREAD

**Issue by SunDawning** [magit/magit#3644]
After setting windows 10 (1809) to global utf-8:

- what behavior you expected
   Magit can be used normally.
- what behavior you observed
  ```
  Debugger entered--Lisp error: (coding-system-error cp65001)
    encode-coding-string("--no-pager" cp65001)
    (lambda (arg) (encode-coding-string arg (intern (format "cp%d" w32-ansi-code-page))))("--no-pager")
    mapcar((lambda (arg) (encode-coding-string arg (intern (format "cp%d" w32-ansi-code-page)))) ("--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "i18n.logOutputEncoding=UTF-8" "rev-parse" "--show-toplevel"))
    (if (and (eq system-type 'windows-nt) (boundp 'w32-ansi-code-page)) (mapcar (function (lambda (arg) (encode-coding-string arg (intern (format "cp%d" w32-ansi-code-page))))) args) args)
    magit-process-git-arguments(("rev-parse" "--show-toplevel"))
  ```
- and how we can reproduce the issue.
  ```
  (setf w32-ansi-code-page 65001)
  ```
- magit-version: 20181029.1438
- emacs-version: GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30
- Quick fix:
  ```
  (eval-after-load 'magit
    '(defun magit-process-git-arguments (args)
       (setq args (append magit-git-global-arguments (-flatten args)))
       (if (and (eq system-type 'windows-nt) (boundp 'w32-ansi-code-page))
           ;; On w32, the process arguments *must* be encoded in the
           ;; current code-page (see #3250).
           (mapcar (lambda (arg)
                     (encode-coding-string
                      arg
                      (if (= w32-ansi-code-page 65001)
                          'utf-8
                        (intern (format "cp%d" w32-ansi-code-page)))))
                   args)
         args)))
  ```
  Or:
  ```
  (unless (cl-member 'cp65001 coding-system-list)
    (define-coding-system-alias 'cp65001 'utf-8))
  ```

**Comment by tarsius** [comment]
It's hard for me to investigate this because I am not on Windows but it appears to me that you are trying to use a code-page that isn't known to Emacs out of the box.

>  ```
>  (unless (cl-member 'cp65001 coding-system-list)
>    (define-coding-system-alias 'cp65001 'utf-8))
>  ```

That doesn't look like a "quick fix", i.e. some hack, to me but like doing the thing that has to be done to teach Emacs about a new code-page. Or parts of it -- maybe you need to do more than that, I don't know.

> ```
> (setf w32-ansi-code-page 65001)
> ```

What's the value before you do that?

**Comment by SunDawning** [comment]
> It's hard for me to investigate this because I am not on Windows

If you are using window, you can set global utf-8 by referring to [Windows10 Insider Preview Build 17035 Supports UTF-8 as ANSI](https://news.ycombinator.com/item?id=15710685) .

> it appears to me that you are trying to use a code-page that isn't known to Emacs out of the box.

Under the premise of not modifying magit, I can solve the problem of "coding-system-error cp65001". I also found out that this is not a problem of magit. This is a problem of Emacs itself.

But it can also be solved by modifying "magit-process-git-arguments", which is the first method in my "Quick fix", so I gave feedback to magit instead of Emacs.

For users who normally use magit, if you encounter the same cp65001 problem, you can use the second method in "Quick fix", regardless of whether Emacs or magit fixes the problem.

> What's the value before you do that?

```
Welcome to the Emacs shell

~ $ pwd
c:/Users/simi/AppData/Roaming
~ $ chcp.com 
Active code page: 65001
~ $ (symbol-value 'w32-ansi-code-page)
65001
```

**Comment by tarsius** [comment]
> I also found out that this is not a problem of magit. This is a problem of Emacs itself.

In that case I am closing this.
