### ISSUE TITLE
Possibility to highlight refs based on regex

### ISSUE THREAD

**Issue by martin5233** [magit/magit#3645]
I had defined an advice, which allowed to use a different face for certain branches in the refs buffer, which worked until Magit 2.11. The code has changed a bit, such that this advice does no longer work. Therefore I would like to request a general feature, which allows to define the face of a ref in the refs buffer, e.g. by regex matching or similar.
I saw other people having to deal with many branches, so this might be a worthy extension not only for me.

**Comment by tarsius** [comment]
That already exists. Add an entry to `magit-ref-namespaces`.

**Comment by martin5233** [comment]
Wow, that's really great. I searched through the docs and the source code, but did not find this. Thanks a lot for this great tool!

**Comment by martin5233** [comment]
Unfortunately it doesn't seem to work in the refs buffer, it seems to be used only for log and diff, at least as of version 2.13.0.

**Comment by tarsius** [comment]
It works in refs buffers too now.

**Comment by martin5233** [comment]
Thanks a lot, it works without problems.

**Comment by martin5233** [comment]
That was too quick. It seems, that since your change it's not possible to create branches anymore. When calling magit-branch-and-checkout I receive the message 
    eieio-oref: Wrong type argument: (or eieio-object class), (commit unpushed status), obj
The version I tried is the current master branch (dc0a2e70).

**Comment by tarsius** [comment]
Could I have a full backtrace please?

(I cannot reproduce and suspect that this might be an unrelated regression.)

**Comment by martin5233** [comment]
This is strange: I had just switched back to v2.13.0, when you message arrived. Therefore I switched to master again and now I cannot reproduce the problem. Sorry.
