### ISSUE TITLE
Removing remote branches gives a false positive when there is a failure

### ISSUE THREAD

**Issue by hexmode** [magit/magit#3650]
I have a [phabricator](https://secure.phabricator.com/) managed repository on my own server.

When I went to delete the remote branch, the UI showed that the branch was deleted, but the remote rejected the action.

Here is the output of `magit-process`:
```
  1 git.exe … "push" "origin" ":master"
remote: *** PUSH REJECTED BY COMMIT HOOK ***        
remote: 
remote: DANGEROUS CHANGE: The change you're attempting to push deletes the branch 'master'.        
remote: Dangerous change protection is enabled for this repository.        
remote: Edit the repository configuration before making dangerous changes.        
remote: 
To https://phabricator.nichework.com/diffusion/7
 ! [remote rejected] master (pre-receive hook declined)
error: failed to push some refs to 'https://phabricator.nichework.com/diffusion/7'
```

Magit 20181104.1651, Git 2.19.1.windows.1, Emacs 26.1, windows-nt

**Comment by kyleam** [comment]
> When I went to delete the remote branch, the UI showed that the branch was deleted, but the remote rejected the action.

Just as background about what's happening here: When the push fails, Magit falls back to deleting the local ref `refs/remotes/REMOTE/BRANCH`.  It does so because a common reason the push fails is that the ref no longer exists on the remote (i.e., it would have been removed with `git fetch --prune`).  See c2cc9f21 (magit-branch-delete: fallback to delete tracking branch, 2016-09-26).  In this case, the failure isn't because the ref no longer exists, so `refs/remotes/REMOTE/BRANCH` ref would be restored with the next `git fetch REMOTE`.

**Comment by hexmode** [comment]
But the operation should not appear to succeed.  The user should be notified that the server reported a failure.  magit should probably ask if they want to just delete the local tracking branch and leave the remote branch alone.  Or, if you don't like the idea of prompting, that should be another option.

**Comment by tarsius** [comment]
We should only explicitly delete the local remote-tracking ref if the error message is something to the effect of "did not delete, does not exist".

**Comment by kyleam** [comment]
@hexmode
> But the operation should not appear to succeed.

I don't disagree.

>  magit should probably ask if they want to just delete the local tracking branch and leave the remote branch alone.

I'm not sure of a case when the user would want to delete the local tracking branch when the remote ref still exists.  It will just come back on the next fetch.

@tarsius 
> We should only explicitly delete the local remote-tracking ref if the error message is something to the effect of "did not delete, does not exist".

Hmm, I played around with that a bit:

```diff
diff --git a/lisp/magit-branch.el b/lisp/magit-branch.el
index 7adea0d0..042f9984 100644
--- a/lisp/magit-branch.el
+++ b/lisp/magit-branch.el
@@ -691,7 +691,17 @@ (defun magit-delete-remote-branch-sentinel (refs process event)
   (when (memq (process-status process) '(exit signal))
     (if (= (process-exit-status process) 0)
         (magit-process-sentinel process event)
-      (if-let ((rest (-filter #'magit-ref-exists-p refs)))
+      (if-let ((rest (-filter #'magit-ref-exists-p refs))
+               (process-buf (process-buffer process))
+               (section (process-get process 'section))
+               ((and (buffer-live-p process-buf)
+                     (with-current-buffer process-buf
+                       (and (oref section content)
+                            (save-excursion
+                              (goto-char (oref section start))
+                              (search-forward "does not exist"
+                                               (oref section end)
+                                               t)))))))
           (progn
             (process-put process 'inhibit-refresh t)
             (magit-process-sentinel process event)

```

One downside of that approach is that Git marks that message for translation.   I suppose the main alternative is  cross-checking with `magit-remote-list-branches/refs`.

**Comment by tarsius** [comment]
That's what I had in mind.

> One downside of that approach is that Git marks that message for translation.

That's unfortunate but acceptable to me. I guess we could add a variable with a list of those errors in other languages and users could add their own language's string if they really cared.

**Comment by tarsius** [comment]
Are you sure it actually works though? The actual implementation looks suspicious.

**Comment by kyleam** [comment]
> Are you sure it actually works though?

No, especially not if you're asking that question :/  While I would of course test more thoroughly before pushing, I tested it a bit last night and thought it worked, but perhaps I was mistaken or was testing only a restricted case that would work.

> The actual implementation looks suspicious.

Even if it does work, I don't want to be responsible for suspicious looking code :]

**Comment by kyleam** [comment]
I'm guessing the part the looked suspicious is the single value form at the end of the `if-let` spec.  Indeed that only works as of Emacs 26 (bug#28254).

**Comment by kyleam** [comment]
The troubles with my suggested patch continue: it only checks the last section, but multiple refs are allowed (and common when deleting from the refs buffer), so there may be multiple push sections. Eh... unhelpful patch/suggestion withdrawn :]

**Comment by tarsius** [comment]
@kyleam Could you please pick this up again?

**Comment by kyleam** [comment]
Sure, I'll take another look soon.

**Comment by tarsius** [comment]
Thanks! I am currently trying to squash some of the other bugs and flies and it looks like that's gonna be a lot of work.
