### ISSUE TITLE
Optionally treat discarding staged as unstaging

### ISSUE THREAD

**Issue by unhammer** [magit/magit#3655]
I've several times done `magit-discard` when I meant to `magit-unstage` in the Staged changes section. They're both kind of "remove something" so I guess that's why I get the keys messed up, but it's kind of dangerous, since when discarding something, it's not saved in the reflog. 

Would it be possible to have a `magit-discarding-staged-is-unstaging` option, so it's not possible to send a change straight from Staged to completely-gone?

**Comment by kyleam** [comment]
> but it's kind of dangerous, since when discarding something, it's not saved in the reflog.

With the default value of `magit-no-confirm`, the user has to confirm the discard, though.

**Comment by tarsius** [comment]
1. You can add `discard` to `magit-slow-confirm`, forcing you to type `y e s RET`, and/or
2. You can enable `magit-wip-mode`, making a first-aid kit available when you do shoot yourself in the foot.

**Comment by unhammer** [comment]
Oh, `magit-slow-confirm` should help, thanks :-)
(I stopped using wip since I got sick of it asking me to save other files from the same buffer each time I saved one file, don't know if there's a good solution around that since we do want that question for "regular" commits.)
 I guess there are enough alternative solutions that this can be closed.

**Comment by tarsius** [comment]
Setting `magit-save-repository-buffers` to `dontask` (and just do it), should help with that. I would make that the default but it would provoke unpleasant reactions from users who think that doing that would be wrong™.
