### ISSUE TITLE
🦄 I apologize for the spam about sourcerer.io

### ISSUE THREAD

**Issue by Silex** [magit/magit#3660]
Hello,

Just FYI, we received 2-3 emails from http://sourcerer.io, it's because by default "Notify GitHub followers about my code insights" is ticked.

No worries, but I was not sure you were aware of this so now you know :wink:

**Comment by tarsius** [comment]
I am very sorry about that. I saw the `☑ spam everyone` and unmarked it, but then I went to some other page before coming back and didn't check it was still unmarked.

So if you learned about me using sourcerer.io, then here's another interesting fact: I only did so for about three minutes. The information it managed to come up with was bordering on being completely useless.

**Comment by tarsius** [comment]
@anatolystansler @sergey48k It would be nice if you did not default to spam followers. It doesn't do anyone any good. Followers will be annoyed and developers will lose followers as a result.

**Comment by Silex** [comment]
Also the links @tarsius sent were 404 (probably because he removed the analysis), but then today I tried to use it because I was curious and it was not working for me (the github oauth is added but then login in fails with some red banner error at the top of the page).

**Comment by Silex** [comment]
> It would be nice if you did not default to spam followers

Or at least make this checkbox very visible. Like it is now we barely notice it.

**Comment by tarsius** [comment]
> we received 2-3 emails

What do you mean by "we" did you receive 2-3 mails to the same address or do you have multiple accounts all following me and received one per account?

@anatolystansler @sergey48k Don't send more than on mail. And give the user ten minutes to realize that they don't like this and close their account. Do not send any mail until the user had a chance to check whether your service produces useful data in their case and to delete the account again otherwise. Do not send any mail after the account has been deleted.

**Comment by Silex** [comment]
> > we received 2-3 emails
>
> What do you mean by "we" did you receive 2-3 mails to the same address or do you have multiple accounts all following me and received one per account?

Sorry, I thought it was 3 different emails to the same address but after verification it's just one email to one account (mine), but it was sent to all my github registered emails, which happens to be 3.

**Comment by tarsius** [comment]
@Silex Who send the emails? Github on behalf of the third-party or did Github hand over the email addresses to the third-party?

**Comment by Silex** [comment]
@tarsius it's from sourcerer.io (from: tarsius <join@followers.sourcerer.io>)

I forwarded you the email to the address listed in your profile.
