### ISSUE TITLE
Possible bug in magit-display-file-buffer-other-window?

### ISSUE THREAD

**Issue by dpapavas** [magit/magit#3662]
When configuring `magit-display-file-buffer-function` to use `magit-display-file-buffer-other-window`, hitting `RET` on a hunk in a diff buffer with the to-be-displayed buffer already visible has the result that the buffer is re-visited in the place of the diff buffer, instead of simply switching to the already visible buffer.

Looking at the definition of `magit-display-file-buffer-other-window` (I'm using version 2.90.0, but it is the same as [the current version of the file](https://github.com/magit/magit/blob/b45c0c350c944057954c787d3fa762f8b591ad5c/lisp/magit-diff.el#L1352)), this seems to be deliberate, but since this seems somewhat counter-intuitive and since it may conceivably be a copy-paste bug, as the function is basically an inversion of `magit-display-file-buffer-traditional`, where the inverse behavior makes more sense, I'm pointing it out here.

If this behavior is the desired one, feel free to close the issue with no further explanations.

**Comment by kyleam** [comment]
I suspect that behavior's unintentional.  As you say, it's likely a copy-paste bug, where part of the condition should have been dropped:

```diff
diff --git a/lisp/magit-diff.el b/lisp/magit-diff.el
index e033d1db..67413086 100644
--- a/lisp/magit-diff.el
+++ b/lisp/magit-diff.el
@@ -1354,7 +1354,7 @@ (defun magit-display-file-buffer-other-window (buffer)
 With a prefix argument display it in the current window.
 Option `magit-display-file-buffer-function' controls
 whether `magit-diff-visit-file' uses this function."
-  (if (or current-prefix-arg (get-buffer-window buffer))
+  (if current-prefix-arg
       (switch-to-buffer buffer)
     (pop-to-buffer buffer)))
```

**Comment by tarsius** [comment]
I agree and have pushed the fix.
