### ISSUE TITLE
Stashes and commit lists are not displayed after updating to 2.90.0

### ISSUE THREAD

**Issue by yasuhirokimura** [magit/magit#3664]
OS: FreeBSD 11.2-RELEASE amd64
Emacs: 26.1
git: 2.19.1
Magit: 2.90.0
dash.el: 2.14.1
Ghub: 3.0.0
GraphQL.el: 0.1.1
Magit-Popup: 2.12.4
treepy.el: 0.1.1
With-Editor: 2.8.0
Output of `M-x magit-version`: Magit 2.90.0, Git 2.19.1, Emacs 26.1, berkeley-unix

I'm a maintainer of FreeBSD Magit, Ghub, GraphQL.el, Magit-Popup treepy.el and With-Editor ports.
Recently I updated Magit port from 2.13.0 to 2.90.0 and faced problem.

![magit-bug 01](https://user-images.githubusercontent.com/5249848/48474488-012ad200-e83e-11e8-8110-321cccab85a9.png)
![magit-bug 02](https://user-images.githubusercontent.com/5249848/48474495-07b94980-e83e-11e8-8503-9beedd364975.png)

As you can see `Stashes`, `Unmerged into origin/local`, `Unpulled from origin/local` and `Recent commits` are not displayed. I tried `M-x magit-emacs-Q-command` debugging method. But same problem still happened.

Then is this bug of Magit and/or other libraries? Or did I do something wrong with porting them?

**Comment by AlecTroemel** [comment]
I'm seeing this exact same problem, on macOS

**Comment by fice-t** [comment]
They should appear when pressing <kbd>TAB</kbd> on them, right? I believe those sections default to hidden now.

@tarsius Perhaps hidden sections could have a customizable string displayed at the end of the heading, like `org-mode`'s `org-ellipsis`?

**Comment by yasuhirokimura** [comment]
> They should appear when pressing TAB on them, right? I believe those sections default to hidden now.

Does following sentences in 2.90.0 Release Notes explain it?

> Changed the order and the initial visibility of log sections in the
>  status buffer to optimize for "usefulness".  Previously the focus
>  was on making it more likely that the user did not ignore the less
>  frequently useful logs, but that was quite annoying because it got
>  in the way of the more frequently performed tasks.  #3518

I read them before I started porting but couldn't connect them with this issue.

But anyway I understand it isn't bug. So I close this issue.

**Comment by fice-t** [comment]
@tarsius Sounds good, but it should be noted that terminal users don't have a fringe, so perhaps an alternative should be provided for them.

**Comment by adamrt** [comment]
Thanks for all the hard work on the new release. I use stashes and rebase very frequently, both of which I use the Stash and Recent Commits section to verify. 

Is there a way to default back to the old behavior by default. I went through the #3518 diff but didn't notice a new variable or anything that managed this configuration.

Thanks again!

**Comment by kyleam** [comment]
> Thanks for all the hard work on the new release. I use stashes and rebase very frequently, both of which I use the Stash and Recent Commits section to verify.
> 
> Is there a way to default back to the old behavior by default.

Try configuring `magit-section-initial-visibility-alist`:

```lisp
(setq magit-section-initial-visibility-alist '((stashes . show)
                                               (unpushed . show)))
```

**Comment by adamrt** [comment]
@kyleam I apologize I didn't see that initially. I was looking for a new variable since I thought this was a new feature.

Thank you.
