### ISSUE TITLE
Git commit instant fixup/squash: allow to specify --keep-empty

### ISSUE THREAD

**Issue by pasqualesoldano** [magit/magit#3670]
When performing an instant fixup or squash on a previous commit, in case there is an empty commit between the target commit and the current head, the empty commit is implicitly removed as result of the command `git rebase -i --autosquash --autostash`.
This behaviour can modified to keep empty commits by adding the `--keep-empty` option to `git rebase`.

It would be nice to add an option to `magit-commit-instant-fixup/squash`, so that empty commits can possibly be preserved.

**Comment by luknax** [comment]
I think it is a good idea, I had the same issue in the past and I had to switch to a standard interactive rebase.

**Comment by kyleam** [comment]
> It would be nice to add an option to `magit-commit-instant-fixup/squash`, so that empty commits can possibly be preserved.

Hmm, for the `commit-instant` variants, I'm not sure we need to add the option.  I don't see a reason to not use `--keep-empty` unconditionally.

**Comment by kyleam** [comment]
> I don't see a reason to not use `--keep-empty` unconditionally.

The one reason I considered was the case where the fixup/squash completely reverses the target commit.  Would we be missing out on an arguably more useful error message if we used `--keep-empty` unconditionally?  But it seems like the current variants will already keep the empty commit in this case, so there should be no change in behavior here if we add `--keep-empty` in `magit-commit-squash-internal`.

**Comment by AndreaCorallo** [comment]
> Hmm, for the `commit-instant` variants, I'm not sure we need to make it optional. I don't see a reason to not use `--keep-empty` unconditionally.

Agree on that, using `--keep-empty` always in this case looks like a sane default behavior.

**Comment by pasqualesoldano** [comment]
I also agree with making `magit-commit-squash-internal` always use `--keep-empty`, I think this behaviour is sane considering the use case of `magit-commit-instant-fixup/squash`.

**Comment by tarsius** [comment]
I also agree and would even go one step further and do the same for `magit-rebase-autosquash`.

**Comment by kyleam** [comment]
> would even go one step further and do the same for `magit-rebase-autosquash`

Makes sense, and the PR looks good to me.

**Comment by pasqualesoldano** [comment]
Thanks a lot for the quick response and fix. Cheers.
