### ISSUE TITLE
By default, magit-status should complete on all directories

### ISSUE THREAD

**Issue by vanicat** [magit/magit#3673]
Hello, and thanks for your work

I'm forwarding a bug I receive on the magit debian package (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=914137).

The problem, as I see it, is that the new completion for `magit-status` make discovering magit harder: you have to configure something before `magit-status` is able to discover your git repositories.

May be, by default, `magit-repository-directories` should be nil, and `magit-read-repository` should complete on all directories when `magit-repository-directories` is nil.

Also, the documentation of `magit-status` should refer to `magit-repository-directories`: I had to read `magit-status` code source to find about it.

Thanks,
Rémi.

**Comment by kyleam** [comment]
> I'm forwarding a bug I receive on the magit debian package

Thanks.  I was just in the process of opening an issue to discuss this change in behavior.

> The problem, as I see it, is that the new completion for `magit-status` make discovering magit harder: you have to configure something before `magit-status` is able to discover your git repositories.

That description is a bit off.  It is relevant for *non*-git repositories.

> May be, by default, `magit-repository-directories` should be nil,

It was nil prior to f77d1158 (magit-repository-directories: Add some default directories, 2018-10-24).

The previous behavior with vanilla Magit: If a user calls `magit-status` in a non-git repo, they get prompted to read a directory, with the default being the current non-git directory, and then upon selecting that, they get asked whether they want to initialize a repository.

The current behavior with vanilla Magit: If a user calls `magit-status` in a non-git repo and their ~/.emacs.d is a git repo, they get prompted with one candidate [*] (.emacs.d, the repo found using `magit-repository-directories`).  

They can still initialize the new repo with `C-u C-u magit-status` or by calling `magit-init` directly, but it is a change in behavior for users (me, at least) that have come to expect that a plain `magit-status` call in  a non-git directory can be used to initialize a new repo.

[*]: or more, if they have repos under ~/.emacs.d/lib/

**Comment by vanicat** [comment]
The 21 November 2018, Kyle Meyer wrote:


[...]

> That description is a bit off.  It is relevant for *non*-git repositories.

Yes, I forgot the common « run magit from a file in git » use case.

[...]

> They can still initialize the new repo with `C-u C-u magit-status` or by calling `magit-init` directly, but it is a change in behavior for users (me, at least) that have come to expect that a plain `magit-status` call in  a non-git directory can be used to initialize a new repo.
>

In my way of using magit, the problem is not about initializing a repo, but about finding an already existing one.

I very often start by running magit-status before opening any file, to check if everything is correctly committed before doing any change, or to pull changes from upstream before doing my changes. (I even lurk on some repos, where I pull and then look at the log).

In this use case, being able to find any git repository in any directory is very useful. Obviously I can (and I will) configure `magit-repository-directories`, but new user will be put off by not (easily) been able to find  their repos (and yes, I now that `C-u C-u M-x magit-status` do it)

**Comment by kyleam** [comment]
> In my way of using magit, the problem is not about initializing a repo, but about finding an already existing one. I very often start by running magit-status before opening any file [..]

After reading this description and going back to your initial post, I realize my reading was off.  Sorry. My initializing description, then, is another example where the new `magit-repository-directories` default may lead to an undesirable change in behavior for some users.

**Comment by tarsius** [comment]
I have reverted that commit and updated the documentation.

**Comment by tarsius** [comment]
Ups, forgot the release notes entry.
