### ISSUE TITLE
Note and commit editing should behave differently

### ISSUE THREAD

**Issue by nertpinx** [magit/magit#3676]
When editing notes, magit warns me if second line is not empty (and uses the font-faces accordingly as well), the same way as commit editing works.  However (and I hope my assumption is correct), there is no reason for notes to start with a subject/summary (one line), then an empty line and continue with the full description.  Feel free to correct me if I'm using notes incorrectly, though.

How to reproduce:

    M-x magit-status RET
    T T
    write a multi-line note.

Version: `Magit 20181004.1127, Git 2.19.2, Emacs 26.1, gnu/linux`

**Comment by tarsius** [comment]
Done. See `git-commit-need-summary-line`'s doc-string.
