### ISSUE TITLE
wrong add-to-list 'with-editor-file-name-history-exclude

### ISSUE THREAD

**Issue by rurban** [magit/magit#3678]
latest magit git, with emacs 26.1

`add-to-list` requires the symbol to be defined already, but `with-editor-file-name-history-exclude` is not.
use push or check it before using it.

broken: lisp/git-rebase.el, lisp/git-commit.el

**Comment by tarsius** [comment]
Both of these libraries require `with-editor` *before* using this variable, so it should be defined. Also nothing changed here lately and nobody else is having issues with this.

**Comment by rurban** [comment]
Interesting. I'm having with-editor-20181103.2149 with `(defvar with-editor-file-name-history-exclude nil ...) so it should have been defined.
But I also had ./elpa/with-editor-20151209.732/ and ./elpa/with-editor-20170111.609/, so this could have been it.
