### ISSUE TITLE
Toggling diff file filter doesn't work with --follow

### ISSUE THREAD

**Issue by articuluxe** [magit/magit#3680]
Using latest magic, execute `magit-log-buffer-file` in a git-controlled buffer.  The history of commits affecting that file shows, but no longer restricted to that file.  

In the magic-log buffer, select a diff that affects more than that one file.  All of the diff's show.  Hit 'D' to bring up the diff-refresh popup; hit F to toggle file filter: there is no change, the message shown is:
'No diff file filter to toggle'

**Comment by tarsius** [comment]
I cannot reproduce any of that.

Make sure you do not have two versions of Magit installed and end up loading the old one.

**Comment by articuluxe** [comment]
It is not that, but the fact that I've added "--follow" to `magic-log-arguments`.  When I remove it, the expected behavior resumes (file filters work).

Any idea what the correlation is between these two?

**Comment by articuluxe** [comment]
I don’t think so. I invoke log-buffer-file from a single file. Without —follow, only that 1 file’s changes are shown.

**Comment by kyleam** [comment]
> Hit 'D' to bring up the diff-refresh popup; hit F to toggle file filter: there is no change, the message shown is:
> 'No diff file filter to toggle'

OK, I can reproduce that, even with 5d662349 (magit-revision-toggle-file-filter: generalize and rename, 2017-07-23), which introduced `magit-diff-toggle-file-filter`.  This limitation now feels vaguely familiar, but perhaps I'm mistaken. I won't be able to dig until deeper (my) tonight.

**Comment by kyleam** [comment]
> This limitation now feels vaguely familiar, but perhaps I'm mistaken.

Right, probably b44f680e (magit-show-commit: don't use log's file restriction with --follow, 2017-07-23).

https://github.com/magit/magit/blob/b14a7a2053498eca5d9dc68bab7b5330e788f8ae/Documentation/magit.org#L3107-L3110

**Comment by kyleam** [comment]
[sorry, posts crossed]

> So I think what we should do is to use the `--follow` argument when showing a diff from a log that also used `--follow`.

Ah, I think propagating --follow to the diff call just didn't occur to me, given I wrote

```
To avoid showing an empty diff for file renames in this situation,
ignore the log's file restriction when --follow is present in the
log's arguments.
```

**Comment by kyleam** [comment]
> The only commit that seems to benefit from dropping the file restriction is the commit that renamed the file. For all other commits the result is worse.

The goal actually wasn't to change how the rename commit is displayed.  It's to avoid displaying empty diffs for all the commits before the rename, since they'd be passed a pathspec that doesn't exist. 

Having time to look at this in more detail, I see that your comment about using `--follow` restricted to how the rename commit is displayed.  However, that still leaves the problem of the prior commits being empty. 

Take the following history (script to generate below):

```
$ git log --pretty=oneline --numstat --follow -- foonew | git name-rev --stdin
1fdfdd3e2f76666f04cb39cc9f4997d9b1aeb697 (master) change bar and foo new
1	0	foonew
329b80fe6133e3ffa1ba60843948738b027925dc (master~1) rename foo
0	0	foo => foonew
c008d69c5fc8edf0d8884ed7affdce896153b506 (master~2) change foo bar
1	1	foo
fdfd1107dae81558d37e26e91370309ddb25d6a8 (master~3) foo bar
1	0	foo
```

So the rename happened at master~1.  Along the lines of what you mention, `git show --follow master~1 -- foonew` will show the rename, while dropping `--follow` just shows a new file. But if I show the *previous* commit with `--follow` and the new pathspec (`git show --follow master~2 -- foonew`), it is still empty.

(I wasn't even aware that `git-show` would take a `--follow` argument before you mentioned it, so I might very well be missing something, though).

<details>
<summary>script</summary>

```sh
#!/bin/sh

set -eux

tdir=$(mktemp -d --suffix=-magit-testing)
git init $tdir
cd $tdir
git commit --allow-empty -mroot

echo foo >foo
echo bar >bar
git add foo bar && git commit -m"foo bar"

echo change-foo >foo
echo change-bar >bar
git add foo bar && git commit -m'change foo bar'

git mv foo foonew
git add foonew && git commit -m'rename foo'

echo more >>bar
echo more >>foonew
git add bar foonew && git commit -m'change bar and foo new'
```

</details>

**Comment by tarsius** [comment]
@kyleam Could you please pick this up again?

**Comment by kyleam** [comment]
Sure, I'll take another look soon.

**Comment by kyleam** [comment]
Unfortunately looking at this with fresh eyes didn't reveal any clean solutions.  The best route I can think of is adding an option that controls whether the diff honors the log's file restriction when `--follow` is given.  (I'll put together a PR for this unless there are objections.)

---

To summarize: The core issue is that, when the log is created with `--follow` and there is a rename event, revision buffers _before_ the rename will have an empty diff if we use the file restriction.  (Passing `--follow` to `git show` doesn't result in a useful diff being shown for these pre-rename commits.)

So we can

1. honor the file restriction and have empty diffs for commits before the rename

2. not honor the file restriction

   This is the approach of b44f680e (magit-show-commit: don't use log's file restriction with --follow, 2017-07-23).


The key differences:

  * Both of these could confuse users in different ways.  With *1*, users may be confused about why they are seeing empty diffs.  With the *2*, users may be confused about why the restriction isn't honored.

  * The frequency of confusion may differ.  With *1*, the empty diffs are shown only when there are actual renames.  With *2*, the file restriction isn't honored any time `--follow` is used, which the user may use liberally despite there not actually being renames.

  * *1* removes desired information, while *2* provides more than desired.

I still lean towards *2* (which isn't surprising, given my b44f680e).  But I could see how users would weigh things differently, particularly based on  whether they use `--follow` liberally.

**Comment by tarsius** [comment]
Nice analysis, thanks! It might be even more important than giving users an option to choose the lesser evil. Please go ahead and add the option, explaining all this in the doc-string.
