### ISSUE TITLE
magit-which-function doesn't seem to be working properly

### ISSUE THREAD

**Issue by agzam** [magit/magit#3691]
This isn't of great importance, just posting it here as fyi. If I have time, maybe I'll dig into this myself. 

`magit-log-trace-definition` has stopped working for me, so I had to see why, it seems `magit-which-function` doesn't work for some languages, in my case Clojure and Lua.

As a workaround for `magit-log-trace-definition` I temporarily did this: `(setq magit-log-trace-definition-function 'which-function)`

**Comment by kyleam** [comment]
I tested in lua mode and can reproduce your issue.  I can never remember the details of imenu, but looking at it quickly, `magit-which-function` relies on `imenu-extract-index-name-function` being defined, but some modes don't use this mechanism.  (I think lua mode defines `imenu-generic-expression` as a alternative.)

**Comment by tarsius** [comment]
`magit-which-function` should use `imenu-generic-expression` too. Seems I overlooked that.

Please try the `fix-3691` branch.

**Comment by tarsius** [comment]
It's actually a bit more complicated than that...

**Comment by tarsius** [comment]
The old implementation was completely broken and I have decided to go with an inefficient but reliable approach instead of trying to outsmart Imenu.
