### ISSUE TITLE
Solarized dark diff faces differ in GUI and iTerms2 with same config

### ISSUE THREAD

**Issue by srustamo** [magit/magit#3694]
Expected same faces in GUI and iTerm2. They differ, see screenshots.

Magit 20181208.1559, Git 2.19.1, Emacs 26.1, darwin
GUI screenshot:

<img width="878" alt="screenshot 2018-12-12 14 47 24" src="https://user-images.githubusercontent.com/749813/49862993-2997f300-fe21-11e8-80da-f345aaf4975d.png">

iTerm2 screenshot:
![screenshot 2018-12-12 14 47 33](https://user-images.githubusercontent.com/749813/49863036-3f0d1d00-fe21-11e8-9c33-d876698f7c5a.png)

Also raised this issue in Solarized repo:
https://github.com/bbatsov/solarized-emacs/issues/319

**Comment by tarsius** [comment]
> Also raised this issue in Solarized repo:

Closing as a duplicate of that then.
