### ISSUE TITLE
Missing autoload for `magit-log-popup`

### ISSUE THREAD

**Issue by Alexander-Shukaev** [magit/magit#3695]
https://github.com/magit/magit/blob/e50dac59e4d608e807c69cd1e231a30cd4be1433/lisp/magit-log.el#L494-L496

**Comment by Alexander-Shukaev** [comment]
Thanks! 👍

**Comment by Alexander-Shukaev** [comment]
After #3728, we now have only `magit-log`, i.e.:

```emacs-lisp
(define-transient-command magit-log ()
  "Show a commit or reference log."
  ...
```

Is there any particular reason why it's not marked as `autoload` now?

**Comment by tarsius** [comment]
I've removed them by mistake, probably during a rebase. Added them back now.
