### ISSUE TITLE
Remove ghub, treepy, graphql from magit as dependencies

### ISSUE THREAD

**Issue by atomontage** [magit/magit#3699]
Since Forge exists now, I see no reason for these extra dependencies to be part of magit.
Going through the source, it seems most of these dependencies aren't used at all. I can only
see ghub used by magit-collab, which also looks to be redundant now. I would assume that
many are using magit purely as an interface to git and do not interface with Github/Gitlab/etc
at all through Emacs.

Is there interest for such a change? Removing unnecessary dependencies makes the installation
process faster, provides less external libraries for me to keep track of, makes the code easier to understand
and is always a win in my book.

**Comment by tarsius** [comment]
That was long coming (note that 51d562f0e5870254cd1afd7c03ad495a4911a6c4 is four months old) but I first had to release Forge and then let it sit for a few days to see how things go.

After some bug fixes it works well enough for these commands to be removed from Magit. Some more work is required on Forge before Magit can be released though. That way users who used these commands but are having difficulties with Forge can stay on the last release for a while.
