### ISSUE TITLE
Per-repository settings of fields like signoff

### ISSUE THREAD

**Issue by Profpatsch** [magit/magit#3701]
According to https://github.com/magit/magit/issues/1524, it is possible to set defaults, for example always enable the `signoff` flag by default.

When I use `C-c C-c` in that manner, it sets the defaults *globally* instead of per repository.
Different repositories have different policies of whether e.g. `Signed-Off-By` fields are required, so it would be nice to be able to configure it per repository.

**Comment by tarsius** [comment]
I plan to do that, see #2993.
