### ISSUE TITLE
Please run `git remote prune origin` in magit-refs buffer when pressing g

### ISSUE THREAD

**Issue by wvxvw** [magit/magit#3709]
When someone tries to refresh the refs buffer, they expect it to reflect the situation in the origin (beside other things).  For no reason, Git itself doesn't update this information if you do a fetch or similar... so, this needs extra work and fixing.  You already have the list of all origins, so it would be nice if refresh in this buffer would also synchronize your local view with the actual state of the origins.

Right now, if your colleague working on the same repository deleted a branch, you will never know it is gone, until you try to pull it / delete it etc, which confuses people and, sometimes will result in you restoring the branch deleted by your colleague from your (typically incomplete) history, so once the other person sees it they will be really puzzled about what had happened.

**Comment by tarsius** [comment]
You can configure Magit to always prune when fetching: `f` (enter popup), `- p` (set `--prune`), and finally `C-x C-s` (save the arguments).

> For no reason, Git itself doesn't update this information if you do a fetch or similar...

It makes it less likely that accidental deletions propagate unnoticed.

> When someone tries to refresh the refs buffer, they expect it to reflect the situation in the origin (beside other things).

What refreshing as always done in this and other buffers is to update to reflect the situation in the local repository.  *That* is what most users would expect and to instead perform a destructive operation would be very surprising and dangerous.

So I won't add the requested feature, but you can easily implement it using `magit-post-refresh-hook`.

**Comment by wvxvw** [comment]
You probably don't understand what `git remote prune origin` does...

It doesn't do anything destructive in the remote repository. It
synchronizes your *local* refs with the remote refs, taking *remote*
as the source of truth, and updating the local to reflect it.  Thus,
it doesn't do any destructive changes at all, neither locally nor
remotely.  The functionality of Git is just wrong when it does a
fetch, it should've also fetched the refs, but... it doesn't.  And I'm
just too tired of Git's boolshit to try to fight it.

Think about this operation as cache invalidation, all it does is it
instructs to invalidate the local cache of remote refs, which it
should've been doing by default anyways.

**Comment by tarsius** [comment]
> You probably don't understand what `git remote prune origin` does...

Every time I disagree with you, things escalate quickly. I do not want to do this again.

**Comment by tarsius** [comment]
Note to others: yes the above is not that bad, but in my experience doubling down on your position results in a highly unplesant conflict with this person.
