### ISSUE TITLE
Implement 'git update-index --skip-worktree'

### ISSUE THREAD

**Issue by kschwarz1116** [magit/magit#3710]
As far as I can tell this feature does not exist. Often, while developing, I make changes for testing which I have no intent of committing. The common use-case here is [config files](https://medium.com/@igloude/git-skip-worktree-and-how-i-used-to-hate-config-files-e84a44a8c859). Rather than these changes clogging up the status buffer, I would like to group them separately. Git allows for this through `git update-index --skip-worktree <file>`. I would like to:
1. Be able to mark a file as `skip-worktree`
2. See all `skip-worktree` files from the status buffer, along with their difference from the index.
3. Remove a file from the `skip-worktree` list.

Willing to help with implementation if you can give me a high-level overview of what the code change might look like!

**Comment by tarsius** [comment]
I've implemented this myself now.

To add the list to the status buffer use something like:

```lisp
(magit-add-section-hook 'magit-status-sections-hook
                        'magit-insert-skip-worktree-files nil t)
```

I have added the new commands `magit-{,no-}skip-worktree` to the `magit-gitignore` transient, but disabled them by default. You can enable them as described [here](https://magit.vc/manual/transient/Enabling-and-Disabling-Suffixes.html), or you can give them your own key bindings.
