### ISSUE TITLE
unused variable name magit-view-git-documentation in message

### ISSUE THREAD

**Issue by GregorZattler** [magit/magit#3712]
Magits info pages contain references to git documentation.  When I follow such link in emacs info browser via RETURN, the specified git documentation is not found but emacs shows

Invalid value for ´magit-view-git-documentation´ 

in the echo area.

But there is no variable magit-view-git-documentation in Magit version 20190110.1553, Git 2.19.1, Emacs 27.0.50, gnu/linux.

The message is part of function Info-follow-nearest-node--magit-gitman in magit-utils.el and I think it should reference magit-view-git-manual-method instead.

In my case setting magit-view-git-manual-method to 'man' helped: The message is not shown instead I see the manual page for the respective git command.

Thanks for providing magit, Gregor

```diff
diff --git a/lisp/magit-utils.el b/lisp/magit-utils.el
index 1ca051fb..c3a18b00 100644
--- a/lisp/magit-utils.el
+++ b/lisp/magit-utils.el
@@ -1093,7 +1093,7 @@ or (last of all) the value of EXP."
               (`woman (require 'woman)
                       (woman (match-string 1 node)))
               (_
-               (user-error "Invalid value for `magit-view-git-documentation'")))
+               (user-error "Invalid value for `magit-view-git-manual-method'")))
           (funcall fn fork)))
     (funcall fn fork)))
```

**Comment by kyleam** [comment]
Thanks for catching that!
