### ISSUE TITLE
magit-branch-pull-request doesn't work as described

### ISSUE THREAD

**Issue by floli** [magit/magit#3713]
Hello,

https://magit.vc/manual/magit/The-Branch-Popup.html describes `magit-branch-pull-request`, however, this function does not seem to be present in `Magit 20190113.1949, Git 2.20.1, Emacs 26.1, gnu/linux`.

I am not sure, if this is documentation problem, and I need additional packages or if the functionality should be present in magit.

Thanks!

**Comment by vermiculus** [comment]
It's possible the docs are out of date but it is probably related to the 'can't make a major release quite yet' issue.

I bet this functionality was moved to Forge.

**Comment by tarsius** [comment]
Yes, that command has been removed in favor of `forge-branch-pullreq` from the Forge package announced [here](https://emacsair.me/2018/12/19/forge-0.1).

The manual at that location should be updated when I big change is made on `master`. I forgot to do it this time around. Just pushed an update but it might take a while until the cache is invalidated.
