### ISSUE TITLE
Add support for `git push --push-option=<option>`

### ISSUE THREAD

**Issue by drrlvn** [magit/magit#3717]
GitLab added a feature that allows skipping the CI by specifying the `ci.skip` push option to `git push`:
https://about.gitlab.com/2019/01/22/gitlab-11-7-released/#skip-ci-builds-during-git-push

I couldn't find a way to specify `--push-option` or `-o` to `git push` using magit and also couldn't find another feature request asking for it.

**Comment by kyleam** [comment]
> I couldn't find a way to specify `--push-option` or `-o` to `git push` using magit

Have you tried to add that option with `magit-define-popup-option`?

https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands

**Comment by drrlvn** [comment]
Welp, I didn't read that page carefully enough (I guess no matter how big and bold you put notices, people just ignore them...)

I'll use that in my config, sorry for wasting your time.

**Comment by kyleam** [comment]
No worries.  And plus your post taught me and probably others about GitLab's new feature :]

**Comment by drrlvn** [comment]
Actually I tried to add this but ran into a small problem and would love some help.

I could just add:
```elisp
(magit-define-popup-option 'magit-push-popup ?o "Set push option" "--push-option=")
```

But `--push-option` can be passed multiple times to `git push` and this wouldn't allow that.

Should I use `magit-define-popup-variable` instead?
I couldn't find examples for that, a nudge in the right direction would be great!

**Comment by kyleam** [comment]
> But `--push-option` can be passed multiple times to `git push` and this wouldn't allow that.

There's not an easy way to repeat options in popups.  At the moment, you'd have define a reader that uses something like `completing-read-multiple` and then make deeper changes to Magit (or a custom command) so that, somewhere between the popup invocation and the `git push` call, the value is converted into a repeated option.  The main place that does this sort of massaging (though not with a true option) is the log and diff processing of files (`=f`).  gh-1756 discusses repeated options a bit more.

I don't recall whether additional support for repeated arguments is something planned for magit-popup's successor, [transient], though I don't see a mention of that when doing a quick scan of gh-2957.  (I'm not very familiar with transient at the moment, though, so it might even already be possible.)

[transient]: https://github.com/magit/transient

**Comment by drrlvn** [comment]
I see, then for now I'll use a simple option and use the command-line if I ever need multiple instances.

Thank you very much for the detailed explanation!

**Comment by ldeck** [comment]
@drrlvn I assume there’s a common set of push options you typically might use.

So these can be defined as optional switches which can be toggled. e.g.,
```
(magit-define-popup-switch 'magit-push-popup ?S "Skip gitlab pipeline" "--push-option=ci.skip”)
...
```

Then if you do need some other ad-hoc switches to git push, I wonder if it make sense to add an option to allow appending arbitrary options. Would this work?
```
(magit-define-popup-option 'magit-push-popup ?O "Set extra push option #1" "--push-option=“)
(magit-define-popup-option 'magit-push-popup ?P "Set extra push option #2" "--push-option=“)
```

**Comment by chaoflow** [comment]
magit switched to [transients](https://magit.vc/manual/transient/Modifying-Existing-Transients.html), the following adds switches after the last default switch ``-u`` (in the Arguments block of the magit-push transient), visible on level 1:

```lisp
  (transient-append-suffix 'magit-push "-u"
    '(1 "=s" "Skip gitlab pipeline" "--push-option=ci.skip"))
  (transient-append-suffix 'magit-push "=s"
    '(1 "=D" "DEBUG" "--push-option=ci.variable=DEBUG=1"))  ;; no special meaning for gitlab
  (transient-append-suffix 'magit-push "=D"
    '(1 "=V" "Set CI variable" "--push-option=ci.variable="))  ;; Will prompt, can only set one extra variable
  (transient-append-suffix 'magit-push "=V"
    '(1 "=O" "Set push option" "--push-option="))  ;; Will prompt, can only set one extra push option
```

**Comment by chaoflow** [comment]
See https://docs.gitlab.com/ce/user/project/push_options.html for further options.

**Comment by anarcat** [comment]
i did this in magit:

```
;; in Debian: elpa-magit
;;
;; severely out of date, see https://bugs.debian.org/elpa-magit (bug #TBD)
(use-package magit
  :bind (("C-x g" . magit-status)
         ("C-x C-g" . magit-status)
         ([f6] . anarcat/magit-commit-buffer))
  :config
  ;; cargo-culted from https://github.com/magit/magit/issues/3717#issuecomment-734798341
  ;; valid gitlab options are defined in https://docs.gitlab.com/ee/user/project/push_options.html
  ;;
  ;; the second argument to transient-append-suffix is where to append
  ;; to, not sure what -u is, but this works
  (transient-append-suffix 'magit-push "-u"
    '(1 "=s" "Skip gitlab pipeline" "--push-option=ci.skip"))
  (transient-append-suffix 'magit-push "=s"
    '(1 "=m" "Set push option" "--push-option=merge_request.create"))
  (transient-append-suffix 'magit-push "=m"
    '(1 "=o" "Set push option" "--push-option="))  ;; Will prompt, can only set one extra
  ;;(transient-append-suffix 'magit-push "=D"
  ;;  '(1 "=V" "Set CI variable" "--push-option=ci.variable="))  ;; Will prompt, can only set one extra variable
  )
```

**Comment by basil-conto** [comment]
FTR, Transient supports reading multiple values for the same option, and with default choices, without needing to write a custom reader (which is also supported):
- [`(info "(transient) Binding Suffix and Infix Commands")`](https://gnu.org/s/emacs/manual/html_node/transient/Suffix-Specifications.html)
- [`(info "(transient) Suffix Slots")`](https://gnu.org/s/emacs/manual/html_node/transient/Suffix-Slots.html)

For example:
```el
(transient-append-suffix 'magit-push "-F"
  `("-o" "Transmit string" ("-o" "--push-option=")
    :multi-value repeat
    :choices ,(map-apply (lambda (str suf)
                           (let ((fmt #("%s (%s)" 2 7
                                        (face completions-annotations))))
                             (propertize str 'display (format fmt str suf))))
                         '(("skip-ci" . "SourceHut")
                           ("ci.skip" . "GitLab")))))
```

<img width="495" height="290" alt="Image" src="https://github.com/user-attachments/assets/d0313e4a-4843-45dc-8a0d-383b349bba4b" />

**Comment by tarsius** [comment]
I've added a note to add something like this: #5478.

**Comment by tarsius** [comment]
I've added `--push-option` in 7edf8c33a06021bc24a6282bd8fd7be943fc7197.

It's disabled by default, see https://docs.magit.vc/transient/Enabling-and-Disabling-Suffixes.html.

I've not added any completion candidates by default. Instead the new `magit-push-options` user option can be used to configure the choices. (You could go fancy as @basil-conto has done above.)
