### ISSUE TITLE
Empty commit message interpreted as missing remote branch

### ISSUE THREAD

**Issue by lorenzhs** [magit/magit#3719]
This is a bit of an edge-case since git doesn't permit empty commit messages, but it can happen when using git-svn or GitHub's transparent svn bridge. I have a collaborator who likes to commit with empty commit messages (don't ask) and this confuses magit.

Basically, magit interprets the empty string commit message as the remote branch not existing.

I'm on the master branch (512790bb7119dabcd90a0695a0b506e315d72c2e), `magit-version` says Magit 2.90.1, Git 2.20.1, Emacs 26.1, gnu/linux 

![screenshot from 2019-01-25 09-46-01](https://user-images.githubusercontent.com/142205/51734851-0b5f1d00-2086-11e9-8281-27d07431d053.png)

**Comment by tarsius** [comment]
To speed this up, could you please figure out how to create a commit with an empty message using `git` *plumbing* commends. Thanks.

**Comment by kyleam** [comment]
> could you please figure out how to create a commit with an empty message using `git` _plumbing_ commends

It'd take me a bit of time to figure out how to do that with plumbing, so I hope you don't mind porcelain :]

```
git commit --allow-empty --allow-empty-message -m ''
```

This boils down to `magit-rev-format` returning nil for an empty string:

https://github.com/magit/magit/blob/5e512721baecd251169bded90b7fe841b1a38feb/lisp/magit-status.el#L489-L492

**Comment by tarsius** [comment]
> ` --allow-empty-message`

Ah! Well that was simple. Didn't expect this gun2foot was so readily available.
