### ISSUE TITLE
Narrow scope of log to a subdirectory

### ISSUE THREAD

**Issue by MaikBeckmann** [magit/magit#372]
The following feature is missing in magit.  Passing a path to git log 

```
git log path/to/subdir
```

or gitk 

```
gitk path/to/subdir
```

will narrow down the presented history to files within this subdirectory.  I found this to be very useful when browsing the history of a project, knowing the changes of interest in are in a particular subdirectory.

**Comment by augustl** [comment]
Found this via Google, `magit-file-log` seems to be gone now (magit-20160410.222). Has the feature been removed, and/or is there another way to log a directory now?

**Comment by tarsius** [comment]
The command is now called `magit-log-buffer-file`. There's also a `magit-log-buffer-file-popup`. Both are available from `magit-file-popup`, which is bound to <kbd>C-c C-g</kbd> in file-visiting buffers after enabling `global-magit-file-mode`. Also see [Minor mode for buffers vistiting files](https://magit.vc/manual/magit/Minor-mode-for-buffers-visiting-files.html#Minor-mode-for-buffers-visiting-files).
