### ISSUE TITLE
Set left-fringe-width to 20 by default when fringe markers are enabled?

### ISSUE THREAD

**Issue by phil-s** [magit/magit#3726]
When `magit-section-visibility-indicator` is enabled, the lack of padding around the indicator looks rather awkward.

As noted in https://github.com/magit/magit/pull/3679#issuecomment-443435062 a value of 20 for `left-fringe-width` looks much better.

Perhaps this could be set as a default?

Failing that, the documentation could mention that users can set `left-fringe-width` in `magit-mode-hook` to provide such padding.

**Comment by tarsius** [comment]
> the lack of padding around the indicator looks rather awkward ... value of 20 for `left-fringe-width` looks much better.

Personally I don't even notice the lack of padding and think using a fringe width that is not consistent across all of Emacs to look rather awkward. :grin:

> Perhaps this could be set as a default?

So no.

> Failing that, the documentation could mention

If you open a pr for that, I'll merge it.

In the long run I would like to generate to generate the bitmaps based on the dimensions (and the generated images should ensure there is padding). But I do not feel like doing that myself. Also there is the issue that simply increasing the size of the bitmap to more than (I think) 8x8 appears to trigger some bug that causes only part of the bitmap to be used.
