### ISSUE TITLE
Melpa Install not working, package 'transient-0' is unavailable

### ISSUE THREAD

**Issue by einSelbst** [magit/magit#3729]
When I try to install magit from melpa it fails because it requires the mentioned package `transient-0` which is unavailable.

```
Install package ‘magit-20190214.2056’? y
package-compute-transaction: Package ‘transient-0’ is unavailable
``` 

The mentioned package is listed as Requirement:

```
magit is an available package.

     Status: Available from melpa -- Install
    Archive: melpa
    Version: 20190214.2056
     Commit: 1ed3febfb3abf179778e672989c82f3808c137e3
    Summary: A Git porcelain inside Emacs.
   Requires: emacs-25.1, async-20180527, dash-20180910, git-commit-20181104, lv-0, transient-0, with-editor-20181103
```

**Comment by phil-s** [comment]
Works for me.  Transient gets installed along with Magit.  Transient is brand new, so maybe just refresh your package list and try again.

**Comment by einSelbst** [comment]
Thanks @phil-s , that worked. Was a brand new emacs install so maybe I had just bad luck with the timing. Closing issue.
