### ISSUE TITLE
Key conflicts with transient 

### ISSUE THREAD

**Issue by Yevgnen** [magit/magit#3730]
Please explain
  (1) what behavior you expected: `remote.pushDefault` is switched.
  (2) what behavior you observed: `remote.pushDefault` is not switched and `End of history` is echoed.
  (3) and how we can reproduce the issue: In some `magit-status` buffer press `P`, `C`, `M-p`.

Also post the output of `M-x magit-version RET`: ```Magit 20190214.2056, Git 2.20.1, Emacs 26.1.90, darwin```

**Comment by tarsius** [comment]
I'll have to think what bindings to use instead.

Currently favoring

```emacs-lisp
  ["Configure repository defaults"
   ("R" magit-pull.rebase)
   ("P" magit-remote.pushDefault)]
  ["Configure branch creation"
   ("C-c m" magit-branch.autoSetupMerge)
   ("C-c r" magit-branch.autoSetupRebase)]
```

**Comment by tarsius** [comment]
I ended up using other keys, see d65dbc0c07bfd09cc00e33284111ee2805d9e035.
