### ISSUE TITLE
Problem setting commit number limit in log transcient

### ISSUE THREAD

**Issue by DamienCassou** [magit/magit#3731]
1. `$ make emacs-Q` and open Magit on a repository
1. type <kbd>l</kbd> to get the log transcient
2. type <kbd>-n</kbd> to remove the commit number limit (default is 256)
3. type <kbd>-n 10 RET</kbd>

Result:
- Expected: the log transcient is still visible and the maximum number of commits is 10
- Actual: the transcient disappears

Magit version is: Magit v2.90.1-239-g1ed3febf, Git 2.20.1, Emacs 26.1.90, gnu/linux (both magit and transcient are at the latest commit on `master`)

**Comment by tarsius** [comment]
Fixes with https://github.com/magit/transient/commit/8219c0ba1d3bb54a005841c544e8ad440c3b2d51.
