### ISSUE TITLE
Error (use-package): markdown-mode/:config: Symbol’s value as variable is void: magit-dispatch-popup

### ISSUE THREAD

**Issue by dennismayr** [magit/magit#3733]
Since this morning's update (as of Feb 15 2019), launching Emacs+Spacemacs shows the following `magit` error during startup:

```
Error (use-package): markdown-mode/:config: Symbol’s value as variable is void: magit-dispatch-popup
```

Magit version:
`Magit 20190214.2056, Git 2.17.1, Emacs 26.1, gnu/linux`

There are no `markdown` nor `magit` customizations in the dotfile.
No commands have been invoked.

**Comment by Silex** [comment]
This is a bug in spacemacs, they need to modify https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Bsource-control/git/packages.el according to the latest magit changes.

**Comment by Silex** [comment]
Found this https://github.com/syl20bnr/spacemacs/issues/11978, I think you can close this issue.

**Comment by dennismayr** [comment]
Thanks for the quick reply!

I'm closing the issue.
