### ISSUE TITLE
Push with `-f` does not force

### ISSUE THREAD

**Issue by jqtruong** [magit/magit#3735]
Magit version: Magit 20190215.1359, Git 2.20.1, Emacs 26.1, gnu/linux

when i try to push with `--force-with-lease`, i get the error:

> hint: Updates were rejected because the tip of your current branch is behind
> hint: its remote counterpart. Integrate the remote changes (e.g.
> hint: 'git pull ...') before pushing again.
> hint: See the 'Note about fast-forwards' in 'git push --help' for details.

so as if it didn't add the `-f` option, in fact i didn't see it in the git command from the logs.

it worked fine right before i updated to this new version.

**Comment by tarsius** [comment]
The `-f` key binding in the log popup/transient uses `--force-with-lease`, even though on the command-line `-f` is the short-hand for `--force`.

See the `git-push` manpage for the difference between these two arguments.

**Comment by jqtruong** [comment]
that is true, but i meant that neither `-f` nor `-F` worked, and that's actually entering the chars `-` and `f` (or `F`) after `P u` for pushing.

**Comment by tarsius** [comment]
Just in case, I checked whether these arguments get passed to `git` when they are enabled in the transient. They are.

That means that this is a Git "issue". It appears that in some cases `git` (or whatever additional software is involved on the remote side) refuses to carry out certain actions. For `--force-with-lease` this is expected, for `--force` not really.

In any case, it does not appear to have anything to do with Magit.

**Comment by ryankask** [comment]
This is happening to me as well. I've never seen this error before and often use the `-f` flag with magit.

**Comment by rmm5t** [comment]
This just happened to me as well right after upgrading to the latest version of magit today. I had to manually `git push --force-with-lease` from the command line, because the `-f` option passed to magit didn't turn into a `--force-with-lease` option. Here's the output of the magit-process after I tried <kbd>P</kbd><kbd>-f</kbd><kbd>u</kbd>.

```
 1 git … push -v origin rmm/1270-fix-deprecation-warnings\:refs/heads/rmm/1270-fix-deprecation-warnings
Pushing to git@github.com:<redacted>/<Redacted>.git
To github.com:<redacted>/<Redacted>.git
 ! [rejected]            rmm/1270-fix-deprecation-warnings -> rmm/1270-fix-deprecation-warnings (non-fast-forward)
error: failed to push some refs to 'git@github.com:<redacted>/<Redacted>.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by tarsius** [comment]
> This just happened to me as well right after upgrading to the latest version of magit today.

`package.el` does not unload old package versions before installing a new version. That can lead to a mixture of old and new versions being loaded. Restarting Emacs usually fixes that and I recommend that you *always* do so after updating.

**Comment by rmm5t** [comment]
@tarsius That makes sense. Thanks for the explanation!

**Comment by vaab** [comment]
Same here, and ... it depends on the remote. When I specify `-f`, it isn't carried over in the command actually run by `magit` (we can see it by pressing `$`). What is very strange, is that it is working well on another remote of the same repository. I'm on a version from 2024-06-25 (commit: b5aa1afc40 ).

**Comment by vaab** [comment]
Thanks for your prompt answer. I've been a magit user for more than 10 years, and this happened to me only very recently. I'm currently using emacs `30.0.50`, compiled in june.

I type `P` `-f` (and `-F` for good measure) (double check visually that both are highlighted) `e` (for elsewhere) select my remote/branch, press enter, I see flashing in the echo area (bottom line) the command that magit actually runs (in my case `Running git push -v myc master:master`) without the expected `--force` and `--force-with-lease`.

If I type `P` `-f` `p`, I get the line `Running git push -v --force --force-with-lease origin refs/heads/master:refs/heads/master`.

I can see this in `*magit-process*` buffer also. What stroke me, is that I'm on the exact same repository, and I can repeat these two examples one after the other. 

Using the command line by hand works without an issue (as reported by the previous user reporting on this issue). Anyway, it is not related to some git configuration as the command line sent by magit is obviously missing the arguments.

I understand that it is probably linked to some emacs quirks. I didn't update `magit` recently, but as any emacs user, my 
configuration grew with me on the last 20 years. I'm pretty sure that if I killed my emacs, and restarted it, it could solve the issue. But as it is not the first time this occurs, I wouldn't consider this as a settled issue as I didn't figure out clearly what was going on, and this happened a few time recently.

However, I feel I might have to spend the time debugging this (I'm just a little rusty, have a tight agenda and bad organizational skills), as it is probably linked to some personal emacs configuration, and I don't want to make you loose too much time on this issue. I'll try to find the cause tomorrow(?) by live-debugging the code.

**Comment by vaab** [comment]
I dived into the elisp, here is what I found regarding `magit-push-current`:

This form works:

```elisp
;;;###autoload
(defun magit-push-current (target args)
  "Push the current branch to a branch read in the minibuffer."
  (interactive
    (if-let ((current (magit-get-current-branch)))
      (let ((args (magit-push-arguments)))
        (list (magit-read-remote-branch (format "Push %s to" current)
                                       nil nil current 'confirm)
          args))
      (user-error "No branch is checked out")))
  (magit-git-push (magit-get-current-branch) target args))
```

Where-as the actual code:

```elisp
;;;###autoload
(defun magit-push-current (target args)
  "Push the current branch to a branch read in the minibuffer."
  (interactive
   (if-let ((current (magit-get-current-branch)))
       (list (magit-read-remote-branch (format "Push %s to" current)
                                       nil nil current 'confirm)
             (magit-push-arguments))
     (user-error "No branch is checked out")))
  (magit-git-push (magit-get-current-branch) target args))
```

Doesn't (`args` is empty at the time of the final line). It seems calling `magit-read-remote-branch` before will kinda reset the args... is that possible ?

BTW, the behavior is constant after full restart of emacs.

**Comment by tarsius** [comment]
And indeed I didn't spot that. It seems I never noticed this because apparently I don't use `-f` with that variant. Thanks for locating it!

Anyway, I'll look into removing this `transient-args` gotcha. If I cannot always spot this issue, then what hope do other package authors have? If they are even aware of this complication.

**Comment by tarsius** [comment]
I tried and cannot actually reproduce the issue. `transient-args` can already be used after using the minibuffer. I can't remember when I fixed that, so probably it was quite a while ago.

I suspect that you are using an older Transient version.

Of course I bump the minimal Transient version in the dependency list when appropriate (i.e., if I start using a new feature or after fixing a major bug), but unfortunately the maintainers of several package managers have decided to ignore that information for built-in packages and to just skip requested updates of those.

`package.el` even does so silently, I believe. See http://yummymelon.com/devnull/updating-built-in-emacs-packages.html for more information and how to fix it. More information and links to discussions at https://irreal.org/blog/?p=12426.

Please determine (and tell me) the version you have been using and whether it comes from Emacs or was installed by the (which?) package manager, before forcing the update, and thus losing the ability to make this determination.

**Comment by vaab** [comment]
I'm on `transient` `v0.7.2-1-gab546bb` ... and you are probably right. I'm updating now. I'm using `straight`, but I have the bad habit of `git pull -r` in the cloned repository of `magit`. However, `straight` doesn't seem to do any dependency checks to update other packages when I ask for a rebuild, or when relaunching emacs.

I confirm that, with current version `v0.7.5-5-g5a41cd5`, the problem is gone ! (did a `git pull -r` in `transient` cloned repository, and had to restart emacs). Many thanks for your patience and reactivity, and sorry about not thinking about updating magit's dependencies before.

**Comment by tarsius** [comment]
> I'm on `transient` `v0.7.2-1-gab546bb`

Ah, now I understand my confusion. This wasn't a long-lived bug (or "gotcha") but a short-lived regression introduced by this very commit. I fixed that shortly after, in a second iteration of that commit (https://github.com/magit/transient/commit/0e0ece32362bb5eed430328583018a35f44d3c7d), which I then force pushed.
