### ISSUE TITLE
Highlight issues when `magit-diff-refine-hunk` is t

### ISSUE THREAD

**Issue by Alexander-Miller** [magit/magit#3738]
I think I am seeing two different issues, both related to hunk refining. Starting from
```
(setq package-user-dir "~/.emacs.d/elpa/26.1/develop")
(require 'package)
(package-initialize)
(require 'magit)
(setf magit-diff-refine-hunk t)
```
when I activate the mark (or visual state with magit-evil) all the extra highlighting from the hunk refining disapppears (issue 1). However moving to another line and then back to the one mark was activated in makes the highlighting come back for a short time, but then quickly disappear, as if on an idle timer (issue 2).

[You can see it in action here](https://imgur.com/a/dmNNd5p).

magit-version says `Magit 20190215.1903, Git 2.20.1, Emacs 26.1, gnu/linux`

**Comment by tarsius** [comment]
I cannot tell from the video, because it is to fast, but I think what you are seeing is the intended behavior.

**Comment by Alexander-Miller** [comment]
Let's slow down then.

[Video1](https://imgur.com/m9AlBlO): activating mark removes hunk refinement.

[Video2](https://imgur.com/mmvigFn): moving back to where mark was activated makes hunk refinement reappear, but only for a split second.

**Comment by tarsius** [comment]
> Video1: activating mark removes hunk refinement.

That's intentional. While the hunk-internal region is active pressing `s` only stages the changes inside the selection. To make that obvious, the appearance of the changes outside the selection is changed. While the selection is active, outside "removed" lines are actually "context" lines as far as the selected change are concerned and the "added" lines are being ignored when performing the stage operation.

Considering that these lines are being treated as context lines or even as "lines that aren't actually there" it makes sense to not show their word differences. Showing the word difference would mean showing "detailed changes about something that hasn't actually changed".

> Video2: moving back to where mark was activated makes hunk refinement reappear, but only for a split second.

This is due to implementation details. It would be a lot of work (or potentially impossible) to prevent the short flickering.

**Comment by Alexander-Miller** [comment]
> To make that obvious, the appearance of the changes outside the selection is changed.

I was just about ready to write a long explanation about how that doesn't really work with region faces and what not, but then I remembered about `magit-diff-highlight-hunk-region-functions` and how this is just a general compatibility issue with `magit-diff-highlight-hunk-region-dim-outside`. Now I understand whey there's so many options for highlight-hunk functions. It's just a pity that drawing horizontal line makes text move around, but that's not the kind of issue either of us can touch.

> This is due to implementation details. It would be a lot of work (or potentially impossible) to prevent the short flickering.

And now for something completely different: while playing around with these settings I stumbled on a performance issue. Basically activating a region pushes cpu load to 100% due to excessive calls of `buffer-list-update-hook`. This happens in treemacs, where I use that hook to keep focus on the current file, but it seems to be a general thing, reproducible like this:
```
(setq package-user-dir "~/.emacs.d/elpa/26.1/develop")
(require 'package)
(package-initialize)
(require 'magit)
(setf magit-diff-refine-hunk t)


(setq test-timer nil)

(defun debounced-call ()
  (message "debounced-call")
  (unless test-timer
    (setf test-timer (run-with-idle-timer 0.2 nil #'action-call))))

(defun action-call ()
  (message "action-call")
  (setf test-timer nil))

(add-hook 'buffer-list-update-hook #'debounced-call)
```
You need the timer, otherwise it won't work. I have traced the problem to the use of a temp buffer in `magit-diff-hunk-region-patch`, it can be fixed by let-binding `buffer-list-update-hook` to nil first, but I cannot say why the timer is leading to such a feedback loop. 

The problem is not critical (ui remains responsive) and very specific, but I would still like to make our packages work together without such strangeness. Any advice?

**Comment by tarsius** [comment]
I am wondering whether `with-temp-buffer` itself should suppress that hook. Buffers created and disposed of by that are not something other packages should take an interest in, it's just an emacsy way of doing text-processing. Of course there are other use-cases...

So probably there is something somewhere that depends on the hook being run for temporary buffers, but in the case of the temporary buffers created by `magit-diff-hunk-region-patch` I can't image what that would be. If you open a pr to add the let-binding, then I will merge it. (Please link here and provide a short summary.)

**Comment by Alexander-Miller** [comment]
Sounds good to me. 
grep says `with-temp-buffer` is used nearly thirty times in magit's code base. Would you agree to introducing a `magit--with-temp-buffer` wrapper, or should I work around just the specific case?

**Comment by tarsius** [comment]
Lets stick to this one case.

**Comment by Alexander-Miller** [comment]
> I am wondering whether with-temp-buffer itself should suppress that hook.

FYI I have now raised that question upstream: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=34765
