### ISSUE TITLE
Sub-interfaces such as "Push", "Help" have trailing whitespaces

### ISSUE THREAD

**Issue by yurimx** [magit/magit#3740]
## what behavior you expected
There are no trailing whitespaces in all places

## what behavior you observed
I saw trailing whitespace in the "Help", "Commit", "Diff", "Merge", "Push", "Stash" etc. interfaces.

Screenshot:
<img width="1280" alt="2019-02-17 9 01 12" src="https://user-images.githubusercontent.com/26828933/52907064-a073c100-3294-11e9-9bab-ad5e2febb15c.png">

## how we can reproduce the issue.
1. Put `(sets-default show-trailing-whitespace t)` in your init file.
2. Open these interfaces of magit and you will see it.

## Magit-version
> Magit 20190216.2144, Git 2.20.1, Emacs 26.1, gnu/linux

Also, if this is an unsolvable problem, how can I avoid seeing these trailing whitespaces?

In my configuration, `show-trailing-whitespace` is enabled by default. I wrote a function that disables this feature in the buffer. What hook should I add to it?

I'm sorry for my poor English.

Thank you!

**Comment by kyleam** [comment]
> In my configuration, show-trailing-whitespace is enabled by default. I wrote a function that disables this feature in the buffer. What hook should I add to it?

When this came up before (#2747), the recommendation was to enable that setting more selectively.  The two concrete suggestions from that post are

```elisp
(add-hook 'prog-mode-hook (lambda () (setq show-trailing-whitespace t))
(add-hook 'text-mode-hook (lambda () (setq show-trailing-whitespace t))
```

and 

```elisp
;; only show trailing whitespace in files
(defun my-find-file-hook ()
  (setq show-trailing-whitespace t))
(add-hook 'find-file-hook #'my-find-file-hook)
```

**Comment by phil-s** [comment]
Is there any problem with this?

    --- transient.el
    +++ #<buffer transient.el>
    @@ -2179,6 +2179,7 @@
                 (insert ?\n))))
           (when (or transient--helpp transient--editp)
             (transient--insert-help))
    +      (delete-trailing-whitespace)
           (let ((lv-force-update t))
             (lv-message "%s" (buffer-string))))))

**Comment by tarsius** [comment]
Well, searching for trailing whitespace in order to paint it bright and then searching for trailing whitespace again in order to remove it, has a cost but no benefit. I think using `show-trailing-whitespace` as intended is to be preferred. I am sure there are other non-file-visiting modes that don't bother avoiding trailing whitespace and "fixing" them all is the wrong way to go IMO.

**Comment by basil-conto** [comment]
> Well, searching for trailing whitespace in order to paint it bright and then searching for trailing whitespace again in order to remove it, has a cost but no benefit.

Agreed.

> I think using `show-trailing-whitespace` as intended is to be preferred.

How is it intended to be used? There is nothing wrong with setting a default value for buffer-local user options; see [`(elisp) Default Value`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Default-Value.html). I prefer enabling `show-trailing-whitespace` globally and selectively disabling it, as this gives me increased confidence that no pesky whitespace might escape me, even in non-file-visiting or non-derived modes. Does `transient` provide some standard way of hooking into it to achieve something like this? I'm sorry if I've missed its mention somewhere or if this is the wrong place to discuss this.

Thanks!

**Comment by tarsius** [comment]
Since there is no hook that could be used to remove the whitespace, I have decided to add the `delete-trailing-whitespace` anyway.

**Comment by yurimx** [comment]
I think adding a hook to `transient` is a long-term solution.

Otherwise today I want to remove whitepsace, I want to ring tomorrow, the day after tomorrow I want to do something else...

**Comment by tarsius** [comment]
While I am going to add some hooks to `transient` I also do not want to rush it.
