### ISSUE TITLE
(magit-section-update-highlight) causing (wrong-type-argument (or eieio-object class) nil obj)

### ISSUE THREAD

**Issue by sunqingyao** [magit/magit#3741]
When trying to enter `magit-status` and `magit-mode`, I got an error saying

```
Error in post-command-hook (magit-section-update-highlight): (wrong-type-argume\
nt (or eieio-object class) nil obj)
```

No trace stack is produced beside this message, so I did a `M-: (magit-section-update-highlight) RET`, and here what I got:

```
Debugger entered--Lisp error: (wrong-type-argument (or eieio-object class) nil $
  signal(wrong-type-argument ((or eieio-object class) nil obj))
  eieio-oref(nil start)
  #f(compiled-function (it) #<bytecode 0x406fa141>)(nil)
  mapcar(#f(compiled-function (it) #<bytecode 0x406fa141>) (nil))
  magit-section-maybe-paint-visibility-ellipses()
  magit-section-update-highlight()
  eval((magit-section-update-highlight) t)
  eval-expression((magit-section-update-highlight) nil nil 127)
  funcall-interactively(eval-expression (magit-section-update-highlight) nil ni$
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

I tried a brute force fix, i.e. `(advice-add #'magit-section-update-highlight :override (lambda ()))`. Now the error disappears, but the whole buffer becomes monochrome then.

To reproduce the error, you would need to install the Homebrew version of Emacs (with no extra flags), and run `emacs` in a terminal instead of as a Cocoa application. The exact command I used is

```
% pwd
/Users/nalzok/.emacs.d/elpa/magit-20190215.1903
% emacs -Q --debug-init --eval '(setq debug-on-error t)' -L ../dash-20190128.1920 -L ../git-commit-20190102.107 -L ../lv-20181110.1740 -L ../transient-20190215.2239 -L ../with-editor-20181113.1845 -L . -l magit
```

The Magit version is `Magit 20190215.1903, Git 2.17.2 (Apple Git-113), Emacs 26.1, darwin`. In case it's relevant, the Emacs version is `emacs: stable 26.1 (bottled), HEAD`.

**Comment by tarsius** [comment]
This suggests that some other error occurred earlier, e.g. maybe `(list (magit-current-section)` evaluates to `(nil)`, which should not happen. Look in *Messages* for earlier errors.

**Comment by sunqingyao** [comment]
I think I've found the issue: I was trying to use `Magit` while not in a git-enabled directory. While it's a user error,  a better error message would be appreciated.

**Comment by tarsius** [comment]
Magit is supposed to notice that `default-directory` isn't inside a working tree and prompt you with "Git repository: ". And for me that's what happens.

**Comment by dsfalves** [comment]
I got the same error message, but for me it is happening in folders that already have projects. Inspecting *Messages* I found this:
`magit-section-visibility-ident: Wrong type argument: magit-section, #s(#s(eieio--class magit-section nil nil [#s(cl-slot-descriptor type nil t nil) #s(cl-slot-descriptor value nil t nil) #s(cl-slot-descriptor start nil t nil) #s(cl-slot-descriptor content nil t nil) #s(cl-slot-descriptor end nil t nil) #s(cl-slot-descriptor hidden nil t nil) #s(cl-slot-descriptor washer nil t nil) #s(cl-slot-descriptor process nil t nil) #s(cl-slot-descriptor heading-highlight-face nil t nil) #s(cl-slot-descriptor inserter (symbol-value (quote magit--current-section-hook)) t nil) ...] #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8125 data (type 0 value 1 start 2 content 3 end 4 hidden 5 washer 6 process 7 heading-highlight-face 8 inserter 9 ...)) (magit-hunk-section magit-file-section) ((:type . type) (:value . value) (:start . start) (:parent . parent)) [#s(cl-slot-descriptor keymap nil t nil)] [nil] ...) status nil #<marker at 1 in magit: scrapper> nil nil nil nil nil nil ...)
Error in post-command-hook (magit-section-update-highlight): (wrong-type-argument (or eieio-object class) nil obj)`
Magit version from list-packages: 20190316.182
Emacs version: 26.1
I'm running Archlinux, uname -a shows "Linux e2311lab 5.0.0-arch1-1-ARCH #1 SMP PREEMPT Mon Mar 4 14:11:43 UTC 2019 x86_64 GNU/Linux".

**Comment by thomasf** [comment]
Hmm. I just stumbeled upon this error after upgrading from ubuntu 18.10 to 19.04 using emacs 26.2. 

```el

Debugger entered--Lisp error: (wrong-type-argument (or eieio-object class) nil obj)
  signal(wrong-type-argument ((or eieio-object class) nil obj))
  eieio-oref(nil combined)
  magit-diff-visit--goto-from-p(nil nil)
  magit-diff-visit-file--noselect("/home/thomasf/src/redacted/facebook/management/commands/fb_import_adset.py" nil)
  magit-diff-visit-file("/home/thomasf/src/redacted/facebook/management/commands/fb_import_adset.py")
  funcall-interactively(magit-diff-visit-file "/home/thomasf/src/redacted/facebook/management/commands/fb_import_adset.py")
  call-interactively(magit-diff-visit-file nil nil)
  command-execute(magit-diff-visit-file)
```

I got this error just now and have not looked for a solution yet, might update this comment

**Comment by tarsius** [comment]
@thomasf This is unrelated to the above because it concerns code I have written over the last few days. I'll look into it. In what context did you call `magit-diff-visit-file`?

**Comment by thomasf** [comment]
I'm trying to open a buffer and this error happens instead of the buffer being opened.   I'm trying to gather more information.. I don't think I have any local customizations for magit which interferes with this code path.

**Comment by thomasf** [comment]
The problem seems to happoen when I open an untracked file

**Comment by thomasf** [comment]
I can create a new untracked file but when i close and reopen it again this error is triggered.

**Comment by thomasf** [comment]
If I stage the file it opens correctly.

**Comment by thomasf** [comment]
I will investigate If I have any other modes active which might be calling magit functions.

These files match magit- but I'm not sure what might be active and why the stack trace doesnt tell more about why magit is called.

```
▶11 ~/.emacs.d/elpa git:master?+ 
:57 tf@whale!$ rg -l magit- 
hide-lines-20151127.1840/hide-lines.el
anti-zenburn-theme-20180712.1838/anti-zenburn-theme.el
simple-call-tree-20180224.2056/simple-call-tree.el
quick-buffer-switch-20151007.2208/quick-buffer-switch.el
syslog-mode-2.2/syslog-mode.el
projectile-20190416.1458/projectile-autoloads.el
projectile-20190416.1458/projectile.el
diff-hl-20190223.2333/diff-hl.el
zenburn-theme-20190317.1846/zenburn-theme.el
python-django-20150822.404/python-django.el
magit-popup-20190223.2234/dir
magit-popup-20190223.2234/magit-popup-pkg.el
magit-popup-20190223.2234/magit-popup.el
magit-popup-20190223.2234/magit-popup.info
magit-popup-20190223.2234/magit-popup-autoloads.el
docker-20190424.1713/docker-network.el
docker-20190424.1713/docker-pkg.el
docker-20190424.1713/docker.el
docker-20190424.1713/docker-machine.el
docker-20190424.1713/docker-container.el
docker-20190424.1713/docker-image.el
docker-20190424.1713/docker-volume.el
docker-20190424.1713/docker-compose.el
docker-20190424.1713/docker-utils.el
magit-stgit-20190313.1155/magit-stgit.el
magit-stgit-20190313.1155/magit-stgit-pkg.el
magit-stgit-20190313.1155/magit-stgit-autoloads.el
ido-completing-read+-20190409.318/ido-completing-read+.el
mo-git-blame-20160129.1759/mo-git-blame.el
magit-svn-20190324.1459/magit-svn-autoloads.el
magit-svn-20190324.1459/magit-svn-pkg.el
magit-svn-20190324.1459/magit-svn.el
transient-20190425.948/transient.info
transient-20190425.948/transient.el
magit-20190427.2049/magit-clone.el
magit-20190427.2049/magit-branch.el
magit-20190427.2049/magit-gitignore.el
magit-20190427.2049/magit-autorevert.el
magit-20190427.2049/magit-tag.el
magit-20190427.2049/magit-subtree.el
magit-20190427.2049/magit-submodule.el
magit-20190427.2049/magit-refs.el
magit-20190427.2049/magit-apply.el
magit-20190427.2049/magit.info-2
magit-20190427.2049/magit-commit.el
magit-20190427.2049/magit-bookmark.el
magit-20190427.2049/magit-stash.el
magit-20190427.2049/magit-status.el
magit-20190427.2049/magit-bisect.el
magit-20190427.2049/magit-utils.el
magit-20190427.2049/magit-git.el
magit-20190427.2049/magit-files.el
magit-20190427.2049/magit-mode.el
magit-20190427.2049/git-rebase.el
magit-20190427.2049/magit-blame.el
magit-20190427.2049/magit-extras.el
magit-20190427.2049/magit-log.el
magit-20190427.2049/magit-fetch.el
magit-20190427.2049/magit-worktree.el
magit-20190427.2049/magit-section.el
magit-20190427.2049/magit-sequence.el
magit-20190427.2049/AUTHORS.md
magit-20190427.2049/magit-reflog.el
magit-20190427.2049/magit-process.el
magit-20190427.2049/magit-ediff.el
magit-20190427.2049/magit-notes.el
magit-20190427.2049/magit-wip.el
magit-20190427.2049/magit-transient.el
magit-20190427.2049/magit.el
magit-20190427.2049/magit-imenu.el
magit-20190427.2049/magit-patch.el
magit-20190427.2049/magit-pull.el
magit-20190427.2049/magit-remote.el
magit-20190427.2049/magit-autoloads.el
magit-20190427.2049/magit-reset.el
magit-20190427.2049/magit-merge.el
magit-20190427.2049/magit-diff.el
magit-20190427.2049/magit-core.el
magit-20190427.2049/magit-margin.el
magit-20190427.2049/magit-repos.el
magit-20190427.2049/magit.info-1
magit-20190427.2049/magit-obsolete.el
magit-20190427.2049/magit-push.el
magit-topgit-20160313.1954/magit-topgit-pkg.el
magit-topgit-20160313.1954/magit-topgit-autoloads.el
magit-topgit-20160313.1954/magit-topgit.el
solarized-theme-20190220.151/solarized.el
dpaste-20160303.2112/dpaste.el
with-editor-20190224.931/with-editor.el
git-timemachine-20190317.1547/git-timemachine.el
git-commit-20190426.1503/git-commit.el
workgroups2-20141102.1922/workgroups2.el
archives/marmalade/archive-contents
archives/melpa/archive-contents
archives/melpa-stable/archive-contents
```

**Comment by tarsius** [comment]
> The problem seems to happen when I open an untracked file.

Sounds like some code assumes that every `file` has `hunk`s, which is not the case. Should be easy to fix and I'll do so soon.

**Comment by tarsius** [comment]
Fixed in ba7b09cca230c0af7d7866d8141d4f494ea9765a.

**Comment by thomasf** [comment]
Confirmed working here by applying the patch manually inside my elpa packages directory.

**Comment by green7ea** [comment]
I'm currently running into this exact same issue when magit is compiled by `straight.el`. I can get everything to 'work'  with the following change:

```diff
diff --git a/lisp/magit-section.el b/lisp/magit-section.el
index 221a300..3dafaeb 100644
--- a/lisp/magit-section.el
+++ b/lisp/magit-section.el
@@ -357,7 +357,7 @@ Magit-Section is documented in info node `(magit-section)'."
   ;; (hack-dir-local-variables-non-file-buffer)
   (make-local-variable 'text-property-default-nonsticky)
   (push (cons 'keymap t) text-property-default-nonsticky)
-  (add-hook 'post-command-hook #'magit-section-update-highlight t t)
+  ;(add-hook 'post-command-hook #'magit-section-update-highlight t t)
   (add-hook 'deactivate-mark-hook #'magit-section-update-highlight t t)
   (setq-local redisplay-highlight-region-function
               'magit-section--highlight-region)
```

I'm running magit from master at commit `2db04ea92562350ec5f0e78fa21c7d53f38d351c` and have the previously mentioned fix. My emacs config can be found here https://github.com/green7ea/dotfiles/tree/master/.emacs.d

Should I stay in this issue or open a new issue? The title matches my exact problem as can be seen in the screenshot bellow:

![image](https://user-images.githubusercontent.com/1398908/126905440-fae920b5-e5e8-4132-8321-3a1eb62009c9.png)

I'm running `GNU Emacs 27.2` in a voidlinux musl distro (but I don't think that matters).

Please let me know if there's any other information I can provide or I can try to create a patch with a proper fix given a bit of direction.

**Comment by tarsius** [comment]
Create a new issue and post a backtrace.

**Comment by toma-te** [comment]
@green7ea Could it be that you recently upgraded to org-roam v2 and still use the ([no longer existing](https://github.com/org-roam/org-roam/wiki/Hitchhiker's-Rough-Guide-to-Org-roam-V2#org-roam-mode-is-no-longer-a-global-minor-mode)) org-roam-mode minor mode? At least this is what caused this bug for me, albeit only when running emacs in daemon mode.

**Comment by cesarolea** [comment]
> @green7ea Could it be that you recently upgraded to org-roam v2 and still use the ([no longer existing](https://github.com/org-roam/org-roam/wiki/Hitchhiker's-Rough-Guide-to-Org-roam-V2#org-roam-mode-is-no-longer-a-global-minor-mode)) org-roam-mode minor mode? At least this is what caused this bug for me, albeit only when running emacs in daemon mode.

Thank you, you saved me multiple hours of debugging.

In my case I had the following:

```
(use-package org-roam
  :pin melpa
  :hook ((after-init . org-roam-mode)
         (org-roam-backlinks-mode . visual-line-mode))
  :config ...)
```
So I changed it to:
```
(use-package org-roam
  :pin melpa
  :hook ((after-init . org-roam-setup)
         (org-roam-backlinks-mode . visual-line-mode))
  :config ...)
```
And that did it.

**Comment by vonpupp** [comment]
This was a life saver, I had the exact same issue. Thank you @cesarolea !
