### ISSUE TITLE
Magit popup ignores magit-popup-key face from now?

### ISSUE THREAD

**Issue by ogdenwebb** [magit/magit#3743]
My theme uses the same color in faces to highlight key symbols in which-key package and magit-popup-key. Today I see that magit-popup uses the different face(probably font-lock-builtin-face).

Which-key popup.
![which-key](https://user-images.githubusercontent.com/9018005/52963589-e28e2700-33a8-11e9-87bb-797d5de5e624.png)

Magit-diff popup.
![magit-popup](https://user-images.githubusercontent.com/9018005/52963624-f6398d80-33a8-11e9-9b8c-b4213c414047.png)

**Comment by tarsius** [comment]
That's because Magit now uses `transient` instead of `magit-popup`. Your theme will have to updated to theme the `transient-*-face`s.

https://emacsair.me/2019/02/14/transient-0.1/

**Comment by kyleam** [comment]
The master branch has been migrated from magit-popup to transient.  [Here] are the faces you can tweak for transient.

[Here]: https://github.com/magit/transient/blob/b155eec353961bccde4faeafbf11e116ed5c8b72/lisp/transient.el#L210-L269

**Comment by kyleam** [comment]
oy, 1 second too slow

**Comment by ogdenwebb** [comment]
@tarsius @kyleam thanks for your responses. Close then.
