### ISSUE TITLE
Segmentation fault with SJIS encoding and CJK fonts when diffing

### ISSUE THREAD

**Issue by thenamewastaken** [magit/magit#3745]
Hello,
when a diff buffer is opened, under certain conditions the whole Emacs process crashes with a segmentation fault.

I have a repository containing some files encoded as UTF-8 and some encoded as SJIS (these files' encoding can't be changed), containing mostly Japanese symbols.
When diffing these files, Magit (or maybe just Git?) can't deal with the encoding, so the diff buffer shows essentially garbage.

At some point in time, I added these lines to my init file:
```
(let ((jp "Noto Sans Mono CJK JP"))
  (set-fontset-font "fontset-default" 'unicode jp nil 'append)
  (set-fontset-font "fontset-default" 'kana jp)
  (set-fontset-font "fontset-default" 'japanese-jisx0208 jp))
```
(Previously, I used Unifont as my fallback font.)
After adding this change, opening the diff would consistently crash Emacs with a segmentation fault.
Opening the diff using VC (the built-in version control application, by default the ``C-x v =`` keybinding), correctly shows the diff, including properly handling the encoding and showing the Japanese symbols.
Removing the font configuration stopped the crashes.

**Comment by npostavs** [comment]
The segfault might be [Emacs Bug#30874](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30874), what Emacs version are you using?

**Comment by thenamewastaken** [comment]
I'm using 26.1 from the Gentoo's package.
Built with pure X, no toolkit.
Trying the example in the bug report doesn't cause any issue (I'm using DejaVu Sans Mono as my default font, not just in a fontset.)

**Comment by tarsius** [comment]
Maybe there is a bug in Magit that triggers this, after all it only happens with Magit. But it is at least as likely that is something *legitimate* that Magit does that triggers it. In any case elisp should never be able to trigger a segfault. If it does, then that is a bug in Emacs, regardless of whether there is a bug in the elisp code.

I don't know enough about encodings to be able to help you here. You should report this to the Emacs developers. It would probably help if you could give access to the repository and come up with steps to reproduce this issue that do not involve Magit.

**Comment by thenamewastaken** [comment]
The segmentation fault might be caused by the font, which means it's a real bug in emacs.
It could be that when Magit receives the raw bytes that git can't deal with (being SJIS), emacs tries to apply the font to these bytes, causing a segmentation fault somehow.
I didn't think of this scenario until now.
I'll try and see if other programs that can't handle SJIS also cause this issue when dumping their output in an emacs buffer.
Meanwhile, it would be nice if Magit could have some kind of workaround to use different encodings for different files, but that's a separate matter.
