### ISSUE TITLE
Emacs 25/26 and if-let: magit-pull broken

### ISSUE THREAD

**Issue by zimoun** [magit/magit#3746]
Dear,

From the NEWS file (`C-u C-h n 25.1`), the `if-let` is introduced in `subr-x`.
However, after installing using MELPA with `package-install` then the command `magit-pull` (F) does not work with Emacs 26: `Symbol’s function definition is void: if-let`.

If the file `magit.elc` is removed, then there is no error; it works as expected.

Therefore, it should come from `(eval-when-compile (require 'subr-x))` in `magit.el`.

Do I miss something ?

Thank you in advance for any tips.

**Comment by zimoun** [comment]
To provide more information, `magit-version` returns `Magit 20190217.2150, Git 2.20.1, Emacs 26.1, gnu/linux`, installed from MELPA and Emacs from Guix.

From my understanding, firstly it maybe lacks `(eval-when-compile (require 'subr-x))` in `magit-pull.el`. However, it still fails to find `if-let`. I am not sure to understand all the mechanisms of `macroexpand` but it should be the reason.

Secondly, the commit 61e7434c9337475 replaces the `magit-pull` with `define-transient-command`. And I think it introduces the bug.

From my opinion, if the bug is reproducible, the simplest fix should be to add `(require 'subr-x)` without the `eval-when-compile`. 

Or to spit the `if-let` with a naive:
```elisp
(let ((branch (magit-get-current-branch)))
   (if branch
         ...))
```


Thank you for your work on this awesome tool!

**Comment by npostavs** [comment]
> From my understanding, firstly it maybe lacks `(eval-when-compile (require 'subr-x))` in `magit-pull.el`. However, it still fails to find `if-let`. I am not sure to understand all the mechanisms of `macroexpand` but it should be the reason.

By "it still fails" do you mean it still fails after adding `(eval-when-compile (require 'subr-x))` to `magit-pull.el`? I would guess it's because the `if-let` call is inside a vector literal, so it might not get expanded by the compiler.

**Comment by zimoun** [comment]
> By "it still fails" do you mean it still fails after adding `(eval-when-compile (require 'subr-x))` to `magit-pull.el`? I would guess it's because the `if-let` call is inside a vector literal, so it might not get expanded by the compiler.

Yes, it still fails after adding `(eval-when-compile (require 'subr-x))` to `magit-pull.el`.
And yes, it's because the `if-let` call is inside a vector literal, so it might not get expanded by the compiler. If I understand well.
