### ISSUE TITLE
Wrong type argument: commandp, magit-dispatch-popup

### ISSUE THREAD

**Issue by komali2** [magit/magit#3747]
1. I type `spc g m` expecting the magit-dispatch-popup to appear
2. The magit dispatch popup does not appear. Instead I see the warning `Wrong type argument: commandp, magit-dispatch-popup`
3. Install magit 20190219.2226 while running git 2.11.0 on Emacs 25.1.1, installed on Debian 9.8 inside of ChromeOS ("linux apps"). 

Please let me know what further information I can provide, or testing I can do.

**Comment by vermiculus** [comment]
Has spacemacs been updated for the changes with transient?

**Comment by komali2** [comment]
I am happy to investigate based off what you said, first, can you help me understand what you mean? I don't know what "transient" means in this context. I installed spacemacs today using this command: `git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`

**Comment by komali2** [comment]
Also, in case it helps, my .spacemacs and ~/.emacs.d/init.el are available here: https://github.com/komali2/Configs/tree/master/emacs They both work as-is on 3 other machines, all running Ubuntu 18.04.

**Comment by kyleam** [comment]
> I don't know what "transient" means in this context. 

transient is the replacement for magit-popup. All magit-*-popup commands no longer exist as of 1ed3febf (Merge branch 'transient' [#3728], 2019-02-14).

**Comment by kyleam** [comment]
> I installed spacemacs today using this command: git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

I know very little about spacemacs, but, as @vermiculus suggests, it needs to be updated:

```
% git clone https://github.com/syl20bnr/spacemacs >/dev/null 2>&1 && git -C spacemacs grep magit-dispatch-popup
layers/+intl/keyboard-layout/packages.el:      (magit-change-popup-key 'magit-dispatch-popup :actions ?t ?j)
layers/+intl/keyboard-layout/packages.el:      (magit-change-popup-key 'magit-dispatch-popup :actions ?s ?k)
layers/+intl/keyboard-layout/packages.el:      (magit-change-popup-key 'magit-dispatch-popup :actions ?S ?K))))
layers/+source-control/git/packages.el:        "gm"  'magit-dispatch-popup
```

Or perhaps it has been updated, but you need to check out a different branch or something.  Dunno.
