### ISSUE TITLE
Saved transient values are not restored for magit-{log*,diff*,show-refs}

### ISSUE THREAD

**Issue by iquiw** [magit/magit#3750]
>  (1) what behavior you expected

When `~/.emacs.d/transient/values.el` has the following contents,
```
((magit-log "-n256" "--graph" "--color" "--decorate"))
```

In magit-log, `--color` option is selected as well as `-n256`, `--graph` and `--decorate`.

>  (2) what behavior you observed

`--color` option is not selected, but other (default) options are selected.

>  (3) and how we can reproduce the issue.

1. Execute `magit-status`.
2. Type <kbd>l</kbd>, <kbd>-c</kbd>, and then <kbd>C-x C-s</kbd>
3. Restart emacs.
4. Execute `magit-status`.
5. Type <kbd>l</kbd>.

>  M-x magit-version RET

`Magit 20190220.2315, Git 2.20.1, Emacs 26.1, gnu/linux`

**Comment by tarsius** [comment]
The log and diff commands still use some legacy code that hasn't been fully ported to the `transient` way of doing things. I'll try to get to this soon.

**Comment by tarsius** [comment]
Doing this properly involves some major design decisions. I took another look today and I am afraid there are no easy shortcuts, to at least make `C-x C-s` work as before and so this will probably remain broken for a while (for `magit-diff` too).

As a workaround you can manually customize `magit-{diff,log}-arguments`.

**Comment by iquiw** [comment]
@tarsius Thanks for the workaround. And thanks for all your work on Magit ❤️

**Comment by tarsius** [comment]
Same for `magit-refs-mode`.

Fix eminent now.

**Comment by iquiw** [comment]
Thanks!
