### ISSUE TITLE
Allow inline expansion of stash diff in magit-status with TAB

### ISSUE THREAD

**Issue by taktoa** [magit/magit#3752]
Currently, in the "Unstaged changes" section of `magit-status`, you can move your cursor to the line of the unstaged file and press TAB to see the diff for that file. I think there should be a similar interface for the "Stashes" section. I know that you can press ENTER to see the diff, but it pops up a new buffer rather than showing it inline, which I find less convenient.

**Comment by kyleam** [comment]
Here's a previous discussion about this: #1464

**Comment by vermiculus** [comment]
Does the recent enhancement to populate sections on-demand make this more feasible?

**Comment by tarsius** [comment]
> Does the recent enhancement to populate sections on-demand make this more feasible? Assuming my understanding is correct.

Yes.

**Comment by tarsius** [comment]
And I still don't intend to add it. If it turns out that many users want it, then I would reconsider, but it doesn't seem like there is a huge demand for it.
