### ISSUE TITLE
Can't commit - "Waiting for Emacs... *ERROR*: BUG: missing headers"

### ISSUE THREAD

**Issue by rsm-lisper** [magit/magit#3754]
Magit was working for me for a long time. However now when I try to commit, Emacs waits for a moment and then I get message:

`GitError! There was a problem with the editor '/usr/bin/emacsclient --socket-name=/tmp/emacs1000/server'
`

When I hit `$`:

```
  1 git … commit --
Waiting for Emacs...
*ERROR*: BUG: missing headers
  See https://github.com/magit/ghub/issues/81.
  headers: nil
  status: nil
  buffer: #<buffer  *http api.github.com:443*>
  buffer-string:
  ""
  --- end of buffer-string ---
error: There was a problem with the editor '/usr/bin/emacsclient --socket-name=/tmp/emacs1000/server'.
Please supply the message using either -m or -F option.
```

I removed whole _elpa_ dir and reinstalled packages. I added `$EDITOR` in shell and set editor in git global config. I removed _.authinfo_. No change. I spent almost a week, and I'm done, have no clue and I have to ask for help...

I'm on Slackware Linux 14.2
GNU Emacs 25.3.1
Magit 20190221.1446

My only bit of magit related configuration is keybinding `(global-set-key (kbd "C-x g") 'magit-status)
`.

OH WOW! I've done it! When playing with suggested `emacs -Q --debug-init --eval '(setq debug- ...` I finally figured out it's working when I remove `magithub` package! IT'S ALIVE! :) And since I don't really use magithub, this solution is good enough for me. I'll post this for your information, feel free to remove it if it's not very usefull.

And thank you very much for very nice tool! :)

**Comment by vermiculus** [comment]
Linking magit/ghub#81.

This is probably because magithub makes sure it's pulled a list of issues and pull requests once you enter git-commit-mode. Instead of magithub, though, I encourage you to take a look at the shiny-and-new [Forge](https://github.com/magit/forge) package 😄

**Comment by tarsius** [comment]
@vermiculus explained why fetching happens **while committing**.

For information about why this leads to an error, see https://github.com/magit/ghub/issues/81.
