### ISSUE TITLE
Transient: Allow to add a new "group" of suffixes to a command

### ISSUE THREAD

**Issue by bastianbeischer** [magit/magit#3758]
It would be nice if there would be the possibility to add new groups to an existing transient command. For example, I want to add the suffix: "--rebase" to the magit pull transient command as a new suffix. I can do it with this snippet:

(transient-insert-suffix 'magit-pull "r" '("-r" "Rebase local commits" "--rebase"))

But this will put the command in the section "Configure". Logically "--rebase" would go into the section "Arguments" which exists for other transients but not for magit-pull. It would be nice if it were possible to extend the magit-pull transient with a new group "Arguments" which could then be populated with custom arguments.

P.S.: I nominate the above for inclusion in magit-pull (maybe at a non default level). It is fairly useful to me and I think others would appreciate having it as well.

Thanks for your work on magit!

**Comment by tarsius** [comment]
> Allow to add a new "group" of suffixes to a command

That's really a transient feature request and I already plan to do that.

> I nominate the above for inclusion in magit-pull (maybe at a non default level).

I've added.  At the default level.  And enabled it right away.

I recommend to never pull, but sometime I accidentally do it myself.  This way I at least don't have to undo a merge when it happens.  ;-)

**Comment by bastianbeischer** [comment]
> > Allow to add a new "group" of suffixes to a command
> 
> That's really a transient feature request and I already plan to do that.

Great, thanks! Sorry for not posting that in the transient repository. If you prefer I can open another issue there to track this feature request appropriately?

> 
> > I nominate the above for inclusion in magit-pull (maybe at a non default level).
> 
> I've added. 

Thanks a lot!

> At the default level. And enabled it right away.
> 
> I recommend to never pull, but sometime I accidentally do it myself. This way I at least don't have to undo a merge when it happens. ;-)

I disagree here. This may be your personal preference (and I tend to agree with your opinion), but it's not a good default. I think when you open the pull popup you expect magit to "pull" by default, which is fetch+merge. Anyone who doesn't like the default can change it forever with just a few keystrokes (-r C-x C-s) Also, for users which push to multiple locations, pull --rebase will cause woes, too...

**Comment by bastianbeischer** [comment]
I just saw that the option is still disabled by default, so forget what I wrote there :-)

**Comment by tarsius** [comment]
> Great, thanks! Sorry for not posting that in the transient repository. If you prefer I can open another issue there to track this feature request appropriately?

No problem. Just explaining why I was closing. No need to open an issue--I won't forget about it and will likely get to it soonish.

> This may be your personal preference

Agreed. I only enabled it in my own configuration.
