### ISSUE TITLE
Auto-complete HEAD, FETCH_HEAD, ORIG_HEAD

### ISSUE THREAD

**Issue by benma** [magit/magit#3765]
Magit 20190215.1903, Git 2.17.1, Emacs 25.2.2, gnu/linux

When switching branches, or doing a hard reset, or anywhere where there is autocompletion for a ref, it would be nice if those three would also be auto completed in the minibuffer.

:heart:

**Comment by tarsius** [comment]
Some commands do that now.

**Comment by benma** [comment]
When I checkout a branch, I still can't autocomplete FETCH_HEAD. To this day I manually type it out every time 😅 

Could you please re-open this issue?

**Comment by tarsius** [comment]
I've opened #5331 for this.
