### ISSUE TITLE
Compile error when installing from melpa (transient.el)

### ISSUE THREAD

**Issue by larsga** [magit/magit#3768]
On Emacs 26.1 (Mac) I followed install instructions here (not stable, the first one): https://magit.vc/manual/magit/Installing-from-Melpa.html#Installing-from-Melpa

On `package-install` I get:

```
Compiling file /Users/gjest/.emacs.d/elpa/transient-20190226.2059/transient.el at Wed Feb 27 14:51:21 2019
Entering directory ‘/Users/gjest/.emacs.d/elpa/transient-20190226.2059/’
transient.el:840:1:Error: Wrong type argument: integer-or-marker-p, loc
```

All attempts to run `magit-status` lead to the error message:

```
Eager macro-expansion failure: (wrong-type-argument integer-or-marker-p loc)
Compiler-macro error for cl--block-wrapper: (wrong-type-argument integer-or-marker-p key)
Eager macro-expansion failure: (wrong-type-argument integer-or-marker-p key)
cl-generic-ensure-function: transient--init-suffix-key is already defined as something else than a generic function
```

I replaced melpa with stable melpa, did `package-reinstall` and everything worked.

**Comment by tarsius** [comment]
You are installing for the first time, not updating?

I just installed `magit` following these same instructions in a fresh `~/.emacs.d`. I got no error.

**Comment by larsga** [comment]
Yes, this was a first-time install on a completely blank machine.

**Comment by tarsius** [comment]
> transient.el:840:1:Error: Wrong type argument: integer-or-marker-p, loc

On that line `loc` isn't actually being used as an integer; it appears in the arglist of a function whose definition begins on that line.

I don't know what's going on.

**Comment by npostavs** [comment]
[Don't take the line number too seriously](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=2681) (I don't see where the error is coming from either though)

**Comment by tarsius** [comment]
I don't have a clue what could be wrong and you seem to be the only one that is affected, which makes me think that there is probably something wrong with your installation. I am closing this because I don't see how I could help you.

**Comment by larsga** [comment]
Started a new job, started setting up new laptop. Installed Emacs yesterday, do `list-packages`, find magit, press `i`, then `x`, and get:

```
Compiling file /Users/larsga/.emacs.d/elpa/async-20190502.1206/smtpmail-async.el at Fri May  3 09:03:47 2019

Compiling no file at Fri May  3 09:03:47 2019
Leaving directory ‘/Users/larsga/.emacs.d/elpa/with-editor-20190224.931’

Compiling file /Users/larsga/.emacs.d/elpa/with-editor-20190224.931/with-editor.el at Fri May  3 09:03:48 2019
Entering directory ‘/Users/larsga/.emacs.d/elpa/with-editor-20190224.931/’

Compiling no file at Fri May  3 09:03:48 2019
Leaving directory ‘/Users/larsga/.emacs.d/elpa/transient-20190429.1258’

Compiling file /Users/larsga/.emacs.d/elpa/transient-20190429.1258/transient.el at Fri May  3 09:03:48 2019
Entering directory ‘/Users/larsga/.emacs.d/elpa/transient-20190429.1258/’
transient.el:919:1:Error: Wrong type argument: integer-or-marker-p, loc

Compiling no file at Fri May  3 09:03:48 2019
Leaving directory ‘/Users/larsga/.emacs.d/elpa/git-commit-20190501.1823’

Compiling file /Users/larsga/.emacs.d/elpa/git-commit-20190501.1823/git-commit.el at Fri May  3 09:03:48 2019
Entering directory ‘/Users/larsga/.emacs.d/elpa/git-commit-20190501.1823/’

Compiling no file at Fri May  3 09:04:16 2019
```

The only package I installed before this one was dumb-jump. I tried looking at the source code of that, but it doesn't seem to be doing anything that would affect transient.

Still no idea what's going on. Maybe it's something in my `.emacs`? That's the only thing that was added to this Emacs setup before dumb-jump and magit.

**Comment by tarsius** [comment]
> Maybe it's something in my `.emacs`?

Maybe. It's easy to find out; remove it and try again.

**Comment by larsga** [comment]
It was my `.emacs`. :-(

No idea why, but at least you can forget about this issue. Thank you for all the help!
