### ISSUE TITLE
Discarding a directory called `~` in the working tree does not work as expected

### ISSUE THREAD

**Issue by kqr** [magit/magit#3769]
I accidentally created a directory called `~` in my working tree (with an external tool that's unaware of Unixy conventions). This was listed in the `magit-status` buffer as `\~`, which seems correct as far as I'm concerned.

I put point over it and pressed `k` to discard it. I got asked if I wanted to discard it, then if I wanted to discard it recursively, and only when I had answered yes to that question did it dawn on me what I might have done.

In the end, Magit did not delete my home directory, for the following reason:

```
move-file-to-trash: Cannot move /home/kqr to trash: Permission denied
```

But

1. I do not expect Magit to delete my home directory when I ask it to discard a directory called `\~` in the working tree.
2. Whatever Magit is intent on deleting, I expect it to succeed and not encounter a "permission denied" error, as long as it is running as the user owning the directory in question.

This is using Magit 20180214.1339, Git 2.11.0, Emacs 26.1, gnu/linux

**Comment by tarsius** [comment]
Thanks for reporting this. I have opted to simply refuse to delete any file beginning with `\~` or `~`.

> Whatever Magit is intent on deleting, I expect it to succeed and not encounter a "permission denied" error, as long as it is running as the user owning the directory in question.

It (luckily) did not work because you do not have permissions to modify `/home/` and deleting something from `/home/` is a modification to `/home/`, not to the subdirectory that you are deleting.

**Comment by kqr** [comment]
That is certainly an improvement. Thanks!

Good explanation on why it didn't work, but I was under the impression that a recursive remove would first recursively remove the contents of a directory, and only when it is empty remove the directory itself. Under that assumption, the expectation is that my home directory would be cleared out, and only then would it have stopped on the permission denied error. Any idea why that did not happen?
