### ISSUE TITLE
Lazy `magit-status` and `magit-revision`

### ISSUE THREAD

**Issue by Alexander-Shukaev** [magit/magit#3774]
Sometimes the diffs of commits (`magit-revision`) or stages (`magit-status`) are simply too big to be rendered quickly.  I was wondering whether there is already or in progress or planned feature to neither insert nor render diffs in these two modes by default but rather do it lazily as the point is moving towards the corresponding sections or expands those sections explicitly with a key stroke?

**Comment by Alexander-Shukaev** [comment]
Resembles 5th point from #2982.

**Comment by tarsius** [comment]
Yes, that is planned. I have now briefly summaries this in #2982 at (B4).
