### ISSUE TITLE
Feature Request: magit-sync: update local branches with upstream git objects

### ISSUE THREAD

**Issue by rmm5t** [magit/magit#3777]
I looked for an equivalent feature in magit to [`hub sync`](https://hub.github.com/hub-sync.1.html), but didn't find it. 

> Fetch git objects from upstream and update local branches.
>
> - If the local branch is outdated, fast-forward it;
> - If the local branch contains unpushed work, warn about it;
> - If the branch seems merged and its upstream branch was deleted, delete it.
>
> If a local branch does not have any upstream configuration, but has a same-named branch on the remote, treat that as its upstream branch.

- https://hub.github.com/hub-sync.1.html
- https://github.com/github/hub/blob/master/commands/sync.go

Is this something that might be considered in magit? Or is this something that already exists and I just didn't find it?

**Comment by tarsius** [comment]
I am swamped; maybe you want to give it a try yourself.

Don't just translate the go code. From a quick look I think it forgot about some "edge cases". The upstream of local branches can be other local branches. And the remote upstreams may be branches on different remotes.

**Comment by kyleam** [comment]
Assuming `hub sync` works well for you, I wonder what the appeal of supporting this in Magit is.  It seems like the operation is not intended to take any arguments, so it wouldn't benefit from Magit's completion functions.  So I guess the main motivation is being able to call it with a single key from Magit and perhaps seeing the output in the process buffer.

In that case, IMO this is already easy enough to do on the user-side.  Something like (untested)

```emacs-lisp
(defun my/hub-sync ()
  (interactive)
  (magit-shell-command-topdir "hub sync"))

(define-key magit-mode-map KEY #'my/hub-sync)
```

**Comment by tarsius** [comment]
On second though, I agree with @kyleam; a simple wrapper should do. Of course if you are interested in implementing it in elisp yourself, then maybe that could be added to Magit, but I don't really want to do it myself.

**Comment by rmm5t** [comment]
@tarsius @kyleam Totally understand. Thanks!

**Comment by rmm5t** [comment]
Btw, for future onlookers, the quick workaround I'm using (for now) is to just run <kbd>!</kbd><kbd>!</kbd> in a magit-status buffer and then running `hub sync` from there. Later, I might add a key binding to speed that up.

**Comment by chmouel** [comment]
adding a bit to this in case other are googling for it, I had that interactive function for quite some time which works quite well : 

```emacs-lisp
(defun magit-sync-repos ()
  (interactive)
  (require 'magit-repos)
  (dolist (repo (magit-list-repos))
    (progn
      (magit-status-setup-buffer repo)
      (unless (magit-anything-modified-p t repo)
        (magit-git-command-topdir "hub sync")
        (call-interactively 'magit-fetch-from-upstream)
        (call-interactively 'magit-section-show-level-4-all)))))
```

it's using [magit repositories listing ](https://magit.vc/manual/magit/Repository-List.html) which would need to be set and customized
