### ISSUE TITLE
Cursor can be moved into a position where TAB does not work correctly

### ISSUE THREAD

**Issue by Alexander-Miller** [magit/magit#3789]
Starting from `emacs -q` load magit:
```Lisp
(setq package-user-dir "~/.emacs.d/elpa/26.1/develop")
(package-initialize)
(require 'magit)
```
Call magit-status for a repo with at least two modified files, move to a line with a modified file such that the line above contains another modified file: https://imgur.com/fbFgZc7

Call beginning-of-line and then left-char. Press TAB. Nothing happens. Press TAB again and you see the diff for the file in the line *above* point: https://imgur.com/0XDM1tN

While left-char is bound to the arrow keys it's not a necessary condition for this bug, I have recently started noticing it with my evil/spacemacs setup where I generally only navigate up and down, never left and right, I don't know what's causing it then.

Magit version is "Magit 20190312.409, Git 2.20.1, Emacs 26.1, gnu/linux".

**Comment by tarsius** [comment]
Emacs is supposed to move point out of invisible text, in this case the hidden section body. Here it fails to do so I don't know why though it seems to have something to do with the last hidden character being a newline character. If you invoking `backward-char` with a prefix argument, then it moves to the other end of the hidden text.

**Comment by tarsius** [comment]
And I don't want to implement a workaround.
