### ISSUE TITLE
Magit-status doesn't load since it migrated to transient (using el-get)

### ISSUE THREAD

**Issue by alvatar** [magit/magit#3792]
Magit-status (or all other magit commands), stopped working, resulting in this:

```
Cannot open load file: No such file or directory, transient 
```

After some googling I concluded this happens since Magit migrated to _transient_.
I'm using el-get, Emacs 26.1 on OSX.

`M-x magit-version RET` also returns the same message

I've tried removing .emacs.d, updating, the usual.

**Comment by tarsius** [comment]
An update to the `el-get` recipe is in the works but hasn't been merged yet: https://github.com/dimitri/el-get/pull/2690.

Until that has been taken care of you will have to install `transient` explicitly.
