### ISSUE TITLE
vc-region-history equivalent

### ISSUE THREAD

**Issue by luismbo** [magit/magit#3796]
This has been requested before in #1717 and #2189, then implemented in #2226.

Perhaps I'm misunderstanding how `=L` in `magit-log-popup` works but, it explicitly asks for file and line numbers, disregarding both the current file and the current region. Is that a bug?

Something along these lines would be much more convenient:

```elisp
(defun magit-log-region (from to)
  (interactive "r")
  (magit-log (list (magit-get-current-branch))
             (list "--graph"
                   "--decorate"
                   "-n256"
                   (format "-L%s,%s:%s"
                           ;; note: these line numbers are different from
                           ;; vc-region-history's, which uses (- from-line 1)
                           ;; and (- to-line 2) for some reason.
                           (line-number-at-pos from)
                           (line-number-at-pos to)
                           (magit-file-relative-name)))))
```

Can `=L` take the current file/region into account? Can the `=L` option be activated automatically if a region is active when `magit-log` is invoked? Additionally, could a non-popup version like `magit-log-region` exist?

**Comment by tarsius** [comment]
(Update magit it now uses transient instead of magit-popup.)

`magit-log-buffer-file` and `magit-log-trace-definition` both do something like this. They are available from `C-c M-g` in file-visiting buffers.

**Comment by luismbo** [comment]
Oh! 😅 The popup works as expected now. `magit-log-buffer-file` is exactly what I need and transient looks great. Thanks!

**Comment by luismbo** [comment]
I've noticed one key feature of `vc-git-region-history` that seems to be missing from `magit-log-buffer-file` (with a region). From `vc-git-region-history`:

```  ;; The "git log" command below interprets the line numbers as applying
  ;; to the HEAD version of the file, not to the current state of the file.
  ;; So we need to look at all the local changes and adjust lfrom/lto
  ;; accordingly.
```

`vc-git-region-history` then proceeds to call `git diff` and adjusts the region boundaries to match what's in HEAD. 

Without this, the log results are very confusing if you happen to have unstaged changes in the current file.

**Comment by tarsius** [comment]
I've added a note about this to the relevant issue.
