### ISSUE TITLE
Point gets stuck on "old mode" line in magit-status output after permissions change

### ISSUE THREAD

**Issue by mikecrowe** [magit/magit#3797]
Magit 2.90.1, Git 2.20.1, Emacs 26.1, gnu/linux (Debian Buster)

Steps to reproduce:
```
$ mkdir test
$ cd test
$ git init
$ echo test > one
$ git add one
$ git commit -m "one"
$ chmod +x one
```
Run emacs and open up ```magit-status``` in this repository. Drop down the
"Unstaged changes". Notice that it says:
```
modified   one
old mode 100644
new mode 100755
```
Move point down to the "old mode" line, then attempt to move down one line
further. The cursor stays on the "old mode" line and:
```
magit-next-line: Wrong type argument: number-or-marker-p, nil
```
appears in the minibuffer. Attempting to move up emits the same error
message. The point is now trapped on the "old mode" line.

When running in `magit-emacs-Q-command` the behaviour is the same, but I
also get the stack trace:

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  magit-diff-inside-hunk-body-p()
  magit-next-line(1 1)
  funcall-interactively(magit-next-line 1 1)
  call-interactively(magit-next-line nil nil)
  command-execute(magit-next-line)
```

**Comment by tarsius** [comment]
Couldn't reproduce with `master`; seems I already fixed this.

**Comment by mikecrowe** [comment]
That's great then. Thanks.

I noticed it a while ago and kept meaning to get round to entering a bug. When is master due to appear on stable MELPA?

**Comment by tarsius** [comment]
I had another look and something was still slightly off. Fixed that too now.
