### ISSUE TITLE
Pushing to non existing destination fails

### ISSUE THREAD

**Issue by bastianbeischer** [magit/magit#3799]
With git 2.21 I can no longer use "P u" to push a new branch to my remote repository. Previously the branch was created on the remote side and the ref was pushed, setting the upstream branch name of my local branch as well. 

Now the branch gets pushed, but setting the upstream reference does not work.

Magit tried to run (from magit-process)

```
  1 git … branch --set-upstream-to public/X X
error: the requested upstream branch 'public/X' does not exist
hint: 
hint: If you are planning on basing your work on an upstream
hint: branch that already exists at the remote, you may need to
hint: run "git fetch" to retrieve it.
hint: 
hint: If you are planning to push out a new local branch that
hint: will track its remote counterpart, you may want to use
hint: "git push -u" to set the upstream config as you push.

  0 git … push -v public X\:refs/heads/X
Pushing to ...
Total 0 (delta 0), reused 0 (delta 0)
To ...
 * [new branch]          X -> X
updating local tracking ref 'refs/remotes/public/X'
```

So the git branch command runs first and fails, then the push happens.

**Comment by kyleam** [comment]
Thanks.  I can reproduce the failure and confirm that I see the behavior on git v2.21 but not v2.20.1.

**Comment by tarsius** [comment]
I am working on "upstreaming handling" *right now*. I'll have a look at this too.

**Comment by kyleam** [comment]
I said

>  I can reproduce the failure and confirm that I see the behavior on git v2.21 but not v2.20.1.

Sorry, I can confirm that I see the failure, but what I said about the difference between git versions is wrong.  (I think I tested v2.20.1 after v2.21 and forget to delete the branch on the remote :/)

Anyway, this bisects to bb8500c6 (magit-set-upstream-branch: Use "git branch --set-upstream-to", 2019-03-06).

**Comment by tarsius** [comment]
#3813 fixed this (among other things).
