### ISSUE TITLE
Asyncronous bisection for long commands or large histories

### ISSUE THREAD

**Issue by matthew-piziak** [magit/magit#3802]
`magit-bisect` with a test script is very useful. However, sometimes these scripts can take a long time to run, especially if they are looking for an obscure bug that requires recompilation. Right now, Magit hangs Emacs the moment that the bisect shell command is input, and does not report progress or allow the user to do other things. 

It would be nice if this happened in the background instead, with status messages for `running bisect` and `bisect finished`. Better still would be if Magit reported the number of revisions or steps remaining, e.g. `running bisect: 41 revisions left to test (roughly 6 steps)`.

**Comment by tarsius** [comment]
> It would be nice if this happened in the background instead, with status messages for `running bisect` and `bisect finished`.

That happens now.

> Better still would be if Magit reported the number of revisions or steps remaining, e.g. `running bisect: 41 revisions left to test (roughly 6 steps)`.

This information is visible in the process buffer, where it is updated asynchronously. In the status buffer the information is only updated once the process has returned.

**Comment by matthew-piziak** [comment]
Brilliant, thank you!!
