### ISSUE TITLE
Cherry pick hunks out from any diff buffer

### ISSUE THREAD

**Issue by jwiegley** [magit/magit#3804]
If I'm looking at any diff buffer, it would be nice to be able to say "apply this change to my current work tree if possible".

**Comment by tarsius** [comment]
<kbd>a</kbd> "apply this change to my current work tree if possible"

<kbd>C-u a</kbd> "... try a little harder"

Also see https://magit.vc/manual/magit/Applying.html.

**Comment by jwiegley** [comment]
@tarsius Thank you! I had only tried `A`.
