### ISSUE TITLE
Improper handling of usernames containing @

### ISSUE THREAD

**Issue by JoeOsborn** [magit/magit#3806]
# What behavior I expected

Overleaf's git bridge uses full email addresses as usernames, e.g. https://joseph.osborn@pomona.edu@git.overleaf.com.  I expected magit's auth source password finding implementation to find my git.overleaf.com passwords in my authinfo.gpg.

# What behavior I observed

I was prompted for my password.  I investigated and saw that magit-process-password-auth-source fails if the given key contains more than one @ sign, as the key above does (joseph.osborn@pomona.edu@git.overleaf.com).

# How to fix the issue

Changing the regex from:

```
(string-match "\\`\\([^@]+\\)@\\([^@]+\\)\\'" key)
```
To:

```
(string-match "\\`\\(.+\\)@\\([^@]+\\)\\'" key)
```

Fixes things, so it works if the key contains at least one @ and takes everything after the last @ as hostname and everything before as username.  I think a more correct fix would be something like this (untested):

```
  (let* ((source (or
                  (and (string-match "\\`\\(.+\\)@\\([^@]+\\)\\'" key)
                       (let* ((user (match-string 1 key))
                              (host (match-string 2 key)))
                         (car (or (auth-source-search :max 1 :host host :user user)
                                  (auth-source-search :max 1 :host key))))
                       )
                  (car (auth-source-search :max 1 :host key))))
         (secret (plist-get source :secret)))
    (if (functionp secret)
        (funcall secret)
      secret)
    )
```

# Magit version

Magit 20190320.1451, Git 2.17.1, Emacs 26.1, gnu/linux

**Comment by tarsius** [comment]
I went with the updated regexp.

**Comment by pmeckoni** [comment]
Hi @JoeOsborn ,
Can you guide me what should the authinfo entry look like for using Overleaf's git-bridge with Magit Emacs?
Is there any magit configuration specific for Overleaf?

**Comment by JoeOsborn** [comment]
There’s nothing particularly overleaf-specific as I recall; the username should be your.email@email.domain and the host is https://git.overleaf.com.  I’ve switched from using authinfo to libsecret in the last year so I don’t have my authinfo lines handy anymore.  Hope this helps!

**Comment by pmeckoni** [comment]
It didn't work for me. I tried host as `https://git.overleaf.com` and then again as `git.overleaf.com`. 

Details here: https://emacs.stackexchange.com/q/62459/22137
