### ISSUE TITLE
magit-checkout-branch defaults to ref

### ISSUE THREAD

**Issue by dhull** [magit/magit#3811]
I usually switch branches by getting switching to the `magit-refs` buffer by typing `y` (`magit-show-refs`), moving the cursor to the desired branch, and then typing `b b <return>` to run `magit-checkout`. In commit 7889f5d8803f8345a5715e0023470ab33da62e45, the default ref when I do that is now something like `refs/heads/BRANCH`, where in 2980f3c5b49f5f32695dbe0d095c7589745e9af1 it was just `BRANCH`. I don't know for sure if the new behavior is wrong, but I liked the old behavior better.

Magit v2.90.1-393-g7889f5d8, Git 2.19.2, Emacs 26.2, darwin

**Comment by tarsius** [comment]
It was a silly mistake.
