### ISSUE TITLE
Swap order of branch-create arguments?

### ISSUE THREAD

**Issue by lassik** [magit/magit#3812]
Does anyone else constantly trip over the order in which Magit asks for the names of the old and new branches?

Every time I do `b c` (`magit-branch-create`), I instinctively start typing the name of the new branch I want to create (similar to typing `git checkout -b new-branch` on the command line). Instead, Magit expects the name of the old branch first, so I always get an error. This has happened to me dozens of times by now.

Would it be possible to swap the order of these so it feels more like command line Git?

Anyway, I love everything else about Magit so thanks for the great work on it :)

**Comment by tarsius** [comment]
> Does anyone else constantly trip over the order in which Magit asks for the names of the old and new branches?

Yes. So I added the option `magit-branch-read-upstream-first`.
