### ISSUE TITLE
Commit fails when using QubesOS Split GPG

### ISSUE THREAD

**Issue by haplo** [magit/magit#3818]
I'm using QubesOS, which has a cool GPG setup called [Split GPG](https://www.qubes-os.org/doc/split-gpg/) where the private keys are held in a separate VM, so if your current VM is compromised then the attacker won't be able to access the private keys. I have set up git to sign commits using this setup, the only change is specifying the `gnupg` executable in `.gitconfig`, like this:

    [gpg]
        program = /usr/bin/qubes-gpg-client-wrapper

`git` works fine this way, but magit fails to commit, throwing the following error:

    128 git … commit --verbose
    Waiting for Emacs...
    error: gpg failed to sign the data
    fatal: failed to write commit object

**Comment by haplo** [comment]
I haven't debugged it fully, but my suspicion is with the use of `magit-read-gpg-secret-key` in `magit-commit.el`. There are no keys in the machine, they are all in the other VM.

If magit won't honor `.gitconfig` maybe a fix would mean using a variable that can point to `/usr/bin/qubes-gpg-client-wrapper`, it's a drop-in replacement for most usages of gnupg.

**Comment by haplo** [comment]
Another possible reason for the problem is that QubesOS displays a dialog to authorize the GPG signing operation. I saw in #2776 that magit doesn't use a pty, so maybe this is the issue? Is there something I can do to test this hypothesis?

**Comment by tarsius** [comment]
`magit-read-gpg-secret-key` is not used when committing. It is only used when setting the value of the `--gpg-sign` and `--local-user` arguments. Doing that might also fail when using your setup, but that's a different issue. If there is such an issue, then that would have to be addressed by teaching the `epg` package about your setup.

Magit just calls `git commit`, which then hands things over to `gpg.program`, which in turn concludes that it has to ask the user for a passphrase. The reason that doesn't work in this case most likely is that the question comes in a form unknown to Magit.

Do it on the command line, note the prompt, adjust `magit-process-password-prompt-regexps`, and test it. Finally open a pull request to add the regex to the default value.

**Comment by haplo** [comment]
OK, I fixed it, and it was a stupid mistake: QubesOS needs you to define a `QUBES_GPG_DOMAIN` shell variable, that wasn't defined in Emacs because I was starting it from the GUI. When I started Emacs from a shell it worked straight away, confirmation dialog and all.

Sorry for the false alarm and thank you for your time!

**Comment by 0x9060** [comment]
@haplo , I'm experiencing a similar issue with Qubes OS and magit, using split SSH. `git push` works fine from the command line (with a dialog for confirmation), but pushing from magit fails with:

```
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```

Happen to have any ideas?

**Comment by 0x9060** [comment]
@haplo  - Thanks, you're absolutely right! When I compared the 2, `SSH_AUTH_SOCK` was different. From my terminal, it's set to `/home/user/.SSH_AGENT_ssh-vault`, whereas  in Emacs it's set to some temp folder: `/tmp/ssh-[random name]/agent.709`.

Like you, when I start Emacs from the terminal, the environmental variables are then equivalent, and push from magit works fine (with a graphical popup to confirm SSH key usage). 

So... silly noob Emacs question: what's the preferred way to define this environmental variable in my Emacs config file?

I also notice there's an `SSH_AGENT_PID` that is consistent between Emacs in my terminal, which I hope will also remain consistent.

Thanks again!

**Comment by 0x9060** [comment]
I tried simply putting this in my Emacs config and it does not seem to work:

```
(setenv "SSH_AUTH_SOCK" "/home/user/.SSH_AGENT_ssh-vault")
```

Either it gets overwritten, or this is simply the wrong approach... Happy to go to Stack Exchange with this question if you don't have the time.

Thanks!
