### ISSUE TITLE
Support default worktree location

### ISSUE THREAD

**Issue by happy-barney** [magit/magit#3820]
Please allow to specify default worktree location, either via customizable template or callback function.

Example:
`~/work/{repository}/{ref-name}`

It will be nice to provide also quick worktree operation, eg `%` `q` will create worktree using known ref-name (branch or tag) and default location without dir confirmation

**Comment by tarsius** [comment]
> Please allow to specify default worktree location, either via customizable template or callback function.

What part of Magit should support that? `magit-clone` and `magit-init`? Please provide more details. If there is a way to do what you want to do using `git` directly, then show the commands needed to do it.

> It will be nice to provide also quick worktree operation, eg `%` `q` will create worktree using known ref-name (branch or tag) and default location without dir confirmation

I believe I understand this part. You want commands like `magit-worktree-{checkout,branch}` that instead of prompting for a directory just use some directory that is derived from known values; the branch name and some rule.

I don't think I would add additional commands. Instead I would add an option such as `magit-read-worktree-default-function`. That function would be called with the branch as only argument (things such as the "name of the repository" the function can determine itself) and return a directory, which is then used as the default for `read-directory-name`. You would still have to press `RET` to confirm it (and implement such a function).

**Comment by happy-barney** [comment]
ad what part: I'm fine with customizable variable - I think every user has its own workflow which is consistent regardless on repository

ad functionality: that sounds even better :-) Apart of callback via `defcustom` I believe I can even imagine implementation.

**Comment by shipmints** [comment]
Question on this feature.  I'd like to default the directory name to the selected branch name, perhaps having substituted dashes for embedded slashes.   It seems `magit-worktree-read-directory-name-function` is called only with the prompt, but not the proposed branch.  Is it intended that the let-bound `branch` variable be accessible from inside this `funcall`?

i.e., is this intended to work?

```elisp
  (defun my/magit-worktree-read-directory-name-function (prompt)
    (read-directory-name prompt branch nil 'confirm-completion))
  (setq magit-worktree-read-directory-name-function
        #'my/magit-worktree-read-directory-name-function)
```

Or should the function accept an optional branch argument?

I've done that for the time being.

```elisp
  (defun my/magit-worktree-read-directory-name-function (prompt &optional branch)
    (read-directory-name prompt
                         (if branch (string-replace "/" "-" branch)
                           default-directory)
                         nil
                         'confirm-completion))

  (setq magit-worktree-read-directory-name-function
        #'my/magit-worktree-read-directory-name-function)

  (defun my/magit-worktree-checkout (path branch)
    "Checkout BRANCH in a new worktree at PATH."
    (interactive
     (let ((branch (magit-read-branch-or-commit "Checkout")))
       (list (funcall magit-worktree-read-directory-name-function
                      (format "Checkout %s in new worktree: " branch)
                      branch)
             branch)))
    (when (zerop (magit-run-git "worktree" "add"
                                (magit--expand-worktree path) branch))
      (magit-diff-visit-directory path)))

  (advice-add #'magit-worktree-checkout :override #'my/magit-worktree-checkout)
```

**Comment by tarsius** [comment]
> Is it intended that the let-bound `branch` variable be accessible from inside this `funcall`?

Not when using lexical scope as we do in Magit.

> Or should the function accept an optional branch argument?

I've started working on that. There are backward compatibility concerns to take into account and design decisions to be made.

**Comment by shipmints** [comment]
Right on lexical binding. I was more curious if it was just a half-finished idea at the time.

I'll use my hack for the time being. And thank you for your continued Emacs work.

-Stéphane

**Comment by tarsius** [comment]
I've added a new option and added some reader functions in 6177b4d210eaa57f4a91e41c6d66a18e0b659254.

**Comment by shipmints** [comment]
Looks good. Thank you for adding the sibling and nested default implementations.

**Comment by tarsius** [comment]
If added an "offsite" variant.
