### ISSUE TITLE
auto-revert-buffer-list-filter documentation error

### ISSUE THREAD

**Issue by dhull** [magit/magit#3822]
The documentation for `auto-revert-buffer-list-filter` in `magit-autorevert.el` says:

```
This option is provided by `magit', which also redefines
`auto-revert-buffers' to respect it.  Magit users who do not turn
on the local mode `auto-revert-mode' themselves, are best served
by setting the value to `magit-auto-revert-repository-buffers-p'.
```

The `magit-auto-revert-repository-buffers-p` should be `magit-auto-revert-repository-buffer-p` (singular "buffer").

**Comment by basil-conto** [comment]
Looks like @tarsius forgot to regenerate `magit.texi` from `magit.org` before merging #3819.

**Comment by tarsius** [comment]
Ups.
