### ISSUE TITLE
When pushing I can no longer access the small options windows

### ISSUE THREAD

**Issue by joakim-hove** [magit/magit#3826]
## Background

I have just installed a fresh Debian stable box and then built emacs26.1 from source. I use spacemacs, in my spacemacs configuration I have listed the (ma)git related packages:

```
magit-gh-pulls magit-gitflow evil-magit magit magit-popup git-commit
```

## What happens
When I want to push my branch to a remote I do a `magit status` and then press `p`  to push, the window is then split in two horizontally, with a list of options (most notably `-f` to force push) in the lower window. The problem is that I can seemingly not select the lower window - the cursor will not become active here, and I can not alter the options - i.e. I currently have to go to the terminal to force push - and I force push a lot!

## M-x magit-version RET
```
Magit 20190408.1841, Git 2.11.0, Emacs 26.1, gnu/linux
```
I used the custom kill-ring command to run a plain emacs+magit session; that failed in exactly the same way - although the error messages on the frame were easier to read - they were something like:

"Unbound suffix <...> (Use `C-g' to abort, '?' for help)"

Would be extremly cool if you could help me with this magit - gets me through the working day!

**Comment by npostavs** [comment]
>  press `p` to push, the window is then split in two horizontally, with a list of options (most notably `-f` to force push) in the lower window. The problem is that I can seemingly not select the lower window - the cursor will not become active here, and I can not alter the options

Does typing in <kbd>-</kbd> <kbd>f</kbd> work?

**Comment by joakim-hove** [comment]
> Does typing in `- f` work?

Not entirely clear to me when I should press `_ f` - but when I press 'P' and then `_ f`  in the plain emacs - it does at least not work.

**Comment by npostavs** [comment]
> Not entirely clear to me when I should press `_ f`

When the window pops up; but that should be `- f`, i.e., dash not underscore.

**Comment by joakim-hove** [comment]
> When the window pops up; but that should be - f, i.e., dash not underscore.

Yes - that worked; entirely new behavior(?) - but - cool enough; thanks! What is the markdown to get those cool HTML buttons by the way?

**Comment by npostavs** [comment]
> Yes - that worked; entirely new behavior(?)

Actually, the old Magit-popup package supported `- f` in that context too. 

Magit-popup has now been replaced by Transient, which does lose support for a few workflows: https://github.com/magit/transient/issues/17#issuecomment-464243333

> What is the markdown to get those cool HTML buttons by the way?

`<kbd>key</kbd>`

**Comment by joakim-hove** [comment]
Thank you for the assistance!
