### ISSUE TITLE
[bugreport] magit blame behavior badly

### ISSUE THREAD

**Issue by ctriple** [magit/magit#3829]
i use spacemacs.

![image](https://user-images.githubusercontent.com/36628823/55929761-d445e400-5c50-11e9-8943-3796d72e4aa4.png)

b Show commits adding lines       ---- not working

![image](https://user-images.githubusercontent.com/36628823/55929810-0eaf8100-5c51-11e9-953f-5b4b9ef5476f.png)

m Blame echo                               ---- show bad (old blame with authors, dates display looks better)

**Comment by tarsius** [comment]
> b Show commits adding lines ---- not working

What about it is not working?

> m Blame echo ---- show bad (old blame with authors, dates display looks better)

`b` still does this by default. This simply serves a different purpose, you can continue to edit while blame echo is active. But this is configurable using `magit-blame-echo-style`.

I also recommend reading https://magit.vc/manual/magit/Blaming.html#Blaming. There are now multiple display styles and you can cycle through them and select the one you like as the default.

**Comment by ctriple** [comment]
```
b Show commits adding lines ---- not working
```
Unbound suffix: ‘M-m b b’ (Use ‘C-g’ to abort, ‘?’ for help)

```
m Blame echo ---- show bad (old blame with authors, dates display looks better)
```

i will read the doc, thanks

**Comment by tarsius** [comment]
> Unbound suffix: ‘M-m b b`

There is indeed no such suffix binding; the suffix is `b`. I am guessing that `M-m b` is the Spacemacs binding that brings up the popup as shown in your first screenshot. Try this instead:

1. Bring up the popup with `M-x magit-blame RET`.
2. Press `b` to invoke "Show commits adding lines".

**Comment by ctriple** [comment]
yes, it works. i think shis would be spacemacs integration bug, i will issue this to spacemacs community.

thks
