### ISSUE TITLE
Can't persist refs arguments between sessions

### ISSUE THREAD

**Issue by agzam** [magit/magit#3830]
In pre-transient Magit it was possible to set and save values for popups. One thing I have gotten used to is to have refs sorted by `committerdate`. 
It seems latest magit ignores `magit-show-refs-arguments`, maybe?

i.e. if I do: 
- `(setq magit-show-refs-arguments '("--sort=-committerdate"))`
- then open refs popup with a argument
- it shows that sort is not set

**Comment by tarsius** [comment]
See #3750.
