### ISSUE TITLE
commit message buffer should include a Commands section

### ISSUE THREAD

**Issue by benma** [magit/magit#3831]
The commented part of the commit message could inline a `Commands` section, same as when rebasing:

```
#
# Commands:
# C-c C-c  tell Git to make it happen
# C-c C-k  tell Git that you changed your mind, i.e. abort
# p        move point to previous line
```

This issue is prompted by me wanting to file an issue that I have to re-type commit messages on failure, unaware that `M-p` can restore my previous messages. This will probably save a lot of users time and help them discover features.

**Comment by tarsius** [comment]
There are many key bindings that are not always being displayed whenever it is not obvious what commands are available. That is also true for `git-rebase-mode`. The reason we display bindings there is that `git rebase --interactive` does that on its own. I don't think that the `git-commit-mode` to that mode is sufficient justification to start displaying available bindings here too.
