### ISSUE TITLE
status buffer not automatically refreshed on file changed inside emacs

### ISSUE THREAD

**Issue by zakora** [magit/magit#3833]
## Steps to reproduce
1. Do `magit-status` in a git folder, displays:
```
Head:     master initial commit

Recent commits
0aa0c82 master initial commit
```
2. Change a versioned file from this git repository.
3. Save that file within emacs

## Expected behavior
The `magit-status` buffer should show:
```
Head:     master initial commit

Unstaged changes (1)
modified   README

Recent commits
0aa0c82 master initial commit
```

## Actual behavior
Magit status buffer is not updated, showing the same:
```
Head:     master initial commit

Recent commits
0aa0c82 master initial commit
```
Typing `g` in this buffer actually refreshes to the current status.

## Notes
The [screenshots page](https://magit.vc/screenshots/#status-is-automatically-updated) says:

> If you use Emacs to edit and save a file which is located inside the repository or if you use Magit to perform some action such as staging a change, then the status buffer is automatically updated.

But maybe my interpretation is wrong, since somewhere else in the [docs](https://magit.vc/manual/magit/Automatic-Refreshing-of-Magit-Buffers.html) it is less clear that saving a file would always trigger an automatic update of magit status:

>  The status buffer may optionally be automatically refreshed whenever a buffer is saved to a file inside the respective repository. 

### `magit-version`
```
Magit 20190413.1201, Git 2.17.1, Emacs 25.2.2, gnu/linux
```
from MELPA.

### debug mode

Tested the reproducibility steps above with:
```
/usr/bin/emacs25 -Q --eval \(setq\ debug-on-error\ t\) -L /home/zakora/.emacs.d/elpa/dash-20190413.1058/ -L /home/zakora/.emacs.d/elpa/transient-20190319.1928/ -L /home/zakora/.emacs.d/elpa/with-editor-20190224.931/ -L /home/zakora/.emacs.d/elpa/magit-20190413.1201/ -L /home/zakora/.emacs.d/elpa/git-commit-20190413.1201/ -l /home/zakora/.emacs.d/elpa/magit-20190413.1201/magit
```

**Comment by tarsius** [comment]
You have to enable that feature using:

```lisp
(add-hook 'after-save-hook 'magit-after-save-refresh-status t)
```

**Comment by zakora** [comment]
Thank you for your answer. It does solve my issue!

I made an attempt to clarify the documentation  about this with PR magit/magit.vc#11 and #3834 .
Feel free to integrate or discard them.
