### ISSUE TITLE
Cannot enter SSH passphrase during fetch or push with openssh-8.0

### ISSUE THREAD

**Issue by juristi** [magit/magit#3843]
## Summary
After upgrading OpenSSH from 7.9 to 8.0 the SSH passphrase during git fetch or push can no longer be entered in minibuffer.

## Software versions
- Distro: Arch Linux, x86_64
- OpenSSH: OpenSSH_8.0p1, OpenSSL 1.1.1b  26 Feb 2019
- Emacs: GNU Emacs 26.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.8) of 2019-04-12
- Magit (from MELPA): Magit 20190422.1347, Git 2.21.0, Emacs 26.2, gnu/linux

## Steps to reproduce
1. Have a local clone of a remote git repository (e.g. from Github) over SSH with keys set up
1. Open a version controlled file in Emacs
1. `M-x magit-pull`
1. `u` (default remote branch)

### Expected result
- The minibuffer shows "`Enter passphrase for key '/home/user/.ssh/id_rsa':`", the passphrase can be entered and the action completes successfully

### Actual result
- The minibuffer shows "running git pull origin refs/heads/master"
- The passphrase query can be seen in magit-process buffer, but cannot enter any input there
- The process hangs in waiting for the key input

## Notes
- Downgrading the OpenSSH to version 7.9 fixed the problem, so the change that has broken the behaviour seems to come from there. Decided to report here, because Magit will probably need to react and adapt anyway.
- Fetching and pushing over HTTPS still works, the problem is only with interacting with the remote repository over SSH.
- Git fetch and push works fine from command line (I use bash 5.0.3)
- Link to the OpenSSH release notes for quick reference: https://www.openssh.com/txt/release-8.0
- Upgraded Magit and dependencies, restarted Emacs, used `M-x magit-emacs-Q-command` and started Emacs with the provided command, but problem persisted in all the cases.
- `M-x toggle-debug-on-error` produced no stack trace, since nothing actually crashes

**Comment by kyleam** [comment]
> The passphrase query can be seen in magit-process buffer, but cannot enter any input there

Can you show what the query is?  I wonder if it changed in the latest version and no longer matches the first item in `magit-process-password-prompt-regexps`.

**Comment by juristi** [comment]
Sure, but they seem to be identical between the versions:
7.9: `Enter passphrase for key '/home/user/.ssh/id_ed25519':`
8.0: `Enter passphrase for key '/home/user/.ssh/id_ed25519':`

Also evaluating `(re-search-forward (car  magit-process-password-prompt-regexps))` in the magit-process buffer finds the match.

**Comment by npostavs** [comment]
Maybe it outputs with different chunking? Can you try `(trace-function 'magit-process-filter)` and show the output in `*trace-output*`?

**Comment by juristi** [comment]
Two lines in `*trace-output*`:
```
======================================================================
1 -> (magit-process-filter #<process git> "^MEnter passphrase for key '/home/user/.ssh/id_ed25519': ")
1 <- magit-process-filter: #<marker at 99 in magit-process: .emacs.d>
```

The difference with the 7.9 version is the ^M in the beginning of the string. With 7.9 only the first line is shown before the prompt appears in the minibuffer. With 8.0 both lines were printed instantly.

**Comment by juristi** [comment]
Tried adding the carriage return to the regexp and the prompt started working again:
`(setq magit-process-password-prompt-regexps '("^\r?\\(Enter \\)?[Pp]assphrase\\( for \\(RSA \\)?key '.*'\\)?: ?$" "^\\(Enter \\)?[Pp]assword\\( for '\\(https?://\\)?\\(?99:.*\\)'\\)?: ?$" "^.*'s password: ?$" "^Yubikey for .*: ?$" "^Enter PIN for .*: ?$"))`

The ^M in the beginning of the prompt in the minibuffer is a bit ugly, though, but at least it works.

**Comment by juristi** [comment]
After a bit of digging, the change does indeed come from OpenSSH: https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.bin/ssh/readpass.c.diff?r1=1.52&r2=1.53
> Print an \r in front of the password prompt so parts of a password that was entered too early are likely clobbered by the prompt.

If the regex change is enough and everybody's busy, I can also try to create a PR. But that will be tomorrow evening at earliest, though.

**Comment by npostavs** [comment]
We already strip `\r` in `magit-process-filter`; the correct fix would be to shuffle the code around so that it happens before password prompt checking instead of after.

**Comment by fosskers** [comment]
Confirming that the downgrade temporarily fixes the issue.

**Comment by bezirg** [comment]
Confirming that happens on ArchLinux when upgrading `openssh (7.9p1-1 -> 8.0p1-1)`

**Comment by npostavs** [comment]
Could someone with openssh 8.x try the patch in #3849?

**Comment by fosskers** [comment]
I can confirm that the fix works for Arch Linux, even with openssh `8.0` installed.
