### ISSUE TITLE
Magit-process-filter supports user defined prompt

### ISSUE THREAD

**Issue by baolonglin** [magit/magit#3845]
Now the `magit-process-filter` does not support user defined prompt, I have pre-commit prompt like:

> "What to continue (a/f/c): "

At begining, I updated the `magit-process-yes-or-no-prompt-regexp`:

> " [[(]\\([Aa]\\(?:pply\\)?\\)[/|]\\([Ff]\\(?:orce\\)?\\)[/|]\\([Cc]\\(?:ancel\\)?\\)[])] ?[?:] ?$"

but the `yes-or-no-p` only suport 2 options, in my scenario it has 3 options.

I hack the code like:
```elisp
(defun magit-process-yes-or-no-prompt (process string)
  "Forward Yes-or-No prompts to the user."
  (when-let ((beg (string-match magit-process-yes-or-no-prompt-regexp string)))
    (let ((max-mini-window-height 30)
          (num 1)
          (choices '()))
      (while (match-string num string)
        (setq choices (cons (string-to-char (downcase (match-string num string))) choices))
        (setq num (+ num 1))
        )
      (process-send-string
       process
       (downcase
        (concat
         (string (save-match-data
                   (magit-process-kill-on-abort process
                     (read-char-choice string choices))) )
         "\n"))
       ))))
```
It works for my pre-commit, but i think it's not a good solution. It will cause yes-or-no prompt break, and not so flexable. Another idea i thought is to change `magit-process-filter`, make the prompt handling as hooks. 
What do you thing?

**Comment by tarsius** [comment]
Yes, I think something like

```diff
diff --git a/lisp/magit-process.el b/lisp/magit-process.el
index 51b3d418e..86b00cbad 100644
--- a/lisp/magit-process.el
+++ b/lisp/magit-process.el
@@ -687,6 +687,7 @@ (defun magit-process-filter (proc string)
       (magit-process-yes-or-no-prompt proc string)
       (magit-process-username-prompt  proc string)
       (magit-process-password-prompt  proc string)
+      (run-hook-with-args-until-success 'magit-process-prompt-hook proc string)
       (goto-char (process-mark proc))
       (setq string (propertize string 'magit-section
                                (process-get proc 'section)))
```

is the way to go.

**Comment by baolonglin** [comment]
Good to hear from you, much better.

**Comment by tarsius** [comment]
Are you waiting for me? I was waiting for you to say that you have succeeded implementing your function before actually adding the hook. (The surrounding code recently changed due to unrelated reasons, but it should still be easy to add this line at the appropriate place for testing purposes.)

Once you have implemented your function, it would be nice if you could add it to https://github.com/magit/magit/wiki/Tips-and-Tricks as an example.

**Comment by baolonglin** [comment]
I had no time to access the computer those days, I'll update when I have the function.

**Comment by baolonglin** [comment]
My function is ready:
```elisp
(defun tn-magit-process-apply-force-or-cancel-prompt-hook (proc str)
  "Hook method to handle STR in magit process filter with PROC."
  (when-let ((regex " [[(]\\([Aa]\\(?:pply\\)?\\)[/|]\\([Ff]\\(?:orce\\)?\\)[/|]\\([Cc]\\(?:ancel\\)?\\)[])] ?[?:] ?$")
             (beg (string-match regex str))
             (choices '(?a ?f ?c))
             (resize-mini-windows t))
    (process-send-string
     proc
     (downcase
      (concat
       (string (magit-process-kill-on-abort proc
                 (let* ((prompt-str nil)
                        (prompt-start-regex "Below files need")
                        (prompt-beg (string-match prompt-start-regex str)))
                   (if prompt-beg
                       (setq prompt-str (substring str prompt-beg))
                     (with-current-buffer (process-buffer proc)
                       (save-excursion
                         (goto-char (point-max))
                         (search-backward prompt-start-regex)
                         (setq prompt-str (concat (string-trim-right (buffer-substring (point) (point-max))) "\n" str))
                         )
                       )
                     )
                   (read-char-choice prompt-str choices t)
                   )
                 ) )
       "\n"))
     )
    )
  )
```
The reason i check `"Below files need"` is to show full information of the prompt. 
The reason i set `INPUT-KEYBOARD-QUIT` argument to be `t` to force user input one valid char is even `magit-process-kill-on-abort` set the mini-buffer key success, `C-g` dose not trigger the lambda function, the process is not exit when i input `C-g`, looks like the `read-char-choice` dose not propagate the `C-g` to the mini-buffer. I did not look into it, maybe you know more information.
`yes-or-no-p` has the same behavior, the process is not exit when i press `C-g`.
