### ISSUE TITLE
Add an "upstream changes" variant to the diff transient

### ISSUE THREAD

**Issue by fredefox** [magit/magit#3851]
Can we get a "Diff upstream" option added to the `magit-diff` menu?

I envisage a prompt for the ref to diff against (defaulting to HEAD) which then issues:

    git diff @{upstream}..REF

Documentation for the `@{upstream}` directive can be found [here](https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt-emltbranchnamegtupstreamemegemmasterupstreamememuem).

Now the difficult unresolved question is what mnemonic to use for this given that `M-x magit-diff u` is used for unstaged changes...

I'm not elisp shark, but given a few choice pointers I might even volunteer to implement this.

**Comment by tarsius** [comment]
Are you aware that pressing `RET` on `Unmerged into <upstream>` and `Unpushed to <upstream>` shows the respective diff?

**Comment by tarsius** [comment]
Note that there are at least three "compare with upstream" variants that users may find useful, depending on what they are doing: `<upstream>..HEAD`, `HEAD..<upstream>` and `<upstream>...HEAD`.

**Comment by fredefox** [comment]
> Are you aware that pressing RET on Unmerged into <upstream> and Unpushed to <upstream> shows the respective diff?

zomg. Wasn't aware of this.

> Note that there are at least three "compare with upstream" variants that users may find useful, depending on what they are doing: <upstream>..HEAD, HEAD..<upstream> and <upstream>...HEAD.

This is a fair point. I think I might be content with your point above.

Cheers.

**Comment by tarsius** [comment]
I would prefer not to add these commands at this time.

**Comment by lmartelli** [comment]
Looks like pressing `RET` on `Unmerged into <upstream>` also show the reverse diffs of `Unpulled from <upstream>`. I think it would be more convenient not to include these.

**Comment by tarsius** [comment]
Yes, but "it's more complicated than that". I have added an entry to my private todo list to look into this, but if you want to have a talk about it, then open a new issue.

This is a quick summary for why it is more complicated than that:

>       For a more complete list of ways to spell <commit>, see "SPECIFYING
>       REVISIONS" section in gitrevisions(7). However, "diff" is about
>       comparing two endpoints, not ranges, and the range notations
>       (<commit>..<commit> and <commit>...<commit>) do not mean a range as
>       defined in the "SPECIFYING RANGES" section in gitrevisions(7).
