### ISSUE TITLE
Jump to a branch in log buffer

### ISSUE THREAD

**Issue by yurikhan** [magit/magit#3853]
I’m in a log buffer (`l a` with `--graph --color --decorate -n"4096"`, no `--simplify-by-decoration`), pruning old local branches. In another window, I have a list of local branches (`y`).

In the list of branches, I see a branch name. In the log buffer, I want to jump to that branch, so that I see it in the context of the commit graph — whether it has been merged into the development branch, whether it has been rebased; basically, whether I can safely delete it.

Unsatisfying workarounds:

* I can start an isearch and type the branch name, but that can give lots of false positives if the branch name is a word commonly used in commit message summaries.

* I can start an isearch and type in a part of a commit message summary, but that is a lot of typing and inconvenient. It can also give false positives if the branch has been rebased a few times.

The obvious user interface would be a key binding in `magit-log-mode`, first prompting for any commitish (a prefix of a commit hash, a branch name, a tag name, a remote ref name, the symbolic reference `HEAD`, or any history expression; with completion for any references) and moving point to that commit’s line and decoration if applicable. I’d maybe even bind it to something starting with `M-g`.

Bonus points for a key binding in any magit buffer mode where a commitish can be displayed, to grab the commitish thing at point and jump to it in the appropriate log buffer.

**Comment by tarsius** [comment]
> whether it has been merged into the development branch, whether it has been rebased; basically, whether I can safely delete it.

These questions can be answered by using the features available in the refs buffer. Some of those features are disabled by default, so read the documentation: https://magit.vc/manual/magit/References-Buffer.html.

As for the "jump to this ref in a log" command that you are proposing, that sounds useful and simple enough, but doing it properly would likely be a lot of work. I don't intend to do that anytime soon, so here is a minimal viable implementation instead:

```emacs-lisp
(defun magit-log-jump-to-branch (rev)
  (interactive (list (magit-read-branch-or-commit "In log, jump to")))
  (with-current-buffer
      (cond ((derived-mode-p 'magit-log-mode)
             (current-buffer))
            ((when-let ((buf (magit-get-mode-buffer 'magit-log-mode)))
               (pop-to-buffer-same-window buf)))
            (t
             (apply #'magit-log-all-branches (magit-log-arguments))))
    (magit-log-goto-commit-section (magit-rev-abbrev branch))))
```

**Comment by tarsius** [comment]
I've added this command as `magit-log-move-to-revision`, see #4418.
