### ISSUE TITLE
`auto-revert-buffers-counter` has been removed from `autorevert.el`

### ISSUE THREAD

**Issue by waymondo** [magit/magit#3859]
The variable `auto-revert-buffers-counter` has been removed from `autorevert.el` on Emacs master in favor of an alternative polling mechanism:

https://github.com/emacs-mirror/emacs/commit/c61bbb4c8e7e2f2068c1cfac9a001806a1969202#diff-bda3e8e824c8b5f088c5f98de8503fac

As such, this conditional Emacs logic does not define the missing variable and errors are thrown when `magit-auto-revert-mode` is enabled:
https://github.com/magit/magit/blob/master/lisp/magit-autorevert.el#L210

**Comment by tarsius** [comment]
There's already a pull-request for that:  #3854.

I'll try to look into this later today or tomorrow.

**Comment by waymondo** [comment]
Oh nice. I searched through the issues but forgot to check for any related open PRs.

**Comment by tarsius** [comment]
Merged.
