### ISSUE TITLE
Kill all associated buffers when killing a project's status buffer

### ISSUE THREAD

**Issue by tsdh** [magit/magit#3862]
I work with many repositories throughout a day.  Most of the I only need temporarily, i.e., I open a Magit status buffer for one of them, update the project, maybe view the log, add a commit, and then kill the status buffer when I'm done and move on.

It would be nice if killing a project's status buffer would (maybe optionally) also kill all associated Magit buffers like the `magit-process` buffer, all `magit-log`, `magit-revision` and `magit-diff` buffers for that project, etc.

Right now, those buffers just stick around until you kill them manually.  Because of their uniform naming scheme (common prefix), they can easily make buffer switching more cumbersome.

If you think that's a good idea in general, feel free to comment how you'd like to have it implemented and I'll do it and add a PR.

**Comment by tarsius** [comment]
I would merge that.

The interface seems simple enough:

```emacs-lisp
(defun magit-mode-bury-buffer (&optional kill-buffer)
  "Bury the current buffer.
With a prefix argument, kill the buffer instead.
This is done using `magit-bury-buffer-function'."
  (interactive "P")
  (funcall magit-bury-buffer-function kill-buffer))
```

I would suggest adding a `magit-bury-buffer-function`-implementation, which takes two prefix arguments to mean "... and also kill all the other Magit buffers for this repository".

**Comment by tsdh** [comment]
Will do!

**Comment by tsdh** [comment]
@tarsius That was easier than I've thought.  And my first encounter with Forge which is really awesome!
