### ISSUE TITLE
ediffing shows strange diffs

### ISSUE THREAD

**Issue by haifenghan** [magit/magit#3864]
I'm using the latest Magit 20190502.1206, Git 2.21.0, Emacs 26.2, gnu/linux.
In the status buffer, when pressing the `e` command on a unstaged file, it will show:

1) HEAD file and working file are totally different
2) INDEX file is empty

I tried to delete all magit packages and to reinstall them, however, magit still has this issue.
Please see the below screenshot. Could you please look into it?

![image](https://user-images.githubusercontent.com/4157827/57176065-e4369980-6e85-11e9-9d70-e053916cad51.png)

**Comment by michael-heerdegen** [comment]
I'm having similar problems with the Magit Ediff interface.  All index buffers are empty.

**Comment by tarsius** [comment]
Thanks for the report.

**Comment by michael-heerdegen** [comment]
There is still a problem: updating the index from an index buffer fails with an error "[file] isn't visiting the index".  Try magit-stage for example, you get the error after exiting Ediff (q).

**Comment by tarsius** [comment]
That should now work again too.

**Comment by michael-heerdegen** [comment]
Yip, works - thanks!
