### ISSUE TITLE
If 'Recent commits' is collapsed behaviour of C-n is incorrect

### ISSUE THREAD

**Issue by baerrach** [magit/magit#3867]
Magit 20190501.2009, Git 2.21.0.windows.1, Emacs 26.2, windows-nt

When navigating `(magit)Status Buffer` via `C-n` I expect the cursor to move to the next thing correctly, but when 'Recent commits' is collapsed it will jump down quite a few lines instead of just moving to the next line. If I expand 'Recent commits' then everything behaves correctly.

**Comment by tarsius** [comment]
Since I cannot reproduce that I will need more information like for example what command C-n is bound to for you and from where to where that jumps.

**Comment by baerrach** [comment]
Ok I've managed to reproduce it on my home computer as well

Magit 20190507.130, Git 2.16.2.windows.1, Emacs 25.1.1, windows-nt

Here is what the status buffer is displaying

```
Head:     master Applied prettier.
Merge:    origin/master Applied prettier.

Unstaged changes (1)
modified   README.md

Staged changes (1)
modified   gatsby-config.js
```

describe-key C-n says

C-n runs the command next-line (found in global-map), which is an interactive
compiled Lisp function in ‘simple.el’.

It is bound to C-n, <down>.

If you press Tab on Staged changes to collapse it, and then press C-n the pointer will move past the end of the buffer ~ 15 blank lines past Staged changes.

Pressing C-n again moves the pointer directly under Staged changes.

If I expand Staged changes, C-n moves down one line at a time without jumping around.

**Comment by tarsius** [comment]
This sounds like another error occurred earlier while the status buffer was being refreshed. Check *Messages* for errors. The weird movement is probably due to the buffer being corrupted due to the earlier error.

**Comment by baerrach** [comment]
*Messages* has no errors when it jumps past the end of the buffer.

**Comment by baerrach** [comment]
I found that I can `C-n` when its collapsed anywhere from `Unstaged c hanges` downwards.

But if I `C-n` anywhere in the first 3 lines the problem shows up.

**Comment by tarsius** [comment]
It's hard to imaging that `next-line` would do that. The buffer would have to be really messed up for that to happen (though maybe in a way that is not visible). I still think that the problem could be that an error occurred when the buffer was first created or refreshed. You say:

> `*Messages*` has no errors when it jumps past the end of the buffer.

Does that mean that no errors appear due to `next-line` being invoked or that it does not contain any errors to begin with? I am interested in the later.

We are now down to basic debugging strategies.

1. Do `M-x toggle-debug-on-error`, followed by `M-x magit-status`. If that causes a backtrace, then that would be very useful.

2. Try to reproduce the issue without your configuration, using `emacs -Q` (see https://magit.vc/manual/magit/Debugging-Tools.html).

**Comment by baerrach** [comment]
`*Messages*` has no new entries when I `C-n` and the problem occurs.

I'll try what you suggest.

**Comment by baerrach** [comment]
I've forgotten that I needed to follow your instructions, so I haven't done that yet.

This morning on a restart of Emacs I noticed these errors with Recent commits was collapsed

```
user-error: Cannot hide root section
user-error: No next section [2 times]
```

**Comment by baerrach** [comment]
Following the instructions in the debugging tools and running Emacs with only Magit via the clipboard command produces no problems...

Hacking magit-extras.el/next-line to add `(message "stay=%s (max (1- arg) 1)=%d arg=%d try-vscroll=%s" stay (max (1- arg) 1) arg try-vscroll)`

Produces the same message `stay=t (max (1- arg) 1)=1 arg=1 try-vscroll=1` even when the error occurs.

Which would indicate that the problem is within next-line not magit.

I noticed an advice around next-line, which was for smooth-scrolling. Turning that off didn't fix the problem either. 

I'll have to live with the problem since its not magit and I've exhausted my Emacs-fu trying to investigate.

**Comment by baerrach** [comment]
I'm in the process up cleaning up my crusty `init.el` and migrating to `use-package`.

I've worked around the problem by using
```
  :custom
  (magit-section-initial-visibility-alist
   '((untracked . show)
     (unstaged . show)
     (unpushed . show)
     (unpulled . show)
     (stashes . show)))
```

So its always visible.

I've also noticed that I had an newer version of magit BUT an older configuration setup.

Once I've cleaned up my setup files I'll be in a better position to work out where the problem is.
