### ISSUE TITLE
magit-subtree arguments are ignored

### ISSUE THREAD

**Issue by danielmartin** [magit/magit#3868]
**Magit version:** Magit 20190507.130, Git 2.20.1 (Apple Git-117), Emacs 26.2, darwin

**Steps to reproduce the problem:**

- Open a repository and Magit status.
- Type O (Subtree)
- Type i (Import)
- Select Squash (-s)
- Type f (Pull)

**Expected results:**

The git subtree command invocation has a `--squash` argument.

**Actual results:**

The git subtree command invocation does not have a `--squash` argument.

This seems to happen because the arguments are taken from the `magit-subtree` transient command, which does not have any arguments (as it was recently split in `import` and `export`).

**Comment by tarsius** [comment]
Thanks for the report!
