### ISSUE TITLE
`magit-status` across file systems and mounts

### ISSUE THREAD

**Issue by Alexander-Shukaev** [magit/magit#3869]
```
Magit 20190328.1154, Git 2.21.0, Emacs 26.2, gnu/linux
```

Initialize a Git repository somewhere and maybe add a file.  Then create a mount point inside of this repository, i.e. let some other file system be mounted to some nested directory in the repository.  You can then add some files from it as well.  Observe that `git status` works everywhere, either outside of that mount point or inside (as long as it is issued in the repository), while `magit-status` works only outside of the mount point.  Inside of the mount point `magit-status` offers to initialize a new repository.  `(setenv "GIT_DISCOVERY_ACROSS_FILESYSTEM" "1")` did not help.

**Comment by tarsius** [comment]
> `(setenv "GIT_DISCOVERY_ACROSS_FILESYSTEM" "1")` did not help.

For me it did. Before I did that it didn't work, afterwards it did.

**Comment by Alexander-Shukaev** [comment]
The reason may be that I do it via TRAMP.  Could you try via e.g. `sudo`?  The oddity is that the environment variable `GIT_DISCOVERY_ACROSS_FILESYSTEM` is set even in `sudo` TRAMP buffer, where I invoke `magit-status`.

**Comment by tarsius** [comment]
> The oddity is that the environment variable `GIT_DISCOVERY_ACROSS_FILESYSTEM` is set even in `sudo` TRAMP buffer,

Are you sure about that? Tramp uses `tramp-remote-process-environment`, not `process-environment`.

**Comment by Alexander-Shukaev** [comment]
Fixed with:

```
  (define-advice tramp-open-shell
      (:around (function vec &rest ...) init/:around)
    #$
    (let ((tramp-remote-process-environment
           (if (and (equal (tramp-file-name-method vec) "sudo")
                    (equal (tramp-file-name-host   vec) (system-name)))
               (prog1
                   process-environment
                 (message "Overridden (locally) \
the default value of variable `%s' (by the current value of variable `%s'):
- current: %s
- default: %s"
                          'tramp-remote-process-environment
                          'process-environment
                          process-environment
                          tramp-remote-process-environment))
             tramp-remote-process-environment)))
      (apply function vec ...)))
```

Sorry for the noize.
