### ISSUE TITLE
Show prencentage in magit-clone

### ISSUE THREAD

**Issue by azzamsa** [magit/magit#3870]
When using `magit-clone` for big size repo, we didn't get any feedback how far the clone is going. Is it better to show how many percent left, so we get a good feedback from this operation ?

this is the original git clone output looks like:

![https://www.decodingdevops.com/wp-content/uploads/2018/09/git-clone-remote-repository.png](https://user-images.githubusercontent.com/17734314/57415703-20bc1980-7227-11e9-998e-e7dcbda37a50.png)

Thank you for this awesome package.

**Comment by tarsius** [comment]
This has been suggested before.

I don't want to do this because it would require major changes to how process output is read and I don't think this is worth it. Maybe eventually.

**Comment by azzamsa** [comment]
Sorry, searched in closed issue but not found. Maybe I put different search key.

By the way, Thank you for magit.

**Comment by tarsius** [comment]
Yeah, I didn't find it either. I would have linked it otherwise. Cheers!
