### ISSUE TITLE
P p now pushes to merge branch instead of push branch

### ISSUE THREAD

**Issue by aaronjensen** [magit/magit#3872]
```
Magit 20190508.655, Git 2.19.1, Emacs 27.0.50, darwin

$ git --version
git version 2.19.1
```

I'm not sure what caused it, but `P p` now pushes to the merge branch instead of the push remote on one of my projects. I just force pushed over master on accident because of this... Did I do something wrong or is something broken?

**Comment by kyleam** [comment]
I haven't noticed any issues in my daily usage and can't trigger an issue with a test repo.  Can you reproduce the issue with a test repo?  Also it could be useful to show the process buffer output for that push, if you still have it around, as well as the .git/config section for that branch.

**Comment by aaronjensen** [comment]
I'll try and repro on a new repo soon. In the meantime:

<img width="810" alt="CleanShot 2019-05-11 at 20 50 42@2x" src="https://user-images.githubusercontent.com/8588/57577545-76164780-742e-11e9-928d-781a69d6ea40.png">


```
[branch "fetch-boards-lazily-on-account-management"]
	remote = origin
	merge = refs/heads/master
```



```
  0 git … push -v origin refs/heads/fetch-boards-lazily-on-account-management
Pushing to git@github.com:org/repo.git
Total 0 (delta 0), reused 0 (delta 0)
To github.com:org/repo.git
   988e7f793..81bc3009f  fetch-boards-lazily-on-account-management -> master
updating local tracking ref 'refs/remotes/origin/master'
```

**Comment by aaronjensen** [comment]
Thanks, @kyleam. I think I actually want `push.default=current`, now, so I'll change to that as well.
