### ISSUE TITLE
magit-view-git-manual-method should be set to nil for gitman to work?

### ISSUE THREAD

**Issue by pedz** [magit/magit#3873]
Magit v2.90.1-659-g2ba84577-dirty, Git 2.20.1, Emacs 26.1, darwin

#### what behavior you expected
If I accept the default for magit-view-git-manual-method or customize it to use "info", I would expect it to work.  The particular test was going to the "Worktree" node in the magit info and clicking on the "Also see *note (gitman)git-worktree::." text.

#### what behavior you observed
user-error: Invalid value for ‘magit-view-git-manual-method’

#### and how we can reproduce the issue.
  * Start emacs
  * ^h-i => start info
  * m magit => go to info magit
  * m worktree => go to the worktree node
  * click the (gitman)git-worktree text.

#### Fix ?
If magit-view-git-manual-method is set to nil, it works just fine.  Looking at the code, this appears to be how it should work but the info for the variable as well as the customization process does not allow nil.

**Comment by kyleam** [comment]
Thanks for the report.  The default value `info` is now handled.
