### ISSUE TITLE
New changes breaks "ask for confirmation before push" tip from wiki 

### ISSUE THREAD

**Issue by akash-akya** [magit/magit#3875]
https://github.com/magit/magit/commit/7fee4089f6fd4ef50e3b15202e2f97aded9cc2ed breaks https://github.com/magit/magit/wiki/Tips-and-Tricks/cd6ff1c66f8910632daf2cff4babe1d764c5ef1f#ask-for-confirmation-before-pushing-to-originmaster as `magit-push-current-to-pushremote` no longer goes through `magit-git-push`. I know new changes don't necessarily *have* to work with these hacks. But Is there an alternate solution to this? If not please close this.

Also, I have removed this tip from the wiki.

Magit version:
Magit 20190507.1317, Git 2.16.3, Emacs 26.2, darwin

**Comment by tarsius** [comment]
I don't see a way to do this using advice given the current implementation.

**Comment by npostavs** [comment]
Wouldn't something like this work? Or am I missing some subtlety?

```elisp
(defun query-magit-push-upstream (args)
  (when-let ((branch (magit-get-current-branch)))
    (unless (yes-or-no-p (format "Push %s branch upstream to %s? "
                                 branch
                                 (magit-get "branch" branch "remote")))
      (user-error "Pushed aborted"))))

(advice-add 'magit-push-current-to-upstream :before #'query-magit-push-upstream)
```

**Comment by tarsius** [comment]
You are right, that should work.

**Comment by akash-akya** [comment]
Thought of that, but I think that works only for `upstream`? not other remotes

**Comment by npostavs** [comment]
> Thought of that, but I think that works only for `upstream`? not other remotes

The advice you linked to only talks about `magit-push-current-to-upstream`, but you could write similar advice for the other `magit-push-*` commands too.

**Comment by azzamsa** [comment]
The current wiki doesn't had the updated solution from npostavs. Should we update the wiki?

**Comment by phil-s** [comment]
FWIW, I (unsurprisingly) agree with restoring this to the Wiki.  I still consider it an important safety net for my own workflows.

**Comment by kyleam** [comment]
It looks like it was removed by Akash because it was out of date (9e0b207), so I don't think there would be any objections to someone adding an updated/working variant.

**Comment by phil-s** [comment]
Done.  https://github.com/magit/magit/wiki/Tips-and-Tricks#ask-for-confirmation-before-pushing-to-originmaster
