### ISSUE TITLE
"Warning (magit): Magit no longer uses Magit-Popup." could be more helpful

### ISSUE THREAD

**Issue by aspiers** [magit/magit#3877]
After a recent upgrade of packages, I get:

```
Warning (magit): Magit no longer uses Magit-Popup.
It now uses Transient.
See https://emacsair.me/2019/02/14/transient-0.1.

However your configuration and/or some third-party package that
you use still depends on the `magit-popup' package.  But because
`magit' no longer depends on that, `package' has removed it from
your system.

If some package that you use still depends on `magit-popup' but
does not declare it as a dependency, then please contact its
maintainer about that and install `magit-popup' explicitly.

If you yourself use functions that are defined in `magit-popup'
in your configuration, then the next step depends on what you use
that for.

* If you use `magit-popup' to define your own popups but do not
  modify any of Magit's old popups, then you have to install
  `magit-popup' explicitly.  (You can also migrate to Transient,
  but there is no need to rush that.)

* If you add additional arguments and/or actions to Magit's popups,
  then you have to port that to modify the new "transients" instead.
  See https://github.com/magit/magit/wiki/Converting-popup-modifications-to-transient-modifications [5 times]
```

I really appreciate the level of care which went into crafting this helpful message, but the problem I am facing is that it is not immediately obvious how to figure out *which* of the very many packages I use is depending on `magit-popup`.  Until I figure that out, I can't follow the stated request of contacting the relevant maintainers.  (BTW I don't use it to define my own popups.)

So would it be possible for this error message to be improved to show those packages, or at least give a hint on how to find them?  Thanks!

**Comment by aspiers** [comment]
Rapid epilogue: since I am reasonably familiar with the whole ELPA ecosystem, it occurred to me that a simple `grep -r magit-popup ~/.emacs.d/elpa` would find packages still using this, and sure enough it turned up `magit-topgit` and `magit-gerrit` which are probably both unmaintained, and both of which I was requiring in my init files.  Removing the requirements made the error vanish.  But my main point was that it would be nice if the error message had automatically listed these packages in the first place, or at least suggested the `grep -r` command or something else appropriate.

**Comment by tarsius** [comment]
That's the only other packages I found by grepping all packages on the Emacsmirror. There are a bunch of other packages that could switch to `transient` or somehow do something with `magit-popup` without depending on `magit-popup`, but from a quick look I think that the don't *need* to be updated to prevent errors.

**Comment by aspiers** [comment]
Great job, thanks!
