### ISSUE TITLE
magit-auto-revert-mode makes it near impossible to edit files with conflicts

### ISSUE THREAD

**Issue by mscfd** [magit/magit#3878]
With magit-auto-revert-mode enabled, the cursor within a file containing conflicts (from merge, rebase, stash pop ...) automatically jumps to the next conflict after a few seconds. This makes it near impossible to reasonably read, edit and finally resolve conflicts. Disabling magit-auto-revert-mode resolves the issue and allows to edit the buffer.
I have not found any options controlling this behaviour. I am also lost why this (automatically jumping to the next conflict) is even part of magit-auto-revert-mode? Offering a function which can be bound to a key sounds like a good idea, though.

**Comment by tarsius** [comment]
I cannot reproduce this. Check if you have added `smerge-start-session` to any hooks.

**Comment by mscfd** [comment]
Strange, at my home laptop with a somewhat older emacs version (26.0.50, half a year old or so) and slightly different setup I cannot reproduce it either. On my computer at work it looks like that smerge-next is executed automatically, but by whom? To which hooks should I add smerge-start-session? And if smerge-next is executed automatically, then smerge session is already running, right? Actually I have tried turning off smerge session, but as far as I remember it is re-enabled automatically. I will check tomorrow. Any further hints about how I can debug this issue?

**Comment by npostavs** [comment]
> On my computer at work it looks like that smerge-next is executed automatically, but by whom?[...] Any further hints about how I can debug this issue?

`M-x debug-on-entry RET smerge-next RET` might give some hints.

**Comment by mscfd** [comment]
Well, I found the option causing this problem. It is auto-revert-check-vc-info. Enabling it causes the smerge-session to be restarted every 5 seconds, which then calls smerge-next. Even if I turn off smerge-mode, it is restarted automatically. Now, I cannot recall where I exactly picked up the auto-revert-check-vc-info option. It was definitely after compiling the new emacs 26.2. This finally resolved the git locked problem, and I re-enabled the magit-auto-revert-mode. In conjunction with this I also added the auto-revert-check-vc-info option.
Searching for auto-revert-check-vc-info I came across https://emacs.stackexchange.com/questions/48090/mode-line-not-updated-after-checking-out-new-branch-using-magit, which suggests that using magit in conjunction with auto-revert-check-vc-info should not be a problem? So there might still be more to it?

Anyway, thanks for the help!

**Comment by mscfd** [comment]
Ups, I missed that the stackexchange link contains a link to the magit manuals itself: https://magit.vc/manual/magit/The-mode_002dline-information-isn_0027t-always-up_002dto_002ddate.html

**Comment by tarsius** [comment]
> It is auto-revert-check-vc-info. Enabling it causes the smerge-session to be restarted every 5 seconds, which then calls smerge-next.

Sounds like a bug in vc/smerge (though maybe it is a feature and you are using it in an unexpected way).

Thanks for this information; if someone else runs into this, then it might help I heard about it before.

**Comment by pera** [comment]
Sorry for the necrobump but I am also experiencing this issue and I believe this could make a simple workaround:
```elisp
(add-hook 'smerge-mode-hook (lambda () (setq auto-revert-check-vc-info (not smerge-mode))))
```
If anyone has a better solution please let me know.
