### ISSUE TITLE
Update documentation concerning `magit-log-section-arguments`

### ISSUE THREAD

**Issue by fredefox** [magit/magit#3879]
`magit-log-section-arguments` was removed in 4641aa07e0b1f4654fceb139a36b160d594d7846, however they are still mentioned in the user manual.

For my use-case I'm currently trying to figure out how to get rid of the `--graph` argument.

**Comment by tarsius** [comment]
> For my use-case I'm currently trying to figure out how to get rid of the `--graph` argument.

https://magit.vc/manual/transient/Saving-Values.html
