### ISSUE TITLE
git blame weird behavior on spacemacs master branch

### ISSUE THREAD

**Issue by neo-anderson** [magit/magit#3883]
Please explain
    (1) Magit blame to show blame information of the open file
    (2) No blame information is shown
    (3) Use master branch version of spacemacs and open magit blame `SPC g b`.

"Please include a backtrace in your report.  In most cases doing:
    M-x toggle-debug-on-error RET"
Not sure where to find the backtrace. There was nothing in "Messages" buffer.

Also post the output of:
    M-x magit-version 
`Magit 20190520.1708, Git 2.13.2, Emacs 27.0.50, darwin`

I also noticed that the magit blame arguments window is not shown in the development build. 

Screenshot of magit blame in Spacemacs (master)
<img width="986" alt="Screen Shot 2019-05-21 at 12 37 53 PM" src="https://user-images.githubusercontent.com/7310004/58125538-a3e55400-7bc5-11e9-889c-67368970059f.png">

Magit blame in Spacemacs (development)
<img width="985" alt="Screen Shot 2019-05-21 at 12 42 19 PM" src="https://user-images.githubusercontent.com/7310004/58125684-f9b9fc00-7bc5-11e9-8adc-4e594717b6db.png">

**Comment by tarsius** [comment]
If you are using the same Magit version in both cases and it works with the master version of Spacemacs but not the development version of Spacemacs, then the issue is in the development version of Spacemacs and this should be reported in the issue tracker of Spacemacs.

It might be that in the latter case you are in `edit` mode and in the former you are in `insert` (?) mode. I don't use Vi bindings so I don't know more about this.

**Comment by kivikakk** [comment]
I'm experiencing this too, and per the user above, the strange behaviour is Spacemacs master, not Spacemacs development. I'm not using evil mode or vi bindings and it happens regardless.

Happy to help diagnose further if you can point me in the right direction, but blame is weirdly broken at the moment.

**Comment by tarsius** [comment]
Sounds like an issue that was fixed in Spacemacs' development branch but for some reason wasn't backported to the master branch. You could try to locate the commit that introduced the fix (and related issues and pull-requests) and then ask for it to be backported.

**Comment by tarsius** [comment]
The issue might be related to the `Press [_b_] ... up or quit` message--Magit isn't responsible for that message.

**Comment by kivikakk** [comment]
> Magit isn't responsible for that message.

TIL! In that case, I think it's very likely entirely on Spacemacs' end. Thank you for your response!

**Comment by kivikakk** [comment]
Upgraded to Spacemacs develop, and everything is fine. Thanks for your patience.
