### ISSUE TITLE
magit loses faces when num3-mode active

### ISSUE THREAD

**Issue by stribb** [magit/magit#3885]
### Context

Magit v2.90.1-423-g0abc761f, Git 2.21.0, Emacs 26.2, darwin

I have num3-mode globally enabled, but magit status modes and num3-mode interact poorly.

### Expected

magit faces in all their glory even using num3-mode:

<img width="707" alt="Screenshot 2019-05-23 at 10 27 44" src="https://user-images.githubusercontent.com/7216352/58238909-665d0400-7d48-11e9-9f22-f72738793a19.png">

### Observed

Most of the faces were missing. See attached images.

<img width="707" alt="Screenshot 2019-05-23 at 10 31 05" src="https://user-images.githubusercontent.com/7216352/58238813-3877bf80-7d48-11e9-940d-7ba492dbbe38.png">

3. I can reproduce using the following command-line, inspired by M-x magit-emacs-Q-command:

```
/Applications/Emacs.app/Contents/MacOS/Emacs-x86_64-10_14 -Q --eval \(setq\ debug-on-error\ t\) -L /Users/andstrib/.emacs.d/elpa/dash-2.15.0/ -L /Users/andstrib/.emacs.d/straight/repos/transient/lisp/ -L /Users/andstrib/.emacs.d/elpa/with-editor-2.8.1/ -L /Users/andstrib/.emacs.d/straight/repos/magit/lisp/ -L  /Users/andstrib/.emacs.d/straight/repos/num3-mode/ -l /Users/andstrib/.emacs.d/straight/repos/magit/lisp/magit --eval \(load-library\ \"num3-mode\"\) --eval \(global-num3-mode\)
```

Then go to a git repo and run `M-x magit`.

The reason this feels like a Magit bug is that num3-mode works fine with (eg) programming language and `org-mode` major modes.

**Comment by tarsius** [comment]
> The reason this feels like a Magit bug is that num3-mode works fine with (eg) programming language and `org-mode` major modes.

Modes that only work properly in buffers in which `font-lock` is enabled should only be enabled such buffers. Globalized variants of that mode should forgo turning the local variant on in buffers in which that causes breakage. That's why I think it is a `num3-mode` bug.

Merging #3840 would probably "fix" this.

**Comment by stribb** [comment]
I came across this bug in a different guise earlier today and I'm inclined to agree with @tarsius -- thanks for the explanation!

Turns out `num3-mode` was stomping on my `helm-mode` faces.

Here's how I'm working around it for now, while I try to find a less hacky solution:

``` emacs-lisp
(defadvice num3-mode (around stribb/num3-mode-turn-on-maybe)
      (let ((mode (symbol-name major-mode)))
        (unless (or (string-prefix-p "magit-" mode)
                    (string-prefix-p "helm-" mode))
          ad-do-it)))
    (ad-activate 'num3-mode
```

**Comment by tarsius** [comment]
Font-lock-using minor-modes are actually support in magit buffers now, so your kludge isn't strictly *necessary* anymore, but you might still want to keep it since `num3-mode` makes little sense in such buffers.
