### ISSUE TITLE
Fringe color is hard-coded

### ISSUE THREAD

**Issue by valff** [magit/magit#3887]
With solarized light theme, the fringe color is too similar with background. I found that it is hard-coded here:

https://github.com/magit/magit/blob/faa0e52a6b67280e5114bd87b8958071dbac1af6/lisp/magit-section.el#L1368

It would be great if this color was configurable.

**Comment by tarsius** [comment]
I agree this should not be hard-coded, but I do not agree that the color is not suitable for solarized light. That's the them I am using and IMO the color hits the sweet spot between intrusive and still being visible enough if you actually look for information in the fringe.

By the hard-coded color is the same color as one how gets from the `fringe` face when using solarized light.

**Comment by valff** [comment]
Don't know maybe my display is calibrated differently or it is because I use solarized light from doom-themes package. But I just added this to my config:

```elisp
(set-face-foreground 'fringe "#96A7A9")
```

And I like how it looks now. Thank you for this change!
