### ISSUE TITLE
magit-file-untrack - do not match any files

### ISSUE THREAD

**Issue by happy-barney** [magit/magit#3895]
magit version: 2.90.1

attempt to untrack current buffer's file fails unless file is in git root.

Step to reproduce:
- open for example `list/magit-files.el`
- `M-x magit-file-untrack`
-- prompt correctly uses current buffer's file path as default
-- prompt refuses to accept relative file name

Result:
```
fatal: pathspec ... did not match any files
```

Expected reason:
git command is executed from buffer directory not project directory

**Comment by tarsius** [comment]
Thanks for the report.
