### ISSUE TITLE
View logs from multiple points in a single repository simultaneously

### ISSUE THREAD

**Issue by IvanMalison** [magit/magit#3896]
Forgive me if the ability to do this already exists -- I looked through magit's documentation and C-h v for anything that looked like it might have an effect and found nothing.

Basically I want to be able to look at the logs starting from two different refs in a single repository, but magit seems to have a dedicated buffer for showing logs, so this is not possible afaict.

**Comment by kyleam** [comment]
You can use the magit-toggle-buffer-lock command for this.

**Comment by IvanMalison** [comment]
thanks @kyleam
