### ISSUE TITLE
Magit commit results Lisp nesting exceeds max-lisp-eval-depth

### ISSUE THREAD

**Issue by MatthewZMD** [magit/magit#3897]
When I try to commit something using magit, it breaks emacs and prompting lisp nesting exceeds `max-lisp-eval-depth`.
This is what I am seeing when pressing `$`
```
﻿  1 git.exe … "commit" "--"

*ERROR*: Lisp nesting exceeds ‘max-lisp-eval-depth’error: There was a problem with the editor '"c:/Development/Programs/emacs-27.0.50-snapshot-2019-06-08-x86_64/bin/emacsclient.exe"'.
Please supply the message using either -m or -F option.
```

This is what I am seeing in *Messages* buffer

```
Turning on magit-auto-revert-mode...done (0.451s, 11 buffers checked)
﻿Running C:/Development/Programs/Git/mingw64/libexec/git-core/git.exe commit --
Git failed ... [Hit $ to see buffer magit-process: x for details]
Error in post-command-hook (magit-auto-revert-mode-check-buffers): (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
Updating buffer list...done
Magit 20190609.1424, Git 2.21.0.windows.1, Emacs 27.0.50, windows-nt
Entering debugger...
getenv: Lisp nesting exceeds ‘max-lisp-eval-depth’
Error in post-command-hook (magit-auto-revert-mode-check-buffers): (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
Entering debugger...
Quit
Entering debugger...
Unchanged content check: (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
Entering debugger...
vc-rcs-registered: Lisp nesting exceeds ‘max-lisp-eval-depth’
```
I do not see anything even after turning on `toggle-debug-on-error`

This is my [configuration](https://github.com/MatthewZMD/.emacs.d#magit).

**Comment by npostavs** [comment]
> This is my [configuration](https://github.com/MatthewZMD/.emacs.d#magit).

Does it happen also without your configuration? (i.e., using the result of `M-x magit-emacs-Q-command`)

I'm not sure if it would cause this, but I think your `enable-smerge-maybe` is redundant since Emacs 25.1: `vc-git-find-file-hook` enables smerge already.

**Comment by MatthewZMD** [comment]
Yes I also figured it out just now. I found out about smerge from [stackexchange](https://emacs.stackexchange.com/a/16470) recently and copied that code to give it a try. I wasn't aware the connection between that function with the error in magit commit before. Once removing that function, the error does to resolve. I think this issue can be closed now.
