### ISSUE TITLE
Missing magit-log-arguments variable?

### ISSUE THREAD

**Issue by AndreaCrotti** [magit/magit#3900]
I'm running magit version:
`Magit 20190613.2124, Git 2.17.2 (Apple Git-113), Emacs 26.2, darwin`

and I noticed that from the function doc `magit-log-buffer-file`

```
magit-log-buffer-file is an interactive compiled Lisp function in
‘magit-log.el’.

(magit-log-buffer-file &optional FOLLOW BEG END)

Show log for the blob or file visited in the current buffer.
With a prefix argument or when ‘--follow’ is part of
‘magit-log-arguments’, then follow renames.  When the region is
active, restrict the log to the lines that the region touches.

[back]
```

it mentions a `magit-log-arguments` which I thought would be a `defcustom` from that doc.
However I can only find a function called like that, I guess if I set the var manually it will still work (it works with `C-u` prefix) but should there be a `defcustom` to customise for this?

**Comment by tarsius** [comment]
I have removed all mentions of this variable, which I removed a while ago.

To learn how to set arguments see the [Transient manual](https://magit.vc/manual/transient). Especially section 2.7 and the rest of 2.
