### ISSUE TITLE
Cycle merge branch commits inside magit log

### ISSUE THREAD

**Issue by FirstLoveLife** [magit/magit#3901]
Assuming a repo like: 
```
4bf5d6cd4027 *   Merge branch 'master' into master-xx
             |\  
178574b66509 | * c1
55cbeea76e76 | * c2
6235c229fea4 | * c3
......(over 1000 commits inside this merge commit)
5578e28d4e* Merge branch 'linux-4.4.y-sw' into master-xx  
           |\
4e84cccacb12 | * c4
41e0254d32bd | * c5
b0234f15d2e2 | * c6
......
```
As above shows, `Merge branch 'master' into master-xx` has many sub-commits, what I want to see is
``` 
4bf5d6cd4027 *   Merge branch 'master' into master-xx...
5578e28d4e* Merge branch 'linux-4.4.y-sw' into master-xx...  
```
`...` part is just like `org head`, which can be toggled(org-cycle) via `tab`. 

How to do it in magit log?

**Comment by tarsius** [comment]
I have though about on-the-fly hiding of parts of the history but don't think I will implement anything like this anytime soon. But by mentioning #2989 I am adding this to that list of things to think about when I actually get around to improving the log.

**Comment by afrepues** [comment]
@FirstLoveLife  are you aware of the option [`--simplify-by-decoration`](https://www.git-scm.com/docs/git-log#_history_simplification)? it is available in Magit, and though not interactively, it reduces the log graph in a way similar to what you describe.
