### ISSUE TITLE
Possible bug in use of `magit-refs-filter-alist`

### ISSUE THREAD

**Issue by elibarzilay** [magit/magit#3904]
The documentation string for `magit-refs-filter-alist` says that tags begin with `tags/`.  While trying to find a problem in tags not being hidden, I made `magit-refs--insert-refname-p` push its `refname` argument to a global list, and found that it has tag names as-is, without any prefix.

(Note: I'm using `2.13.0`, since I can't build the recent version:

    Magit 2.13.0-43-gf963d552, Git 2.19.2, Emacs 25.1.1, gnu/linux

.)

**Comment by tarsius** [comment]
That information wasn't accurate anymore, I have updated it. Tags are not prefixed with "tags/".

Also in order to not display any tags at all you should remove `magit-insert-tags` from `magit-refs-section-hook` instead of using this alist.

**Comment by elibarzilay** [comment]
Thanks for the clarifications!
