### ISSUE TITLE
magit-find-file-noselect ignores "{worktree}"

### ISSUE THREAD

**Issue by SavchenkoValeriy** [magit/magit#3905]
Hi, I just noticed that `magit-find-file-noselect` doesn't work with `"{worktree}"` pseudo-revision, while its docstring says the opposite.

It doesn't have any special conditions for it. At the same time, `magit-find-file` works with it as expected.

BTW Thank you for your great work!

**Comment by kyleam** [comment]
Thanks for pointing this out.  It looks a documentation issue to me.  `magit-find-file--internal` catches the "{worktree}" case and calls `find-file-noselect` rather than `magit-find-file-noselect`, so it's ok that `magit-find-file-noselect` doesn't handle it.  AFAICS no current callers assume `magit-find-file-noselect` accepts "{worktree}".

**Comment by SavchenkoValeriy** [comment]
I was using it in a separate package (using magit as a dependency) and encountered this problem.

Maybe `if` from https://github.com/magit/magit/blob/e5d16b1f0dde68ac7661b72c7c44911ff3c45bf9/lisp/magit-files.el#L88 can be moved into `magit-find-file-noselect-1` and substituted with a simple call to `magit-find-file-noselect`?

**Comment by kyleam** [comment]
> I was using it in a separate package (using magit as a dependency) and encountered this problem.

I see.

> Maybe `if` from
> [...]
> can be moved into `magit-find-file-noselect-1` and substituted with a simple call to `magit-find-file-noselect`?

Sounds fine to me.  In that case, `*-1`s REVERT should be documented as not applying to the "{worktree}" case.  Another option would be to move that `if` to magit-find-file-noselect (not `*-1`) and adjust `*-1`s docstring to drop "{worktree}".

**Comment by SavchenkoValeriy** [comment]
Thanks for the swift solution!
