### ISSUE TITLE
git-commit-setup-check-buffer chokes on a fresh Emacs

### ISSUE THREAD

**Issue by nex3** [magit/magit#3906]
I'm using Emacs 26.2 and Magit 2.90.1.

If I run Emacs with Magit installed and a `.emacs` containing only `(package-initialize)`, open a file named `PULLREQ_EDITMSG` (I manually created this in my home directory to reproduce the bug), and manually run `M-ESC : (git-commit-setup-check-buffer)`, it produces this error:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  find-file-name-handler(nil file-remote-p)
  file-remote-p(nil)
  hack-dir-local-variables()
  git-commit-setup()
  git-commit-setup-check-buffer()
  eval((git-commit-setup-check-buffer) nil)
  eval-expression((git-commit-setup-check-buffer) nil nil 127)
  funcall-interactively(eval-expression (git-commit-setup-check-buffer) nil nil 127)
  #<subr call-interactively>(eval-expression nil nil)
  apply(#<subr call-interactively> eval-expression (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> eval-expression nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (eval-expression nil nil))
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

I'd expect to be able to invoke `git-commit-setup-check-buffer` here since it's an autoloaded function. I'd *like* to use `git-commit-setup-check-buffer` rather than `global-git-commit-mode` because I don't want to eagerly load all of `git-commit.el` before knowing whether I'm actually going to be editing a commit message.

**Comment by nex3** [comment]
This actually also seems to happen if I run `(global-git-commit-mode)` before opening `PULLREQ_EDITMSG`.

**Comment by kyleam** [comment]
Thanks for the report.
