### ISSUE TITLE
Magit fails to reflow text when using a theme and the window size changes

### ISSUE THREAD

**Issue by brainlessdeveloper** [magit/magit#3907]
## Expected behavior

When Magit's window undergoes a change in size, the text in the window flows correctly into position.

![image](https://user-images.githubusercontent.com/16181067/60090920-beba6380-9743-11e9-9a44-eb4af614dfca.png)

## Observed behavior

Under the following circumstances:

- ~Using the [base16](https://github.com/belak/base16-emacs) theme `material-darker`.~
- Use any theme.
- In the terminal version of Emacs.

When Magit's window undergoes a change in size, text in the Magit buffer appears garbled. Empty lines appear, as well as whitespace before and after some lines.

![image](https://user-images.githubusercontent.com/16181067/60090675-49e72980-9743-11e9-9eac-2244e30729f2.png)

This happens regardless of whether what triggered the resize was a change in the terminal size or a change in the window Emacs created for Magit (for example if I go `M-x delete-other-windows RET` while focusing the Magit window).

## How to reproduce this issue

- Install the [base16](https://github.com/belak/base16-emacs) theme `material-darker`.
  I do it like this:
  ```
    (use-package base16-theme
    :ensure t
    :config
    (load-theme 'base16-material-darker t))
  ```
- Open Magit in a project where text overflows the terminal window.
- Force Magit to reposition text through a change in the terminal window size or something like `M-x delete-other-windows RET`.

## A workaround

For some reason, when I select a visual region of the text that has failed to reflow properly, it flows back into place:

![image](https://user-images.githubusercontent.com/16181067/60090718-5c616300-9743-11e9-9f5a-7f546c2ac381.png)

Another workaround is to use no theme at all.

### Results from following the issue template suggestions

- Versions:

  ```
  Magit 20190624.2143, Git 2.22.0, Emacs 27.0.50, gnu/linux
  ```

- Toggling debug on error didn't produce a backtrace. This is a visual bug.
- Running the command produced by `M-x magit-emacs-Q-command RET` results in the problem **not** happening anymore. This is because the `base-16` theme is not installed anymore. This is the produced command:

  ```
  /usr/bin/emacs -nw -Q --eval \(setq\ debug-on-error\ t\) -L /home/fausto/.emacs.d/elpa/dash-20190424.1804/ -L /home/fausto/.emacs.d/elpa/transient-20190528.804/ -L /home/fausto/.emacs.d/elpa/with-editor-20190511.1157/ -L /home/fausto/.emacs.d/elpa/magit-20190624.2143/ -L /home/fausto/.emacs.d/elpa/git-commit-20190625.323/ -l /home/fausto/.emacs.d/elpa/magit-20190624.2143/magit
  ```

### Why am I posting this here instead of on the base16 theme repository?

Using the theme has only affected my experience on Magit, and not on any other type of work on Emacs. However, this is just my assumption, and I'll gladly make another issue on the theme repository if this is not the case.

**Update**: this happens with other themes as well. I've tried many variations of `base-16` but also [material](https://github.com/cpaulik/emacs-material-theme) and [darktooth](https://github.com/emacsfodder/emacs-theme-darktooth).

Thank you for your patience, and above all, thanks for building such an awesome tool!

**Comment by tarsius** [comment]
I probably won't do anything about this any time soon. It might be impossible to fix or come at to high a cost. How often does one really resize terminal windows? Pressing `g` should always fix it.

**Comment by brainlessdeveloper** [comment]
@tarsius I suppose my use case is very particular. I use this:

```bash
function mg() {
  emacsclient -nw -c -a "" -e "(funcall 'magit)" -e "(funcall 'delete-other-windows)"
}
```

So this happens every time I run `mg`. Also, I run things inside `tmux` so resizing happens really often after initialization.

Using no theme is an acceptable workaround for me, and the bug does seem really hard to fix. If you give me some pointers as to what you think may be causing this, I can try to investigate. What do you think?

**Comment by tarsius** [comment]
Something is strange about your screenshots, including the first screenshot, which as you say looks as it is supposed to look. There appear two cursors and the current section does not appear to be highlighted.

**Comment by brainlessdeveloper** [comment]
I'll try to reproduce this with a more constrained environment. When I first wrote the issue I hadn't realized this happens when you add a theme. With that info I can try again with vanilla everything + just a theme.

**Comment by tarsius** [comment]
I don't really have any hints what to look for than what I just did: figure out if the display errors have something to do with highlighting of the current section or not. If not, then I am completely lost as to what the cause may be. Otherwise I can point you to... well the highlighting code. You can find your way into that starting with `magit-section-highlight-hook`.
