### ISSUE TITLE
Magit's log margin conflicts with avy

### ISSUE THREAD

**Issue by cireu** [magit/magit#3908]
# Info

- Emacs ver: 27.0.5
- Magit ver: https://github.com/magit/magit/commit/fe3965de28b96a95adc4564111df90ac1fd5739c
- Avy ver: https://github.com/abo-abo/avy/commit/9ae059deaa1b5076096bcbdbf01af763a7278aff

# Recipes

1. Use magit's `make emacs-Q` to run a plain emacs with magit
2. load `avy.el`
3. Goto a git repo and run `magit-log-current`
4. Run `avy-goto-line` in log buffer 

Expect well-formed display but some parts of buffer disappear.

![image](https://user-images.githubusercontent.com/18224684/60232834-5e0c6180-98d0-11e9-881f-fd240fffe436.png)

![image](https://user-images.githubusercontent.com/18224684/60232832-58af1700-98d0-11e9-822c-157ded2eb4a5.png)

**Comment by cireu** [comment]
Any ideas? @abo-abo

**Comment by tarsius** [comment]
> Any ideas?

Yes, the interface for putting text in the margin [is weird](https://www.gnu.org/software/emacs/manual/html_node/elisp/Display-Margins.html) and has a rather hackish feel to it:

```emacs-lisp
(let ((o (make-overlay (line-beginning-position))
                       (line-end-position)))
  (overlay-put o 'evaporate t)
  (overlay-put o 'before-string
                 (propertize "o" 'display
                             (list (list 'margin 'right-margin)
                                   string))))
```

This is how magit does it, except it uses `(1+ (line-beginning-position))` to work around #1880. That is why the margin only breaks in your screenshot when the second character on a line is displayed differently by avy.

I tried setting the `priority` of both the overlay as well as the "before string" itself to 100. Didn't make a difference. I don't think there is anything else I or @abo-abo could do, though he is of course welcome to experiment.
