### ISSUE TITLE
Confused transient naming

### ISSUE THREAD

**Issue by Arctice** [magit/magit#3909]
My problem with the current version is quite simple. magit-cherry-pick ("A") in the transient popup has been renamed from "Cherry-picking" to "Apply", which matches neither the function name nor what it actually does in git. What makes it worse is that there is in fact a git apply command, which does something entirely different, and "a", which of course is part of the same functionality but overloads the name "Apply" further in the main popup.
I don't want to make this a big issue but I feel like renaming basic git operations is the very opposite of user friendliness, would it be possible to undo the change?

**Comment by tarsius** [comment]
> magit-cherry-pick ("A") in the transient popup has been renamed from "Cherry-picking" to "Apply",

This is inaccurate.  This is what happened:

- The description of <kbd>A</kbd> was changed from "Cherry Pick" to "Pick".
- The description of <kbd>a</kbd> was changed from "Cherry Apply" to "Apply".

Relevant commits are:

- dc3bcdfe8d506313450fbf012a1cf2cbea9d0205
- 4cc98d55bfe3db3935d6f8e415a93a31dd185bc3

**Comment by Arctice** [comment]
I'm sorry if my lack of experience with magit's details makes this hard to understand, but I was trying to refer to [this](https://github.com/magit/magit/blob/fe3965de28b96a95adc4564111df90ac1fd5739c/lisp/magit.el#L228) line in magit.el, which describes magit-cherry-pick in the '?' transient popup and appears to have been changed in https://github.com/magit/magit/commit/dde9a5b77a483fa35d932aecd22c1a4c954ce77e.

**Comment by Silex** [comment]
Ah, yeah that's likely a typo.

**Comment by kyleam** [comment]
> renamed from "Cherry-picking" to "Apply", which matches neither the function name nor what it actually does in git

It's true that the description doesn't match the transient name, but I disagree that it doesn't match what git actually does for a cherry-pick (or the overall spirit of that transient).  The word "apply" is used 14 times in `man git-cherry-pick`.

**Comment by tarsius** [comment]
I think I made this change on purpose.

I think "applying a change" makes more sense than "picking fruit". My guess as to why `git cherry-pick` got its name is that `git apply` was already taken by the low-level command. If you were not already familiar with git, then "apply" would make more sense than "cherry-pick".

On the other hand the names of some of Magit's unique apply variants are also fruit inspired, e.g. "harvest".

**Comment by Arctice** [comment]
I agree with the above reasoning, but not with your philosophy that magit should be free to rename git concepts, since it can confuse users with pre-existing git knowledge(which happens to be most developers in the world), and makes it harder to operate magit while relying on the git documentation. 

If you won't change your stance on this, feel free to close the issue. My only suggestion at this point would be to offer a config variable to keep original git command display names.

**Comment by tarsius** [comment]
Magit doesn't rename concepts left and right.

I do think "apply" is a good term for what is being done. It also makes <kbd>A</kbd> mnemonic. Maybe some users will need a little more time to find this functionality than they would if the term "cherry-pick" were used. On the other hand, people whose native language is not English will be able to guess what "apply" means while they have never heard "cherry-pick" before. There are pros and cons. I will stick with what I prefer.

**Comment by Silex** [comment]
For information, AFAIK you can rename the transient name yourself with a bit of elisp, see the transient manual.

**Comment by phil-s** [comment]
FWIW, I agree that many new users will spend time looking for the "cherry-pick" option, which is a down-side; but OTOH cherry-picking is (at least to my knowledge) specifically about picking *commits*, whereas Magit's notion of "apply" works on more than just commits (in particular you can "apply" any hunk from any diff), and having a consistent terminology for "applying" any sort of change does make sense.  So long as the manual indexes the term "cherry-pick" (if it doesn't, that ought to happen), then I think it's good as-is.

**Comment by tarsius** [comment]
The manual's indices and search engines do take the user to the right place.
