### ISSUE TITLE
CUA dont work in magit buffers

### ISSUE THREAD

**Issue by consciencia** [magit/magit#3912]
CUA keys are not working in magit buffers. 

I hit C-c and nothing happens.

Old version of magit does not have this issue, I regularly copied stuff from magit status buffer.

Actual versions:
Emacs: 26.2
Magit: 2.91.0

Old and correctly working versions:
Emacs: 25.3
Magit: 2.4.0

**Comment by tarsius** [comment]
1. Please don't [double post](https://emacs.stackexchange.com/questions/51421/cua-dont-work-in-magit-status-buffer).
2. I don't use `cua-mode`. Maybe someone who uses it could look into this?

**Comment by consciencia** [comment]
Sorry. I kind of really wanted to find answer.

I even tried to find Emacs code which is responsible for routing key sequences to elisp and somehow hook in there in order to copy stuff everytime C-c is encountered, but I managed to encounter something like that only in C code base, so nothing I can override from elisp.

Interesting thing is, I can copy things like list of commits and so on in magit buffers, but Iam unable to copy anything from code diffs. 

So, its not like C-c is not working in magit buffers, its not working in specific places of magit buffers.

**Comment by consciencia** [comment]
I managed to somehow fix this issue. But its not optimal and there is hint that much larger problem lurks under the surface.

First, code:
```
(loop for m in (list magit-diff-mode-map
                     magit-file-section-map
                     magit-hunk-section-map
                     magit-unstaged-section-map
                     magit-staged-section-map)
      do (define-key m (kbd "C-c") 'cua-copy-region))
```

Problem is, magit defines commands with prefix C-c which will become dead after this fix. It can be solved by remapping them, but it is extremely unfriendly for newcomers who will use CUA mode most of the time.

Solutions of this problem is up to you, creator of this package.

Second and much larger problem is, CUA mode uses emulation-mode-map-alists which is able to translate keys to operations at higher priority than standard keymaps, so global remapping of C-c to copy operation was feasible even though many modes usually use C-c as prefix for something. 

This way, C-c was remapped without need to manually hack every possible package.

Iam shocked it failed this time. CUA keys are essential for every newcomer like me.

**Comment by npostavs** [comment]
> Second and much larger problem is, CUA mode uses emulation-mode-map-alists which is able to translate keys to operations at higher priority than standard keymaps,

Ah, the problem is that diff hunks have a keymap text property, which is higher priority than `emulation-mode-map-alists`.  See [(elisp) Searching Keymaps](https://www.gnu.org/software/emacs/manual/html_node/elisp/Searching-Keymaps.html):
```
           (or (FIND-IN (get-char-property (point) 'keymap))
               (FIND-IN-ANY emulation-mode-map-alists)
               ...
```

**Comment by consciencia** [comment]
I see. I missed that. Thanks for info.

Anyway, are you planning to add native support for CUA in magit? Its extremely important for newcomers.

**Comment by tarsius** [comment]
> Anyway, are you planning to add native support for CUA in magit?

No, I don't plan to do that because I believe it would involve re-implementing the most essential parts of CUA mode.

> Its extremely important for newcomers.

I don't think that this is *extremely* important for newcomers. Text can still be easily copied using the mouse.

**Comment by npostavs** [comment]
> > Anyway, are you planning to add native support for CUA in magit?
> 
> No, I don't plan to do that because I believe it would involve re-implementing the most essential parts of CUA mode.

I agree reimplementing CUA support in magit wouldn't make much sense. I think a possible way to avoid overriding Emacs CUA mode, would be to stop using the `keymap` text property in sections, and instead use a conditional keybinding (the `(menu-item ... :filter FILTER)` thing) which would check the current section. It would be an incompatible change for external packages which hook in to magit though.

**Comment by tarsius** [comment]
> instead use a conditional keybinding (the `(menu-item ... :filter FILTER)` thing)

I don't know what you means. Looks like the syntax for "popup menus", which I haven't used in a while. Without looking at the documentation I don't have a clue how that extension to what a keybinding can be could help this issue (which seems completely unrelated).

Doesn't matter though because I want to stick to section-type specific keymaps that are implemented using the keymap text property. Not least because of:

> It would be an incompatible change for external packages which hook in to magit though.

**Comment by phil-s** [comment]
This is one of my favourite 'hidden' (because it's not restricted to menus) features of key bindings; it's definitely worth knowing.

With the `menu-item ... :filter` syntax, you specify a function which *returns the command to call* when the key sequence is used -- and furthermore if the function returns `nil` then Emacs treats it as if no binding exists in that keymap, and so continues searching in the lower-priority keymaps.  So you can use it to implement conditional keybindings, which is pretty powerful.

Here's an example I use with some REPLs.  If the process is running, `g` just does its normal thing (which will be self-insert); but if the process has died for any reason I make `g` do the logical "refresh buffer" type of behaviour, and restart the process...

    ;; When there is no running process, 'g' starts a new one.
    ;; So to restart the repl, use 'C-d' (to exit), and then 'g'.
    (define-key map "g"
      `(menu-item "" run-repl
                  :filter ,(lambda (cmd)
                             (unless (get-buffer-process (current-buffer))
                               cmd))))

**Comment by consciencia** [comment]
I dont ask for deep changes in magit. Just something like:

`(magit-enable-CUA-hack)`

Which will perform remapping of C-c in affected keymaps.

Its apparent there is no easy solution for this kind of issue.

**Comment by tarsius** [comment]
Is someone aware of something like `kbd-concat`? As in:

```emacs-lisp
(define-key map (kbd-concat magit-C-c-prefix (kbd "C-e")) 'magit-edit-thing)
```

Even if that exists and doesn't have an excessively long name, I still don't like it much.

**Comment by npostavs** [comment]
As far as I can tell, `vconcat` would work there.

**Comment by tarsius** [comment]
And does a suitable Custom type for `magit-C-c-prefix` exist?

**Comment by npostavs** [comment]
`key-sequence` seems to fit the bill, [(elisp) Simple Types](https://www.gnu.org/software/emacs/manual/html_node/elisp/Simple-Types.html):
```
`key-sequence'
     The value is a key sequence.  The customization buffer shows the
     key sequence using the same syntax as the `kbd' function.  *Note
     Key Sequences::.
```
