### ISSUE TITLE
Commit should [be able to] reuse COMMIT_EDITMSG after failure

### ISSUE THREAD

**Issue by treyharris** [magit/magit#3913]
I frequently run into this issue:

1. My GPG key has recently exceeded its time-to-live and been relocked, but I'm not aware of this yet.
2. I attempt to start a commit with <kbd>c c</kbd>.
3. I enter a commit message.
4. I attempt to issue the commit with <kbd>C-c c</kbd>.
5. I get the error, ``GitError! failed to write commit object  [Type `$' for details]``. Using `$`, I see:

        128 git … commit --gpg-sign\=23677313213F4EFF
        treyharris@…
        ^[[Kerror: gpg failed to sign the data
        fatal: failed to write commit object
6. Using another tool, I refresh my GPG key.
7. I restart the commit process with <kbd>c c</kbd>.

### Expected behavior

Given this was a transient issue I have now repaired, I expect the behavior of other transient errors—the COMMIT_EDITMSG is reloaded from the prior attempt, so I can just press <kbd>C-c c</kbd> and continue.

### Actual behavior

COMMIT_EDITMSG is zeroed (by git, not Magit) before being loaded, and my prior edit message is lost.

If I was moving too hastily, I cannot recover my prior commit message (which may have contained a fair bit of work to compile changes or refer and link to external issues) since the file has been clobbered.

Since I'm now painfully aware of this issue and I know this behavior, I _usually_ remember to open COMMIT_EDITMSG manually and copy its contents before restarting the commit.

But sometimes I forget. And (after grunting more or less loudly depending on how much work went into the commit message), I wonder why I have to remember.

### Considerations

1. I'm aware that this is Git's own behavior, and adding this feature would require that Magit squirrel away a copy of COMMIT_EDITMSG. But this is difficult to work around.

2. The definition of "transient error" which will allow me to reuse an edit message is well-defined from the Git side, and this is not such a case. But I wouldn't expect most Magit users (many of whom _never_ use the default porcelain and see “Git” as functionally equivalent to Magit) to be aware of the difference, and from the Emacs/Magit side, this _feels like_ the sort of transient error that should allow a second go at the edit.

3. I _don't_ think this should be controllable with a new infix or suffix—I think it should simply be the Magit behavior. But perhaps it should be suppressable with a customization.

   I can't really see the use case for an ad-hoc "re-use the last commit message from a successful commit" nor for a "_don't_ re-use the last commit message even though you normally would because of an error state". It's rather easy to delete text resuscitated after an error or to capture text from an already-completed commit. Here we're only talking about saving text that would otherwise be entirely clobbered and unrecoverable short of having a snapshotting filesystem.

4. One might ask how much change to a commit should result in the prior COMMIT_EDITMSG being tossed—and specifically about the commit command's autogenerated commentary text. I'm ambivalent as to whether Magit needs to pay attention to whether the commit is changed in substantive ways before a re-try, and only squirrel away the prior edit message if the commit has not been substantively changed.

   I can see the argument for this, but it also seems like additional and probably unnecessary work to carry around any state at all except whether the `magit-status` buffer currently contains an error message or not. I don't expect Magit to save me in this case if I quit Emacs before retrying the commit.

   (If I had my druthers, I'd want the non-comment text of a never-committed COMMIT_EDITMSG to stick around regardless, but for the autogenerated commentary to be replaced if necessary. But this seems like a "nice-to-have" that has several corner cases that are perhaps best avoided. I'll leave it to you, since you know Magit's code interactions better than me.)

**Comment by npostavs** [comment]
Have you tried <kbd>M-p</kbd> in the COMMIT_EDITMSG buffer?

**Comment by tarsius** [comment]
Well one could argue that <kbd>M-p</kbd> isn't discoverable enough. One probably has to consult the documentation to learn about this.

But despite of this I think we should stick to just relying on `git`'s behavior and providing this key binding to get the message back.
