### ISSUE TITLE
Make M-p in commit more discoverable

### ISSUE THREAD

**Issue by treyharris** [magit/magit#3920]
Following up from the reply from @tarsius in #3913  —

My suggestion for discoverability: follow the example of Emacs’ own reminder of key shortcuts.

So:

1. If the current commit command follows an error
1. and there’s something in the commit msg ring
1. display `You can use M-p to retrieve the previous commit message` in the minibuffer.

The first point (checking for prior errors) may be optional.

**Comment by tarsius** [comment]
Both `git-commit` and `with-editor` have to be updated for the message to be shown. If `with-editor-usage-message` has been removed from `git-commit-setup-hook`, then the message won't be shown.
