### ISSUE TITLE
Document `magit-stash-save` arguments

### ISSUE THREAD

**Issue by xged** [magit/magit#3921]
I just stumbled upon this fundamental (deep rooted, important) function, but it could be a general lack of documentation of fundamental functions throughout the source code too.

**Comment by tarsius** [comment]
It would be better if everything was documented but I don't have the time for that. Generally speaking my packages have fewer doc-strings than those of comparable packages, which is compensated by many of my packages having manuals instead, which go way beyond what usually can be found in the readme-s of other packages.

I.e. I don't intend to do anything about it anytime soon.
