### ISSUE TITLE
Suggest selected reflog item for reset

### ISSUE THREAD

**Issue by jtrakk** [magit/magit#3923]
In the reflog when I do X it only suggests resetting to branches, not to the current item my cursor is on, but it will accept that reference if I type it out. Would it be good for it to suggest the selected reference as well?

---
magit "v2.90.1-653-g91da0fcf"
emacs 26.1

**Comment by kyleam** [comment]
> Would it be good for it to suggest the selected reference as well?

I believe that's the intended behavior, and, when I try on master (a26862d41) or the commit that your version indicates, I'm offered the commit at point as the default completion value.

**Comment by jtrakk** [comment]
I maybe misunderstand what the command does. If I have some branch checked out, then `l r X s` it suggests `master`, not the commit at point.

**Comment by tarsius** [comment]
> If I have some branch checked out, then `l r X s` it suggests `master`, not the commit at point.

It only does that if the commit at point is also the commit that `master` points at.

This command and other commands that can operate on commits and branches default to the commit and branch at point. The prefer a branch over a commit hash, so when there is a branch that points at the commit at point, then these commands offer that branch as the default, not the hash.

After you press `l r` point is usually put on the first item in the reflog, which is the commit that the branch currently points at. So the name of that branch is offered as the default.

To verify that, you can move to the next line and press `X s` there, that will offer the respective hash as default. (Unless some other branch points at that commit of course.)
