### ISSUE TITLE
Wildcard expansion in a precommit hook

### ISSUE THREAD

**Issue by jimrthy** [magit/magit#3926]
My team has a bash script defined for a git precommit hook that runs a linter over staged changes. I don't have permission [yet] to share the full script, but its heart is:

`staged_files=$(git --no-pager diff --staged --name-only --no-color -- '*.py')`

This command finds the list of all changed python files everywhere else I've tried to run it (various terminals and the emacs shell). When I try to commit changes using magit, that list of files comes back empty.

When I change the line to
`staged_files=$(git --no-pager diff --staged --name-only --no-color)` then it correctly returns the list of all staged files (which is probably a perfectly acceptable work-around).

I don't see any errors or stack traces.

My guess is that the quotes get ignored so wild-card expansion happens before git is called rather than passing the parameter through. I halfway suspect this is actually an emacs problem, but I don't know enough about that to even start diagnosing it.

Repro steps:

1. Set up a precommit hook script
```bash
#! /bin/bash

staged_files=$(git --no-pager diff --staged --name-only --no-color -- '*.py')
if [[ -z "$changed_files" ]]; then
  echo "No .py files staged"
  exit -1
fi
```
2. Stage a change to foo/bar.py 
3. Try to commit

Expected behavior: should be able to
Actual: Fails with that error message

magit-version:
Magit 2.90.1, Git 2.22.0, Emacs 25.2.2, gnu/linux

I have not had any luck [yet] following the instructions to run emacs with a minimal set of plugins. It keeps trying to drag in the kitchen sink. I decided that it made more sense to get this filed so you can at least be aware of it, rather than waiting until I have enough time to figure out what my problem might be there.

Thank you for a really great tool!

**Comment by npostavs** [comment]
I think it's this issue:

https://magit.vc/manual/magit/My-Git-hooks-work-on-the-command_002dline-but-not-inside-Magit.html

**Comment by jimrthy** [comment]
That was it.
I remember reading that page and not connecting the dots. *blush*
