### ISSUE TITLE
Symmetric difference from the log buffer

### ISSUE THREAD

**Issue by jtrakk** [magit/magit#3929]
From a log buffer, I can select some revisions and `d r D r` to get the symmetric difference diff. Would it make sense to have `d R` (or `D r`) be a command for symmetric difference diff, directly from the log buffer?

**Comment by tarsius** [comment]
I'm afraid I don't understand. Please explain. Also there is no `d r D r` binding.

**Comment by jtrakk** [comment]
From `man gitrevisions`:


> Dotted Range Notations
> 
> The .. (two-dot) Range Notation
> The ^r1 r2 set operation appears so often that there is a shorthand for it. When you have two commits r1 and r2 (named according to the syntax explained in SPECIFYING REVISIONS above), you can ask for commits that are reachable from r2 excluding those that are reachable from r1 by ^r1 r2 and it can be written as r1..r2.
> 
> The ... (three-dot) Symmetric Difference Notation
> A similar notation r1...r2 is called symmetric difference of r1 and r2 and is defined as r1 r2 --not $(git merge-base --all r1 r2). It is the set of commits that are reachable from either one of r1 (left side) or r2 (right side) but not from both.
> 
> In these two shorthand notations, you can omit one end and let it default to HEAD. For example, origin.. is a shorthand for origin..HEAD and asks "What did I do since I forked from the origin branch?" Similarly, ..origin is a shorthand for HEAD..origin and asks "What did the origin do since I forked from them?" Note that .. would mean HEAD..HEAD which is an empty range that is both reachable and unreachable from HEAD.


From a log buffer, select a range. `d r` to view the range diff. In the range diff buffer, `D r` invokes `magit-diff-switch-range-type` to switch from `..` "range" diffs to `...` "symmetric difference" diffs. 

I am wondering if it would be good to add a `D r` or `d R` keybinding in the log buffer to view `...` symmetric difference diffs.

**Comment by tarsius** [comment]
@kyleam On top of your bd5a2d91ae95e7bf90ee830ddb6f66df0620d81e we could use *two* prefix arguments to mean "show A...B as-is (without replacing one of them with the merge base)". What do you think.

When it is not identical to `A..B`, then I often find `A...B` highly confusing, so I don't think it should be added by default. We could add an additional command that has to be enabled explicitly in the transient prefix, but I so far I prefer the two-prefixes approach.

**Comment by kyleam** [comment]
@jtrakk: 

> From `man gitrevisions`:

This doesn't change your request, but it's worth noting that the explanation of `...` and `..` in `man gitrevisions` does not correspond `diff`s interpretation of these notations.  See `man diff`:

```
For a more complete list of ways to spell <commit>, see "SPECIFYING REVISIONS" section
in gitrevisions(7). However, "diff" is about comparing two endpoints, not ranges, and
the range notations ("<commit>..<commit>" and "<commit>...<commit>") do not mean a
range as defined in the "SPECIFYING RANGES" section in gitrevisions(7).
```


@tarsius:
> @kyleam On top of your [bd5a2d9](https://github.com/magit/magit/commit/bd5a2d91ae95e7bf90ee830ddb6f66df0620d81e) we could use _two_ prefix arguments to mean "show A...B as-is (without replacing one of them with the merge base)". What do you think?

The one prefix argument variant actually already uses "A...B" or "B...A" as is, assuming one of the revisions isn't also the merge base.  Perhaps the current version tries to be too clever though and---even if the merge base is one of the specified endpoints---we should just always ask for the side of interest and use a `...` range .

So, I think at the most we should tweak the current one prefix argument behavior, but the "make <kbd>d r</kbd> use `...` with the selected commits" that @jtrakk is after is already possible with <kbd>d C-u r</kbd>.

**Comment by tarsius** [comment]
Let's leave it as-is then.
