### ISSUE TITLE
Typo: "miscellanous" -> "miscellaneous"

### ISSUE THREAD

**Issue by cyrus-and** [magit/magit#3932]
Just a typo that I've accidentally spotted:

https://github.com/magit/magit/blob/68840e6da97fd35ac41c6f007c1c22dde62a7a6a/lisp/magit-core.el#L70

https://github.com/magit/magit/blob/d508f022c15864db4cccfca9803b3fca484332db/lisp/magit-git.el#L249

**Comment by kyleam** [comment]
Thanks for reporting.
