### ISSUE TITLE
Broken bug-reference buttons/links in revision buffers

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#3933]
Hi,

I'm browsing the Emacs repository with Magit.  Commit messages often include textual references to bugs looking like "(Bug#19461)".  In the Magit revision buffer these appear covered with overlays like this:

There are 2 overlays here:
 From 331 to 1026
  evaporate            t
  font-lock-face       magit-section-highlight
 From 1014 to 1023
  bug-reference-url    "https://debbugs.gnu.org/19461"
  category             bug-reference

There are text properties here:
  fontified            t
  keymap               [Show]
  magit-section        [Show]

But when I click on it with RET, I only get a user error directly thrown by 'magit-visit-thing'.  mouse-2 OTOH works.  Seems like Magit partly occupies the bug reference link but doesn't know what to do with it.

**Comment by npostavs** [comment]
`C-c C-m` (`bug-reference-push-button`) should work.

**Comment by michael-heerdegen** [comment]
Oh, hi.  Yes, indeed, I just saw that everything binding in  bug-reference-map works.  It's just kind of unexpected that RET throws an error.  So the question remains if Magit could make RET work in this case.

**Comment by michael-heerdegen** [comment]
```
(with-eval-after-load 'bug-reference
  (define-key bug-reference-map (kbd "RET") #'bug-reference-push-button))
```
does what I want.
So this is purely wishlist: could Magit do the right thing when hitting RET out of the box, because users likely expect that RET works (I myself learned just now that the link hasn't even been created by Magit).

**Comment by michael-heerdegen** [comment]
Thanks!
