### ISSUE TITLE
Add fetch/push commands for git notes?

### ISSUE THREAD

**Issue by phil-s** [magit/magit#3934]
The `git notes` command does not provide its own `fetch` or `push` commands, so it's no surprise that Magit doesn't have them either; but `git notes` is generally pretty clunky, and *explicitly* pushing notes is awkward, so I think it would be nice if the notes menu in Magit had fetch and push actions with autocompletion for the `refs/notes/` namespace.  Particularly as Magit's "push explicit refspec" command completes on (I think) `refs/heads` only -- something which is normally a benefit, but makes things more cumbersome in this particular scenario.

Primarily I'm thinking of the case where you've added a note to an old commit, and all you want to do is push your note to the remote -- *without* potentially pushing other things as well.

**Comment by phil-s** [comment]
It might also be nice to have a configurable option in the menu to say "auto-push after editing" ?   In the case where notes are configured to always allow force-pushing (which to my current understanding is almost a *requirement* to be able to use them sanely), I think such an option would be an added convenience.

**Comment by phil-s** [comment]
I'm not sure how other people use notes, so in case it's at all useful my current approach is as follows, which makes `git fetch` and `git push` do my definition of The Right Thing with notes.

    # Configure repository for git notes.
    #
    # n.b. the '+' in the remote.origin.(fetch|push) lines means that the
    # local (if fetching) or remote (if pushing) ref will be updated even if
    # it's not a fast-forward (i.e. a normal force-update).  That's ok for
    # 'fetch = +refs/heads/*:refs/remotes/origin/*' because the local ref
    # path for the remote branches is *not* the same as the local ref path
    # for the local branches, and therefore the local branches are not
    # getting clobbered.
    #
    # When the path on both sides is identical this '+' force/clobbering is
    # not usually what we want; however in the case of notes we *do* want
    # it, simply because git notes are a bit rubbish, such that if notes
    # can't be fetched due to non-FF changes, it's actually difficult to
    # know what the heck to do to resolve that situation.
    #
    # We work around this by name-spacing the notes on a per $USER basis
    # This way the only refs which can be clobbered are notes for that same
    # user's namespace -- in which case the user would need to be causing
    # conflicts, in different branches, with their *own* notes.  We are
    # sufficiently unconcerned about this that the benefits of "nobody will
    # ever need to manually resolve a notes conflicts" vastly outweigh any
    # concerns about notes being lost.
    cd "/path/to/project" \
        && git config --add core.notesRef "refs/notes/${USER}" \
        && git config --add notes.displayRef 'refs/notes/*' \
        && git config --add notes.rewriteRef 'refs/notes/*' \
        && git config --add notes.mergeStrategy theirs \
        && git config --add notes.${USER}.mergeStrategy manual \
        && git config --add remote.origin.fetch '+refs/notes/*:refs/notes/*' \
        && git config --add remote.origin.push '+refs/notes/*:refs/notes/*' \
        && git fetch origin

**Comment by tarsius** [comment]
My experience with this feature is limited. It seems to me that adding a refspecs as you have done should cover most use-cases. But you only have limited experience also, so I would suggest you use it for a while, potentially adding (and discarding) Magit commands along the way that you think would be useful at the time. Lets not add any commands that we only imagine might be useful.

**Comment by phil-s** [comment]
Yep, that's entirely reasonable.

I'd be keen to see input from other users, so am name-checking @vermiculus and @LemmingAvalanche based on their involvement in issues #1346 and #2855 / 2857.

**Comment by phil-s** [comment]
For the moment I've just done this:

    (defun magit-notes-push (ref remote &optional args)
      ;; Derived from `magit-push-tag'.
      "Push a notes ref to another repository."
      (interactive
       (let ((note (magit-notes-read-ref "Push notes")))
         (list note
               (magit-read-remote (format "Push %s to remote" note)
                                  nil t)
               (magit-push-arguments))))
      (run-hooks 'magit-credential-hook)
      (magit-run-git-async "push" remote ref args))

which I've added to `magit-notes-popup` as action `P`.

**Comment by tarsius** [comment]
Did that proof to be sufficient?
If so, then please open a pr.

**Comment by phil-s** [comment]
I think it's the most notable bit, but I should have a bit more of a play (I was really hoping for some input from the others, so I've not done anything much in the interim).

I guess it would be more consistent (with the likes of pushing a Tag) for this command to be part of the Push popup rather than the Notes popup?

**Comment by phil-s** [comment]
The only slight annoyance/inconsistency with putting it under Push is that the Notes popup is bound to `T` and in the Push popup `T` is already used for one of the tag actions, so we wouldn't have a common character meaning "notes".

I note that `n` and `N` are not used by default, though.  Was there a reason that Notes wasn't bound to one of those to start with?  I guess `n` isn't so good (outside of popups it will do some kind of "next" behaviour), but `N` seems available?

**Comment by tarsius** [comment]
Err... given these complications I am back to not wanting to add anything yet.

**Comment by tarsius** [comment]
It's the time for closing low hanging ~~fruit~~ issues. Maybe this can / has to be improved eventually, but adding the basic command now (but without enabling it by default) seems like a good idea.
