### ISSUE TITLE
allow jumping to fork-point in log buffer

### ISSUE THREAD

**Issue by edgimar** [magit/magit#3940]
It would be convenient in the log buffer to have a magit command which performs a `git merge-base --fork-point <rev>` on the currently selected commit, and then jumps to that commit in the log buffer.  This is convenient for determining the branch that another was forked from, knowing how long ago the fork occurred, and knowing what the initial state of the branch was.

**Comment by edgimar** [comment]
One other idea might be to have this be a set of commands for navigating in the buffer along a particular branch.  So currently up/down just go to the newer/older commits in the graph log view, but it would also be nice to have a version of 'up' and 'down' which stay on the current branch, and a version of 'Ctrl-up' and 'Ctrl-down' that stay on the current branch.  The 'Ctrl-down' variant would move to the fork-point, and the 'Ctrl-up' variant would move to HEAD of the currently selected branch.

**Comment by tarsius** [comment]
The arguments are `git merge-base --fork-point <ref> [<commit>]`. We would use the commit at point as `<commit>`. How is Magit to know what should be used for `<ref>`?

**Comment by edgimar** [comment]
There will be one or more <ref> associated with <commit>, so if there is one, just choose it, and if more than one, allow the user to select which one.

**Comment by tarsius** [comment]
Maybe `magit-log-move-to-parent` is all you need?

**Comment by edgimar** [comment]
No, `magit-log-move-to-parent` isn't the same -- what I'm proposing walks back over many commits until it finds where the chosen branch was forked off of another branch, but `magit-log-move-to-parent` doesn't seem to do this.

**Comment by edgimar** [comment]
I realize that what I'm looking for isn't exactly the same as what `merge base --fork-point` performs.  Really what I'm hoping for is something that for a current/selected branch looks at all of the most recent common-ancestors with all other branches, and chooses the most recent of them all.

**Comment by tarsius** [comment]
Something like this?

```emacs-lisp
(defun magit-log-previous-crotch ()
  (interactive)
  (forward-line -1)
  (if (re-search-backward "|/" nil t)
      (forward-line)
    (user-error "No more crotches")))

(defun magit-log-next-crotch ()
  (interactive)
  (if (re-search-forward "|/" nil t)
      (forward-line)
    (user-error "No more crotches")))
```

**Comment by edgimar** [comment]
How would that work if you are viewing a log with multiple branches?  The goal would be to stay on the current branch, even when there are parallel branches that have more recent fork-points with other parallel branches.

**Comment by tarsius** [comment]
Yes that obviously would jump to unrelated "fork-points" too. On the other hand this implementation is very simple while I expect that a correct implementation would be rather complicated.

**Comment by kyleam** [comment]
>  while I expect that a correct implementation would be rather complicated

Here's a more complicated implementation.  I'm not confident enough at this point to claim it is correct (I've been bitten by plenty of edge cases in my reasoning about graphs), but it does appear to work in the somewhat involved cases I've tested.

Note that it queries for the branch of interest.  I don't think considering all branches and trying to find the best match is something we'd want to get into, though we could probably provide better suggestions in certain cases (e.g., point is on a branch and the branch has a configured upstream).  Also, even if it is correct (or at least good enough), it should certainly have a second pass for code clean-up, name choices, and documentation.


```emacs-lisp
(defun magit-log-move-to-fork ()
  (interactive)
  (when (derived-mode-p 'magit-log-mode)
    (when (magit-section-match 'commit)
      (let* ((section (magit-current-section))
             (rev (oref section value))
             (branch (magit-read-branch
                      "Go to most recent fork from branch"))
             (other (or (magit-git-string
                         "rev-list" "--reverse" "--first-parent"
                         (format "%s..%s" rev branch))
                        (user-error "%s contains all commits in %s"
                                    rev branch)))
             (fork (magit-rev-parse
                    "--short"
                    (concat
                     (or (magit-git-string "rev-list" "--reverse"
                                           (format "%s^..%s" other rev))
                         (user-error "%s did not split from %s"
                                     rev branch))
                     "^"))))
        (if-let ((fork-sec (--first (equal (oref it value)
                                           fork)
                                    (magit-section-siblings section 'next))))
            (magit-section-goto fork-sec)
          (user-error
           (substitute-command-keys
            (concat "Fork point " fork " not found.  Try typing "
                    "\\[magit-log-double-commit-limit] first"))))))))
```

**Comment by tarsius** [comment]
@kyleam Do you feel like following through with this? I do not feel like investing any time in this and recommend that @edgimar places my or your suggested commands in their init file.

**Comment by kyleam** [comment]
> @kyleam Do you feel like following through with this? I do not feel like investing any time in this and recommend that @edgimar places my or your suggested commands in their init file.

It's not at the top of my list and I wouldn't use the command myself, so your recommendation is fine by me.
