### ISSUE TITLE
Unpulled commit count displayed is out of sync with actual commit count

### ISSUE THREAD

**Issue by gergelypolonkai** [magit/magit#3941]
I have a branch that hasn’t been updated for a long while. This is what `git status` tells me:

```
$ git status
On branch very-old-changes
Your branch and 'origin/master' have diverged,
and have 3 and 310 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
```

However, when i open this repo in Magit, i see this:

```
> Unmerged into origin/master (3)
> Unpulled from origin/master (256)
```

This value of 256 is suspiciously 2 on the power of 8.

If i keep rebasing commit by commit (ie. rebase on `origin/master~309`, then on `origin/master~308`, etc. up to `origin/master~256`) the value in Magit remains 256. When i rebase on `origin/master~255`, the value starts showing the actual commit count.

**Comment by kyleam** [comment]
> However, when i open this repo in Magit, i see this:
> 
> ```
> > Unmerged into origin/master (3)
> > Unpulled from origin/master (256)
> ```

Yes, that is confusing.

> This value of 256 is suspiciously 2 on the power of 8.

It comes from the default `-n` for log calls:

https://github.com/magit/magit/blob/5385e81f98abed2757720479e10f77a6021af28a/lisp/magit-status.el#L369-L370

**Comment by gergelypolonkai** [comment]
That explains why commit counts appear fine in the `magit-refs` window.

**Comment by tarsius** [comment]
We limit the number for performance reasons. Calculating the correct number of commits when the limit kicks in would at least partially give up on that speed bump. I think we should leave things as-is.

**Comment by phil-s** [comment]
What about reporting:

> Unpulled from origin/master (256+)

(or N+ generally) when the value N obtained is an exact match for the configured limit?

**Comment by phil-s** [comment]
Or the (more complicated) approach that I tend to take in such situations, which is to request 1 more than the configured limit, check to see whether we actually ended up with the maximum N+1 results and, if so, set a flag to say "there are more than N results" (and then drop the extra/unwanted one).

**Comment by gergelypolonkai** [comment]
@tarsius Git can do that calculation for you:

```
$ git branch --list -vv my-branch
  my-branch b047e062b [origin/master: ahead 3] Fancy commit message
```

I don’t know how/if that can be parsed though, as there is no `--porcelain` flag for `git-branch`. You can still list 256 commits (or ever less if you ask me). But that number is plain confusing.
