### ISSUE TITLE
Support update of diff view for list of stashes.

### ISSUE THREAD

**Issue by bastianbeischer** [magit/magit#3943]
Magit supports automatic updates of the displayed revision when moving through a magit-log buffer with "magit-section-forward/backward", through "magit-section-movement-hook" which contains "magit-log-maybe-update-revision-buffer" .

It would be nice if a similar feature where implemented for the list of stashes. This list is visible when listing with "magit-stash-list", but also on the magit-status page. In principle magit-stashes mode is derived from magit-reflog-mode, so magit-log-maybe-update-revision-buffer is called, but then the logic there does not work because stashes are not revisions and need to be handled slightly differently (more specifically, both the when-let conditions evaluate to nil in magit-log-maybe-update-revision-buffer).

I implemented my own functions based on magit-log-maybe-update-revision-buffer, which works with stashes:

```
(defun magit-stashes-maybe-update-revision-buffer (&optional _)
  "When moving in a stashes buffer, update the revision buffer.
If there is no revision buffer in the same frame, then do nothing."
  (when (eq major-mode 'magit-stashes-mode)
    (magit-stashes-maybe-update-revision-buffer-1)))

(defun magit-stashes-maybe-update-revision-buffer-1 ()
  (unless magit--update-revision-buffer
    (when-let ((stash (magit-section-value-if 'stash))
               (buffer (magit-get-mode-buffer 'magit-stash-mode nil t)))
      (setq magit--update-revision-buffer (list stash buffer))
      (run-with-idle-timer
       magit-update-other-window-delay nil
       (lambda ()
         (pcase-let ((`(,rev ,buf) magit--update-revision-buffer))
           (setq magit--update-revision-buffer nil)
           (when (buffer-live-p buf)
             (let ((magit-display-buffer-noselect t))
               (funcall 'magit-stash-show rev))))
         (setq magit--update-revision-buffer nil))))))
```

When adding magit-stashes-maybe-update-revision-buffer to magit-section-movement-hook stashes are update automatically when moving through the list.

I'm not sure whether it's a good idea to use magit--update-revision-buffer in the new functions, though.

**Comment by tarsius** [comment]
> I'm not sure whether it's a good idea to use magit--update-revision-buffer in the new functions, though.

Like the names of the functions its not really "correct", but it doesn't really matter. To make the names correct you would have to replace "revision" with "stash".

**Comment by tarsius** [comment]
I'll do it. The existing code could use a little make over and I might as well do that at the same time.

**Comment by bastianbeischer** [comment]
Thank you @tarsius.

For completeness I think the new functions should also be added as options to the defcustom:

```
diff --git a/lisp/magit-section.el b/lisp/magit-section.el
index 187488a7..93a32794 100644
--- a/lisp/magit-section.el
+++ b/lisp/magit-section.el
@@ -72,9 +72,11 @@ That function in turn is used by all section movement commands."
   :options '(magit-hunk-set-window-start
              magit-status-maybe-update-revision-buffer
              magit-status-maybe-update-blob-buffer
+             magit-status-maybe-update-stash-buffer
              magit-log-maybe-update-revision-buffer
              magit-log-maybe-update-blob-buffer
-             magit-log-maybe-show-more-commits))
+             magit-log-maybe-show-more-commits
+             magit-stashes-maybe-update-stash-buffer))
 
 (defcustom magit-section-highlight-hook
   '(magit-diff-highlight
```

Personally my vote vould be to add them to the default value, too (at least the magit-stashes-... version), to have consistent behaviour between magit log buffers and magit stashes buffers.
