### ISSUE TITLE
Magit-log-select very slow on big projects (e.g. Linux kernel)

### ISSUE THREAD

**Issue by derkling** [magit/magit#3944]
Using magit-log-select on big git repositories (e.g. Linux kernel) for example to select a commit for an "instant fixup" is instead very slow.
This seems to be due to:
```elisp
(put 'magit-log-select-mode 'magit-log-default-arguments
     '("--graph" "-n256" "--decorate"))
```
where we enable by default --graph which is known to sensibly slow down logs especially in projects with many merge commits.

Would it be possible to make these options configurable?

Maybe it's just my admittedly limited knowledge of elisp but I was not able to find a way to configure and change at run-time the options above. Is it possible via a hook or some other configuration file snippet?

**Comment by npostavs** [comment]
> Maybe it's just my admittedly limited knowledge of elisp but I was not able to find a way to configure and change at run-time the options above. Is it possible via a hook or some other configuration file snippet?

The last call to `put` wins, so you could do something like this:

```elisp
(with-eval-after-load 'magit-log
  (put 'magit-log-select-mode 'magit-log-default-arguments
       '("-n256" "--decorate")))
```

**Comment by derkling** [comment]
Right, that works! Thanks for the prompt reply!

**Comment by arvidj** [comment]
FYI, the property name has changed name, so it should now be:

```elisp
(with-eval-after-load 'magit-log
   (put 'magit-log-mode 'magit-log-default-arguments
        '("-n256" "--decorate")))
```
