### ISSUE TITLE
Symbol's function definition is void: transient-get-value when viewing logs

### ISSUE THREAD

**Issue by BrandonShega** [magit/magit#3945]
I'm getting an error when trying to view git logs.

Steps to reproduce:

1. Open a file that is under source control.
2. Open magit transient window.
3. Type `l l`, `l b` or `l L` to open logs.
4. Receive error message `Symbol's function definition is void: transient-get-value`

I expect to see the logs.
I actually see an error message.

Debug Output:
```
Debugger entered--Lisp error: (void-function transient-get-value)
  transient-get-value()
  magit-log-arguments()
  byte-code("\300\301!\302 B\207" [magit-log-read-revs t magit-log-arguments] 2)
  call-interactively(magit-log-current nil nil)
  command-execute(magit-log-current)
```

I have tried uninstalling magit and reinstalling and I'm still seeing the issue.  I recently updated magit this morning and this started happening.

Emacs Version: GNU Emacs 26.2
OS: Mac OS 10.15 Beta

**Comment by kyleam** [comment]
transient-get-value was added to transient in d33fe5a (Split new transient-get-value from transient-args, 2019-08-11), so you likely need to update transient.

**Comment by AndrewBurdyug** [comment]
The same problem for diff: 

`magit-diff-arguments: Symbol’s function definition is void: transient-get-value [5 times]  `
Versions: 

magit              20190813.1640 installed 
transient          20190812.1336 installed

**Comment by AndrewBurdyug** [comment]
Hmm... reinstallation of magit showed: 
```
Compiling file /home/buran/.emacs.d/elpa/git-commit-20190717.29/git-commit.el at Wed Aug 14 16:08:45 2019
Entering directory ‘/home/buran/.emacs.d/elpa/git-commit-20190717.29/’

In end of data:
magit-diff.el:3107:1:Warning: the function ‘transient-get-value’ is not known
     to be defined.

In end of data:
magit-log.el:1731:1:Warning: the function ‘transient-get-value’ is not known
     to be defined.
    ```

**Comment by AndrewBurdyug** [comment]
@BrandonShega ha-ha, seems I've fixed this for my emacs: 

1. list-packages shows that I have 2 version of transient: latest and "obsolete"
2. delete magit, delete "obsolete" version of transient 
3. install magit again, you should not see any warnings about "transient-get-value" 
4. check magit log / diff actions, both of them should work!

**Comment by BrandonShega** [comment]
@AndrewBurdyug Ya, I was able to fix this by just removing the transient folder and running `doom refresh` (I'm running Doom Emacs) to reinstall transient and it's working now.  I'll close this for now as it seems to be something on Doom's end that didn't cause the transient package to update when magit did.
