### ISSUE TITLE
Magit diff fontification clashes with whitespace-mode

### ISSUE THREAD

**Issue by basil-conto** [magit/magit#3950]
Steps to reproduce:

1. `make emacs-Q`
2. ```el
   (progn (setq whitespace-style '(face lines-tail))
          (global-whitespace-mode))
   ```
   <kbd>C-x</kbd><kbd>C-e</kbd>

3. <kbd>M-x</kbd>`find-variable`<kbd>RET</kbd>`magit--minimal-git`<kbd>RET</kbd>
4. <kbd>C-s</kbd>`2.2.0`<kbd>RET</kbd><kbd>DEL</kbd>`1`
5. <kbd>C-x</kbd><kbd>C-s</kbd>
6. <kbd>C-x</kbd><kbd>g</kbd>
7. <kbd>S-TAB</kbd>

![bad](https://user-images.githubusercontent.com/9121222/63267931-c4dc4480-c29b-11e9-9758-84d9c9979dc2.png)

Note that all three strings present in the diff are fontified as strings, rather than as part of the Magit diff section. Typing <kbd>C-u</kbd><kbd>C-x</kbd><kbd>=</kbd> inside the first string in the status buffer gives the following:

```
There are text properties here:
  face                 font-lock-string-face
  font-lock-face       magit-diff-removed-highlight
  fontified            t
  keymap               [Show]
  magit-section        [Show]
```

If you omit step (2) of the recipe above, the diff is fontified as expected:

![good](https://user-images.githubusercontent.com/9121222/63268209-52b82f80-c29c-11e9-9360-c404dca9c334.png)

In this case <kbd>C-u</kbd><kbd>C-x</kbd><kbd>=</kbd> reports the following instead:

```
There are text properties here:
  font-lock-face       magit-diff-removed-highlight
  keymap               [Show]
  magit-section        [Show]
```

I first noticed this issue after a month or two of not having updated Magit. I suppose it may be related to #3886 et al.

Note that not all `whitespace-style` settings give rise to the issue; e.g. setting it to `(tab-mark)` is fine. I suppose it is the `face` setting which gives rise to the issue. This intuitively makes sense, given the presence of the `face` property listed above for the pathological case.

I can reproduce the issue with both of the following Emacs versions:

```
In GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
 of 2019-08-19 built on thunk
Repository revision: 50dc4ca8d02a466a7236765edf83ae7cfb02d74c
Repository branch: master
Windowing system distributor 'The X.Org Foundation', version 11.0.12004000
System Description: Debian GNU/Linux bullseye/sid

In GNU Emacs 26.2.90 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
 of 2019-07-16 built on thunk
Repository revision: b2fde4b5e8e91aa57313af09465091303eeb7d39
Windowing system distributor 'The X.Org Foundation', version 11.0.12004000
System Description:	Debian GNU/Linux bullseye/sid
```

and the following Magit version:

```
Magit v2.90.1-771-gb8a90fa8, Git 2.20.1, Emacs 27.0.50, gnu/linux
```

**Comment by npostavs** [comment]
> I first noticed this issue after a month or two of not having updated Magit. I suppose it may be related to #3886 et al.

Well, it's obviously related in that whitespace mode was simply disabled in magit buffers before that. We could do that again; using `font-lock-face` would still remain useful for compatibility with other minor modes.

I'm a bit confused as to what is generating the `font-lock-string-face` though.

**Comment by basil-conto** [comment]
> I'm a bit confused as to what is generating the `font-lock-string-face` though.

I think, without being 100% certain (as I'm not a font lock expert), that it is automatic syntactic font lock; see #3951.

**Comment by npostavs** [comment]
Yes, seems to be the case. I had just found out that `(setq-local font-lock-syntactic-face-function #'ignore)` fixes it, but I think your patch would be the more canonical way of doing that.

**Comment by alphapapa** [comment]
Please note that this has broken fontification for `magit-todos`: https://github.com/alphapapa/magit-todos/issues/84

**Comment by npostavs** [comment]
Ah, perhaps `(setq-local font-lock-syntactic-face-function #'ignore)` is the better way do it after all.

**Comment by alphapapa** [comment]
By the way, I tried changing the property set in `magit-todos` from `face` to `font-lock-face`, and it did fix most of it.  However one of the things the package does is fontify items found in Org files by using Org's own fontification (i.e. calling `font-lock-ensure` in an Org buffer), and that fontification is still wiped out by https://github.com/magit/magit/commit/546a9c33715f12a9b1101eca22b070004c9c6392.

**Comment by npostavs** [comment]
> Ah, perhaps `(setq-local font-lock-syntactic-face-function #'ignore)` is the better way do it after all.

I've changed to that now.

5a2786cc005c1dfb698b6c2fc1dd592c344b0e4a

**Comment by alphapapa** [comment]
@npostavs Thank you very much!
