### ISSUE TITLE
Outdated documentation MacOS-Performance

### ISSUE THREAD

**Issue by kommen** [magit/magit#3959]
https://magit.vc/manual/magit/MacOS-Performance.html#MacOS-Performance

> Nobody knows when the changes on the master branch will be released as 26.1, but it is still a long way off. You might want to get your hands on this change before then. The easiest way to get a patched Emacs is to install the emacs-plus formula 3 using homebrew.

This seems outdated since emacs 26.1 was released a while ago.

**Comment by kommen** [comment]
Thank you @tarsius!

**Comment by tarsius** [comment]
Cheers!
