### ISSUE TITLE
Add a shortcut for Co-authored-by pseudo header

### ISSUE THREAD

**Issue by JosephKiranBabu** [magit/magit#3964]
There's a good collection of git pseudo headers in [git-commit.el](https://github.com/magit/magit/blob/master/lisp/git-commit.el#L86)

Please provide a shortcut to add the git pseudo header for **Co-authored-by**
The Co-authored-by header is different from the existing headers. The commit author is the default entry for the other headers, but for Co-authored-by, it's someone else.

There should be a configurable list of (name \<email-address\>) entries to select from for co-authors.

This will be very useful for pair programming.

**Comment by tarsius** [comment]
```elisp
(defun git-commit-co-authored-by (name mail)
  "Insert a header mentioning the person who co-authored the commit."
  (interactive (git-commit-read-ident))
  (git-commit-insert-header "Co-authored-by" name mail))

(define-key map (kbd "C-c o") 'git-commit-co-authored-by)
```

**Comment by tarsius** [comment]
This is as far as I want to go.

**Comment by JosephKiranBabu** [comment]
Sorry for the late response. 

I was looking for something like the following:

``` emacs-lisp

(setq git-committers
      '(("jd" "John Doe" "john@doe.net")
        ("mj" "Mary Jane" "mary@mj.com")))

(defun git-committer-read-key ()
  (list (read-string "Committer Key: ")))

(defun git-commit-co-authored-by (key)
  "Insert a header mentioning the person who co-authored the commit."
  (interactive (git-committer-read-key))
  (let ((name (cadr (assoc key git-committers)))
        (email (caddr (assoc key git-committers))))
    (git-commit-insert-header "Co-authored-by" name email)))

```

If the above alist is empty, then the function should prompt for a name and email address.

If you're okay with the approach, I'll try to implement handling both the alist and the fallback in a pull request.

**Comment by tarsius** [comment]
I don't like that approach and have pushed something better.

**Comment by lima-limon-inc** [comment]
Hello, I am from the future.
If you (like me) are searching for a function to add a co authored by message

Call the function  `git-commit-co-authored` inside the commit message prompt.

It will give you a nice list of co authors as well!

**Comment by tarsius** [comment]
I don't know what you mean by "commit message prompt", but in the buffer used to write the commit message, you can press `C-c C-i` to pick the trailer[^1] you want to insert.

[^1]: Formerly known as "pseudo header", a term we stopped using because there is isn't really anything "pseudo" about it and these also aren't really a "headers". :grinning:

**Comment by lima-limon-inc** [comment]
> I don't know what you mean by "commit message prompt", but in the buffer used to write the commit message, you can press `C-c C-i` to pick the trailer[1](#user-content-fn-1-94262334afeae0cc81b717848ecf9f15) you want to insert.
> ## Footnotes
> 
>     1. Formerly known as "pseudo header", a term we stopped using because there is isn't really anything "pseudo" about it and these also aren't really a "headers". 😀 [↩](#user-content-fnref-1-94262334afeae0cc81b717848ecf9f15)

Holy moly! I was not aware of this feature.

This looks great! Thank you @tarsius !!!
