### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by sinelaw** [magit/magit#3965]
Is there any reason no minor release has happened since Nov. 2018? github claims >700 commits to master since then.
(In some corporate settings it makes it easier to upgrade if there's a release)

**Comment by tarsius** [comment]
Yes there are reasons. One of them is that it won't actually be minor release but a major release. It would have been good to make a few minor releases on the way, but now that there are 700 unreleased commit, that ship has sailed.

I am sure there will be a release before the end of the year, hopefully before November. Sorry about the delay.

**Comment by anarcat** [comment]
is this ship ready to sail again? :) would be real nice to have a new release...
