### ISSUE TITLE
Support writing lengthy release tag messages

### ISSUE THREAD

**Issue by bandali0** [magit/magit#3966]
As of now, creating a release tag using `t r` only prompts for a (short) tag message. It would be nice to be able to use the regular magit commit buffer to compose proper tag messages.

Example of a release tag created through magit:  
https://git.sr.ht/~bandali/george-mode/refs/v0.1.0

Example of what's possible:  
https://git.sr.ht/~sircmpwn/aerc/refs/0.2.0

On a side note, I think it would be nice to be able to toggle `--sign` (gpg signing) for release commits.

**Comment by tarsius** [comment]
As the commands doc string says, you can use the prefix argument to create an annotated tag: <kbd>t C-u t</kbd>. Alternatively you can use the `--annotate` infix argument: <kbd>t - a t</kbd>.

**Comment by bandali0** [comment]
Whoops, I'd somehow (?) missed that. That covers my use-case, thanks!
