### ISSUE TITLE
Trouble using overcommit

### ISSUE THREAD

**Issue by argent-smith** [magit/magit#3968]
Hi. I'm using sds/overcommit (gated commit tool w/hooks). After upgrading my Emacs installation recently I started encountering this behaviour:

What I do:

committing the staged changes (C-C)

What I expect:

Commit run w/possible linter errors indicated

What I get:

```
  0 git … stash apply --index stash\@\{0\}
[Russian locale messages skipped]
  0 git … rev-parse stash\@\{0\}
38851d8333d60b04e9fb2925380980a15bb2aa56

  0 git … reflog delete --updateref --rewrite stash\@\{0\}
  0 git … update-ref -d refs/stash
  1 git … commit --
Unable to setup environment for pre-commit hook run:
STDOUT:
STDERR:error: pathspec ':/' did not match any file(s) known to git
```

How to reproduce:

It's reproducible on all my repos. Without Emacs/magit overcpommit works without a problem.

Here's the corresponding issue in sds/overcommit: https://github.com/sds/overcommit/issues/671

Backtrace: buffer empty.

Magit-version: Magit 20190906.2217, Git 2.23.0, Emacs 26.3, darwin

**Comment by tarsius** [comment]
So like in the case of #3955 this is about an error occurring in a git hook.

It seems to me that you are in a much better position to figure out what is wrong about that hook when run on your machine than we are. On the other hand you seem to get the same error

> `pathspec ':/' did not match any file(s) known to git`

so maybe @mkleehammer can tell you what has to be done to fix whatever it is that is wrong.

**Comment by argent-smith** [comment]
> It seems to me that you are in a much better position to figure out what is wrong about that hook when run on your machine than we are

Any ideas on investigating? The only thing I've figured out so far: it works fine without magit. Question: what does magit do that interferes with a commit?

**Comment by argent-smith** [comment]
Also, after the error, I see this:
```
Stashes (1)
stash@{0} On ERP-737: Overcommit: Stash of repo state before hook run at 2019-09-21 14:56:00 +0300
```

**Comment by tarsius** [comment]
This issue is probably causes by difference in the environments of Emacs and the shell.

If you started Emacs by typing `emacs` in a shell instead of by clicking on an icon, then the issue would probably go away. That way `emacs` is a subprocess of the shell and therefore inherits the (shell variable) environment from the shell. There are other ways to "import" settings from the shell into Emacs, such as the [`exec-path-from-shell`](https://github.com/purcell/exec-path-from-shell) package.

**Comment by argent-smith** [comment]
It reproduces in console Emacs, too.

**Comment by argent-smith** [comment]
exec-path-from-shell makes no difference

**Comment by argent-smith** [comment]
The most frustrating thing is, I can't spot the difference between my previous Emacs config and the current one (

**Comment by argent-smith** [comment]
Well, the only difference I see is Magit version update& How can I downgrade?

**Comment by npostavs** [comment]
> STDERR:error: pathspec ':/' did not match any file(s) known to git

This error message suggest to me the literal pathspec problem: https://magit.vc/manual/magit/My-Git-hooks-work-on-the-command_002dline-but-not-inside-Magit.html

But you say it worked with magit before upgrading, which doesn't fit. It might be worth dumping all the environment variables in the failing hook, to see if there any relevant differences in Emacs vs non-Emacs situations.

**Comment by argent-smith** [comment]
@npostavs ❤️ GIT_LITERAL_PATHSPECS makes the difference! Thanks! Now figuring out how to fix the thing.

**Comment by tarsius** [comment]
Once you have done so, please let us know how you fixed it, in case someone else runs into the same issue.

**Comment by argent-smith** [comment]
@tarsius sure

**Comment by scottjacobsen** [comment]
I've started getting this too - it happened after I upgrade all the things - emacs and magit. So I'm not sure which upgrade caused it. If I can provide any info to help out let me know.

**Comment by argent-smith** [comment]
@scottjacobsen it's because of this: https://magit.vc/manual/magit/My-Git-hooks-work-on-the-command_002dline-but-not-inside-Magit.html

Right now @sds is addressing the issue and I am testing the solution.
