### ISSUE TITLE
Custom Password Retrieval

### ISSUE THREAD

**Issue by jsuskalo** [magit/magit#3970]
At my organization it's required that I use a GitHub Access Token to gain access to repos and to have push, pull, and other permissions. I'd prefer not to have to memorize this access token (honestly it's somewhat of an unfeasible task to do so), and having my git repo configured to automatically be able to push or pull without a password isn't something I'm a fan of for security reasons, so I can't configure git to just remember the password.

I think a general-case solution to this would be to have a configurable variable which fetches the password from the user instead of just directly using emacs' password prompt. This allows password fetching to be more general, and in my use case would allow me to create a function which prompts the user for a password which will be used with GPG to decrypt the access token before passing that token back to magit and cleaning up.

I think this would be a very simple change, and I may make a pull request with the change in it if this feature isn't picked up quickly.

**Comment by jsuskalo** [comment]
This looks like it already exists at some level based on starting to read the source of magit, but it doesn't appear to be documented.
Currently it exists as `magit-process-find-password-functions`, I'll try working with this, and if it behaves the way I expect, I'll close this feature request.

**Comment by tarsius** [comment]
Yes, that's the variable I was going to suggest.

Once you have something that works, don't forget to post it here for the benefit of others.

**Comment by jsuskalo** [comment]
Yeah, it turns out this was pretty simple once I messed around with that variable. Just added the following to my config:

```lisp
(defun make-gpg-decrypt-file (filename)
  "Creates a function which decrypts the given file, returns its
  contents as a string, and deletes the temporary file it was
  decrypted into"
  (lambda ()
    (let ((out-path (make-temp-name (file-name-base filename))))
      (epa-decrypt-file filename out-path)
      (prog1
          (string-trim
           (with-temp-buffer
             (insert-file-contents out-path)
             (buffer-string)))
        (delete-file out-path)))))

(push (make-gpg-decrypt-file "the-gpg-location") magit-process-find-password-functions)
```
