### ISSUE TITLE
Line numbers in magit

### ISSUE THREAD

**Issue by jeffersoncarpenter** [magit/magit#3971]
It's very important to my workflow that I have relative line numbers on.  A commonly used key of mine is C-u \<amount> C-[pn] to move up or down \<amount> lines.  Line numbers work correctly in magit adding this to custom-set-variables:

```
 '(display-line-numbers-type (quote visual))
 '(display-line-numbers-widen 0)
```

However magit explicitly disables them during startup [link](https://github.com/magit/magit/blob/master/lisp/magit-mode.el#L614).  I believe this is a mis-feature and would prefer not to need to add more code to counteract code that has been added to magit.

**Comment by tarsius** [comment]
I've added a new option `magit-disable-line-numbers` in c19d8bb4f7d436ff7654be57601703ef517d6d4d. For now you have to set this to `nil` to prevent the mode from being disabled.

**Comment by tintinthong** [comment]
@tarsius Is [c19d7bb](https://github.com/magit/magit/commit/c19d8bb4f7d436ff7654be57601703ef517d6d4d) this merged in?

**Comment by tintinthong** [comment]
> @tarsius Is [c19d7bb](https://github.com/magit/magit/commit/c19d8bb4f7d436ff7654be57601703ef517d6d4d) this merged in?

nvm I found it. Thanks for doing this @tarsius and @jeffersoncarpenter for the suggestion.

**Comment by dharmaturtle** [comment]
For people like me who get here through Google, it's been renamed to `magit-section-disable-line-numbers` in Magit v3.0

e.g. in `config.el`:

```elisp
(setq display-line-numbers-type 'visual)
(global-display-line-numbers-mode t)
(setq magit-section-disable-line-numbers nil)
```
