### ISSUE TITLE
void-function diff-hl-magit-post-refresh

### ISSUE THREAD

**Issue by kirk86** [magit/magit#3973]
Please explain
    (1) what behavior you expected
Normal magit operation, not lisp debugger error on calling magit

    (2) what behavior you observed
![image](https://user-images.githubusercontent.com/2902390/65840861-a004d380-e315-11e9-89ef-ece72c3a854d.png)

    (3) and how we can reproduce the issue.
`https://github.com/kirk86/emacs.d`

Please include a backtrace in your report.  In most cases doing:

    M-x toggle-debug-on-error RET
```
Debugger entered--Lisp error: (void-function diff-hl-magit-post-refresh)                                                                                                                     
  diff-hl-magit-post-refresh()                                                                                                                                                               
  run-hooks(magit-post-refresh-hook)                                                                                                                                                         
  magit-run-hook-with-benchmark(magit-post-refresh-hook)                                                                                                                                     
  magit-refresh()                                                                                                                                                                            
  magit-run-git("add" "-u" ".")                                                                                                                                                              
  magit-stage-1("-u" nil)                                                                                                                                                                    
  magit-stage-modified()                                                                                                                                                                     
  magit-stage(nil)                                                                                                                                                                           
  funcall-interactively(magit-stage nil)                                                                                                                                                     
  call-interactively(magit-stage nil nil)                                                                                                                                                    
  command-execute(magit-stage) 
```

and then going through the steps again should result in a backtrace.

Also post the output of:

    M-x magit-version RET

`Magit 20190928.1729, Git 2.21.0 (Apple Git-122), Emacs 26.3, darwin`

Is `diff-hl` a dependecy for magit or am I missing something fundamental?

**Comment by tarsius** [comment]
> Is `diff-hl` a dependecy for magit 

No, but `diff-hl` can hook into `magit` as [documented in its README](https://github.com/dgutov/diff-hl#magit) like so.

```elisp
(add-hook 'magit-post-refresh-hook 'diff-hl-magit-post-refresh)
```

You probably had `diff-hl` installed at some point and added the above line. Now `diff-hl` for some reason isn't installed anymore, so this function doesn't exist anymore, and trying to call it anyway results in the above error. You can fix that by removing that line.

**Comment by kirk86** [comment]
@tarsius Thanks for the reply. It seems that the above line was left over when I was trying to cleanup my config. I'm closing this since the issue has been resolved.
