### ISSUE TITLE
Log help for -- incorrect

### ISSUE THREAD

**Issue by yhvh** [magit/magit#3974]
1) Open magit log popup, press `?` for help, press `--` for limit to files
Expected to get link to git-log section for  [--] <path>... 

2) Link into git-log manual lands at:
--[no-]use-mailmap

3) Reproduce. magit log popup, type `?`, type `--`

magit-version:
`Magit 20190928.1729, Git 2.23.0, Emacs 26.3, gnu/linux`

**Comment by tarsius** [comment]
Pushed a fix for that: https://github.com/magit/transient/commit/4f80a8999caf470e9a67f8af7f4d9bffcaf77957.
