### ISSUE TITLE
Magit-log not working in tui interface.

### ISSUE THREAD

**Issue by Ergus** [magit/magit#3982]
>    (1) what behavior you expected

- I expect to see the a log as I do in the gui, or at least a log

>    (2) what behavior you observed

- In gui everything works just fine.
- In TUI Emacs freezes and I need to kill it. 
- When debug-on-error is enabled the debugger is not oppened as there is not error... But emacs also freezes.

>    (3) and how we can reproduce the issue.

    emacs -nw
    M-x magit-log-all

> Please include a backtrace in your report.  In most cases doing:

emacs freezes but not trigger any error, so no backtrace. Sometimes it freezes before showing the magit-log but other it shows it.

---
>  M-x magit-version RET

Magit 20191008.727, Git 2.23.0, Emacs 27.0.50, gnu/linux

 > M-x magit-emacs-Q-command RET

I tried this but I added the -nw to the command line as the problem is only exposed in tui interface and I get the freeze as well as explained before.

**Comment by tarsius** [comment]
> Please do not ignore these instructions.
> ...
> ---- now delete this line and everything above ----

Why did you ignore this? Lately this has been happening a lot and I have decided to no longer except it. Once you have cleaned up your post I will read it.

You were instructed to remove instructions, which are intended for you to read and then act on. You may choose to keep *select parts* of the instructions, but if you do so then you should quote the text that you have not written yourself. By doing so you make it possible for other people to quick see what parts you have written and which parts you are replying to, for example:

> (1) what behavior you expected

- I expect to see the a log as I do in the gui, or at least a log

**Comment by Ergus** [comment]
Probably the delete instructions should be at the top not at the end in order to busy people see it. And don't incontinently ignore something that looks like a comment at the end of a long form.

**Comment by tarsius** [comment]
I was not able to reproduce this.

My guess is that you are testing this in different repositories depending on whether you are running in GUI or terminal Emacs. `l a` (`magit-log-all`) shows the log for all refs, not just branches. You might want to give `l b` a try. Also check whether the `-n` argument is set, e.g. `-n256`. If this is not set, then all commits are shown, which can take a long time, especially if you requested the log for every ref.

So Emacs probably isn't hanging, it is just taking a long time doing something that necessarily takes a long time. You should be able to abort that by typing `C-g` or if that doesn't help then `ESC` several times.

**Comment by Ergus** [comment]
Did you tried it in Emacs 27? Actually I have this issue in the same repo, same machine, same emacs, same command, with and without -Q. The only difference is tui vs gui.

Of course I've tried to cancel with C-g and with ESC ESC ESC. It stays locked the only solution it to kill it fro outside.

**Comment by tarsius** [comment]
> Did you tried it in Emacs 27?

That's what I am using, yes.

> The only difference is tui vs gui.

I cannot think of a reason why that would make a difference.

I don't know what to do next; maybe someone else has an idea?

**Comment by Ergus** [comment]
Just to update this thread for the future visitors. 

This issue was related with a new functionality in emacs 27 (extend attribute for faces) implemented in the display engine completely unrelated with magit. Magit only exposed the issue and it is already fixed in the emacs master branch Commit: [7a10082093791f0](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=7a10082093791f0e035e4f9f95a774a7be1cd586)
