### ISSUE TITLE
magit-mode-get-buffers and symlinked repositories

### ISSUE THREAD

**Issue by gusbrs** [magit/magit#3984]
When using `magit` on a git repository whose path is somehow symlinked the "magit-diff" buffer follows the symlinks while the others do not. This tricks `magit-mode-get-buffers` to not include the diff buffer in the list it returns. I'd expect all buffers generated by magit in dealing with the repository were returned by `magit-mode-get-buffers`.

Steps to reproduce:

```bash
mkdir git-repo
cd git-repo
touch test-file.txt
git init
git add .
git commit -m "Initial commit"
cd ..
ln -s git-repo git-repo-linked
```

Start `emacs -Q` and perform basic setup (I could not start Emacs with any of the methods described in the report instructions, I hope this is enough):

```emacs-lisp
(package-initialize)
(global-set-key (kbd "C-x g") 'magit-status)
```

`magit-version` returns "Magit 2.90.1, Git 2.17.1, Emacs 26.3, gnu/linux".

Now find file `./git-repo-linked/test-file.txt`, change something, stage and commit.

If we now `list-buffers` ("C-x C-b") we will find three magit buffers there (trimmed info, just the relevant part):

```
magit-process: git-repo-linked    ./git-repo-linked/
magit-diff: git-repo              ./git-repo/
magit: git-repo-linked            ./git-repo-linked/
```

Note the `magit-diff` buffer followed the symlink and gets the truename.

Going back to the buffer of `test-file.txt` and evaluating `(magit-mode-get-buffers)` it returns: `(#<buffer magit-process: git-repo-linked> #<buffer magit: git-repo-linked>)`, which leaves out the "magit-diff" buffer.

**Comment by tarsius** [comment]
I don't think we can do anything about it. This is what happens:

1. Magit calls `git commit`
2. Git calls `EDITOR` (`emacsclient ...`) passing the full path to `COMMIT_EDITMSG` as argument. Git resolves all symlinks in that path and cannot be told not to do so.
3. Magit shows the diff using the `default-directory` from the `COMMIT_EDITMSG`, i.e. the fully resolved path.

If diff is invoked without involving `git commit`, e.g. directly from the status buffer, then `default-directory` will have the expected value in the resulting diff buffer.

**Comment by gusbrs** [comment]
Thank you for your consideration and answer.
