### ISSUE TITLE
cannot commit with git-commit-20191106.1247

### ISSUE THREAD

**Issue by haifenghan** [magit/magit#3997]
I'm using the latest magit-20191105.2244 and git-commit-20191106.1247 from elpa.
When submitting a commit, there is always an error:
`git-commit-save-message: Invalid function: (message (git-commit-buffer-message))`

**Comment by tarsius** [comment]
As a quick fix add `(require 'subr-x)` to you init file. I have added that to `git-commit.el` too, but it can take a few hours before a new version hits Melpa.

**Comment by gicmo** [comment]
I added `(require 'subr-x)` to my init file (also tried manually applying a2168f9ed92d90888f43cd9e88ff9d46673120dd) but I still get `git-commit-save-message: Invalid function: (message (git-commit-buffer-message))`

**Comment by gicmo** [comment]
Sorry for the noise, forgot to nuke `git-commit.elc`.

**Comment by joelekstrom** [comment]
Maybe keep this issue open/pinned, was not obvious until I started creating another report for the same issue and it came up in suggestions. 

This actually makes me have to force quit emacs, because I can't abort the commit (neither C-c or C-k) works, and to apply the fixes one needs to restart. Magit prevents exiting emacs when there's a commit buffer open, asking to use C-c C-k in it first, which doesn't work.

**Comment by joelekstrom** [comment]
Actually, I still get the problem even after adding `(require 'subr-x)` and cleaing `.elc`-files. Probably adding stuff in the wrong order or something

**Comment by tarsius** [comment]
Since it is a temporary hack, why not just add `(require 'subr-x)` before anything else?

**Comment by joelekstrom** [comment]
That doesn't work for me anyway. Have it at the top of my `init.el`, still have the same issue

**Comment by tarsius** [comment]
Maybe there's a `init.elc`, which you did not update or remove? Also, are you sure you removed `git-commit.elc`?

**Comment by joelekstrom** [comment]
I have no `init.elc` and I removed all `.elc`-files inside `~/.emacs.d/elpa/magit-20191105.2244/`

**Comment by haifenghan** [comment]
It's not in magit but in git-commit. Please see mine:

```
ls ~/.emacs.d/elpa-26.3/git-commit-20191106.1247/
git-commit-autoloads.el  git-commit.el  git-commit.elc  git-commit-pkg.el
```

**Comment by joelekstrom** [comment]
Ah yes, that was it, sorry about that. Thanks!
