### ISSUE TITLE
Is it feasible to use magit sections in other packages yet?

### ISSUE THREAD

**Issue by titaniumbones** [magit/magit#4003]
Way back in #2956 you mentioned releasing `magit-section` as an independent package, and then in #3118 decided against it. I am interested in imitating the magit UI in another package (an interface to [Canvas LMS](https://canvas.instructure.com/doc/)), but I'm not smart enough to code any of that plumbing myself, and wondered if magit-section is in a state such that I could feasibly make use of it for another purpose.  A magit dependency isn't really an issue for me since at present I'm the only user of my package :-) and in all likelihood any potential users will also have magit installed.  

Thanks!

**Comment by tarsius** [comment]
Yes, should be perfectly fine to use it like this as long as you don't mind depending on all of `magit`. In #3118 I mentioned potential breaking changes in preparation of a replacement but those would happen on a feature branch and if I decided to merge into `master` at some point, then it should be easy to adapt--I don't plan any major changes *before* writing an actual replacement. It will probably play out similar to how `magit-popup` got replaced with `transient` (i.e. on a feature branch and nobody got disturbed at all).

Actually now that you brought this up again I am thinking about releasing this as a separate package after all.

**Comment by contrapunctus-1** [comment]
It would be great if it were released separately! I too was thinking of using it (for an Emacs interface to Syncthing), but wasn't too sure about depending on all of Magit.

**Comment by tarsius** [comment]
I've already worked on this and the `spin-off-sections` branch might be all that is needed (aside from updating the Melpa recipes of course). But I have not tested this *at all* yet and it might be another week or two until I get around to that.

**Comment by tarsius** [comment]
This is progressing well. I discovered some other things that still had to be done most of which I have merged with 1e3215fa1f0bb4047099bc81f20fa1950e064c6f. Now all that is left to do is to actually spin off the new package--I believe. This should happen in January. Oh and write some documentation, that might delay it a bit, but I already started with that too. See `spin-off-sections` branch.

**Comment by tarsius** [comment]
Some complications related to hooks have come up.

**Comment by Alexander-Shukaev** [comment]
See one more extension idea from https://github.com/magit/magit/issues/2982#issuecomment-539525687.

**Comment by tarsius** [comment]
Tataaa :tada:  https://emacsair.me/2020/01/23/magit-section/
