### ISSUE TITLE
Don't ask for remote.pushDefault when cloning

### ISSUE THREAD

**Issue by DamienCassou** [magit/magit#4007]
When running `M-x magit-clone`, Magit usually asks to set the remote as `pushDefault`. I find that question annoying because:

- the question arrives late, usually interrupting what I'm doing
- I always answer yes to this question even if I don't have write access to the repo. When adding another remote, I will get the question again anyway.

I suggest always setting `pushDefault` to `origin` when cloning a repository.

**Comment by tarsius** [comment]
There's an option for that™
`magit-clone-set-remote.pushDefault`

**Comment by DamienCassou** [comment]
Jonas Bernoulli <notifications@github.com> writes:
> There's an option for that™
> `magit-clone-set-remote.pushDefault`

thank you, sorry for the noise.

-- 
Damien Cassou

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill
