### ISSUE TITLE
Surface hook failures to magit buffer

### ISSUE THREAD

**Issue by ahonnecke** [magit/magit#4009]
I use the python pre-commit package to implement git hooks.  This is lovely, but it results in a failure that then requires I move over to the magit-process buffer to see what failed, like this:
![image](https://user-images.githubusercontent.com/419355/70184290-c6901380-16a4-11ea-97ac-cc036d556668.png)

Which in the magit-process buffer looks like this:
![image](https://user-images.githubusercontent.com/419355/70184329-dd366a80-16a4-11ea-948e-82e03ace8463.png)

Ideally, the failure output would be surfaced to the main magit buffer, something like this:
```
GitError! Git failed  [Type `$' for details]
Head:     decode-with-abi Merge pull request #86 from digital-assets-data/decode-with-abi
Merge:    upstream/dev Merge pull request #86 from digital-assets-data/decode-with-abi
Push:     upstream/decode-with-abi update ci config to match new scripname

Failures (1)
flake8   bin/completeness_checker.py 

Staged changes (1)
modified   bin/completeness_checker.py
```

Where the line is actionable (hitting enter when over it takes you to the file and line)

Alternatively just making the file path in magit-process a working link to the file would be a useful improvement from the current behavior.

**Comment by ahonnecke** [comment]
Right now, I kind of accomplish this by binding find-file-at-place to enter for magit-process:
https://github.com/ahonnecke/prelude/blob/ubuntu/personal/magit-bindings.el#L59-L66

**Comment by kyleam** [comment]
> Alternatively just making the file path in magit-process a working link to the file would be a useful improvement from the current behavior.

This lesser request has been made in the past (gh-3105), with the conclusion that it should be handled outside of Magit.  In my view the same applies to your more involved suggestion of transforming failures into a status buffer section.  While the feature's interesting, it'd probably be more suitable for a third-party package than Magit proper.

**Comment by tarsius** [comment]
I haven't changed my mind about this since I commented on #3105.

**Comment by ahonnecke** [comment]
Apologies, I hadn't found the refused feature request, any chance that anyone would be able to point me at existing code, or relevant documentation for the appropriate way to go about the proper way to make a third party package?

**Comment by tarsius** [comment]
The Melpa documentation links to some useful resources: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#making-your-package-ready-for-inclusion. But my recommendation is to first solve the issue at hand and only later worry about proper packaging.

You might be able to use `magit-process-prompt-functions` to hook into Magit. Also look at how the value of `magit-this-error` is set an acted on.

**Comment by ahonnecke** [comment]
For future visitors, this doesn't integrate the failures into magit (which would be better), but functionally it performs pretty well:
https://github.com/ahonnecke/prelude/blob/ubuntu/personal/magit-bindings.el#L11-L67

When a hook fails, the failure shows up in magit-process, and this makes it open the magit-process buffer: https://github.com/ahonnecke/prelude/blob/ubuntu/personal/magit-bindings.el#L58-L63

Then this alters find file at point to parse line numbers:
https://github.com/ahonnecke/prelude/blob/ubuntu/personal/magit-bindings.el#L11-L56

This just binds return to the file opener to enter when in the magit-process buffer:
https://github.com/ahonnecke/prelude/blob/ubuntu/personal/magit-bindings.el#L65-L67

**Comment by JSpenced** [comment]
@ahonnecke I can't get pre-commit to run at all when committing? How did you got pre-commit to cooperate with magit?

**Comment by JSpenced** [comment]
Okay, I just found that if I remove `--literal-pathspecs` from the global-arguments it works. @tarsius Is this also what you had to do and if so is there any downside to this elsewhere in magit?

**Comment by npostavs** [comment]
@JSpenced Have you seen https://magit.vc/manual/magit/My-Git-hooks-work-on-the-command_002dline-but-not-inside-Magit.html

**Comment by JSpenced** [comment]
Okay, that explains a lot. I set that in the python pre-commit hook with no issues now. Thanks.
