### ISSUE TITLE
wrong number of arguments for executable-find

### ISSUE THREAD

**Issue by tpapp** [magit/magit#4012]
6401ba9343d4d25c8b77867b0301421bb1ecc980 broke this recently, stacktrace:
```elisp
Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 2)
  executable-find("git" t)
  magit-turn-on-auto-revert-mode-if-desired()
  magit-auto-revert-mode-enable-in-buffers()
```
At least in Emacs 26.3, `executable-find` has a *single* argument.

Magit 20191207.2321, Git 2.20.1, Emacs 26.3, gnu/linux.

**Comment by tarsius** [comment]
#4010 #4011 

It might take a few hours for the fix to make it into a Melpa package.

**Comment by tpapp** [comment]
Apologies, should have checked first.
