### ISSUE TITLE
Automatically stash uncommitted changes before switching branches

### ISSUE THREAD

**Issue by gaudecker** [magit/magit#4013]
I would like to humbly request a new feature that would automatically stash unstaged changes when switching branches.

It would create a stash named after the current branch, like `"Auto-stash for feature/foo-bar"`, then later when switching back to our imaginary branch `feature/foo-bar`, Magit would check if an auto-stashed stash exists for the branch and pop it automatically (or at least prompt the user if they want it to be popped).

I looked through the documentation but did not find this feature. I would probably hack this myself, but I did not find any pre-checkout-branch hook.

**Comment by tarsius** [comment]
Sounds useful but so far it hasn't bothered me that I have to do it manually. Also I often use a regular commit (with message `[wip]` or `[dump]`) to "stash" the work.

Adding this to Magit would involve changes to quite a few commands, so I would like to first look into alternatives.

It seems to me it would be best if `git branch` and `git checkout` gained new `--autostash` and `--autopop` arguments, similar to the `--autostash` supported by `git rebase`. Can't hurt to suggest this on the Git mailing list as well.

**Comment by gaudecker** [comment]
Having the feature it Git itself would indeed be best. I'll return here if I have some luck at the Git mailing list.

**Comment by lukasjuhrich** [comment]
@gaudecker did you have any success at the mailing list? Searching in the archives for `checkout autostash` was a bit too broad to find anything.

**Comment by kyleam** [comment]
> did you have any success at the mailing list? Searching in the archives for `checkout autostash` was a bit too broad to find anything.

No one took up the idea.  Here's the thread: https://lore.kernel.org/git/8ab7d980-9584-4ce7-b4ee-9acac62c030c@www.fastmail.com/T/#u

**Comment by mgaitan** [comment]
As I didn't find a solution, I made this script https://gist.github.com/mgaitan/d9a3523d79cd5f9fbfd626f646f0560b

I hope it'll be useful for somebody else. Any feedback is welcome.
