### ISSUE TITLE
Untracked files won't show when ignoreSubmodules = dirty

### ISSUE THREAD

**Issue by r-darwish** [magit/magit#4019]
My git configuration contains the following snippet

```ini
[diff]
    ignoreSubmodules = dirty
```

Which is a valid value according to the man page. After a7699f86 trying to run `magit-status` does not show untracked files. Instead, I get the following line in the buffer

```
Filter!   diff.ignoreSubmodules=dirty
```

No trackback pops up when `toggle-debug-on-error` is set. I managed to reproduce it with Magit Q command. This problem effects all repositories, even those without submodules.

**Comment by tarsius** [comment]
> After a7699f8 trying to run `magit-status` does not show untracked files. 

I cannot reproduce that.

Did you actually narrow the issue down to this commit using `git blame`?

> Instead, I get the following line in the buffer `Filter!   diff.ignoreSubmodules=dirty`.

That's intentional, except the "instead" part of course.

**Comment by tarsius** [comment]
What git version do you use? Maybe its `git status` does not support `--ignore-submodules` as used in `magit-insert-untracked-files`.

**Comment by tarsius** [comment]
2.2.0 is the minimal version and that supports `--ignore-submodules`. Run `git status --porcelain --ignore-submodules` in a terminal to see if anything weird is going on.

**Comment by r-darwish** [comment]
> Did you actually narrow the issue down to this commit using `git blame`?

Yes. Blaming showed that specific commit and managed to reproduce it with `magit-emacs-Q-command`. When I comment out `ignoreSubmodules = dirty` and refresh the status buffer the untracked files appear again. I also removed everything else from my git configuration beside ignoreSubmodules = dirty` and it still happens. I'm using Git 2.24.1 on macOS.

`git status --porcelain --ignore-submodules` shows the untracked file

**Comment by tarsius** [comment]
Since I cannot reproduce it, please investigate this yourself by adding debug statements and such to `magit-insert-untracked-files`. Start by commenting out the call to `magit-ignore-submodules-p`.

**Comment by r-darwish** [comment]
Commenting out `magit-ignore-submodules-po` solves the problem. I put `(prin1 args)` at the beginning of `magit-git-items` and here is the command:

```elisp
("status" "-z" "--porcelain" "diff.ignoreSubmodules=dirty" "--" nil)("ls-files" "-z" "--stage")
```

Shouldn't "diff.ignoreSubmodules=dirty" be "--ignore-submodules=dirty" instead?

**Comment by tarsius** [comment]
Ah, couldn't reproduce before because I had `status.showUntrackedFiles=all`, which uses a code path without the bug.

**Comment by r-darwish** [comment]
Thank you 🙏
