### ISSUE TITLE
add no-autostash option resp. autodetect default config

### ISSUE THREAD

**Issue by ensc** [magit/magit#4022]
I have

```ini
[rebase]
        autosquash = true
```

in my global `~/.gitconfig`.  Sometimes I want to deselect this when starting an interactive rebase (`r i`).  There you have two (!) autostash options (`-a` and `-A`) but none which sets `--no-autostash`.

I suggest to either autodetect the default configuration and pre-select `-a` and set `--no-autostash` when option is disabled, or add another switch to set `--no-autostash` explicitly.

**Comment by tarsius** [comment]
The plan is to add some sort of combined argument that knows about the argument, its inverse and relevant variables. See #2993.

I won't rush that. Meanwhile you can work around this by *not* setting the variable and instead enabling the argument permanently. (Try `C-x s` inside the transient prefix command.) You can then temporarily disable the argument when needed.
