### ISSUE TITLE
interactive rebase should start one commit later

### ISSUE THREAD

**Issue by ensc** [magit/magit#4023]
see #4021

The workaround mentioned there does not work when megit is installed as a packaging. You have to `eval-defun` on `magit-rebase-interactive-1` which is not an option.  Probably it is too hacky to redefine the `concat` builtin function.

For reference:

```lisp
(defun ensc/magit-concat (&rest sequences)
  (if (equal (cadr sequences) "\\^")
      (progn (message "magit: rewriting %s" (car sequences))
	     (car sequences))
    (apply 'concat* sequences)))

;; https://github.com/magit/magit/issues/4021#issuecomment-567921449
(defun ensc/magit-rebase-interactive-1 (fn commit args message &optional editor delay-edit-confirm noassert confirm)
  (print "============{{{")
  (print this-command)
  (print commit)
  (if (eq this-command 'magit-rebase-interactive)
      (cl-letf (((symbol-function 'concat*)
		 (symbol-function 'concat))
		((symbol-function 'concat) 'ensc/magit-concat))
	(funcall fn commit args message editor
		 delay-edit-confirm noassert confirm))
    (funcall fn commit args message editor
	     delay-edit-confirm noassert confirm))
  (print "============}}}")
  )

(eval-after-load 'magit-sequence
  (advice-add #'magit-rebase-interactive-1 :around
	      #'ensc/magit-rebase-interactive-1))
```

produces

```
"============{{{"

magit-rebase-interactive

#("327f581" 0 7 (fontified nil))

Proceed despite merge in rebase range?  [c]ontinue, [s]elect other, [a]bort c
Running git rebase -i 327f581^
magit: rewriting 327f581

"============}}}"
```

**Comment by npostavs** [comment]
> The workaround mentioned there does not work when megit is installed as a packaging. You have to `eval-defun` on `magit-rebase-interactive-1` which is not an option.

`advice-add` works on functions which haven't been defined yet (the advice will get applied when the function gets defined), so I don't think there should be any need to `eval-defun` anything.

**Comment by ensc** [comment]
does not make a difference; still the same result when executing `advice-add` immediately.

(It is the right place; after removing https://github.com/magit/magit/blob/master/lisp/magit-sequence.el#L639-L641 `r i` behaves as expected.)

**Comment by npostavs** [comment]
> (It is the right place; after removing https://github.com/magit/magit/blob/master/lisp/magit-sequence.el#L639-L641 `r i` behaves as expected.)

For me, applying the advice seems to have the same effect as removing those lines (i.e., the earliest commit highlighted is left out of the rebase), so I'm not sure what the problem is.

**Comment by ensc** [comment]
Try to byte-compile the magit-sequence.el file and restart emacs.  Here (GNU Emacs 26.3 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 2.24.32) of 2019-11-05), the behavior differs from `eval-defun` then:

- the `"^"` string (when dumping `ensc/magit-concat` arguments) becomes `"\\^"`

- the "Running git rebase -i 327f581^" message (with `^`) appears before the debug output in concat

So I guess, byte-compiling the file optimizes the `concat` builtin call and the override does not work anymore.

**Comment by tarsius** [comment]
> see #4021

I don't appreciate it that you opened a new issue. If you open a third issue about this, then I will ban you.

> the `"^"` string (when dumping `ensc/magit-concat` arguments) becomes `"\\^"`

Its obvious what you have to do to make the advice work regardless of whether it is compiled or not.

**Comment by ensc** [comment]
> I don't appreciate it that you opened a new issue

then please do not close the issue until they are resolved!

> Its obvious what you have to do to make the advice work regardless of whether it is compiled or not

Then please tell the obious way!

**Comment by tarsius** [comment]
`(member (cadr sequences) '("^" "\\^")`

**Comment by ensc** [comment]
@tarsius please look in my code.  I am using `"\\^" already there.

The problem is that byte compiling seem to optimize the `concat` call

**Comment by npostavs** [comment]
> So I guess, byte-compiling the file optimizes the `concat` builtin call and the override does not work anymore.

Oh, that makes sense actually.

> the "^" string (when dumping ensc/magit-concat arguments) becomes "\\^"

This part doesn't quite make any sense to me. Different shell-quoting styles perhaps? What OS are you on?

> > I don't appreciate it that you opened a new issue
> 
> then please do not close the issue until they are resolved!

Please note that you can continue to post in closed issues.

**Comment by ensc** [comment]
> This part doesn't quite make any sense to me. Different shell-quoting styles perhaps? What OS are you on?

Linux, Fedora 31

**Comment by npostavs** [comment]
Okay, how about this alternative which overrides `magit-run-git-sequencer` instead of `concat`. I tried to handle both `\^` and `^`, though I'm still not entirely clear on where the backslash is coming from.
```emacs-lisp
(defun magit-rebase-interactive-1-my-way (fn &rest args)
  (if (eq this-command 'magit-rebase-interactive)
      (cl-letf* ((magit-run-git-sequencer-orig
                  (symbol-function 'magit-run-git-sequencer))
                 ((symbol-function 'magit-run-git-sequencer)
                  (lambda (&rest rebase-args)
                    (let ((last (last rebase-args)))
                      ;; Drop trailing ^ or \^ in last arg.
                      (when (string-match "\\\\?^\\'" (car last))
                        (setcar last (substring (car last) 0 (match-beginning 0)))))
                    (apply magit-run-git-sequencer-orig rebase-args))))
        (apply fn args))
    (apply fn args)))

(advice-add #'magit-rebase-interactive-1 :around
            #'magit-rebase-interactive-1-my-way)
```

**Comment by ensc** [comment]
> Okay, how about this alternative which overrides magit-run-git-sequencer

The result will be ok, but the `magit-rebase-interactive-assert` call will work on the wrong commit and cause unneeded "in merge" queries.

I guess I will end up in copy & pasting the current `magit-rebase-interactive-1` implementation and add the `(unless (eq this-command 'magit-rebase-interactive)` there.  Of course, this will fall on my feets in some years but is probably the best which I can do atm.

**Comment by tarsius** [comment]
https://github.com/raxod502/el-patch
