### ISSUE TITLE
no password prompt on push to a particular ssh remote

### ISSUE THREAD

**Issue by ahihi** [magit/magit#4025]
push works normally except for this one particular remote, where i get no password prompt and the push goes nowhere. pressing $ shows that there is a prompt, but i guess magit is failing to recognize it?

```
run git … push -v foo master\:refs/heads/master
Pushing to ssh://ahihi@foo:/home/ahihi/git/dotfiles
Password for ahihi@foo:
```

client:
Magit 20200102.2204, Git 2.13.6 (Apple Git-96), Emacs 26.2, darwin
OpenSSH_7.4p1, LibreSSL 2.5.0

server:
Git 2.12.1, FreeBSD
OpenSSH_7.2p2, OpenSSL 1.0.2k-freebsd  26 Jan 2017

**Comment by kyleam** [comment]
> pressing $ shows that there is a prompt, but i guess magit is failing to recognize it?
> 
> ```
> run git … push -v foo master\:refs/heads/master
> Pushing to ssh://ahihi@foo:/home/ahihi/git/dotfiles
> Password for ahihi@foo:
> ```

Yeah, that wouldn't match any regexp defined here:

https://github.com/magit/magit/blob/df191f42a21416ab73616769aa116928db2fec9f/lisp/magit-process.el#L165-L176

If there were quotes around `ahihi@foo`, then the second entry would match.  Given the client/server details you listed, I'm a bit surprised that this hasn't been reported before.  We should probably adjust the regexp to make the quotes optional, but in the meantime you can of course resolve this issue by configuring `magit-process-password-prompt-regexps` on your end.

**Comment by ahihi** [comment]
thanks! i've adjusted my regex for now.
