### ISSUE TITLE
Blame with --ignore-revs doesn't group the same commit together for some lines

### ISSUE THREAD

**Issue by verhovsky** [magit/magit#4030]
I have these lines in `~/.gitconfig`

```yaml
[blame]
    ignoreRevsFile = ~/.ignore-revs
```

in that file I put the hashes of a few large and useless commits like changing the formatter or mass-renamings, so that they don't show up in `git blame`. This works with Magit's blame, but it seems like it doesn't group the commits correctly and in the Magit blame view I'll sometimes get a a few lines in a row that are all shown as the same commit, but the line with the commit date and hash is repeated multiple times for lines that should be grouped

```
me        2019-10-05 12:12 "do stuff, commit A"
def foo():
me        2019-10-05 12:12 "do stuff, commit A"
    whatever()
me        2019-10-05 12:12 "do stuff, commit A"
    some_other_stuff()
    2 + 2
me        2019-10-05 12:12 "do stuff, some other commit B"
    return True
me        2019-10-05 12:12 "do stuff, commit A"


```

`--ignore-revs` and `--ignore-revs-file` were added to `git blame` fairly recently, in Git 2.23

**Comment by tarsius** [comment]
There seems to be a bug in git:

```
git blame --ignore-rev c6ee049c -- file                 
^1dffd24 (Jonas Bernoulli 2020-01-21 21:54:38 +0100 1) 1
3dcc6075 (Jonas Bernoulli 2020-01-21 21:54:52 +0100 2) 2
c6ee049c (Jonas Bernoulli 2020-01-21 21:55:08 +0100 3) 3
8988bdd0 (Jonas Bernoulli 2020-01-21 21:55:16 +0100 4) 4
```

I expected:

```
git blame --ignore-rev c6ee049c -- file                 
^1dffd24 (Jonas Bernoulli 2020-01-21 21:54:38 +0100 1) 1
3dcc6075 (Jonas Bernoulli 2020-01-21 21:54:52 +0100 2) 2
3dcc6075 (Jonas Bernoulli 2020-01-21 21:55:08 +0100 3) 3
8988bdd0 (Jonas Bernoulli 2020-01-21 21:55:16 +0100 4) 4
```

Am I wrong to expect that?

**Comment by kyleam** [comment]
I haven't played around with this feature much, but I think the issue is that there is no previous commit to fall back on and blame.  If you `git config blame.markUnblamableLines true`, you should see c6ee049c marked with a "*".

**Comment by tarsius** [comment]
It indeed gets prefixed with `*` but:

```
git log --oneline -u
8988bdd (HEAD -> master) 4
diff --git a/file b/file
index 7d8164b..94ebaf9 100644
--- a/file
+++ b/file
@@ -1,4 +1,4 @@
 1
 2
 3
-3
+4
c6ee049 3
diff --git a/file b/file
index 6cb54d9..7d8164b 100644
--- a/file
+++ b/file
@@ -1,4 +1,4 @@
 1
 2
-2
-2
+3
+3
3dcc607 2
diff --git a/file b/file
index 98fb6a6..6cb54d9 100644
--- a/file
+++ b/file
@@ -1,4 +1,4 @@
 1
-1
-1
-1
+2
+2
+2
1dffd24 1
diff --git a/file b/file
new file mode 100644
index 0000000..98fb6a6
--- /dev/null
+++ b/file
@@ -0,0 +1,4 @@
+1
+1
+1
+1
```

**Comment by tarsius** [comment]
Well, I am going to try with git's test for this feature.

**Comment by kyleam** [comment]
> It indeed gets prefixed with `*` but [git log]

When `blame` is trying to assign lines, it considers the content similarity as well.  See git's 1d028dc682 (blame: add a fingerprint heuristic to match ignored lines, 2019-06-20).  Before that commit (or rather the next commit that wired the fingerprint heuristic up to the blame machinery), the ignore-rev feature actually used a simpler method.  If I checkout a check out a commit in that series so that the simpler method is used and then generate a repo with the structure of yours, I see a line that matches what you expected (aside from `s/2)/3)/`, which I think is correct, and the hash of course).

So, with that simple history and one character lines, I don't think anything you showed is unintended behavior on git's end.

**Comment by tarsius** [comment]
We get neighboring chunks that are attributed to the same commit because we use the `--incremental` argument. We could try to merge these chunks again in `magit-blame--make-overlays`.

**Comment by tarsius** [comment]
...but for the time being I am going to consider this a feature. :stuck_out_tongue_winking_eye:
It's not a high priority at least.
