### ISSUE TITLE
ediff-copy-diff: buffer-read-only 

### ISSUE THREAD

**Issue by kootenpv** [magit/magit#4033]
Please explain

    (1) what behavior you expected

to be able to solve my conflicts: when I press `e` and then try either `a` or `b`, it throws the error of the title

    (2) what behavior you observed

I am not allowed to copy the contents from one buffer to another

    (3) and how we can reproduce the issue.

for me it happens with any merge conflict

**Comment by tarsius** [comment]
In a Magit buffer `e` invokes the Ediff command that some heuristic has determined to be the right Ediff command to invoken base on the location of the cursor. It's possible that it gets it wrong in some cases and/or that you simply expect something else and neither you nor Magit's heuristic is *wrong*.

Try  `E` instead and then explicitly use the variant that makes sense to you in that context. Does that work as expected?

If you think Magit's behavior is wrong, then please explain in what context you pressed `e` and what Ediff variant was used and which variant should have been used instead.
