### ISSUE TITLE
git-commit-co-authored fails because of wrong argument

### ISSUE THREAD

**Issue by mbuczko** [magit/magit#4035]
I'm not really sure if it's an issue or the problem of my own configuration (sorry for bothering in this case), but trying to call `git-commit-co-authored` fails with following message:

```
In ‘git-commit-co-authored History’ source: ‘#[0 \304\302\300\305\303$\211\205\306\307\310\301""\207 [nil nil git-commit-read-ident-history t helm-comp-read-get-candidates nil delete  helm-cr-default] 6]’ 
 (wrong-type-argument listp git-commit-read-ident-history)
```

At the begining I was pretty sure that `git-commit-read-ident-history` was not loaded in my doom-emacs config, but looking at https://github.com/magit/magit/blob/master/lisp/git-commit.el I can't find any other occurence of this symbol. Where does it actually come from?

Steps to reproduce:
`C-c tab C-a` when editing commit message.

magit-version:
Magit 20200126.1750, Git 2.25.0, Emacs 26.3, darwin

**Comment by tarsius** [comment]
This sounds like an outdated `git-commit.elc` is still laying around. Try removing that and restarting Emacs. If that works, then uninstall Magit, restart Emacs, and then reinstall Magit.

**Comment by mbuczko** [comment]
Thanks, I tried it - removed all magit-* packages + git-commit one, made sure that nothing was left, restarted emacs and installed magit from scratch. Following packages were added:

git-commit-20200123.1706
magit-20200126.1750
magit-popup-20200102.1811

and unfortunately the problem still persists. I looked again into git-commit.el and `git-commit-read-ident` function still contains `git-commit-read-ident-history` which emacs complains about:

https://github.com/magit/magit/blob/e5e475c61ce568a7e20ed8f795fa343a93632871/lisp/git-commit.el#L777

**Comment by tarsius** [comment]
That is `magit-completing-read`'s HIST argument, which is forwarded to `completing-read`, where it is documented like so:

```
HIST, if non-nil, specifies a history list and optionally the initial
  position in the list.  It can be a symbol, which is the history list
  variable to use, or it can be a cons cell (HISTVAR . HISTPOS).  In
  that case, HISTVAR is the history list variable to use, and HISTPOS
  is the initial position (the position in the list used by the
  minibuffer history commands).  For consistency, you should also
  specify that element of the history as the value of INITIAL-INPUT.
  (This is the only case in which you should use INITIAL-INPUT instead
  of DEF.)  Positions are counted starting from 1 at the beginning of
  the list.  The variable `history-length' controls the maximum length
  of a history list.
```

So it is expected that this could be a symbol.

This could also be caused by a third-party completion framework, but then a lot of other things would be broken too.

**Comment by mbuczko** [comment]
> So it is expected that this could be a symbol

Yup, indeed. But in my specific case it points to nothing that emacs recognizes, whereas doc says: "It can be a symbol, _which is the history list variable_ to use."

Adding variable explicitly like this: `(defvar git-commit-read-ident-history nil)` solves my problem, but I wonder why it happens on my side only...

**Comment by tarsius** [comment]
Yeah, it should be declared. Maybe it works without that only for me because we use different Emacs versions.

**Comment by mbuczko** [comment]
I have just created a tiny PR for that: https://github.com/magit/magit/pull/4039.

Feel free to reject if you think my case is exceptional and shouldn't really happen :)
