### ISSUE TITLE
lsp breaks magit-log-trace-definition

### ISSUE THREAD

**Issue by agzam** [magit/magit#4038]
This is [most likely] not an issue in Magit itself, but maybe someone suggests a workaround. I recently noticed that `magit-log-trace-definition` stopped working for me. And then started digging, and interestingly I have found that it works but only until lsp-mode gets connected to the server.
Strangely, somehow it changes the way how `(which-function)` works. Before `lsp` - it would return just the function name, after `lsp` gets connected, it appends things like `(Function)` or `(Variable)` to the string it returns. And that breaks aforementioned Magit function. Would appreciate if anyone can help me find a way to fix it.

upd: it seems lsp changes `imenu--index-alist` and `(which-function)` depends on that.

**Comment by kyleam** [comment]
Short of fixing lsp to not do that, you could set `magit-log-trace-definition-function` to `add-log-current-defun`. (I don't recall what the disadvantages of that are.  Perhaps support for fewer modes?).  Another would be to set it to another function that wraps `magit-which-function` (the default value for `magit-log-trace-definition-function`) and strips the extra text that is appended.  Or, similarly, you could add advice to `magit-which-function` that strips this text.

**Comment by agzam** [comment]
Thank you. For now I decided to simply `(setq lsp-enable-imenu nil)` and that worked for me. I have also created an issue here https://github.com/emacs-lsp/lsp-mode/issues/1363

I will keep this issue open for a couple more days, maybe someone suggest some better way.

**Comment by agzam** [comment]
`add-log-current-defun` seems to be returning `nil` in some cases

**Comment by agzam** [comment]
Closing this, since this is an upstream issue that has to be fixed outside of Magit. See: emacs-lsp/lsp-mode#1363
