### ISSUE TITLE
xfuncname for Clojure

### ISSUE THREAD

**Issue by dotemacs** [magit/magit#4051]
According to https://github.com/magit/magit/issues/3706 this can be configured for Emacs Lisp which is great, but it doesn't quite work for Clojure.

In **.gitconfig**:

```config
[diff "clojure"]
        xfuncname = (^\\(.*|\\s*\\(def|defn|defrecord|defmulti|defmacro|deftest|ns).*
```

In **.gitattributes**:

```config
*.clj  diff=clojure
*.cljc diff=clojure
*.cljs diff=clojure
*.cljx diff=clojure
```

When the pointer is on the line where I have `defn` declared, that is under git, and I run: <kbd>M-x magit-log-trace-definition RET</kbd>, it works as expected: it narrows to the defined `defn` and I can see the git log just for that sexp.

Where it fails is when I try to narrow it to a sexp where I have `defmethod` defined, which will look something like:

```clojure
(defmethod process :foo:bar
...
```

If I were to run this via:

```shell
git log -L'/process :foo:bar/':src/app/foo/bar.clj
```
I do get the desired results back.

(NOTE: You'll note that I've edited the syntax above and instead of using just the colons around the desired string like so: **:function-name:**, I wrapped the desired string to search in single quotes, which I wrapped in forward slashes: **'/function-name /'**. Which works on the command line, since I want to match Clojure's `defmethod` declarations.)

But trying to tweak `magit-log-trace-definition` and changing:

```
   (cons (format ;;"-L:%s%s:%s"
                 "-L'/%s%s/':%s"
                 (regexp-quote fn)
...
```
(NOTE: I'm talking about this: https://github.com/magit/magit/blob/master/lisp/magit-log.el#L729-L730)

Then I chord: <kbd>C-x C-e</kbd>

And running <kbd>M-x magit-log-trace-definition RET</kbd> on a `defmethod` returns a buffer without any log lines. But if I run the command in the shell:

```shell
git log -L'/process :foo:bar/':src/app/foo/bar.clj
```

I do get the results.

What needs to be tweaked to enable the above setup to work on Clojure's `defmetho` definitions? 

Thanks

**Comment by dotemacs** [comment]
Would it help to create a sample repo that would give you example defmethods, so that this can be tried out, rather than just following my write up?

**Comment by tarsius** [comment]
The quoting is just for the shell. `call-process` et al. don't use a shell so the quoting get passed along to `git`, which then gets confused by it. Just use `"-L/%s%s/:%s"` instead; then it works in Emacs as well.

```
$ git log "-L:bbb \\:foo:bar/:foo.el"
fatal: There is no path bar/:foo.el in the commit
```

I don't see anything in the documentation about how to quote `:` in the function name, so we have to use `/<regexp>/` as you have done I think. It should be possible to detect when that is necessary and to construct the value ourselves using the appropriate `diff.*.xfuncname`. If the "function name" contains `:` and `/`, then we probably lose.

Maybe you want to have a go at this yourself?

**Comment by kyleam** [comment]
> I don't see anything in the documentation about how to quote `:` in the function name, so we probably have to use `/<regexp>/` as you have done.

I don't spot anything in the documentation either, but on my end the same `\` that works for regexp characters works for `:` (e.g., `git log -L':process \:foo\:bar:b.clj'`).  Here's Git's handling of that:

```c
static const char *parse_range_funcname(
[...]	
	term = arg+1;
	while (*term && *term != ':') {
		if (*term == '\\' && *(term+1))
			term++;
		term++;
	}
```

So perhaps something like below would do:

```diff
diff --git a/lisp/magit-log.el b/lisp/magit-log.el
index c3c25e44..6764bfd6 100644
--- a/lisp/magit-log.el
+++ b/lisp/magit-log.el
@@ -727,7 +727,7 @@ (defun magit-log-trace-definition (file fn rev)
   (magit-log-setup-buffer
    (list rev)
    (cons (format "-L:%s%s:%s"
-                 (regexp-quote fn)
+                 (replace-regexp-in-string ":" "\\:" (regexp-quote fn) nil t)
                  (if (derived-mode-p 'lisp-mode 'emacs-lisp-mode)
                      ;; Git doesn't treat "-" the same way as
                      ;; "_", leading to false-positives such as
```

**Comment by dotemacs** [comment]
@kyleam's solution is spot on. 

I can do the PR for this.

I have a question:
For my needs escaping the "**:**" is sufficient.
Do you want the escaping of the of "**/**" also ?
Or should I go "crazy" and create a function that allows the users to specify all the possible escape sequences that they'd want/need?

Something like:

```emacs
(magit-log-trace-definition-regexp-escape-alist '((":" . "\\:") ("\" . "\\\")))
```

Or is there an even better approach?

Thank you for your time

**Comment by dotemacs** [comment]
Or thinking about it, maybe even:

```emacs-lisp
(magit-log-trace-definition-regexp-escape-list '(":" "\"))
```

Where every element of the list would be escaped.

What do you think?

**Comment by tarsius** [comment]
Are you maybe overthinking his? Which cases are not covered by the trivial change @kyleam suggested?

**Comment by dotemacs** [comment]
Well, I'm happy to bring in @kyleam's change as a PR, but you mentioned '/' as a possible string that might need to be escaped also...
