### ISSUE TITLE
Rebase strategy option

### ISSUE THREAD

**Issue by sergefdrv** [magit/magit#4059]
Sometimes it is useful to specify different strategies for `git rebase` command, e.g. `subtree` strategy when rebasing a commit range including a subtree merge commit. Magit currently does not support specifying a rebase strategy in the Rebase Popup buffer. So one has to use an inconvenient CLI, like `git rebase -s subtree <...>`. It would be nice to add `-s` switch to Magit Rebase Popup buffer for specifying rebase strategy.

**Comment by tarsius** [comment]
Certain transient popups hide some of their suffix commands by default. These additional suffixes can be [enabled interactively](https://magit.vc/manual/transient/Enabling-and-Disabling-Suffixes.html). TL;DR Enter the transient as usual and type <kbd>C-x l</kbd>.

<sub>This is a [canned response](https://help.github.com/en/github/writing-on-github/working-with-saved-replies); it may not apply 100% in this case.</sub>

**Comment by sergefdrv** [comment]
@tarsius Thanks for adding this!
