### ISSUE TITLE
Global key bindings when Global Magit-File mode enabled

### ISSUE THREAD

**Issue by sergefdrv** [magit/magit#4060]
For some reason, Magit-File mode binding `C-x g` (`magit-status`) doesn't work for me until I invoke `magit-status` manually for the first time, even though I have Global Magit-File mode enabled. So I have to add `(global-set-key (kbd "C-x g") 'magit-status)` to my Emacs configuration file myself.

I wonder if this behavior of Global Magit-File mode is intentional?

**Comment by tarsius** [comment]
The global mode only enables the local `magit-file-mode` in file-visiting buffer. The bindings are in the keymap of that mode, so pressing `C-x g` in non-file-visiting buffers has not effect. You should explicitly bind `magit-status` in the global map as well, as you have done. At least the last part is documented.

**Comment by sergefdrv** [comment]
Thank you for answering. Apparently, `C-x g` doesn't work in file-visiting buffers if Global Magit-File mode is enabled in Customize...

**Comment by tarsius** [comment]
`global-magit-file-mode` is enabled by default now, so you don't have to do that explicitly. Does it work if you don't do it explicitly yourself?

By the way this is all due to a defect of `define-globalized-minor-mode`. This is how we use it:

```emacs-lisp
;;;###autoload
(define-globalized-minor-mode global-magit-file-mode
  magit-file-mode magit-file-mode-turn-on
  :package-version '(magit . "2.13.0")
  :link '(info-link "(magit)Minor Mode for Buffers Visiting Files")
  :group 'magit-essentials
  :group 'magit-modes
  :init-value t)
;; Unfortunately `:init-value t' only sets the value of the mode
;; variable but does not cause the mode function to be called, and we
;; cannot use `:initialize' to call that explicitly because the option
;; is defined before the functions, so we have to do it here.
(cl-eval-when (load eval)
  (when global-magit-file-mode
    (global-magit-file-mode 1)))
```

**Comment by sergefdrv** [comment]
> `global-magit-file-mode` is enabled by default now, so you don't have to do that explicitly. Does it work if you don't do it explicitly yourself?

I removed the customization, and, indeed, `C-h v global-magit-file-mode` says it is set to `t`. But unfortunately, this doesn't change the behavior. The binding only start working after doing `C-u 1 M-x global-magit-file-mode`.

**Comment by tarsius** [comment]
I don't think there is anything that can be done about this.

The doc-strings and default values of `magit-file-mode` and `global-magit-file-mode` are the only parts that are being autoloaded.  If we also autoloaded the mode activation kludge then the local mode would get activated when appropriate...

...but at a very high price.  If we did that then all of Magit would have to be loaded as soon as any file-visiting buffer is visited (even one that isn't located inside a Git repository).  That takes quite some time so we very much want to avoid that.

You will have to do something to explicitly load Magit.  The easiest way would be adding `(require 'magit)` to your init file.  Or you can add key bindings in the global map and load Magit on demand by using one of those bindings.  I don't see any other alternative.

**Comment by sergefdrv** [comment]
Thank you for elaborating on the issue. I see the trade-off and will stick to the latter solution :+1:
