### ISSUE TITLE
Add "color.ui=false" to magit-git-global-arguments as default or explicitly tell user why when the magit-git-wash-diffs is not complete

### ISSUE THREAD

**Issue by twlz0ne** [magit/magit#4064]
I just started learning to use magit a few days ago. There was a problem that once bothered me, and I think other people may also encounter this problem when they first try magit.

The thing is, When I load magit I had this lines in `~/.giconfig`:

```ini
[color]
    ui = always
```

But I thought it just made the output a bit ugly, so I did not set the `magit-git-global-arguments` immediately.

Then I found that my magit status buffer is different from the pictures I found on Google.

**The `Unstaged changes` section was disappeared without any notice.**

I can not use the `stage/unstage` command until the `"-c" "color.ui=false"` was
added to `magit-git-global-arguments` then this problem was incidentally resolved.

After some debugging, I found that that the problem was ingored during the wash process:
    
```elisp
;; magit-git.el
(defun magit-git-wash (washer &rest args)
    ......
      (save-restriction
        (narrow-to-region beg (point))
        (goto-char beg)
        (funcall washer args)) ;; ----------.
      (when (or (= (point) beg)             |
                (= (point) (1+ beg)))       |
        (magit-cancel-section)) ;; <--------(--------.
      (magit-maybe-make-margin-overlay))))  |        |
                                            |        |
;; magit-diff.el                            v        |
(defun magit-diff-wash-diffs (args &optional limit)  |
  ......                                             |
  ;; Do nothing because the `magit-diff-headline-re' does not
  ;; match when the diff output contains ANSI color sequence.
  (when (re-search-forward magit-diff-headline-re limit t)
    (goto-char (line-beginning-position))
    (magit-wash-sequence (apply-partially 'magit-diff-wash-diff args))
    (insert ?\n)))
```

EDIT: or change `magit-diff-headline-re` to match the color sequence to solve this problem.

**Comment by tarsius** [comment]
There's a FAQ entry about this: https://magit.vc/manual/magit/Diffs-contain-control-sequences.html#Diffs-contain-control-sequences.

I'm not sure why we didn't add these settings to the default value.

Iam guessing its because its my opinion that nobody should ever set one of these variables to `always` in the first place. IMO `always` means "do it even when that is harmful", while `true` means "do it only hen it is useful". Users should prefer the latter. :stuck_out_tongue_winking_eye:

**Comment by tarsius** [comment]
@kyleam @npostavs Should we add it to the default value?

**Comment by kyleam** [comment]
> Should we add it to the default value?

I'm in favor of the status quo here and think the manual's treatment of this is sufficient.

**Comment by npostavs** [comment]
i think it could make sense to add it to the default value. But I don't feel strongly about it either way.

**Comment by phil-s** [comment]
FWIW I suggest that if it *never* makes sense to have colour control sequences in the git output being consumed by Magit, then adding this to the default value is the right thing to do.

I agree that users shouldn't use `always` as a value in the first place -- but perhaps the `true` behaviour is broken for them somehow for something outside of Magit, and they have gone with `always` as a dodgy solution for that.  I think that if Magit has a way of ensuring that doesn't cause problems, it should use it.

I'm assuming there's no particular down-side to including the option?

**Comment by tarsius** [comment]
> I'm assuming there's no particular down-side to including the option?

I cannot think of one, but if it turns out I was wrong then I might have to revert this.
