### ISSUE TITLE
Executing magit-list-submodules over TRAMP connection lead to 100% CPU consumption and take unexpectedly long time to finish

### ISSUE THREAD

**Issue by lyskov** [magit/magit#4066]
When executing `magit-list-submodules` on repository over TRAMP connection that have multiple submodules (~13) Emacs starts to consume 100% CPU and hang for an _unexpectedly  long_ time (at least 10m+, possibly longer, - was never able to see if it finishes). This behavior is always reproducible.

Magit version: Git master branch at `1916e83aa463fee86ac1c6bcfd80d780d0544901`

**Comment by tarsius** [comment]
I just did it with a repository that has 87 submodules and it took 15 seconds. Now while that isn't exactly fast it also demonstrates that it does not always take more than ten minutes.

**Comment by phil-s** [comment]
Which version of Emacs?  (What does `M-x emacs-version` report?)

If you're using a build of 27 or 28, compiling a newer version might help, as there have been Tramp-related issues with CPU usage fixed upstream in relatively recent times.

Or if you prefer not to recompile, you can try installing the latest Tramp release from GNU ELPA.

**Comment by lyskov** [comment]
> Which version of Emacs? (What does `M-x emacs-version` report?)

"GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6) of 2019-12 05"

Which I am guessing is a bit old? - I will see if i can upgrade my build and if that will help. - thanks @phil-s !



> I just did it with a repository that has 87 submodules and it took 15 seconds. Now while that isn't exactly fast it also demonstrates that it does not always take more than ten minutes.

@tarsius thats impressive, but just to double check: this is over TRAMP connection, right? Because i do not see any weird behavior when i am working with submodules from local repositories.

**Comment by phil-s** [comment]
26.3 is still the current stable release.  Try updating Tramp from GNU ELPA though.

`M-x package-list-packages` then `i` to mark `tramp` for installation/update, and `x` to make it happen.

**Comment by lyskov** [comment]
I can confirm that upgrading TRAMP to 2.4.3.2 indeed fixed this issue. After upgrade `magit-list-submodules` starts to take reasonable time (~20s). Thank you for your help @phil-s !

One more thing: i noticed that even after upgrade execution of `magit-list-submodules` still trigger 100% of CPU consumption until it finishes. Which seems odd to me since most of this time Emacs should be waiting for network replies. Maybe it something worth investigating? (because of this i am not closing this issue and leaving it to you in case you think it would be something thats needed to be looked up).

Thank you for you help!
