### ISSUE TITLE
Question about windows cygwin configuration alongside Git

### ISSUE THREAD

**Issue by ema2159** [magit/magit#4067]
Hi. Sorry if this is something basic. I'm new to using Emacs in Windows and I wanted to know how I could use normal Git when cygwin is installed. I'm doing the following:

- If I don't add cygwin to PATH, Magit works correctly.
- If I add cygwin to the PATH environment variable like this:
``` elisp
(setq cygwin-bin "C:\\cygwin64\\bin")
    (setenv "PATH"
	    (concat (getenv "PATH") ";" cygwin-bin))
```
- It throws an error (`rmail-autodetect: Wrong type argument: stringp, cygwin-bin `)

- If I do `M-x getenv RET PATH`, the following is printed:
`C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\TortoiseSVN\bin;C:\Users\ebustos\AppData\Local\Microsoft\WindowsApps;C:\Users\ebustos\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\ebustos\AppData\Local\Programs\Git\cmd;C:\cygwin64\bin
` 
If I concat PATH and cygwin-bin the other way, the same thing happens.

What should I do in order for them to work properly?

**Comment by npostavs** [comment]
[The issue tracker isn't for support requests](https://github.com/magit/magit#support)

> It throws an error `(rmail-autodetect: Wrong type argument: stringp, cygwin-bin )`
> [...]
>If I concat PATH and cygwin-bin the other way, the same thing happens.

But I guess the same thing would happen even if you remove the `concat` entirely. You've got an extra quote in front of `cygwin-bin` somewhere else in your config.

**Comment by ema2159** [comment]
@npostavs there isn't. That's the only piece of code where that variable is used. I'll try to find a workaround then.

**Comment by articuluxe** [comment]
﻿
Have you tried setting magit-git-executable to the path of the “normal” git?

**Comment by ema2159** [comment]
@articuluxe no, but if I'm not wrong, tarsius said that doing that is a workaround that can be done in certain cases but is something that should not be necessary. It works properly now with the fix I used up! Thanks!
