### ISSUE TITLE
diff-hl-magit-post-refresh doesn't refresh modified files after commit

### ISSUE THREAD

**Issue by afine** [magit/magit#4073]
I'm opening this ticket here at the request of @dgutov, the corresponding diff-hl issue is here: https://github.com/dgutov/diff-hl/issues/136

diff-hl does not appear to automatically update buffers after I commit using magit. I need to execute `(diff-hl-update)` manually to get the desired effect.

I use diff-hl with magit and have the hook configured like so:
```elisp
(use-package diff-hl
  :after magit
  :demand
  :hook (magit-post-refresh . diff-hl-magit-post-refresh)
  :config
  (global-diff-hl-mode)
  (diff-hl-flydiff-mode))
```
I instrumented `diff-hl-magit-post-refresh` and ran through the commit process with Edebug. I noticed that the hook executes twice when going through the commit flow, once before the actual commit and once after.

On the first run, it appears that `(diff-hl-update)` is run on the appropriate buffers, but since the commit has not happened yet this does nothing.

On the second run, `(diff-hl-update)` is not run. It looks like `modified-files` (https://github.com/dgutov/diff-hl/blob/master/diff-hl.el#L597) is nil and the file is in an unmodified state.

magit version: Magit 20200313.1657, Git 2.21.0, Emacs 26.3, darwin

**Comment by kyleam** [comment]
> diff-hl does not appear to automatically update buffers after I commit using magit. I need to execute `(diff-hl-update)` manually to get the desired effect.
> 
> I use diff-hl with magit and have the hook configured like so:

Using those settings, adding the diff-hl (fb9eb1cd3) and magit (68b5a13fa) to `load-path`, and running with `emacs -Q`, I haven't been able to trigger the issue.  When I make a commit, the diff-hl decoration is removed automatically.

(Other info: Emacs 26.3, Git 2.25.0)

> I instrumented `diff-hl-magit-post-refresh` and ran through the commit process with Edebug. I noticed that the hook executes twice when going through the commit flow, once before the actual commit and once after.

Hmm, on committing with a staged file, the hook is triggered only once on my end.

> On the first run, it appears that `(diff-hl-update)` is run on the appropriate buffers, but since the commit has not happened yet this does nothing.
> 
> On the second run, `(diff-hl-update)` is not run. It looks like `modified-files` (https://github.com/dgutov/diff-hl/blob/master/diff-hl.el#L597) is nil and the file is in an unmodified state.

I think that's only relevant for files with unstaged changes.  It's not that condition where I see `diff-hl-update` call after committing changes to a file; it's the next:

```elisp
((not (memq (vc-state file backend) unmodified-states))
 (vc-state-refresh file backend)
 (diff-hl-update))
```

After a commit, `(vc-state file backend)` returns `edited`, which isn't in `unmodified-states`, triggering the update.

What does `(vc-state file backend)` return on your end?

**Comment by afine** [comment]
(vc-state file backend) returns up-to-date

**Comment by afine** [comment]
I stripped down my config (more than I have done in my previous debugging) and that appears to resolve the issue. I'll let you know once I find my misconfiguration.

**Comment by afine** [comment]
I think I found the root cause:

I have `(setq auto-revert-check-vc-info t)` as suggested here: https://magit.vc/manual/magit/The-mode_002dline-information-isn_0027t-always-up_002dto_002ddate.html

Removing this flag makes the issue go away. 

I do like seeing the branch in the mode line so it would be great to keep this around.

**Comment by kyleam** [comment]
> I have `(setq auto-revert-check-vc-info t)`

Thanks for digging.  I can trigger it with that.  That leads to `auto-revert-handler` calling `vc-refresh-state`, so the state is `up-to-date` by the time it's checked by `diff-hl-magit-post-refresh`.

> I do like seeing the branch in the mode line so it would be great to keep this around.

At a personal config level, the fix is easy, I think.  Just hook in somewhere and call `diff-hl-update`.  For example, the autorevert.el code in question looks like this:

```elisp
(when (or revert auto-revert-check-vc-info)
  (let ((revert-buffer-in-progress-p t))
    (vc-refresh-state)))
```

So this should do the trick:

```elisp
(advice-add 'vc-refresh-state :after #'diff-hl-update)
```

Perhaps that's too expensive.  I'm not a vc or diff-hl user.  But, at any rate, you should be able to find somewhere to call `diff-hl-update`.

On the other hand, at a package level (most likely `diff-hl`), I'm not really sure what the right change is.  Focusing just on `diff-hl-magit-post-refresh`, one way to make this work would be

```diff
diff --git a/diff-hl.el b/diff-hl.el
index e78ae10..b97ca11 100644
--- a/diff-hl.el
+++ b/diff-hl.el
@@ -594,6 +594,8 @@ (defun diff-hl-magit-post-refresh ()
                  (backend (vc-backend file)))
             (when backend
               (cond
+               (auto-revert-check-vc-info
+                (diff-hl-update))
                ((member file modified-files)
                 (when (memq (vc-state file) unmodified-states)
                   (vc-state-refresh file backend))
```

But stepping back a bit, it looks like this situation (i.e. committing with a non-nil `auto-revert-check-vc-info`) probably used to trigger `diff-hl-update` (though I didn't check) because `diff-hl-mode` adds `diff-hl-update` to `magit-revert-buffer-hook` and `magit-not-reverted-hook`.  Those hooks were dropped in v2.4.0 with f916cd03 (revert buffers using a globalized variant of auto-revert-mode, 2016-01-12).

As of f916cd03, perhaps it makes sense to find somewhere in autorevert.el to hook into.  That'd have the advantage of handling commits from Magit as well as the command line.  But, scanning autorevert.el, I don't see any existing hooks that'd work for that.  So, then again, perhaps the diff above would be the best way to go.  I don't know.

Given that you're both a diff-hl user and Magit user, would you like think about/investigate what would be best and propose that change to the appropriate project?

**Comment by dgutov** [comment]
@kyleam 

> But stepping back a bit, it looks like this situation (i.e. committing with a non-nil auto-revert-check-vc-info) probably used to trigger diff-hl-update (though I didn't check) because diff-hl-mode adds diff-hl-update to magit-revert-buffer-hook and magit-not-reverted-hook

That's for previous versions of Magit. Starting with 2.4, `diff-hl-magit-post-refresh` was introduced, see https://github.com/dgutov/diff-hl/issues/60 and https://github.com/magit/magit/issues/2491. This function was written according to @tarsius's advice.

If it's still not enough, it's up to Magit's developers decide how it should be fixed. You can even merge this piece of integration inside Magit, so you can update it whenever the available hooks change again. It certainly changes more often than `diff-hl`.

**Comment by dgutov** [comment]
OK, so I did a refresher on the past dicsussions, starting here: https://github.com/magit/magit/wiki/Code-snippets#magit-update-uncommitted-buffer-hook

Apologies to @tarsius, the recommendation is to use both `magit-post-refresh-hook` and `magit-pre-refresh-hook` (and two other hooks? I'm not sure why).

**Comment by dgutov** [comment]
@afine

Could you try the patch below together with this additional line in the init script?

```emacs
(add-hook 'magit-pre-refresh-hook 'diff-hl-magit-pre-refresh)
```

```diff
diff --git a/diff-hl.el b/diff-hl.el
index 9cfb2e5..d955530 100644
--- a/diff-hl.el
+++ b/diff-hl.el
@@ -575,12 +575,22 @@ The value of this variable is a mode line template as in
 (declare-function magit-toplevel "magit-git")
 (declare-function magit-unstaged-files "magit-git")
 
+(defvar diff-hl--magit-modified-files nil)
+
+(defun diff-hl-magit-pre-refresh ()
+  (setq diff-hl--magit-modified-files (magit-modified-files t)))
+
 (defun diff-hl-magit-post-refresh ()
   (let* ((topdir (magit-toplevel))
          (modified-files
           (mapcar (lambda (file) (expand-file-name file topdir))
-                  (magit-unstaged-files t)))
+                  (delete-consecutive-dups
+                   (sort
+                    (nconc (magit-modified-files t)
+                           diff-hl--magit-modified-files)
+                    #'string<))))
          (unmodified-states '(up-to-date ignored unregistered)))
+    (setq diff-hl--magit-modified-files nil)
     (dolist (buf (buffer-list))
       (when (and (buffer-local-value 'diff-hl-mode buf)
                  (not (buffer-modified-p buf))
```

**Comment by afine** [comment]
Apologies for the long delay, work has been a little crazy for me.

I'll give this a shot this week.

**Comment by afine** [comment]
The patch appears to have broken magit for me. 

I now get a `setq: Symbol’s function definition is void: magit-modified-files` when attempting to stage my changes in magit.

**Comment by afine** [comment]
I was able to get it to work by changing `(magit-modified-files t)` to `magit-tracked-files` in the patch. 

Perhaps that's less efficient. Not sure how much of a problem that would be.

**Comment by dgutov** [comment]
> I now get a setq: Symbol’s function definition is void: magit-modified-files

Okay. :man_shrugging:  @tarsius, please update the wiki.

@afine Is `magit-unstaged-files` function still available?

**Comment by afine** [comment]
Looks like it...
```
magit-unstaged-files is a compiled Lisp function in ‘magit-git.el’.

(magit-unstaged-files &optional NOMODULES FILES)

Not documented.
```

**Comment by dgutov** [comment]
Very good.

Does it work okay if you replace both uses of `magit-modified-files` with `magit-unstaged-files`. Apparently the function has just been renamed.

**Comment by afine** [comment]
that appears to work as well

**Comment by dgutov** [comment]
Thanks for verifying.

I've pushed it now. Please let me know if you see further problems.

**Comment by tarsius** [comment]
Thanks!
