### ISSUE TITLE
Cannot input GnuPG passphrase through pinentry over TRAMP

### ISSUE THREAD

**Issue by Apteryks** [magit/magit#4076]
(1) behavior you expected

When using Magit over TRAMP, I'd expect to be able to input my GnuPG passphrase when needed, for example for signing commits.

(2) what behavior you observed

Doing a fetch on an authenticated repository hangs, and I can see in the magit-process buffer ($ key) that it is querying for my passphrase there:

```
─────────────────────────────────────────────────────┐│ Please enter the passphrase to unlock the OpenPGP secret key:  ││ [...]
```

There's no way that I can provide the passphrase there, as input doesn't seem to be read, and keybindings are enabled.

(3) and how we can reproduce the issue.

This is the tricky part.  The following details the *remote* relevant GnuPG configuration. I'm using GnuPG 2.2.19 on the remote, with the config:
```
# PIN entry program
enable-ssh-support
allow-emacs-pinentry
```
I have the regular pinentry package installed (1.1.0), and launch my gpg-agent service with:

```
 gpg-agent --daemon --pinentry-program /abs/path/to/my/pinentry
```
And finally in my `~/.bashrc` I have the following config to use gpg-agent as an ssh-agent as well as redirecting the pinentry to the incoming SSH session:

``` bash
# Make gpg-agent available for any shell invocation.
export GPG_TTY=$(tty)

# We use gpg-agent instead of ssh-agent.
unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
    export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi

# Allow pinentry to display even for remote SSH connections.
echo UPDATESTARTUPTTY | gpg-connect-agent > /dev/null
```

    M-x magit-version RET

Magit , Git 2.25.2, Emacs 26.3, gnu/linux

The same occurs when launching emacs with the Q switch and loading the magit library manually.

**Comment by Apteryks** [comment]
It seems to me that there needs to be a new process filter to be used in `magit-process-filter', that would detect the pinentry prompt and forward the user's passphrase to the process.

**Comment by Apteryks** [comment]
I added this to my ~/.emacs:
``` lisp
(setq-default magit-process-password-prompt-regexps
  '("^\\(Enter \\)?[Pp]assphrase\\( for \\(RSA \\)?key '.*'\\)?: ?$"
    ;; Match-group 99 is used to identify the "user@host" part.
    "^\\(Enter \\)?[Pp]assword\\( for '\\(https?://\\)?\\(?99:.*\\)'\\)?: ?$"
    ;; Pinentry Curses box in the terminal when used with GnuPG
    "Please enter the passphrase for the ssh key"
    "^.*'s password: ?$"
    "^Yubikey for .*: ?$"
    "^Enter PIN for .*: ?$"))
```
The new entry is "Please enter the passphrase for the ssh key".  It seems to work! I'll refine the regexp and send a patch.

**Comment by Apteryks** [comment]
Providing more information through the prompt such as the MD5 of the SSH key or username@hostname tuple is not possible with the current code, but still, I think the simple proposed patch is a good improvement of the situation.

**Comment by tarsius** [comment]
Try if `(setenv "PINENTRY_USER_DATA" "USE_CURSES=1")` helps.

https://superuser.com/questions/1108170/gnupg-pinentry-depending-on-gui-presence/1354971#1354971

**Comment by Apteryks** [comment]
@tarsius Thanks for the idea! First I defined this:
```
(setq-default magit-git-environment
              (cons "PINENTRY_USER_DATA=USER_CURSES=0" magit-git-environment))
``` 
in my .emacs file, so that this environment variable would get set in the TRAMP process started by magit-git-process (I followed the source to get this insight). Sadly, it didn't help.

I then used the more sure way by setting `export PINENTRY_USER_DATA="USE_CURSES=0"` in my remote machine's ~/.bashrc.  That also didn't help.

Thinking about it, it seems Curses is not even used. The pinentry-tty prompt is what I'm seeing. It looks like this: https://user-images.githubusercontent.com/19255313/47235564-b7370380-d3d9-11e8-9c42-a01d8cffb1b4.png. This is the "dumbest" pinentry mode available.

I'm now thinking the crux of the issue is that the git (remote) process is not treated equally by Magit when started with TRAMP, for the lack of a synchronous mean to keep stdin and stdout attached to the process (see: https://github.com/magit/magit/blob/master/lisp/magit-process.el#L441). So the remote process is started, and Magit waits for it to finish, with no mean for sending a passphrase or anything to the process.

Is my understanding correct?

**Comment by tarsius** [comment]
I don't actually remember how that works.

**Comment by tarsius** [comment]
Please have a look at #4111. Does that help?

**Comment by ning-y** [comment]
I have the same issue using `--gpg-sign` on a remote repository. On the remote machine, I am able to create a GPG-signed commit via command line git. After a failed attempt at creating a signed commit in magit, if I view the log using `$`, I can see a brief glimpse of the GPG pinentry interface (the same one that was shared in the [screenshot above](https://user-images.githubusercontent.com/19255313/47235564-b7370380-d3d9-11e8-9c42-a01d8cffb1b4.png)).

- Setting `magit-process-password-prompt-regexps` as defined in this thread did not solve the issue
- My default TRAMP method is already `'ssh` (re #4111)

Just wanted to add my account to this bug. Honestly, it seems the proportion of magit users who actually create signed commits over TRAMP is small, and magit is easily still the best git interface even if I have to switch over to a terminal to create signed commits; so I understand if this is not a top-priority issue.

**Comment by robert-zaremba** [comment]
I made it working with https://elpa.gnu.org/packages/pinentry.html
In my `gpg-agent.conf` I have:

```
pinentry-program /usr/bin/pinentry-tty
allow-loopback-entry
allow-emacs-pinentry
```

This will:
* use pinentry-tty when initiating the request from CLI (eg by calling `git commit ...` directly)
* use emacs prompt if initiating the request from emacs

**But** if possible, magit should use `allow-loopback-entry` mechanism, which is for example correctly used by `(epa-sign-file)`. It seams `magit` could do the same.

**Comment by trevarj** [comment]
For anyone looking how to get pinentry in the minibuffer on Emacs 29:

`~/.gnupg/gpg.conf`
```
pinentry-mode loopback
```
`~/.gnupg/gpg-agent.conf`
```
pinentry-program /usr/bin/pinentry-tty
allow-loopback-pinentry
```

`init.el`
```elisp
(setq epg-pinentry-mode 'loopback)
```

**Comment by farblos** [comment]
Thanks @trevarj for necroposting ... this issue still comes up rather high on DDG.

A minor nit: I think setting `epg-pinentry-mode` is not strictly required for entering PINs during commit/tag signing - it seems the prompt handling is done by magit, and not EPG/EPA in that case.  (However, if you want to use GnuPG to also en/decrypt files on the fly in Emacs, you do need `epg-pinentry-mode` so it definitely makes sense setting that.)

And a follow-up question: What to do if I want to use loopback pinentry *only* when signing commits from Magit, but not from plain Git?  The most reasonable idea I came up with was to tweak `magit-git-environment` so that it uses a `gpg` wrapper which adds command line option `--pinentry-mode loopback` to the `gpg --sign` calls done from `git`.  Bah.

**Comment by farblos** [comment]
See also https://github.com/magit/magit/discussions/5096.
