### ISSUE TITLE
magit/transient is marking windows no-other-window and leaving them.

### ISSUE THREAD

**Issue by EricGebhart** [magit/magit#4082]
Magit 20200318.1224, Git 2.25.1, Emacs 26.3, gnu/linux

## The problem
    I would expect windmove.el to continue working after using magit.

## The cause
    Windows are marked as _no-other-window_ after using magit.

 ## to reproduce

* Create a session with a few windows in a frame, use windmove.el to
move around in them.  
* Use magit. Commit something, maybe push something.
* Quit magit.
* Try using the windmove.el keys to move around.  shift-arrows

I use this to create my initial windows.
```
(defun main-window ()
    (interactive)
    (balance-windows)
    (split-window-horizontally)
    (split-window-horizontally)
    (split-window-below))
```
## 3 unsavory solutions so far.

* Modify _windmove-find-other-window_ in windmove.el to send `t` to
_window-in-direction_ so that ignored windows will be returned.
* Modify _transient-show_ in transient.el to not mark windows with 
_no-window-ignore_
* Always open magit in a separate frame so it won't mess with windows
it doesn't own.

I have only been sneaking up on this problem to understand it. I do not
know why transient is marking windows it doesn't own, or if it does why
magit or transient doesn't unmark them when it's done.  There are no
errors or messages indicating anything.

I also do not know why transient is marking them in the first place. 
Any one of these solutions seems to work without side effects but
not knowing the reasoning behind marking the windows in the first 
place I can only guess at what possible problems might appear with
either of these first two changes.   The first change is just a band-aide
and is clearly not the right solution.  The second solution I cannot say.

The third solution is just a nice way to encapsulate the bad behavior 
so no one gets hurt.

### The first solution. 

```
(defun windmove-find-other-window (dir &optional arg window)
  "Return the window object in direction DIR.
DIR, ARG, and WINDOW are handled as by `windmove-other-window-loc'."
  (window-in-direction
   (cond
    ((eq dir 'up) 'above)
    ((eq dir 'down) 'below)
    (t dir))
   window t arg windmove-wrap-around t))
```
### The second solution

```
(defun transient--show ()
  (transient--timer-cancel)
  (setq transient--showp t)
  (let ((buf (get-buffer-create transient--buffer-name))
        (focus nil))
    (unless (window-live-p transient--window)
      (setq transient--window
            (display-buffer buf transient-display-buffer-action)))
    (with-selected-window transient--window
      (when transient-enable-popup-navigation
        (setq focus (button-get (point) 'command)))
      (erase-buffer)
      (set-window-hscroll transient--window 0)
      (set-window-dedicated-p transient--window t)
      ;;(set-window-parameter transient--window 'no-other-window t)
      (setq window-size-fixed t)
      (when (bound-and-true-p tab-line-format)
        (setq tab-line-format nil))
      (setq mode-line-format (if (eq transient-mode-line-format 'line)
                                 nil
                               transient-mode-line-format))
      (setq mode-line-buffer-identification
            (symbol-name (oref transient--prefix command)))
      (if transient-enable-popup-navigation
          (setq-local cursor-in-non-selected-windows 'box)
        (setq cursor-type nil))
      (setq display-line-numbers nil)
      (setq show-trailing-whitespace nil)
      (transient--insert-groups)
      (when (or transient--helpp transient--editp)
        (transient--insert-help))
      (when (and (eq transient-mode-line-format 'line)
                 window-system)
        (insert (propertize "__" 'face 'transient-separator
                            'display '(space :height (1))))
        (insert (propertize "\n" 'face 'transient-separator 'line-height t)))
      (let ((window-resize-pixelwise t)
            (window-size-fixed nil))
        (fit-window-to-buffer nil nil 1))
      (goto-char (point-min))
      (when transient-force-fixed-pitch
        (transient--force-fixed-pitch))
      (when transient-enable-popup-navigation
        (transient--goto-button focus)))))
```

### The third solution

```
(defun magit-other-frame ()
  "Start Magit status in another frame."
  (interactive)
  (if (magit-inside-gitdir-p)
      (progn (select-frame (make-frame-command))
             (magit-status)
             (delete-other-windows))))

(global-set-key (kbd "C-c g") 'magit-other-frame)
(define-key magit-mode-map (kbd "q") 'delete-frame)

```

**Comment by tarsius** [comment]
`transient` by default creates a new window to display the transient popup buffer. Have you customized e.g. `transient-display-buffer-action` causing some existing window to be reused?

**Comment by tarsius** [comment]
`transient` deletes the window that it used to display the popup. It's the only window where it sets `no-other-window`. So once the transient popup is exited that should not have an effect anymore.

**Comment by tarsius** [comment]
Please help us narrow the issue down by trying to reproduce it without your personal configuration by starting from `emacs -Q ...`. The manual [documents](https://magit.vc/manual/magit/Debugging-Tools.html) the tools that we provide to make that easier.

<sub>This is a [canned response](https://help.github.com/en/github/writing-on-github/working-with-saved-replies); it may not apply 100% in this case.</sub>

**Comment by EricGebhart** [comment]
I have started from nothing and slowly added back my settings.  I have
traced it to an interaction with _popwin.el_  which I was using to try to
keep magit windows under control.  These are the settings which cause havoc.  They did work at one time. But it has been a while.
I haven't gotten much further than this.  It does seem that windows are being reused.  I'll have to dig deeper tomorrow.

```
(setq popwin:special-display-config
      '(("*Help*"  :height 30)
        ("*Completions*" :noselect t)
        ("*Messages*" :noselect t :height 30)
        ("*Apropos*" :noselect t :height 30)
        ("*compilation*" :noselect t)
        ("*Backtrace*" :height 30)
        ("*Messages*" :height 30)
        ("*Occur*" :noselect t)
        ("*Ido Completions*" :noselect t :height 30)
        ("*magit-commit*" :noselect t :height 40 :width 80 :stick t)
        ("*magit-diff*" :noselect t :height 40 :width 80)
        ("*magit-edit-log*" :noselect t :height 15 :width 80)
        ("\\*ansi-term\\*.*" :regexp t :height 30)
        ("*shell*" :height 30)
        (".*overtone.log" :regexp t :height 30)
        ("*gists*" :height 30)
        ("*sldb.*":regexp t :height 30)
        ("*cider-error*" :height 30 :stick t)
        ("*cider-doc*" :height 30 :stick t)
        ("*cider-src*" :height 30 :stick t)
        ("*cider-result*" :height 30 :stick t)
        ("*cider-macroexpansion*" :height 30 :stick t)
        ("*Kill Ring*" :height 30)
        ("*Compile-Log*" :height 30 :stick t)
        ("*git-gutter:diff*" :height 30 :stick t)))
```

**Comment by tarsius** [comment]
Related https://github.com/magit/transient/issues/34.

**Comment by EricGebhart** [comment]
Ha, yes.  After digging around in the code for a while, it seems pretty obvious to me that popwin reached it's end of life in emacs 24.

I hacked it a bit and got it to ignore some windows but it doesn't seem
worth it to fix.  If someone wants it then it should be brought up to date to work with the current display-buffer-alist etc.

At this point display buffer alist can do most of what anyone ever wanted with popwin as far as I can tell.  So there doesn't seem to
be that much use for it.  Except now I've got to make a display-buffer-alist that will help my windows behave more nicely.

**Comment by EricGebhart** [comment]
BTW, here is a better function for opening magit in a separate frame.
Although perhaps it would work just as well in a display-buffer-alist entry.
```
;; package --- Summary
;;; Commentary:

;; provides functionality to open magit in another frame.

;;; Code:
(require 'magit-git)

(defun magit-other-frame ()
  "Start Magit status in another frame."
  (interactive)
  (if (magit-toplevel)
      (progn
        (select-frame (make-frame-command))
        (magit-status-setup-buffer)
        (delete-other-windows))
    (magit--not-inside-repository-error)))

(provide 'git-frame)
;;; git-frame.el ends here
```

**Comment by EricGebhart** [comment]
Also, I noticed that, at least in my opinion, the transient buffer name
is mispelled  as " *transient" instead of "*transient*".  The space at
the beginning may not make for the easiest day if someone were trying to reference that buffer somewhere.

**Comment by tarsius** [comment]
> I hacked it a bit and got it to ignore some windows but it doesn't seem worth it to fix.

If that's a somewhat simple patch it might still be worth posting. For people who want to slowly transition away from `popwin`.

> The space at the beginning may not make for the easiest day if someone were trying to reference that buffer somewhere.

This is a buffer that users should never access manually and the convention is to prefix the names of such buffers with a space exactly *because* it makes it harder to access that buffer.

**Comment by kyleam** [comment]
> BTW, here is a better function for opening magit in a separate frame.
>  Although perhaps it would work just as well in a display-buffer-alist entry.

Something like this should work:

```elisp
(add-to-list 'display-buffer-alist
             '("magit: .*" (display-buffer-pop-up-frame)))
```

Alternatively, you could do this:

```elisp
(defun my/magit-display-buffer (buffer)
  (if (eq (with-current-buffer buffer major-mode)
          'magit-status-mode)
      (display-buffer-pop-up-frame buffer nil)
    (magit-display-buffer-traditional buffer)))

(setq magit-display-buffer-function #'my/magit-display-buffer)
```

**Comment by EricGebhart** [comment]
The patch was not that simple, and it still didn't work 100% so I don't
think it would be worth it to post.  Perhaps a better thing to post would be a simple display-buffer-alist which has some examples of managing magit windows.   I may come up with something, but I'm unsure of my time frame.  Although I do seem to have extra time in front of the computer for the coming months.

It is also worth noting that if popping Magit into another frame It might be desirable to use this mapping for quit in order to close the frame when done.

```
(define-key magit-mode-map (kbd "q") 'delete-frame)
```

**Comment by EricGebhart** [comment]
I think it's reasonable to close this.  I'm actually pretty happy with popping xmonad in another frame. I use Xmonad so it's seamless.  I don't know that some display-buffer-alist examples are really needed.  Maybe just as a suggestion for managing windows.

**Comment by tarsius** [comment]
I've added a note to https://github.com/magit/transient/wiki/FAQ.
