### ISSUE TITLE
Discard cmd is not working

### ISSUE THREAD

**Issue by michengit** [magit/magit#4083]
Please explain
    (1) what behavior you expected
The file will be reverted and not shown at unstaged
    (2) what behavior you observed
The file is still shown at unstaged and not be discarded
    (3) and how we can reproduce the issue.
Run discard cmd (k) on unstaged file

Please include a backtrace in your report.  In most cases doing:

  1 Debugger entered--Lisp error: (error "Selecting deleted buffer")
  2   read-from-minibuffer(#("Discard unstaged changes in xfile? (y or n) " 28 37 (fontified nil)) nil (keymap (keymap (escape . abort-recursive-edit) (rem$
  3   y-or-n-p(#("Discard unstaged changes in xfile? " 28 37 (fontified nil)))
  4   magit-y-or-n-p(#("Discard unstaged changes in xfile? " 28 37 (fontified nil)) discard)
  5   magit-confirm(discard "Discard unstaged changes in %s" "Discard unstaged changes in %i files" nil (#("xfile" 0 9 (fontified nil))))
  6   magit-confirm-files(discard (#("xfile" 0 9 (fontified nil))) "Discard unstaged changes in")
  7   magit-discard-files--discard((#<magit-file-section "xfile" [file unstaged status] nil-nil>) nil)
  8   magit-discard-files((#<magit-file-section "xfile" [file unstaged status] nil-nil>))
  9   magit-discard-file(#<magit-file-section "xfile" [file unstaged status] nil-nil>)
 10   magit-discard()
 11   funcall-interactively(magit-discard)
 12   call-interactively(magit-discard nil nil)
 13   command-execute(magit-discard)

    M-x magit-version RET
Magit 20200401.2225, Git 2.15.1, Emacs 27.0.90, gnu/linux

**Comment by kyleam** [comment]
Without more information, I think this one's going to be hard for others to make any traction on.  `magit-discard` is not failing across the board.

Can you trigger the failure with `emacs -Q` and just Magit loaded?

**Comment by michengit** [comment]
Find the root cause and it is due to some buffer deleting on the cfg. Many thanks.
