### ISSUE TITLE
Not able to pushRemote, after setting that... [No match]

### ISSUE THREAD

**Issue by dadinn** [magit/magit#4086]
I am using Emacs version: `GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-09-23, modified by Debian`

I am using Magit version: `2.90.1`

I am trying to call `magit-push-current-to-pushremote` using the key binding `P p`, which says in the magit popup menu: "**pushRemote**, after setting that"

The prompt asks for an input: "Set `branch.release/v8.pushRemote' and push there:"

I try to give the input value `origin/release/v8`. To which the prompt complains `[No match]`

I have done similar pushes before, and always used the same patterns to set the pushRemote settings, and it used to work.

Therefore I assume this is a bug/regression.

**Comment by dadinn** [comment]
There is a workaround though, which is to use `magit-push-current` with key-binding `P e` (i.e. to push "elsewhere"), but this requires me to type the destination (e.g. `origin/release/v8`) every time.

**Comment by tarsius** [comment]
> I try to give the input value `origin/release/v8`. To which the prompt complains `[No match]`

You have to give a *remote* not a remote tracking branch as you have done. All the available options such as `origin` are given as completion candidates.

> I have done similar pushes before, and always used the same patterns to set the pushRemote settings, and it used to work.

It never worked like that. `branch.<name>.pushRemote` is not a Magit invention but a Git concept and it always referred to a remote, not a branch. The remote branch will always have the same name as the local branch.

**Comment by dadinn** [comment]
Actually you are right. 

Not sure where I took those paths from, but once typed, it blocks the completion from offering the shorter `origin`.

 I am using `ido`, not sure if it is the same with other engines too.
