### ISSUE TITLE
Handle password prompts in Git process

### ISSUE THREAD

**Issue by matthewbauer** [magit/magit#4088]
Password prompts in magit-process are not handled properly. This happens when `sudo` is needed for sending data to a repo.

My setup works like this:

- run `git remote add origin /etc`
- set `git config remote.origin.receivepack 'sudo git-receive-pack'` in the sending repo
- run `git push`
- observe sudo timeout in magit-process looking like this:

```
Pushing to /etc
[sudo] password for XXX: 
sudo: timed out reading password
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

magit-version:

```
    Magit 20200108.532, Git 2.23.1, Emacs 26.3, gnu/linux
```

**Comment by matthewbauer** [comment]
I think this may be just as simple as adding another entry to magit-process-password-prompt-regexp.

**Comment by matthewbauer** [comment]
Done in https://github.com/magit/magit/pull/4089

**Comment by tarsius** [comment]
See #4089.
