### ISSUE TITLE
Automate "reword post-processing" after successful magit-rebase-interactive?

### ISSUE THREAD

**Issue by erikmd** [magit/magit#4101]
Dear **magit** maintainers, thanks for developing this very nice Git porcelain!

As regular users of magit and GItHub, @proux01 and I noticed the following issue:

when pushing a feature branch to GitHub after an interactive rebase (e.g. when working on a Pull Request that has been reviewed, etc.), the order of commits displayed by GItHub do not respect the "topological structure" of the branch: even if the branch at stake is "linear", GitHub sorts the commits only relying on dates, using a standard lexicographic order: sorting first by commit dates, then by author dates. But it happens that after a `git rebase -i`, **all rebased commits do have the same commit date**, which thereby results in an awkward order that hinders a bit the subsequent review… 

For example, after rebasing the last 3 commits of a branch, I get:

<pre>
$ git log HEAD~4.. --format=$'commit %h\nAuthor Date: %ai\nCommit Date: %ci\n'

commit 51f4dbc
Author Date: 2020-05-01 13:49:37 +0200
<b>Commit Date: 2020-05-01 14:47:16 +0200</b>

commit d30dcbd
Author Date: 2020-05-01 00:32:47 +0200
<b>Commit Date: 2020-05-01 14:47:16 +0200</b>

commit b94f293
Author Date: 2020-05-01 00:39:48 +0200
<b>Commit Date: 2020-05-01 14:47:16 +0200</b>

commit 7303c58
Author Date: 2020-04-28 20:10:39 +0200
Commit Date: 2020-04-28 20:10:39 +0200
</pre>

So even if the underlying cause of this issue is very clear, it appears to be quite distracting in practice (see e.g. [that SO question](https://stackoverflow.com/q/54989224/9164010))

Actually, @proux01 and I are systematically finding ourselves applying the following workaround:
* after the rebase, **do another `rebase -i` with magit**, starting from the first rebased commit
* **select `reword` for each commit** and apply the changes
* keep all commit messages and **wait for 1 or 2 seconds between each step** 

FYI here is a transcript of the corresponding session thanks to `(view-lossage)`:

```
 C-x g [magit-status]
 l [magit-log]
 l [magit-log-current]
 <down> [magit-next-line]
 <down> [magit-next-line]
 r [magit-rebase]
 i [magit-rebase-interactive]
 r [git-rebase-reword]
 r [git-rebase-reword]
 r [git-rebase-reword]
 C-c C-c [with-editor-finish]
 C-c C-c [with-editor-finish]

 C-c C-c [with-editor-finish]

 C-c C-c [with-editor-finish]
```

As a result, we get some different commit dates (with at least 1" of time difference) and the issue does not occur anymore.

But if this workaround could be automated in Magit, that would be really great! :+1:

so would you agree to develop a new command in `magit-rebase`, or a new option to `magit-rebase-interactive`, in order to be able to perform that "reword post-processing" from the base commit automatically? (e.g. waiting for 1.1" or so between each reword)

**Comment by kyleam** [comment]
[ Sorry if I'm missing something; I'm scanning this quickly and won't be able to read it closely until tonight, but... ]

`magit-reshelve-since` could help you here.  I assume that this GitHub quirk is the primary reason it exists.

**Comment by erikmd** [comment]
Thanks @kyleam, that's helpful indeed!

For the record:

```
magit-reshelve-since is an interactive autoloaded compiled Lisp
function in ‘magit-extras.el’.

(magit-reshelve-since REV)

Change the author and committer dates of the commits since REV.

Ask the user for the first reachable commit whose dates should
be changed.  Then read the new date for that commit.  The initial
minibuffer input and the previous history element offer good
values.  The next commit will be created one minute later and so
on.

This command is only intended for interactive use and should only
be used on highly rearranged and unpublished history.
```

so although it does not behave exactly as the feature I had outlined, `M-x magit-reshelve-since` is very OK for my use case, thanks!

I don't close the issue immediately though, as I believe this feature might be slightly extended:

* regarding the GItHub quirk, changing only the commit date would be enough :-) so maybe one might add an option to `(magit-resherve-since)` to change both dates like the current implem., or preserve the author date (which might be a useful information if e.g. the author of that commit is not the committer) − what do you think?  (Cc @proux01)
* then if you think the previous item makes sense, maybe the least change, i.e. only the commit dates, could be the default behavior(?)
* finally as this feature is really a plus, would you be in favor of adding a related keybinding in magit? e.g., in `(magit-rebase)`, <kbd>C-x g r r</kbd>…

**Comment by tarsius** [comment]
> I assume that this GitHub quirk is the primary reason it exists.

No I created it because I sometimes do 10% of the work and commit that, and then months later I do the remaining 90% and don't feel anyone needs to know that I started work so long ago. But it's nice that it works here too.

> regarding the GItHub quirk

That's not a "quirk". It is a deeply embarrassing bug that they should feel ashamed about. They had more than a decade to fix it and they still haven't gotten around to it. If this were an foss project with a single maintainer, then I would suggest you file a bug report and a week later it would probably be fixed, but since you are dealing with a billion dollar company that would be a complete waste of time.

> changing only the commit date would be enough

Since this feature wasn't *designed* for this use-case, that never occurred to me.

> then if you think the previous item makes sense, maybe the least change, i.e. only the commit dates, could be the default behavior(?)

That would defeat the actual design goal of effectively lying about history.

> finally as this feature is really a plus, would you be in favor of adding a related keybinding in magit? 

Since this makes it so easy to lie about history, we might not want too many people to know about it :stuck_out_tongue_closed_eyes:

**Comment by tarsius** [comment]
I'd be open to a prefix argument to make it only change the committer dates.

**Comment by erikmd** [comment]
Hi @tarsius, thanks a lot for your feedback :)

> I'd be open to a prefix argument to make it only change the committer dates.

OK! that would be very fine. Do you plan to do it?

**Comment by tarsius** [comment]
Due to how some internals work it would be surprisingly hard to do that actually. I think one could have to add an additional argument to `magit-log-select` to pass along the prefix argument. Would a variable do as well?

**Comment by erikmd** [comment]
> I think one could have to add an additional argument to magit-log-select to pass along the prefix argument.

IINM you suggest to:

* add a prefix argument to select the weak version (<kbd>C-u M-x magit-reshelve-since RET</kbd>)
* add an optional argument to `magit-log-select`

> Would a variable do as well?

If you think of evaluating `(setq some-var t)` before <kbd>M-x magit-reshelve-since RET</kbd>, that wouldn't be very convenient I guess(?)

**Comment by proux01** [comment]
> Would a variable do as well?

It seems that nobody needs to constantly switch between the two behaviors so that looks fine.

**Comment by erikmd** [comment]
Great! thank you @tarsius

**Comment by tarsius** [comment]
You're welcome!
