### ISSUE TITLE
Partial Clone and Sparse Checkout

### ISSUE THREAD

**Issue by aseltmann** [magit/magit#4102]
I've just taken a look at options for handling large files with git/magit. Of course, git-annex (with magit-annex) or git-lfs (with magit-lfs) come to mind. Then I read that the main git project introduced Partial Clone ([1]) at some point, which e.g. Gitlab recommends now for large files ([2],[3]). 

It seems for magit to be able to support these workflows, some keybindings and menu options would have to be added, e.g. for cloning the option to support `clone --filter` or the command `git sparse-checkout`.

Is there any plan to support this?

[1]: https://git-scm.com/docs/partial-clone
[2]: https://about.gitlab.com/blog/2020/03/13/partial-clone-for-massive-repositories/
[3]: https://docs.gitlab.com/ee/topics/git/partial_clone.html

**Comment by kyleam** [comment]
I don't recall seeing either the partial clone or sparse-checkout features mentioned on the tracker yet, but I'd say those are both features that should eventually be supported, even if hidden away by default.  

They've been on my radar.  I think it'd probably be fine to add `--filter` to clone now.  For sparse-checkout, my impression is that it's a bit of a moving target right now in terms of the interface, so it might make sense to see how things settle before trying anything on Magit's end.

**Comment by tarsius** [comment]
I've just skimmed over https://github.blog/2020-01-17-bring-your-monorepo-down-to-size-with-sparse-checkout/ and https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/. Good stuff. But I think I have to remove the `good first issue` label. :grin:

**Comment by kyleam** [comment]
@tarsius I plan to take a look at this within the next few months (but of course feel free to wave me off :>).

**Comment by tarsius** [comment]
I've just assigned four issues to myself too. I hope we can address all remaining reported bugs within the next 1-2 months. I am not particularly stoked dealing with the other two remaining bugs and would very much appreciate it if you could look into those. No obligation, just mentioning it.
