### ISSUE TITLE
oset is an obsolete macro

### ISSUE THREAD

**Issue by manuel-uberti** [magit/magit#4105]
Since this is not a bug breaking my usual Magit usage, I thought of opening a feature request instead.

I am using latest Magit (where "latest" means commit `9a388a61d95761b9c748dc186602ba7c691d580f`) on:

```
GNU Emacs 28.0.50

Master branch commit:
     Hash: 106936415d2892fc373842b3aedd805096fc9e0e
  Message: Simplify by using attribute.h macros

Configured with the following options:
  --host=x86_64-debian-linux-gnu
  --with-modules
  --with-imagemagick
  --with-harfbuzz
  host_alias=x86_64-debian-linux-gnu

Running on:
  Ubuntu 20.04 LTS
  GNOME Shell 3.36.1 (x11)
  GTK+ Version 3.24.18, cairo version 1.16.0
```

When I open `magit-status` I get this warning message:
```
‘oset’ is an obsolete macro (as of 28.1); use (setf (oref ..) ..)
```
Without breaking the usage for other people on a different Emacs version, would it be possible to adopt the suggested alternative in order to avoid the deprecation warning?

**Comment by tarsius** [comment]
[I am trying to get it un-deprecated.](https://lists.gnu.org/archive/html/emacs-devel/2020-05/msg00674.html)

**Comment by basil-conto** [comment]
It has now been un-deprecated:

https://lists.gnu.org/archive/html/emacs-devel/2020-06/msg00099.html
https://lists.gnu.org/archive/html/emacs-devel/2020-06/msg00247.html

**Comment by manuel-uberti** [comment]
Fantastic. Thanks a lot.

**Comment by tarsius** [comment]
Great! Many thanks!
