### ISSUE TITLE
"Cannot determine Magit's version" message on startup

### ISSUE THREAD

**Issue by chasecaleb** [magit/magit#4106]
I just updated magit from `68b5a13fa1b6b122d4a2547b8c415aadff83d8ca` to the current head of master (`9a388a61d95761b9c748dc186602ba7c691d580f`) and now see this in `*Messages*` on startup:
> Cannot determine Magit’s version (error "/home/caleb/.emacs.d/lib/magit/lisp/magit.el" repo static elpa dirname)

I didn't dig very deeply into what's going on, but the value of `magit-version` variable is `'error'`. I'm using borg (which I love by the way, so thanks!) and use-package for my config. The magit-related portion is:

```emacs-lisp
(use-package magit
  :config
  (setq magit-diff-refine-hunk 'all)
  ;; keep-foreground is a bit hard on the eyes (with spacemarks-dark).
  (setq magit-diff-unmarked-lines-keep-foreground nil)
  (setq magit-branch-prefer-remote-upstream '("master"))
  (setq magit-branch-adjust-remote-upstream-alist '(("origin/master" "master")))
  (setq magit-module-sections-nested nil)
  (setq magit-clone-set-remote.pushDefault t))

(use-package magit-mode
  :config
  (setq magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

(use-package magit-ediff
  :config
  (setq magit-ediff-dwim-show-on-hunks t))

(use-package magit-wip
  :diminish
  :config
  (magit-wip-mode))
```

However I didn't touch my config between updates (and I made sure to rerun `borg build`), so I think it is a code regression and not config related.

**Comment by tarsius** [comment]
Please either step through `magit-version` or add some debug statements to figure out what is going on. When using `borg`, then the version is supposed to come from `(magit-git-string "describe" "--tags" "--dirty")`. Try to figure out why that isn't called by inspecting the tests on the way there.

**Comment by chasecaleb** [comment]
Alright, I investigated closer and I'll close this issue since it looks like it's working as intended - my setup is just an extreme edge case. Sorry about that and thanks for pointing me in the right direction.

I have no idea why I thought I wasn't seeing that error before, but I just reverted back to `68b5a13fa1b6b122d4a2547b8c415aadff83d8ca` and it's present there too so I must have been blind. I spent a little time debugging `magit-version` and discovered the issue is that I don't have the `.git` dir present. I build and install an Arch Linux package from my emacs source repo, and my package excludes dot directories like `.git`. So of course it fails because `magit-version` can't find the non-existent `.git` directory.

Since it looks like `magit-version` is only used for informational output on startup I'm fine with it working the way it does currently.

**Comment by tarsius** [comment]
> I build and install an Arch Linux package from my emacs source repo, and my package excludes dot directories like `.git`.

What do you do instead. On the command line you could set `$GIT_DIR`, but how does `magit` know in which repository it is?

**Comment by chasecaleb** [comment]
Here's my workflow for modifying my Emacs config, hopefully this makes more sense:
1. I keep [my source repo](https://gitlab.com/chasecaleb/emacs.d/) checked out at `~/code/emacs.d`. It's a normal git project so it has `.git`.
1. I modify my config in the source repo and try it out interactively via `eval-last-sexp`, etc.
1. Once I'm happy with a change, I commit and push it to Gitlab.
1. Gitlab CI triggers a build in my main project, [arch-as-code](https://gitlab.com/chasecaleb/arch-as-code/), which creates an Arch Linux system package for my Emacs config (including dependencies) and pushes it to my repo in AWS S3.
    - [This is the PKGBUILD](https://gitlab.com/chasecaleb/arch-as-code/-/blob/master/packages/chasecaleb-emacs/PKGBUILD) for my Emacs package. It checks out my Emacs source repo, runs `make bootstrap-borg` and `make bootstrap`, then copies files to be packaged. You'll see in `package()` this it excludes files starting with `.`, such as `.git`.
    - You can download a recent build here: https://gitlab.com/chasecaleb/arch-as-code/-/jobs/539910377/artifacts/file/repo/chasecaleb-emacs-3:r32.20200506.011707.0ead8ee-1-any.pkg.tar.xz
1. I run `pacman -Syu` (system package manager) to update. This puts my config in `/etc/emacs`, which is not user-writable and does not contain `.git`. So I have `/etc/emacs/init.el`, `/etc/emacs/lib/borg/borg.el`, etc. 
1. I have a symlink from `~/.emacs.d` -> `/etc/emacs`, so I just restart Emacs to use the new build of my config.

If you're familiar with infrastructure-as-code from the dev ops world, that's why I'm doing it like this. I can wipe my laptop, run an install script, and have my whole system installed and configured within a few minutes. You're welcome to try it out in a VM if you're curious or bored. It's scripted so it's easy to do - instructions are in the [arch-as-code readme](https://gitlab.com/chasecaleb/arch-as-code).

**Anyways, TLDR summary:** I have two copies of my Emacs config. One is the source, checked out from Gitlab, that I make changes to. The other is a read-only, `.git`-less copy that is symlinked to `~/.emacs.d` for Emacs to load.

**Comment by tarsius** [comment]
Thanks for the reply, I think I understand. Sounds interesting but... I don't think I am gonna do that myself. :grin: Dabbling with Guix a bit though.
