### ISSUE TITLE
magit blocks the UI for ~4s on find-file, when browsing files that aren't in git, but are on a slow filesystem

### ISSUE THREAD

**Issue by tomfitzhenry** [magit/magit#4108]
>    M-x magit-version RET

2.90.1

# Steps to reproduce

1. Mount a slow file system (e.g. a network file system), which contains no git repositories.

2. Enable magit, and open a non-git file on that slow file system:
```shell
$ emacs -q --eval "$(cat << EOF
(progn
  (setq vc-handled-backends nil) ;; disable vc.el because that has the same problem.
  (require 'magit)
  (find-file "/mnt/nfs/a/long/path/in/some/non-git/directories/foo.c") ; warm up
  (pp
   (benchmark-run 1
     (find-file "/mnt/nfs/a/long/path/in/some/non-git/directories/bar.c"))))
EOF
)"
```

# Expected
0.005s (which is the time I get if I don't load magit)

# Actual
3.9s.

During this 3.9s, the UI is blocked.

# What's going on?

When magit loads, it enables modes that add find-file-hooks:
* magit-edit-branch*description-check-buffers
* global-magit-file-mode-check-buffers
* magit-auto-revert-mode-check-buffers

Each of those hooks will perform some action if the file is in a git repository. This file isn't in a git repository, so no action is taken. This is reasonable behaviour. However, checking whether the file is in a git repository is expensive: it'd involve traversing up for the file hierarchy `stat`'ing for `.git`.

Since each of the three hooks perform their own git status, for a path containing 10 directories (common for my workflow), that'd 30 stats, which against a slow filesystem is slow!

# Workarounds/fixes

## Advise the git functions to exit early if in /mnt/nfs

```elisp
(defun my/nfs-early-exit (orig-fun &rest args)
  (if (string-prefix-p "/mnt/nfs/" (buffer-file-name))
      (progn (message "my/nfs-early-exit overrode.") nil)
    (apply orig-fun args)))
(advice-add 'magit-toplevel :around #'my/nfs-early-exit)
(advice-add 'magit-inside-worktree-p :around #'my/nfs-early-exit)))
```

## Use auto-mode-alist somehow?

If modes weren't autoloaded, then they could be configured to only load outside of /mnt/nfs, using `auto-mode-alist`.

## Ideal: magit provides a hook to early exit, `magit-ignore-function`, which is called at the top of each find-file hook.

**Comment by tarsius** [comment]
This appears to be an *exceptionally* slow file-system. I think it might be okay for you to have to advice functions as you have; few others will have to deal with such slow file-systems. What do others think?

> However, checking whether the file is in a git repository is expensive: it'd involve traversing up for the file hierarchy `stat`'ing for `.git`.

That shouldn't be an expensive operation. By the way Emacs is also looking for other such files, `.dir-locals.el` and `.dir-locals-2.el` come to mind.

**Comment by tomfitzhenry** [comment]
On further investigation, I have isolated this to just `magit-auto-revert-mode-check-buffers` (and the problem goes away when auto-revert-mode is enabled). I expect I can workaround this with auto-revert-buffer-list-filter. I'll raise another bug, if that is unsuitable.

**Comment by tomfitzhenry** [comment]
I had look more into how that 3.9s is spent, and I understand it a bit more.

Opening a source file triggers `find-file-hook` and `after-change-major-mode-hook`, both of which trigger:

* `magit-auto-revert-mode-enable-in-buffers`, which triggers
    * `magit-toplevel`, which triggers
        * `git rev-parse --show-toplevel` ~600ms
        * `git rev-parse --git-dir` ~700ms
* `global-magit-file-mode-enable-in-buffers`, which triggers
    * `magit-inside-worktree-p`, which triggers
        * `git rev-parse --is-inside-work-tree` ~700ms

2*(0.6+0.7+0.7) = 4s.

Since all 6 of those git commands execute and fail on each source file open, I expect some of those  checks could be avoided. However, even a single 600ms is too long.

**Comment by tomfitzhenry** [comment]
Closing, since 600ms is a problem on my end.
