### ISSUE TITLE
Repeated magit-diff-toggle-file-filter has no effect

### ISSUE THREAD

**Issue by olysonek** [magit/magit#4110]
Hi,

I ran into a glitch related to `magit-diff-toggle-file-filter`. I'm doing the following:
1. Open a file that's part of a git repo
2. Run `magit-log-buffer-file`.
3. Show one of the commits that I know touches multiple files. It shows the commit limited to the file.
4. Run `magit-diff-toggle-file-filter`. This correctly results in the file limiting being dropped.
5. Quit the revision buffer using `q`
6. Show the same commit again (or even any other commit from the log). It's limited again. So far so good.
7. Run `magit-diff-toggle-file-filter` again.

The last step seems to have no effect - the commit remains limited to the file. I think it should drop the file limiting.

If I kill the revision buffer instead of just pressing `q`, it works again.

I'm also able to workaround the issue by pressing `D`, clearing the list of files using `--` and pressing `g`, instead of running `magit-diff-toggle-file-filter`.

Output of `magit-version`: `Magit 20200503.1905, Git 2.25.4, Emacs 26.3, gnu/linux`.

I also tried running magit from the repo using `make emacs-Q` as of commit 9a388a61d95761b9c748dc186602ba7c691d580f. The result is the same.

And while I'm here, let me say thank you for this amazing software! I don't know what I'd do without it anymore :).

**Comment by tarsius** [comment]
Thanks for the report!

**Comment by olysonek** [comment]
Hmm, I'm not sure that fixed it. I can still reproduce it as described. I even tried removing all `magit*` packages from MELPA to make sure I'm running it from the repo.

**Comment by kyleam** [comment]
26da7ef fixed the issue you reported, but for diff buffers.  I've applied the same fix for revision buffers.

Thank you for the steps to trigger this.  I got into this state a while ago, noted it, but once I got around to looking into it, I could not figure out how to get back into the buggy state.

**Comment by olysonek** [comment]
It works now. Thank you both for fixing it so quickly!
