### ISSUE TITLE
Provide (maybe optionally) hyperlinks to commits referred to by their hash

### ISSUE THREAD

**Issue by doublep** [magit/magit#4115]
In commit comments I often refer to other commits, like this:

    Undo accidental reversion of most parts of commit c305a42 in 41c759a.

It would be great if Magit turned commit hashes to hyperlinks so that I could easily visit related commits.  Such hyperlinks could be added both in "Magit Log" and "Magit Rev" modes.

**Comment by tarsius** [comment]
For revision buffers this already exists, though you might have to tweak `magit-revision-use-hash-sections`.

**Comment by doublep** [comment]
Indeed. I never noticed, because for me log buffer is more important. I tend to write longer comments in the first line, so that I see them wholly just in the log. Also, in the log buffer I would hope for `Tab` to cycle through all the links. In revision buffer this key is already taken for section management.

**Comment by tarsius** [comment]
> Oh and you can use `RET` to visit a commit mentioned in commit messages, even if they the hash is not linkified in that buffer.

This doesn't appear to be true anymore.

**Comment by tarsius** [comment]
> This doesn't appear to be true anymore.

I've fixed that regression.

> hyperlinks could be added [...] in "Magit Log"

Here it works too now. In fact `magit-show-commit` used the commit hash at point in most cases now, not just here.
