### ISSUE TITLE
Magit installation failure: transient-define-prefix is void

### ISSUE THREAD

**Issue by errissa** [magit/magit#4117]
I just installed Magit from MELPA. During compilation there were warnings "Symbol's function definition is void: transient-define-prefix" and after installation when I tried M-x magit-version I got an error with the same thing. I tried restarting emacs to no avail.

I see transient-define-prefix used an many magit files but no definition of it. In transient.el I see a reference to it in the function documentation string for transient-setup, but no definition of it.

It's magit-20200517.1537 that was installed which installed transient-20200512.1320 as a dependency. I am running emacs 26.3.

**Comment by tarsius** [comment]
Updates to Melpa are not atomic. In this case `magit` has already been updated but the new version of `transient`, which it now depends on has not. Wait an hour or two until Melpa's update loop has gotten from `m` to `t`.

Ups... turns out I had not pushed the changes to `transient` to its `master` branch yet. This may delay the update a few more hours for Melpa users.

**Comment by idcrook** [comment]
With https://github.com/magit/transient/commit/30387690fda86e3a594906e154dac4e20f60bbfb  the `"Symbol's function definition is void: transient-define-prefix"` error is gone. 

Want to note that other packages (`magit-todos`, `magit-diff-flycheck`) are now encountering another error issue w.r.t. `magit-margin-settings`. 

```
Error (use-package): magit-todos/:init: Symbol’s value as variable is void: magit-margin-settings
Error (use-package): magit-todos/:catch: Symbol’s value as variable is void: magit-margin-settings
```

There may be others dependent; those are just what I had in my .emacs.

```lisp
(use-package magit-diff-flycheck)

(use-package magit-todos
  :init
  (magit-todos-mode +1))
```

**Comment by tarsius** [comment]
You might have to reinstall these packages and/or `magit`, and/or recompile your init file.

**Comment by idcrook** [comment]
> You might have to reinstall these packages and/or `magit`, and/or recompile your init file.

I use straight.el, and these are the errors visible after a fresh pull of all packages. (Note: these "new" errors were behind the `transient-define-prefix` error, which has been fixed in latest `transient` package)

**Comment by ereslibre** [comment]
Melpa just got in sync with commit https://github.com/magit/transient/commit/30387690fda86e3a594906e154dac4e20f60bbfb.

Everything is fine over here now :+1:

**Comment by errissa** [comment]
Everything is fine for me now as well. Thanks!

**Comment by j3pic** [comment]
I'm having this issue 4 years later. Should I keep waiting?
