### ISSUE TITLE
Several packages stopped working with last version

### ISSUE THREAD

**Issue by pbgc** [magit/magit#4118]
Hi,

After updating to last dev version (20200517.1537) at least diff-hl is not working anymore and neotree (configured with projectile) stopped showing different colors depending of each file vc state.
If I remove this line from init.el:

`(setq vc-handled-backends (delq 'Git vc-handled-backends))`

then they work.

Thanks

**Comment by tarsius** [comment]
Why do you think this has something to do with Magit?

Try to narrow the issue down, starting with `emacs -Q`.
Try to reproduce the issue with and without Magit, etc.

For me `diff-hl` still works as expected. I don't use `neotree`.

**Comment by pbgc** [comment]
> Why do you think this has something to do with Magit?

Because it was Magit that changed ?
I have (for years) this lines on init:
```
(require 'magit)
(setq vc-handled-backends (delq 'Git vc-handled-backends))
(global-set-key (kbd "C-c g") 'magit-status)
```
If I comment them, diff-hl and neotree works
And even with the (require 'magit) it works if I comment the second line (that is recommended on magit manual).

> Try to reproduce the issue with and without Magit, etc.
Off course I did that! How do you think I found that it works without that line ?

> For me diff-hl still works as expected
Do you have 
`(setq vc-handled-backends (delq 'Git vc-handled-backends))`
on your init.el ?
Without this or Magit, diff-hl works as expected .. both with Git, Hg and Darcs

**Comment by Silex** [comment]
@pbgc: can you copy-paste the error you are getting? or screenshot it?

**Comment by pbgc** [comment]
@Silex No error! diff-hl just does not show nothing as changed and neotree does not color the changed files.

**Comment by Silex** [comment]
@pbgc: can you try `emacs -Q` and `(setq vc-handled-backends (delq 'Git vc-handled-backends))` and confirm that neotree does not work?

I mean, neotree just uses vc and you are telling vc not to work for git with these lines.

**Comment by pbgc** [comment]
@Silex That line is from MAgit manual: https://magit.vc/manual/magit/The-mode_002dline-information-isn_0027t-always-up_002dto_002ddate.html

> I mean, neotree just uses vc and you are telling vc not to work for git with this line, so that'd be > logical that neotree does not work, even before your magit upgrade.

It worked for YEARS until yesterday!
It is telling not to use git ... but instead Magit will be used (as diff-hl, neotree, projectile, etc do!!)

> That to me implies magit has nothing to do with it, and you thought (setq vc-handled-backends > (delq 'Git vc-handled-backends)) was active but it was not.

That does not imply nothing! I'm sure that the line was active and tried several things before posting a bug report.

**Comment by tarsius** [comment]
> Do you have `(setq vc-handled-backends (delq 'Git vc-handled-backends))` on your init.el ?

Actually I didn't try that. That was a bit sloppy of me. This setting makes all the difference. By the way I also still have to try without Magit, but that is more challenging to do given my setup.

**Comment by Silex** [comment]
@pbgc: What about my test? Please, before you answer another time do my test.

> It worked for YEARS until yesterday!
> It is telling not to use git ... but instead Magit will be used (as diff-hl, neotree, projectile, etc do!!)

This is what I consider to be neotree: https://github.com/jaypei/emacs-neotree/blob/dev/neotree.el

There's no sign of magit at all in that. It just uses vc. The line `(setq vc-handled-backends (delq 'Git vc-handled-backends))` tells vc not to work for git.

Again you need to run my test to confirm or infirm that my theory is right.

**Comment by pbgc** [comment]
@Silex  I will no do your test ... because I already did and others.

That's you that need to test what I said! Including that line and that before searching for neotree code ... because you obviously don't use neotree! If you used it you would know about:

https://www.emacswiki.org/emacs/NeoTree#toc11

Neotree is almost used everytime with projectile!!! 

Try searching here instead: https://github.com/bbatsov/projectile/blob/master/projectile.el
and see:

```
(defun projectile-vc (&optional project-root)
  "Open `vc-dir' at the root of the project.
For git projects `magit-status-internal' is used if available.

```

**Comment by pbgc** [comment]
@Silex try to search for magit here also: https://github.com/dgutov/diff-hl/blob/master/diff-hl.el

**Comment by tarsius** [comment]
I have been trying to get `diff-hl` to work just by itself in a pristine `~/.emacs.d`; so far with no success. It is quite possible that this is so because I am doing something extremely stupid. I am doing this for your benefit, so when @Silex asks you to do something to debug your issue, then please try to do that. It is possible that you made a mistake earlier or are misunderstanding something, and maybe the thing he asked you to do what help with that. Maybe not, but its possible. Please try it.

**Comment by tarsius** [comment]
Maybe you could help me with something too (by doing the same steps and telling me where I went wrong):

1. Move the old `~/.emacs.d` a way
2. Create a new one containing an init with:

   ```
   (require 'package)
   (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
   (package-initialize)
   ```

3. `package-refresh-contents`
4. `package-diff-hl`
5. Edit init.el

```
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages '(magit diff-hl)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(require 'diff-hl)
(global-diff-hl-mode)
```

Restart. Visit a file that was modified. Why are the differences not shown?

**Comment by pbgc** [comment]
@tarsius like I said ... I already tried that before and even If I would not ... what @Silex is saying is obvious that it will work! It's like saying: remove Magit from Emacs and then restart and check that Magit does not work!

The question here is that both diff-hl and neotree (with projectile) both use Magit when available ... not vc!!!

My diff-hl setup:

`
(add-hook 'magit-pre-refresh-hook 'diff-hl-magit-pre-refresh)
(add-hook 'magit-post-refresh-hook 'diff-hl-magit-post-refresh)

(when (display-graphic-p)
  (add-hook 'prog-mode-hook 'turn-on-diff-hl-mode)
  (add-hook 'vc-dir-mode-hook 'turn-on-diff-hl-mode)
)
(unless (display-graphic-p)
  (defun diff-hl-custom ()
    (diff-hl-margin-mode)
    (turn-on-diff-hl-mode))
  (add-hook 'prog-mode-hook 'diff-hl-custom)
  (add-hook 'vc-dir-mode-hook 'diff-hl-custom)
)
`

**Comment by pbgc** [comment]
@tarsius 
`Why are the differences not shown?`

Maybe you missed and this is required ?: https://github.com/dgutov/diff-hl#magit

**Comment by tarsius** [comment]
As I have said I have installed `diff-hl` and nothing else. Do you know how I can get it to do something without also installing `magit` (it's author does not use `magit`, so that must be possible).

**Comment by pbgc** [comment]
> As I have said I have installed `diff-hl` and nothing else. Do you know how I can get it to do something without also installing `magit`? (It's author does not use `magit`, so that must be possible).

Yes Sorry ... I misunderstood your request. Only now I saw that you are trying without Magit. 
I will try to do what you ask

**Comment by tarsius** [comment]
The problem is that I had to move my `~/.emacs.d` out of the way to use a pristine `~/.emacs.d`. My setup to easily switch between different configurations broke. I am quite lost without my regular key bindings from my regular `~/.emacs.d`. I will have to make my profile switcher work again and then I will have to port my key bindings to such a `emacs -Q` + my key bindings profile, and then I can start debugging such issue efficiently again.

**Comment by Silex** [comment]
@tarsius: my guess is https://github.com/bbatsov/projectile/blob/master/projectile.el#L3703
@pbgc: you lost me as a helper.

``` emacs
(define-obsolete-function-alias 'magit-status-internal
  'magit-status-setup-buffer "Magit 3.0.0")

(defun projectile-vc (&optional project-root)
  "Open `vc-dir' at the root of the project.
For git projects `magit-status-internal' is used if available.
For hg projects `monky-status' is used if available.

```

**Comment by pbgc** [comment]
@tarsius I did what you asked and it worked perfectly.
On your second init.el ... you have '(package-selected-packages '(magit diff-hl)))

Mine is:```

(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (diff-hl))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(require 'diff-hl)
(global-diff-hl-mode)
```

and it works:

![Captura de ecrã 2020-05-19, às 11 45 23](https://user-images.githubusercontent.com/180825/82317632-7ee91400-99c6-11ea-860a-219216baf573.png)

**Comment by tarsius** [comment]
Thanks! I got it working now. Not sure if that was the issue or if I just didn't see it because its much more visible with the theme I usually use.

In any case I will have to improve my testing setup before I can get back to helping you. Sorry.

**Comment by pbgc** [comment]
@tarsius 
Then installed Magit and put those lines on init.el
```

(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (magit diff-hl))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(require 'diff-hl)
(global-diff-hl-mode)

(require 'magit)
(setq vc-handled-backends (delq 'Git vc-handled-backends))
(global-set-key (kbd "C-c g") 'magit-status)
```

And stopped working:

![Captura de ecrã 2020-05-19, às 11 58 41](https://user-images.githubusercontent.com/180825/82318739-421e1c80-99c8-11ea-8fde-633151ea5bca.png)

**Comment by pbgc** [comment]
@tarsius 
Commenting that line ... makes it work again:
```

(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (magit diff-hl))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(require 'diff-hl)
(global-diff-hl-mode)

(require 'magit)
;;(setq vc-handled-backends (delq 'Git vc-handled-backends))
(global-set-key (kbd "C-c g") 'magit-status)

```

![Captura de ecrã 2020-05-19, às 12 00 47](https://user-images.githubusercontent.com/180825/82318882-814c6d80-99c8-11ea-97dd-2f9864dadc25.png)

**Comment by pbgc** [comment]
> In any case I will have to improve my testing setup before I can get back to helping you. Sorry.

Ok. Thanks for your help!
It's working now without that line ... I had that line since the first time I installed Magit (LONG time ago) only because the manual said it was good for performance...

**Comment by dgutov** [comment]
Hey guys.

`diff-hl` is not expected to work correctly with `Git` removed from `vc-handled-backends`. Just look at the definition of `diff-hl-changes`: we need to know the current backend in use, and we do different things depending on the state of the file. The latter can be advised, but the former...

In any case, this didn't work before, and it doesn't work now. Magit updated are unlikely to have changed anything.

Can Magit provide the same information, in memoized fashion? Otherwise there's no point at all in disabling `vc-git`.

**Comment by Silex** [comment]
> In any case, this didn't work before, and it doesn't work now. Magit updated are unlikely to have changed anything.

Thanks for confirming what could have been confirmed ages ago by @pbgc if only he ran my test.

**Comment by pbgc** [comment]
@Silex My only answer for you ... is: You have YET to understand the problem ... It seems that you blocked on your test ... and fail to understand that some packages in the presence of Magit DON'T USE VC
Your test ... is NONSENSE regarding the problem I reported ... I will not answer anything more from you!

**Comment by pbgc** [comment]
@dgutov you are wrong ... and @Silex is. You failed to read the entire thread and read that the problem only occurs when that line (that I use for YEARS and it's recommended in the Magit Manual) is used. Until this version ... it worked ... after doesn't.
For me ... this is over ...

**Comment by dgutov** [comment]
@pbgc So previously, `diff-hl` would work together with that line if Magit was also installed? But now it doesn't?

You can test that theory by installing some older version of Magit.

**Comment by tarsius** [comment]
> `diff-hl` is not expected to work correctly with `Git` removed from `vc-handled-backends`.

Thanks for the information. I expected as much but did not get around to looking at the source yet.

> Can Magit provide the same information, in memoized fashion? Otherwise there's no point at all in disabling `vc-git`.

The advice in Magit manual to disable VC is pretty old and I am likely to remove it or at least add some more warnings about potential downsides. But again, that will require some investigating and I won't get to it right away.

**Comment by dgutov** [comment]
> I am likely to remove it or at least add some more warnings about potential downsides

That sounds like a good idea.

**Comment by pbgc** [comment]
@dgutov 
> @pbgc So previously, `diff-hl` would work together with that line if Magit was also installed? But now it doesn't?
> 
> You can test that theory by installing some older version of Magit.

Yes! I said that several times in both issues I opened.

**Comment by tarsius** [comment]
Re https://github.com/dgutov/diff-hl/issues/141.

**Comment by pbgc** [comment]
@dgutov 
> You can test that theory by installing some older version of Magit.

I don't need to test the theory ... I have that line on my init.el at leat since October 2017 (just checked my emacs conf repo) .. but probably before because I started a new repo on that that.
It always worked until this version ... and it was not only diff-hl that stopped working with this version ... neotree using projectile also.

**Comment by dgutov** [comment]
@pbgc

I'm sorry, I just don't understand how that could work. Some other package or customization reset the variable to the original value, perhaps?

`neotree` also has VC integration, which would be disabled by this line.

In any case, one good outcome of this discussion might be the documentation update in Magit.

**Comment by pbgc** [comment]
@dgutov 
I use neotree with projectile (https://www.emacswiki.org/emacs/NeoTree#toc11) as, I think, almost anyone that uses neotree.
Projectile uses Magit, if installed, for git and not VC.

I don't know why it worked and now it doesn't .. but it worked for ages and stopped working and that was what I reported. 
It seems that without that line things work and even what is described on Magit manual (about the things that would appear on modeline) does not happen anymore ... so I'm not seeing any problem without the line ... so I'm happy without it and for me it's over!
Thank you all for the help

**Comment by dgutov** [comment]
> Projectile uses Magit, if installed, for git and not VC.

Not really: it has a command `projectile-vc` which shows the status buffer. But it doesn't use Magit for anything else.

> so I'm not seeing any problem without the line ... so I'm happy without it and for me it's over!

Very good. :-)

**Comment by pbgc** [comment]
@dgutov 
> Not really: it has a command `projectile-vc` which shows the status buffer. But it doesn't use Magit for anything else.

That's exactly that! What stopped working in neotree (i said it) was the coloring of the files on the tree regarding it's git status

**Comment by pbgc** [comment]
@dgutov Just to finish .. This is what I meant:

![Captura de ecrã 2020-05-22, às 14 29 40](https://user-images.githubusercontent.com/180825/82672789-bc54d800-9c38-11ea-8d64-fde790135ada.png)

**Comment by dgutov** [comment]
That doesn't work through Projectile.

**Comment by dgutov** [comment]
Will https://magit.vc/manual/magit/The-mode_002dline-information-isn_0027t-always-up_002dto_002ddate.html be updated later?

**Comment by tarsius** [comment]
I overlooked that part. I'll remove that too.

**Comment by tarsius** [comment]
Replaced with:

```
If you don't really care about seeing this information in the
mode-line, but just don't want to see /incorrect/ information,
then consider simply not displaying it in the mode-line:

#+BEGIN_SRC emacs-lisp
  (setq-default mode-line-format
                (delete '(vc-mode vc-mode) mode-line-format))
#+END_SRC
```

Might take a while to propagate.
