### ISSUE TITLE
magit-copy-section-value w/ region and prefix arg: incompatible with transient-mark-mode

### ISSUE THREAD

**Issue by ilohmar** [magit/magit#4119]
Magit 20200517.1537, Git 2.26.2, Emacs 28.0.50, gnu/linux

Make sure `transient-mark-mode` is enabled (AFAICT it is by default).
In any revision (or status) buffer, mark a region inside a hunk, press C-u C-w to copy its contents w/o the diff markers.

Expected behavior: The region with stripped diff markers is added to the kill ring.

Actual behavior: Emacs messages "magit-copy-section-value: The mark is not active now", and no region has been added to the kill ring.

Additional info: If `transient-mark-mode` is disabled, the command behaves as expected.

It appears that the `(deactivate-mark)` in the first cond branch of `magit-copy-section-value` is the culprit.  It seems to me that, if it is desirable at all, it should come *after* the `kill-new` call.

Additional info: If `transient-mark-mode` is disabled, the command behaves as expected --- this fits the picture perfectly.

**Comment by kyleam** [comment]
With a vanilla configuration where Transient Mark mode is enabled, I haven't been able to trigger this with Magit's current master (b1b2683f6) and an emacs built from the current master (5352bda4e).  When I select a region of a hunk and hit <kbd>C-u C-w</kbd>, the lines are copied without the diff markers.

Do you see the behavior without any custom configuration?

**Comment by ilohmar** [comment]
I am sorry, I forgot to mention one ingredient (but will also re-try from `emacs -q` later today): I have `(setq mark-even-if-inactive nil)`, that's what makes (in the default `transient-mark-mode`) the difference.

**Comment by kyleam** [comment]
> (setq mark-even-if-inactive nil)

Ah, makes sense.

> On a more general note, the `deactivate-mark` call before the `kill-new` is weird, anyway, or isn't it?

Yes, I think it's weird and wrong (and not surprisingly my doing :).  I won't be free to fix it until (my) tonight, though.

**Comment by kyleam** [comment]
Thanks for catching my mistake and making me aware of `mark-even-if-inactive`.

**Comment by ilohmar** [comment]
Thank you!
