### ISSUE TITLE
RFE: magit-file-rename should allow directory destination

### ISSUE THREAD

**Issue by juhp** [magit/magit#4122]
Today I discovered `magit-file-rename`, which is helpful indeed.

But usually I find myself _moving_ files around not actually renaming them.
So I would like suggest adding an additional command `magit-file-move`
which would take a directory as the second argument.

Or maybe better also accept a directory for the second argument of `magit-file-rename`?
This would parallel the behavior of `git mv`.

**Comment by tarsius** [comment]
> Or maybe better also accept a directory for the second argument of `magit-file-rename`?
> This would parallel the behavior of `git mv`.

That sounds like the better option.

**Comment by juhp** [comment]
Looking around https://github.com/magit/magit/blob/master/lisp/magit-files.el#L445
2 problems I see are that:
- `magit-file-rename` currently gives up if `newname` exists
- `set-visited-file-name` can't take a directory, so for a directory the filename needs to be appended.
