### ISSUE TITLE
Consider allowing magit-diff-default-arguments to be configurable

### ISSUE THREAD

**Issue by scalisi** [magit/magit#4126]
The status buffer can be too slow when changes include large PDFs that have been deleted. I resolved this issue by adding `"--irreversible-delete"` to [line 390 in magit-status.el](https://github.com/magit/magit/blob/master/lisp/magit-status.el#L390).

Please consider allowing `magit-diff-default-arguments` to be configurable so that this change can be made in an init file rather than by editing and byte-compiling magit-status.el after every Magit update.

Thank you for Magit!

**Comment by tarsius** [comment]
The <kdb>D</kbd> popup can be used to change (and optionally permanently save) the diff arguments used in the current buffer. The `--irreversible-delete` isn't available by default but...

**Comment by tarsius** [comment]
Certain transient popups hide some of their suffix commands by default. These additional suffixes can be [enabled interactively](https://magit.vc/manual/transient/Enabling-and-Disabling-Suffixes.html). TL;DR Enter the transient as usual and type <kbd>C-x l</kbd>.

<sub>This is a [canned response](https://help.github.com/en/github/writing-on-github/working-with-saved-replies); it may not apply 100% in this case.</sub>

**Comment by tarsius** [comment]
Also in this case you should make the same change to `magit-diff-refresh` as well as `magit-diff`.

**Comment by scalisi** [comment]
Setting `--irreversible-delete` as a default argument via the `magit-diff-refresh` transient did the trick. Thank you, @tarsius.
