### ISSUE TITLE
Honor a configured mergetool in magit-ediff-resolve

### ISSUE THREAD

**Issue by jsyjr** [magit/magit#4128]
I am trying to persuade a community of developers using various tools and editors to give a standalone magit instance a look-see.  In most instance magit's functionality is a slam-dunk improvement over our current alternatives (commit grooming, imerge integration, etc).

The one place where magit will be perceived as a clear step backwards is when I ask developers to forego their current, polished merge tools in favor or emacs' 3-way merge.

I would like to suggest a very limited magit improvement, namely extending magit-ediff-dwim's logic to honor any configured git merge tool.  I achieved a serviceable prototype with the following two line patch to magit-ediff-resolve.  (It may not be up to magit's normal level of polish but it gets the job done.)

```elisp
  (magit-with-toplevel
    (with-current-buffer (find-file-noselect file)
      (if (eq 0 (call-process "git" nil nil nil "config" "merge.tool"))
          (call-process "git" nil nil nil "mergetool" file)
        (smerge-ediff)
        . . .
```

**Comment by tarsius** [comment]
Seems to me that this should just be a separate command, defined in the "External Tools" section of `magit-extras.el`. `magit-ediff-resolve`'s `interactive` form could be factored out into a `magit-ediff-resolve--read-file` argument. `magit-mergetool-resolve` should be added to `magit-run` and maybe on level 6 to `magit-ediff`. The manual and release notes should be updated. If the mergetool is unspecified, the user should be informed gracefully. Feel up to it? :wink:

**Comment by jsyjr** [comment]
Wow!  I was disappoint by your original reply.  In part because I did not fully understand it and in part because I knew that I lacked the elisp chops to carry out your suggestion.

Thank you so much for your follow-through.

**Comment by tarsius** [comment]
Your are welcome.
