### ISSUE TITLE
log: Regression in ++header output

### ISSUE THREAD

**Issue by kyleam** [magit/magit#4129]
As mentioned in gh-4127, the output shown with `++header` and `--graph` no longer has a vertical bar beside the `magit-log-revision-headers-format` information.  It appears the expected number of bars may have instead ended up under the information.

This bisects to my db97623a (magit-insert-{log,bisect-rest}: handle refs with parentheses, 2017-04-15).  I haven't taken a closer look yet.

**Comment by kyleam** [comment]
This comes down to git's output when `--graph` is used with a `--format` value that includes a `%x00`.

```
$ git log --graph "--format=%h%n%an%n%ad" master~2..master
* 80420c9f
| Jonas Bernoulli
| Sun May 31 14:03:26 2020 +0200
* 22cc9fd7
  Jonas Bernoulli
  Fri May 29 19:34:56 2020 +0200

$ git log --graph "--format=%h%x00%an%n%ad" master~2..master
* 80420c9f^@Jonas Bernoulli
Sun May 31 14:03:26 2020 +0200
* 22cc9fd7^@Jonas Bernoulli
Fri May 29 19:34:56 2020 +0200
```

I think that's probably worth digging into to more and reporting upstream.  However, even if that is taken as a bug and easily fixable, that of course still doesn't help us for older git versions that we support.  Since the null byte it tripping up git, one approach is to just swap in another character.  Changing `magit-log-heading-re` to use `%x03` instead of `%x00`, with the corresponding `s/\0/^L/` in `magit-insert-log`, seems to work.

**Comment by kyleam** [comment]
I didn't find time to revisit this tonight.  Pushed a mostly finished state to km/log-format-no-null (80fdf8f4).  I'll wrap that up tomorrow.

**Comment by tarsius** [comment]
Thanks!
