### ISSUE TITLE
magit doesn't depend on a recent enough verision of transient

### ISSUE THREAD

**Issue by kidd** [magit/magit#4134]
Hi, after upgrading magit to the latest melpa version, it seems I needed a new transient version (which has `transient-define-prefix`) but it wasn't pulled automatically (I had a previous version of transient installed already).

I see `magit/magit` depends on `magit/transient` but the version of transient still doesn't have transient-define-prefix. maybe it needs a bump of the dependency?

Not sure if it's related, but after installing latest transient, when starting emacs I get `Symbol's value as variable is void: magit-margin-settings`.  Still figuring out this one (will update when I have more details)

**Comment by tarsius** [comment]
See #4120.

**Comment by kidd** [comment]
oops, sorry for the noise... I didn't check the closed issues before posting :(.

Thanks!
