### ISSUE TITLE
Clickable URL in remote messages

### ISSUE THREAD

**Issue by bersace** [magit/magit#4136]
Hi,

When pushing a new branch on GitHub or GitLab, the remote sends an URL to create the Pull Request or Merge Request. This looks like :

```
  0 git … push -v fork refs/heads/mybranch\:refs/heads/mybranch
Poussée vers git@github.com:bersace/project.git
Écriture des objets: 100% (8/8), 1.77 KiB | 906.00 KiB/s, fait.
Total 8 (delta 4), réutilisés 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 2 local objects.        
remote: 
remote: Create a pull request for 'mybranch' on GitHub by visiting:        
remote:      https://github.com/bersace/project/pull/new/mybranch        
remote: 
To github.com:bersace/project.git
 * [new branch]      mybranch -> mybranch
updating local tracking ref 'refs/remotes/fork/mybranch'
```

I know that forge can ease creating a PR, but I like the web interface (for template, reviewer, draft, labels, etc.).

Thus, I'm used to type `$` right after pushing a branch creating it, and `TAB` to show remote messages. However, the URL is not clickable. Selecting text is hard due to conflicts with evil keybindings.

I'm using Doom Emacs with magit ae82fcf4d47559688a0ad7dfee55dd74bbe14b9e

Merci pour magit :-)

**Comment by phil-s** [comment]
Perhaps just enable `goto-address-mode` in `magit-process-mode-hook` and then you can `C-c RET` or `<mouse-1>` on the URL.

**Comment by tarsius** [comment]
Why try to avoid doing to much parsing on the text that goes into the process log buffer for performance reasons.

@phil-s sound like a good alternative.

**Comment by bersace** [comment]
Thanks @phil-s , that's exactly what I wanted. I contributed a patch to doom-emacs https://github.com/hlissner/doom-emacs/pull/3292
