### ISSUE TITLE
Make magit usable on large changes - currently magit-status, etc. are unusable on large changes

### ISSUE THREAD

**Issue by JohnC32** [magit/magit#4143]
If I have a large number of diff's, e.g. many meg of diff output, magit-status basically hangs and magit is unusable. Can this be fixed? 

One way to fix would be to defer showing diffs until requested, i.e. magit-status would just show what "git status" shows and when I hit tab on a changed file, the diff would be computed?

It would be great if magit could be used on large changes as it's an excellent improvement over the command line git interface.

**Comment by tarsius** [comment]
> Can this be fixed?

Of course but it will be a lot of work, including major refactorings, and I just haven't gotten around to it yet.

That has come up before, see e.g. #2982, which we use to keep track of the fact that this an other potential performance improvements have not been taken care of yet.

**Comment by JSpenced** [comment]
@tarsius Is there a way to disable certain files from showing there diffs? .Ipynb notebook files are always big because of the binaries often embedded in them. I was hoping to just turn off the diffing for these files.

**Comment by tarsius** [comment]
This can be done using `git update-index --assume-unchanged`, which is accessible from <kbd>i</kbd>.
