### ISSUE TITLE
Reusing buffer for magit if it is derived mode?

### ISSUE THREAD

**Issue by SreenivasVRao** [magit/magit#4145]
Hi, I use magit traditional  display buffer function in emacs. I notice that when I want to commit or view the log, magit opens a new buffer. I was checking the options for display buffer and I see a few.

I'm not sure what I'm supposed to choose to get this to work: 

if current buffer mode!=magit mode
Then use other window
Else use current window

Reuse the current magit buffer as much as possible. This seems to be opposite to display-buffer-same-window-except-diff-v1 which opens a new window if it *is* a magit mode currently.

**Comment by kyleam** [comment]
[ In the future please ask support questions in one of the channels listed in the README. ]

> I'm not sure what I'm supposed to choose to get this to work:
> 
> if current buffer mode!=magit mode
> Then use other window
> Else use current window

None of the built-in options do that.  You can set `magit-display-buffer-function` to a custom function though:

```elisp
(defun my/magit-display-buffer (buffer)
  (display-buffer
   buffer (if (derived-mode-p 'magit-mode)
              '(display-buffer-same-window)
            '(nil (inhibit-same-window . t)))))

(setq magit-display-buffer-function #'my/magit-display-buffer)
```

However, I suspect after trying that out a bit, you won't prefer it.  In particular, when in a log buffer, it is very useful to display revision buffers in the other window, enabling you to move point down log lines and have a revision buffer in the other window follow along.

> This seems to be opposite to display-buffer-same-window-except-diff-v1 which opens a new window if it _is_ a magit mode currently.

`magit-display-buffer-same-window-except-diff-v1` only tries to display in the other window when the buffer to be displayed devise from `magit-diff-mode` or `magit-process-mode`.

**Comment by SreenivasVRao** [comment]
Yeah sorry, thanks for the tip. What you said is true. Perhaps I could
tweak it based on if it is showing magit-log mode?

I will try this out and post on one of the other channels if it doesn't
work.

I think it would be a useful option to have something similar to this,
though I can see it being cumbersome to customize...

Cheers!

**Comment by kyleam** [comment]
> Perhaps I could tweak it based on if it is showing magit-log mode?

Yep.  It'd essentially be adding a second condition to what's in `magit-display-buffer-same-window-except-diff-v1`.

**Comment by kyleam** [comment]
In my view `-same-window-except-diff-v1` gets close enough to the proposed variant, and `magit-display-buffer-function` is always there for users that want something slightly different.
