### ISSUE TITLE
magit-diff-mode failed to stage hunks containing emoji

### ISSUE THREAD

**Issue by wyuenho** [magit/magit#4146]
Reproduction:
1. git init a new repo
2.
bash
```
cat << END_TEXT >> test.txt
hello
world
END_TEXT
```
3. git commit -a -m "test"
4. In emacs, visit test.txt
5. Now add a line containing only one emoji such as 😀 between hello and world
6. M-x magit-diff RET u RET
7. In the magit diff buffer, press n to select the hunk containing the emoji
8. Press s to stage
9. Now the diff buffer becomes:
<img width="301" alt="Screen Shot 2020-06-15 at 13 01 53" src="https://user-images.githubusercontent.com/160028/84655197-68bc6e00-af08-11ea-8b5a-78a83e79b029.png">
10. In terminal:
<img width="428" alt="Screen Shot 2020-06-15 at 13 02 44" src="https://user-images.githubusercontent.com/160028/84655265-92759500-af08-11ea-936d-3f1f499c7157.png">

Expectation:
magit should stage the emoji instead of adding a line with a space, stage it, then remove that line with a space.

magit-version:
Magit 20200614.1018, Git 2.27.0, Emacs 27.0.91, darwin

**Comment by tarsius** [comment]
I cannot reproduce that but for my Emacs does not show an image for the smiley but a "font does not feature this character" box thingy. What did you do to get to see a smiley instead?

**Comment by wyuenho** [comment]
Can you input any emoji at all? If you are on emacs 28 you should be able to.

**Comment by tarsius** [comment]
I copy-pasted the character from Github into Emacs. So yes I was able to "input" it I guess. I am using 28. Is there a build-in "select a emoji from a list" feature in 28? Did you install any packages that related to this. Did you try to reproduce starting from `emacs -Q`?

**Comment by wyuenho** [comment]
I didn't install any packages. I've set my default font in emacs to
Google's Noto. Emojis are just regular Unicode codepoints these days.

**Comment by tarsius** [comment]
> I've set my default font in emacs to Google's Noto.

My font on the other hand does not appear to feature the character in question. I believe that is irrelevant to this issue. If it did feature this character and did not display some generic placeholder instead, then I would still be able to stage.

> Emojis are just regular Unicode codepoints these days.

Yes but your screenshot does not show a text character; it shows that a image file has been substituted for that character. I suspect that whatever does the substitution does it wrong, which is why I try to figure out what that thing is.

**Comment by tarsius** [comment]
Please help us narrow the issue down by trying to reproduce it without your personal configuration by starting from `emacs -Q ...`. The manual [documents](https://magit.vc/manual/magit/Debugging-Tools.html) the tools that we provide to make that easier.

<sub>This is a [canned response](https://help.github.com/en/github/writing-on-github/working-with-saved-replies); it may not apply 100% in this case.</sub>

**Comment by wyuenho** [comment]
That's not an image, that's just the native macOS emoji display.

This is all I have put in my .emacs

```
(set-fontset-font "fontset-default" 'unicode "Apple Color Emoji" nil 'prepend)
```

Without that line, the emoji inserted is just a blank

**Comment by tarsius** [comment]
> That's not an image, that's just the native macOS emoji display.

I don't know how that works then. Also I am not on macOS.

I am classifying this issue as "edge-case that doesn't affect many people but that will take a lot of effort to fix" and delay working on it until I have no more pressing things to do.

**Comment by wyuenho** [comment]
This is likely a problem with default-process-coding-system not set to utf-8. I'm closing this.
