### ISSUE TITLE
Error in latest version. Popups are unusable! cl-etypecase failed: [eieio-class-tag--transient-column ...]

### ISSUE THREAD

**Issue by frrad** [magit/magit#4150]
I am experiencing problems exactly like https://github.com/magit/magit/issues/3732 after upgrading.

magit-version
`Magit 20200622.2019, Git 2.17.2 (Apple Git-113), Emacs 25.3.1, darwin`

The workaround of removing `transient.elc` suggested here https://github.com/magit/magit/issues/3732#issuecomment-464058617 worked to fix my problem. Thought you might want to know anyways in case there has been some regression.

**Comment by tarsius** [comment]
Sounds like a temporary hick up (likely the transient and magit packages being out of sync on Melpa) that appears to have ended up affecting only you. Thanks for reporting, but I think we can close it now.
