### ISSUE TITLE
Interactive Rebase and Empty Commit Messages

### ISSUE THREAD

**Issue by whxvd** [magit/magit#4153]
On current master (`v2.90.1-1015-g0123e377`) and running Emacs with what `magit-emacs-Q-command` produces.

In an empty directory, run:
```
git init
git commit --allow-empty -m0
touch 1; git add .; git commit -m1
touch 2; git add .; git commit -m2
touch 3; git add .; git commit --allow-empty-message -m ''
touch 4; git add .; git commit --allow-empty-message -m ''
```
Then, in Magit, trying to interactively rebase `HEAD` on the commit with message `0` leads to a `git-rebase-todo` buffer starting with:
```
pick 3e0ca4b 0 # empty
pick 073b6dc 1
pick 1882401 2
pick 3d4961b
pick ca20e39
```
However, the last two `pick` lines receive no fontification. And it is not possible to run commands like `M-p` or `m` on them.

Empty commits get a comment `# empty` at the end. Maybe this issue can be resolved by just adding something similar for commits with empty commit messages. E.g. `# empty commit` instead of just `# empty`. And `# empty commit message` and `# empty commit, empty commit message` in those cases.

**Comment by kyleam** [comment]
Fixed.  Thanks for the report and for providing a minimal example.
