### ISSUE TITLE
Magit fails to access local git repo via tramp

### ISSUE THREAD

**Issue by AndrewBitar** [magit/magit#4155]
I am using Tramp/Emacs on a Windows machine to access a local git repo stored on an external Linux machine within my network. I'd like to use magit from emacs on my Windows machine to access the git repo.

M-x magit-version RET: Magit 20200313.1657, Git 2.19.0, Emacs 26.3, windows-nt

Trying to run magit-status gives the following error: 
magit-merge-in-progress-p: Wrong type argument: stringp, nil

Here's the full backtrace:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-exists-p(nil)
  magit-merge-in-progress-p()
  magit-insert-merge-log()
  apply(magit-insert-merge-log nil)
  magit-run-section-hook(magit-status-sections-hook)
  magit-status-refresh-buffer()
  apply(magit-status-refresh-buffer nil)
  magit-refresh-buffer()
  magit-setup-buffer-internal(magit-status-mode nil ((magit-buffer-diff-args ("--no-ext-diff")) (magit-buffer-diff-files nil) (magit-buffer-log-args ("-n256" "--decorate")) (magit-buffer-log-files nil)))
  magit-status-setup-buffer("/plink:blade:/home/abitar/work/my-repo/emulator/core/inc/")
  magit-status(nil ((5 . 10) (("/plink:blade:c:/msys64/home/abitar/work/my-repo/" magit-git-dir "MERGE_HEAD")) (("/plink:blade:c:/msys64/home/abitar/work/my-repo/" "rev-parse" "--verify" "HEAD")) (("/plink:blade:c:/msys64/home/abitar/work/my-repo/" "rev-parse" "--show-toplevel") . "sh: cd: c:/msys64/home/abitar/work/my-repo/: No such file or directory") ((nil . config) . #<hash-table equal 1/65 0x3ed761>) (("/plink:blade:c:/msys64/home/abitar/work/my-repo/" . magit-toplevel)) (("/plink:blade:/" "rev-parse" "--git-dir")) (("/plink:blade:/" "rev-parse" "--show-toplevel")) (("/plink:blade:/home/abitar/work/my-repo/emulator/core/inc/" "version") . "git version 2.19.0") (("/plink:blade:/home/abitar/work/my-repo/emulator/core/inc/" . magit-toplevel) . "/plink:blade:c:/msys64/home/abitar/work/my-repo/") (("/plink:blade:/home/abitar/work/my-repo/emulator/core/inc/" "rev-parse" "--show-toplevel") . "/home/abitar/work/my-repo")))
  funcall-interactively(magit-status nil ((5 . 10) (("/plink:blade:c:/msys64/home/abitar/work/my-repo/" magit-git-dir "MERGE_HEAD")) (("/plink:blade:c:/msys64/home/abitar/work/my-repo/" "rev-parse" "--verify" "HEAD")) (("/plink:blade:c:/msys64/home/abitar/work/my-repo/" "rev-parse" "--show-toplevel") . "sh: cd: c:/msys64/home/abitar/work/my-repo/: No such file or directory") ((nil . config) . #<hash-table equal 1/65 0x3ed761>) (("/plink:blade:c:/msys64/home/abitar/work/my-repo/" . magit-toplevel)) (("/plink:blade:/" "rev-parse" "--git-dir")) (("/plink:blade:/" "rev-parse" "--show-toplevel")) (("/plink:blade:/home/abitar/work/my-repo/emulator/core/inc/" "version") . "git version 2.19.0") (("/plink:blade:/home/abitar/work/my-repo/emulator/core/inc/" . magit-toplevel) . "/plink:blade:c:/msys64/home/abitar/work/my-repo/") (("/plink:blade:/home/abitar/work/my-repo/emulator/core/inc/" "rev-parse" "--show-toplevel") . "/home/abitar/work/my-repo")))
  call-interactively(magit-status nil nil)
  command-execute(magit-status)

```

**Comment by tarsius** [comment]
Try `(setq magit-git-executable "git")`.

**Comment by AndrewBitar** [comment]
Already did. The git version is the one I expect, i.e. the one on my remote Linux machine.

**Comment by tarsius** [comment]
> Already did.

Did you really? (I am asking because sometimes we say we did something when we did something else that we think is equivalent.)

> The git version is the one I expect, i.e. the one on my remote Linux machine.

It's not about the version its about the path to the executable. On Windows it is something like `c:/path/to/git` by default (for performance reasons), which of course does not work when connecting to Linux.

**Comment by AndrewBitar** [comment]
My .emacs has: ` (setq magit-git-executable "git")`

If it was using c:/path/to/git somehow then I assum magit-version when not return the correct Git version.

**Comment by tarsius** [comment]
This should give you a useful error message:

```elisp
(let ((default-directory "/plink:blade:/home/abitar/work/my-repo/emulator/core/inc/"))
  (call-process magit-git-executable nil t t "rev-parse" "--git-dir"))
```

**Comment by AndrewBitar** [comment]
It returns: `fatal: not a git repository (or any of the parent directories): .git`

**Comment by tarsius** [comment]
And if you add back the `c:` that got lost along the way? Also try in a new and very normal repository. If it works there, then we can start looking into what's weird about the other repository.

**Comment by npostavs** [comment]
> I am using Tramp/Emacs on a Windows machine to access a local git repo stored on an external Linux machine within my network.

>     "/plink:blade:c:/msys64/home/abitar/work/my-repo/"

I'm confused here, presumably `blade` is the name of the external Linux machine, but then why does the dirname start with `c:/msys64`? What is the correct Emacs filename (i.e., works for dired) of the directory containing the git repo?

**Comment by AndrewBitar** [comment]
@npostavs I suspect this is the crux of the issue. "blade" is my Linux machine. I'm running emacs from an msys environment on Windows where I'm using tramp to access "blade". It seems magit is incorrectly prefixing my repo directory on Linux with "c:/msys64/". The correct directory would be `/plink:blade:/home/abitar/work/my-repo/`

Any idea how I can prevent magit from inserting the "c:/msys64/" prefix?

**Comment by npostavs** [comment]
> Any idea how I can prevent magit from inserting the "c:/msys64/" prefix?

I'm not clear where it's getting added. Can you step through `magit-read-repository`?

**Comment by AndrewBitar** [comment]
Given the backtrace that I pasted above, isn't magit-read-repository never called?

**Comment by npostavs** [comment]
It's called from the `interactive` form of `magit-status`; so the `call-interactively(magit-status nil nil)` would go through there. Oh, but only if `magit-toplevel` returns `nil`. You didn't mention where you call `magit-status` from. Do you have to answer any prompts?
