### ISSUE TITLE
better highlight of diffs

### ISSUE THREAD

**Issue by brandelune** [magit/magit#4156]
I found that ediff has a general highlight for the diffed regions and a darker highlight inside the diffed regions to indicate to the character level what has changed.

I wish magit could have the same kind of display for diff results.

**Comment by MatthewFluet** [comment]
Are you looking for the `magit-diff-refine-hunk` option (https://magit.vc/manual/magit/Diff-Options.html#Diff-Options)?

**Comment by brandelune** [comment]
Ok... Is there a reason why it is not on by default ? I don't think I modified the default ediff settings to get that there.

**Comment by tarsius** [comment]
Performance.
