### ISSUE TITLE
scroll-conservatively over 100 makes actions not center properly.

### ISSUE THREAD

**Issue by mohkale** [magit/magit#4159]
Specifically I've found `magit-stage` and `magit-unstage` in the `magit-status` buffer seems to recenter to put your point at the bottom of the window. Hiding pretty much everything after the entry you've just staged. I've uploaded an asciinema recording of the affects [here](https://asciinema.org/a/RVGqgC2Eoa6aUtMmKC2ae1Lrs).

### Reproduction Instructions
1. run `emacs -q`
2. navigate to a repository with some changed files.
3. enter `M-x magit-status RET`
4. enter `M-: (setq scroll-conservatively 101)`.
5. try staging or unstaging some files.

### Expected Behaviour
window recenters to show the next staged item at either the middle or top.

### Actual Behaviour
window recenters to show the next item at the bottom of the window.

### Version Info
emacs: `GNU Emacs 27.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.17.3) of 2020-06-05`
magit: `Magit 20200617.2306, Git 2.27.0, Emacs 27.0.91, gnu/linux`

**Comment by tarsius** [comment]
Magit has some code to recenter reasonably itself, so if you just dropped `(setq scroll-conservatively 101)`, then odds are things would just work as you expect.

**Comment by mohkale** [comment]
I'm not using `scroll-conservatively` to center, I'm using it to so that when (for example) I'm at the low point of a window and start running `next-line` emacs doesn't just recenter at my current line. Its kind of hard to explain (please see [here](https://asciinema.org/a/T69hBfD0c5s3IfxsPq64wYEf3)), but it lets me scroll instead of the view suddenly changing whenever I go one line past the bottom of the window. For now I've disabled `scroll-conservatively` in magit buffers, but this still feels like a bug.
