### ISSUE TITLE
Stashes are not saved when using envrc

### ISSUE THREAD

**Issue by glasserc** [magit/magit#4160]
I recently started work on a project and I've noticed that pressing `z z` to save a stash is generating "empty" stashes that nevertheless erase my changes. It seems to be an interaction with [envrc](https://github.com/purcell/envrc) although I haven't tracked it down exactly.

Steps to reproduce:

- Add a `.envrc` file to a project. The file can be empty.
- I also add `.envrc` to `.git/config/exclude` so that it won't be considered part of a stash.
- Turn on `envrc-global-mode` and `direnv allow` the file using `envrc-allow`.
- Change a file. I've been adding `Test` to the top of the project's README.
- `magit-status`
- `z z RET`

Expected behavior:

The created stash should have contents.

Actual behavior:

The stash appears empty. Applying it or popping it does not restore the modifications.

![Screenshot from 2020-06-30 10-23-32](https://user-images.githubusercontent.com/17006/86137920-cbdb0280-babb-11ea-95d1-adba0c3f52a3.png)

Other observations:

- A stash is created.
- Doing `git stash` from the command line works OK.
- In `magit-process` for the repository, I see `  0 git … update-ref --create-reflog -m On\ master\:\ 5dcbb9d8\ Need\ to\ set\ up\ autocommit refs/stash b93d90cbf849168ed30d505b77b8830c4e22ff65 ''`.
- Because no error condition is hit, no backtrace is available.
- `magit-version` says `Magit 20200627.806, Git 2.25.1, Emacs 26.3, gnu/linux`
- `magit-debug-git-executable` looks normal (`git` from `/usr/bin/git`, `2.25.1`).
- Everything works correctly if `envrc-global-mode` is off (either never turned on, or turned on and then turned off).
- Everything works correctly if `envrc-global-mode` is on but there is no `.envrc` file in any parent directory.
- Everything works correctly if `envrc-global-mode` is on but the `.envrc` file has not been allowed, or even if an allowed file is denied using `envrc-deny`.

**Comment by tarsius** [comment]
> It seems to be an interaction with envrc although I haven't tracked it down exactly.

Does envrc do anything related to the location of the git datadir and workdir?

**Comment by glasserc** [comment]
I don't *think* so. To the best of my knowledge, it should only be updating the environment, mainly by copying environment variables in. However, I copied `process-environment` before/after and the only variables `envrc` adds are `DIRENV_DIFF`, `DIRENV_DIR`, and `DIRENV_WATCHES`.

Further testing shows that adding the files to the index and then doing `z z` causes the staged file to appear in the stash. It's only unstaged files that are getting lost. I guess that whatever is going wrong must be in `magit-with-temp-index`.

I see that `magit-with-temp-index` uses the `process-environment` variable. I think `envrc` works by making this variable buffer-local. Could that be the problem? I see that `magit-with-temp-index` uses `let`, does that work on buffer-local variables? Is it possible that the buffer in which `process-environment` is being set is different from the one in which the index is actually being written? (For example, maybe something is happening in the process buffer?)

**Comment by tarsius** [comment]
Could be. From [Buffer-Local Variables](https://www.gnu.org/software/emacs/manual/html_node/elisp/Buffer_002dLocal-Variables.html).

>    *Warning:* When a variable has buffer-local bindings in one or more
> buffers, ‘let’ rebinds the binding that’s currently in effect.  For
> instance, if the current buffer has a buffer-local value, ‘let’
> temporarily rebinds that.  If no buffer-local bindings are in effect,
> ‘let’ rebinds the default value.  If inside the ‘let’ you then change to
> a different current buffer in which a different binding is in effect,
> you won’t see the ‘let’ binding any more.  And if you exit the ‘let’
> while still in the other buffer, you won’t see the unbinding occur
> (though it will occur properly)

> Is it possible that the buffer in which `process-environment` is being set is different from the one in which the index is actually being written?

I took a quick look and didn't see that, but that's worth investigating more.

**Comment by tarsius** [comment]
I have taken another look and still didn't find any buffer switching going on. I suspect it is `envrc` that does the buffer switching, which causes the let-bound variables to be lost.

/cc @purcell

**Comment by purcell** [comment]
Thanks for tagging me in. I'll take a look.

**Comment by purcell** [comment]
Hey @glasserc, could you try enabling `envrc-debug`? Then you should get some info in a buffer called something like `*envrc debug*` which might help us figure this out.

**Comment by purcell** [comment]
Actually, it's probably due to the following behaviour of `envrc.el`, which I plan to rework imminently: when `envrc-mode` calls direnv, it applies it (explicitly) to the default value for `process-environment`, not to the any local or `let`-bound version: https://github.com/purcell/envrc/blob/master/envrc.el#L330

That's necessary right now, because it keeps some of the env var merging logic simple and consistent, but ultimately it's wrong. Obviously, in this case, it has the effect of throwing away the `GIT_INDEX_FILE` var when run.

So, sorry about the unfortunate interaction with `magit`. FWIW, I hadn't really noticed it myself yet, despite using magit intensively. I'll look at reworking this code as a matter of urgency.

**Comment by glasserc** [comment]
Great, thank both of you so much. I don't really understand your diagnosis -- why would `envrc` be reloaded in the middle of a stash operation? If it isn't being reloaded then why would it be discarding the `GIT_INDEX_FILE` variable? Also, I could be wrong but I think https://github.com/magit/magit/blob/master/lisp/magit-git.el#L342 is changing buffers. This function is called by [magit-commit-tree](https://github.com/magit/magit/blob/master/lisp/magit-git.el#L2007). Anyhow for now I have a workaround -- mark the envrc file as denied before doing a stash. Thanks again!

**Comment by purcell** [comment]
My thinking was that if the `@,body` of `magit-with-temp-index` creates a new buffer, that buffer will tend to trigger `envrc-mode`, which would mask any `let`-bound `process-environement`. But I absolutely could be wrong.

**Comment by glasserc** [comment]
Just for completion, I killed the `*envrc-debug*` buffer, set `envrc-debug` to `t`, and retried the stash. I got:

```
[*envrc-debug*] reset environment to default
[*envrc-debug*] applied merged environment
[magit-stash: fedora] applied merged environment
```

I'm not sure when the last line happened. Doing `magit-status` adds a `[magit: fedora] applied merged environment` line. Doing the stash itself doesn't appear to add anything.

**Comment by manuel-uberti** [comment]
Thank you @glasserc for reporting this and for the workaround. I didn't think of `envrc-global-mode` when getting this problem.

**Comment by purcell** [comment]
> I didn't think of `envrc-global-mode` when getting this problem.

Oh? I always assume that @purcell guy broke it.

**Comment by manuel-uberti** [comment]
Well, that guy is usually the one fixing Emacs problems IIRC ;)

**Comment by purcell** [comment]
10 FIX PROBLEM
20 CAUSE PROBLEM
30 GOTO 10

**Comment by purcell** [comment]
I believe this is fixed in the above changes I just pushed to `envrc.el`. Please let me know if you experience issues.

**Comment by manuel-uberti** [comment]
I'm going to do more tests later, but on a first quick try the update doesn't seem to have fixed the problem for me. I am still losing my changes when I pop the stash.

**Comment by purcell** [comment]
Hmm, I tested that case locally before posting this. I'll give it another try. :-(

**Comment by purcell** [comment]
Yeah, can confirm. The funny thing is that things are fine when creating a stash from the index (`z i`), but not just a regular stash (`z z`).

**Comment by purcell** [comment]
Okay, that was some fairly epic debugging. It comes down to this Emacs behaviour (verified in 26.3 at least) which feels pretty darned wrong to me:

```el
(let ((process-environment (cons "FOOBAR=baz" process-environment)))
  (with-temp-buffer
    (getenv "FOOBAR")))

;; => "baz"

(with-temp-buffer
  (setq-local process-environment (cons "FOOBAR=baz" process-environment))
  (getenv "FOOBAR"))

;; => "baz"

(with-temp-buffer
  (setq-local process-environment (cons "FOOBAR=baz" process-environment))
  (let ((process-environment process-environment))
    (with-temp-buffer
      (getenv "FOOBAR"))))

;; => "nil"

(with-temp-buffer
  (make-local-variable 'process-environment)
  (let ((process-environment  (cons "FOOBAR=baz" process-environment)))
    (with-temp-buffer
      (getenv "FOOBAR"))))

;; nil
```

This is independent of `envrc-global-mode`, and those last two examples are pretty wild, IMO. @tarsius, maybe you can think of a reason why that behaviour is to be expected? Otherwise I'm inclined to think it's an Emacs bug that has remained undetected due to the rarity of people combining buffer-local and `let`-bound values for `process-environment`.

In the concrete case here, a buffer-local binding is created by `envrc-mode` in the buffer from which the magit stash command is called. Then `magit-with-temp-index` `let`-binds it locally to add `GIT_INDEX_FILE`, but then when `magit-git-items` uses `with-temp-buffer`, the `let`-bound value is lost, as in the final value above, so the invoked `git` process doesn't see that `GIT_INDEX_FILE` var.

Now, of course the above magit behaviour is unlikely to be triggered without using `envrc-mode`, but it's still a potential failure mode given the `with-temp-buffer` quirk. I'd therefore be inclined to patch `magit` to use a variant of `with-temp-buffer` that explicitly propagates the caller's `process-environment` into the temp buffer, but I'm thinking there may also be an Emacs bug report to file here.

**Comment by purcell** [comment]
https://github.com/magit/magit/pull/4169 is a proposed fix for this.

**Comment by manuel-uberti** [comment]
Thank you Steve for going deep into this problem. Also, sorry if I didn't specify that the problem occurs with <kbd>z z</kbd>. It's the only way I stash my changes, I didn't think about another option.

**Comment by purcell** [comment]
Oh, no worries. This was quite an engrossing investigation.

I looked at how `with-temp-buffer` works. In theory I suspect I could work around this issue in a general way in `envrc.el` by advising `get-buffer-create` (!) such that if `envrc-mode` is active in the calling buffer and the buffer needs to be created, then the calling buffer's environment would be explicitly propagated to the new buffer after creation. It seems quite bold to do that, though, and there may be risks that aren't obvious.

**Comment by phil-s** [comment]
This interaction is described in `(elisp)Intro to Buffer-Local`:

>   *Warning:* When a variable has buffer-local bindings in one or more
buffers, ‘let’ rebinds the binding that’s currently in effect.  For
instance, if the current buffer has a buffer-local value, ‘let’
temporarily rebinds that.  If no buffer-local bindings are in effect,
‘let’ rebinds the default value.  If inside the ‘let’ you then change to
a different current buffer in which a different binding is in effect,
you won’t see the ‘let’ binding any more.  And if you exit the ‘let’
while still in the other buffer, you won’t see the unbinding occur
(though it will occur properly).  Here is an example to illustrate:
>
>     (setq foo 'g)
>     (set-buffer "a")
>     (make-local-variable 'foo)
>     (setq foo 'a)
>     (let ((foo 'temp))
>       ;; foo ⇒ 'temp  ; let binding in buffer ‘a’
>       (set-buffer "b")
>       ;; foo ⇒ 'g     ; the global value since foo is not local in ‘b’
>       BODY...)
>     foo ⇒ 'g        ; exiting restored the local value in buffer ‘a’,
>                      ; but we don’t see that in buffer ‘b’
>     (set-buffer "a") ; verify the local value was restored
>     foo ⇒ 'a

**Comment by phil-s** [comment]
You could do this:

```lang-el
(require 'cl-lib)
(with-temp-buffer
  (setq-local process-environment (cons "FOOBAR=baz" process-environment))
  (cl-letf (((default-value 'process-environment) process-environment))
    (with-temp-buffer
      (getenv "FOOBAR"))))
```

**Comment by purcell** [comment]
Right, yes, after (intentionally) debugging it to find out for myself what was going on, I didn't connect it back to that snippet Jonas had posted. I think the workaround in #4169 is still the appropriate one.
