### ISSUE TITLE
Add support for building without libgit

### ISSUE THREAD

**Issue by JohnC32** [magit/magit#4161]
I'm building magit from source by directly compiling the lisp files using the tip as of Jul-27-2020 9e35f989 using Debian 10 with Emacs 26 and would like to build without libgit. Changing magit-libgit.el

    (require 'libgit)

to the following enables building. 

    (require 'libgit nil t)
    (declare-function libgit-repository-open "libgit")
    (declare-function libgit-repository-bare-p "libgit")

Could this (or whatever is appropriate) be added to the repo?

Thanks

**Comment by tarsius** [comment]
Use `BUILD_MAGIT_LIBGIT=false make` or `echo BUILD_MAGIT_LIBGIT=false >> config.mk`.

**Comment by JohnC32** [comment]
I was directly byte-compiling the lisp files (I need to do this because of the way we internally deploy magit on a shared file server). I see the makefiles just skip building magit-libgit.elc, so that what I'll do. Thanks
