### ISSUE TITLE
During git commit facing with fatal: could not read commit message: No such file or directory [help]

### ISSUE THREAD

**Issue by avatar-lavventura** [magit/magit#4163]
I have an interesing issue that I am unable to solve it.

I was using following answer: https://emacs.stackexchange.com/a/57535/18414 to set markdown on the `.git/COMMIT_EDITMSG` file.

```
(add-to-list 'auto-mode-alist
             '("/\\.git/COMMIT_EDITMSG\\'" . markdown-mode))
(setq git-commit-major-mode 'markdown-mode)
```

---

My `.gitconfig` file, to open commit message with `emacs`:

```
[core]
    editor = TERM=xterm-256color emacsclient -t -q
```

---------

On my emacs-daemon `magit-git` was enable. Discussion on [emacs](https://emacs.stackexchange.com/questions/59387/is-it-possible-to-force-markdown-mode-during-git-commit/59390?noredirect=1#comment92916_59390)
        

-------

Now during the commit (due to some squash operations in git), I see the commit messag along with the opened `magit-diff:` window.

Example image: 

[![enter image description here][1]][1]

Afterwards, when I added into `COMMIT_EDITMSG` file and do `C-x C-c`, commit fails and I get following message:

`fatal: could not read commit message: No such file or directory`

But instead if I re-enable `markdown-mode`, save and exit there would be no error.

**[Q]** Is it possible to fix this error somehow?

  [1]: https://i.stack.imgur.com/m0KPm.png

**Comment by tarsius** [comment]
> do `C-s C-x`

Try `C-c C-c` instead.

**Comment by avatar-lavventura** [comment]
Thanks C-c C-c works all fine.

During git commit, I usually squash in to latest commit. For that before the commit I always do ` git reset --soft HEAD~1`. 

By accident if I press `C-x C-c` , I had to do `git reset --soft 'HEAD@{1}'` in order to get back to my latest work. In some cases, I also forget to do that and the history of commits may get mix up.

=>  Some how, is there any way to wrap `C-c C-c` s behavior under `C-x C-s`?

**Comment by tarsius** [comment]
> Some how, is there any way to wrap `C-c C-c` s behavior under `C-x C-s`?

We already try to remap certain keys/commands to that behavior, but I consider `C-x C-s` (`save-buffer`) to do something related but different. Even when using the default end-of-session commands that command is not considered one of them, it does not terminate the session, the client won't be informed.

If you want that, then you can do it in `with-editor-mode-map`, similarly to how it is done for other commands.
