### ISSUE TITLE
Commit fails when working on a worktree over tramp

### ISSUE THREAD

**Issue by crogre** [magit/magit#4165]
When trying to commit a file that's in a worktree (with not .git folder), commit fails with an `error in process filter: Version must be a string` message. Committing in the repository (the worktree with the .git folder) works for me.

Versions: Magit 485ee181564655d21c0770a4e021f7b805f4d643, Git 2.17.1, Emacs 28.0.50, gnu/linux

Back trace:

    Debugger entered--Lisp error: (error "Version must be a string")
      signal(error ("Version must be a string"))
      error("Version must be a string")
      version-to-list(nil)
      version<=("2.19.0" nil)
      magit--insert-diff("diff" nil "-p" "--no-prefix" "--numstat" "--cached" ("--stat" "--no-ext-diff") "--" nil)
      magit-insert-diff()
      apply(magit-insert-diff nil)
      magit-run-section-hook(magit-diff-sections-hook)
      magit-diff-refresh-buffer()
      apply(magit-diff-refresh-buffer nil)
      magit-refresh-buffer()
      magit-setup-buffer-internal(magit-diff-mode nil ((magit-buffer-range nil) (magit-buffer-typearg "--cached") (magit-buffer-diff-args ("--stat" "--no-ext-diff")) (magit-buffer-diff-files nil) (magit-buffer-diff-files-suspended nil)))
      magit-diff-setup-buffer(nil "--cached" ("--stat" "--no-ext-diff") nil)
      magit-diff-staged(nil ("--stat" "--no-ext-diff"))
      magit-commit-diff()
      run-hooks(with-editor-filter-visit-hook)
      with-editor-output-filter("WITH-EDITOR: 122552 OPEN /home/username/work/src/.git/worktrees/version-controlled-data/COMMIT_EDITMSG\37 IN /home/username/work/version-controlled-data\n")
      with-editor-process-filter(#<process git<1>> "WITH-EDITOR: 122552 OPEN /home/username/work/src/.git/worktrees/version-controlled-data/COMMIT_EDITMSG\37 IN /home/username/work/version-controlled-data\n" t)
      (lambda (proc str) (magit-process-filter proc str) (with-editor-process-filter proc str t))(#<process git<1>> "WITH-EDITOR: 122552 OPEN /home/username/work/src/.git/worktrees/version-controlled-data/COMMIT_EDITMSG\37 IN /home/username/work/version-controlled-data\n")

**Comment by tarsius** [comment]
That most likely means that Magit/Tramp/Emacs was unable to locate the `git` executable. Start your adventure from there. :smiley:

**Comment by crogre** [comment]
But magit over tramp when the repository has a .git folder works, wouldn't that indicate that git is found? To clarify, on the remote host I have

  cd work/src # Here is the git repo
  git worktree add ../version-controlled-data # add a new worktree

Remotely, if I edit in `work/src`, I can commit nicely, but if I edit in `work/version-controlled-data`, I get the error above.

**Comment by kyleam** [comment]
I tried with a worktree accessed over tramp via `sudo` and another via `ssh`, and in both cases committed without an issue.

To figure out why `magit-git-version` is returning nil, you could try a combination of stepping through the function call, setting `magit-git-debug` to t and inspecting the process buffer, and checking if calling `git version` from a shell visiting that worktree fails for some reason.
