### ISSUE TITLE
Cannot revert multiple commit hashes with V V

### ISSUE THREAD

**Issue by thomassross** [magit/magit#4166]
Hi,

With the git command line, I'm able to revert two commit hashes with `git revert <commit1> <commit2>`, but I'm not able to do that with `V V` from the status screen. If I type `V V <commit1> SPC <commit2> RET`, the command that Magit runs is `git ... revert <options> <commit1>\ <commit2>`, i.e. it escapes the space which lets git know that I'd like to revert multiple commits. I'd expect it to run `git ... revert <options> <commit1> <commit2>` instead.

**Comment by tarsius** [comment]
This command defaults to act on the commit at point. If the region marks multiple commits, then it acts on those instead.

(Many Magit commands act that way.)

**Comment by thomassross** [comment]
Right, but if you're on the status screen with no commits at the point, it will prompt for (a) commit(s). In this case I'd expect to be able to enter multiple (non-contiguous) commits like I can with the Git CLI and have it work the same way (i.e. not escape the space).

In any case, the problem is that (AFAICT) there is currently no way in Magit to revert multiple non-contiguous/non-adjacent commits.

**Comment by tarsius** [comment]
It prompts for `Revert commit: ` (not `commit(s)`).

I'll stick with the "read a single thing" reader. In most cases that's what is needed and switching to the "read one or maybe several things" reader would have drawbacks that would make the common workflow somewhat more cumbersome.

I'm afraid you'll have to invoke the command multiple times.
