### ISSUE TITLE
Idea: consider support for git-revise

### ISSUE THREAD

**Issue by aspiers** [magit/magit#4167]
(This is just an idea - I certainly wouldn't complain if it's rejected and closed.  Perhaps it makes more sense as some kind of module extension anyway.)

I recently discovered [git-revise](https://mystor.github.io/git-revise.html), which looks like a very nice in-memory partial alternative to `git rebase` which is faster for specific use cases, such as a simple fixup + rebase.  Would it be worth adding some kind of support to magit for this?  For example, if magit is asked to do an instant fixup, it could check whether git-revise is available, and if so, use that for better performance.

Of course, it would have to be optional, falling back to the normal behaviour if it wasn't available.  And it's not a general rebase replacement either.

Food for thought!

**Comment by tarsius** [comment]
> For example, if magit is asked to do an instant fixup, it could check whether git-revise is available, and if so, use that for better performance.

Well that sounds nice but I wonder if it is worth the added complexity. Also I wonder whether "conflicts are resolved interactively" means we get to use the awful `git ... -p ...` interface instead of getting a chance to use magit to do it in style. Some of the quality of live improvements sound nice.

For now my answer is: not any time soon.

**Comment by aspiers** [comment]
Agreed that `git add -p` is terrible! :rofl:  Yes, I also wonder if it is worth it.  If I get more familiar with `git-revise` I will return here and provide extra thoughts.

**Comment by tarsius** [comment]
I've reread some of the documentation and concluded that while this is a nice effort to improve upon `git rebase`, this is not a good fix for Magit. Not touching the index and worktree is a nice feature (speed, safety) but it also makes it much harder to build an alternative UI on top of it.
