### ISSUE TITLE
Title: magit-clone-regular

### ISSUE THREAD

**Issue by tvraman** [magit/magit#4168]
Description:

The asynchronous nature of magit-clone-regular means that the y-or-n-p prompt
that appears re  tracking upstream comes much later, ie after the clone has
finished. A better experience would be to prompt for that y-or-n-p before
starting the clone, so that the user can just leave it go do its thing?

**Comment by tarsius** [comment]
Thanks for the suggestion.

**Comment by tvraman** [comment]
thanks for magit as ever:-)
--
