### ISSUE TITLE
Crashes when rebase interactively in emacs-native-comp

### ISSUE THREAD

**Issue by 404cn** [magit/magit#4170]
Please explain
    (1) what behavior you expected
    popup rebase window
    (2) what behavior you observed
    exit
    (3) and how we can reproduce the issue.
    archlinux emacs-nativecomp, then use magit to rebase interactively

Please include a backtrace in your report.  In most cases doing:

    exit. can not do this

and then going through the steps again should result in a backtrace.

Also post the output of:

    20200706.1352

**Comment by tarsius** [comment]
Are you saying that Emacs *crashes* if you try to open the rebase popup by pressing <kbd>r</kbd> in some Magit buffer?

**Comment by 404cn** [comment]
> Are you saying that Emacs _crashes_ if you try to open the rebase popup by pressing r in some Magit buffer?

Yes, ```r``` then press ```i```.

Sorry for my pool english. 😭️

**Comment by phil-s** [comment]
https://akrl.sdf.org/gccemacs.html is somewhat unstable at present, as I understand it.

What does `M-x emacs-version` report?  And what is the value of `C-h v emacs-repository-version`?

**Comment by 404cn** [comment]
> https://akrl.sdf.org/gccemacs.html is somewhat unstable at present, as I understand it.
> 
 What does `M-x emacs-version` report? 
![emacsversion](https://user-images.githubusercontent.com/24653356/87623615-5f693000-c758-11ea-927f-369778b2c680.png)

And what is the value of `C-h v emacs-repository-version`?
![repo-version](https://user-images.githubusercontent.com/24653356/87623620-63954d80-c758-11ea-908a-b0570ba7148c.png)

**Comment by basil-conto** [comment]
> https://akrl.sdf.org/gccemacs.html is somewhat unstable at present, as I understand it.

If something, e.g. Magit, doesn't work properly on the `feature/native-comp` branch, but it does on `master`, then it's very likely a bug in `feature/native-comp`, not in Magit, and should be reported appropriately upstream.

**Comment by tarsius** [comment]
Yes, please report this issue to Andrea. At this stage such reports are probably very useful.
