### ISSUE TITLE
Support regions in git-rebase-kill-line

### ISSUE THREAD

**Issue by Stebalien** [magit/magit#4172]
To reproduce, open the interactive rebase buffer, highlight a region of commits to remove, then run `git-rebase-kill-line`. Currently, this will kill the commit on the next line, not the commits in the selected region. I'd expect it to kill all selected commits.

**Comment by aesyondu** [comment]
Same, I'm doing something like this:

<img width="117" alt="image" src="https://user-images.githubusercontent.com/57334943/96336703-3b4d2000-10b4-11eb-8553-abc135d51f05.png">

GIVEN BRANCHES master AND feature

WHEN CHECKOUT master (lb + mov to master + bb)
WHEN REBASE -INTERACTIVELY ELSEWHERE (mov to feature + r-ie)
WHEN SELECT ALL LINES EXCEPT LAST LINE (C-SPACE nnnnnnn)
WHEN DROP (k)

THEN all selected lines should be dropped.

----

Or maybe I'm doing it the wrong way and there is a much better way? I basically want to move the commit that the branch points to to a separate branch (picking), while hard resetting the branch there at the same time.

```
From this:
A - B - C (master)
  \
    - D (feature-other) - E (feature)

To this:
A - B - C (master) - E (feature)
  \
    - D (feature-other)
```

**Comment by kyleam** [comment]
> Or maybe I'm doing it the wrong way and there is a much better way?

I think `magit-rebase-subset` (<kbd>rs</kbd>) would work nicely for your situation.

---

Teaching `git-rebase-kill-line` (and other related commands) to act on the region makes sense to me, though it's also not an itch I've ever had (despite having a pretty rebase-heavy workflow).  A few weeks ago a started putting something together for this.  I _think_ it was mostly working but had some rough edges.  Anyway, I'll try to revisit it soon-ish.

**Comment by aesyondu** [comment]
Works nicely, thanks for the tip!
