### ISSUE TITLE
Stash selections in magit status

### ISSUE THREAD

**Issue by rgrinberg** [magit/magit#4174]
There's an incredibly useful for staging/unstaging selections via the status buffer. It would be nice if it was extended to stashes. In particular, I find myself often wanting to stash a selection. There are workarounds for this. For example unstage everything, stage the selection you want to stash, and then stash only the staged area. It's obviously very cumbersome however.

**Comment by tarsius** [comment]
So what you are saying it that you want to stash a subset of the uncommitted changes while two other subsets already exist -- the staged and the unstaged changes -- but the subset that you want to stash is not identical to either one of these existing subsets, right?

(If the to-be-stashed set is identical to either the staged or unstaged changes, then there already are commands for doing just that.)

Implementing the feature you ask for is much more difficult than it might look like at first sight. A secondary index would have to be used. The likelihood of conflict increases between the various subsets increase. If a conflict occurs then the only option is to say "I'm Afraid I Can't Do That, Dave."

I am sorry but I don't want to do this.

**Comment by rgrinberg** [comment]
> but the subset that you want to stash is not identical to either one of these existing subsets, right?

That's right.

> (If the to-be-stashed set is identical to either the staged or unstaged changes, then there already are commands for doing just that.)

Here's another suggestion that should be much simpler: What about adding a `stash-this` that will either stash all unstaged or all staged changes depending on the section the cursor is pointing to. I know there is `Z{i,w,x}` for doing just that, but it's quite to remember which one is which (at least for me).

> I am sorry but I don't want to do this.

No worries. Thanks for the serious consideration.

**Comment by tarsius** [comment]
> What about adding a `stash-this` that will either stash all unstaged or all staged changes depending on the section the cursor is pointing to.

To me this feels different from other places where we do similar things. But here's an implementation of that idea (untested):

```elisp
(defun magit-stash-dwim (message &optional include-untracked)
  (interactive (magit-stash-read-args))
  (magit-section-case
    ([* staged]   (magit-stash-index    message))
    ([* unstaged] (magit-stash-worktree message include-untracked))
    (t            (magit-stash-both     message include-untracked))))
```

**Comment by rgrinberg** [comment]
I just tried it out and it works great! Thank you so much.

**Comment by tarsius** [comment]
You're welcome!
