### ISSUE TITLE
magit-section-position-in-heading-p: Wrong type argument: number-or-marker-p, nil

### ISSUE THREAD

**Issue by DamienCassou** [magit/magit#4181]
In Emacs 27, in a status buffer with changes visible, navigating the buffer (with normal cursor movements), I get an error. I've just updated to Emacs 27 so this might be related.

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  (< 148 nil)
  (and section (>= pos (eieio-oref section 'start)) (< pos (or (eieio-oref section 'content) (eieio-oref section 'end))) t)
  (magit-section-position-in-heading-p)
  (magit-next-line 1 1)
  (funcall-interactively magit-next-line 1 1)
  (call-interactively magit-next-line nil nil)
  (command-execute magit-next-line)
```

This happens in the last part of `magit-section-position-in-heading-p` (within the `or` and the 2 `oref` calls):

```emacs
(defun magit-section-position-in-heading-p (&optional section pos)
  "Return t if POSITION is inside the heading of SECTION.
POSITION defaults to point and SECTION defaults to the
current section."
  (unless section
    (setq section (magit-current-section)))
  (unless pos
    (setq pos (point)))
  (and section
       (>= pos (oref section start))
       (<  pos (or (oref section content)
                   (oref section end)))
       t))
```

Magit v2.90.1-1030-g798aff56, Git 2.27.0, Emacs 27.1, gnu/linux

I don't have any recipe to reproduce so you might just want to close the issue :-).

**Comment by tarsius** [comment]
`end` is always an integer unless an error occurred while the section was being created.

The error during navigation is only a symptom. We need to address that other error that occurs then the buffer is being populated--whatever that might be.

**Comment by DamienCassou** [comment]
It happened again today (and it didn't during 2 months). I was having a look at the revision of a very large commit (9000 changed lines): because it was taking too long, I pressed `C-g` to stop building the nice diff but I still wanted to have a look at the content.

**Comment by tarsius** [comment]
This is somewhat expected. If you abort refreshing the current buffer, then the buffer will end up in an inconsistent state and as a result some things will break. I don't see what can be done about short of making it unnecessary to abort in the first place.

**Comment by DamienCassou** [comment]
Would it be possible to make navigation commands capable of going outside broken sections?

**Comment by zenspider** [comment]
This fixes navigation:

```elisp
(defun magit-section-position-in-heading-p (&optional section pos)
  "Return t if POSITION is inside the heading of SECTION.
POSITION defaults to point and SECTION defaults to the
current section."
  (unless section
    (setq section (magit-current-section)))
  (unless pos
    (setq pos (point)))
  (and section
       (>= pos (oref section start))
       (<  pos (or (oref section content)
                   (oref section end)
                   pos))                              ; ensure we have a valid result
       t))
```
