### ISSUE TITLE
Provide a way to disable header-line info thing

### ISSUE THREAD

**Issue by andreyorst** [magit/magit#4184]
Magit has few settings regarding header-line in its customize section:

![image](https://user-images.githubusercontent.com/19470159/89455874-a81a7480-d76b-11ea-922e-0b5d8e8dbc9a.png)

However there's no way to completely disable this behavior. I'm not a big fan of it, as I use tabs from Emacs 27, and header line in Magit is styled like a tab itself:

![image](https://user-images.githubusercontent.com/19470159/89456043-efa10080-d76b-11ea-9809-0ed8a6f0ab63.png)

![image](https://user-images.githubusercontent.com/19470159/89456101-07788480-d76c-11ea-8fd8-64b865e76f6a.png)

Ideally I'd like to use Tab to display this info instead, by changing buffer names `magit-log: <project> commits in <branch>`, and `magit-diff: <project> staged changes`, **but** this feature request is mostly for ability to simply turn this thing off.

I can customize function `magit-log-header-line-function` to use `ignore` function, but it still produces empty header-line (small blue rectangle in the upper right corner):

![image](https://user-images.githubusercontent.com/19470159/89456378-748c1a00-d76c-11ea-99ea-245492e94840.png)

And does not seem to affect some buffers at all:

![image](https://user-images.githubusercontent.com/19470159/89456439-8a014400-d76c-11ea-9272-763fb5caeb94.png)

Which seems like a bug on itself.

**Comment by kyleam** [comment]
Disabling the headers would lose information, and in my view Magit shouldn't add an option for removing the header unless that information is exposed in another way.

Users that really don't want the header can remove it with something like

```
(advice-add 'magit-set-header-line-format :override #'ignore)
```

**Comment by andreyorst** [comment]
>Disabling the headers would lose information, and in my view Magit shouldn't add an option for removing the header unless that information is exposed in another way.

That's why I mentioned alternative format for buffer names.

**Comment by kyleam** [comment]
> That's why I mentioned alternative format for buffer names.

You did, emphasizing that the feature request is "mostly for ability to simply turn this thing off".  I don't think such an option should come on its own.  As for tacking the header information onto the buffer name, I wonder if there would often be too little real estate.  And, without looking too closely, I wouldn't be surprised if reworking the code to do so would involve some substantial changes, including much more frequent buffer renames (e.g., when moving point in the log buffer and updating the corresponding revision buffer).

Also, your reason for not liking the header line is that it's "styled like a tab itself".  Isn't that mostly about the face's background?  Wouldn't tweaking the face help?

**Comment by tarsius** [comment]
The "align the right side" implementation in `magit-set-header-line-format` does not appear to work anymore. The background color is supposed to extend to the edge of the window. This would work thought:

```elisp
(defun magit-set-header-line-format (string)
  (setq header-line-format
        (concat (propertize " " 'display '(space :align-to 0))
                string))
  (face-remap-add-relative 'header-line 'magit-header-line))
```

We shouldn't remap the face elsewhere but for testing this is good enough.

@andreyorst If you use the above definition, do you cease to dislike seeing this information as part of the buffer?

**Comment by andreyorst** [comment]
> Also, your reason for not liking the header line is that it's "styled like a tab itself". Isn't that mostly about the face's background? Wouldn't tweaking the face help?

I'm sorry, I should have doublechecked this, as I've thought that this is Magit's intention, but perhaps, this is the themer decision (as it was this way way before the `:extend` attribute was added)

>@andreyorst If you use the above definition, do you cease to dislike seeing this information as part of the buffer?

Yes, this is better, but I guess I just have to tweak the theme I'm using, and this is not an issue with Magit at all. Sorry for the buzz
