### ISSUE TITLE
cherry-pick --continue, --skip, --abort not available

### ISSUE THREAD

**Issue by agzam** [magit/magit#4192]
It seems cherry-pick actions are not available when cherry-pick is in progress.

repro steps:

- chose a branch with commit(s) that guaranteed to have conflicts with current
- cherry-pick
- run `git status` in terminal. Make sure it says: `Cherry-pick currently in progress.`

Expected behavior:

- pressing `A` should allow to continue, skip or abort (it currently doesn't seem to)

**Comment by tarsius** [comment]
Works for me.

**Comment by agzam** [comment]
Hmmm... my apologies for the false alarm then. I'll check what's wrong on my system. Thank you Jonas! Closing it for now.
