### ISSUE TITLE
Rebase and squash all commits on feature branch relative origin (master) branch with a single commit message

### ISSUE THREAD

**Issue by nordlow** [magit/magit#4193]
The typical way of finishing a Github pull request is to do 

    git rebase -i <MASTER_BRANCH>

squash all commits into a single commit followed by editing commit message buffer to contain only one commit.

`magit-rebase-autosquash` doesn't quite do this.

I would like to have a similar command that

- Asks for branch to perform rebase from (defaulting to branch current branch was branched off from).
- Squashs all commits from feature branch into one commit _automatically_,
- Asks for a commit message (maybe defaulting to first message among the squashed commits or bringing up a buffer show all the commits line by line), finally
- Does a commit with that message

I haven't found that many git aliases that do this either. It would be great if Magit had an interactive function for this.

**Comment by tarsius** [comment]
> The typical way of finishing a Github pull request is to do
> 
> ```
> git rebase -i <MASTER_BRANCH>
> ```
> 
> squash all commits into a single commit followed by editing commit message buffer to contain only one commit.

This is an exceptionally awful way to bring changes into the mainline. I am aware that Github provides that as one of their "merge" methods and that other people and projects that are not completely clueless recommend or even enforce this workflow. They are wrong. Teaching people that doing this is okay or even the right thing to do is reckless.

I don't feel like explaining why that is so. There must be hundreds of blog posts out there that do just that. (And many others that explain why it is a good thing -- though hopefully fewer than the posts against it.)

> It would be great if Magit had an interactive function for this.

This is not going to happen. Except in a few rare cases I try to keep Magit as unopinionated as possible. This is one of those exceptions. I have such a strong opinion about this method being plain wrong, that I would not want to risk that someone might think that I am not fundamentally against it. Just reading this proposal made my pulse spike and I had to reply immediately.

Very very very seldomly it is okay to "squash merge". So seldom in fact, that we don't need a dedicated command for that.

Sorry.

**Comment by nordlow** [comment]
No problem. Thanks for your advice.

**Comment by tarsius** [comment]
Cheers! :wink:
