### ISSUE TITLE
magit-rebase-remove-commit does not work on latest commit

### ISSUE THREAD

**Issue by mithrandi** [magit/magit#4195]
Selecting the latest commit results in "error: nothing to do" from git. Since there is nothing to be rebased but rather the branch must just be reset, this makes sense, but I couldn't quite find a convenient method using the reset UI, and as a user it would be nice to use the same method in both cases.

**Comment by kyleam** [comment]
> noop was in fact added in git 1.6.0.3

Thanks for digging.
