### ISSUE TITLE
Issue when magit-after-save-refresh-status hook.

### ISSUE THREAD

**Issue by Ergus** [magit/magit#4196]
Hi:

When I add this line to my config: `(add-hook 'after-save-hook 'magit-after-save-refresh-status t)`

Every time I save a relative long file the buffer moves to some random place close to the beginnining of the buffer. After some debugging I got that:

`magit-refresh-buffer` calls `magit-section-goto-successor` for the current window (I don't really understand why) with a very long `args`. And then `magit-section-goto-successor-hook` produces the undesired scroll because of some problem in `magit-hunk-goto-successor` parsing the long input.

I tried to debug a bit more but the `args` there is huge and I don't understand exactly what it does. it looks like this (but much much longer):

```
#s(magit-hunk-section hunk (nil (8743 7) (8728 100)) #<marker (moves after insertion) at 9982 in magit: emacs> #<marker at 1 in magit: emacs> #<marker at 1 in magit: emacs> nil nil nil nil ((magit-status-sections-hook magit-insert-unstaged-changes)) #s(magit-file-section file lisp/simple.el #<marker (moves after insertion) at 9982 in magit: emacs> #<marker at 1 in magit: emacs> #<marker at 1 in magit: emacs> nil nil nil nil ((magit-status-sections-hook magit-insert-unstaged-changes)) #s(magit-section unstaged nil #<marker (moves after insertion) at 9982 in magit: emacs> #<marker at 1 in magit: emacs> #<marker at 1 in magit: emacs> nil nil nil nil ((magit-status-sections-hook magit-insert-unstaged-changes)) #s(magit-section status nil #<marker (moves after insertion) at 9982 in magit: emacs> nil #<marker at 1 in magit: emacs> nil nil nil nil nil nil (#s(magit-section branch WIP_icomplete #<marker (moves after insertion) at 9982 in magit: emacs> #<marker (moves after insertion) at 9982 in magit: emacs> #<marker at 1 in magit: emacs> nil nil nil nil ((magit-status-headers-hook magit-insert-head-branch-header) (magit-status-sections-hook magit-insert-status-headers)) #3 (#s(magit-section tag emacs-27.1 #<marker (moves after insertion) at 9982 in magit: emacs> nil #<marker at 1 in magit: emacs> nil nil nil nil ((magit-status-headers-hook magit-insert-tags-header) (magit-status-sections-hook magit-insert-status-headers)) #5 nil))) #s(magit-section untracked nil #<marker (moves after insertion) at 9982 in magit: emacs> #<marker at 1 in magit: emacs> #<marker at 1 in magit: emacs> nil nil nil nil ((magit-status-sections-hook magit-insert-untracked-files)) #3 (#s(magit-file-section file build_arch/ #<marker (moves after insertion) at 9982 in magit: emacs> nil #<marker at 1 in magit: emacs> nil nil nil nil ((magit-status-sections-hook magit-insert-untracked-files)) #5 nil nil nil) #s(magit-file-section file build_debian/ #<marker (moves after insertion) at 9982 in magit: emacs> nil #<marker at 1 in magit: emacs> nil nil nil nil ((magit-status-sections-hook magit-insert-untracked-files)) #5 nil nil nil) #s(magit-file-section file build_native/ #<marker (moves after insertion) at 9982 in magit: emacs> nil #<marker at 1 in magit: emacs> nil nil nil nil ((magit-status-sections-hook magit-insert-untracked-files)) #5 nil nil nil)
```

To reproduce the issue I just 
1) added that hook line in the magit configuration 
2) edited a long file (like simple.el in emacs sources) 
3) Added some lines and save.
4) M-x magit-status
5) Go to the changes and RET to go to the file.
6) Add some lines again and save.

I have notice that the "jump" mainly happens when I went to the buffer file throw `magit-diff` buffer and the changes add new lines.

I added some lines around line 8700 and after saving It goes to line 169.

**Comment by tarsius** [comment]
> because of some problem

How does the "problem" manifest itself? If it involves a backtrace, then please post that.

**Comment by tarsius** [comment]
> a very long `args`

I think that argument is named `section` and it is an object that represents the section that was current before the refresh. Part of refreshing the buffer involves putting the cursor on the same object as before but because the buffer content was erased it isn't actually the *same* section anymore, its is merely the *successor*, i.e. an object that represents the same piece of data (e.g. a hunk), but is a different object.

**Comment by Ergus** [comment]
> > because of some problem
> 
> How does the "problem" manifest itself? If it involves a backtrace, then please post that.

Hi:

There is not backtrace sorry. The `error` is that the buffer looses the current "position"; the cursor (point) moves to some random line (usually much closer to the beginning of the buffer scrolling it and forcing me to search again where I was before... which is very annoying. (in the example as said it goes from line 8700 to line 169). This is worst when working with multiple files because I need to search again for all of them.

I said that I don't understand the error, because I don't know the reason why a simple text buffer needs to move at all after a save. I have usually enable auto-revert-mode and emacs does not looses the buffer position after a refresh. But I suppose magit has a reason to need that.

Very thanks in advance

**Comment by tarsius** [comment]
I've had similar issues before myself but couldn't narrow it down because it always stopped happening when I tried figuring out what was going on. Also because nobody else was reporting anything I figured it didn't have anything to do with Magit but was due to something in my personal setup.

How sure are you that the things you talked about so far are actually to be blamed?

> I don't know the reason why a simple text buffer needs to move at all after a save

It doesn't.

I didn't register that the undesired jumping happens in the file-visiting buffer (not in the magit diff/status/... buffer).

**Comment by Ergus** [comment]
> How sure are you that the things you talked about so far are actually to be blamed?
 
When I remove the hook the problem goes away and after some debug I located the issue up to the function I mention in the first message. I also tried a simplified version of my config with only magit (almost) and I can reproduce the issue with the steps I mentioned before.

> > I don't know the reason why a simple text buffer needs to move at all after a save
> 
> It doesn't.
> 
> I didn't register that the undesired jumping happens in the file-visiting buffer (not in the magit diff/status/... buffer).

In `magit-refresh-buffer` the (apply refresh (with-no-warnings magit-refresh-args))  happens for that buffer too. Is this expected?

**Comment by tarsius** [comment]
This might help me figure out what's going on. But I probably won't find the time to investigate before the weekend.

**Comment by tarsius** [comment]
I was unable to reproduce using these steps. Please try to make them more precise.

> 5. Go to the changes and RET to go to the file.
> 6. ...
> 
> I have notice that the "jump" mainly happens when I went to the buffer file throw magit-diff buffer and the changes add new lines.

Adjust (5) taking this remark into account. Also specify where exactly "in the changes" you press RET. Does it make a difference if you are on the file or hunk heading, or on a added/removed/context line.

**Comment by Ergus** [comment]
Hi:

I press `RET` in in the added lines to go to the actual version of the changed text file. (If `RET` is made in the removed lines magit opens the old version of the file and step 6 cannot be executed because that buffer is read only)

**Comment by tarsius** [comment]
What about your remark about "magit-diff buffer"? Does it make a difference if you press RET while inside the diff inside the `magit-status-mode` buffer or inside the `magit-diff-mode` buffer?

**Comment by geza-herman** [comment]
This issue still happens for me, version is magit-20210304.1456.
The selected window was my source file, not magit-status. I just executed the evil command ":w" to save the file (or I pressed my save shortcut, which does the same thing, I don't remember).
It seems (?) that set-window-start is intended to move window position in magit-status, but instead it moved the position my window?
(the magit-status buffer was not visible, but if after unhide magit-status window and select that window, the cursor was standing on a diff-hunk header)

Here's the backtrace:
```
Debugger entered--entering a function:
* set-window-start(#<window 600 on t.cpp> #<marker (moves after insertion) at 2433 in magit: polylib (master)> nil)
  magit-section-set-window-start(#<magit-hunk-section (nil (484 7) (505 7)) [hunk file unstaged status] 2433-[2533-]2752>)
  magit-hunk-set-window-start(#<magit-hunk-section (nil (484 7) (505 7)) [hunk file unstaged status] 2433-[2533-]2752>)
  magit-section-goto(#<magit-hunk-section (nil (484 7) (505 7)) [hunk file unstaged status] 2433-[2533-]2752>)
  magit-hunk-goto-successor(#<magit-hunk-section (nil (484 7) (506 7)) [hunk file unstaged status] 3482-[1-]1> nil)
  run-hook-with-args-until-success(magit-hunk-goto-successor #<magit-hunk-section (nil (484 7) (506 7)) [hunk file unstaged status] 3482-[1-]1> nil)
  magit-section-goto-successor(#<magit-hunk-section (nil (484 7) (506 7)) [hunk file unstaged status] 3482-[1-]1> 0 0 nil)
  magit-refresh-buffer()
  magit-after-save-refresh-buffers()
  run-hooks(post-command-hook)
  evil-ex-call-command(nil #("w" 0 1 (ex-index 1)) nil)
  eval((evil-ex-call-command nil #("w" 0 1 (ex-index 1)) nil))
  evil-ex-execute(#("w" 0 1 (ex-index 1)))
  evil-ex(nil)
  funcall-interactively(evil-ex nil)
  command-execute(evil-ex)
```

**Comment by tarsius** [comment]
Add a debug statement to `magit-after-save-refresh-buffers` printing all the values `buffer` takes.

**Comment by geza-herman** [comment]
It only prints the magit-status buffer.

I found a way how to reproduce a similar (same?) issue:
 - modify a file which is under git control (add a new line with some text to it), save it
 - go to magit-status, find the file under "unstaged changes", go to the hunk which represents the modification done at the previous step, place the cursor under the line which has "+" in the front
 - press C-RET (which calls magit-diff-visit-worktree-file). This will cause that the file will be displayed in the window where magit-status was
 - modify the file again (add a new line to it), and save it. Now the cursor will jump somewhere at the beginning.

It seems that magit thinks that the window is still used by magit-status, so it tries to move the cursor back into the position where it was before the refresh in the magit-status window.

**Comment by tarsius** [comment]
Interesting...

**Comment by tarsius** [comment]
Thanks everyone! Your reports helped me to finally figure out what was going on.
