### ISSUE TITLE
Show stash description in magit-stash-apply selection menu

### ISSUE THREAD

**Issue by Atemu** [magit/magit#4198]
By default, it only shows the stash "name" as `stash@{0}` etc. These aren't very useful unless you know how often you've stashed since the stash you're trying to apply. The stash descriptions are a lot more expressive and at worst (default description left in place) it's as useless as `stash@{n}` IMO.

You can expand the "Stashes" section, see the descriptions there and also apply them but I find getting there rather inconvenient (not as convenient as pressing `z a` from anywhere in the magit buffer).

It'd be even better if we could customise which stash information is shown in this menu through a variable (I couldn't find any existing one).

**Comment by Atemu** [comment]
You're amazing, thank you!

**Comment by tarsius** [comment]
You're welcome!
