### ISSUE TITLE
magit-reshelve-since doesn't honor the commit.gpgsign git option

### ISSUE THREAD

**Issue by erikmd** [magit/magit#4199]
### Description

[This report is a follow-up of the discussion in #4101, dealing with `(magit-reshelve-since)`]

when rebasing PRs on GitHub, I often use:

* `M-x magit-shelve-since RET`
* or `M-: (setq magit-reshelve-since-committer-only t) RET M-x magit-shelve-since RET`

Also, I contribute to some repositories that have the git-config option [`commit.gpgsign`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-commitgpgSign) enabled.

So I was expecting that the `(magit-reshelve-since)` function honors this option, but this is not yet the case.
This is then an issue if the upstream repository also [requires commit signing](https://docs.github.com/en/github/administering-a-repository/about-required-commit-signing).

### How to reproduce the issue

```
# Create a repo with 2 signed commits:
$ mkdir repo && cd repo && git init && git config commit.gpgsign true
$ for text in foo bar; do echo "$text" >> file.txt && git add file.txt && git commit -m "Update file.txt"; done

# cf. https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work#_signing_commits
$ git log --pretty="format:%h %G? %aN  %s"
712ca2d G Firstname Lastname  Update file.txt
8e30c67 G Firstname Lastname  Update file.txt

# Run (magit-reshelve-since)
$ emacs .
  M-x magit-reshelve-since RET C-c C-c RET
  C-x C-c

# We get "N" instead of "G":
$ git log --pretty="format:%h %G? %aN  %s"
f44fe90 N Firstname Lastname  Update file.txt
8e30c67 G Firstname Lastname  Update file.txt
```

### Magit version

`Magit 20200825.1251, Git 2.11.0, Emacs 25.1.1, gnu/linux`

**Comment by tarsius** [comment]
This command uses `git filter-branch` and the documentation of that mentions that it is "by definition not possible to preserve signatures". (it does that while discussing signed tags, not signed commits, which it doesn't mention, but given the wording it is clear that this is also considered "not possible".

Of course that is only true for signatures by other people, not your own, but since `git filter-branch` is a tool primarily intended to rewrite "all" history, not just some recent commits authored by the person who does the rewriting, it is not surprising that it takes this stance.

As long as we use `git filter-branch` we cannot do anything about this.

**Comment by erikmd** [comment]
OK I see, thanks for your reply.

**Comment by erikmd** [comment]
Hi @tarsius,
on second thought it seems the `--commit-filter` option of `git filter-branch` may be used to enforce a signature for all rewritten commits by the commiter: cf. [this StackOverflow answer](https://stackoverflow.com/a/41883164/9164010) which relies on the command below to sign commits:

```
git filter-branch --commit-filter 'git commit-tree -S "$@";' -- #etc.
```

so do you believe that adding a bool. option `magit-reshelve-since-gpg-sign` or so (`nil` by default) to make `magit-reshelve-since` pass `"--commit-filter" "git commit-tree -S \"$@\";"` as extra args would be working?

**Comment by tarsius** [comment]
Just signing all commits actually sounds like a good idea. I didn't think of that and was worrying about the complexities of figuring which commits are signed or not and by whom etc.

I think it would make sense for a prefix argument to mean "use the additional arguments" and to add an option that specifies those arguments. It's doc-string could mention this use-case as demonstrate how to get the quoting right.

Do you want to take a stab at this?

**Comment by erikmd** [comment]
Hi @tarsius, OK thanks, I'm willing to have a look when I have time.

But to clarify, by `an option that specifies those (additional) arguments`, did you mean:
1. an option containing `'("--commit-filter" "git commit-tree -S \"$@\";")`
2. or an option containing `"-S"` ?

At first sight I'd say 2. is preferable (as it's less risky w.r.t. clashing other CLI filters, and suffices anyway for this use case :)

WDYT?

**Comment by tarsius** [comment]
The latter. Probably.

**Comment by erikmd** [comment]
Hi @tarsius,
I've just take another look at this issue, and it seems you implemented in 05bff21683aae893253da5699c5178a8b2482b78 the feature I had suggested :+1: (in which case, maybe the `wontfix` label on this issue #4199 can be removed :)

However, I am unsure how the command is intended to be used interactively:

* To be more precise, <kbd>M-: (magit-reshelve-since nil t)</kbd> works,
* while using a prefix argument does not work: <kbd>C-u M-x magit-reshelve-since RET</kbd>.
* The docstring says:
  ```
  (magit-reshelve-since REV KEYID)
  …
  If KEYID is non-nil, then use that to sign all reshelved commits.
  Interactively use the value of the \"--gpg-sign\" option in the
  list returned by `magit-rebase-arguments'.
  ```
  but I wasn't able to figure out how `magit-rebase-arguments` should work in the perspective of `magit-reshelve-since` :sweat_smile:

**Comment by tarsius** [comment]
While it isn't technically build on `git rebase`, this command is nevertheless available from the rebase popup. So use `r t` to invoke it.

While the popup is active you have to option to enable arguments as usual. This command respects `--gpg-sign` if present, but ignores all others. You can enable this option and then save the enabled options using (`C-x C-s`). This will affect this command but also all rebase commands.

**Comment by erikmd** [comment]
Thanks a lot, @tarsius!
But then, I don't understand why `r t` does not work in my case: I get `Unbound suffix: 't'`, cf. the screenshot below.
(Regarding my config: I have Magit from MELPA − `magit-20210616.1958` − and GNU Emacs 26.1)

![2021-06-19_13-14-34_Screenshot_Unbound_suffix](https://user-images.githubusercontent.com/10367254/122640542-6fc02280-d100-11eb-95c7-c30bf1c33210.png)

**Comment by tarsius** [comment]
Certain transient popups hide some of their suffix commands by default. These additional suffixes can be [enabled interactively](https://magit.vc/manual/transient/Enabling-and-Disabling-Suffixes.html). TL;DR Enter the transient as usual and type <kbd>C-x l</kbd>.

<sub>This is a [canned response](https://help.github.com/en/github/writing-on-github/working-with-saved-replies); it may not apply 100% in this case.</sub>

**Comment by erikmd** [comment]
Awesome! makes a lot of sense. Thank you very much for the tip, @tarsius :)
