### ISSUE TITLE
Deleting multiple branches in magit-show-refs buffer is very slow (several minutes)

### ISSUE THREAD

**Issue by jsravn** [magit/magit#4200]
Version: `Magit 798aff56457aef4d1896db8129ab56d08ae12066, Git 2.25.4, Emacs 27.1, gnu/linux`

Deleting branches is very slow in magit-show-refs. If I delete a dozen branches, which is instant on the command line, it can take 3-5 minutes inside of magit.

From running a profile, it looks like all the time is spent refreshing the show-refs buffer. This repo has thousands of tags and it's very slow to render them in magit. I'm guessing it should only have to refresh once, but is it refreshing on each branch delete?

![image](https://user-images.githubusercontent.com/522123/91463700-9bc59b00-e883-11ea-9e90-51af1984f2f0.png)

**Comment by tarsius** [comment]
> I'm guessing it should only have to refresh once, but is it refreshing on each branch delete?

I don't think so.

You can confirm that yourself by comparing how long it takes to show the buffer initially and how long it takes to delete a bunch of repositories. `M-x magit-toggle-verbose-refresh` should help with that.

> This repo has thousands of tags and it's very slow to render them in magit.

Yes. Most repositories have much fewer tags so it is a good default to show them all. Of course it is possible to forgo showing them when there's too many of them. The FAQ mentions [this page](https://magit.vc/manual/2.90.1/magit/Performance.html), which shows how to do that.

**Comment by jsravn** [comment]
Just opening the buffer takes a while - maybe 10-15s. But it seems there is some O(n) effect where the number of branches I try to delete is multiplied by this value. If I delete a single branch, it takes around the same amount of time. When I delete a dozen branches it takes minutes to become responsive again.

**Comment by tarsius** [comment]
Guess I'll have to have another look.

**Comment by tarsius** [comment]
Please post the commands that Magit uses to delete the branches (copy that from the process buffer, which you can get with `$`).

**Comment by jsravn** [comment]
Apologies, I think my sense of time must be totally off. With magit-toggle-verbose-refresh on, it does seem to be indeed the same order of time - it was about 10s slower after deleting branches, for a total of 90s to refresh the ref buffer. Vast majority is in inserting tags, so I guess I'll disable the tag section for now. Thanks for your help!

For reference here is what I saw:

```
Delete 9 unmerged branches? (y or n) y
Refreshing magit...
Running magit-pre-refresh-hook...done (0.000s)
Refreshing buffer ‘magit-refs: core-infrastructure’...
  magit-insert-error-header                          1.891e-06
  magit-insert-branch-description                    0.002923886
  magit-insert-local-branches                        0.007778356
  magit-insert-remote-branches                       0.238157852
  magit-insert-tags                                  84.605912143
Refreshing buffer ‘magit-refs: core-infrastructure’...done (86.216s)
Refreshing buffer ‘magit: core-infrastructure’...
  magit-insert-error-header                          1.391e-06
  magit-insert-diff-filter-header                    2.4074e-05
  magit-insert-head-branch-header                    0.128737758
  magit-insert-upstream-branch-header                0.129525511
  magit-insert-push-branch-header                    3.1751e-05
  magit-insert-tags-header                           0.235129368
  magit-insert-status-headers                        0.494398148
  magit-insert-merge-log                             0.001583643
  magit-insert-rebase-sequence                       0.000103819
  magit-insert-am-sequence                           5.4911e-05
  magit-insert-sequencer-sequence                    0.000173208
  magit-insert-bisect-output                         0.000101437
  magit-insert-bisect-rest                           1.1876e-05
  magit-insert-bisect-log                            1.1623e-05
  magit-insert-untracked-files                       0.033962524
  magit-insert-unstaged-changes                      0.002491319
  magit-insert-staged-changes                        0.003149091
  magit-insert-stashes                               0.001582707
  magit-insert-unpushed-to-pushremote                3.0648e-05
  magit-insert-unpushed-to-upstream-or-recent        0.135092006
  magit-insert-unpulled-from-pushremote              2.7301e-05
  magit-insert-unpulled-from-upstream                0.126321082
  forge-insert-pullreqs                              0.061710001
  forge-insert-issues                                0.012302782
Refreshing buffer ‘magit: core-infrastructure’...done (0.901s)
Running magit-post-refresh-hook...done (0.003s)
Refreshing magit...done (87.122s, cached 87/114)

```
