### ISSUE TITLE
allow clicking on URLs inside commit messages

### ISSUE THREAD

**Issue by dadinn** [magit/magit#4202]
I would expect URLs to be highlighted while looking at commit messages,
so that they will automatically open in a browser when clicked on.

**Comment by kyleam** [comment]
Is the request specifically about enabling this out of the box?  Otherwise, it's already simple to do on the user's end:

    (add-to-list 'magit-revision-mode-hook #'goto-address-mode)

**Comment by tarsius** [comment]
I think it makes sense to add this by default.

**Comment by dadinn** [comment]
Seems like it's now enabled by default as of Melpa version `20200829.1629`.

Awesome, Cheers!
