### ISSUE TITLE
Provide magit-diff-refine-* faces

### ISSUE THREAD

**Issue by andreyorst** [magit/magit#4205]
**Note**: I'm aware of `(magit-diff-refine-hunk t)` for highlighting inline changes only in active hunk, and this is not what I'm looking for.
#

Currently it is possible to configure `refine` faces by changing `diff-refine-*` faces, such as `diff-refine-added` and `diff-refine-removed`. However Magit diff uses four faces instead of two: `magit-diff-added`, `magit-diff-added-highlight`, `magit-diff-removed`, and `magit-diff-removed-higlight`.

I'm programmatically setting `diff-refine-*` faces to a slightly more accent color, so it match any theme as long as target face features both foreground and background. I use `magit-diff-added-highlight` and  `magit-diff-removed-higlight` as my target faces. However, this doesn't look nice when hunk is unfocused:

![image](https://user-images.githubusercontent.com/19470159/91942212-36e6c680-ed03-11ea-801a-7859d292ae2a.png)

In unfocused hunk faces are too bright, and bring too much attention, but in focused they are not as bright as I'd like them to be. If I use `magit-diff-added` and  `magit-diff-removed`, then the situation is reversed:

![image](https://user-images.githubusercontent.com/19470159/91942710-0bb0a700-ed04-11ea-8618-59f95822b5c4.png)

Now the unfocused hook is more or less ok, but focused hook is barely seen.

Ideally it would be great if Magit provided these faces: `magit-diff-refine-added`, `magit-diff-refine-added-highlight`, `magit-diff-refine-removed`, and `magit-diff-refine-removed-higlight`, and I could tweak highlight and non-highlight versions independently. Here's mockup of how it would look:

![image](https://user-images.githubusercontent.com/19470159/91942868-4e727f00-ed04-11ea-956d-987ff8e63102.png)
(you can compare it with the first screenshot to spot the difference)

**Comment by tarsius** [comment]
Magit doesn't do the refinement itself and the code that does it only provides the currently used faces and does not know about focused vs. other hunks. It probably would not be impossible to work around by either post-processing the result or providing your own implementation. The former would likely impact performance and the latter eat into my development time.

So I don't thin anything like that is going to happen any time soon. Sorry!

**Comment by andreyorst** [comment]
Understood, thanks!
