### ISSUE TITLE
visibly differentiate checked-out branch from terminal (i.e. --no-window-system)

### ISSUE THREAD

**Issue by dadinn** [magit/magit#4206]
I am running Emacs with the `-nw` flag from the terminal.

When looking at the commit graph using log all-branches (keymap `l b`) I cannot differentiate which is the currently checked-out branch, as they all look the same.

In contrast, when using Emacs GUI the current branch is highlighted/boxed, which makes it highly visible.

I would expect the font-faces to be different in the terminal interface (maybe even bold text would be enough), to allow better differentiating the currently checked out branch.

**Comment by bchallenor** [comment]
I find inverse video good for this:
```
(set-face-attribute 'magit-branch-current nil :inverse-video t)
```

**Comment by tarsius** [comment]
> (maybe even bold text would be enough)

Many themes make *all* branch (and other refs) bold, so maybe not.

> I find inverse video good for this

Sounds like a good idea. Some people might not like the look of that, but it should "always" work.

I was thinking about underlining, as that is similar to boxing, but does that even work?

**Comment by dadinn** [comment]
the inverse video recommended by @bchallenor would be exactly what I am looking for!

**Comment by tarsius** [comment]
Yes faces can have different definitions for different display types.
