### ISSUE TITLE
Enable single submodule operations for all submodules

### ISSUE THREAD

**Issue by wbl** [magit/magit#4210]
I'd like to be able to update all submodules, rather than step through one by one. https://magit.vc/manual/magit/Submodule-Transient.html#Submodule-Transient hints at being able to do this already via a prefix command but I haven't been able to figure it out yet.

**Comment by tarsius** [comment]
Use `o C-p f`, for example.

**Comment by wbl** [comment]
That works! I guess I need to spend more time with the documentation to understand this trick and where else it can be used.
