### ISSUE TITLE
Magit refuses to do a checkout-local-branch with dirty submodules 

### ISSUE THREAD

**Issue by dabrahams** [magit/magit#4212]
1. `git clone git@github.com:dabrahams/magit-bugreport`
2. `echo CHANGES >> magit-bugreport/submodule/README.md`
3. Open magit-bugreport in magit
4. `b l origin/master-2'

You will get “user-error: Cannot checkout when there are uncommitted changes”

You can, however do:

`git checkout -b master-2 origin/master-2'

which should have been the result.

I've been unable to generate a backtrace, sorry!

Magit 20190202.1535, Git 2.28.0.618.gf4bc123cb7-goog, Emacs 27.1, darwin

Reproduces with magit-emacs-Q-command

Thanks!

**Comment by kyleam** [comment]
> Magit 20190202.1535

As of ae82fcf4 (magit-branch-checkout: Ignore submodule modifications, 2020-06-01), magit-branch-checkout no longer aborts due to submodule changes.

**Comment by kyleam** [comment]
Please reopen if I'm mistaken and this isn't already addressed.
