### ISSUE TITLE
Github CLI Support

### ISSUE THREAD

**Issue by MatthewZMD** [magit/magit#4214]
Since [Github CLI 1.0](https://github.blog/2020-09-17-github-cli-1-0-is-now-available/) is now available, I tried it a bit and it seems to work quite nicely. I wonder if the Magit community is planning to integrate it into existing Magit or create a separate package (ex. `magit-gh`)?

I know the existence of [forge](https://github.com/magit/forge), it might be better to integrate the Github CLI into that package. If so, this issue can be moved to the forge repo instead.

**Comment by tarsius** [comment]
I am not going to implement any support for Github CLI but if someone else did, then that might become a useful wrapper. Even if this wrapper is implemented as an extension to Magit or Forge, I think it should be an independent package, maintained in a separate repository.

Forge is supposed to support many different forges. Investing time into supporting a tool that only supports Github, goes against that idea. And I am already short on time.

I am sure Github CLI has some features that are missing from Forge (and vice-versa). One thing I noticed is that if you click on the green `Clone` button in the web interface, then a new option is now "Github CLI". I wanted to add something similar for Forge for a while, but they beat me to it.

I think this could be done using "org protocol". If someone wants to help with that, that would be very welcome. In particular the browser part, i.e. inject the button into the page and wrap the whole thing as a browser extension.
