### ISSUE TITLE
fatal: No names found, cannot describe anything.

### ISSUE THREAD

**Issue by diamond-lizard** [magit/magit#4215]
When typing "make" in the magit directory I cloned from git, I get a bunch of
errors that say:
```
fatal: No names found, cannot describe anything.
```

Here is a full log of the make:  https://dpaste.com/4UV36UWW4

M-x magit-version reports

Magit b49dfd7d0f11b15aaf58d36bcc4ea260b5e013da, Git 2.21.0, Emacs 27.1, gnu/linux

**Comment by tarsius** [comment]
This probably comes from `VERSION ?= $(shell test -e $(TOP).git && git describe --tags --abbrev=0 | cut -c2-)` in `default.mk`. Run `git describe --tags` manually to investigate. Are you working in a shallow clone?

**Comment by diamond-lizard** [comment]
```git describe --tags``` responds with ```fatal: No names found, cannot describe anything.```

I am in fact working with a shallow clone.

I cloned the magit repo using ```git clone --depth=1``` because I didn't think I'd need the history and to save time and bandwidth, and never expected it to be an issue.

Doing an ordinary ```git clone`` on magit's repo and then a ```make``` eliminated the problem.
