### ISSUE TITLE
(option to) use magit-process-buffer more completely

### ISSUE THREAD

**Issue by dabrahams** [magit/magit#4217]
Magit exposes lots of useful and sometimes magical-seeming things that are possible with git but not obvious.  I sometimes use magit to teach me about git, by looking at what it does in the magit-process-buffer.  But several of the actions magit takes don't show up there, and I don't see a way to change that.  One example is "preview merge," which looks awesome in general.  But I can't easily tell what magit is doing to create it.  I'd like magit-process-buffer to always show me what magit is doing behind the scenes, and if that's going to be too much for some people, I'd like a customizable option to have it do so.

Thanks!

**Comment by tarsius** [comment]
> I sometimes use magit to teach me about git, by looking at what it does in the magit-process-buffer.

At other times that will continue to involve having to look at the source code, I'm afraid.

> But several of the actions magit takes don't show up there, and I don't see a way to change that.

Magit runs `git` either for side-effects, to display the output, to read the output and do things with that. Only when it runs it for side-effects is the output (and the command that was run) put into the process buffer. Putting all git invocation and output there would be to expensive and complicated.

> One example is "preview merge,"

Okay you picked a good example. It takes *a lot* of hopping around to find the place where all the arguments come together (`magit--insert-diff`).

Maybe it would make sense to optionally print some run-for-output commands into the process buffer (but without the actual output). `magit-git-wash` might be a good place for that. Or even:

```diff
 (defun magit-process-file (process &optional infile buffer display &rest args)
   "Process files synchronously in a separate process.
 Identical to `process-file' but temporarily enable Cygwin's
 \"noglob\" option during the call and ensure unix eol
 conversion."
+  (when magit-extreme-logging
+    (message "$ %S" (cons process args)))
   (let ((process-environment (magit-process-environment))
         (default-process-coding-system (magit--process-coding-system)))
     (apply #'process-file process infile buffer display args)))
```

Doing that would be okay. The overhead of inserting this information into the process buffer would be to large.

**Comment by dabrahams** [comment]
Yeah, absolutely, I was going to suggest just having a variable that turns on dumping all the commands to the message buffer.  Just having *some way* to observe what magit is doing would be a big help.

I'd suggest `(message "magit: $ %S" (cons process args)))` just to distinguish them from other messages.

Thanks!
