### ISSUE TITLE
A way to specify "merge strategy options"

### ISSUE THREAD

**Issue by dabrahams** [magit/magit#4218]
For example, if I want a recursive merge with diff-algorithm=histogram, there's no way to do that through Magit's UI.

**Comment by kyleam** [comment]
> if I want a recursive merge with diff-algorithm=histogram, there's no way to do that through Magit's UI.

Passing `-Xdiff-algorithm` is already supported (though it's hidden by default), but it's true that the other merge strategy options aren't present in the merge transient, so at the moment users would have to add ones of interest to the merge transient themselves.

**Comment by dabrahams** [comment]
How do I un-hide it?

**Comment by kyleam** [comment]
https://magit.vc/manual/transient/Enabling-and-Disabling-Suffixes.html

**Comment by dabrahams** [comment]
Oh, very awesome, time to re-read the manual!

**Comment by tarsius** [comment]
Let's add more merge strategy options when concrete options are actually being requested.
