### ISSUE TITLE
Symbol’s function definition is void: magit--any-wip-mode-enabled-p

### ISSUE THREAD

**Issue by bchallenor** [magit/magit#4219]
If the rest of magit is not `require`d yet, `magit-log` cannot be run via its autoload:
```
Symbol’s function definition is void: magit--any-wip-mode-enabled-p
```
There appears to be a circular dependency between `magit-log` and `magit-wip`. `magit-wip` requires `magit-log`, and `magit-log` assumes the existence of `magit--any-wip-mode-enabled-p`, which is defined in `magit-wip`.

**Comment by tarsius** [comment]
Thanks for the report!

**Comment by bchallenor** [comment]
Thanks! That fixes it.
