### ISSUE TITLE
Remote menu doesn't update when returning from sub-menu

### ISSUE THREAD

**Issue by bendlas** [magit/magit#4220]
Some menus don't seem to correctly update, when shown values change in sub-menu invocations.

Observed in `magit-remote-configure`:

>    (1) what behavior you expected

- in `magit-remote` menu (`M`):
  - in sub-menu `magit-remote-configure` (`C`)
    - update remote url `u`
    - quit sub-menu `q`
  - **updated url is shown**

>    (2) what behavior you observed

- ...
  - **previous url is still shown**
  - when re-opening the menu, the updated url is shown

>    (3) and how we can reproduce the issue.

- Enter any repository, where you don't mind updating a remote url
- Follow key strokes in expected behavior

>    M-x magit-version RET

`Magit 20200816.955, Git 2.28.0, Emacs 26.3, gnu/linux`

**Comment by tarsius** [comment]
Updating the `transient` package should fix that.
