### ISSUE TITLE
magit-commit: Wrong number of arguments: (1 . 4), 5

### ISSUE THREAD

**Issue by manuel-uberti** [magit/magit#4221]
## Expected behaviour

<kbd>c c</kbd> from a `magit-status` buffer lets me fill the Summary and the Body of my commit message, so I can press <kbd>C-c C-c</kbd> to complete the commit.

## Actual behaviour

```
Running git commit --
error in process sentinel: user-error: Don’t kill this buffer #<buffer COMMIT_EDITMSG>.  Instead cancel using C-c C-k
error in process sentinel: Don’t kill this buffer #<buffer COMMIT_EDITMSG>.  Instead cancel using C-c C-k
Type C-c C-c to finish, C-c C-k to cancel, and M-p and M-n to recover older messages
There was a problem with the editor '/usr/local/bin/emacsclient --socket-name=/run/user/1000/emacs/server7082'. ... [Hit $ to see buffer magit-process: test for details]
```
Hitting `$` shows:
```
  0 git … add -- test-0
  1 git … commit --
hint: Waiting for your editor to close the file...
Waiting for Emacs...
*ERROR*: Wrong number of arguments: (1 . 4), 5
error: There was a problem with the editor '/usr/local/bin/emacsclient --socket-name=/run/user/1000/emacs/server7082'.
Please supply the message using either -m or -F option.
```

## Steps to reproduce the problem

- run `emacs -Q`
- install Magit (I use `straight`, so I followed [these instructions](https://github.com/raxod502/straight.el#using-straightel-to-reproduce-bugs))
- create a `test` directory (e.g., `~/Downloads/test`)
- run `git init` in it (e.g, I ran <kbd>M-x shell</kbd>, typed `git init` and press <kbd>RET</kbd>)
- create a `test-0` file under your `test` directory (e.g., `~/Downloads/test/test-0`)
- add some random content to it
- run `M-x magit-status`
- move point onto `test-0`
- hit <kbd>s</kbd>
- hit <kbd>c c</kbd>

## Magit and Git version

Magit 6c1c92e5a2abbdf1c852f7da50e69f0b898e7a72, Git 2.25.1

## System information

```
GNU Emacs 28.0.50

➤ Master branch commit:
   6c0f1c26d296132e37b2508a00efc73f3df95b0c
   Don't have C-x = bug out in a "C" locale with non-ASCII chars

➤ Configured with the following options:
   --with-harfbuzz
   --with-json
   --with-mailutils

➤ Running on:
   Ubuntu 20.04 LTS
   GNOME Shell 3.36.4 (x11)
   GTK+ Version 3.24.18, cairo version 1.16.0
```

**Comment by manuel-uberti** [comment]
If it may help, I get the same problem by starting Emacs with the command printed by `magit-emacs-Q-command`, following the same recipe from the third step onwards.

**Comment by nigredo-tori** [comment]
I can reproduce this issue as well. I've minimized it to the following:
1. Save this as `/tmp/foo.el`:
    ```el
    (package-initialize)
    (require 'use-package)
    (use-package magit)
    ```
1. Start emacs as `emacs --no-init --daemon`.
1. Run `emacsclient /tmp/foo.el`
1. Select the contents of the file and `M-x eval-region`.
1. In another console tab run another instance of `emacsclient /tmp/foo.el` and see it fail.

**Comment by DurhamSmith** [comment]
Also experiencing this issue both with changes to old repos and starting new ones.

**Comment by leungbk** [comment]
This seems to arise from one of Emacs `master`'s commits within the last two or so days. A version built using commits from Sept 28 or so worked fine for me, but it was only when I rebuilt this morning that I saw this problem.

**Comment by manuel-uberti** [comment]
Could it be this one: https://github.com/emacs-mirror/emacs/commit/7f2c35d02874129723cc5e89d54cc3ab5bf07a31 ?

**Comment by tarsius** [comment]
Yes; https://github.com/magit/with-editor/issues/82.

**Comment by tarsius** [comment]
I just pushed a fix.

**Comment by manuel-uberti** [comment]
Thank you, @tarsius, it works as expected now.
