### ISSUE TITLE
Not enough context to apply patch. Increase the context

### ISSUE THREAD

**Issue by dadinn** [magit/magit#4222]
# Expected
I am trying to decrease the the context to one to 0 line, so i can individually discard, stage, or unstage hunks from the unstaged / staged changes. This used to work before, though even sometimes the hunks got mixed up even then (i.e. got hunks duplicated/moved at random places... maybe this should be reported as a separate issue).

# Observed
Nevertheless, when I try to discard/stage individual hunks from the `Unstaged changes`, the operation fails with the message `Not enough context to apply patch. Increase the context`.

# Versions

OS: MacOS (darwin)
Emacs version: 27.1
Git version 2.28.0
Magit version: 20200927.1644

**Comment by dadinn** [comment]
I actually have the same issue with this config:

OS: Debian 10 (i.e. Buster)
Emacs version: 26.1
Git version: 2.20.1
Magit version: 20200908.1311

**Comment by tarsius** [comment]
It is `git` that does not want to apply those patches. You say it used to do so, which might be the case, but as you mentioned it also got it wrong sometimes, which might be why it refuses to attempt to do it now. I don't think Magit can do here.

**Comment by kyleam** [comment]
You're blaming the wrong git :)  I introduced this change with 6b3c90d46 (magit-apply-patch: Abort when there is no context, 2019-08-02).  It was prompted by gh-3924, which also brought about d508f022c (apply: Adjust hunk line positions for partial application, 2019-07-28).

**Comment by tarsius** [comment]
oO

**Comment by tarsius** [comment]
So before I assume to much again...
Am I right in thinking there isn't much we can do here except restoring the footgun?

**Comment by kyleam** [comment]
Yeah, I think the only other option would be exploring whether we can [tweak][1] the hunk headers to make it work.  Without a compelling use case though, I still lean toward the conclusion from that thread that it's not worth the complication.

[1]: https://github.com/magit/magit/issues/3924#issuecomment-515917455

**Comment by dadinn** [comment]
In case there won't be a fix for this on the git side, magit could still limit decreasing the context below 1.

**Comment by tarsius** [comment]
IMO the current situation is the best compromise: you cannot apply hunks with zero context but at least you can look at them that way.

**Comment by dadinn** [comment]
I have [followed up with this](https://public-inbox.org/git/26316a94-ed0f-cf52-74f5-b20508345569@gmail.com/) on the git mailing list, and they said this should be supported using `--unidiff-zero` flag, and therefore the issue is magit related.

**Comment by kyleam** [comment]
> I have [followed up with this](https://public-inbox.org/git/26316a94-ed0f-cf52-74f5-b20508345569@gmail.com/) on the git mailing list, and they said that zero context patches are supported

Yes, as Phillip said over there, the conclusion of this issue was _not_ that git doesn't support zero-context patches.

> but only when using `--unidiff-zero` flag, as a safety measure. Therefore the issue is not with git, but due to magit not handling zero-context case correctly.

The use of `--unidiff-zero` was dropped in 6b3c90d4 (magit-apply-patch: Abort when there is no context, 2019-08-02), the commit that was mentioned above.  The relevant thread is gh-3924.

Here's the usecase you gave in your message to the git mailing list:

```
Without handling no-context hunks, I see I will have to stash/redo
entire change-sets, to be able to commit logically separate hunks
separately. This would be a major PITA.
```

You don't need to reduce the hunk context to stage a subset of lines within a hunk.  Select the part you want with the region and hit <kbd>s</kbd> to stage it.  You can do similar for unstaging and discarding.

**Comment by dadinn** [comment]
Ok, to give an example of what I would like to do, consider the following file with 7 lines of Xs
```
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

On every second line I would like to write something:
```
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXOOOOOOOOOOOOOOOOOOOOOOXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXOOOOOOOOOOOOOOOOXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXooooooooooooooooooooooooooooooooXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

The task is to make the second change on the first one, then commit each line separately.
Another example [here](https://github.com/dadinn/magit-issue-4222/commits/master)
My point is it is not possibly to work on a file, and commit separate pieces of logic in separate commits. The only way such things can be done is by stashing away everything, and reapplying/committing changes line-by-line.

**Comment by kyleam** [comment]
> The task is to make the second change on the first one, then commit each line separately. Like for how it's done [here](https://github.com/dadinn/magit-issue-4222/commits/master).
> My point is, that it's not possible to work on a file and commit separate pieces of logic separately.

Committing separate lines from a hunk is possible by selecting the lines to stage with the region.  Perhaps there are cases that zero-context hunks would allow that region-based line staging don't.  Intraline changes require using `magit-ediff-stage` (discussed in gh-2718, which is linked to in the referenced issue above), though zero-context hunks wouldn't help there anyway.

> Now the only way that can be achieved is by stashing away everything, and reapplying/committing changes line-by-line.

For [your demo case][0] at least, that's not true.  I started with all those changes on top of the base (0a87b87):

```diff
diff --git a/example.txt b/example.txt
index 0382d5f..c1e7480 100644
--- a/example.txt
+++ b/example.txt
@@ -1,7 +1,7 @@
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXTHISXISXJUSTXTHEXFIRSTXLINEXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXBUTXLOOK!XHEREXISXTHEXSECONDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
+XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXIXWILLXNOTXSTOP!XTHEXTHIRDXSTRIKE!XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

I used line-based region staging (stage the change, stage the top deleted line) to get the exact same result.

```console
$ git diff --stat master redo
 README.md | 1 -              
 1 file changed, 1 deletion(-)
$ git range-diff 0a87b87 master redo      
1:  ff6246e = 1:  aad21e7 first change
2:  3cc239a = 2:  e108f57 second change
3:  6bdd8ee = 3:  e232898 third change
4:  e7e53c2 < -:  ------- added README
```

(Note: I set `user.name` and `user.email` in the repo to match to avoid the author difference noise in the range-diff output.)

And I also achieved the same series using `magit-ediff-stage`:

```console
$ git range-diff 0a87b87 master redo-ediff  
1:  ff6246e = 1:  9b3bed1 first change
2:  3cc239a = 2:  28aa09d second change
3:  6bdd8ee = 3:  ab0809a third change
4:  e7e53c2 < -:  ------- added README
```

[0]: https://github.com/dadinn/magit-issue-4222/

**Comment by dadinn** [comment]
Hmm, I am using magit from commit `08449840608ab20c0361caf2174628fd188dba5a`, and when I apply the final/expected state, on the initial commit, I would not be able to stage/commit the lines one-by-one. Which version are you using?

**Comment by kyleam** [comment]
> Which version are you using?

The tip of master at the time I posted or something close to it.  But nothing has changed in the area of region-based staging recently, and I just redid it [*] again on 084498406 with a vanilla config.

[*] stage the line with "FIRST", stage a deleted line, commit; stage the line with "SECOND", stage a deleted line, commit; stage rest, commit

**Comment by dadinn** [comment]
I am sorry, but I don't understand what you are saying.
I have tried again with magit HEAD of master `c7af7872`

You must be doing something different. If you checkout the initial commit in my [example repo](https://github.com/dadinn/magit-issue-4222/commits/master) earlier, and overwrite it with the contents of the [example.txt](https://github.com/dadinn/magit-issue-4222/blob/6bdd8ee4f1ddab2b5eed0a08730c679621753bc6/example.txt) from the "third change" commit, then there is no way to stage/commit anything except the entire file, if the context is larger than zero. 

When the context is zero, it fails the to stage the hunks.

**Comment by dadinn** [comment]
sorry, I am not sure what `magit-ediff-stage` does. Is this a new feature? I don't understand how I could stage hunks with it, there don't seem to be any key-bindings for staging the hunks individually... also it feels more complicated than using the `magit-status` buffer.

**Comment by kyleam** [comment]
> there is no way to stage/commit anything except the entire file, if the context is any larger than zero

This is the same claim as you made above.  As I said there, "[c]ommitting separate lines from a hunk is possible by selecting the lines to stage with the region".  This is also mentioned in the referenced commit and the issue I pointed to, specifically <https://github.com/magit/magit/issues/3924#issuecomment-516026707>.

**Comment by dadinn** [comment]
Apologies, I must have missed that. It looks like that this hunk-internal region is exactly the feature I'm looking for. Thanks!
