### ISSUE TITLE
Cannot resolve conflict on file deleted by both 

### ISSUE THREAD

**Issue by lmartelli** [magit/magit#4225]
During a rebase, I had a conflict where on a file that was deleted by both. Git status said : 

```
Unmerged paths:
  (use "git restore --staged <file>..." to unstage)
  (use "git rm <file>..." to mark resolution)
	both deleted:    web-service/src/test/kotlin/com/smilemate/clinical/spring/internal/utils/RandomUtils.kt
```

I could not resolve the conflict using `k` the way I usually do. Magit proposed to trash the file but that failed :
```
move-file-to-trash: Renaming: No such file or directory, /home/laurent/src/screening/web-service/src/test/kotlin/com/smilemate/clinical/spring/internal/utils/RandomUtils.kt, /home/laurent/.local/share/Trash/files/RandomUtils.ktNqQFZb.trashinfo
```
`git rm` as suggested by `git status` worked.

**Comment by tarsius** [comment]
I think you can just stage the change with `s`.

**Comment by tarsius** [comment]
How does one get a file into the "both deleted" state? Simply deleting it on two branches (even after otherwise editing it on both of them) did not do it for me. Maybe you can point me to a public pair of branches where that happens for you?

**Comment by kyleam** [comment]
> How does one get a file into the "both deleted" state?

Perhaps there are other ways, but one is to rename the file (differently) on each side.

```sh
set -e

cd "$(mktemp -d "${TMPDIR:-/tmp}"/magit-XXXX)"
git init
echo f >f
git add f
git commit -mf

git mv f f-rename
git commit -m'rename'

git checkout HEAD~1
git mv f f-rename-side
git commit -m'rename on side'

git rebase '@{-1}'
```

This shows up in Magit as

```
Rebasing detached HEAD onto master
join 1610dbd rename on side
onto cc50a7c rename

Staged changes (3)
unmerged   f (both deleted)
unmerged   f-rename (added by us)
unmerged   f-rename-side (added by them)
```

I've only played around with this state briefly, but some initial notes:

  * Staging individual entries doesn't work here
  * Unstaging any of the entries works
  * `k` on either of the renames will hit an error for the side that doesn't an entry for the file
  * `k` on f shows the error reported in the initial post

**Comment by kyleam** [comment]
I've pushed a tentative fix to [km/both-sides-rename-conflict](https://github.com/magit/magit/compare/km/both-sides-rename-conflict).  I should have time to revisit that with fresh eyes in a couple of days and will plan to merge it then if I still don't spot any issues with it and nobody has raised any objections.
