### ISSUE TITLE
Option to fill the commit message ring from history

### ISSUE THREAD

**Issue by clanghans** [magit/magit#4227]
Hi, 
I am a huge fan of M-p in git-commit.el and it would be very useful if the commit message ringbuffer would come filled with previous commit messages from the current repository. 

I would like to contribute this if wanted. 

Alternative: if the above feature is not wanted I could also imagine a commit history file which is persisted to survive a session shutdown. 

Thanks for considering this

**Comment by tarsius** [comment]
> it would be very useful if the commit message ringbuffer would come filled with previous commit messages from the current repository.

That doesn't sound very useful to me but of course workflows differ. Never-the-less I think this should not be added.

When would you populate the history variable from the git history? When it is empty? Then this feature would only be useful in the first repository in which you create a commit in the current Emacs session. Or you maintain separate history variables for each repository, which would break my main use-case: using the same message in a few closely related repositories after making identical changes in each one of them.

Adding a option to let users choose between different behaviors seem like too much in this case.

> Alternative: if the above feature is not wanted I could also imagine a commit history file which is persisted to survive a session shutdown.

There already is persistent history and it is stored using git...

Have you investigated if you can get around having to rely on the history variable so much by using various commit amend variants and the rebase fixup variants?
