### ISSUE TITLE
Magit inhibits emacsclient immediate display

### ISSUE THREAD

**Issue by vshelton** [magit/magit#4228]
Starting from emacs -Q:

(server-start)

I can now run this command in a shell:

emacsclient -n foo.txt

and get the content of foo.txt immediately displayed in emacs for editing.

However, if I load magit:

(add-to-list 'load-path (expand-file-name "elpa/transient-20200503.1401" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "elpa/git-commit-20200207.1819" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "elpa/with-editor-20200217.1015" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "elpa/dash-20200426.2244" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "elpa/magit-20200503.1905" user-emacs-directory))
(require 'magit)

emacsclient -n foo.txt

loads foo.txt into emacs, but the buffer is not immediately displayed.

I hope this description is clear.  Please write if I need to explain further.

**Comment by tarsius** [comment]
I cannot reproduce this. Please try updating all the involved packages. What Emacs version are you using?

**Comment by vshelton** [comment]
Latest emacs from git.  emacs-version reports 28.0.50.

Thanks.  I will update the packages and report back.

**Comment by vshelton** [comment]
Yes!  After updating all the packages, emacsclient works properly again!

Thank you,
  Vin
