### ISSUE TITLE
I have never wanted to create a branch starting from anything but the current branch.

### ISSUE THREAD

**Issue by verhovsky** [magit/magit#4232]
I use the `b c` shortcut often. Many times I type the name of the branch I want to create, hit Enter and am told that the branch I just tried to create "is not a valid starting-point". Then I have to type the shortcut again and remember what branch name I came up with. I always check out the branch I want to create the new branch from because git is probably going to complain that my unstaged changes have a conflict. Personally, I would prefer to never be prompted for the name of the branch I'm on, or at least have the prompt be the second question.

**Comment by tarsius** [comment]
There's an option for that. :grinning:

`magit-branch-read-upstream-first`

**Comment by verhovsky** [comment]
@tarsius thanks, I'm using Doom Emacs, adding the following to `config.el` makes magit prompt me for the new branch name first:

```lisp
(after! magit
  (setq magit-branch-read-upstream-first nil))
```

The magit docs say "The default is `nil`", but isn't the default `t`?

https://github.com/magit/magit/blob/ae82fcf4d47559688a0ad7dfee55dd74bbe14b9e/lisp/magit-branch.el#L42

Or is there something in the Doom Emacs magit config that is setting this option? Because it doesn't seem to be explicitly referenced https://github.com/hlissner/doom-emacs/blob/develop/modules/tools/magit/config.el
