### ISSUE TITLE
smerge-mode not invoked automatically for file move/move conflict

### ISSUE THREAD

**Issue by greenrd** [magit/magit#4235]
While performing a rebase using magit, I encountered something I think I had not encountered before: a conflict where on the base branch, a file had been moved to one directory, but on the current branch, the very same file had been moved to a different directory. At the same time, other changes had been made to that file - it was not the case that the same changes were made on both branches. (Actually, amusingly, the person who moved it, in both branches, was me.)

Git correctly identified this as a conflict, and, in one version of the file, even helpfully added filenames to the conflict markers to show that this was a move/move conflict. However, magit did not identify this version of the file as being in conflict, so it did not invoke smerge-mode on the buffer when I pressed RET. I had to manually do M-x smerge-mode myself, which I don't usually have to do.

Maybe magit got confused by the non-standard appearance of the conflict markers. By the way, the conflict markers were diff3-style, as that's how I've configured git to render merge conflicts.

Magit 2.90.1, Git 2.27.0.windows.1, Emacs 26.3, windows-nt

**Comment by kyleam** [comment]
Could you provide a reproducer for the state?  I tried to follow your description, but I didn't have any luck getting into the same state.

<details>
<summary>attempt</summary>

```sh
set -eu

cd "$(mktemp --tmpdir -d magit-4235-XXX)"
git init
git config merge.conflictstyle diff3

git for-each-ref --help >foo
git add foo
git commit -mfoo

mkdir a
git mv foo a/
git add a/foo
git commit -m'move foo to a/'

sed -i 's/objecttype/objecttypeee/g' a/foo
git add a/foo
git commit -m'change in a'

git checkout -b side HEAD~2

mkdir b
git mv foo b/
git add b/foo
git commit -m'move foo to b/'

sed -i 's/objectname/objectnameee/g' b/foo
git add b/foo
git commit -m'change in b'

pwd
```

Then I visited that directory with magit and rebased side onto the master branch.  That resulted in the following state that I don't think matches what you're describing:

```
Staged changes (3)
unmerged   a/foo (added by us)
unmerged   b/foo (added by them)
unmerged   foo (both deleted)
```

</details>

**Comment by tarsius** [comment]
For quite some time now `smerge-mode` often (always?) fails to automatically activate for me. I have blamed it on a change in `smerge`/Emacs and have not investigated further. Magit does not actively enable `smerge-mode` (if I remember correctly) but relies on something in Emacs doing that. I've been assuming that something in Emacs changed causing this not to work anymore. So a good place to start investigating this would be the history of `smerge-mode.el` and maybe `vc`.

**Comment by tarsius** [comment]
Which is to say, @greenrd, I would appreciate it you could attempt to get to the root of this yourself. I hope my observations help with that.

**Comment by kyleam** [comment]
> For quite some time now `smerge-mode` often (always?) fails to automatically activate for me. I have blamed it on a change in `smerge`/Emacs and have not investigated further.

Hmm, not worth much, but I use smerge regularly and haven't noticed any issues (Emacs 27.1).

**Comment by tarsius** [comment]
> Hmm,

Yeah... hasn't happened to me anymore either. :grin:

**Comment by tarsius** [comment]
Still hasn't happened for me again.
