### ISSUE TITLE
magit-section: custom keymaps per section

### ISSUE THREAD

**Issue by jethrokuan** [magit/magit#4243]
#### Abstract
I would like to be able to specify custom keymaps for `magit-insert-section`.

#### Long description
I'm trying to use `magit-section` for Org-roam, aiming for a buffer not unlike the `magit-status` buffer (https://github.com/org-roam/org-roam/pull/1241). In the `magit-status` buffer, each section uses a separate keymap, which from delving into the code I understand is a result of this part of the `magit-insert-section` macro.

https://github.com/magit/magit/blob/2fb3bf782ccf5652b98f8de989f014749473eacf/lisp/magit-section.el#L1021

I would also like to be able to specify my own keymaps as part of `magit-insert-section`, but am unsure how to pass the class map into the macro. It looks like the `section` object is always generated with the default keymap of `nil`, and the class map obtained here is always `nil`.

**Comment by tarsius** [comment]
This is how its done:

```elisp
(defclass org-roam-demo-buffer (magit-section)
  ((keymap :initarg org-roam-demo-buffer-map)))

(defvar org-roam-demo-buffer-map
  (let ((map (make-sparse-keymap)))
    ...
    map))

(defun org-roam-insert-demo ()
  (magit-insert-section (org-roam-demo-buffer)
    ...))
```

You should always define a class for each section type and specify the keymap explicitly as shown above.

I will probably remove the `magit-TYPE-section-map` kludge today. And while I probably won't remove the kludge that allows using a TYPE that has no corresponding class that soon, new code should always use a class whose name is prefixed with the package prefix. I'll update the documentation.

**Comment by tarsius** [comment]
(Going full circle. Magit's sections where inspired by those of Org.) :grinning:

**Comment by jethrokuan** [comment]
Thanks for the example, that helps a lot!

**Comment by jethrokuan** [comment]
I'm reopening this because the above doesn't work right out of the box: it throws the message:

because the type is not in `magit--section-type-alist`, which is set here:

https://github.com/magit/magit/blob/2fb3bf782ccf5652b98f8de989f014749473eacf/lisp/magit-diff.el#L821-L839

```diff
                          :type
                          (if (class-p ,tp)
                              (or (car (rassq ,tp magit--section-type-alist))
-                                 (error "BUG: No entry for %s in %s" ,tp
-                                        'magit--section-type-alist))
+                                 'magit-section
+                                 ;; (error "BUG: No entry for %s in %s" ,tp
+                                 ;;        'magit--section-type-alist)
+                                 )
                            ,tp)
                          :value ,(nth 1 (car args))
                          :start (point-marker)
```

was required for it to render successfully.

**Comment by tarsius** [comment]
Turns out that `keymap` slot wasn't actually used for a single section type yet...

Anyway, your proposed change isn't quite right, but you were on the right track. I've pushed a fix (with improved documentation) and this should work now.

**Comment by tarsius** [comment]
> I will probably remove the `magit-TYPE-section-map` kludge today.

That's not gonna happen. ;P
