### ISSUE TITLE
auto-revert-mode scales poorly with many files

### ISSUE THREAD

**Issue by catern** [magit/magit#4248]
When enabling auto-revert-mode for a new buffer, as magit does by default, auto-revert-notify-add-watch is called to register the new file with file-notify. Unfortunately, auto-revert-notify-add-watch has some O(N) behavior: It calls maphash to map over all already-registered files. Here's an excerpt from Emacs HEAD:

```elisp
(defun auto-revert-notify-add-watch ()
  "Enable file notification for current buffer's associated file."
...
      (maphash
       (lambda (key _value)
         (when (and
                (file-notify-valid-p key)
                (equal (file-notify--watch-absolute-filename
                        (gethash key file-notify-descriptors))
                       (directory-file-name file))
                (equal (file-notify--watch-callback
                        (gethash key file-notify-descriptors))
                       'auto-revert-notify-handler))
         (setq auto-revert-notify-watch-descriptor key)))
       auto-revert--buffers-by-watch-descriptor)
...
)
```

On my Emacs, with 1500 buffers, this adds a couple seconds to every find-file in a git repo.

This aspect of auto-revert-mode can be optimized, of course, but this makes me a little concerned about the quality of the auto-revert-mode implementation in general - does it have other O(N) scaling behaviors?

Perhaps magit should avoid auto-revert-mode in favor of something more explicit? It's convenient, certainly, that auto-revert-mode handles file reversion without any kind of explicit tracking on the magit side, and it's even asynchronous. On the other hand, it seems unfortunate for magit to throw away information that it already has - magit knows, e.g., when we kill a hunk, that that will update the file containing that hunk.

Or maybe, at least, there could be an alternative for reverting buffers besides auto-revert-mode; magit used to have a magit-revert-buffers function which would synchronously revert all files open in the repo, perhaps it could have such a function again, off by default, and use it if configured by the user. As the number of files open in Emacs grows, such a function will become more and more competitive with auto-revert.

**Comment by tarsius** [comment]
That's a lot of buffers.

> This aspect of auto-revert-mode can be optimized, of course, but this makes me a little concerned about the quality of the auto-revert-mode implementation in general - does it have other O(N) scaling behaviors?

If the quality were low, then that would be even more reason to fix it. IMO this is where improvements should be made.

> Perhaps magit should avoid auto-revert-mode in favor of something more explicit? [...] it seems unfortunate for magit to throw away information that it already has 

Magit does not have perfect knowledge of everything that could happen to Git data. We could rely more on things we know but if we relied on that exclusively, then that would be a regression.

> Or maybe, at least, there could be an alternative for reverting buffers besides auto-revert-mode;

I'm sorry but I don't feel like implementing and/or maintaining that. You're best option is to remove the bottlenecks from Emacs itself. That would also have the advantage of benefiting the most people.
