### ISSUE TITLE
Install problems with dash and transient

### ISSUE THREAD

**Issue by wwulfric** [magit/magit#4251]
(1) what behavior you expected: I followed https://magit.vc/manual/magit/Installing-from-the-Git-Repository.html#Installing-from-the-Git-Repository and expected it would work.
(2) I've met some problems:

environment: mac big sur; emacs: GNU Emacs 27.1

0. What I did before install
```shell
git submodule add magit
git submodule add dash.el
git submodule add transient
git submodule add with-editor
```
and the result was:
```shell
ls ../ | grep -e magit -e transient -e with-editor -e dash
# dash.el
# magit
# transient
# with-editor
```

1. git-commit.el:115:1:Error: Cannot open load file: No such file or directory, dash
I solved this problem. Magit makefile looked up dash by 'dash', but 'dash' package's default name is dash.el.
```
#config.mk
...
LOAD_PATH += -L /paht/to/dash.el
```
2. After I solved dash problem: git-commit.el:121:1:Error: Cannot open load file: No such file or directory, transient

I don't know why here.

3. I tried to do `make` in transient: make[1]: *** No rule to make target `dir', needed by `info'.  Stop.

`make lisp` works well but `make docs' not.

(3) and how we can reproduce the issue.
Clone packags by `git submodule add packages` and do `make` in Mac OS big sur and emacs 27.1.

**Comment by tarsius** [comment]
> Cannot open load file: No such file or directory, transient

If you manually install the dependencies then you don't just need to tell `make` about it, you also need to tell `emacs` about it:

```elisp
(add-to-list 'load-path "/path/to/dash")
(add-to-list 'load-path "/path/to/transient")
(add-to-list 'load-path "/path/to/with-editor")
```

**Comment by tarsius** [comment]
I've just improved the instructions a bit.

**Comment by wwulfric** [comment]
@tarsius I  executed `ielm` and checked my `load-path`, packages(dash, transient, with-editor) were all in my load path.

![image](https://user-images.githubusercontent.com/8315997/99255613-239dbe80-284f-11eb-87cb-614ff4a2376c.png)

The problem is reported at line 121 of [git-commit.el](https://github.com/magit/magit/blob/master/lisp/git-commit.el#L121). I swapped line 121(require transient) and line 122(require with-editor), and then this problem was reported at line 122, which meant that with-editor was loaded successfully.

**Comment by tarsius** [comment]
> packages(dash, transient, with-editor) were all in my load path.

Well this error message that you posted earlier claims otherwise.

```
git-commit.el:121:1:Error: Cannot open load file: No such file or directory, transient
```

I don't know what else I can do to help you, except reminding you to restart Emacs before trying again.

**Comment by wwulfric** [comment]
Yes it's very strange😂 that with-editor and dash's loading work well but transient not. I restarted my Emacs a lot of times.
