### ISSUE TITLE
Show log with --first-parent?

### ISSUE THREAD

**Issue by nilsdeppe** [magit/magit#4252]
Hello!

Thank you for the super awesome package! I absolutely love magit. Next to prog-mode it's easily what I use most in Emacs :)

I'm trying to have the log displayed be what I would get from `git log --graph --first-parent`. I saw the issue #2989 that seems to be somewhat related to this. While being able to expand/collapse the individual merge commits would be awesome, just being able to view `--first-parent` in magit would be amazing. I noticed `--first-parent` seems to be somewhat supported(?) in so far as I found it in the `"Commit limiting"` part of `magit-log.el`
https://github.com/magit/magit/blob/dc6dd40f1ab4abb32a1babf8c8f23ccbeb6c39c6/lisp/magit-log.el#L417
However, I'm unable to actually convince magit to show me that option. I also couldn't find anywhere in the Logging part of the manual that described how to get `--first-parent` to show in the `Commit Limiting` part of the log popup.

Thank you so much in advance!

**Comment by tarsius** [comment]
Certain transient popups hide some of their suffix commands by default. These additional suffixes can be [enabled interactively](https://magit.vc/manual/transient/Enabling-and-Disabling-Suffixes.html). TL;DR Enter the transient as usual and type <kbd>C-x l</kbd>.

<sub>This is a [canned response](https://help.github.com/en/github/writing-on-github/working-with-saved-replies); it may not apply 100% in this case.</sub>
