### ISSUE TITLE
Unable to choose/unchoose the --color-moved option

### ISSUE THREAD

**Issue by xuhdev** [magit/magit#4254]
Please explain
    (1) what behavior you expected
`magit-diff` should show an option to enable or disable "--color-moved option" (according to https://github.com/magit/magit/blob/97ccce9b4823755fb01a3db01e54cf851cc5c065/lisp/magit-diff.el#L902-L903)
    (2) what behavior you observed
There's no such option listed after invoking `magit-diff`.
    (3) and how we can reproduce the issue.
Open a file in a git repository and run `magit-diff`.

Also post the output of:

    M-x magit-version RET

    Magit 20201122.2005, Git 2.27.0, Emacs 27.1.50, gnu/linux

**Comment by kyleam** [comment]
It's hidden.  (The 5 in the snippet you show is the level; 4 and below are shown by default.)  You can unhide it with <kbd>C-x l</kbd> and choosing a lower level.

https://magit.vc/manual/transient/Enabling-and-Disabling-Suffixes.html
