### ISSUE TITLE
Cannot search for author in magit-log buffer

### ISSUE THREAD

**Issue by Apteryks** [magit/magit#4255]
Hello,

While I'm aware of the 'Limit to author' (-A) switch when entering the log viewer with 'l', I still often find myself trying to search in the resulting buffer with C-s.  The problem is that for some reason the author column is not 'searchable' this way.  Is there a reason for this limitation?

Thank you for Magit :-)

**Comment by tarsius** [comment]
Yes, this is implemented using an Emacs feature called "margin" and unfortunately the text in there is not searchable.

**Comment by Apteryks** [comment]
OK, thanks for the answer/information.
