### ISSUE TITLE
magit-revision-insert-related-refs is not working properly

### ISSUE THREAD

**Issue by dbelous** [magit/magit#4256]
I want to include remote branches to the contained list in the revision buffer. 
I set magit-revision-insert-related-refs to different values:

- (setq magit-revision-insert-related-refs 'mixed)
- (setq magit-revision-insert-related-refs '(all mixed))

But it doesn't work because magit-diff.el contains following code

```elisp
(magit--insert-related-refs
       magit-buffer-revision "--contains" "Contained"
       (eq magit-revision-insert-related-refs '(all mixed)))
```

And `(eq magit-revision-insert-related-refs '(all mixed))` returns `nil` every time
Seems we should use equal operator or 'mixed instead of `'(all mixed)`, right?

**Comment by tarsius** [comment]
You located the correct location but the fix is something else.

(Also, "edit" your post to see the changes I made, in order to learn how to format code blocks.)
