### ISSUE TITLE
Delete the remote branch on Github

### ISSUE THREAD

**Issue by kjhsdf** [magit/magit#4257]
I asked this on reddit and StackOverflow, seems no one knows how to delete a remote branch (on Github) from magit. I know that `b k` deletes the local branch, but how do you delete the remote branch somewhere on the cloud? In git you would do it `git push origin --delete branch`. Is it already possible to do this in Magit instead of changing to terminal for this one task?

**Comment by kyleam** [comment]
`magit-branch-delete` (<kbd>bk</kbd>) can be used on remote branches too (and runs `git push` underneath).

**Comment by tarsius** [comment]
I already gave the same answer on stackoverflow. :roll_eyes:
I have now updated that to correct a false claim in a followup comment.

https://emacs.stackexchange.com/questions/61998/deleteing-remote-branches
