### ISSUE TITLE
`magit-diff-working-tree` leaks file list to later invocations

### ISSUE THREAD

**Issue by doublep** [magit/magit#4261]
To reproduce:

* Go to a Magit buffer
* Evaluate: `(magit-diff-working-tree "HEAD" nil '("x"))` (where `"x"` is a filename)
* It shows diffs in given file only; close this buffer
* Open any commit that doesn't touch this file
* It shows "empty" as commit's changeset

Expected:
* It shows commit's changeset, regardless of any commands I have issued before.

Note that issuing `(magit-diff-working-tree "HEAD" nil nil)`, i.e. "resetting" file list "fixes" it, suggesting that the file list is stored somewhere and is reused even where it certainly shouldn't be.

Magit 2.90.1, Git 2.20.1, Emacs 27.1, gnu/linux

**Comment by tarsius** [comment]
That's a feature but it is customizable, see `magit-prefix-use-buffer-arguments` and `magit-direct-use-buffer-arguments`.
