### ISSUE TITLE
GIT-SHORTLOG(1) interface

### ISSUE THREAD

**Issue by olav35** [magit/magit#4262]
I would love to have a GIT-SHORTLOG(1) interface in Magit. It would be useful to me, since I often use shortlog to get a quick overview of all contribut{ions,ors}(`git shortlog -sen`) and recent activity(`git shortlog -sen --since=20XX`) .

**Comment by tarsius** [comment]
I've added rudimentary support, but it unbound by default.

**Comment by tarsius** [comment]
Certain transient popups hide some of their suffix commands by default. These additional suffixes can be [enabled interactively](https://magit.vc/manual/transient/Enabling-and-Disabling-Suffixes.html). TL;DR Enter the transient as usual and type <kbd>C-x l</kbd>.

<sub>This is a [canned response](https://help.github.com/en/github/writing-on-github/working-with-saved-replies); it may not apply 100% in this case.</sub>

**Comment by olav35** [comment]
Great, thank you!
