### ISSUE TITLE
git `diff.suppressBlankEmpty=true` breaks magit diff hunk parsing

### ISSUE THREAD

**Issue by slippycheeze** [magit/magit#4263]
Observed behaviour: after setting `diff.suppressBlankEmpty=true` in my git configuration magit would leave diff content hanging out in the buffer, and otherwise behave quite strangely.  minimal reproduction screenshot at end.

With some debugging I tracked this down to the implementation of `magit-diff-hunk-region-patch` which failed because the buffer content with the patch wouldn't match the third line, since `(looking-at "\\(.\\)\\([^\n]*\n\\)")` is false on an entirely empty line.  (whitespace replaced for obvious reasons in the example text, as it is with `whitespace-mode`.)

```
·(defvar-local·projectile--mode-line·projectile-mode-line-prefix)¶
+(put·'projectile--mode-line·'risky-local-variable·t)¶
¶
·(defun·projectile-default-mode-line·()¶
···"Report·project·name·and·type·in·the·modeline."¶
```

Magit should probably set `diff.suppressBlankEmpty` false explicitly, or otherwise copy with that blank line.   Since this error left lingering diff content in place the rest of the parsing was probably thrown off, which is why magit would, eg, show some-but-not-all of the changed or staged files, etc, when there was more than one trivial change.

    M-x magit-version RET
    => Magit v2.90.1-1101-g068f8389, Git 2.29.2, Emacs 27.1, darwin

**screenshot of hunk parse failure**:
<img src="https://user-images.githubusercontent.com/306753/101244059-778c1c80-3704-11eb-8d78-219aa558ef4c.png">

**Comment by tarsius** [comment]
Yes. Please don't do that.

If you want to keep doing for use outside of Magit, then you have to undo it inside Magit by reversing the setting using `magit-git-global-arguments`.
