### ISSUE TITLE
Reword stash messages

### ISSUE THREAD

**Issue by dabrahams** [magit/magit#4267]
Often I find myself with a bunch of old stashed work, some of which is valuable, and it can be hard to sort through.  After I've decided which things to hang onto, often they have a non-descriptive message like "WIP on <branchname>". I'd like an easy way to change the message to something more useful.

Thanks!

**Comment by kyleam** [comment]
See gh-2650 for some past discussion of this.  There's a hacky command there that may work for your purposes.  (If you want to try it with the current magit though, you'll need to drop the second argument from the `magit-read-stash` call.)

**Comment by dabrahams** [comment]
I commented there; Please feel free to close this one as a duplicate if it's not helpful.
