### ISSUE TITLE
Allow wip modes for untracked files?

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#4271]
Hello,

currently the wip modes do nothing when I edit a file that is not tracked.  I think it would be beneficial if that would be made possible.  I'm not sure what extra setup would be necessary to allow that.

I have setup my home dir as a repository.  I don't want to track all files, but I want wip saves for any file I edit, apart from, maybe, very large files - these could be excluded or the user could be asked.

WDYT?

TIA, Michael.

**Comment by tarsius** [comment]
The original idea was to use git as the backend of regular emacs backups to be used for all files. I probably won't get around to that any time soon.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> The original idea was to use git as the backend of regular emacs
> backups to be used for all files. I probably won't get around to that
> any time soon.

Good to know, anyway.

I had tried to comment the `magit-file-tracked-p' condition in the code,
but it's not that simple, I got errors.  I stopped there, messing with
these references can cause trouble (I don't want to loose my other wip
commits).

**Comment by michael-heerdegen** [comment]
Another, related question: say I have accidentally added a wip commit, e.g. associated with  a very large file, and I already have other wip commits on top of that, and now I want to get rid of the accidental commit to save disk space.  How would you do that?  Interactive rebase with a detached head?  TIA - Michael.

**Comment by tarsius** [comment]
You have to manually delete (or rewind) the respective refs and then you have to manually run `git gc ...`.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> You have to manually delete (or rewind) the respective refs and then
> you have to manually run git gc ....

Does "manually" mean in the shell?

**Comment by tarsius** [comment]
You can (and should) use <kbd>X h</kbd> to do the resetting. But Magit provides no wrapper for `git gc`.

```
git gc --aggressive --prune=now
```

**Comment by michael-heerdegen** [comment]
That does not work as far as I can tell.  I used X h to hard-reset master to the commit the wip ref pointed to (by hash).  Then I used r i to delete some commits.  Then I reset master back to the original commit.  What l w showed was more or less unaffected by all of these actions, apart from the fact that some  added wip commits by themselves.  Disabling magit-wip-before-change-mode did not help (I had though that one might interfere).  gc took half of an hour or so (is the aggressive option really needed?).

**Comment by michael-heerdegen** [comment]
If you don't mind the question: Do you think I did it wrong or does it make sense what I said?

**Comment by tarsius** [comment]
My instructions probably were a bit misleading because I just responded to the last message.

You can reset the current branch using `X h`. However that does not reset respective wip refs. If you only do the former, then garbage collection does not do anything with the undesired commit because it is not actually garbage (it is still reachable from those refs).

The easiest way to remove the commit from those refs is to just delete those refs using e.g. `git update-ref -d refs/wip/index/refs/heads/master`. There's a ref containing `index` and one containing `wtree`. You need to delete both.

The wip modes might get confused by you simply wiping the wip refs. It's probably best to do this while emacs is not running.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> using e.g. git update-ref -d refs/wip/index/refs/heads/master.

Wouldn't that remove all of my wip history?  AFAIU what I want is that,
when the wip history is ... > X > Y > Z > ... with newer wip commits on
the right, when I want to get rid of Y I need to change the parent
commit of Z to X (instead of Y).

**Comment by tarsius** [comment]
Yes.

You can also use `git update-ref refs/... X` to rewind. Of course that also discards Z. And of course that can be prevented as well, but it is complicated, requires some testing, and I lack the time and motivation to write a guide about it.

**Comment by tarsius** [comment]
> The original idea was to use git as the backend of regular emacs backups to be used for all files. I probably won't get around to that any time soon.

Unless I do that, I don't think I will implement for untracked files. Doing just that would already complicate matters a lot. So much that additionally supporting tracking files *outside of any repository* would probably play a smaller part. Unless I do that too, it's not worth it.
