### ISSUE TITLE
Push should not default to origin/master when upstream is unset

### ISSUE THREAD

**Issue by dandavison** [magit/magit#4274]
Currently, when a branch upstream is not set, and we do `P u`, magit offers `origin/master` as the default remote to push to. This is true also for force push. I suggest that magit should not do that, because the cost of accidentally (force-) pushing to master is high, and the probability that a hasty user might accidentally enter `RET` to accept that default is also high.

I suggest that, when the upstream is unset, the magit UI should require the user to enter the name of the desired remote target, with completion.

magit-version: 20201218.1819

**Comment by tarsius** [comment]
You'll still have to enable this feature. See the commit.
