### ISSUE TITLE
DOCEDIT: option to start emacs in server mode using emacsclient when emacs server is not already running

### ISSUE THREAD

**Issue by edmwagner** [magit/magit#4278]
I noticed will looking for solution to another issue that [Manual](https://github.com/magit/magit/blob/master/Documentation/magit.org#user-content-git-commit-mode-isnt-used-when-committing-from-the-command-line:~:text=Tautology%20ahead.%20If%20you%20want%20to,then%20you%20cannot%20use%20emacsclient%20directly) for starting emacs could have an alterative for the staring emacs server.

I use this setting in my global git config for `core.editor`:

    git config --global core.editor "emacsclient --alternate-editor='' -c"

I looks like this in config file:

    [core]
        editor = emacsclient --alternate-editor='' -c

Adding ` -c` at the end after the two single quotes.  This may not work when `EDITOR` is defined with single and double quotes swapped.
 
See `emacsclient --help`

   
This looks to work with emacs >=26.1 included emacs 27.1 as there were a lot of updates and improvements to emacsclient in the time.

UPDATED:  I originally though I use the environment variable.  But git config takes precedence over environment variables in this case so I was really using the `core.editor` from git config the whole time.

**Comment by tarsius** [comment]
Also see https://github.com/magit/magit/issues/4178. That still stands.

That being said if you write a well tested and carefully worded guide on how to configure it, then I would probably more it. Until then I am closing this as "I don't want work on this because it is actually beyond the scope of this document".
