### ISSUE TITLE
git-commit-mode highlights pseudo headers incorrectly

### ISSUE THREAD

**Issue by alphapapa** [magit/magit#4279]
* Magit 20201225.4, Git 2.7.4, Emacs 26.3, gnu/linux
* Tested in a clean Emacs configuration (i.e. `emacs-sandbox.sh -i magit`)

I noticed that `git-commit-mode`'s highlighting of pseudo headers doesn't quite work correctly.  Here's a screenshot:

![python-4](https://user-images.githubusercontent.com/601365/103180320-58dbfa00-485a-11eb-9dcd-c24f9a34babb.png)

In case it helps, I'm attaching the text of the screenshot: [text.txt](https://github.com/magit/magit/files/5745315/text.txt)

As always, thanks for your work on Magit.

**Comment by tarsius** [comment]
I don't understand. That is `git log` output--what is it doing in the buffer that is being used to write the commit message and why do you expect `git-commit.el` to know how to prettify log output?

**Comment by alphapapa** [comment]
That's not a `magit-log` buffer, that's a `COMMIT_EDITMSG` buffer.  I was writing the commit message for a squash commit, and the `COMMIT_EDITMSG` buffer looked like that, with some parts highlighted using the `git-commit-pseudo-header` face, and others not, without any apparent pattern to where the boundaries are.  I guess the font-lock keywords need adjustment, but I'm not sure.

**Comment by tarsius** [comment]
> That's not a `magit-log` buffer, that's a `COMMIT_EDITMSG` buffer. 

I figured so much when I mentioned "the buffer that is being used to write the commit message".

> I was writing the commit message for a squash commit, and the `COMMIT_EDITMSG` buffer looked like that, 

I don't think I have ever seen a squash command do that, that's why I asked how that text ended up in that buffer. Did a magit command do that or did you squash on the command line? How?

Anyways...

For me the font-lock sometimes goes berserk even when that buffer contains more conventional text. I don't know why and also why no one has reported that until now. I haven't looked into it. I guess now I finally have to do it.

That being said, if this is a different issue that only kicks in when the buffer contains this (until now at least to me) unexpected text, then I am probably fine with that. We cannot properly propertize everything that might somehow end up in that buffer.

I would appreciate help with this. I have ignored it for so long, I will probably continue to do unless you or someone else helps me figure out what's going on. (I am gonna be busy for a while.)

**Comment by alphapapa** [comment]
> I don't think I have ever seen a squash command do that, that's why I asked how that text ended up in that buffer. Did a magit command do that or did you squash on the command line? How?

I did it all with Magit, i.e. in the `magit-status` buffer I pressed `m s` and then `c c`.

> That being said, if this is a different issue that only kicks in when the buffer contains this (until now at least to me) unexpected text, then I am probably fine with that. We cannot properly propertize everything that might somehow end up in that buffer.

Since I did it with Magit, and since it seems like a squash merge is a common thing to do, I was surprised that the resulting commit buffer was fontified inconsistently.

> I would appreciate help with this. I have ignored it for so long, I will probably continue to do unless you or someone else helps me figure out what's going on. (I am gonna be busy for a while.)

*shrug*  I don't do squash merges that often, and debugging font-lock-keywords isn't my idea of a good time, so I can live with it.

If anyone else comes along and wants to take a look, here are some helpful tools: https://github.com/alphapapa/emacs-package-dev-handbook#highlighting--font-locking

Thanks.

**Comment by alphapapa** [comment]
Well, I couldn't resist.  So here's what the result looks like now:
![fix](https://user-images.githubusercontent.com/601365/103182156-d3af1000-486e-11eb-9377-2025e7caa9ae.png)

If you want the `Date:` headers to be fontified also, that would be a simple change, so let me know.

The patch:
```diff
From 8d9e1e0327d602395564e3f4fec9953849396450 Mon Sep 17 00:00:00 2001
From: Adam Porter <adam@alphapapa.net>
Date: Sun, 27 Dec 2020 18:11:53 -0600
Subject: [PATCH] Fix: (git-commit-font-lock-keywords-1): Pseudo headers

---
 lisp/git-commit.el | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/lisp/git-commit.el b/lisp/git-commit.el
index 32c98d3..05c9445 100644
--- a/lisp/git-commit.el
+++ b/lisp/git-commit.el
@@ -866,7 +866,7 @@ Added to `font-lock-extend-region-functions'."
                        (regexp-opt git-commit-known-pseudo-headers))
               (1 'git-commit-known-pseudo-header)
               (2 'git-commit-pseudo-header)))
-    ("^[-a-zA-Z]+: [^<]+? <[^>]+>"
+    ("^[-A-Za-z]+:[[:blank:]]+[^\n<]+?[[:blank:]]+<[^\n>]+>[[:blank:]]*$"
      (0 'git-commit-pseudo-header))
     ;; Summary
     (eval . `(,(git-commit-summary-regexp)
-- 
2.7.4
```
BTW, @Lindydancer's `font-lock-studio` package made it so easy to find the problem.  It looked like this in-action:
![font-lock-studio](https://user-images.githubusercontent.com/601365/103182217-5df77400-486f-11eb-84b4-0fedbbebe98e.png)

Let me know what you want to do about the date headers, then I can send a PR, or you can just apply this patch if you want.

Thanks.

**Comment by a13** [comment]
offtopic: @alphapapa thank you very much for mentioning `xr`! #TIL

**Comment by tarsius** [comment]
> I did it all with Magit, i.e. in the `magit-status` buffer I pressed `m s` and then `c c`.

Squash merging, aye! Well I never do that, but when I just did, then it did insert a log for me as well.

> The patch:

Thanks!

> If you want the `Date:` headers to be fontified also, that would be a simple change, so let me know.

Sure, why not. How about the `commit a...9`? Would that be simple enough too? Seems like emphasizing that is way more important than either Author or Date.

**Comment by alphapapa** [comment]
> Sure, why not. How about the `commit a...9`? Would that be simple enough too? Seems like emphasizing that is way more important than either Author or Date.

Sure.  All with the `git-commit-pseudo-header` face, or a different face?

**Comment by tarsius** [comment]
Stick with the same face for now.

**Comment by alphapapa** [comment]
See PR.  Now looks like this: 
![fixed](https://user-images.githubusercontent.com/601365/103236760-508fc780-490b-11eb-985d-821c43120014.png)
