### ISSUE TITLE
Incorrect diffs for commits to be amended and strange behavior in `magit-diff-while-committing`

### ISSUE THREAD

**Issue by danielmartin** [magit/magit#4282]
**Steps to reproduce the problem:**

- `emacs -Q`.
- `M-x magit-init` and create an empty repository.
- Visit a `sample.txt` file in the new repository place this content and save it:

Hello, World!

- Stage and commit the new file as "First commit" (for example).
- Go back to `sample.txt` and change "Hello" with "Bye" (you can also add new lines if you want).
- Amend the changes (`c a`).

**Expected results:**

1. The commit message is reused from the commit you are amending. 
2. The diff window shows the changes to be committed. According to https://magit.vc/manual/magit/Editing-Commit-Messages.html#Editing-Commit-Messages, pressing C-c C-d should switch between all the changes or the new changes.

**Actual results:**

1. The commit message is reused from the commit you are amending (this is OK).
2. The diff window shows `(empty)`, which is strange. C-c C-d shows all changes to be committed, but pressing C-c C-d again does not switch back to showing the new changes.

Does the documentation reflect the current logic in `magit-diff-while-committing`?

Thanks.

**Comment by tarsius** [comment]
Is this one of the cases mentioned in #3246? In any case I am going to fix all those bugs at once but not necessarily any time soon.
