### ISSUE TITLE
Wrong options passed to `git update-index --cacheinfo`

### ISSUE THREAD

**Issue by janEbert** [magit/magit#4286]
1. ##### What behavior I expected
   After a `magit-ediff-dwim` session, I am asked to confirm whether the index should be updated according to my changes to the center ediff buffer (`<my-file>.~{index}~`) and whether to save the worktree file. I confirm both queries with `y` and expect the index as well as my worktree to be updated accordingly.
2. ##### What behavior I observed
   The index update does not occur because of an error:
```
129 git … update-index --cacheinfo 100644 <my-file>
error: option 'cacheinfo' expects <mode>,<sha1>,<path>
```
3. ##### How you can reproduce the issue.
   I did the whole process over TRAMP, so maybe that case messed up the options passed to `git update-index`.

    M-x magit-version RET
`Magit 20210105.1030, Git 2.18.4, Emacs 27.1.50, gnu/linux`

**Comment by tarsius** [comment]
It seems `(magit-git-string "hash-object" ...)` in `magit-update-index` returns `nil`. We have to figure out why. Do `(setq magit-git-debug t)`, repeat the action and get the error for `git hash-object ...` from the process buffer (`$`).

**Comment by janEbert** [comment]
Hi, sorry it took a bit longer. The machines had some issues.

```
128 git … hash-object -t blob -w --path\=dir/code.py -- /tmp/indexJFIkHh
fatal: Cannot open '/tmp/indexJFIkHh': No such file or directory

129 git … update-index --cacheinfo 100644 dir/code.py
error: option 'cacheinfo' expects <mode>,<sha1>,<path>
```

**Comment by tarsius** [comment]
I don't know how that is possible. Have a look at `magit-update-index`. Just before `git` apparently fails to find this file, we not only create it but also access it.

**Comment by tarsius** [comment]
Manually check if the file was created and what its content and permissions are.

**Comment by pritambaral** [comment]
The issue is reproducible. A synopsis of how it occurs is provided in the linked PR.

**Comment by janEbert** [comment]
Thank you for the fix!
