### ISSUE TITLE
Does magit support Collaborator ? If not will it be supported in no long future?

### ISSUE THREAD

**Issue by BaoshanPang** [magit/magit#4289]
It would be great to be able to submit my code into Collaborator directly through magit instead of using some extra commands.

Thanks,
Baoshan

**Comment by kyleam** [comment]
Collaborator refers to <https://smartbear.com/product/collaborator/overview/>?

At any rate, there's not support for it in Magit proper, and I'm not aware of an extension for it.  In my opinion something like that isn't a good fit for Magit itself; it'd be the sort of thing that an interested somebody (you?) would implement as an extension.

**Comment by tarsius** [comment]
If I added support for this "to magit", then I would actually add it to [forge](https://github.com/magit/forge) instead.

I recently added a [faq entry](https://github.com/magit/forge/wiki/FAQ#do-you-plan-to-addextend-support-for-forge-x) about supporting more forges, which essentially boils down to "I don't intend to do it myself".
