### ISSUE TITLE
Proposals for how to checkout a branch with HEAD detached

### ISSUE THREAD

**Issue by olavfosse** [magit/magit#4291]
I would like there to be an interactive way to checkout a branch with HEAD detached, as with `git checkout --detach`. Below are two proposals for how this could be done.

For an example of why one would want to do this, see [this](https://stackoverflow.com/a/65700762/14793677) SO answer by me.

Thanks

edit: Apologize for the many edits, I accidentally published my issue prematurely.

---

1. If the user tries to checkout a branch which is already checked out in another worktree, the user would be prompted something like this: "The branch master is already checkout out in worktree wrktr, do you wish to check it out head detached (y/n)?". There could be a variable that if set, skipped the prompt and always checked out with detached head or didn't check out at all.

2. An alternative under `magit-branch` > checkout > "local branch HEAD detached". I am less in favor of this.

**Comment by fossegrim** [comment]
PS: If this is of interest I will gladly try implementing it myself. Just tell me which proposal, or how you think it would best be implemented, and reserve it for me for some amount of time and I will see what I can do :-).

**Comment by tarsius** [comment]
You can already check out the commit at point using `b o` followed by `M-n` (`next-history-element`) and then `RET`.

This is a technique is not my invention, some commands that are part of Emacs also use the initial "next history element" to provide some secondary default like this.

**Comment by tarsius** [comment]
Of course I meant `b b`...

**Comment by fossegrim** [comment]
I don't understand how that allows me to check out a branch HEAD detached.

https://user-images.githubusercontent.com/24797093/104453231-65738880-55a4-11eb-8081-3cb87b1e6c9f.mp4

**Comment by tarsius** [comment]
1. Clone the magit repository and how the status buffer for it.
2. Move to the line that reads `25f432551 * origin/master magit-commit-ask-to-stage: Reduce width of doc-string`.
3. Press `b b`. This gives you a minibuffer with content `Checkout: `.
4. Press `M-n`. This changes the minibuffers content to `Checkout: 25f432551`.
5. Press `RET` to checkout `25f432551` directly.

**Comment by fossegrim** [comment]
That does not work for me, even with `emacs -q` I just get `origin/diff-parse`.

**Comment by kyleam** [comment]
I can't see your screencast, but your point needs to be at the commit hash for the `M-n` trick to work.  Another approach: you can append `^0` (short for `^{commit}`) to a ref to dereference the object, getting the associated commit (e.g., `b b master^0` will created a detached head at the commit that master points to).

**Comment by fossegrim** [comment]
> I can't see your screencast, but your point needs to be at the commit hash for the `M-n` trick to work. 

Hmm, I tried it with point at the commit hash. For commits without branches on them, I get the hash, otherwise I get branch name.

> Another approach: you can append `^0` (short for `^{commit}`) to a ref to dereference the object, getting the associated commit (e.g., `b b master^0` will created a detached head at the commit that master points to).

That works and is indeed an interactive way of checking out a branch headlessly. I concede, thanks for showing me.

Either way, I still think that prompting the user to checkout a branch headlessly, when trying to checkout a branch already checked out in another worktree, would be an improvement compared to just failing with a git error.

Consider this issue, repurposed to requesting the behaviour described in the previous paragraph.

**Comment by fossegrim** [comment]
> I can't see your screencast, but your point needs to be at the commit hash for the `M-n` trick to work. 

Hmm, I tried it with point at the commit hash. For commits without branches on them, I get the hash, otherwise I get branch name.

> Another approach: you can append `^0` (short for `^{commit}`) to a ref to dereference the object, getting the associated commit (e.g., `b b master^0` will created a detached head at the commit that master points to).

That works and is indeed an interactive way of checking out a branch headlessly. Sorry for imlplying that it was not possible interactively, I concede, thanks for showing me.

Either way, I still think that prompting the user to checkout a branch headlessly, when trying to checkout a branch already checked out in another worktree, would be an improvement compared to just failing with a git error.

I will close this issue now and request this behaviour in a clean new issue.

Thanks.

**Comment by tarsius** [comment]
> your point needs to be at the commit hash for the `M-n` trick to work

I cannot figure out where that is implemented anymore. Please point me to the code that makes that happen. :blush:

**Comment by kyleam** [comment]
> Please point me to the code that makes that happen

I'm using ivy, and, taking another look, it looks like the behavior comes from the ivy's wrapper for `next-history-element` (which explains why @fossegrim reported not seeing the behavior).  The commit at point is inserted by the marked line below:

```elisp
(defun ivy-next-history-element (arg)
  "Forward to `next-history-element' with ARG."
  (interactive "p")
  (if (and (= minibuffer-history-position 0)
           (equal ivy-text ""))
      (progn
        (when minibuffer-default
          (setq ivy--default (car minibuffer-default)))
        (insert ivy--default)  ; <====================================
        (when (and (with-ivy-window (derived-mode-p 'prog-mode))
                   (eq (ivy-state-caller ivy-last) 'swiper)
                   (not (file-exists-p ivy--default))
                   (not (ivy-ffap-url-p ivy--default))
                   (not (ivy-state-dynamic-collection ivy-last))
                   (> (point) (minibuffer-prompt-end)))
          (ivy--insert-symbol-boundaries)))
    (next-history-element arg))
   ...)
```

And `ivy--default` is set to the thing at point in `ivy--reset-state`:

```elisp
    (setq ivy--default
          (if (region-active-p)
              (buffer-substring (region-beginning) (region-end))
            (ivy-thing-at-point)))
```

**Comment by tarsius** [comment]
Ha! So we both thought we had implemented this.

We probably should implement this for the default completion mechanism as well. But I am currently staring down the rabbit hole that is completion and am not sure I want to take a leap right now. It's pretty scary.

I'll reopen this issue as a reminder.

**Comment by phil-s** [comment]
As a workaround, with point at the hash in question, you can of course do this:

`M-d b b C-y RET`
