### ISSUE TITLE
Issue defering git-commit

### ISSUE THREAD

**Issue by Ergus** [magit/magit#4293]
Hi: 

Recently I have seen an increase in my loading time when opening files in git repositories (like: emacs myfile). The increase seems to be related with the loading of many packages/dependencies I cannot defer properly because they are loaded when calling `git-commit-setup-check-buffer`. So different questions come to me now:

1) `global-git-commit-mode` is `t` by default... this makes it very difficult to disable it without autoloading the package first (dependencies like log-edit are very "heavy"). The code goes in the quickstart but also I am not sure if it is right to enable by default global external packages modes that are not in vanilla... is this intended?? So only installing the package will affect the user.

2) I also see that the function `git-commit-setup-check-buffer` is somehow a manual implementation for what `auto-mode-alist` does and needs to be added to `find-file-hook`... which means that it always autoloads the git-commit package. Is this intended?? Isn't it just the same and simpler to add the git-commit-setup and the related hooks to a minor mode and set that to auto-mode-alist?? That may take care of the autoloading properly deffering that and specially does not affect the loading time just because the user installed (probably indirectly) git-log as a magit dependency.

3) As a consequence of 1 `package-quickstart` has this code:
```
(defcustom global-git-commit-mode t 
  :set #'custom-set-minor-mode 
  :initialize 
    (lambda (symbol exp) 
      (custom-initialize-default symbol exp) 
      (when global-git-commit-mode (add-hook 'find-file-hook 'git-commit-setup-check-buffer))) 
  :group 'git-commit 
  :type 'boolean)
```
Which means that `global-git-commit-mode` needs to be set to nil in the early-init to avoid the unconditional autoloading. Otherwise `global-git-commit-mode` will always be true. This problem is somehow recent so it seems it is related with some recent change in git-log or magit... is it??

This also breaks my `use-package` config that used to be very simple and efficient.

Thanks in advance,
Ergus

**Comment by tarsius** [comment]
> Which means that `global-git-commit-mode` needs to be set to nil in the early-init to avoid the unconditional autoloading. Otherwise `global-git-commit-mode` will always be true.

IMO that's acceptable.

> This problem is somehow recent so it seems it is related with some recent change in git-log or magit... is it??

I don't think it is.

**Comment by basil-conto** [comment]
> Which means that `global-git-commit-mode` needs to be set to nil in the early-init to avoid the unconditional autoloading.

(Or package activation deferred until `user-init-file` via `package-enable-at-startup`.)

**Comment by Ergus** [comment]
> > Which means that `global-git-commit-mode` needs to be set to nil in the early-init to avoid the unconditional autoloading. Otherwise `global-git-commit-mode` will always be true.
> 
> IMO that's acceptable.
> 
Actually, after some tests I found that this doesn't defer at all. So the package is always loaded any way either to call the `(global-git-commit-mode nil)` or when calling the hook.

I only need magit that has the autoloaded commands properly... Why I cannot defer this package that is only a magit dependency for me? But also, why it does not use `auto-mode-alist` that must properly solve all the defer issues properly?

**Comment by Ergus** [comment]
> > This problem is somehow recent so it seems it is related with some recent change in git-log or magit... is it??
> 
> I don't think it is.

else then some recent change in vanilla master exposed the issue.

**Comment by basil-conto** [comment]
FWIW, here's how I defer `git-commit` in my `user-init-file`:

```el
(setq-default global-git-commit-mode nil)

(when (boundp 'git-commit-filename-regexp)
  (add-to-list 'auto-mode-alist
               (cons git-commit-filename-regexp #'git-commit-setup)))
```

See also #3070.

**Comment by Ergus** [comment]
> FWIW, here's how I defer `git-commit` in my `user-init-file`:
> 
> ```emacs-lisp
> (setq-default global-git-commit-mode nil)
> 
> (when (boundp 'git-commit-filename-regexp)
>   (add-to-list 'auto-mode-alist
>                (cons git-commit-filename-regexp #'git-commit-setup)))
> ```
> 
> See also #3070.

Yes, that's more or less what I have in my config now... with the first part in the early init and the rest in the `:mode` section of my `use-package`. My main concern is why this is not implemented in this package as in almost all the other packages... instead of using a hook and enabling a global mode without user desire, calling the setup and so on...

Isn't this package's functionality just as any other minor mode around??

**Comment by tarsius** [comment]
I've had another look and the slowdown really is massive so I decided to remove the autoloading.

**Comment by Ergus** [comment]
> I've had another look and the slowdown really is massive so I decided to remove the autoloading.

Very thanks. Does it makes sense to add an entry to auto-mode-alist in order to load `git-commit-setup` when editing a commit. For example, when we call `git commit` from the terminal that opens emacs to edit the commit message??

It is similar to what @basil-conto  suggested https://github.com/magit/magit/issues/4293#issuecomment-761893316 without the when and with a single autoload... I still don't get why git-commit doesn't use the auto-mode-alist mechanism.

Or are there some magit config to do so??

**Comment by tarsius** [comment]
> I still don't get why git-commit doesn't use the auto-mode-alist mechanism.

`auto-mode-alist` is for major-modes but `git-commit-mode` is a minor-mode.

`git-commit-mode` is a minor-mode so that you can use whatever text mode makes sense for a given repository; `text-mode`, `markdown-mode` or `org-mode` for example.

**Comment by NimoTh** [comment]
Good to see improvements in this regard. Unfortunately, this broke my setup :-) I simply had `(global-git-commit-mode)` in my init.el. I run git commit from a terminal most of the time. Using use-package, what would be the recommended way to ensure git-commi-mode is loaded when I edit a commit message? If I want to use `git-commit-filename-regexp` to setup autoloading, isn't there a henn-egg-problem because that one is not autoloaded, either?
TIA

**Comment by tarsius** [comment]
> The autoloads triggered full loading as soon as the user created
> any buffer.  The autoloads had to do that to be of any use, which
> means that they had nearly the same effect as loading the library
> explicitly, which unfortunately is very slow.

> Now that the autoloads are gone, users can actually choose whether
> they want to pay that price.  Most users likely won't notice that
> anything has changed as this only matter when one sometimes commits
> from the command-line without loading `magit' first.

In other words just `(require 'git-commit)`, which isn't any worse than the old autoloads.
