### ISSUE TITLE
Prompt to checkout a branch with HEAD detached, on attempts to checkout a branch which is already checked out in another worktree

### ISSUE THREAD

**Issue by fossegrim** [magit/magit#4294]
Currently if the user tries to checkout a branch which is already checked out in another worktree, a git error is outputted. I think this could be better handled if Magit where to display a prompt informing the user that  the branch is already checked out and prompting the user to either checkout the commit of the branch with HEAD detached or cancel the operation.

**Current behaviour**
Scenario: `master` is checked out in worktree `/path/to/worktree`.

- User runs `M-x magit-checkout master`.
- User gets error `fatal: 'master' is already checked out at '/path/to/worktree'`

**Requested behaviour**
Scenario: `master` is checked out in worktree `/path/to/woktree`.

- User runs `M-x magit-checkout master`
- User gets prompt "master is already checked out at '/path/to/worktree'. Do you wish to check out <hash of master> with HEAD detached (y/n)?"

If the user answers 'y' it checks out the commit of master with HEAD detached. Otherwise it does nothing.

**Comment by tarsius** [comment]
That would be nicer, but I don't think implementing this would be worth the effort.

**Comment by zaeph** [comment]
I've been running into similar bumps lately.  How much trouble would it be to `y/n` a jump to the worktree where the branch is checked out?  I could take care of the implementation if we like this.

**Comment by tarsius** [comment]
If you want to give it a try then see "Branch %s is checked out.  " in `magit-branch-delete` and do something similar, implementing abort as well as the two alternative behaviors suggested so far.

**Comment by zaeph** [comment]
Great; I'll take a look at it when I have some time next week.
