### ISSUE TITLE
Migrate from Travis CI to GitHub Actions?

### ISSUE THREAD

**Issue by CyberShadow** [magit/magit#4300]
As the future of Travis CI [seems to be, at best, uncertain](https://news.ycombinator.com/item?id=25338983), it may make sense to migrate to another CI service. As magit is hosted on GitHub, GitHub Actions seem to be a good fit.

npostavs/emacs-travis can be replaced with [purcell/setup-emacs](https://github.com/purcell/setup-emacs).

A related task would be to also enable code coverage reports.

Today I migrated [Emacs-D-Mode](https://github.com/Emacs-D-Mode-Maintainers/Emacs-D-Mode) to GitHub Actions, and added support for GitHub Actions to [undercover.el](https://github.com/undercover-el/undercover.el) (which we use to [upload coverage reports to Coveralls](https://coveralls.io/github/Emacs-D-Mode-Maintainers/Emacs-D-Mode?branch=master)). So, I would be happy to submit a pull request implementing a similar setup for the magit repository.

**Comment by tarsius** [comment]
> As the future of Travis CI [seems to be, at best, uncertain](https://news.ycombinator.com/item?id=25338983), it may make sense to migrate to another CI service. As magit is hosted on GitHub, GitHub Actions seem to be a good fit.

The plan was to wait until things break to add some urgency to this migration. :grinning: 

> npostavs/emacs-travis can be replaced with [purcell/setup-emacs](https://github.com/purcell/setup-emacs).

@npostavs is a magit maintainer so that was an advantage of using his tooling, but @purcell's approach seems better in the long-run, and he is a helpful fellow as well. :wave: I would have preferred guix because of the lisp. :turtle: :turtle: :turtle: ... :smile: 
 
> A related task would be to also enable code coverage reports.

Yeah... that would be embarrassing though, so maybe don't do that just yet.

> Today I migrated [Emacs-D-Mode](https://github.com/Emacs-D-Mode-Maintainers/Emacs-D-Mode) to GitHub Actions, and added support for GitHub Actions to [undercover.el](https://github.com/undercover-el/undercover.el) (which we use to [upload coverage reports to Coveralls](https://coveralls.io/github/Emacs-D-Mode-Maintainers/Emacs-D-Mode?branch=master)). So, I would be happy to submit a pull request implementing a similar setup for the magit repository.

Great! That would be very welcome.

**Comment by CyberShadow** [comment]
> The plan was to wait until things break to add some urgency to this migration. grinning

I don't know if it's related or not, but Travis CI has stopped posting commit statuses to my GitHub repositories... This was what triggered me to migrate.

> Yeah... that would be embarrassing though, so maybe don't do that just yet.

Ah. Well, it's difficult to improve what can't be measured. Perhaps collect and render coverage information, but don't advertise this anywhere yet? :)

> Great! That would be very welcome.

OK, here it is: #4303

**Comment by npostavs** [comment]
> @npostavs is a magit maintainer so that was an advantage of using his tooling

As far as I remember the other stuff didn't exist at the time (I think evm did exist, but didn't have any pre-built binaries yet, so it was a ~15 min build to run ~1min test). Looking at the Github Actions docs I could probably replicate the setup there too, but assuming purcell's thing works fine we may as well use that.

**Comment by basil-conto** [comment]
> assuming purcell's thing works fine

FWIW, it's been working fine for Dash for the last month.

**Comment by tarsius** [comment]
> > Yeah... that would be embarrassing though, so maybe don't do that just yet.
> 
> Ah. Well, it's difficult to improve what can't be measured. Perhaps collect and render coverage information, but don't advertise this anywhere yet? :)

Let's do that.
