### ISSUE TITLE
Unable to open repolist with missing "Path" column

### ISSUE THREAD

**Issue by Karrq** [magit/magit#4301]
What behavior I expected: opening magit repolist, and sorting by last sorted column 
What I observed: couldn't open repolist
How to reproduce: simply set `magit-repolist-column` to not have any "Path" column

Backtrace:
```
Debugger entered--Lisp error: (error "No column named Path")
  error("No column named %s" "Path")
  tabulated-list--column-number("Path")
  tabulated-list--get-sorter()
  tabulated-list-print()
  magit-list-repositories()
  funcall-interactively(magit-list-repositories)
  command-execute(magit-list-repositories)
```

Magit version:
`Magit 21454777, Git 2.30.0, Emacs 28.0.50, gnu/linux`

---

I tried searching the documentation or online but I wasn't able to find anything referencing this.
I did some looking around and found that `tabulated-list-sort-key` is [hardcoded](https://github.com/magit/magit/blob/86eec7ba39eb46fa1e4c2f37800d22c6dfd155c7/lisp/magit-repos.el#L160) to "Path".

I tried readding the column, sorting by another column, and removing and reopening the repolist but I still got the error.
Would be nice if either it sorted by the first column encountered or by the last column sorted...

Note:
I'm using Doom Emacs

**Comment by kyleam** [comment]
Thanks for reporting.  With 0390cebd, the label from the first column will be used if a path column isn't available.
