### ISSUE TITLE
Commit doesn't work with a point centered mode

### ISSUE THREAD

**Issue by asif-mahmud** [magit/magit#4304]
(1) what behavior you expected
In magit buffer, if i press `c c` to commit when the point is over `Staged changes` section, a commit message buffer would come up and let me type in the commit message.

(2) what behavior you observed
First magit buffer shows a error message like the following - 
```
GitError! There was a problem with the editor '/usr/bin/emacsclient --socket-name=/run/user/1000/emacs/server'.  [Type `$' for details]
```
Then when i press `$` then it shows the following - 
```
hint: Waiting for your editor to close the file...
Waiting for Emacs...
*ERROR*: ‘recenter’ing a window that does not display current-buffer.
error: There was a problem with the editor '/usr/bin/emacsclient --socket-name=/run/user/1000/emacs/server'.
Please supply the message using either -m or -F option.
```

(3) and how we can reproduce the issue.

I have the following code snippet in my init script - 

```
(define-minor-mode centered-point-mode
  "Alaways center the cursor in the middle of the screen."
  :lighter "..."
  (cond (centered-point-mode (add-hook 'post-command-hook 'line-change))
        (t (remove-hook 'post-command-hook 'line-change)))
  )

(defun line-change ()
  (recenter)
  )

(add-hook 'prog-mode-hook 'centered-point-mode)
```

This is not mine, copied it. I am no expert in elisp, i can do little tweaks only. So i understand is this code keeps my point at center position of the buffer, thats what i wanted and it does that quite well. I suspect this part is somehow not letting magit commit buffer to work properly, cause if i turn centered-point-mode off, then the commit buffer works expectedly.

Emacs version: 27.1 (archlinux)
Magit version: Magit 20210124.2150, Git 2.30.0

Please let me know if the above code snippets needs to adjusted or is it magit. Either way thanks in advance.

**Comment by tarsius** [comment]
This would probably do the trick.

```elisp
(defun line-change ()
  (when (eq (get-buffer-window)
            (selected-window) )
    (recenter)))
```

**Comment by asif-mahmud** [comment]
Thank you so much, its working with your code.
