### ISSUE TITLE
magit-reset when current line is on a line in the reflog should DWIM

### ISSUE THREAD

**Issue by glittershark** [magit/magit#4307]
Lots of other stuff in magit seems to DWIM like this, and it's *delightful*. I love that apply does different things depending on where my cursor is, etc. It seems like mostly an unintentional omission that if my cursor is on a line in a reflog and I do magit-reset, the prompt for which commit to reset to isn't preselected with the commit my cursor is on.

**Comment by kyleam** [comment]
> the prompt for which commit to reset to isn't preselected with the commit my cursor is on

It may not show the hash for the commit at point, but the default candidate should at least be a name that refers to the commit at point.  reset commands will end up calling `magit-branch-or-commit-at-point`, which tries to assign a name to the revision before returning it:

https://github.com/magit/magit/blob/f6098f702a6d0bd922d40d940a41ef2c7e312bef/lisp/magit-git.el#L1291-L1298

**Comment by glittershark** [comment]
Hmm, maybe this is actually a bug report then, because for me it's defaulting to the name of the current branch. Does `magit-branch-or-commit-at-point` not work in reflogs?

**Comment by glittershark** [comment]
interesting - I checked, and `magit-branch-or-commit-at-point` does return the correct commit for me on the reflog. I wonder what's breaking here for me. Likely a result of my specific config.

**Comment by glittershark** [comment]
now I'm trying it again, and it's having the expected behavior. I'll close this for now, and see if I can find a way to reliably reproduce.

Thanks for the (ridiculously) quick triage @kyleam!
