### ISSUE TITLE
Add support for angular to git-commit-style-convention-checks

### ISSUE THREAD

**Issue by eyal0** [magit/magit#4313]
[Angular-style commit messages](https://gist.github.com/brianclements/841ea7bffdb01346392c) are very popular now.  The standard makes it easy for software to process git logs and extract useful information, including automatically generating the correct version number according to [semantic versioning](https://semver.org/).

I propose that a check for angular style commit messages should be added to `git-commit-style-convention-checks`.  Though it would be possible for users to write their own function and add it to `git-commit-check-style-conventions`, it's common enough that it would be worthwhile to add for all users.

I'm able to write this code and will start on it.

**Comment by tarsius** [comment]
> Angular-style commit messages are very popular now.

That's the first time I heard of them, so this probably depends a bit on whether you do javascript or not.

> I propose that a check for angular style commit messages should be added to `git-commit-style-convention-checks`.

Additional checks could be added but they should be opt-in and they should probably be implemented using a new `git-commit-finish-query-functions` function.

I looked at these conventions and consider them fairly opinionated. For people who want to (or are asked to) use these conventions, it would be nice if more than a simple style-checker existed. I think it would therefore be best to implement this as a separate package.

Such a package could for example provide type and scope completion. `git-commit` itself but also `hl-todo` could serve as inspiration for the sort of feature such a package might want to provide and how to implement them.

**Comment by eyal0** [comment]
I heard about them not through javascript usage but rather by looking at tooling around releases.  GitHub Actions have some plugins that will scan your commits since the most recent release and figure out the correct version number for you and also create a nice summary of the changes.

If i were to put it into a package, I think that it wouldn't be discoverable enough.  People wouldn't find it so I don't think that it would be worth going through the trouble of packaging it.  So I'll probably just write my own function and add it to the existing hook.

Probably there is already a commit-msg hook for git that does it, too.

I think that there is no action for magit here.  Thanks!
