### ISSUE TITLE
magit-reset-soft should default to HEAD^1 if no commit is selected.

### ISSUE THREAD

**Issue by verhovsky** [magit/magit#4315]
Out of the last 10 times that I've used `O s` (which btw, why does it say `X s` in [the documentation](https://magit.vc/manual/magit/Resetting.html)? I don't think I configured this, and it [doesn't look like Doom Emacs configures this either](https://github.com/hlissner/doom-emacs/blob/16a495c97dd796ec20939d07bad3beb38586a1fe/modules/tools/magit/autoload.el)), I typed in `HEAD^1` (i.e. reset the previous commit) 10/10 times. It would be useful for me and I assume others if this was already the default if I didn't have a commit selected, because currently it pre-fills the branch I'm on, which is already pointing to the latest commit and reseting to the latest commit does nothing. 

Otherwise the fastest way to reset to the previous commit is to do `l l` and move down to the previous commit and then press `O s`, right?

**Comment by kyleam** [comment]
Fwiw there is previous discussion on this at gh-4189.

> which btw, why does it say `X s` in [the documentation](https://magit.vc/manual/magit/Resetting.html)?

`X` is the default key for the `magit-reset` transient.  `O` is bound to `magit-subtree` by default.

https://github.com/magit/magit/blob/13f20763ada7c9c9252fe146f5ec5643ce7b66c4/lisp/magit-mode.el#L390

https://github.com/magit/magit/blob/13f20763ada7c9c9252fe146f5ec5643ce7b66c4/lisp/magit-mode.el#L375

**Comment by tarsius** [comment]
`X` comes from `evil-collection-magit-popup-changes`.

**Comment by verhovsky** [comment]
> Fwiw there is previous discussion on this at gh-4189.

I'll close this as a duplicate then. I still think this should be the default (or at least a config option?), but your snippet works for me, thanks.
