### ISSUE TITLE
[Feature Request] Integration for git-credential-manager-core

### ISSUE THREAD

**Issue by ztlevi** [magit/magit#4318]
Hi,

I recently switch to [git-credential-manager-core](https://github.com/microsoft/Git-Credential-Manager-Core) as my default git credential helper across all platforms. But I realized I have to authenticate it via command line for the first time on my new machine. 

Could you take a look at this? 

It would be great if magit could have a helper function to download and configure it out of box as well.

## Reproduce
In order to reproduce this, you will need to init pass on linux and delete saved credential under `$HOME/.local/share/password-store/git/https/github.com` if needed. 

You git config will have something like this.

```
[credential]
	helper = /usr/local/bin/git-credential-manager-core
```

Thanks!

**Comment by tarsius** [comment]
Please provide the output of an example session on the command-line, so that I don't have to install this myself.

Most likely we just have to modify `magit-process-password-prompt-regexps` and/or some related option.

**Comment by ztlevi** [comment]
@tarsius Thanks!

There are a few options there.
1. Open the web browser and auth via web page. Only work on client machine.
```
✖ git push
Select an authentication method for 'https://github.com/':
  1. Web browser (default)
  2. Personal access token
option (enter for default): 1
info: please complete authentication in your browser...
```
2. Use personal access token. Should work for both ssh environment and client.
```
✖ git push
Select an authentication method for 'https://github.com/':
  1. Web browser (default)
  2. Personal access token
option (enter for default): 2
Enter GitHub personal access token for 'https://github.com/'...
Token:
```
3. If under a ssh environment.

**Comment by tarsius** [comment]
Please give this a try:

```diff
diff --git a/lisp/magit-process.el b/lisp/magit-process.el
index edd250c60..5aa61e81c 100644
--- a/lisp/magit-process.el
+++ b/lisp/magit-process.el
@@ -172,7 +172,10 @@ (defcustom magit-process-password-prompt-regexps
     "Please enter the passphrase to unlock the OpenPGP secret key"
     "^.*'s password: ?$"
     "^Yubikey for .*: ?$"
-    "^Enter PIN for .*: ?$")
+    "^Enter PIN for .*: ?$"
+    ;; For git-credential-manager-core: #4318
+    "option (enter for default): "
+    "Token: ")
   "List of regexps matching password prompts of Git and its subprocesses.
 Also see `magit-process-find-password-functions'."
   :package-version '(magit . "2.8.0")
```

**Comment by ztlevi** [comment]
@tarsius Thanks! It works!

1. How did you copy that colorful git diff section and render it on github?
2. I realized messages will not pop up and I need to open the magit log buffer by pressing `$`. For new users, they might miss messages like 
```
Select an authentication method for 'https://github.com/':
  1. Web browser (default)
  2. Personal access token
```
```
To complete authentication please visit https://github.com/login/device and enter the following code:
0D6A-C0D5
```
   This might cause problems for them to properly authenticate. Is there a way to pop those messages out?

**Comment by tarsius** [comment]
Check out the ` do-4318` branch.

**Comment by ztlevi** [comment]
@tarsius I tried but it doesn't pop up `magit-process` buffer or let me type options. Then I add `(edebug)` at this [line](https://github.com/magit/magit/commit/301eebb5e12cb6a589354cb0a3e29eb6a0c4b3cd#diff-f9ce4e1fa926529ddc27ce396848ad0fa1ab5897c8cce930746321b91f4f52aaR815). And add hook as well, but it doesn't work. Something's wrong with `magit-process-find-password-functions`.

**Comment by tarsius** [comment]
The hook mentioned in the doc-string was wrong. Please try again with the correct hook.

**Comment by ztlevi** [comment]
@tarsius It doesn't pop up buffer `(magit-process-display-buffer process)`. But it triggers the functions now.

**Comment by tarsius** [comment]
Right. Another small mistake. This should be `(magit-process-buffer)`. In the default configuration `magit-process-display-buffer` ends up not showing the buffer. Yes, the names confused me here; they are due to historic events. :grin:

**Comment by ztlevi** [comment]
@tarsius Thanks! it works! You can merge it now...

**Comment by ztlevi** [comment]
@tarsius Do we need to add the hook by default?

**Comment by tarsius** [comment]
Maybe. Is this popular yet?

**Comment by ztlevi** [comment]
Hmm, it has 600 stars on Github now. https://github.com/microsoft/Git-Credential-Manager-Core

I don't think there are too many ppl care about this 🥲. But they might integrate it into things like VSCode, Azure services in the future. You know, most ppl don't maintain their own .gitconfig TBH.

**Comment by tarsius** [comment]
For now I have just added this: https://github.com/magit/magit/wiki/Authentication.

**Comment by Rajeta-Sarkar** [comment]
@ztlevi thanks it worked for me.
