### ISSUE TITLE
magit-process-password-prompt not called in synchronous magit-run-git

### ISSUE THREAD

**Issue by thisch** [magit/magit#4323]
I have a problem with `magit-run-git`, which doesn't ask me for the keyring password when my keyring is not yet unlocked.
However, when I use the async version of `magit-run-git`, called `magit-run-git-async`, I see the password prompt.

Is it possible to get the password prompt also for the sync version?

*Calltrees*:
```
magit-run-git-async -> magit-start-git -> magit-start-process (magit-process-filter -> magit-process-password-prompt)
magit-run-git -> magit-call-git -> magit-call-process (doesn't call magit-process-password-prompt)
```

*Why do I ask?*

I have a function, which calls several git commands in a row using `magit-run-git/magit-call-git`.  This function is often called  as the first git function after a login. Therefore, it fails due to missing credentials.

**Comment by tarsius** [comment]
> Is it possible to get the password prompt also for the sync version?

No. Instead you should use a sentinel to call the next command. See `magit-delete-remote-branch-sentinel` as an example.

**Comment by thisch** [comment]
IMO the sentinel code is a bit hard to use. What do you think about the following minimal example?

```elisp
(progn
  (magit-run-git-async "fetch"
                       "--all")
  (set-process-sentinel
   magit-this-process
   (lambda (process event)
     (when (memq (process-status process) '(exit signal))
       (if (not (zerop (process-exit-status process)))
           ;; error
           (magit-process-sentinel process event)

         (message "git-fetch was successful")

         ;; Where should I call `magit-process-sentinel` and should I set `inhbit-refresh` before calling it?

         (magit-call-git "tag" "-l")
         (magit-process-sentinel process event))))))
```

I guess this is the intended way to chain an async command with a sync command, right? Probably `magit-process-sentinel` should be called before my sync git call, because `magit-process-sentinel` calls `magit-process-finish`.

**Comment by tarsius** [comment]
Run `magit-process-sentinel` in the same place as in `magit-delete-remote-branch-sentinel` and with the same arguments. Also like in `magit-delete-remote-branch-sentinel` call `magit-refresh` at the end.
