### ISSUE TITLE
magit use too much memory/cpu when selection in buffer, cause emacs hung.

### ISSUE THREAD

**Issue by algogavin** [magit/magit#4324]
I had used magit within emacs without problem for years. But recently I update magit (along with others pacakges in emacs), then I notice that it will stuck whenever I do "selection" in the magit buffer. [For example, I want to select multiple files to be committed. ]   Then I did the profile in emacs and find the excess memory being used by magit.  I have to "ctrl-G" to terminate the selection and everything back to normal.  Note that, it only occurred in "magit-mode", I can do the same selection in other modes without problem.[For example, in a c++mode].

magit-version >>
Magit 20210128.1702, Git 2.18.0, Emacs 27.1, gnu/linux

I use emacs' profiler to show show cpu/mem usage.
![image](https://user-images.githubusercontent.com/44672953/108153533-5e5eff00-70a9-11eb-9dc8-87ef96cb1e06.png)

Actually, I find that "stage a file" also has the issue now
![image](https://user-images.githubusercontent.com/44672953/108153988-2e642b80-70aa-11eb-8796-40f99fd595e6.png)

**Comment by tarsius** [comment]
I cannot think of any "recent" changes that might cause that and suspect that a change somewhere else caused this change in behavior. Because I have enough other things on my plate, I do not plan to investigate this report any time soon.
