### ISSUE TITLE
magit-section depends on bitmap definitions in magit-utils.el.

### ISSUE THREAD

**Issue by ROCKTAKEY** [magit/magit#4325]
Thanks for your great packages. I love magit and magit-section!!

 This bug report is not for magit but for magit-section released by melpa (magit-section-20210124.1824).
Magit-section is released independently, but [some code](https://github.com/magit/magit/blob/c3505b6934b8d5133d1bdb7e3d6ace147532ccc1/lisp/magit-section.el#L137) in magit-section.el depends on [bitmaps definitions](https://github.com/magit/magit/blob/c3505b6934b8d5133d1bdb7e3d6ace147532ccc1/lisp/magit-utils.el#L1145) in magit-utils.el, which is not bundled with magit-section. The bitmap definitions seem to be used only by magit-section, so why don't you move to magit-section.el? Or adding magit-utils.el to recipe for magit-section also seems to work.

The bug reported below should be caused by the dependency problem above.
 
# what behavior you expected
Bitmap image like `>` or `v` is displayed in left fringe next to line inserted by `magit-insert-heading` in `magit-insert-section`, **even without `(require 'magit-utils)`**.
![image](https://user-images.githubusercontent.com/20369462/108507883-521faf80-72fe-11eb-83e6-d3cdb7aa89aa.png)

# what behavior you observed
No bitmap image on fringe is shown, without `(require 'magit)` or `(require 'magit-utils)`.
![image](https://user-images.githubusercontent.com/20369462/108507771-27cdf200-72fe-11eb-80c8-4436b6d5072a.png)

# How we can reproduce the issue
Without `(require 'magit)` or `(require 'magit-utils)`, eval (by C-x C-e):
```emacs-lisp
(magit-insert-section (example)
  (magit-insert-heading "Example heading")
  (insert "Content\n")
  (insert "Content\n"))
```

**Comment by tarsius** [comment]
Thanks!
