### ISSUE TITLE
Redisplay asynchronously?

### ISSUE THREAD

**Issue by jcs090218** [magit/magit#4328]
Magit redisplay cause a bit of time on Windows. I have read the performance #2982 and manual [here](https://magit.vc/manual/magit/Microsoft-Windows-Performance.html#Microsoft-Windows-Performance). And I don't think [libgit2](https://github.com/magit/libegit2) will resolve performance issue any sooner? Can we make redisplay asynchronously so at least magit doesn't hang while redisplaying the buffer? Thanks!

**Comment by tarsius** [comment]
> Can we make redisplay asynchronously so at least magit doesn't hang while redisplaying the buffer?

No. Currently commands can assume that things have been parsed and are not prepared to deal with unparsed parts of the buffer.

I don't think having another open issue about this is useful and close this in favor of #2982, which outlines the steps I intend to take.
