### ISSUE TITLE
Tags pushed to github don't seem to recognized by github

### ISSUE THREAD

**Issue by Boruch-Baum** [magit/magit#4329]
* Stage and commit something locally
* Use magit to create a 'release tag' for the commit: In magit buffer, press `t r v1.0`
* Verify that the tag was created locally by observing that `v1.0` has been added to the main HEAD commit in a special font.
* Push the commit to github
* Observe that github has registered the commit, but not the tag.

C-u M-x magit-version
Magit 20210124.2150, Git 2.30.0, Emacs 26.1, gnu/linux

**Comment by tarsius** [comment]
I think you are looking for `--follow-tags`.

**Comment by tarsius** [comment]
Certain transient popups hide some of their suffix commands by default. These additional suffixes can be [enabled interactively](https://magit.vc/manual/transient/Enabling-and-Disabling-Suffixes.html). TL;DR Enter the transient as usual and type <kbd>C-x l</kbd>.

<sub>This is a [canned response](https://help.github.com/en/github/writing-on-github/working-with-saved-replies); it may not apply 100% in this case.</sub>

**Comment by Boruch-Baum** [comment]
On 2021-02-22 04:12, Jonas Bernoulli wrote:
>    I think you are looking for --follow-tags.

Could be. I did some searching and see I can do the following:

    git config --global push.followTags true

So, hopefully that will work in the future.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by Boruch-Baum** [comment]
Thanks for the link to the magit manual describing `C-x l`. Although I haven't verified the operation, I accept your suggestion and close the issue.
