### ISSUE TITLE
Make MAGIT-ELLIPSIS a string instead of a character

### ISSUE THREAD

**Issue by j3pic** [magit/magit#4331]
I have my `LANG` environment variable set to `C`. This, unfortunately, excludes Unicode in terminals. This has an unfortunate side effect when using Magit:

![image](https://user-images.githubusercontent.com/26551894/108901147-6ae7d800-7612-11eb-8537-5ea580570c9d.png)

The default Unicode character used for the ellipsis is rendered as its Unicode character number instead. 

I looked for and found the `magit-ellipsis` customization, but unfortunately, it is of type `character`, meaning that you *must* use Unicode with it if you want something that looks like an ellipsis. If it was a string instead, I'd be able to set it to the ASCII character sequence `...`, which approximates the `…` Unicode character.

**Comment by basil-conto** [comment]
The usual guard for this stuff is `char-displayable-p`, FWIW.

**Comment by tarsius** [comment]
That's not actually the option that controlled how that was displayed and the option that does control it did already allow doing what you want to do. But there was room for improvement anyway. See the commit message.

**Comment by basil-conto** [comment]
Thanks, just a couple of typos in the new docstring:
Currenlty -> Currently
tt -> it

**Comment by j3pic** [comment]
@tarsius Great, so that leaves me still having to see `\u2026` in Magit's interface, since I can find no other options that look relevant. The way I found `magit-ellipsis` was by grepping the source code for the `…` character. It shows up in only one place.

**Comment by tarsius** [comment]
Look at this commit, https://github.com/magit/magit/commit/ce34a59746baf0d94f0b7ed157b6e740924ce64a, and you will see other places where that symbol used to appear and still appears, but differently.

Maybe you are using a very old version and should update?

**Comment by tarsius** [comment]
Not that `magit-section.el` is distributed as a separate package.
