### ISSUE TITLE
find-file-visit-truename has no effect on diff displayed during commit

### ISSUE THREAD

**Issue by luismbo** [magit/magit#4338]
When using magit with `find-file-visit-truename` set to `nil`, the diff that is displayed while composing a new commit points to the truename. It would be nice to use the original pathname instead, as magit thankfully does everywhere else AFAICT.

The git-commit-mode buffer also points to the truename which is also slightly inconvenient, but not as much.

I'm running Magit 20210228.1841, Git 2.30.1.windows.1, Emacs 27.1, windows-nt.

Thanks!

**Comment by tarsius** [comment]
What kind of symlink leads to that behavior? There is a number of situations where we cannot avoid disrespecting this setting. From the doc-string of `magit-toplevel`:

> Try to respect the option `find-file-visit-truename`, i.e.  when
> the value of that option is nil, then avoid needlessly returning
> the truename.  When a symlink to a sub-directory of the working
> tree is involved, or when called from within a sub-directory of
> the gitdir or from the toplevel of a gitdir, which itself is not
> located within the working tree, then it is not possible to avoid
> returning the truename.

**Comment by tarsius** [comment]
The diff buffer is created while the `COMMIT_EDITMSG` buffer is current (and thus its `default-directory` is active). This complicates matters and I don't think it is possible to do anything about it. (Or maybe there is, but look at `magit-toplevel` -- I don't want to complicate that any further.)

**Comment by luismbo** [comment]
ACK. The symlink is a SUBST drive `"z:"` pointing to `"c:/Users/foo/src/"`, nothing fancy. I see how the git commit indirection complicates matters. This is a very annoying git behaviour. 😔
