### ISSUE TITLE
Stashing during a merge removes MERGING status

### ISSUE THREAD

**Issue by tsdh** [magit/magit#4345]
`M-x magit-version RET` => `Magit 20210309.1112, Git 2.30.2, Emacs 28.0.50, gnu/linux`

Today at work, I've done some huge merge with many conflicts.  I've resolved them but it would not compile yet because large differences between the branches.  To look up how something has been done before the merge, I just stashed away the merge & conflict resolution changes using `z z` and eventually re-applied the stash with `z p`.  Then I fixed the remaining compile errors and committed.

When committing the merge and my changes, I saw that the commit message was empty instead of the default "Merge remote-tracking branch X" message, and after commit I saw that my commit had just one parent, i.e., it was no merge commit!

As a poor-man's solution I've resetted to `origin/master`, re-initiated the merge, copied over all changed files from a backup I've made from the state above, marked everything resolved, committed and pushed.  (I wonder if there was a better way...)

Anyway, it seems to be that it is a bug that stashing gets me out of MERGING state.  (In the process buffer, I can see that stashing doesn't actually use `git stash` but `git update-ref` and `git reset`.  But I can reproduce that also using `git stash` on the command line.)

I can reproduce that using the magit repository itself using `magit-emacs-Q-command` and this simple recipe:
* Open magit for magit's master branch
* `m m origin/km/reshelve-rewrite RET`
* That generates a merge conflict in `magit-extras.el`.  Just stage it with conflict markers (or resolve and stage it).
* Stash using `z z`
* Pop the stash using `z p`
* Voila, the working tree state is as before stashing but I'm not in the MERGE state anymore and committing will create a single-parent commit.

I think this is no actual bug in Magit but in Git itself (I'll report it there, too).  However, maybe Magit could ask for confirmation before stashing during MERGING state.

**Comment by tsdh** [comment]
Here's the bug report to git itself: https://public-inbox.org/git/875z1xwznd.fsf@gnu.org/T/#u

**Comment by tarsius** [comment]
> To look up how something has been done before the merge, I just ...

Are you aware that you can just press `RET` on a removed line to go to the last commit before that line was removed? In this case that would be `HEAD`.

Alternatively you could use a separate worktree. The worktree commands are available on `%`.

**Comment by tsdh** [comment]
Jonas Bernoulli ***@***.***> writes:

>> To look up how something has been done before the merge, I just ...
>
> Are you aware that you can just press `RET` on a removed line to go to
> the last commit before that line was removed? In this case that would
> be `HEAD`.

Yes, I needed a broader picture, i.e., see how a certain set of
functions in different files called each other.

> Alternatively you could use a separate worktree.  The worktree
> commands are available on `%`.

Yes, I use worktrees a lot, and the next time, I'll just create a
temporary worktree for such purposes, too [1].  It never occurred to me
that stashing could be a shot-yourself-in-the-foot operation.

Bye,
Tassilo

[1] The downside of this is that with our huge codebase at work,
creating a fresh worktree and opening IntelliJ with it will take at
least 5 minutes for indexing before the typical analysis operations are
available.

**Comment by tarsius** [comment]
> Here's the bug report to git itself:

Interesting conversation, which I reread earlier today and now summarize hours later:

- Unconditionally saving and restoring this status would be dangerous.
- So this should be optional and controlled by an argument.
- Otherwise a warning about this state being lost would be nice.
- It is not clear how to save record the state.
- There are other similar states that one might also want to record.
- There's talk about a "super-stash" and I get the impression something will be done eventually but it might have to cook for a few years.

Meanwhile I am adding a warning to magit.

**Comment by tsdh** [comment]
@tarsius Thanks, Jonas, that's the best you can do except for the typo in "Applying the resulting stash won't restored the merge state." where the "restored" should be "restore".
