### ISSUE TITLE
Resolving conflicts à la git mergetool

### ISSUE THREAD

**Issue by luismbo** [magit/magit#4348]
`magit-ediff-resolve`'s A and B buffers only actually show the A and B versions of regions with merge conflicts. The remainder of the file in both buffers actually reflects the bits of version C that were merged automatically from A and B. This can be quite confusing when one needs to look at context in either A or B as buffer A will contain changes from version B and vice-versa.

Here's a first stab at an alternative version that behaves more like `git mergetool`:

```elisp
(defun magit-ediff-resolve/with-context (file)
  "Resolve outstanding conflicts in FILE using Ediff.
FILE has to be relative to the top directory of the repository."
  (interactive
   (let ((current  (magit-current-file))
         (unmerged (magit-unmerged-files)))
     (unless unmerged
       (user-error "There are no unresolved conflicts"))
     (list (magit-completing-read "Resolve file" unmerged nil t nil nil
                                  (car (member current unmerged))))))
  (magit-with-toplevel
    (with-current-buffer (find-file-noselect file)
      (let ((file-buffer (current-buffer))
            (winconf (current-window-configuration)))
        ;; FIXME: other operations can lead to merge conflicts, not just merge and rebase, maybe?
        (let ((head (if (magit-merge-in-progress-p) "MERGE_HEAD" "REBASE_HEAD")))
          (set-buffer
           (ediff-vc-merge-internal "HEAD"
                                    head
                                    (magit-git-string "merge-base" "--octopus" "HEAD" head))))
        (ediff-toggle-show-clashes-only)
        (when ediff-show-ancestor
          (ediff-toggle-show-ancestor))
        (setq-local
         ediff-quit-hook
         (lambda ()
           (let ((bufC ediff-buffer-C))
             (with-current-buffer file-buffer
               (when (yes-or-no-p (format "Conflict resolution finished; save %s? "
                                          buffer-file-name))
                 (erase-buffer)
                 (insert-buffer-substring bufC)
                 (save-buffer))))
           (when (buffer-live-p ediff-buffer-A) (kill-buffer ediff-buffer-A))
           (when (buffer-live-p ediff-buffer-B) (kill-buffer ediff-buffer-B))
           (when (buffer-live-p ediff-buffer-C) (kill-buffer ediff-buffer-C))
           (when (buffer-live-p ediff-ancestor-buffer)
             (kill-buffer ediff-ancestor-buffer))
           (let ((magit-ediff-previous-winconf winconf))
             (run-hooks 'magit-ediff-quit-hook))))))))
```

Perhaps it'd be nicer to construct buffers A and B ourselves, as `smerge-ediff` does, so that we can give them more descriptive names and use `ediff-merge-buffers` / `ediff-merge-buffers-with-ancestor` rather than an internal ediff function.

Does this seem like a sensible command? If so, I'd argue that this should be the default behavior of `magit-ediff-resolve`.

**Comment by tarsius** [comment]
Doesn't this part of `magit-diff-resolve`'s doc-string not address this?

> In the rare event that you want to manually resolve all
> conflicts, including those already resolved by Git, use
> `ediff-merge-revisions-with-ancestor`.

**Comment by luismbo** [comment]
`ediff-merge-revisions-with-ancestor` is painful to use. The user has to manually input the proper revisions (three of them, not always trivial to determine, with defaults that aren't useful for this use case), the merged result is not moved over to the target file  nor does it restore the window configuration (i.e., the final steps done via `ediff-quit-hook` in `magit-diff-resolve`).

**Comment by luismbo** [comment]
I'm happy to polish this first draft a bit more, but at this point I would welcome some guidance on how to reliably identify what's being merged. The `(if (magit-merge-in-progress-p) "MERGE_HEAD" "REBASE_HEAD")` bit seems fragile.

If you agree that constructing buffers A and B ourselves is better, so that we can then use `ediff-merge-buffers-with-ancestor`, I can pursue that too.

**Comment by tarsius** [comment]
> I would welcome some guidance on how to reliably identify what's being merged

I don't know what's best here either and would have to investigate too.

Instead of getting the information from git/magit, you could get it from the file that has conflicts. Conflict markers contain abbreviated hashes. I would expect that that `smerge` already has support for extracting them from there. If not, I think that should be added.

Also, have you considered to instead of a new `(magit)-ediff-...` command (or additionally) you could add some sort of `smerge-find-blob-for-revision-at-point` command? Maybe that even already exists, it sounds so useful or at least obvious. To do the visiting it could us a function from the `magit-find-file` family.

**Comment by luismbo** [comment]
OK, I see 3 options:

1. Extract commit hashes from conflict markers. Depends on `merge.conflictstyle=diff3` if we want to display ancestor buffer.
2. Grab revisions using `git ls-files -u -- <file>` . `git-mergetool.sh` seems to test for other things before going for `ls-files -u`, not sure if they're relevant for this use case. https://github.com/git/git/blob/84d06cdc06389ae7c462434cb7b1db0980f63860/git-mergetool.sh#L533
3. Invoke `git mergetool` with the `mergetool.<something>.cmd` pointing back to Emacs somewhat like `magit-run-git-with-editor`.

At this point, I'm leaning towards option 2.

**Comment by luismbo** [comment]
Current status: got stuck while prototyping option 2 as `ls-files -u` hashes point to blobs rather than commits and I couldn't find anything in the `magit-find-file` family for blobs.

**Comment by kyleam** [comment]
> got stuck while prototyping option 2 as `ls-files -u` hashes point to blobs rather than commits and I couldn't find anything in the `magit-find-file` family for blobs

Given a file, I think you could just use the stage of interest (1-3), e.g., ` (magit-find-file ":1" "foo")`.

**Comment by luismbo** [comment]
@kyleam thanks for the tip. Here's a prototype using that approach, then:

```elisp
(defun magit-ediff-resolve/with-context (file)
  "Resolve outstanding conflicts in FILE using Ediff.
FILE has to be relative to the top directory of the repository."
  (interactive
   (let ((current  (magit-current-file))
         (unmerged (magit-unmerged-files)))
     (unless unmerged
       (user-error "There are no unresolved conflicts"))
     (list (magit-completing-read "Resolve file" unmerged nil t nil nil
                                  (car (member current unmerged))))))
  (magit-with-toplevel
    (with-current-buffer (find-file-noselect file)
      (let ((file-buffer (current-buffer))
            (winconf (current-window-configuration)))
        (set-buffer
         (ediff-merge-buffers-with-ancestor (magit-find-file-noselect ":2" file)
                                            (magit-find-file-noselect ":3" file)
                                            (magit-find-file-noselect ":1" file)))
        (ediff-toggle-show-clashes-only)
        (when ediff-show-ancestor
          (ediff-toggle-show-ancestor))
        (setq-local
         ediff-quit-hook
         (lambda ()
           (let ((bufC ediff-buffer-C))
             (with-current-buffer file-buffer
               (when (yes-or-no-p (format "Conflict resolution finished; save %s? "
                                          buffer-file-name))
                 (erase-buffer)
                 (insert-buffer-substring bufC)
                 (save-buffer))))
           (when (buffer-live-p ediff-buffer-A) (kill-buffer ediff-buffer-A))
           (when (buffer-live-p ediff-buffer-B) (kill-buffer ediff-buffer-B))
           (when (buffer-live-p ediff-buffer-C) (kill-buffer ediff-buffer-C))
           (when (buffer-live-p ediff-ancestor-buffer)
             (kill-buffer ediff-ancestor-buffer))
           (let ((magit-ediff-previous-winconf winconf))
             (run-hooks 'magit-ediff-quit-hook))))))))
```

Problems / TODO:

1. I suspect this approach of skipping ls-files won't work for merge conflicts that involve file renames. I haven't confirmed this.
2. For some reason the C buffer does not reflect the working tree (which might have been edited already). I haven't yet figured what `smerge-ediff` or `magit-ediff-resolve` are doing differently in that regard.
3. Pick better names for the A/B/ancestor buffers.

**Comment by tarsius** [comment]
> Resolving conflicts à la git mergetool

I have implemented that. Please refer to the updated documentation; you'll have to set an option.

> For some reason the C buffer does not reflect the working tree (which might have been edited already).

I have not implemented that because Ediff does not support it.

Ediff takes three versions and constructs a forth version with conflicts from that, or it takes a single input with embedded conflicts and constructs the three versions from that. Note that `git mergetool` also does not support this. Actually as far as I know no tool supports this. It would be nice to implement it eventually, but it looks like a big task, and I don't want to implement it.

**Comment by Patryk27** [comment]
> I have implemented that. Please refer to the updated documentation; you'll have to set an option.

Hi, I've been searching for this option, but I can't find it - would you mind sharing its name?

**Comment by kyleam** [comment]
> Hi, I've been looking for this option, but I can't find it - would you mind sharing its name?

`magit-ediff-dwim-resolve-function` (5a7519fd)

**Comment by Patryk27** [comment]
Ah, that allows you to run `git mergetool --gui`, but doesn't provide anything like OP's `magit-ediff-resolve/with-context`, right?

**Comment by kyleam** [comment]
> Ah, that allows you to run `git mergetool --gui`, but doesn't provide anything like OP's `magit-ediff-resolve/with-context`, right?

That option lists three values:

```elisp
(defcustom magit-ediff-dwim-resolve-function #'magit-ediff-resolve-rest
  "The function `magit-ediff-dwim' uses to resolve conflicts."
  :package-version '(magit . "3.4.0")
  :group 'magit-ediff
  :type '(choice (const magit-ediff-resolve-rest)
                 (const magit-ediff-resolve-all)
                 (const magit-git-mergetool)))
```

`magit-ediff-resolve-all` is intended to be like the `magit-ediff-resolve/with-context` draft above, as far as I understand (though I don't use ediff, so perhaps I'm missing something).
