### ISSUE TITLE
Add option to disable highlighting local/remote branch names in git-commit font-lock

### ISSUE THREAD

**Issue by blahgeek** [magit/magit#4353]
In a large git repo, listing all local and remote branch names can be super slow, which slows down opening git-commit buffer. (In my case, it takes more than 10 seconds). It would be better if there's a option to disable this feature.

My current workaround:

```
(defun my/wrap-git-commit-setup-font-lock (orig-fn &rest args)
  (defun my/return-empty-cons (&rest args)
    '())
  (advice-add 'magit-list-local-branch-names :override #'my/return-empty-cons)
  (advice-add 'magit-list-remote-branch-names :override #'my/return-empty-cons)
  (let ((res (apply orig-fn args)))
    (advice-remove 'magit-list-local-branch-names #'my/return-empty-cons)
    (advice-remove 'magit-list-remote-branch-names #'my/return-empty-cons)
    res))

(advice-add 'git-commit-setup-font-lock :around #'my/wrap-git-commit-setup-font-lock)
```

**Comment by tarsius** [comment]
How many branches are we talking here?

**Comment by blahgeek** [comment]
> How many branches are we talking here?

In my case, there's tens of thousands of branches. I think for companies using mono-repo approach, this number is not surprising (e.g. 1000 developers, more than 10 unmerged branches per person)

**Comment by tarsius** [comment]
We've tried dealing with that before in 254d57788db4d256628b32b381a07a6d5119fb51 but apparently even just listing the branches takes a long time. Could you please some benchmarking to figure out what exactly is taking so long. Most of the action happens in `magit-list-refs`, but also see `magit-list-{local,remote}-branch-names` and `magit-list-refnames`. Is even just `git for-each-ref` slow? Or only if call that with a certain argument? Or is it our post-processing?

**Comment by tarsius** [comment]
Never mind. All that work isn't even necessary.
