### ISSUE TITLE
Deleting a stash fails with an error: wrong-type-argument stringp

### ISSUE THREAD

**Issue by ckonstanski-olo** [magit/magit#4362]
Magit 20210414.1306, Git 2.31.1, Emacs 27.2, gnu/linux

When I try to drop a stash with z-k I get the following error and the stash does not delete. This has been going on for a long time, so I don't thik it's a bug introduced by any recent changes.

```
Debugger entered--Lisp error: (wrong-type-argument stringp ("stash@{0} On master: snowflake egress loop"))
  string-match("^\\([^ ]+\\) \\(.+\\)" ("stash@{0} On master: snowflake egress loop"))
  magit-read-stash("Drop stash")
  byte-code("\301\302!\211\203\21\0\303\304\305\306\305\5%\202\27\0\307\30\310\311!)\262\1C\207" [helm-comp-read-use-marked magit-region-values stash magit-confirm drop-stashes nil "Drop %i stashes" t magit-read-stash "Drop stash"] 7)
  call-interactively(magit-stash-drop nil nil)
  command-execute(magit-stash-drop)
```

**Comment by tarsius** [comment]
I suspect that the completion framework that you are using for some reason causes `completion-read` to return a list instead of a string in this case. Try turning of the completion framework and test whether you can reproduce this using default completion.

**Comment by ckonstanski-olo** [comment]
This is quite possible as I have helm and possibly other things running which tend to vie for completion. Will try with a barebones init file later.
