### ISSUE TITLE
magit-log-margin miscalculates width of date format string

### ISSUE THREAD

**Issue by Boruch-Baum** [magit/magit#4363]
Magit 20210124.2150, Git 2.30.2, Emacs 26.1, gnu/linux

I've customized variable `magit-log-margin`, and the customization does take effect. However, the final character of the date string is truncated. When I add a trailing space to the date format-spec, that space is truncated but I can at least get the entire desired date string. 

This value truncates the final character of `%d`:
```
(setq magit-log-margin '(t "%Y-%m-%d" magit-log-margin-width nil 10))
```
This value displays what I want, but it's still truncating the final (garbage) character:
```
(setq magit-log-margin '(t "%Y-%m-%d " magit-log-margin-width nil 10))
```

**Comment by kyleam** [comment]
I see Jonas added a label, so he may have been able to reproduce this, but fwiw I tried with Emacs 26.1 and 27.2 (GNU/Linux) on Magit's current master (c7364e16) as well a commit closer to the date you report (8e23c49b) and wasn't able to trigger the problem.

![magit-margin](https://user-images.githubusercontent.com/1297788/115167272-eef39480-a084-11eb-95c8-f4f2f45250bc.png)

**Comment by tarsius** [comment]
I didn't actually try to reproduce.

**Comment by tarsius** [comment]
I've tried now and I also could not reproduce.

**Comment by Boruch-Baum** [comment]
On 2021-04-21 15:06, Jonas Bernoulli wrote:
>    I've tried now and I also could not reproduce.

OK, Try this: Maybe, it's reproducible when using my frame/window
configuration of side-by-side windows (ie. C-x 3). If I display the log
in both windows, the left window displays log lines truncated and the
right window complete. Commands shrink/enlarge-window-horizontally
(C-x {, C-x }) don't affect the result.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by tarsius** [comment]
> Try this: 

Didn't make a difference.

> However, the final character of the date string is truncated.

Is it completely invisible or only partially? Try `(setq frame-resize-pixelwise nil)`. Also try updating Emacs.

I don't think this is caused by an off-by-one error in Magit.

**Comment by Boruch-Baum** [comment]
On 2021-04-22 00:25, Jonas Bernoulli wrote:
>    Is it completely invisible or only partially?

Completely. I'm using emacs-nox so there's no way to partially display a
character.

>    Try (setq frame-resize-pixelwise nil).

See above.

>    Also try updating Emacs.

Yeah, been meaning to.

>    I don't think this is caused by an off-by-one error in Magit.

It's not a big deal, so I don't object to closing this.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0
