### ISSUE TITLE
magit-status with prefix arg or inside a non git directory fails with "Corrupt Git configuration"

### ISSUE THREAD

**Issue by plumenator** [magit/magit#4365]
(1) what behavior you expected

When I call `magit-status` with a prefix arg or inside a non git directory, it should list the repos available in `magit-repository-directories`.  My `magit-repository-directories` is set to `(("~" . 2))` via `customize`

(2) what behavior you observed

Whether I give a prefix arg (anywhere on the filesystem) or I call `magit-status` from inside a non git directory (while in the initial scratch buffer, say), I get the same error message: "Corrupt Git configuration"

(3) and how we can reproduce the issue.

- Install latest melpa magit (20210414.1306)
- call `magit-status` with a prefix arg from anywhere
- or call `magit-status` from `*scratch*`

Backtraces:

C-u + `magit-status`

```
Debugger entered--Lisp error: (magit-corrupt-git-config . "~/: error: unknown option `default=_'\nusage: git c...")
  signal(magit-corrupt-git-config "~/: error: unknown option `default=_'\nusage: git c...")
  #f(compiled-function (err) #<bytecode 0x1fea192a22ed>)("error: unknown option `default=_'\nusage: git confi...")
  magit-git-insert("config" "--default=_" "core.bare")
  apply(magit-git-insert ("config" "--default=_" "core.bare"))
  magit-git-string("config" "--default=_" "core.bare")
  magit--assert-usable-git()
  byte-code("\302\211BC\30\11\204\17\0\303 ?\205\31\0\304 \210\305\306\11!\307Y!\10)D\207" [magit--refresh-cache current-prefix-arg 0 magit-toplevel magit--assert-usable-git magit-read-repository prefix-numeric-value 16] 3)
  call-interactively(magit-status nil nil)
  command-execute(magit-status)
```

`magit-status` from *scratch*
```
Debugger entered--Lisp error: (magit-corrupt-git-config . "~/: error: unknown option `default=_'\nusage: git c...")
  signal(magit-corrupt-git-config "~/: error: unknown option `default=_'\nusage: git c...")
  #f(compiled-function (err) #<bytecode 0x1fea192a22ed>)("error: unknown option `default=_'\nusage: git confi...")
  magit-git-insert("config" "--default=_" "core.bare")
  apply(magit-git-insert ("config" "--default=_" "core.bare"))
  magit-git-string("config" "--default=_" "core.bare")
  magit--assert-usable-git()
  byte-code("\302\211BC\30\11\204\17\0\303 ?\205\31\0\304 \210\305\306\11!\307Y!\10)D\207" [magit--refresh-cache current-prefix-arg 0 magit-toplevel magit--assert-usable-git magit-read-repository prefix-numeric-value 16] 3)
  call-interactively(magit-status nil nil)
  command-execute(magit-status)

```
The output of:

    M-x magit-version RET

```
Magit 20210414.1306, Git 2.17.2 (Apple Git-113), Emacs 27.1.90, darwin
```

**Comment by kyleam** [comment]
[ quick lunch break response ]

It looks git-config's `--default` was added in 2.18.  (Sorry, I should have checked.)  I'll come up with a backward-compatible way tonight.

**Comment by plumenator** [comment]
Quick follow up:
I just upgraded to Mac OS X Big Sur and forgot to install developer tools, which also installs git. When I tried to use `magit-status` I got the same error message again. I suppose that's because it couldn't find git, but I think the error message should have said that.
