### ISSUE TITLE
Add an option to make the rev buffer stop following the blame revision under cursor

### ISSUE THREAD

**Issue by Atemu** [magit/magit#4367]
When trying to resolve a merge conflict today, I needed the context from other commits, so I moved my cursor over a line and opened its revision with `RET`.

When I moved my cursor down to another line however, the rev buffer updated its content to the rev of that line. 

When I then moved by cursor back up again, the rev buffer updated to the revision I actually wanted it to show again but, to my dismay, it lost the position in the diff I had previously selected and needed for context. (the rev buffer jumps to the correct file in the diff but not the correct position inside that file).

This feature also makes moving the cursor through git blame unusable when a rev buffer is open because it needs to update the rev buffer with a huge diff every few lines.

I need a way to turn that off; even if it worked flawlessly without a hitch. Solving merge conflicts is already hard enough.    
I looked through the magit-rev and magit-blame variables but could not find anything relevant.

**Comment by tarsius** [comment]
> When I moved my cursor down to another line however, the rev buffer updated its content to the rev of that line.

It shouldn't do that. Use `C-h c ....` to find you what command is invoked when you press the key that you use to move to another line.

Please also try to reproduce this issue without your configuration. For instructions see `magit-emacs-Q-command` at https://magit.vc/manual/magit/Debugging-Tools.html.

**Comment by Atemu** [comment]
Hi, sorry for not getting back to you sooner.

The keys are bound to the regular next/prev line functions.

The same behaviour can be observed in emacs run via `magit-emacs-Q-command`.

**Comment by tarsius** [comment]
`C-n` `C-p` don't do that.

`n` and `p` do and here you can disable it with `(remove-hook 'magit-section-movement-hook #'magit-log-maybe-update-revision-buffer)`.

**Comment by Atemu** [comment]
This also happens with `C-n`, `C-p` and removing the hook doesn't seem to help either. Can you reproduce this behaviour?

**Comment by tarsius** [comment]
> The keys are bound to the regular next/prev line functions.

If you don't explicitly state which keys "the keys" refer to and I also leave me guessing what you consider to be "the regular next/prev line functions", then that means we are going to have more of a back an forth until we know what's going on.

> This also happens with `C-n`, `C-p`

I doubt that. For me those commands are bound to `magit-next-line` and `magit-previous-line`, which are essentially the same as `next-line` and `previous-line`.

I recommend not doing anything to disable the feature that automatically updates the revision buffer when moving around in a log using `magit-section-forward/backward` (on `n/p`) and to instead use these commands in those cases when you don't want the automatic updating to happen. But maybe you really want to always disable it.

> and removing the hook doesn't seem to help either.

At what time did you do that? You have to do it after magit has added the hook function to the hook variable, i.e. after loading `magit-log`. There are actually several such hooks so you might want to do all of this:

```elisp
(with-eval-after-load 'magit-log
  (add-hook 'magit-section-movement-hook #'magit-log-maybe-show-more-commits)
  (add-hook 'magit-section-movement-hook #'magit-log-maybe-update-revision-buffer)
  (add-hook 'magit-section-movement-hook #'magit-log-maybe-update-blob-buffer))
```

`magit-section-movement-hook` is run by `magit-section-goto`, which is run by section movement commands such as `magit-section-forward` (on `n`) but not by e.g. `magit-nest-line` (on `C-n`).

**Comment by tarsius** [comment]
To really be sure that nothing is on `magit-section-movement-hook` do `(setq magit-section-movement-hook nil)` right before trying to reproduce the issue.

**Comment by lua-vr** [comment]
Same thing was happening for me. Found out the relevant option is `magit-blame-goto-chunk-hook`:

```elisp
(remove-hook 'magit-blame-goto-chunk-hook 'magit-blame-maybe-update-revision-buffer)
```

fixes it.

Also, `magit-toggle-buffer-lock` is very useful!
