### ISSUE TITLE
Make all magit-diff-visit-*-file functions obey the value of 'magit-display-buffer-function'

### ISSUE THREAD

**Issue by rswgnu** [magit/magit#4368]
Hi Tarsius:

One should be able to control where files referenced in diffs are displayed when RET is pressed, based on a variable setting without having to give a prefix argument.  Since you already have this variable, magit-display-buffer-function, just use it in these functions.  That would be great.

**Comment by tarsius** [comment]
Would this work for you too?:

``` emacs-lisp
(define-key magit-diff-section-base-map [remap magit-visit-thing]
  'magit-diff-visit-file-other-window
  ;; or 'magit-diff-visit-file-other-frame
  ;; or your own variant (takes ~ two lines to define)
  )
```

**Comment by rswgnu** [comment]
I think that will do fine.  Thanks very much.  -- Bob
