### ISSUE TITLE
magit-dired-log void variable error

### ISSUE THREAD

**Issue by Boruch-Baum** [magit/magit#4369]
Magit 20210421.1731, Git 2.30.2, Emacs 28.0.50, gnu/linux

Running function magit-dired-log succeeded in opening a log buffer. At that point, I pressed '?' expecting some kind of help dialog, but instead got the back-trace included below.

```
(void-variable --cl-s--)
  apply(debug (error (void-variable --cl-s--)))
  transient--exit-and-debug(error (void-variable --cl-s--))
  #f(compiled-function (def) #<bytecode 0xa375233156fed95>)(#<transient-columns transient-columns-1585a19e2de0>)
  mapcan(#f(compiled-function (def) #<bytecode 0xa375233156fed95>) (#<transient-columns transient-columns-1585a19e2de0> #<transient-columns transient-columns-1585a1a14ece> #<transient-column transient-column-1585a1a20832> #<transient-columns transient-columns-1585a19febca>))
  cl-mapcan(#f(compiled-function (def) #<bytecode 0xa375233156fed95>) (#<transient-columns transient-columns-1585a19e2de0> #<transient-columns transient-columns-1585a1a14ece> #<transient-column transient-column-1585a1a20832> #<transient-columns transient-columns-1585a19febca>))
  transient--flatten-suffixes((#<transient-columns transient-columns-1585a19e2de0> #<transient-columns transient-columns-1585a1a14ece> #<transient-column transient-column-1585a1a20832> #<transient-columns transient-columns-1585a19febca>))
  transient--init-objects(magit-dispatch nil nil)
  transient-setup(magit-dispatch)
  magit-dispatch()
  funcall-interactively(magit-dispatch)
  call-interactively(magit-dispatch nil nil)
  command-execute(magit-dispatch)
```

**Comment by tarsius** [comment]
Neither `magit` nor `transient` directly use a variable named `--cl-s--`. I suspect there briefly was a bug in Emacs itself or that your Emacs installation is somehow corrupted. Try updating Emacs and that itself does not help, then also reinstall `transient` and `magit`.

**Comment by Boruch-Baum** [comment]
On 2021-04-29 00:15, Jonas Bernoulli wrote:
>    Neither magit nor transient directly use a variable named --cl-s--. I
>    suspect there briefly was a bug in Emacs itself or that your Emacs
>    installation is somehow corrupted. Try updating Emacs and that itself
>    does not help, then also reinstall transient and magit.

I've tried the easy part. Recompiling transient yields a byte compiler
warning:

In transient--flatten-suffixes:
transient.el:1703:21: Warning: reference to free variable ‘--cl-s--’

So, I'll try updating (or reverting) emacs...

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0
