### ISSUE TITLE
Add support for 'Fixes' git pseudo header

### ISSUE THREAD

**Issue by Flowdalic** [magit/magit#4375]
It would be great to have support for the 'Fixes' pseudo header, which, when invoked, allows to select a commit and inserts the header's value, a git revision, in kernel style. That is

```
Fixes:  %h ("%s")
```

**Comment by tarsius** [comment]
Recently someone else suggested this but I cannot find the issue.

In short we agree that this would be nice for those who use this style but this could and should be implemented outside of Magit.

**Comment by Flowdalic** [comment]
> In short we agree that this would be nice for those who use this style but this could and should be implemented outside of Magit.

How can I extend magit by custom git pseudo header? Furthermore, this header should pop-up a selection window of commits, akin to what happens with pseudo headers that have person as value.

**Comment by tarsius** [comment]
Ah sorry, I did not read you request properly I though this was about git-commit/magit colorizing this sort of thing.

You can use `C-u C-c C-w` to insert a commit not from the stack but read from the minibuffer. Only refs are offered as completion candidates but you could also type or paste a hash.

**Comment by kyleam** [comment]
> Furthermore, this header should pop-up a selection window of commits, akin to what happens with pseudo headers that have person as value.

In the process of fixing a commit, I think I almost always have visited a revision buffer for the commit in question so it seems natural to me to "push to stack/kill-ring/where ever" approach and then, once in the commit message buffer, grabbing it from there.  On the other hand, popping up a large number of commits and searching the commit once in the commit message buffer seems like it'd be inconvenient to find the commit unless it happened to be pretty recent.

Anyway, I think you can get pretty close to the behavior you're after by defining a custom function that uses `magit-log-select`:

```elisp
(defun my/magit-select-and-insert-fixes-header ()
  (interactive)
  (magit-log-select
    (lambda (commit)
      (let ((magit-pop-revision-stack-format '("Fixes: %h (\"%s\")")))
        (magit-pop-revision-stack commit (magit-toplevel))))
    "Fixes commit:"))
```
