### ISSUE TITLE
Default values for "Detect renames" and "Detect copies"

### ISSUE THREAD

**Issue by sergefdrv** [magit/magit#4379]
It would be quite convenient to allow enabling just `-M` and `-C` flags to `git diff`, assuming the default values. Currently, the respective transient arguments seem to require an explicit positive number.

**Comment by tarsius** [comment]
Done. You'll also have to update transient to include https://github.com/magit/transient/commit/626d105ecfb44ab9e1a4bf1fccb9340d6488b631.
