### ISSUE TITLE
Log limiting to a deleted file not showing correctly

### ISSUE THREAD

**Issue by prati0100** [magit/magit#4381]
Hello,

I am using Magit on top of the linux-next repo (found [here](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/)) on tag `next-20210511`. Now I make some commits, one of which deletes a file (`drivers/media/platform/ti-vpe/cal.c` to be specific).

Now I want to see the log of this file so I press `l` to open the log window, `--` to limit to the file, and then press `o` and specify `master`. The log shows a bunch of merge commits, and no actual commits touching the file. Example:

```
8fe889082ca2 upstream/akpm-base Merge remote-tracking branch 'tpmdd-jejb/tpmdd-for-next'
379193f20279 Merge remote-tracking branch 'rust/rust-next'
2bd8bac98fc2 Merge remote-tracking branch 'iomem-mmap-vs-gup/topic/iomem-mmap-vs-gup'
6ede3c902673 Merge remote-tracking branch 'hyperv/hyperv-next'
8d48a41dba0c Merge remote-tracking branch 'nvmem/for-next'
cd15c5fd6392 Merge remote-tracking branch 'slimbus/for-next'
34608be209b2 Merge remote-tracking branch 'gnss/gnss-next'
4b9140911be8 Merge remote-tracking branch 'kspp/for-next/kspp'
```

and so on till it reaches the "show more history" button.

When I run `git log --oneline master -- drivers/media/platform/ti-vpe/cal.c` on the same repo, I get the correct log:

```
38e89e790fe2 media: ti-vpe: cal: Implement media controller centric API
b01edcbd409c media: v4l2-async: Improve v4l2_async_notifier_add_*_subdev() API
5a402af5e19f media: ti-vpe: cal: fix write to unallocated memory
2ad100f359c2 media: ti-vpe: cal: Simplify the context API
67252cf0ea44 media: ti-vpe: cal: Store buffer DMA address in dma_addr_t
2e2279b53a9f media: ti-vpe: cal: Set cal_dmaqueue.pending to NULL when no pending buffer
ca4fec54f6ba media: ti-vpe: cal: Group all DMA queue fields in struct cal_dmaqueue
```

You can get the Git repo with the commits from here: https://github.com/prati0100/linux-next using tag `for_magit`.

Magit version: `Magit 577f16da, Git 2.31.1, Emacs 27.2, gnu/linux`

**Comment by kyleam** [comment]
Thanks for reporting this.  I've scratched my head over this a few times but have never stopped what I was in the middle of doing to record the details needed to trigger it.

The issue is that `--full-history` is added for a single removed file.  That was motivated by the case in gh-3012:

```
$ git log --oneline -- contrib/lisp/org-remember.el
$ git log --full-history --oneline -- contrib/lisp/org-remember.el | head -2
48bc6ad52 Add AUTHORS, update contrib/README, clean-up and fix comment sections in other files
0c9b46854 Merge branch 'maint'
```

I believe a key piece of the first invocation (default mode) being simplified to empty output is that the file was renamed (and `--follow` isn't specified).

The most straightforward fix (at least in the above case and your example) would be to use `--simplify-merges` instead.

```
$ git log --simplify-merges --oneline -- contrib/lisp/org-remember.el
48bc6ad52 Add AUTHORS, update contrib/README, clean-up and fix comment sections in other files
6c788fe73 Move org-remember.el to contrib/lisp/
```

However, I'd actually vote for going back to matching the command-line behavior and not automatically adding either of these arguments (which are of course still available from the magit-log transient) for two reasons:

  * `--full-history/simplify-merges` aren't needed for many cases of a removed file

  * those options can be relatively expensive

    ```
    $ time git log --oneline --graph -- drivers/media/platform/ti-vpe/cal.c >/dev/null
    git log --oneline --graph -- drivers/media/platform/ti-vpe/cal.c > /dev/null  0.79s user 0.07s system 99% cpu 0.860 total
    
    $ time git log --simplify-merges --oneline --graph -- drivers/media/platform/ti-vpe/cal.c >/dev/null
    git log --simplify-merges --oneline --graph --  > /dev/null  13.85s user 0.27s system 99% cpu 14.121 total
    
    $ time git log --full-history --oneline --graph -- drivers/media/platform/ti-vpe/cal.c >/dev/null
    git log --full-history --oneline --graph --  > /dev/null  15.08s user 0.25s system 99% cpu 15.324 total
    ```

**Comment by prati0100** [comment]
> The most straightforward fix (at least in the above case and your example) would be to use `--simplify-merges` instead.

Yes, using `--simplify-merges` fixes the issue for me. Thanks.

> However, I'd actually vote for going back to matching the command-line behavior and not automatically adding either of these arguments (which are of course still available from the magit-log transient) for two reasons:
> 
>     * `--full-history/simplify-merges` aren't needed for many cases of a removed file
> 
>     * those options can be relatively expensive
>       ```
>       $ time git log --oneline --graph -- drivers/media/platform/ti-vpe/cal.c >/dev/null
>       git log --oneline --graph -- drivers/media/platform/ti-vpe/cal.c > /dev/null  0.79s user 0.07s system 99% cpu 0.860 total
>       
>       $ time git log --simplify-merges --oneline --graph -- drivers/media/platform/ti-vpe/cal.c >/dev/null
>       git log --simplify-merges --oneline --graph --  > /dev/null  13.85s user 0.27s system 99% cpu 14.121 total
>       
>       $ time git log --full-history --oneline --graph -- drivers/media/platform/ti-vpe/cal.c >/dev/null
>       git log --full-history --oneline --graph --  > /dev/null  15.08s user 0.25s system 99% cpu 15.324 total
>       ```

Using Magit on large repos like Linux is a bit slow. Any performance improvements are very welcome :-)
