### ISSUE TITLE
"merge-into" is confusingly named

### ISSUE THREAD

**Issue by real-or-random** [magit/magit#4386]
Today I tried `magit-merge-into` without reading the docs first. Judging from the name and the description in the buffer, I expected it to be a "reverse" merge, so simply a normal merge with branches reversed. But it turns out to be a reverse `magit-merge-absorb`, where absorb has rather drastic functionality:
 - it pushes to a remote
 - it deletes a local branch
 - it potentially even removes a remote branch

These outcomes were very unexpected to me. I think these are okay-ish for `absorb` because "absorb" is not a plain git term. So it signals to me that there's some magic (or magit) involved. But this is different for "into". `merge into` is not a plain git command either but "into" is a common term when talking about merging, e.g., `man git merge` describes `merge` as "Incorporates changes from the named commits (since the time their histories diverged from the current branch) *into* the current branch. "

**Comment by tarsius** [comment]
I do not intend to do anything about this.

> Today I tried `magit-merge-into` without reading the docs first.

Are you aware that you can show the documentation for the suffix bound to `<key>` by pressing `C-x h <key>`?

**Comment by real-or-random** [comment]
> I do not intend to do anything about this.

That's a valid solution, just not the one I hoped for. A possible solution I can imagine is to  rename this. That would help people with a similar intuition as mine.

> 
> > Today I tried `magit-merge-into` without reading the docs first.
> 
> Are you aware that you can show the documentation for the suffix bound to `<key>` by pressing `C-x h <key>`?

Yes, thanks for the hint!

**Comment by tarsius** [comment]
I'll leave this open for others to comment for a while.

**Comment by tarsius** [comment]
So I had this confusing post-it with just the word "dissolve" on it sitting on my desk for a while now... :grinning:

That might work well here, what do others think? If we use that description should we also change the command name and/or key binding?

**Comment by alphapapa** [comment]
I don't know that my opinion matters, but I'm generally in favor of these extra commands unique to Magit using unique names that bear no resemblance to any actual git command.  I think it's the only way that users have a chance of remembering what they do.  :)  So "dissolve" sounds good to me.

**Comment by real-or-random** [comment]
Dissolve is indeed a neat word for this action. Another approach would be "absorb into" to clarify it's the reverse of an absorb. I think both are good.

**Comment by zzeitt** [comment]
The behavior of `magit-merge-into` is quite confusing to me, too. I never realised the ["removes former (branch)"](https://magit.vc/manual/magit/Merging.html#index-m-i#:~:text=merges%20the%20current%20branch%20into%20another%20local%20branch%20and%20then%20removes%20the%20former) action by just looking at this command's name at the first time.

One advice from me would be, adding a warning in command's minibuffer:

> |  Your buffer                        |
> |-------------------------------------|
> |`Merge ‘release’ into (default master, [Warning: This will remove the source branch!!!]):`  |

**Comment by tarsius** [comment]
I've now changed the name of the command, see 280fa3ddab5da375ed977660674cfa1db680c901.
