### ISSUE TITLE
magit-section-set-window-start can affect an urelated window

### ISSUE THREAD

**Issue by jakanakaevangeli** [magit/magit#4389]
emacs -Q:

1. `(add-hook 'after-save-hook 'magit-after-save-refresh-status)`
2. Open a ~2000 line file
3. At ~70% of the file, add a comment block or something
4. M-x magit-status
5. Open the diff hunk of the added comment block and place point on it
6. Close magit-status window
7. Insert a new line in the middle of the added comment block
8. Save the buffer

The current window will be scrolled instead of magit-status, because it isn't
shown in any window.

**Comment by tarsius** [comment]
This indeed was a longstanding bug. However, two days a go I finally fixed it. See 482c25a3204468a4f6c2fe12ff061666b61f5f4d and update magit.

**Comment by jakanakaevangeli** [comment]
Whoops, sorry, thanks.
