### ISSUE TITLE
Add support for creating bundles

### ISSUE THREAD

**Issue by andli197** [magit/magit#4392]
It would be useful to add support for git bundles in magit. From what I can see there is no implementation supporting this and I always find myself needing to use a shell for this task instead.

**Comment by tarsius** [comment]
This would be a good project for someone who wants to learn how to use `transient`.

**Comment by kwas** [comment]
I'd like to work on this issue

**Comment by tarsius** [comment]
Great!

Let me know if you have questions. My first tips would be to use a separate file and learn from other, fairly self-contained menus that are part of Magit.
