### ISSUE TITLE
git-credential-manager-core helper doesn't ask for access token

### ISSUE THREAD

**Issue by CIAvash** [magit/magit#4393]
I added the `magit-process-git-credential-manager-core` to the `magit-process-prompt-functions` hook. And then `push`ed inside `magit-status`, I was asked to select an authentication method, with prompt `option`. I entered `2` for Personal access token:

```
Select an authentication method for 'https://github.com/':
  1. Web browser (default)
  2. Personal access token
option (enter for default): 2
```
I expected `magit` to ask for the `token`:

```
Enter GitHub personal access token for 'https://github.com/'...
Token:
```

But after I entered `2` as the option, nothing happened. No errors, no operations, no messages or output.

For reproducing, setup the `git-credential-manager-core`, then push inside a project.

Magit version:
Magit 20210525.844, Git 2.31.1, Emacs 27.2, gnu/linux

Unrelated to this issue, `magit-emacs-Q-command` lacked the `-L magit-section` package.

**Comment by tarsius** [comment]
This was added in response to #4318 with 884b4f2e48fc5ec46a9a614f6baa1d4d200acce3. Apparently it worked back then. @ztlevi does it still work for you?

**Comment by ztlevi** [comment]
It's working for me. But you'll need to open the `magit-process-buffer`. After `M-x magit-status`, you need to use `$` key to open `magit-process-buffer`. Since the echo area can only output one line, you cannot see the full instruction when starting git-credential-manager authentication. 

You can open that buffer and see if it's there. The token input prompt should be popped already.

BTW, you can verify your setup working in terminal. My setup is [here](https://github.com/ztlevi/Dotfiles/blob/master/shell/git/config#L58-L59)

**Comment by CIAvash** [comment]
> It's working for me. But you'll need to open the `magit-process-buffer`. After `M-x magit-status`, you need to use `$` key to open `magit-process-buffer`. Since the echo area can only output one line, you cannot see the full instruction when starting git-credential-manager authentication.
> 
> You can open that buffer and see if it's there. The token input prompt should be popped already.
>

Magit opens the process buffer. After I enter the number, nothing happens.
 
> BTW, you can verify your setup working in terminal. My setup is [here](https://github.com/ztlevi/dotty/blob/master/shell/git/config#L58-L59)

I know, I just wanted to report the issue.

If it can't be reproduced, then nothing can be done about it. If I find some time I may look into what's happening.

**Comment by CIAvash** [comment]
I modified the `magit-process-git-credential-manager-core` and added a newline(`"\n"`) to the the return value of `read-char-choice` inside the format function and it worked:
```elisp
(format "%c\n" (read-char-choice "Option: " '(?\r ?\j ?1 ?2)))
```

The "Token: " prompt made the height of minibuffer larger.

If I cancel the prompt(with `C-g`), the git process is not killed.

**Comment by ztlevi** [comment]
Glad it worked. Maybe you can raise a PR.
