### ISSUE TITLE
Add support for git-secret

### ISSUE THREAD

**Issue by baron42bba** [magit/magit#4398]
Thanks for all the great work you are doing.

Lately i dived into
https://git-secret.io
but my beloved magit has no support for it.

git secret reveal
git secret add
git secret hide

would already be enough in the beginning.

**Comment by baron42bba** [comment]
I would like to see if I can create a seperate package for Magit.
Where should I start?
Is there something like a reference package I could read to figure out how to do it the right way?

**Comment by alphapapa** [comment]
@baron42bba This may not be the best answer, but you could start by looking at how Magit itself supports various git commands.  Eventually you could end up with a package defining some `magit-git-secret-` commands, and then you could add them to the Transient dispatcher.

**Comment by tarsius** [comment]
Look at the simpler examples in magit, i.e. `magit-submodule` and not `magit-diff`. Also maybe look at (still maintained) extensions to magit. The official ones that you can find inside the magit account maybe. They are more complex than `magit-submodule` though.
