### ISSUE TITLE
Auto-show magit-process-buffer on fetch

### ISSUE THREAD

**Issue by MicahElliott** [magit/magit#4401]
I find that I commonly miss migrations (special date-stamped files) that show up in my fetches. I rarely need to watch `magit-process-buffer` except when pulling, since sometimes migration files are part of the pull. When they are present, I know I need to manually run a migration. I have to assume this is the case for lots of folks. I'm training myself to press `$` every time I fetch, but this feels like something I should either automate (though not sure the magit trick yet), or ask magit to have a setting to do this for me.

An alternative, for when "significant git output" occurs, would be to have magit-status show the usual informational line at the top (probably not in red) that "something happened" and to press `$` to see more details. 

Taking it even further, and probably overkill, is to allow for a search pattern to auto-open or auto-info-message when git's output matches. In this case, it'd be like `'.*migration.*\.sql'` in git's output.

**Comment by tarsius** [comment]
`magit-credential-hook` is run right before fetching; but also before pushing and cloning. If you don't mind the latter, then this does the trick:

```elisp
(add-hook 'magit-credential-hook 'magit-process-buffer)
```

**Comment by tarsius** [comment]
A related tip: https://github.com/magit/magit/wiki/Tips-and-Tricks#automatically-displaying-the-process-buffer.
