### ISSUE TITLE
"Limit to files" does not work if the file name has a comma in it

### ISSUE THREAD

**Issue by prati0100** [magit/magit#4402]
Hi,

If a file name has a comma in it, "limit to files" does not work on it. When I press `l` to bring up the log menu and then hit `--` to bring the limit to files prompt, and enter the file name, say `foo,bar.c` it gets converted into two entries: `foo` and `bar.c`. The repo I encountered this in is the Linux repo: https://github.com/torvalds/linux.git file `Documentation/devicetree/bindings/mtd/jedec,spi-nor.yaml` (lots of other files with comma in name there as well).

If I go to the file's buffer and run `magit-log` there, it auto fills the "limit to files" with the file name. It works correctly in this case. So this looks more like an input parsing problem and not a problem with the core functionality. I tried entering `jedec\,spi-nor.yaml` but that didn't help. It split the input into `jedec\\` and `spi-nor.yaml`.

M-x magit-version: Magit b68a760c, Git 2.32.0, Emacs 27.2, gnu/linux

**Comment by tarsius** [comment]
At this prompt you can select multiple files -- selected by commas. You can pick another character by setting `crm-separator`, but that will affect all calls to `completing-read-multiple`.

**Comment by prati0100** [comment]
@tarsius Right. I understand that comma is a file separator. Is there any way to escape the separator so that it is parsed as a part of the file name? This problem would apply to every separator I choose. Having an escape character would be the best solution.

**Comment by tarsius** [comment]
You could experiment with something like `"[^\\],"` as `crm-separator`. Look at how that regexp is used and how that might allow you to implement/fake quoting.
