### ISSUE TITLE
Quitting magit window returns to original window rather than visible one

### ISSUE THREAD

**Issue by countvajhula** [magit/magit#4412]
**Expected behavior:**
When you quit the magit window by hitting `q`, it should return focus to the other currently active, visible window. This is the usual behavior when hitting `q` on popup buffers such as help buffers.

**Observed behavior:**
It restores the original window at the time magit was entered.

**How to reproduce the issue:**

1. Open a git-versioned file.
2. Enter magit -- it opens a magit window alongside the original buffer
3. Return to the original window and switch to any other buffer (e.g. another file in the same repo)
4. Switch back to the magit window and hit `q`

The active window on the left disappears and is replaced with the original buffer that was there in step 1.

For comparison, you could go through these steps to see the behavior with popup windows:
1. Type "describe-symbol" in the emacs scratch buffer
2. Execute `describe-function` while point is within the typed text -- it pulls up a help window alongside
3. Return to the original window and switch to any other buffer
4. Switch back to the help window and hit `q`

Focus is returned to the active window on the left.

**Usage example:**
Sometimes when I'm in the middle of preparing a commit or just reviewing changes, I may have a magit window alongside that I periodically refresh and review while making changes in various files. At the end when I'm done, I could be in the middle of working on some file in one pane, and notice that the magit window is still open. At this point when I close the magit window, the window configuration is altered (it seems) to some arbitrary configuration (which, upon looking more closely, I see that it's the original one at magit entry time), losing the current context.

**`magit-version`**: `Magit v2.90.1-1117-g9e9f7cb3, Git 2.12.2, Emacs 27.1, darwin`

Thanks for making a truly excellent tool in magit :)

**Comment by tarsius** [comment]
This is controlled by the option `magit-bury-buffer-function`. Personally I have set this to `magit-mode-quit-window` a long time ago. Maybe that should be the default.

**Comment by countvajhula** [comment]
Nice, that did it! And I now see that it is documented in the user manual 🤦 . I would be in favor of making this option the default behavior. Other than that, feel free to close this issue.

**Comment by hariseldon78** [comment]
I think it should be the default too, because it's very unexpected that when i close the last magit window, which could have been there since many hours/days, it closes/move/replace buffer in a lot of other windows, usually all, _making me lose all my focus_. It really have the appearence of a bug, I don't know any other package that interferes with _not-his-own_ windows.

**Comment by countvajhula** [comment]
Is this behavior known to be preferred by some users? If not, I would venture that it could just be removed entirely, in favor of the `quit-window` behavior as default, so that there's less code to maintain 🏃

**Comment by tarsius** [comment]
I've changed the default. Maybe some users who prefer the old default will home here and explain why.

**Comment by countvajhula** [comment]
Good idea.

**Comment by manuel-uberti** [comment]
I am one of the users who prefer the old default. I have `magit-display-buffer-function` set `magit-display-buffer-fullframe-status-v1`, so when I enter `magit-status` from a multiple windows situation (usually no more than three) I like `q` to restore the previous window configuration I was in.

**Comment by manuel-uberti** [comment]
> Is this behavior known to be preferred by some users? If not, I would venture that it could just be removed entirely, in favor of the `quit-window` behavior as default, so that there's less code to maintain runner

Please don't. I can set `magit-bury-buffer-function` to the old value, and I can understand the new default, but keep the original logic around at least.

**Comment by tarsius** [comment]
@manuel-uberti No worries!
