### ISSUE TITLE
Use image from bbdb if no gravatar

### ISSUE THREAD

**Issue by unhammer** [magit/magit#4414]
BBDB has some support for storing (base64-encoded) images in the `image-uri` field. It'd be nice if we could fallback to these when gravatar shows up empty, it'd be something like 

    (create-image (base64-decode-string
                (bbdb-record-xfield (car (bbdb-search (bbdb-records)
                                                        :mail author-email))
                                    'image-uri))
                nil
                'data)

plus error handling

**Comment by tarsius** [comment]
IMO it would be better if there were one package that supported multiple image sources. Maybe `gravatar` could be that package, even though its name then wouldn't be quite correct anymore. Otherwise over time support for this might end up being implemented in every package that uses `gravatar`.

> plus error handling

And most of these downstream packages would skip details such as this. Better do it once, properly.

**Comment by unhammer** [comment]
https://github.com/unhammer/gnavatar#use-as-library-to-insert-avatars reuses the callback api of gravatar.el, seems to work as a drop-in replacement (gravatar-retrieve→gnavatar-retrieve).

Though I worry I won't be quite up to the task of Doing It Properly (does it need tests? CI? multiple dependency inheritance? I wouldn't know), so if anyone wants to take over maintainership I'd be happy to step into the shadows.

**Comment by tarsius** [comment]
Sorry for not commenting earlier.

> seems to work as a drop-in replacement (gravatar-retrieve→gnavatar-retrieve).

So one could just `(advice-add 'gravatar-retrieve :override #'gnavatar-retrieve)`, right? If so then you should mention that in the documentation.

> Though I worry I won't be quite up to the task of Doing It Properly (does it need tests? CI? multiple dependency inheritance? I wouldn't know), so if anyone wants to take over maintainership I'd be happy to step into the shadows.

Good luck finding someone :grinning: 
Anyway, I think it doesn't need any of that but you would have to add it to Melpa and do some maintenance.

(By the way, the image source I would be most interested in is Github. Just in case you looking for something else to implement. :grin: )

**Comment by unhammer** [comment]
> So one could just (advice-add 'gravatar-retrieve :override #'gnavatar-retrieve), right? If so then you should mention that in the documentation.

Ah, I had only documented use as library. A user should `(advice-add 'gravatar-retrieve :around #'gnavatar-override)` (slightly different to avoid loops for those who want to use both gravatar and bbdb as providers), now documented.

> (By the way, the image source I would be most interested in is Github. Just in case you looking for something else to implement.  )

Good idea! But might be difficult,
https://docs.github.com/en/github/searching-for-information-on-github/searching-on-github/searching-users#search-by-account-name-full-name-or-public-email
says "For privacy reasons, you cannot search by email domain name", though you can search by partial email. Might lead to lots of mismatches. It's easy enough to get the image if you know the github *username* though – would it be helpful to have a function from github username to github image?

**Comment by tarsius** [comment]
> would it be helpful to have a function from github username to github image?

Potentially :grin:

**Comment by unhammer** [comment]
added in https://github.com/unhammer/gnavatar/commit/9fc27e2e7048ff67e01c94bf1404fae0eb629eac 
(I also put in a helper that lets you quickly copy github avatars to bbdb)

**Comment by tarsius** [comment]
Ah thanks! Gonna have to give that a spin.
