### ISSUE TITLE
-F "--grep" is not playing nice with escaped brackets

### ISSUE THREAD

**Issue by hisnawi** [magit/magit#4417]
In our project commit headers we usually use:
[ProjName] to start the commit message.
It is always handy fetching for all commits related to a specific project with
git log --grep="\\[ProjName"

unfortunately, in magit when trying:
l -F "\\[ProjName" L
I am unable to fetch these commits.
I think Magit has issues processing \\[ in grep.

**Comment by kyleam** [comment]
Did you try escaping the `[`?  Git is (by default) expecting a closing `]` for the pattern:

```console
$ git log --oneline --format=%s
[bar] def
[foo] abc

$ git log --oneline --format=%s --grep='[foo'
fatal: command line, '[foo': Unmatched [, [^, [:, [., or [=

$ git log --oneline --format=%s --grep='[foo' -F
[foo] abc

$ git log --oneline --format=%s --grep='\[foo'
[foo] abc
```

**Comment by kyleam** [comment]
By the way, for debugging purposes, you can set `magit-git-debug` to t.  Then you should see 

```
fatal: command line, '[ProjName': Unmatched [, [^, [:, [., or [=
```

in the process buffer.

**Comment by hisnawi** [comment]
@kyleam Thanks for your prompt response.
I updated my original description. Yes I did escape using \\[
Once you escape the bracket [ then there should be no errors finding a matching bracket.
As I mentioned above, it works fine with git Command Line. But not with Magit.

**Comment by kyleam** [comment]
On my end, I can't trigger a problem.  In particular, typing `l-F`, entering `\[foo`, and then hitting `L` in the repo above returns the expected

```
df883c1 [foo] abc
```

I'd suggest 1) checking what you see when `magit-git-debug`is t and 2) pointing to a public repo and exact commit on which you can trigger the problem.

**Comment by hisnawi** [comment]
@kyleam That seems to work on your side because is matching with foo not [foo].
If instead of "\\[Projname" I just do \\[Projname then yes all commits with \[Projname] and just Projname would show up.
But I want to specifically match on the first bracket as well.

**Comment by kyleam** [comment]
> That seems to work on your side because is matching with foo not [foo].

You're mistaken.  When I enter `\[foo` in magit (no quotes), it's matching `[foo`.

```
$ git log --oneline --format=%s               
foo other
[bar] def
[foo] abc
```

<kbd>l -F \\[foo L</kbd> (spaces for clarity)

```
df883c1 [foo] abc
```

<kbd>l -F foo L</kbd>

```
1a81cdf master foo other
df883c1 [foo] abc
```

> If instead of "\[Projname" I just do \[Projname

In the Magit prompt, it's incorrect to add the quotes.  Unlike in the shell, those are matching literal quotes.  That would explain why you're not seeing the commits.

> then yes all commits with [Projname] and just Projname would show up.

Do you actually see that on your end when you try?  If so, please point to a public repository and give exact steps to reproduce.

**Comment by hisnawi** [comment]
> l -F foo L

When you try the above why the:
foo other 
didn't show up?

**Comment by hisnawi** [comment]
Yes, you are correct.
l -F \[Projname L
Did work. Not sure what was happening before.
Thanks for your patience and help :)
