### ISSUE TITLE
Support `M-x revert-buffer` inside magit buffers

### ISSUE THREAD

**Issue by nagy** [magit/magit#4432]
Currently, when using `M-x revert-buffer` inside of any magit buffer, it shows:

```
Buffer does not seem to be associated with any file
```

We can make use of this function by setting the value of
`revert-buffer-function` to a helper of `magit-refresh` like so:

```elisp
(defun +magit-set-revert-function ()
    (setq revert-buffer-function (lambda (&optional ignore-auto noconfirm) (call-interactively #'magit-refresh))))
(add-hook 'magit-mode-hook #'+magit-set-revert-function)
```

Now we can use `M-x revert-buffer` in all magit derived buffer to refresh the
view.

If you want I can make a PR out of this.

**Comment by tarsius** [comment]
What's wrong with pressing `g` to invoke `magit-refresh` directly?

**Comment by nagy** [comment]
> What's wrong with pressing `g` to invoke `magit-refresh` directly?

Nothing ( in `evil-mode` it would be something like `g r` ), but each project
has its own refresh function. I see `revert-buffer` as Emacs's intended way of
refreshing a buffer. And since right now it does not do anything besides
printing a useless message, I thought other users might benefit from this.

It is like saying, what would be wrong with something like `magit-kill-buffer`.
Nothing, but there is already `kill-buffer` so why not use that?

**Comment by nagy** [comment]
Besides, other modes in Emacs do this as well, like in `ibuffer`:

```elisp
(set (make-local-variable 'revert-buffer-function)
       #'ibuffer-update)
```

https://github.com/emacs-mirror/emacs/blob/emacs-27.1/lisp/ibuffer.el#L2715-L2716

**Comment by tarsius** [comment]
Makes sense.

Any reason why you use `call-interactively`?

**Comment by basil-conto** [comment]
> Any reason why you use call-interactively?

Separately, I'd suggest using a named function rather than anonymous `lambda` for this, so that the `*Help*` docs are more readable. Thanks.

**Comment by tarsius** [comment]
That's what I was planning on doing, yes.

**Comment by nagy** [comment]
> Any reason why you use `call-interactively`?

Oh, I just tested it without and it still works. So no reason.

**Comment by tarsius** [comment]
I had to revert this because somehow the value from the magit buffers leaked into file-visiting buffers effectively making it impossible to revert them. I don't understand why that happens. Maybe you could investigate this?

**Comment by nagy** [comment]
I could reproduce this. Weird, I never noticed this before.

> Maybe you could investigate this?

I will.

**Comment by nagy** [comment]
So it seems like the definition of `revert-buffer-function` is:
```elisp
(put 'revert-buffer-function 'permanent-local t)
(defvar revert-buffer-function #'revert-buffer--default)
```

https://github.com/emacs-mirror/emacs/blob/emacs-27.1/lisp/files.el#L5967-L5968

You used `setq` in your code, and so did I. From my tests it seems like this
goes away if you use `setq-local`. Even though my help buffers show me that this
variable is buffer-local, it does not seem to be the case. Good to know. Maybe
they should use `defvar-local` instead.

**Comment by tarsius** [comment]
Autsch. Indeed, I looked at the documentation, saw `This variable's value blablabla a local binding.` and proceeded as if I had just read `Automatically becomes permanently buffer-local when set.` instead. The latter being what would appear if `defvar-local` had been used. Note to self: read those lines more carefully. :roll_eyes: 

> Maybe they should use `defvar-local` instead.

So it was my mistake, but maybe they should. Grepping the Emacs source indicates that others have made the same mistake before. `(setq revert-buffer-function 'bookmark-bmenu--revert)` for example seems wrong.

I would apprechiate it if you could discuss this on emacs-devel.

**Comment by nagy** [comment]
> others have made the same mistake before.

I never noticed that value leaking from `bookmark-bmenu` buffers either and it does not seem to do. So there still seems to be something that I dont understand.

> I would apprechiate it if you could discuss this on emacs-devel.

Sure, why not.

**Comment by alphapapa** [comment]
Thanks to both of you.  I'm curious enough to follow along but not enough to get involved.  :)  Maybe this issue should be reopened in the meantime?

**Comment by jakanakaevangeli** [comment]
bookmark-bmenu-mode is derived from `tabulated-list-mode`, which already makes
the variable local. Similarly for other results of
`grep -r "setq revert-buffer-function"`, it's always done in a mode deriving
from `tabulated-list-mode`, `help-mode` or some other mode which explicitly
makes the variable local.

**Comment by tarsius** [comment]
Ah, that makes sense. It's kinda obvious once you know it. :grin:

**Comment by nagy** [comment]
Thank you @jakanakaevangeli for the research. I still think the declaration of
`revert-buffer-function` as `defvar` and not `defvar-local` is not correct.

**Comment by nagy** [comment]
I have started a thread in emacs-devel about this here: https://lists.gnu.org/archive/html/emacs-devel/2021-08/msg00363.html

**Comment by tarsius** [comment]
Thanks! Looks like interest is low though. :(
