### ISSUE TITLE
Change Default Value Of transient-enable-popup-navigation

### ISSUE THREAD

**Issue by tvraman** [magit/magit#4436]
title:  Change Default Value Of transient-enable-popup-navigation
name: Feature request
about:Enabling Transient Navigation Makes Transient More Keyboard
Friendly 

Is there  a good reason why transient-enable-popup-navigation is
turned off by default? I just discovered it, along with the option to
enable single-column layout, and it immediately makes magit
transients  far more pleasant to use with spoken feedback. The ability
to move through the options with arrows and also to isearch  is a
winner! 

Only  other feature I'd like in regards to the navigation in the popup
would be the ability to   jump between /sections/ of the transient
window, ie between prefix, infix and suffix commands --- could we add
that?

Before you ask for a new feature to be added to Magit or for an existing feature to be improved, please make sure that what are asking for does not already exist by consulting the documentation [1].

Then describe the feature you would like to see in Magit and why it would be useful to you.  You might also want to describe any alternative solutions or features you've considered.

[1]: https://magit.vc/manual/magit/#Top
[2]: https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands

---- now delete this line and everything above ----

**Comment by tarsius** [comment]
> Is there a good reason why transient-enable-popup-navigation is turned off by default?

I don't think it is useful for a sighted person. Some of them disagree and so I ended up restoring that functionality early on.

For blind people this is obviously different and would guess that most of them would want this enabled, so definitely do that in emacspeak.

A big difference between magit-popup and transient is that the former made the popup buffer current while the latter lets the previously current buffer remain current. Using the former approach we got navigation among the available argument and commands; using the latter we have to implement it explicitly. But I switched to the latter approach for a reason: we get *something else* for free: acting on the thing at point and the (opt-in and unused by magit) ability to move around outside the popup buffer while the popup buffer is active.

> Only other feature I'd like in regards to the navigation in the popup would be the ability to jump between /sections/ 

Should be fairly easy to implement, using code similar to buffer-next but moving among text with the face transient-heading.

**Comment by tvraman** [comment]
Jonas Bernoulli ***@***.***> writes:

Thanks!
I totally get how transient is better than magit-popup for everyone.

Re transient navigation not being useful for other than blind users, I
agree; however the question is "Does it hurt users who can see to have
this on in any way"? The option is hard to discover ( I'm witness to
that :-)) and I've now added a note in the emacspeak manual saying that
that option should be turned on when using spoken feedback.

Could we implement section nav for transients in transient itself; I
could implement it in emacspeak, but binding keys within transient from
outside of transient so it's available in all transients  feels fragile.


>     Is there a good reason why transient-enable-popup-navigation is
>     turned off by default?
>
> I don't think it is useful for a sighted person. Some of them disagree
> and so I ended up restoring that functionality early on.
>
> For blind people this is obviously different and would guess that most
> of them would want this enabled, so definitely do that in emacspeak.
>
> A big difference between magit-popup and transient is that the former
> made the popup buffer current while the latter lets the previously
> current buffer remain current. Using the former approach we got
> navigation among the available argument and commands; using the latter
> we have to implement it explicitly. But I switched to the latter
> approach for a reason: we get something else for free: acting on the
> thing at point and the (opt-in and unused by magit) ability to move
> around outside the popup buffer while the popup buffer is active.
>
>     Only other feature I'd like in regards to the navigation in the
>     popup would be the ability to jump between /sections/
>
> Should be fairly easy to implement, using code similar to buffer-next
> but moving among text with the face transient-heading.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tarsius** [comment]
> "Does it hurt users who can see to have this on in any way"?

Yes it does because they can now see a second "active" cursor. One cursor is in the buffer that is actually the current buffer, and a second one in the buffer that lists the available arguments and commands. This makes it unclear which buffer is the current buffer but cannot be avoided because some commands act on the "current buffer" while the additional navigation commands act on the "list of commands" buffer so both cursors should be highly visible. While not technically true in a sense enabling "popup navigation" causes there to be two "current buffers" and I would rather not needlessly expose users to this confusion.

**Comment by tvraman** [comment]
Jonas Bernoulli ***@***.***> writes:

OK, I understand --- I was blissfully unaware of the two cursor issue.

Incidentally, transient navigation appears to have some unpredictable
behavior unless I'm misunderstanding things, here are examples:

Issue: Pressing enter on a selected suffix command doesn't appear to
quit the transient.

Example:

0. Hit 'l in the magit-status buffer,
1. Navigate to a suffix command using arrows (takes a while)    or use
   C-s and search for the relevant string eg "head " to land on suffix h
   2. Press enter --- you end up remaining in the transient.

      On the other hand, navigating to infix controls such as "--" for
      file pattern and pressing enter does work, you get to provide
      input in the minibuffer after  which the transient continues to
      wait for a suffix which is correct behavior; but pressing enter on
      a suffix should quit the transient and execute the suffix?

      


>     "Does it hurt users who can see to have this on in any way"?
>
> Yes it does because they can now see a second "active" cursor. One
> cursor is in the buffer that is actually the current buffer, and a
> second one in the buffer that lists the available arguments and
> commands. This makes it unclear which buffer is the current buffer but
> cannot be avoided because some commands act on the "current buffer"
> while the additional navigation commands act on the "list of commands"
> buffer so both cursors should be highly visible. While not technically
> true in a sense enabling "popup navigation" causes there to be two
> "current buffers" and I would rather not needlessly expose users to
> this confusion.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tarsius** [comment]
> Pressing enter on a selected suffix command doesn't appear to quit the transient.

That appears to be a regression, I'll look into it.

**Comment by tarsius** [comment]
Probably this was always broken, but e90481000f071e9a26a1cc0f40d347f7d3e2201e should fix it.

**Comment by tarsius** [comment]
https://github.com/magit/transient/commit/e90481000f071e9a26a1cc0f40d347f7d3e2201e
