### ISSUE TITLE
title:  Trouble binding keys into transient popup

### ISSUE THREAD

**Issue by tvraman** [magit/magit#4438]
name: Really A Support Question: Bug report

First off, apologies for not using the Support discussion group, but I
couldn't figure out how to post there using Emacs/Magit+forge.

I implemented myself transient popup section navigation but am having
trouble getting the keybinding to take, see
https://github.com/tvraman/emacspeak/blob/master/lisp/emacspeak-transient.el#L258

what I did:
Wrote myself the needed nav functions,
Bound them them in the relevant keymap
But I still got undefined prefix when I tried the bindings.
Then I updated the transient predicate app by mimicking the code in
transient.el but failed:-)

---

Please do not ignore these instructions.

If you have just updated Magit, then restart Emacs. If that does not fix the issue, then also uninstall Magit and all dependencies that were updated at the same time, restart Emacs and then reinstall Magit.

The reason why this might fix the issue is that updating a package does not cause the old version to be unloaded, so you might end up with a franken-version; a mixture of parts of the old and new version being loaded at the same time. Worse it is possible for the old version to leak into the byte-code of the new version, which is why reinstalling might help.

Please explain
    (1) what behavior you expected
    (2) what behavior you observed
    (3) and how we can reproduce the issue.

Please include a backtrace in your report.  In most cases doing:

    M-x toggle-debug-on-error RET

and then going through the steps again should result in a backtrace.

Also post the output of:

    M-x magit-version RET

Before reporting a defect please try to reproduce it using an Emacs instance in which only Magit and its dependencies have been loaded. Other packages or your configuration should not be loaded. This makes it easier to determine whether the issue lays with Magit or something else.

If you run Magit from its Git repository, then you can do so using:

    $ cd /path/to/magit
    $ make emacs-Q

Alternatively, run:

    M-x magit-emacs-Q-command RET

to save a shell command to the `kill-ring` and the system's clip-board, which you can then copy into a shell to run.

Finally, if that didn't work and you have installed Magit from Melpa, then run commands similar to the ones above, but use tab completion to replace the various Ns with the correct versions:

    $ cd ~/.emacs.d/elpa/magit-N
    $ emacs -Q --debug-init --eval '(setq debug-on-error t)' -L ../dash-N -L ../git-commit-N -L ../transient-N -L ../with-editor-N -L ../ghub-N -L . -l magit

More debugging tools are described in the manual.

    https://magit.vc/manual/magit/Debugging-Tools.html

---- now delete this line and everything above ----

**Comment by tarsius** [comment]
> I implemented myself transient popup section navigation but am having
> trouble getting the keybinding to take, see
> https://github.com/tvraman/emacspeak/blob/master/lisp/emacspeak-transient.el#L258

That looks okay as far as transient-specific things go. But you do not require transient before calling the function that adds the bindings but only if the keymaps exist that transient defines. So your bindings might never get added.

**Comment by tvraman** [comment]
Jonas Bernoulli ***@***.***> writes:

That file --- emacspeak-transient.el --- gets loaded by emacspeak as
soon as transient is loaded --- in general, each emacspeak extension
module for package <p> gets loaded via an eval-after-load on package
<p>.


>     I implemented myself transient popup section navigation but am
>     having
>     trouble getting the keybinding to take, see
>     https://github.com/tvraman/emacspeak/blob/master/lisp/emacspeak-transient.el#L258
>     
>
> That looks okay as far as transient-specific things go. But you do not
> require transient before calling the function that adds the bindings
> but only if the keymaps exist that transient defines. So your bindings
> might never get added.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tvraman** [comment]
I got the keybinding working, turns out binding left/right requires
two levels of indirection in transient-predicate-map --- I still dont
understand how this works.

See
https://github.com/tvraman/emacspeak/blob/master/lisp/emacspeak-transient.el#L263
However the section navigation still fails as in:

  1. After you move to the next section, up/down continue to navigate
     through buttons in the first section
     2.  Trying to move back always throws an error since point
        appears to be at the start of the transient buffer

        I've mimicked transient-forward-button in my code, I also
        tried explicitly switching to (window-buffer
        transient--window) with no change.

**Comment by tarsius** [comment]
I know what's going on. It's complicated and I'll have to implement section movement myself. Basically we cannot just move around the buffer, we also have to remember the location we moved to. Then, when we return to the command loop, the buffer content is recreated and we have to go back to the location. The code that does the location remembering and restoring assumes that one would only ever want to jump between the suffix (buttons) so at present trying to move anywhere else is futile.

**Comment by tvraman** [comment]
Jonas Bernoulli ***@***.***> writes:

Thanks, makes sense.

 > I know what's going on. It's complicated and I'll have to implement
> section movement myself. Basically we cannot just move around the
> buffer, we also have to remember the location we moved to. Then, when
> we return to the command loop, the buffer content is recreated and we
> have to go back to the location. The code that does the location
> remembering and restoring assumes that one would only ever want to
> jump between the suffix (buttons) so at present trying to move
> anywhere else is futile.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tarsius** [comment]
Off topic: I don't know whether you are aware that in some repositories the user is presented with repository-specific instructions when opening an issue or pull-request. These instructions are located inside the same text-field that the user then uses to write their message. It is done that way because in some cases the instructions serve as a template that you are expected to fill out Q/A style. In my repositories the instructions usually end with something like "now delete this line and everything above".

When using the web interface, then the cursor is placed inside the text-field before any instructions. In Forge the cursor is placed there or if there is a line that begins with "title: ", then right after that space.

Please try to delete these instructions, they are intended for the contributor, not the maintainer.

**Comment by tarsius** [comment]
Correction: On the web the cursor is placed in a separate title text-field and pressing TAB three times moves the cursor to the beginning of the body text-field

**Comment by tvraman** [comment]
Will look for those, I did see it but I still got confused re the
template.

Note that I never use the web interface, I exclusively use magit and
forge

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tarsius** [comment]
I haven't forgot about this and just bumped it up on my todo list.

**Comment by tarsius** [comment]
I have just pushed a change, which makes it quite simple to implement section movement commands. See https://github.com/magit/transient/commit/769219b5f5757f1373a28e993f36b6a41c778651. I am not adding any section movement commands to transient itself because

1. I don't think that is particularly useful for sighted people because no actions can be performed on them.
2. To adjust it for blind people you would still have to add explicit support in emacspeak.
3. Because transient does not already have functions comparable to `emacspeak-speak-previous-block` I would have to add a few dozen lines.

Below is an implementation that should work for emacspeak. I have actually tested this but had to comment out the calls to emacspeak-speak-this-personality-chunk in emacspeak-speak-previous-block and emacspeak-speak-next-block to be able to do so.

```elisp
(defun emacspeak-transient-previous-section ()
  (interactive)
  (with-selected-window transient--window
    (emacspeak-speak-previous-block 'transient-heading)
    (point)))

(defun emacspeak-transient-next-section ()
  (interactive)
  (with-selected-window transient--window
    (emacspeak-speak-next-block 'transient-heading)
    (point)))

(define-key transient-predicate-map
  [emacspeak-transient-previous-section] 'transient--do-move)
(define-key transient-predicate-map
  [emacspeak-transient-next-section] 'transient--do-move)

(define-key transient-popup-navigation-map
  [left] 'emacspeak-transient-previous-section)
(define-key transient-popup-navigation-map
  [right] 'emacspeak-transient-next-section)

(setq transient-enable-popup-navigation t)
```

**Comment by tvraman** [comment]
Awesome, I can take this from here.

As ever thanks for magit and transient --- it really levels the playing
field --- but more so, it puts me far ahead of my Chrome-bound mouse-waving peers:-)


-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tarsius** [comment]
You are welcome!

**Comment by tvraman** [comment]
I now have transient header navigation integrated and "mostly" working.

"Mostly" because:

1. in the logs transient, section navigation works for commit ordering
   etc in that after moving to that section, up/down moves through the
   items in that section. However the "Log" section doesn't appear to
   behave the same way; after navigating there, up/down seems to jump
   back to  items in the Commit Ordering section. Is "Log" section
   somehow special? I couldn't quite tell how it might be different.

   Also, C-s for isearch works, but it's  not always clear how to stop
   searching when it succeeds and continue in the transient, the
   *transient* buffer suddenly becomes current. However pressing return
   there does appear to act on the button  under point.
   
-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tarsius** [comment]
I've pushed a fix for the first issue.

**Comment by tvraman** [comment]
Better -- in that I can now correctly navigate to the log section and
move  to the button for "l" But pressing ENTER just dismisses the
transient,  rather than opening the logs.

Note: this is all for a new user learning magit; as an experienced user,
I just press 'll' for my own usage. But this is getting very close to a
nice system for learning magit and git options that one wants to use, it
also lets one discover rarely used options and commands.

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tarsius** [comment]
> But pressing ENTER just dismisses the transient,  rather than opening the logs.

I can't reproduce that.

**Comment by tvraman** [comment]
Jonas Bernoulli ***@***.***> writes:

Me Culpa -- it opened the logs in the "other window" as it dismissed the
transient, and I did not realize it had done that, since pressing 'l l'
usually leaves me in the logs :-)


>     But pressing ENTER just dismisses the transient, rather than
>     opening the logs.
>
> I can't reproduce that.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

-- 

Thanks,

--Raman(I Search, I Find, I Misplace, I Research)
♈ Id: kg:/m/0285kf1  🦮

**Comment by tarsius** [comment]
> C-s for isearch works, but it's not always clear how to stop searching when it succeeds and continue in the transient, the *transient* buffer suddenly becomes current.

I'll look into that some other time, when I deal with a few other issue of this sort.
