### ISSUE TITLE
`magit-auto-revert-mode` breaks marks in a buffer

### ISSUE THREAD

**Issue by Hi-Angel** [magit/magit#4442]
Ultimately, my problem is that attempt to use Evil-mode "marks" to remember important positions in a buffer gets hindered by magit causing all of the marks to get reset to the same line. So, for example: suppose a buffer had marks on lines `1500`, `3000`, `4500`. When I do a `git checkout HEAD^` in the repo causing the file/buffer to get auto-reverted, every mark gets reset to the single line `26`.

Some research showed that it doesn't seem to be specific to `evil-mode`, at least something very similar can be reproduced with the usual `set-mark-command` *(bound to <kbd>C</kbd>-<kbd>SPACE</kbd> by default)*. So, given the same buffer from the previous paragraph: what happens is that when I set a mark with `set-mark-command`, and execute `git checkout HEAD^`, the subsequent magit auto-revert causes the region between the current line and the line `26` to get highlighted.

This does not happen in all cases of revert. Reproducing it requires that the auto-revert makes some changes above the mark and below the mark. Which is simulated in steps-to-reproduce.

# Steps to reproduce

1. Inside `magit` repo execute `make emacs-Q` to make Emacs appear.
2. Evaluate <kbd>M</kbd>-<kbd>:</kbd> `(magit-auto-revert-mode 1)`
3. Open the `Makefile` in the magit repo.
4. Go to the `15`th line
5. Set a mark with `(set-mark-command)`
6. In terminal inside the repo execute `sed -i '1d;30d' Makefile` *(that deletes two lines: the 1st and the 30th, and magit subsequently auto-reverts the file/buffer)*

## Expected

In Emacs there wouldn't appear any highlighted region.

## Actual

In Emacs, the region between 1st line and the current point gets visually highlighted.

# Version

* magit from ELPA 20210713.939
* latest magit from git as of commit fa604f2c5ae86f8117c

**Comment by Hi-Angel** [comment]
Hmm, some further research shows, it's reproducible in Emacs `auto-revert-mode` as well *(so not a magit problem)*, and the problem seems to stem from `(revert-buffer)` function

**Comment by tarsius** [comment]
I've you haven't done so yet, then please open an issue in Emacs' issue tracker about this (after checking there isn't one already). Please link to it here.

(I can reproduce this.)

**Comment by Hi-Angel** [comment]
Sure, will do! Just, not right now, in 1-2 days.

Btw, @tarsius I suppose you wanted label `bug emacs` instead?

**Comment by phil-s** [comment]
Markers are relocated when buffer changes occur.  Adding or removing text *before* the marker will cause its position to increase or decrease accordingly in order to maintain its relative position; but if you delete a region *containing* a marker position, though, it will be relocated to the start of that deleted text.  E.g. deleting the region from chars 80-100 would move any marker in that region to position 80.

Emacs 28.1 introduces the command `revert-buffer-with-fine-grain`

>     revert-buffer-with-fine-grain is an interactive compiled Lisp function
>     in `files.el'.
>     
>     (revert-buffer-with-fine-grain &optional IGNORE-AUTO NOCONFIRM)
>     
>       Probably introduced at or before Emacs version 28.1.
>     
>     Revert buffer preserving markers, overlays, etc.
>     This command is an alternative to `revert-buffer' because it tries to be as
>     non-destructive as possible, preserving markers, properties and overlays.
>     Binds `revert-buffer-insert-file-contents-function' to the function
>     `revert-buffer-insert-file-contents-delicately'.
>     
>     With a prefix argument, offer to revert from latest auto-save file.  For more
>     details on the arguments, see `revert-buffer'.

**Comment by phil-s** [comment]
Some references:

* https://debbugs.gnu.org/cgi/bugreport.cgi?bug=34720
* https://debbugs.gnu.org/cgi/bugreport.cgi?bug=18
* https://debbugs.gnu.org/cgi/bugreport.cgi?bug=43016

**Comment by tarsius** [comment]
Ah, somehow I was under the impression that behavior that we can enable with the new `revert-buffer-with-fine-grain` has always been how it worked. So (a) I am enabling that in my config now and (b) it's probably not gonna make much of a difference in my case. :grin: 

Ah ha! That's why I though it already worked and kinda was right but not really: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=18#11.

Anyway, thanks for the information!

**Comment by Hi-Angel** [comment]
Thanks for the hint! I'm trying to research on how it works right now. It seems that one should use `(setq revert-buffer-function 'revert-buffer-with-fine-grain)`, and then all problems with markers are gone, but for me the subsequent `(revert-buffer)` call bails out with `revert-buffer-with-fine-grain: Variable binding depth exceeds max-specpdl-size`. So it's not quite clear just yet how one supposed to use that new funciton.

**Comment by Hi-Angel** [comment]
Alright! I think I figured it out!

So, what needs to be done for `magit-auto-revert-mode` to not break the marks *(i.e. to make use of the new function)* is to execute `(setq revert-buffer-insert-file-contents-function 'revert-buffer-insert-file-contents-delicately)`.

I think I'll probably also send a fix in documentation, because right now we wouldn't know all that unless @phil-s told us. The `revert-buffer` docs should really refer to that function, that would have saved us all quite some time.

**Comment by Hi-Angel** [comment]
FTR: [fixes to Emacs docs](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=49661) on the matter.

**Comment by Hi-Angel** [comment]
As a followup, if someone's gonna make use of `revert-buffer-insert-file-contents-delicately`, please make sure you have [this commit in your Emacs version included](https://github.com/emacs-mirror/emacs/commit/4ec10c80abfc985efa9707e5129b4cb5612d6582), otherwise the function might cause some unexpected behavior *(as a known example, Evil is known to start infinitely asking if you want to revert a buffer)*.

**Comment by tarsius** [comment]
Thanks for the note. I was wondering why it wasn't working for me.
