### ISSUE TITLE
RelNotes.org is a symlink

### ISSUE THREAD

**Issue by oscarfv** [magit/magit#4444]
symlinks are problematic on some systems (i.e. Windows, where they require elevated user rights to create).

Because of this, right now it is not possible to checkout `master` on Windows without Administrator privileges or changing the configuration of the OS (on recent versions.)

**Comment by tarsius** [comment]
According to [this](https://stackoverflow.com/questions/31149046) "symlinks are supported on Windows, and no longer require privilege elevation".

**Comment by tarsius** [comment]
Note that they do the exact same thing in git's own repository. I don't intend to drop the symlink.

**Comment by oscarfv** [comment]
Symlinks without administrator privileges are supported on Windows 10 only (from some version onwards) and even then it requires to put the OS on a special configuration (that does require administratator privileges to enable) and has several other effects. And IIRC git-for-windows must be configured to enable symlinks too.

So users of previous versions of Windows, users without Administrator privileges and users that don't want to put Windows on a special configuration state are out of luck.

> Note that they do the exact same thing in git's own repository.

Who are "they"? Microsoft? For several reasons, IMHO Microsoft is not a good model for development best practices on Magit's case (not for anyone else).

> I don't intend to drop the symlink.

Fair enough. Another change on my local fork then. Closing.

**Comment by tarsius** [comment]
> Who are "they"?

The developers of `git`. See https://github.com/git/git/blob/master/RelNotes. My reasoning is that if the `git` developers think this is a reasonable thing to do, then it is also good enough for `magit`.

**Comment by npostavs** [comment]
> Because of this, right now it is not possible to checkout `master` on Windows without Administrator privileges or changing the configuration of the OS (on recent versions.)

It gets checked out as a text file containing the target filename for me. `git version 2.23.0.windows.1`

**Comment by oscarfv** [comment]
The `git` development community is strongly Linux-centric (or POSIX-centric, being generous), everybody else is second-class, at best. It is expected that `git` developers on other platforms must jump through hoops to overcome differences and those developers are extensively familiarized with those differences, since their work consists precisely on porting `git`.

In Magit's case it is unfortunate that can't be cloned on an arbitrary Windows box as-is, moreover since a typical Windows developer often is not acquainted with POSIX concepts (and symlinks are a relatively new and rarely used feature on Windows). Hence, it is an inconvenience. Nothing terrible, though.

**Comment by oscarfv** [comment]
> It gets checked out as a text file containing the target filename for me. `git version 2.23.0.windows.1`

Thanks. I'm using `2.21.0.windows.1`. I'll try later with the most recent version and see if it is necessary to tweak some option on Git's configuration.

**Comment by oscarfv** [comment]
> > It gets checked out as a text file containing the target filename for me. `git version 2.23.0.windows.1`
> 
> Thanks. I'm using `2.21.0.windows.1`. I'll try later with the most recent version and see if it is necessary to tweak some option on Git's configuration.

While installing `2.32.0.2` it shows an option `Enable symbolic links ... (requires the SetCreateSymbolicLink permission)...` I leave it checked. Then cloning Magit works. Updating a previously existing Magit clone fails because of the symlink. All this on a Windows 8.1 machine without Administrator privileges.

So the problem can be solved by upgrading `git` and re-cloning. If someone has local changes on a previous clone I guess he can pull them to the new clone.

So the issue it is not as bad as I thought. I don't know what happens if the user changes the file that corresponds to the symlink, though. Not a big concern with just this file, but something to ponder before adding more symlinks.
