### ISSUE TITLE
Super slow (on long lines?)

### ISSUE THREAD

**Issue by dabrahams** [magit/magit#4448]
Check out https://github.com/sean-parent/reveal.js, add a character to the end of the first line of https://github.com/sean-parent/reveal.js/blob/master/plugin/highlight/highlight.js, and visit the working copy in magit.  It takes a *long* time to bring up the repository buffer.  I suspect that's because the main content is one extremely long line of text, but it could be something else.

**Comment by tarsius** [comment]
Emacs has issues excessively long lines. There's not really anything Magit can do about it.
