### ISSUE TITLE
magit slowdown with excessive use

### ISSUE THREAD

**Issue by nkiesel** [magit/magit#4451]
### Discussed in https://github.com/magit/magit/discussions/4450

<div type='discussions-op-text'>

<sup>Originally posted by **nkiesel** July 21, 2021</sup>
Hi,

I love Magit and use it especially when dealing with complicated commits.  The only problem I have is that with every use, Magit gets slower and slower.  While the first diff shown for a commit - even if the diff contains changes for dozens of files - is fast (1-2 seconds), after a couple of such commits the "commit diff" takes up to a minute and Magit is frozen during that time.

The only solution I'm aware of is to restart Emacs,

My laptop of reasonably powerful (1 year old Dell, 1GB memory, Intel i-7, SSD), and other resource-intensive stuff (e.g. IntelliJ) continues to perform w/o much performance regressions.

Am I doing something wrong?</div>

**Comment by alphapapa** [comment]
See https://github.com/magit/magit/discussions/4450#discussioncomment-1035460
