### ISSUE TITLE
Stashing seems to be broken with git 2.31 onwards

### ISSUE THREAD

**Issue by mgamito** [magit/magit#4452]
There's an odd behaviour with stashing that appeared with git 2.31 forward. git 2.30 is fine.
This is with the latest released magit 3.1.1

If I stash a bunch of files with zz and later un-stash them with zp, something seems to stay behind.
On the command line 'git stash list' shows nothing but 'git stash show' still shows the files that have been stashed, which seems like an inconsistent state to me.  gitk also shows the presence of a stash, even though magit no longer reports anything.

**Comment by tarsius** [comment]
I'm on 2.31.1 and v3.1.1-57-g0ea7868e3 and cannot observe any such behavior.

Can you reproduce this consistently in different repositories? Even if you apply the stash again immediately after creating it? Two `git stash` subcommands disagreeing on whether there is any stash sounds like something is seriously borked and magit probably isn't to be blamed.

**Comment by mgamito** [comment]
I tried with three different repos and get the same result. Using the git command line to stash/un-stash works ok.

**Comment by tarsius** [comment]
Since we haven't touched the respective code in months and you seem to be the only one having issues, I suspect there's some issue on your end. All I can do is give you some pointers. Create a stash using the command line and then inspect it using `git log -p --graph stash@{1}`, `git reflog refs/stash` ... Then apply it and inspect refs/stash again. Then create and apply using magit instead. Inspect the result the same way and look for differences.

**Comment by mgamito** [comment]
I did a bit more digging into this. I set `(setq magit-git-debug t)` Then with git-2.30.1, I get this log after un-stashing a file

```
0 git ... stash apply --index stash\@\{0\} ...
0 git ... rev-parse stash\@\{0\} ...
0 git ... reflog delete --updateref --rewrite stash\@\{0\} 
0 git ... update-ref -d refs/stash
```

If I now try with git-2.31.1, I get instead:

```
0 git ... stash apply --index stash\@\{0\} ...
0 git ... rev-parse stash\@\{0\} ...
0 git ... reflog delete --updateref --rewrite stash\@\{0\} 
```

The missing last statement seems consistent with the error I'm getting, where `git stash list` reports nothing but `git stash show` still shows files in the stash. I did a git bisect on the git repo and the commit that causes this change in behaviour is:

```
6436a20284f33d42103cac93bd82e65bebb31526 is the first bad commit
commit 6436a20284f33d42103cac93bd82e65bebb31526
Author: Denton Liu <liu.denton@gmail.com>
Date:   Thu Jan 7 02:36:59 2021 -0800

    refs: allow @{n} to work with n-sized reflog
```

Honesly, I don't know if the problem is with magit or git itself. I'm sorry if I'm bothering you with this when maybe I should be reporting to git instead.

Perhaps I should mention that I'm behind a firewall at work and don't have the http connectivity to do a `git clone` or use the emacs melpa archive so I have to painstakingly download all the relevant .tar.gz files and install everything by hand, including libgit2, libegit2, dash, transient and with-editor. I wonder if somewhere along that long process I'm doing something wrong.

**Comment by tarsius** [comment]
Nice detective work and sorry for being a bit dismissive.

```
magit-stash-drop: Use "git stash drop"

Previously we called "git rev-parse --verify refs/stash@{0}" and if
that didn't return a revision then we knew that no stash remains and
so we also deleted the "refs/stash" reference itself.  We cannot do
that anymore because a special case was added in 6436a20284f33d421,
which makes that command return a revision even when the reflog is
empty.  Now we use "git stash drop" directly.  It uses the same logic
to determine whether any stash remains before deleting the ref, but
it does so using a lower-level C api, which is not affected by this
backward incompatible change in git.  We did not use "git stash drop"
when we first implemented `magit-stash-drop' because "git-stash" was
still a shell-script and just copying the relevant bits made more
sense.
```
