### ISSUE TITLE
git operations from `magit-list-repositories` buffer

### ISSUE THREAD

**Issue by Boruch-Baum** [magit/magit#4453]
This is a follow-up to PR #4399 and related PR's.

The idea is to enable a user to select one or more lines of the `magit-list-repositories` buffer, and perform git operations in bulk on all repositories represented by the selection.

For example, you start your work-week after a few days away, and you expect that repositories of interest have had upstream pushes. Currently, you need to manually navigate to each repository and individually perform a `git fetch` or `git pull`. The idea would have the user perform M-x `magit-list-repositories`, then `C-x h` to select the entire buffer (ie. all repositories), then invoke some single one-time buffer-specific mode-specific keybinding or transient for the `git fetch` or `git pull` operation on all the selected repositories.

It could be that other git operations would make sense to expose for this idea. Maybe `git push origin`. Maybe `forge` commands for retrieving issue or PR data.

**Comment by tarsius** [comment]
Also see #2971.
