### ISSUE TITLE
magit-log-select broken with magit-display-buffer-noselect set t

### ISSUE THREAD

**Issue by duncanburke** [magit/magit#4461]
With "Magit v3.1.1-62-g2db04ea9, Git 2.32.0, Emacs 28.0.50, gnu/linux" at commit 2db04ea92562350ec5f0e78fa21c7d53f38d351c

Steps to reproduce:
1. `emacs -Q -l ~/.emacs.d/straight/repos/straight.el/bootstrap.el` 
2.  `(straight-use-package 'magit)` 
4. `(setq magit-display-buffer-noselect t)`
5. Open up a repository in magit
6. Try to use a function based on `magit-log-select` e.g start an interactive rebase or try to create a fixup commit
7. Observe the message "Type M-x magit-log-select-pick on a commit to fixup into it, or M-x magit-log-select-quit to abort"
8. Try to select a commit with `C-c C-c`
9. Observe the message "magit-log-select-pick: Symbol’s function definition is void: nil"

I'm guessing this is something to do with it not picking up on the keybindings in `magit-log-select-mode-map` if focus isn't changed to the new buffer. Note that `C-c C-c` is still bound to `magit-log-select-pick`, and it can even be called manually with `M-x magit-log-select-pick`, but that doesn't work either.

**Comment by tarsius** [comment]
Yes. Don't do that.

This variable is intended to be let bound in certain situations. It is not intended to be permanently set by the user.

**Comment by duncanburke** [comment]
Okay, thanks. I note, though, that it is not named with a `--`, as is conventional for private variables, nor is there any mention in the docstring that it is dangerous to set permanently.

**Comment by tarsius** [comment]
It's not really a private variable. Authors of third-party packages might very well have to use it. For now I am not augmenting the doc-string either, if additional users report that they concluded that this was intended for user customization then I would change my mind about it. While there is nothing explicit about it, I think that its technical wording implies that it isn't for end-user use. (At least I would not write an end-user doc-string like this.)
