### ISSUE TITLE
Save patches into buffers or kill ring (rather than just files)

### ISSUE THREAD

**Issue by Hugo-Heagren** [magit/magit#4462]
At the moment, the only way destination for generated patches is a file. I propose that it would be good if patches could be written to buffers (new buffers, not yet associated with actual files) and to the kill ring.

This is because sometimes a patch never needs to 'leave' emacs, and would be easy to manipulate if it didn't. Obviously the easiest way to manipulate a large piece of text in emacs is to store it (alone) in a buffer, but the kill ring is also useful.

Here's an example. I recently wanted to contribute to [the unix passwordstore](https://www.passwordstore.org/). I use magit and forge, so I made my commits and sent a PR. Then I read the website properly and realised that contributions and other discussion happen on a mailing list. So I went to the log of my local copy of the project, and created a patch of the commit I had made for my change. I had to pick a name, and save it to a file. Then I opened gnus, wrote my email, inputted the file, had to remember where I had put it, and sent the email. An hour later I wondered why I had a patch file (ambigously named 'patch'?) in my home dir. Then I checked and deleted it.

What I needed was something less permanent than storage. I use ivy so having big entried in the kill ring is fine and that would have been ideal. A buffer is a similar principle though.

**Comment by kyleam** [comment]
> a patch never needs to 'leave' emacs, and would be easy to manipulate if it didn't

Yeah.  There are lots of different patch/email workflows, and once you start working on a multi-patch series, I think the above carries less weight, but I agree with the sentiment.  In case you or others find them useful, here are two `magit-patch-save`-inspired commands from my config that I use for sending one-off patches (especially as replies) and for including plain diffs in mail or posts to other locations:

<details>
<summary>commands</summary>

```elisp
(defun km/magit-dump-diff-to-buffer (&optional arg)
  "Like `magit-patch-save', but dump output to a buffer."
  ;; Note: Nearly all of this is just copied from `magit-patch-save'.
  (interactive "P")
  (require 'magit-patch)
  (unless (derived-mode-p 'magit-diff-mode)
    (user-error "Only diff buffers can be saved as patches"))
  (let ((rev magit-buffer-range)
        (typearg magit-buffer-typearg)
        (args magit-buffer-diff-args)
        (files magit-buffer-diff-files))
    (cond ((eq magit-patch-save-arguments 'buffer)
           (when arg
             (setq args nil)))
          ((eq (car-safe magit-patch-save-arguments) 'exclude)
           (unless arg
             (setq args (-difference args (cdr magit-patch-save-arguments)))))
          ((not arg)
           (setq args magit-patch-save-arguments)))
    (with-current-buffer
        (generate-new-buffer
         (replace-regexp-in-string
          "^\\*" "*diff dump: "
          (funcall magit-generate-buffer-name-function
                   major-mode (magit-buffer-value))))
      (magit-git-insert "diff" rev "-p" typearg args "--" files)
      (pop-to-buffer (current-buffer)))))

(defun km/magit-dump-patch-to-buffer ()
  (interactive)
  (require 'magit-patch)
  (unless (derived-mode-p 'magit-revision-mode)
    (user-error "Not revision buffer"))
  (let ((rev magit-buffer-revision))
    (with-current-buffer
        (generate-new-buffer
         (replace-regexp-in-string
          "^\\*" "*patch dump: "
          (funcall magit-generate-buffer-name-function
                   major-mode (magit-buffer-value))))
      (magit-git-insert "format-patch" "--stdout" (concat rev "^-1"))
      (pop-to-buffer (current-buffer)))))
```

</details>

Those generate a new buffer.  I typically use `insert-buffer` to insert the resulting patch/diff buffer into another buffer (e.g., a `message-mode` buffer), though it'd be straightforward to adapt those to kill the text as well.

The above commands are obviously very much personal-config material and aren't fit for inclusion in Magit as is, and I'd understand the point of view that functionality like this is obscure enough to not be worth adding to Magit proper.

**Comment by Hugo-Heagren** [comment]
Fair point. Thanks for the commands from your config. I didn't know how to add commands like these to magit, so for posterity in case anyone else wants something like this, here's what I ended up with:

<details><summary>Custom Patch Command Definitions</summary>
<p>

```emacs-lisp
(use-package magit
  :config
  (require 'magit-patch)
  (transient-insert-suffix
    'magit-patch "r" '("b" "Save diff as patch to buffer" my/magit-write-patch-to-buffer))
  (transient-insert-suffix
    'magit-patch "r" '("w" "Copy diff as patch to kill-ring" my/magit-copy-patch-kill-ring)))

(defun my/magit-write-patch (write-function &optional arg)
  "Write patch of current diff to a temp buffer, then run WRITE-FUNCTION.

This is useful as a backend abstraction for
`my/magit-write-patch-to-buffer' and `my/magit-copy-patch-kill-ring'.

Cribs lots of code from `magit-patch-save'. Inspired by
https://github.com/magit/magit/issues/4462#issuecomment-892358920."
  (interactive)
  (require 'magit-mode)
  (require 'magit-diff)
  (unless (derived-mode-p 'magit-diff-mode)
    (user-error "Only diff buffers can be saved as patches"))
  (let ((rev     magit-buffer-range)
        (typearg magit-buffer-typearg)
        (args    magit-buffer-diff-args)
        (files   magit-buffer-diff-files))
    (cond ((eq magit-patch-save-arguments 'buffer)
           (when arg
             (setq args nil)))
          ((eq (car-safe magit-patch-save-arguments) 'exclude)
           (unless arg
             (setq args (-difference args (cdr magit-patch-save-arguments)))))
          ((not arg)
           (setq args magit-patch-save-arguments)))
    (with-temp-buffer ;; This drops you in the buffer you selected
      (magit-git-insert "diff" rev "-p" typearg args "--" files)
      (funcall write-function)))
  (magit-refresh))

(defun my/append-all-to-chosen-buffer ()
  "`Append-to-buffer' all text in the current buffer to a chosen buffer.

Finishes with chosen buffer displayed."
  (let ((buffer (ivy-read "Dump/append patch to buffer: " #'internal-complete-buffer
 			  :def "*patch*")))
    (mark-whole-buffer)
    (append-to-buffer buffer (region-beginning) (region-end))
    (pop-to-buffer buffer)))

(defun my/kill-buffer-text ()
  "Kill all text of current buffer."
  (mark-whole-buffer)
  (kill-region (region-beginning) (region-end)))

(defun my/magit-write-patch-to-buffer ()
    "Write patch format of current diff into chosen buffer.

Uses `magit-patch-save' internally, so inherit it's settings."
  (interactive)
  (my/magit-write-patch 'my/append-all-to-chosen-buffer))

(defun my/magit-copy-patch-kill-ring ()
  "Copy patch format of current diff into kill ring.

Uses `magit-patch-save' internally, so inherit it's settings."
  (interactive)
  (my/magit-write-patch 'my/kill-buffer-text))

```

</p>
</details>

Commands for copying to the kill ring (under <kbd>w</kbd>) and  to another buffer (<kbd>b</kbd>) will now show up in the magit transient prompts and behave like any other transient commands (I think. I may have missed some subtleties). I'm sure that this could be expanded or tidied up and included in magit proper, but like you say it's probably a bit obscure, and I'm happy enough with this solution!
