### ISSUE TITLE
the layout of ediff merge windows look weird

### ISSUE THREAD

**Issue by huangfeiyu** [magit/magit#4463]
Thank you for your work, I really appreciated.
![Screenshot_2021-08-05_17-57-53](https://user-images.githubusercontent.com/12697122/128333414-8534de64-2c71-4461-9829-b8a7eac6c2d7.png)

1. There are two control windows, it should be only one.
2. The height of the control window is too high before I adjust it manually.

Magit 20210715.500, Git 2.20.1, Emacs 26.1, Debain 10
By the way, I used the version of magit from Debian 10 repository, it works perfectly. But the above version have the above issues.

**Comment by alphapapa** [comment]
Can you reproduce using `emacs -q` and the latest version of Magit?

**Comment by huangfeiyu** [comment]
@alphapapa the latest works as expected. thanks.
