### ISSUE TITLE
Magit install config stopped working

### ISSUE THREAD

**Issue by trev-dev** [magit/magit#4465]
I had a reason to wipe/recompile my .emacs.d/elpa folder and realized that magit would no longer compile/install with me `use-package` config:

```elisp
(use-package magit
  :ensure t
  :config
  (global-set-key (kbd "C-c g") 'magit-status))
```

I'm getting the following warning:
`Error (use-package): magit/:catch: Loading file /home/me/.emacs.d/elpa/with-editor-20210524.1654/with-editor.elc failed to provide feature ‘with-editor’`

I attempted a manual install and did not have much luck.

**Comment by alphapapa** [comment]
I just tested in a clean config using https://github.com/alphapapa/emacs-sandbox.sh and Magit installs and magit-status works without errors.

**Comment by tarsius** [comment]
This is a known mystery bug: https://github.com/magit/with-editor/issues/86. I don't think magit or with-editor are to be blamed but then again I have no idea what is going so who knows. Let me know (on that issue) if you have an idea.

**Comment by trev-dev** [comment]
@alphapapa Your sandbox script is pretty cool. I'm also able to install magit with it. I went back to my own env, purged my `.emacs.d/elpa` folder, removed my `use-package` config and installed it the traditional way.

It still broke. Over 40 tracebacks for every time a magit lib tries to load with-editor. 

I'm new to lisp but not be to programming, I'll see what I can find.
