### ISSUE TITLE
Diff config interferes with magit-status

### ISSUE THREAD

**Issue by Boruch-Baum** [magit/magit#4466]
Magit 20210728.2026, Git 2.30.2, Emacs 27.1, gnu/linux (debian)

Starting from a repository with no current changes, ie nothing (un)staged, open the `magit` transient, select 'D', then '-w' and '-b' so that diffs will ignore whitespace, then select 'w' to "refresh buffer and save defaults". For future diffs, this does work as expected and does ignore whitespace. Great, so far.

However, it seems to also apply these setting (partially) to the `magit-status` buffer in an unexpected fashion, with undesirable and burdensome results:

1) make a whitespace-only change to a file under that repository's version control.
2) refresh the `magit-status` buffer and see no changes recorded as (un)staged.
3) attempt to perform a change of branch, or a rebase
4) magit reports an error to the effect that changes need to be commited or stashed.
5) refresh the `magit-status` buffer and see no changes reported!
6) perform a stash ( 'z' 'z' ), and see the white-space change stashed
7) now it is possible to rebase or change branch

**Comment by tarsius** [comment]
> Starting from a repository with no current changes, ie nothing (un)staged, open the magit transient, select 'D', then '-w' and '-b' so that diffs will ignore whitespace, then select 'w' to "refresh buffer and save defaults". For future diffs, this does work as expected and does ignore whitespace. Great, so far.

If you press `D` while a status buffer is active, then you change the setting for status buffers. If you do it while a diff buffer is active, then that affects diff buffers instead. I recommend you only use these arguments in diff buffers. When you want to see the staged or unstaged changes without the whitespace changes, then you should bring up the respective diff in a separate buffer and enable those arguments there.

This behaves as expected.

**Comment by Boruch-Baum** [comment]
If so, then let me suggest a change to the wording of the transient to
make that clear. Currently, the transient reads (on the bottom of the 'D'
transient):

   s buffer and set defaults
   w buffer and save defaults

How about re-wording that to:

   s set buffer defaults
   w save buffer defaults

>    This behaves as expected.

1) I challenge that. How many other people have told you that's what
   they expect?

2) Your advice puts the user in a position of needing to laboriously
   repeat the same three keypress operations for every diff action.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by tarsius** [comment]
@kyleam How do you feel about changing to: `buffer and set defaults for diff buffers` and the other descriptions accordingly?

1. As in "The code behaves as its author wanted it to behave. There is no bug." You can of course argue that it would make more sense for something else to happen.

2. Which three key presses?

**Comment by kyleam** [comment]
> @kyleam How do you feel about changing to: `buffer and set defaults for diff buffers` and the other descriptions accordingly?

I feel okay about the wording, but would that involve repeating the `transient-set` and `transient-save` entries in the `magit-diff-refresh` and `magit-log-refresh` transients with descriptions for each affected mode (via `:if-mode`)? If so, what about instead changing the shared description to something like `buffer and set defaults for mode's buffers`?

**Comment by tarsius** [comment]
> `... set defaults for mode's buffers?`

That sounds like it would confuse more people than help. Since when do modes have buffers that are "theirs"? etc.

No duplication is needed for `... set defaults for diff buffers` but it is still ugly:

```elisp
  [["Refresh"
    ("g" "buffer" magit-diff-refresh)
    ("s" transient-set :transient nil :description
     (lambda () (format "buffer and set defaults for %s buffers"
                   (if (derived-mode-p 'magit-status-mode) "status" "diff"))))
    ("w" transient-save :transient nil :description
     (lambda () (format "buffer and save defaults for %s buffers"
                   (if (derived-mode-p 'magit-status-mode) "status" "diff"))))]
```

And the extra verbosity when the text is displayed *also* bothers me.

I am leaning towards the status quo.

**Comment by Boruch-Baum** [comment]
On 2021-08-06 10:03, Jonas Bernoulli wrote:
>    ***@***.*** How do you feel about changing to: buffer and set defaults
>    for diff buffers and the other descriptions accordingly?
>     1. As in "The code behaves as its author wanted it to behave. There is
>        no bug." You can of course argue that it would make more sense for
>        something else to happen.
>     2. Which three key presses?

Once in the 'D' transient, the key sequences '-w', '-b', and then 'w' (or
possibly 's'), so three key sequences once in the transient, but more
than three key presses.

If you're still set on retaining the current behavior, here's an
alternative suggestion for re-wording the transient: Change the section
heading from simply 'Refresh' to 'Refresh Buffer'. That will more
clearly indicate that all operations in that section are
buffer-specific. Then you might also re-word key-presses 's' and 'w' to
'and set buffer defaults' / 'and save buffer defaults'

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by kyleam** [comment]
> No duplication is needed

Right, thanks.

> (if (derived-mode-p 'magit-status-mode) "status" "diff")

Wouldn't some other modes need to be accounted for?  For example, "set defaults" in a `magit-diff-mode` buffer doesn't affect `magit-revision-mode`.

**Comment by tarsius** [comment]
Right, we would have to extract the middle part of the mode name... making it even uglier. :(

**Comment by tarsius** [comment]
@Boruch-Baum I think you want `(setq magit-prefix-use-buffer-arguments 'always)`.

**Comment by Boruch-Baum** [comment]
On 2021-08-09 16:09, Jonas Bernoulli wrote:
>    ***@***.*** I think you want (setq
>    magit-prefix-use-buffer-arguments 'always).

That does sound helpful. Thank you. However, it isn't what I want or
what I expected based upon the text in the transient. The transient, as
currently worded, sounds to me as a permanent and persistent setting of
default behavior. A second issue is that I was expecting that default
behavior to apply only to diff buffers and not to the diff calculation
performed by the magit status buffer.

I don't mean to be a continuing bother about this; the first issue is an
annoyance, but one that I can live with, and now that you pointed out
the config option, it will occur less often. If I'm the only one
reporting the issue and you feel its uncalled for, fine. The second
issue was more than an annoyance - it was perplexing and took a while
for me to even figure out what was going on; I expect it will trip up
others, but hey no one else seems to be complaining. The magit status
buffer was reporting no changes staged or unstaged, but was refusing to
let me switch branches. I eventually tried stashing what looked like a
clean state, and only then saw in the stash that there had in fact been
changes (white-space) otherwise hidden from view in status buffer.

--
hkp://keys.gnupg.net
CA45 09B5 5351 7C11 A9D1  7286 0036 9E45 1595 8BC0

**Comment by Boruch-Baum** [comment]
On 2021-08-09 16:09, Jonas Bernoulli wrote:
>    ***@***.*** I think you want (setq
>    magit-prefix-use-buffer-arguments 'always).

Separately, I have a related documentation request. The
`describe-variable' output for the above says, "This variable was
introduced, or its default value was changed, in version 3.0.0 of the
magit package." However, the output of M-x `magit-version' (magit
haveing been installed via melpa) uses a calendar-date based version
string instead.

   Magit 20210728.2026, Git 2.30.2, Emacs 27.1, gnu/linux

Could you add to that string the 'tagged' version?

--
hkp://keys.gnupg.net CA45 09B5 5351 7C11 A9D1 7286 0036 9E45 1595 8BC0

**Comment by tarsius** [comment]
> Could you add to that string the 'tagged' version?

If just done that. Well not quite because the tag is not available when the package is installed from Melpa. However, very recently (less than a week) ago I started setting `Package-Version` so that Magit could be added to NonGNU Elpa. So we can use that information here as well!

**Comment by tarsius** [comment]
>  1. make a whitespace-only change to a file under that repository's version control.
>  2. refresh the `magit-status` buffer and see no changes recorded as (un)staged.
>  3. attempt to perform a change of branch, or a rebase
>  4. magit reports an error to the effect that changes need to be commited or stashed.
>  5. refresh the `magit-status` buffer and see no changes reported!
>  6. perform a stash ( 'z' 'z' ), and see the white-space change stashed
>  7. now it is possible to rebase or change branch

You could be more explicit about it but the issue you are reporting seems to be that you think (4) should not happen. I.e. you expect to do (3) and then go straight to (7) from there.

This has nothing to do how diff arguments are set and saved in status and diff buffers and how the respective arguments have to enabled again or not, etc. All that matters here is that there *are* differences, and thus you cannot rebase. `git rebase` doesn't care what is or is not being shown in magit's status buffer, it simply doesn't want to do anything if there are uncommitted changes.

(Actually by using the `--autostash` argument `git rebase` can be told to stash away the uncommitted changes before it performs the rebase. I.e. you can automate the step of stashing before rebasing, but what that doesn't change is the fact that rebasing is *not possible* while there are uncommitted changes.)

This is the reason why I suggested that you only hide whitespace changes in the dedicated diff buffer but not in the status buffer: It ensures that you are always aware of these changes and thus won't attempt to perform any actions that are not possible (and if only by default) if that is the case.

Again, this has nothing to do with magit. You could exit emacs and then type `git rebase ...` into a terminal and it still wouldn't work. If you added `--autostash`, then it would.

----

Concerning how diff arguments are changed and saved, and how different modes and buffer and options come into play and what not: Yes this is complicated. I believe it is necessarily complicated and cannot be made significant more intutive without losing important functionality.

You suggested that the descriptions of the set and save commands are improved. Maybe that would help a bit, or not. But regardless it could not make it unnecessary to read the documentation to really understand what is going on, and how to make the most of it.

Sooner or later all users (who use this often enough to run into a situation in which the observed behavior does not match their expectancy) won't get around reading [Transient Arguments and Buffer Variables](https://magit.vc/manual/magit/Transient-Arguments-and-Buffer-Variables.html) *at least* twice.
