### ISSUE TITLE
Magit action P p hangs after username prompt

### ISSUE THREAD

**Issue by sivaramn** [magit/magit#4467]
`Magit 3.2.0, Git 2.32.0, Emacs 27.2, cygwin`

I have no idea since when it was broken but I was able to push to my github repo regularly from within magit.  Now, it simply does nothing after getting the username prompt and email id entered.  The session does not hang but it does not ask for the passphrase token anymore.  Nothing happens after entering my email id

I initially thought, there might be a windows10 firewall problem but I was able to push my changes through with
`git push https://github.com/sivaramn/initfiles master:master` from the commandline  within cygwin

Trying debugging as suggested below, resulted in the same issue. username prompted for and after entering, nothing happens(it should prompt for github token for password).  Emacs is responsive though.  The `magit-process` buffer shows the command and the last username prompt text

`/usr/bin/emacs -Q --eval \(setq\ debug-on-error\ t\) -L /home/sivaramn/.emacs.d/elpa/dash-2.19.0/ -L /home/sivaramn/.emacs.d/elpa/transient-0.3.6/ -L /home/sivaramn/.emacs.d/elpa/with-editor-3.0.4/ -L /home/sivaramn/.emacs.d/elpa/magit-3.2.0/ -L /home/sivaramn/.emacs.d/elpa/magit-section-3.2.0/ -L /home/sivaramn/.emacs.d/elpa/git-commit-3.2.0/ -l /home/sivaramn/.emacs.d/elpa/magit-3.2.0/magit`

**Comment by tarsius** [comment]
Once a process terminates the exit code is shown in the process buffer. Is it shown for the `git push` process? What is it?

> I was able to push my changes through with `git push https://github.com/sivaramn/initfiles master:master` from the commandline within cygwin

Please post the output.

**Comment by sivaramn** [comment]
> Once a process terminates the exit code is shown in the process buffer. Is it shown for the `git push` process? What is it?

No, the process doesnt seem to terminate.  I wait for the passphrase prompt and since it doesnt appear, I exit emacs and I get a warning that 'active processes are running, do you want to continue prompt'

> 
> > I was able to push my changes through with `git push https://github.com/sivaramn/initfiles master:master` from the commandline within cygwin
> 
> Please post the output.

     $ pushgithub # alias for git push
    Username for 'https://github.com':
    Password for 'https://nsivaraxxx@gmail.com@github.com':
    Enumerating objects: 34, done.
    Counting objects: 100% (34/34), done.
    Delta compression using up to 4 threads
    Compressing objects: 100% (26/26), done.
    Writing objects: 100% (27/27), 4.90 KiB | 1003.00 KiB/s, done.
    Total 27 (delta 15), reused 0 (delta 0), pack-reused 0
    remote: Resolving deltas: 100% (15/15), completed with 5 local objects.
    To https://github.com/sivaramn/initfiles
    0a33ecc..a37004e  master -> master

**Comment by sivaramn** [comment]
This is all I see in Magit Process buffer and nothing else happens.

    0 git.exe … commit --
    Waiting for Emacs...
    [master 342d9e0] changed font to Cascadia
    1 file changed, 5 insertions(+), 3 deletions(-)

    run git.exe … push -v origin refs/heads/master\:refs/heads/master
    Pushing to https://github.com/sivaramn/initfiles.git
    Username for 'https://github.com':

**Comment by tarsius** [comment]
> I have no idea since when it was broken but I was able to push to my github repo regularly from within magit.

Back then did you also have to enter the username and password every time, or did you have it configured so you wouldn't have to do that?

**Comment by sivaramn** [comment]
> 
> 
> > I have no idea since when it was broken but I was able to push to my github repo regularly from within magit.
> 
> Back then did you also have to enter the username and password every time, or did you have it configured so you wouldn't have to do that?

Yes, it was initially username and password and then changed to passphrase token by github and it worked without any issues when it changed.  So, fairly long time I was entering userid+pass to push to github.

Also, I initially used win64 emacs +cygwin and it failed.  then went into cygwin terminal and tried exclusively with cygwin emacs with the same failed results.  And in cygwin terminal, commandline `git push` works.  Just for the record, all other local operations with magit 3.2.1 works, staging, committing and status saying "you're x commits ahead of master" all work.  Just that convenient P p bombs;  The only thing I find additionally strange is that emacs used to freeze a bit in the process of connecting, validating the 2 steps of userid and password, now it doesn't at all.  it simply is as responsive as typing text stuff immediately after userid prompt.

**Comment by tarsius** [comment]
I very much dislike dealing with support requests related to pushing on Windows.

I don't understand whether you are saying that you previously were able to push without having to provide a username and password, or if you are saying the opposite.

In any case that should be the goal. Do not even try getting "pushing with password prompt" going. That is very inferior experience and maybe it is even impossible with your current combination of software.

Instead of that you should search the web for instructions on how to configure password-less pushing. Also see our wiki page on the matter: https://github.com/magit/magit/wiki/Pushing-with-Magit-from-Windows.

I would also like to ask you to ask somewhere else for help with this because I find this category of support requests very draining and they keep me from doing more productive things and I am by no means the best person to help you with this. I have never used magit on windows.
