### ISSUE TITLE
Make magit-copy-buffer-revision work also in magit-log-mode

### ISSUE THREAD

**Issue by lelit** [magit/magit#4471]
Is there a particular reason why `M-w` does not currently work in `magit-log-mode`?

If so, could it emit a _beep_ (or some other visual indication, of course) when it cannot copy the hash? That would be nice, because in a couple of occasion I used it on the long log window, and actually yanked a previously copied hash, the wrong one, i.e. not the one I supposed to have copied with `M-w` there.

**Comment by tarsius** [comment]
What revision do you expect it to store? For the commit at point you can use `C-w`.

Otherwise which revision would expect to be stored for, say, `git log --all`?

**Comment by lelit** [comment]
Yes, `C-w` does the job, thank you.
For some reason, I never met `magit-copy-section-value` before, probably because the name isn't so evocative...
