### ISSUE TITLE
Allow setting of environment variables and/or extra commands to run before magit runs git

### ISSUE THREAD

**Issue by david-greene-cb** [magit/magit#4473]
My workpace has various git hooks that rely on environment variables to work.  I often run Emacs from a place where those environment variables are not set (TRAMP is typical).  Therefore, many of magit's commands fail because the environment variables are not set and the git hooks fail.

One way to do this would be to prepend the git command with some string:

`$string git ...`

Where $string could be something like `env <set-my-vars>`.

This could be used to allow arbitrary pre-executed commands if string is something like `<command>; ` or `<command> &&`.

In order to limit shooting oneself in the foot, an alternative would be a configuration that lets the user define environment variables that will be set when magit runs git.

I don't need the ability to set different values for different git commands, but maybe others might so that's something to consider.

**Comment by tarsius** [comment]
#4474
