### ISSUE TITLE
Autostash is not enabled by default 

### ISSUE THREAD

**Issue by realcomplex** [magit/magit#4475]
The documentation for rebasing suggests that the `--autostash` option is enabled by default for rebasing. However, this doesn't seem to be the case anymore (since the switch to transient?). Instead, I saved the option by enabling and saving it (`C-x C-s` in transient). Unless I am mistaken, I would suggest enabling the option by default, or adapting the documentation.

Thanks for a fantastic package!

**Comment by tarsius** [comment]
Thanks!
