### ISSUE TITLE
Consider adding support for reversing `clone --single-branch`

### ISSUE THREAD

**Issue by aspiers** [magit/magit#4480]
(This is definitely low priority, and much weaker than a normal feature request - it's more like a request to briefly consider whether a small new feature would make sense, but I'm not sure if it would.)

A while back I submitted #4197 which added the ability to do a `git fetch --unshallow`, with the intention of converting a shallow clone into a normal one.  The main motivation for this was being able to set [`straight-vc-git-default-clone-depth`](https://github.com/raxod502/straight.el/blob/1e27b0590df77a5d478970ca58fd6606971692f5/straight.el#L2434-L2445) to `10` to avoid full clones of the many emacs packages I use, and then later for selected packages which I want to hack on, use `--unshallow` to fetch the full history.

However, it turns out that `fetch --unshallow` is not sufficient to do the job, because with the above variable setting, [`straight.el` also clones with the `--single-branch` option](https://github.com/raxod502/straight.el/blob/1e27b0590df77a5d478970ca58fd6606971692f5/straight.el#L2449-L2459), which results in the remote being configured 

    fetch = +refs/heads/master:refs/remotes/origin/master

Therefore `fetch --unshallow` will fail to fetch other branches.  The way to widen the fetch is of course to [reconfigure the refspec to use a wildcard](https://stackoverflow.com/questions/6802145/how-to-convert-a-git-shallow-clone-to-a-full-clone#comment38918620_17937889).

So I'm wondering if there would be a nice way of extending magit to allow this reconfiguration?

Quite possibly the answer is "this is way too specific a use case, since the user would need to choose the new widened refspec themself".  And that naturally leads on to the question (which I guess is probably a FAQ, but I don't see it listed in the FAQ or wiki) - why doesn't magit have a UI for `git config`?  Is that on the roadmap, or deliberately rejected for some reason?  I can imagine it being extremely useful, but weirdly I could not find any discussion of it based on an admittedly hurried skim of this issue tracker.

**Comment by aspiers** [comment]
Worth noting that

    (setq straight-vc-git-default-clone-depth '(10))

should be a workaround of sorts, as that avoids `--single-branch` in the first place.

**Comment by tarsius** [comment]
> (This is definitely low priority, and much weaker than a normal feature request - it's more like a request to briefly consider whether a small new feature would make sense, but I'm not sure if it would.)

I was on the fence. Ultimately decided to do it because you're not the only user of `straight`.

Anyway, for future "thinking out load" enhancement "requests", please open a discussion of type "Ideas".

**Comment by aspiers** [comment]
Thanks so much!

> Anyway, for future "thinking out load" enhancement "requests", please open a discussion of type "Ideas".

Will do, thanks for the tip!
