### ISSUE TITLE
magit-dired-am-apply-patches not compatible with Emacs < 27: error with wrong number of arguments

### ISSUE THREAD

**Issue by pierre-rouleau** [magit/magit#4498]
The `magit-dired-am-apply-patches` command fails in Emacs < 27.

It passes 5 arguments to `dired-get-marked-files` as is available in Emacs ≥ 27, bit not in Emacs 26 and before. In Emacs 26 the ERROR argument (whose value is t in the code) is not available.  The byte compiler complain with a warning and the code generates the following error:

```
Eval error ***  Wrong number of arguments: (0 . 4), 5
```

The culprit code is the following:

```lisp
;;;###autoload
(defun magit-dired-am-apply-patches (repo &optional arg)
  "In Dired, apply the marked (or next ARG) files as patches.
If inside a repository, then apply in that.  Otherwise prompt
for a repository."
  (interactive (list (or (magit-toplevel)
                         (magit-read-repository t))
                     current-prefix-arg))
  (let ((files (dired-get-marked-files nil arg nil nil t)))
    (magit-status-setup-buffer repo)
    (magit-am-apply-patches files)))
```
I'm not familiar enough with Magit at the moment to submit a fix, but I assume the course of action would be to check Emacs version, pass only the first 4 arguments on Emacs < 27 and manually detect that nothing got selected and raise an error manually then.

**Comment by kyleam** [comment]
Thanks for the report.
