### ISSUE TITLE
Bug: magit-branch-adjust-remote-upstream-alist doesn't work as expected

### ISSUE THREAD

**Issue by chasecaleb** [magit/magit#4508]
It seems like `magit-branch-adjust-remote-upstream-alist` no longer works like it used to, possibly related to commit 5e734c02 or b6751568 given how recent they are. It's possible that I'm imagining things and it never worked the way I expected, though.

**Reproduction**
1. Clone a fresh repo: e.g. `M-x magit-clone RET` => url => `git@github.com:magit/magit.git` => `/tmp/magit` => answer `y` for prompt `Set 'remote.pushDefault' to "origin"?`
2. Open magit status buffer for the repo
3. Create branch: `bc` => starting at: `master` => name for new branch: `asdf`
4. Show branch variables: `b` => `branch.asdf.merge` and `branch.asdf.remote` show `unset`, whereas I expect them to be `branch.asdf.merge = refs/heads/master` and `branch.asdf.remote = origin`.

---
**Relevant config:**
* Magit version: 1e40d002 (master a week ago)
* Git config: `branch.autoSetupMerge` is not set at any level (so it defaults to `true`)
* Magit config:
    ```elisp
    (setq magit-branch-prefer-remote-upstream '("master" "main"))
    ;; I don't think adjust-remote-upstream-alist is relevant, but just in case this is what I use.
    ;; However I get the same behavior with this set to nil as well.
    (setq magit-branch-adjust-remote-upstream-alist '(("origin/master" . ("master" "main"))
                                                      ("origin/main" . ("master" "main"))))
    ```

**Comment by tarsius** [comment]
> I don't think adjust-remote-upstream-alist is relevant

Did you mean to say "I don't think `magit-branch-prefer-remote-upstream` is relevant"?

**Comment by tarsius** [comment]
I get `refs/heads/master` and `.`, which is the expected result. These don't get set for you because `branch.autoSetupMerge=true` is a stupid default. Set `branch.autoSetupMerge=always` instead.

> - true — automatic setup is done when the starting point is a remote-tracking branch
> - always —  automatic setup is done when the starting point is either a local branch or remote-tracking branch

`magit-branch-adjust-remote-upstream-alist` only has an effect when creating a local branch from a **remote feature branch**, but in this example you create a local branch from the **local mainline branch**.

**Comment by chasecaleb** [comment]
> > I don't think adjust-remote-upstream-alist is relevant
> 
> Did you mean to say "I don't think `magit-branch-prefer-remote-upstream` is relevant"?

No, I meant what I originally said because (like you confirmed in the next comment) I didn't think it was relevant when creating from a local branch.

> These don't get set for you because branch.autoSetupMerge=true is a stupid default. Set branch.autoSetupMerge=always instead.

Ah ha, that makes sense. That was my issue, confirmed.
