### ISSUE TITLE
magit waits (indefinitely) for ssh passhrase without prompting for it

### ISSUE THREAD

**Issue by walkermalling** [magit/magit#4509]
(1) Expected Behavior: When I push to a remote, I expect magit to prompt me for my ssh passphrase
(2) Observed Behavior: the magit process "hangs", waiting for a passphrase it never receives. Opening the `magit-process` buffer shows:
```
Pushing to <remote>
Enter passphrase for key '/path/to/key':
```
(3) Repro: set up a git remote using ssh (in my case, github) and run push.

Additional info:

Magit version: 2.90.1
Git 2.31.1
Emacs 27.2
NixOS 21.05

This repro works on my machine with a clean emacs with only magit installed. I can verify this because I use a nix expression to build emacs. 

Ass far as ssh-agent, I've re evaluated it and added the key in question, but it has no effect on magit's behavior. 

Running debug-on-error has no effect because no error is thrown. 

There have been some historical tickets that seem related (https://github.com/magit/magit/issues/255), but have been specific to Windows. Nevertheless I tried the solutions proposed there, with no resolution.

For what it's worth, the machine I'm working on has been freshly imaged, so there is no prior ssh config that could have been corrupted by various system updates, etc.

**Comment by tarsius** [comment]
> Magit version: 2.90.1

Please update, this release is three years old.

The first entry of `magit-process-password-prompt-regexps` matches the prompt on 2.90.1 and the current release, but only if I add a space at the end of "Enter passphrase for key '/path/to/key':". Is there a space at the end of the actual prompt? If not, try modifying the regexp.

**Comment by walkermalling** [comment]
Thanks, that fixed it. For anyone reading this with a similar problem, I was pulling in magit from nixos' melpaStable fetcher; switching to melpaUnstable got me `20210519.2015` and fixed the problem.
