### ISSUE TITLE
"Cannot determine Magit's version" message with straight.el

### ISSUE THREAD

**Issue by fredericgiquel** [magit/magit#4511]
When magit is installed with `straight.el`, the following message is displayed at magit startup :

```
Cannot determine Magit’s version (error "/home/fred/.emacs.d/straight/build/magit/magit.elc" repo static elpa dirname hash)
```
# How to reproduce

- Use the following `init.el`

```elisp
;; Bootstrap straight
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; Install magit
(straight-use-package 'magit)
```

- `M-x magit-status` on a git repository
- Check `*Messages*` buffer

# Other informations

- Magit version : last commit from github
- Emacs version : 27.1 from Debian
- The problem seems to have been introduced by commit d173de73e96e207d4ba3821e1d720c8d81f6bafb

**Comment by tarsius** [comment]
Probably works now ...

**Comment by fredericgiquel** [comment]
The fix works with Emacs 28. But unfortunaly, the problem persists with Emacs 27.

**Comment by tarsius** [comment]
@fredericgiquel Exact same error?

@raxod502 Can I use `straight` from an alternative location, so that I can avoid having to move my existing .emacs.d out of the way first. Didn't see anything in the docs.

**Comment by fredericgiquel** [comment]
Yes. Exact same error. 
![Capture d’écran de 2021-09-23 21-40-12](https://user-images.githubusercontent.com/17704127/134573294-e05321de-5d18-419c-8a4c-127c86b78dfe.png)

**Comment by fredericgiquel** [comment]
I think I better understand the cause of the error.

Before d173de7 commit, `locate-library` was called with "magit.el" argument and always returns the path for `magit.el` in the build directory of `straight`.
Now, `(locate-library "magit")` returns :
- "/home/fred/.emacs.d/straight/build/magit/magit.elc" with Emacs 27
- "/home/fred/.emacs.d/straight/build/magit/magit.el" with Emacs 28

According to `locate-library` documentation, the `load-suffixes` variable is used to determine which file extensions to search. So replacing 
```elisp
(setq toplib (locate-library "magit"))
```
by
```elisp
(let ((load-suffixes (delete ".elc" load-suffixes)))
        (setq toplib (locate-library "magit")))
```
fixes the error with `straight` installation of `magit` (at least in my case). And I think it should work with "magit.el.gz" installation.

**Comment by tarsius** [comment]
Thanks!

**Comment by raxod502** [comment]
> Can I use straight from an alternative location, so that I can avoid having to move my existing .emacs.d out of the way first. Didn't see anything in the docs

Yeah, you can. In particular you should be able to set `straight-base-dir` (defaults to `user-emacs-directory`) before running the bootstrap snippet. Unfortunately, it looks like this isn't documented at present, so I filed https://github.com/raxod502/straight.el/issues/852 accordingly.

**Comment by tarsius** [comment]
Thanks!

**Comment by drcxd** [comment]
Hello, I found a similar issue.:

`magit-version` does not work and report the error message:

```
Cannot determine Magit’s version (error "d:/emacs_home/.emacs.d/straight/build/magit/magit.el" repo static elpa dirname hash)
```

This message also shows when the first time `magit` is invoked.

My emacs version is 29.4, straight version is
```
prerelease (HEAD -> master, origin/master, origin/develop, origin/HEAD) 88e574a 2024-05-23
```

I am using Emacs on Windows.

The issue can be reproduced using the same procedure in the original post.

**Comment by centuryx476** [comment]
> Hello, I found a similar issue.:
> 
> `magit-version` does not work and report the error message:
> 
> ```
> Cannot determine Magit’s version (error "d:/emacs_home/.emacs.d/straight/build/magit/magit.el" repo static elpa dirname hash)
> ```
> 
> This message also shows when the first time `magit` is invoked.
> 
> My emacs version is 29.4, straight version is
> 
> ```
> prerelease (HEAD -> master, origin/master, origin/develop, origin/HEAD) 88e574a 2024-05-23
> ```
> 
> I am using Emacs on Windows.
> 
> The issue can be reproduced using the same procedure in the original post.

I'm in the exact same boat as you.
Platform: Windows
Emacs: 29.4

I get the exact same error when typing magit-version and it remains in the "Messages" buffer. 
Any work around ?

**Comment by tarsius** [comment]
This is not an error, it is a warning.

In a few days I'll start suppressing this warning when Magit is being loaded. Until then you will just have to ignore it.

In a future step I'll try to add yet another special case to that function, so that it can once more determine the version when using the Straight package manager.
