### ISSUE TITLE
Can't reorder commits in interactive rebase

### ISSUE THREAD

**Issue by JulienPalard** [magit/magit#4525]
Magit version 20211005.1646.

When I'm in the `interactive rebase` mode (`r i`), I want to reorder some commits, I tried `M-p` and `M-n` as the [doc says](https://magit.vc/manual/magit/Editing-Rebase-Sequences.html#Editing-Rebase-Sequences) with no luck.

The doc tells about `git-rebase-move-line-down` but I don't have it, looks like I'm not in `git-rebase` mode, but in `magit-log` / Magic Select mode.

I can `M-x git-rebase-mode` here, so `git-rebase-move-line-*` do appear, and keys are properly bound, but when hitting `M-n` or `M-p` I get `Args out of range: 0, 1`.

**Comment by kyleam** [comment]
> looks like I'm not in git-rebase mode, but in magit-log / Magic Select mode.

`magit-rebase-interactive` (`ri`) takes the commit at point as the bottom edge (inclusive) of the set of commits to rebase.  If called without a commit at point, it will throw the user into a `magit-log-select-mode` buffer and ask them to specify a commit.  The `git-rebase-mode` buffer comes after that.

Do you think that's what you're observing?

If not, please point to a public repo and provide a recipe, including a description of where point is when `magit-rebase-interactive` is invoked, that triggers the issue on your end.

**Comment by JulienPalard** [comment]
> `magit-rebase-interactive` (`ri`) takes the commit at point as the bottom edge (inclusive) of the set of commits to rebase.

Ohhhh I got it.

> If called without a commit at point, it will throw the user into a `magit-log-select-mode` buffer and ask them to specify a commit. The `git-rebase-mode` buffer comes after that.

It make sense now, magit is asking me the argument to give to `git rebase -i` while I expected `C-x g r i` to behave as `git rebase -i` with no arguments.

Is there a way to get the equivalent of `git rebase -i` (without arguments)? If not, I have a suggestion: make the magit-log-select-mode point to the last pushed commit of the tracked remote, so `git rebase -i` could be done as `C-x g r i C-c C-c` instead of having to scroll the right amount in the commit list?

> Do you think that's what you're observing?

Yes! And I understand what I'm observing now, and I'm able to make it work! Thank you!!

The visual similarity between magit-log-select-mode and the git rebase mode is understandable (I mean I don't know how to make them look different... I'm bad at UI/UX) but to one like me using a lot of argumentless `git rebase -i` it's misleading.
