### ISSUE TITLE
Git push doesn't work on Windows when using plink as ssh client

### ISSUE THREAD

**Issue by markokocic** [magit/magit#4527]
I am using the latest magit version from melpa on Windows.

When trying to push my commit from magit to the remote repository, I got an error from git subprocess that I am no authorized to push to the repository.

Pushing the same commit using git command line works.
I am using Windows and Git is configured to use `plink` as ssh client using environment variable.

GIT_SSH=plink

When pushing using command line, I don't get any prompts for authentication, since plink uses putty connection information for the host, where private key is configured.

**Comment by tarsius** [comment]
Please follow the advice in https://github.com/magit/magit/wiki/Pushing-with-Magit-from-Windows.
