### ISSUE TITLE
Donate/cherry-pick from detached HEAD

### ISSUE THREAD

**Issue by xeruf** [magit/magit#4534]
I am currently on a detached HEAD and would like to cherry-pick the HEAD commit onto another branch, but that seems to be impossible as all 'Apply Elsewhere'-commands want to modify the current branch. There should be a subcommand that simply cherry-picks onto elsewhere, not modifying the current branch.

The only solution I currently see is switching to that branch and then cherry-picking via 'A A', which is cumbersome as I have to re-enter the commit hash of the detached HEAD.

**Comment by tarsius** [comment]
`magit-cherry-donate` can now be used when the head is detached.
