### ISSUE TITLE
In git-commit.el, search commit messages from history with M-s and M-r

### ISSUE THREAD

**Issue by danielmartin** [magit/magit#4537]
When committing with Magit, you can M-p and M-n to cycle and reuse previous and next commit messages from history. It would be a good idea to also bind M-s and M-r to a couple of new commands that perform a history search forwards and backwards, respectively. This new feature would avoid having to manually cycle until you get the commit message you want.

See similar commands `log-edit-comment-search-backward` and `log-edit-comment-search-forward` from vc-mode.el.

**Comment by tarsius** [comment]
Pushed to the `message-search` branch. Please give it a try.

I am not using `M-s` and `M-r` because IMO the global bindings of these keys should not be shadowed. Any better ideas than `C-c M-p` and `C-c M-n`?

**Comment by tarsius** [comment]
We can still change the key bindings, though preferably sooner than later.

**Comment by danielmartin** [comment]
Jonas Bernoulli ***@***.***> writes:

> Pushed to the `message-search` branch. Please give it a try.

Thanks for implementing this!  I checked it out and it works well.

>
> I am not using `M-s` and `M-r` because IMO the global bindings of these keys should not be shadowed. Any better ideas than `C-c M-p` and `C-c M-n`?

OK, makes sense.  I see C-c M-s is already in use, so C-c M-n is the
closest one that is still mnemonic.
