### ISSUE TITLE
Allow magit-remote-unshallow

### ISSUE THREAD

**Issue by chuxubank** [magit/magit#4541]
https://github.com/magit/magit/blob/2bd1d823ddebb0cfef31a3338916aaef9ae01660/lisp/magit-remote.el#L91

Why there's a `7` at the beginning and is it intended or just a typo?
I could't find the shortcut key to call this function either.

**Comment by tarsius** [comment]
Certain transient popups hide some of their suffix commands by default. These additional suffixes can be [enabled interactively](https://magit.vc/manual/transient/Enabling-and-Disabling-Suffixes.html). TL;DR Enter the transient as usual and type <kbd>C-x l</kbd>.

<sub>This is a [canned response](https://help.github.com/en/github/writing-on-github/working-with-saved-replies); it may not apply 100% in this case.</sub>

**Comment by chuxubank** [comment]
Thanks for the explanation!
