### ISSUE TITLE
magit-log-maybe-update-blob-buffer broken since commit 19ef14cc81fdcc809e73851cf341e7e295110c84

### ISSUE THREAD

**Issue by nickalcock** [magit/magit#4552]
With any magit version postdating this commit, magit-log-maybe-update-blob-buffer fails. It calls magit-blob-visit with BLOB-OR-FILE and LINE parameters:
```
(magit-blob-visit (list (magit-rev-parse rev)
                        (magit-file-relative-name
                         magit-buffer-file-name))
                  (line-number-at-pos))
```

but since commit 19ef14cc81fdcc809e73851cf341e7e295110c84, magit-blob-visit has taken only BLOB-OR-FILE on the grounds that "`magit-find-file' takes care of preserving the location now". This reasoning seems flawed in this case: we're not trying to load the location we used to have it open at, after all. Maybe we need a specialized version of magit-blob-visit for this one use case -- I hacked that up and it seemed to work, but this feels ugly to me so maybe there's a better way.

**Comment by nickalcock** [comment]
You missed a bit!

```
From c2b0637edb014c060e8513be8f09aeca9e6d163e Mon Sep 17 00:00:00 2001
From: Nick Alcock <nick.alcock@oracle.com>
Date: Tue, 7 Dec 2021 21:16:58 +0000
Subject: [PATCH] Drop remaining refs to the two-arg magit-blob-visit

---
 lisp/magit-log.el | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/lisp/magit-log.el b/lisp/magit-log.el
index bc99fa74..663a4b47 100644
--- a/lisp/magit-log.el
+++ b/lisp/magit-log.el
@@ -34,7 +34,7 @@
 (require 'magit-core)
 (require 'magit-diff)
 
-(declare-function magit-blob-visit "magit-files" (blob-or-file line))
+(declare-function magit-blob-visit "magit-files" (blob-or-file))
 (declare-function magit-insert-head-branch-header "magit-status"
                   (&optional branch))
 (declare-function magit-insert-upstream-branch-header "magit-status"
```

**Comment by tarsius** [comment]
I was wondering why the byte-compiler never complained... here we have the reason. Seems I have to somehow include `check-declare` in the build process.

Thanks again!
