### ISSUE TITLE
During make: git-commit.el:118:1: Error: Cannot open load file: No such file or directory, dash

### ISSUE THREAD

**Issue by avatar-lavventura** [magit/magit#4553]
I am following  [Installing from the Git Repository](https://magit.vc/manual/magit/Installing-from-the-Git-Repository.html#Installing-from-the-Git-Repository). But during `make`, I am having following error:  `git-commit.el:118:1: Error: Cannot open load file: No such file or directory, dash`

```
$ git clone https://github.com/magit/magit.git ~/.emacs.d/site-lisp/magit
$ cd ~/.emacs.d/site-lisp/magit
$ echo "LOAD_PATH  = -L ~/.emacs.d/site-lisp/magit/lisp
LOAD_PATH += -L ~/.emacs.d/site-lisp/dash
LOAD_PATH += -L ~/.emacs.d/site-lisp/transient/lisp
LOAD_PATH += -L ~/.emacs.d/site-lisp/with-editor" > config.mk
$  make
make[1]: Entering directory '/home/alper/.emacs.d/site-lisp/magit/lisp'
Compiling git-commit.el

In toplevel form:
git-commit.el:118:1: Error: Cannot open load file: No such file or directory, dash
make[1]: *** [Makefile:79: git-commit.elc] Error 1
make[1]: Leaving directory '/home/alper/.emacs.d/site-lisp/magit/lisp'
make: *** [Makefile:74: lisp] Error 2
```

How could I fix it? Did I do something wrong during installation?

**Comment by tarsius** [comment]
You shouldn't even have to set `LOAD_PATH`. Try with `config.mk` removed.

**Comment by avatar-lavventura** [comment]
Thanks. Now I am getting following error :-( Please not I have installed `sudo apt install libgit2-dev`
 
```
In toplevel form:
magit-libgit.el:54:1: Error: Cannot open load file: No such file or directory, libgit
make[1]: *** [Makefile:79: magit-libgit.elc] Error 1
make[1]: Leaving directory '/home/alper/.emacs.d/site-lisp/magit/lisp'
make: *** [Makefile:74: lisp] Error 2
```

**Comment by kyleam** [comment]
> magit-libgit.el:54:1: Error: Cannot open load file: No such file or directory, libgit

I believe you need to either point to libgit.el  (https://github.com/magit/libegit2) or set `BUILD_MAGIT_LIBGIT` to false.

**Comment by avatar-lavventura** [comment]
Please note that clean installation does not give the `magit-libgit.el:54:1: Error: Cannot open load file: No such file or directory, libgit` error.

**Comment by kyleam** [comment]
> Please note that clean installation does not give the `magit-libgit.el:54:1: Error: Cannot open load file: No such file or directory, libgit` error.

I suspect that that has nothing to do with whether it's a clean installation and instead relates to a change from earlier today: 895fd3f8 (make: Default to no libgit support, 2021-12-16).
