### ISSUE TITLE
(wrong-type-argument sequencep t) while trying to commit with hooks disabled

### ISSUE THREAD

**Issue by bbigras** [magit/magit#4563]
I'm trying to do a commit while disabling hooks (-n).

`C-x g` -> `c`
When I type `-n` the first time, "disable hooks" is not highlighted. It does if I try again, but when I hit `c` I get this error:

```
Debugger entered--Lisp error: (wrong-type-argument sequencep t)
  magit-run-git-async(("commit" (t)))
  magit-run-git-with-editor("commit" (t))
  magit-commit-create((t))
  funcall-interactively(magit-commit-create (t))
  command-execute(magit-commit-create)
```

Magit 20211216.1915 [>= 3.3.0], Git 2.34.0, Emacs 29.0.50, gnu/linux

**Comment by tarsius** [comment]
Try updating `transient`.

**Comment by bbigras** [comment]
to master? I'm already on 20211208.1819.

**Comment by tarsius** [comment]
I think there is good chance that the issue goes away if you:

1. Uninstall magit and transient.
2. Exit Emacs.
3. Restart Emacs.
4. Reinstall magit and transient.

Please give it a try.

**Comment by tarsius** [comment]
The backtrace implies that `(transient-args 'magit-commit)` returned `(t)` when it should have returned `("-n")`. Quickly looking through the path the value should have taken, this implies that this some somehow returned `t` instead of `"-n"`:

```elisp
(cl-defmethod transient-infix-read ((obj transient-switch))
  "Toggle the switch on or off."
  (if (oref obj value) nil (oref obj argument)))
```

But of course its possible that somewhere something took the wrong path. I would debug this using debug statements to check if things have the values I expect but since I cannot reproduce the issue it won't do any good if I do that here. You can start adding debug statements to the above method (what does `(oref obj argument)` return?) and maybe `transient-args`.

**Comment by tarsius** [comment]
It is also possible that for some reason the `transient.el` that ships with emacs is earlier on the load-path than the version you installed using package.el (so check that) and that the older version in emacs has a bug. (I plan to update the bundled version soon, but need to do a few things first.)

**Comment by bbigras** [comment]
I did some tests.

- I don't have the problem if I only use magit
- I don't have the problem if I remove [pomm](https://github.com/SqrtMinusOne/pomm.el) (which also use transient I think).

**Comment by tarsius** [comment]
Pomm redefines the function I mentioned for `transient-switch`:

```elisp
(cl-defmethod transient-infix-read ((_ transient-switch))
  "Toggle the switch on or off."
  (setq pomm-reset-context-on-iteration-end
        (not pomm-reset-context-on-iteration-end)))
```

The intention probably was to do it for `pomm--set-context-on-iteration-end-infix ` instead.

@SqrtMinusOne please fix that. While you are at it you might also want to increase the minimal `transient` version and adapt to the changes in the names of `transient`'s define macros.

**Comment by SqrtMinusOne** [comment]
Fixed that, the issue seems to have disappeared with the new version.

Sorry for the inconvenience, and thanks for tracking this!

**Comment by bbigras** [comment]
It seems to work now.

Thank you very much everyone!
