### ISSUE TITLE
Allow a size limit for hunk refining?

### ISSUE THREAD

**Issue by DarwinAwardWinner** [magit/magit#4564]
I was recently working on a diff where one hunk in particular was many lines, and each time I scrolled in or out of that hunk, emacs would freeze for around 10 seconds while magit did the word refining of the hunk. I was able to solve this by turning off hunk refining entirely until I was done working with that diff, but it would be nice if I could set a size threshold and have magit only refine hunks smaller than this threshold. If you think this is a worthwhile feature, I'd be happy to try implementing it and submitting a PR.

Also, I'm not entirely sure how "size" should be defined in this context. Lines changed? Word count or changed lines? Lines/words added/removed? Something else?  

(In case you're curious, the offending hunk was a large section of bullet point outline text being replaced by the same text rewritten as prose paragraphs.)

**Comment by tarsius** [comment]
I think it would be hard to come up with a heuristic that is correct most of the time and also does not add an additional slowdown. I think I would rather have to turn off refinement once in a while than to always pay a price in speed and/or code complexity.

**Comment by DarwinAwardWinner** [comment]
Is it really that slow/expensive to determine the number of lines in a hunk? Certainly counting words would be more expensive, but lines seems like it should be easy enough. As for the heuristic, I'm hoping something simple like "100 lines" is good enough. I think once you've hit 100 lines or so, the word-level diff probably becomes unimportant, and as long as it's fast enough at 100 lines, then everything works smoothly.

**Comment by tarsius** [comment]
> Is it really that slow/expensive to determine the number of lines in a hunk?

No, but if that is the condition then I am not gonna turn on that feature locally or by default.

Since you really want this please go ahead but also try to keep it self-contained, so that any later large-scale, performance-motivated refactoring is not complicated by it.

**Comment by DarwinAwardWinner** [comment]
Ok, I'll have a stab at implementing it soon, and if I think it's sufficiently clean and self-contained I'll submit a PR. Thanks for being willing to consider this.
