### ISSUE TITLE
[bug] `magit-log-graph` face broken

### ISSUE THREAD

**Issue by cstby** [magit/magit#4570]
I'm on `Magit v3.3.0-73-g03f495f3, Git 2.30.2, Emacs 27.1, gnu/linux`. It appears that the face `magit-log-graph` is not working as expected. I can customize the face, but the log graph does not appear to use this face.

### Steps to Reproduce
- Open a magit status buffer from a local git repo.
- Show the current log with `l l`.
- Call the interactive command `list-faces-dislpay`
- Find `magit-log-graph` and follow the link to the customization window.
- At the bottom of the window, hit the `choose` button to select a new foreground color for the `magit-log-graph` face.
- Choose any color different from the current one.
- Hit `Apply`.

### Expected Result
- The graph in the the magit log should use the newly selected foreground color.

### Actual Result
- The graph color remains unchanged.

**Comment by kyleam** [comment]
The `magit-log-graph` face is only in effect when the `--color` and `--graph` switches are specified:

https://github.com/magit/magit/blob/03f495f351d6e622143e4628681019df1313a5f2/lisp/magit-log.el#L1190-L1198

**Comment by cstby** [comment]
Ah, thank you for that clarification. Closing this issue.
