### ISSUE TITLE
stash [drop] does not work

### ISSUE THREAD

**Issue by hbsd** [magit/magit#4571]
Hi
I'm trying to drop (remove) a stash in magit with: `z k`

![1](https://user-images.githubusercontent.com/78821889/147826238-c598cbb1-5323-4691-ad67-3e0e4aa4c145.png)

But when I select a stash and hit Enter, the following message is displayed:
`Wrong type argument: stringp` (please see the picture)

![2](https://user-images.githubusercontent.com/78821889/147826366-d8e5b9d4-9577-4571-a618-06108753ceb9.png)

It should be noted that when I use the git itself, the commands works without any problems: `git stash drop stash@{0}`

![3](https://user-images.githubusercontent.com/78821889/147826609-fbd2a6df-152e-476f-a702-3a4b6d92517f.png)

All other stash commands works great on magit except this.

Thanks. I'd appreciate for any help. Thank you for this wonderful software.

My softwares version:

**Emacs version: 27.1
Magit version: 3.3.0**

**Comment by kyleam** [comment]
Thanks for the report.  This is Helm-specific.  I can trigger the error with the latest Magit (03f495f3) and Helm (c010f5ee).

<details>
<summary>backtrace</summary>

```
Debugger entered--Lisp error: (wrong-type-argument stringp ("stash@{0} On main: 5f1ee1d Handle gpg.[ssh].progra..."))
  string-match("^\\([^ ]+\\) \\(.+\\)" ("stash@{0} On main: 5f1ee1d Handle gpg.[ssh].progra..."))
  (and choice (string-match "^\\([^ ]+\\) \\(.+\\)" choice) (substring-no-properties (match-string 1 choice)))
  (let* ((atpoint (magit-stash-at-point)) (default (and atpoint (concat atpoint (magit-rev-format " %s" atpoint)))) (choices (mapcar #'(lambda (c) (let* (... ... ... ... ...) (let ... ...))) (magit-list-stashes "%gd%x00%s"))) (choice (magit-completing-read prompt choices nil t nil nil default (car choices)))) (and choice (string-match "^\\([^ ]+\\) \\(.+\\)" choice) (substring-no-properties (match-string 1 choice))))
  magit-read-stash("Drop stash")
  (let ((helm-comp-read-use-marked t)) (magit-read-stash "Drop stash"))
  (if it (magit-confirm 'drop-stashes nil "Drop %i stashes" nil it) (let ((helm-comp-read-use-marked t)) (magit-read-stash "Drop stash")))
  (let ((it (magit-region-values 'stash))) (if it (magit-confirm 'drop-stashes nil "Drop %i stashes" nil it) (let ((helm-comp-read-use-marked t)) (magit-read-stash "Drop stash"))))
  (list (let ((it (magit-region-values 'stash))) (if it (magit-confirm 'drop-stashes nil "Drop %i stashes" nil it) (let ((helm-comp-read-use-marked t)) (magit-read-stash "Drop stash")))))
  call-interactively(magit-stash-drop nil nil)
  command-execute(magit-stash-drop)
```

</details>

I haven't taken a closer look yet, though I pretty sure it has to do with the functionality added in 53f7cfe6 (magit-{tag-delete,stash-drop}: Supports Helm's marked candidates, 2020-08-29).  I'll need to check, but assuming this issue wasn't there at the time it was added, then it's likely the result of a change on Helm's side.

---

What's your Helm version?

**Comment by kyleam** [comment]
I said:

> I'll need to check, but assuming this issue wasn't there at the time it was added, 

It wasn't...

> then it's likely the result of a change on Helm's side.

... but it's on our side.  The error starts with 7f7c3aa4 (magit-read-stash: Show the commit messages while reading, 2020-10-20).

**Comment by kyleam** [comment]
I'd say we should just drop the `helm-comp-read-use-marked` binding.  I'll plan to merge the commit at km/stash-no-helm-multi to master tomorrow.
