### ISSUE TITLE
Add hint for `K` "Untrack file" command

### ISSUE THREAD

**Issue by cstby** [magit/magit#4572]
Magit supports untracking files, but there is no hint in the "popup of popups" for this command, which can be called with `K`.

In situations where a user has updated their .gitignore file and needs to untrack the files from their repo, they are likely to look at the "popup of popups" for this option. Is the omission of this command intentional?

**Comment by tarsius** [comment]
The "popup of popups" doesn't list all top-level bindings.

It lists the popups (and some other important commands) in "Transient and dwim commands", some essential commands in "Essential commands" and apply commands in "Applying changes".

One could argue that `magit-file-untrack` fits in the last category, but I it seems to me to make sense to not overload that group.  If this was the only command command with a top-level binding that isn't listed in the dispatcher, then I would probably just add it anyway.

Look at the definition of `magit-dispatch`, it contains comments mentioning the commands that are not shown.  Fitting all those (in the existing groups) would be harder.

This does not include commands that have top-level bindings where that binding is not a *alphabetic* binding, e.g. `C-c C-w` for `magit-browse-thing`.  If we include *all* the alphabetic bindings shouldn't also include all the non-alphabetic bindings too; after all they are *less* discoverable.

So the dispatcher provides only a curated subset of the available commands and to get a list of all the available bindings one can use the command that can be used for that purpose in any buffer: `describe-bindings` (`C-h b`).

@kyleam, do you agree with that approach in general? Are there any commands you would add to the dispatcher?

Oh! We could make use of transient levels to give users a choice.

**Comment by cstby** [comment]
Thanks for referencing `magit-dispatch`. I see that not including all commands was deliberate, and I understand your reasoning.

> If we include all the alphabetic bindings shouldn't also include all the non-alphabetic bindings too; after all they are less discoverable.

This is a very good point. One consideration is that the popup currently _appears_ to be inclusive of all non-navigational alphabetic bindings. Making every command discoverable may not be feasible, but you also want to ensure that you're setting user expectations appropriately.

As a user, I wanted to untrack a file, but I didn't know whether magit could do that or which magit command to use. I worked through this situation by googling "magit untrack file", which led me stack exchange where I found that my answer. It didn't take long. I was mildly surprised that the popup didn't include a hint for `K`.  If you consider that flow acceptable, then there's nothing else to do here.

**Comment by kyleam** [comment]
@tarsius:
> @kyleam, do you agree with that approach in general?

Yes, I agree.  While the dispatch is certainly helpful for discoverability, I don't think we should aim for it be the sole place users go to look for functionality.  `describe-bindings` helps here, as you mentioned. So does `describe-mode` and `command-apropos` (searching for, say, "magit untrack").  There's also the info manual of course, where for example `i` (`Info-index`) would help discover `magit-file-untrack` (though I know some would prefer a web search at that point).

> Are there any commands you would add to the dispatcher?

Nothing jumps out at me.

**Comment by tarsius** [comment]
> `describe-bindings` helps here, as you mentioned. So does
> `describe-mode` and `command-apropos`

And `describe-mode` even has a binding in the dispatcher.
