### ISSUE TITLE
magit-list-refs should be case-sensitive to support `head` branch

### ISSUE THREAD

**Issue by blackgnezdo** [magit/magit#4575]
I work in a repo with main branch named `head` (yes, lowercase, no, I didn't choose it). This makes it impossible to set as an upstream in magit. E.g. `b`-`C`-`RET`-`u` refuses to accept `origin/head` despite branch existence. 

I tracked this behavior down to this term 
```
(--remove (string-match-p "\\(\\`\\|/\\)HEAD\\'" it) refs)
```
[here](https://github.com/magit/magit/blob/7d0d7068deff003a02f49fa430153e4611c80175/lisp/magit-git.el#L1694) in `magit-list-refs`. Sadly the behavior of `string-match-p` is dependent on a global and I didn't figure out how to make this case-sensitive. I confirmed I was right by mangling the search string and `head` is happily accepted then.

Could somebody more fluent in elisp fix this?

**Comment by npostavs** [comment]
I guess let-binding `case-fold-search` should do the job?
```elisp
        (let ((case-fold-search nil))
          (--remove (string-match-p "\\(\\`\\|/\\)HEAD\\'" it) refs))
```

**Comment by blackgnezdo** [comment]
It does work (I keep forgetting how terrible dynamic scoping is, thanks for reminding me :)
I used a bit tinier scope, though maybe that's exactly the opposite of what it should be
to improve efficiency?
```patch
--- magit-git.el~	2022-01-05 11:53:18.861975479 -0800
+++ magit-git.el	2022-01-05 16:45:38.337636067 -0800
@@ -1691,7 +1691,9 @@
                                         ((and val (pred listp)) val)))
                                (or namespaces magit-list-refs-namespaces))))
     (if (member format '("%(refname)" "%(refname:short)"))
-        (--remove (string-match-p "\\(\\`\\|/\\)HXEAD\\'" it) refs)
+        (--remove
+	 (let ((case-fold-search nil)) (string-match-p "\\(\\`\\|/\\)HEAD\\'" it))
+	 refs)
       refs)))
```
