### ISSUE TITLE
Add autoload comment to `magit-generate-changelog`

### ISSUE THREAD

**Issue by dalanicolai** [magit/magit#4581]
In my opinion, it shouldn't be necessary to manually load `magit-extra` to get the `magit-generate-changelog` command available.
Currently, when I create a commit, I can not directly use the command (which is desirable for contributing to Emacs).
It is not very important, we can easily autoloadable make it ourselves, but if you agree, then I guess having it directly available would be nice. I hope your policy about biting heads off did not change in the mean time ;)

**Comment by tarsius** [comment]
All the other commands in that file are autoloaded, so it seems this was just an oversight.
