### ISSUE TITLE
Commit title in magit-revision low contrast in dark theme

### ISSUE THREAD

**Issue by bradyt** [magit/magit#4594]
When reviewing a commit in magit, I expect that the commit title will be reasonably easy to scan for, in the "revision" pane I'm scanning as I navigate the magit-log in the other window.

Instead, the commit title for the parent commit is much better at drawing my attention, and I have to refocus my eyes to read the title of the current commit.

![Screen Shot 2022-02-08 at 10 19 15 AM](https://user-images.githubusercontent.com/6107051/153067724-8efadcd0-3831-4c30-9f35-99d594eca99a.png)

I don't think the dark theme is obscure, I'm simply using `(invert-face 'default)`, which has similar results in terminal with `--reverse` or `--eval \"(setq frame-background-mode 'dark) (mapc 'frame-set-background-mode (frame-list))\""`.

Somehow I don't think the commit title is as difficult to read with light background, as follows:

![Screen Shot 2022-02-08 at 12 16 22 PM](https://user-images.githubusercontent.com/6107051/153068824-0ee5334e-87b0-4edc-a4bb-a0f46cbc91ce.png)

In this case, at least the eye can more easily focus on where the commit title is, even if the text itself is still low contrast.

I can't imagine what would be a good way to fix this, but felt it might be helpful to at least file the issue.

**Comment by tarsius** [comment]
I've increased the contrast.
