### ISSUE TITLE
Add face for magit-insert-child-count

### ISSUE THREAD

**Issue by DivineDominion** [magit/magit#4599]
I am experimenting with variable pitch fonts for user interface elements: mode line, tab bar, and magit section headings and file names.

In this process, I noticed that I could easily customize magit faces via `(set-face-attributes FACE-NAME nil :inherit 'variable-pitch)` to get started. This works for `magit-diff-file-heading`, `magit-diff-file-heading-highlight`, `magit-section-heading`, `magit-section-highlight`, and thus I'm almost finished.

Except the child count that is inserted -- when the line is highlighted the child count is styled in the `magit-section-highlight` face, which looks good enough:

![image](https://user-images.githubusercontent.com/59080/153702676-11620af6-fab3-422f-a74f-198464dbc697.png)

But when the line is _not_ highlighted, the child count reverts to default fixed pitch font:

![image](https://user-images.githubusercontent.com/59080/153702576-ce94dedb-9d80-403b-853f-0fe729da260e.png)

From the code it looks like the child count is inserted as plain text without any face:

https://github.com/magit/magit/blob/master/lisp/magit-section.el#L1223-L1242

My suggestion/feature request would be to either add the section heading face or add a new face for this to customize the child count style. 

Wanted to report and discuss this before stomping in with a PR, so what do you think?

**Comment by tarsius** [comment]
I've just add `magit-section-child-count` for this.

I also noticed one place in `forge` where I had to explicitly use that face. There might be other places where something inserts the count itself instead of relying on `magit-insert-child-count` to do it. If you notice any, then let me know.

**Comment by DivineDominion** [comment]
@tarsius I have trouble finding the face name of the un-selected file names in a section, because I can't select the line, since that changes the face at point :)

![image](https://user-images.githubusercontent.com/59080/155571898-ebe77c62-e9d5-44ed-93e2-3c15c25be3d9.png)

What would the non-emboldened, monospaced faces be in this case?

**Comment by tarsius** [comment]
Highlighting can be disabled using `(setq magit-section-highlight-hook nil)`.
