### ISSUE TITLE
add support for GIT_DIR (and GIT_WORK_TREE as well)

### ISSUE THREAD

**Issue by mbunkus** [magit/magit#460]
I'm keeping parts of my `$HOME`in a Git repo. As I don't want to have git think that my whole `$HOME` is a Git repository I've put Git's directory into `$HOME/.config/dot-home.git` (a bare repo).

So whenever I want to work on this I usually use a wrapper script that sets `GIT_DIR` to `$HOME/.config/dot-home.git` and `GIT_WORK_TREE` to `$HOME`. This works nicely.

It would be nice such separations of Git's directory and its working tree were supported by magit. At the moment I can achieve that in several ways, but all of those have their drawbacks:
1. Set both environment variables and start a new Emacs process from that shell.
2. Use a wrapper function around `magit-status` that sets those environment variables before calling `magit-status` and hooking into its quit function in order to un-set those variables.

The first solution is... well... not a solution in my book. It counts as a workaround at best. I don't want to start new processes! It slows me down, requires other kinds of key strokes, I already have Emacs running.

The second solution has a lot of problems as well:
- The environment cannot be made buffer-local because `magit-status` removes all buffer-local variables after creating its buffer.
- All buffers creating from that "modified" `magit-status` buffer (log-edit, log view, branch view, even files opened via `find-file` and friends etc etc) inherit the environment. Unfortunately quitting those buffers doesn't remove them, it only buries them leaving the environment modification alive in more buffers that you might be aware of. This requires killing all of those buffers, otherwise git (and magit by extension) won't work with other non-$HOME repos.
- I have to finish working on that repo completely, killing all buffers from that process, before being able to continue working on any other repository.

This whole scenario isn't limited to `$HOME`. Other situations in which the work tree is not the same dir as Git's dir apply as well.

**Comment by andreas-h** [comment]
Hey, thanks for this, I'd really like to use that piece of code.  However, I have trouble (Emacs 25.2) getting it to work.  When I run `vcsh-link` I get prompted for a repository, but when I choose one, nothing happens (minibuffer closes). Any idea what might go wrong?

**Comment by cpitclaudel** [comment]
Instead of linking and unlinking, the following seems to work mostly fine.  @tarsius, anything deeply wrong with it?

```
(defun ~/magit-process-environment (env)
  "Add GIT_DIR and GIT_WORK_TREE to ENV when in a special directory.
https://github.com/magit/magit/issues/460 (@cpitclaudel)."
  (let ((default (file-name-as-directory (expand-file-name default-directory)))
        (home (expand-file-name "~/")))
    (when (string= default home)
      (let ((gitdir (expand-file-name "~/.dotfiles.git/")))
        (push (format "GIT_WORK_TREE=%s" home) env)
        (push (format "GIT_DIR=%s" gitdir) env))))
  env)

(advice-add 'magit-process-environment
            :filter-return #'~/magit-process-environment)
```

**Comment by tarsius** [comment]
It seems this could work.

I quickly went through all occurrences of `magit-git-executable` and it seems all calls to `git` either get this environment or are somehow involved in determining values to be used in this environment. Except for one, but that was a bug, which I fixed.

**Comment by cpitclaudel** [comment]
Perfect, thanks a lot! :)

**Comment by he-sk** [comment]
With the solution by @cpitclaudel I can work on $HOME from magit but it doesn't show in the output of `magit-list-repositories` even though it is configured in `magit-repository-directories`. Is there a way to fix that?

**Comment by indigoviolet** [comment]
I think it is possible to use https://direnv.net/ to set `GIT_DIR` and `GIT_WORK_TREE`, in combination with https://github.com/purcell/envrc so that this situation can be handled more easily (and correctly: for instance, https://github.com/magit/magit/issues/460#issuecomment-837449105 will only work in $HOME not subdirectories) , but https://github.com/magit/magit/wiki/Don't-set-$GIT_DIR-and-alike means that Magit will prevent this. 

Is there a way to configure Magit not to unset GIT_DIR and GIT_WORK_TREE when loaded? I realize this is a potential footgun .. but perhaps it's worth enabling if you know what you are doing?

**Comment by indigoviolet** [comment]
@tarsius - any thoughts on allowing GIT_DIR/GIT_WORK_TREE https://github.com/magit/magit/issues/460#issuecomment-1180919509? None of the solutions here really work for this situation, and that's really unfortunate because both the dotfiles manager and magit are individually great.

**Comment by yalfg** [comment]
A variation on @cpitclaudel idea, allowing having several bare repos: if a file is not under a normal git repo, check it against an association list of work directories to bare repos. If found, configure the git environment as @cpit

**Comment by yalfg** [comment]
A variation on @cpitcl

**Comment by yalfg** [comment]
A variation on @cpitclaudel idea, supporting several bare repositories. If
a file is not in a normal git repo, check it against a list of bare
repositories work directories. If under one, associate it to the bare repo
in the same way @cpitclaudel did:

```lisp
(setq my/bare-repos
      '(("~/tmp/bare/workdir" . "~/tmp/bare/repo")))

(defun my/magit-bare-repo-env (env)
  "Detect and set the git command environment ENV for a bare repo.
If a file is not inside a normal git repo, check it against a
configured list or bare repository work directories. If it's
under one, associate the file to the configured bare repo by
setting the GIT_DIR and GIT_WORK_TREE environment variables
before running a git command for Magit.
See https://github.com/magit/magit/issues/460.
"
  (unless (vc-call-backend 'Git 'root default-directory)
    (let* ((bare-pair (seq-some
                       (lambda (p)
                         (if (file-in-directory-p default-directory
                                                  (car p))
                             p))
                       my/bare-repos))
           (workdir (car bare-pair))
           (bare-repo (cdr bare-pair)))
      (when bare-pair
        (message "Bare repo, adding to env")
        (push (format "GIT_WORK_TREE=%s" (expand-file-name workdir)) env)
        (push (format "GIT_DIR=%s" (expand-file-name bare-repo)) env))))
  env)

(advice-add 'magit-process-environment
            :filter-return #'my/magit-bare-repo-env)
```

There is still the limitation that a given work directory can only be
associated to a single bare repo, so this will not work for `vcsh`. But for
people fine with a single bare repo for their home directory configuration,
plus the occasional bare repo for other specific need, this could be
enough.

**Comment by astoff** [comment]
FWIW, I used this idea for some time and I now prefer the following variant, where magit gets stuck into the bare repo until you press `C-]` or `C-M-c` to end the recursive edit:

```emacs-lisp
(defun magit-dotfiles ()
  "Magit on dotfiles repo for the duration of a recursive edit."
  (interactive)
  (require 'magit)
  (let ((magit-git-global-arguments
         `(,(substitute-env-vars "--git-dir=$HOME/.dotfiles.git")
           ,(substitute-env-vars "--work-tree=$HOME")
           ,@magit-git-global-arguments)))
    (magit-status "~")
    (recursive-edit)))
```

**Comment by noncog** [comment]
Here's my updated version of @cpitclaudel's solution. This one gets a list of all files/directories being tracked under the current branch of your dotfiles and sets the environment variable when you're in a relevant directory instead of just home. As far as I can tell, it works seamlessly. Now I can finally manage my dotfiles from anywhere.
```lisp
(defun my/magit-process-environment (env)
  "Detect and set git -bare repo env vars when in tracked dotfile directories."
  (let* ((default (file-name-as-directory (expand-file-name default-directory)))
         (git-dir (expand-file-name "~/.dotfiles/"))
         (work-tree (expand-file-name "~/"))
         (dotfile-dirs
          (-map (apply-partially 'concat work-tree)
                (-uniq (-keep #'file-name-directory (split-string (shell-command-to-string
                (format "/usr/bin/git --git-dir=%s --work-tree=%s ls-tree --full-tree --name-only -r HEAD"
                        git-dir work-tree))))))))
    (push work-tree dotfile-dirs)
    (when (member default dotfile-dirs)
      (push (format "GIT_WORK_TREE=%s" work-tree) env)
      (push (format "GIT_DIR=%s" git-dir) env)))
  env)

(advice-add 'magit-process-environment
            :filter-return #'my/magit-process-environment)
```
I'm sure it could be a little more compact. I couldn't get it to work in a more direct manner relying on Magit commands. It lead to wild circular logic. Happy hacking!

**Comment by tarsius** [comment]
I am currently working on something vaguely related.

So for now, just a question: do you actually have to set `GIT_WORK_TREE`? Aren't you just doubling down on the worktree that would be used anyway? That's relevant because, unlike `magit-gitdir`, `magit-top-level` does not take the respective variable into account.

**Comment by tarsius** [comment]
> I am currently working on something vaguely related.

Before you get too excited about that, I would add that I am working on caching the location of the gitdir and worktree for performance reasons, which may *break* the advices above. But I plan for the caches to be optional, so maybe all that means that you won't be able to use them if you also need to set these variables.

**Comment by noncog** [comment]
> I am currently working on something vaguely related.
> 
> So for now, just a question: do you actually have to set `GIT_WORK_TREE`? Aren't you just doubling down on the worktree that would be used anyway? That's relevant because, unlike `magit-gitdir`, `magit-top-level` does not take the respective variable into account.

I haven't looked too deeply into the workings of Magit but perhaps this quick test provides you the answer you need.  Commenting out the line that sets GIT_WORK_TREE results in magit-status not showing any changed files in home or subdirectories of it. Basically, the above solution doesn't work at all without it.

**Comment by ryukinix** [comment]
hey man, @noncog!

I waited some solution for this for years! Thank you, that worked for me https://github.com/magit/magit/issues/460#issuecomment-1475082958

Since this at least: https://github.com/magit/magit/issues/2713#issuecomment-337051724

**Comment by jn64** [comment]
[Last solution](https://github.com/magit/magit/issues/460#issuecomment-1475082958) uses `-map`, `-uniq`, and `-keep` from [dash.el](https://github.com/magnars/dash.el).

If you don't have dash.el for whatever reason, they can be replaced with the equivalent `seq-map`, `seq-uniq`, and `seq-keep` from seq.el (built-in).

**Comment by dieggsy** [comment]
Has a recent change made this no longer work? The advice to `magit-process-environment` doesn't work for me currently, though the recursive edit method does.

~It may be that we can't rely on `default-directory` like this because it's being run from a temp buffer?~ (not sure that makes sense, actually)

I guess I consider the recursive edit method cleaner anyway, since it doesn't rely on comparing directories to the output of a shell command.

**Comment by ryukinix** [comment]
@dieggsy something like this doesn't works anymore? I think I still use a old version of magit:

```emacs-lisp
(with-eval-after-load 'magit
  (defun lerax-magit-process-environment (env)
    "Detect and set git -bare repo env vars when in tracked dotfile directories."
    (when (equal default-directory (expand-file-name "~/"))
     (let* ((default (file-name-as-directory (expand-file-name default-directory)))
            (git-dir (expand-file-name "~/.dot/"))
            (work-tree (expand-file-name "~/")))
       (push (format "GIT_WORK_TREE=%s" work-tree) env)
       (push (format "GIT_DIR=%s" git-dir) env)))
    env)

  (advice-add 'magit-process-environment
              :filter-return #'lerax-magit-process-environment))
```

This is still working for me using magit `20260130.1505`

**Comment by dieggsy** [comment]
@ryukinix actually both seem to be working for me now. must have been misconfiguration on my part.

**Comment by NU11V01D** [comment]
I ended up coming with this one.

```elisp
  (defvar +dotfiles--git-dir (expand-file-name "~/.dotfiles/")
    "Path to my dotfiles Git directory.")
  (defvar +dotfiles--work-tree (expand-file-name "~/")
    "Path to my dotfiles work-tree.")

  (defun +dotfiles--magit-env-advice (env)
    "Inject bare repo variables only when executing commands within the dotfiles."
    (if (or (equal default-directory +dotfiles--work-tree)
            (bound-and-true-p magit-buffer-topdir))
        (append (list (format "GIT_DIR=%s" +dotfiles--git-dir)
                      (format "GIT_WORK_TREE=%s" +dotfiles--work-tree))
                env)
      env))

  (advice-add 'magit-process-environment :filter-return #'+dotfiles--magit-env-advice)
  
  (defun +dotfiles-status ()
    "Open `magit-status' for my dotfiles."
    (interactive)
    (magit-status-setup-buffer +dotfiles--work-tree))

  (defun +dotfiles-add-file (file)
    "Add FILE to my dotfiles bare repo."
    (interactive (list (read-file-name "Add to dotfiles: " "~/")))
    (let ((magit-git-global-arguments
           (append magit-git-global-arguments
                   (list (format "--git-dir=%s" +dotfiles--git-dir)
                         (format "--work-tree=%s" +dotfiles--work-tree)))))
      (magit-call-git "add" (expand-file-name file))
      (magit-refresh)
      (message "Added %s to dotfiles." file)))
```

I then bind `+dotfiles-status` to something like `C-c g` to invoke it anywhere. Normal `C-x g` works as normal, and you can call it from everywhere and it won't interfere with future calls of Magit. I also made a function to add files to the bare repo since I set `status.showUntrackedFiles` and Magit will only show me files I'm currently tracking.
