### ISSUE TITLE
Should run `git pull` in with-editor for all cases (in particular also for pushremote)

### ISSUE THREAD

**Issue by siccegge** [magit/magit#4604]
Magit fails to open the commit editor when pulling from pushremote ('F p') but operates flawlessly with an 'F u'

I believe this is due to 
https://github.com/magit/magit/blob/master/lisp/magit-pull.el#L96
executing a magit-git-run-async while
https://github.com/magit/magit/blob/master/lisp/magit-pull.el#L136
executes a magit-run-git-with-editor

>    M-x magit-version RET

Magit 3.3.0, Git 2.30.2, Emacs 27.1, gnu/linux

Behaviour is the (i guess expected) in magit-process

> hint: Waiting for your editor to close the file...
> *ERROR*: Terminal type "dumb" is not powerful enough to run Emacs
> error: There was a problem with the editor 'emacsclient -a '' -nw'.
> Not committing merge; use 'git commit' to complete the merge.

**Comment by kyleam** [comment]
Thanks for the report and analysis.
