### ISSUE TITLE
Rebase, color of "have not been applied yet" commits

### ISSUE THREAD

**Issue by geza-herman** [magit/magit#4612]
I'm not sure whether this is a documentation or a code issue, but the document says in "6.9.2 Information About In-Progress Rebase":
```
The following colors are used:

* Yellow commits have not been applied yet.
```

However, I think that `pick` or `edit` commits are in the "not applied yet" category, but their color is now yellow, but the emacs `default` (usually some kind of gray). They use the `magit-sequence-pick` face, but this face doesn't have any colors overridden, it just inherits from `default`. I saw yellow commits previously, so I think that there are some kind of commits which are correctly rendered as yellow (like `goal`), but "future" commits are not yellow.

![image](https://user-images.githubusercontent.com/27892988/155522366-8e01d5f6-b573-48b1-926c-80d5926aad10.png)

**Comment by geza-herman** [comment]
Regarding your edit, now the yellow color is not documented (sorry, I don't want to nit-pick, I'm just not sure whether it's intentional or not).

**Comment by tarsius** [comment]
I've updated the documentation again and changed the theme I use for screenshots to match the documented behavior.

**Comment by geza-herman** [comment]
Thank you!
