### ISSUE TITLE
"void" vs. "poof" commit prefixes at rebase

### ISSUE THREAD

**Issue by geza-herman** [magit/magit#4613]
I was trying to understand the difference between `void` and `poof` prefixes at rebase. I checked the code, and it seems that they have the same condition? Don't these two prefixes mean the same?

These are the clauses in a `cond` expression:
```elisp
           ((--first (magit-rev-equal it stop) done)
            ;; The commit's testament has been executed.
            (magit-sequence-insert-commit "void" stop 'magit-sequence-drop))
```

vs

```elisp
           ;; The commit is definitely gone...
           ((--first (magit-rev-equal it stop) done)
            ;; ...but all of its changes are still in effect.
            (magit-sequence-insert-commit "poof" stop 'magit-sequence-drop))
```

**Comment by tarsius** [comment]
Yes, it seems the second clause is dead-code but I will leave it in place because then I might one day look at it and remember what other state I intended to visualize.

**Comment by geza-herman** [comment]
I just wanted to mention this, because the manual also talks about it, but magit won't ever display `poof` currently. Also, I now noticed that the current code can display `like`, which is not documented. The color description also seems to be not 100% agreement with the code, for example the manual talks about three possible colors of `same`, but as I see, it can only be yellow currently. Not a big deal of course, I just wanted to let you know.

**Comment by tarsius** [comment]
Adding it to my private list of details to look at some point in the future. :grin:
