### ISSUE TITLE
Error message: cannot invoke transient magit-commit while minibuffer is active

### ISSUE THREAD

**Issue by AtomicNess123** [magit/magit#4617]
I am trying to commit on disk some changes and when attempting to I receive the message:

`cannot invoke transient magit-commit while minibuffer is active`

Expected behaviour: just go about normally when committing.

Magit-version: Magit 20210531.1524, Git 2.23.0, Emacs 27.2, darwin [2 times]

**Comment by tarsius** [comment]
Update `transient` and then you can.

On the other hand, it doesn't actually make sense to initiate a commit while the minibuffer is active. But it is possible now.

**Comment by AtomicNess123** [comment]
> Update `transient` and then you can.
> 
> On the other hand, it doesn't actually make sense to initiate a commit while the minibuffer is active. But it is possible now.

How do I update transient? I'm a newbie.

**Comment by tarsius** [comment]
I don't use `package.el` but this is what google provided: https://www.systutorials.com/how-to-upgrade-packages-installed-by-elpa-in-emacs/.

The official documentation is here: https://www.gnu.org/software/emacs/manual/html_node/emacs/Packages.html.

It might get a bit more complicated in this instance. If you get weird errors after updating, then you might have to:

1. Uninstall magit and transient (mark them for deletion with `d` in the package list and then `x` to perform the deletes)
2. Exit Emacs
3. Restart Emacs
4. Reinstall magit (which also causes transient to be reinstalled)
