### ISSUE TITLE
cannot visit a file with chmod changes

### ISSUE THREAD

**Issue by robohack** [magit/magit#4623]
###    (1) what behavior you expected

I press return on a line in the status buffer for a file with both chmod changes and diff hunks and expect to visit the file.

###     (2) what behavior you observed

The following error is thrown.

 ###    (3) and how we can reproduce the issue.

Change the mode of a file with other content changes, update the status buffer, and then try to visit the file.

(see below for a view of an example status buffer)

 ###    M-x toggle-debug-on-error RET

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  magit-diff-hunk-line(#<magit-hunk-section (chmod) [hunk file unstaged status] 1612-[1644-]1644> nil)
  magit-diff-visit-file--noselect("/home/more/woods/work/experiments/techo.awk" nil)
  magit-diff-visit-file--internal("/home/more/woods/work/experiments/techo.awk" nil pop-to-buffer-same-window)
  magit-diff-visit-file("/home/more/woods/work/experiments/techo.awk" nil)
  funcall-interactively(magit-diff-visit-file "/home/more/woods/work/experiments/techo.awk" nil)
  call-interactively(magit-diff-visit-file nil nil)
  command-execute(magit-diff-visit-file)
```

 ###    M-x magit-version RET

```
Magit 20220217.349 [>= 3.3.0-git], Git 2.19.1, Emacs 26.1, berkeley-unix
```

Example status buffer attached
![win](https://user-images.githubusercontent.com/328917/156939858-72b7934a-c095-42f3-b864-5f58e03f0d70.png)
:

**Comment by kyleam** [comment]
Thanks for reporting.  This was a regression in v3.2.0.  Will push a fix in a bit.
