### ISSUE TITLE
Wiki page referenced in error does not exist

### ISSUE THREAD

**Issue by indigoviolet** [magit/magit#4633]
```
Magit unset $GIT_DIR (was "/home/venky/.local/share/yadm/repo.git/").  See https://github.com/magit/magit/wiki/Don’t-set-$GIT_DIR-and-alike
Magit unset $GIT_WORK_TREE (was "/home/venky").  See https://github.com/magit/magit/wiki/Don’t-set-$GIT_DIR-and-alike
```

I created a dummy page https://github.com/magit/magit/wiki/Don%E2%80%99t-set-$GIT_DIR-and-alike, but it might need filling out :)

**Comment by kyleam** [comment]
Bah, Emacs is messing with the single quote when it renders the message.  The page is here: https://github.com/magit/magit/wiki/Don't-set-$GIT_DIR-and-alike

Thanks for reporting.

**Comment by tarsius** [comment]
You're to fast for me :grinning: 
I already fixed it last night too, but then went to bed before committing.

**Comment by kyleam** [comment]
> I already fixed it last night too, but then went to bed before committing.

Shoot, was hoping to save you work not repeat your work :/

**Comment by tarsius** [comment]
I didn't have to write a comment and commit message. ;D
