### ISSUE TITLE
When magit-cherry-apply on multiple commit generates a conflict, cherry-pick state is not recognized

### ISSUE THREAD

**Issue by geza-herman** [magit/magit#4646]
Magit doesn't recognize the cherry-pick state when:
 * cherry picking multiple commits
 * without commiting the result (`magit-cherry-apply`)
 * cherry picking fails because of a conflict
 
`git status` tells that "Cherry-pick currently in progress.", but `magit-status` doesn't recognize this state. The reason for this is that magit checks the existence of the file `.git/CHERRY_PICK_HEAD`, but it doesn't exist in this case.

Applying multiple commits without doing a commit may be rare, but can happen accidentally (this is what happened for me). The problem is, that after the conflict happened, and I reverted the conflict (using `magit-discard`), and re-tried to apply the commits, this time with `magit-cherry-pick` (i.e., commit the result). This of course failed because of the conflict, but cherry-pick state is still not recognized, because of the first failed cherry pick. The reason is that because of the first cherry pick, git is stuck in the "no-commit" state. I had to manually abort the cherry pick with `git cherry-pick --abort`, and then doing `magit-cherry-pick` worked correctly.

You can reproduce the issue, if you create a repository with this script:
```bash
git init -b main repo
cd repo

git config user.email "a@b.com"
git config user.name "Name"

echo "initial" >file.txt
git add file.txt
git commit -m "Initial"

git checkout -b topic

echo "topic A" >file.txt
git commit -a -m "A"

echo "topic B" >file.txt
git commit -a -m "B"

git checkout main
echo "main" >file.txt
git commit -a -m "main"
```

This creates a `main` and a `topic` branch, with a `file.txt`. Now, try to apply the two commits of the `topic` branch into `main`: use `magit-show-refs`, select the two commits (`B` and `A`) of `topic`, then press `a`. Notice that the apply fails. Now, `git status` tells that "Cherry-pick currently in progress.". But `magit-status` doesn't recognize this.

magit-version is: Magit 20220211.2231 (>= 3.3.0-git), Git 2.33.0, Emacs 29.0.50, gnu/linux

**Comment by kyleam** [comment]
Thanks for the report and detailed reproduction steps.

I don't think we can get around checking both `$GIT_DIR/{CHERRY_PICK,REVERT}_HEAD` and `$GIT_DIR/sequencer/todo`.  (`magit-cherry-pick-in-progress-p` and `magit-revert-in-progress-p` have checked both in the past, just not at the same time.)

I've pushed that to the km/pick-revert-no-commit-seq branch.  I'll plan to merge that tomorrow unless there are objections.
