### ISSUE TITLE
Cannot commit anymore with MELPA version 20220426.2016

### ISSUE THREAD

**Issue by tsdh** [magit/magit#4669]
Since today's MELPA release, I cannot commit anymore.  When I have staged files and do `c c`, I get this output in the process buffer:

```
  1 git … commit --
hint: Waiting for your editor to close the file...
Waiting for Emacs...
*ERROR*: Don’t kill this buffer #<buffer COMMIT_EDITMSG>.  Instead cancel using C-c C-k
error: There was a problem with the editor '/home/horn/bin/emacsclient --socket-name=/run/user/1000/emacs/server'.
Please supply the message using either -m or -F option.
```

Then I've tried with `magit-emacs-Q-command` which resulted in an error where I had to add `-L /home/horn/.emacs.d/elpa/compat-28.1.1.0/ ` to the command line to make it start (which could be an issue only with emacs 29).

Anyway, now that I have it running, I get a different problem.  After staging some files and doing `c c`, the `COMMIT_EDITMSG` is created but not displayed in some window.  When I switch to it manually, type a message and do `C-c C-c` it vanishes but the status buffer stays as-is.  The process buffer shows just:

```
run git … commit --
hint: Waiting for your editor to close the file...
Waiting for Emacs...
```
So it seems like it didn't recognize that emacsclient has already closed.  `git status` on the command line also confirms no commit was made.

I can confirm the issue with two different computers.  However, they are probably too similar (both up-to-date Arch GNU/Linux, up-to-date emacs master, and up-to-date emacs packages) to give that argument weight.

Sadly, I cannot try easily with emacs 28 because there seem to be byte-code incompatibilities leading to errors on startup.  I've tried deleting all elc files below `~/.emacs.d/elpa/` but then got an error on startup that some version could not be extracted (sorry, don't remember the exact error but can try again later).  If there is a better way to tell (an older) emacs not to use the elc files, I'm all ears.

**Comment by tarsius** [comment]
Same as https://github.com/magit/with-editor/issues/111.

To avoid more duplicates, I am leaving this issue open and in this repository.

**Comment by tsdh** [comment]
@tarsius Ah, yes, it's the same.  And I suspect its an emacs issue.  When I just opened a text file from firefox (which would also open emacsclient), the emacs frame appeared but the buffer wasn't shown so similar to the `magit-emacs-Q-command` recipe.

Should I file another issue for the `magit-emacs-Q-command` needs to add the `compat` package to `load-path` issue?

**Comment by tsdh** [comment]
@tarsius Hehe, thanks for the quick fix and the good reminder comment. :-)

**Comment by tsdh** [comment]
Reported to emacs: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=55149

**Comment by liuyinz** [comment]
same problem.

**Comment by markk** [comment]
I'm also seeing this committing in emacs. The commit works, but the magit staging window doesn't refresh and this is in the messages buffer:

```
Running /usr/bin/git commit --
Only whitespace and/or comments; message not saved
Diffing changes to be committed (C-g to abort diffing)
When done with a buffer, type \ c
Type \ c to finish, \ k to cancel, and M-p and M-n to recover older messages
Auto-saving...done
Message saved
Saving file /path/to/.git/COMMIT_EDITMSG...
Wrote /path/to/.git/COMMIT_EDITMSG
Git finished
error in process sentinel: if: Symbol’s function definition is void: compat-assoc
error in process sentinel: Symbol’s function definition is void: compat-assoc
```

**Comment by tarsius** [comment]
@markk That is a different issue.

> And indeed `compat-assoc` is an unknown function in emacs.

You need to install the `compat` package; it is a new dependency of Magit.

**Comment by markk** [comment]
> @markk That is a different issue.
> 
> > And indeed `compat-assoc` is an unknown function in emacs.
> 
> You need to install the `compat` package; it is a new dependency of Magit.

Ah, sorry, it may be a different issue. But I do have compat-28.1.1.0 installed, so not sure why I'm getting this error.

**Comment by miangraham** [comment]
This should be fixed on emacs master. See: https://github.com/magit/with-editor/issues/111#issuecomment-1112314215

**Comment by tarsius** [comment]
@tsdh thanks for getting this fixed!
