### ISSUE TITLE
git-commit-setup-hook appears twice in manual

### ISSUE THREAD

**Issue by felker** [magit/magit#4672]
In https://magit.vc/manual/magit/Commit-Mode-and-Hooks.html built from [magit.org](https://github.com/magit/magit/blob/master/docs/magit.org), "User Option: `git-commit-setup-hook`" appears twice. I believe the second usage is incorrect, although I am not sure what the correct option is.

```
- User Option: git-commit-setup-hook ::

  Hook run at the end of ~git-commit-setup~.
```

```
- User Option: git-commit-setup-hook ::

  Hook run after the user finished writing a commit message.

  This hook is only run after pressing ~C-c C-c~ in a buffer used to
  edit a commit message.  If a commit is created without the user
  typing a message into a buffer, then this hook is not run.

  This hook is not run until the new commit has been created.  If
  doing so takes Git longer than one second, then this hook isn't run
  at all.  For certain commands such as ~magit-rebase-continue~ this
  hook is never run because doing so would lead to a race condition.

  This hook is only run if ~magit~ is available.

  Also see ~magit-post-commit-hook~.
```

**Comment by tarsius** [comment]
Thanks for the report!

**Comment by felker** [comment]
Thanks for the quick fix! While you are here, any chance I could dig your brain why the following `init.el` `use-package` snippet's use of that hook does not work as written in `:hook`, but does work as written in `:init`?

```
(use-package git-commit
  :hook ((git-commit-mode . (lambda () (setq fill-column 72)))
         ;;  Approach #1: the following line does not work and breaks git-commit mode from starting in a COMMIT_MSG buffer
         ;; (git-commit-setup . git-commit-turn-on-flyspell)
          )
  :ensure t
  ;;  Approach #2
  :init 
  (add-hook 'git-commit-setup-hook #'git-commit-turn-on-flyspell)
)
```

Even stranger, `C-h v <RET> git-commit-setup-hook` shows `git-commit-turn-on-flyspell`, and then `git-commit` minor mode is loaded in `COMMIT_MSG` after I check the value of the hook variable even in Approach 1.

**Comment by tarsius** [comment]
I use approach #2, and don't know #1 is supposed to work.

Use `pp-macroexpand-last-sexp` to compare the two approaches.

**Comment by felker** [comment]
So I have figured out why the `:hook` section was problematic--- adding the following line there actually sets `git-commit` to deferred/ lazy loading as it defines an autoload for the last argument function
```
:hook (
(git-commit-setup . git-commit-turn-on-flyspell)
)
```

Whereas lazy loading is disabled if `:hook` only consists of
```
:hook (
(git-commit-mode . (lambda () (setq fill-column 72)))
)
```
since you obviously cant establish an autoload definition for a lambda function.

And `C-h v <RET> git-commit-setup-hook` loads `git-commit.el` since `git-commit-autoloads.el` contains:
```
(register-definition-prefixes "git-commit" '("git-commit-" "global-git-commit-mode"))
```
I was a bit unaware of this autoloading behavior described in https://www.gnu.org/software/emacs/manual/html_node/elisp/Autoload-by-Prefix.html . Thought I would share my findings with others in case someone else is confused.
