### ISSUE TITLE
Changing git variables with transient-infix-read fails when magit is byte-compiled

### ISSUE THREAD

**Issue by miangraham** [magit/magit#4676]
Okay, here's a weird one. On my darwin system (running emacs v28 and installing packages with straight.el), git variable modifications using `transient-infix-read` fail, but only when magit is byte-compiled.

I haven't observed this problem on any linux systems, but the mac affected is also the only place I use straight.el so that may be a factor as well. It isn't my primary dev machine so I'm a fairly light user here, but it's been running magit and org libraries for a couple years with no other obvious issues. Emacs v28 just became available last month via the package I use for installation so it's possible that the upgrade introduced some problem.

Let me know if there's anything I should test to help diagnose. Details below and thanks in advance for looking.

#### What I did:

1. Run `magit-status` on any repo.
2. Modify a variable using `transient-infix-read`, for example `remote.origin.pushurl` using `M s RET foo RET`

#### Expected: 

Prompt for the new value closes and the **Variables** section reflects the change.

#### Observed:
```
Debugger entered--Lisp error: (invalid-function transient--with-suspended-override)
  apply(debug (error (invalid-function transient--with-suspended-override)))
  transient--exit-and-debug(error (invalid-function transient--with-suspended-override))
  transient--with-suspended-override(("foo"))
  #f(compiled-function (cl--cnm obj) #<bytecode 0xb07e130cf80f797>)(#f(compiled-function (&rest cnm-args) #<bytecode -0x192c3b1a88572818>) #<magit--git-variable:urls magit--git-variable:urls-1ff884a36d00>)
  apply(#f(compiled-function (cl--cnm obj) #<bytecode 0xb07e130cf80f797>) #f(compiled-function (&rest cnm-args) #<bytecode -0x192c3b1a88572818>) #<magit--git-variable:urls magit--git-variable:urls-1ff884a36d00>)
  #f(compiled-function (&rest args) #<bytecode -0xe71ece52ec96c8>)(#<magit--git-variable:urls magit--git-variable:urls-1ff884a36d00>)
  apply(#f(compiled-function (&rest args) #<bytecode -0xe71ece52ec96c8>) #<magit--git-variable:urls magit--git-variable:urls-1ff884a36d00> nil)
  transient-infix-read(#<magit--git-variable:urls magit--git-variable:urls-1ff884a36d00>)
  magit-remote\.<remote>\.pushurl()
  funcall-interactively(magit-remote\.<remote>\.pushurl)
  call-interactively(magit-remote\.<remote>\.pushurl nil nil)
  command-execute(magit-remote\.<remote>\.pushurl)
```

## Workaround

I'm able to mitigate the problem on my end with [this straight.el recipe override](https://github.com/miangraham/emacs-config/commit/9f947c3a5142337ba2da774a1f87ec38132ff6bc) which adds `:build (:not compile)` to stop magit from being byte-compiled on disk. Manually deleting the .elc files after the initial build works as well.

After making either of the two changes above and restarting emacs, `M s RET foo RET` produces no error and the **Variables** display contains the new value.

#### emacs-version
```
GNU Emacs 28.1 (build 1, x86_64-apple-darwin21.4.0, Carbon Version 165 AppKit 2113.4) of 2022-04-13
```
(installed with homebrew using https://github.com/railwaycat/homebrew-emacsmacport)

#### magit-version
```
Magit v3.3.0-300-g2235876d, Git 2.35.2, Emacs 28.1, darwin
```

#### Package revs from git repos on disk
magit: 2235876dd86f24530ec415c30e41a34cec2a8520
transient: 84f2d12ef31ec74c85e616283926780532fed13f

#### emacs -Q start command
```
/usr/local/Cellar/emacs-mac/emacs-28.1-mac-9.0/Emacs.app/Contents/MacOS/Emacs -Q --eval \(setq\ debug-on-error\ t\) -L /Users/ian/.emacs.d/straight/build/compat/ -L /Users/ian/.emacs.d/straight/build/dash/ -L /Users/ian/.emacs.d/straight/build/transient/ -L /Users/ian/.emacs.d/straight/build/with-editor/ -L /Users/ian/.emacs.d/straight/build/magit/ -L /Users/ian/.emacs.d/straight/build/magit-section/ -L /Users/ian/.emacs.d/straight/build/git-commit/ -l /Users/ian/.emacs.d/straight/build/magit/magit
```

**Comment by miangraham** [comment]
Narrowing things down a bit: I also stop being able to reproduce this problem when I switch my package installation method from straight.el to package.el (still via use-package). This results in transient-20220425.1314 and magit-20220430.919 with .elc files on disk, and no error when performing `M s RET foo RET`.

**Comment by miangraham** [comment]
This might be a bug in straight.el. After letting it install and build magit and verifying I can reproduce the error, running `(byte-compile-file "/Users/ian/.emacs.d/straight/build/magit/magit-transient.el")` to overwrite straight's .elc output fixes the problem after a restart.

I've also verified that most of magit's .elc files change content (hash values) when the same .el files are built by straight versus `byte-compile-file`. I'll see if I can get a better idea of how the build process is different and refile over there when I've got a better grasp of the details.

**Comment by duckwork** [comment]
Just to add: I'm having the same issue on Debian, with straight.el and Magit. I did the `(:build (:not compile)` workaround, but still had to `(autoload 'transient--with-suspended-override "transient")` for that macro to be registered by Emacs, for some reason. The workaround does seem to work at this point, however.

**Comment by Apteryks** [comment]
I'm also getting this in GNU Guix; perhaps the issue should be re-opened?  The current `emacs-magit` package direct dependencies in Guix are:
```
emacs-compat@29.1.4.0 emacs-dash@2.19.1 emacs-with-editor@3.2.0 git@2.39.2 perl@5.34.0
+ texinfo@6.7
```

**Comment by Apteryks** [comment]
Thank you, @tarsius!  I've updated emacs-transient and emacs-magit to their latest commit (and added emacs-transient as a propagated input to emacs-magit), and it resolved the problem.
