### ISSUE TITLE
Bad position after staging a region

### ISSUE THREAD

**Issue by ensc** [magit/magit#4682]
Commit 95b432530a6b131e63bec7411ee768f1dee9f629 (result from `git bisect`) seems to break positioning the cursor when staging a region.  After performing such a staging operation, cursor will be moved to the very last hunk while it should just move to the next one.

Steps to reproduce:

1.  <details><summary>Prepare a repository</summary>

    ```sh
    git init

    cat <<EOF >file
    H0-0
    H0-1-next-new
    H0-3
    H0-4-remove
    H0-5
    H0-6
    H0-7
    H0-8
    H1-0
    H1-1
    H1-2
    H1-3-remove
    H1-4
    H1-5
    H1-6
    H2-0
    H2-1
    H2-2
    H2-3-next-new
    H2-5
    EOF

    git add file && git commit -m X

    cat <<EOF >file
    H0-0
    H0-1-next-new
    H0-2-new
    H0-3
    H0-5
    H0-6
    H0-7
    H0-8
    H1-0
    H1-1
    H1-2
    H1-4
    H1-5
    H1-6
    H2-0
    H2-1
    H2-2
    H2-3-next-new
    H2-4-new
    H2-5
    EOF
    ```
    </details>

2. inspect this repository with `magit-status` and mark the first changed line (`ctrl-space`)

    ![step-1](https://user-images.githubusercontent.com/43379/167123048-2f13b0e1-fe6c-480a-a342-12efe7c63978.png)

4. stage this line by pressing `s`

    ![step-2](https://user-images.githubusercontent.com/43379/167123700-3d5e2c1e-f548-49fe-8740-1a195df71965.png)

Now, cursor is at `H2-4-new` while I would expect it to be in the first hunk.

**Comment by tarsius** [comment]
Thanks for the report!
