### ISSUE TITLE
Trailing whitespace is not highlighted if the file uses CRLF as end-of-line convention

### ISSUE THREAD

**Issue by tncaudex** [magit/magit#4693]
I expect `M-x magit-status` to highlight trailing spaces, even if the changed file uses CRLF to end lines.

If a file uses CRLF as end-of-line convention, Magit does not highlight trailing whitespace. Although `git diff` on the command line does, by the way.

To reproduce,

- Create a new text file, open it in Emacs and change EOL convention by typing: `C-x RET f dos RET`.
- Type some text into the file, save the file and commit it into a Git repository.
- Place the point to the end of any line in the file, type in some spaces, save the file.
- Get to a terminal that supports coloured output and enter `git diff`, observe how the trailing spaces are shown in red colour.
- Get back to Emacs and do `M-x magit-status`, see how the trailing spaces are NOT highlighted,
  - or, if `magit-diff-hide-trailing-characters` is non-nil, unrecognisable at all.

Additional information:

- Magit 3.3.0, Git 2.33.0, Emacs 27.1, gnu/linux
- `magit-diff-paint-whitespace` t
- `magit-diff-highlight-trailing` t

I've tracked the problem down to function `magit-diff-paint-whitespace` in `magit-diff.el`, where the regexp `.*?\\([ \t]+\\)$` is used to detect trailing whitespace. 
https://github.com/magit/magit/blob/9a09823e56ccb1d9a63f0edeac260fbc9bd5025b/lisp/magit-diff.el#L3273

Apparently, the presence of additional `^M` at the end of lines prevents `$` from matching. This is also funny because Emacs itself goes to great lengths to avoid this problem by decoding EOLs of a file when it reads it into a buffer, and encoding them back in every time it writes the file to disk. For the very reason of this coding mechanism, `$` usually matches end-of-lines because they are converted to just LF inside a buffer. Obviously, Magit is doing something else here, possibly applying the regexp directly to the file itself and not to a buffer. I'm not sure how to best fix it though.

By the way, Git itself is not impressed by CRLF at all. It highlights trailing whitespace just fine.

**Comment by tarsius** [comment]
Magit may show parts of multiple files in one buffer and those files might not all use the same eol style. I have adjusted the regexp to account for both styles.
