### ISSUE TITLE
Explicitly requiring 'compat-2[67] is incorrect and breaks batch compilation

### ISSUE THREAD

**Issue by owinebar** [magit/magit#4698]
Batch compiling magit-section and magit-base breaks because they have explicit 
(require 'compat-26)
(require 'compat-27)
The source for those libraries explicitly states they are not to be explicitly loaded by user code, only the compat library.  All the version specific compat libraries load a library compat-macs that explicitly generates an error if it detects it is being loaded by any library other than itself or one of the compat-2[4-8] libraries.
Once those are removed, I'm able to both byte and native compile magit in batch mode.

**Comment by tarsius** [comment]
> The source for those libraries explicitly states they are not to be explicitly loaded by user code, only the compat library.

You are mistaken, see https://sr.ht/~pkal/compat/#usage.

**Comment by tarsius** [comment]
> All the version specific compat libraries load a library compat-macs that explicitly generates an error if it detects it is being loaded by any library other than itself or one of the compat-2[4-8] libraries.

There is a bug in compat, that makes it necessary to byte-compile all of its libraries before loading a third-party library that depends on one of its `compat-XY` libraries.

**Comment by tarsius** [comment]
Ps: I've worked on fixing that bug a while ago but didn't finish it. I might have another stab at it soon.

**Comment by owinebar** [comment]
I'm not mistaken.  Take a look at line 25-28 of compat-28.el, for example:
https://git.sr.ht/~pkal/compat/tree/master/item/compat-28.el
;; Find here the functionality added in Emacs 28.1, needed by older
;; versions.
;;
;; Do NOT load this library manually. Instead require `compat'.

The way compat is written, those files are never loaded by require in any
case.  compat.el performs its own custom read and macro expansion pass so
the function definitions from those files should appear in the byte code of
compat.elc.

If for some reason the files require explicit byte compiling, it should be
done during the installation process for compat.

**Comment by owinebar** [comment]
Apparently you're explicitly requiring compat-26 to get compat-alist-get,
which compat doesn't generate because it only expands forms starting with
one of the compat-* forms. The right way to get those would be to make a
new library, say magit-compat, that requires compat but also copies the
code from compat but only expands forms not expanded by lines 80-89.  Or
you could just add gv-define-expander to line 89 (and any other forms you
require).

**Comment by tarsius** [comment]
> I'm not mistaken.  Take a look at line 25-28 of compat-28.el

That information was outdated. I have [reported](https://todo.sr.ht/~pkal/compat/3) that and it is [already fixed](https://git.sr.ht/~pkal/compat/commit/2f3593ab7f41ce46cc2dbf40868fcf0b4dbd0cd5).

**Comment by owinebar** [comment]
We have different definitions of what constitutes a bug.  For me, if
something causes the compile to break, that's an issue, whether it's known
to drive from a bug in a dependency or not.  It remains a bug until there's
a known good version of the dependency that can be specified, or there's a
workaround in place that solves the issue for the immediate project.

**Comment by tarsius** [comment]
The workaround is to compile compat-XY before compiling a library that depends on compat-XY.

**Comment by owinebar** [comment]
I've done that, it still breaks.
The only way to compile it successfully is to require the library in the
compile time environment:
emacs -batch --eval "(progn (require 'compat-26) (require 'compat-27)
(batch byte-compile "path/to/magit-section.el" 't))"

**Comment by tarsius** [comment]
> The only way to compile it successfully is to require the library in the compile time environment:

I am not doing that but am never-the-less able to compile successfully, and that strongly suggests that this is not the only way. Thousands of users not doing this, while still being able to successfully compile and use magit is also a strong indicator.

It is likely that you did not succeed in compiling compat, or made some other mistake.

Of course there is always a possibility, however small, that something is different about your system. But because you already demonstrated that you can 100% certain about things that you are wrong about, I do not wish to invest time investigating that possibility. If this is a real problem, then a more constructive user will eventually run into it, and we can investigate it then.

Anyway, this soon shouldn't matter anymore; I have submitted a fix

**Comment by owinebar** [comment]
It's almost certain my system is different.  I'm precompiling a huge number
of packages, but not using the package manager, and in a common directory
because having a 1000+ directories on the load-path is inefficient.  One of
a handful of problem builds was magit-section/magit-base, and I spent way
too long tracking down the issue so I could patch it.  Then I found that
the documentation in the source code of compat-XY clearly states not to
directly include it, presumably because the author was aware of the issue I
spent too long identifying.
I have no idea how you and the compat author will want to resolve the
issue, so I make a local fix and report it to you, since the compat code
(as distributed) clearly states it shouldn't be used in the way it's being
used.
You immediately close the issue citing a change in the documentation.  I'm
reporting the issue  as much for other people who might face the same
problem as for you.  When I initially investigated the issue, I found one
hit from a mailing list for the build automation of one of those
pre-packaged emacs customized distributions - boom-something.  Of course I
can't recall the magic search terms now, but since there was someone else
seeing the problem, I thought the cause should be documented for their
benefit, at least until the issue is resolved to the point where their
automated build won't break.
I'm not sure how much more constructive you want me to be.

**Comment by owinebar** [comment]
From that  https://bytemeta.vip/index.php/repo/magit/magit/issues/4665 :

Eason0210
Eason0210 ***@***.***>NONE
Created 1 month ago

I agree that the issue is from compat, but I have no idea how to reproduce
it withoutborg.

As you mentioned, with latest commit of borg, when I run make all, borg will
be the first package to execute borg--native-compile , and then compat is
the second one.

But when compile other packages( such as magit, org-roam , etc ...) which
depends on compat, will cause the issue. I found that other packages need
to require the referred compat.el andcompat-xx.el(xx means 24 to 28) before
borg--native-compile.

I tried to require compat before building other packages, and it works
well. Let's take magit for example:

[submodule "magit"]
	no-byte-compile = lisp/magit-libgit.el
	build-step = (require 'compat-26)
	build-step = (require 'compat-27)
	build-step = borg-compile
        build-step = borg-update-autoloads
	path = lib/magit
	url = ***@***.***:magit/magit.git



I don't use borg-collective, but I am guessing those two build steps
requiring compat-26 and compat-27 are exactly what I described previously
which you claimed I was mistaken about.  Your philosophy that it's not an
issue with magit because it should be fixed in compat is bizarre.
And you're correct about my certainty.  I did not report the issue until I
had tracked down the source and was certain what was causing the
problematic behavior.  AFAIC, that is as constructive as it gets short of
creating a pull request with a solution.

**Comment by tarsius** [comment]
> Your philosophy that it's not an issue with magit because it should be fixed in compat is bizarre.

This assessment leaves out a lot of context.  A user of the Borg package manager reported that it was unable to install the Magit package.  I happen to be the author of both Magit and Borg, and as such I am qualified to make the call which of the two needs to be fixed.  I determined that it is Borg and proceeded to close the Magit bug report and fix the issue in Borg.

> I did not report the issue until I had tracked down the source and was certain what was causing the problematic behavior.

You observed the symptoms and found a way around them. You then proceeded to explain to me why what I am doing is wrong, and continued to do so even after being made aware of information that challenges that assessment.

That is frustrating for me because I had already identified the actual root cause, had communicated with the author of Compat about it, had successfully implemented a functioning workaround in my package manager, had successfully helped other users work around the issue, and was working on a proper fix for the root cause.

**Comment by owinebar** [comment]
Given your comments, I went back and rechecked my work.
You were precisely correct.  I had only natively compiled the compat-XY
libraries before trying to both natively compile and byte compile
magit-section.
When I byte-compiled compat-26.el and compat-27.el, magit-section.el will
successfully byte-compile and native-compile regardless of whether the eln
files for compat-26 and compat-27 exist in the eln cache.
When I only native-compile compat-26 and compat-27 (and remove the elc
files), magit-section will neither byte-compile nor native-compile.
That seems like an issue in emacs itself.
I apologize for my error.
