### ISSUE TITLE
Can't discard changes to unmerged files

### ISSUE THREAD

**Issue by avar** [magit/magit#47]
Here's the usecase. Say I have a stash that I haven't touched in a while, so I do "a" on it, find that it gives me a bunch of unmerged stuff and is old and out of date anyway. Now I want to nuke the changes it made.

I can "k" on the staged/changed files it'll add. But these:

```
Unstaged changes:
    Unmerged builtin/fetch.c                                                                                                                                 
    Unmerged builtin/merge.c
```

Will cause a "Git failed":

```
$ git --no-pager checkout -- builtin/fetch.c
error: path 'builtin/fetch.c' is unmerged
```

Maybe it should do this on unmerged files (after asking "are you really sure"):

```
git checkout --ours builtin/fetch.c && git add builtin/fetch.c
```

Or:

```
git checkout HEAD -- builtin/fetch.c
```

**Comment by ReubenRahul** [comment]
you can reset the file and later on can checkout from the file you want.

**git reset builtin/fetch.c** 

**git checkout builtin/fetch.c** 

I hope these will solve the problem.
