### ISSUE TITLE
magit-wip-commit-worktree: Invalid function: ("GIT_INDEX_FILE" file0)

### ISSUE THREAD

**Issue by njsmith** [magit/magit#4714]
Magit c1fb53d, Git 2.32.0, Emacs 28.0.50, gnu/linux
via Doom emacs

I just upgraded magit, and now most magit operations fail with an error like:

```
Debugger entered--Lisp error: (invalid-function ("GIT_INDEX_FILE" file0))
  ("GIT_INDEX_FILE" file0)()
  magit-wip-commit-worktree("refs/heads/integration-tests-on-self-hosted-arm64" (".github/workflows/test_integration.yml") " before stage")
  magit-wip-commit((".github/workflows/test_integration.yml") " before stage")
  magit-wip-commit-before-change((".github/workflows/test_integration.yml") " before stage")
  magit-stage-1("-u" (".github/workflows/test_integration.yml"))
  magit-stage(nil)
  funcall-interactively(magit-stage nil)
  #<subr call-interactively>(magit-stage nil nil)
  apply(#<subr call-interactively> magit-stage (nil nil))
  call-interactively@ido-cr+-record-current-command(#<subr call-interactively> magit-stage nil nil)
  apply(call-interactively@ido-cr+-record-current-command #<subr call-interactively> (magit-stage nil nil))
  call-interactively(magit-stage nil nil)
  command-execute(magit-stage)
```

My magit configuration is:

```elisp
(setq
 magit-completing-read-function 'magit-ido-completing-read
 magit-diff-refine-hunk 'all
 magit-save-some-buffers 'dontask
 magit-wip-after-apply-mode t
 magit-wip-after-save-mode t
 magit-wip-before-change-mode t
)

(use-package! magit-delta :hook (magit-mode . magit-delta-mode))
```

From the backtrace, I suspect the issue is that I have `magit-wip-*-mode` enabled?

To confirm that, I tried commenting out all the `magit-wip-*-mode` settings from my configuration and restarting emacs, and now magit seems to be working again. But of course I like the `magit-wip-*` features, so I would prefer to keep them enabled :-)

**Comment by kyleam** [comment]
Hmm, that's coming from here:

https://github.com/magit/magit/blob/adf5848ea787401b09aa37b134aacaaaae3007f7/lisp/magit-git.el#L2314-L2315

And that looks valid.  `with-environment-variables` came with Emacs 28.1 (specifically 7cb29440433 2021-09-26).  For Emacs versions before that, compatibility is provided by the `compat` package (looks like that's probably not relevant for you, depending on when your 28.0.50 build is from).

So, this smells like a bad elc state, and I don't have any better suggestions than clearing out your Magit *elc's and trying a fresh compile.  (I'm not familiar with Doom, but perhaps an uninstall/reinstall dance would accomplish that.)

**Comment by njsmith** [comment]
> specifically 7cb29440433 2021-09-26

lol, it looks like I'm still running a homebrew build using https://github.com/konstare/emacs-gcc-pgtk from... 2021-09-14. So two weeks off!

So it sounds like I just need to upgrade! fair enough.

In retrospect, that's kind of a neat trick that elisp pulled, to produce such a confusing error message. Of course if you're missing a macro, then you'll try to evaluate its arguments, and they'll fail, blaming the wrong subexpression... but I've never run into that before.

**Comment by njsmith** [comment]
OK yeah can confirm that upgrading emacs and running `doom build` to recompile all .el files seems to have fixed this. Thanks!
