### ISSUE TITLE
magit-stash-create needs upstream configured

### ISSUE THREAD

**Issue by yanjijinxiao** [magit/magit#4716]
I use spacemacs with simple config.
```
(git :variables
          git-magit-status-fullscreen t
```
When I start to stash my changes, it seems occur some errors.
```
magit-stash-create: Invalid function: ("GIT_INDEX_FILE" file455)
```
I set `(setq magit-git-debug t)` to see what's going on.
```
fatal: no upstream configured for branch 'xxxxxxx'
```

Is there any branch need an upstream before stashing? But `git stash` in command-line works just fine.

**Comment by kyleam** [comment]
> Invalid function: ("GIT_INDEX_FILE" file455)

As with gh-4714, this is coming from `magit-with-temp-index` (called by `magit-stash-create` in this case).  What I said there pretty much applies here too: https://github.com/magit/magit/issues/4714#issuecomment-1165168155

> Is there any branch need an upstream before stashing?

No, an upstream doesn't need to be configured.  Setting `magit-git-debug` to t bubbles to lots of stderr, much of it routine and not problematic.

**Comment by kyleam** [comment]
Closing because, as I mentioned above, I think your installation is an invalid state.  Unfortunately, I don't think there is anything to do on Magit's end.
