### ISSUE TITLE
`magit-refresh` performance when dealing with a large commit

### ISSUE THREAD

**Issue by kaushalmodi** [magit/magit#4718]
Hello,

I am dealing with a mega commit which is created with a company-internal tool.

I was unable to stage that from within Emacs/Magit as the Magit Status buffer kept on hanging for many minutes. I was unable to get the staging finish from within Emacs. Once I set the staging run through my lunch break (~45 minutes) and it still hadn't finished!

So I did `git add -A` from the terminal (which did take few seconds to finish) to get past that.

Even with staging done now, the Magit Status buffer is unusable because now `magit-insert-staged-changes` during `magit-refresh` is causing the same freeze. _I appreciate that you have provided `magit-refresh-verbose` which helped me figure out that bottleneck._

So next, I tried running the same command from terminal that `magit-insert-staged-changes` is running.

I cannot share the full commit as it's proprietary but the below info tells how large the commit is:

```
> git --no-pager diff --cached --no-prefix -- | wc -l
warning: exhaustive rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 3627 and retry the command.
27283992
```

The diff had 27283992 lines.

```
> time `git --no-pager diff --cached --no-prefix --`
70.216u 12.860s 1:18.91 105.2%  0+0k 15232+0io 61pf+0w
```

The command took 1 min 18 seconds to run from the terminal.

---

### Magit version

```
Magit 20220625.1219 [>= 3.3.0-git], Git 2.34.0, Emacs 28.1.90, gnu/linux
```

>    (1) what behavior you expected

Magit Status buffer shouldn't freeze if repo has a lot of unstaged or staged changes.

>    (2) what behavior you observed

The Magit Status buffer was unusable with a lot of unstaged or staged changes (27283992 lines)

>    (3) and how we can reproduce the issue.

I am unable to provide an example as the code/repo is proprietary.

> Please include a backtrace in your report.  In most cases doing:
>
>    M-x toggle-debug-on-error RET

I couldn't use `M-x toggle-debug-on-error RET`, but I did `M-x toggle-debug-on-quit RET` and refreshed the Magit Status buffer. Once I noticed that the buffer had frozen, I hit `C-g` and I got this backtrace. 
 
```
Debugger entered--Lisp error: (quit)
  call-process("git" nil (t nil) nil "--no-pager" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color.ui=false" "-c" "color.diff=false" "--no-pager" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color.ui=false" "-c" "color.diff=false" "diff" "--ita-visible-in-index" "--cached" "--no-ext-diff" "--no-prefix" "--")
  apply(call-process "git" nil (t nil) nil ("--no-pager" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color.ui=false" "-c" "color.diff=false" "--no-pager" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color.ui=false" "-c" "color.diff=false" "diff" "--ita-visible-in-index" "--cached" "--no-ext-diff" "--no-prefix" "--"))
  process-file("git" nil (t nil) nil "--no-pager" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color.ui=false" "-c" "color.diff=false" "--no-pager" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color.ui=false" "-c" "color.diff=false" "diff" "--ita-visible-in-index" "--cached" "--no-ext-diff" "--no-prefix" "--")
  magit-process-file("git" nil (t nil) nil "--no-pager" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color.ui=false" "-c" "color.diff=false" "--no-pager" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color.ui=false" "-c" "color.diff=false" "diff" "--ita-visible-in-index" "--cached" "--no-ext-diff" "--no-prefix" "--")
  magit-process-git((t nil) ("--no-pager" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color.ui=false" "-c" "color.diff=false" "diff" "--ita-visible-in-index" "--cached" "--no-ext-diff" "--no-prefix" "--"))
  magit-git-insert(("diff" "--ita-visible-in-index" "--cached" "--no-ext-diff" "--no-prefix" "--"))
  magit-git-wash(magit-diff-wash-diffs "diff" ("--ita-visible-in-index" "--cached" "--no-ext-diff" "--no-prefix" "--"))
  magit--insert-diff("diff" "--cached" ("--no-ext-diff") "--no-prefix" "--" nil)
  magit-insert-staged-changes()
  magit-run-section-hook(magit-status-sections-hook)
  magit-status-refresh-buffer()
  magit-refresh-buffer()
  magit-refresh()
  funcall-interactively(magit-refresh)
  call-interactively(magit-refresh nil nil)
  command-execute(magit-refresh)
```

---

### Workaround

The workaround for staging and committing such large commits is to do it from the terminal.

```sh
# stage
git add -A
# commit
git commit -m "Some useful commit message"
```

---

I understand that it's not a Magit problem. The buffer freezes because Emacs is trying to apply the diff faces to a 27283992 line buffer? If so, is it possible for Magit to populate a diff-free buffer in the Status buffer?

Thanks!

**Comment by kaushalmodi** [comment]
More along the lines of:

>  is it possible for Magit to populate a diff-free buffer in the Status buffer?

When I ran `git diff --cached --no-prefix --name-only -- | wc -l`, it returned 6194, meaning that roughly 6k files were being modified in that commit.

**Comment by kyleam** [comment]
Here are some links you may be interested in:

 * https://magit.vc/manual/magit/I-changed-several-thousand-files-at-once-and-now-Magit-is-unusable.html
 * gh-2985
 * gh-2982
 * gh-4700

As the first link suggests, Magit just isn't currently a good fit for these scenarios.

**Comment by kaushalmodi** [comment]
Thanks for the reply. I did resort to command line for that large commit.
