### ISSUE TITLE
Help: Wrong type argument: commandp, magit-help

### ISSUE THREAD

**Issue by rusimody** [magit/magit#4719]
Asking to show manual in the magit menu gives
`Wrong type argument: commandp, magit-help`

Function `magit-help` does not seem to exist

Magit version at
`Version: 20220625.1219`
Dash version at
` Version: 20220608.1931`
Emacs version 27.1

Magit uninstalled along with all dependencies, reinstalled and error still present

**Comment by kyleam** [comment]
Thanks for the report.
