### ISSUE TITLE
magit-commit with automatic staging shows wrong diff

### ISSUE THREAD

**Issue by bronger** [magit/magit#4725]
If I hit “c c” for `magit-commit` with unstaged changes, Magit asks me to stage them. I hit “y”, and then I can enter a commit message.

Now the diff Magit shows me is the result of `git HEAD^..HEAD`, in other words, not the index against HEAD but the last already commited change.  But I expect the <strike>latter</strike>first, and until quite recently, it used to be this way.

Note that using `magit-commit` with some things already in the index, everything is fine, i.e. the diff shows the changes in the index.

**Comment by kyleam** [comment]
Thanks for the report.  Confirmed.  This bisects to 2dfeaa68 (magit-commit-diff-1: Use different heuristics, 2022-06-07).

(I don't have any time tonight to look more closely, but I'll try to debug it at some point this week.)
