### ISSUE TITLE
coding system is missing in some el files

### ISSUE THREAD

**Issue by gitqic** [magit/magit#4732]
I am using magit version (20220722.345 [>= 3.3.0-git], Git 2.37.0, Emacs 28.1, windows-nt) from Elpa

When any magit command is called, the error message pops up:

```
Debugger entered--Lisp error: (invalid-read-syntax "?" 6 0)
  read(#<buffer  *load*-612970>)
  load-with-code-conversion("c:/Users/qiche/.emacs.d/elpa/magit-20220722.345/magit-log.el" "c:/Users/qiche/.emacs.d/elpa/magit-20220722.345/magit-log.el" nil t)
  require(magit-log)
  load-with-code-conversion("c:/Users/qiche/.emacs.d/elpa/magit-20220722.345/magit.el" "c:/Users/qiche/.emacs.d/elpa/magit-20220722.345/magit.el" nil t)
  require(magit)
  load-with-code-conversion("c:/Users/qiche/.emacs.d/elpa/magit-20220722.345/magit-status.el" "c:/Users/qiche/.emacs.d/elpa/magit-20220722.345/magit-status.el" nil t)
  (magit-status)
  my-magit-status()
  funcall-interactively(my-magit-status)
  command-execute(my-magit-status)
```
The root cause is magit-log.el contains unicode char at line 1539 in function magit-log-format-author-margin

So it is better to force coding system utf-8 in the file header as in other files like magit.el

same issue happens in magit-section.el (unicode char at line 146 and line 186 version magit-section-20220719.2014)

**Comment by kyleam** [comment]
Thanks for reporting.
