### ISSUE TITLE
invalid-function compat-declare-version

### ISSUE THREAD

**Issue by jangid** [magit/magit#4745]
Dispatch command `C-x g` is producing - invalid-function compat-declare-version

I am using `emacs` from `master` branch. Currently -> `commit 9f692bcd84e2b6e450e154361e1058186e6481a8 (HEAD -> master, origin/master)`

`magit-version` command also produces the same error. But I am using the latest from MELPA (as of today, 30 August, 2022).

Attached is the stack-trace.

Following is the minimal init file to produce the error.

```
;;; init-bug.el --- Emacs configuration -*- lexical-binding: t -*-

;;; Commentary:

;;; Code:

(setq debug-on-error t)

(require 'package)
(add-to-list 'package-archives
	     '("melpa" . "https://melpa.org/packages/"))

(eval-when-compile (package-initialize))

(unless (package-installed-p 'magit)
  (package-install 'magit))

(provide 'init-bug)
;;; init-bug.el ends here

```

Steps to reproduce the issue:

1. save the above content in a file `init-bug.el`
2. `emacs -Q -l init-bug.el`
3. open a file from a git based project
4. `C-x g`

[st.txt](https://github.com/magit/magit/files/9449161/st.txt)

**Comment by jangid** [comment]
Yes. This fixed the issue. Surprisingly, when I upgraded all the packages and restarted Emacs, it didn't solve the issue.

**Comment by kyleam** [comment]
As far as I can tell, there's nothing to do on Magit's end.  Please reopen if I'm mistaken.

**Comment by chief** [comment]
I noticed that reinstalling `compat` only, also fixes the problem.

**Comment by tarsius** [comment]
> I noticed that reinstalling `compat` only, also fixes the problem.

However, if it does not, then still try the full re-installation rain dance. The exact cause may be different for different users.
