### ISSUE TITLE
Local config for textconv does not show the same as `git diff`

### ISSUE THREAD

**Issue by jakob1379** [magit/magit#4749]
Please explain
    (1) what behavior you expected: Magit should show the same output as git diff even  though I use a custom textconv/diff for excel files.
    (2) what behavior you observed:  Magit does not include modified file in  magit  buffer
    (3) and how we can reproduce the issue: Assume we have a script called `xls2txt.py` that takes an excel file as input and pretty prints it, then we only need to specify `git diff` to use this for Excel files in
 1. Setting the git config
```bash
# /.git/config
[diff "excel"]
    textconv = `git rev-parse --show-toplevel`/virt/bin/python `git rev-parse --show-toplevel`/xls2txt.py
```
 2. Config git attributes to determine what files to use the excel-diff with
```bash
# /.gitattributes
*.xlsx   diff=excel
```

Resulting output from magit
```
# magit-diff
1 file changed, 0 insertions(+), 0 deletions(-)
my_file.xlsx | Bin 0 -> 12433 bytes 

new file  my_file.xlsx
```

Version  of  magit: Magit 20220810.1158 [>= 3.3.0-git], Git 2.37.2, Emacs 28.1, gnu/linux

Loading emacs with only magit did not change the result

Setup and results:
![image](https://user-images.githubusercontent.com/17257805/188829447-046127a3-33bd-4e4e-8b93-c3ee84e24b8c.png)

**Comment by kyleam** [comment]
> Local config for textconv does not show the same as git diff

I regularly use Magit with a repo that has a `gpg ...` textconv, so there's probably something more specific going on here.

 I wondered whether it might have something to do with the embedded `git rev-parse --show-toplevel`, but that works at least for the simple case I tested on my end.

<details>
<summary>test</summary>

```sh
set -eu

tdir=$(mktemp -d "${TMPDIR:-/tmp}"/magit-4749-XXXXXXX)
cd "$tdir"

git init
echo '*.foo diff=foo' >.gitattributes
git add .gitattributes
git commit -mattr

git config diff.foo.textconv 'echo `git rev-parse --show-toplevel`'
git config diff.foo.binary true

echo 123 >a.foo
git add a.foo
git commit -m a.foo

echo 456 >>a.foo
git commit -am more
```

</details>

Perhaps something about that environment is causing your custom script to error.  In any case, if you can provide a reproducer, it's more likely that someone will be able to help.

**Comment by jakob1379** [comment]
Changing to the full path produces  the  same situation, where  regular `git  diff <file>` show the proper diff,  magit  does not give  anything. The xls2txt.py is
```python
import pandas as pd
import typer
import typer
from typing import Optional
from pathlib import Path
from rich import print


def main(
    excel_file: Path = typer.Argument(
        ..., readable=True, exists=True, help="Excel file to diff"
    )
):
    df = pd.read_excel(
        excel_file, sheet_name=None, engine="openpyxl", keep_default_na=False
    )
    print(df)


if __name__ == "__main__":
    typer.run(main)
```

**Comment by kyleam** [comment]
> The xls2txt.py is

Thanks, that's useful information, though, for a reproducer, I'm hoping for something both minimal and complete.  That of course involves some work on your end to figure out what the essential pieces are.

After setting up an environment to use xls2txt.py, I'm still unable to trigger the issue.  The textconv filter works on my end.  Here's the script I used to set up the test repo.

<details>
<summary>script</summary>

```
# guix commit: 9b3124b2fc19e83c516606e84932a449e0b2b8a1
$ guix shell python python-pandas python-rich python-typer
```

```sh
#!/bin/sh

set -eu

tdir=$(mktemp -d "${TMPDIR:-/tmp}"/magit-4749-XXXXXXX)
cd "$tdir"

git init

cat <<'EOF' >xls2txt.py
#!/usr/bin/env python3

import pandas as pd
import typer
from typing import Optional
from pathlib import Path
from rich import print


def main(
    excel_file: Path = typer.Argument(
        ..., readable=True, exists=True, help="Excel file to diff"
    )
):
    df = pd.read_excel(
        excel_file, sheet_name=None, engine="openpyxl", keep_default_na=False
    )
    print(df)


if __name__ == "__main__":
    typer.run(main)
EOF

chmod +x xls2txt.py

git add xls2txt.py
git commit -m xls2txt.py

echo '*.xlsx diff=excel' >.gitattributes
git add .gitattributes
git commit -mattr

git config diff.excel.textconv '$(git rev-parse --show-toplevel)/xls2txt.py'

python3 -c 'import pandas as pd; pd.DataFrame({"c1": [1, 2]}).to_excel("o.xlsx", engine = "openpyxl")'
git add o.xlsx
git commit -m o.xlsx

python3 -c 'import pandas as pd; pd.DataFrame({"c1": [1, 3]}).to_excel("o.xlsx", engine = "openpyxl")'
git add o.xlsx
git commit -m 'change o.xlsx'
```

</details>

**Comment by kyleam** [comment]
I'm closing this, as I don't see anything actionable that can be done with the information at hand, but please feel free to follow up with any additional information.

**Comment by jakob1379** [comment]
You can remove the unconfirmed!

I tracked down the issue to be caused by a exception being raised in my custom formatter. Being able to see such errors in any of the magit-buffers would be quite convenient.

Sorry for the uproar.
