### ISSUE TITLE
M-x magit-clone for sourcehut incorrectly automatically prepends a ~

### ISSUE THREAD

**Issue by LudvikGalois** [magit/magit#4753]
Recently, the ability to clone from sourcehut was added. In an attempt to be convenient it automatically prepends a `~` in front of the username, since the usernames of all regular users on sourcehut begin with one. Unfortunately in the future there will be support for more kinds of users on sourcehut and they won't start with a `~`, so this is considered undesirable behaviour.

Relevant excerpt from #sr.ht on libera.chat that spawed this ticket (I'm neither person involved, but I noticed that no-one had raised a ticket yet, ddevault is one of the sourcehut team)

```
<nacho> in case there were Emacs+Magit users around, recent versions of Magit (from MELPA) support cloning Git repositories in git.sr.ht by name out of the box. Ex: "M-x magit-clone u sh:d12frosted/vino".
<ddevault> you should file a bug telling them to use sh:~user/repo
<ddevault> given that we'll support orgs later with a different prefix
```

**Comment by kyleam** [comment]
> Unfortunately in the future there will be support for more kinds of users on sourcehut and they won't start with a `~`, so this is considered undesirable behaviour.

Hmm, fair enough.

So, I think going with something like below and requiring an explicit `~` would be fine.  (Note that we can't quite reduce `magit-clone-url-format` to a single value due to the trailing ".git", and either way I think the flexibility added in )

@nbarrientos what do you think?

<details>
<summary>diff</summary>

```diff
diff --git a/lisp/magit-clone.el b/lisp/magit-clone.el
index 23abff7a..29488725 100644
--- a/lisp/magit-clone.el
+++ b/lisp/magit-clone.el
@@ -94,7 +94,7 @@ (defcustom magit-clone-name-alist
                        (string :tag "User name or git variable"))))
 
 (defcustom magit-clone-url-format
-  '(("git.sr.ht" . "git@%h:~%n")
+  '(("git.sr.ht" . "git@%h:%n")
     (t . "git@%h:%n.git"))
   "Format(s) used when turning repository names into urls.
 
diff --git a/test/magit-tests.el b/test/magit-tests.el
index 82630365..e6230f0e 100644
--- a/test/magit-tests.el
+++ b/test/magit-tests.el
@@ -307,7 +307,7 @@ (ert-deftest magit-process:password-prompt-observed ()
 
 (ert-deftest magit-clone:--name-to-url-format-defaults ()
   (magit-with-test-repository
-   (magit-git "config" "--add" "sourcehut.user" "shuser")
+   (magit-git "config" "--add" "sourcehut.user" "~shuser")
    (magit-git "config" "--add" "github.user" "ghuser")
    (magit-git "config" "--add" "gitlab.user" "gluser")
    ;; No explicit service
@@ -327,14 +327,14 @@ (ert-deftest magit-clone:--name-to-url-format-defaults ()
                          "git@github.com:a/b.git"))
    (should (string-equal (magit-clone--name-to-url "gl:t/s")
                          "git@gitlab.com:t/s.git"))
-   (should (string-equal (magit-clone--name-to-url "sh:x/y")
+   (should (string-equal (magit-clone--name-to-url "sh:~x/y")
                          "git@git.sr.ht:~x/y"))
    ;; Explicit user (long service names)
    (should (string-equal (magit-clone--name-to-url "github:a1/b1")
                          "git@github.com:a1/b1.git"))
    (should (string-equal (magit-clone--name-to-url "gitlab:t1/s1")
                          "git@gitlab.com:t1/s1.git"))
-   (should (string-equal (magit-clone--name-to-url "sourcehut:x1/y1")
+   (should (string-equal (magit-clone--name-to-url "sourcehut:~x1/y1")
                          "git@git.sr.ht:~x1/y1"))))
 
 (ert-deftest magit-clone:--name-to-url-format-single-string ()
```

</details>

**Comment by nbarrientos** [comment]
Hi,

Actually it was me who triggered the conversation in the IRC channel and I even offered to propose a patch myself! :grin: . Then, the kid took over.

Your patch is basically what I had in mind so LGTM.

**Comment by tarsius** [comment]
Reminder to self: Also update forge, emir, emacsmirror db, package-build and melpa recipes. :frowning_face:

**Comment by kyleam** [comment]
@nbarrientos  It seemed likely that was you :)

> Your patch is basically what I had in mind so LGTM.

Thanks for looking it over.
