### ISSUE TITLE
blame is slow on files with a large history when magit-blame-styles includes margin-format 

### ISSUE THREAD

**Issue by geza-herman** [magit/magit#4765]
I use `magit-blame-styles` setting which includes `margin-format`, and I noticed that blaming is very slow.

I think that the issue is that when `magit-blame--make-overlays` calls `magit-blame--make-margin-overlays`, the point is not on `beg`. And even though `magit-blame--make-margin-overlays` receives `_beg`, it doesn't set the point to it. So this function doesn't create overlays for the correct region and potentially it can create overlays for much more lines than it's needed to. If I add an `(goto-char _beg)`, then the issue seems to be fixed:

```elisp
(defun magit-blame--make-margin-overlays (chunk revinfo _beg end)
  (save-excursion
    (let ((line 0))
      (goto-char _beg)
      (while (< (point) end)
        (magit-blame--make-margin-overlay chunk revinfo line)
        (forward-line)
        (cl-incf line)))))
```

**Comment by tarsius** [comment]
Thanks for the report!
