### ISSUE TITLE
Very slow desktop restores (astonishingly slow with magit-wip-mode on)

### ISSUE THREAD

**Issue by nickalcock** [magit/magit#4768]
This is with Emacs 28.1.90 (with native compilation enabled) and Magit 3.3.0 installed from ELPA.

So I have a rather, uh, bloated Emacs right now: it has 1600-odd buffers, mostly header files in various git repos (largely courtesy of CEDET's tendency to open files for parsing and forget to close them again).

Starting Emacs takes a few minutes when you have this many buffers, but you shouldn't have to wait for hours. Unfortunately, as of late it seems I do, because multiple parts of magit (magit itself, magit-wip-mode, and likely other things too) all of which are invoked at desktop load time for every relevant buffer, all call 'magit-inside-worktree-p' and 'magit-file-tracked-p' and a bunch of similar git-invoking functions. Each of these ends up calling git with various args (git rev-parse --is-inside-work-tree, git status --untracked-files, etc)... the net effect of which is that I was sitting there with git getting forked off over a thousand times a second and three hours in Emacs *still* hadn't finished starting. An hour per 500 buffers is way too slow! And this is on a beefy server with enough RAM to keep everything cached always, with git taking only milliseconds per invocation at most. This is a *best* case.

With git-wip-mode turned off, startup takes "only" about fifteen minutes (!) with about 200 forks of git status --untracked-files per second. Note that I do not have tens of thousands of buffers open, so it seems to be repeatedly reinvoking many of these things for files it previously invoked them for only a few seconds earlier.

This really needs at least some rudimentary results caching (maybe we can make cache invalidation trivial by wiping the cache whenever we return to the command loop), so that at least individual commands (like desktop-load) don't take literally hours doing the same thing over and over again. I'll see if I can hack something up over the weekend.

One sample backtrace:

  call-process("git" nil (t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color$
  process-file("git" nil (t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" "color$
  magit-process-file("git" nil (t nil) nil "--no-pager" "--literal-pathspecs" "-c" "core.preloadindex=true" "-c" "log.showSignature=false" "-c" $
  magit-process-git((t nil) ("rev-parse" "--is-inside-work-tree"))
  magit-git-output(("rev-parse" ("--is-inside-work-tree")))
  magit-git-true("rev-parse" ("--is-inside-work-tree"))
  magit-rev-parse-true("--is-inside-work-tree")
  magit-inside-worktree-p(t)
  magit-wip-after-save-local-mode-turn-on()
  magit-wip-after-save-mode(1)
  magit-wip-mode(1)
  desktop-create-buffer(208 "/pkg/linux-kernel-headers/5.10.13/usr/include/linu..." "metadesc_defines.h" c-mode (auto-fill-mode abbrev-mode over$
  load-with-code-conversion("/home/oranix/.emacs.desktop" "/home/oranix/.emacs.desktop" t t)
  load("/home/oranix/.emacs.desktop" t t t)

**Comment by phil-s** [comment]
Cross-referencing with:

* https://github.com/magit/magit/issues/4823
* https://github.com/magit/magit/issues/4900#issuecomment-1469063589

**Comment by tarsius** [comment]
I made some changes. Did it help?

**Comment by tarsius** [comment]
That commit should result in a noticeable speedup.
