### ISSUE TITLE
`update-ref` cannot be removed in `git rebase -i`

### ISSUE THREAD

**Issue by ojab** [magit/magit#4776]
`Magit 20220926.56 [>= 3.3.0-git], Git 2.38.0, Emacs 28.2, gnu/linux`

git-2.38.0 added [`--update-refs`](https://github.blog/2022-10-03-highlights-from-git-2-38/) option for `git rebase` that updates parent branches, in interactive mode it looks like `update-ref refs/heads/test1` line.
This line cannot be actioned on in magit's `git-rebase-mode` like generic commits.

Simple reproducer:
```sh
#!/bin/sh

mkdir /tmp/tst
cd /tmp/tst
git init -b main
echo 1 > 1
git add 1
git commit -m 'first commit'
git checkout -b test1
echo 2 > 2
git add 2
git commit -m 'branch commit'
git checkout -b test2
git checkout main
echo 2 > 1
git add 1
git commit -m 'second commit'
git checkout test2
git rebase -i --update-refs main
```
leads to the buffer with
```
pick d9e7b8a branch commit
update-ref refs/heads/test1


# Rebase 4f24d42..d9e7b8a onto 4f24d42 (2 commands)
…
```
and second line apparently cannot be removed/moved/etc. Probably it should behave like a generic commit.

**Comment by tarsius** [comment]
I've added the argument and updated reflog output.

@kyleam I am not familiar with the current rebase action implementation. Could you please implement this? Thanks!

**Comment by kyleam** [comment]
> I've added the argument and updated reflog output.

Nice, thanks.

> @kyleam I am not familiar with the current rebase action implementation. Could you please implement this? Thanks!

Sure.  It's on my list to look into (though it may be a couple of weeks before I find the time to do so).

**Comment by thejan2009** [comment]
Not sure if this is the right place, but I think enabling this option would also be useful for `magit-commit-instant-fixup`. I tried enabling the option with global config `git config --global rebase.updateRefs true` but it seems it wasn't picked up by `magit-rebase-interactive-1`.

**Comment by kyleam** [comment]
I've pushed a branch ([km/update-ref](https://github.com/magit/magit/compare/master...km/update-ref)) that adds `update-ref` support to git-rebase.el.  Based on light testing, it seems to work, but I'll plan to test it a bit more tomorrow night before applying to master.
