### ISSUE TITLE
magit-branch-delete switches to detached mode if upstream branch is remote

### ISSUE THREAD

**Issue by DamienCassou** [magit/magit#4785]
1. Open magit in any repository
2. Checkout the `master` (or `main`) branch
3. Create a branch `foo` pointing at the parent commit of `HEAD`
4. Checkout `foo`
5. Make sure the upstream branch is `origin/master`
6. Type `b k` to delete `foo`
7. You get a message "Branch foo is checked out.  [d]etach HEAD & delete, [c]heckout origin/master & delete, [a]bort"
8. Choose "[c]heckout origin/master & delete" by typing `c`

Actual: There is no current branch and Git is in detached mode
Expected: The current branch is `master`

    M-x magit-version RET

Magit v3.3.0-452-g557ab2c0, Git 2.36.2, Emacs 28.2, gnu/linux

**Comment by tarsius** [comment]
Ah, this command again:

```
  ;; One would expect this to be a command as simple as, for example,
  ;; `magit-branch-rename'; but it turns out everyone wants to squeeze
  ;; a bit of extra functionality into this one, including myself.
```

:grin: 

Anyway, it's simple enough to improve it a bit more.

**Comment by DamienCassou** [comment]
> Ah, this command again

I'm sorry. Thank you very much for your work!
