### ISSUE TITLE
“Bisect Rest” shows confusing info with `--first-parent`

### ISSUE THREAD

**Issue by sellout** [magit/magit#4786]
“Bisect Rest” has a number after it, which is the number of commits in the log/graph displayed while bisecting. However, when using `--first-parent`, this number may be much larger than the number of commits that are testable in the bisect. E.g., in a recent bisect, I had “Bisect Rest (103)”, but the corresponding `git bisect run` output showed “Bisecting: 6 revisions left to test after this (roughly 3 steps)”.

I don’t mind the graph output being complete (easy enough to read which commits are down the main column), but without `magit-bisect-show-graph`, the log output is also confusing. So I’m thinking `magit-insert-bisect-rest` should replace
```elisp
(and magit-bisect-show-graph "--graph")
```
with something like
```elisp
(if magit-bisect-show-graph
    "--graph"
  (and (transient-arg-value "--first-parent" (transient-args 'magit-bisect))
       "--first-parent"))
```
The `--first-parent` case there should also result in a more reasonable number next to “Bisect Rest”, but it would still require work in the `--graph` case.

**Version**: Magit 20220916.1716 [>= 3.3.0-git], Git 2.34.1, Emacs 28.1, darwin

**Comment by tarsius** [comment]
I've done something similar.

**Comment by sellout** [comment]
Thanks!
