### ISSUE TITLE
magit-get-submodule-name not working

### ISSUE THREAD

**Issue by declantsien** [magit/magit#4793]
`magit-list-module-names` and `magit-get-submodule-name` returns `(nil nil ...)`
and `nil`.

I believe name command from `git submodule--helper` has been removed
https://github.com/git/git/blob/v2.38.1/builtin/submodule--helper.c#L3407

**Comment by kyleam** [comment]
Thanks, that was removed in 76d63ddc46 (submodule--helper: remove unused "name" helper, 2022-09-02), part of the 2.38.0 release.

**Comment by kyleam** [comment]
At first glance, I'm not sure whether 3c057da7 (magit-get-submodule-name: Use "git submodule--helper name", 2020-09-08) was  1) optimization and/or code simplification or 2) a bug fix for an edge case.  If it's the former, we can restore that code (perhaps guarding it by a version check).

**Comment by tarsius** [comment]
I think it's the former.

I brought up the removal of `name` and `list` at https://lore.kernel.org/git/87czatrpyb.fsf@bernoul.li, and work is under way to provide substitutes.

**Comment by kyleam** [comment]
@tarsius great, thanks for the link

**Comment by tarsius** [comment]
I've changed it to use the old implementation for this release.
