### ISSUE TITLE
`magit-list-submodules` is empty with a fresh checkout

### ISSUE THREAD

**Issue by declantsien** [magit/magit#4801]
Let's say I have a git repo(`/tmp/gitrepo2`) with a submodule configuration like this

    [submodule "subdir/gitrepo1"]
    	path = subdir/gitrepo1
    	url = /tmp/gitrepo1

Then clone `/tmp/gitrepo2` to `/tmp/gitrepo3` with

    git clone /tmp/gitrepo2 /tmp/gitrepo3

`magit-list-submodules` gave me an empty list in `/tmp/gitrepo3`

**Comment by tarsius** [comment]
Currently this is supposed to only list populated modules. Maybe it would make sense to (optionally) also list other modules, but that would have consequences that would have to be considered first. Some of the functions that collect information for display may currently assume that they are only feed populated modules.
