### ISSUE TITLE
*ERROR*: Wrong number of arguments: ((eshell-preoutput-filter-functions t).....

### ISSUE THREAD

**Issue by sweet66** [magit/magit#4802]
### Expected behaviour
`c  c` from a magit-status buffer lets me fill the Summary and the Body of my commit message, so I can press `C-c C-c `to complete the commit.

### Actual behaviour

```
  1 git … commit --
hint: Waiting for your editor to close the file...
Waiting for Emacs...
*ERROR*: Wrong number of arguments: ((eshell-preoutput-filter-functions t) (fn &optional next-buffer killed-one filepos) "Honor `with-editor-server-window-alist' (which see)." (let ((server-window (save-current-buffer (set-buffer (or next-buffer (current-buffer))) (if with-editor-mode (progn (setq with-editor-previous-winconf (current-window-configuration)))) (with-editor-server-window)))) (funcall fn next-buffer killed-one filepos))), 5
error: There was a problem with the editor '/Applications/Emacs.app/Contents/MacOS/bin/emacsclient --socket-name=/var/folders/10/c15_wl850s13j3n9k9ynzr3w0000gn/T/emacs501/server'.
Please supply the message using either -m or -F option.
```

### Magit and Git version
 Magit v3.3.0-461-gccd82ffe, Git 2.21.1

### Emacs version
GNU Emacs 28.2 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2022-09-13

###  #4221
 tried to do that.  It still doesn't work.

**Comment by tarsius** [comment]
Based on `((eshell-preoutput-filter-functions t) (fn &optional next-buffer killed-one filepos) "Honor `with-editor-server-window-alist' (which see)." (let ((server-window (save-current-buffer (set-buffer (or next-buffer (current-buffer))) (if with-editor-mode (progn (setq with-editor-previous-winconf (current-window-configuration)))) (with-editor-server-window)))) (funcall fn next-buffer killed-one filepos)))` I can tell that your `with-editor` is outdated and does not include the fix from #4221. Please update `with-editor`.

**Comment by sweet66** [comment]
> Based on `((eshell-preoutput-filter-functions t) (fn &optional next-buffer killed-one filepos) ...)` I can tell that your `with-editor` is outdated and does not include the fix mentioned in #4221. Please update `with-editor`.

`with-editor` update to the latest version and restart emacs.  still prompt above error.  `with-editor` version is: 
```
Head:     master make: Suppress warning about obsolete autoload package
Merge:    origin/master make: Suppress warning about obsolete autoload package
Tag:      v3.2.0 (27)
```
I installing from the Git Repository.  remake after update.

**Comment by tarsius** [comment]
There is no function with the signature `(fn &optional next-buffer killed-one filepos)` in this version of `with-editor`. Before c4768f51c7415119519b4626d8643d60e584098c there was.

I suspect that you have installed `with-editor` twice. When you switched to installing `with-editor` from the repository, did you also delete the version previously installed using `package`? Try `M-x find-library RET with-editor RET` and see whether that takes you do the file in the repository.

**Comment by sweet66** [comment]
> There is no function with the signature `(fn &optional next-buffer killed-one filepos)` in this version of `with-editor`. Before [magit/with-editor@c4768f5](https://github.com/magit/with-editor/commit/c4768f51c7415119519b4626d8643d60e584098c) there was.
> 
> I suspect that you have installed `with-editor` twice. When you switched to installing `with-editor` from the repository, did you also delete the version previously installed using `package`? Try `M-x find-library RET with-editor RET` and see whether that takes you do the file in the repository.

Oh.  You're right.  There are indeed two 'with-editor'.  Thanks a lot.
