### ISSUE TITLE
Teach `magit-commit-instant-fixup` about `--update-refs`

### ISSUE THREAD

**Issue by tarsius** [magit/magit#4805]
> Not sure if this is the right place, but I think enabling this option would also be useful for `magit-commit-instant-fixup`. I tried enabling the option with global config `git config --global rebase.updateRefs true` but it seems it wasn't picked up by `magit-rebase-interactive-1`.

_Originally posted by @thejan2009 in https://github.com/magit/magit/issues/4776#issuecomment-1293379983_

**Comment by tarsius** [comment]
> I tried enabling the option with global config `git config --global rebase.updateRefs true` but it seems it wasn't picked up by `magit-rebase-interactive-1`.

That's surprising, are you sure? I don't see anything that would actively prevent that from working.

**Comment by thejan2009** [comment]
> That's surprising, are you sure? I don't see anything that would actively prevent that from working.
Sorry about that, it seems my config is borked. It works as expected in a plain installation.

**Comment by kyleam** [comment]
It sounds like there is nothing to do here.  Please reopen if I'm missing something.
