### ISSUE TITLE
Add support for git-rebase --update-refs

### ISSUE THREAD

**Issue by To1ne** [magit/magit#4815]
Since git 2.38 a new option `--update-refs` exists on `git-rebase`, see https://github.blog/2022-10-03-highlights-from-git-2-38/#rebase-dependent-branches-with-update-refs

This allows you to rebase a branch, and also rebase all other branches that point to one of the commits that being rebased.

This is so far not supported by magit.

It's easy to add the option, but there's more to it. There's also a new action in interactive rebase:

![20221115_07h03m23s_grim](https://user-images.githubusercontent.com/121621/201841451-5516943b-e694-4a83-a287-1b9f87d56833.png)

**Comment by tarsius** [comment]
We added support for that two weeks ago, see #4776.

**Comment by To1ne** [comment]
I'm sorry Jonas, I searched for a bit, but couldn't find anything. I should have put more effort into that. Thanks! You're the best.
