### ISSUE TITLE
v. 20221208.1848 contains a UNIX-specific encoding instruction in magit-autoloads.el, breaking the install on Windows

### ISSUE THREAD

**Issue by tomdavey** [magit/magit#4831]
Hello folks, 

Please see the title of the issue. The offending encoding instruction lies in the section "Local Variable" at the end of magit-autoloads.el. The instruction says: 

;; coding: utf-8-emacs-UNIX

But it should say, as in previous Magit versions: 

;; coding: utf-8

When I installed v. 20221208.1848 from MELPA using package.el, I received this message: "Error loading autoloads: (user-error Local variables entry is missing the suffix) [4 times]". 

Directly afterwards, when starting a new instance of Emacs with v. 20221208.1848, start-up fails with messages about being unable to find Magit functions. I'm using Emacs 29.0.50 on Windows 10 Pro 19045.2364. 

Hope this helps! Thanks for the most amazing package in all of Emacs. 

Tom Davey

**Comment by tarsius** [comment]
This file is generated by the package manager. Magit (or any other package) has no control over such details as the encoding, it can only specify what entries should be added to the file.

Emacs 29 comes with major changes to how autoload files are generated. https://debbugs.gnu.org/cgi/bugreport.cgi?bug=53529 might be relevant to this issue. You should probably report a bug in that issue tracker.

**Comment by tarsius** [comment]
But before you do that, update Emacs, restart, and then recompile Magit before trying to reproduce.

**Comment by tomdavey** [comment]
Thanks for this advice. Will do!
