### ISSUE TITLE
`--force` is missed when I made a push to another branch

### ISSUE THREAD

**Issue by catap** [magit/magit#4832]
When I push `P` to make a push from magit, I've decided to add `--force` via `-F`; also I've selected `another branch` as `o`, selected from and to where... and git fails because my push wasn't fast-forward.

When I've checked a git command, I've discovered that it had missed `--force` option.

**Comment by kyleam** [comment]
Thanks for reporting.  I can trigger this as well.

> I've discovered that it had missed `--force` option.

More generally, `magit-push-arguments` is returning nil, dropping any options.

It looks like the value is being lost following the second `completing-read` call.

With the following on top of Magit 8fd16d34 (and Transient c6cf2f2):

```diff
diff --git a/lisp/magit-base.el b/lisp/magit-base.el
index 0a9ab29d..5245a615 100644
--- a/lisp/magit-base.el
+++ b/lisp/magit-base.el
@@ -585,9 +585,16 @@ (defun magit-builtin-completing-read
       (fset 'completion-pcm--all-completions
             'magit-completion-pcm--all-completions))
     (let ((ivy-sort-functions-alist nil))
-      (completing-read prompt choices
-                       predicate require-match
-                       initial-input hist def))))
+      (message "---\ntransient-current-command before cr: %S"
+               transient-current-command)
+      (message "push args before cr: %S" (magit-push-arguments))
+      (prog1
+          (completing-read prompt choices
+                           predicate require-match
+                           initial-input hist def)
+        (message "transient-current-command after cr: %S"
+                 transient-current-command)
+        (message "push args after cr: %S\n---" (magit-push-arguments))))))

 (defun magit-completing-read-multiple
     (prompt choices &optional sep default hist keymap)
```

I see the following after calling `magit-push-other`, selecting `--dry-run`, and then calling `magit-push-other` (`P-no`):

```
---
transient-current-command before cr: magit-push
push args before cr: ("--dry-run")
transient-current-command after cr: magit-push
push args after cr: ("--dry-run")
---
---
transient-current-command before cr: magit-push
push args before cr: ("--dry-run")
transient-current-command after cr: nil
push args after cr: nil
---
Running git push -v origin other:other
```

I'm out of time to dig into this more tonight, but it's interesting that the transient-current-command and args are lost only after the second completing-read call.

**Comment by kyleam** [comment]
Filed a transient issue (magit/transient#229).  Until that's resolved, it probably makes sense to leave this issue open for visibility purposes to avoid duplicate issues being filed against Magit.

**Comment by tarsius** [comment]
"Fixes" but see https://github.com/magit/transient/issues/229.
