### ISSUE TITLE
magit-show-commit doesn't show the right commit details after a reverse blame

### ISSUE THREAD

**Issue by kvaneesh** [magit/magit#4834]
magit-version gives

Magit 20221208.1848 [>= 3.3.0.50-git], Git 2.38.1, Emacs 29.0.60, gnu/linux

magit-blame-copy-hash (keybinding to alt-w) shows the right commit id. While using magit-show-commit (keybinding to RET) shows different commit details.

**Comment by kyleam** [comment]
Thanks for reporting.

I've pushed a fix to [km/commit-at-point-blame-reverse](https://github.com/magit/magit/compare/master...km/commit-at-point-blame-reverse).  I might be overlooking a reason for why `magit-commit-at-point` and `magit-branch-or-commit-at-point` should only consider `addition` blame chunks, so I'll wait a day or two for any objections before pushing.
