### ISSUE TITLE
Please bump the Compat dependency to 29.1.1.0

### ISSUE THREAD

**Issue by minad** [magit/magit#4844]
* Follow up on https://github.com/magit/magit/issues/4836
* https://github.com/emacs-compat/compat/commit/887ec71fa3a90bc0d333ae9c333436148e909dbd
* https://github.com/magit/magit/issues/4841#issuecomment-1373810769

Bumping the version ensures that Magit is recompiled with the (bytecode-incompatible) Compat release. The new version 29.1.1.0 of Compat should appear in the GNU ELPA archive soon.

**Comment by tarsius** [comment]
Done.

**Comment by minad** [comment]
Thanks for the quick action!

**Comment by SL-RU** [comment]
Thank you! I've updated packages and faced this problem!

**Comment by minad** [comment]
@SL-RU In case you observe any future issues, it should always help to reinstall both Compat and Magit. First uninstall both and then install Magit, which will pull in the newest Compat as dependency.

**Comment by tarsius** [comment]
But before you do that, try if simply restarting Emacs does the trick.

**Comment by minad** [comment]
@tarsius Good point!
