### ISSUE TITLE
Symbol’s function definition is void: compat-assoc

### ISSUE THREAD

**Issue by edrx** [magit/magit#4852]
I'm getting this error when I try to push my changes with magit-push:
```
error in process sentinel: magit-section-cache-visibility: Symbol’s function definition is void: compat-assoc
error in process sentinel: Symbol’s function definition is void: compat-assoc
```
The error happened in both Emacs29 and in a very recent Emacs30, and it remained in both Emacs versions after upgrading to packages with M-x list-packages and then typing U and all confirmations, and then running (package-recompile-all) and restarting Emacs. These are the versions of magit and compat that I have here:
```
Magit 20230120.1616 [>= 3.3.0.50-git], Git 2.30.2, Emacs 30.0.50, gnu/linux
Compat 29.1.2.0
```
I hope that this is something easy to fix... I won't have time tonight for finding the change that caused the error, but I can try tomorrow if you need.

**Comment by minad** [comment]
See #4841 and #4836.

**Comment by edrx** [comment]
I use just package.el - I don't use use-package - so what worked for me was this:
```
(package-initialize)
(package-refresh-contents)
(package-delete (ee-package-desc 'magit-section))
(package-delete (ee-package-desc 'magit))
(package-install 'magit-section)
(package-install 'magit)
```
but ee-package-desc is an eev-ism, defined here: <http://angg.twu.net/eev-current/eev-elinks.el.html#ee-package-desc>... the translation of the sexps above to a recipe that "normal" package.el users can use is: delete both magit-section and magit by hand, and install them again.

Deleting and reinstalling only magit and compat did not work for me, but deleting and reinstalling magit and magit-section worked... but I don't know why and I don't have time to discover =(

**Comment by tarsius** [comment]
I've edited the other thread to mention magit-section earlier.
