### ISSUE TITLE
Don't lose written commit message when user gets GPG password wrong

### ISSUE THREAD

**Issue by chriselrod** [magit/magit#4879]
1. Enable GPG pinentry
2. Write a commit message.
3. Enter password wrong.

This gives a magit error, and the commit message is gone.
I occasionally mistype the password. It'd be nice not to lose the commit message, but to instead have the chance to reenter the password without having to go through the transients to get to the message again and then need to retype it.

**Comment by chriselrod** [comment]
> The message is saved.

Thanks, I didn't know that. I just tried this and it worked.

**Comment by tarsius** [comment]
> I occasionally mistype the password. It'd be nice [to] have the chance to reenter the password

We cannot do that. We call `git commit`, which calls `$EDITOR` which we have arranged to be `emacsclient ...`. When you finish with `C-c C-`, `emacsclient` terminates and then `git` decides that it has to ask you for the passphrase. If you mistype it at this point, the Emacs/Magit has already closed the buffer and it is `git` that is informed about the passphrase being wrong. It then decides to abort and even to delete the file in which the message is stored.

Providing a way for you to get back the message in `git-commit-mode` is the best we can do.
