### ISSUE TITLE
`magit-revision-show-gravatars` hides `magit-diff-revision-summary` face

### ISSUE THREAD

**Issue by peniblec** [magit/magit#4896]
## Version info

`emacs-version`

> GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.35, cairo version 1.17.6) of 2023-02-05

`magit-version`

> Magit 20230302.2135 [>= 3.3.0.50-git], Git 2.39.2, Emacs 30.0.50, gnu/linux
(From MELPA)

> Magit v3.3.0-542-gb926ab0e, Git 2.39.2, Emacs 30.0.50, gnu/linux
(From the repo)

## In a nutshell

Setting `magit-revision-show-gravatars` makes `magit-rev-insert-format` paint the whole `git-log` output with `'face 'fixed-pitch`, which hides the summary line's `'font-lock-face 'magit-diff-revision-summary`.

(`magit-diff-revision-summary-highlight` is unaffected, IIUC because it is applied via overlays which have priority over `'face 'fixed-pitch`).

## Repro steps

From the top of the Magit repo:

``` sh
# Somehow git-commit-elisp-text-mode undoes the damage, so get rid of 
# it in order to reproduce.
rm .dir-locals.el
cat <<EOF >repro.el
(require 'outline)

(custom-set-variables
 '(magit-revision-show-gravatars t))
(custom-set-faces
 '(magit-diff-revision-summary ((t (:inherit (outline-1 magit-diff-hunk-heading)))))
 '(magit-diff-revision-summary-highlight ((t (:inherit (outline-1 magit-diff-hunk-heading-highlight))))))
EOF
make emacs-Q
```

From there:

```
M-x load-file repro.el
C-x g   ; magit-status
SPC RET ; magit-diff-show-or-scroll-up (main)
```

Observations:

* The summary line is not displayed with the `magit-diff-revision-summary` face.
* Setting `magit-revision-show-gravatars` to nil and reverting with `g` fixes this.

More observations:

```
M-n C-p     ; move point right before summary line
M-: (describe-char (1+ (point)))
```

Relevant excerpt:

    There are text properties here:
      face                 fixed-pitch
      font-lock-face       (magit-diff-revision-summary)
      fontified            t

## Comments

No patch yet; off the top of my head, I see two paths we could explore, so I wanted to get a second opinion before going too far in the wrong direction:

1. apply `fixed-pitch` locally, to the `(Author|Commit)(Date)?:` lines, instead of the whole `git-log` output; maybe in `magit-insert-revision-gravatar` or `magit-insert-revision-gravatar-cb`?
2. if the goal is to ensure consistent alignment when the UI uses `variable-pitch`, look into using `:align-to` properties with `(elisp) Pixel Specification`, instead of `fixed-pitch`?

Happy to explore either option if they make sense.  FWIW, I have only very quickly skimmed the context re. the recent `fixed-pitch` additions in #4861 and #4876; apologies if I've missed something (thinking about this some more, it' s not obvious to me why `face fixed-pitch` has priority over `font-lock-face (magit-diff-revision-summary)` since `font-lock-mode` is enabled in revision buffers 🤔).

**Comment by peniblec** [comment]
No objection to a revert; both "exploratory paths" I mention remain vaporware at this stage on my end.

FWIW, assuming the feature in question is variable-pitch support: I don't think it's wholly misguided; I'm peppering some variable-pitch here & there in my personal theme to denote "read-only" UI elements (in contrast to editable text), and it feels like an effective visual cue (to me), so I understand the appeal.

So I'd say it was worth a shot :shrug: and even if this "sloppy implementation" gets unceremoniously reverted, at least it will work as a signpost for future intrepid variable-pitchers.

**Comment by sellout** [comment]
FWIW, I don’t mind that change being reverted. I’ve been continuing to use my approach that just positions the gravatar at the beginning of the line, avoiding the variable-pitch alignment issue.

**Comment by peniblec** [comment]
Thanks @tarsius :pray:
