### ISSUE TITLE
Magit occasionally loses log limit

### ISSUE THREAD

**Issue by glasserc** [magit/magit#4898]
I have noticed that under certain circumstances, issuing a command to get the revision history for the project I'm working on will not pass the `-n` argument. I'm working on a project with a long history so when this happens, my CPU spikes and emacs becomes nonresponsive for a while. Typically this is not a problem, but some command seems to cause it to drop the limit from future log commands.

To demonstrate this, we need a project with a bunch of history. I've used `magit/magit`, which I cloned to `~/tmp`. Each of the following sets of steps assumes pwd being `~/tmp/magit` and I am recording them from an emacs from `magit-emacs-Q-command`.

Steps to reproduce:

- Start `emacs`
- `C-x C-f README.md RET`
- `M-x magit-status RET`
- Pressing `l` brings up the transient to retrieve logs. I'm not 100% sure about the name of this transient but I'll call it the `magit-log` transient for the purposes of this issue.
- We can observe that the first two lines of the transient are `Commit limiting: -n Limit number of commits (-n256)`, which is what we expect.
- We can also `C-g` out of the transient and open a specific file: `C-x C-f lisp/magit.el RET`
- `M-x magit-file-dispatch RET`
- If we press `l` to log this file, it brings up a `magit-log` buffer. Jumping to the end of this buffer using `M->` shows us on line 257, with `Type + to show more history`. This is also what we would expect.
- Press `+`. If we jump to the end of the buffer again using `M->` we see that we are on line 515, demonstrating that the log limit has been roughly doubled. There is still a `Type + to show more history`.
- `M-x magit-status RET`
- Back in the `magit-status` buffer, we press `l` to bring up the `magit-log` transient again.

Expected behavior:

We should still see `-n256`. Dispatching this log command should complete quickly and only show a subset of the project's history.

Actual behavior:

- We observe that now, the first two lines of the transient are: `Commit limiting: -n Limit number of commits (-n)`, without a limit.
- If we press `l` again to dispatch the log, the laptop gets very hot for a few seconds.
- The `magit-log: magit` buffer that is eventually shown has 14458 lines in it. The very last one reads something like `a55e3f54 * Initial commit     Marius Vollmer   15 years`.

Version information: `Magit 20230131.1151 [>= 3.3.0.50-git], Git 2.38.4, Emacs 28.2, gnu/linux`. This is NixOS 22.11. 

<details>
<summary>The command I got from `magit-emacs-Q-command`</summary>
`/run/current-system/sw/bin/emacs -Q --eval \(setq\ debug-on-error\ t\) -L /home/ethan/.emacs.d/elpa/compat-29.1.3.1/ -L /home/ethan/.emacs.d/elpa/dash-20221013.836/ -L /home/ethan/.emacs.d/elpa/transient-20230130.2135/ -L /home/ethan/.emacs.d/elpa/with-editor-20230118.1656/ -L /home/ethan/.emacs.d/elpa/magit-20230131.1151/ -L /home/ethan/.emacs.d/elpa/magit-section-20230106.1659/ -L /home/ethan/.emacs.d/elpa/git-commit-20230103.2224/ -l /home/ethan/.emacs.d/elpa/magit-20230131.1151/magit`
</details>

**Comment by kyleam** [comment]
Thanks for the report and the detailed steps to trigger the issue.
