### ISSUE TITLE
Performance issue moving in the magit-diff buffer

### ISSUE THREAD

**Issue by Ergus** [magit/magit#4900]
Hi:

When using magit and moving cursor on the `magit-diff` buffer emacs takes several seconds just to move the cursor (~5-10 s just to move cursor from one point to the next).

I profiled and these were the results:

```
           1 100% - ...
           1 100%  - eq
           1 100%   - magit-diff-type
           1 100%    - let
           1 100%     - if
           1 100%      - progn
           1 100%       - cond
           1 100%        - let
           1 100%         - cond
           1 100%          - or
           1 100%           - magit-rev-eq
           1 100%            - magit-commit-p
           1 100%             - magit-rev-verify
           1 100%              - magit-git-string-p
           1 100%               - magit-process-git
           1 100%                - magit-process-file
           1 100%                   process-file
           0   0%    Automatic GC
```

It seems like magit calls `process-file` in `magit-section-post-command-hook` throw `magit-section-update-highlight`

So, is it really needed to call something "expensive" like `process-file` on every move of the cursor in magit-diff? This is very bad specially in Tramp and MS-windows. 

Is there some hook I could use to stop this?

In case it is useful here I attach my magit config:

```
(use-package magit :defer t
  :init
  (setq-default magit-git-executable (executable-find "git")
		magit-define-global-key-bindings nil
		magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1
		;; This may help for tramp
		auto-revert-buffer-list-filter 'magit-auto-revert-repository-buffer-p
		magit-git-debug t
		magit-process-display-mode-line-error nil ;; magit errors in modeline
		;; This may help on MS_Windows
		magit-refresh-status-buffer nil
		magit-diff-highlight-indentation nil
		magit-revision-insert-related-refs nil
		magit-diff-highlight-trailing nil
		magit-diff-paint-whitespace nil
		magit-diff-highlight-hunk-body nil
		magit-diff-refine-hunk nil
		)
  :config
  (keymap-unset magit-section-mode-map "C-<tab>" t) ;; magit-section-cycle shadows tab next

  (add-hook 'magit-log-mode-hook (lambda nil
				   (setq-local show-trailing-whitespace nil
					       tab-width 4)))
						   
  (remove-hook 'magit-refs-sections-hook 'magit-insert-tags))
```

In the config you can see I already set multiple options to `nil`, because the magit performance on ms-windows was just terrible (starting windows processes is terribly slow and MS doesn't care... but then you add antivirus and things get much worst).

However... I don't find any information in the documentation for this one.

Thanks in advance,

Ergus

**Comment by tarsius** [comment]
From a quick look, it seems `git rev-parse --verify COMMIT` is called twice when moving in a diff. If that takes 5-10 seconds, then something else is very broken, as in:

> (starting windows processes is terribly slow and MS doesn't care... but then you add antivirus and things get much worst)

It's not like we are starting dozens of processes here. Two seems reasonable. I would look into the antivirus virus.

You could also remove `magit-diff-highlight` from `magit-section-unhighlight-hook`, but then of course diffs wouldn't be highlighted properly anymore.

**Comment by Ergus** [comment]
Hi Tarsius:

Thanks for replying... I have faced this same issue using Tramp for a very long time... So, it is not only a MS-windows issue, windows just makes it worst (as everything else ;) )

However, I will try your hook workaround... however I still thing that these calls while moving may be completely avoided considering that the buffer is already drawn... but probably I am totally wrong here...

Best, Ergus

**Comment by phil-s** [comment]
It seems like `magit-section-update-highlight` results in calls to git in diff buffers but not revision buffers?

`trace-function` on `process-file` shows me that moving point from one file/hunk to another tends to result in multiple *pairs* of calls to `git rev-parse`, like so:

```
git rev-parse --verify origin/master..^{commit}
git rev-parse --verify HEAD^{commit}
git rev-parse --verify origin/master..^{commit}
git rev-parse --verify HEAD^{commit}
git rev-parse --verify origin/master..^{commit}
git rev-parse --verify HEAD^{commit}
```

(That example collection of six calls resulting from a single command/movement.)

In some brief testing, I've seen anything from 1 pair to 4 pairs (I imagine more are possible, depending on circumstances).  The same calls are repeated when I move back to a position I'd previously moved to.

In my brief tests, the argument to the first call of each pair is the argument I gave to the diff command; the argument to the second call is always HEAD^{commit}; and the pairs seem to be identical every time.  I don't know whether that's always true, but if it is then it seems cacheable.

**Comment by tarsius** [comment]
We use a cache to avoid such repeated calls during *buffer refresh*. Magit commands do their work and when they are done they (in most case implicitly/indirectly) call `magit-refresh` to trigger the refresh. The existing cache only covers identical calls to git *during* that refresh.

The scope of the cache cannot be extended to also cover the calls to git while the command is doing its thing, because many commands have side-effects, which would would require cache invalidation.

But maybe we should use an additional "cache" here. I haven't looked into it yet, but I am guessing that we can calculate these values up front (i.e., when the buffer is refreshed) and store them in the appropriate section objects and (probably) `magit-diff-type` would have to be taught to use these values, if present, instead of calling git.

**Comment by Ergus** [comment]
That's my first guess; when moving point the repo does not change, so It is unclear for me why `magit` needs to repeat redundant external calls.

**Comment by Ergus** [comment]
> But maybe we should use an additional "cache" here. I haven't looked into it yet, but I am guessing that we can calculate these values up front (i.e., when the buffer is refreshed) and store them in the appropriate section objects and (probably) `magit-diff-type` would have to be taught to use these values, if present, instead of calling git.

Just to mention... emacs-29 added a new with-memoization macro that seems could be useful here. For older emacs, the definition is very simple:

```Lisp
(defmacro with-memoization (place &rest code)
  "Return the value of CODE and stash it in PLACE.
If PLACE's value is non-nil, then don't bother evaluating CODE
and return the value found in PLACE instead."
  (declare (indent 1) (debug (gv-place body)))
  (gv-letplace (getter setter) place
    `(or ,getter
         ,(macroexp-let2 nil val (macroexp-progn code)
            `(progn
               ,(funcall setter val)
               ,val)))))
```

**Comment by phil-s** [comment]
Cross-referencing with: https://github.com/magit/magit/issues/3094#issuecomment-304992413

I only recently updated from Magit version 2.12.0 to 3.3.0, and I'd stashed my customisations in the process, one of which was that cache (refer to link), and I have *really* been noticing the difference.  I just now did some profiling to figure out why it was taking Emacs so long to do certain things, and spotted large numbers of duplicate `git rev-parse` calls going on (with the extra activity due to the Magit WIP modes exacerbating things), and thought of this issue, and then remembered John's patch.

Restoring that has made a huge difference for me.

**Comment by tarsius** [comment]
The diff-type is now remembered in `magit-diff-mode` buffers.

(I am not sure cross-referencing all the open performance related issues was particularly useful. They already shared the `area: performance` label.)

**Comment by phil-s** [comment]
> I am not sure cross-referencing all the open performance related issues was particularly useful

That was purely for the benefit of the people who had raised/were experiencing the WIP issues, as I thought those people would want to try out the rev-parse caching.
