### ISSUE TITLE
Magit is perhaps overly insistent about some keybindings

### ISSUE THREAD

**Issue by dabrahams** [magit/magit#4902]
I'm using the technique shown [here](https://emacs.stackexchange.com/a/360/20572) to globally bind C-return to `other-window`.  It uses `emulation-mode-map-alists` to get the absolute highest precedence for the keybinding.  As far as I can tell that should work, but if I put the cursor on a diff hunk in the magit status buffer and hit C-return, I get `magit-diff-visit-worktree-file` (found in `magit-hunk-section-map`).  I don't see any guidance about how to change that in the manual.  Is there a way?

**Comment by tarsius** [comment]
> It uses `emulation-mode-map-alists` to get the absolute highest precedence for the keybinding.

If you want that, you have to use `overriding-terminal-local-map` instead, as shown here: https://www.gnu.org/software/emacs/manual/html_node/elisp/Searching-Keymaps.html.

**Comment by dabrahams** [comment]
Thanks for the hint!

**Comment by dabrahams** [comment]
For the record, setting bindings in `overriding-terminal-local-map` works for a while, but then something (I'm not sure what) mysteriously sets it to `nil`.
