### ISSUE TITLE
magit-section-cache-visibility: Symbol’s function definition is void: \(setf\ compat-alist-get\)

### ISSUE THREAD

**Issue by yanchith** [magit/magit#4913]
Hello, I recently updated magit to the recent main (dd2e870b134bd292e470c830a42ce59a4396cdb7), and I keep getting `magit-section-cache-visibility: Symbol’s function definition is void: \(setf\ compat-alist-get\)` when updating the status buffer, making magit unusable, because the UI doesn't refresh after any action.

I have tried clean reinstalls of both emacs, and my config.

Haven't had a lot of time to debug, but I tried checking out an older version of magit from before Feb 12, 2023 (558050c46c0d807602b69cad80df2ea856fd310f), before the compat package was updated, and the error went away.

I use Emacs. 28.1 and 28.2.

**Comment by tarsius** [comment]
See #4836 and #4841.

Essentially, uninstall `magit` and `compat`, restart Emacs, reinstall `magit`.

**Comment by yanchith** [comment]
What confused me is that a clean reinstall of everything didn't result in a working config. Only deleting `magit` and `compat` and restarting *after* doing the clean reinstall does, as suggested by both your comment and this one: https://github.com/magit/magit/issues/4841#issuecomment-1410675050 (yeah, I am using straight). What's even worse, now I can't even reproduce that, and suddenly everything works on a clean reinstall. #heisenbug

Thanks anyway :)
