### ISSUE TITLE
magit-list-worktrees broken on older versions of git which don't support "-z"

### ISSUE THREAD

**Issue by igkper** [magit/magit#4930]
Sorry for not filling in a full bug report but I just want to mention this given limited time and I think I've identified the issue well enough.

To reproduce, use older version of git which doesn't support "-z" flag with "git worktree list --porcelain". 
My Ubuntu 18.04 uses git version 2.25.1 for example.

The symptom I see is no worktrees listed. I guess git fails given the invalid flag and magit silently accepts this.

**Comment by tarsius** [comment]
Thanks for the report!
