### ISSUE TITLE
`magit-section-post-command-hook` causes issues when using `magit-restore-window-configuration`

### ISSUE THREAD

**Issue by Walheimat** [magit/magit#4940]
Recent commit 3224b1765ff30c9f893527ce39d752342550bb25 leads to an error in `magit-section-post-command-hook` when using `magit-restore-window-configuration` for `magit-bury-buffer-function` (unrelated to #4931).

The error seems to be caused by `cursor-sensor-move-to-tangible` eventually calling `(get-pos-property pos 'cursor-intangible)` where `pos` is a position in the restored configuration but the window is the `magit-status` window.

The easiest way to reproduce:

```elisp
(require 'magit)

(setq magit-bury-buffer-function 'magit-restore-window-configuration)

;; In a sufficiently long project buffer got to `point-max` and call `magit-status`

;; Hit q or call `magit-mode-bury-buffer'
```

Result:

```
Error in post-command-hook (magit-section-post-command-hook): (args-out-of-range 1136 1136)
```

**Comment by Walheimat** [comment]
Not sure I understand what you're missing, but evaluating the following from `emacs -Q` should do the trick.

```elisp
(progn 
  (package-initialize)

  (require 'magit)
  (setq magit-bury-buffer-function 'magit-restore-window-configuration)

  ;; Adapt to the location of your clone
  (find-file (expand-file-name "~/repos/magit/LICENSE"))
  (goto-char (point-max))
  (magit-status)
  (magit-mode-bury-buffer))
```

```
Error in post-command-hook (magit-section-post-command-hook): (args-out-of-range 35149 35149)
```

**Comment by tarsius** [comment]
> Not sure I understand what you're missing,

It wasn't clear that "project buffer" means "a buffer visiting a file in the repository".
I can reproduce now.

**Comment by Walheimat** [comment]
Ah, I see. Sorry for the confusion. Glad you can reproduce.
