### ISSUE TITLE
Use Unicode box-drawing characters for magit-log

### ISSUE THREAD

**Issue by haxney** [magit/magit#495]
Replacing the current use of back- and forward-slashes, pipes, and asterisks with [Unicode box-drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character) would increase the readability of `*magit-log*` buffers. This would change the output from this (taken from the git mirror of the Emacs repo):

```
785f829 | * * alloc.c (mark_object): Use meaningful PVEC_NORMAL_VECTOR. * lisp.h (enum pvec_type): Adjust comments and omit explicit initializer for PVEC_NORMAL_VECTOR.
995a23d | * Clean out old termopts cruft.
1faee51 | *   select.el (xselect--encode-string): If a coding is specified for selection, and that is compatible with COMPOUND_TEXT, use it.
        | |\
360ac10 | | *   merge trunk
        | | |\
        | | |/
        | |/|
81adaff | * | * alloc.c (gc_sweep): Use pointer-to-a-pointer loop for buffers.
15b5649 | | * select.el (xselect--encode-string): If a coding is specified for selection, and that is compatible with COMPOUND_TEXT, use it.
        | |/
e56411e | * In switch-to-buffer optionally restore window point (Bug#4041).
612ea6b | * * commands.h (immediate_quit): Remove duplicate decl.
```

To this:

```
785f829 │ ◆ * alloc.c (mark_object): Use meaningful PVEC_NORMAL_VECTOR. * lisp.h (enum pvec_type): Adjust comments and omit explicit initializer for PVEC_NORMAL_VECTOR.
995a23d │ ◆ Clean out old termopts cruft.
1faee51 │ ◆   select.el (xselect--encode-string): If a coding is specified for selection, and that is compatible with COMPOUND_TEXT, use it.
        │ │╲
360ac10 │ │ ◆   merge trunk
        │ │ │╲
        │ │ │╱
        │ │╱│
81adaff │ ◆ │ * alloc.c (gc_sweep): Use pointer-to-a-pointer loop for buffers.
15b5649 │ │ ◆ select.el (xselect--encode-string): If a coding is specified for selection, and that is compatible with COMPOUND_TEXT, use it.
        │ │╱
e56411e │ ◆ In switch-to-buffer optionally restore window point (Bug#4041).
612ea6b │ ◆ * commands.h (immediate_quit): Remove duplicate decl.
```

This can be done with a few `query-replace`s.

A side benefit is that commits beginning with `*` are no longer visually confused with the nodes of the commit graph.

**Comment by Pitometsu** [comment]
Should I use for such nice unicode https://github.com/georgek/magit-pretty-graph or is it already part of magit, and how can I customize it then?

**Comment by tarsius** [comment]
Magit doesn't currently support unicode graphs and loading `magit-pretty-graph` will certainly break Magit.

I plan to implement prettier graphs eventually, see #2989.

**Comment by georgek** [comment]
Actually it won't break magit because it calls git directly. The problem is it's not a part of magit at all. It's an emacs rendering of the git graph.

I actually have time to work on this now if you would like to, @tarsius. It might at least save you some effort in reinventing what I did before.

**Comment by tecosaur** [comment]
Hey @georgek, this looks lovely! Do you plan on getting back to this eventually? (assuming that @tarsius is still interested :slightly_smiling_face:)

**Comment by codygman** [comment]
This has been affecting me recently, it appears this isn't a big focus though?
