### ISSUE TITLE
C-s breaks popups

### ISSUE THREAD

**Issue by zenspider** [magit/magit#4951]
## Repro:

In `magit-status`:

1. hit `h` to bring up the help command list,
2. hit `C-s` and search for anything,
3. move to quit searching, (in previous versions `RET` to quit searching worked also, but now `RET` puts it back to the right state)
4. `q` to dismiss help

## Expected:

`q` should dismiss the help

## Observed:

it added `q` as modified text to the buffer, and all subsequent interactions.

To get OUT of that predicament and back to my previous state I flipped back to `magit-status`,  `l` for log to replace the help, `q` to quit.

No backtrace because no error is raised. Just bad UX.

Magit 20221008.1927 [>= 3.3.0-git], Git 2.40.1, Emacs 28.2, darwin

(it would be nice if magit-version put the string in kill)

This does reproduce using only emacs, and is actually worse because my logging workaround reports an "unbound suffix: `q`" and just errors out.

**Comment by tarsius** [comment]
I suspect you `transient` may be out of date. Update and restart before giving another try.

> hit `C-s` and search for anything,

Where do you want that search to take place? In the popup buffer showing the commands or whatever other buffer is current? The latter is generally not possible, though it can be made to work I think. The former should just work with the (newish) default value of `transient-enable-popup-navigation`.

**Comment by zenspider** [comment]
I updated everything before filing this. 

I wanted the search to take place in the pop-up, so that part is working fine.

**Comment by tarsius** [comment]
Right. Somethings wrong.

**Comment by tarsius** [comment]
That should do the trick. Let me know if not.
