### ISSUE TITLE
When a password prompt is cancelled, a git process is left behind

### ISSUE THREAD

**Issue by geza-herman** [magit/magit#4962]
If magit asks for a password (for example, using `F u` in the `magit-status` window), and I cancel it with either `ESC ESC ESC` or `C-g`, a git process is left behind running, `list-process` shows:

```
git             1595086 run     magit-process: doboz      /dev/pts/9   Main         git --no-pager --literal-pathspecs -c core.preloadindex=true -c log.showSignature=false -c color.ui=false -c color.diff=false pull origin refs/heads/master
```

Normally I use `ssh-agent`, but sometimes it doesn't have my password. So I cancel magit's prompt, add my password to `ssh-agent`, and then retry magit. And when I exit emacs, emacs asks me whether it should really exit because of running git processes. Which is scary, because I definitely don't want to interrupt a running git process which does something. But these stuck processes supposedly wait for user input. But it's not always easy to know whether a git process is just slow, or waits for user input.

I think these processes shouldn't be left behind, but cleaned up. I'm not sure why they keep running (perhaps it is a git problem?).

**Comment by tarsius** [comment]
Thanks for the report!
