### ISSUE TITLE
Revert keybinds incorrectly documented

### ISSUE THREAD

**Issue by comburent** [magit/magit#4964]
The [manual](https://magit.vc/manual/magit/Reverting.html) indicates `V A` for resuming a cherry-pick or revert but I see this:
![image](https://github.com/magit/magit/assets/124596272/04d7b63d-a129-435b-83e2-8b5b1fa7fe4e)

`M-x magit-version RET`:
```
Magit 3.3.0-4.a760dd1, Git 2.40.1, Emacs 28.2, gnu/linux
```

Edit: Apologies, I must have mispressed some key that resulted in the
issue being submitted way earlier than it was supposed to.

**Comment by kyleam** [comment]
Thanks for reporting.
