### ISSUE TITLE
Long Magit logs (more than ~5000 commits) are painfully slow to create

### ISSUE THREAD

**Issue by doublep** [magit/magit#4974]
_[I have read and decided to ignore the standard instructions. I will show below how I tested, and yes, the issue is still present with current source.]_

I have long noticed that Magit logs exhibit quadratic (or worse) building time based on number of commits N. While usually default value of 300 is appropriate, a few time in a month I have to build really long logs to look years back into history. Keybinding `+` in a log buffer doubles its commit count, but the time Magit takes to generate longer log doesn't just double — it grows much faster.

To quickly, robustly and repeatedly reproduce the issue and also exclude any possibility of influence of configuration etc., I used Eldev. I created file `Eldev-local` in Lisp subdirectory of Magit source repository with the following contents:

    (setf eldev-project-main-file "magit.el")

    (eldev-use-package-archive 'gnu-elpa)
    (eldev-use-package-archive 'melpa)

To see the problem now you can run Eldev like this:

1. Without UI at all:

        $ time eldev -d eval "(progn (magit-status \"~/git/emacs\") (magit-log-setup-buffer '(\"master\") '(\"-n12000\" \"--graph\" \"--decorate\") nil))"

2. Starting new Emacs independent of your normal Emacs (without your configuration, for example):

        $ time eldev -d emacs --eval "(progn (magit-status \"~/git/emacs\") (magit-log-setup-buffer '(\"master\") '(\"-n12000\" \"--graph\" \"--decorate\") nil))"

For this you also need some repository with a long history. I used `~/git/emacs` here, replace in the command lines as needed. 12000 can of course also be replaced as desired. Note that in Emacs it goes back only ~1 year, so it's not a stretch of imagination that people need logs this long — and even longer.

On my machine the first command (without UI) takes 85 seconds, which is obviously already unusably long. You can verify with the second command (the one starting UI Emacs) that it really creates log buffer as requested.

After some investigations I noticed that function `magit-log-wash-rev` is called for each commit and this function slows down a lot. I added the following to `Eldev-local`:

    (defvar n-calls 0)
    (defvar shared-notch nil)
    (defadvice magit-log-wash-rev (around debug-it activate)
      (unless shared-notch (setf shared-notch (float-time)))
      (setf n-calls (1+ n-calls))
      ad-do-it
      (when (= (% n-calls 100) 0)
        (eldev-debug "%.3f" (- (float-time) shared-notch))
        (setf shared-notch nil)))

This prints time spent for 100 calls (replace 100 with 1 to see that it is _this_ function that slows down, not something between calls). Here it takes about 0.03 s per 100 calls in the beginning, and slows down to ~1.5 s at the end of processing 12000 commits.

Anyway, after investigating this function further, I noticed that the problem is that it creates _sections_. If I simply remove section creating code (see the patch at the end), there is no detectable slowdown anymore, total time is down to 4,5 s (from 85) and if I check the generated log in UI (the second command) it at least _looks_ fine.

I of course don't propose to apply the patch as is, I'm sure sections are there (in the logs) for a reason. However, could you consider picking this up from here and trying to make such mass section creation not have O(N^2) — or maybe worse — complexity? I'm not familiar with this code, so I cannot really debug this. One obviously O(N^2) piece of code would be the addition of new section to the list of root's children, but according to tests this is not the main problem.

GitHub didn't let me attach this, so this is the patch that disables section creation (only for investigation):

    diff --git a/lisp/magit-log.el b/lisp/magit-log.el
    index cf5a0db3..c40a61d7 100644
    --- a/lisp/magit-log.el
    +++ b/lisp/magit-log.el
    @@ -1288,11 +1288,6 @@ Do not add this to a hook variable."
           ;; of the youngest expired reflog entry.
           (when (and (eq style 'reflog) (not date))
             (cl-return-from magit-log-wash-rev t))
    -      (magit-insert-section section (commit hash)
    -        (pcase style
    -          ('stash      (oset section type 'stash))
    -          ('module     (oset section type 'module-commit))
    -          ('bisect-log (setq hash (magit-rev-parse "--short" hash))))
             (setq hash (propertize hash 'font-lock-face
                                    (pcase (and gpg (aref gpg 0))
                                      (?G 'magit-signature-good)
    @@ -1395,7 +1390,7 @@ Do not add this to a hook variable."
                     (looking-at "[-_/|\\*o<>. ]*"))
                   (setq graph (match-string 0))
                   (unless (string-match-p "[/\\.]" graph)
    -                (insert graph ?\n))))))))
    +                (insert graph ?\n)))))))
       t)

     (defun magit-log-propertize-keywords (_rev msg)

**Comment by tarsius** [comment]
> _[I have read and decided to ignore the standard instructions.

That is perfectly okay; I prefer good reports over those that concentrate on checking the boxes. ;P

> I have long noticed that Magit logs exhibit quadratic (or worse)
> building time based on number of commits N.

As surprising as that may be, I wasn't aware of that. Or maybe not that surprising, since this obviously is something that has to be fixed. It is bed time, so I haven't tried reproducing this yet, much less tried fix it. But I have quickly looked at the relevant code, and there are a few places that to me immediately jump out as problematic (after being primed by your report).

**Comment by tarsius** [comment]
It's again bed time, so just a quick note: the `speed` branch looks promising. There are other things that I intend be improved, but not using markers when possible, already makes a huge difference.

**Comment by doublep** [comment]
> already makes a huge difference

According to a quick test quadratic slowdown is gone completely. It is totally understandable that if you format two times more commits, you need to wait two times longer. So, at this point it looks like possible constant factor improvement only.

One potential way at making this even faster than `O(N)` (if you ignore the time Git itself takes, of course) would be to make formatting lazy and bind it to buffer fontification, so that it happens on-demand. But that's certainly not easy, especially if sections are somehow really important so that you have to define them all at once.

**Comment by doublep** [comment]
> According to a quick test quadratic slowdown is gone completely.

Actually, now I cannot reproduce the "gone completely" part, it does slow down. But anyway, it is certainly much faster and it is feasible to go back much further in history, thanks.

Another idea that might or might not be easier to implement compared to lazy fontification and section creation, would be to make log buffers always try to reuse what is there. E.g. a frequent usecase (where slowness is visible) is pressing that `+` key and basically regenerating the same log again, only two times as many commits. If it could see that the log already contains half of them and avoid formatting anew, only format the second half, this would presumably give a substantial speedup.

**Comment by tarsius** [comment]
> Actually, now I cannot reproduce the "gone completely" part, it does slow down.

That's probably caused by the margin. Even when that is not shown, we still generate an overlay per commit. The motivation for that is that we don't have to parse everything again when toggling the margin. However, it should be possible to store the necessary information somewhere and delay creating the overlays until the margin is shown.

> If it could see that the log already contains half of them and avoid formatting anew, only format the second half, this would presumably give a substantial speedup.

With linear history that would work well, but if there is more than one branch that crosses the boarder between already present and newly inserted commit, then the graphs would not be correct.

**Comment by doublep** [comment]
> That's probably caused by the margin.

I tried commenting out code of `magit-make-margin-overlay` and `magit-maybe-make-margin-overlay`, but that doesn't give any noticeable speedup for me (testing as described before). The margin is visibly gone, but no tangible gain.

> With linear history that would work well, but if there is more than one branch that crosses the boarder between already present and newly inserted commit, then the graphs would not be correct.

Cannot reproduce that. I created logs on a repository with branches, then increased number of commits, and the  last commit line of the first log can be found verbatim in the second log, even though it starts with "* | *" because of branching graph.

Anyway, what I meant is not "either full match or nothing", but comparison line-by-line or section-by-section, whatever works. So, if you have log "ABCDE" currently and newly generated log is "ABCDXYZVW", then you quickly (presumably) skip "ABCD", delete line "E" and finally insert "XYZVW" as the second half or so.

**Comment by tarsius** [comment]
```
$ git log --oneline --graph
*   19047f6 (HEAD -> main) Merge branch 'other'
|\  
| * 7eb09d2 (other) 1
* | 9b74751 c
* | f11102a b
|/  
* cf93dab a

$ git log --oneline --graph -n3
*   19047f6 (HEAD -> main) Merge branch 'other'
|\  
| * 7eb09d2 (other) 1
* | 9b74751 c

$ git log --oneline --graph 9b74751
* 9b74751 c
* f11102a b
* cf93dab a

Tacked together variant 1 (what you propose)
*   19047f6 (HEAD -> main) Merge branch 'other'
|\  
| * 7eb09d2 (other) 1
* 9b74751 c
* f11102a b
* cf93dab a

Tacked together variant 2
*   19047f6 (HEAD -> main) Merge branch 'other'
|\  
| * 7eb09d2 (other) 1
* | 9b74751 c
* f11102a b
* cf93dab a
```

**Comment by tarsius** [comment]
Ah, I see what you mean now. :grinning: 

I'll take that into consideration some other time. I think the changes I already made are a big enough improvement to stick to just that for a while. But I've been hoping to revisit all this for quite some time now, and one day I probably will.
