### ISSUE TITLE
command-execute: Wrong type argument: commandp, magit-jump-to-diffstat-or-diff

### ISSUE THREAD

**Issue by Lenbok** [magit/magit#4975]
I am viewing a diff and press 'j' to jump between the diffstat and the actual diff.

It doesn't work, and we get:

```
Debugger entered--Lisp error: (wrong-type-argument commandp magit-jump-to-diffstat-or-diff)
  call-interactively(magit-jump-to-diffstat-or-diff nil nil)
  command-execute(magit-jump-to-diffstat-or-diff)
```

Magit version: Magit 6d300bf, Transient 0.4.1, Git 2.34.1, Emacs 29.1.50, gnu/linux

It looks to me as though e8152c76bf636805c0eb9027083d0ff10d28d1a8 has removed the `(interactive)` from that function. Is this done in error?

**Comment by tarsius** [comment]
> Is this done in error?

Yes. I'll fix it in the morning.
