### ISSUE TITLE
Staging binary files reports 'patch does not apply'

### ISSUE THREAD

**Issue by haji-ali** [magit/magit#4977]
When staging binary files (corresponding to gpg encrypted files) I constantly get the error

```
error: cannot apply binary patch to 'file.gpg' without full index line
error: file.gpg: patch does not apply
```

Staging using `git add` works as expected. This also happened on a few text files with unicode characters. I saw a few issues here that report similar error (#3625, #1742, #3608 and #32 are a few). My `locale` is `en_GB.UTF-8` in case that helps.

`magit-version` reports `Magit 5d91aad, Git 2.37.1, Emacs 29.1.50, darwin`.

**Comment by tarsius** [comment]
I cannot reproduce that.

Do the modified binary files look like this in the status buffer?:

```
modified   secrets.gpg (binary)
```

**Comment by haji-ali** [comment]
Yes, that's exactly what it shows. I should say that not all files have this error but I am wondering how I can debugging diagnositics without sharting my passwords!

**Comment by tarsius** [comment]
How do you stage these files? By pressing `s` when the cursor is sitting on one of these lines? If so, `magit-apply-diff` shouldn't come into play.

The way I understand it, in your last post you say that `(magit-diff-file-header section)` both does, and does not, return `diff ...`.

**Comment by haji-ali** [comment]
Yes, I press `s` on the files which calls `magit-stage` 
`(magit-diff-type)` returns `unstaged`, `(magit-diff-scope)` returns `file` and `(magit-apply--diff-ignores-whitespace-p))` returns `t` which then calls `(magit-apply-diff   s "--cached")`.

Sorry, I had a typo in my previous message. Corrected.
