### ISSUE TITLE
Major mode hooks not run in magit-find-file due to delay-mode-hooks

### ISSUE THREAD

**Issue by dieggsy** [magit/magit#4986]
Version: Magit v3.3.0-706-gdd6ecd5f, Transient 0.3.7-git, Git 2.41.0, Emacs 29.1, darwin
# Expected behavior

I'd like major mode hooks to run when doing magit-find-file in most cases

# Observed behavior

Major mode hooks are not run when doing magit-find-file (I believe due to `delay-mode-hooks` in `magit-revert-rev-file-buffer`)

# Reproduction

Add a function to prog-mode-hook, magit-find-file a file, the function will not run. 

Looks like this was intentionally introduced in https://github.com/magit/magit/commit/f331092df4d4dfc0a2a7424d929a9c845088d57f to deal with issues with `lsp-mode`. I'm not sure the solution is adequate? It turns off all major mode hooks indiscriminately, which results in things like no line numbers and other useful things like rainbow-delimiters-mode, both of which I turn on through prog-mode-hook.

**Comment by tarsius** [comment]
I would like to revert that commit and asked for help at https://github.com/doomemacs/doomemacs/pull/6309#issuecomment-1681382742.

**Comment by dieggsy** [comment]
Thank you!
