### ISSUE TITLE
auto-fill-mode is broken in commit messages when using in git-commit-major-mode

### ISSUE THREAD

**Issue by eyal0** [magit/magit#4990]
# Summary

[`auto-fill-mode`](https://ftp.gnu.org/old-gnu/Manuals/emacs-20.7/html_node/emacs_213.html#:~:text=Auto%20Fill%20mode%20is%20a%20minor%20mode%20which%20is%20enabled,you%20type%20SPC%20or%20RET%20.) (which automatically adds line breaks into comments if lines are too long) doesn't work properly when [`git-commit-major-mode`](https://github.com/magit/magit/blob/48818355728c48d986d74dde8b1e9fba25f0fd53/lisp/git-commit.el#L182) is set.

# Detail

Long ago, in ff155a6a10a667c849f1e0b46453c5e3b1e26ede, @npostavs added the ability to have line continuations in comments.  Comments usually start with `#` but it can actually be whatever  git config has listed for `core.commentchar`.  Assuming `#`, if you are typing something like:

```
# blah blah blah blah blah
```

If you line gets long enough, eventually it will wrap on to the next line and the start of the line will automatically get the same prefix as the previous line.  So if you only ever type `blah` with spaces, you'll get this:

```
# blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah
# blah
```

The `comment-start-skip` was set to recognize which part of the previous line is the prefix that must be repeated.  In this case, it's the `#` and the space after it.

Because we're going to use this method and ignore all the major mode stuff, we will turn off all the complex syntax stuff by setting `comment-use-syntax` to `nil`.

Later on, `git-commit-major-mode` was invented and comments can now be typed in any major mode.  However, setting the major-mode did *not* re-enable the `comment-use-syntax` and that causes the markdown to be edited with the `#` comment style instead of the comment style of the major mode.  This leads to all sorts of weirdness.

In my case, if I have `git-commit-major-mode` set to `markdown-mode`, then if have a `#` **anywhere** in my commit message, the continuation puts an arrow after the line and then starts the next line with `#`.  It looks like this:

```
# My Heading

# blah blah blah blah blah blah blah blah blah blah blah blah blah -->
# blah blah blah 
```

It's recognizing the `#` which is a heading in markdown and not even on the same line!  And then it is using an HTML comment ending (HTML is valid instead markdown) and then using the continuation as before.  Totally screwy!

# Reproduce

Even without setting `git-commit-major-mode`, just start a commit message, switch to markdown-mode, turn on `auto-fill-mode`, and then type a heading that starts with `#` and then type `blah` on the following line with spaces, many times, until you get a line wrap.

I'll get to work on a patch.

# Version
```
Magit 20230815.1255 [>= 3.3.0.50-git], Transient 0.4.1, Git 2.25.1, Emacs 29.0.50, gnu/linux
```

**Comment by eyal0** [comment]
The variable `comment-use-syntax` can be set to `'undecided` which means that it's up to the `auto-fill-mode` to figure out if it can trust the syntax table to do comment or if it should use the comment-start-skip and comment-end-skip.  That seems like a good way to go.  So if the major mode is, like `text-mode`, the undecided will find that it's unable to notice comments and it'll use the `comment-start-skip` and `comment-end-skip` like before.  But if not, then it'll use the `#` comments.

I have tested this in these scenarios:

1. git-commit-major-mode unset, continuation for line start with `#`
2. git-commit-major-mode unset, continuation for line start without `#`
3. git-commit-major-mode unset, continuation for line follow line starting with `#`
4. git-commit-major-mode set to markdown, line starting with `#`
5. git-commit-major-mode set to markdown, line starting without `#`
6. git-commit-major-mode set to markdown, continuation for line follow line starting with `#`

it's all working as best as we could expect.  All we have to do is stop setting that variable to nil and just leave it at default, which is undecided.  Easy.

**Comment by tarsius** [comment]
Given `.dir-locals.el` with

```
((git-commit-mode
  (git-commit-major-mode . markdown-mode)))
```

and `.git/config` with

```
[core]
	commentchar = ";"
```

it doesn't seem to make a difference if we

```
(setq-local comment-use-syntax nil) ; or
(setq-local comment-use-syntax 'undecided)
;; or don't set the local value and use the default `undecided'
```

In all cases the local value seems to end up being `nil`.

> In my case, if I have `git-commit-major-mode` set to `markdown-mode`, then if have a `#` **anywhere** in my commit message, the continuation puts an arrow after the line and then starts the next line with `#`.  It looks like this:

> ```
> # My Heading
> 
> # blah blah blah blah blah blah blah blah blah blah blah blah blah -->
> # blah blah blah 
> ```

I was able to reproduce that for `#`, until I set `core.commentchar` to `";"`, after which I could reproduce it for `;`, which was to be expected.

I can prevent the `-->` from appearing using `(setq-local comment-use-syntax t)`, but then the beginning comment char (whether that is `#` or `;`), is not inserted when a line break is automatically inserted.

**Comment by eyal0** [comment]
The default for `comment-use-syntax` is `'undecided`.  The very first time that `auto-fill-mode` is triggered, that `'undecided` is going to be replaced with either `t` or `nil` depending on whether or not the comment matching test works.   The code is here: https://github.com/emacs-mirror/emacs/blob/master/lisp/newcomment.el#L367-L378

So when you observe `comment-use-syntax`, it will often already be `t` or `nil` because the `undecided` got resolved.

What you say about markdown with semicolon comments is interesting!  I'll try to reproduce this...

Hmm, it's not working the same for me as it is for you.  Can you confirm that you have actually modified the right magit source code file?  I've got `markdown-mode` set for `git-commit-major-mode` and I'm using the semicolon, too.

> I can prevent the --> from appearing using (setq-local comment-use-syntax t), but then the beginning comment char (whether that is # or ;), is not inserted when a line break is automatically inserted.

Right, that's how it'll work after this commit.  Without this PR:

The comment mode will always be `#` or `;` or whatever the commentchar is in git.  And if you type too much text on a line that starts with one of those, when it wraps, it'll continue a line with that character.  And if you happen to be in markdown down, it'll get a little confused and it'll put an HTML end of comment `-->` and then start the next line with the `#` or `;`.

With this PR:

emacs will detect if it's in a mode that supports comments or not.  c++, lisp, python, markdown all have comments so they'll work.  However, if you're in a mode that doesn't have comments, like fundamental or text, then you'll get the comment continuations using a leading `#` or `;`.  But it'll always be just one or the other.  emacs doesn't have the ability to continue, say, c++ comments *and* git comments at the same time.  So it's not perfect but it's surely better than what we had before!

I get that this is kind of complex!  Let me know if there's anything else. 

>  it doesn't seem to make a difference if we
> (setq-local comment-use-syntax nil) ; or
> (setq-local comment-use-syntax 'undecided)
> ;; or don't set the local value and use the default `undecided'
> In all cases the local value seems to end up being nil.

This is surprising to me!  Like I said, I just tested it and I got `t`.  Try again?

**Comment by eyal0** [comment]
@tarsius Were you able to look at this again?

I was pretty confusing before so I'll try to reword my thoughts.

Before this change, only "git-style" comment worked properly with auto-fill-mode.  Whatever your `commit.commentchar`, like `#` or `;`, those comments will continue just fine.  The rest won't continue properly and in some cases just `markdown-mode`, will get **really** screwed up.

After this change, "git-style" comments will work properly with auto-fill-mode if the major mode of the buffer is a type that doesn't have comments, eg, `text-mode`.  But if your buffer's major-mode *does* have comments, like `c++` or `lisp`, then that major-mode's comments will wrap to the next line correctly *instead* of the git comments.  It's *not* possible for both the git comments and the major-mode's comments to both wrap correctly (unless of course, both of them are the same comment style, like if you used python with `#` commentchar or lisp with `;` commentchar).

This fix seems to make the commit message editing better in most cases because hardly anyone is going to care about the git comment at the bottom, which is just a comment like `Changes to be commited:` and `Your branch is up to date with...`.

Overall, I think that this change makes the editing of comment messages strictly better than before.

**Comment by tarsius** [comment]
> Were you able to look at this again?

I am currently looking at it again.

**Comment by tarsius** [comment]
IMO the solution is to force use Git-style comments. That is also what we already tried to do, but we forgot to set `comment-end`. It seems to my that your approach of not setting `comment-use-syntax` just adds an additional defect, which when combined with the existing defect, leads to a change in behavior that you find favorable, while introducing other undesirable value, which you consider less bad (but which I consider worse).

Luckily we can just fix the actual issue and set `comment-end` to make everything work as desired. Well almost, we also have to neutralize `markdown-fill-paragraph`.

**Comment by eyal0** [comment]
Alright, we'll see if this works.  :shrug: Hopefully you don't end up playing whack-a-mole with major-modes.
