### ISSUE TITLE
ssh password prompt not matched by regexps

### ISSUE THREAD

**Issue by ahihi** [magit/magit#4992]
ssh client: OpenSSH_9.1p1, OpenSSL 3.0.8 7 Feb 2023
ssh server: OpenSSH_7.2p2, OpenSSL 1.0.2k-freebsd  26 Jan 2017

gives a password prompt that looks like:
`(user@host) Password for user@host:`

this is not matched by the [regexps](https://github.com/magit/magit/blob/f8353f575e9ed968715a685d69501e5c105f2aee/lisp/magit-process.el#L167) in `magit-process-password-prompt-regexps` and so Magit fails to catch it.

i worked around it in my own config by adding a new regexp `^([^)]+) *[Pp]assword\\( for '?\\(https?://\\)?\\(?99:[^']*\\)'?\\)?: ?$`, but for a potential PR i wonder

1. should the bit inside the parens be more restrictive?
2. would it be better to merge this into the existing pattern `^\\(Enter \\)?[Pp]assword\\( for '?\\(https?://\\)?\\(?99:[^']*\\)'?\\)?: ?$`?

**Comment by tarsius** [comment]
I went with 1:no, 2:yes.
