### ISSUE TITLE
Cannot apply/pop stashes with conflicts

### ISSUE THREAD

**Issue by doublep** [magit/magit#4993]
Tested with Magit from source, revision f8353f57 (latest as of this moment).

Situation: I have a large repository (proprietary, cannot share) and a fairly old stash. There have been several commits since the stash was made and there are now conflicts.

If I type `z a` on the stash line, nothing is done and Magit writes "GitError! conflicts in index. Try without --index.  [Type `$' for details]" at the top of the buffer.

If I do this from the command line, I can reproduce the failure Magit is facing:

    $ git stash apply stash\@\{0\} --index
    error: patch failed: [FILENAME:LINE]
    error: [FILENAME:LINE]: patch does not apply
    error: patch failed: [FILENAME2:LINE2]
    error: [FILENAME2:LINE2]: patch does not apply
    error: conflicts in index. Try without --index.

However, Magit doesn't allow me to run the command easily without `--index`. If I run it manually from the command line without `--index`, then it does succeed, as Git sort-of-promised. There are conflicts (unmerged hunks) afterwards, but this is expected.

Because I don't really know Git internals and what "index" is, I cannot create a simple reproducer or suggest how to fix this. But in any case Magit must not leave me with no obvious way of applying a stash from the normal UI and force me to resort to command line.

**Comment by tarsius** [comment]
Magit automatically uses `--index` when it concludes that it is safe:

```elisp
(defun magit-stash-apply (stash)
  "Apply a stash to the working tree.
If nothing is staged, then try to reinstate the stashed index.
Doing so is not possible if there are staged changes."
  (interactive (list (magit-read-stash "Apply stash")))
  (magit-run-git "stash" "apply" stash
                 (and (not (apply #'magit-anything-staged-p nil
                                  (magit-stashed-files stash)))
                      "--index")))
```

It doesn't do so when any of the affected files have staged changes, because when `--index` is used, then `git stash apply` automatically unstages all changes to those files, and if there are also unstaged changes to those files, then that state (which parts of those files are staged and which are not) would be lost. (Even if there are no unstaged changes, the "file is completely staged" state would be lost, though that might be less risky.)

We could refine the check performed by this command, to check whether there are both staged and unstaged changes. Maybe we could also/instead show a warning which informs the user about this complication.

**Comment by doublep** [comment]
In my case there were absolutely no changes ­— staged or unstaged. The working directory was completely clean, yet the stash didn't apply. Again, as I don't really know what "index" is, I don't know how that is possible. But I have seen that myself.

**Comment by tarsius** [comment]
> In my case there were absolutely no changes ­— staged or unstaged. The working directory was completely clean, yet the stash didn't apply.

Then I'll have to look into it some more.

> Again, as I don't really know what "index" is, I don't know how that is possible.

The "index" is the same thing as the "staging area".

**Comment by doublep** [comment]
> The "index" is the same thing as the "staging area".

Ah, so then the problem is reproducible when the _stash_ contains conflicting staged changes:

    #! /bin/sh

    rm -rf /tmp/git-stash-index

    mkdir -p /tmp/git-stash-index
    cd /tmp/git-stash-index

    git init -q

    echo "bla bla bla" > file
    git stage file
    git commit -m 1

    echo "foo" >> file
    git stage file
    git stash

    echo "bar" >> file
    git stage file
    git commit -m 2

    git status
    echo ^^^

    git stash apply "stash@{0}" --index

This doesn't involve Magit, but naturally Magit will also fail to apply the stash, as the underlying command it'd use fails itself.

**Comment by tarsius** [comment]
Further work is required to make it always possible to apply a stash, see `stash-apply` branch.
