### ISSUE TITLE
Weird void-variable errors regarding magit-section-inhibit-markers

### ISSUE THREAD

**Issue by alphapapa** [magit/magit#4995]
241b327b7ae04e898cdc6343fbee0a1be3b2ce3f, made a few weeks ago, involved the variable `magit-section-inhibit-markers`.

In about that timeframe I've begun seeing weird errors about that variable being void when I load or compile packages that use `taxy-magit-section`.  I just had a user of Ement.el mention seeing a `void-variable magit-section-inhibit-markers` error when he tries to use `ement-room-list`.

Glancing at the diff, nothing jumps out at me as causing this problem, but since it's the only commit in the whole repository that contains that variable, I guess it must be related.

I don't have any more details at this moment.  I'm hoping that you'll know what to do, @tarsius, since it was working before.  Thanks.

**Comment by tarsius** [comment]
Seems pretty weird too me and smells like recompiling the things that depend on `magit-section` would do the trick. Or maybe a dependency on `magit-section` (directly or via another feature) is missing somewhere.

`magit-section-inhibit-markers` is defined in the same file as `magit-insert-section`. Another variable that is define in `magit-section.el` and is used in `magit-insert-section`, is `magit--section-type-alist`. That has existed for a long time and hasn't caused any issues like this. I don't see why `magit-section-inhibit-markers` would be any different.

**Comment by alphapapa** [comment]
Ok, I'll continue to keep an eye out for further occurrences of the warning/error.  If you don't mind, please leave this issue open for another month or so, as I've shared the link and asked another user to chime in if possible.  Thanks.

**Comment by tarsius** [comment]
Did something come up?

**Comment by alphapapa** [comment]
No, I haven't seen this happen again.  I'll close it.  Thanks.

**Comment by axelson** [comment]
I just ran into what might be the same issue: `Symbol’s value as variable is void: magit-section-inhibit-markers`

I was able to resolve it by updating all my packages (with `M-x list-packages` followed by `U x`) and restarting emacs.

**Comment by alphapapa** [comment]
I've found that this happens, e.g. in the following case:

1.  Install `magit-section` from MELPA.
2. Install a package that depends on `magit-section`.
3. Downgrade `magit-section` to v3.3.0 from GNU ELPA.
4. Try to use the package that depends on `magit-section`.

To fix it requires recompiling the dependent package ensuring that the older version of `magit-section` is loaded by the Emacs that compiles it, then ensuring that that recompiled library is loaded.
