### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by pikrzysztof** [magit/magit#5003]
Hi!

https://github.com/magit/magit/discussions/4630 seems to be out of date - `M-x magit-info` does not seem to exist in my emacs. I also tried grepping magit 3.3 sources for `magit-info` in my `~/.emacs.d/elpa` directory and grep hasn't returned anything.

I'm running Magit 3.3.0, Git 2.42.0, Emacs 29.1, gnu/linux

**Comment by tarsius** [comment]
Magit v3.3.0 lacks `magit-info` but the next release (and the current development version) don't.

**Comment by tarsius** [comment]
And of course you can access magit's manual starting with `M-x info`.
