### ISSUE TITLE
Reported-by and other git trailers not added below commit message

### ISSUE THREAD

**Issue by Apteryks** [magit/magit#5005]
Hello!

    (1) what behavior you expected

I'd expect the `Reported-by:` and other git trailers to be added, as their name imply, to the bottom of a git message.

    (2) what behavior you observed

The `Reported-by` trailer is added on the second line of my message, not below it.

    (3) and how we can reproduce the issue.

Here's the content of my COMMIT_MSG buffer, after filling in the content of my commit:

```
gnu-maintenance: Support URI list of mixed mirrors, HTTP URLs.

Fixes <https://issues.guix.gnu.org/58697>.

* guix/gnu-maintenance.scm (import-html-updatable-release): Update doc.
<expand-uri>: New nested procedure.  Apply it to the origin URI.
```

The Emacs cursor is at the end of the last ChangeLog line.  Hitting `C-c C-p` and entering the name of the reporter produces:

```
gnu-maintenance: Support URI list of mixed mirrors, HTTP URLs.
Reported-by: Someone <someone@somewhere.org>

Fixes <https://issues.guix.gnu.org/58697>.

* guix/gnu-maintenance.scm (import-html-updatable-release): Update doc.
<expand-uri>: New nested procedure.  Apply it to the origin URI.
```

I would have instead expected:

```
gnu-maintenance: Support URI list of mixed mirrors, HTTP URLs.

Fixes <https://issues.guix.gnu.org/58697>.

* guix/gnu-maintenance.scm (import-html-updatable-release): Update doc.
<expand-uri>: New nested procedure.  Apply it to the origin URI.

Reported-by: Someone <someone@somewhere.org>
```

This seems to affect all the git trailers that Magit can add for me.

    M-x magit-version RET

=> `Magit 3.3.0-5.186414a, Transient 0.4.3, Git 2.41.0, Emacs 28.2, gnu/linux`

Thanks for maintaining Magit!

**Comment by tarsius** [comment]
Thanks for the report!

**Comment by Apteryks** [comment]
It works!  I've already updated `emacs-magit` in Guix to incorporate the change.  Thank you!

**Comment by Apteryks** [comment]
Hello!

Related to this issue, when there are existing git trailers, adding change log lines via `magit-commit-add-log`, the change logs are added *below* the trailers, while they should be added *above*.

Should I create an issue for that?

Thank you!

**Comment by tarsius** [comment]
Please open an "idea" discussion.

(As far as I know gnu-style changelogs and linux-style trailers are not commonly used together, so this isn't a bug.)

**Comment by Apteryks** [comment]
Hello @tarsius!  Thanks for your prompt reply; I've now done so, see: https://github.com/magit/magit/discussions/5315
