### ISSUE TITLE
Commit 1ab107a7 broke M-2 and likely other section-related commands

### ISSUE THREAD

**Issue by doublep** [magit/magit#5009]
Reproducible with every commit afterwards, with 053831a1 it works.

To reproduce, from `lisp` of the source checkout:

    eldev emacs --eval "(magit-status \"~/git/magit\")"

and then press `M-2` in UI.

This assumes you have this `Eldev-local`:

    (setf eldev-project-main-file "magit.el")
    (eldev-use-package-archive 'gnu-elpa)
    (eldev-use-package-archive 'melpa)

I get the following error:

    Debugger entered--Lisp error: (wrong-type-argument (or eieio-object cl-structure-object oclosure) nil)
      eieio-oref(nil start)
      (goto-char (eieio-oref s 'start))
      (while (> (1- (length (magit-section-ident s))) level) (setq s (eieio-oref s 'parent)) (goto-char (eieio-oref s 'start)))
      (let ((s (magit-current-section))) (setq level (1- level)) (while (> (1- (length ...)) level) (setq s (eieio-oref s 'parent)) (goto-char (eieio-oref s 'start))) (magit-section-show-children magit-root-section (1- level)))
      (if (< level 0) (let ((s ...)) (setq level (1- level)) (while (> ... level) (setq s ...) (goto-char ...)) (magit-section-show-children magit-root-section (1- level))) (let* ((s ...) (i ...)) (while (not ...) (progn ... ...)) (magit-section-goto s)))
      magit-section-show-level(-2)
      magit-section-show-level-2-all()
      funcall-interactively(magit-section-show-level-2-all)
      command-execute(magit-section-show-level-2-all)

Reproducible at least with Emacs 29 and 28.

This is not a glitch somehow caused by Eldev, I have the same problem in "normal" Emacs with a very recent installed package, i.e. where Eldev is not involved at all.

Since the commit itself looks harmless, I can only guess that something goes wrong as a side-effect of loading or not loading `cl-lib`.

I really wish you made stable releases more frequently than once in several years. The current stable is _very_ old and missing too many recent features. But this is a very large package, and it's not the first time the "rolling release" from MELPA.Unstable is _really_ unstable and buggy, and this is annoying.

**Comment by tarsius** [comment]
Contrary to what I claimed in the revert commit, this was just a silly bug. (`(- n)` and `(- n 1)` are not the same thing.)

**Comment by doublep** [comment]
Right, I also missed that.

I'd suggest you to add some automated tests for basic functionality that would catch complete breakage like this, regardless of reason.
