### ISSUE TITLE
Symbol’s function definition is void: seq-keep

### ISSUE THREAD

**Issue by jroimartin** [magit/magit#5011]
After updating Magit, it looks like this:

![image](https://github.com/magit/magit/assets/1223476/dd9a97fa-f4ab-4788-9848-d0955246ebea)

It seems that 84eaa20 causes the following error to show up:

```
magit-format-ref-labels: Symbol’s function definition is void: seq-keep
```

I followed these instructions but the problem persists.

> If you have just updated Magit, then restart Emacs. If that does not fix the issue, then also uninstall Magit and all dependencies that were updated at the same time, restart Emacs and then reinstall Magit.

Magit version: `Magit 20230921.2037 [>= 3.3.0.50-git], Transient 0.4.3, Git 2.41.0, Emacs 28.2, gnu/linux`

**Comment by jroimartin** [comment]
As a workaround I installed `seq-2.24` manually and added `(require 'seq-25)` to my init file. I guess this has to do with the builtin `seq` (v2.23 in my case) package being loaded first. I'm adding this comment here just in case it helps on debugging the issue.

**Comment by tarsius** [comment]
Last night I started using `seq-keep` in `forge` but did not add `seq-2.24` as a dependency. It is possible you updated packages at this point. I then noticed the issue thanks to CI and fixed it for `forge`. I then went on to using `seq-keep` in `magit` as well. I did add the dependency this time around.

So it is likely that just updating packages again would also have fixed this issue; the fact that you had to manually install `seq-2.24` speaks for that. If not -- if an older version of `seq` is being loaded, despite of the `package`-installed 2.24 being on the `load-path`, then it is most likely an issue with `package` or something internal to the `seq` backport package itself.

**Comment by tarsius** [comment]
You should not have to manually require `seq-25` because that's what the `package`-installed `seq.el` does:

```elisp
[snip]
;;; Code:

(if (version< emacs-version "25")
    (require 'seq-24)
  (require 'seq-25))

(provide 'seq)
;;; seq.el ends here
```

**Comment by jroimartin** [comment]
I think I found the issue.

GNU Emacs 28.2 comes with seq-2.23 built in and it does not upgrade built-in packages automatically. Thus, I had to install seq-2.24 manually. Also, the function seq-keep used by magit is not autoloaded, which requires to explicitly load the library.

Long story short, my current workaround is:

1. Install seq-2.24 manually.
2. Add `(load "seq")` to the init file.

Does it make sense?

**Comment by jroimartin** [comment]
Information about upgrading built-in packages in GNU Emacs 29: https://git.savannah.gnu.org/cgit/emacs.git/tree/etc/NEWS.29#n1714

**Comment by tarsius** [comment]
I've added an explicit `require`.

(You shouldn't use `load`. It is almost always better to use `require`.)

I'll have to look into those news. I don't use `package` myself, and assume(d) that it does not silently ignore explicitly specified dependency versions (by default, or ever).

**Comment by jroimartin** [comment]
However, I cannot use `(require 'seq)` because it seems the feature is already provided by `/usr/share/emacs/28.2/lisp/emacs-lisp/seq.elc` (instead of `~/.emacs.d/elpa/seq-2.24/seq.el`) when it is called in my init file. So `require` is ignored.

**Comment by tarsius** [comment]
I see. That probably means that something loads `seq` before `package-initialize` is called. Across Emacs releases, there are big difference in how and when that is automatically called for you, if at all, how you can call it explicitly instead, and what the recommended way of doing that is. It could be that this defaults to being broken, but it could also could be that you do something that results in this behavior (possibly because it at one point was recommended that you do that).

In other words I will have to investigate. Meanwhile, other users running into this, should first try to update, and if that alone doesn't work add `(require 'seq)` explicitly early on (but after `package-initialize`, if that can be found in `early-init.el` or `init.el`), and only if that also doesn't work, fall back to `(load 'seq)`.

If this is indeed a bug causes by the default configuration of some Emacs releases, or a common misconfiguration, then I might have to require `seq` like so:

```elisp
(when (and (featurep' seq)
      (not (fboundp 'seq-keep))
  (unload-feature 'seq))
(require 'seq)
```

**Comment by makohoek** [comment]
@jroimartin thank you for opening this. I confirm your work-around works for me as well. I'm also on emacs 28.2.

I've made a similar hack in my spacemacs config here:
https://github.com/makohoek/dotfiles/commit/c7868f96aa59fbc3c9777b42dddea6863ac94f66

**Comment by RastaDill** [comment]
Hello. Does anyone know how to install the previous version of the package?
Why used rolling release?

**Comment by qezz** [comment]
As a short-term solution, it's possible to have the `seq-keep` definition in `init.el`

```cl
(defun seq-keep (function sequence)
  "Apply FUNCTION to SEQUENCE and return the list of all the non-nil results."
  (delq nil (seq-map function sequence)))
```

After this magit works fine.

**Comment by tarsius** [comment]
I've installed the mentioned kludge.

**Comment by doolio** [comment]
Just ran into this issue. Uninstalling `magit` and its dependencies and re-installing doesn't install the latest version of the `seq` package. I use `straight.el` rather than `package.el` if that matters and am still on Emacs 27.1. The workaround mentioned [here](https://github.com/magit/magit/issues/5011#issuecomment-1732622958) is working for me though.

**Comment by tarsius** [comment]
@doolio You should probably report that to Straight's maintainers.

**Comment by tarsius** [comment]
Straight does not update dependencies and even ignores the specified minimal versions. See https://github.com/radian-software/straight.el/issues/1083.

**Comment by doolio** [comment]
> Straight does not update dependencies and even ignores the specified minimal versions.

The [latest commit ](https://github.com/radian-software/straight.el/commit/b3760f5829dba37e855add7323304561eb57a3d4) on straight's `develop` branch fixes this issue wrt `magit` at least.

**Comment by spacekookie** [comment]
I ran into this issue again on magit version `20231112.914`. I'm installing emacs and dependencies via nix, so manually side-loading `seq` isn't an option. But I thought it also wouldn't be required anymore in this version?

**Comment by Nebucatnetzer** [comment]
> I ran into this issue again on magit version `20231112.914`. I'm installing emacs and dependencies via nix, so manually side-loading `seq` isn't an option. But I thought it also wouldn't be required anymore in this version?

Do you have by chance a workaround for a Nix based config?

**Comment by crawford** [comment]
Thanks for the hint @mmarx. I've adapted it for Home Manager in case anyone is looking for that as well:

```nix
{
  programs = {
    emacs = {
      overrides = self: super: rec {
        // Taken from https://github.com/magit/magit/issues/5011#issuecomment-1838598138
        seq = self.callPackage ({ elpaBuild, fetchurl, lib }:
          elpaBuild rec {
            pname = "seq";
            ename = "seq";
            version = "2.24";
            src = fetchurl {
              url = "https://elpa.gnu.org/packages/seq-2.24.tar";
              sha256 = "1w2cysad3qwnzdabhq9xipbslsjm528fcxkwnslhlkh8v07karml";
            };
            packageRequires = [];
            meta = {
              homepage = "https://elpa.gnu.org/packages/seq.html";
              license = lib.licenses.free;
            };
            # tests take a _long_ time to byte-compile, skip them
            postInstall = ''rm -r $out/share/emacs/site-lisp/elpa/${pname}-${version}/tests'';
          }) {};
      };
    };
  };
}
```
