### ISSUE TITLE
Commit word-wrapping can result in discarded message.

### ISSUE THREAD

**Issue by comburent** [magit/magit#5020]
Magit version: `Magit 3.3.0-6.7a1d503, Transient 0.4.3, Git 2.41.0, Emacs 29.1, gnu/linux`

Consider the following line of text in the commit message body:
```
The %gnu-build-system-modules variable is intended to be used for the #:imported-modules parameter ….
```

Magit will automatically word-wrap this line to:
```
The %gnu-build-system-modules variable is intended to be used for the
#:imported-modules parameter ….
```
but the line-breaking doesn't account that the word now starts with `#` which results in the text following it to be discarded since it's interpreted as a comment.

It should be possible to begin a message line with `#` (perhaps by resorting to some exotic escape, some unicode non-printing character or a combination of both).
At the very least Magit should account for the first character in the word when word-wrapping to avoid having the remainder of the line treated as a comment and discarded.

**Comment by tarsius** [comment]
> It should be possible to begin a message line with `#`

You can configure another comment character, e.g., `git config --global core.commentChar ";"`.

**Comment by tarsius** [comment]
> Magit should account for the first character in the word when word-wrapping to avoid having the remainder of the line treated as a comment and discarded.

Magit (or more precisely `git-commit.el`) does not implement word-wrapping from scratch. It uses `auto-fill-mode`, which does account for complications related to comments, but apparently it does not deal with this particular issue. This is were such a feature should be implemented as it does not only apply to commit messages. (Maybe I overlooked something and there already is a knob that we can turn to get the desired behavior. Let me know if you find one.)
