### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by zenspider** [magit/magit#5025]
I'm trying to see if a bug I'm observing is already fixed, but I can't actually update magit:

```
     Status: Incompatible because it depends on uninstallable packages.
    Archive: melpa
    Version: 20231010.1103
     Commit: 139f603cb85e57baf0e3c657bc3d4860af3a9544
    Summary: A Git porcelain inside Emacs.
   Requires: emacs-25.1, compat-29.1.3.4 (not available), dash-20221013, git-commit-20230101, magit-section-20230101,
               seq-2.24 (not available), transient-20230201, with-editor-20230118
```

I'm on emacs 29.1 but the above dependencies (compat and seq) aren't available?

I've refreshed the package list to no avail. Clue me?

**Comment by tarsius** [comment]
You have probably used `setq` instead of `add-to-list` to modify `package-archives`. These packages are available from the `gnu` archive, which is part of the default value of that variable.

**Comment by zenspider** [comment]
yes and no... I have this:

```elisp
(dolist (repo '(("melpa"        . "http://melpa.org/packages/")
                ("melpa-stable" . "http://stable.melpa.org/packages/")
                ("gnu"          . "https://elpa.gnu.org/packages/")
                ("nongnu"       . "https://elpa.nongnu.org/nongnu/")
                ))
  (add-to-list 'package-archives repo))
```

so it SHOULD have been good... but what was really happening was I was getting bit by `package-archives` and `package-archive-priorities` that somehow got persisted into customize sans-gnu.

Thank you. Closing.
