### ISSUE TITLE
void-variable alist-get displaying sections

### ISSUE THREAD

**Issue by zenspider** [magit/magit#5026]
Welp. I finally got everything updated and my original bug is gone, but now I'm seeing this when I try to do pretty much anything with a section:

toggling:
```
Debugger entered--Lisp error: (void-variable alist-get)
  magit-section-cache-visibility(#<magit-section nil [untracked status] 566-[587-]1267>)
  magit-section-maybe-cache-visibility(#<magit-section nil [untracked status] 566-[587-]1267>)
  magit-section-show(#<magit-section nil [untracked status] 566-[587-]1267>)
  magit-section-toggle(#<magit-section nil [untracked status] 566-[587-]1267>)
  funcall-interactively(magit-section-toggle #<magit-section nil [untracked status] 566-[587-]1267>)
  call-interactively(magit-section-toggle nil nil)
  command-execute(magit-section-toggle)
```
changing branch:
```
Debugger entered--Lisp error: (void-variable alist-get)
  magit-section-cache-visibility(#<magit-section #<process git> [process processbuf] 1-[39-]248>)
  magit-section-maybe-cache-visibility(#<magit-section #<process git> [process processbuf] 1-[39-]248>)
  magit-section-hide(#<magit-section #<process git> [process processbuf] 1-[39-]248>)
  magit-process-finish(#<process git>)
  magit-process-sentinel(#<process git> "finished\n")
```

Magit 20231010.1103 [>= 3.3.0.50-git], Transient 0.4.3, Git 2.42.0, Emacs 29.1, darwin

this reproduces inside of: `magit-emacs-Q-command` with: `M-x magit-status RET TAB TAB`

**Comment by zenspider** [comment]
looks like alist-get was last patched in compat-26.el

**Comment by zenspider** [comment]
confirmed that changing it from `compat-call` to plain `alist-get` does indeed fix the problem. Not sure how far back you need magit compatibility to go or how to pull in the old `alist-get` in compat26

**Comment by tarsius** [comment]
You have to update `compat` to the latest release. This should happen automatically because `magit` explicitly depends on that.

**Comment by zenspider** [comment]
I did: `Version: 29.1.4.2`

**Comment by tarsius** [comment]
This is probably the old "obsolete loaded version leaks into new byte-code" issue. Uninstall magit, exit emacs, restart emacs, reinstall magit.

**Comment by zenspider** [comment]
Seems to be
