### ISSUE TITLE
Jump to pushremote-related sections in magit status buffer does not seem to work

### ISSUE THREAD

**Issue by jroimartin** [magit/magit#5029]
Starting from the following magit status buffer

![image](https://github.com/magit/magit/assets/1223476/bfda5e3d-0413-4d20-8e7a-cce87c2ef7e8)

This is the observed behavior when using the "Jump to section" commands:

- `jfu` (Unpulled from upstream): jumps to `Unpulled from origin/main`
- `jfp` (Unpulled from pushremote): echoes `Section "Unpulled from <push-remote>" wasn’t found`
- `jpu` (Unmerged into upstream): jumps to `Unmerged into origin/main`
- `jpp` (Unpushed to pushremote): echoes `Section "Unpushed to <push-remote>" wasn’t found`

I would expect:

- `jfp` to jump to `Unpulled from origin/branch`
- `jpp` to jump to `Unpushed to origin/branch`

Magit version:

```
Magit 20231006.2318 [>= 3.3.0.50-git], Transient 0.4.3, Git 2.41.0, Emacs 28.3, gnu/linux
```

**Comment by tarsius** [comment]
Thanks for the report!
