### ISSUE TITLE
Can't reorder commits with E (interactive rebase)

### ISSUE THREAD

**Issue by catphive** [magit/magit#503]
rebase-mode.el seems to prevent me from reordering commits during an interactive rebase. It doesn't let me kill and yank lines of text, so I don't see any way to change the order of commits.

**Comment by waffletower** [comment]
Yikes, annoying when someone adds a mode you don't yet know to Emacs...

**Comment by johnmastro** [comment]
Default package hubris? I don't understand. `git-rebase.el` is part of Magit, not Emacs.

(I'm not a Magit developer, just a confused reader)
