### ISSUE TITLE
Recent commits showing `^L` between elements.

### ISSUE THREAD

**Issue by 8dcc** [magit/magit#5044]
Inside the `magit-status` buffer, the recent commits show `^L` between the commit hash, author, etc. This has also been mentioned in a [stackoverflow post](https://emacs.stackexchange.com/questions/78971/hide-l-in-magit-log-buffer).

I tried restarting emacs, reinstalling magit, updating git, but nothing.

Screenshot of the issue:

![image](https://github.com/magit/magit/assets/29655971/2e6e8790-99a2-4ab5-a58e-d5720c97fdf8)

Magit version:
```
Magit v3.3.0-824-g2b02bfb0, Transient 0.4.3, Git 2.42.1, Emacs 28.2, gnu/linux
```

Git version:
```
git version 2.42.1
```

I think it's also important to not that I **didn't** have this issue while using this exact configuration in a different machine. I can post the version details of the other machine if needed.

**Comment by kyleam** [comment]
Magit uses those form feed characters as field separators when generating the log (specified via the `--format` in `magit--insert-log` and processed/washed by `magit-log-wash-rev`).  Your buffer likely ends up in that state because parsing the output fails for some reason.

I cloned the repo from your image; the recent commit sections were generated without error on my end (Magit 2b02bfb04, Emacs 29.1, Git 2.42.1, vanilla Emacs config):

```
Recent commits
0a0bd86 main origin/main Add "SPC p c" and "SPC p C" keybinds
57b4851 Add config.el
a9683bf Add rainbow-delimiters package
08bb08a Update rainbow colors
0dd33fb Move packages to config.org
ac4ea33 Change completion background
cecb2e5 Read config directly from config.org, instead of init.el
c01feba Add orderless packages for better completion
c921033 Add config.org file
778c792 Set org-link-descriptive by default
```

---

 * Do you see the issue just with this repo or in general?

 * If you generate the first few lines of that log from the command line, does anything look differ from the reference below?

   ```
   $ git log --format=%h%x0c%D%x0c%x0c%aN%x0c%at%x0c%s HEAD~5..HEAD
   0a0bd86^LHEAD -> main, origin/main, origin/HEAD^L^L8dcc^L1699314122^LAdd "SPC p c" and "SPC p C" keybinds
   57b4851^L^L^L8dcc^L1699312702^LAdd config.el
   a9683bf^L^L^L8dcc^L1699312656^LAdd rainbow-delimiters package
   08bb08a^L^L^L8dcc^L1699312497^LUpdate rainbow colors
   0dd33fb^L^L^L8dcc^L1699311065^LMove packages to config.org
   ```

 * Do you get a backtrace if you `M-x toggle-debug-on-error` and refresh the buffer?  You could also try to pinpoint an error by instrumenting `magit-log-wash-rev` and stepping through.

**Comment by 8dcc** [comment]
> Do you see the issue just with this repo or in general?

With all repos:

![image](https://github.com/magit/magit/assets/29655971/b5bbf0f2-7f16-436d-bf12-20499fcd19a9)

I tried putting:
```emacs-lisp
(defvar bootstrap-version)
(let ((bootstrap-file
        (expand-file-name "straight/repos/straight.el/bootstrap.el"
                          user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
      (url-retrieve-synchronously
        "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
        'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'magit)
```

In my `init.el` to check if it was because of another package, but the issue persisted:

![image](https://github.com/magit/magit/assets/29655971/6cb7d0c2-0b63-4d37-864b-5336ec992568)


> If you generate the first few lines of that log from the command line, does anything look differ from the reference below?

No, the output is the same:
```
0a0bd86^LHEAD -> main, origin/main, origin/HEAD^L^L8dcc^L1699314122^LAdd "SPC p c" and "SPC p C" keybinds
57b4851^L^L^L8dcc^L1699312702^LAdd config.el
a9683bf^L^L^L8dcc^L1699312656^LAdd rainbow-delimiters package
08bb08a^L^L^L8dcc^L1699312497^LUpdate rainbow colors
0dd33fb^L^L^L8dcc^L1699311065^LMove packages to config.org
```

Also, after making a commit with magit (Stage 2 files from status screen, `c c`, saving buffer), I get the following error in the minibuffer:

![image](https://github.com/magit/magit/assets/29655971/e57a8060-078d-4f56-9185-abe563427321)

Trying to push with `p p` gives the same error. Note that both the commit and the push were successful.

> Do you get a backtrace if you `M-x toggle-debug-on-error` and refresh the buffer?

Yes.

![image](https://github.com/magit/magit/assets/29655971/81dbe61d-08c6-4631-802a-e1e1f383fcf7)

Text backtrace:
```
Debugger entered--Lisp error: (void-function seq-keep)
  seq-keep(#f(compiled-function (name) #<bytecode 0x630b18883703ba9>) (#("origin/HEAD" 0 11 (face magit-branch-remote font-lock-face magit-branch-remote)) #("origin/main" 0 11 (face magit-branch-remote font-lock-face magit-branch-remote))))
  magit-format-ref-labels("HEAD -> refs/heads/main, refs/remotes/origin/main,...")
  magit-log-wash-rev(log 7)
  apply(magit-log-wash-rev (log 7))
  #f(compiled-function (&rest args2) #<bytecode -0x40a37344136579>)()
  magit-wash-sequence(#f(compiled-function (&rest args2) #<bytecode -0x40a37344136579>))
  magit-log-wash-log(log ("log" "--format=%h%x0c%D%x0c%x0c%aN%x0c%at%x0c%s" "--decorate=full" "-n10" "--use-mailmap" "--no-prefix" "HEAD~10..HEAD" "--"))
  apply(magit-log-wash-log (log ("log" "--format=%h%x0c%D%x0c%x0c%aN%x0c%at%x0c%s" "--decorate=full" "-n10" "--use-mailmap" "--no-prefix" "HEAD~10..HEAD" "--")))
  #f(compiled-function (&rest args2) #<bytecode -0x24c0978b041757f>)(("log" "--format=%h%x0c%D%x0c%x0c%aN%x0c%at%x0c%s" "--decorate=full" "-n10" "--use-mailmap" "--no-prefix" "HEAD~10..HEAD" "--"))
  magit--git-wash(#f(compiled-function (&rest args2) #<bytecode -0x24c0978b041757f>) nil "log" "--format=%h%x0c%D%x0c%x0c%aN%x0c%at%x0c%s" ("--decorate=full" "-n10") "--use-mailmap" "--no-prefix" "HEAD~10..HEAD" "--" nil)
  magit--insert-log(nil "HEAD~10..HEAD" ("-n10" "--decorate"))
  magit-insert-recent-commits(unpushed "@{upstream}..")
  magit-insert-unpushed-to-upstream-or-recent()
  apply(magit-insert-unpushed-to-upstream-or-recent nil)
  magit-run-section-hook(magit-status-sections-hook)
  magit-status-refresh-buffer()
  magit-refresh-buffer()
  magit-refresh()
  funcall-interactively(magit-refresh)
  call-interactively(magit-refresh nil nil)
  command-execute(magit-refresh)
```

**Comment by tarsius** [comment]
Duplicate of See https://github.com/magit/magit/issues/5011.

Straight didn't support installing the updated `seq` from GNU Elpa, but Magit started depending on that updated version (or alternatively the latest Emacs release). See https://github.com/radian-software/straight.el/pull/1125.

Straight also does not update dependencies and even ignores the specified minimal versions. See https://github.com/radian-software/straight.el/issues/1083.

While you update `seq`, also update `transient`. If things don't work after updating, then uninstall all involved packages, exist Emacs, restart Emacs, and only then reinstall.

**Comment by 8dcc** [comment]
Indeed, that fixed it. I just noticed that the version in my two machines is different, so that's probably why it was fine in one of them.
