### ISSUE TITLE
issues with compat.el

### ISSUE THREAD

**Issue by DaKnig** [magit/magit#5057]
`M-x package-install (return) magit` doesn't work. it throws an error: "https://elpa.gnu.org/packages/compat-29.1.4.2.tar: Not found". and indeed this file doesn't exist, but that file .lz does exist on the server.

I am no emacs expert. I run emacs 29.1 and enjoy it very much, and usually enjoy it with a bit more magit.

this is an issue I see on a specific machine. I cant give steps to reproduce since I cant uninstall/reinstall emacs on it. sorry for that.

as to the backtrace, not sure it is relevant.

and then going through the steps again should result in a backtrace.

cant install magit, thus cant say what version I have (have none).

would love to get some pointers on how to make it work anyway without waiting for an update.

**Comment by tarsius** [comment]
Run `M-x package-refresh-contents` and try again.
