### ISSUE TITLE
transient-prefix-object requires transient 0.5.0

### ISSUE THREAD

**Issue by progfolio** [magit/magit#5059]
Ran into this error today:

```
transient-setup: Symbol’s function definition is void: transient-prefix-object
```

Magit declares a min version of 0.3.6 for transient.el.

https://github.com/magit/magit/blob/5ad367d7a3094fb6098c1d8e457ed80630ed3e5e/lisp/magit.el#L28

Should be bumped due to the changes in 5ad367d, no?
Will there be a matching bump for the bundled Emacs version of transient.el?

**Comment by tarsius** [comment]
Thanks for the reminder!

I've bumped the dependencies in 51fc450b6eb440381708bdfcade351c9efc31f2d.

**Comment by djgoku** [comment]
I use `elpaca`, nix (emacs-overlay) and I had to add the below since `emacs-git` is using `transient` 0.4.2.

Thank you for the fix @tarsius 

```
(use-package transient)
```
