### ISSUE TITLE
Magit displays warning about transient version, even though I'm using the latest.

### ISSUE THREAD

**Issue by eamonnsullivan** [magit/magit#5069]
Magit version: `Magit v3.3.0-853-gc7ab6931, Transient 0.5.3, Git 2.39.3, Emacs 28.2, darwin`
Emacs version: `GNU Emacs 28.2 (build 2, aarch64-apple-darwin22.1.0, NS appkit-2299.00 Version 13.0 (Build 22A8380)) of 2023-04-27`

    (1) what behavior you expected

Magit should work without displaying a warning about upgrading transient.

    (2) what behavior you observed

Magit displays this warning, although I'm using straight.el and am using transient version v0.5.3.
```
Emergency (magit): Magit requires ‘transient’ >= 0.5.0,
but due to bad defaults, Emacs’ package manager, refuses to
upgrade this and other built-in packages to higher releases
from GNU Elpa.

To fix this, you have to add this to your init file:

  (setq package-install-upgrade-built-in t)

Then evaluate that expression by placing the cursor after it
and typing C-x C-e.

Once you have done that, you have to explicitly upgrade ‘transient’:

  M-x package-upgrade transient \‘RET’

Then you also must make sure the updated version is loaded,
by evaluating this form:

  (progn (unload-feature ’transient t) (require ’transient))

If you don’t use the ‘package’ package manager but still get
this warning, then your chosen package manager likely has a
similar defect. Disable showing Disable logging
```
    (3) and how we can reproduce the issue.

Install magit through straight.el

**Comment by eamonnsullivan** [comment]
I'm guessing that magit is checking something that is only working on package.el and maybe needs to use a more generic test? The magit-version returns the transient version loaded. Maybe that would be better?

**Comment by kyleam** [comment]
> I'm guessing that magit is checking something that is only working on package.el and maybe needs to use a more generic test?

It checks that `transient-prefix-object`, which was added Transient 0.5.0, is bound:

https://github.com/magit/magit/blob/c7ab6931c61e63db02edd2f9ad3688312936cf0b/lisp/magit-mode.el#L38-L43

So it looks to me as though this is flagging a real problem in your setup.

**Comment by eamonnsullivan** [comment]
Yup, that looks generic enough. Maybe I'm not loading things in the right order. I'll try loading transient first.

**Comment by eamonnsullivan** [comment]
I've moved magit to one of the first things I'm loading and the warning goes away, so I must have been loading something with a dependency on an earlier version of transient, or some other race condition. Apologies. Happy Christmas!

**Comment by olessavluk** [comment]
Got same error after updating emacs, only nuking whole `emacs.d` folder and reinstalling everything from scratch helped. Likely some broken caches
