### ISSUE TITLE
magit-diff-paths output is not washed

### ISSUE THREAD

**Issue by kyleam** [magit/magit#5094]
### Discussed in https://github.com/magit/magit/discussions/5093

<div type='discussions-op-text'>

<sup>Originally posted by **gustav-b** February 16, 2024</sup>
Using `Magit 20240211.1712 [>= 3.3.0.50-git], Transient 0.5.3, Git 2.43.2, Emacs 29.2, darwin`

Not sure if this is expected, but if I diff two files in a working directory using `d p` (`magit-diff-paths`) the resulting buffer is without any colors/highlighting. Any other diff I get from Magit is colored. For example:

`magit-diff-working-tree`:
<img width="1040" alt="magit-diff-working-tree" src="https://github.com/magit/magit/assets/368219/af17611f-9774-422c-aafb-03c673f1cc5b">

`magit-diff-paths`:
<img width="1037" alt="magit-diff-paths" src="https://github.com/magit/magit/assets/368219/f2dd9286-48d7-4d84-82a9-8f5bde557b70">

Is this a bug? If not, how do I enable coloring for path diffs? </div>

---

My reply from <https://github.com/magit/magit/discussions/5093#discussioncomment-8498799>

>> Is this a bug?
>
> Yes.
> 
> As of [78a979f](https://github.com/magit/magit/commit/78a979fde52815242b165f083d171259db28e0b4) (Support displaying errors that occur when washing a section, 2023-03-18), the diff buffer is washed only if the `git diff` command exits with a zero status. That's a problem with `git diff --no-index ...` because exits with 1 if there are differences (like `diff(1)`).

**Comment by tarsius** [comment]
Thanks @kyleam. I've pushed a fix.
