### ISSUE TITLE
Binding C-<tab> conflicts with Emacs' tab-bar-mode

### ISSUE THREAD

**Issue by gerd-moellmann** [magit/magit#5106]
I recently submitted [bug#69578](https://lists.gnu.org/archive/html/bug-gnu-emacs/2024-03/msg00263.html) to Emacs, about the interference of `tab-bar-mode` global binding of `C-<tab>` with Magit. Juri Linkov then asked if Magit could perhaps avoid using `C-<tab>` which he said Org had already done.

I submit this as an issue because `tab-bar` is part of Emacs, and thus Magit's binding of `C-<tab>` conflicts with Emacs, somewhat. 

I'm currently using this in my `init.el`, to make tabs more usable, if that makes it clearer.

```
(keymap-unset magit-section-mode-map "C-<tab>")
```

(And thanks for Magit, BTW :-)).

**Comment by tarsius** [comment]
Addressed in 8a3c1ccdda8185255ce76adc2ba41b9a43f18b8c. See debbugs for more information.
