### ISSUE TITLE
Confirm commit message when running emacs as client

### ISSUE THREAD

**Issue by pascal-niklaus** [magit/magit#5114]
I am always running emacs as client, primarily because of the speedy startup. 

    (1) what behavior you expected

When using magit and making a commit, I would like to be able to confirm the commit message (C-c C-c) without my entire emacs session with all the other visited buffers closing, i.e. just the window with the commit message should close.

    (2) what behavior you observed

When I hit C-c C-c, my entire emacs client with all the other documents I am working on terminates.

    (3) and how we can reproduce the issue.

- start emacs as a client and edit some files
- prepare a commit using magit
- confirm the commit message with C-c C-c

Is there a way to work around this issue?

**Comment by kyleam** [comment]
> When using magit and making a commit, I would like to be able to confirm the commit message (C-c C-c) without my entire emacs session with all the other visited buffers closing, i.e. just the window with the commit message should close.

That's the intended behavior.  Perhaps there is something tailored or misconfigured about your setup that is tripping [with-editor](https://github.com/magit/with-editor) up.  https://magit.vc/manual/with-editor/Debugging.html may be a good place to start.

**Comment by pascal-niklaus** [comment]
> That's the intended behavior.

Maybe I was not very clear.

When I edit a file starting emacs like this...

    emacs a.txt

...and do some changes, switch to magit status, stage the file, and commit, everything works as intended. The commit message goes away, emacs stays open, and I can continue working.

When I, however, start emacs like so

    emacsclient -c a.txt

...then confirming the commit with C-c C-c closes the whole client, not just the commit message window.

My impression is that Magit simply assumes that only the commit message editing runs as client, and that users have not set up emacs to always run as client, with the emacs server running in the background as daemon (in my case started by systemd -- https://www.emacswiki.org/emacs/EmacsAsDaemon).

**Comment by kyleam** [comment]
> My impression is that Magit simply assumes that only the commit message editing runs as client, and that users have not set up emacs to always run as client, with the emacs server running in the background as daemon

No, I don't think that's accurate. I've used emacsclient as the entry point for my main session for a long time.  My impression is that many people do so.

**Comment by pascal-niklaus** [comment]
Your are right, I had the following function in my config, which caused this behaviour:

     (custom-set-variables
          '(server-done-hook (quote ((lambda nil (kill-buffer nil)) delete-frame))))

After removing it, the client does no longer shut down.

**Comment by kyleam** [comment]
@pascal-niklaus Glad to hear you found the culprit.
