### ISSUE TITLE
Trying to visit files in `magit-diff-paths` output leads to wrong path

### ISSUE THREAD

**Issue by gustav-b** [magit/magit#5116]
If I diff two files using the `d p` (`magit-diff-paths`) and then try to visit the files from the resulting diff buffer using `RET` (`magit-diff-visit-file`), this will fail because the attempted path is wrong.

Using `Magit 20240320.2336 [>= 3.3.0.50-git], Transient 0.6.0, Git 2.44.0, Emacs 29.3, darwin`

Steps to reproduce:
1. In a repos `/tmp/foo`, `magit-diff-paths` the files `a.txt` and `b.txt`
2. The resulting buffer will say `Differences between /tmp/foo/a.txt and /tmp/foo/b.txt` (correct)
3. Now press `RET` in this buffer to visit `b.txt`
**Expected behavior**: `/tmp/foo/b.txt` is opened.
**Actual behavior**:  Emacs tries to open `/tmp/foo/tmp/foo/b.txt` instead: `process-file: Setting current directory: No such file or directory, /tmp/foo/tmp/foo/`

<img width="799" alt="magit-1" src="https://github.com/magit/magit/assets/368219/19959d83-e420-4e2d-bc8d-72ef75dbf238">
<img width="801" alt="magit-2" src="https://github.com/magit/magit/assets/368219/dc74e8b3-e023-4389-bcba-971e649ed811">

**Comment by tarsius** [comment]
That's fixed now. Sorry for the delay.
