### ISSUE TITLE
submodule update with universal argument still prompts for submodule selection when there is only one submodule

### ISSUE THREAD

**Issue by Atemu** [magit/magit#5122]
According to https://github.com/magit/magit/discussions/4953, you can prefix submodule operations with the universal argument in order to make them apply to all submodules. This works when there are multiple submodules but interestingly not when there is only a single one; in that case it asks you to select from a list of one.

**Comment by tarsius** [comment]
Thanks for the report!

**Comment by Atemu** [comment]
Thanks for the fix!
