### ISSUE TITLE
Some update broke my custom git-commit-hook to insert comment into commit buffer

### ISSUE THREAD

**Issue by ipvych** [magit/magit#5132]
Hi, I have following piece of code in my config to insert custom text into git commit buffer after it is created
```elisp
(defun ipv-magit-git-commit-setup ()
  "Hook for `git-commit-mode-hook' to setup my preffered options."
  (save-excursion
    (comment-search-forward (point-max))
    (move-beginning-of-line nil)
    (insert "# The commit subject line ought to finish the phrase:"
            "\n# \"If applied, this commit will <your subject line here>.\"\n\n")))

(add-hook 'git-commit-mode-hook #'ipv-magit-git-commit-setup)
```

After updating magit at 2024-04-21 without updating it for like a month or so commiting changes **when this hook is enabled** started resulting in 
`Git failed ... [Hit $ to see buffer magit-process: ivan for details]` error message with the contents of magit process buffer being
```
1 git … commit --
hint: Waiting for your editor to close the file...
Waiting for Emacs...
*ERROR*: No comment
```
There is no backtrace or error produced with `toggle-debug-on-error` enabled when this error happens

My current `magit-version` is `Magit 20240428.1821 [>= 3.3.0.50-git], Transient 0.6.0, Git 2.44.0, Emacs 29.3, gnu/linux`.
I can reproduce this error using `emacs -Q` by installing magit, evaluating that piece of code & trying to commit anything

**Comment by ipvych** [comment]
Found out that git has builtin way to insert such text using `commit.template` option. Should have checked this beforehand, sorry for if this issue is irrelevant, feel free to close it if you don't think this is a bug, using this option in git settings is enough for me as I only want to insert static text there.

**Comment by tarsius** [comment]
You should use `git-commit-setup-hook` instead of `git-commit-mode-hook`. I've quickly tried your function with the former and it works, while with the latter it doesn't work for me either.

I'll look into making it more obvious that one should not use `git-commit-mode-hook`.

**Comment by tarsius** [comment]
> I'll look into making it more obvious that one should not use `git-commit-mode-hook`.

If done this instead: e37c9ea4dec249ee95672dfba280e94ac870e263.
