### ISSUE TITLE
Magit push doesn't respect configured refspecs

### ISSUE THREAD

**Issue by Haxxflaxx** [magit/magit#5133]
I'm using gerrit, which requires me to push towards `origin HEAD:refs/for/<branch>`.
To not have to specify this using `magit-push-refspecs` I instead set the remote.origin.push to `refs/heads/*:refs/for/*`.
I expected this to allow me to just push normally but it continued push towards `refs/heads/<branch>`.

Looking into the implementation this is quite obvious as the ref specs are more or less hard coded.
I'm assuming this is for a good reason, but in my particular case it would be better to leave them out and let git insert them as needed from the variable.

Magit Version:
Magit 20240423.2030 [>= 3.3.0.50-git], Transient 0.6.0, Git 2.34.1, Emacs 29.3, gnu/linux

**Comment by tarsius** [comment]
> Looking into the implementation this is quite obvious as the ref specs are more or less hard coded.
> I'm assuming this is for a good reason,

Magit provides different key bindings (and thus commands) to push to different locations. It is important that each of these keys has consistent behavior.

Relying solely on trivial arguments to `git push` as documented in its man pages, does not achieve that. The behavior depends on several options, whose descriptions are scattered across the documentation.

But again, the idea behind Magit's push commands is that they behave consistently, so it makes sense to not rely on `git push`'s complex logic. The main effect of using Git's logic would be an increase in predictability. Git's logic makes sense (IMO only to an extend), but it is optimized for reducing how much users have to type in to shell, to achieve their preferred kind of push, which happens to differ vastly between users. That logic doesn't make much sense for Magit, where we can provide *different* commands for different needs, which are more predicable, and can be invoked with less key presses than it takes to type `git`.

> I'm using gerrit, 

"Pushing to Gerrit" is another special case. If I were in your situation I would implement a dedicated command for that. (There are several Emacs packages for Gerrit, at least one of them specifically targeting Magit. That should provide such a command.)

Magit also features the `magit-push-implicitly`, which *does* respect all git variables. It's docstring also explains how to add that to the push menu.

**Comment by Haxxflaxx** [comment]
`magit-push-implicitly` was exactly the thing I was looking for.
Thank you.

Making a specific command for pushing to gerrit might also be a good idea.

**Comment by wojciech-graj** [comment]
An alternative solution from https://emacs.stackexchange.com/a/19723

`P` `r` `origin` `RET` `HEAD:refs/for/master` `RET`
