### ISSUE TITLE
Pressing RET (magit-visit-thing) on an URL in the magit-process buffer doesn't open URL

### ISSUE THREAD

**Issue by dimsuz** [magit/magit#5134]
When pushing to a PR on Github/Gitlab, the server often helpfully posts a link to a created/updated PR. My workflow is to always visit it and edit/review the PR.

```
remote: Resolving deltas: 100% (79/79), completed with 40 local objects.        
remote: 
remote: View merge request for my-branch-name:        
remote:   https://gitlab.com/group/project/-/merge_requests/994        
remote: 
```

This is displayed in Magit's `magit-process` buffer and the link is correctly underlined and when mouse-clicked, external browser is opened, as desired.

But when pressing RET on this link the output I get is:

> magit-visit-thing: There is no thing at point that could be visited

It would be nice if I wouldn't have to reach out for the mouse and for RET to work too.

Sorry I can't create a PR for this as I'm new to elisp and emacs/magit internals...

---

Magit version (I'm using Doom Emacs): 
> Magit b5637d6, Transient 0.6.0, Git 2.45.0, Emacs 29.3, gnu/linux

**Comment by dimsuz** [comment]
I noticed a typo introduced by this commit, suggested fix:

```diff
-  "This is a placeholder command, which may signals an error if called.
+  "This is a placeholder command, which may signal an error if called.
```

**Comment by tarsius** [comment]
More like a changed-contexto :grinning:
