### ISSUE TITLE
Magit hangs on staging hunk over tramp

### ISSUE THREAD

**Issue by mgrunwald** [magit/magit#5154]
I encounter the same bug as this one:
https://github.com/magit/magit/issues/4870

I.e.: when I try to stage a part of a hunk via tramp, I see this message:
```
Tramp: Opening connection git for ha using ssh...done
```
and magit is stuck. I can C-g to continue, but the hunk is not staged. Enabling `debug-on-quit` results in:
```
Debugger entered--Lisp error: (quit)
  sleep-for(0.005)
  magit-run-git-with-input("apply" ("--cached") "-p0" nil "--ignore-space-change" "-")
  magit-apply-patch(#<magit-file-section "fhem.cfg" [file unstaged status] 98041-[98061-]156616> ("--cached") #("diff --git fhem.cfg fhem.cfg\nindex 5194395..a63404..." 29 85 (fontified nil)))
  magit-apply-region(#<magit-hunk-section (nil (27 14) (37 14)) [hunk file unstaged status] 99938-[100032-]100821> "--cached")
  magit-stage(nil)
  funcall-interactively(magit-stage nil)
  command-execute(magit-stage)
```

Versions:
```
Magit 20240614.2318 [>= 3.3.0.50-git], Transient 0.6.0, Git 2.20.1, Emacs 29.2, gnu/linux
Tramp: 2.6.2.29.2
```

Edit-start: I also ran the `magit-emacs-Q-command` and its output:
```
 /usr/local/bin/emacs -Q --eval \(setq\ debug-on-error\ t\) -L /home/markus/.emacs.d/elpa/compat-29.1.4.5/ -L /home/markus/.emacs.d/elpa/dash-20240510.1327/ -L /home/markus/.emacs.d/elpa/transient-20240609.2020/ -L /home/markus/.emacs.d/elpa/with-editor-20240609.1518/ -L /home/markus/.emacs.d/elpa/magit-20240614.2318/ -L /home/markus/.emacs.d/elpa/magit-section-20240613.2254/ -L /home/markus/.emacs.d/elpa/git-commit-20240520.1135/ -l /home/markus/.emacs.d/elpa/magit-20240614.2318/magit
```
... with the exact same result.
Edit-end. 

I did as the template suggested and uninstalled/reinstalled magit but that didn't help. I don't rule out that I still have an old version somehow, but then I'd need some help to detect/remedy that, please.

**Comment by tarsius** [comment]
While I usually don't like it when users necrobump issues, in this case I recommend you post on  #3624. That would reach the users who previously run into this issue and they might be able to help you. I don't have the time to walk through this with yet another user. I also don't use Tramp.
