### ISSUE TITLE
`with-editor-file-name-history-exclude` incorrectly doesn't apply to home directory paths

### ISSUE THREAD

**Issue by jcreedcmu** [magit/magit#5159]
Thank you for magit, it is my favorite git porcelain, and also thanks for your excellent issue-reporting documentation and infrastructure.

Summary
--------
The intended effect of
```
(add-to-list 'with-editor-file-name-history-exclude git-commit-filename-regexp)
```
(from [this code here](https://github.com/magit/magit/blob/be549268313bdcc6008285312a4ac5367d3b4402/lisp/git-commit.el#L510)) is not working for me on paths that are inside my home directory. That is:

(1) I expect `.git/COMMIT_EDITMSG` files to not appear in `file-name-history`
(2) I observe `.git/COMMIT_EDITMSG` files appearing in `file-name-history`, in the special case that the git repository in question is inside my home directory.

### Diagnosis

I believe the issue is caused by home directory paths being inconsistently abbreviated to `~`, causing the `delete` in [this advice](https://github.com/magit/with-editor/blob/main/lisp/with-editor.el#L723) to the function `server-visit-files` to have no effect --- because it's trying to delete `/home/$USER/.../COMMIT_EDITMSG` but `file-name-history` contains `~/.../COMMIT_EDITMSG`.

I'm not sure what the proper resolution is, but I have a workaround below. If you feel this issue should instead be filed against https://github.com/magit/with-editor/ I would be happy to do so.

Steps-to-Reproduce
------------------

`M-x magit-emacs-Q-command RET` instructed me to run:
```
/usr/local/bin/emacs -Q --eval \(setq\ debug-on-error\ t\) \
  -L /home/jcreed/.emacs.d/elpa/compat-29.1.4.5/ \
  -L /home/jcreed/.emacs.d/elpa/dash-20240510.1327/ \
  -L /home/jcreed/.emacs.d/elpa/transient-20240622.1240/ \
  -L /home/jcreed/.emacs.d/elpa/with-editor-20240618.1840/ \
  -L /home/jcreed/.emacs.d/elpa/magit-20240622.2136/ \
  -L /home/jcreed/.emacs.d/elpa/magit-section-20240621.2229/ \
  -L /home/jcreed/.emacs.d/elpa/git-commit-20240618.1142/ \
  -l /home/jcreed/.emacs.d/elpa/magit-20240622.2136/magit
```
after which `M-x magit-version` gives:
```
Magit 20240622.2136 [>= 3.3.0.50-git], Transient 0.7.1, Git 2.34.1, Emacs 29.3, gnu/linux
```

In that emacs I then do the following:
- Open a file in git repository whose path begins with `/home/$USER`, for example in my case `/home/jcreed/proj/twelf-mac/README.md`
- Make some trivial change to that file
- Do `M-x magit-status RET`, stage the change, and then `c c C-c C-k` to start making a commit, and abandon that commit.
- Observe that the elisp variable `file-name-history` contains a `COMMIT_EDITMSG` file (in my case specifically `~/proj/twelf-mac/.git/COMMIT_EDITMSG`).
  *Note that the directory that appears in `file-name-history` has been normalized to contain `~` instead of `/home/$USER`!* I believe this is the crux of the undesired behavior.

For comparison, if I instead repeat the above procedure outside my home directory, e.g. on `/tmp/some-git-repository/README.md`, then `file-name-history` does *not* contain `/tmp/foo/.git/COMMIT_EDITMSG`, as desired. The undesired behavior seems to only occur when working with paths in my home directory.

Workaround
----------

I found that I could get the desired behavior by simply wrapping `abbreviate-file-name` around `file` in the advice to `server-visit-files`. Specifically I evaluated:

```
(advice-remove 'server-visit-files
            'server-visit-files@with-editor-file-name-history-exclude)

(defun workaround-server-visit-files--with-editor-file-name-history-exclude
    (files _proc &optional _nowait)
  (pcase-dolist (`(,file . ,_) files)
    (when (cl-find-if (lambda (regexp)
                        (string-match-p regexp file))
                      with-editor-file-name-history-exclude)
      (setq file-name-history (delete (abbreviate-file-name file) file-name-history)))))
;                                     ^^^^^^^^^^^^^^^^^^^^^     ^
;                                      this is my change
(advice-add 'server-visit-files :after
            #'workaround-server-visit-files--with-editor-file-name-history-exclude)
```
If I repeat my steps-to-reproduce above, `COMMIT_EDITMSG` was correctly removed from `file-name-history`.

I don't know if this workaround has unintended consequences elsewhere.

**Comment by tarsius** [comment]
Thanks for the report!

**Comment by jcreedcmu** [comment]
Great! Glad the solution is as simple as that, then.
