### ISSUE TITLE
Unable to install with elpaca

### ISSUE THREAD

**Issue by nathanvy** [magit/magit#5161]
I am attempting to install magit via elpaca, and I am unable (see screenshot).

<img width="1037" alt="Screenshot 2024-06-27 at 10 42 16 PM" src="https://github.com/magit/magit/assets/2128134/27e5a549-035c-45ae-a265-cc626b9767c0">

It appears that magit depends on `git-commit` which depends on something called `transient`.

The relevant invocation from my init file is simply `(use-package magit)` which causes `elpaca` to pull from github behind the scenes.  I thought perhaps I had an old version of `transient` cached somewhere but I nuked my `.emacs.d/` directory completely and the issue persists, so I'm completely at a loss as to how the version is incorrect and have no idea how to debug this any further.  Please help!

**Comment by tarsius** [comment]
I don't know enough about elpaca to be able to help you.

Maybe @progfolio can help.

**Comment by progfolio** [comment]
@nathanvy please see https://github.com/progfolio/elpaca/issues/324#issuecomment-2192762062
