### ISSUE TITLE
magit-blame should ignore `git gc` stderr

### ISSUE THREAD

**Issue by Feyorsh** [magit/magit#5175]
# Problem
(1) Expectation: `magit-blame` to run without error
(2) Observed: `Lisp error: (error "Blaming failed due to unexpected output: Auto packing the repository in background for optimum performance.")`
(3) Reproduce: `git clone --filter=blob:none https://github.com/NixOS/nixpkgs.git` and `M-x magit-blame RET b` (pick your large repository of choice, make sure to make a blobless clone though)

When using `git scalar` features for large repositories (e.g. partial clones), `git` will emit garbage collection information to stderr, like so:
```
git blame --incremental -- pkgs/tools/bootloaders/refind/default.nix > /dev/null
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
...
```
This is problematic, because `magit-blame-process-filter` is not well equipped to handle these messages, e.g.
```
git blame --incremental -- pkgs/tools/networking/ntp/default.nix
<output truncated>
summary ntp: add license
previous 4920d7adb07c653d0480bcd1fb99ba9b366f2f64 pkgs/tools/networking/ntp/default.nix
filename pkgs/tools/networking/ntp/default.nix
6aba5e26b3bf79ba8e193ea3ece74011c1b33ce0 47 36 1
previous 4920d7adb07c653d0480bcd1fb99ba9b366f2f64 pkgs/tools/networking/ntp/default.nix
filename pkgs/tools/networking/ntp/default.nix
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
2d679dbe745e05e62a0f14c0fad12f83f3d4e2b3 9 2 1
author Tuomas Tynkkynen
...
```

It's possible there are other Magit processes that would need their stderr redirected (ignored), but I haven't run into any issues besides blaming.

## Backtrace
```
Debugger entered--Lisp error: (error "Blaming failed due to unexpected output: Auto packing the repository in background for optimum performance.")
  error("Blaming failed due to unexpected output: %s" "Auto packing the repository in background for opti...")
  magit-blame--parse-chunk(addition)
  magit-blame-process-filter(#<process git> "Auto packing the repository in background for opti...")
  sit-for(0.01)
  magit-blame-mode(-1)
  magit-blame-quit()
  funcall-interactively(magit-blame-quit)
  command-execute(magit-blame-quit)
```

# Fix
I believe the easiest fix is to modify the blame process launch to pass in a buffer for `stderr` to be redirected to (see Async Processes in the [manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Asynchronous-Processes.html)).

I'm attaching a patch that seems to fix the issue, but is certainly not up to the standards of the rest of the Magit codebase; I'd be happy to spin this off into a PR if you'd like.
[0001-magit-process-redirect-stderr.patch](https://github.com/user-attachments/files/16254490/0001-magit-process-redirect-stderr.patch)

The other, potentially less intrusive, fix is to make `magit-blame-process-filter` aware of these auto packing messages. This fix doesn't seem very future-proof, but would require changing only one function.

# Version Information
```
M-x magit-emacs-Q-command
/nix/store/ismv7jzf3hcqziq5bpjfs54zd4qfjjn7-emacs-mac-macport-29.1/Applications/Emacs.app/Contents/MacOS/Emacs -Q --eval \(setq\ debug-on-error\ t\) -L /nix/store/cfw9z6gs1jykvza55ghzjk07j9239rn8-emacs-packages-deps/share/emacs/site-lisp/elpa/compat-29.1.4.5/ -L /nix/store/cfw9z6gs1jykvza55ghzjk07j9239rn8-emacs-packages-deps/share/emacs/site-lisp/elpa/dash-20240405.946/ -L /nix/store/cfw9z6gs1jykvza55ghzjk07j9239rn8-emacs-packages-deps/share/emacs/site-lisp/elpa/transient-20240421.1737/ -L /nix/store/cfw9z6gs1jykvza55ghzjk07j9239rn8-emacs-packages-deps/share/emacs/site-lisp/elpa/with-editor-20240415.1558/ -L ~/Downloads/magit/lisp/ -L /nix/store/cfw9z6gs1jykvza55ghzjk07j9239rn8-emacs-packages-deps/share/emacs/site-lisp/elpa/magit-section-20240426.1325/ -L /nix/store/cfw9z6gs1jykvza55ghzjk07j9239rn8-emacs-packages-deps/share/emacs/site-lisp/elpa/git-commit-20240415.1544/ -l ~/Downloads/magit/lisp/magit
```
```
M-x magit-version
Magit v3.3.0-1043-g9d1f8db5-dirty, Transient 0.6.0, Git 2.44.1, Emacs 29.1, darwin
```

**Comment by tarsius** [comment]
Do you actually know that gc messages are send to stderr? I would like to verify that but don't know how I can force `git blame` to gc, so that I can verify.

**Comment by kyleam** [comment]
> Do you actually know that gc messages are send to stderr?

Yep, the gc messages go to stderr.  Note that stdout is sent to `/dev/null` in the initial example.

Here's a standalone minimal example with that Magit repo:

```sh
#!/bin/sh

set -eu

tdir=$(mktemp -d "${TMPDIR:-/tmp}"/magit-5175-XXXXXXX)
git clone --filter=blob:none https://github.com/magit/magit.git "$tdir" >/dev/null 2>&1
cd "$tdir"
git blame --incremental -- lisp/git-commit.el >/dev/null
```

If you run that as is, you'll see the fetch chatter like

```
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (1/1), 4.40 KiB | 1.10 MiB/s, done.
```

And you'll also see some messages for the auto gc triggered by that object fetching:

```
Auto packing the repository in background for optimum performance.
See "git help gc" for manual housekeeping.
```

If you redirect standard error to a file, Git suppresses the fetch progress output, but the gc messages remain.

**Comment by tarsius** [comment]
Thanks for confirming, @kyleam.

I've pushed a fix.  It is somewhat risky, especially so shortly before a release.  I was on the fence about doing this now.  I've done it because `magit-parse-git-async` isn't used by anything but blaming.  But if issues arise, simply reverting this is a likely course of action.  (After all dealing with blaming having failed because of gc is simple: just blame again, no gc will happen this time around.)

After the release we can refine this and look into using `make-process` in `magit-start-process` as well.
