### ISSUE TITLE
Refs buffer not remembering arguments?

### ISSUE THREAD

**Issue by daemianmack** [magit/magit#5177]
@tarsius I interpret PR #2898 to mean I should be able to...

1. eval `(magit-show-refs)` (or hit `y` from the magit status buffer)
2. sort the resulting list of branches (`C-u y -s <choose> y` to select and view a custom sort)
3. exit this view via `magit-mode-bury-buffer` (or `q`)
4. and, because of that PR's changes, eval `(magit-show-refs)` again, now _seeing the custom sort from step 2 applied_

I don't. Am I mis-interpreting?

magit-version: Magit 20240713.1925 [>= 3.3.0.50-git], Transient 0.7.3, Git 2.39.1, Emacs 29.1, darwin

**Comment by tarsius** [comment]
If you want to always use the same arguments in all repositories, but they are different from the default arguments, then you can permanently save your preference. To do so bring up the prefix command and usual, set the arguments to your liking, and then safe them using `C-x C-s`.

`magit-show-refs` can also remember the chosen arguments just for the refs buffer of a specific repository. The arguments are remembered using the buffer-local value of a variable, and therefore this only works as long as the buffer is not killed (so check the value of `magit-bury-buffer-function`. Whether that value is used, further depends on the value of `magit-prefix-use-buffer-arguments`. You probably want to set that to `always`.
