### ISSUE TITLE
In a dired buffer, the magit-dispatch pop-up run "git blame" intead of checking out a branch

### ISSUE THREAD

**Issue by FabienRCT** [magit/magit#5185]
When in a dired buffer, within the magit-dispatch transient pop-up buffer, the Branch (b) -> branch/revision (b) command try to run "git blame" instead of checking out a branch, from a file buffer it works fine.

Magit 3.3.0, Git 2.43.5, Emacs 29.3, gnu/linux

Debugger entered--Lisp error: (error "Blaming failed due to unexpected output: ")
  transient--exit-and-debug(error (error "Blaming failed due to unexpected output: "))
  error("Blaming failed due to unexpected output: %s" "")
  magit-blame--parse-chunk(addition)
  magit-current-blame-chunk(addition t)
  magit-branch-or-commit-at-point()
  magit-read-other-branch-or-commit("Checkout")
  byte-code("\300\301!\302 D\207" [magit-read-other-branch-or-commit "Checkout" magit-branch-arguments] 2)
  advice-eval-interactive-spec((byte-code "\300\301!\302 D\207" [magit-read-other-branch-or-commit "Checkout" magit-branch-arguments] 2))
  #f(compiled-function (spec) #<bytecode 0x7398e96e6ca09b6>)((byte-code "\300\301!\302 D\207" [magit-read-other-branch-or-commit "Checkout" magit-branch-arguments] 2))
  funcall(#f(compiled-function (spec) #<bytecode 0x7398e96e6ca09b6>) (byte-code "\300\301!\302 D\207" [magit-read-other-branch-or-commit "Checkout" magit-branch-arguments] 2))
  command-execute(magit-checkout)

**Comment by tarsius** [comment]
> Magit 3.3.0

Please update to the development version or wait a few days (most likely less than a week) until I release 4.4.0.

**Comment by FabienRCT** [comment]
Thanks for the answer
