### ISSUE TITLE
Character-wise diff highlights '+'/'-'

### ISSUE THREAD

**Issue by edmz** [magit/magit#5198]
I'm running version `e777822`, which is what I think `doom-emacs` points to.

I don't know if this is a bug or expected behaviour, but the plus and minus symbols get highlighted when highlighting diffs character-wise.

I've observed this behaviour for some time now. I just updated to said version, restarted emacs and the behaviour is still there.

![CleanShot 2024-08-12 at 10 35 20@2x](https://github.com/user-attachments/assets/23896064-03f2-4baf-9ba8-d37a9cb9a7df)

**Comment by edmz** [comment]
Fair point. Just wanted to know I didn't have a borked setup. Thanks for your work!

**Comment by tarsius** [comment]
You're welcome!

(You should have asked at https://github.com/magit/magit/discussions/categories/announcements though.)
