### ISSUE TITLE
transient--... already defined as something else than a generic function

### ISSUE THREAD

**Issue by Shirumipi** [magit/magit#5199]
Hello,

Just install Magit for the first time but encountered an error:
    
(1) What I want to do : successfully compile Magit and use it
(2) What I have encountered: error while compiling: 
Compiling file /home/[USERDIR]/.emacs.d/elpa/magit-20240811.1419/magit-commit.el at Wed Aug 14 18:27:43 2024
magit-commit.el:31:2: Error: transient--init-suffix-key is already defined as something else than a generic function
(3) What did I do to reproduce the error : I deleted the source files, rebooted my PC and tried to compile Magit again but same issue. I also comment every except Magit in my init.el file and tried compiling it but same issue.

OS: Gentoo Linux
Kernel: 6.6.38-gentoo
There is a package in Portage (app-emacs/magit) but did not install it.

**Comment by tarsius** [comment]
Please see #5180. The solution more or less is "re-compile *cleanly*".

**Comment by Shirumipi** [comment]
Thanks for the details. It works now.

**Comment by tarsius** [comment]
(Somehow) fixed in 0e35673ef5cfb4ae9ec8047a34d652b2f9986db6.
