### ISSUE TITLE
ERROR: Couldn't collect commit list because: fatal: bad object cf94190410ef163fd102cdbcb67f28599d31eabc

### ISSUE THREAD

**Issue by Juul-Mc-Goa** [magit/magit#5204]
Updating magit with `doom sync` fails with a git error.
[Here](https://github.com/magit/magit/commit/cf94190410ef163fd102cdbcb67f28599d31eabc) is the problematic commit.

I tried uninstalling magit, restarting emacs and reinstalling, but the problem persists.

Magit version (after applying workaround below): `Magit 55656a31, Transient 0.7.4, Git 2.45.2, Emacs 29.4, gnu/linux`

## Expected behavoir
Magit builds succesfully.

## Observed Behavior
```shell
 $ doom sync                                                                                                                                                    
> Synchronizing "default" profile...
  > Regenerating envvars file
    ✓ Generated ~/.config/emacs/.local/env
  > Ensuring packages are installed and built...
    - No packages need attention
  > Updating pinned packages...
    > (50/267) Re-cloning magit...
      > Cloning magit (for magit-section)...
    ✓ (50/267) magit: 55656a3 -> cf94190 [1 commit(s)] (w/ 5 dependents)
        ERROR: Couldn't collect commit list because: fatal: bad object cf94190410ef163fd102cdbcb67f28599d31eabc
```

## Workaround
Overwrite magit recipe to force using the `main` branch instead of the `melpa` one. 
```elisp
(package! magit
  :recipe (:host github :repo "magit/magit" :branch "main"))
```

**Note**
Trying to view the commit [here](https://github.com/magit/magit/commit/cf94190410ef163fd102cdbcb67f28599d31eabc) shows a "This commit does not belong to any branch on this repository" warning.

**Comment by tarsius** [comment]
Please reopen this issue in the Doom issue tracker, mention me (so that I get notified), and also mention that I will later provide more information (so others, don't start replying until I have provided the necessary context).
