### ISSUE TITLE
`magit-commit` says "nothing staged" when git submodule changes are the only staged changes

### ISSUE THREAD

**Issue by dhull** [magit/magit#5212]
When attempting to create a commit where the only changes are updates to git submodule, `magit-commit` gives the error "user-error: Nothing staged (or unstaged)". This has been broken for a couple of weeks now; before that I was able to create a commit where the only change was an update to a submodule.

Magit version:
Magit 20240822.1737 [>= 4.0.0], Transient 0.7.4, Git 2.46.0, Emacs 29.1, darwin

(I tried running `emacs -Q --debug-init --eval '(setq debug-on-error t)' -L ../dash-20240510.1327 -L ../git-commit-20240811.1419 -L ../transient-20240821.158 -L ../with-editor-20240822.2051 -L . -l magit` but it failed with the error `Lisp error: (file-missing "Cannot open load file" "No such file or directory" "compat")`. I did run the "magit-emacs-Q-command" and it failed with same "user-error: Nothing staged (or unstaged)" error.)

**Comment by dhull** [comment]
I just upgraded to magit-20240830.1753 and it has the same error.

**Comment by tarsius** [comment]
I cannot reproduce that and the involved functions were not recently modified.

The check is performed in `magit-commit-assert`; you might want to insert debug statements there. `(magit-anything-staged-p)` is supposed to return t preventing the path to the mentioned error being taken. Check what it returns for you. Without any arguments, it runs `git diff --quiet --cached --`, which is expected to exit with 1 in this case. Try that in a shell.

**Comment by dhull** [comment]
Thanks so much for your help. It seems like there is a bug in the git diff command involving the `--submodule=log` option (which I have configured in my `~/.gitconfig` file.

I have git 2.46.0 installed via homebrew on my Mac.
```
% brew info git
==> git: stable 2.46.0 (bottled), HEAD
Distributed revision control system
https://git-scm.com
Installed
/usr/local/Cellar/git/2.46.0 (1,678 files, 51.3MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-07-30 at 07:57:59
...
```

I ran the `git diff` command you suggested above, replacing `--quiet` with `--exit-code` so I can see git's output.

First is from the system git, which produces the correct exit codes.
```
% /usr/bin/git --version
git version 2.39.3 (Apple Git-146)

% /usr/bin/git diff --exit-code --cached --submodule=short --; echo $?
diff --git a/fbt-modules/fbt-type b/fbt-modules/fbt-type
index 7e5bc70e..61ede884 160000
--- a/fbt-modules/fbt-type
+++ b/fbt-modules/fbt-type
@@ -1 +1 @@
-Subproject commit 7e5bc70ea084ecb39172159988072645c16478b0
+Subproject commit 61ede884d055fcca68849b7f05c2a75b10e8d290
1
# ^^^ CORRECT

% /usr/bin/git diff --exit-code --cached --submodule=log --; echo $?
Submodule fbt-modules/fbt-type 7e5bc70e..61ede884:
  > PurchaseRedemptionInfo: Add reward type for custom rewards.
  > PurchaseRecord: Add rewardIdsRedeemed attribute.
1
# ^^^ CORRECT
```

Second is from the brew-installed git, which produces the incorrect exit code with `--submodule=log`.
```
% /usr/local/bin/git --version
git version 2.46.0

% /usr/local/bin/git diff --exit-code --cached --submodule=short --; echo $?
diff --git a/fbt-modules/fbt-type b/fbt-modules/fbt-type
index 7e5bc70e..61ede884 160000
--- a/fbt-modules/fbt-type
+++ b/fbt-modules/fbt-type
@@ -1 +1 @@
-Subproject commit 7e5bc70ea084ecb39172159988072645c16478b0
+Subproject commit 61ede884d055fcca68849b7f05c2a75b10e8d290
1
# ^^^ CORRECT

% /usr/local/bin/git diff --exit-code --cached --submodule=log --; echo $?
Submodule fbt-modules/fbt-type 7e5bc70e..61ede884:
  > PurchaseRedemptionInfo: Add reward type for custom rewards.
  > PurchaseRecord: Add rewardIdsRedeemed attribute.
0
# ^^^ WRONG; SHOULD BE 1
```

I will report a bug to the git project, but a workaround seems to explicitly specify `--submodule=short` on the git diff command line.

**Comment by tarsius** [comment]
> I will report a bug to the git project,

Please post a link to that report. Thanks!

**Comment by dhull** [comment]
> Please post a link to that report. Thanks!

I reported the bug by sending it to the git mailing list. (That appears to be the way that the git project handles bug reports.)

My original email is [here](https://marc.info/?t=172537434500009&r=1&w=2). There are currently two patches in progress [here](https://marc.info/?t=172577918500001&r=1&w=2) and [here](https://marc.info/?t=172577936900001&r=1&w=2).
