### ISSUE TITLE
Cannot open load file: No such file or directory, git-commit

### ISSUE THREAD

**Issue by gs-101** [magit/magit#5217]
### Behavior
1. Be able to use Magit and Forge commands, sutch as `magit`, `magit-status`...
2. `use-package` reports that forge can't find `git-commit`, rendering magit unusable.
3. Install magit and forge from MELPA with `use-package`.
### Backtrace
    (toggle-debug-on-error)

<details>

```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "git-commit")
  require(git-commit)
  byte-code("\301\302!\210\301\303!\210\301\304!\210\301\305!\210\301\306!\210\307\310\311\312\313\314\315\316\315\317&\11\210\320\321\322\323\324DD\325\315\310\326\327&\7\210\320\330\322\323\331DD\332\333\334\315\310\326\327&\11\210\320\335\322\323\336DD\337\333\340\315\310\326\341&\11\210\320\342\322\323\343DD\344\333\345\315\310\326\346&\11\210\320\347\322\323\350DD\351\333\352\353\354\315\310\326\327\355\356&\15\210\320\357\322\323\360DD\361\333\362\315\310\326\346&\11\210\320\363\322\323\364DD\365\315\310\366\367\326\370&\11\210\320\371\322\323\372DD\373\333\374\353\375\315\310\366\376\326\346&\15\210\377\363\201@\0\201A\0#\210\320\201B\0\322\323\201C\0DD\201D\0\333\201E\0\315\310\326\201F\0&\11\210\320\201G\0\322\323\201H\0DD\201I\0\315\310\366\201J\0\326\201K\0&\11\210\320\201L\0\322\323\201M\0DD\201N\0\333\201O\0\315\310\366\201P\0\326\201Q\0&\13\210\320\201R\0\322\323\201S\0DD\201T\0\315\310\366\376\326\346&\11\210\320\201U\0\322\323\201V\0DD\201W\0\315\310\326\201X\0\201Y\0\201Z\0\201[\0\201\\\0\201]\0\201^\0\201_\0\201`\0\10\257\5\201a\0BBBED&\7\210\320\201b\0\322\323\201c\0DD\201d\0\333\201e\0\315\310\326\346&\11\210\320\201f\0\322\323\201g\0DD\201h\0\333\201i\0\315\310\326\346&\11\210\320\201j\0\322\323\201k\0DD\201l\0\333\201m\0\315\310\326\201n\0&\11\207" [tab-width require magit-core git-commit diff-mode image smerge-mode custom-declare-group magit-diff nil "Inspect and manipulate Git diffs." :link (info-link "(magit)Diffing") :group magit-commands magit-modes custom-declare-variable magit-diff-mode-hook funcall function #f(compiled-function () #<bytecode 0x18c000ae69414>) "Hook run after entering Magit-Diff mode." :type hook magit-diff-sections-hook #f(compiled-function () #<bytecode 0x18c8911b6b214>) "Hook run to insert sections into a `magit-diff-mode' buffer." :package-version (magit . "2.3.0") magit-diff-expansion-threshold #f(compiled-function () #<bytecode 0x18c000ae6df14>) "After how many seconds not to expand anymore diffs.\n\nExcept in status buffers, diffs usually start out fully expanded.\nBecause that can take a long time, all diffs that haven't been\nfontified during a refresh before the threshold defined here are\ninstead displayed with their bodies collapsed.\n\nNote that this can cause sections that were previously expanded\nto be collapsed.  So you should not pick a very low value here.\n\nThe hook function `magit-diff-expansion-threshold' has to be a\nmember of `magit-section-set-visibility-hook' for this option\nto have any effect." (magit . "2.9.0") float magit-diff-highlight-hunk-body #f(compiled-function () #<bytecode 0x18c000ae69b14>) "Whether to highlight bodies of selected hunk sections.\nThis only has an effect if `magit-diff-highlight' is a\nmember of `magit-section-highlight-hook', which see." (magit . "2.1.0") boolean magit-diff-highlight-hunk-region-functions #f(compiled-function () #<bytecode 0x18c891c15f714>) "The functions used to highlight the hunk-internal region.\n\n`magit-diff-highlight-hunk-region-dim-outside' overlays the outside\nof the hunk internal selection with a face that causes the added and\nremoved lines to have the same background color as context lines.\nThis function should not be removed from the value of this option.\n\n`magit-diff-highlight-hunk-region-using-overlays' and\n`magit-diff-highlight-hunk-region-using-underline' emphasize the\nregion by placing delimiting horizontal lines before and after it.\nThe underline variant was implemented because Eli said that is\nhow we should do it.  However the overlay variant actually works\nbetter.  Also see https://github.com/magit/magit/issues/2758.\n\nInstead of, or in addition to, using delimiting horizontal lines,\nto emphasize the boundaries, you may wish to emphasize the text\nitself, using `magit-diff-highlight-hunk-region-using-face'.\n\nIn terminal frames it's not possible to draw lines as the overlay\nand underline variants normally do, so there they fall back to\ncalling the face function instead." (magit . "2.9.0") :set-after (magit-diff-show-lines-boundaries) :options (magit-diff-highlight-hunk-region-dim-outside magit-diff-highlight-hunk-region-using-underline magit-diff-highlight-hunk-region-using-overlays magit-diff-highlight-hunk-region-using-face) magit-diff-unmarked-lines-keep-foreground #f(compiled-function () #<bytecode 0x18c000ae69b14>) "Whether `magit-diff-highlight-hunk-region-dim-outside' preserves foreground.\nWhen this is set to nil, then that function only adjusts the\nforeground color but added and removed lines outside the region\nkeep their distinct foreground colors." ...] 17)
  require(magit-diff)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\210\300\306!\210\300\307!\210\300\310!\210\300\311\312\313#\210\300\314!\210\315\316\317\320\321DD\322\323\324\325\326\327\330&\11\207" [require magit-core magit-diff magit-log magit-wip magit-apply magit-repos git-commit format-spec package nil t with-editor custom-declare-variable magit-openpgp-default-signing-key funcall function #f(compiled-function () #<bytecode -0x455813ccd50498e>) ("/home/gabriel/.emacs.d/elpa/magit-20240831.2255/magit.elc" . 87) :package-version (magit . "4.0.0") :group magit-commands :type string] 10)
  require(magit)
  load-with-code-conversion("/home/gabriel/.emacs.d/elpa/forge-20240831.2307/forge.el" "/home/gabriel/.emacs.d/elpa/forge-20240831.2307/forge.el" t t)
  require(forge nil t)
  (not (require 'forge nil t))
  (if (not (require 'forge nil t)) (display-warning 'use-package (format "Cannot load %s" 'forge) :error))
  (condition-case err (if (not (require 'forge nil t)) (display-warning 'use-package (format "Cannot load %s" 'forge) :error)) ((debug error) (funcall use-package--warning8 :catch err)))
  load-with-code-conversion("/home/gabriel/.emacs.d/modules/gs-dev.el" "/home/gabriel/.emacs.d/modules/gs-dev.el" nil t)
  require(gs-dev)
  load-with-code-conversion("/home/gabriel/.emacs.d/init.el" "/home/gabriel/.emacs.d/init.el" t t)
  load("/home/gabriel/.emacs.d/init" noerror nomessage)
  #f(compiled-function () #<bytecode 0x866644c30b6cf90>)()
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x1cf958f9fde8689b>) #f(compiled-function () #<bytecode 0x731968ef8c4ca9b>) t)
  command-line()
  normal-top-level()
```

</details>

    M-x magit-version RET

<details>

```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "git-commit")
  require(git-commit)
  byte-code("\301\302!\210\301\303!\210\301\304!\210\301\305!\210\301\306!\210\307\310\311\312\313\314\315\316\315\317&\11\210\320\321\322\323\324DD\325\315\310\326\327&\7\210\320\330\322\323\331DD\332\333\334\315\310\326\327&\11\210\320\335\322\323\336DD\337\333\340\315\310\326\341&\11\210\320\342\322\323\343DD\344\333\345\315\310\326\346&\11\210\320\347\322\323\350DD\351\333\352\353\354\315\310\326\327\355\356&\15\210\320\357\322\323\360DD\361\333\362\315\310\326\346&\11\210\320\363\322\323\364DD\365\315\310\366\367\326\370&\11\210\320\371\322\323\372DD\373\333\374\353\375\315\310\366\376\326\346&\15\210\377\363\201@\0\201A\0#\210\320\201B\0\322\323\201C\0DD\201D\0\333\201E\0\315\310\326\201F\0&\11\210\320\201G\0\322\323\201H\0DD\201I\0\315\310\366\201J\0\326\201K\0&\11\210\320\201L\0\322\323\201M\0DD\201N\0\333\201O\0\315\310\366\201P\0\326\201Q\0&\13\210\320\201R\0\322\323\201S\0DD\201T\0\315\310\366\376\326\346&\11\210\320\201U\0\322\323\201V\0DD\201W\0\315\310\326\201X\0\201Y\0\201Z\0\201[\0\201\\\0\201]\0\201^\0\201_\0\201`\0\10\257\5\201a\0BBBED&\7\210\320\201b\0\322\323\201c\0DD\201d\0\333\201e\0\315\310\326\346&\11\210\320\201f\0\322\323\201g\0DD\201h\0\333\201i\0\315\310\326\346&\11\210\320\201j\0\322\323\201k\0DD\201l\0\333\201m\0\315\310\326\201n\0&\11\207" [tab-width require magit-core git-commit diff-mode image smerge-mode custom-declare-group magit-diff nil "Inspect and manipulate Git diffs." :link (info-link "(magit)Diffing") :group magit-commands magit-modes custom-declare-variable magit-diff-mode-hook funcall function #f(compiled-function () #<bytecode 0x18c000ae69414>) "Hook run after entering Magit-Diff mode." :type hook magit-diff-sections-hook #f(compiled-function () #<bytecode 0x18c8911b6b214>) "Hook run to insert sections into a `magit-diff-mode' buffer." :package-version (magit . "2.3.0") magit-diff-expansion-threshold #f(compiled-function () #<bytecode 0x18c000ae6df14>) "After how many seconds not to expand anymore diffs.\n\nExcept in status buffers, diffs usually start out fully expanded.\nBecause that can take a long time, all diffs that haven't been\nfontified during a refresh before the threshold defined here are\ninstead displayed with their bodies collapsed.\n\nNote that this can cause sections that were previously expanded\nto be collapsed.  So you should not pick a very low value here.\n\nThe hook function `magit-diff-expansion-threshold' has to be a\nmember of `magit-section-set-visibility-hook' for this option\nto have any effect." (magit . "2.9.0") float magit-diff-highlight-hunk-body #f(compiled-function () #<bytecode 0x18c000ae69b14>) "Whether to highlight bodies of selected hunk sections.\nThis only has an effect if `magit-diff-highlight' is a\nmember of `magit-section-highlight-hook', which see." (magit . "2.1.0") boolean magit-diff-highlight-hunk-region-functions #f(compiled-function () #<bytecode 0x18c891c15f714>) "The functions used to highlight the hunk-internal region.\n\n`magit-diff-highlight-hunk-region-dim-outside' overlays the outside\nof the hunk internal selection with a face that causes the added and\nremoved lines to have the same background color as context lines.\nThis function should not be removed from the value of this option.\n\n`magit-diff-highlight-hunk-region-using-overlays' and\n`magit-diff-highlight-hunk-region-using-underline' emphasize the\nregion by placing delimiting horizontal lines before and after it.\nThe underline variant was implemented because Eli said that is\nhow we should do it.  However the overlay variant actually works\nbetter.  Also see https://github.com/magit/magit/issues/2758.\n\nInstead of, or in addition to, using delimiting horizontal lines,\nto emphasize the boundaries, you may wish to emphasize the text\nitself, using `magit-diff-highlight-hunk-region-using-face'.\n\nIn terminal frames it's not possible to draw lines as the overlay\nand underline variants normally do, so there they fall back to\ncalling the face function instead." (magit . "2.9.0") :set-after (magit-diff-show-lines-boundaries) :options (magit-diff-highlight-hunk-region-dim-outside magit-diff-highlight-hunk-region-using-underline magit-diff-highlight-hunk-region-using-overlays magit-diff-highlight-hunk-region-using-face) magit-diff-unmarked-lines-keep-foreground #f(compiled-function () #<bytecode 0x18c000ae69b14>) "Whether `magit-diff-highlight-hunk-region-dim-outside' preserves foreground.\nWhen this is set to nil, then that function only adjusts the\nforeground color but added and removed lines outside the region\nkeep their distinct foreground colors." ...] 17)
  require(magit-diff)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\210\300\306!\210\300\307!\210\300\310!\210\300\311\312\313#\210\300\314!\210\315\316\317\320\321DD\322\323\324\325\326\327\330&\11\207" [require magit-core magit-diff magit-log magit-wip magit-apply magit-repos git-commit format-spec package nil t with-editor custom-declare-variable magit-openpgp-default-signing-key funcall function #f(compiled-function () #<bytecode -0x455813ccd50498e>) ("/home/gabriel/.emacs.d/elpa/magit-20240831.2255/magit.elc" . 87) :package-version (magit . "4.0.0") :group magit-commands :type string] 10)
  command-execute(magit-version record)
  execute-extended-command(nil "magit-version" "magit-version")
  funcall-interactively(execute-extended-command nil "magit-version" "magit-version")
  command-execute(execute-extended-command)
```

</details>

This happens even with only my development and package modules loaded ([Org Header](https://github.com/gs-101/.emacs.d/blob/main/emacs.org#development-1) and [Elisp File](https://github.com/gs-101/.emacs.d/blob/main/modules/gs-dev.el) for reference). I disabled treesit in my test.
Checking with `list-packages`, the magit version is "20240831.2255", and forge is "20240831.2307".
My Emacs version is "GNU Emacs 31.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.0) of 2024-08-05".

**Comment by gs-101** [comment]
Thank you, reinstalling magit solved the issue.

**Comment by allentiak** [comment]
@tarsius 
Thanks for the previous answer.
I have a related question.

You mentioned adopting `git-commit` as part of `magit`. That's awesome!

Are you planning to do the same with either `git-gutter+`/`git-gutter-fringe+` or `git-gutter`/`git-gutter-fringe`? Or is their functionality already part of `magit`'s?

I'm asking this beacuse of https://github.com/syl20bnr/spacemacs/issues/16555.

**Comment by tarsius** [comment]
@allentiak Thanks for the reminder that I still had to open https://github.com/nonsequitur/git-gutter-plus/issues/48. :grin:

I don't intend to integrate any of these packages into Magit. The situation isn't comparable to that of `git-commit.el`. That has been part of the Magit repository for nearly a decade and was maintained by me during all that time, while the mentioned packages are completely separate projects. The `+` variants even stopped being maintained nearly a decade ago, and thus shouldn't be used anymore.

A better alternative than all of these packages is the maintained `diff-hl` package. (Which also is a separate project and won't be merged into Magit.)

You installed `git-gutter` yourself, right? As far as I can tell that is not included in Spacemacs. Given that it hasn't been touched in a decade and appears to be broken, regardless of the `git-commit` complication, it would be very surprising if Spacemacs (still) used it.

**Comment by allentiak** [comment]
> @allentiak Thanks for the reminder that I still had to open [nonsequitur/git-gutter-plus#48](https://github.com/nonsequitur/git-gutter-plus/issues/48). 😁

@tarsius
You're welcome 😁

> A better alternative to all of these packages is the maintained `diff-hl` package -- that is what I use. (That is also a separate project and also won't be merged into Magit.)

Thanks for mentioning this!
I didn't know about this package.


> You installed `git-gutter` yourself, right? As far as I can tell that is not included in
> Spacemacs. Given that it hasn't been touched in a decade and appears to be broken, regardless > of the `git-commit` complication, it would be very surprising if Spacemacs (still) used it.

In fact, `git-gutter` is actually used in Spacemacs (albeit transitivilly, I think).

Thanks again for mentioning `diff-hl`. It seems that the actual problem is that many of us didn't know about possible alternatives to `git-gutter*`, ha ha.
I have already suggested the Spacemacs maintainers to use `diff-hl` instead.

**Comment by felker** [comment]
Is it fair to say that this doc page is outdated, then? https://magit.vc/manual/magit/git_002dcommit_002dmode-isn_0027t-used-when-committing-from-the-command_002dline.html


Related #4672 (I am trying to update  my `use-package` hooks but haven't fiddled around with my `init.el` probably since that issue!)

```lisp
...
(use-package git-commit
  :ensure t
  :hook ((git-commit-mode . (lambda () (setq fill-column 72)))
         )
  :demand
  :init
  (add-hook 'git-commit-setup-hook #'git-commit-turn-on-flyspell)
)
```

After reinstalling magit and removing `:ensure t`, I think my setup is working again, but I could have sworn that running `git commit`  from the command line (with `EDITOR=emacsclient -t --alternate-editor=`) opened up my emacs with a `git-commit` minor mode buffer and `magit-diff` major mode buffer in the window underneath, but I see only the latter (unless I start `magit` manually)

**Comment by tarsius** [comment]
> Is it fair to say that this doc page is outdated, then? https://magit.vc/manual/magit/git_002dcommit_002dmode-isn_0027t-used-when-committing-from-the-command_002dline.html

It indeed appears that `--alternate-editor=` without a value should work.

I cannot confirm this fully because I have run into similar issues as you have, but I believe these are specific to my setup and go very deep.

(My distribution (Guix) packages Emacs in a way that messes with manually installed Emacs, and I am doing that anyway. I counter that in `.bashrc`, but when `emacsclient` starts `emacs`, does kludges do not apply. It gets more complicated, and despite it being an issue that affects me personally, I don't currently have the time to investigate it.)

In your case the problem might also has something to do with the environment in which emacs is started being different. Use debug statements to inspect relevant things such as `load-path`.

> ```elisp
> (use-package git-commit
>   :ensure t
>   :hook ((git-commit-mode . (lambda () (setq fill-column 72)))
>          )
>   :demand
>   :init
>   (add-hook 'git-commit-setup-hook #'git-commit-turn-on-flyspell)
> )
> ```

`:demand` takes a value, usually `t`.

> After reinstalling magit and removing `:ensure t`, I think my setup is working again, but I could have sworn that running `git commit` from the command line (with `EDITOR=emacsclient -t --alternate-editor=`) opened up my emacs with a `git-commit` minor mode buffer and `magit-diff` major mode buffer in the window underneath, but I see only the latter (unless I start `magit` manually)

Well that sounds like the issue might be simpler in your case.  The `COMMIT_EDITMSG` buffer isn't being displayed, that we know. But does it also not exist? If that is the case, fiddling with settings such as `inhibit-startup-screen` might help.

----

I intend to get this working on my own machine eventually. Once I know more, I'll update the documentation.

**Comment by felker** [comment]
thanks for the reply--- I now realize I made a mistake in my description (that is what I get for writing it at 11pm). So sorry for the confusion:

> After reinstalling magit and removing :ensure t, I think my setup is working again, but I could have sworn that running git commit from the command line (with EDITOR=emacsclient -t --alternate-editor=) opened up my emacs with a git-commit minor mode buffer (`COMMIT_EDITMSG`) and magit-diff major mode buffer in the window underneath, but I see **only the former** (unless I start magit manually)

See bolded phrase; i.e. a coldstart of `emacsclient` after a `killemacs`, shows that `git-commit` is eagerly loaded, as I expected
```
Loading package git-commit...done (0.204s)
```

But `git commit` from the command line results in:
<img width="802" alt="Image" src="https://github.com/user-attachments/assets/f7a2a833-ab75-4633-9f46-1980756a0f29" />

In the past with a nearly identical `init.el`, the first `git commit` from the command line would start `magit`, and I would get a `magit-diff` buffer below. 

I recently updated to Emacs 30.1 on macOS and `magit-20250312.1432`, removing `git-commit` as discussed above.


------------
I still have an old version of Emacs 27.1 running headless on a remote Linux machine with `magit-20230107.2134` and `git-commit-20230103.2224` and there the same `init.el`, Git setup, etc. I see the same eager loading of `git-commit` in `*Messages*` after cold starting Emacs after a `killemacs`, as above. 

But a `git commit` from the command line results in the old (desired) behavior, as I remembered:

<img width="802" alt="Image" src="https://github.com/user-attachments/assets/6efc0a60-71bb-4015-a5ab-98b2adabe214" />

Keeping Emacs 27.1 but updating magit to the latest and removing the standalone `git-commit` package reproduces the change that I am seeing on macOS. So I suppose I need to find a change for my `init.el` to start Magit when committing from the command line.

**Comment by felker** [comment]
for now, I will add `:demand` to my `magit` use-package configuration (unless there is a more elegant / narrowly-tailored way to start magit automatically when running `git commit`?), but it would be nice to understand how the magit update / change to the packaging of `git-commit` caused this difference in behavior, and maybe it could help improve that doc page. And it would be nice to avoid the unnecessary penalty to my `emacsclient` startup time for when I am not doing `git` stuff on that remote Linux machine

**Comment by felker** [comment]
```lisp
(use-package magit
  :ensure t
  :bind
  ("C-x g" . magit-status)
  ("C-x C-g" . magit-status)
  :init
  (defun my/magit-commit-message ()
  (when (string-match "COMMIT_EDITMSG" (buffer-file-name))
    (require 'magit)
    ))
  (add-hook 'server-visit-hook 'my/magit-commit-message)
  )
```

this is the best I could come up with, and I think it works, but surely there must be a more elegant way...
