### ISSUE TITLE
Unable to revert to (unstaged) worktree version of file after `magit-diff-visit-file` on diff in magit status buffer

### ISSUE THREAD

**Issue by bramadams** [magit/magit#5218]
I've recently stumbled upon `magit-diff-visit-file`, which is bound to RET in a magit diff view such as shown in the status buffer. When on a removed line, it jumps back to the previous blob containing that line, which is handy, yet it also seems to revert the worktree file to that old blob, even if I have unstaged/uncommitted changes to that file.

This happened a couple of times (Magit 4d05419, Transient 0.7.5, Forge 0.4.2, Git 2.39.1, Emacs 29.3, darwin), and I could not find any way to revert back to my (uncommitted) worktree file except for copying back the ~ backup file.

There is a `magit-diff-visit-worktree-file` command, but that one requires the magit status buffer to still show the uncommitted worktree changes, which is no longer the case if closing the status buffer after invoking `magit-diff-visit-file`.

The discussion on https://www.reddit.com/r/emacs/comments/1f7nz9e/reverting_to_worktree_version_after/ suggested that this might be a bug, hence this report. If not a bug, is there an option to prompt for confirmation before `magit-diff-visit-file` is about to execute?

**Comment by tarsius** [comment]
Magit of course doesn't do that intentionally, and I also doubt that it could do so by accident. In any case, I cannot reproduce this.

I suspect that some other package or your own modifications are causing this. So you should try to reproduce it with as much of your configuration removed. Ideally start with `emacs -Q`, see https://magit.vc/manual/magit/Debugging-Tools.html. Then add your configuration back, step by step, to narrow it down to a specific cause.

But first, check the process buffer (`$`), is there a git invocation logged there, that does the resetting. If not, that is a strong indication, that Magit has nothing to do it. The opposite isn't the case, if you see a git invocation there that does the resetting, that does not mean that Magit called that, it could also have been another package, which uses functions from Magit to run Git.

**Comment by bramadams** [comment]
Thanks for the quick reply.

I think I narrowed it down to the use of https://github.com/cybniv/poetry.el, in particular its global minor mode `poetry-tracking-mode`.

Somehow, when doing `magit-diff-visit-file` on a removed line, the blob's buffer shows up, followed by messages "Compilation finished" and "Poetry finished", after which the worktree file buffer is reverted (`magit-revert-rev-file-buffer` runs on the worktree file buffer).

Will continue debugging this later today.
