### ISSUE TITLE
magit hangs when staging a hunk with `tramp-direct-async-process` enabled

### ISSUE THREAD

**Issue by CeleritasCelery** [magit/magit#5220]
`magit-version` : Magit v4.1.0-2-g4d054196, Transient 0.7.4, Git 2.37.1, Emacs 29.4, darwin
`tramp-version` : 2.7.1.1

This is similar to #3624, but is **not** the same issue. That issue was related to an older version of tramp and this is with `2.7.1`. However it only manifests when you have [tramp-direct-async-process](https://www.gnu.org/software/tramp/#Improving-performance-of-asynchronous-remote-processes-1) enabled.

starting with `magit-emacs-Q-command` and tramp `2.7.1`, add the following config:

```lisp
(connection-local-set-profile-variables
 'remote-direct-async-process
 '((tramp-direct-async-process . t)))

;; Set "remotehost" to match your host.
(connection-local-set-profiles
 '(:application tramp :machine "remotehost")
 'remote-direct-async-process)
```
 Then run `magit-status` on a remote repo and try to stage a hunk. Magit will hang, and I got the following backtrace using `debug-on-quit`:

```lisp
Debugger entered--Lisp error: (quit)
  magit-run-git-with-input("apply" ("--cached") "-p0" nil "--ignore-space-change" "-")
  magit-apply-patch(#<magit-file-section "README.md" [file unstaged status] 695-[716-]1906> ("--cached") "diff --git README.md README.md\nindex 10fde69a01..0...")
  magit-apply-hunk(#<magit-hunk-section (nil (20 7) (20 7)) [hunk file unstaged status] 1178-[1277-]1672> "--cached")
  magit-stage(nil)
  funcall-interactively(magit-stage nil)
  command-execute(magit-stage)
```
The backtrace doesn't seem particularly useful since all it tells us is that magit is hanging while running the command.

**Comment by tarsius** [comment]
> However it only manifests when you have [tramp-direct-async-process](https://www.gnu.org/software/tramp/#Improving-performance-of-asynchronous-remote-processes-1) enabled.

That feature improves performance, but as described, it breaks quite a few things. It looks like "staging individual hunks using magit", has to be added to that list. To generalize that a bit, the feature that seems to break is "sending text to the remote process on its stdin". You could ask Tramp's maintainer, if this indeed is something that is inherently impossible with this optimization.

**Comment by CeleritasCelery** [comment]
I don't think it is related to sending text on stdin. That is not listed as a limitation in the tramp manual, so I tried the following code (trying to mirror the functions magit uses). This works fine with direct async processes.

```lisp
(defun process-with-stdin ()
  (let* ((process-name "test-process")
         (buffer-name "*test-process-buffer*")
         (process (start-file-process process-name buffer-name "cat")))
    (process-send-string process "Hello from stdin!\n")
    (process-send-eof process)
    (while (and process
                (eq (process-status process) 'run))
      (sleep-for 0.005))
    (with-current-buffer buffer-name
      (buffer-string))))
```
The reason I am interested in getting this working is because async processes are really slow over tramp by default, and magit uses `magit-run-git-async` all over the place. Using direct async processes drops the time it takes to call `magit-run-git-async` from 3 seconds to 0.5 seconds on my machine. That makes the whole interface much snappier, but we have this issue with staging hunks.

**Comment by CeleritasCelery** [comment]
I tracked down the issue to `process-connection-type` being `nil` (pipe). Changing `magit-tramp-pipe-stty-settings` to `pty` fixed the issue. I don't know enough about the history of this setting to determine if there is way to configure that automatically for users. Maybe using `tramp-direct-async-process-p`? Currently by default for remote files it will do a pipe for connections with input and a pty for connections without, which is why most operations work but ones that use `magit-run-git-with-input` don't.

**Comment by tarsius** [comment]
I should have mentioned that variable -- that's what these "can't stage hunk" issues come down to.

> I don't know enough about the history of this setting to determine if there is way to configure that automatically for users.

It's a tradeoff; as you found out a pty has to be used when `tramp-direct-async-process` is enabled, but if a pty is used, then it doesn't work for files with DOS line endings. So I have just extended the docstring for now.

I intend to look into the matter (and the wider issue of running subprocesses) in depth eventually, but don't know when I will get to that.
