### ISSUE TITLE
`magit-auto-revert-mode` makes tramp hang and/or slow down (with suggested fix)

### ISSUE THREAD

**Issue by bramadams** [magit/magit#5222]
[This is a follow-up report for #5109]

I've continued debugging a tramp hanging issue connecting to an Oracle Solaris 11.4.59.144.2 server, where emacs 29.3, even after the fixes in #5109, would still either hang or severely slow down. I'm using the latest upstream Magit 4d05419, Transient 0.7.5, Git 2.39.4, Emacs 29.3, darwin. The issue also occurs when using emacs -Q.

Using the debugger, I noticed that the hangs/slowdowns happened when `magit-auto-revert-mode` was being called on the server via the `after-change-major-mode-hook`. This issue has been discussed before:
- https://github.com/magit/magit/discussions/4817
- https://www.reddit.com/r/emacs/comments/yw3gpx/magit_autorevert_and_tramp/

The latter reddit discussion actually suggests a fix that works, i.e., preventing `magit-turn-on-auto-revert-mode-if-desired` from being called from a buffer visiting a remote file using `:around` advice. Tramp is super-smooth with this fix.

Since such advice is a bit of a hack, I've changed `magit-turn-on-auto-revert-mode-if-desired`, also adding a configuration value to allow people to choose whether they want `magit-auto-revert-mode` to be on or off when visiting a remote file. See PR #5223.

BA

**Comment by tarsius** [comment]
I have chosen to slightly reinterpret the meaning of the existing `auto-revert-remote-files` instead of merging your pull-request, see 61c051ea1cda5fe6c9404cb5ae228088d2e254f0.

**Comment by bramadams** [comment]
Great, thanks a lot!
