### ISSUE TITLE
Problem with overlay, face inheritance and :before-string

### ISSUE THREAD

**Issue by aburlot** [magit/magit#5233]
I am reporting a bug related to [an issue](https://github.com/jdtsmith/indent-bars/issues/67) reported on the indent-bars package. The author of this package (@jdtsmith) suggests that there is an issue in some magit inheritance:

> Magit should not inherit the  `face` property of the first character on a line into its blame overlay `:before-string`, since it doesn't control what that is or will be (and `face` overrides `font-lock-face`).

Here is the original post with pictures:

> Unfortunately, `indent-bars-reset` changes nothing. The command gives me this :
> ```elisp
> #("My name          2024-09-26 15:33 commentary and cleaning
> " 0 20 (font-lock-face (magit-blame-name magit-blame-heading)) 20 21 (font-lock-face magit-blame-heading) 21 37 (font-lock-face (magit-blame-date magit-blame-heading)) 37 38 (font-lock-face magit-blame-heading) 38 61 (font-lock-face (magit-blame-summary magit-blame-heading)) 61 62 (font-lock-face magit-blame-heading))
> ```
> 
> Strangely, in Python, I have a mixed effect:
> ![indent-bars](https://github.com/user-attachments/assets/15de4a00-fe2b-4b8b-ad88-615558cf08be)
> 
> In C++, I notice that it starts to be messy when I am in a function, thus when the indent-bars start appearing:
> ![indent-bars-2](https://github.com/user-attachments/assets/cb4cd40f-36fd-4954-af61-fe4a18936b3e)
> But a few commits appear normally even inside the function. I tried the command on several lines, but they always show the same resultats as above.
> 
> I hope this helps!
> 
> _Originally posted by @aburlot in https://github.com/jdtsmith/indent-bars/issues/67#issuecomment-2380638784_

All of this is above my elisp knowledge.

I am using Magit 20240928.1355 [>= 20240928.1355], Transient 20240929.1847, Git 2.25.1, Emacs 29.4, gnu/linux.

**Comment by tarsius** [comment]
Addressed in b0e6d02e6183c53663f170d64c19f17db7d04812.
