### ISSUE TITLE
Magit doesn't work when the system locale is set to a non-English language.

### ISSUE THREAD

**Issue by umanwizard** [magit/magit#5242]
magit-version output: `Magit v4.1.1-2-g66731bda, Transient 20241008.1824, Git 2.46.0, Emacs 30.0.91, gnu/linux`

Various things don't work properly when the system is set to a non-English language. I assume this is because Magit uses regexes to parse the output of git, and can only cope with the well-known English output.

For example, the commit process just hangs forever after confirming the commit message editor. 

As a workaround, setting `LANG=""` in the git environment seems to fix things. With the following line in my `.emacs`, I am able to use Magit again.

```
(push "LANG=\"\"" magit-git-environment)
```

**Comment by tarsius** [comment]
I think most parts of Magit can deal with other languages. The notable exceptions are yes/no questions and password prompts Git/SSH/GNUPG might ask when pushing, fetching and committing.

These can be customized using various `magit-process-*-{regexps,functions}` options.

**Comment by umanwizard** [comment]
You're right, sorry, it _was_ trying to use GPG signing. I though it wasn't because I had disabled `-S`, but I also had that in my `.gitconfig`.

As an aside, maybe we need a `--no-gpg-sign` option in the commit transient to countermand `.gitconfig`.

**Comment by tarsius** [comment]
For the time being you can add that argument yourself, see https://magit.vc/manual/transient/Modifying-Existing-Transients.html.

I do plan to improve complex arguments like this in the future. (In this case there is an on variant (which optionally takes a value), an off variant, and then there's also a variable that controls the same behavior. It is possible to implement that using a single infix command, but it's not trivial to design and implement that, and I haven't done it yet.
