### ISSUE TITLE
submodule `populate` doesn't pass the `--recursive` flag

### ISSUE THREAD

**Issue by greg7mdp** [magit/magit#5256]
When using: `o -r p` for submodules, the `--recursive` option is highlighted, but *not* passed to `git submodule update --init ` even though the git command `git submodule update --init --recursive` works fine.

`Magit 20241116.1557 [>= 20241116.1557], Transient 20241115.2034, Git 2.47.0, Emacs 29.4, gnu/linux`

**Comment by kyleam** [comment]
It looks like this is covered by the feature request at https://github.com/magit/magit/discussions/5191

**Comment by greg7mdp** [comment]
Thanks for the quick fix!
