### ISSUE TITLE
git stash push can add args after --

### ISSUE THREAD

**Issue by tomdl89** [magit/magit#5260]
If I press `z P` (once P is enabled) to bring up the `git stash push` transient, I have the option of limiting to files (with `--`) and other options like keeping index (with `-k`). If I use either on their own, they work fine, but together, they bring up the error:
```
pathspec '--keep-index' did not match any file(s) known to git ...
```
because magit is supplying the args to git in the wrong order. Anything after `--` should be files to limit to, not options. To be clear, magit is constructing this command:
```
git stash push -- "path/to/my/file.foo" --keep-index
```
which is an invalid git command.
This can be confirmed by changing `args` to `(reverse args)` in the last line of the `transient-define-prefix` for `magit-stash-push`, which fixes the problem. Obvs not correct fix, but hopefully illustrative.

**Comment by tarsius** [comment]
Thanks for the report!
