### ISSUE TITLE
Error void-function magit-process-git when opening a file after magit-auto-revert-mode

### ISSUE THREAD

**Issue by pkryger** [magit/magit#5263]
After calling `magit-auto-revert-mode` I cannot `find-file`. A `void-function magit-process-git` is signalled instead.

I have stumbled upon this with a bit of a very old configuration that tried to diminish "MRev" supposedly lighted up by `magit-auto-revert-mode` (I know: even if it had been the case it was probably years ago). Once loading of `magit` has been deferred, I couldn't visit any file. Originally stumbled upon this issue using Emacs-mac 29.4 on macOS but I managed to minimise the reproduction steps, using relatively plain [Emacs in Docker container](https://github.com/Silex/docker-emacs/blob/master/images/master/debian/Dockerfile). The backtrace in both case have exactly the same top 8 frames.

1. In a new container start `emacs` (I know no `-Q`, but this I think this is important later)
2. In `*scratch*` evaluate:
```emacs-lisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(package-refresh-contents)
(package-install 'magit)
(magit-version) ;"20241130.1707"
(cl-assert (symbol-function 'magit-process-git)) ; <--- it has been bound
```
3. Exit emacs
4. Start emacs again: `emacs` (no `-Q` such that it set up `load-path` and load autoloads from installed packages)
5. In `*scratch*` evaluate:
```emacs-lisp
(cl-assert (not (symbol-function 'magit-process-git))) ; <-- it has NOT been bound
(magit-auto-revert-mode) ; alternative: (require 'magit-autorevert)
(find-file (make-temp-file "foo"))
```

The last line produces the following backtrace (with `debug-on-error`):
```
Debugger entered--Lisp error: (void-function magit-process-git)
  magit-process-git((t nil) ("rev-parse" "--show-toplevel"))
  magit-git-str("rev-parse" "--show-toplevel")
  apply(magit-git-str "rev-parse" "--show-toplevel")
  magit-rev-parse-safe("--show-toplevel")
  magit-toplevel()
  magit-turn-on-auto-revert-mode-if-desired()
  magit-auto-revert-mode-enable-in-buffer()
  run-hooks(change-major-mode-after-body-hook after-change-major-mode-hook)
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer foohDFCrP> "/tmp/foohDFCrP" nil nil "/tmp/foohDFCrP" (32991 37))
  find-file-noselect("/tmp/foohDFCrP" nil nil nil)
  find-file("/tmp/foohDFCrP")
  (progn (find-file (make-temp-file "foo")))
  eval((progn (find-file (make-temp-file "foo"))) t)
  elisp--eval-last-sexp(nil)
  #f(compiled-function () #<bytecode 0x5186490b2fc0a>)()
  handler-bind-1(#f(compiled-function () #<bytecode 0x5186490b2fc0a>) (error) eval-expression--debug)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

**Comment by tarsius** [comment]
Adding `(magit-auto-compile-mode)` to your init file no longer causes this issue. However, there is no need to do that because that mode is enabled by default. See 961b966f9a350bbe30d5ed54ad255d3b2a9a6fc5 for details.

**Comment by pkryger** [comment]
Thank you for fast reaction. Your explanation is as always complete and on a point.
