### ISSUE TITLE
defaut-directory changes to inside .git/ subdirectory in COMMIT_MSG buffer

### ISSUE THREAD

**Issue by apteryks** [magit/magit#5270]
Hello!

Please explain

    (1) what behavior you expected

When pressing c twice (`c c`) in the `magit: $project` buffer to author a commit, the current directory (`default-directory` variable in Emacs) should be set to the project top directory.

    (2) what behavior you observed

Instead, it gets set to the `.git/ subdirectory`, or a `.git/worktrees/$worktree` subdirectory.  This breaks diff-operating commands such as `C` (`magit-add-log`), and I need to do `M-x cd $correct_dir` and C-c C-d to refresh the diff on each commit, which gets annoying quickly.

    (3) and how we can reproduce the issue.

I'm using Emacs 29.4 with Magit 4.1.3.  I can reproduce this on my Guix checkout, starting Emacs wih `emacs -q`, manually loading the Magit library with `M-x load magit` then attempting to author a commit in that checkout.

Post the output of:

    M-x magit-version RET

```
Magit 4.1.3, Transient 0.8.1, Git 2.46.0, Emacs 29.4, gnu/linux
```
[...]
Alternatively, run:

    M-x magit-emacs-Q-command RET

I can reproduce the problem in such an environment; the above command returned:
```
/home/maxim/.guix-profile/bin/emacs -Q --eval \(setq\ debug-on-error\ t\) -L /gnu/store/5fz4hfsqgh2rgdz2gxpxsnf6ak2nbsnx-emacs-compat-30.0.0.0/share/emacs/site-lisp/compat-30.0.0.0/ -L /gnu/store/225hahh22k3bsxxlq479463lwsxj8fix-emacs-dash-2.19.1/share/emacs/site-lisp/dash-2.19.1/ -L /gnu/store/cxsacyan78s9p1l1fnkri5q370n30ngy-emacs-transient-0.8.1/share/emacs/site-lisp/transient-0.8.1/ -L /gnu/store/yb845lyz9d7ycidrdzc8qrkj9bhy4vyr-emacs-with-editor-3.4.3/share/emacs/site-lisp/with-editor-3.4.3/ -L /gnu/store/mn0hmr3rk52zgqh8jwml8cfyg6hjv7ia-emacs-magit-4.1.3/share/emacs/site-lisp/magit-4.1.3/ -l /gnu/store/mn0hmr3rk52zgqh8jwml8cfyg6hjv7ia-emacs-magit-4.1.3/share/emacs/site-lisp/magit-4.1.3/magit
```

Thank you!

**Comment by Apteryks** [comment]
It doesn't seem to be a regression caused by git, as I've tried reverting from git 2.46 to 2.45.2 and even 2.41.0, but all reproduce the problem.

**Comment by Apteryks** [comment]
Hm, but maybe it'd work, as it seems it was always the case that the default-directory when editing the COMMIT_MSG file would be the directory it's created in, which is inside the .git/ directory (c.f.: https://github.com/magit/magit/issues/5100#issuecomment-1967390767). I'll retry with 2.41.0, trying `magit-add-log` instead of just looking at the value of the `default-directory` variable.

**Comment by Apteryks** [comment]
Yes, it works with git 2.41.0 even when the `COMMIT_EDITMSG` and `magit-diff: .git` buffers' `default-directory` is the `.git/` project subdirectory.

**Comment by Apteryks** [comment]
It also works using git 2.45.2... and... in 2.46.0 !??.

I must be nuts.  I swear this was not working, even after restarting my emacs server.  I've since rebooted, though...  I'll close it for now, and will reopen if I manage to make sense of how to reproduce it.
