### ISSUE TITLE
Can't stage files when the filename is quoted by git

### ISSUE THREAD

**Issue by YoungFrog** [magit/magit#581]
Hi,

First of all, I don't want to waste your time with this part, but still : magit is just awesome, thanks to whoever made that ! Now to the issue :

I did the following :

```
~/tmp $ mkdir testmagit
~/tmp $ cd testmagit/
~/tmp/testmagit $ git init
Initialized empty Git repository in /home/youngfrog/tmp/testmagit/.git/
~/tmp/testmagit $ touch 'Say "hello".txt'
~/tmp/testmagit $ emacs -q -L /home/youngfrog/sources/magit/usr/local/share/emacs/site-lisp/ -l magit . -f magit-status
```

(where the above path is where I installed magit from commit 7a507b9e376e82bb9aa967a13ab9257afffd260a)

Now positionning my cursor on the untracked file and hitting 's' gives :
    magit-run_: Git failed ... [Hit $ or see buffer *magit-process_ for details]

hitting $ now show the buffer _magit-process_ which contains :

```
$ git --no-pager add "Say \"hello\".txt"
fatal: pathspec '"Say \"hello\".txt"' did not match any files
```

The same problem happens when I have files which contain accented letters.

I tried looking at the code with the hope to fix it myself, but my elisp skills are very limited, my CL skills are inexistant, and it seems that edebug isn't of much help to me here. IOW, I'm stuck.

**Comment by philsf** [comment]
FYI, I'm seeing this issue when trying to stage files with accented characters. I'm using `magit 20160907.945`, from MELPA.

**Comment by tarsius** [comment]
This was supposed to be fixed  a long time ago. I just tried again and was able to stage `ä`.

Please provide steps that allow us to reproduce this issue. Install Magit as described [here](https://magit.vc/manual/magit/Installing-from-the-Git-repository.html) and then run `make emacs-Q`. Also read [Reproduce bugs in emacs -Q](https://magit.vc/manual/magit/Installing-from-the-Git-repository.html) to learn why you have to do this.

**Comment by philsf** [comment]
I'm sorry, I'm unable to clone from github right now (possibly because of some obscure corporate network rules). Maybe the output in a test case gives enough information?

I wonder if my issue is related to character encoding? I can stage/unstage in the command line, but even using git itself, `git status` returns a strange encoding for the accented filename.

```
$ mkdir ~/magit-test
$ cd ~/magit-test/
$ git init
Initialized empty Git repository in <snip>/magit-test/.git/
$ touch á.txt
$ git status
On branch master
Initial commit
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        "\303\241.txt"
nothing added to commit but untracked files present (use "git add" to track)
```

If I try to stage this file in magit, I get the following in the `magit-process` buffer:

```
128 C:/Program Files/Git/mingw64/libexec/git-core/git … add -- á.txt
fatal: pathspec 'Ã¡.txt' did not match any files
```
Does this look like **this** issue, or something else?

**Comment by npostavs** [comment]
I can reproduce on Windows. It's probably Windows specific, and not the same as this issue; rather more like #2738, I expect.
