### ISSUE TITLE
add after commit hook to magit

### ISSUE THREAD

**Issue by steckerhalter** [magit/magit#603]
I'm using diff-hl https://github.com/dgutov/diff-hl  and was looking for a way to update all the buffers when I had commited something, I wrote some function and an advice:

``` lisp
(defun diff-hl-update-each-buffer ()
  (interactive)
  (mapc (lambda (buffer)
          (condition-case nil
              (with-current-buffer buffer
                (diff-hl-update))
            (buffer-read-only nil)))
        (buffer-list)))
(defadvice magit-update-vc-modeline (after my-magit-update-vc-modeline activate)
  (progn (diff-hl-update-each-buffer)))
```

to avoid that it would be nice to have hook, maybe even some way to run a command on every magit buffer after a commit has been made? (comparable to magit-vc-update-vc-modeline)

**Comment by lionel-** [comment]
Just FYI, I found out that adding `diff-hl-magit-post-refresh` to `magit-post-refresh-hook` slows down staging and unstaging noticeably. A commit hook, or some way to determine the cause of the refresh from the refresh hook, would be helpful for performance.
