### ISSUE TITLE
magit-log-long shows raw color escape sequences

### ISSUE THREAD

**Issue by nyuichi** [magit/magit#733]
Magit does not recognize ANSI color sequences in `*magit-log*` buffer. I tried hitting `ansi-color-for-comint-mode-on` in the buffer but nothing happened.

![untitled](https://f.cloud.github.com/assets/540144/866193/8be58d32-f65d-11e2-9c95-65b9d1e8f874.png)

```
$ git config -l | grep color
color.ui = auto
```

**Comment by mekeor** [comment]
Shouldn't `--no-color` be an element of `magit-git-standard-options` by default?

**Comment by tarsius** [comment]
Note that is a very old issue, so not everything said above still applies.

Why should it be? Do you have some issue that you think would be fixed by doing that? In any case, the answer is: no it should not.

**Comment by mekeor** [comment]
I had configured Git's `color.ui` option to `always` and magit didn't work with this configuration but maybe it should still work?

**Comment by tarsius** [comment]
There exists a FAQ entry about this: https://magit.vc/manual/magit/Diffs-contain-control-sequences.html.

**Comment by tarsius** [comment]
(It also seems you should update Magit, `magit-git-standard-options` was renamed a long time ago.)

**Comment by mekeor** [comment]
Thank you. (`magit-git-standard-options` still exists on recent magit releases but it's indeed obsolete.)
