### ISSUE TITLE
Please add -G option to magit log

### ISSUE THREAD

**Issue by vspinu** [magit/magit#739]
Hi, 

Currently there is a way to specify -S and --grep options in log buffers, but in
my experience those are pretty useless if you want to inspect a very specific
change. -S (pickaxe) counts the number of occurrences and thus doesn't detect
the changes related to a looked-up string. --grep searches only the log message.

 A much more powerful alternative is -G. It looks for a regexp in each diff.

 Thanks.

**Comment by AtomicNess123** [comment]
search option in MAGIT (l l -G) to search changes, the result is a list of commits that contain such expression. Is there a way to show the expression in context, as if it was a grep search?
