### ISSUE TITLE
How do you pronounce 'magit'?

### ISSUE THREAD

**Issue by daemianmack** [magit/magit#742]
I've been a devout magit adherent for years, but I've never been sure how to say its name. Here are some of the prevailing theories at my place of work, where there are roughly as many pronunciations as magit users...

"MA-jit" (like 'magic' with a 't' at the end)
"MAH-git" ('maggot')  # Please be this one.
"muh-JIT"
"muh-GIT"

Can you lay this weighty matter to rest? Thanks!

**Comment by djhaskin987** [comment]
OOOOOOOOOOOOOO is THAT how you pronounce it. I feel better.
